### ISSUE TITLE
Default hyperparameters create confusion in "Getting Started with Balance Ball"

### ISSUE THREAD

**Issue by ashwal** [Unity-Technologies/ml-agents#1]
When following the ["Getting Started with Balance Ball"](https://github.com/Unity-Technologies/ml-agents/wiki/Getting-Started-with-Balance-Ball) tutorial the hyperparameters `max_steps`  and `summary_freq` in [PPO.ipynb](https://github.com/Unity-Technologies/ml-agents/blob/master/python/PPO.ipynb) are equal. This leads to tensorboard showing only a single point. Which may have confused, uhh, some of us, that something was broken :)

**Comment by awjuliani** [comment]
Thanks for pointing this out @ashwal! I actually think a better solution is to set the network to train for longer than 10,000 timesteps, since that will be required anyway for all but the most trivial environments.
