### ISSUE TITLE
Small correction in "Getting Started with Balance Ball" wiki page

### ISSUE THREAD

**Issue by malvakian** [Unity-Technologies/ml-agents#10]
The second point of section **Embedding the trained model itself** must show this destination directory
`unity-environment/ML-Agents/Assets/Resources/TensorflowModels/` intead of 
`unity-environment/ML-Agents/Resources/TensorflowModels/`.

Regards

**Comment by awjuliani** [comment]
Hi @malvakian,

Thanks for pointing this out! We've just updated the wiki page to link to the correct location.
