### ISSUE TITLE
Matrix size-incompatible

### ISSUE THREAD

**Issue by mplantady** [Unity-Technologies/ml-agents#100]
I get this error :
UnityAgentsException: Matrix size-incompatible: In[0]: [8,32], In[1]: [12,64]
	 [[Node: dense/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_state_0_0, dense/kernel/read)]]

When I try to load a trained model with :
-32 states continuous
-8 actions discrete

Any idea ?

Thanks!

**Comment by awjuliani** [comment]
Hi @mplantady,

Did you happen to change the hidden state size from 64 to 32?

**Comment by mplantady** [comment]
I've restarted the process and it worked, not sure what went wrong! Thanks!
