### ISSUE TITLE
Strange training behavior

### ISSUE THREAD

**Issue by dracolytch** [Unity-Technologies/ml-agents#101]
Hey folks,

I'm using the standard PPO for training my examples. The bot starts off doing well, gets to super-human ability, and then skill drops. A lot. Any idea what might be causing this?

Thanks!

Mean Reward: 2.3333333333333335
Mean Reward: 4.128571428571429
Mean Reward: 5.371428571428571
Mean Reward: 6.475
Mean Reward: 8.014285714285714

.
. Time passes
.

Mean Reward: 69.94166666666666
Mean Reward: 69.85714285714286
Mean Reward: 70.27857142857142
Mean Reward: 70.71666666666667
Mean Reward: 69.35714285714286

.
. Time passes
.

Mean Reward: 56.66428571428571
Mean Reward: 52.91428571428571
Mean Reward: 53.65
Mean Reward: 48.16428571428571
Mean Reward: 41.714285714285715

.
. Time passes
.

Mean Reward: 8.728571428571428
Mean Reward: 7.508333333333334
Mean Reward: 7.921428571428572
Mean Reward: 7.428571428571429
Mean Reward: 6.725

.
. Time passes
.

Mean Reward: 0.17857142857142858
Mean Reward: 0.175
Mean Reward: 0.37142857142857144
Mean Reward: 0.2

**Comment by mplantady** [comment]
I think your system converged to results that were wrong, and with the continuous decrease of the entropy gets stuck in a dead-end.
Maybe you should work with a more deterministic environment or rewards that your agent cannot obtain with pure randomness.

Good luck!

**Comment by pengee** [comment]
Have you checked the [PPO docs](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/best-practices-ppo.md)? I was having the same problem but adjusting some of the Hyperparameters changed this pattern.

**Comment by dracolytch** [comment]
That doc is only 5 days old. No wonder I hadn't seen it before (whew). Glad to see more documentation in the project. Very helpful, thank you.

**Comment by mplantady** [comment]
Effectively seeing your video, it seems to work well!
The lack of physic stability is from my understanding related to the entropy of your agent.
If you continue to train it further, this entropy will decrease and maybe the agent will then fail to achieve its goal.

Tweaking Hyperparameters should help. And maybe adding a very small penalty for any unnecessary movement could help to stabilize it earlier.

Keep us updated ! :)
