### ISSUE TITLE
 Getting Error log : " d3d11: failed to create 2D texture shader" when training the agent

### ISSUE THREAD

**Issue by shrirammoni** [Unity-Technologies/ml-agents#1010]
Hi,
I am trying to replicate similar scenario like Visual Pyramids using **visual observation**, and I am getting this "**d3d11: failed to create 2D texture shader** resource view id=229182 [D3D error was 80070057]" error log and the player crashes during the training. Any help would be really appreciated.

Thanks,
Shri

**Comment by mmattar** [comment]
@shrirammoni - can you share specifics on your Unity and ML-Agents versions? Also, is this error appearing during training or inference?

**Comment by shrirammoni** [comment]
@mmattar  - I am using unity version - 2017.2.0f3 and ML-Agents version - 0.4.0. The error is appearing during the training.

**Comment by mmattar** [comment]
Thanks for the info @shrirammoni. No one has run into this issue before, so I'd like to ask a few more follow-ups:
- What platform did you build on?
- What platform are you running on?
- Are you training the VisualPyramids scene or your own?
- If your own scene, what is the resolution of your visual observation?
- If your own scene, have you been able to get training for VisualPyramids working?

Also, not that I think it would solve your problem, but we've fixed a few issues with ML-Agents, so upgrading to the latest version is recommended.

**Comment by shrirammoni** [comment]
What platform did you build on? - **Windows**
What platform are you running on? - **Windows**
Are you training the VisualPyramids scene or your own? - **Our Own**
If your own scene, what is the resolution of your visual observation? **84x84**
If your own scene, have you been able to get training for VisualPyramids working? - **Yes, but it will pause for sometime and memory is at its peak and then resume once memory is freed**

**Comment by mmattar** [comment]
Hi @shrirammoni - thanks for pointing this out. I suspect that this is a Unity scene issue as opposed to an ML-Agents issue. I encourage you to submit a question to the Unity forums or maybe respond to the one that you linked.

**Comment by shrirammoni** [comment]
@mmattar  yeah I will do that. 

Thanks.
