### ISSUE TITLE
NullExeption AgentMakeRequest

### ISSUE THREAD

**Issue by Superotter2** [Unity-Technologies/ml-agents#1011]
Hi 
After setting up my own Agents at Runtime the Agent Script throws the following NullException and I dont know how to handle it.:

NullReferenceException: Object reference not set to an instance of an object
Agent.MakeRequests (System.Int32 academyStepCounter) (at Assets/ML-Agents/Scripts/Agent.cs:877)
Agent.SetStatus (System.Boolean academyMaxStep, System.Boolean academyDone, System.Int32 academyStepCounter) (at Assets/ML-Agents/Scripts/Agent.cs:773)
Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:467)
Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:508)

Is there someone who could help me out? 
Thanks in advance.

**Comment by vincentpierre** [comment]
Hi, What version of ML-Agents are you on? Does this happen on the example environments? What is line 877 of your Agent Script? Is the error arising because the agentParameters are null? I cannot reproduce this error, in what context does it happen ?

**Comment by Superotter2** [comment]
sorry for bothering. I was able to fix it myself. The Acadamy and the Agents didnt exist at the right time.
