### ISSUE TITLE
The parameters of tennis

### ISSUE THREAD

**Issue by xiaozhuzhuzhu** [Unity-Technologies/ml-agents#1014]
How can I set the parameters of tennis to get the correct curve?

**Comment by vincentpierre** [comment]
All the trainer configurations are [here](https://github.com/Unity-Technologies/ml-agents/blob/master/python/trainer_config.yaml) The tennis brain uses the default values for training, you can modify them under the `TennisBrain` line 134 in v0.4

**Comment by xiaozhuzhuzhu** [comment]
@vincentpierre 
Thank you!
But I  use the  default values of tennis brain,but the curves are not all correct.

**Comment by xiaozhuzhuzhu** [comment]
![image](https://user-images.githubusercontent.com/23623240/43364454-20bd474c-934d-11e8-97b1-3b22c3294bf3.png)
![image](https://user-images.githubusercontent.com/23623240/43364462-319781a4-934d-11e8-870b-4367847126d0.png)
The curves of cumulative_reward and entropy are not correct.
How do I modify the parameters?

**Comment by xiaozhuzhuzhu** [comment]
I am sorry. I use version of v03. When I use v04,the images is shown as follows.
![image](https://user-images.githubusercontent.com/23623240/43365376-a00f2216-935e-11e8-8af3-636d7e1c49b5.png)
![image](https://user-images.githubusercontent.com/23623240/43365381-b21ec15a-935e-11e8-86cc-4e1e890814c1.png)
Thank you very much!
