### ISSUE TITLE
Less strict requirements.txt

### ISSUE THREAD

**Issue by christopherhesse** [Unity-Technologies/ml-agents#1016]
Hi!  Would it be possible to have less strict requirements in https://github.com/Unity-Technologies/ml-agents/blob/master/python/requirements.txt?

It might be that ml-agents actually does only work with tensorflow==1.7.1, but if it was tensorflow>=1.7.1, it wouldn't uninstall my custom built tensorflow each time.  I think a similar argument could be made for protobuf and grpcio, but tensorflow is the only one that affects me.

**Comment by vincentpierre** [comment]
Hi, You could be using a virtual environment to train your environments. We do not want to set `tensorflow>=1.7.1` because the TensorFlowSharp plugin does not work for latter versions of TensorFlow.

**Comment by christopherhesse** [comment]
Okay, thanks for the response!
