### ISSUE TITLE
negative entropy?

### ISSUE THREAD

**Issue by Ihsees** [Unity-Technologies/ml-agents#1019]
First of all, thank you for making and improving ml-agents! I've been following this project for a while and use this algorithm for hobby purposes to dip my toe into machine learning.

I read about the tensorflow metrics, and the trend that they should follow for a succesful training. But I just can't make sense of entropy. As far as I can tell, entropy is a measure for how random the actions were since the last summary. 
Once it reaches zero, the actions are deterministic, and there isn't any randomness to the actions for given observations (and no learning). 

But what does negative entropy mean then? 

![grafik](https://user-images.githubusercontent.com/17814024/43273358-88a6c246-90fc-11e8-8824-30e3978c1938.png)

**Comment by vincentpierre** [comment]
Hi, It is possible for the Entropy to be negative in the case of Continuous Control. [See article.](https://en.wikipedia.org/wiki/Differential_entropy) That is because of the way it is defined. In the case of Discrete Control, the Entropy is always positive.
