### ISSUE TITLE
UnityEnvironmentException: The Unity environment took too long to respond. Make sure test does not need user interaction to launch and that the Academy and the external Brain(s) are attached to objects in the Scene.

### ISSUE THREAD

**Issue by inoue0426** [Unity-Technologies/ml-agents#102]
I got an error.

# Enviroment
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
Python 3.6.2 :: Anaconda custom (x86_64)
unity version 2017.1.1f1 Personal

# 

# Error Message
---------------------------------------------------------------------
timeout                             Traceback (most recent call last)
~/ml-agents/python/unityagents/environment.py in __init__(self, file_name, worker_id, base_port)
     84                 self._socket.listen(1)
---> 85                 self._conn, _ = self._socket.accept()
     86                 self._conn.setblocking(1)

~/anaconda/lib/python3.6/socket.py in accept(self)
    204         """
--> 205         fd, addr = self._accept()
    206         # If our type has the SOCK_NONBLOCK flag, we shouldn't pass it onto the

timeout: timed out

During handling of the above exception, another exception occurred:

UnityEnvironmentException           Traceback (most recent call last)
<ipython-input-3-5c6a85258571> in <module>()
----> 1 env = UnityEnvironment(file_name=env_name)
      2 print(str(env))
      3 brain_name = env.brain_names[0]

~/ml-agents/python/unityagents/environment.py in __init__(self, file_name, worker_id, base_port)
     91                 "The Unity environment took too long to respond. Make sure {} does not need user interaction to launch "
     92                 "and that the Academy and the external Brain(s) are attached to objects in the Scene.".format(
---> 93                     str(file_name)))
     94         except UnityEnvironmentException:
     95             proc1.kill()

UnityEnvironmentException: The Unity environment took too long to respond. Make sure test does not need user interaction to launch and that the Academy and the external Brain(s) are attached to objects in the Scene.

---------------------------------------------------------------------

Please teach me.

**Comment by gerardsimons** [comment]
You need to put the Brain on External

**Comment by inoue0426** [comment]
I got it!
Thanx 👍
