### ISSUE TITLE
More FixedUpdate calls during training in python

### ISSUE THREAD

**Issue by matsui-k20xx** [Unity-Technologies/ml-agents#103]
Hi

My game calls FixedUpdate from 9 to 20 times per Update during training in python. I found this by counting them between AgentStep() calls. In Unity Editor, it is from 0 to 2 per Update. 

My Academy params are following,
Max Steps 0
Frame To Skip 9
Wait Time 0
Training:
Time Scale 1
Target Frame rate 60
Inference:
TimeScale 1
Target Frame Rate 60

Someone knows why this happens?

**Comment by matsui-k20xx** [comment]
and Im confused with a following strange behavior of env_info. 

In this code, update_count gets around 45. Frame To Skip is 0. So this update_count is fine. env_info.states[0][0] has the number of Update calls during steps.

update_count = 0
for _ in range(100):
    env_info = env.step([0])[default_brain]
    update_count += env_info.states[0][0]

But here I added time.sleep(0.1) in the for loop, update_count gets around 6. 

update_count = 0
for _ in range(100):
    env_info = env.step([0])[default_brain]
    update_count += env_info.states[0][0]
    time.sleep(0.1)

The same kind of the decrease of update_count happens when I execute env.step in jupyter notebook cells manually.

**Comment by vincentpierre** [comment]
There is no guaranty that the number of updates will be proportional to the number of fixed updates.  Update is once per screen frame and fixed update corresponds to physics updates which happen multiple times per screen frame. We suggest you put all the logic of your game into fixedUpdates or else, you will have different behaviors depending on how good high your screen frame rate is (which depends on many elements such as TimeScale, TargetFrameRate, etc...).

**Comment by matsui-k20xx** [comment]
Thank you for the advice!
Now I have realized that the problem is separating my game logic into FixedUpdate and Update. 

I didn't assume that the difference can be huge from python, although I  know that "There is no guaranty that the number of updates will be proportional to the number of fixed updates." .
