### ISSUE TITLE
Unity Download Assistant incompatible with OS X 10.10

### ISSUE THREAD

**Issue by cjm715** [Unity-Technologies/ml-agents#1038]
I tried installing unity on OSX 10.10. Although my system matches the requirements (OS X 10.9+), I still got the error message shown in the attached screenshot.
<img width="1280" alt="screenshot 2018-07-30 21 50 03" src="https://user-images.githubusercontent.com/14244727/43432864-e911b228-9442-11e8-8f8f-9bcad4378e7b.png">

**Comment by vincentpierre** [comment]
Hmm, this looks like a Unity specific error. Have you tried asking on the Unity forums? Maybe you will be able to download an older version of Unity?

**Comment by cjm715** [comment]
I ended up just updating OSX. I will close since you are right that this is a Unity specific error.
