### ISSUE TITLE
Help on Training Team Behaviour

### ISSUE THREAD

**Issue by m-kul** [Unity-Technologies/ml-agents#1039]
Hello!

I am trying to teach team behaviour on a 2D basketball game. I can successfully train 1 attacker on 1 defense using curiosity, but I cannot get them play as a team. I would like agents to pass each other when they need to. Which approach would be best? I am forcing agents to pass between players randomly, so that they have to adopt this during training, up to now this didn't help much though.

**Comment by vincentpierre** [comment]
This is a very interesting problem. If you want your agents to cooperate, you will need to define your reward function accordingly and give them all the observations that are needed. Maybe reward your agents when they do an appropriate pass. Reward all agents when any agent scores. Penalize them for losing the ball when they could have passed. 
Make sure the agents know the position of the other agents so they can place themselves relative to the rest of the team. These are just suggestions, but if your agents can earn as much rewards without playing as a team, then they will do so.
I hope this helps.

**Comment by m-kul** [comment]
@vincentpierre Thanks a lot, I will try and let you know. Do you think curiosity=true the way to go or I should go with simple PPO?

**Comment by vincentpierre** [comment]
If you are making the reward super dense, then I do not think curiosity will help that much. You can try it still. You can give a bonus reward at each score depending on the number of players that touched the ball. It all depends on what you want your agents to do. You can penalize agents for walking too far with the ball, forcing them to pass it without encouraging them to constantly pass it.

**Comment by m-kul** [comment]
@vincentpierre that makes perfect sense. Thanks.

**Comment by m-kul** [comment]
@vincentpierre sorry to open again. let’s say I use 3 agents in each team. Should I assign the same brain for 3 of them or should I have 3 different brains for them?

**Comment by vincentpierre** [comment]
Not sure. Are all your agents the same of do they have specific roles. I would first experiment with one brain if they are all identical.
