### ISSUE TITLE
Getting IndexError: index 8 is out of bounds for axis 0 with size 8

### ISSUE THREAD

**Issue by shrirammoni** [Unity-Technologies/ml-agents#1040]
I am getting this error "**IndexError: index 8 is out of bounds for axis 0 with size 8**" when training with **visual observation**. Any help ?

**Comment by vincentpierre** [comment]
Hi, 
What line are you getting this error ? It seems you are trying to access index 8 of an array of size 8 (I suppose the `vectorActions` array. You cannot do this as an array of size 0 has indices between 0 and 7.
I hope this helps.

**Comment by shrirammoni** [comment]
Traceback (most recent call last):
  File "learn.py", line 84, in <module>
    tc.start_learning()
  File "\ml-agents-master\python\unitytrainers\trainer_controller.py", line 260, in start_learning
    trainer.add_experiences(curr_info, new_info, take_action_outputs[brain_name])
  File "\ml-agents-master\python\unitytrainers\ppo\trainer.py", line 283, in add_experiences
    next_info.visual_observations[i][idx])
IndexError: index 8 is out of bounds for axis 0 with size 8

This is the  error i got when i try to train 4 environments in same scene.

Every Environment has three different agents and two camera attached to them for visual observation.

References:
Below is the Brain Script and its Parameter
![brain script](https://user-images.githubusercontent.com/28861120/43501588-d8dc9d6e-9573-11e8-90ef-6631e98a0582.JPG)

Hope this helps!

**Comment by vincentpierre** [comment]
I think you found a bug. Can you try to replace line 283 of `ml-agents-master\python\unitytrainers\ppo\trainer.py`: replace `next_info.visual_observations[i][idx]` with `next_info.visual_observations[i][next_idx]` and see if it helps.
I will investigate more. Thank you.

**Comment by vincentpierre** [comment]
Fix pushed to develop in this [commit](https://github.com/Unity-Technologies/ml-agents/commit/40365ded71c5bf94c79c7b94e75fe52623935261)

**Comment by Waengna** [comment]
#  Tensorflow DeepLab 实现的可视化
import matplotlib.pyplot as plt
from matplotlib import gridspec
import numpy as np
import cv2


def create_pascal_label_colormap():
    """
    PASCAL VOC 分割数据集的类别标签颜色映射label colormap

    返回:
        可视化分割结果的颜色映射Colormap
    """
    colormap = np.zeros((256, 3), dtype=int)
    ind = np.arange(256, dtype=int)

    for shift in reversed(range(8)):
        for channel in range(3):
            colormap[:, channel] |= ((ind >> channel) & 1) << shift
        ind >>= 3

    return colormap

#label = np.asarray(['background', 'person'])
def label_to_color_image(label):
    """
    添加颜色到图片，根据数据集标签的颜色映射 label colormap

    参数:
        label: 整数类型的 2D 数组array, 保存了分割的类别标签 label

    返回:
        result: A 2D array with floating type. The element of the array
        is the color indexed by the corresponding element in the input label
        to the PASCAL color map.

    Raises:
        ValueError: If label is not of rank 2 or its value is larger than color
        map maximum entry.
    """

    if label.ndim != 2:       # 原label.ndim != 2:
        raise ValueError('Expect 2-D input label')

    colormap = create_pascal_label_colormap()

    if np.max(label) >= len(colormap):
        raise ValueError('label value too large.')

    return colormap[label]


def vis_segmentation(image, seg_map):
    """
    输入图片和分割 mask 的可视化.
    """
    plt.figure(figsize=(10, 6.67))
    grid_spec = gridspec.GridSpec(1, 4, width_ratios=[6, 6, 6, 1], height_ratios=[0.1])  # 网格规格,即此处只是设置尺寸！！ ,原语句为： grid_spec = gridspec.GridSpec(1, 4, width_ratios=[6, 6, 6,1])

    plt.subplot(grid_spec[0])
    plt.imshow(image)
    plt.axis('off')
    plt.title('input image')

    plt.subplot(grid_spec[1])
    seg_image = label_to_color_image(seg_map).astype(np.uint8)
    plt.imshow(seg_image)
    plt.axis('off')
    plt.title('segmentation map')

    plt.subplot(grid_spec[2])
    plt.imshow(image)
    plt.imshow(seg_image, alpha=0.7)
    plt.axis('off')
    plt.title('segmentation overlay')

    unique_labels = np.unique(seg_map)  # 原句为：unique_labels = np.unique(seg_map)
    ax = plt.subplot(grid_spec[3])

    # 原句为：plt.imshow(FULL_COLOR_MAP[unique_labels].astype(np.uint8), interpolation='nearest')

    plt.imshow(FULL_COLOR_MAP[unique_labels].astype(np.uint8), interpolation='nearest')

    ax.yaxis.tick_right()
    plt.yticks(range(len(unique_labels)), LABEL_NAMES[unique_labels])
    plt.xticks([], [])
    ax.tick_params(width=0.0)
    plt.grid('off')
    plt.show()

def vis_segmentation2(image, seg_map):
    """
    输入图片和分割 mask 的统一可视化.
    """
    seg_image = label_to_color_image(seg_map).astype(np.uint8)
    plt.figure()
    plt.imshow(image)
    plt.imshow(seg_image, alpha=0.7)
    plt.axis('off')
    plt.show()

LABEL_NAMES = np.asarray(['background', 'person']) # 假设只有两类
FULL_LABEL_MAP = np.arange(len(LABEL_NAMES)).reshape(len(LABEL_NAMES), 1)
FULL_COLOR_MAP = label_to_color_image(FULL_LABEL_MAP)

imgfile = 'image.jpg'
pngfile = 'mask.jpg'
image = cv2.imread(imgfile, 1)
image = image[:, :, ::-1]
seg_map = cv2.imread(pngfile, 0)
vis_segmentation(image, seg_map)

print('Done.')

Traceback (most recent call last):
  File "F:/Users/nana/PycharmProjects/yuyitry/yuyitrying.py", line 112, in <module>
    vis_segmentation(image, seg_map)
  File "F:/Users/nana/PycharmProjects/yuyitry/yuyitrying.py", line 83, in vis_segmentation
    plt.imshow(FULL_COLOR_MAP[unique_labels].astype(np.uint8), interpolation='nearest')
IndexError: index 37 is out of bounds for axis 0 with size 2
Why?Can you help me?
