### ISSUE TITLE
Tried to upgrade from version  v 0.3 to  v 0.4 but this error pops up

### ISSUE THREAD

**Issue by jpax1996** [Unity-Technologies/ml-agents#1046]
Hello,
I had built an environment in the  v 0.3 and it was working fine, but i decided to upgrade to  v 0.4 in order to use the curiosity feature, but this error appeared after i run the training
![image](https://user-images.githubusercontent.com/26434446/43516901-d571ffd8-957e-11e8-919e-791a91a58f18.png)

The game launches but the training doesn't start, did i forget to do something?

**Comment by vincentpierre** [comment]
Did you update the version of the Unity side of ML-Agents as well ? This error usually arrises when the Python and Unity version of ML-Agents are not compatible.
I hope this helps and please let us know.

**Comment by jpax1996** [comment]
Yes i forgot about that, imported the floder unity-environment/Assets, but i get the error : 
Assets/ML-Agents/Assets 1/ML-Agents/Scripts/RpcCommunicator.cs(138,46): error CS0246: The type or namespace name `PlayModeStateChange' could not be found. Are you missing an assembly reference?

Do i need to do something else?

**Comment by vincentpierre** [comment]
You need to have Unity version 2017.3 or above for version 0.4 to work. There is a fix for that on the `develop` branch.

**Comment by jpax1996** [comment]
Thank you for the help, i downloaded the latest version of Unity and downloaded TFSharpPlugin and now evereything seems to work fine.
