### ISSUE TITLE
VisualPushBlock Where is the trained brain?

### ISSUE THREAD

**Issue by superjayman** [Unity-Technologies/ml-agents#1051]
When I change the brain to Internal, no trained brain is Available for the examples? To train the Visual examples brain do I need to setup new parameters in trainer_config.yaml file.

**Comment by unityjeffrey** [comment]
hi @superjayman thank you for reaching out.  unfortunately we do not include trained models with the visual observation based enviornments.  however, the parameters work okay from the yaml file.  we are hoping to add the trained model in future releases.

**Comment by unityjeffrey** [comment]
this will be available in the next release.  closing now but please feel free to reopen later if needed.
