### ISSUE TITLE
Exported frozen Model not working

### ISSUE THREAD

**Issue by aliBUT** [Unity-Technologies/ml-agents#1053]
I trained a model for image classification using tensorflow 1.71  and I exported is using code from google's object_detection sample script export_inference_graph.py. i also converted its extension to bytes and updated label maps accordingly. For some reason, it is not working. but if I use default models available on the internet they work perfectly fine 

`https://github.com/MatthewHallberg/TensorFlowUnity-ImageClassification/blob/master/Assets/Scripts/Classification.cs`

and it crashes at line 

`runner.AddInput (graph [INPUT_TENSOR] [0], tensor).Fetch (graph [OUTPUT_TENSOR] [0]);
var output = runner.Run();`

is it because i am exporting it in wrong way?

**Comment by unityjeffrey** [comment]
hi @aliBUT - just wanted to confirm this was an issue for the ml-agents project.  can you provide some more detail?

**Comment by aliBUT** [comment]
Hi @unityjeffrey , sorry for the confusion and I found out that tfcsharp is completely separate project and ml agents are separate. the issue I am facing is I trained a model to recognize some images in python and I exported that model from python. when i tried to run it in tfcsharp it just gives me null exception . but the model which was provided with tfcsharp works perfectly. I am aware that this is not ml agent project issue but some advice will be very helpful for me

thanks

**Comment by aliBUT** [comment]
Actually, I downloaded tensorflow plugin from here 

https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-TensorFlow-Sharp-in-Unity.md

Not sure if that helps

thanks

**Comment by aliBUT** [comment]
@unityjeffrey  any idea what could be the problem?

**Comment by unityjeffrey** [comment]
hi @aliBUT - unfortunately, I would not be able to really debug this issue on the TFCsharp side.  I might suggest to post your questions on the main TFCsharp github page - https://github.com/migueldeicaza/TensorFlowSharp.

**Comment by aliBUT** [comment]
ok, i will jump over there . thanks @unityjeffrey
