### ISSUE TITLE
Observation function doesn't work

### ISSUE THREAD

**Issue by ChrisBearX** [Unity-Technologies/ml-agents#1054]
Hi everyone, I'm working on develop a obstacle avoiding AI. 
I use the ray perception script and it looks like it does not work at all. I use the code in default pyramids example, and the brain do received several observation data. But the outcome of the training are always terrible. It looks like agent cannot 'SEE' anything in front of it, neither walls or goal. I use both reinforcement learning and imitation learning, the result always been the same. My agent keep crash in the wall or stuck in a corner, and when it pass by the goal it just go away. I can see all the ray go through the goal or walls, it just didn't notice there were any thing in front of it.
And even when I train the default examples with default training parameters, they didn't work neither.
Here is the code I use to collect observations.

![code](https://user-images.githubusercontent.com/42033393/43581428-79339732-968b-11e8-8349-fec48de904ec.png)

**Comment by unityjeffrey** [comment]
hi @ChrisBearX thanks for reaching out.  to confirm, are you trying to train on the pyramid scene or a different scene?

**Comment by scotthovestadt** [comment]
I've done this collision avoidance / goal AI (although I modified the ray perception script):
https://www.youtube.com/watch?v=pLofPJNPFVw

You see the `detectableObjects` line? Those are tags you need to place on your object in Unity. Have you done this?

Additionally, are you sure those objects have colliders for the ray to hit?

Lastly, what are you doing if the agent does hit a wall? What is your overall reward structure? In the simplest possible case, you'll want at least a very small penalty for touching the wall each frame it collides.

**Comment by ChrisBearX** [comment]
Hi@unityjeffrey , I just trained the pyramid scene by unity editor, and it worked. But my scene still didn't;(

**Comment by ChrisBearX** [comment]
Hi @scotthovestadt , I have watch your video and it is awesome!
I add tags already and all walls and target have colliders on them. I've tried to give agent negative reward by hitting the wall or no reward, it doesn't work neither. I just create a scene just like the pyramid example, and let the target randomly born any where in the scene, the only thing agent should do is try to find the target and hit it. I tried to use unity editor to train it and it fail again...

**Comment by scotthovestadt** [comment]
I haven't tried to teach the Pyramid example but my understanding is that it requires curiosity be enabled. Have you done that for your brain?

**Comment by ChrisBearX** [comment]
@scotthovestadt Thank you for your help! I use the same training parameters as the example. And the latest thing I tried is change the original pyramid and make it totally same as my project, and when I train this, it worked. Totally don't know why...

**Comment by unityjeffrey** [comment]
hi - looks like this was resolved.  closing for now but feel free to reopen if needed.
