### ISSUE TITLE
Memory problem during training

### ISSUE THREAD

**Issue by alessiabertugli** [Unity-Technologies/ml-agents#1055]
Hey,
I'm trying to train my Unity project with ml-agents, using PPO. Training process seems to go well, but Unity process increases memory usage until saturation. It's strange because my computer has 32 G of RAM.

**Comment by unityjeffrey** [comment]
hi @alessiabertugli - hope you are doing well.  I am not aware of any existing issue on memory leaks.  Can you provide a few more details - 1) did you make any changes to python 2) which enviornments (or your own) 3) any logs or screenshots you can provide.  For now, I'll classify this as a bug until we can debug your issue.  Thanks.

**Comment by scotthovestadt** [comment]
I've seen memory issues when not using object pooling and generating a very high number of objects. In this case, my training process eventually crashed.

Adding an object pooling routine fixed it.

Unity 2018 r2

**Comment by unityjeffrey** [comment]
thanks @scotthovestadt.  @alessiabertugli based on scott's comments, let me know if this addresses some of your issue.

**Comment by alessiabertugli** [comment]
I didn't make any change to python code. It's unity build that give memory leak. I'm using my own environment, but I don't generate objects, I just change their transform position and rotation when they collide with another collider.

**Comment by unityjeffrey** [comment]
hi @alessiabertugli to confirm - if you try to do training in the editor, can you run the Unity profiler to see where the memory leak is happening?

**Comment by karta1297963** [comment]
@alessiabertugli  are you using visual observation?
I also have memory leak issue, but after upgrade to version 0.4b, the issue is solved.

**Comment by alessiabertugli** [comment]
@karta1297963 Solved. Thank you.

**Comment by unityjeffrey** [comment]
thanks @karta1297963 and @alessiabertugli
