### ISSUE TITLE
Does the trained brain still need the code?

### ISSUE THREAD

**Issue by m-kul** [Unity-Technologies/ml-agents#1056]
Let's say I trained an agent to chase a given GameObject (set in the inspector), and the agent has parameters like speed, stamina etc. also set in the inspector. Then after the training, I get the internal brain set with the model. If I change agent's parameters or the GameObject to chase, will the agent adopt to those changes? And do I need to keep the code the brain has trained with for it to use? Or the internal brain will embed these things inside itself? I am sorry, I am kinda confused.

**Comment by scotthovestadt** [comment]
You need the observations that were fed to the brain during training. It uses those to make decisions.

You do not need to continue feeding it rewards.

Changing parameters a brain learned on (such as speed and stamina) is possible, but you need to prepare it for these to be changed in advance. One way of doing that is to randomly set these values during training so it will learn to adapt. You will probably also want to feed it to the current speed/stamina values as observations.

**Comment by unityjeffrey** [comment]
thanks @scotthovestadt.  @m-kul let me know if this helps resolve your issue

**Comment by unityjeffrey** [comment]
hi all - closing this thread.  but feel free to reopen if needed.
