### ISSUE TITLE
Make agent backtrack using curiosity

### ISSUE THREAD

**Issue by jpax1996** [Unity-Technologies/ml-agents#1057]
Hello,
I've been trying to use the new curiosity feature to try and make my agent finish a level where he will have to move backwards at some point.
![image](https://user-images.githubusercontent.com/26434446/43601839-278fb852-9686-11e8-8379-1f78b5534fb1.png)
This is a picture of the current level. The agent will receive a reward of +1 once he reaches the checkpoints (red squares). If he falls on the spikes, the agent will reset but will not get a penalty (i'm not sure if i should give it a penalty).
The training is using curiosity to test out its usefulness, but i'm not sure what exactly is going wrong with the training.
https://drive.google.com/open?id=1-SaAU7sUWIrk5M9XgmpMisAJJFmLMiAp
I'm training with:
curiosity_strength: 0.01
curiosity_enc_size: 190

Any advice on how i could improve my training would be greatly appreciated.

**Comment by unityjeffrey** [comment]
hi @jpax1996 i believe you have a thread with @vincentpierre on this here - https://github.com/Unity-Technologies/ml-agents/issues/1042

Let me know if this is a duplicate and move the discussion to that issue.

**Comment by jpax1996** [comment]
yes it is, sorry about that

**Comment by unityjeffrey** [comment]
hi @jpax1996 no problems at all.  i'll go ahead and close this issue then.
