### ISSUE TITLE
Guide to add custom summary

### ISSUE THREAD

**Issue by dora-gt** [Unity-Technologies/ml-agents#106]
A document for adding custom summary for TensorBoard may help some people.

- How to send data from Unity to Python
- How to add the data to TF summary

If possible, I want to do this not modifying Python code, only modifying C# or Unity scene data.
In the future, please consider this function, though I'm trying to do this on my own now.

**Comment by unityjeffrey** [comment]
Thank you for your comments.  We’ve documented your feedback and will prioritize when appropriate.

**Comment by dora-gt** [comment]
Thank you for the consideration.

**Comment by CaptainPineapple** [comment]
Hello,

i'd like to add additional summary information like a successrate or a total success count but i cannot seem to find any information on how to do this. Was there any progress in this matter or did i miss some documentation?
Thank's in advance.
