### ISSUE TITLE
Frozen graph problem

### ISSUE THREAD

**Issue by Maleandr** [Unity-Technologies/ml-agents#1060]
Hi,

I have custom CNN model trained and exported in TF 1.7.1 (which should be currently supported version), but I got error message while loading graph: 

`{TensorFlow.TFException: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SA…}`

I found some advices about TF version, but TF 1.7.1 should be supported right? I'm little bit confused, because calling `TFCore.Version` gives me "1.1.0-rc2", which is 1 year old TF version.

**Comment by unityjeffrey** [comment]
hi @Maleandr thank you for your email.  this seems to be a bug with the TFS plugin.  let me do some looking around

**Comment by Maleandr** [comment]
Thank you for reply. Do you have any update please @unityjeffrey @xiaomaogy ?

**Comment by vincentpierre** [comment]
Hi @Maleandr Did you download the latest TF# plugin ? [Here](https://s3.amazonaws.com/unity-ml-agents/0.4/TFSharpPlugin.unitypackage)

**Comment by Maleandr** [comment]
@vincentpierre Yes I did. It works for you?

**Comment by Maleandr** [comment]
Hmm I have downloaded and imported it again and now it shows "1.7.0", but "1.7.1" should be supported right?

**Comment by vincentpierre** [comment]
This `NodeDef mentions attr 'dilations' not in Op<name=Conv2D` error is usually thrown when the TF version is off. If you are sure your model was trained with the same version as TF#, then it should work.  It could also be the case that you are using Con2D with a `dilation` argument that we do not use in our  InternalBrain. Please look at how we do convolutions in the PPO trainer and make sure you are using convolutions in the same way. If you want to be sure, you could train the GridWorld and try to use the trained model with the InternalBrain. If it does work, then this means there is an issue in the way you use convolutions in your model.

**Comment by Maleandr** [comment]
@vincentpierre My issue is not with 'dilations' - `TFCore.Version gives` me '1.7.0' now, but you mention in documentation '1.7.1' as supported version. I don't know what version of TF should be used then.

**Comment by vincentpierre** [comment]
Your issue states that `NodeDef mentions attr 'dilations' not in Op<name=Conv2D;` If the issue you are seeing is different, could you post it here ? The difference between 1.7.0 and 1.7.1 is [very small](https://github.com/tensorflow/tensorflow/compare/v1.7.1...r1.7) so I do not think you can have an issue due to incompatibility between those versions. It seems 1.7.1 works with the current TF# plugin.

**Comment by Maleandr** [comment]
Well I downloaded TF# plugin again and it worked, but I was confused because of difference between '1.7.0' in TF# plugin and '1.7.1' in documentation. I understand that diff between 1.7.0 and 1.7.1 is very small. Thank you for help.
