### ISSUE TITLE
ML-agent for my game?

### ISSUE THREAD

**Issue by edesdan** [Unity-Technologies/ml-agents#1061]
Hi,

I was planning to use ml-agent to implements an AI in my game project. The game is a local multiplayer where each player drives a boat and try to shoot the other in an arena environment. I'd like to add the feature for a human player to play against an CPU-agent. I guess that is achievable using an ml-agent but I don't know where to start. Can you give me any suggestions?  

What kind of learning should I go for? Imitation learning? How difficult would be implementing that?

Thank you, this project seems really really cool. 👍

**Comment by unityjeffrey** [comment]
Hi @edesdan thank you for reaching out.  you can definately achieve what you are doing using ml-agents.  I would first suggest our basic guide to understand how ml-agents works.  From there, it will describe how to train using our basic environment as well as embed the models back into the game.  https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Basic-Guide.md

Let me know if this is helpful

**Comment by edesdan** [comment]
@unityjeffrey Thanks for your reply, I'll have a look. I'm following the youtube tutorials now, let's see how it goes.. I'll let you know! :)

**Comment by unityjeffrey** [comment]
hi all - closing this thread.  but feel free to reopen if needed.
