### ISSUE TITLE
Imitation learning outside the editor? Imitation + curriculum learning?

### ISSUE THREAD

**Issue by BartMartner** [Unity-Technologies/ml-agents#1065]
So imitation learning seems really powerful! I'm trying to use it to train deathmatch bots in a 2d platformer and the results seems fairly promising. However, I don't know that I'll ever be able to teach them a general way to solve a wide variety of platforming problem by having it watch a single session of play in a single environment. I'm feeding the brain a representation of the tilemap, some raycast, and some info on the position and direction of goals as training data, but it seems to get stuck where it would need to make two jumps (to one platform then another) to reach said goals.

The way I understand imitation learning is that the teacher/player brain is recording input/output pairs and then those are being back propagated into the student brain. Is there currently any way to save those recordings from the player brain across multiple sessions and then back prop a whole bunch of them while the editor isn't running? I think it would be useful if I could record multiple play sessions in different environments, each focused on different simple tasks, then have a brain just repeatedly learn on that for a good long bit while I go watch TV and eat a sandwich.

Is this possible? How do?

**Comment by unityjeffrey** [comment]
hi @BartMartner thank you for your comment.  unfortunately, this isn't yet available today, but we are considering adding some functionality.  if you are also interested to help contribute to this type of feature, we would welcome that as well.

**Comment by BartMartner** [comment]
I've poked around trying to figure it out, but don't feel confident in my understanding of the existing code.

I assume that the AgentInfoProto that Batcher.cs is appending to the message it sends to Python (line 258 in Batcher.cs) is what would need to be serialized and saved to some file(s).  I think that maybe contains that input/output data?

I'm not sure what's involved in serializing a sealed partial class, and I know virtually nothing about Python. So even past that step I'm not certain how to pass the data in those saved files to learn.py (or whatever it's communicating to) and spit out bytes.

**Comment by unityjeffrey** [comment]
no worries @BartMartner - we'll add this issue as part of our exploration to enable scenarios for using imitation learning to learn from non-human players

**Comment by vqt123** [comment]
+1 for this!!

**Comment by unityjeffrey** [comment]
Hi all - closing this as we have shipped demonstration recorder in v0.6 https://blogs.unity3d.com/2018/12/17/ml-agents-toolkit-v0-6-improved-usability-of-brains-and-imitation-learning/?_ga=2.158778168.364000799.1554222568-145274537.1510700117
