### ISSUE TITLE
Proper bytes model is not being saved

### ISSUE THREAD

**Issue by Dongseon-SHIN** [Unity-Technologies/ml-agents#1068]
Hi guys.
After 3DBall learning, there is .bytes file in the models folder, but it's not learned model.

Is there anything I missing?
![s](https://user-images.githubusercontent.com/40270471/43714665-3e07d5bc-996d-11e8-96ca-39c8dcc1d7cb.PNG)

**Comment by unityjeffrey** [comment]
hi @Dongseon-SHIN - thank you for reaching out.  That should be the right model file.  Have you tried to load into the Unity scene using the TensforFlowSharp plugin?

**Comment by Dongseon-SHIN** [comment]
Thanks for comment. @unityjeffrey
Yes l used Tensorflowsharp. But I am begginer, so not sure about that I loaded it correctly.
Is this problem being occur when not using tensorflowsharp?
