### ISSUE TITLE
How to print detailed training information?

### ISSUE THREAD

**Issue by CicieChen** [Unity-Technologies/ml-agents#1069]
Hi all, May I ask how to print or save a file of every training step information. Like if I want to print "step#, step reward". Which documents should I modify?
Another question is how to print the teacher training information while I use imitation learning?
Thanks!

**Comment by unityjeffrey** [comment]
hi @CicieChen - when you run learn.py, the outputs of each step and cumulative reward should be displayed.  you can also modify the trainer_config.yaml file and modify the summary_freq variable to your needs.  The default is to output every 1000 steps.  

for your second question - can you elaborate what teacher training information you are looking to output?

**Comment by unityjeffrey** [comment]
hi all - closing this thread.  but feel free to reopen if needed.
