### ISSUE TITLE
Question:  Multi discrete has been pushed to the develop branch, will there be a new release soon?

### ISSUE THREAD

**Issue by EstonianGiant** [Unity-Technologies/ml-agents#1074]
Hi,

I have been waiting for this change (multi-discrete) to go live, so I'm happy that's it's now on the develop branch!  Will there be a new 'master' release soon?  If not, I guess I'll start toying with the develop branch!

Thanks

**Comment by unityjeffrey** [comment]
hi @EstonianGiant, we are glad you are happy to see this feature get developed.  We do plan to push this to Master in the near future.  We'll keep you posted when this will happen.  For now, using the develop branch would be best.

**Comment by EstonianGiant** [comment]
Great, thanks!
