### ISSUE TITLE
Develop branch - error message: No External Brains found in the Unity Environment

### ISSUE THREAD

**Issue by kg905812262** [Unity-Technologies/ml-agents#1075]
Hi everyone,
I want to use the multi-discrete feature in the _develop_ branch, but it gives me this error message upon executing the training command. Here's my steps:

1. Download the _develop_ branch from GitHub (so now I have _master_ and _develop_ simultaneously).
2. Copy the Assets folder from unity-environment (_develop_ ) to my Unity project.
3. Check .NET 4.x Equivalent and ENABLE_TENSORFLOW are set in the player settings.
4. Change Action Space Type to Discrete, set Branches Size and each Branch (3 and 7, 7, 4 in my case).
5. Reimplement my AgentAction, make sure Brain gameObject assigned to my Agent is child of Academy gameObject, and its Brain Type is set to External.
6. Invoke the training command from the directory of python folder in _master_.
7. Error message: "No External Brains found in the Unity Environment" occurs.

EDIT:
If I invoke the training command from _develop_, the following error occurs:

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "...\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 106, in spawn_main
>     exitcode = _main(fd)
>   File "...\AppData\Local\Programs\Python\Python35\lib\multiprocessing\spawn.py", line 116, in _main
>     self = pickle.load(from_parent)
> AttributeError: Can't get attribute 'run_training' on <module '__mp_main__' from '...\\ml-agents\\python\\learn.py'>

I don't know which step went wrong.
Any help is appreciate.

**Comment by awjuliani** [comment]
Hi @kg905812262,

Can you please share some details about your operating system? We now use python multi-processing  in order to allow for running more than one training session simultaneously, and this error seems to be related to that.

**Comment by kg905812262** [comment]
Hi @awjuliani ,

I'm running on Windows 10 Pro x64, version 1803 and OS build 17134.165.
Thanks for your reply.

**Comment by EstonianGiant** [comment]
This same issue is also being discussed in: #1041

**Comment by kg905812262** [comment]
Thanks to @EstonianGiant ,
After learn.py been modified, the error related to multi-processing has gone, but the error message: No External Brains found in the Unity Environment occurs. I've checked that academy (script) has added the brain to its parameters correctly and brain type set to external. Don't know why is this happening. Any ideas?

**Comment by kg905812262** [comment]
Thanks to @EstonianGiant ,

The problem has solved and now it works like a charm.
