### ISSUE TITLE
What is the dependence on the editor for Training? Is it only for the "Play Event"?

### ISSUE THREAD

**Issue by EstonianGiant** [Unity-Technologies/ml-agents#1079]
Is the "Play Button Event" just being used as an convenient way to tell python (via grpc) to start & stop training, or are there any other editor dependencies?

**Comment by awjuliani** [comment]
Hi @EstonianGiant,

The majority of the training process is not dependent on the Editor. As you mention, only the logic needed to connect when the "Play" button is pressed.

**Comment by EstonianGiant** [comment]
Great, thanks!
