### ISSUE TITLE
TFException: Matrix size-incompatible

### ISSUE THREAD

**Issue by gerardsimons** [Unity-Technologies/ml-agents#108]
At times when I try and run of my trained bytes brain (Internal) I get this error : 

```
TFException: Matrix size-incompatible: In[0]: [1,12], In[1]: [5,64]
	 [[Node: dense/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_state_0_1, dense/kernel/read)]]
TensorFlow.TFStatus.CheckMaybeRaise (TensorFlow.TFStatus incomingStatus, System.Boolean last) (at <6ed6db22f8874deba74ffe3e566039be>:0)
TensorFlow.TFSession.Run (TensorFlow.TFOutput[] inputs, TensorFlow.TFTensor[] inputValues, TensorFlow.TFOutput[] outputs, TensorFlow.TFOperation[] targetOpers, TensorFlow.TFBuffer runMetadata, TensorFlow.TFBuffer runOptions, TensorFlow.TFStatus status) (at <6ed6db22f8874deba74ffe3e566039be>:0)
TensorFlow.TFSession+Runner.Run (TensorFlow.TFStatus status) (at <6ed6db22f8874deba74ffe3e566039be>:0)
CoreBrainInternal.DecideAction () (at Assets/ML-Agents/Scripts/CoreBrainInternal.cs:244)
Brain.DecideAction () (at Assets/ML-Agents/Scripts/Brain.cs:308)
Academy.DecideAction () (at Assets/ML-Agents/Scripts/Academy.cs:250)
Academy.RunMdp () (at Assets/ML-Agents/Scripts/Academy.cs:337)
Academy.RunMdp () (at Assets/ML-Agents/Scripts/Academy.cs:328)
Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:260)
```

It actually often happens just after I set the wrong number of states. So first I would get this : 

```
UnityAgentsException: The number of states does not match for agent pointerAgent:
	Was expecting 5 states but received 12.
```

Which I then change, so the incompatible number of states is not the issue. Nor is the number of actions. I also do not use *any* experiences or observations.

Please see the below screenshot. Thank you.

<img width="1280" alt="screen shot 2017-10-26 at 10 39 18" src="https://user-images.githubusercontent.com/4247845/32043317-b60214d2-ba3a-11e7-8eff-fc2db910db6a.png">

**Comment by JoshuaLight** [comment]
Well, as far as I remember, two matrices can be multiplied if they have sizes like `A x B` and `B x C`.

It looks like error says: "Hey, you want to multiple `1 x 12` by `5 x 64`, so, this is kinda impossible".

Did you try to change `State Size` for brain from `12` to `5`? Error is still the same?

**Comment by gerardsimons** [comment]
@JoshuaLight Thanks for the help. I understand the linear algebra behind it and why it's impossible, it's just that I don't understand why these matrices are of different dimensions. Indeed as explain in my post I changed the state size so they match.

**Comment by vincentpierre** [comment]
It looks to me that you trained you model with `state size` of 5 and THEN modified the brain to take in 12 states. If that is the case, here is what I would do : What is the state size you want for your model?  
 * If you want 5, you need to modify `CollectState` to return 5 states and set the brain parameter state size to 5
 * If you want 12, you will need to retrain your model to take in 12 states and set the brain parameter state size to 12

**Comment by gerardsimons** [comment]
Ah yes, the problem was that in the `CollectState` code it was still returning a different number of states. I forgot my Agent.cs is still being used, even by an internal brain. So to summarized, the number returned by `CollectState` must match the State declared in the Academy and the number in the actual TensorFlow model.
