### ISSUE TITLE
Why my tf summaries graphs are having more than one y axis value for x axis value, when step is along x axis 

### ISSUE THREAD

**Issue by TejaswiniiB** [Unity-Technologies/ml-agents#1081]
Hi,
Following are two graphs - one with step on horizontal axis, and another with wall on horizontal axis. I don't understand why there are more than one y value, when step is on horizontal axis, when everything is fine for wall on horizontal axis ?
All my statistics graphs are in the same above way.

Where am I doing wrong? When this might occur?

Thankyou !!

![step](https://user-images.githubusercontent.com/24452276/43954454-38ad3ecc-9cba-11e8-8300-46297dc3d4ea.PNG)
![wall](https://user-images.githubusercontent.com/24452276/43954455-38df87f6-9cba-11e8-95b5-e72e8ad7c82c.PNG)

**Comment by mbaske** [comment]
Did you run multiple training sessions with the same run-id? Could be that the stats from multiple sessions accumulated in your summaries folder. In Tensorboard, they overlap in "step" mode but not in "wall" mode because the latter is time-based.

**Comment by TejaswiniiB** [comment]
Oh Okay, yes I  ran multiple training sessions with the same run-id. Thankyou !
