### ISSUE TITLE
Agent.AddVectorObs(float observation) and Agent.AddVectorObs(List<float> observation) lead to different training resluts

### ISSUE THREAD

**Issue by timdhoffmann** [Unity-Technologies/ml-agents#1090]
Adding float observations to a list and calling a single `AddVectorObs()`, passing that list as argument did not work in my training scenario (read: *did not* lead to expected results).
Replacing the single call with multiple `AddVectorObs()`, passing one float observation with each as argument, *did* lead to the expected training results.

Is this expected behaviour?

Best,
Tim

See commented code below:

```
public override void CollectObservations()
    {
        // Define observations.
        
        var raycastDistance = 20.0f;

        var distanceUp = 100f;
        // Raycasts up.
        RaycastHit2D hit2D = Physics2D.Raycast(transform.position, Vector2.up, raycastDistance);
        if (hit2D.collider)
        {
            distanceUp = hit2D.distance; 
        }

        var distanceDown = 100f;
        // Raycasts down.
        hit2D = Physics2D.Raycast(transform.position, Vector2.down, raycastDistance);
        if (hit2D.collider)
        {
            distanceDown = hit2D.distance;
        }

        var distanceLeft = 100f;
        // Raycasts left.
        hit2D = Physics2D.Raycast(transform.position, Vector2.left, raycastDistance);
        if (hit2D.collider)
        {
            distanceLeft = hit2D.distance;
        }

        var distanceRight = 100f;
        // Raycasts right.
        hit2D = Physics2D.Raycast(transform.position, Vector2.right, raycastDistance);
        if (hit2D.collider)
        {
            distanceRight = hit2D.distance;
        }

        // Submit observations.

        /// [IMPORTANT!] 
        /// Submitting observations in a single list seems to lead
        /// to undesired results!!!
        //var state = new List<float>()
        //{
        //    distanceUp,
        //    distanceDown,
        //    distanceLeft,
        //    distanceRight,
        //    _rigidBody2D.velocity.x,
        //    _rigidBody2D.velocity.y,
        //};
        //AddVectorObs(state);

        /// Therefore, submitting each observation separately.
        AddVectorObs(distanceUp);
        AddVectorObs(distanceDown);
        AddVectorObs(distanceLeft);
        AddVectorObs(distanceRight);
        AddVectorObs(_rigidBody2D.velocity.x);
        AddVectorObs(_rigidBody2D.velocity.y);
    }
```

**Comment by awjuliani** [comment]
Hi @timdhoffmann,

Thanks for bringing this us. Behind the scenes the difference is between repeatedly calling `.Add(item)` vs calling `.AddRange(List<item>)`. On the surface I don't see a reason why these would lead to different behaviors. I can look into this more though.

Would it be possible to use the Basic notebook (https://github.com/Unity-Technologies/ml-agents/blob/master/python/Basics.ipynb) to print out what the observation vector looks like in both cases?

**Comment by timdhoffmann** [comment]
Ok, I figured out how to run the notebook. Initially I followed the official instructions for running it on windows, but I had to activate the ml-agents environment in Anaconda Prompt first and then run `jupyter notebook` from the environment...

Anyways, these are the two exported outputs:
# **a) When using multiple `AddVectorObs(float)`:**

# Unity ML-Agents Toolkit
## Environment Basics
This notebook contains a walkthrough of the basic functions of the Python API for the Unity ML-Agents toolkit. For instructions on building a Unity environment, see [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Getting-Started-with-Balance-Ball.md).

### 1. Set environment parameters

Be sure to set `env_name` to the name of the Unity environment file you want to launch. Ensure that the environment build is in the `python/` directory.


```python
env_name = "MultipleFloats/Unity Environment"  # Name of the Unity environment binary to launch
train_mode = True  # Whether to run the environment in training or inference mode
```

### 2. Load dependencies

The following loads the necessary dependencies and checks the Python version (at runtime). ML-Agents Toolkit (v0.3 onwards) requires Python 3.


```python
import matplotlib.pyplot as plt
import numpy as np
import sys

from unityagents import UnityEnvironment

%matplotlib inline

print("Python version:")
print(sys.version)

# check Python version
if (sys.version_info[0] < 3):
    raise Exception("ERROR: ML-Agents Toolkit (v0.3 onwards) requires Python 3")
```

    Python version:
    3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]
    

### 3. Start the environment
`UnityEnvironment` launches and begins communication with the environment when instantiated.

Environments contain _brains_ which are responsible for deciding the actions of their associated _agents_. Here we check for the first brain available, and set it as the default brain we will be controlling from Python.


```python
env = UnityEnvironment(file_name=env_name)

# Examine environment parameters
print(str(env))

# Set the default brain to work with
default_brain = env.brain_names[0]
brain = env.brains[default_brain]
```

    INFO:unityagents:
    'Academy' started successfully!
    Unity Academy name: Academy
            Number of Brains: 1
            Number of External Brains : 1
            Lesson number : 0
            Reset Parameters :
    		
    Unity brain name: AvoidingMLAgentBrain
            Number of Visual Observations (per agent): 0
            Vector Observation space type: continuous
            Vector Observation space size (per agent): 6
            Number of stacked Vector Observation: 1
            Vector Action space type: continuous
            Vector Action space size (per agent): 4
            Vector Action descriptions: , , , 
    

    Unity Academy name: Academy
            Number of Brains: 1
            Number of External Brains : 1
            Lesson number : 0
            Reset Parameters :
    		
    Unity brain name: AvoidingMLAgentBrain
            Number of Visual Observations (per agent): 0
            Vector Observation space type: continuous
            Vector Observation space size (per agent): 6
            Number of stacked Vector Observation: 1
            Vector Action space type: continuous
            Vector Action space size (per agent): 4
            Vector Action descriptions: , , , 
    

### 4. Examine the observation and state spaces
We can reset the environment to be provided with an initial set of observations and states for all the agents within the environment. In ML-Agents, _states_ refer to a vector of variables corresponding to relevant aspects of the environment for an agent. Likewise, _observations_ refer to a set of relevant pixel-wise visuals for an agent.


```python
# Reset the environment
env_info = env.reset(train_mode=train_mode)[default_brain]

# Examine the state space for the default brain
print("Agent state looks like: \n{}".format(env_info.vector_observations[0]))

# Examine the observation space for the default brain
for observation in env_info.visual_observations:
    print("Agent observations look like:")
    if observation.shape[3] == 3:
        plt.imshow(observation[0,:,:,:])
    else:
        plt.imshow(observation[0,:,:,0])
```

    Agent state looks like: 
    [4.5        4.5        8.39999962 8.39999962 0.         0.        ]
    

### 5. Take random actions in the environment
Once we restart an environment, we can step the environment forward and provide actions to all of the agents within the environment. Here we simply choose random actions based on the `action_space_type` of the default brain. 

Once this cell is executed, 10 messages will be printed that detail how much reward will be accumulated for the next 10 episodes. The Unity environment will then pause, waiting for further signals telling it what to do next. Thus, not seeing any animation is expected when running this cell.


```python
for episode in range(10):
    env_info = env.reset(train_mode=train_mode)[default_brain]
    done = False
    episode_rewards = 0
    while not done:
        if brain.vector_action_space_type == 'continuous':
            env_info = env.step(np.random.randn(len(env_info.agents), 
                                                brain.vector_action_space_size))[default_brain]
        else:
            env_info = env.step(np.random.randint(0, brain.vector_action_space_size, 
                                                  size=(len(env_info.agents))))[default_brain]
        episode_rewards += env_info.rewards[0]
        done = env_info.local_done[0]
    print("Total reward this episode: {}".format(episode_rewards))
```

    Total reward this episode: 18.80000029504299
    Total reward this episode: 12.90000020712614
    Total reward this episode: 17.700000278651714
    Total reward this episode: 50.100000746548176
    Total reward this episode: 17.30000027269125
    Total reward this episode: 21.100000329315662
    Total reward this episode: 50.100000746548176
    Total reward this episode: 33.1000005081296
    Total reward this episode: 14.70000023394823
    Total reward this episode: 13.70000021904707
    

### 6. Close the environment when finished
When we are finished using an environment, we can close it with the function below.


```python
env.close()
```


# **b) When using a single `AddVectorObs(List<float>)`:**

# Unity ML-Agents Toolkit
## Environment Basics
This notebook contains a walkthrough of the basic functions of the Python API for the Unity ML-Agents toolkit. For instructions on building a Unity environment, see [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Getting-Started-with-Balance-Ball.md).

### 1. Set environment parameters

Be sure to set `env_name` to the name of the Unity environment file you want to launch. Ensure that the environment build is in the `python/` directory.


```python
env_name = "SingleFloatList/Unity Environment"  # Name of the Unity environment binary to launch
train_mode = True  # Whether to run the environment in training or inference mode
```

### 2. Load dependencies

The following loads the necessary dependencies and checks the Python version (at runtime). ML-Agents Toolkit (v0.3 onwards) requires Python 3.


```python
import matplotlib.pyplot as plt
import numpy as np
import sys

from unityagents import UnityEnvironment

%matplotlib inline

print("Python version:")
print(sys.version)

# check Python version
if (sys.version_info[0] < 3):
    raise Exception("ERROR: ML-Agents Toolkit (v0.3 onwards) requires Python 3")
```

    Python version:
    3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]
    

### 3. Start the environment
`UnityEnvironment` launches and begins communication with the environment when instantiated.

Environments contain _brains_ which are responsible for deciding the actions of their associated _agents_. Here we check for the first brain available, and set it as the default brain we will be controlling from Python.


```python
env = UnityEnvironment(file_name=env_name)

# Examine environment parameters
print(str(env))

# Set the default brain to work with
default_brain = env.brain_names[0]
brain = env.brains[default_brain]
```

    INFO:unityagents:
    'Academy' started successfully!
    Unity Academy name: Academy
            Number of Brains: 1
            Number of External Brains : 1
            Lesson number : 0
            Reset Parameters :
    		
    Unity brain name: AvoidingMLAgentBrain
            Number of Visual Observations (per agent): 0
            Vector Observation space type: continuous
            Vector Observation space size (per agent): 6
            Number of stacked Vector Observation: 1
            Vector Action space type: continuous
            Vector Action space size (per agent): 4
            Vector Action descriptions: , , , 
    

    Unity Academy name: Academy
            Number of Brains: 1
            Number of External Brains : 1
            Lesson number : 0
            Reset Parameters :
    		
    Unity brain name: AvoidingMLAgentBrain
            Number of Visual Observations (per agent): 0
            Vector Observation space type: continuous
            Vector Observation space size (per agent): 6
            Number of stacked Vector Observation: 1
            Vector Action space type: continuous
            Vector Action space size (per agent): 4
            Vector Action descriptions: , , , 
    

### 4. Examine the observation and state spaces
We can reset the environment to be provided with an initial set of observations and states for all the agents within the environment. In ML-Agents, _states_ refer to a vector of variables corresponding to relevant aspects of the environment for an agent. Likewise, _observations_ refer to a set of relevant pixel-wise visuals for an agent.


```python
# Reset the environment
env_info = env.reset(train_mode=train_mode)[default_brain]

# Examine the state space for the default brain
print("Agent state looks like: \n{}".format(env_info.vector_observations[0]))

# Examine the observation space for the default brain
for observation in env_info.visual_observations:
    print("Agent observations look like:")
    if observation.shape[3] == 3:
        plt.imshow(observation[0,:,:,:])
    else:
        plt.imshow(observation[0,:,:,0])
```

    Agent state looks like: 
    [4.5        4.5        8.39999962 8.39999962 0.         0.        ]
    

### 5. Take random actions in the environment
Once we restart an environment, we can step the environment forward and provide actions to all of the agents within the environment. Here we simply choose random actions based on the `action_space_type` of the default brain. 

Once this cell is executed, 10 messages will be printed that detail how much reward will be accumulated for the next 10 episodes. The Unity environment will then pause, waiting for further signals telling it what to do next. Thus, not seeing any animation is expected when running this cell.


```python
for episode in range(10):
    env_info = env.reset(train_mode=train_mode)[default_brain]
    done = False
    episode_rewards = 0
    while not done:
        if brain.vector_action_space_type == 'continuous':
            env_info = env.step(np.random.randn(len(env_info.agents), 
                                                brain.vector_action_space_size))[default_brain]
        else:
            env_info = env.step(np.random.randint(0, brain.vector_action_space_size, 
                                                  size=(len(env_info.agents))))[default_brain]
        episode_rewards += env_info.rewards[0]
        done = env_info.local_done[0]
    print("Total reward this episode: {}".format(episode_rewards))
```

    Total reward this episode: 26.10000040382147
    Total reward this episode: 28.40000043809414
    Total reward this episode: 18.700000293552876
    Total reward this episode: 16.200000256299973
    Total reward this episode: 12.300000198185444
    Total reward this episode: 19.40000030398369
    Total reward this episode: 17.500000275671482
    Total reward this episode: 24.600000381469727
    Total reward this episode: 17.900000281631947
    Total reward this episode: 28.700000442564487
    

### 6. Close the environment when finished
When we are finished using an environment, we can close it with the function below.


```python
env.close()
```

**Comment by awjuliani** [comment]
Thanks for sharing the output from Jupyter, @timdhoffmann. Strangely, it seems that the observation in both cases is exactly the same:

`[4.5        4.5        8.39999962 8.39999962 0.         0.        ]`

vs

`[4.5        4.5        8.39999962 8.39999962 0.         0.        ]`

Can you describe a little more about how the training and learned behavior is different between the two methods?

**Comment by timdhoffmann** [comment]
That's weird. Or maybe it's not. I wouldn't rule out the possibility that the mistake is on my end ;) 
I might have done something wrong when I initially experienced the problem, or when building the two different project versions for the notebook testing.
Don't have the time right now, but I will try to do more testing in order to reproduce the issue.

Anyways, here is a brief description of the setup and my observations:
1. Setup:
- It is a simple 2D test project, where the agent with a Rigidbody2D and 0 gravity should learn to float while avoiding to hit one of the four borders around it. 
- Observations are up/down/left/right distances to the four borders from raycasting and its own x/y velocity.
- Actions should be applying x/y force to its own Rigidbody2D.

2. My observations:
- When using a single list of floats as argument with AddVectorObs(), the agent constantly bumped into the borders. I tried a few (3 < few < 10) training passes with no success.
- When I switched to using multiple calls to AddVectorObs() with a single float as argument per call, the agent was able to float around and avoid the borders right after the first training.

I don't know if it might have been just by chance that i had been unlucky with the first trainings and suddenly had success with the other method...

**Comment by dhar174** [comment]
I am wondering about this same issue. My project is a 2D project as well, and with very similiar expectations and similar problems. My 2d agents keep running into borders when they should know better, and I'm passing a List of floats.... I will currently test to see if it makes a difference to pass them as separate floats and post back.

**Comment by xiaomaogy** [comment]
@awjuliani Can I close this?

**Comment by harperj** [comment]
This issue has been inactive for some time (and we've since released a newer version of ML-Agents), so I'm going to close it.  Please feel free to re-open if you continue to see this problem.
