### ISSUE TITLE
On-Demand Decision training against a heuristic brain throws exception

### ISSUE THREAD

**Issue by jo3w4rd** [Unity-Technologies/ml-agents#1093]
I made an environment of a two-player game using On-Demand decisions and two brains. Training functions properly if both brains are external, but the environment hangs if I set one brain to external and one to heuristic. Inference works fine with either or both brains set to internal or heuristic.

The environment always hangs just before the second turn of the second player. In the environment log, I see two exceptions, listed below. The first is thrown a few hundred times and then after that the second is thrown from that point onward.

Exception
ArgumentNullException: Value cannot be null.
Parameter name: values
Google.Protobuf.Collections.RepeatedField`1[T].AddRange (System.Collections.Generic.IEnumerable`1[T] values) (at <53efaed03be741309d533ea799514544>:0)
Google.Protobuf.Collections.RepeatedField`1[T].Add (System.Collections.Generic.IEnumerable`1[T] values) (at <53efaed03be741309d533ea799514544>:0)
MLAgents.Batcher.AgentInfoConvertor (MLAgents.AgentInfo info) (at <74dd45c0456640008ef7a6bc7fba4308>:0)
MLAgents.Batcher.SendBrainInfo (System.String brainKey, System.Collections.Generic.Dictionary`2[TKey,TValue] agentInfo) (at <74dd45c0456640008ef7a6bc7fba4308>:0)
MLAgents.CoreBrainHeuristic.DecideAction (System.Collections.Generic.Dictionary`2[TKey,TValue] agentInfo) (at <74dd45c0456640008ef7a6bc7fba4308>:0)
MLAgents.Brain.DecideAction () (at <74dd45c0456640008ef7a6bc7fba4308>:0)
MLAgents.Academy.EnvironmentStep () (at <74dd45c0456640008ef7a6bc7fba4308>:0)
MLAgents.Academy.FixedUpdate () (at <74dd45c0456640008ef7a6bc7fba4308>:0)

Exception
ArgumentException: An item with the same key has already been added. Key: OAgent (TicTacToeAgent)
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <e1a80661d61443feb3dbdaac88eeb776>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <e1a80661d61443feb3dbdaac88eeb776>:0)
MLAgents.Brain.SendState (MLAgents.Agent agent, MLAgents.AgentInfo info) (at <74dd45c0456640008ef7a6bc7fba4308>:0)
MLAgents.Agent.SendInfoToBrain () (at <74dd45c0456640008ef7a6bc7fba4308>:0)
MLAgents.Agent.SendInfo () (at <74dd45c0456640008ef7a6bc7fba4308>:0)
MLAgents.Academy.EnvironmentStep () (at <74dd45c0456640008ef7a6bc7fba4308>:0)
MLAgents.Academy.FixedUpdate () (at <74dd45c0456640008ef7a6bc7fba4308>:0)

**Comment by jo3w4rd** [comment]
Assets for this project are here: https://github.com/jo3w4rd/roughdraft/tree/master/unity/Tic-Tac-Toe/Assets

**Comment by awjuliani** [comment]
Thanks for pointing this out @jo3w4rd. I am assigning @vincentpierre since he has worked most with ODD.

**Comment by vincentpierre** [comment]
Is due to the memory of the agent being set to null in the Heuristic Brain. One temporary fix is to modify the `RandomDecision` script method 
```csharp
    public List<float> MakeMemory(
            List<float> vectorObs,
            List<Texture2D> visualObs,
            float reward,
            bool done,
        List<float> memory){
        return null;
    }
```
with 
```csharp
    public List<float> MakeMemory(
            List<float> vectorObs,
            List<Texture2D> visualObs,
            float reward,
            bool done,
        List<float> memory){
        return new List<float>();
    }
```
But there should be a nice catching of null memories either in Agent or in Batcher.
