### ISSUE TITLE
'Academy' started successfully But Training not responding

### ISSUE THREAD

**Issue by X-funbean** [Unity-Technologies/ml-agents#1100]
Hi!
I'm using Unity 2018.2.1f1 Personal(64 bit) and I cloned the latest version of ml-agents-master. I'm getting started with 3DBall. I've already set the brain type to 'External', and I decided to train it with `Basics.ipynb`.
Here's my environment parameters:
![set env](https://user-images.githubusercontent.com/24663255/44277803-6fcbb400-a27e-11e8-90a2-a14579a73496.PNG)
and loading dependencies:
![python versionn](https://user-images.githubusercontent.com/24663255/44277835-896cfb80-a27e-11e8-9eea-3f2e395f279a.PNG)
and when I started the environment, it says 'Ball3DAcademy' started successfully!' and shows the info:
![default](https://user-images.githubusercontent.com/24663255/44277881-c0431180-a27e-11e8-9bba-93626eafba8d.PNG)
However, the training window hung, and I saw nothing!
![default](https://user-images.githubusercontent.com/24663255/44278023-495a4880-a27f-11e8-9e76-1164d67a2174.PNG)
I had to kill the process. The second time I started the training, it threw the error 'The Unity environment took too long to respond':
![not responding](https://user-images.githubusercontent.com/24663255/44278194-d7363380-a27f-11e8-9b05-aaf1765d4439.PNG)
I opened the 'output_log.txt'  and found 'Fallback handler could not load library...': 

```
Mono path[0] = 'F:/Study/Unity/ml-agents-master/python/3DBall/Ball_Data/Managed'
Mono config path = 'F:/Study/Unity/ml-agents-master/python/3DBall/MonoBleedingEdge/etc'
PlayerConnection initialized from F:/Study/Unity/ml-agents-master/python/3DBall/Ball_Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55207
Multi-casting "[IP] 192.168.1.103 [Port] 55207 [Flags] 2 [Guid] 1295603901 [EditorId] 3829322133 [Version] 1048832 [Id] WindowsPlayer(X-funbean) [Debug] 0 [PackageName] WindowsPlayer" to [225.0.0.222:54997]...
Started listening to [0.0.0.0:55207]
PlayerConnection already initialized - listening to [0.0.0.0:55207]
Initialize engine version: 2018.2.1f1 (1a9968d9f99c)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: AMD Radeon(TM) R6 Graphics (ID=0x130a)
    Vendor:   
    VRAM:     3027 MB
    Driver:   14.201.1003.1002
Begin MonoManager ReloadAssembly
- Completed reload, in  0.206 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 1.324502 ms
Fallback handler could not load library F:/Study/Unity/ml-agents-master/python/3DBall/Ball_Data/Mono/libcoreclr.so
Fallback handler could not load library F:/Study/Unity/ml-agents-master/python/3DBall/Ball_Data/Mono/libcoreclr.so.dll
Fallback handler could not load library F:/Study/Unity/ml-agents-master/python/3DBall/Ball_Data/Mono/libcoreclr.so
Fallback handler could not load library F:/Study/Unity/ml-agents-master/python/3DBall/Ball_Data/Mono/libdl.so
Fallback handler could not load library F:/Study/Unity/ml-agents-master/python/3DBall/Ball_Data/Mono/libdl.so.dll
Fallback handler could not load library F:/Study/Unity/ml-agents-master/python/3DBall/Ball_Data/Mono/libdl.so
Fallback handler could not load library F:/Study/Unity/ml-agents-master/python/3DBall/Ball_Data/Mono/libSystem.dylib
Fallback handler could not load library F:/Study/Unity/ml-agents-master/python/3DBall/Ball_Data/Mono/libSystem.dylib.dll
Fallback handler could not load library F:/Study/Unity/ml-agents-master/python/3DBall/Ball_Data/Mono/libSystem.dylib
Fallback handler could not load library F:/Study/Unity/ml-agents-master/python/3DBall/Ball_Data/Mono/libcoreclr.so
Fallback handler could not load library F:/Study/Unity/ml-agents-master/python/3DBall/Ball_Data/Mono/libcoreclr.so.dll
Fallback handler could not load library F:/Study/Unity/ml-agents-master/python/3DBall/Ball_Data/Mono/libcoreclr.so
Fallback handler could not load library F:/Study/Unity/ml-agents-master/python/3DBall/Ball_Data/Mono/libdl.so
Fallback handler could not load library F:/Study/Unity/ml-agents-master/python/3DBall/Ball_Data/Mono/libdl.so.dll
Fallback handler could not load library F:/Study/Unity/ml-agents-master/python/3DBall/Ball_Data/Mono/libdl.so
Fallback handler could not load library F:/Study/Unity/ml-agents-master/python/3DBall/Ball_Data/Mono/libSystem.dylib
Fallback handler could not load library F:/Study/Unity/ml-agents-master/python/3DBall/Ball_Data/Mono/libSystem.dylib.dll
Fallback handler could not load library F:/Study/Unity/ml-agents-master/python/3DBall/Ball_Data/Mono/libSystem.dylib

```

I've got no idea how to handle this. Anyone could please help me out?

**Comment by vincentpierre** [comment]
Hi, do not worry about Fallback Handler, this is not an issue.
Are you able to do in editor training ? In editor training allows us to see bugs raised in Unity more easily.
Are you able to play with a balance ball executable with a player brain ?
Did you run all the cells in order and waited between each step or are you not able to run cell 4 and 5 at all? 
If not, I think this could be a Windows firewall issue.

**Comment by X-funbean** [comment]
@vincentpierre Thanks for help!
After a few trials, I somehow managed to train in both Unity editor and jupyter notebook! Maybe I got something wrong in previous trials. 
![unity](https://user-images.githubusercontent.com/24663255/44301741-04054c00-a34f-11e8-99be-d583d601f07a.PNG)
Thanks a lot!
