### ISSUE TITLE
How can I add a brain at runtime?

### ISSUE THREAD

**Issue by ann234** [Unity-Technologies/ml-agents#1103]
Hello, I tried to train multiple modular robots so every robot agent has different brain.
I tried to add a agent and brain at runtime(at start) but gets an error like

UnityAgentsException: The brain RobotAgentBrain1 was set to External mode but Unity was unable to read the arguments passed at launch.
MLAgents.CoreBrainExternal.InitializeCoreBrain (MLAgents.Batcher brainBatcher) (at Assets/ML-Agents/Scripts/CoreBrainExternal.cs:28)
MLAgents.Brain.InitializeBrain (MLAgents.Academy aca, MLAgents.Batcher brainBatcher) (at Assets/ML-Agents/Scripts/Brain.cs:211)
BrainManager.MakeBrain (RobotAgent agent) (at Assets/Scripts/ReinforcementLearning/BrainManager.cs:62)
RobotAgent.InitializeAgent () (at Assets/Scripts/ReinforcementLearning/RobotAgent.cs:78)
MLAgents.Agent.OnEnableHelper (MLAgents.Academy academy) (at Assets/ML-Agents/Scripts/Agent.cs:302)
MLAgents.Agent.OnEnable () (at Assets/ML-Agents/Scripts/Agent.cs:267)

I instantiate a prefab that only have brain and set observation, action type and size, braintype(external for training) and set this child to academy,
Is it impossible to add new brain at runtime? should I have to add a brain at academy before starting?

**Comment by vincentpierre** [comment]
As of version 0.4, it is not possible to add brains at runtime. That is because the Academy must communicate to Python all the information about the brains it is tracking at initialization.
I hope this helps.

**Comment by ann234** [comment]
It helps me a lot thanks!

Additionally, then can I change brain's parameters(vector observation, actions etc..) at runtime?

My project's flow is
1. Train first generation agents(All of agents has different brain, I can set up at start)
2. After N steps, based on my 1st generation agents, make 2nd generation agents and destroy 1st agents
3. What I want is train 2nd generation agents but I can't make new brains for my 2nd agents.
So, 2nd agents will use previous brains and **I need to change brain parameters at runtime and train this brains**.

Any advice is very welcome.

**Comment by MarcoMeter** [comment]
@vincentpierre 
What about adding an internal brain at run-time?

**Comment by vincentpierre** [comment]
Because of the way the brains are currently being initialized, it is not possible to spawn any brain at runtime but we are looking into ways to add non-external and non-broadcasting brains at runtime.

**Comment by antoine-doolaeghe** [comment]
Hello, I'm curious to know if there has been any evolution on supporting brain load at runtime ? Thanks

**Comment by vincentpierre** [comment]
This issue is closed, please open a new one.
It is possible to load `.nn` models into existing brains. This is not loading a new brain but it is loading a different model in an existing brain. You will need to modify the public property model of the Learning Brain and then call ReloadModel().
Now that brains are scriptable objects, it might be possible to spawn them at runtime but loading a new .nn should be good enough (you wont have to worry about passing the right brain parameters).
