### ISSUE TITLE
Is there anyway to tell agent use action per episode only once?

### ISSUE THREAD

**Issue by surferau** [Unity-Technologies/ml-agents#111]
For example if each action represents consumable, 1 - apple, 2 - grape, 3 - melon , so agent cant use repetitive actions like [1,1,3] there was only 1. The work around i use now is to punish agent when he tries to eat something twice with negative reward, but i feel it slows down overall learning process significantly.

**Comment by dora-gt** [comment]
Interesting. I want to know too.

- Punishing
- Ignore the action
- Using memory (though it may have limitation)
- Adding state that means `You are able to consume X`
  - like...
    - State: can consume apple = 1.0f
    - State: can consume grape = 1.0f
    - State: can consume melon = 1.0f

Which is the best answer? 🤔
I think the last one is...?

**Comment by dora-gt** [comment]
Interesting. I want to know too.

- Punishing
- Ignore the action
- Using memory (though it may have limitation)
- Adding state that means `You are able to consume X`
  - like...
    - State: can consume apple = 1.0f
    - State: can consume grape = 1.0f
    - State: can consume melon = 1.0f

Which is the best answer? 🤔
I think the last one is...?

**Comment by awjuliani** [comment]
Hi @surferau,

This is an interesting question. One simple answer is to have nothing happen. The same as if a human tried clicking a disabled button on a screen.  Punishing it would likely have unintended consequences, where the agent would learn to avoid that action, even when it is useful. As @dora-gt mentioned, it would likely be helpful to provide a state representation which lets the agent know what items or actions are currently available to it.

**Comment by surferau** [comment]
In theory it may make model hang, say for example there are only one legitimate action left according to gameplay but it is bad action and will be punished so agent will choose to spam the non legitimate action instead since according to training there is no problem with it.

**Comment by dora-gt** [comment]
I think it depends on the reward design.
I mean...

- rewarded +1.0 when good and legitimate action
- rewarded +0.1 when bad and legitimate action
- rewarded 0.0 (or -1.0) when non legitimate action
(I don't know the very meaning of PUNISHMENT, difference between 0.0 and -1.0)

This design doesn't make model hang I think.
Am i wrong?

**Comment by mmattar** [comment]
Hi @dora-gt - your reward set-up looks reasonable. A negative reward is a good form of punishment :). Closing this out, but let us know if you have any additional questions. We've also since released v0.3 of ML-Agents.
