### ISSUE TITLE
How to build input layer when using own source code

### ISSUE THREAD

**Issue by kanchi0914** [Unity-Technologies/ml-agents#112]
Hi there,
I'm trying to implement my own Deep Q-Network code in simple environment based on mainly ppo.py and models.py.
I build　input layer as follows (input_num = 2, state is continuous) , 
`self.x = tf.placeholder(shape=[None, self.input_num], dtype=tf.float32, name='state')`
and ran, but returned error as below.

>   ValueError: Cannot feed value of shape (1, 1, 2) for Tensor 'state:0', which has shape '(?, 2)'

Instead, I used input layer as follows, then it looked like the program completely works well.
`self.x = tf.placeholder(shape=[None, 1, self.input_num], dtype=tf.float32, name='state')`
`self.x = tf.reshape(self.x, [-1, self.input_num])`

However, when I moved created .bytes file into Unity and build, my agent does not move at all(agent moves as expected when using .bytes flie created by ppo.py). 

How do I build input layer correctly when using my own code?
I made agent as class (like `class MyAgent: ~~~`) contained TensorFlow separately from main class, so did it cause errors?
Sorry for my bad English, thanks.

**Comment by awjuliani** [comment]
Hi @kanchi0914,

The size `[None, state_size]` is the correct input shape. You might want to reshape the inputs to the network themself using numpy to ensure they are in that shape.

**Comment by kwea123** [comment]
feed "state = env_info.states[0]", which has shape (1, state_size)
if you have many, use "np.vstack(states)", which has shape (n, state_size) where n is the number of states
