### ISSUE TITLE
Speed up crawler movement speed

### ISSUE THREAD

**Issue by louis030195** [Unity-Technologies/ml-agents#1129]
Hello,

I'm playing around with ML-agent (great library btw !), i successfully build a game with 2 brains, one type of agent(herbivorous agent) that try to eat some white cubes(food) and another agent(carnivorous) that try to eat the herbivorous one.
It works pretty well atm using dense rewards (collide with the other one) and using rayperception.

Now i wanted to have a more realistic agent instead of simple cube, so i'm trying to add the crawler example in my game.
I don't know really how the joints works, anyway i added the crawler into my game but i find it very slow to test  and i was wondering if it's possible to boost his movement speed ?

**Comment by mmattar** [comment]
What value are you setting the `Time Scale` field in the `Academy` to? For our own Crawler environment it is set to 100.

**Comment by louis030195** [comment]
It is 100 also, but is there any way to accelerate more the agent ? I tried to change the values in the joint controller without success ...

**Comment by xiaomaogy** [comment]
@harperj

**Comment by harperj** [comment]
Unfortunately there's not currently a way to increase the time scale further.  I'm going to close this issue due to inactivity / not being actionable but please feel free to reopen if there's more to discuss.
