### ISSUE TITLE
Is Memory/RNN implemented ?

### ISSUE THREAD

**Issue by SPINACHCEO** [Unity-Technologies/ml-agents#113]
Hi there.
I saw there is a ‘memory’ field in the brain inspector, but I couldn’t find any implementation of RNN or such models in the python code.
Is the memory function not yet implemented?

Thanks you :)

**Comment by awjuliani** [comment]
Hi @SPINACHCEO,

We haven't implemented an RNN model yet. You are correct in identifying that this is exactly what `Memory` will be used for in the future though. It is a placeholder to allow recurrent inputs to a neural network.

**Comment by vincentpierre** [comment]
We have an implementation of RNN for both PPO and Imitation learning as of version 0.3
