### ISSUE TITLE
Python error when both brains have visual observation in imitation learning 

### ISSUE THREAD

**Issue by lcyzgdy** [Unity-Technologies/ml-agents#1130]
I want to train a brush AI in my painter project use imitation learning. There are two brains in my scene -- teacher brain and student brain. Each brain has visual observation, with width: 256, height: 144 and "Black And White": false. But when I start training, it occurred in Python: "ValueError: Cannot feed value of shape (1, 32, 144, 256, 3) for Tensor 'visual_observation_0:0', which has shape '(?, 144, 256, 3)'" and Unity exited playing mode. If only teacher brain has this visual observation, nothing will happen and Python can save a '.byte' model.

**Comment by xiaomaogy** [comment]
@mmattar

**Comment by IJEMIN** [comment]
Same here. I got this : 
`ValueError: Cannot feed value of shape (1, 32, 256, 256, 3) for Tensor 'visual_observation_0:0', which has shape '(?, 256, 256, 3)'`

I found set `use_recurrent: false` would fix the problem but I don't know why.

**Comment by IJEMIN** [comment]
I could reproduce error by using "use_recurrent : true" with imitation learning and multiple agents using visual observation.

**Comment by mmattar** [comment]
Hi, @lcyzgdy / @IJEMIN - apologies for the delays in looping back on this. We've released v0.7 of ML-Agents, are you still observing this issue? Also, is this occurring in any of our demo scenes?

**Comment by harperj** [comment]
I'm going to close this issue due to a few months of inactivity.  Please feel free to reopen if you are still experiencing this issue.
