### ISSUE TITLE
A class which just inherited Brain shows different inspector options in Unity editor

### ISSUE THREAD

**Issue by macgebi** [Unity-Technologies/ml-agents#1139]
Hi, recently I tried to inherit  Brain class without any modification just to give a different brain name to mine.
But it showed different options from the original Brain in inpector window of Unity editor.

Not only the sequence of options, the item is different.
(Core Brain, broadcast, key and axis actions)

![image](https://user-images.githubusercontent.com/6808677/44698283-47cc2400-aaba-11e8-81b2-258d9d9bd16e.png)

**Comment by jo3w4rd** [comment]
The Unity Editor allows you to customize the Inspector dialog for a component. These scripts can be found in the ml-agents/editor folder. In this case, the editor script is BrainEditor.cs.

**Comment by macgebi** [comment]
@jo3w4rd Thank you. I’ll look into the code.
