### ISSUE TITLE
Controlling start/stop in the game

### ISSUE THREAD

**Issue by Ina299** [Unity-Technologies/ml-agents#1140]
Hi, I try Unity ML-agent and get a problem.
I wanted to start learning when I push a joystick button in the game.
But learn.py only starts learning when the Unity Editor's play button.
I wanted to do this because I want to arrange the learning environment in the game.
Do you have any idea to start/stop learning in the game?
Best Regards,

**Comment by MarcoMeter** [comment]
Can't you just "arrange" everything using the Start() event function?

**Comment by Ina299** [comment]
I want to arrange "during the game play", so I cant do it in Start().
Well, I know, my use case is really rare...
What I do is in this video https://www.youtube.com/watch?v=kHsYElp78Uk
All learning processes run at my video start but I hide it by editing transform.position of agents.
Agents are actually falling down at the video start and this is not good when this is more difficult state(using visual feature or something).
Another possible solution will be assigning agents dynamically, but I guess it is also impossible currently.

**Comment by mmattar** [comment]
Hi @Ina299 - I don't believe this is supported as the learning process assumes that the engine can be sped up and there is no need for human interaction. Can you clarify what you mean by arranging the learning environment?

**Comment by Ina299** [comment]
Next video will be vrchat world like environment and there can be some gimmicks I can change during the game.
For example, I want to stop learning when I move floors in mario like stage.
I want to do this during the game because I want to try this on youtube live in future.(not video clip)
My avatar body will reset position if I stop the editor and arrange the game out of the game.
And there is another problem, I can not speed up the learning process during the game.
(So currently, Start/Stop/Speed up require editor stop and start)
I believe my problem will solve if python script can attach to running game.

By the way, in the future, I plan to make a game which interacts with human. 
I think that it can be done without any code modification. (it cannot speed up but I think that is not the problem)

**Comment by mmattar** [comment]
Thanks for sharing the additional context. As mentioned above, we don't currently support this, but will keep this request in mind for future iterations.

**Comment by mmattar** [comment]
Closing this issue for now - we've logged this request into our backlog.
