### ISSUE TITLE
Load model clarification

### ISSUE THREAD

**Issue by mplantady** [Unity-Technologies/ml-agents#116]
Hi,

Just a quick question about the load_model parameter.

What is the difference between doing a long consecutive training, or many short ones with reloading  the previous saved model each time (assuming cumulative steps are similar in the end) ?

The learning rate curve seems to bump at each reloading. But I'm wondering if it makes any difference in the training ?

Thanks!

**Comment by awjuliani** [comment]
Hi @mplantady,

The learning rate is set to linearly decrease over the course of a training session. By reloading the model with the same `max_steps`, the learning rate should be set to what it was at the last save model. Unless you are increasing the `max_steps`, it should be the case that the learning rate is reset to the same value as before.
