### ISSUE TITLE
Unloading broken assembly Assets/ML-Agents/Plugins/Android/TensorFlowSharp.Android.dll, this assembly can cause crashes in the runtime' error .

### ISSUE THREAD

**Issue by skywalker78** [Unity-Technologies/ml-agents#1165]
Hello ,

Im trying to build tensorflow on android using the TensorFlow plugin for unity and it wouldnt build or even load ,and keep throwing the error 'Unloading broken assembly Assets/ML-Agents/Plugins/Android/TensorFlowSharp.Android.dll, this assembly can cause crashes in the runtime' error .'
Im using unity 2018.2.6f1 and tried with the previous version ,same error .It is really annoying ,can you anyone help with that ?

**Comment by xiaomaogy** [comment]
This is a repost of the same issue https://github.com/Unity-Technologies/ml-agents/issues/979, please refer in that post. I will close this for now.
