### ISSUE TITLE
Providing PreBuilt Binaries for Linux

### ISSUE THREAD

**Issue by Davidnet** [Unity-Technologies/ml-agents#119]
Hi everyone!

I was wondering if it were possible to put some prebuilt binaries for linux, It is not possible for me to do the unity builds since I do not own either a windows or mac machine. 

Thank you, and keep up the good work.

**Comment by awjuliani** [comment]
Have you tried the Linux Unity Editor? https://forum.unity.com/threads/unity-on-linux-release-notes-and-known-issues.350256/

**Comment by mmattar** [comment]
Hi @Davidnet, we're closing this out due to inactivity. We've also since released v0.3, so please create a new issue if you run into any additional problems.
