### ISSUE TITLE
SIGALRM not present in windows

### ISSUE THREAD

**Issue by Jaleyhd** [Unity-Technologies/ml-agents#12]
How do you run the model in ubuntu and unity in windows? SIGALARM signal is not present in windows. After I disabled the 30 second signal for raising execption, it still doesn't seem to be working. In Jupyter, it seems to not leave control, however, The build seem to load.
Bellow is the line, 
env = UnityEnvironment(file_name=env_name)

**Comment by Maximus-CZ** [comment]
Fixed by getting rid of Signal: 4958f04

**Comment by anktplwl91** [comment]
I tried the above fix, but following exception shows up?
![screenshot-2017-9-21 ppo](https://user-images.githubusercontent.com/13707940/30689020-5b0d9a92-9edd-11e7-8e67-784e645d1f34.png)
