### ISSUE TITLE
No episode was completed since last summary. - Shows indefinitely after implementing a committed bug fix

### ISSUE THREAD

**Issue by sam-ulrich1** [Unity-Technologies/ml-agents#1208]
No matter what my max step is set for (agent or academy) I receive a "No episode was completed since last summary." every 1000 steps. This followed after implementing a committed bug fix ([Fix bug 1040] (#1062) - https://github.com/Unity-Technologies/ml-agents/commit/40365ded71c5bf94c79c7b94e75fe52623935261). I have also verified that I am rewarding the agents (both positive and negative).

**Comment by sam-ulrich1** [comment]
Updated to version 0.5 instead of trying to fix 0.4. Works great now.

**Comment by awjuliani** [comment]
Glad you got it working!
