### ISSUE TITLE
Not all Environments connecting when running multiple concurrent training sessions.

### ISSUE THREAD

**Issue by greatscots** [Unity-Technologies/ml-agents#1212]
When starting multiple concurrent training sessions (e.g. --num-runs=6), some Unity Instances are unable to connect to python.
![screen](https://user-images.githubusercontent.com/8713282/45423763-8c4be800-b694-11e8-8178-d571461dfdb9.jpg)

As seen in the image, Assembly-0 and Assembly-1 are not connected and give no results.

Using time.sleep(5) after starting a new process in learn.py helped.

**Comment by MarcoMeter** [comment]
Couldn't reproduce this issue on Ubuntu Server using --no-graphics flag.
Reproduced it on Windows.

**Comment by awjuliani** [comment]
Hello,

This has been addressed in v0.6.0 of ML-Agents.
