### ISSUE TITLE
mlagent trainer always stops when I got to step 50000

### ISSUE THREAD

**Issue by ezio008** [Unity-Technologies/ml-agents#1214]
<img width="1680" alt="captura de pantalla 2018-09-12 a las 16 50 31" src="https://user-images.githubusercontent.com/19394314/45433243-076cc880-b6ac-11e8-9264-afd1e50c5eb0.png">

I have been following this tutorial: [Making a New Learning Environment](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md)

I followed all the steps and everything works perfectly, except for one thing, when it reaches step 50000 the play mode stops. I've looked if I had something different to the tutorial, but it's all the same.

Forgive my English, I used the translator to streamline things, I'm Spanish ;)

**Comment by dericp** [comment]
Hi Ezio,

Happy to see that you're trying out v0.5! The `mlagents-learn` command requires you pass the config file as a positional argument. You might notice that you're passing `config/trainer_config.yaml` as instructed in the documentation. In our [provided configuration file](https://github.com/Unity-Technologies/ml-agents/blob/master/config/trainer_config.yaml), `max_steps` is set by default to `50,000`. If you want to train for more steps, increase this number, or better yet, create your own custom trainer configuration file and pass that to `mlagents-learn`.
