### ISSUE TITLE
Strange Error after migrate my project from 0.4 to 0.5 ML-Agents

### ISSUE THREAD

**Issue by icaro56** [Unity-Technologies/ml-agents#1215]
In the console is shown only this: Unsupported type vector. 

It happens in the editor, the time we change the type of brain.

But everything works normally.

**Comment by vincentpierre** [comment]
I have never seen this. Is there a line number associated we could look into ? Does this error appear only once or is it consistently happening ?
What version of Unity are you using ?

**Comment by icaro56** [comment]
It is only a error/warning. I am using the new Unity version (2018.2.7f1).

All the time that we change the brain type the error occurs.

**Comment by vincentpierre** [comment]
When you click on the error in the console, it should give you stack trace, could you paste it here ?

**Comment by icaro56** [comment]
Only this message is displayed without track trace.

**Unsupported type vector.**

**Comment by vincentpierre** [comment]
This is very strange. Apparently, this kind of error is deep into the Editor and I think it might be due to the serialization of the Brain in the scene. Could you try:
 1. Removing the Brain Component
 2. Saving the scene
 3. Closing Unity
 4. Re-adding the Brain component
 5. Re-saving the scene

**Comment by icaro56** [comment]
@vincentpierre . You are right. For new brains, this error does not occur.
