### ISSUE TITLE
Use tensorforce algorithm with Unity

### ISSUE THREAD

**Issue by SestoAle** [Unity-Technologies/ml-agents#1229]
Hi,

I'm trying to create some models with tensorforce algorithms. I managed to do the training step but i can't import my tensorforce model to Unity. I froze the graph, set the brain to internal and specified the name of the output node of the graph, but Unity still raise the error:

UnityAgentsException: The tensorflow graph needs an input for ppo/state-state  of type DT_FLOAT
MLAgents.CoreBrainInternal.DecideAction (System.Collections.Generic.Dictionary`2[TKey,TValue] agentInfo) (at Assets/ML-Agents/Scripts/CoreBrainInternal.cs:400)
MLAgents.Brain.DecideAction () (at Assets/ML-Agents/Scripts/Brain.cs:237)
MLAgents.Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:584)
MLAgents.Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:610)

I tried to set Vector Observation Name = ppo/state-state in Unity, but then a got the error

UnityAgentsException: The tensorflow graph needs an input for ppo/deterministic  of type DT_BOOL
MLAgents.CoreBrainInternal.DecideAction (System.Collections.Generic.Dictionary`2[TKey,TValue] agentInfo) (at Assets/ML-Agents/Scripts/CoreBrainInternal.cs:400)
MLAgents.Brain.DecideAction () (at Assets/ML-Agents/Scripts/Brain.cs:237)
MLAgents.Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:584)
MLAgents.Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:610)

**Comment by SestoAle** [comment]
Ok i managed to resolve the error editing the CoreBrainInternal script adding a new Input called pop/deterministic. 

I changed also the line:

long[,] output = networkOutput[0].GetValue() as long[,];

to

long[] output = networkOutput[0].GetValue() as long[];

because my net returns a one-dimensional array, and i can't understand why the ml-agents net returns a two dimensional array: what is the first dimension?

**Comment by awjuliani** [comment]
Hi @SestoAle,

The two dimensions correspond to the batch size and the length of the action space.
