### ISSUE TITLE
The API number is not compatible between Unity and python.

### ISSUE THREAD

**Issue by ljyda214** [Unity-Technologies/ml-agents#1232]
hi everyone

when i used new version of mlagents, i had a exception like this.

mlagents.envs.exception.UnityEnvironmentException: The API number is not compatible between Unity and python. Python API : API-5, Unity API : API-4.
Please go to https://github.com/Unity-Technologies/ml-agents to download the latest version of ML-Agents.

i use unity 2018.2.7f1 and i install new version of mlagents already.

what is problem in this exception?

**Comment by MarcoMeter** [comment]
You are using ml-agents v0.5 on the Python side, but the Unity ml-agents version is still on v0.4. So you have to update your Unity project to ml-agents version 0.5.

**Comment by eshvk** [comment]
Hey @ljyda214, the solution @MarcoMeter suggested should work for you. Please let us know if it does and we can close the issue.

**Comment by ljyda214** [comment]
thank you for replying my question @MarcoMeter @eshvk 
I solved my problem to update unity to ml-agents version.
so you can close the issue :D

**Comment by wwxFromTju** [comment]
Hi, @eshvk 
How to built a env with API-4?

I want to build more easy(old) env, which obs is more easy than now env. 

For example, the obss of the previous Push Block is the x, y coordinate. The Vector Observation space of the Push Block: (Continuous) 70 variables corresponds to 14 ray-casts each detecting one of three possible objects (wall, goal, or block). It's a lot harder, so I want to know how do I build out the previous environment to use?

thx !

**Comment by ZeratuuLL** [comment]
Hello,

I am quite new to Unity and I met the same problem. I have the latest version of ml-agents so I guess I should update my Unity. But I cannot find anyway to update it.... Is there a solution? Thank you!

**Comment by JunaidRana** [comment]
I have same error...Need help



UnityEnvironmentException: The API number is not compatible between Unity and python. Python API : API-4, Unity API : API-8.
Please go to https://github.com/Unity-Technologies/ml-agents to download the latest version of ML-Agents.
