### ISSUE TITLE
tensorflow-lite support or lightweight version plans?

### ISSUE THREAD

**Issue by g82** [Unity-Technologies/ml-agents#1241]
Hello! I'm developing with ml-agent to implement a iOS multiplayer AI Bot.
I have no background knowledge of Tensorflow or machine learning things, but I was able to make a nice movement Bot in short time with ml-agents. I'm very impressive that.

My goal is to put pretrained model file into the game using Brain internal mode of the provided SDK.
However, the problem is that size of the tensorflow binary(**libtensorflow-core.a**) is huge.

There are 3 Questions.

### 1. Why tensorflow iOS binary is big & Android binary is small?
android **libtensorflow.so** file is only **14.2MB**,
but iOS **libtensorflow-core.a** files is almost **280MB**.(it's one architecture file size, provided original file was 1.39GB with all architecture)
I wonder why the size difference so huge between Android and iOS.

### 2. Is there anything else I can try to reduce binary size?
My game support only the ARM64 in iOS, so I tried to build only ARM64 arch.
I used **build_all_ios.sh** with [selectively register](https://github.com/tensorflow/tensorflow/blob/9590c4c32dd4346ea5c35673336f5912c6072bf2/tensorflow/contrib/makefile/README.md#optimization) options.
My ml-agent trained model file(.pb) uses 59 types Ops(I chekced ops_to_register.h after analysis)
So I tried this build, result was **libtensorflow-core.a**(arm64) **280MB -> 163.6MB**. (I did not test for actual working.)
but it was still big.

### 3. Is there tensorflow-lite support or lightweight version plans?
I know tensorflow-lite is is very small and mobile friendly, but I wonder if it is compatible with all the Ops used in Unity-ML. If it's not a Tensorflow-lite, I wonder if a lightweight version is planned in the future.

I will submit this question to Tensorflow pages too.
Thank you all of Unity-ML Team! 😄

**Comment by eshvk** [comment]
Hi @g82, some of the work in making a lightweight version is on our long term roadmap. We will  communicate as and when it becomes available.

**Comment by eblabs** [comment]
Hi, 
Any updates on this? The libtensorflow-core.a file is nearly 500mbs and I cant even check it into my regular github repo. Thanks for any advice!
Eric

**Comment by vladimiroster** [comment]
Hi Eric,
We're hard at work in finishing up an initial version of our internal inference engine, that will have no dependency on other high level libraries (such as tensorflow, coreml and tensorflow-lite). Due to that, we're not currently investing in integrating with tensorflow-lite or optimizing tensorflow binary size.
Please stay put, and relatively soon we'll release our cross-platform inference engine!'

Thanks,
Vlad

**Comment by awjuliani** [comment]
Hi all. We have shipped the inference engine solution in recent versions of ml-agents, and as such I will close this issue.
