### ISSUE TITLE
Custom Training and Inference

### ISSUE THREAD

**Issue by Kugelkopf** [Unity-Technologies/ml-agents#1245]
Hello everyone!

Firstly, I would like to thank you for your work. I think this is a great platform!
I've already started using it and it works like a charm! I read some of the docs to get more insight in the project and understand how it really works, though I still have a lot to do to catch up. I would like to use it for my thesis work and thus I'm really interested in the python API part. I would like to experiment with custom algorithms and create custom environments as well, and later on implement my own.
It would be great to have a tutorial on how to implement a simple reinforcement learning algorithm in python and then set it up so it could be trained and **debugged** in an IDE(e.g. Visual Studio) while following the whole learning process in the editor or on a built app.
Could you tell me if there will be anything like this in the near future or if not could provide me some tips on how to proceed with it?

Thank you in advance!

**Comment by eshvk** [comment]
Hi @Kugelkopf, have you taken a look at our tutorial documents or the [Udacity Deep RL course](https://www.udacity.com/course/deep-reinforcement-learning-nanodegree--nd893)?

**Comment by Kugelkopf** [comment]
Hello @eshvk!
Thanks for pointing it out, it looks great, though i cannot afford it at the moment. Nevertheless I could figure out the python API and it works well. I can now interact with the editor or a custom built environment from a python script and i can even debug it in visual studio. Makes learning easier. However, I'm really excited about the opportunities that Unity can bring into machine learning and what i can bring out of it for my thesis work. For now i'm going with free ML courses and see how it works out for me.

**Comment by mmattar** [comment]
Thank you for your comments @Kugelkopf.  We’ve documented your feedback and will prioritize when appropriate. Closing this issue out.
