### ISSUE TITLE
Using CPU vs GPU in training with ML-Agents

### ISSUE THREAD

**Issue by adam-pociejowski** [Unity-Technologies/ml-agents#1246]
Hello,
I'm using ML-Agents on Windows 10 my hardware is:
CPU: ADM Ryzen 7 1700 Eight-Core Processor 
RAM: 16GB
GPU: NVIDIA GeForce GTX 1060 6GB

I tried using ML-Agents using CPU and GPU 
I activated CUDA support and installed tensorflow-gpu following this guide: 
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation-Windows.md

Surprisingly I had better performace using CPU than GPU. 
I was expecting that using GPU to train would give me better performance than CPU.

To learn i was using script from guide:
`python learn.py ./pushblock/1 --train --run-id=1`

ML-Agents window was not responding for some time after run script using GPU, and training was much slower.

Is there any sense to using GPU instead of CPU to train using ML-Agents? 
Maybe I did something wrong?

**Comment by MarcoMeter** [comment]
Hi @adam-pociejowski 
This PPO implementation is not optimized for the use of a GPU. In general, it is not that easy to optimize Reinforcement Learning for the use of a GPU. So  you are better of with a CPU currently.

**Comment by adam-pociejowski** [comment]
Thanks for fast response!
As you said I will use my CPU.

**Comment by maystroh** [comment]
@MarcoMeter When are you planning to support GPU? I'm wondering because I'm using visual observations which requires GPU capabilities to run the trainings.

**Comment by unityjeffrey** [comment]
Hi @maystroh - can you clarify your ask for GPU support?

**Comment by maystroh** [comment]
Sorry my question was not clear enough. I meant by GPU support to have the PPO implementation optimized for GPU since working with visual observation needs GPU more than CPU, especially if we use use a more complex CNN than the 2 layers CNN (the one implemented so far in the library).

**Comment by 3dalgo** [comment]
When I tried A3C with the same spec. PC as 'adam' except GPU, mine is 1080, CPU was surely faster than GPU. It's clear and natural as A3C uses multi-threads.  In windows 10, even GPU version made some garbage values  in neural weights and was not trainable.
