### ISSUE TITLE
Train on Google Colaboratory - /bin/bash: mlagents-learn: command not found

### ISSUE THREAD

**Issue by louis030195** [Unity-Technologies/ml-agents#1252]
Hey i'm trying to train on Google Colaboratory to speed up the training, i made a notebook:

```
import os

!git clone https://github.com/Unity-Technologies/ml-agents

os.chdir('ml-agents')
# Import binaries
!mv ../evol.zip .
!unzip evol.zip

!pip install -r ./ml-agents/requirements.txt

!mlagents-learn trainer_config.yaml --env=Evol --train

```

I'm getting the error

> /bin/bash: mlagents-learn: command not found

i tried also with 

`
!python3 ml-agents/mlagents/trainers/learn.py trainer_config.yaml --env=Evol --train
`

> Traceback (most recent call last):
  File "ml-agents/mlagents/trainers/learn.py", line 10, in <module>
    from .trainer_controller import TrainerController
ModuleNotFoundError: No module named '__main__.trainer_controller'; '__main__' is not a package

Is it even possible to train there ? (headless mode of couse)

Thanks !

**Comment by MarcoMeter** [comment]
Hi @louis030195 
I suppose you are using Jupyter. What if you just use the integrated terminal 
instead of the notebook?

![terminal](https://user-images.githubusercontent.com/6996955/45895127-9d050800-bdd0-11e8-85df-fdeafd924fb7.png)

**Comment by louis030195** [comment]
@MarcoMeter ??? I'm using Google Colaboratory, can't use terminal here

**Comment by MarcoMeter** [comment]
So you are not using Jupyter?

![jupyter](https://user-images.githubusercontent.com/6996955/45898237-aba3ed00-bdd9-11e8-9596-efb84878c6dd.png)

**Comment by louis030195** [comment]
![screenshot from 2018-09-21 20-09-13](https://user-images.githubusercontent.com/25003283/45898478-5e744b00-bdda-11e8-8ca7-bebdc06c64c6.png)

**Comment by vincentpierre** [comment]
```
import os
!git clone https://github.com/Unity-Technologies/ml-agents
os.chdir('ml-agents')
# Import binaries
!mv ../evol.zip .
!unzip evol.zip
!pip install -e ./ml-agents/ml-agents
!mlagents-learn trainer_config.yaml --env=Evol --train
```

**Comment by louis030195** [comment]
Thanks @vincentpierre ! 

Anyway Colab is lacking Mono or something (I don't really know)

> Debug info from gdb:
> 
> mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb
> 
> =================================================================
> Got a SIGABRT while executing native code. This usually indicates
> a fatal error in the mono runtime or one of the native libraries 
> used by your application.
> =================================================================

**Comment by vincentpierre** [comment]
Did you make sure the environment was build for Linux_x64 and Headless mode selected? I did not try to run an environment maybe Colab and ML-Agents are incompatible.

**Comment by louis030195** [comment]
Yes it runs well on my Ubuntu with headless, probably incompatible with Colab, thanks anyway !

**Comment by IJsLauw** [comment]
Try these steps: https://qiita.com/Rowing0914/items/10627e5c1fc348b5ea36

Works for me (with runtime running local of course)

**Comment by kengorou2014** [comment]
I'm trying this with ml-agents' version v.0.5 and had the same trouble. Strongly hoping this will be fixed...
