### ISSUE TITLE
Can't Train My Agent 

### ISSUE THREAD

**Issue by DavisDauk** [Unity-Technologies/ml-agents#1256]
I have tried training from the editor or from a build, but every time the game boots up and then crashes with this error. I'm probably doing something wrong in the configuration. I'm still really new to this so I don't have a clue what's wrong. 

### **Error from .exe**
INFO:mlagents.envs:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Reset Parameters :

Unity brain name: Brain
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 3
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): [1]
        Vector Action descriptions: ,
INFO:mlagents.envs:Hyperparameters for the PPO Trainer of brain Brain:
        batch_size:     1024
        beta:   0.005
        buffer_size:    10240
        epsilon:        0.2
        gamma:  0.99
        hidden_units:   128
        lambd:  0.95
        learning_rate:  0.0003
        max_steps:      5.0e4
        normalize:      False
        num_epoch:      3
        num_layers:     2
        time_horizon:   64
        sequence_length:        64
        summary_freq:   1000
        use_recurrent:  False
        graph_scope:
        summary_path:   ./summaries/--id=EPQ1-0
        memory_size:    256
        use_curiosity:  False
        curiosity_strength:     0.01
        curiosity_enc_size:     128
Process Process-1:
Traceback (most recent call last):
  File "c:\users\davis\anaconda3\envs\ml-agents\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "c:\users\davis\anaconda3\envs\ml-agents\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\davis\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 47, in run_training
    tc.start_learning()
  File "c:\users\davis\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 368, in start_learning
    value=take_action_value)
  File "c:\users\davis\anaconda3\envs\ml-agents\lib\site-packages\mlagents\envs\environment.py", line 384, in step
    self._n_agents[_b] = len(s[0][_b].agents)
KeyError: 'Brain'

### **Error when trained from the editor**

UnityAgentsException: The Communicator was unable to connect. Please make sure the External process is ready to accept communication with Unity.
MLAgents.Batcher.SendAcademyParameters (MLAgents.CommunicatorObjects.UnityRLInitializationOutput academyParameters) (at Assets/ML-Agents/Scripts/Batcher.cs:83)
MLAgents.Academy.InitializeEnvironment () (at Assets/ML-Agents/Scripts/Academy.cs:320)
MLAgents.Academy.Awake () (at Assets/ML-Agents/Scripts/Academy.cs:227)

**Comment by eshvk** [comment]
@DavisDauk: Is your python setup working fine? It looks like Unity is waiting to communicate with Python because you are using an external brain and hangs on getting no response from Python.

**Comment by xiaomaogy** [comment]
Hi @DavisDauk, the only time we see this error is when there are two Academy in the scene. Can you check if that's what happend?

**Comment by jayeshBaviskar** [comment]
I am Facing the Same Issue.

![untitled_page](https://user-images.githubusercontent.com/5250082/46282975-acceda00-c590-11e8-8df4-f6fffbd60ff4.png)

**Comment by jayeshBaviskar** [comment]
As well My Python Setup is also Working Fine.

![image](https://user-images.githubusercontent.com/5250082/46397137-08bf6d00-c70f-11e8-9d99-628d3dc7c67b.png)

**Comment by xiaomaogy** [comment]
@jayeshBaviskar I think you are facing a different issue because the error message is different, please open another issue and describe the issue in more detail (like which version of ml-agents, which version of Unity, how did you setup everything. )

**Comment by jayeshBaviskar** [comment]
> @jayeshBaviskar I think you are facing a different issue because the error message is different, please open another issue and describe the issue in more detail (like which version of ml-agents, which version of Unity, how did you setup everything. )

@xiaomaogy  Thank you. I will Open separate Issue.

**Comment by deeplearningrobotics** [comment]
I have the same issue with the "Reacher" model. Maybe some setting in the build process was not correct.

**Comment by xiaomaogy** [comment]
Hi @deeplearningrobotics , this error 
```
UnityAgentsException: The Communicator was unable to connect. Please make sure the External process is ready to accept communication with Unity.
```

Can be due to a number of reasons. Please describe your question in more detail (like how you get to this error) under another new issue.

**Comment by xiaomaogy** [comment]
This question is too general and vague, so I will close it to avoid any further confusion.
