### ISSUE TITLE
How to train agents with complicated behaviour?

### ISSUE THREAD

**Issue by m-kul** [Unity-Technologies/ml-agents#1257]
Hello Community,

I am trying to expand on the soccer example for a while now, but no success. I added one more attacker and I want them to be able pass to each other when they need to. I cannot seem to find the right way to do it. I tried reward heavy approach (many different ways) and also sparse reward (curiosity) approach. The agents don't collaborate with each other in any way. 

I also wonder if the agents can learn to find the ball + pass + evade defense players + shooting together? I use a helper method to shoot and pass so that when the signal is pass a method is called to pass to other user and similarly shoots directly to the hoop. So agent doesn't need to learn to aim.

If somebody can give me some guidance on which training type to use and some hyper parameter, I would be very happy.

**Comment by harperj** [comment]
Hi @m-kul, unfortunately the ml-agents project maintainers are unable to support development of custom environments.  We welcome community discussion, but it looks like this issue has been inactive for more than 30 days so I'm going to close it.
