### ISSUE TITLE
send more data from unity to python

### ISSUE THREAD

**Issue by YuMurata** [Unity-Technologies/ml-agents#1258]
Hi community.

I want to send more data from unity to python by rpc.
I think i have to edit .proto file and compile it.
Where are .proto files?

**Comment by awjuliani** [comment]
Hi @YuMurata,

The protobuf definitions are available here: https://github.com/Unity-Technologies/ml-agents/tree/master/protobuf-definitions.

**Comment by YuMurata** [comment]
thanks !
