### ISSUE TITLE
use Max Step with external Brain only

### ISSUE THREAD

**Issue by ffrige** [Unity-Technologies/ml-agents#1263]
Shouldn't the MaxStep parameter of the Academy only be used during training and not during inference? I tested with internal and player mode and in both cases the games resets when reaching max steps. I don't see why that would be the case?

**Comment by vincentpierre** [comment]
We let MaxStep be effective in both training and inference so it is easy to see its impact on the environment. If we made it only active in training, it would be very hard to debug with a Player Brain when testing the scene. But you are right, maxStep is only useful at training time.

**Comment by nathanvogel** [comment]
Is there any way we can programmatically set the max steps property of academy objects at runtime? AgentParameters.maxStep is public, but not Academy.maxSteps.

Even if having the Academy reset in "test mode" is indeed useful, I'm constantly switching between "game mode" and "training mode".
