### ISSUE TITLE
protobuf-definitions/make.bat for windows

### ISSUE THREAD

**Issue by YuMurata** [Unity-Technologies/ml-agents#1266]
hi.

i ran protobuf-definitions/make.bat with windows, but it didnt run correctly.
so, i recoded it for windows.
can i do PR ?

**Comment by xiaomaogy** [comment]
@YuMurata Thanks for the contribution. That script was only intended for Mac or Linux and it would be nice if you have something that works for Windows. Just remember to issue the PR against 'develop' branch.

**Comment by YuMurata** [comment]
I create PR.

I dont know whether I could create PR, because I have never crated PR.
Please tell me after confirming PR.

Thanks !

**Comment by harperj** [comment]
Closing this since your PR was merged.  Thanks for the contribution!
