### ISSUE TITLE
no matter what i download or try i cannot run anything that uses the mlagents module

### ISSUE THREAD

**Issue by zachcc99** [Unity-Technologies/ml-agents#1267]
from mlagents.envs.environment import UnityEnvironment
ModuleNotFoundError: No module named 'mlagents'
that is the error i get every time and i have searched through almost every notebook and github thread and i cant find anything. please help

**Comment by zachcc99** [comment]
> @zachcc99 I think maybe you haven't installed the mlagents python package correctly. Have you done 'pip install .' within the mlagents/ml-agents/ directory (the directory that contains requirements.txt)?

i  went to C:\ml-agents-master\ml-agents which contained requirements.txt then typed pip install/ pip install ml-agents. neither worked any other ideas

**Comment by zachcc99** [comment]
ya i just relised how to do it but i can only run it in my pycharm terminal which was confusing me. kind of annyoing that i can run it in the normal way but ill live. thanks you so much

**Comment by zachcc99** [comment]
on another note where would be a good place to start learning how to use the toolkit

**Comment by xiaomaogy** [comment]
The best place is our documentation, the installation guide and the basic guide.

**Comment by JunaidRana** [comment]
have resolved this using this command.

from mlagents.envs import UnityEnvironment

**Comment by TheStoneMX** [comment]
worked for me 
pip install unityagents
