### ISSUE TITLE
No internal option for brain in 3DBall

### ISSUE THREAD

**Issue by adnphllps** [Unity-Technologies/ml-agents#127]
For the 3DBall example, at the "Embedding the trained model into Unity" step, I don't have the option to select an internal brain.  Adding the flag "ENABLE_TENSORFLOW" via the inspector didn't seem to work so I added it manually to the ProjectSettings.asset file as:

```
  scriptingDefineSymbols:
    1: ENABLE_TENSORFLOW
```

I am running the notebook and its requirements in a virtualenv. The previous steps, and training seemed to work as expected. 

A minor note: The object is named Ball3DBrain in the scene inspector, but in the instructions it is referred to as "3DBallBrain".

Using ver: 2017.2.f03. Personal Mac

![image](https://user-images.githubusercontent.com/1544500/32358144-c70cb392-c019-11e7-9440-890afdc3b57e.png)

**Comment by liuyihunter** [comment]
i think the easiest way to fix it is directly modify the code in "Brain.cs"
you just need to remove "#if ENABLE_TENSORFLOW"

/------------------------------------------------
#if ENABLE_TENSORFLOW   
public enum BrainType
{
    Player,
    Heuristic,
    External,
    Internal
}
/---------------------------------------------------

**Comment by adnphllps** [comment]
Thanks. I commented the if block and left the enum and it works.

**Comment by vincentpierre** [comment]
Did you make sure you had the ENABLE_TENSORFLOW in the ight target platforms in the scripting defined symbols? You might need to click anywhere inside the inspector to make sure the scripting defined symbols are saved. make sure you do this for the Settings for PC, Mac & Linux Standalone. removing `#if ENABLE_TENSORFLOW` should be the exact same thing as having ENABLE_TENSORFLOW in the scripting defined symbols.

**Comment by weiweitoo** [comment]
@awjuliani I am using ml-agent v0.8. I cannot find the choice for creating an internal brain as well.

**Comment by weiweitoo** [comment]
Solved. Just figure out that can import the .nn model and assign it into learning brain. Then run it with --slow flag

**Comment by xiaomaogy** [comment]
Nice, what went wrong before?

**Comment by weiweitoo** [comment]
Not sure what is the problem. But I guess is because internal brain feature is replaced with learning brain in the new update?

**Comment by xiaomaogy** [comment]
Yes it is.
