### ISSUE TITLE
Can't get to training

### ISSUE THREAD

**Issue by TaiPrev** [Unity-Technologies/ml-agents#1273]
After installing ml-agents step by step, opening the demo unity project and building only with the 3DBall scene (brain set to external) I'm trying to test the training from the python scripts. However, I find myself with the next error when trying to do so in the anaconda prompt enviroment and with the following command:

> (ml-agents) C:\...\Unity ML_agents>python ml-agents-master\ml-agents\mlagents\trainers\learn.py "Unity Environment.exe" --train
Traceback (most recent call last):
  File "ml-agents-master\ml-agents\mlagents\trainers\learn.py", line 10, in <module>
    from .trainer_controller import TrainerController
ModuleNotFoundError: No module named '__main__.trainer_controller'; '__main__' is not a package

[For clearence, my Unity executable is in the same Unity ML_agents directory, the master of the original project is kept in a subfile named "ml-agents-master", in which nothing has been changed.]

Is this an already solved issue, a mistake on my part or something that hasn't been detected before?

Edit: The same issue has arised when testing with the scene 3DBallHard instead of the 3DBall in another build.

Edit2: The error has disappeared after changing lines 10 & 11 of learn,py to this:

> from trainer_controller import TrainerController

> from exception import TrainerError

However, it doesn't seem to do anything after this, I was expecting for it to launch the unity build and run the ML process from the external trainers.

Edit3:
Now using the following command:

> mlagents-learn ml-agents-master\config\trainer_config.yaml --env="Unity Enviroment" --train

However, it won't recognize the Unity executable's name as a valid enviroment. This problem persists be it the filename with .exe or .app after it.

The complete terminal text is the following:

> (ml-agents) C:\Users\Tai\Desktop\UNI\CURSO 18-19\ATAI\Unity ML_agents>mlagents-learn ml-agents-master\config\trainer_config.yaml --env="Unity Enviroment.exe" --run-id=cob_1 --train

                        ▄▄▄▓▓▓▓
                   ╓▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
          ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
          ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓▌
                        ¬`▀▀▀█▓

> INFO:mlagents.trainers:{'--curriculum': 'None',
> '--docker-target-name': 'None',
>  '--env': 'Unity Enviroment.exe',
>  '--help': False,
>  '--keep-checkpoints': '5',
>  '--lesson': '0',
>  '--load': False,
>  '--no-graphics': False,
>  '--num-runs': '1',
>  '--run-id': 'cob_1',
>  '--save-freq': '50000',
>  '--seed': '-1',
>  '--slow': False,
>  '--train': True,
>  '--worker-id': '0',
>  '<trainer-config-path>': 'ml-agents-master\\config\\trainer_config.yaml'}
> Process Process-1:
> Traceback (most recent call last):
>   File "c:\users\tai\anaconda3\envs\ml-agents\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
>   File "c:\users\tai\anaconda3\envs\ml-agents\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
>   File "c:\users\tai\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 46, in run_training
    docker_target_name, trainer_config_path, no_graphics)
>   File "c:\users\tai\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 101, in __init__
    no_graphics=no_graphics)
>   File "c:\users\tai\anaconda3\envs\ml-agents\lib\site-packages\mlagents\envs\environment.py", line 58, in __init__
    self.executable_launcher(file_name, docker_training, no_graphics)
>   File "c:\users\tai\anaconda3\envs\ml-agents\lib\site-packages\mlagents\envs\environment.py", line 181, in executable_launcher
    .format(true_filename))
mlagents.envs.exception.UnityEnvironmentException: Couldn't launch the Unity Enviroment environment. > Provided filename does not match any environments.

> (ml-agents) C:\Users\Tai\Desktop\UNI\CURSO 18-19\ATAI\Unity ML_agents>

**Comment by xiaomaogy** [comment]
Hi @TaiPrev Did you actuall name your environment "Unity Enviroment"? Maybe try some name without the space. Also you don't need to provide .exe.

**Comment by TaiPrev** [comment]
After some more digging and changing a few things it runs appropiately. Sorry if this whole issue seemed unnecesary or bothersome.
