### ISSUE TITLE
Can't train(windows10-cpu)

### ISSUE THREAD

**Issue by xiaozhuzhuzhu** [Unity-Technologies/ml-agents#1275]
I upgraded from 04 to 05. I installed mlagents first and then run ‘mlagents-learn config / trainer_config.yaml --env = 3DBall --train‘ according to the above URL https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Migrating.md. But after running, the training didn't start and there was no error, so I don't know where I went wrong.
![image](https://user-images.githubusercontent.com/23623240/46195984-62ebb700-c338-11e8-9714-a23de3178d54.png)

Also, the documentation should be changed here to ml-agents instead of python in URL https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Migrating.md .
![image](https://user-images.githubusercontent.com/23623240/46196011-77c84a80-c338-11e8-9a1d-4bb9c1c28bae.png)

**Comment by Phantomb** [comment]
Don't add the `--env` if you're training from inside the unity editor. 

Not sure if that's where it went wrong for you, but might be. Let me know!

**Comment by xiaomaogy** [comment]
I think you should run this command within the root folder that contains the config folder, instead of under the sub ml-agents folder, which doesn't contain the config folder. (We know this might confuse people, and we had some debates on this, but this is something we end up with due to other reasons).

**Comment by xiaozhuzhuzhu** [comment]
Thank you all
My problem is solved. 
![image](https://user-images.githubusercontent.com/23623240/46592308-f620ab80-caf3-11e8-8438-817535d14c26.png)

I logdir to the master folder as described in @xiaomaogy . In addition, I have another error that the sense file is opened for the tennis sense, but the save is 3Dball.exe (not 3DBall), and the "../envs/3DBall" is not modified in the jupterbook.
