### ISSUE TITLE
Agents gets stuck after first reset

### ISSUE THREAD

**Issue by m-kul** [Unity-Technologies/ml-agents#1276]
Hello All,

When I start training everything goes alright without any errors and the agent starts running around. Then they slow down and stop. After first reset, agent stops moving totally. It keeps still on the primary position. Reset On Done continues reseting after 1000 steps but the agents won't move again. Also it looks like it is training on the terminal window. What might be the reason for this?

Edit: I am using discrete action space with 7 actions. I tried examples from UnitySDK and they are working fine. When I test it on Player mode, everything is also OK.

**Comment by majausone** [comment]
Maby you are giving 0 of reward and then he dont want to work more?

**Comment by m-kul** [comment]
@majausone The rewards are working fine. Any other idea?

**Comment by majausone** [comment]
what is the goal of your agent? what conditions of reward do you have? maby negative reward for moving or by time? i dont know...

**Comment by m-kul** [comment]
@majausone I am using only positive reward when the agents finds the ball and takes it to the goal.

**Comment by majausone** [comment]
but the agent recieve this reward or dont have time to do this?
reset in 1000 steps are few steps to do this... put the ball very near of your agent in the start and put more steps like 5000, and lets see..

**Comment by m-kul** [comment]
@majausone I have found the problem. It keeps giving the same signal after a point which is shoot. Shoot works if the agent is close to ball only. So it stops iterating on signals and just gives that signal.

**Comment by m-kul** [comment]
I confirmed that the issue is caused by invalid discrete signal. I restarted the computer, re-wrote the code, reinstalled ml-agents, updated Unity to latest version changed numbers of branches and tried everything I could imagine. Nothing helps.

The issue is if the discrete signal. I set it to 6, so the highest signal I should get is 5 but after a while I get a 6 and keeps getting 6. Please help.

<img width="607" alt="screen shot 2018-09-30 at 19 29 48" src="https://user-images.githubusercontent.com/15053537/46261720-3d50e000-c4e7-11e8-81ee-69b11a7ab9c0.png">


<img width="395" alt="screen shot 2018-09-30 at 19 27 12" src="https://user-images.githubusercontent.com/15053537/46261704-e4814780-c4e6-11e8-9c47-981ee8040030.png">

**Comment by m-kul** [comment]
@xiaomaogy I think this is a bug. How can I get 6 when the branch size is 6? Also it only comes after a while.

**Comment by xiaomaogy** [comment]
I guess you are somehow setting up the multi-discrete control incorrectly. If you want to get help from the community to debug this. You can post your detailed steps to reproduce the bug.

**Comment by m-kul** [comment]
I have found the problem, I was passing float.max value to addvectorobs() which caused the failure silently.
