### ISSUE TITLE
Not able to the Train the Brain with Reinforcement Learning – Due to the Error: The Communicator was unable to connect.  

### ISSUE THREAD

**Issue by jayeshBaviskar** [Unity-Technologies/ml-agents#1286]
Not able to the Train the Brain with Reinforcement Learning – Due to the Error: The Communicator was unable to connect.  

I have set the Brain Type to External 
(Ball3DAcademy -->  Ball3DBrain -->  Brain Type=External)

Selected .NET 4.x Equivalent as a Scripting Runtime Version.
Defined ENABLE_TENSORFLOW flag in Scripting Defined Symbols and  imported TensorFlowSharp plugin in the project

![project settings](https://user-images.githubusercontent.com/5250082/46454039-0c5ffc00-c7c2-11e8-81f6-a753007697a8.JPG)

I tried mlagents-learn command from the root directory. The command is executing successfully. 

![mlagents-learn](https://user-images.githubusercontent.com/5250082/46454033-0538ee00-c7c2-11e8-9d3c-6efe62d38c05.png)

Then I fired `mlagents-learn config\trainer_config.yaml --run-id=firstrun –train` command.
The command returned 

> “Start training by pressing the Play button in the Unity Editor.” 

So I Pressed Play button of my Unity with 3DBall as a loaded scene. 

After Pressing Play Button Unity is displaying the following error Message: 

> UnityAgentsException: The Communicator was unable to connect. Please make sure the External process is ready to accept communication with Unity.
> MLAgents.Batcher.SendAcademyParameters (MLAgents.CommunicatorObjects.UnityRLInitializationOutput academyParameters) (at Assets/ML-Agents/Scripts/Batcher.cs:83)
> MLAgents.Academy.InitializeEnvironment () (at Assets/ML-Agents/Scripts/Academy.cs:320)
> MLAgents.Academy.Awake () (at Assets/ML-Agents/Scripts/Academy.cs:227)

![error](https://user-images.githubusercontent.com/5250082/46454030-fe11e000-c7c1-11e8-9ce4-c0207f6ef104.JPG)

![detailed error](https://user-images.githubusercontent.com/5250082/46454025-f8b49580-c7c1-11e8-97f2-2b025319ccda.JPG)

I am using Following components: 
Unity Version: 2018.2.2f1
Visual Studio 2015 with.NET Framework 4.7.1
My C# Project’s csproj File is using 6 as a LangVersion

conda 4.5.11 (Anaconda)  with Python 3.6.6

These are the Packages which I have in my Python Environent: 
_tflow_1100_select        		0.0.2                     eigen
absl-py                   		0.5.0                    py36_0
astor                     		0.7.1                    py36_0
atomicwrites              		1.2.1                    py36_0
attrs                     		18.2.0           py36h28b3542_0
backcall                  		0.1.0                     <pip>
blas                      		1.0                         mkl
bleach                    		1.5.0                    py36_0
ca-certificates           		2018.03.07                    0
certifi                   		2018.8.24                py36_1
colorama                  		0.3.9            py36h029ae33_0
cycler                    		0.10.0           py36h009560c_0
decorator                 		4.3.0                     <pip>
defusedxml                		0.5.0                     <pip>
docopt                    		0.6.2                    py36_0
entrypoints               		0.2.3                     <pip>
freetype                  		2.9.1                ha9979f8_1
gast                      		0.2.0                    py36_0
grpcio                    		1.11.1                    <pip>
grpcio                    		1.12.1           py36h1a1b453_0
html5lib                  		0.9999999                py36_0
icc_rt                    		2017.0.4             h97af966_0
icu                       			58.2                 ha66f8fd_1
intel-openmp              		2019.0                      118
ipykernel                 		5.0.0                     <pip>
ipython                   		7.0.1                     <pip>
ipython-genutils          		0.2.0                     <pip>
ipywidgets                		7.4.2                     <pip>
jedi                      			0.12.1                    <pip>
Jinja2                    		2.10                      <pip>
jpeg                      		9b                   hb83a4c4_2
jsonschema                		2.6.0                     <pip>
jupyter                   		1.0.0                     <pip>
jupyter-client            		5.2.3                     <pip>
jupyter-console           		5.2.0                     <pip>
jupyter-core              		4.4.0                     <pip>
kiwisolver                		1.0.1            py36h6538335_0
libpng                    		1.6.34               h79bbb47_0
libprotobuf               		3.6.0                h1a1b453_0
libtiff                   			4.0.9                h36446d0_2
markdown                  		2.6.11                   py36_0
MarkupSafe                		1.0                       <pip>
matplotlib                		3.0.0            py36hd159220_0
mistune                   		0.8.3                     <pip>
mkl                       		2019.0                      118
mkl_fft                   		1.0.6            py36hdbbee80_0
mkl_random                		1.0.1            py36h77b88f5_1
mlagents                  		0.5.0                     <pip>
more-itertools            		4.3.0                    py36_0
nbconvert                 		5.4.0                     <pip>
nbformat                  		4.4.0                     <pip>
notebook                  		5.7.0                     <pip>
numpy                     		1.15.2           py36ha559c80_0
numpy                     		1.14.5                    <pip>
numpy-base                		1.15.2           py36h8128ebf_0
olefile                   		0.46                     py36_0
openssl                   		1.0.2p               hfa6e2cd_0
pandocfilters             		1.4.2                     <pip>
parso                    		0.3.1                     <pip>
pickleshare               		0.7.5                     <pip>
pillow                    		5.2.0            py36h08bbbbd_0
pip                       			18.0                      <pip>
pip                       			10.0.1                   py36_0
pluggy                    		0.7.1            py36h28b3542_0
prometheus-client         		0.3.1                     <pip>
prompt-toolkit            		1.0.15                    <pip>
protobuf                  		3.6.0            py36he025d50_0
py                        			1.6.0                    py36_0
Pygments                  		2.2.0                     <pip>
pyparsing                 		2.2.0                    py36_1
pyqt                      		5.9.2            py36h6538335_2
pytest                   		3.8.1                    py36_0
python                    		3.6.6                hea74fb7_0
python-dateutil          		2.7.3                    py36_0
pytz                      		2018.5                   py36_0
pywinpty                  		0.5.4                     <pip>
pyyaml                    		3.13             py36hfa6e2cd_0
pyzmq                     		17.1.2                    <pip>
qt                        			5.9.6            vc14h1e9a669_2
qtconsole                 		4.4.1                     <pip>
Send2Trash                		1.5.0                     <pip>
setuptools                		40.2.0                   py36_0
simplegeneric             		0.8.1                     <pip>
sip                       			4.19.8           py36h6538335_0
six                       			1.11.0                   py36_1
sqlite                    		3.25.2               hfa6e2cd_0
tensorboard               		1.7.0                     <pip>
tensorflow                		1.7.1                     <pip>
termcolor                 		1.1.0                    py36_1
terminado                 		0.8.1                     <pip>
testpath                  		0.4.1                     <pip>
tk                        			8.6.8                hfa6e2cd_0
tornado                   		5.1              py36hfa6e2cd_0
traitlets                 		4.3.2                     <pip>
vc                        			14.1                 h0510ff6_4
vs2015_runtime            		14.15.26706          h3a45250_0
wcwidth                   		0.1.7                     <pip>
werkzeug                  		0.14.1                   py36_0
wheel                     		0.31.1                   py36_0
widgetsnbextension        	3.4.2                     <pip>
wincertstore              		0.2              py36h7fe50ca_0
yaml                      		0.1.7                hc54c509_2
zlib                      			1.2.11               h8395fce_2

**Comment by xiaomaogy** [comment]
@jayeshBaviskar Have you tried to build the executable, and then provide it the --env to the command line? (refer to this doc https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Executable.md)

**Comment by jayeshBaviskar** [comment]
@xiaomaogy 

Yes, I have also tried with the Executable. 

![2](https://user-images.githubusercontent.com/5250082/46524065-4b1ab280-c8a5-11e8-8d26-2be926ef2dd0.JPG)


Used 
`mlagents-learn config\trainer_config.yaml --env=3dgame\3dgame --run-id=first-run --train`
Command 

But still getting the same Error: 

![issue-1](https://user-images.githubusercontent.com/5250082/46524112-64bbfa00-c8a5-11e8-8428-a791498c2ed4.png)

**Comment by jayeshBaviskar** [comment]
@xiaomaogy 
I found the Issue.
I had assigned HTTP_PROXY and HTTPS_PROXY values in my Environment variables to install python packages. I removed them and now it is working.

**Comment by SharangSharma09** [comment]
@jayeshBaviskar Dear Jayesh, I am exactly in the same situation as you did. 
How do you remove HTTP_PROXY and HTTPS_PROXY values?

**Comment by jayeshBaviskar** [comment]
@SharangSharma09  
I had those variables in my Environment variables, So I removed them.

**Comment by SharangSharma09** [comment]
As I am new to all of this, do you think you can explain to me how to access these environment variables and then debug? I have very limited programming experience
