### ISSUE TITLE
Confusing typo in Python API docs.

### ISSUE THREAD

**Issue by kdbanman** [Unity-Technologies/ml-agents#129]
Under "Interacting with a Unity Environment" in `docs/Unity-Agents---Python-API.md`, this appears:

> **`states`** : A two dimensional numpy array of dimension `(batch size, state size)` if the state space is continuous and `(batch size, state size)` if the state space is discrete.

The dimension tuple `(batch size, state size)` is identical for both continuous and discrete state spaces.  If they are actually different tuples, then the difference should be indicated.

**Comment by vincentpierre** [comment]
Thank you, it should say the array is of dimension `(batch_size, 1)` in the discrete case. I fixed it in the docs.

**Comment by kdbanman** [comment]
Looks good now.  Thanks for the prompt response!
