### ISSUE TITLE
Change config and train_mode in the gym wrapper

### ISSUE THREAD

**Issue by cyrilibrahim** [Unity-Technologies/ml-agents#1290]
Hi, 

I wonder how can I do to change the configuration of the environment with the gym wrapper and how to set train_mode to false? 

Thank you !

**Comment by eshvk** [comment]
Thanks for bringing this. up @cyrilibrahim. Unfortunately, we don't have a nice way of passing those parameters to the gym wrapper. It is on  roadmap and we will let you know once you ship this.

**Comment by eshvk** [comment]
We are going to close this issue for now, if and when it gets prioritized, this feature will be noted in our release notes.
