### ISSUE TITLE
Having trouble synchronizing state/actions

### ISSUE THREAD

**Issue by carlsc2** [Unity-Technologies/ml-agents#1298]
Hello, I'm trying to run some experiments in a simple turn-based world, but I'm running into a number of issues related to keeping things in sync.

I have an academy object which maintains the world state, and 2 agents who take turns doing things. The agents are using on-demand decision making.

This is what I'm trying to do:
1) Agent A spawns. Agent A performs up to N observation-action cycles in a row, modifying the world.
2) Agent B spawns, Agent A waits for Agent B to perform up to M observation-action cycles.
3) If a terminal state is reached, Agent A is issued a reward based on agent B's performance. Agent B is issued a reward based on its own performance. The world is then reset, the agents are destroyed, and the cycle repeats.

My current approach:

All the logic is on my academy object. I need everything to happen in discrete steps, so I have it in the AcademyStep() method. Depending on whose turn it is, I call the RequestDecision() method of that agent. I then check for a terminal state (done=true or steps > N+M)- if the end has been reached, I call Done() on each individual agent.

Agent B's AgentAction() calls the academy's validation method, which will issue rewards / set the done flag on the academy object if the agent completes the task in its turn.

I found that simply calling Done() on the academy itself seemed to make the final reward never reach the agents (I see "No episode was completed since last summary. ").

I've been reading documentation/issues trying to figure this out, but it's really not clear what's going on. Is there some event execution order I should follow or is there some parallelism I need to account for? How should I structure my code to ensure things happen in sequence?

**Comment by carlsc2** [comment]
Regarding the logging above, my questions are:

1) Why isn't the reward being sent to the agents if I call Done() from the academy?
2) Why is AcademyReset() called twice (false reset due to ForcedFullReset())?

**Comment by vincentpierre** [comment]
I made a few experiments with the resetOnDone and the Academy's Done and I have not been able to reproduce your issue. Both the reward and the Done flag are sent successfully. When the Academy is set to Done, all agents in the scene should be set to Done as well (And so complete an episode). What version of ML-Agents are you on ? Did you make sure your agents were present in the scene?

**Comment by carlsc2** [comment]
Thanks for the reply. I am running the latest code (as of a few days ago). Agents are present. All I did was call the academy's Done() function - this propagates to the agents in the scene and calls their AgentOnDone methods, but does not issue a reward to the Python brain. Are you suggesting that I should not call academy.Done() until the agents themselves are done? This sort of inverts the logic I'm trying to achieve (i.e. the academy controls the world state step by step).

The only method I got working was: during academy.AcademyStep(), if terminal state reached, set done flag to true, issue rewards then call AgentA.Done() and AgentB.Done(), and return. Next loop, at the top of academy.AcademyStep(), I have: 
`
if (done) {
    Done();
    return;
}
`

I'm wary of this approach because it essentially creates an extra world loop and I don't know what else is happening under the hood. I'm trying to figure out if things are synchronized properly or if I have hyperparameter issues, since my agents don't seem to be improving at all.

Part of why I'm suspecting logic issues is because if I enable the use of recurrent networks because I get the following error:

`Process Process-1:
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "c:\users\user\appdata\local\programs\python\python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\mlagents\trainers\learn.py", line 47, in
run_training
    tc.start_learning()
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\mlagents\trainers\trainer_controller.py",
 line 371, in start_learning
    take_action_outputs[brain_name])
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\mlagents\trainers\ppo\trainer.py", line 1
96, in add_experiences
    curr_to_use = self.construct_curr_info(next_info)
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\mlagents\trainers\ppo\trainer.py", line 1
75, in construct_curr_info
    memories = np.vstack(memories)
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\numpy\core\shape_base.py", line 234, in v
stack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate`

This error actually happens as soon as Agent B spawns, before any rewards are even issued. Is this because when I use on-demand learning I stop sending signal to Agent A? Or do I have a logical disconnect somewhere?

**Comment by vincentpierre** [comment]
In think the error you get from the trainer is a separate issue. @awjuliani 
The fact that you have to do this extra step is problematic. Could you try to interact directly with the environment with the Python-API, carry a few steps then analyse if the `local_done` flag is set to true at any point. When I tested it, the academy's done flag propagated properly to the agents. In you case it seems neither the done flag nor the reward goes to python (because you have this no episode completed message).
Could you share some code with a minimal (not) working example?

**Comment by carlsc2** [comment]
Well, I stripped down much of my code and now it works, so something weird is happening. I will have to investigate further.
