### ISSUE TITLE
[Feature Request] Can you perform training multiple times within a build?

### ISSUE THREAD

**Issue by ConorZAM** [Unity-Technologies/ml-agents#1299]
I am looking to combine a genetic algorithm with the RL implemented by ML agents.

I was wondering if you are (or will be) working on a way of initiating training in game? I would like to be able to create an agent, train it and evaluate it and then alter the agent over generations to simultaneously find optimal policy and topology for a given task.

If this isn't something you're looking at I'll get cracking, I just don't want to spend the time developing this only to see you release it anyway!

Thanks!

**Comment by bjmolitor** [comment]
You may use mlagents-learn with parameter --load to continue training and you might want to take a look at the curriculum learning guide in the docs folder of this project.

**Comment by awjuliani** [comment]
Due to inactivity, I am closing this issue for now. Please feel free to re-open if you deem it necessary.
