### ISSUE TITLE
The model seems to be changing rewards to strings somehow

### ISSUE THREAD

**Issue by ConorZAM** [Unity-Technologies/ml-agents#130]
I keep getting this error during training:

TypeError                                 Traceback (most recent call last)
<ipython-input-4-ea338ed77184> in <module>()
     38             info = env.reset(train_mode=train_model)[brain_name]
     39         # Decide and take an action
---> 40         new_info = trainer.take_action(info, env, brain_name)
     41         info = new_info
     42         trainer.process_experiences(info, time_horizon, gamma, lambd)

~\Desktop\Machine Learning\ml-agents\python\ppo\trainer.py in take_action(self, info, env, brain_name)
     54         self.stats['learning_rate'].append(learn_rate)
     55         new_info = env.step(actions, value={brain_name: value})[brain_name]
---> 56         self.add_experiences(info, new_info, epsi, actions, a_dist, value)
     57         return new_info
     58 

~\Desktop\Machine Learning\ml-agents\python\ppo\trainer.py in add_experiences(self, info, next_info, epsi, actions, a_dist, value)
     81                     history['action_probs'].append(a_dist[idx])
     82                     history['value_estimates'].append(value[idx][0])
---> 83                     history['cumulative_reward'] += next_info.rewards[idx]
     84                     history['episode_steps'] += 1
     85 

TypeError: unsupported operand type(s) for +=: 'float' and 'str'

**Comment by surferau** [comment]
Did you try to debug it, like 
print(next_info.rewards[idx])
to see whats inside ?

**Comment by vincentpierre** [comment]
Can you give us more details ? Like @surferau suggested, I think printing the value of the reward will help. Also, does this happen right after you start training or does it happen randomly after some time? What kind of environment are you running ? How many agents / brains? Are you using the ppo script or are you using python directly?

**Comment by ConorZAM** [comment]
I'm using the ppo script, I'm sorry but I don't know where I can access the next_into.rewards[idx] from, it's not available to the agents class and that's all I've been working with so far.
It's usually a good hour or so into training that it crops up. I'm running a continuous state and action environment with 6 agents all sharing the same brain. It's nothing especially far from the balance ball example.

**Comment by vincentpierre** [comment]
Interesting, Could you go into ppo/trainer.py line 83 and replace the line 83
```python
history['cumulative_reward'] += next_info.rewards[idx]
```
with 
```python
try:
     history['cumulative_reward'] += next_info.rewards[idx]
except:
     print(next_info.rewards[idx])
     print(next_info.rewards)
```
This way, when the error occurs, the content of reward will be displayed.
Did you modify code on the python side ? 
What is the maximum value for the reward per agent ?

**Comment by ConorZAM** [comment]
I've added the code in and will update you next time it happens.
I've not changed anything on the python side.
The maximum value for reward over an agent's lifetime would be difficult to determine as it reflects their distance travelled from a point, however, my agents never manage to get very far and the mean reward has never gone above 10. (yet!)

**Comment by kwea123** [comment]
I got this error too. It's because the reward in 'NaN' so not a number. I guess it's either you have some invalid math operations in your reward calculation (e.g. division by zero) or some unknown issue of Unity engine (I personally got this without any invalid math operations so...)

To avoid this, I use "if type(reward) is float:" statement to skip these invalid rewards.
Hope this helps.

**Comment by ConorZAM** [comment]
Thanks for the advice, I've actually been making a lot of progress recently and the rewards have been behaving themselves since I posted this issue. I think the NaNs causing it were mainly a result of my environment being a mess and the agents being unable to find anything within them. If I do catch the string I'll let you know.
