### ISSUE TITLE
Saving Numpy/Pytorch Models as Internal Brain

### ISSUE THREAD

**Issue by EmrahErden** [Unity-Technologies/ml-agents#1300]
Hello,

I'm training models with help of **Numpy in Anaconda** (custom NN architectures). May use **PyTorch** in the future, but **not** Tensorflow. 

Can follow the iteration results (via the small pop up window while running code), or print out rewards during training. Also storing the weights in ."p" file using pickle library.

But I can't find a way to **store** the models in extension of type "**.bytes**" , so that I can run them in Unity3d. Can you suggest a practical solution to this problem?

**Comment by harperj** [comment]
At this time we don't have any plans to support PyTorch models as internal brains as part of this project.  We're focusing primarily on developing the feature set on top of Tensorflow in the near future.

This issue has been inactive for more than 30 days so I'm going to close it, but feel free to reopen if you have any additional requests or questions.

**Comment by msaroufim** [comment]
Am wondering if we could revisit this issue? It's just that looking at Pytorch code is just so much easier to understand. There's even a Udacity course where they use Pytorch to train the models using unityagents but AFAIK there's still no way to embed Pytorch code back into Unity.

I'm happy to work on this feature myself if someone on the ML agents team wants to give me some initial guidance on which parts of the codebase I should be touching

**Comment by jkim447** [comment]
Yeah, the option to use PyTorch brains would be GREAT -- in order for that to work, it's just the inputs and the outputs that needs to be correct across TF/Torch platforms -- is that right? 

The work-around for now (if not rewriting the code into TF) is to use the python API to iterate your game action-by-action, where you get the action from the torch model output. However, this is no where near as effective as click-dragging PyTorch .cpkt files to check performance :(

**Comment by msaroufim** [comment]
Another option could be to support ONNX models and then support any DL backend by default
