### ISSUE TITLE
Training time scale

### ISSUE THREAD

**Issue by hejcz** [Unity-Technologies/ml-agents#1301]
Hello, 

I was wondering if there is some reason to set training time scale to something less than 100. As far as I understand no matter what time scale is, an agent will take same amount of actions as with time scale equal to 1.

So if I have 15 seconds timeout for some scene and in this time I would take 1000 actions then with time scale == 100 and agent would take 1000 actions as well before it was timed out. Am I right? It would be just too fast for human player to choose actions with 100 time scale.

So is there any reason to choose let's say 15 or 40 time scale for training?

**Comment by bjmolitor** [comment]
You might want to take a look at the issue I've been having yesterday.

https://github.com/Unity-Technologies/ml-agents/issues/1315

So basically: depending on how complex your enviroment is, it just won't work at timescale 100 a similar way as it does at lower timescales. I suggest pausing a training in unity editor and checking whether the screen has plausible content (like distance and number of objects).
I ended up with a brain that performs well, only on higher timescales.
Also: higher timescale does not shorten the training time considerably (or improve the training result). So actually the ideal timescale for complex enviroments will be much lower then 100. 50 worked for me.
