### ISSUE TITLE
Any chance to get WebGL builds?

### ISSUE THREAD

**Issue by bjmolitor** [Unity-Technologies/ml-agents#1307]
So, I know Tensorflow Sharp does not support WebGL as a target plattform. Any chance it will in the future? Could we possibly run on Tensorflow.js? Any plans in that direction?

And btw: Some sort of error message would be sweet. Currently, if you try to run a WebGL build, it just takes a long time and you end up with an empty folder.

Keep up the great work though! And I hope you can achieve much cooperating with DeepMind.

**Comment by mmattar** [comment]
Hi @bjmolitor - we've released v0.7 of ML-Agents which replaces our TF# with our own internal inference engine. Please give this a go and let us know if it fixes your issue. I'm closing this issue for now, but please submit a new issue if something else comes up.
