### ISSUE TITLE
HyperParameters from a model/summary

### ISSUE THREAD

**Issue by mplantady** [Unity-Technologies/ml-agents#131]
Hi,

Is there already a way to retrieve hyperparameters from a model or a summary ?
I do so much trainings on different machine that I sometimes forget what I have tweaked on it.
If not, I will just add a small log file with all infos in the model directory.

Thanks,
Max

**Comment by surferau** [comment]
you can modify the json generated by python in environment.py and extract the data in ExternalCommunicator.cs

**Comment by vincentpierre** [comment]
@mplantady If by hyperparameters you refer to the ppo training hyperparameters, the bytes file model generated does not contain such information. It just contains the information about the neural network, not on how it was trained. Same goes for the summaries as of right now. You could add the hyperparamters to the summary in tensorflow manually or generate a log file like you suggested.

**Comment by mplantady** [comment]
Thanks that's what I thought!

**Comment by awjuliani** [comment]
Hi @mplantady,

As of 0.2 we save the hyperparameters to tensorboard, so they can be retrieved from their and compared between sessions.
