### ISSUE TITLE
Bug: far worse results with mlagents-learn --slow replay

### ISSUE THREAD

**Issue by bjmolitor** [Unity-Technologies/ml-agents#1315]
Observation: I am controlling a Space Shooter-Type game using ML-Agents (Link below). Problem was that Tensorboard showed an average score of 350 with single episodes going as high as 2000. As internal brains, the Models performed poorly seldomly reaching more then 100 points. After lengthy consideration and evaluation I have included Debug.Log outputs of the average score after so and so many games. That showed, that the last three graphs I trained (PPO, 5 million steps, 3 layers, 512 units) deliver similar results (average of around 50).
If however, I replay the last model, using an external brain, I get an average of 300 points. Just by adding the "--slow" parameter that score goes down to an average of 50 as observed.

Conclusion: It's not a bug in my observations, rewards or actions (three repeated trainings), it's not the training environment (first two where --no-graphics, last was using Unity editor (ran about 12 hours)) - it must be the time scale.

I'd mention, that it's 23:45 and I need it working by tomorrow for very serious reasons... if that would help. If someone would help?

All the project is here: https://github.com/bjmolitor/ML-Space-Shooter/ 

Creating a branch "ml-agents issue" right now, with the situation.

**Comment by bjmolitor** [comment]
To make it more clear: If I run my internal brain and the score is 50 on an average. Just setting the Time.TimeScale from 1 to 100 in the debugger will make it perform with an average score of around 300.

**Comment by bjmolitor** [comment]
OK. I think I figured... There's a plenitude of waits and delays in the code, which are not scaled by Time.deltaTime... Have to say to my defense, that this is actually coding from the Unity Tutorial, which is missing scaling...

**Comment by vincentpierre** [comment]
I am glad to see you managed to resolve your issue.

**Comment by bjmolitor** [comment]
Well... It still behaves differently with TimeScale and falls apart above 70. But maybe other people are more aware of the fact, that they can not run any game at any speed without oddities.

**Comment by awjuliani** [comment]
Hi @bjmolitor,

Unfortunately it is the case that for certain kinds of environments, the results are not consistent between different time scales. This typically has to do with certain physics-based environments, where the physics calculations become inaccurate beyond a certain point of increased time scale.

**Comment by bjmolitor** [comment]
I would also like to add, that (--no-graphics) training with timescale 50 lasts 5 hours as compared to 4 hours 30 minutes with timescale 100 - meaning there seems to be a point were timescale does not speed up the training anymore and a point from where things (like co-processes and waits) get inaccurate.

Thanks for reacting - and reacting so quickly.

**Comment by hejcz** [comment]
@awjuliani

Could you specify which calculations might not be ideal for scaling?

**Comment by awjuliani** [comment]
Hi @hejcz,

It is typically things related to physics calculations such as object collision which degrades in accuracy with increased time.scale. This is because less time is allotted to the physics solver per step, and at some point the time given to the solver isn't enough to accurately determine whether certain objects interact, and what should be the accurate result of that interaction. I hope that helps.

**Comment by bjmolitor** [comment]
I think in my project the problem is caused by coroutines getting out of sync. I suspect, that happens much earlier then collision events not triggering correctly etc.:
If you do `StartCoroutine(SpawnWaves());` and within this method  `WaitForSeconds(spawnWait)`, that will get slower in relation to the main thread. In this case meaning "hazards" would spawn less frequent, making the scenario overall easier. In this way, training in Time.Scale 100, I got a TFModel which did - by far - not perform as good in slow replay as one, which was trained at 70 or 50 - while, as I said, the training did not even last much longer (ca. 15%) at slower Time.Scale.
