### ISSUE TITLE
Unity Can't connect to tensor flow

### ISSUE THREAD

**Issue by thetnswe** [Unity-Technologies/ml-agents#1330]
Getting the annoying **"The brain Ball3DBrain was set to External mode but Unity was unable to read the arguments passed at launch."**

--Python, Anaconda, Tensorflow already setup and jupyter is running.

After that, I am trying to train ball3d scene using editor.

--Activated my environment and browsed to ml-agents-master directory
After that I typed mlagents-learn config/trainer_config1234.yaml
and the command prompt is telling "Start training by pressing the Play button in the Unity Editor."

I hit play in Unity Editor and still getting the annoying **"The brain Ball3DBrain was set to External mode but Unity was unable to read the arguments passed at launch."** message.

After a while I got message " "The Unity environment took too long to respond. Make sure that :\n"
mlagents.envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
         The environment does not need user interaction to launch
         The Academy and the External Brain(s) are attached to objects in the Scene
         The environment and the Python interface have compatible versions." in the command prompt since Unity is not talking to the python and tensorflow..

![mlerror](https://user-images.githubusercontent.com/1559536/46903815-91ed5580-cf00-11e8-96ce-8abd31f70f70.PNG)

Looks like unity is not talking to python and tensorflow. What am I missing? I've been stuck on this for a while and can't find the right answer on the net yet. Please someone help me.

**Comment by vincentpierre** [comment]
This is strange. When doing in editor training, the Academy does not read arguments at all. I do not know how this can happen unless brains are being instantiated after the simulation started. But since you are using a tutorial environment, this should not happen. 
What version of ML-Agents are you using ? Do you have any other error in the console ? If you are using v0.5, could you use Debug.Log statements to try and figure out if the communicator was instantiated correctly ? (In Academy.cs : InitializeEnvironment around line 280) Since you are using In Editor Training, the port should be the default 5005.

**Comment by thetnswe** [comment]
I am using the latest version v0.5 I guess since I downloaded it 4 days ago. There're no other errors in the console. The problem is in Academy.cs script => InitializeEnvironment =>  if (!communicator.CommunicatorHandShake())
        {
            communicator = null;
        }

the CommunicatorHandShake function always returns false and the communicator became null and the error produced. It also happened when I just clicked play button without doing mlagents-learn command.. So looks like the error occurs if there's no communication between tensorflow and Unity.

 I guess that mlagents-learn does nothing to communicate with Unity since it should listen for the unity to communicate with tensorflow when I clicked play in the editor but it doesn't even try to communicate with Unity at all.

![editorerror](https://user-images.githubusercontent.com/1559536/46989623-b6754780-d123-11e8-8cc2-e9e02cc25533.PNG)

**Comment by vincentpierre** [comment]
`CommunicatorHandShake()` was removed in v0.4. I think you have an old version. The Unity Project in 0.5 is under UnitySDK as we removed unity-environment
Could you maybe try cloning in a new repo ?

**Comment by thetnswe** [comment]
Oops.. Now I got it. The problem was that
1 - I downloaded the latest version v0.5
2 - I downloaded the wrong version of tensor flow sharp unity plugins and imported it to Unity so it overwrites to the latest version and everything goes wrong.

Now it's solved and I correctly imported tensor flow plugins and everything works fine.. Thanks Alot :)
