### ISSUE TITLE
previousDistance is never used in Making a New Learning Environment

### ISSUE THREAD

**Issue by eltronix** [Unity-Technologies/ml-agents#1334]
You can confirm the above [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md).

Wondering if this was intentional? Probably not. I suppose the idea was to use `previousDistance` to calculate whether the agent was moving towards the target or not and reward accordingly. Yes?

**Comment by jo3w4rd** [comment]
We've had some internal debate on whether to use previousDistance or not for this example. On the one hand, it does make training faster, on the other, it shouldn't be necessary and is, in some ways, an anti-pattern for setting up rewards. Ideally, you set up your rewards based on achieving the end goal, not achieving intermediate goals. 

Two things that help (which I need to roll into the article) is better randomization of the starting conditions and just a lot more training iterations than you get using the default configuration settings (like 500,000 vs 50,000 steps).

**Comment by theDiverDK** [comment]
Thanks for the clarification.

I have already set max steps to 500k, and ill try to add a better randomization :)

**Comment by theDiverDK** [comment]
There is a little thing in the text as well: 

'For example, the RollerAgent reward system provides a small reward if the Agent moves closer to the target in a step*

Guess that should be removed also.

**Comment by theDiverDK** [comment]
Hi Joe

I noticed something running the training.
At some point the brain decides to be better at failing fast, which also lowers the score, but it does not care about the target at all.
Slowly the rewards gets less negative, but not more than that.

Any ideas?

**Comment by theDiverDK** [comment]
Hi Joe, one last question.

I got it to actually train, by removing time penalty, and use 'SetReward' instead of 'AddReward' inspired by the 3dball.

Is that a good solution?

**Comment by theDiverDK** [comment]
Wow thanks, for the very good explanation :-)

Still trying to learn simple ML.

Do you any good books worth reading, to learn about simple ML?

**Comment by jo3w4rd** [comment]
As a beginner, I found this course to be good:
https://www.coursera.org/learn/machine-learning

In some ways it is a bit dated since everything now seems to be all neural networks all the time, but it does give you a good background for understanding neural networks. It is also free to take.

This course is very similar, but focuses exclusively on neural networks:
https://www.coursera.org/learn/neural-networks-deep-learning

I don't think this one is free, though that could have changed. 

Neither of these cover reinforcement learning.

**Comment by theDiverDK** [comment]
Hi Joe

Thanks for the reply.

I was bad at explaining what i was looking for.

Not so much the theory behind machine learning, but more good/bad practices regarding giving positive/negative rewards. Like in this example we have been talking about.

Like if this is good/bad:
` public override void AgentAction(float[] vectorAction, string textAction)
    {
        var distanceToTarget = Vector3.Distance(transform.position, Target.position);

        if (distanceToTarget < 1.42f)
        {
            AddReward(5.0f);
            Done();
        }

        AddReward(-0.0005f);

        if (transform.position.y < -1.0)
        {
            AddReward(-2.0f);
            Done();
        }

        var controlSignal = Vector3.zero;
        controlSignal.x = vectorAction[0];
        controlSignal.z = vectorAction[1];
        _rigidBody.AddForce(controlSignal * speed);
    }`

I followed your suggestion about lowering the time penalty, and thought if falling of/finding target should have other rewards also.
I did let it run this night with 5.000.000 steps, and now it runs very well :)

But i would like to have more knowledge of what is a good practice of using rewards, and when not to.

At some point ill try to let it run on another plane, to see if it can handle other shapes as well.

**Comment by ervteng** [comment]
I hope the discussion here answered your questions - general guidance on rewards can be found [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Best-Practices.md). 

Closing this discussion due to inactivity. Feel free to reopen the issue if you need additional help.
