### ISSUE TITLE
Get image of every frame

### ISSUE THREAD

**Issue by kukiel** [Unity-Technologies/ml-agents#134]
Hi guys!

I was trying to get image/screenshot of environment in any form after each step. I see only an option for capturing brain state images in _environment.py_ file. Any way to grab images of whole environment view (to be clear - the same as in opened Unity Environment window)?

Would appreciate any tip on that.

**Comment by vincentpierre** [comment]
If you are training with a custom neural network you can add an agent with the `main camera` as observation and connect it to a second external brain. The Brain you had before will send the states as usual and this second brain will record observations. You can access these images by doing 
```python
env_info = env.step()
for observation in env_info['nameOfSecondBrain'].observations:
    print("Agent observations look like:")
    if observation.shape[3] == 3:
        plt.imshow(observation[0,:,:,:])
    else:
        plt.imshow(observation[0,:,:,0]) 
   plt.show()
```
You could also add a camera observation to the brain you already have (but if you have more than one agent, you will send these images multiple time which can be a burden) and collect the images in python without feeding them into a neural network.
I hope this helps.

**Comment by kukiel** [comment]
@vincentpierre I see what you mean but was thinking of more generic solution without a need to modify a brain/environment - to have images of whole environment.

anyway thanks for help

**Comment by nickvazz** [comment]
@kukiel Were you ever able to figure this out without adding another brain?

**Comment by kukiel** [comment]
@nickvazz from what I remember we used separate brain so not really
