### ISSUE TITLE
Enforcing game rules in a board game/discrete environment

### ISSUE THREAD

**Issue by bestpx** [Unity-Technologies/ml-agents#1357]
Hi,

I'm new to ML and am trying to train agent to play a board game. In different game states, the available list of  actions will be different. How do I define that?

I'm trying to set `brain.brainParameters.vectorActionSize[0]` to the number of available actions right before `RequestDecision` in `Update` function. Then in `AgentAction()`, after agent takes action/gets rewards, the list of available action is updated. Is this the right approach? It seems to still stick to what the initial vectorActionSize and provide out-of-bound indecies.

If this is wrong, how to properly make the agent only take certain subset of actions at certain game state?

Thanks,
Dennis

**Comment by awjuliani** [comment]
Hi @bestpx,

We actually have a feature to allow you to "mask" actions during training. You can read about it here: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design-Agents.md#masking-discrete-actions. Also, our `GridWorld` example environment uses this feature, so feel free to check that out to learn more about it as well.

**Comment by bestpx** [comment]
This looks like exactly what I needed. Thanks for the help @awjuliani !
