### ISSUE TITLE
Dropdown missing in 'Learning-Environment-Create-New.md'

### ISSUE THREAD

**Issue by theDiverDK** [Unity-Technologies/ml-agents#1358]
In the guide it says:
**Finally, select the Brain GameObject so that you can see its properties in the Inspector window. Set the following properties:

Vector Observation Space Type = Continuous**

But there is no 'Vector Observation Space Type' selector when git cloning the newest version from the 16/10-2018

**Comment by awjuliani** [comment]
Hi @theDiverDK,

Thanks for pointing this out. You are correct that vector observation type has been removed in the latest versions of ML-Agents. We will correct it appropriately.

**Comment by awjuliani** [comment]
We have a PR for it here: https://github.com/Unity-Technologies/ml-agents/pull/1360. Thanks for pointing it out.

**Comment by theDiverDK** [comment]
Glad to help :-)
