### ISSUE TITLE
Integration of TFLite in Unity TF-Sharp for optimised mobile performance

### ISSUE THREAD

**Issue by chetu3319** [Unity-Technologies/ml-agents#1359]
Hi Community, 

I'm trying to integrate an optimized graph of Deeplab: https://ai.googleblog.com/2018/03/mobile-real-time-video-segmentation.html into unity for a real-time video segmentation. 

I got some success with simply TF Deeplab model in unity, but on running it, the performance is like 4-10 seconds per frame, which is quite not what the application requirements. 

I'm looking intoTFLite unity integration as mentioned on the Github repo: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/lite/experimental/examples/unity/TensorFlowLitePlugin

Target device: Galaxy Note 9 
OS: Android
Building on : Windows10 OS
Unity Version :  Unity 2018.2.10f1

It's giving a real hard time, to follow along and to build necessary plugins. Help on this will be appreciated.
-Chaitanya

**Comment by chetu3319** [comment]
@awjuliani, Any update which you can share?

**Comment by awjuliani** [comment]
Hi @chetu3319 

We will be switching to an internal Unity inference solution for ML-Agents v0.7. As such we won't be supporting TF# or TFLite going forward.
