### ISSUE TITLE
Found a different cause of timeout errors

### ISSUE THREAD

**Issue by dracolytch** [Unity-Technologies/ml-agents#136]
This may be one for the docs... I upped my action space in my brain by one, but forgot to change the Decide function to match. When I did this, it refused to connect (probably because something was silently crashing)

```csharp
//Blah blah blah
    public float[] Decide(List<float> state, List<Camera> observation, float reward, bool done, float[] memory)
    {
        if (gameObject.GetComponent<Brain>().brainParameters.actionSpaceType == StateType.continuous)
        {
            return new float[5] { 0f, 0f, 0f, 0f, 0f }; // I had to update this
        }
// Blah blah blah
```

**Comment by awjuliani** [comment]
Thanks for pointing this out. We are currently working on a solution to better surface errors like this, so you won't have to go hunt them down yourself in the editor.
