### ISSUE TITLE
Cant find trainer_config.yaml when running mlagents-learn

### ISSUE THREAD

**Issue by EdwardBurden** [Unity-Technologies/ml-agents#1364]
I'm using the 3DBall balancing tutorial and cant get the training to work.

Unity Version: 2017.4.13f1
Error in Unity: 
UnityAgentsException: The Communicator was unable to connect. Please make sure the External process is ready to accept communication with Unity.
MLAgents.Batcher.SendAcademyParameters (MLAgents.CommunicatorObjects.UnityRLInitializationOutput academyParameters) (at Assets/ML-Agents/Scripts/Batcher.cs:83)
MLAgents.Academy.InitializeEnvironment () (at Assets/ML-Agents/Scripts/Academy.cs:320)
MLAgents.Academy.Awake () (at Assets/ML-Agents/Scripts/Academy.cs:227)

Error in command line:
(ml-agents) D:\Year 3\Project\Research\ml-agents\ml-agents>mlagents-learn config/trainer_config.yaml --run-id=firstrun --train

                        ▄▄▄▓▓▓▓
                   ╓▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
          ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
          ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓▌
                        ¬`▀▀▀█▓

INFO:mlagents.trainers:{'--curriculum': 'None',
 '--docker-target-name': 'None',
 '--env': 'None',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--no-graphics': False,
 '--num-runs': '1',
 '--run-id': 'firstrun',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': False,
 '--train': True,
 '--worker-id': '0',
 '<trainer-config-path>': 'config/trainer_config.yaml'}
INFO:mlagents.envs:Start training by pressing the Play button in the Unity Editor.
INFO:mlagents.envs:
'Ball3DHardAcademy' started successfully!
Unity Academy name: Ball3DHardAcademy
        Number of Brains: 1
        Number of External Brains : 1
        Reset Parameters :

Unity brain name: Ball3DHardBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 5
        Number of stacked Vector Observation: 5
        Vector Action space type: continuous
        Vector Action space size (per agent): [2]
        Vector Action descriptions: ,
Process Process-1:
Traceback (most recent call last):
  File "c:\users\edward\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 247, in _load_config
    with open(self.trainer_config_path) as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config/trainer_config.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\edward\anaconda3\envs\ml-agents\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "c:\users\edward\anaconda3\envs\ml-agents\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\edward\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 47, in run_training
    tc.start_learning()
  File "c:\users\edward\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 289, in start_learning
    trainer_config = self._load_config()
  File "c:\users\edward\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 253, in _load_config
    .format(self.trainer_config_path))
mlagents.envs.exception.UnityEnvironmentException: Parameter file could not be found at config/trainer_config.yaml.

**Comment by awjuliani** [comment]
HI @EdwardBurden,

It seems that you need to run `mlagents-learn` from one directory higher. 

Rather than 

`(ml-agents) D:\Year 3\Project\Research\ml-agents\ml-agents`

Try it from 

`(ml-agents) D:\Year 3\Project\Research\ml-agents`

**Comment by EdwardBurden** [comment]
Yes!

Thanks, works now
