### ISSUE TITLE
python folder missing

### ISSUE THREAD

**Issue by cuddiheer1** [Unity-Technologies/ml-agents#1367]
The "python" folder appears to be missing from the Unity-Technologies/ml-agents GitHub download.

**Comment by awjuliani** [comment]
Hi @cuddiheer1,

We have replaced the `python` folder with the `ml-agents` folder. https://github.com/Unity-Technologies/ml-agents/tree/master/ml-agents

**Comment by cuddiheer1** [comment]
Thank you. This is extremely helpful.
Sincerely,

Bob Cuddihee
