### ISSUE TITLE
discussion : monitoring your agents observations and rewards

### ISSUE THREAD

**Issue by sterlingcrispin** [Unity-Technologies/ml-agents#1368]
Hey I just stumbled across this asset called Squiggle that's incredibly helpful for debugging streams of values like the observations and rewards agents get and thought someone else might find it helpful. I don't have any connection to the author of the asset just thought it was very helpful

It's helped me realize some of the values I was sending weren't properly normalized and in general just take a look at what's going on under the hood of my agent

![sqiggle](https://user-images.githubusercontent.com/2976761/47262258-009e5600-d4a1-11e8-8f8a-7cb54c390322.png) 
https://assetstore.unity.com/packages/tools/utilities/squiggle-21970

**Comment by awjuliani** [comment]
Hi @sterlingcrispin 

Thanks for bringing this up. The plugin seems quite nice. Perhaps one day we can integrate similar visualizations directly into ML-Agents.

**Comment by awjuliani** [comment]
Hi @sterlingcrispin,

We've made a note of this feature, and are closing the GitHub issue for now. Thanks again for sharing.
