### ISSUE TITLE
Can I constrain the range of exploration?

### ISSUE THREAD

**Issue by kanchi0914** [Unity-Technologies/ml-agents#137]
Hi there. I'm grateful for your work.
I've trained my agent, and now I have  some questions.
1. In continuous action space, can I constrain the range of exploration? I mean, in PPO algorithm, it seems that an agent receives action value beyond its available action space(e.g. agent can execute only [-1.0f~1.0f] as act[0] but received 2.0f). I feel it is needlessness, but is there no problem in PPO?
2. When Type Of Brain is internal, and state space is continuous, what does epsilon mean? I think it is kind of exploration rate, but I'm not sure about Min Value and Max Value. If I change value from 0, how do they work?

I look forward to hearing from you.

**Comment by awjuliani** [comment]
Hi @kanchi0914,

You are right that PPO outputs unbounded real-valued numbers. This is an aspect of the algorithm that is not changed. In practice it should not be a problem to simply clip the networks outputs on the Unity side.

As for `epsilon` it adds noise to the action outputs of the neural network. The network takes in a state and outputs a mean and standard deviation, to get actions it uses the equation `action = mean + std * epsilon`. By increasing epsilon, you get noisier actions which increase exploration. Hope that makes things a little clearer.

**Comment by kanchi0914** [comment]
Thank you for your reply! I think your advice would be useful.
thanks a lot!
