### ISSUE TITLE
Memory Leak when sending large vector observations

### ISSUE THREAD

**Issue by imankgoyal** [Unity-Technologies/ml-agents#1370]
Hi,
For my environment, I need to send large vector observations (size 10 x 100 x 100 x 100). I am getting the following message in the unity debug log:

```
##utp:{"type":"MemoryLeaks","allocatedMemory":25184475,"memoryLabels":[{"Default":792},{"NewDelete":6290961},{"Manager":824},{"GfxDevice":976},{"FMOD":640},{"Serialization":11328},{"BaseObject":560},{"Terrain":176},{"String":3370},{"DynamicArray":64},{"HashMap":18874368},{"PoolAlloc":-176},{"CloudService":360},{"SceneManager":232}]}
```

The same environment works fine in the editor mode. Also I am using a 32GB RAM system. I would very much appreciate any advice to address this issue.

Thanks!

**Comment by xiaomaogy** [comment]
@awjuliani

**Comment by imankgoyal** [comment]
Hi, 

I am using Mac OS with unity 2017.4.0f1 to create a Linux Standalone executable. I am running the executable on a CentOS Linux (Version 7 machine). I am sending integers. I flatten the tensor to create a vector observation.

**Comment by xiaomaogy** [comment]
@awjuliani

**Comment by awjuliani** [comment]
We will add this to our bug log to look into. Closing this issue for now. Please feel free to re-open if you deem it necessary.
