### ISSUE TITLE
Help Needed (Agent being reset systematically) - Making a New Learning Environment

### ISSUE THREAD

**Issue by SamHS-OCI** [Unity-Technologies/ml-agents#1372]
I've been following the tutorial to learn how to use the ML-Agents 0.5 

It's been very instructive, but I am having a problem. Very likely that I have forgotten one step or mistyped part of the code. 

I am trying to move my RollerAgent through the scene, using W-A-S-D keys. Unfortunately, what has been happening is that my Agent is being reset systematically and being placed in random positions.  I do understand that this is part of the else portion of the AgentReset() function. But could someone help me understand what is calling the AgentReset() function?

Attached is part of my RollerAgent code:

`
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using MLAgents;

public class RollerAgent : Agent {

    Rigidbody rBody;

	// Use this for initialization
	void Start ()
    {
        rBody = GetComponent<Rigidbody>();	
	}

    public Transform Target;
    public override void AgentReset()
    {
        if (this.transform.position.y <= -1.0f)
        {
            this.transform.position = Vector3.zero;
            this.rBody.angularVelocity = Vector3.zero;
            this.rBody.velocity = Vector3.zero;
        }
        else
        {
            Debug.Log("Reseting");
            Target.position = new Vector3(Random.value * 8 - 4, 0.5f, Random.value * 8 - 4);
        }
    }

    public override void CollectObservations()
    {
        Vector3 relativePosition = Target.position - this.transform.position;

        //Relative Position
        AddVectorObs(relativePosition.x / 5);
        AddVectorObs(relativePosition.z / 5);

        //Distance to edges of platform
        AddVectorObs((this.transform.position.x + 5) / 5);
        AddVectorObs((this.transform.position.x - 5) / 5);
        AddVectorObs((this.transform.position.z + 5) / 5);
        AddVectorObs((this.transform.position.z - 5) / 5);

        //Agent Velocity

        AddVectorObs(rBody.velocity.x / 5);
        AddVectorObs(rBody.velocity.z / 5);
    }

    public float speed = 10;
    private float previousDistance = float.MaxValue;

    public override void AgentAction(float[] vectorAction, string textAction)
    {
        //Rewards
        float distanceToTarget = Vector3.Distance(this.transform.position, Target.position);

        //Reached Target

        if(distanceToTarget <= 1.42f)
        {
            AddReward(1.0f);
            Done();
        }

        //Time Penalty

        AddReward(-0.05f);

        //Fell off Platform

        if (this.transform.position.y < -1.0f)
        {
            AddReward(-1.0f);
            Done();
        }

        //Actions, size 2 -> Can move in 2 directions

        Vector3 controlSignal = Vector3.zero;
        controlSignal.x = vectorAction[0];
        controlSignal.z = vectorAction[1];
        rBody.AddForce(controlSignal * speed);
    }
}`

Also my settings:

![image](https://user-images.githubusercontent.com/36551435/47391305-0ed9b580-d6df-11e8-9ae5-1bade3f2d6b0.png)

![image](https://user-images.githubusercontent.com/36551435/47391344-27e26680-d6df-11e8-9c5a-d6497291f4fe.png)

**Comment by jo3w4rd** [comment]
AgentReset() should be called when the Agent becomes "done", the Agent step counter reaches MaxStep, or the Academy step counter reaches MaxStep. If MaxStep is set to zero, the counter doesn't matter, though. What is your Academy MaxStep setting?

**Comment by SamHS-OCI** [comment]
It is set to 0.

![image](https://user-images.githubusercontent.com/36551435/47392464-51e95800-d6e2-11e8-8ef6-842afa425106.png)

**Comment by jo3w4rd** [comment]
How often are you seeing it reset? 

I just recreated the scene from scratch and don't see any resets.

**Comment by SamHS-OCI** [comment]
I cannot count, actually. It is pretty fast.

**Comment by jo3w4rd** [comment]
Actually, I see the problem. In your Agent Inspector, you set the Target object to be the Agent rather than the Cube.

**Comment by SamHS-OCI** [comment]
Awesome, 👍 ! Problem solved! Thank you very much! That was a bad distraction! :(

**Comment by jo3w4rd** [comment]
Happy to help!
