### ISSUE TITLE
What is Bytes file in the TFmodels folder

### ISSUE THREAD

**Issue by xiaozhuzhuzhu** [Unity-Technologies/ml-agents#1376]
hello,
I want to know what is bytes file which is embedded in the internal brain in the TFmodels folder. 
What role do they have? 
When I embed it in unity, it is based on the target, or from the beginning of training (from nothing to achieve the goal)?

**Comment by eshvk** [comment]
The bytes file is a TensorFlow embedded graph in the protobuf file format. It is the "model" that is trained and then serialized.

**Comment by xiaozhuzhuzhu** [comment]
> bytes文件是protobuf文件格式的TensorFlow嵌入图。它是经过训练然后序列化的“模型”。

Thank you very much for your reply. 
Does  bytes file use the trained policy to feed back the corresponding action instead of starting from nothing if the agent is now in a new environment (a scene that may never have occurred during training).

**Comment by jo3w4rd** [comment]
You can think of a policy as a function that takes in the observations that you give it and returns the action to take. The training process determines what that function looks like internally (by determining the coefficients of the neural network matrices). When you use that function after training, the policy does not change (it doesn't learn anything from the environment when you are not explicitly training). Thus, how well a policy does in a new environment depends on how representative the training environment was.

**Comment by xiaozhuzhuzhu** [comment]
> You can think of a policy as a function that takes in the observations that you give it and returns the action to take. The training process determines what that function looks like internally (by determining the coefficients of the neural network matrices). When you use that function after training, the policy does not change (it doesn't learn anything from the environment when you are not explicitly training). Thus, how well a policy does in a new environment depends on how representative the training environment was.

I see, thank you！
