### ISSUE TITLE
Does anyone have the code for this project? Self-driving.

### ISSUE THREAD

**Issue by xiaozhuzhuzhu** [Unity-Technologies/ml-agents#1377]
Hi 
Does anyone have the code for this project? Self-driving.It is based on V 0.4
![image](https://user-images.githubusercontent.com/23623240/47540897-b6d2c700-d909-11e8-91ee-da0e72d6ea1d.png)
Thank you!

**Comment by xiaomaogy** [comment]
HI @xiaozhuzhuzhu where do you see this example?

**Comment by xiaozhuzhuzhu** [comment]
> HI @xiaozhuzhuzhu where do you see this example?
Unity China.
https://connect.unity.com/p/shi-yong-unityji-qi-xue-xi-dai-li-gong-ju-ml-agentsjin-xing-zi-dong-jia-shi-xun-lian

**Comment by eshvk** [comment]
Unfortunately, we don't have access to the code for this. I am going to close this issue for now.
