### ISSUE TITLE
Discrete Action Masking during inference

### ISSUE THREAD

**Issue by hyounesy** [Unity-Technologies/ml-agents#1380]
Hello,
Is the discrete action masking only considered during training or is it also checked during inference (internal brain)?
I am adding the recently introduced action masking to my existing pre trained agents (0.4) and I notice that the agents are choosing the actions regardless of whether they are masked or not.

**Comment by xiaomaogy** [comment]
@vincentpierre

**Comment by vincentpierre** [comment]
Action masking was introduced in v0.5. If you are using an older model, the action masking will not work at inference time.

**Comment by hyounesy** [comment]
Makes sense. Thanks for the clarification @vincentpierre .
