### ISSUE TITLE
It seems like there is a bug in the CoreBrainInternal.cs

### ISSUE THREAD

**Issue by tominku** [Unity-Technologies/ml-agents#1386]
When I run multiple agents, the value estimates (from agent.GetValueEstimate()) are quite weird.
And I've found that there is a bug code in the following c# script.

https://github.com/Unity-Technologies/ml-agents/blob/d6dad11c773a8598540a8896d0d48b2489b222ae/UnitySDK/Assets/ML-Agents/Scripts/CoreBrainInternal.cs#L439

while the var i  is declared, it is not increased in the loop, thus not updating the value estimates of the
agents in the scene.

I correct it as follows and it seems work.

                var i = 0;
                foreach (Agent agent in agentList)
                {
                    agent.UpdateValueAction(value_estimates[i,0]);
                    ++i;
                }
Hope it might be helpful !

**Comment by xiaomaogy** [comment]
Hi @vincentpierre, It seems this is a valid bug.

**Comment by vincentpierre** [comment]
This has been resolved in v0.6
