### ISSUE TITLE
Input.mousePosition as vectoraction

### ISSUE THREAD

**Issue by michaelzlatkin** [Unity-Technologies/ml-agents#1387]
I'm trying to make a Top-Down shooter using the ML-Agents framework, but I realized that you can only use axis inputs as actions for your agents. Does anyone know a way around this?

**Comment by LeSphax** [comment]
Hey I am not sure what you mean by axis inputs as actions.

The agent is basically a function that takes an array of floats as input and returns a different array of floats.

You specify the input in CollectObservations.
You get the output in AgentAction (the parameter float[] vectorAction)

Then you can interpret this output array as you want. For example, saying that the first element is an x position and the second one a y position.
So you would get your mousePosition like that:
mousePosition = new Vector2(vectorAction[0], vectorAction[1])

Actually, I am currently doing this in my own project and it seems that the agent is having trouble understanding how to returns x,y coordinates, so there might be a better way to do this.
I am currently experimenting in replacing cartesian coordinates (x,y) with polar coordinates (angle, distance)

Hope that helps :)

**Comment by michaelzlatkin** [comment]
Thanks for the response!

I think I should have clarified more, basically what I want to do is to create multiple models, one from plain ppo, one from imitation learning, and one where I combine the two (if possible).

So basically, every action that can be done as a vector action needs a player brain action counterpart. Now, entering actions done by the player brain gives you key continuous inputs or axis inputs.

If I were to make a top down shooter in the style of say hotline Miami, I would want to point towards the position of my mouse. Sadly, the Input.mousePosition variable I would normally use for that is not an option in the player brain actions.

Luckily, I did figure out a "solution": I dug up my old third-party controller and made it a twin stick shooter instead. This will allow me to do everything the AI can in an intuitive way.

Thanks again for your help!

**Comment by banish09** [comment]
@michaelzlatkin Can you please explain how to implement the Input.mousePosition in the PlayerBrain Asset. I am struggling with the same problem.

**Comment by michaelzlatkin** [comment]
@banish09 unfortunately I didn't find a solution for this issue and used a workaround instead.

**Comment by banish09** [comment]
@michaelzlatkin Can you please expand a little bit about the workaround you figured out?

**Comment by michaelzlatkin** [comment]
@banish09 I switched to a Xbox controller and used the right analog stick's axis input to rotate my AI, you should be able to map this directly in your player brain. Unfortunately my memory is a bit hazy since it's been almost a year, but I hope this helps!

**Comment by banish09** [comment]
I'll try it out. Thanks for the help!

**Comment by Zilch123** [comment]
Hi @banish09, were you able to solve it. I'm trying the same, to use Input.mousePosition in the PlayerBrain Asset. I was wondering if there is any workaround what you were able to find. 
Thank you,
Zilch123
