### ISSUE TITLE
How to incorporate supervised learning with game variables into models?

### ISSUE THREAD

**Issue by Serious-Joker** [Unity-Technologies/ml-agents#1390]
Hi, I want to add a branch to the Brain that uses supervised learning to train on game features.
A good example is in [Arnold](https://github.com/glample/Arnold) where the agent has shared weights between the policy and the prediction of the game features which is trained using supervised learning.
Since having game specific features like "can I see an enemy?" is [trivial](https://en.wikipedia.org/wiki/Wikipedia:Citation_needed) in Unity , there should be a way to do this. 

I think it has to do with sending extra data to python that isn't part of the observation. I could extend the `BrainInfo` in `brain.py` to include game feature information and add an extra `"game feature training"` function to a Trainer which would be called in `trainer_controller.py`.

As for sending the data itself, I think it might be useful to extend the `Agent` and `AgentInfo` classes defined in `Agent.cs` to include extra information that can be sent from Unity via the agents `SendInfoToBrain` function but I'm not sure if this is the right direction.

Thoughts?

**Comment by awjuliani** [comment]
Hi @Serious-Joker,

The easiest way to do this is to simply add all the information as observations, and then split the observation on python into the RL-specific observation, and the auxiliary information. In the case where there might be an image which is used as the observation to the policy, and numerical information that are the supervised targets, that is pretty straightforward. It would also be possible to augment the AgentInfo class with an additional field, but this would require modifying the protobuf definitions as well. https://github.com/Unity-Technologies/ml-agents/tree/master/protobuf-definitions

**Comment by Serious-Joker** [comment]
Hey @awjuliani, thanks for the quick reply.

If I split the observation on the python side, I would have to remember how many vector observations I need to split off from the observation list. As I want to be able to change the number of game variables or add extra data for analytics later, I feel like it would become more difficult to maintain although easier to implement at the start than modifying protobuf definitions.

I'm also confused as to how that would work with using a trained agent internally. 
I think if I set the vector observations to 15 in Unity, 10 for the agent and 5 for game variables, then trained agent it would only ever see 10 vector obs. If I tried to use it internally, wouldn't it break because Unity is now serving it 15 variables? I'd have to manually update the number in Unity (from 15 to 10) to make sure Unity is serving the trained model the right number of variables. This could lead to a really confusing bug where training the agent requires 15 variables but using the agent internally requires 10.

Given this, perhaps adding a field to the Brain of extra data and updating the protobuf might be more powerful and seems like a good idea for a feature.

**Comment by awjuliani** [comment]
Hi @Serious-Joker,

Those are all great points. We plan to expand the kinds of information which can be exposed via the api in the future to allow for something like this. Right now another option is to use the "text observation," and send the relevant information over as a json object.

**Comment by Serious-Joker** [comment]
Hi @awjuliani,
Great idea on the text observation! Thanks!
That works really well. I was quickly able to get some analytic data out and display it using tensorboard after I modified trainer_controller.py. Its really flexible which is awesome 🥇.

**Comment by awjuliani** [comment]
Glad to hear. Closing this issue for now. Please feel free to re-open if you deem it necessary.
