### ISSUE TITLE
Unity UWP build error

### ISSUE THREAD

**Issue by keanudicap** [Unity-Technologies/ml-agents#1398]
I trained a model with ML-agents and plan to run the trained model as internal brain in HoloLens. While building UWP, three errors are shown:

Assets\ML-Agents\Scripts\CoreBrainInternal.cs(12,7): error CS0246: The type or namespace name 'TensorFlow' could not be found (are you missing a using directive or an assembly reference?)
Assets\ML-Agents\Scripts\CoreBrainInternal.cs(70,5): error CS0246: The type or namespace name 'TFGraph' could not be found (are you missing a using directive or an assembly reference?)
Assets\ML-Agents\Scripts\CoreBrainInternal.cs(71,5): error CS0246: The type or namespace name 'TFSession' could not be found (are you missing a using directive or an assembly reference?)

I did follow the instruction to import TensorflowSharp package and define ENABLE_TENSORFLOW, and the project runs well in Unity editor.

**Comment by keanudicap** [comment]
Also, an error was shown in the inspector when brain was switched to internal saying:

You cannot have ENABLE_TENSORFLOW without NET_4_6.

However, I have net 4.6 framework installed.

**Comment by keanudicap** [comment]
This is the Setting->Player
![image](https://user-images.githubusercontent.com/8280596/47923154-f6288700-deb8-11e8-8604-e85dfe33ee28.png)

**Comment by keanudicap** [comment]
> Hi @keanudicap, we haven't tested this on hololens yet. Does this error happen on Windows also or it is only for hololens build?

**Comment by keanudicap** [comment]
It happened when switch the build platform to Universal Windows Platform (UWP). We didn't really include HoloLens toolkit (Mixed reality toolkit) in the project for testing.

**Comment by keanudicap** [comment]
I guess the main problem would be failure in finding NET_4_6 which results in the disability of ENABLE_TENSORFLOW. However, as the image I showed above, I switched Api compatibility level to .NET 4.x.

**Comment by xiaomaogy** [comment]
Not sure how this works on hololens.....

**Comment by keanudicap** [comment]
It is easy to reproduce the error. 

1. Having any Unity project using ML-agents, for instance, we could use 3D ball example. 
2. Import Tensorflowshap.package, and do all the settings, e.g. create ENABLE_TENSORFLOW
3. File->Build setting-> switch platform to UWP
![image](https://user-images.githubusercontent.com/8280596/47945943-16326780-df06-11e8-9843-4858ec05199a.png)
4. When build, the error shall be shown.

**Comment by xiaomaogy** [comment]
It does not support UWP for now, it only experimentally supports inference on mac, windows, linux, ios and android.

**Comment by cindychen0204** [comment]
Please consider about supporting this on UWP, or you can give me some hints, maybe it is not so hard.

**Comment by xiaomaogy** [comment]
You can contribute to https://github.com/migueldeicaza/TensorFlowSharp to help supporting it.

**Comment by oddEventHorizon** [comment]
@xiaomaogy 

I have the same issue as described here and on few other posts: 

![image](https://user-images.githubusercontent.com/19377008/50257223-a36c4580-03fa-11e9-877c-0da9a3c3e604.png)

and wherever I search issue was related to unsupported setup (which is not my case), or was not resolved at all. Could you point to what may be wrong? 

When I remove "ENABLE_TENSORFLOW" from Scripting Runtime Symbols, error disappears - I assume it's due to #if ENABLE_TENSORFLOW line.

Brute force removing #if ENABLE_TENSORFLOW didn't help either. 

I have Unity 2018.3.0f2
Tried it on both ML Agents 0.5 and ML Agents 0.6 no success in either case. 

What am I missing?

**Comment by xiaomaogy** [comment]
Hi @oddEventHorizon , as we discussed above, the UWP is not supported by our TFSharp solution right now....And I'm not able to help you on this issue...

**Comment by oddEventHorizon** [comment]
thanks for short, reply. I'm not using UWP yet I see the same error. Should I start a new issue then?

**Comment by xiaomaogy** [comment]
@oddEventHorizon Yes you should start another issue if it is not related with this issue's title.

**Comment by lh784116211** [comment]
你好@xiaomaogy  ，我也遇到了相同的问题，请问它现在能支持UWP了吗？

**Comment by xiaomaogy** [comment]
你好 @lh784116211 , 目前我们已经不用tensorflowsharp，转为使用Barracuda了。理论上Barracuda应该支持UWP， 不过我们没有试过，你可以试一下，要是不行的话可以再post一个新的issue。
