### ISSUE TITLE
Is GPU support?

### ISSUE THREAD

**Issue by spk921** [Unity-Technologies/ml-agents#14]
I am wondering this C#tensorflow build is GPU support?

**Comment by vincentpierre** [comment]
TensorflowSharp must work on iPhones, Android phones. For this reason, we compiled the Tensorflow libraries to work on CPUs only (Tensorflow on phones uses the CPU).
If you want, you can explore the [TensorFlow plugin](https://s3.amazonaws.com/unity-agents/TFSharpPlugin.unitypackage) and the [TensorflowSharp](https://github.com/migueldeicaza/TensorFlowSharp) project to compile Tensorflow for GPU, we would be happy to hear about your results.
