### ISSUE TITLE
Imitation learning timeline?

### ISSUE THREAD

**Issue by karthikveeramani** [Unity-Technologies/ml-agents#140]
I see in your notes that imitation learning will be added soon. Do you have an approximate timeline for this?

**Comment by awjuliani** [comment]
Hi @karthikveeramani,

Preliminary support for Imitation Learning is coming very soon! In fact, if you look in the `development` branch of the repository, it includes a feature called "broadcast" which allows the sharing of states and actions from all brain types to python. In the coming weeks we will be providing more documentation around this, as well as a tutorial on using it for imitation learning.
