### ISSUE TITLE
Player brain options 

### ISSUE THREAD

**Issue by ruairidhcumming** [Unity-Technologies/ml-agents#1400]
Hi 
I'm trying to test a training environment by using a player brain to move the player around. the setup options I'm seeing in my editor do not match the images in the tutorials i have found and i cant work out how to set up the input axes for the player brain. Can anyone tell what I've done wrong?

Tutorial image
![image](https://user-images.githubusercontent.com/35342262/47953955-3997f980-df7c-11e8-8153-e11237777a31.png)

screenshot of my editor
![image](https://user-images.githubusercontent.com/35342262/47954033-38b39780-df7d-11e8-8deb-7974ae177597.png)

**Comment by xiaomaogy** [comment]
Hi @ruairidhcumming , which tutorial are you following? As of v0.5 of ml-agents, you don't create your own brain (DriverBrain.cs), instead you use Brain.cs.

**Comment by ruairidhcumming** [comment]
The Tutorial image was from
 https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design-Player-Brains.md
Thanks for the note on standard Brain.cs
