### ISSUE TITLE
Does unity support linux?

### ISSUE THREAD

**Issue by aznshodan** [Unity-Technologies/ml-agents#1401]
It seems like there is no installation for linux OS. Only supports Windows and Mac.

I only have mac book pro which does not have a gpu. Is there a way I can install unity but train ml-agents on some other computer, preferrably on my linux machine with a gpu?

**Comment by MarcoMeter** [comment]
It runs well on Linux. Just setup your python environment and install ml-agents.

**Comment by aznshodan** [comment]
It says I need to Install Unity 2017.4 or Later at https://store.unity.com/download which is only available for Windows and Mac

**Comment by MarcoMeter** [comment]
You don't need to install Unity on the linux machine to train your environments.

**Comment by aznshodan** [comment]
I see. I was simply following the instructions found  [here]( https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md) which said I needed to install unity.
