### ISSUE TITLE
Contribution: Recording videos during training

### ISSUE THREAD

**Issue by LeSphax** [Unity-Technologies/ml-agents#1403]
Hello,

I have recently started to record videos of my game automatically during training using this code https://github.com/unity3d-jp/FrameCapturer.

I find it quite practical for debugging and I could take the time to create a pull request if you think this is something that could be part of ml-agents.

**Comment by xiaomaogy** [comment]
Hi @LeSphax, thank you very much! It would definitely help if you could create a PR.

**Comment by xiaomaogy** [comment]
I'm closing this since we already have merged a PR.
