### ISSUE TITLE
Are agents' actions executed simultaneously?

### ISSUE THREAD

**Issue by icaro56** [Unity-Technologies/ml-agents#1405]
Hi,

The author of the paper **Exploration Methods for Connectionist Q-Learning in Bomberman** speaked:
> Every Bomberman is controlled by an agent. The game state is sent to the agents, which then determine their next moves. After the actions have been executed, the consequences of the actions are communicated to the agents in the form of rewards. The actions are executed simultaneously so that no agent has an advantage

He speaked **the actions of the agents are executed simultaneously so that no agent has an advantage**

In ML-Agents Toolkit are agents' actions executed simultaneously? I have noticed that all agent observations are performed first and then all actions are performed afterwards.

Example:

My loop code in my PlayerManager:

```
foreach (KeyValuePair<int, Player> entry in playerDict)
{
    entry.Value.RequestDecision();
}
```

Should I iterate over agents randomly?

**Comment by awjuliani** [comment]
Hi @icaro56,

What you have corresponds to simultaneous execution. What is meant in that paper is that there aren't agents getting new observations between actions.

o1 -> a1 -> o2 -> a2 (Bad)

vs

o1 -> o2 -> a1 -> a2 (Good)

**Comment by icaro56** [comment]
> Hi @icaro56,
> 
> What you have corresponds to simultaneous execution. What is meant in that paper is that there aren't agents getting new observations between actions.
> 
> o1 -> a1 -> o2 -> a2 (Bad)
> 
> vs
> 
> o1 -> o2 -> a1 -> a2 (Good)

Thank you @awjuliani .
