### ISSUE TITLE
Any possibile way to combine Imitation learning and PPO by using ML-Agents?

### ISSUE THREAD

**Issue by zheyangshi** [Unity-Technologies/ml-agents#1407]
Hello! Many thanks for the wonderful project~

I am trying to design a simple FPS AI. But it is hard for agent to learn the environment in the begining.

By using ml-agents, **Can we do the Imitation learning to finish the basic tasks, and then start the PPO?**

**Comment by awjuliani** [comment]
Hi @zheyangshi,

This feature is currently not available, but it is something which we are actively working on, and hope to be able to provide in the not too distant future.

**Comment by zheyangshi** [comment]
I can't wait to see it, Thank you so much!
