### ISSUE TITLE
Gym wrapper - no graphics?

### ISSUE THREAD

**Issue by adam-pociejowski** [Unity-Technologies/ml-agents#1413]
Hello,
Is it possible using gym wrapper to not render game while training?
If yes how can I do this?

**Comment by vincentpierre** [comment]
Hi, If you are building for Linux, you can check the headless checkbox when building the game. You can also turn off all the cameras in the scene, this will disable rendering but you will still see a black window open. UnityEnvironment has a no_graphics argument, you could try replacing [this line](https://github.com/Unity-Technologies/ml-agents/blob/master/gym-unity/gym_unity/envs/unity_env.py#L34) with 

```
self._env = UnityEnvironment(environment_filename, worker_id, no_graphics=True)
```
Note that visual observations will not work if you disable rendering.
I hope this helps.
