### ISSUE TITLE
When to Add reward

### ISSUE THREAD

**Issue by tanakataiki4** [Unity-Technologies/ml-agents#1417]
@awjuliani 
Thanks for a good repo
https://github.com/Unity-Technologies/ml-agents/blob/d6dad11c773a8598540a8896d0d48b2489b222ae/UnitySDK/Assets/ML-Agents/Examples/Walker/Scripts/WalkerAgent.cs#L143

in this code reward is added at every step but Action and observation is done at N decision step.
so is this better (more acurate)than adding reward at every decision step?

**Comment by tanakataiki4** [comment]
@vincentpierre 
Thanks. Then Does ppo net work consider step size of action not only at decision step that accumulates reward and states?

**Comment by vincentpierre** [comment]
PPO only receives a signal when a decision is requested, not at every step. The reward ppo receives at each decision is the sum of the rewards that were added at each step between decisions.
```
decision request
 step - AddReward(0.2f)
 step - AddReward(0.2f)
 step - AddReward(0.2f)
decision request -> PPO receives 0.6 reward
 step - AddReward(0.2f)
 step - AddReward(0.2f)
 step - AddReward(0.2f)
decision request -> PPO receives 0.6 reward
...
```

**Comment by tanakataiki4** [comment]
@vincentpierre
Got it. Thanks a lot

**Comment by KReguieg** [comment]
One question depending the reward adding. I added a reward of -0.001 as exploration incentive. But somehow this seems to be not accepted as a reward, because if you write the CumultativeReward into a text field it doesn't change with such a low reward. With hundredths it's working but not with a thousandths, is this correct?

**Comment by vincentpierre** [comment]
The reward is using floating points, rewards of a thousandths should work. It might be truncation in the to string method (try to multiply by 1000 and see if this number is changing)
You could also be overwriting your reward with a SetReward call.
