### ISSUE TITLE
ML-Agents news site

### ISSUE THREAD

**Issue by dora-gt** [Unity-Technologies/ml-agents#142]
Hi,

Thank you, ML-Agents developer @awjuliani, @vincentpierre.

We want to know new releases of ML-Agents including document update.

I found that a document about using [TensorFlowSharp](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-TensorFlow-Sharp-in-Unity-(Experimental).md) was added by chance but most people may not know.

So announcements about your updates are helpful, or is there already?

Thank you.

**Comment by awjuliani** [comment]
Hi @dora-gt,

For major changes to ML-Agents, we will have blog posts. For smaller changes, we will write release notes, which are available here: https://github.com/Unity-Technologies/ml-agents/releases. As you can see, we are close to releasing a new version 0.2, which you are welcome to test on the "development" branch.
