### ISSUE TITLE
Retrain with different net work size

### ISSUE THREAD

**Issue by tanakataiki4** [Unity-Technologies/ml-agents#1421]
Hi is there any way to retrain different net work size such as additional state or visual observation after training completed?

**Comment by 4rzael** [comment]
I don't think there is an easy way to do so. However, it is possible to copy weights from one tensorflow model to another. This isn't trivial and requires some knowledge of tensorflow.

I made [a jupyter notebook](https://gist.github.com/4rzael/bff3cc09972241f263719f4631567c0f#file-copy_all_compatible_weights-ipynb) (the file named copy_all_compatible_weights) where I do so for a small multi-layer perceptron. It is not related to a reinforcement learning agent, but some of the code might be reusable.

**Comment by ervteng** [comment]
We currently do not support this feature, and there are no plans to do so. However, the Tensorflow method @4rzael suggested is a good path to doing what you'd like to do.

**Comment by tanakataiki4** [comment]
@4rzael Could  you tell me if you find a way to use in unity ml agents too, let me know it Thanks .
