### ISSUE TITLE
Academy, Target Frame Rate?

### ISSUE THREAD

**Issue by superjayman** [Unity-Technologies/ml-agents#1425]
What does Target Frame Rate really mean and do exactly? The documentation says, 'FPS the engine attempts to maintain'. What engine, what how, please explain? Say I have v-sync disabled are enabled which changes frame rate update, how does this play together with this parameter?

Also, noticed something strange, if I train my agent in unity editor the agents seem to move correct speed then after training I use the trained brain and enable 'Maximise On Play' in editor, the agents are now moving super fast speed, even tough all physics are done in FixedUpdate? (Speed should be the same?).  p.s. Timescale in training configuration is set to 1.

**Comment by xiaomaogy** [comment]
@harperj

**Comment by harperj** [comment]
Target Frame Rate is the frame rate that the Unity engine will attempt to maintain.  This means that the engine will make a best-effort attempt to run all game logic and physics updates and also render within  the time of `1 / target_fps` seconds.  If this value is set too high, there is a possibility you could see unexpected physics simulation behavior.

When you use the trained brain this is "inference mode" which will use a separate time scale (specified in the Academy).

For more information see [the Unity docs](https://docs.unity3d.com/ScriptReference/Application-targetFrameRate.html).

I'm going to close this issue now but if this doesn't answer or you have more to say feel free to reopen or create a new issue.
