### ISSUE TITLE
Train until SceneLoader.QuitGame()

### ISSUE THREAD

**Issue by SamBlakeman** [Unity-Technologies/ml-agents#1428]
Is there a simple way to train on an environment until the application quits? I use the local_done variable to know when an episode is over and I set the overall simulation time in the unity editor in seconds. Once I reach the limit I quit the application and I want to be able to detect this in my external brain and continue doing a few other things in python. Is this possible?

Thanks in advance,
Sam

**Comment by awjuliani** [comment]
Hi Sam,

There are a couple ways to expose a "final done" signal. The first is that you could use the Academy's done signal as the final done. You could also use a text observation which indicates whether the final done signal has been provided.

**Comment by SamBlakeman** [comment]
Hi Arthur,

Thanks for the prompt reply! Apologies for the beginner question, I am just trying to get to grips with the toolkit for my PhD work. The text observation flag is an elegant solution thank you. Congrats on such a good piece of work!

**Comment by SamBlakeman** [comment]
Yes thank you! Feel free to close!
