### ISSUE TITLE
Camera doesn't move with object

### ISSUE THREAD

**Issue by kwea123** [Unity-Technologies/ml-agents#143]
Hello,
I want to train a simple self driving car, I have the car and the track.
I have attached a camera to the car (as a child) to get the information of the road.
In unity when I control the car by myself, everything works fine, the camera goes with the car, but when I try to train, the camera stays at its initial position and doesn't move with the car. I also tried setting the position manually but it doesn't work either. Please help, thanks!

update:
when I check the position of the camera, it does move, but the image (env_info.observation) is still what it sees from its initial position. (I want the camera to be always in front of the car)
Below are images showing that the car advances but the camera doesn't (while it should and it did when I render the scene by setting train_mode=False)
![init](https://user-images.githubusercontent.com/11364490/32825984-bd19612a-ca21-11e7-9b00-e85460547f7b.png)
![move1](https://user-images.githubusercontent.com/11364490/32825985-bd4600d6-ca21-11e7-924e-af4aaab03a98.png)
![move2](https://user-images.githubusercontent.com/11364490/32825986-bd6efb26-ca21-11e7-9964-8eb1fa57f8a7.png)

**Comment by kwea123** [comment]
OK I solved in on my own.
When initializing the agent, I have to add
`observations[0] = car.transform.Find("Camera").GetComponent<Camera>();`
to actually set the reference of the camera to my camera object.
I guess this is worth mentioning in your documentation, thanks.

**Comment by vincentpierre** [comment]
Hey @kwea123 You can also add the camera to an agent in the inspector. If you want an object to move with another, you need to make that object (here the camera) a child of the object in the scene hierarchy. Glad you solved it.
