### ISSUE TITLE
TFModel not found. (release-v0.6)

### ISSUE THREAD

**Issue by cr545l** [Unity-Technologies/ml-agents#1431]
![img_20181120_090820](https://user-images.githubusercontent.com/10678303/48742815-de684580-eca3-11e8-8379-03b3035c9001.png)

There is a binary file in the TFModels folder, but it is incompatible and unusable.

Revision : c7527a1138d8746c3afc46622050c7ad4f10a7a6
Unity : 2018.2.3f1

**Comment by awjuliani** [comment]
Hi @cr545l,

The `release-v0.6` branch is still under development, and as such the ability to run inference models is currently not functional on this branch. We recommend using v0.5a (on `master`) until v0.6 has been officially released.

**Comment by cr545l** [comment]
Thank you for quick response.
