### ISSUE TITLE
Error in anaconda after entering training command

### ISSUE THREAD

**Issue by AppleiVan9** [Unity-Technologies/ml-agents#1433]
I have this issue in where after a fresh install of anaconda and other installations for using ml-agents. Everything works in the first training. but when i train a second time this appears. 
![image](https://user-images.githubusercontent.com/34593922/48801193-b120a380-ed46-11e8-88a6-56798a84fa64.png)

**Comment by AppleiVan9** [comment]
I also noticed that before training the python.exe file is still inside the environment folder. then after training it disappears. is that normal? here are the screenshots
Before training: 
![before_training](https://user-images.githubusercontent.com/34593922/48801285-f218b800-ed46-11e8-8980-7c76f267b76a.png)

After training:
![after_training](https://user-images.githubusercontent.com/34593922/48801305-f8a72f80-ed46-11e8-80c9-81cbc2e49a42.png)

**Comment by AppleiVan9** [comment]
Also i installed the latest version of anaconda. does this can be a reason why i have this problem? do i need to install the version of anaconda that is stated in the installation document?

**Comment by LokoGD** [comment]
Seems we have the same issue (or at least, a similar one), heres the info of my problem (with other user too): #1447

**Comment by xiaomaogy** [comment]
Please refer to the issue #1447 for help.
