### ISSUE TITLE
the actra brain property is different from doc

### ISSUE THREAD

**Issue by clikes** [Unity-Technologies/ml-agents#1436]
![image](https://user-images.githubusercontent.com/32139042/48852111-9eaa7680-ede7-11e8-80a8-8b30531dd33b.png)
brain in my editor
![image](https://user-images.githubusercontent.com/32139042/48852210-d9141380-ede7-11e8-98ba-71016b11eba2.png)
brain in doc
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design-Brains.md

**Comment by harperj** [comment]
I believe this issue is no longer applicable after the v0.6 release.  Closing, but feel free to reopen or open a new issue if you run into any similar problems in the future.
