### ISSUE TITLE
How do I change the PPO algorithm?

### ISSUE THREAD

**Issue by xiaozhuzhuzhu** [Unity-Technologies/ml-agents#1437]
What files should I change in addition to changing this file(ml-agents-master\ml-agents\mlagents\trainers\ppo\models),if I want to change the PPO algorithm in V05 ?Previously V04 and V03 only changed this one file seems to be fine. But in V05, even if I changed the contents of this file, it seems that I still use the PPO algorithm.

**Comment by xiaozhuzhuzhu** [comment]
I just want to change the contents of this file（ml-agents-master\ml-agents\mlagents\trainers\ppo\models）. Other files don't need to be changed.

**Comment by xiaozhuzhuzhu** [comment]
> Hi @xiaozhuzhuzhu - I think what you need is to instal ml-agents python package in [edit mode](https://stackoverflow.com/questions/23075397/python-how-to-edit-an-installed-package)...
> 
> `pip uninstall mlagents`
> 
> then
> 
> `pip install -e mlagents`

@Sohojoe thank you very much. And how does take it if I want use BC algorithm  which is in  \ml-agents-master\ml-agents\mlagents\trainers. I just change 'trainer: ppo' to 'trainer: bc' in 'trainer_config.yaml' file, but I got an error. The error is 'The trainer config contains an unknown trainer type for brain'
![image](https://user-images.githubusercontent.com/23623240/48967737-2f6b9700-f020-11e8-944c-79507995eb41.png)

**Comment by Sohojoe** [comment]
it should be `trainer: imitation` - https://github.com/Unity-Technologies/ml-agents/blob/e82450ab8304093871fd19b876a0f819d390e79d/docs/Training-Imitation-Learning.md

**Comment by xiaozhuzhuzhu** [comment]
> it should be `trainer: imitation` - https://github.com/Unity-Technologies/ml-agents/blob/e82450ab8304093871fd19b876a0f819d390e79d/docs/Training-Imitation-Learning.md

thank you very much!
