### ISSUE TITLE
Imitation Learning Documation (Offline)

### ISSUE THREAD

**Issue by cxbxmxcx** [Unity-Technologies/ml-agents#1438]
Working through the docs for Imitation Learning and noticed a few things missing or yet to be built.

I can only get **online** Imitation Learning to work and it appears **offline** is still in development?

Cheers,

Micheal

**Comment by awjuliani** [comment]
Hi @cxbxmxcx,

In the v0.6 release branch, offline BC should be functioning. Is there a particular error you are running into?

**Comment by cxbxmxcx** [comment]
I could not find the BC Teacher Helper script on the code I pulled earlier.  Just pulled the latest and the script is there.  However, now getting a null exception here:

`void FixedUpdate()
        {
            // Convert both bools into single comma separated string. Python makes
            // assumption that this structure is preserved. 
            myAgent.SetTextObs(recordExperiences + "," + resetBuffer);
        }`
Added the BC Teacher Helper to the TeacherBrain in the TennisIL scene.

**Comment by xiaomaogy** [comment]
@eshvk

**Comment by eshvk** [comment]
Offline BC works as of Release 0.7, we encourage you to try it and open a new issue if you have further question.
