### ISSUE TITLE
Frequent use of UnloadUnusedAssets

### ISSUE THREAD

**Issue by pengee** [Unity-Technologies/ml-agents#144]
In the Brain class, under GetObservationMatrixList method, there is a call to UnloadUnusedAssets. This garbage collection call, in our game at least, accounts for almost 12ms of time. Less I'm sure without an observed camera.

![capture](https://user-images.githubusercontent.com/33097976/32924871-af5dc940-caf3-11e7-90de-019cc7c032e8.PNG)

Is there a reason for this frequency?
Thanks!

**Comment by vincentpierre** [comment]
Hey @pengee, we call `UnloadUnusedAssets` in each step. This function must be called often enough or the application will run out of memory. You could call it at a lower frequency if it makes your game run smoother as long as the game does not crash. If you found a optimal frequency, we would be happy to know. Do not hesitate to submit a PR if you optimize the code, we would be happy to review it !

**Comment by pengee** [comment]
Thank you, @vincentpierre. Yes, I see now that running the game for 5 minutes accounts for over 30% memory increase without UnloadUnusedAssets call vs only 8% with (if unity profiler is correct), with our config. Though other things are sure to be contributing. We've made some changes that have yielded back the performance we lost at around the same memory gain. After a clean up will try PR.
Thanks!
