### ISSUE TITLE
Trainging with multi-core cpu

### ISSUE THREAD

**Issue by KarlSoHelloworld** [Unity-Technologies/ml-agents#1441]
I am now trying to train my robot. But I found that only one of the cpu is working.

After searching, I still cannot find a way to use all cores of my CPU. 

Are there any parameters/ configuration that I can change for help?

Many thanks.

**Comment by Sohojoe** [comment]
Hi @KarlSoHelloworld python is single threaded however Tensorflow and Unity will try and maximize cpu usage.

A couple of things you can do to improve training performance

1. If you have a modern CPU, make sure you are using a version of tensorflow that is optimized for the faster math instructions. Same goes for Numpy. There is a tutorial [here](
https://software.intel.com/en-us/articles/explore-unity-technologies-ml-agents-exclusively-on-intel-architecture) for intel cpu; as a rule, install Tensorflow and Numpy via Anaconda as it will use the optimized versions if it can. I have also used these python wheels:
  * mac:  https://github.com/vearutop/builds/releases/download/tensorflow-1.7.0-cp36-cp36m-macosx_10_13_x86_64.whl/tensorflow-1.7.0-cp36-cp36m-macosx_10_13_x86_64.whl
  * windows: https://github.com/fo40225/tensorflow-windows-wheel/blob/master/1.7.1/py36/GPU/cuda92cudnn71avx2/tensorflow_gpu-1.7.1-cp36-cp36m-win_amd64.whl

2. Increase the number of simultaneous agents - I've pushed this as high as 64 and I've seen a paper where they pushed the number of agents to 256 with only a small impact on training.

3. Train in headless mode if you don't use visual observations; add the flag `--no-graphics`

4. Always train on cpu - I've never found GPU to be faster

**Comment by superjayman** [comment]
What are python wheels? can you please explain how you use them and what difference it makes?

**Comment by KarlSoHelloworld** [comment]
Hi, @Sohojoe , thanks for your help. It is very clear and helpful.

I am now using anaconda && `--no-graphic`. I am goning to use more agents for trainning. 

Thank you.

**Comment by KarlSoHelloworld** [comment]
> What are python wheels? can you please explain how you use them and what difference it makes?

@superjayman Thanks for your reply. I think Sohojoe has answered my question. Anyway, thank you.
