### ISSUE TITLE
Tennis agents to observation / reward matching.

### ISSUE THREAD

**Issue by deeplearningrobotics** [Unity-Technologies/ml-agents#1442]
Hello, 

I am using Unity-2018.2.7f1 with ml-agents v0.5.0a with the Tennis agent.

The tennis agent has 18 arenas and thus 36 agents in total. By looking at the code in `HitWall` it is clear that if the ball drops both agents on the arena are done.

But I can not figure out how those 36 agents are matched to the 36 entries in the resulting reward etc. vectors. By looking at the dones vector one gets:

```
[(13, True), (23, True)]
[(20, True), (22, True)]
[(16, True), (34, True)]
[(17, True), (32, True)]
[(13, True), (23, True), (26, True), (28, True)]
```

So what is the formula that matches the agent to the reward and dones vector? I could not find it in the code and cannot derive it from my experiments.

**Comment by xiaomaogy** [comment]
@mmattar

**Comment by harperj** [comment]
Hi @deeplearningrobotics -- we also keep a list of unique agent IDs along with the reward and dones vectors.  What interface are you using to interact with the environment?
