### ISSUE TITLE
Where can I place AddReward() function?

### ISSUE THREAD

**Issue by Romaleks360** [Unity-Technologies/ml-agents#1443]
The title says it all. There are some situations when I want to call AddReward() on my custom events. For example, when an agent is killed by another agent, I want to add a negative reward for a killed one and a positive reward for a killer; this logic cannot be implemented inside AgentAction(). So is it safe to call AddReward anywhere else in an Agent-derived class?
Same question for the Done() method.

**Comment by Romaleks360** [comment]
One more question - why AddReward() and Done() are public but AddVectorObs() is private? What if I will make it public and call it from another script on CollectObservation()?

**Comment by ust007** [comment]
Yes, it is perfectly okay.
I am new to ml-agents but I have observed all the examples in the ml-agents package and AddReward function has been used in other places like OnCollisionEnter() and more. So according to my understanding its totally fine.
