### ISSUE TITLE
Animation issue

### ISSUE THREAD

**Issue by SestoAle** [Unity-Technologies/ml-agents#1446]
Hi,

I've got some annoying issues about frame rate and animations; when I run the game in inference mode, with max quality level, time scale 1 and target frame rate -1, all the animations of the game become frame rate dependent: If the frame rate is low, all my game become slower; if the frame rate is high, all the animations speed up. 

Am I doing something wrong? Is there some fix to this?

Thank you

**Comment by awjuliani** [comment]
Hi @SestoAle,

This is due to a line of code in `Academy.cs` which sets `Time.captureFramerate
 = 60`. You can remove this line and the dependence between frame rate and time scale.

**Comment by SestoAle** [comment]
Ok, it solves the issue. If I may ask, is there some reason why you used this line?

**Comment by awjuliani** [comment]
In situations where developers may not follow best-practices, that line ensures that the behavior of the game when the time-scale is increased remains consistent. We will be looking into making it a flag which can be changed in the next version of ML-Agents.

**Comment by SestoAle** [comment]
Ok, thanks you!
