### ISSUE TITLE
Not able to train the 3Dball 

### ISSUE THREAD

**Issue by tcy1998** [Unity-Technologies/ml-agents#1447]
When I type the command: mlagents-learn mlagents/trainers/learn.py --run-id=cub_1 --train 
in anaconda prompt it will show :

![1](https://user-images.githubusercontent.com/44712124/49045739-7d56db00-f197-11e8-9234-0c52c91542f1.PNG)
Then I click the button in the unity and in the anaconda prompt it will show 
![image](https://user-images.githubusercontent.com/44712124/49045787-a4151180-f197-11e8-99cf-0e5141707754.png)
And in the Unity it will show 
![image](https://user-images.githubusercontent.com/44712124/49045812-b7c07800-f197-11e8-8ab4-2b9971785ae7.png)
I follow the instruction on https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Getting-Started-with-Balance-Ball.md
I do  not know what it is going wrong.

**Comment by MarcoMeter** [comment]
It looks like that the Ball3DBrain is set to Internal.
Make sure to set the BrainType to external.

**Comment by tcy1998** [comment]
@MarcoMeter I think I already changed it in the inspector.
![image](https://user-images.githubusercontent.com/44712124/49092254-3a444880-f227-11e8-9344-d8c2d1f1476e.png)

**Comment by zongjingyao** [comment]
>UnityAgentsException: The Communicator was unable to connect. Please make sure the External process is ready to accept communication with Unity.

This error means Unity can't connect to your mlagents-learn process. You should run mlagents-learn first, and press the Play button when you see `INFO:mlagents.envs:Start training by pressing the Play button in the Unity Editor`.

Which version of Python are you using?
The doc says it supports Python 3.6.
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation-Windows.md.

**Comment by tcy1998** [comment]
> > UnityAgentsException: The Communicator was unable to connect. Please make sure the External process is ready to accept communication with Unity.
> 
> This error means Unity can't connect to your mlagents-learn process. You should run mlagents-learn first, and press the Play button when you see `INFO:mlagents.envs:Start training by pressing the Play button in the Unity Editor`.
> 
> Which version of Python are you using?
> The doc says it supports Python 3.6.
> https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation-Windows.md.

I am using Python3.6.7 in the anaconda. @zongjingyao

**Comment by LokoGD** [comment]
Hello, I'm facing the same problem.

I'm using Python 3.6 installed with Anaconda.

TensorFlow package installed in Python.

TFSharp plugin installed.

Trying to teach the default 3DBall env.

Error when trying to teach via Play button in Unity:

`UnityAgentsException: The Communicator was unable to connect. Please make sure the External process is ready to accept communication with Unity.
MLAgents.Batcher.SendAcademyParameters (MLAgents.CommunicatorObjects.UnityRLInitializationOutput academyParameters) (at Assets/ML-Agents/Scripts/Batcher.cs:83)
MLAgents.Academy.InitializeEnvironment () (at Assets/ML-Agents/Scripts/Academy.cs:320)
MLAgents.Academy.Awake () (at Assets/ML-Agents/Scripts/Academy.cs:227)`

Error when trying launching the build with Anaconda Prompt:

Inside build: ![Error inside Buildt](https://i.imgur.com/8eODtwn.png)
Inside build: ![Error inside Build with detail](https://i.imgur.com/TIJnmmZ.png)
Anaconda Prompt: ![Error in Anaconda Prompt](https://i.imgur.com/9I730qV.png)
Anaconda Prompt: ![Error in Detail](https://i.imgur.com/EB83gva.png)

Thanks in advance.

**Comment by harperj** [comment]
@tcy1998 It looks like in your case the command you're running is incorrect.  Rather than a training configuration file like [the one included with the repository](https://github.com/Unity-Technologies/ml-agents/blob/master/config/trainer_config.yaml).  Try running with an appropriate configuration file and see if that fixes your issue.

**Comment by harperj** [comment]
@LokoGD Are you trying to train within the editor or from a build?

**Comment by oddEventHorizon** [comment]
you are trying to run the training from the build but I think that you are expecting to train from the editor. 

Your 1st mistake is taht you haven't provided direct path to trainer_config.yaml file but to the folder where this file is located only
and 2nd mistake is that you are trying to launch training on a build which I don't know you have made or moved to a proper directory. 


Try this command: mlagents-learn ml-agents-master\config\**trainer_config.yaml** --run-id=your_run_name --train


If everything is OK you should shortly after see a prompt telling you to hit play button in the Unity. If you hit play you should see game/gym running as well training process initiated and visible in conda. 

Let me know if it helped.

**Comment by tcy1998** [comment]
> you are trying to run the training from the build but I think that you are expecting to train from the editor.
> 
> Your 1st mistake is taht you haven't provided direct path to trainer_config.yaml file but to the folder where this file is located only
> and 2nd mistake is that you are trying to launch training on a build which I don't know you have made or moved to a proper directory.
> 
> Try this command:
> mlagents-learn **ml-agents-master\config\trainer_config.yaml** --run-id=your_run_name --train
> 
> If everything is OK you should shortly after see a prompt telling you to hit play button in the Unity. If you hit play you should see game/gym running as well training process initiated and visible in conda.
> 
> Let me know if it helped.
@oddEventHorizon It did help, but now I face the similar problem as the @LokoGD had. And I also do not know which button it ask me to click. Is the play button in the Unity? I have tried it, but it does not seems working. 
![capture](https://user-images.githubusercontent.com/44712124/50454942-56173900-0910-11e9-988f-38eb9d6b6ff9.JPG)
![capture](https://user-images.githubusercontent.com/44712124/50454974-a2627900-0910-11e9-868d-27b4e6395092.JPG)

**Comment by tcy1998** [comment]
I have tried the button, but it still say that the environment wait too long to respond. Anyway, I used the old version of the ml-agents. And I could train the 3dball model now.@oddEventHorizon Thanks so much.

**Comment by tcy1998** [comment]
I think I figure it out now. I think the brain type in the ball3dacademy should be 3dballlearning instead of 3dballplayer.

**Comment by harperj** [comment]
Glad you've managed to resolve the problems you were running into tcy1998.  I'm going to close this issue since it's completed but please feel free to reopen or start a new issue if you have any more trouble.

**Comment by dmkaner** [comment]
Make sure "control" is unchecked in ball3dacademy
