### ISSUE TITLE
Test in linux, SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by OneFiveChen** [Unity-Technologies/ml-agents#1452]
I follow the guide [Training on Amazon Web Service](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-on-Amazon-Web-Service.md) and try to run in my own server.
When I test it in python:
`from mlagents.envs import UnityEnvironment`

Error shows that:
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "mlagents/envs/__init__.py", line 1, in <module>`
`    from .environment import *`
`  File "mlagents/envs/environment.py", line 233`
`    def reset(self, config=None, train_mode=True) -> AllBrainInfo:`
`                                                                                ^`
`SyntaxError: invalid syntax`

(^ under "->")

It works in Windows but now it becomes SyntaxError: invalid syntax in Ubuntu. And I open `environment.py`, line 233 looks like nothing wrong.

**Comment by delassus** [comment]
I have the same issue. How did you resolve it?

**Comment by OneFiveChen** [comment]
@delassus your python version may be 2.x. `->` only supports for 3.x
