### ISSUE TITLE
tf.argmax doesn't work in tensorflow>=1.3

### ISSUE THREAD

**Issue by matsui-k20xx** [Unity-Technologies/ml-agents#146]
I got the error below in Unity Editor, Mac standalone, and Android when I run a model including tf.argmax trained in tensorflow r1.3. There is no problem with tensorflow r1.2. 

I guess this error happens because the TensorFlowSharp that is used by the ML-Agents package in [this doc](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Making-a-new-Unity-Environment.md) is outdated. I found that the 'output_type' argument is added in tensorflow r1.3 and the latest TensorFlowSharp has followed this change. 

So it is helpful that you update the package or provide a guide to make a package with newer TensorFlowSharp. 

the error:

TFException: NodeDef mentions attr 'output_type' not in
 Op<name=ArgMax; signature=input:T, dimension:Tidx -> output:int64; 
attr=T:type,allowed=[DT_FLOAT, DT_DOUBLE, DT_INT64, DT_INT32, DT_UINT8, DT_UINT16, DT_INT16, DT_INT8, DT_COMPLEX64, DT_COMPLEX128, DT_QINT8, DT_QUINT8, DT_QINT32, DT_HALF]; 
attr=Tidx:type,default=DT_INT32,allowed=[DT_INT32, DT_INT64]>; NodeDef:
ArgMax = ArgMax[T=DT_FLOAT, Tidx=DT_INT32, output_type=DT_INT32](add_1, ArgMax/dimension).

**Comment by awjuliani** [comment]
Hi @matsui-k20xx,

Thanks for pointing this out. We will update the TensorFlowSharp packages to the latest version of TF in order to ensure compatibility.

**Comment by lagidigu** [comment]
Seem to still have the same error...

**Comment by lagidigu** [comment]
Hi, I still have the same issue, currently using TF 1.4.1. Is there a way to get around this?

**Comment by matsui-k20xx** [comment]
When I tested, argmax only worked in TF <= v1.2.  I think this problem is because of TensorFlowSharp version, but I don't know if it has been updated.

**Comment by lagidigu** [comment]
It does work with Tensorflow 1.0! Thanks!
