### ISSUE TITLE
Is 'mlagents-learn' missing in the latest version?

### ISSUE THREAD

**Issue by LiJiaJim** [Unity-Technologies/ml-agents#1463]
Recently I can't find Getting-the script 'mlagents-learn' in current version of this project, along with the folder 'Python', but they are mentioned in Started-with-Balance-Ball.md and many other toturials online. Does this mean I need to run this example in a different way which is not updated in the document yet? How can I start trainning the program now?

**Comment by xiaomaogy** [comment]
Hi @LiJiaJim , as of v0.5 of ml-agents, we no longer have python/ directory. If you are following a old documentation, you might see that 'Python' folder. Please refer to our latest documentation to get 'ml-agents-learn' to work.

**Comment by LiJiaJim** [comment]
> 
> 
> Hi @LiJiaJim , as of v0.5 of ml-agents, we no longer have python/ directory. If you are following a old documentation, you might see that 'Python' folder. Please refer to our latest documentation to get 'ml-agents-learn' to work.

Well the problem is the script 'ml-agents' is nowhere in this project but according to the lastest document, I need this script to configure both training and inference phases.
Here is what the document says: 
![default](https://user-images.githubusercontent.com/30380504/49772578-bdd25f00-fd28-11e8-8e24-05a564362e54.png)

**Comment by xiaomaogy** [comment]
Hi @LiJiaJim, so the mlagents-learn script will be installed to your PATH once you've did the 'pip install .' to install the mlagent python package. You won't find a script named mlagents-learn within the repo.
