### ISSUE TITLE
tf.miltinomial does not work in Android

### ISSUE THREAD

**Issue by matsui-k-dmj** [Unity-Technologies/ml-agents#147]
tf.miltinomial does not work in Android, though it works in Unity editor and Standalone in mac and linux. The error message is below. I tried this in tensorflow 1.0, 1.2 and 1.3 and Android APK 23 and 24. I dont know if this error is due to ml-agents. I also reported this as an Issue of tensorflow [here](https://github.com/tensorflow/tensorflow/issues/14150).

TFException: No OpKernel was registered to support Op 'Multinomial' with these attrs. Registered devices: [CPU], Registered kernels:<no registered kernels>
[[Node: multinomial/Multinomial = Multinomial[T=DT_FLOAT, seed=0, seed2=0](dense_2/MatMul, multinomial/Multinomial/num_samples)]]
at TensorFlow.TFStatus.CheckMaybeRaise (TensorFlow.TFStatus incomingStatus, System.Boolean last) [0x0004a] in <252020d87a4e4581ad2cfe3f9cc7a0ac>:0

**Comment by awjuliani** [comment]
HI @matsui-k20xx,

Thanks for pointing this out. It is likely that the TensorFlow binary for Android does not contain the `Multinomial` op. It is possible to build TensorFlow on Android manually with the desired set of ops. See here: https://www.tensorflow.org/mobile/android_build . Given that `Multinomial` is used in our PPO implementation, it is something we will add to the default TF Android binary.

**Comment by mmattar** [comment]
Resolving this as we have fixed this in v0.3 of ML-Agents. Let us know if you have any questions.
