### ISSUE TITLE
Problem with ppo

### ISSUE THREAD

**Issue by Semih67** [Unity-Technologies/ml-agents#1474]
I want to code a game where I have three enemys which have the ability of ai. And there will be a player. The player and the enemys can shoot. So the enemys will rewarded if they shoot the player. So my questions are: 

1. Do I have to use the ppo file to train the agents?

2. Does it matter which game is it to use the ppo? Can I use it always for every game I'm wirting?

3. I wanted to write my own tensorflow based code. Do you have a tutorial where I can look into? I have 
    looked to many tensorflow tutorials but I couldn't find one for unity.

**Comment by xiaomaogy** [comment]
Hi @Semih67 , when you use ml-agents toolkit, we don't recommend beginner users to look into our ppo and tensorflow related code. You should use our https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Basic-Guide.md to get started. Once you get more familiar with the toolkit, you can start look into our python code to do small tweaks yourself.
