### ISSUE TITLE
Question to internal mode

### ISSUE THREAD

**Issue by Semih67** [Unity-Technologies/ml-agents#1478]
I'm not sure now. I have read your documentations and I'm a little bit confused. So after I trained my model with the external mode I'm switching to internal. And my question is now: is it still learning if it's configured to the internal mode? If not, why is it still a brain type? I mean it isn't a brain if it's not learning.

**Comment by xiaomaogy** [comment]
Hi @Semih67 
1. When you switch to internal mode, it will not be learning. 
2. If it is not learning, you can still call it a brain, a brain that's not learning.
