### ISSUE TITLE
How can I use the reset parameters?

### ISSUE THREAD

**Issue by ConorZAM** [Unity-Technologies/ml-agents#149]
I'm having loads fun using this, you guys have done an amazing job!

I am unsure what these parameters do. Will they be updated during training depending on the reward progress? I see you use them in the grid world example but I can't seem to find anywhere that changes their values.

I'm going for a similar training exercise to the one used by Google to train their AI to walk so I'm hoping to use the reset parameters to add a curriculum to the obstacle heights in my environment.

**Comment by awjuliani** [comment]
Hi @ConorZAM,

Glad you are enjoying using it! The reset parameters are designed to allow for dynamically adjusting aspects of the environment from python. The curriculum learning scenario is one of the main potential use-cases. Our current version of PPO doesn't support curriculum learning, but we are close to releasing a new version that does. If you want to try it out, you can use the `development` branch of the repo, and follow the instructions here: https://github.com/Unity-Technologies/ml-agents/blob/development/docs/curriculum.md 

Hopefully that is helpful to you!
