### ISSUE TITLE
'UnityEnvironment' object has no attribute 'vector_action_space_size' Error while running PPO.py.

### ISSUE THREAD

**Issue by jfrank94** [Unity-Technologies/ml-agents#1499]
I'm getting this error when trying to run the PPO algorithm for the 3DBall environment. I'm using the PPO algorithm from the older version, and I made a small modification to match up with the current version of ml-agents. I changed create_agent_model to PPOModel. 

Notes: I'm running the latest ml-agents version, and I know the PPO.py file does not exist with this file, so would I have to create a newer algorithm to run the refined PPO model provided? 

Here is the full error code below: 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-770edec8d4a8> in <module>
     20                                h_size=hidden_units, epsilon=epsilon,
     21                                beta=beta, max_step=max_steps,
---> 22                                normalize=normalize, num_layers=num_layers)
     23 
     24 is_continuous = (env.brains[brain_name].action_space_type == "continuous")

~/UnityProjects/ml-agents-master/ml-agents/mlagents/trainers/ppo/models.py in __init__(self, brain, lr, h_size, epsilon, beta, max_step, normalize, use_recurrent, num_layers, m_size, use_curiosity, curiosity_strength, curiosity_enc_size, seed)
     27         :param m_size: Size of brain memory.
     28         """
---> 29         LearningModel.__init__(self, m_size, normalize, use_recurrent, brain, seed)
     30         self.use_curiosity = use_curiosity
     31         if num_layers < 1:

~/UnityProjects/ml-agents-master/ml-agents/mlagents/trainers/models.py in __init__(self, m_size, normalize, use_recurrent, brain, seed)
     27             self.m_size = 0
     28         self.normalize = normalize
---> 29         self.act_size = brain.vector_action_space_size
     30         self.vec_obs_size = brain.vector_observation_space_size * \
     31                             brain.num_stacked_vector_observations

AttributeError: 'UnityEnvironment' object has no attribute 'vector_action_space_size'

**Comment by vincentpierre** [comment]
Hi @jfrank94 If you have modified the PPO training algorithm, I am not sure I will be able to help you debug this error. It seems to me that you are calling `vector_action_space_size` on an Environment instead of a Brain. I think when you initialized the Model, you may have passed `env` instead of `brain` to the constructor. Can you confirm that you can used the appropriate version of PPO with the BalanceBall ?

**Comment by jfrank94** [comment]
@vincentpierre I did pass the environment instead of the brain. How would I instantiate the brain?

The version of PPO I'm using is from 2016. I can't confirm the actual version number, but it does have the PPO paper linked at the top of the jupyter notebook. Here is the [link](https://github.com/marcosfede/Reinforcement-Landing/blob/master/python/PPO.ipynb) to the version I'm using.

**Comment by vincentpierre** [comment]
I have never seen the repository that you linked to, it seems to be using an old implementation of our PPO. I do not remember which version this corresponds to. I would say `0.2.0` but I am not sure. It seems this repository contains all of the files from a previous version so I would suggest using either that repository or ml-agents (At whichever version you see fit) but not the two at the same time as ml-agents is **not** backward compatible.

**Comment by jfrank94** [comment]
@vincentpierre Alright, but is there a similar PPO algorithm in the current version of ml-agents?

**Comment by vincentpierre** [comment]
Yes, although there is no python notebook. The way you use it is through the command line `mlagents-learn` as explained [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-ML-Agents.md#training-with-mlagents-learn) and the PPO code is in this [folder](https://github.com/Unity-Technologies/ml-agents/tree/master/ml-agents/mlagents/trainers/ppo)

**Comment by jfrank94** [comment]
Thanks @vincentpierre! I found that link a few moments ago. However, I'm having another issue. When I execute that command to train it (and it does work!), I'm not seeing any output for the summaries and models directories. I've let it trained for about 5 minutes before stopping, and there are no stats being written.

**Comment by vincentpierre** [comment]
Can you send the console output ? I think this might be either because no brains are set to training mode or because the environment crashed right after initialization.

**Comment by jfrank94** [comment]
@vincentpierre 

`INFO:mlagents.envs:
'Ball3DAcademy' started successfully!
Unity Academy name: Ball3DAcademy
        Number of Brains: 1
        Number of Training Brains : 1
        Reset Parameters :
		
Unity brain name: 3DBallLearning
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 8
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): [2]
        Vector Action descriptions: , 
2018-12-17 13:40:28.831457: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:mlagents.envs:Hyperparameters for the PPO Trainer of brain 3DBallLearning: 
	batch_size:	64
	beta:	0.001
	buffer_size:	12000
	epsilon:	0.2
	gamma:	0.995
	hidden_units:	128
	lambd:	0.99
	learning_rate:	0.0003
	max_steps:	5.0e4
	normalize:	True
	num_epoch:	3
	num_layers:	2
	time_horizon:	1000
	sequence_length:	64
	summary_freq:	1000
	use_recurrent:	False
	summary_path:	./summaries/cob_1-0_3DBallLearning
	memory_size:	256
	use_curiosity:	True
	curiosity_strength:	0.01
	curiosity_enc_size:	128
	model_path:	./models/cob_1-0/3DBallLearning`

**Comment by vincentpierre** [comment]
Was an error raised in the environment ?

**Comment by jfrank94** [comment]
There were no errors raised in the environment while training.

**Comment by vincentpierre** [comment]
Are you sure the platforms have the right brain ? What version are you on ? Are they using the PlayerBrain or the Learning Brain ?

**Comment by jfrank94** [comment]
@vincentpierre I am using Learning Brain with the control box ticked for external learning.

**Comment by vincentpierre** [comment]
Is **each** of the platform connected to a Learning Brain ?

**Comment by jfrank94** [comment]
@vincentpierre It works now! Thank you so much. Just one more question before closing this issue, should I deselect the control box if I wanted to use Internal Learning, or would I have to choose another brain altogether. In the previous version, Internal Learning was an option.

**Comment by vincentpierre** [comment]
To use inference/internal mode, as of v0.6 you need to uncheck the control checkbox and make sure you have the right model in the Learning Brain.

**Comment by jfrank94** [comment]
Okay, thanks a lot again!
