### ISSUE TITLE
PPO: JSONDecodeError

### ISSUE THREAD

**Issue by chujun320** [Unity-Technologies/ml-agents#15]
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-4-8fafc29f76c4> in <module>()
     37             info = env.reset(train_mode=train_model)[brain_name]
     38         # Decide and take an action
---> 39         new_info = trainer.take_action(info, env, brain_name)
     40         info = new_info
     41         trainer.process_experiences(info, time_horizon, gamma, lambd)

D:\Unity Projects\ml-agents-master\python\ppo\trainer.py in take_action(self, info, env, brain_name)
     51         self.stats['value_estimate'].append(value)
     52         self.stats['entropy'].append(ent)
---> 53         new_info = env.step(actions, value={brain_name: value})[brain_name]
     54         self.add_experiences(info, new_info, epsi, actions, a_dist, value)
     55         return new_info

D:\Unity Projects\ml-agents-master\python\unityagents\environment.py in step(self, action, memory, value)
    336             self._conn.send(b"STEP")
    337             self._send_action(action, memory, value)
--> 338             return self._get_state()
    339         elif not self._loaded:
    340             raise UnityEnvironmentException("No Unity environment is loaded.")

D:\Unity Projects\ml-agents-master\python\unityagents\environment.py in _get_state(self)
    204         self._data = {}
    205         for index in range(self._num_brains):
--> 206             state_dict = self._get_state_dict()
    207             b = state_dict["brain_name"]
    208             n_agent = len(state_dict["agents"])

D:\Unity Projects\ml-agents-master\python\unityagents\environment.py in _get_state_dict(self)
    171         state = self._conn.recv(self._buffer_size).decode('utf-8')
    172         self._conn.send(b"RECEIVED")
--> 173         state_dict = json.loads(state)
    174         return state_dict
    175 

d:\program files\python36\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

d:\program files\python36\lib\json\decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

d:\program files\python36\lib\json\decoder.py in raw_decode(self, s, idx)
    353         """
    354         try:
--> 355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
    357             raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting ',' delimiter: line 98 column 13 (char 1460)

**Comment by romerocesar** [comment]
Thanks for trying it out! can you give us more context to help us reproduce the issue? what notebook and on what platform are you running? Have you changed anything from the examples provided?

**Comment by chujun320** [comment]
My examples is ok now! The issue is due to rename the windows exe! Thanks!

**Comment by vincentpierre** [comment]
Hey, what branch are you on and what commit ? 
On what environment are you getting this error ?
Which notebook or script were you running ?
Any piece of information will help.
