### ISSUE TITLE
Doubt: To use LSTM do I need to increment the Stacked Vector?

### ISSUE THREAD

**Issue by icaro56** [Unity-Technologies/ml-agents#1504]
In addition to setting use_recurrent to true, to use LSTM do I need to increment the Stacked Vector?

**Comment by LeSphax** [comment]
No, the LSTM is independent of the stacked vectors.
I think if you increase the stacked vector to N then the agent will have as input the current observation + N -1 past observations.

While if you activate LSTM the agent will get the current observation and some past information that he chose to keep in memory as input. (You can choose the size of the memory in the trainer_config.yaml with `memory_size`)

You can also combine both and the agent will have the current observation, N -1 past observations some past information that he chose to keep in memory as input.

But maybe what you are actually looking for is to change the length of the sequence used during backpropagation and you can control that with the `sequence_length` parameter also in trainer_config.yaml.

**Comment by icaro56** [comment]
Thank you by explanation @LeSphax .

I am trying to set good hyperparameters to train with LSTM. But the training is very slow. So, because of that, I want to remove Stacked Vector and/or decrease all hyperparameter to fast the training.

**Comment by LeSphax** [comment]
Yes in general LSTMs are much slower to train. Combining stacked vectors with it will definitely make it even slower so I wouldn't combine both.

Reducing the hyperparameters, especially sequence length, will have a big impact as well but it could also impact the agents performance. You will have to experiment :)

But in general, I think reducing sequence length should make it harder for memories to last longer and reducing memory size reduces the amount of information the agent can remember.
