### ISSUE TITLE
sequence_length parmeter seems to be used not only when RNN is true

### ISSUE THREAD

**Issue by ishaybe** [Unity-Technologies/ml-agents#1506]
seems like sequence_length is used always.
is this a bug?

def is_ready_update(self):
        """
        Returns whether or not the trainer has enough elements to run update model
        :return: A boolean corresponding to whether or not update_model() can be run
        """
        size_of_buffer = len(self.training_buffer.update_buffer['actions'])
        return size_of_buffer > max(int(self.trainer_parameters['buffer_size'] / self.policy.sequence_length), 1)

**Comment by awjuliani** [comment]
Hi @ishaybe,

When RNNs are not used, the sequence length is set to `1` by default, so that it essentially disappears from calculations like these. As such, it is not a bug.
