### ISSUE TITLE
My migration from 0.5 to 0.6

### ISSUE THREAD

**Issue by louis030195** [Unity-Technologies/ml-agents#1507]
In case some others are struggling with the migration, problems i have encountered:
- ml-agents 0.6 seems to require to turn ON unsafe code
- I had to reimport TFsharp plugin
- Heuristic classes only inherits from Decision now and not from MonoBehaviour and Decision

Everything went well except these :+1:

**Comment by awjuliani** [comment]
Hi @louis030195,

Please let us know if @Sohojoe's response was able to fix your issue.

**Comment by louis030195** [comment]
These issues are fixed, thanks !
