### ISSUE TITLE
Problem with migration from v0.5 to v0.6: How to  update Python API?

### ISSUE THREAD

**Issue by oseq** [Unity-Technologies/ml-agents#1509]
Hello i have problem during migration, i pulled v0.6 version from git and everything works fine until i try to learn new model.

i have error on anaconda side:
> mlagents.envs.exception.UnityEnvironmentException: The API number is not compatible between Unity and python. Python API : API-5, Unity API : API-6.
> Please go to https://github.com/Unity-Technologies/ml-agents to download the latest version of ML-Agents.

So i am using newest version of ml-agents, so how to update Python API?

**Comment by 13Flo** [comment]
I had the same issue. Doing this fixed it:
'cd C:\Downloads\ml-agents\ml-agents
pip install .'

**Comment by awjuliani** [comment]
Hi @oseq, as @13Flo mentioned, you will need to re-install the python package in order to have the latest version of the API. Please let us know if their fix works for you.

**Comment by 13Flo** [comment]
@oseq  You're welcome. You might want to close the issue now then ;)
