### ISSUE TITLE
Help on deciding the input state

### ISSUE THREAD

**Issue by GingerDane** [Unity-Technologies/ml-agents#151]
Hi Everybody

Was really pleased with Unity, when I heard of this SDK. It is providing us all with many new oppertunities!
I have been playing around, first with the balancing ball and then my own project. However, with my own project I cannot get proper training and I do not understand the behavior of the Mean Reward in the training. Before sharing the Tensorboard files, I would like to ask about the correct input states and maybe I can work from that.

Goal for the NN: Detect when a conductor conduct a beat. In my simple implementation, it is when a ball is in its highest position and lowest in a log (sin(t)) movement.

State: Every FixedTimeStep the ball is moved and the new position is saved in a List of earlier positions, along with the current time (seconds from start).
When the amount of positions are under 8, then only 0 are given as inputs for all input nodes.
When more positions exist, then 8 is picked (spread out as evenly as possible in time). These 8 are used to calculate a relative scaled position. The y coordinate and the time for that position are then used as the state. A total of 16 states. I have though of adding a time state as well, e.g. expected length of the beat in seconds.

Reward function: Two actions exist, one for detecting the top and one for the bottom.
When Action TOP is triggered within +/- 0.05 seconds of the toppoint, the reward is set to 1.
When Action DOWN is triggered within +/- 0.05 seconds of the lowestpoint, the reward is set to 1.
If one of the actions is triggers outside of this gab, then the reward is set to -0.25f.
No other rewards is given.

Episode length: The episodes are kept short. When the ball has completed just over one beat (about a second), then everything is reset.

Any advice regarding if I have chosen the correct states, reward function and/or episode length will be much appreciated. If anyone can see anything else wrong in my short presentation, then this is velcome as well =)

Best regards and good luck to you all in your own neural network adventures =)

**Comment by awjuliani** [comment]
Hi @GingerDane,

Perhaps you can have a third action which corresponds to taking no action. This way the agent will not be penalized for taking an action in the intermediate period where a positive reward is not possible. Also, depending on the number of steps between peak or valley, you may want to scale the negative reward down, as it might be overpowering the positive rewards.

Hope that is helpful.

**Comment by GingerDane** [comment]
Hi @awjuliani 

Thanks for the input =) I will try scaling the reward, so if the action is triggered all the time, then it will still be overall positive.

Do you think that the way I create the state is a valid option? If so, then I will verify it once again and start a long training session again =)

Best regards
