### ISSUE TITLE
Is it possible to have multi Teachers (agents) in Imitation Learning training?

### ISSUE THREAD

**Issue by icaro56** [Unity-Technologies/ml-agents#1517]
Is it possible to have multi Teachers (agents) in Imitation Learning training?

Or should I just have 1 teacher agent?

**Comment by awjuliani** [comment]
Hi @icaro56 

It is currently possible only to have a single teacher.

**Comment by icaro56** [comment]
@awjuliani is it currently possible only to have a single teacher agent or a single teacher brain?

PS: I am using the ML-Agent version 0.5

**Comment by awjuliani** [comment]
Using online behavioral cloning, you can only use a single agent connected to a single brain to collect demonstrations.

**Comment by icaro56** [comment]
But, I am using many agents that read a replay file. The brain of them is a heuristic brain.

**Comment by icaro56** [comment]
The heuristic brain is the Specialist Brain.
