### ISSUE TITLE
Scripts not compiling in 0.6v

### ISSUE THREAD

**Issue by ValcoEskex** [Unity-Technologies/ml-agents#1518]
I migrated to 0.6v but i get a lot of errors (1245) in VisualStudio. I tried to run all the trubleshooting that i did with the 0.5v but it doesnt help at all. The most frequent error is the CS0229.

**Comment by awjuliani** [comment]
Hi @ValcoEskex 

Can you please provide a few more details about the specific errors you are encountering?

**Comment by ValcoEskex** [comment]
Of course. There are 9 errors that appear several times. Those errors are:

CS0115 no suitable method found to override
CS0756 A partial method may not have multiple defining aclarations
CS0229 Ambiguity between two variables (mainly)
CS0579 Duplicated attributes
CS0263 Partial declarations of 'brain' must not specify different base classes
CS0121 The vall is ambiguius between two methods or properties
CS0101 The namespace '----' akready contains a Assembly.CSharp definition for'----'
CS0102 The type '----' already contains a Assembly CSharp definition for '----'
CS0111 Type '----' already defines a member called '----' with the same parameter types

**Comment by oddEventHorizon** [comment]
I haven't reported this issue but I reported #1511 and I don't think they are related. Errors look differently.

**Comment by awjuliani** [comment]
Due to inactivity, I am closing this issue for now. Please feel free to re-open if you are still having this issue with ML-Agents v0.7.
