### ISSUE TITLE
Executable is running, but Not Training

### ISSUE THREAD

**Issue by OneFiveChen** [Unity-Technologies/ml-agents#1521]
When I use `mlagents-learn` to train , the executable can run and Agents in the scene can take actions ,but the terminal shows me that `Not Training`
```
INFO:mlagents.trainers: test_VisSoccer_1-0: Brain: Step: 0. No episode was completed since last summary. Not Training.
INFO:mlagents.trainers: test_VisSoccer_1-0: Brain: Step: 0. No episode was completed since last summary. Not Training.
INFO:mlagents.trainers: test_VisSoccer_1-0: Brain: Step: 0. No episode was completed since last summary. Not Training.
```
I use visual observation as input. Memory increases and quickly runs out.

Everything ok last week. v0.6 released 6 days ago, is that the reason?
My ml-agents version is 0.5.

**Comment by OneFiveChen** [comment]
@awjuliani  I build the sample scence: 3dball and train it. It also have the same problem
```
INFO:mlagents.trainers: test_3dball_1-0: Ball3DBrain: Step: 0. Mean Reward: 0.250. Std of Reward: 0.431. Not Training.
INFO:mlagents.trainers: test_3dball_1-0: Ball3DBrain: Step: 0. Mean Reward: 0.268. Std of Reward: 0.440. Not Training.
INFO:mlagents.trainers: test_3dball_1-0: Ball3DBrain: Step: 0. Mean Reward: 0.264. Std of Reward: 0.413. Not Training.
INFO:mlagents.trainers: test_3dball_1-0: Ball3DBrain: Step: 0. Mean Reward: 0.244. Std of Reward: 0.407. Not Training.
```

And I check my `Done()` function and `max steps`,  it's not the origin of the problem

**Comment by awjuliani** [comment]
@OneFiveChen 

I just realized that you likely forgot the `--train` argument when launching `mlagents-learn`. That is why `Not Training` is appearing.

**Comment by OneFiveChen** [comment]
@awjuliani I got that. A few days no training , I forget the command... Thank u

**Comment by prgmrjeong** [comment]
@awjuliani thank you for ur answer :)

**Comment by SaiAvinashDamera** [comment]
> @OneFiveChen
> 
> I just realized that you likely forgot the `--train` argument when launching `mlagents-learn`. That is why `Not Training` is appearing.

this solved my problem
