### ISSUE TITLE
How to combine multi-brains for simple agent?

### ISSUE THREAD

**Issue by yumianhuli2** [Unity-Technologies/ml-agents#1523]
Hello!
For example, I have two brains trained from two different scenarios fpr the same agent, and I got two bytes files.So My question is how to combine two brains(2 tensorflow models) into one brain(one tensorflow model)?
Thank U!

**Comment by awjuliani** [comment]
HI @yumianhuli2 

Thank you for your question. The way to do this is to actually keep two brains, but use the `GiveBrain()` function on the agent to swap out the brains based on some logic you might have that determines which brain is the best to use at a given time.

**Comment by yumianhuli2** [comment]
> HI @yumianhuli2
> 
> Thank you for your question. The way to do this is to actually keep two brains, but use the `GiveBrain()` function on the agent to swap out the brains based on some logic you might have that determines which brain is the best to use at a given time.

Thank U! Got it!
