### ISSUE TITLE
Training doesnt get past loading hyperparameters

### ISSUE THREAD

**Issue by KlamydiaKenneth** [Unity-Technologies/ml-agents#1524]
So i have an issue where my brain doesnt get past loading the hyperparameters. It actually never really starts the training, heres a picture:
![image](https://user-images.githubusercontent.com/43172529/50345368-1b3b8c80-052f-11e9-9e9d-3be927679335.png)
Im 100% i have messed something up somewhere, but im not sure where. Does anyone have a solution or a suggestion?

**Comment by ThrusterJon** [comment]
Did you remember to check the "Control" toggle next to the Learning brain on your academy?

**Comment by KlamydiaKenneth** [comment]
> Did you remember to check the "Control" toggle next to the Learning brain on your academy?

oh god damn it, i completely forgot about that. thank you my man

**Comment by awjuliani** [comment]
Glad you were able to resolve the issue.
