### ISSUE TITLE
On Demand Decisions leads to No episode was completed since last summary.

### ISSUE THREAD

**Issue by atticdweller** [Unity-Technologies/ml-agents#1525]
It seems that when using a Learning Brain with continuous output and on demand decisions that an episode is never completed. 

I made a sample project to test the most minimal setup possible. Here is my agent code: 
```
public class OnDemandAgent : Agent
{
    public override void InitializeAgent()
    {
        Debug.Log("InitializeAgent");
    }

    public override void CollectObservations()
    {
        AddVectorObs(1);
        Debug.Log("CollectObservations");
    }

    public override void AgentAction(float[] vectorAction, string textAction)
    {
        Debug.Log(vectorAction[0]);
        Done();
        AddReward(Random.Range(-1, 1));
        Debug.Log("Agent Action");
    }

    public override void AgentReset()
    {
        Debug.Log("AgentReset");
    }

    public override void AgentOnDone()
    {
        Debug.Log("AgentOnDone");
    }

    public void TakeStep()
    {
        RequestDecision();
        Debug.Log("TakeStep");
    }
}
```
Reset On Done is checked and On Demand Decisions is checked.
I have a single button in the scene, which in OnClick calls TakeStep(). 
This is my OnDemandAcademy: 
```
public class OnDemandAcademy : Academy
{
    public override void AcademyReset()
    {
    }

    public override void AcademyStep()
    {
    }
}
```
This is my brain setup:
```
OnDemandBrain:
    batch_size: 32
    normalize: false
    num_layers: 1
    hidden_units: 20
    beta: 5.0e-3
    gamma: 0.9
    buffer_size: 256
    max_steps: 5.0e5
    summary_freq: 10
    time_horizon: 3
```

When I enter training in the editor with Time Scale =1, I click the button to take steps a few times. I can see in the Console log what is called. The sequence is:
Initialize Agent
Agent Reset
Take Step
Collect Observations
Agent Action
Agent Reset

However even after hundreds of steps I keep getting "No episode was completed since last summary. Training."

Any advice on how to get it to continue training? I've had success with getting all of the example scenes working, but none of the examples use an agent that uses both On Demand Decisions and Continuous Action space.

**Comment by awjuliani** [comment]
Hi @atticdweller 

It looks like your episodes only last a single step. Can you try again with episodes that involve more than one step? There may be a bug for the single step case, which is causing no episode to be registered.

**Comment by atticdweller** [comment]
Howdy @awjuliani 

I modified my code to look like this: 
```
bool run = false;
    public override void AgentAction(float[] vectorAction, string textAction)
    {
        Debug.Log(vectorAction[0]);
        if (run)
        {
            run = false;
            Done();
        }
        else
        {
            run = true;
        }
        AddReward(Random.Range(-1, 1));
        Debug.Log("Agent Action");
    }
```

It now takes 2 steps to complete an episode. Now it's totally working. I'm getting training rewards visible in console and TensorBoard. Thanks for your help!

Is there any plan to allow for single step episodes in the future?

**Comment by awjuliani** [comment]
Hi @atticdweller, I am glad you got it working! We've been aware of this issue, and do indeed plan to resolve it in a future version of ML-Agents. I'll add it to our internal feature tracker, and close this issue for now.
