### ISSUE TITLE
Directory '.' is not installable. File 'setup.py' not found.

### ISSUE THREAD

**Issue by IamJustaguy1** [Unity-Technologies/ml-agents#1529]
i have followed the documentation guide on how to install and i am on the last step where the document states to put in the command pip install -e . into the anaconda prompt but i get the error message
Directory '.' is not installable. File 'setup.py' not found.

**Comment by taesiri** [comment]
It seems you are not in the correct directory. `setup.py` is located in [``ml-agents/ml-agents/``](https://github.com/Unity-Technologies/ml-agents/tree/master/ml-agents) directory.

**Comment by IamJustaguy1** [comment]
hello taesiri  well i have one more question how would i change the directory to ml-agents/ml-agents/
i am new to this kind of setup thank you in advance

**Comment by taesiri** [comment]
The quick answer is just do ``cd`` into where you've downloaded the ml-agents. If you are on windows, do it on ``Command Prompt`` or ``Anaconda command prompt``, if you are on MacOS or Linux, open ``Terminal`` and do so.  An example of that would be ``cd /path-to-ml-agents-folder/ml-agents/ml-agents/``


I strongly recommend watching some online tutorials on basic terminal usage before anything else. There is a good tutorial [here](https://github.com/adaptlearning/adapt_authoring/wiki/Just-Enough-Command-Line-for-Installing), but you can search on Youtube as well.

**Comment by IamJustaguy1** [comment]
thank you  this has helped alot  i cannot say how much this helped me thanks again

**Comment by unityjeffrey** [comment]
hi @IamJustaguy1 it seems that this was solved so will close out the ticket.  @taesiri - thank you so much for assisting!
