### ISSUE TITLE
Pressing Play after setup on demo crashes Unity editor

### ISSUE THREAD

**Issue by pixelknight1** [Unity-Technologies/ml-agents#1530]
Looking to just get the demo running after setup.  Would like / appreciate help and information.

After setup and verifying python things work according to installation documentation:
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md

0) ENABLE_TENSORFLOW is enabled in player settings
1) Go I to first demo scene 3DBall.unity
2) Press Play
3) Unity Editor Hard Crash ... no log output

Installations (in Run As Administrator mode):
Windows 7
Unity v 2017.4.17f1
Unity Asset: TFSharpPlugin
Python via Anaconda v 3.6.7
tensorflow v 1.11.0 gpu_py63h5dc63e2_0
jupyter 1.0.0 py37_7
cuda v9 (from NVidia)
cudnn for v9 (from NVidia)

Build:
When I go to the ml-agents subdirectory and build using pip3 install -e . appears to have worked

Paths:
Appear to have been setup correctly so that installs and builds for python packages

Can verify tensorflow-gpu can successfully run a session in python Anaconda after setup

**Comment by taesiri** [comment]
Without a log file is hard to say what is wrong. You can find Unity's Editor Logfile in ``C:\Users\<YOUR USER NAME>\AppData\Local\Unity\Editor\Editor.log`` ([Source](https://docs.unity3d.com/Manual/LogFiles.html)). Open it and look what it says.

**Comment by pixelknight1** [comment]
It would indeed make it easier if there was some log output.
 
With the hard crash, the log file doesn't get anything written to it.  After loading the project... log reads...
Packing sprites:
[     63 MB ]- Skipping packing - Sprite Packer (Legacy) is off.
[     63 MB ]Reloading assemblies for play mode.
Begin MonoManager ReloadAssembly
Initializing Unity.PackageManager (PackageManager) v2017.4.17 for Unity v2017.4.17f1
Registering platform support modules:
Registered platform support modules in: 0.1153727s.
Native extension for Android target not found
Native extension for iOS target not found
Native extension for tvOS target not found
Native extension for WebGL target not found
Native extension for WindowsStandalone target not found
Native extension for OSXStandalone target not found
Native extension for Facebook target not found
Refreshing native plugins compatible for Editor in 10.32 ms, found 6 plugins.
Preloading 1 native plugins for Editor in 0.13 ms.
Refreshing native plugins compatible for Editor in 1.07 ms, found 6 plugins.
Mono: successfully reloaded assembly
- Completed reload, in  2.081 seconds
Platform modules already initialized, skipping
Load scene 'Temp/__Backupscenes/0.backup' time: 0.510989 ms 

After pressing Play and the crash, nothing addition is written after.

**Comment by zetaFairlight** [comment]
Same here, I have TF installed, latest production Unity env, those details added (like ENABLE_TENSORFLOW).

Crashes without a simple warning and every time from months now. I have no log file to debug...

**Comment by pixelknight1** [comment]
Hmmm... how would I verify if the conda install -e . command put the right files in the right place?

**Comment by unityjeffrey** [comment]
hi @pixelknight1 - sorry you are having some difficulties getting the 3dball demo.  A few things to note - you don't actually need python to run the 3dBall demo in Unity if you are using either the TF model brain (You would need the TF# asset package though), player input brain, or heuristic brain.  Only when you are training is when you would need to have python up and running.  You can still test that ml-agents python package installed correctly by going to `.../ml-agents/ml-agents` and running `mlagents-learn`.  You should see that the ml-agents package was installed.

as for your issue on hard crash in Windows - based on your installation setup described above, we don't actually support Windows 7 (only Windows 10) for ml-agents.  In theory, Win 7 should work, but we've only tested in Windows 10 per our instructions here https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation-Windows.md.  The issue you are having appears to be a Unity issue, not an issue with Python.  Can you try one thing - can you drag the 3DBallPlayer brain inside of `Assets/ML-Agents/Examples/3DBall/Brains` to the Brains property under the broadcast hub in the Ball3dAcademy object and hit play that to see if you are still getting a hard crash?  If so, if you can try on a Win 10 machine to see if that resolves the issue.

**Comment by pixelknight1** [comment]
Thank you so much for your response.

Get a positive (not an error) with the mlagents-learn.  Output shown below.

(tensorflow-gpu) C:\Users\Maple\Documents\Machine Learning\Unity SDK Demo\ml-agents-
master\ml-agents\mlagents>mlagents-learn

        Unity Technologies

Usage:
      mlagents-learn <trainer-config-path> [options]
      mlagents-learn --help



Setup for ADBallPlayer:
https://i.gyazo.com/49af3fd805b58882b5e02f450690c4ab.png
Doesn't Crash, but also doesn't learn how to balance a ball.



Python which runs at the same time...
>>> import tensorflow as tf
>>> sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
2018-12-29 05:35:32.975371: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
405] Found device 0 with properties:
name: GeForce GTX 960 major: 5 minor: 2 memoryClockRate(GHz): 1.1775
pciBusID: 0000:03:00.0
totalMemory: 2.00GiB freeMemory: 752.65MiB
2018-12-29 05:35:33.006373: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
484] Adding visible gpu devices: 0
2018-12-29 05:35:40.877823: I tensorflow/core/common_runtime/gpu/gpu_device.cc:9
65] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-29 05:35:40.886824: I tensorflow/core/common_runtime/gpu/gpu_device.cc:9
71]      0
2018-12-29 05:35:40.901825: I tensorflow/core/common_runtime/gpu/gpu_device.cc:9
84] 0:   N
2018-12-29 05:35:40.932827: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1
097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 wit
h 461 MB memory) -> physical GPU (device: 0, name: GeForce GTX 960, pci bus id:
0000:03:00.0, compute capability: 5.2)
Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce GTX 960
, pci bus id: 0000:03:00.0, compute capability: 5.2
2018-12-29 05:35:41.538861: I tensorflow/core/common_runtime/direct_session.cc:2
88] Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce GTX 960
, pci bus id: 0000:03:00.0, compute capability: 5.2

**Comment by pixelknight1** [comment]
The Unity code seems to fail in file Academy.cs line 295 to produce the hard-crash.

                trainingBrain.SetBatcher(brainBatcher);

What happens here?  What does this part need to run smoothly?

**Comment by CalvinGreen** [comment]
If you have the time to reinstall the Tensorflow-sharp plugin install that after you change the .NET dev. into 4.x. Also I know you are doing this but make sure 'ALLOW UNSAFE CODE' is also checked. After appropriately adjusting player settings to the suggested format ,Then build the environment. If you are getting a socket error this is possibly why. I realize it's all about the order of implementing the script while I have debugged ML-Agents over previous versions. I hope this helps 
![c3](https://user-images.githubusercontent.com/34162134/50600338-cd078100-0e7e-11e9-9b0c-d2737880c10d.PNG)
![c2](https://user-images.githubusercontent.com/34162134/50600343-cf69db00-0e7e-11e9-86c0-fd202aaa7211.PNG)

![c1](https://user-images.githubusercontent.com/34162134/50600356-d42e8f00-0e7e-11e9-888e-8faae470233a.PNG)

**Comment by pixelknight1** [comment]
Response from mlagents-learn when pressing Unity [Play] .... still hard crashes though.

(tensorflow-gpu) C:\Users\Zombie\Documents\Omegatech\Machine Learning\ml-agents-
master\ml-agents\mlagents>mlagents-learn config/trainer_config.yaml --run-id=3DB
allScreenShare --train --slow


        Unity Technologies

INFO:mlagents.trainers:{'--curriculum': 'None',
 '--docker-target-name': 'None',
 '--env': 'None',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--no-graphics': False,
 '--num-runs': '1',
 '--run-id': '3DBallScreenShare',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': True,
 '--train': True,
 '--worker-id': '0',
 '<trainer-config-path>': 'config/trainer_config.yaml'}
INFO:mlagents.envs:Start training by pressing the Play button in the Unity Edito
r.
Process Process-1:
Traceback (most recent call last):
  File "c:\users\zombie\appdata\local\conda\conda\envs\tensorflow-gpu\lib\multip
rocessing\process.py", line 249, in _bootstrap
    self.run()
  File "c:\users\zombie\appdata\local\conda\conda\envs\tensorflow-gpu\lib\multip
rocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\zombie\appdata\local\conda\conda\envs\tensorflow-gpu\lib\site-p
ackages\mlagents\trainers\learn.py", line 46, in run_training
    docker_target_name, trainer_config_path, no_graphics)
  File "c:\users\zombie\appdata\local\conda\conda\envs\tensorflow-gpu\lib\site-p
ackages\mlagents\trainers\trainer_controller.py", line 112, in __init__
    no_graphics=no_graphics)
  File "c:\users\zombie\appdata\local\conda\conda\envs\tensorflow-gpu\lib\site-p
ackages\mlagents\envs\environment.py", line 67, in __init__
    aca_params = self.send_academy_parameters(rl_init_parameters_in)
  File "c:\users\zombie\appdata\local\conda\conda\envs\tensorflow-gpu\lib\site-p
ackages\mlagents\envs\environment.py", line 493, in send_academy_parameters
    return self.communicator.initialize(inputs).rl_initialization_output
  File "c:\users\zombie\appdata\local\conda\conda\envs\tensorflow-gpu\lib\site-p
ackages\mlagents\envs\rpc_communicator.py", line 77, in initialize
    "The Unity environment took too long to respond. Make sure that :\n"
mlagents.envs.exception.UnityTimeOutException: The Unity environment took too lo
ng to respond. Make sure that :
         The environment does not need user interaction to launch
         The Academy and the External Brain(s) are attached to objects in the Sc
ene
         The environment and the Python interface have compatible versions.

**Comment by CalvinGreen** [comment]
Reinstall unity

**Comment by CalvinGreen** [comment]
Make sure your version is up to date for the ml-agents

**Comment by pixelknight1** [comment]
Unity v 2017.4.17f1 is up to date with ml-agents
