### ISSUE TITLE
Error using TF-GPU `pkg_resources.DistributionNotFound: The 'tensorflow<1.8,>=1.7' distribution was not found and is required by mlagents`

### ISSUE THREAD

**Issue by Szpaqn** [Unity-Technologies/ml-agents#1534]
Hi,
I am trying to use mlagents with tensorflow-gpu, but I keep getting this error:
`pkg_resources.DistributionNotFound: The 'tensorflow<1.8,>=1.7' distribution was not found and is required by mlagents`

I followed the install guide for windows, did every thing as described.

All works fine with tensorflow for CPU, but as soon as I uninstall tensorflow, (`pip uninstall tensorflow`) and install tensorflow-gpu (`pip install tensorflow-gpu==1.7.1`) it stops with mentioned error.

I am using *ML-Agents 0.6* on Windows 10 64 bit with Python 3.6.7.

If it's a bug in your python script, could you point which one is it?

**Comment by taesiri** [comment]
Just a quick question, does changing [this line](https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents/setup.py#L31) from ``tensorflow>=1.7,<1.8`` to ``tensorflow-gpu>=1.7,<1.8`` fixes your problem?

You can also confirm TF installation by running ``python -c "import tensorflow as tf; print(tf.__version__)"``.

**Comment by Szpaqn** [comment]
Thanks for the quick response.
I forgot to write, that I found only one mention of tensorflow. It was in setup.py, and I changed it as you suggested. No change.
I ran your code, and I get info, that the version is 1.7.1
![2018-12-29](https://user-images.githubusercontent.com/16925848/50537849-e1d5d300-0b65-11e9-926a-5cbd208a96fc.png)

**Comment by taesiri** [comment]
After changing thet like, do another ``pip install -e .`` and see what happens.

**Comment by Szpaqn** [comment]
It worked.
Thanks.
I didn't know this method of installation, thought it's only for checking installed version, and the script for installing is somewhere else.
