### ISSUE TITLE
The visual Observation 0 of the model does not match.

### ISSUE THREAD

**Issue by Szpaqn** [Unity-Technologies/ml-agents#1537]
Hi,
I am trying to train an agent to play a game (for my bachelor thesis).

I wanted to use visual observations. I was using them in a different project, with ML-Agents 0.3 and all worked fine.
Now in version ML-Agents 0.6, when I try to use the produced .bytes file as a model for my brain, I get:
```The visual Observation 0 of the model does not match. Received Tensor of shape [?x320x180x3] but was expecting [?x180x320x3].```
Any idea what I am doing wrong?
![learningbrain](https://user-images.githubusercontent.com/16925848/50538065-9f15fa00-0b69-11e9-8c28-e08a83c74174.jpg)
![academy](https://user-images.githubusercontent.com/16925848/50538066-a210ea80-0b69-11e9-855b-ea88e3f1ec0e.jpg)

**Comment by ervteng** [comment]
Hi @Szpaqn, I've been able to replicate your issue, and we'll look into this. In the meantime, using a square observation should avoid this issue.

**Comment by Szpaqn** [comment]
Hi, @ervteng and @vincentpierre,
thank you for your information. 
I've checked and it works fine.
