### ISSUE TITLE
Unable to continue training with previous model.

### ISSUE THREAD

**Issue by Szpaqn** [Unity-Technologies/ml-agents#1538]
Hi, 
I would like to continue training with previous model.
In version 0.4 of ML-Agents it only required that I up the `max_steps` count and add `--load` when initializing training from command line. 
Here I still get an error:
`NotFoundError (see above for traceback): Key dense_2/bias not found in checkpoint
         [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]`

![2018-12-29 4](https://user-images.githubusercontent.com/16925848/50538179-a3431700-0b6b-11e9-8aab-4f85db8f34e6.png)

![2018-12-29 3](https://user-images.githubusercontent.com/16925848/50538178-a0e0bd00-0b6b-11e9-9806-5a44f042d91b.png)

**Comment by Szpaqn** [comment]
I don't know what was the reason, but I've tried again next day and it started working.

**Comment by lzccc** [comment]
Hi bro, I also want to continue training with a previous model because the ultimate map of my project is too big but I don't know how. Could you tell me how to load the previous model when I start my training? Thanks a lot!
