### ISSUE TITLE
Alternative AI Inputs

### ISSUE THREAD

**Issue by elanrosen** [Unity-Technologies/ml-agents#154]
So I know that keyboard can be used with the AI and I assume joystick after looking through the input manager file. Does Unity support the AI generating values for multiple variables that would then be interpreted by the game? No simulated keystrokes or joystick movements would be needed. This would make my scripting much simpler, but I am unaware of such a feature. Does this exist?

Thanks

**Comment by vincentpierre** [comment]
I am not sure I understand what you mean. Are you talking about the `Player` brain ? Where you specify keyboard input for the agent's actions? When the `External`, `Internal` or even `Heuristic` brain decides actions they are in the form of an array of floats. Is that what you mean by **"AI generating values for multiple variables"**?
