### ISSUE TITLE
Do I need Decision

### ISSUE THREAD

**Issue by MrGitGo** [Unity-Technologies/ml-agents#1543]
I'm using the space type discrete and I have looked in the decision script of 3dBall. There it is returning just this: return new float[1] { 1f }; if it is discrete. So my question would be: Do I need the methods MakeMemory and Decide?

**Comment by eshvk** [comment]
Hi @MrGitGo, thanks for reaching out to us. No, you don't need these methods. I am going to close this issue, please create a new issue if you have a new question.
