### ISSUE TITLE
Recurrent learning stops after first learning session

### ISSUE THREAD

**Issue by Szpaqn** [Unity-Technologies/ml-agents#1544]
Hi,
I am trying to train a NN to play a game called [Falling Down](https://ixi.itch.io/falling-down).
The game is designed to be challenging to a human player.
It seems to be even harder for NN.

The task is to get a ball/square shape-shifting thing to the bottom of a 2D platformer style cave/maze and not get killed by spikes along the way.
The only way to control the player object (our agent) is by deciding whether it's a ball or a cube (circle or a square). If it's in ball form it's lighter and can bounce quite high. If it's in cube shape it's heavier, cannot bounce but can slide, quickly gaining momentum. 

I tried to teach the NN using visual observations, [link here](https://github.com/Unity-Technologies/ml-agents/issues/1539), but after first learning faze ( after the buffer is full and data are fed to the learning process ) the agent stops making decisions and it's stuck on decision action 0 (discrete).

It happens no matter how large I set the buffer (I've tried from 640 to 128000). I've also tried different parameters, but with no luck. 
I cannot find any bit of code, that is bugged and could be causing it.

Is it possible that the problem of controlling the game is too complicated and the NN "gave up"?
Edit:
I have found, that the problem only occurs using recurrent learning.
Does any one has an idea where I could look for a solution?

**Comment by Szpaqn** [comment]
Solved in the linked topic.

**Comment by zheyangshi** [comment]
Hi, SzPaqn~ I also meet this problem, and I do not understand why it happens. could you tell me how you fix it? Thank you very much!

**Comment by Szpaqn** [comment]
Hi,
The answer is in https://github.com/Unity-Technologies/ml-agents/issues/1539
You need to use the branch 0.0.6a (hotfix).
The problem was with dividing by 0.

pt., 11 sty 2019 o 09:45 zheyangshi <notifications@github.com> napisał(a):
