### ISSUE TITLE
Error: No Learning Brains set to train found in the Unity Environment - No Brain Type options

### ISSUE THREAD

**Issue by dza6549** [Unity-Technologies/ml-agents#1546]
Hi there
Win10 - Unity 2018.3.0f2 - ml-agents 0.6

Trying to work through getting-started.ipynb Notebook but get the following error:

```
INFO:mlagents.envs:
'Ball3DAcademy' started successfully!
Unity Academy name: Ball3DAcademy
        Number of Brains: 1
        Number of Training Brains : 0
        Reset Parameters :
		
Unity brain name: 3DBallLearning
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 8
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): [2]
        Vector Action descriptions: , 
WARNING:mlagents.envs: No Learning Brains set to train found in the Unity Environment. You will not be able to pass actions to your agent(s).
```

I see that I cannot change the Brain type to External. In fact I have no options to change Brain type at all - maybe similar to this problem (bug?) like [https://github.com/Unity-Technologies/ml-agents/issues/1436](https://github.com/Unity-Technologies/ml-agents/issues/1436)

Please let me know if I can provide more info.

![nobraintype](https://user-images.githubusercontent.com/27390320/50553673-5c862600-0cff-11e9-97d0-8c84f3f4fe4e.png)

**Comment by dza6549** [comment]
My fault! Did not have Control ticked in Academy script. Cheers

**Comment by yangbo** [comment]
> My fault! Did not have Control ticked in Academy script. Cheers

Can you show how to tick the Control in Academy script? Thanks.

**Comment by chriselion** [comment]
@yangbo That no longer exists since version 0.11.0. Can you please open a new issue explaining your problem?
