### ISSUE TITLE
Problem with UnityTImeOutException : How to solve this problem? In v0.6

### ISSUE THREAD

**Issue by 170928** [Unity-Technologies/ml-agents#1547]
Hello i have problem during trianing, i pulled v0.6 version from git.
And I tested the custom environment by using player brain in Unity Screen; and there are no problems.
But, when I use learning brain, the "getting-start.ipynb" can not train the environment.

i have error on jupyter notebook side:

UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Academy and the External Brain(s) are attached to objects in the Scene
	 The environment and the Python interface have compatible versions.

at the code "env = UnityEnvironment(file_name=env_name)"
S,o how to handle this error?

**Comment by 170928** [comment]
And I tested the 3DBall environment. This default example is also not executed with the same error.

**Comment by taesiri** [comment]
I can't reproduce your problem. I think your setting is not correct. Does your Unity stays open after running  ``env = UnityEnvironment(file_name=env_name)`` ? 

Also
* Make sure you've checked `Control` in Ball Academy.
* Make sure you are using the correct type of Brain (Learning Brain)

Here is my Jupyter:
![screen shot 2018-12-31 at 4 55 29 pm](https://user-images.githubusercontent.com/588431/50561227-efce5400-0d1d-11e9-982c-54cddee04318.png)

**Comment by 170928** [comment]
@taesiri 
Thank you for response. 
I checked Contorl in Ball Academy. Also, I'm using Learning Brain as follows.
![image](https://user-images.githubusercontent.com/40893452/50565893-05239c80-0d77-11e9-897f-b87554f8fdfa.png)

![image](https://user-images.githubusercontent.com/40893452/50565910-2d130000-0d77-11e9-8b58-483d0182799f.png)

**Comment by 170928** [comment]
I solved this problem. So, I closed this issue.

**Comment by taesiri** [comment]
Does Unity stays open or it crashes?

You should also change Brain in every (or at least one) instance of 3D Ball Agent from Player to Learning.

![screen shot 2018-12-31 at 10 37 42 pm](https://user-images.githubusercontent.com/588431/50566266-d1cc1800-0d4c-11e9-9f13-769c3296bf30.png)
