### ISSUE TITLE
Wrong WallJump demo curriculum json filenames in 0.6

### ISSUE THREAD

**Issue by 13Flo** [Unity-Technologies/ml-agents#1548]
Just to let you know that in 0.6, the curriculum JumpWall demo config files have wrong names "SmallWallBrain" and "BigWallBrain". Python expects it to be "SmallWallJumpLearning" and "BigWallJumpLearning" according to the brain names in the Unity project.

**Comment by 13Flo** [comment]
By the way, I'm having a blast playing with ML-Agents. I'm training racing vehicles to avoid obstacles and getting really good results. Thank you so much for your work!

**Comment by mmattar** [comment]
Thanks for your feedback @13Flo - we're making the necessary changes in the next hotfix release.
