### ISSUE TITLE
Return rich output from Unity to Python

### ISSUE THREAD

**Issue by malmaud** [Unity-Technologies/ml-agents#1549]
Right now, the only output Unity can return to Python is in the form of 1d vectors from `CollectObservations` and a scalar from `AgentAction`. I'd like to be able to create an arbitrary protobuf message for Unity to send back to Python when an action is created that includes some structured metadata about the result of an action in addition to the reward itself. 

I know how to create and compile a custom protobuf message definition for my desired output, but there would still need to be API changes and serialization logic added to ml-agents to enable this.

**Comment by mmattar** [comment]
Hi @malmaud - this is something that has come up in the past and part of the move to gRPC and protobuf (from sockets) was to enable this possibility. It's not something that we have planned in the short-term (~3 months), however. If you decide to try making the changes yourself, do let us know and keep this thread updated.

**Comment by malmaud** [comment]
I did patch things locally so that a custom protobuf field is inserted into `AgentInfoProto` and added a method to `Agent` to set that field during `AgentAction`.  I can submit a PR with those changes.

**Comment by vincentpierre** [comment]
Thank you ! Feature was merged successfully.
