### ISSUE TITLE
[NEWBIE] INFINITE argument in connection.py

### ISSUE THREAD

**Issue by Retardhunter** [Unity-Technologies/ml-agents#1555]
I am trying to get through tutorial example Ball3D. I have build from Unity with TF package imported, and Ball3DLearn brain included in academy. I am executing it in conda shell with command: 
`mlagents-learn config/trainer_config.yaml --env=3DBall --run-id=first-run --train `(with added path to 3DBall environment). It gets into this phase but nowhere else.:
![obrazek](https://user-images.githubusercontent.com/33417875/50603270-440e3b00-0eba-11e9-944c-5f1244b21cb6.png) It also launch the build of Ball3D with very fast spawning balls. It is not returning any additional informations about learning as it should, as is said by tutorial.: 
![obrazek](https://user-images.githubusercontent.com/33417875/50603435-c26add00-0eba-11e9-9881-bb3ee1e953a3.png) After keyboardInterrupt (Ctrl+C) it returns this:
![obrazek](https://user-images.githubusercontent.com/33417875/50603566-36a58080-0ebb-11e9-9d7e-a756f19a6758.png) I think it could be caused by that connection exeption, but I dont know what to do with that.
Thank you for reply.

**Comment by taesiri** [comment]
Do you have any ``3DBallLearning`` in your scene or all of them are``3DBallPlayer``?

![1](https://user-images.githubusercontent.com/588431/50662250-b55df480-0f73-11e9-9f83-aa2fcc605992.png)

**Comment by Retardhunter** [comment]
Thank you, I haven't knew that. Works well now.
