### ISSUE TITLE
Unity API and Python API comptaibilty issue: Help Needed

### ISSUE THREAD

**Issue by sangramioi** [Unity-Technologies/ml-agents#1559]
Hello,

While trying to train I get the following error 
**mlagents.envs.exception.UnityEnvironmentException: The API number is not compatible between Unity and python. Python API : API-6, Unity API : API-5.**

I have taken the most recent pull from ML-Agents and my Unity is 2018.3.0f2, I am not sure how to update unity? Since here https://unity3d.com/unity/beta/unity2018.3.0b6 they say it is Unity 6

Can anyone help how to update to Unity API 6?

**Comment by mmattar** [comment]
@sangramioi The Unity API 6 refers the to learning environment codebase (the C# code in ML-Agents) and not the Unity version. You seem to building your Unity environment with v0.5 of ML-Agents, not v0.6.

**Comment by sangramioi** [comment]
Thank you :)
