### ISSUE TITLE
(MAC) cant train brain in basic guide

### ISSUE THREAD

**Issue by BenjiHilton** [Unity-Technologies/ml-agents#1560]
I completed the installation guide, and succesfully ran a pretrained brain. Now i need to train a brain wiht the 3Dball environment, and it looks like everything is working fine when the terminal responds as promised: 

mlagents-learn config/trainer_config.yaml --run-id=firstRun --train

(UNITY IMAGE)

INFO:mlagents.trainers:{'--curriculum': 'None',
 '--docker-target-name': 'None',
 '--env': 'None',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--no-graphics': False,
 '--num-runs': '1',
 '--run-id': 'firstRun',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': False,
 '--train': True,
 '--worker-id': '0',
 '<trainer-config-path>': 'config/trainer_config.yaml'}
INFO:mlagents.envs:Start training by pressing the Play button in the Unity Editor.

I then press start in the Unity editor but the game freezes and i get the error:
UnityAgentsException: The Communicator was unable to connect. Please make sure the External process is ready to accept communication with Unity.

Meanwhile in terminal replies with:
INFO:mlagents.envs:
'Ball3DAcademy' started successfully!
Unity Academy name: Ball3DAcademy
        Number of Brains: 1
        Number of Training Brains : 1
        Reset Parameters :
		
Unity brain name: 3DBallLearning
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 8
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): [2]
        Vector Action descriptions: , 
Process Process-1:
Traceback (most recent call last):
  File "/Users/benjamin/ml-agents/ml-agents/mlagents/trainers/trainer_controller.py", line 240, in _load_config
    with open(self.trainer_config_path) as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config/trainer_config.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/benjamin/ml-agents/ml-agents/mlagents/trainers/learn.py", line 52, in run_training
    tc.start_learning()
  File "/Users/benjamin/ml-agents/ml-agents/mlagents/trainers/trainer_controller.py", line 282, in start_learning
    trainer_config = self._load_config()
  File "/Users/benjamin/ml-agents/ml-agents/mlagents/trainers/trainer_controller.py", line 246, in _load_config
    .format(self.trainer_config_path))
mlagents.envs.exception.UnityEnvironmentException: Parameter file could not be found at config/trainer_config.yaml.

I'm almost tottally new to python, and just installed Anaconda so it might be a really obvious issue i'm overlooking. Hoping someone will help

**Comment by BenjiHilton** [comment]
That fixed the problem thank you! Any idea why i cant just run the <trainer-config-path> but have to run the direct folder location? If not im fine with just using the direct folder location (;

**Comment by mmattar** [comment]
Thanks @thepycoder. We require the direct path as you may have multiple configuration files for different tests. Closing this issue as it seems that you've fixed the problem, but let us know if the issue persists.
