### ISSUE TITLE
The result of the example of "Making a New Learning Environment" is greatly different

### ISSUE THREAD

**Issue by tcy1998** [Unity-Technologies/ml-agents#1564]
The result in tensorboard is not converge. I could perfectly train the agents but the result is wrong. And I assume is probably caused by the different config parameter.
My result is the first picture and the second picture is the correct result. The third one is my config parameter.
![picture1](https://user-images.githubusercontent.com/44712124/50708263-55c22080-1029-11e9-99fd-6e982687b1b3.JPG)
![picture2](https://user-images.githubusercontent.com/44712124/50708264-565ab700-1029-11e9-8a72-b965f8b01748.JPG)
![picture3](https://user-images.githubusercontent.com/44712124/50708265-565ab700-1029-11e9-8f26-175d6429cfb2.JPG)

**Comment by jo3w4rd** [comment]
Yes, the buffer and batch size have a large affect on how fast the agent learns in this environment. As discussed in https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md#training-the-environment, they should be small.

**Comment by tcy1998** [comment]
@jo3w4rd Thank you. That helps a lot

**Comment by mmattar** [comment]
Thanks @jo3w4rd. @tcy1998 - let us know if this fixes your issue.

**Comment by tcy1998** [comment]
@mmattar Thank you. It did fix my problem.
