### ISSUE TITLE
New Demo can not fill the bytes file!

### ISSUE THREAD

**Issue by segatecm** [Unity-Technologies/ml-agents#157]
CoreBrainInternals.cs file not used in New Demo.
I had download the new version, but i can not find how to input the 'bytes' file.

so please help!

**Comment by awjuliani** [comment]
Hi @segatecm,

Have you looked through the "Getting Started" document (https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Getting-Started-with-Balance-Ball.md#embedding-trained-brain-into-unity-environment-experimental), and added the TensorFlowSharp plugin, as well as set `ENABLE_TENSORFLOW` in the scripting symbols?

**Comment by segatecm** [comment]
Thanks，I set the ENABLE_TENSORFLOW macro and it is all right.
