### ISSUE TITLE
Suggestion: make your Unity method protected virtual

### ISSUE THREAD

**Issue by 13Flo** [Unity-Technologies/ml-agents#1571]
Hey guys, it would be super cool if you could make your **Academy and Agent MonoBehavior methods `protected virtual`**. I feel like it's a very common case to extend Academy and Agent classes, and it makes MonoBehavior methods unusable.

Just a suggestion ;)

Thanks!

Edit: is the issue tracker the best place for this kind of feedback? Or should I use the Unity forum page instead?

**Comment by mmattar** [comment]
Thanks, @13Flo. We made a note internally to add this to our backlog. We'll prioritize accordingly. Closing this issue.
