### ISSUE TITLE
ml-agents + Xvfb on google cloud problem

### ISSUE THREAD

**Issue by markpwoodward** [Unity-Technologies/ml-agents#1574]
I can instantiate an environment on my laptop but when I run on google cloud I get a timeout with the following in Player.log
```
Desktop is 1024 x 768 @ 0 Hz
Unable to find a supported OpenGL core profile
Failed to create valid graphics context: please ensure you meet the minimum requirements
E.g. OpenGL core profile 3.2 or later for OpenGL Core renderer
Vulkan detection: 0
No supported renderers found, exiting
 
(Filename:  Line: 590)
```
My environment (on laptop and GCE) is created with:
```
    $ conda create -n xvfb python=3.6
    $ conda activate xvfb
    (xvfb)$ pip install ./ml-agents/ml-agents/
    (xvfb)$ xvfb-run -s "-screen 0 1024x768x24" python ./test_xvfb.py
```
test_xvfb.py contents:
```
import mlagents.envs

env = mlagents.envs.UnityEnvironment(file_name="ml-agents/ml-agents/mlagents/envs/SimpleGridWorld")
```
Any thoughts on what the problem might be?

Thank you,
Mark

**Comment by eshvk** [comment]
Hi @markpwoodward, are you using release 0.6? i.e. is this code from master? If so, I think this is an issue (with 0.6) that I will look into. In the mean time, can you please try checking out version 0.5.0 and see if you see the same problem?

**Comment by markpwoodward** [comment]
Thank you for the response. I am still on 0.5.0. It turns out it was a conflict with the nvidia driver which I am using for tensorflow training. re-installing the nvidia driver with the "--no-opengl-files" option made this work for me (https://davidsanwald.github.io/2016/11/13/building-tensorflow-with-gpu-support.html).

**Comment by eshvk** [comment]
Hey @markpwoodward, thanks for sending this.

**Comment by bjg2** [comment]
@markpwoodward I tried your solution at https://github.com/Unity-Technologies/ml-agents/issues/1786, and it didn't help. Can you take a look, maybe I have done something wrong?
