### ISSUE TITLE
Adding vector observation at once or x y z separately?

### ISSUE THREAD

**Issue by JPhilipp** [Unity-Technologies/ml-agents#1576]
Hi! I saw some documentation parts where a vector x y z's were added individually instead of in one swoop, even if all of x y z where used (and not just 1 or 2 of them). E.g. at https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design-Agents.md the code

```
AddVectorObs(ball.transform.GetComponent<Rigidbody>().velocity.x);
AddVectorObs(ball.transform.GetComponent<Rigidbody>().velocity.y);
AddVectorObs(ball.transform.GetComponent<Rigidbody>().velocity.z);
```

I do notice though that adding a Vector at once is possible and done in some of the ML-Agents examples, along the lines of

```
AddVectorObs(ball.transform.GetComponent<Rigidbody>().velocity);
```

Do I presume correct that both approaches are exactly equal in results (if all 3 of x y z are needed), or is that not the case? Thanks!

**Comment by HPlumley** [comment]
The old ml-agents only allowed adding a single float at a time, hence that first code snippet. There are now additional function overloads that allow adding a Vector3 in one call and split it to the three floats for you, so you should use the second form now.

**Comment by JPhilipp** [comment]
Thank you!
