### ISSUE TITLE
What's a camera's visual observation width and height specifically?

### ISSUE THREAD

**Issue by JPhilipp** [Unity-Technologies/ml-agents#1578]
Hi! What is the exact meaning of the width and height properties of a brain's visual observation section when one added a camera? They are set to 84x84 by default. Does that "see" what I would see if my screen had an 84x84 resolution? Or is it some kind of downsampling (using pixel interpolation?) of the current resolution's render?

![cam](https://user-images.githubusercontent.com/1754503/50839471-ab1b6c00-1360-11e9-8bfe-4ed7c97e82cf.png)

And is there a nice way to get a live feed preview of that e.g. 84x84 result (if not, that would be a cool feature)? Thanks!

**Comment by vincentpierre** [comment]
The camera resolution is just like what a camera would see if the resolution was set to 84x84. If you want to see what this looks like, you can change the resolution in the editor in the `Game` window. You can also use the [getting started notebook](https://github.com/Unity-Technologies/ml-agents/blob/master/notebooks/getting-started.ipynb) to display the visual observations as received by Python.

**Comment by JPhilipp** [comment]
Excellent thanks! In case anyone arrives here via Google, a screenshot of the part to click Add is below.

![default](https://user-images.githubusercontent.com/1754503/50846672-ff7a1800-136f-11e9-9328-a51c44ba20e0.png)
