### ISSUE TITLE
ML-Agents Roadmap?

### ISSUE THREAD

**Issue by JPhilipp** [Unity-Technologies/ml-agents#1579]
Hi! What's the future features/ development roadmap for ML-Agents? Thanks!

**Comment by mmattar** [comment]
Hi @JPhilipp - we plan to begin externalizing relevant parts of our roadmap in the next few weeks. Stay tuned.

**Comment by JPhilipp** [comment]
Thanks! Would this be posted to https://blogs.unity3d.com or? (And please let me know if I should close this issue.)

**Comment by mmattar** [comment]
Hi @JPhilipp - we would likely share this in the github project itself. We're hoping to do so in the next 3 months. I'm closing this issue for now, and thanks for raising it.

**Comment by mschneider** [comment]
It's been 3 months :)
