### ISSUE TITLE
Hidden layers size is overriden?

### ISSUE THREAD

**Issue by cypreess** [Unity-Technologies/ml-agents#158]
By any chance in lines

https://github.com/Unity-Technologies/ml-agents/blob/development/python/ppo/models.py#L203
and 
https://github.com/Unity-Technologies/ml-agents/blob/development/python/ppo/models.py#L263

aren't you overriding the value of `h_size` variable that is an argument of the class constructor with a value of the height of observation matrix? Is this a bug or desired thing for making layers shapes compatible later on?

**Comment by awjuliani** [comment]
Hi @cypreess,

This is totally a bug on our part! I just fixed it in the development branch. Thanks for catching it.
