### ISSUE TITLE
Specific meaning of curiosity_strength values?

### ISSUE THREAD

**Issue by JPhilipp** [Unity-Technologies/ml-agents#1580]
Hi! What is the specific meaning of the curiosity_strength value in trainer_config.yaml (default 0.01)? Is it basically the weight curiosity (if use_curiosity is used) in the mix with other rewards where 0 is 0% and 1 is 100% (or can I use values larger than 1)? So that for a fully curiosity-driven, no-external-rewards project I would simply set it to 1 (or maybe it doesn't even matter if no other rewards compete with it)? Thanks!

**Comment by mmattar** [comment]
That is correct @JPhilipp. It's mostly a way to specify the importance of the intrinsic reward, compared to the extrinsic reward. If there are no other rewards, then, in theory, it shouldn't matter, but it would scale the reward presented to the agent.

**Comment by harperj** [comment]
This issue has been inactive for some time, so I'm going to close it.  Please feel free to reopen or create a new issue if you have any more trouble.
