### ISSUE TITLE
Request for mlagents processing benchmark for visual observations

### ISSUE THREAD

**Issue by markpwoodward** [Unity-Technologies/ml-agents#1581]
I think it would be good to have a processing benchmark for mlagents. We could then try to improve it through driver/cuda/unity flags and code optimization.

An initial benchmark could be the GridWorld environment that ships with the SDK. 

grid_world_speed_test.py:
```
import mlagents.envs

env = mlagents.envs.UnityEnvironment(file_name="ml-agents/ml-agents/mlagents/envs/GridWorld")
env.reset()

for i in range(1000):
  env.step([0])
```
Here are my initial numbers:

GPU based
$ time python grid_world_speed_test.py
* 5.3s : lenovo thinkpad x1 carbon 2017 integrated graphics, Intel Corporation HD Graphics 620, i7-7600U CPU @ 2.80GHz (boost to 3.9GHz)
* 5.6s: lenovo p520 thinkstation, geforce gtx 1080, Xeon(R) W-2135 CPU @ 3.7GHz (boost to 4.5GHz)
* 15.3s: google cloud, Tesla V100-SXM2..., Xeon(R) CPU @ 2.00GHz 

Xvfb based
$ time xvfb-run -s "-screen 0 1024x768x24" python grid_world_speed_test.py
* 8.0s : lenovo thinkpad x1 carbon 2017 integrated graphics, Intel Corporation HD Graphics 620, i7-7600U CPU @ 2.80GHz (boost to 3.9GHz)
* 10.0s: lenovo p520 thinkstation, geforce gtx 1080, Xeon(R) W-2135 CPU @ 3.7GHz (boost to 4.5GHz)
* 19.0s: google cloud, Tesla V100-SXM2..., Xeon(R) CPU @ 2.00GHz 

A concerning trend is that speeds seem to get slower as the GPU gets more powerful.

**Comment by eshvk** [comment]
I think this is a good idea, we have been thinking about something similar, I will keep you posted when we release something related.

**Comment by markpwoodward** [comment]
> I think this is a good idea, we have been thinking about something similar, I will keep you posted when we release something related.

**Comment by eshvk** [comment]
I am going to reopen this issue so that we can use this to update once we get some more transaction on this.

**Comment by eshvk** [comment]
@markpwoodward I was re-reading your results (which are very counter intuitive). One thought on the GPU computation: How many vCPUs does your gcloud machine have? I noticed that the processing power of the (GCP) chip is lower than both of the lenovos?

**Comment by markpwoodward** [comment]
@eshvk oops, I didn't mean to close this issue. The gcloud machine has 96 vCPUs and 8 V100's :). and nothing else was running but this test. I agree with your hunch about the CPU being the limiting factor. Performance seems to track CPU speed, with a minor bump when rendering on the GPU vs. CPU for each platform.

The example doesn't do any learning (PPO or otherwise). At least that is my intention. I was thinking that this benchmark would be just rendering, not training.

my 2 cents on the visual benchmark environment is that it should have a "batchSize" resetParameter, which dynamically creates Areas. Number of Areas is an important tradeoff, e.g. for a batch size of 32 you could run 8 environments, each with a 4 Areas, or 32 environments, each with 1 Area. And processing time doesn't grow 1:1 with the number of Areas. I did this for my own environment and found the sweet spot.

**Comment by markpwoodward** [comment]
Also, my assumption was that rendering on the GPU would really shine when I increased the number of Areas vs. CPU rendering, but I did not experience that. Another plus for a benchmark that can change the number of Areas.

**Comment by markpwoodward** [comment]
@eshvk Correct. It is only ~3% of the V100.

**Comment by nikola-j** [comment]
Does Xvfb work with environments that use a camera? When I try to run my env I get:

```
Xlib:  extension "NV-GLX" missing on display ":99".
Traceback (most recent call last):
    "The Unity environment took too long to respond. Make sure that :\n"
mlagents_envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Academy and the External Brain(s) are attached to objects in the Scene
	 The environment and the Python interface have compatible versions.
```

**Comment by awjuliani** [comment]
@nikola-j 

Our docker set-up uses xvfb specifically for environments that use cameras. See here for the dockerfile: https://github.com/Unity-Technologies/ml-agents/blob/master/Dockerfile

**Comment by markpwoodward** [comment]
@nikola-j Also take a look at the following issue + solution: https://github.com/Unity-Technologies/ml-agents/issues/1574

**Comment by nikola-j** [comment]
@awjuliani @markpwoodward Thanks guys, the #1574 solution worked!

**Comment by harperj** [comment]
Thanks for the suggestion. I've added it to our internal tracker with the ID MLA-73. I’m going to close this issue for now, but we’ll ping back with any updates.
