### ISSUE TITLE
Get update on intrinsic curiosity reward during training?

### ISSUE THREAD

**Issue by JPhilipp** [Unity-Technologies/ml-agents#1584]
Hi! The Anaconda console during training currently already provides helpful status updates like "Step: 36000. Mean Reward: 0.001. Std of Reward: 0.001." Is there any way to get a similar console value update to gauge success for no-external-rewards, intrinsic-curiosity-driven rewards only trainings (use_curiosity: true, and no AddReward/ SetReward ever provided)? Thanks!

**Comment by vincentpierre** [comment]
You can use **Tensorboard** to visualize all of these values. We have [documentation page](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-Tensorboard.md) on how to use Tensorboard with the ML-Agents Toolkit.

**Comment by JPhilipp** [comment]
Thanks! (I'm closing this as I guess there's no way to also get it to show on the command status output.)
