### ISSUE TITLE
How to silence INFO:mlagents.envs: logging

### ISSUE THREAD

**Issue by markpwoodward** [Unity-Technologies/ml-agents#1590]
How do I set the logging level for mlagents?

I mean logging to stderr/stdout not to Player.log.

Specifically, "INFO:mlagents.envs:Academy reset with parameters:..." is printed whenever I reset the environment.

Thanks,
Mark

**Comment by vincentpierre** [comment]
I think what you are looking for is at [this line](https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents/mlagents/envs/environment.py#L18). This is where we set the logging level.

**Comment by markpwoodward** [comment]
Hi Vincent. Thank you for the response. I hadn't played with python logging until now, pretty cool.

It turns out that another logger higher up in the chain was being set to INFO, so 'mlagents.envs' inherited that level regardless of what it was set to. For me, setting the level of the root logger before calling UnityEnviornment (from the same process if multithreading) did the trick. e.g. `logging.getLogger().setLevel(logging.WARNING)`. All loggers downstream, including "mlagents.envs", then inherit this level.
