### ISSUE TITLE
How to use monobehaivour and Decision in heuristic brain?

### ISSUE THREAD

**Issue by didwuddk** [Unity-Technologies/ml-agents#1591]
Hi!

How to use monobehaivour and Decision in heuristic brain?
![image](https://user-images.githubusercontent.com/19795193/51016277-165c7c80-15b3-11e9-9ffb-a7e44e6871f9.png)

**Comment by vincentpierre** [comment]
Hi, As of v0.6, Decisions are no longer MonoBehaviors. This is to allow us to drag them into ScriptableObjects Brains. The documentation about Heuristic Brain is [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design-Heuristic-Brains.md). And here is an example with a [random decision script](https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Examples/SharedAssets/Scripts/RandomDecision.cs).
Once the decision script is created, you do __not__ need to attach it to a game object. Just drag the script into the Decision field of the Heuristic Brain.
Please let us know how this goes.
