### ISSUE TITLE
Doc may need an update on adding vectors at once

### ISSUE THREAD

**Issue by JPhilipp** [Unity-Technologies/ml-agents#1592]
Hi! The [doc](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design-Agents.md) example says

> For entities like positions and rotations, you can add their components to the feature list individually.
> Vector3 speed = ball.transform.GetComponent<Rigidbody>().velocity;
> AddVectorObs(speed.x);
> AddVectorObs(speed.y);
> AddVectorObs(speed.z);

This should perhaps be updated to say something along the lines that it's fine to either add the vector properties like x y z individually, or in one swoop like AddVectorObs(speed), so people can easier understand both approaches are fine.

Similarly on that page, the 3DBall example shows all values being added individually, even if all of x y z is used.

**Comment by vincentpierre** [comment]
Thank you for noticing this. If you want, you can create a PR for addressing this issue. In the meantime I have added this to our list of documentation improvements.

**Comment by JPhilipp** [comment]
I tried but I'm a github newcomer (using Bitbucket so far), here's what I did which failed:

- Made a local repo of `develop` branch
- Created a local `develop-doc-changes` branch
- Adjusted the doc md file in question in that branch
- Committed with message
- Tried pushing/ publishing, so that I could add a Pull Request later; pushing failed as I'm not an authenicated member for this repo

(Please feel free to ignore this side issue of getting me up to speed)

**Comment by MarcoMeter** [comment]
You start with a fork of the ml-agents repository.

**Comment by harperj** [comment]
A documentation update has been suggested in #1659, I will close this issue and it can be tracked there.
