### ISSUE TITLE
No reference to "normalize" setting in Normalization discussion

### ISSUE THREAD

**Issue by JPhilipp** [Unity-Technologies/ml-agents#1593]
Hi! In the [doc](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design-Agents.md#Normalization) where Normalization is discussed, it would be nice for ease of understanding to see a sentence on how this (manual in-code normalizing) relates to using the trainer_config's `normalize` value (as it's described as "Whether to automatically normalize observations" on [another doc page](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-ML-Agents.md)), i.e. whether the two approaches complement each other/ make each other redundant/ relate or don't relate to each other. The [Best Practices doc](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Best-Practices.md) might need a similar note if relevant. Thanks!

**Comment by vincentpierre** [comment]
Thank you for noticing this. If you want, you can create a PR for addressing this issue. In the meantime I have added this to our list of documentation improvements.

**Comment by JPhilipp** [comment]
Thanks. I'll leave this one untouched as I'm not personally sure if the normalize settings property makes the in-code normalizations redundant or not (I figure it might, but not an expert on that). Please let me know if in case I need to close this issue.

**Comment by eshvk** [comment]
Thank you for this discussion, we are going to close this issue due to inactivity for now.
