### ISSUE TITLE
No mention of "enable_tensorflow" in some setup docs

### ISSUE THREAD

**Issue by JPhilipp** [Unity-Technologies/ml-agents#1594]
Hi! Neither "[Making a New Learning Environment](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md)" nor "[Installation](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md)" make any reference to the potential need to define scripting symbol ENABLE_TENSORFLOW as described [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-TensorFlow-Sharp-in-Unity.md). For ease of developer learning, should they? (I always got errors when not defining it, so it has become part of my project setup routine, but maybe I'm doing it wrong.) Thanks!

**Comment by vincentpierre** [comment]
Hi, in the ML-Agents toolkit v0.6, carrying inference is an optional tool that is not required to perform the training. Therefore, we separated the Setup for inference from the "Making a New Learning Environment" and the "Installation" document. In our next version, we will remove the need for the define scripting symbol ENABLE_TENSORFLOW.

**Comment by JPhilipp** [comment]
Thanks for the info!
