### ISSUE TITLE
hi i have an issue when upload apk to google play for using this tensorflowsharp

### ISSUE THREAD

**Issue by hyunamy** [Unity-Technologies/ml-agents#1598]
i think this ml-agents tensorflowsharp for unity is very useful.
so i made an app for using this module.

however, google play denied to upload apk because of following below issue..

Libpng library
The vulnerabilities were fixed in libpng v1.0.66, v.1.2.56, v.1.4.19, v1.5.26 or higher. You can find more information about how resolve the issue in this Google Help Center article.

how can i fixed this??

**Comment by vincentpierre** [comment]
We have not tried uploading an APK with TensorFlowSharp to Google Play. Maybe someone in the community will be able to help you. We will be releasing a new inference engine in future versions, we are currently working on a prototype on this [branch](https://github.com/Unity-Technologies/ml-agents/tree/develop-barracuda).

**Comment by eshvk** [comment]
We released a new inference engine, so we are closing this issue for now.
