### ISSUE TITLE
"positionWithLocalOffset assign attempt for 'CharacterController' is not valid"

### ISSUE THREAD

**Issue by JPhilipp** [Unity-Technologies/ml-agents#1602]
Hi! I'm repeatedly getting the following error when training an agent that (indirectly via its actions) moves a Character Controller:

"transform.positionWithLocalOffset assign attempt for 'CharacterController' is not valid. Input positionWithLocalOffset is { NaN, NaN, NaN }."

The code is along the lines of (where leftRightSpeed etc. is set elsewhere, through the agent):

```
float delta = Time.smoothDeltaTime;
Vector3 velocity = leftRightSpeed * right + backwardForwardSpeed * forward;
velocity *= forwardAcceleration;
body.Move(velocity * delta); // throws error, but only when University-Controlled
```

It often works, but then after a while stops working...

Any help? Thanks!

**Comment by xiaomaogy** [comment]
Hi @JPhilipp, it would be really hard for us to help you on this kind of issues. (A problem specific to your own code), if you hope to get help from other people, feel free to share more of your source code, so that other people will be able to help.

**Comment by JPhilipp** [comment]
Thanks for getting back!

> A problem specific to your own code

Well, I posted here because it only happens when academy-controlled, hence I figured it might be within the scope of ML-Agents help. The code otherwise runs fine in production, when not training. When searching for this topic online before posting, I found one other forum thread [elsewhere](https://forum.unity.com/threads/transform-position-assign-attempt-for-is-not-valid-and-invalid-aabb-errors.471396/) where the author said that it happened to him when using "DeepMotion's engine", so I had a suspicion it might be a general issue to do with training, but I might be wrong of course. If I ever come up with a dedicated reproducable minimal test case, I'll post here, the current project I'm working (VR multiuser sandbox universe Anyland) on would be too big to share unfortunately.

**Comment by JPhilipp** [comment]
Thanks, no problem. I was hoping it was something known or easy. If anyone else visits this thread from Google: I figure it might be a bad delta value that training provides (maybe Unity can't cope with fast training in all situations?), and maybe a check for that (e.g. <= 0f), or a check for IsNaN on the result could workaround it. I'll have to give that a try.

**Comment by eshvk** [comment]
Thank you for this discussion, we are going to close this issue due to inactivity for now.
