### ISSUE TITLE
Combining Imitation/Demonstration learning with other methods

### ISSUE THREAD

**Issue by vqt123** [Unity-Technologies/ml-agents#1603]
I really feel strongly that pushing / expanding and surfacing the power of imitation learning to the masses will have the highest ROI. It feels intuitive, has that great instant gratification feel and lends itself very well to making NPCs and bots inside a game environment.

Once a user has spent a bit of time training using imitation learning it seems that we all want the same thing, to be able to combine the trained brains with other methods to do more offline training to really try to optimize things. Please consider prioritizing expanding the feature set of this powerful, easy to use, very gratifying way to jump into deep learning. 

Thank you all for your excellent work. You guys are incredible.

**Comment by vqt123** [comment]
Just wanted to add some notes on my first time user experience into using your libraries.
(6 years experience with Unity)
(0 experience using machine learning technologies)

I Jumped chronologically right into your documentation which took me quickly through 

1. Installation - Good
2. Basic Training - Good
3. Ball Balancing - Good

It was at this point that i began to venture into creating my own scenerio and after a few days of futzing with hyper parameters and trying to figure out how to best give rewards, Starting/Restarting training, dragging folders around, toggling boxes between every testing iteration, I quickly became fatigued by how difficult it was to actually get a good result with what I thought was a fairly trivial problem. On the verge of giving up, I FINALLY decided to peruse the rest of the examples and came across Imitation Learning and that's when a flood of hope finally came rushing back. I was able to quickly solve my trivial problem scenerio and the potential space really opened up. 

This is essentially why I decided to come here make a note of where I am now, and having watched other developers play around with your library come to the same epiphanies I did. 

https://www.youtube.com/watch?v=WzuVZuGT-rw

This youtuber has a great tutorial channel using many of your methods and also would like to see Imitation learning expanded on.

**Comment by xiaomaogy** [comment]
Hi @vqt123, thanks a lot for your comment. When you say "to be able to combine the trained brains with other methods to do more offline training to really try to optimize things", what exactly are these "other methods"? 

Also if you are interested in talking more, please fill out our survey at https://docs.google.com/forms/d/e/1FAIpQLSfVnER5i5YiE748MjyI7Ts3gIgpfzXZjSrDGPKR7s2Ydeb9tg/viewform. We are planning to look for game studio to collaborate with in the next few weeks, and one of the place we look for is the survey.

**Comment by vqt123** [comment]
I would like to be able to take my trained brain, and continue training it with a PPO model using rewards.

**Comment by xiaomaogy** [comment]
@vqt123 That's something we are currently working on.

**Comment by vqt123** [comment]
Excellent!

**Comment by hyounesy** [comment]
So what will happen if we train a model using one method (e.g. PPO), then take the saved model and load it in another training session with another method (BC)? Shouldn't it just work, as long we keep all other model parameters the same (observations, network architecture, etc.)?
Disclosure: I haven't tried this yet, but I am planning to.

**Comment by xiaomaogy** [comment]
Hi @hyounesy, it won't work. These two models are fundamentally not compatible with each other.

**Comment by hyounesy** [comment]
Oh right...  the output of the PPO model is value estimates, while the output of the BC model is action probabilities. So, it is not possible to use the trained parameters of one network in the other.
