### ISSUE TITLE
Adjust observation size automatically

### ISSUE THREAD

**Issue by vqt123** [Unity-Technologies/ml-agents#1604]
Completely get that this should probably be set explicitly, but boy would it be nice if I could toggle something that would just automatically set the observation size for me based on what was received. (Maybe with a warning)

**Comment by xiaomaogy** [comment]
Hi @vqt123 , this would be really nice to have, but there is a lot of complicated problem to be solved if we want to make it work.

**Comment by vqt123** [comment]
Fair enough, just wanted to put that out there
