### ISSUE TITLE
Error: (VisualHallwayLearning) Vector Observation size mismatch

### ISSUE THREAD

**Issue by moonsh** [Unity-Technologies/ml-agents#1605]
Hi,

I tried visual hallway training and got this error : 

**UnityAgentsException: Vector Observation size mismatch between continuous agent Agent and brain VisualHallwayLearning. Was Expecting 1 but received 0.** 

I didn't change anything and I just followed the instruction described in the document.

It looks like I should add some code at the agent collect observation part.

**Comment by moonsh** [comment]
@zheyangshi 

Thank you for the suggestion but it doesn't work.

I got this error if I change space size to zero.

**No valid network configuration possible. There are no states or observations in this brain**

**Comment by zheyangshi** [comment]
Sorry about that. I forgot to click on the add new  button (visual observation), and I update the picuture above. Maybe you can try that again.

**Comment by moonsh** [comment]
@zheyangshi  Thank you! It's working now
