### ISSUE TITLE
Docker file build failed - gpg keyserver error

### ISSUE THREAD

**Issue by pringithub** [Unity-Technologies/ml-agents#1606]
Hello, after attempting to install python3.6 (whilst having 3.7.1 installed) and not being able to instal ml-agents, as well as having to clean up the mess that came with that, I decided to use Docker.

Upon running `docker built -t balance.ball.v0.1 .`, I see an error thrown here:

`gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
gpg: keyring '/tmp/tmp.0NJEwiwFwS/secring.gpg' created
gpg: keyring '/tmp/tmp.0NJEwiwFwS/pubring.gpg' created
gpg: requesting key AA65421D from hkp server ha.pool.sks-keyservers.net
gpgkeys: key 0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver receive failed: unknown pubkey algorithm`

The script returned a '2', meaning that the file wasn't found.

I would appreciate any help here :)

**Comment by xiaomaogy** [comment]
Hi @eshvk , could you look at this issue?

**Comment by eshvk** [comment]
@pringithub: Just to confirm, you are running this command in the directory which contains `Dockerfile`?

**Comment by pringithub** [comment]
Correct

**Comment by pringithub** [comment]
Hold up ... i just ran it again, and it seemed to get past the gpg stage .. hmmmmmmmm wtf

**Comment by pringithub** [comment]
welp it works .. the world works in mysterious ways teehee



thx
