### ISSUE TITLE
Seemingly Trivial Application, Hard to solve

### ISSUE THREAD

**Issue by vqt123** [Unity-Technologies/ml-agents#1610]
Hello,

I'm trying to train for a very trivial scenario where I am simply providing 5 numbers , ranging from 0 through 4 in a list in random order. I'd like to be able to train the machine to pick the index that contains the 4.

You would think that machine learning would be able to converge to a solution quickly, but that does not appear to be the case.

On Reset: I generate a new shuffled list of 5 numbers from 0 through 4

CollectObs Size:  The shuffled list
Action: 1 continuous  number , which is normalized betwen 0 and 4 to represent a chosen index.

On Every AgentAction:
I give a .01 reward if correct and a -.001 reward if incorrect.

I reset the entire scenerio every 5 seconds.

What I'm seeing is something that appears to be picking NOT the smallest number, but still gets it wrong a lot of the time. The Reward STD Deviation never appears to settle. (about 1M training steps)

Would love to hear any suggestions on better ways to go about training this

**Comment by vqt123** [comment]
I'll give this a shot... In the meantime here's some code snippets



```
	public override void CollectObservations()
	{
		foreach (var target in scene.targets)
		{
			AddVectorObs(target.GetVectorObs());
		}
	}
```

where 
target.GetVectorObs() returns the score.


```
public override void AgentAction(float[] vectorAction, string textAction)
	{
		var idx = Mathf.FloorToInt((vectorAction[0] + 1) / 2 * scene.targets.Count);

		if (counts.ContainsKey(idx) == false)
		{
			counts[idx] = 0;
		}

		counts[idx]++;
		if (idx < scene.targets.Count)
		{
			if (Mathf.Approximately(scene.targets[idx].score, 4))
			{
				AddReward(.01f);
			}
			else
			{
				AddReward(-.01f);
            }
        }

	}
```

**Comment by vqt123** [comment]
I had a breakthrough today!! So you are right about discrete actions being able to train quickly, but my problem was I needed to use continuous space for other actions as well (movement etc..). And since we aren't able to combine both discrete and continous actions, I had the idea to map each continous action to a binary number -1 to 0 being OFF, 0 to 1 being ON and created binary 2^n input permutations to do my selection. This is working almost as well as discrete, converging very quickly while still giving me the flexibility to use continuous action space!

**Comment by xiaomaogy** [comment]
Yes they work really similar. Also you could use discrete actions with multiple branches, and for places where you need continuous action, you can discretize the continuous space into several buckets.
