### ISSUE TITLE
Recurrent brains do not work.

### ISSUE THREAD

**Issue by TashaSkyUp** [Unity-Technologies/ml-agents#1616]
![image](https://user-images.githubusercontent.com/15312630/51438363-8d78cb80-1cab-11e9-9fa3-dc197aafbd84.png)
The examples which include recurrent layers in config.yaml do not train. They do one step of training then... get stuck not training.

**Comment by xiaomaogy** [comment]
Hi @TashaSkyUp , which platform are you using? Also are you referring to the Hallway not training? We've tested the Hallway ourselves on Windows, and it is training with the default setup.

**Comment by TashaSkyUp** [comment]
Thanks. Actually I think the error was because I had changed the yaml file

**Comment by dhar174** [comment]
@TashaSkyUp , can you tell me what you had changed in the yaml file? I seem to be having this same problem. Training works for a few iterations then the brain just spits all zeros (while not moving, action space value of "0" in my project should make a particular movement). Maybe my problem is unrelated, but could you share what you had done wrong and how you fixed it?

**Comment by TashaSkyUp** [comment]
I think it was that the time_horizon was greater than buffer_size.. when its set that way at step buffer_size the errors begin..

**Comment by dhar174** [comment]
Ooooh.... Yes, that makes sense... that's exactly what my issue was. Thank you.
