### ISSUE TITLE
tensorgenerator on learning brain is allocating memory all the time

### ISSUE THREAD

**Issue by ishaybe** [Unity-Technologies/ml-agents#1618]
hi
on learningbrain.cs exist this code:
  // Prepare the input tensors to be feed into the engine
            _tensorGenerator.GenerateTensors(_inferenceInputs, currentBatchSize, agentInfos);
            
            // Prepare the output tensors to be feed into the engine
            _tensorGenerator.GenerateTensors(_inferenceOutputs, currentBatchSize, agentInfos);
when running with many agents in parrallel the memory allocation and grabage collector of the tensors is become segnificant.

**Comment by xiaomaogy** [comment]
@ishaybe Then you need to sent them n times for each of the agent?

**Comment by ishaybe** [comment]
Can you send only pointers to it?

בתאריך יום ד׳, 23 בינו׳ 2019, 12:12 לפנה״צ, מאת Vincent(Yuan) Gao <
notifications@github.com>:

**Comment by xiaomaogy** [comment]
@vincentpierre

**Comment by vincentpierre** [comment]
In order to do a pass in the Neural Network, the dada must be laid out in a single tensor. Having a reference to the inputs for each agent is not enough. If there is something we missed, we would be happy to discuss new ideas on how to do this.

**Comment by ishaybe** [comment]
But why it need to be allocated dynamically every step?

בתאריך יום ד׳, 23 בינו׳ 2019, 9:41 אחה״צ, מאת Vincent-Pierre BERGES <
notifications@github.com>:

**Comment by vincentpierre** [comment]
I do not understand, If the observations of any agent changed since the last step, we must recreate a whole new tensor of dimension (n_agents, n_observations) to feed to TensorFlowSharp. TensorFlowSharp requires this tensor as input. If the number of agents changed between steps (which does happen in more complex environments) we need to recreate a tensor with a different shape.

**Comment by ishaybe** [comment]
I didn't think on that the number of agents can change across training.
Anyway I will look deeper to this problem.
If you have any other idea it will be nice.

בתאריך יום ה׳, 24 בינו׳ 2019, 12:09 לפנה״צ, מאת Vincent-Pierre BERGES <
notifications@github.com>:

**Comment by eshvk** [comment]
Thank you for this discussion, we are going to close this issue due to inactivity for now.
