### ISSUE TITLE
Hou can I use ml-agents traning in the unity runtime?

### ISSUE THREAD

**Issue by AngealBeats** [Unity-Technologies/ml-agents#162]
Hi everyone,I like ml-agents.

I very wanna konw how can i use ml-agents traning in the unity runtime?

I haven't find the dirction in the documentation.

**Comment by vincentpierre** [comment]
Hi @AngealBeats, we do not support training in the editor at the moment. For now, if you want training, you must use python. [There](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Getting-Started-with-Balance-Ball.md) is the tutorial for the balancing ball example. I would get started with that.

**Comment by AngealBeats** [comment]
Understand,thank you vincent.
