### ISSUE TITLE
Unable to run TFSharpPlugin along with ARCore

### ISSUE THREAD

**Issue by fabiopoiesi** [Unity-Technologies/ml-agents#1620]
Hi,

I'm trying to run TFSharp along with ARCore but when I import TFSharpPlugin (without even using it in the code) I have these errors if I compile the apk (see screeshot).
I saw some other issues related to this, but they didn't work out.
I'm using Unity 2018.3.0f2 and I followed this tutorial: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-TensorFlow-Sharp-in-Unity.md

![untitled](https://user-images.githubusercontent.com/17005352/51535250-34926a00-1e48-11e9-9495-cbda72c190b2.jpg)

Cheers

**Comment by fabiopoiesi** [comment]
My temporary solution to go ahead with the project is to use Unity 2017, but it would be nice to have this problem sorted out on 2018.

**Comment by xiaomaogy** [comment]
Since we are no longer using TensorFlowSharp and this issue is no longer valid, I will close it. Feel free to open if you want to discuss more.
