### ISSUE TITLE
"Decision Frequency" property name is confusing

### ISSUE THREAD

**Issue by danaugrs** [Unity-Technologies/ml-agents#1621]
This is different from https://github.com/Unity-Technologies/ml-agents/issues/779.

The higher the "Decision Frequency" the lower the actual frequency at which decisions are made.
The property should be called "Decision Period" instead.

**Comment by xiaomaogy** [comment]
Hi @danaugrs , this is kind of confusing from your perspective. However 'Decision Period' seems more confusing.

**Comment by TashaSkyUp** [comment]
Personally decision period makes more sense to me.

**Comment by danaugrs** [comment]
@xiaomaogy this is confusing from the perspective of anyone who understands what [frequency](https://en.wikipedia.org/wiki/Frequency#Definitions) means. The "Decision Frequency" property measures the interval of time between decisions (i.e. the period), **not the decision frequency** as its name suggests!

If I increase the "Decision Frequency" property value, it will lower the actual decision frequency.
If I lower the "Decision Frequency" property value, it will increase the actual decision frequency.

The period is the reciprocal of the frequency, and that's the quantity measured. The current name is not just confusing - it's plain wrong.

Another idea for the new name is "Decision Interval".

**Comment by awjuliani** [comment]
Hi all. I agree that `Decision Frequency' is not a good name. We will meet and come up with a new name to use.

**Comment by jo3w4rd** [comment]
My 2 cents: Decision Interval is better than Decision Period. 

Interval means: "an intervening time or space." 

Period implies that it takes that long to make a decision, where in fact, the decision still happens in one simulation step no matter what the frequency/period/interval is.
