### ISSUE TITLE
Failing to learn simple function

### ISSUE THREAD

**Issue by SampaiWasTaken** [Unity-Technologies/ml-agents#1622]
Hello everyone, I started dealing with Unity ML for my finals project in school, I managed to the guided tutorials just fine and understand the basic concecpts of machine learning. My issue now is that I have to train my very own AI now, and it's not working as expected at all. 
The goal is to make a quite simple basketball game, the agent receives rewards on goal, the closer to the hoop he is and loses points whenever he falls without scoring, or the further away he lands, sounds simple enough. It works just fine when the brain is set to Player, but the external Brains starts doing the exact opposite of what it's supposed to(throwing the ball as far as possible (presumably)) at around 750k Steps.
Here's the code the Agent is using:

    [Header("BBall specific")]
    private Collider ballColl;
    public Rigidbody rb;
    public Transform hoopTrans;
    public Vector3 force = new Vector3(0, 10, 0);
    bool hasAplliedForce = false;
    Vector3 startPos;
    public float multiplier;
    int counter = 0;
    public bool hasHit = false;
    public bool hasScored = false;

	void Start () {
        startPos = this.transform.position;
        ballColl = this.GetComponent<Collider>();
	}

    public override void InitializeAgent()
    {
        rb = this.GetComponent<Rigidbody>();
    }

    private void OnTriggerEnter(Collider other)
    {
        if (other.GetComponent<Collider>().name == "TopTrig" )
        {
            hasHit = true;
        } else if (other.GetComponent<Collider>().name == "BotTrig" && hasHit)
        {
            hasScored = true;
            Debug.Log("GOAL!!");
        }

        if (other.GetComponent<Collider>().name == "bad")
        {
            
        }

    }

    public override void CollectObservations()
    {
        Vector3 relativePos = hoopTrans.position - this.transform.position;

        AddVectorObs(relativePos.z);
        AddVectorObs(relativePos.y);
       
        AddVectorObs(rb.velocity.z);
        AddVectorObs(rb.velocity.y);

    }

    public override void AgentAction(float[] vectorAction, string textAction)
    {
        float distance = Vector3.Distance(rb.transform.position, hoopTrans.position);

        if (Math.Abs(rb.transform.position.y - hoopTrans.position.y) <= 0.05)
        {
            float rew = 1 - distance / 7;
            AddReward(rew);
            //Debug.Log(rew);
        }

        //reward when scored
        if (hasScored == true && counter < 1)
        {
            AddReward(5);
            Debug.Log("scored");
            counter++;
            Done();
            
        }

        if (this.transform.position.y < -1 && hasScored == false)
        {
            AddReward(-1.0f);
            Done();
        }
        Vector3 relativePos = hoopTrans.position - this.transform.position;
       

        Vector3 controlSignal = Vector3.zero;
        controlSignal.z = Math.Abs(vectorAction[0])*-1;
        controlSignal.y = Math.Abs(vectorAction[1]*multiplier);
        if (hasAplliedForce == false)
        {
            rb.AddForce(controlSignal * 50);
            hasAplliedForce = true;
        }
    }

    public override void AgentReset()
    {
        if (this.transform.position.y < -1)
        {
            this.transform.position = startPos;
            rb.velocity = Vector3.zero;
            rb.angularVelocity = Vector3.zero;
            rb.rotation.Set(0, 0, 0, 0);
            hasScored = false;
            hasHit = false;
            counter = 0;
            hasAplliedForce = false;
        }
    }

Any help would be greatly appreciated!

**Comment by xiaomaogy** [comment]
Hi @SampaiWasTaken, we don't have the resource to help you debug your code. However the general suggestion would be try to dumb down the problem you are solving even more. Also try to provide more vector observation could help.

**Comment by eshvk** [comment]
Thank you for this discussion, we are going to close this issue due to inactivity for now.
