### ISSUE TITLE
Having a larger Time_horizon than Buffer_size does not throw an error.

### ISSUE THREAD

**Issue by TashaSkyUp** [Unity-Technologies/ml-agents#1623]
Setting the Time_horizon to be larger than Buffer_size is an invalid configuration but does not throw an error. Please make it throw a recognizable error.

**Comment by xiaomaogy** [comment]
Hi @TashaSkyUp , we've added your ask into our trello board, and will take a look at it.

**Comment by xiaomaogy** [comment]
We've looked at this bug and your potential fix, and understand the intention behind it. We will incorporate the intent behind these changes as part of a bigger refactor that is upcoming in our roadmap. Thanks for raising this for us!
