### ISSUE TITLE
Visual observation environment fails on env.reset()

### ISSUE THREAD

**Issue by beyretb** [Unity-Technologies/ml-agents#1625]
Hello!

I am facing an issue when creating an environment for training an agent from visual observations. I am using ml-agents 0.6, on Ubuntu 16.04.5 and Unity  2017.4.18.

I created a very basic environment (following the [doc)](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md ) where an agent with a camera attached sits on a plane surrounded by walls and needs to navigate to goals randomly spawned. From above (agent in blue, goal in green):

<img src="https://user-images.githubusercontent.com/6848378/51550338-163a6780-1e64-11e9-8d18-d9f77dbd10a6.png"  width=150>

When I attempt to run the getting-started notebook on this environment compiled, to display the pixels observations from the agent, the code gets stuck at:

`env_info = env.reset(train_mode=train_mode)[default_brain]`

When debugging this seems to come from environment.py (line 245):
`outputs = self.communicator.exchange(self._generate_reset_input(train_mode, config))`

which in turn is stuck on rpc_communicator.py (line 96):
`output = self.unity_to_external.parent_conn.recv()`

I get no error, it's just stuck there.

Now, where things get odd is that if I take the Pyramids example, modify it to match the above environment, then it works fine. Doing the same from the PushBlock one doesn't. 
I have attempted to copy every setting I could think of (Player, agent camera, brain...) from the Pyramids one to my newly created environment to no avail.

Let me know if you want me to share more details (screenshots or files).
Any help on this is welcome!

PS: thanks for the amazing work done on ml-agents, I'm having a lot of fun!!

**Comment by xiaomaogy** [comment]
Hi @beyretb , we don't have the resource to help you debug your specific case. Our general suggestion on this is: Just tweak the Pyramid environment into your own environment, and use that.

**Comment by beyretb** [comment]
Hi @xiaomaogy ,
Apologies if my question came out the wrong way, I was not asking for help debugging anything, but rather if there is any specific Unity and/or ml-agents configuration needed for using camera output as observations. The documentation provided does not discuss this. I appreciate that you might not have the resources to help at the moment, it would be amazing to have some in the future.

I've solved my issue by doing a fresh install of Unity and ml-agents.

Thanks a lot for your help!
