### ISSUE TITLE
There is no output during the training process at all

### ISSUE THREAD

**Issue by wicaodian** [Unity-Technologies/ml-agents#1628]
Hi There folks,
I setup my ml-agent environment and everything went smoothly and I started training my agents and models creation went smoothly fine, but suddenly next day there is NOoutput that states like this,
`INFO:mlagents.trainers: firstRun-0: 3DBallLearning: Step: 1000. Mean Reward: 1.242. Std of Reward: 0.746. Training.`

My Python version is 3.6.8
I tried changing --save-freq 
I tried using --slow (as mentioned in other issues)
But nothing is working for me.

*One thing I want to mention that I am using "Learning Brains" but still somehow I am able to control the agents during training process either it's executional process or from the editor, I am able to control the agent I double checked my setting and 'Control' is checked and brain is BouncerLearning.

![ss](https://user-images.githubusercontent.com/12078461/51618331-ec5e6f00-1f4f-11e9-821b-6df10eefe407.PNG)

**Comment by eshvk** [comment]
I am assuming you are not doing in-editor training? If so, just to make sure, are you setting the flag `--train` from the command line?

**Comment by wicaodian** [comment]
@eshvk I tried with editor and from executable process and yes I am using `--train` in my command and nothing is working.

As I mentioned in my post it was working perfectly fine but suddenly stopped working, `trainer_config` is also in it's original form nothing is changed

**Comment by wicaodian** [comment]
Issue is resolved Thanks to @vincentpierre for mentioning it.

Play it in editor and In scene for training just make sure that your agents are also assigned a learning brain not a player brain. somehow in most of my scenes my agents are assigned with player brain that is why agent was not able to train.
