### ISSUE TITLE
How many instances of a training environment should we make?

### ISSUE THREAD

**Issue by vqt123** [Unity-Technologies/ml-agents#1631]
The ball balancing example has many duplicated training environments to speed up training. The other examples do not seem to do this, why is that? What is the best practice for how many training environments to duplicate?

**Comment by MarcoMeter** [comment]
The more agents gather data, the more versatile is the distribution of experiences in the experience buffer. This can lead to a more stable training. The number of agents/environments is rather limited by the computational complexity of the environment. Too many environments and agents may slow down the simulation speed. So it's sort of a trade-off among simulation speed and the amount of data which is generated each step.

**Comment by eshvk** [comment]
Thank you for this discussion, we are going to close this issue due to inactivity for now.
