### ISSUE TITLE
How can I decide vector observation space size for a brain?

### ISSUE THREAD

**Issue by moonsh** [Unity-Technologies/ml-agents#1633]
Hi, 
In the 3Dball scene. the Observation function is

public override void CollectObservations()
{
AddVectorObs(gameObject.transform.rotation.z);
AddVectorObs(gameObject.transform.rotation.x);
AddVectorObs((ball.transform.position - gameObject.transform.position));
AddVectorObs(ball.transform.GetComponent().velocity);
SetTextObs("Testing " + gameObject.GetInstanceID());
}

So I know I need 8 vector space size straightforwardly because we need two object transformation z and x, and we need two position vector. Therefore, vector space size should be 8.

However, for the example Hallway, 

    public override void CollectObservations()
    {
        if (useVectorObs)
        {
            float rayDistance = 12f;
            float[] rayAngles = { 20f, 60f, 90f, 120f, 160f };
            string[] detectableObjects = { "orangeGoal",  "orangeBlock", "redGoal", "redBlock",  "wall" };
            AddVectorObs(GetStepCount() / (float)agentParameters.maxStep);
            AddVectorObs(rayPer.Perceive(rayDistance, rayAngles, detectableObjects, 0f, 0f));
        }
    }

**When I checked the Learning brain in the hallway example, I saw the vector space size is 36. I was trying to understand it but I failed to find any clue how to set vector space size from this observation function.**

Thank you,

**Comment by Semih67** [comment]
Hey, I'm also a beginner. How did you came to the 8? Do you not just add the Vectors? So you would have 4 instead of 8?

**Comment by moonsh** [comment]
@Semih67 

Ok, For example in the 3D ball, we need 8 vector space size because we have these 

1. gameObject.transform.rotation.z
2. gameObject.transform.rotation.x
3. ball.transform.position - gameObject.transform.position   x
4. ball.transform.position - gameObject.transform.position   y
5.  ball.transform.position - gameObject.transform.position   z
6.  ball.transform.GetComponent().velocity  x
7.  ball.transform.GetComponent().velocity  y
8.  ball.transform.GetComponent().velocity  z

Thank you,

**Comment by jo3w4rd** [comment]
@moonsh for the Hallway example, you would have to look at what RayPerception.Perceive() returns to know what the correct vector space size. I'm not familiar with how that function works, but it returns a List<float>, so each float needs to be accounted for in the vector space size. (It might return a list sized proportionally to the number of detectableObjects, the number of rayAngles, or both.) 

@Semih67 Each element in the list or vector added to the observation needs to be counted, not each call to AddVectorObs().

**Comment by cratkid** [comment]
Color

**Comment by moonsh** [comment]
@jo3w4rd 

Thank you so much.
