### ISSUE TITLE
Learning Rate changes with max steps

### ISSUE THREAD

**Issue by vqt123** [Unity-Technologies/ml-agents#1638]
It appears that learning rate is dependent on max steps. This is not obvious and feels like it shouldn't even be the case. learning rate should be an independent slope on its own. 

For example, if i setup a training for a max steps of only 50000. But want to continue it later with a max steps of 10,000,000 with the same learning rate, then I need to recalculate the new learning rate.

**Comment by harperj** [comment]
Hi @vqt123, it's true that it is not necessary for learning rate to be dependent on max steps -- however the sort of scaling we're doing here is common practice.  I agree that it would be nice to have a more flexible way of controlling LR.

We don't have any specific plan in our roadmap to change how we handle this, but I'll discuss it with our team and we'd welcome someone in the community working on this.

**Comment by eshvk** [comment]
We are going to close this issue for now, if and when it gets prioritized, this feature will be noted in our release notes.
