### ISSUE TITLE
Can the academy and agent automatically set match step from config parameters

### ISSUE THREAD

**Issue by vqt123** [Unity-Technologies/ml-agents#1639]
Would be nice if the agent and academy automatically set the max steps based on the config paramaters.

**Comment by MarcoMeter** [comment]
The PPO algorithm works with episodes. Therefore the Academy and the Agent have a Max Step property, which is not related to the max steps in the config file.

**Comment by eshvk** [comment]
Thank you for this discussion, we are going to close this issue due to inactivity for now.
