### ISSUE TITLE
Timestamp in summary output

### ISSUE THREAD

**Issue by vqt123** [Unity-Technologies/ml-agents#1641]
Would be nice to have a timestamp in the summary output to track how much time is used per step.

INFO: (TIMESTAMP) mlagents.trainers: th90-0: TimeHorizonBrain: Step: 12000. Mean Reward: 0.008. Std of Reward: 0.000. Training.

**Comment by MarcoMeter** [comment]
You can check the timestamp using tensorboard.

**Comment by vqt123** [comment]
tensorboard appears to always use steps for the x axis and not time

**Comment by eshvk** [comment]
Thank you for this discussion, we are going to close this issue due to inactivity for now.
