### ISSUE TITLE
TensorBoard evalutation

### ISSUE THREAD

**Issue by MrGitGo** [Unity-Technologies/ml-agents#1643]
I have run the game for like an hour and now I have this graphs: 
![tensorboard2-1](https://user-images.githubusercontent.com/33628476/51784940-d966bd00-2150-11e9-80f1-e7f7fca85544.PNG)
![tensorboard2-2](https://user-images.githubusercontent.com/33628476/51784942-dc61ad80-2150-11e9-87ff-52e086715750.PNG)

I don't know how to look at it and if the result is good or not for this hour. Do you think I could go with this or should I do some changes?

**Comment by vqt123** [comment]
i started a thread a couple days ago about the summary data not being reset when you train. the result of it not resetting is you get these crazy graphs where the end of your first train draws a line to the start of your next train and so forth. 

make separate run ids to stop this from happening


as for what the graphs mean , i suggest googling unity tensorboard and you’ll find a nice article that breaks it down

**Comment by eshvk** [comment]
Thank you for this discussion, we are going to close this issue due to inactivity for now.
