### ISSUE TITLE
-bash: mlagents-learn: command not found

### ISSUE THREAD

**Issue by JhihYangWu** [Unity-Technologies/ml-agents#1645]
It might be because I accidentally removed .bash_profile

"mlagents-learn --help" worked earlier today

**Comment by JhihYangWu** [comment]
python Documents/ml-agents-master/ml-agents/mlagents/trainers/learn.py --help works

But I want to use "mlagents-learn"

**Comment by Tailwhip** [comment]
Same problem :/

**Comment by Tailwhip** [comment]
I solved the problem by opening Anaconda prompt AS ADMINISTRATOR and then setting and installing repo with mlagents again.

**Comment by JhihYangWu** [comment]
Works!! Thanks!!

**Comment by xiumin1** [comment]
> I solved the problem by opening Anaconda prompt AS ADMINISTRATOR and then setting and installing repo with mlagents again.

Hi I came across the same problem, what do you mean by setting and installing repo?

**Comment by JhihYangWu** [comment]
1. Are you using macOS or Windows?
2. Can you run learn.py --help from ml-agents-master/ml-agents/mlagents/trainers/learn.py?

**Comment by xiumin1** [comment]
> 1. Are you using macOS or Windows?
> 2. Can you run learn.py --help from ml-agents-master/ml-agents/mlagents/trainers/learn.py?

I use windows, I run it under anaconda, and create a ml-agents environment, it could run now, but not be able to start the training session. The result is as follow:

                  `▀█▓▓▓▓▓▓▓▓▓▌
                        ¬`▀▀▀█▓


INFO:mlagents.trainers:{'--curriculum': 'None',
 '--docker-target-name': 'None',
 '--env': 'tests',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--no-graphics': False,
 '--num-runs': '1',
 '--run-id': '11',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': False,
 '--train': True,
 '--worker-id': '0',
 '<trainer-config-path>': 'config/trainer_config.yaml'}
Traceback (most recent call last):
  File "D:\Anaconda\envs\ml-agents\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "d:\box sync\research projects\ml-agents-master\ml-agents\mlagents\trainers\learn.py", line 114, in main
    run_training(0, run_seed, options, Queue())
  File "d:\box sync\research projects\ml-agents-master\ml-agents\mlagents\trainers\learn.py", line 46, in run_training
    docker_target_name, trainer_config_path, no_graphics)
  File "d:\box sync\research projects\ml-agents-master\ml-agents\mlagents\trainers\trainer_controller.py", line 117, in __init__
    no_graphics=no_graphics)
  File "d:\box sync\research projects\ml-agents-master\ml-agents\mlagents\envs\environment.py", line 58, in __init__
    self.executable_launcher(file_name, docker_training, no_graphics)
  File "d:\box sync\research projects\ml-agents-master\ml-agents\mlagents\envs\environment.py", line 172, in executable_launcher
    .format(true_filename))
mlagents.envs.exception.UnityEnvironmentException: Couldn't launch the tests environment. Provided filename does not match any environments.
