### ISSUE TITLE
package version and dependencies: too old libraries

### ISSUE THREAD

**Issue by wookayin** [Unity-Technologies/ml-agents#1646]
The python package `ml-agents` is dependent on **very old** versions of [dependency packages](https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents/setup.py#L30). To name a few, `tensorflow < 1.8`, `Pillow=4.2.1` (why that specific version?), `numpy>=1.13.3,<=1.14.5`, etc. This really doesn't make a sense. 

Why do you have such a requirement? I think it should be relaxed and there is no reason to be tied to these version.

**Comment by eshvk** [comment]
@wookayin Reg. `tensorflow`, we made that decision previously because the latest version (at that time) was tied to TensorFlowSharp needs. As far as the other packages, I think we'd happy to relax those constraints assuming all tests run.

**Comment by wookayin** [comment]
Hi @eshvk, thanks for your answer. It would be great to have more relaxed version requirements!

Regarding TensorFlow, I still believe we should only have a minimum version requirement (i.e. lower bound), say `>= 1.6` or whatever the recent. For example, [obstacle-tower-env](https://github.com/Unity-Technologies/obstacle-tower-env) requires `ml-agents` because of `UnityEnvironment` (but not about the other parts involving TensorFlow), restricting use of recent TensorFlow versions. I know using a recent TF version might break a few of tests, but ideally we should keep things up-to-date as well. 

One simple way would be to relax the TF version constraint in `setup.py` but use a specific version of TF (which would be the officially supported version by `ml-agents`) when running the test.

**Comment by wookayin** [comment]
Regarding https://github.com/Unity-Technologies/obstacle-tower-env/issues/21, the Unity team has been uploading and maintaining [`mlagents_envs`](https://pypi.org/project/mlagents-envs/) package to PyPi, which consists of only environment-related parts of mlagents (hence no TensorFlow, etc.)

I wish this package would be kept track of in github as well (i.e. I cannot find any history from https://github.com/Unity-Technologies/ml-agents/tree/master/ml-agents) /cc @awjuliani

**Comment by vincentpierre** [comment]
We will be splitting the mlagents package into two packages in the next release (v0.8) which will resolve part of that issue.
