### ISSUE TITLE
visual observations

### ISSUE THREAD

**Issue by zako42** [Unity-Technologies/ml-agents#1647]
I have a question regarding the size of visual observations.  What is a good size to use for width and height?  The starting default was 84 x 84 -- is that what is  "typically" used?  I'm concerned that if the camera is normally rendering at say 1080p, then scaling down to 84 x 84 could scale features out of existence.  I tried testing with 256 x 256 which I figured is not as drastic, but it takes forever to train anything, even when set to black and white.

In my project I'm trying to use downward pointing cameras which cull on some layer to display targets as colored circles.  I also have a separate downward pointing camera with a depth shader (see issue 562) to show the agent's surrounding terrain elevations.  This is for a boat, so the depth shader is kind of like showing the surrounding bathymetry like a radar or sonar, etc.  The circles could be fish or something. 
 But I was worried that if the camera is normally rendering at 1080p, wouldn't scaling down to 84 x 84 lose information?  For example if the target circles got displayed at 10 pixels radius, then getting scaled down that drastically might end up with 0 pixels, etc.

Sorry for the dumb question, but after seeing how long it was taking to train, I wanted to ask in case the way I'm trying to do this is not a good approach and waste of time.

**Comment by MarcoMeter** [comment]
Scaling an image down comes always at the cost of loosing information. Working with image input is really computationally expensive. Smaller environments could even need a whole day of training on a gaming computer.

I'd suggest to start working in a range from 64 - 128 pixels for each dimension. The dimensions of the image and number of color channels (RGB -> 3, Grayscale ->1) affect the size of the neural net and therefore the time needed to update it. Also choosing image dimensions beyond 100 could require to edit the structure of the convolutional part of the neural network, which is hardcoded.

**Comment by zako42** [comment]
@MarcoMeter  thanks very much for the info!  I will reduce my image sizes and try it out.

**Comment by eshvk** [comment]
Thank you for this discussion, we are going to close this issue due to inactivity for now.
