### ISSUE TITLE
Run id name

### ISSUE THREAD

**Issue by Semih67** [Unity-Technologies/ml-agents#1652]
I have noticed, when I start a new run with the name "firstRunTest", the model will be saved as "firstRunTest-0" why is it like this?

**Comment by MarcoMeter** [comment]
Because you can specify the number of concurrent runs with --num-runs=10.
Therefore a single run is the first one of of just one run and gets labeled as 0.

**Comment by harperj** [comment]
👍 @MarcoMeter.  This question is answered so I'm going to close the issue.  Thanks!
