### ISSUE TITLE
Rewards and environment state

### ISSUE THREAD

**Issue by cidelab** [Unity-Technologies/ml-agents#1660]
Hi, thanks to all for this amazing work. Very much appreciated.

I'm training a firefighter agent to extinguish fires randomly distributed in a terrain. The reward for the agent is 1 after every fire is extinguished. after all fires are extinguished a new set of fires are located randomly in the terrain and the agent start again.
I am in the training process and I got this: (please see the image)
![training erros](https://user-images.githubusercontent.com/4483743/52049724-5f667780-2546-11e9-8f83-d7935959c3e0.jpg)

The agent is not learning, 
What I'm doing wrong?
thanks in advance
Carlos.

**Comment by MarcoMeter** [comment]
Did you set a max step on the Academy or the agent? If the environment does not reset frequently, the console will tell you that like seen above.

25000 steps is very short.

How did you define your environment's state observation. Which parameters did you choose?

**Comment by cidelab** [comment]
Thanks a lot harperj,
I set in Agents brain the following parameters:
- maxSteps to 10,000 
- and decision frequency to 10
//
I'm using the config file without to change any hyper-parameter.
- The Space type have been set as Discrete.

Im not having anymore the message No episode was completed... although the Agent is not learning... at all.
![cumulativereward](https://user-images.githubusercontent.com/4483743/52164300-1863b800-26e7-11e9-9968-36f7f82bf0b3.jpg)

any idea?

**Comment by cidelab** [comment]
Hi @harperj  I'm still around testing and playing... unfortunately I haven't found What I'm doing wrong.

In the agents brain:
- Max Step is 25000
- reset on Done: Check
- Decision Frequency 1

 In the Academy:
- Max Steps: 10000

When the Agent hits the number of targets the Done() method is called.

I add a penalisation in every step.
    public override void AgentAction(float[] vectorAction, string textAction)
    {
        AddReward(1f/agentParameters.maxStep);
        MoveAgent(vectorAction);
    }

And since the number of fires changes in every step: my reward is normalized, So if the agent extinguish all fires, it will gets 1.
    void OnCollisionEnter(Collision collision)
    {
        if (collision.gameObject.CompareTag("fire"))
        {
           collision.gameObject.GetComponent<FireControl>().Extinguish();
            AddReward(Norm(target));
            //Debug.Log("Cumulative reward: " + GetCumulativeReward());
            countsT += 1;
        }
        if (target == countsT)
        {
            Done();
        }
    }

It make sense?

**Comment by harperj** [comment]
@cidelab Looks like you're adding a reward on every step?  `AddReward(1f/agentParameters.maxStep);`

It seems you're adding a (1/25000) reward on every step rather than a penalty?

**Comment by cidelab** [comment]
Hi @harperj Thanks a lot for your observation. You were totally right I changed to:  AddReward(-1f/agentParameters.maxStep);

The agent model showed an small improvement, but I am still far from a good performance. I will still looking the error that I'm doing.

thanks again
Carlos.

**Comment by manmeetsingh0013** [comment]
Hi @cidelab,
I am also trying do the same and having the same issue did get any lead on it?
Thanks,
Manmeet Singh
