### ISSUE TITLE
What does this MemoryError mean?

### ISSUE THREAD

**Issue by AppleiVan9** [Unity-Technologies/ml-agents#1670]
![image](https://user-images.githubusercontent.com/34593922/52157661-a762d700-26cb-11e9-93a7-c3e22c60f0b1.png)

I encountered this error when i was using both vector and visual observations to my agent.

**Comment by harperj** [comment]
Hi @AppleiVan9 -- as you might expect this is an issue where your system has run out of memory.  It's strange that we're seeing this before a significant amount of training progress though.  Have you been able to reproduce the issue?  Could you share anything about your system resource usage during the issue as well?

I'd also recommend trying to run training on our example environments and make sure this issue doesn't come up with them.

**Comment by harperj** [comment]
This issue has been inactive for a while, so I'm going to close it.  Please feel free to reopen if you continue to have trouble.
