### ISSUE TITLE
bash: mlagents-learn command not found 

### ISSUE THREAD

**Issue by OrtizDiego** [Unity-Technologies/ml-agents#1673]
I am trying to run **mlagents-learn --help**  from the bash, but I receive the error message:
![image](https://user-images.githubusercontent.com/12345832/52167160-36491100-2717-11e9-9eff-63fd99df2e13.png)

I followed the procedure described here https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md  and already checked with pip3 freeze that all required dependencies including Tensorflow, Jupyter, etc. were correctly installed. I tried to run the learn.py script but didn't worked and became following error:
![image](https://user-images.githubusercontent.com/12345832/52167179-79a37f80-2717-11e9-8216-359426dd1df3.png)
I'm using the version Unity 2018.2.7 on Ubuntu 18.04.1 LTS without Anaconda. Any ideas as to how to fix this?

**Comment by harperj** [comment]
Hi @OrtizDiego-- a couple of questions:

- Did you install mlagents from within a virtual environment?
- Did the `pip3 freeze` include the `ml-agents` library?  If not you likely need to navigate to the `ml-agents/ml-agents` folder and run `pip3 install -e .` from the installation guide.

**Comment by OrtizDiego** [comment]
Hi @harperj 
Thank you for your reply. Regarding your questions:
- Yes, it is an Ubuntu 18.04.1 LTS virtual machine running on a Windows  Server 2012 operating system 
- Yes, `pip3 freeze` includes `ml-agents` as following:

![image](https://user-images.githubusercontent.com/12345832/52733171-59e74380-2fc2-11e9-83bc-0c62fcf861ff.png)

Thank you so much for your help!

**Comment by harperj** [comment]
@OrtizDiego Seems like your `PATH` may not be including the `mlagents-learn` binary.  Maybe check `pip3 show ml-agents`?

You can also try running:
```
python ml-agents/mlagents/trainers/learn.py config/trainer_config.yaml --train
```

**Comment by harperj** [comment]
Hi @OrtizDiego -- sorry for the confusion but I was asking about the Python `virtualenv` command.  Is there any chance you are using a virtualenv before installing ml-agents?

Either way, it seems that wherever `pip3` is installing binaries, they are not added to your `PATH`.  You might try `pip3 show ml-agents` to find the path where ml-agents was installed.

**Comment by harperj** [comment]
This issue has been inactive for a while now so I'm going to close it.  If you continue to have problems with this or there's more to add please feel free to reopen.

**Comment by joobei** [comment]
I'm having the exact same issue on Ubuntu 18.04, I followed the instructions at
[https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md](url)
to the letter. There is no mlagents-learn command anywhere on my system.

**Comment by MikeyBeez** [comment]
You're using the wrong version of pip3.  You need to use python3's venv and its pip3.  I was using conda, and it doesn't work -- nor does virtualenv.  Here's the guide:  https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-Virtual-Environment.md
