### ISSUE TITLE
Use Unity InputSystem for PlayerBrain

### ISSUE THREAD

**Issue by gregaton** [Unity-Technologies/ml-agents#1674]
I would suggest using the default Unity input system for the PlayerBrain.
Instead of mapping keys we would then map the name from the input system.

I'm very aware of how cumbersome that is but it would allow more control over how the player brain is controlled. It would also enable mouse and gamepad input which is not possible atm.

**Comment by harperj** [comment]
Thanks for the suggestion @gregaton -- agreed it would be nice to have this feature, though it isn't on our team's roadmap at this time.  Labeling this as a feature request to keep track.

**Comment by unityjeffrey** [comment]
Thank you for your comments.  We’ve documented your feedback and will prioritize when appropriate.
