### ISSUE TITLE
Agent GetValueEstimate

### ISSUE THREAD

**Issue by zako42** [Unity-Technologies/ml-agents#1676]
Hello,

What is the value returned by Agent.GetValueEstimate() ?  Is this the estimated reward of the current action?  I guess the action returned would always be the highest scoring estimate out of all the actions available?

What if, for example I had 4 discrete outputs, and I wanted to visualize the "good-ness" of each action, is that the value I would use?  Could I get the values of all 4 outputs?

**Comment by harperj** [comment]
Hi @zako42 -- 

The value estimate is the estimate of future reward at the current environment state.  In PPO and other actor-critic methods both the value estimate of a given state (critic) and the action probabilities for a given state (actor) are generated at each model update step.

So, given certain observations / state for a step the model has a set of action probabilities which are used to make a weighted random decision about what to do.  To answer the main question, this wouldn't be the right thing to use to visualize the model's estimate of "good-ness" for each action.

Hope this helps,
H

**Comment by zako42** [comment]
@harperj thanks for the information.  Things are starting to make more sense and I'm slowly learning more.  So is this Advantage Actor Critic, using PPO for the policy?  I was reading about that and it sounds like what you are describing?

For my visualization, if I wanted to display the action probabilities, it looks like Agent stores the selected agent actions, which have a value.  Is that the action probability for the selected action?

If I wanted to get the other actions probabilities that were not selected in the current step, I would have to get them in CoreBrainInternal?

**Comment by saya1984** [comment]
Same question here

**Comment by harperj** [comment]
@zako42 I don't believe we expose the action probabilities to the C# code at this time, you would need to make changes to the Python trainer side to get access to this.  They should be exposed via [Policy evaluation](https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents/mlagents/trainers/ppo/policy.py#L63).

Providing a better way to access these is a good idea but I don't believe we have a plan for how we'd like to expose them at this time.

**Comment by Zilch123** [comment]
Hi @awjuliani ,
I was searching for the Action-Value function and Probability transition matrix. Are they open to access or it's not accessible? 
I was wondering about these to get the Q values for any action input, in Unity.
Thank you,
Zilch123
(P.S., Sorry for the trouble, I am still learning RL, just exploring, Hopefully someone else will find them helpful too)
