### ISSUE TITLE
Which ml agent is to be used for image classification for the models created using Tensorflow 1.12

### ISSUE THREAD

**Issue by Sreee47** [Unity-Technologies/ml-agents#1679]
Hi, 
I am trying to develop image classification using Tensorflow and unity. I have a version which works with models created using Tensorflow  1.4 and 1.7. For model created using 1.7 version of Tensorflow I am using ml agent 5.But when I use for the model using 1.12 I am not able to process it up. Is it because of the ml agent version. Should I use ml agent version 0.6 for that? 

Thanks in advance 
Sreeraj

**Comment by MarcoMeter** [comment]
As of now, ml-agents supports TF 1.7.1.

Are you actually doing reinforcement or imitation learning?

By image classification I think of supervised learning.

**Comment by Sreee47** [comment]
I am doing supervised learning.

**Comment by MarcoMeter** [comment]
Then ml-agents is completely unrelated to your project.

I suggest you to look into Tensorflow-sharp in order to use your tensorflow (python) trained model inside of unity at runtime.

**Comment by Sreee47** [comment]
Can you suggest me which version of tensorflow-sharp package for unity is to be used. Can you suggest any example for the same which i can take up as a reference.

**Comment by MarcoMeter** [comment]
I didn't look into to this area yet, so the research is up to you.

**Comment by Sreee47** [comment]
Thanks a lot. Let me give it a try . If I can get anything positive I will post it over here. For now I am closing the issue.
