### ISSUE TITLE
the soccer and tennis learning brains are not working initially, is that right?

### ISSUE THREAD

**Issue by vxgu86** [Unity-Technologies/ml-agents#1684]
should I train these envs again all by myself?
or Do I miss sth?
I am using the original params

**Comment by MarcoMeter** [comment]
Did you assign the byte files (paht: \ml-agents\UnitySDK\Assets\ML-Agents\Examples\Tennis\TFModels) to the learning brain and uncheked the control checkbox on the Academy?

**Comment by vxgu86** [comment]
Yes I did, and I found the problem: the SoccerFieldTwos in folder prefabs only count for one env And I have to set the env one by one, then it's ok.
