### ISSUE TITLE
in soccer two, what if I make there two strikers and want them to cooperate like passing balls?

### ISSUE THREAD

**Issue by vxgu86** [Unity-Technologies/ml-agents#1685]
in soccer two, what if I make there two strikers and want them to cooperate like passing balls?
should I change the reward function?

**Comment by ervteng** [comment]
You should be able to just add two strikers. The Agents may learn that passing is advantageous behavior in certain situations. It may make training less stable, though. But give it a go - I'm interested in how it will work out!
