### ISSUE TITLE
Crash when use_recurrent=true when code thinks "0 agents" are in the scene

### ISSUE THREAD

**Issue by striderdoom** [Unity-Technologies/ml-agents#1687]
Hello ML Agent folk!

I'm encountering a very odd, difficult to reproduce bug that I think I've tracked down reasonably (and hopefully you can shed some light on things!)

in `ppo/trainer.py` in the `construct_curr_info` function, line 150 to 171 has the following:

![code snippet](http://puu.sh/CIMwU/e9b33bac43.png)

If `next_info.agents` is empty, line 171 still attempts to `vstack(memory)`, yielding an error/crash.  I've changed this section to the following

![bug fix?](http://puu.sh/CIMxi/02d61d6e3f.png)

And my program no longer crashes.  As for my questions/concerns:

1. Is this a reasonable fix?  Will this cause some long term damage on my agent learning that I won't know about and perhaps a crash was correct?
2. Without the fix, my program appears to crash at RANDOM times.  That is, with ZERO changes to code, unity scene, anything, sometimes the code would crash after 3000 steps, sometimes never, sometimes after 150,000 steps.  My guess is that there's some race condition happening somewhere -- possibly that `next_info.agents` isn't getting the data in time on some ticks.
3. To answer some other expect questions -- I'm not deleting/adding any agents to my scene.  I have 1 agent that moves around an empty field and resets to its initial position on `AgentReset`.  If there's other things I should troubleshoot, do let me know!

**Comment by WHiT3R4bBiT** [comment]
Also this is on 0.6a. We had a very similar issue/fix in 0.5 and iirc it only happened when both On Demand was true AND use_recurrent=true in case that helps with a repro.

**Comment by ervteng** [comment]
Thanks for reporting this bug - it has been logged and we'll investigate it. Can you post the error/output you get during the crash? Is `memories` also empty, because `next_info.agents` is empty? 

There was an issue in 0.6 where we would have a divide-by-zero under certain conditions, but that has since been fixed. But this seems to be a different issue altogether.

**Comment by striderdoom** [comment]
Thanks for following up @ervteng !  Here's the error output:

!(Output)[http://puu.sh/CKOJW/719ff30d7e.png]

This led us to the conclusion that when `next_info.agents` is empty, `memories` will be empty, and so we implemented the "fix" in my original post.

Regarding the 0.6 issue -- you're correct in that it's a different issue.  We actually were having issues with the divide by zero issue, but it was all resolved w/ the 0.6a hotfix branch.  Thanks for that!

Please let me know if there's additional information that would be helpful.  We've been training our agents using the fix in the original post and haven't had any of the similar crashes.  However, we're still leery that we've put a bandaid on a specific problem as opposed to addressing the underlying issue (ie, maybe `next_info.agents` should never be empty?)

**Comment by striderdoom** [comment]
Bumping this issue for visibility!

**Comment by striderdoom** [comment]
Following up again @ervteng !

**Comment by ervteng** [comment]
Hey @striderdoom, thanks for posting the logs - we've logged the error and will investigate it. Could you also post the YAML file for the trainer that you're using? It may have something to do, for instance, with using LSTMs or on-demand actions.

**Comment by striderdoom** [comment]
Are you referring to `trainer_config.yaml` ?  If so, here's the configuration settings we are using

![Yaml settings](http://puu.sh/CWzIw/e2b49ccc12.png)

Also, we are using on-demand actions for our agent.  Thanks again for investigating this!

**Comment by ervteng** [comment]
Hey @striderdoom, are you still seeing this issue? From what we see, there shouldn't be a case where next_info.agents is 0, since the Agent is the one asking for the decision. I think for the time being your fix is OK. 

We changed how this portion of the mechanism works in our `develop` branch in preparation for our next release, so perhaps give that a go and see if it works. Let us know if it's still being an issue.

**Comment by striderdoom** [comment]
Thanks for the update!  Can't wait to test things out for the next release!

**Comment by WHiT3R4bBiT** [comment]
We're still seeing this issue in ML-Agents 0.8.1. The same fix, now on line 148 of /trainers/ppo/trainer.py, appears to still avoid the error.
