### ISSUE TITLE
Request for mlagents package without tensorflow

### ISSUE THREAD

**Issue by markpwoodward** [Unity-Technologies/ml-agents#1688]
The required tensorflow version in setup.py is pretty old:

tensorflow>=1.7,<1.8

This messes up tensorflow in an environment by downgrading the current version. Is there a simple work around for this? Perhaps there could be a separate setup.py for people who aren't doing training in mlagents, so no tensorflow would be installed by mlagents. Currently I reinstall tensorflow after the mlagents installation, which works but isn't ideal.

Thanks,
Mark

**Comment by MarcoMeter** [comment]
If you are not using ml-agents, why are you installing it?

**Comment by markpwoodward** [comment]
I am using ml-agents to interact with a unity environment from Python.

env = mlagents.envs.UnityEnvironment()
env.reset(...)
env.step(...)

Is there another way, other than mlagents, to interact with a unity
environment from python?

If not, it would be nice to interact with Unity mlagents without using it
for training, as I am currently doing. I would imagine that there are other
users in addition to myself who have fairly mature models and training
infrastructures and just want to use Unity for the environment.

**Comment by awjuliani** [comment]
Hi @markpwoodward 

We are actually planning to split up the `mlagents` package into two separate packages in a future release. If you'd like to try it out, we already have a version of just the environment interface here: https://pypi.org/project/mlagents-envs/. You can install it with `pip install mlagents_envs`. It has much less strict requirements, and should play more nicely with your python env.

**Comment by markpwoodward** [comment]
Excellent! Thank you

**Comment by markpwoodward** [comment]
Just tested it. That works great. Very clean. Thank you

**Comment by mattinjersey** [comment]
could you explain how to use this. it has no documentation? Will we still type activate ml-agents? Should we use the same mlagents zip file?

**Comment by markpwoodward** [comment]
@mattinjersey I believe that mlagents-envs is just mlagents.envs. I use it the same way, just changing the import statement. I didn't need to change anything when generating the binary from the editor.

```
import mlagents_envs as envs

env = envs.UnityEnvironment(...)
env.reset(...)
# loop
  env.step(...)
```

**Comment by mattinjersey** [comment]
is that a modification of learn.py or some existing program. Thx Matt

**Comment by markpwoodward** [comment]
@mattinjersey I am not familiar with learn.py. The psuedocode I wrote above is just directly instantiating and using a UnityEnvironment object. https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Python-API.md

**Comment by markpwoodward** [comment]
@awjuliani I noticed that mlagents was updated to 0.7.0 on pypi. Congratulations on the excellent progress! Are you able to do the same for mlagents-envs? It is still on 0.6.2. Which makes it incompatible with the latest SDK. Thank you!

**Comment by awjuliani** [comment]
Hi @markpwoodward 

Things are a little out of sync here because the current version of `mlagents_envs` was made as bit of a one-off to support the Obstacle Tower Challenge. With the v0.8 release of ML-Agents in a few weeks, we plan to sync `mlagents_envs` and `mlagents` from that point onward. So unfortunatly `mlagents_envs` will skip v0.7.

**Comment by markpwoodward** [comment]
Sounds good. No worries. Thank you for the info.
