### ISSUE TITLE
"Unable to load mono library" error when execute standalone executable file on Linux.

### ISSUE THREAD

**Issue by YuhangSong** [Unity-Technologies/ml-agents#1689]
I am designing my game with my Mac, and then run them on a remote Linux server (Ubuntu 16.04).

1. I generate the standalone executable file by selecting the platform x86_64, check the server build.
2. Run the executable on a remote server.

It shows:
```
yuhang@pssr:~/Arena/Arena$ ./arena/3DBall-Linux.x86_64
Set current directory to /home/yuhang/Arena/Arena
Found path: /home/yuhang/Arena/Arena/arena/3DBall-Linux.x86_64
Unable to load mono library from /home/yuhang/Arena/Arena/arena/3DBall-Linux_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
Failed to load mono
```

Any ideas?

**Comment by ervteng** [comment]
Hi Yuhang, 

This could be a result of a number of problems. Does it still happen if you build it as x86? Does the file exist in that directory?

You might have good luck asking on the Unity forums about this---there are a variety of threads regarding the mono error for different platforms. https://forum.unity.com/threads/fatal-error-failed-to-load-mono.504060/

**Comment by YuhangSong** [comment]
Many thanks!

I just found the problem is that I use git to sync the built file to my remote server. When I use the default git configuration file, the synced built file doesn’t work and produce this error, though the folder and files seems to be complete. If I use the git configuration file of this repo (or transfer the files as a zip), things works!

I guess the default git configuration file does not async some hidden files?

Many thanks again for the reply, I really struggled on this bug for the whole night!

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ervteng** [comment]
I bet there's a .gitignore for the project that ignores built files. Hence it won't commit the library files - glad you found the issue! Git isn't the best for syncing executables as such - I usually use SCP (or Cyberduck), maybe that would be easier.

**Comment by ervteng** [comment]
Closing this issue for now as you've found a solution. Feel free to repost if need be. Thanks!
