### ISSUE TITLE
Use RenderTexture instead of Camera for Visual Observation

### ISSUE THREAD

**Issue by pyjamads** [Unity-Technologies/ml-agents#1693]
Suggestion:
I would like to render straight to a RenderTexture manually and use that as visual observation instead of using a camera.
I have found a few ways to resolve it for now, but I think ML-agents would benefit from adding RenderTexture as an alternative to the Camera.

For others looking, the solution suggested here, by rendering to a texture in a canvas is a way around it: https://github.com/Unity-Technologies/ml-agents/issues/611

Another alternative would be to do something like this Frame stacking example, that supports textures as an alternative to cameras:
https://github.com/Unity-Technologies/ml-agents/issues/952

**Comment by ervteng** [comment]
That could be pretty useful for a number of cases! This feature isn't currently on our roadmap, but If a community member wants to contribute an implementation of the feature to ml-agents, it would be very much appreciated.

**Comment by pyjamads** [comment]
I created a pull request with the functionality #1698

**Comment by ervteng** [comment]
Huge thanks, we will take a look!

**Comment by pyjamads** [comment]
ups, looks like I forgot a check for the RenderTexture size.

It should be added it to the pull request.

**Comment by ervteng** [comment]
We've merged this feature into our `develop` branch, and it will show up in our next release. Thanks again for the contribution!

**Comment by pyjamads** [comment]
Thanks, that sounds great!
