### ISSUE TITLE
multiarray numpy extension failed 

### ISSUE THREAD

**Issue by benmadinebuisness** [Unity-Technologies/ml-agents#1701]
Hi guys,

Been trying to run ML agents learn, but keep getting this error, even though im using correct build of numpy:
Importing the multiarray numpy extension module failed.

Any help would be great

**Comment by dyvoid** [comment]
@benmadinebuisness Did you manage to fix this? I'm running into this exact problem.

**Comment by tsinopoli** [comment]
I am also stuck on this and haven't been able to find a solution. Any advice would be welcome!

**Comment by fool1280** [comment]
Me too.. I'm looking for a solution.

**Comment by TashaSkyUp** [comment]
There is a method someone suggested for installing with conda instead of
pip maybe try that?

**Comment by awjuliani** [comment]
Hi all.

Looks like this is an issue recently introduced by numpy. We will take a look and try to find a solution.

**Comment by tsinopoli** [comment]
I was able to get past this by reinstalling with Conda. 

`conda install numpy=1.13.1`

Than I got an issue with win32api missing which I was able to reinstall using pip

`pip install pypiwin32` 

After that I was able to launch mlagents-learn one single time then it closed itself and now I just get an "unable to start process" from conda 

Hope this helps someone!

**Comment by Salzian** [comment]
Our team fixed this issue by using a custom yaml installation file.

https://gist.github.com/Salzian/80d34cd486bcdd1d125c2b9045b66349

Install it using

`conda env create -f environment.yaml`

Make sure to delete the existing ml-agents environment first.

**Comment by vincentpierre** [comment]
This does not seem to be a ML-Agents issue. https://github.com/ContinuumIO/anaconda-issues/issues/1508

**Comment by kazurati** [comment]
After all there is no solution?

**Comment by fool1280** [comment]
> After all there is no solution?

you can reinstall with 
`conda install numpy==1.15.4
pip install pypiwin32`

Mine works perfectly.
