### ISSUE TITLE
typo in Installation-Windows.md

### ISSUE THREAD

**Issue by dmalpica** [Unity-Technologies/ml-agents#1706]
**With your approval, I'd like to submit a fix for the windows installation guide:**

**The instructions are a little unclear as there is no mention of invoking the 'python' command to launch the REPL from the Anaconda Prompt.**

> Lastly, you should test to see if everything installed properly and that TensorFlow can identify your GPU. In the same Anaconda Prompt, type in the following command:
> 
> import tensorflow as tf
> 
> sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

**I can see the problem in the markdown, the word 'python' is on the same line as the opening triple single quotes.**

**Thanks for the guide!**

**Comment by dmalpica** [comment]
I would also like to add a warning to this guide: Installing the CUDA toolkit as is may overwrite your Nvidia display drivers. This can cause problems with other applications such as photoshop, Maya and 3D Studio Max.

**Comment by awjuliani** [comment]
Hi @dmalpica 

Thanks for your interest in the ML-Agents toolkit. Please feel free to make a PR with these changes. We can review them from there.

**Comment by awjuliani** [comment]
Closing this issue for now. Please feel free to re-open if you deem it necessary.
