### ISSUE TITLE
How to start learning or play a output model when I press button

### ISSUE THREAD

**Issue by cyzhzhd** [Unity-Technologies/ml-agents#1709]
Hi 

I am having a trouble with controlling when to start learning or play output models.

For now, it seems like it automatically start learning or play ouput model when I press 'Play' in unity.

However , I'd like to do those things when I press certain UI button using OnclickStartbtn() function.

Any ideas are welcome.

**Comment by awjuliani** [comment]
Hi @cyzhzhd,

There are a few approaches to solving this. The simplest one is to switch out the brain attached to the agent when you trigger some event in the scene. You can start by attaching a heuristic brain which does nothing, and then use `GetBrain` on the agent to switch brains to the learning or player brain that you are interested in using.

**Comment by cyzhzhd** [comment]
Thank you for your help @awjuliani 

Can you let me know how to use GetBrain function if you can?

I can not find some examples on Internet.

I'm doing this project for my lab and I'm quite new with Unity :(

**Comment by awjuliani** [comment]
Hi @cyzhzhd 

You can look at the code for the `WallJump` environment to see how to use `GetBrain()`. In that environment we switch between two brains during training. https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Examples/WallJump/Scripts/WallJumpAgent.cs

**Comment by awjuliani** [comment]
Due to inactivity, I am closing this issue for now. Please feel free to re-open if you deem it necessary.
