### ISSUE TITLE
Problem with JobTempAlloc has allocations that are more than 4 frames old

### ISSUE THREAD

**Issue by SestoAle** [Unity-Technologies/ml-agents#1710]
Hi,

when training my env at random time I got this warning and my training stops:

`**Internal: JobTempAlloc has allocations that are more than 4 frames old - this is not allowed and likely a leak**
(Filename: ./Runtime/Allocator/ThreadsafeLinearAllocator.cpp Line: 372)
To Debug, enable the define: TLA_DEBUG_STACK_LEAK in ThreadsafeLinearAllocator.cpp. This will output the callstacks of the leaked allocations`

It only appears in training mode and I don not know what causes it. 

I implemented my game with hybrid ECS, but I disable all my parallel job system when the game starts, so in training mode there aren't any job active.

Anyone knows how can I resolve this?

**Comment by awjuliani** [comment]
Hi @SestoAle,

I have not seen this issue before. This sounds like an error with ECS, rather than the ML-Agents package. Can you share more information about your Unity version and OS platform?

**Comment by SestoAle** [comment]
I use Unity v2018.3.5f1 and the training phase is done in Linux (I built a Linux version of the game in MacOS), and I also think that is related to ECS, but it only appears in training mode so I don't know how to replicate it. Also, the only systems that use ParallelJob are disabled when the game starts, so there are no active jobs and I don't know why this error comes.

**Comment by awjuliani** [comment]
@VilmantasBal Have you seen this error before?

**Comment by jo3w4rd** [comment]
The error is from the JobSystem and is pretty much what the error says. The JobSystem allows you to allocate memory with different "longevity," the fastest, most efficient for temporary memory is Allocator.Temp -- which has this safety restriction. See https://docs.unity3d.com/Manual/JobSystemNativeContainer.html for more info.

I'm not sure at this point how hybrid ECS works with FixedUpdate. Possibly, the Time Scale/ Target Framerate changes ML-Agents does during training is fooling the Job System somehow.

**Comment by VilmantasBal** [comment]
I haven’t seen this error and ml agents dont use ECS,  not even in hybrid
mode.

Can getting temporary render texture cause this error ?

Kind regards,
Vilmantas

**Comment by jo3w4rd** [comment]
@VilmantasBal The project that triggered this report is using ECS and ML-Agents together.

**Comment by zioth** [comment]
I'm seeing this error too. It started as soon as I upgraded to 2019b1, and it produces warnings endlessly from the moment I start my game. I haven't deliberately written any multithreaded code, and while I do have a static class (my game controller singleton), everything is read-only, so I don't expect any race conditions.

I wish this error had a stack trace! I don't know how to "enable the define TLA_DEBUG_STACK_LEAK"

**Comment by SestoAle** [comment]
I see that if I start the training rendering the game, it goes obviously a little slower but the warning disappears. So is there a way to limit the speed of execution a bit to test if it’s really a speed problem?

**Comment by awjuliani** [comment]
Hi all, 

Due to inactivity, I am closing this issue for now. Please feel free to re-open if you deem it necessary.

**Comment by jjxtra** [comment]
Seeing this with a blank project just LWRP, shader graph and post process. Latest Unity 2019.1.

**Comment by nukadelic** [comment]
Try different Unity version.
