### ISSUE TITLE
3D Ball not saving summaries or model

### ISSUE THREAD

**Issue by ErikSvedin** [Unity-Technologies/ml-agents#1711]
I'm following the starter guide [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Getting-Started-with-Balance-Ball.md). 

I'm getting to the point where i run `mlagents-learn ../config/trainer_config.yaml --run-id=test --train` and get prompted to press play in unity. When I press play I can see the scene starting in a speeded up way. In my terminal I get a message saying training has started and the current hyperparameters.

However thats where the fun ends. I never recieve a 'Saved model' or 'Saved summary' message, and my model/summary dirs are empty even after 15 min+ of training. I've tried started `ml-agents-learn` with `--save-freq': '1'` as well as set the summary-freq in conf to 1. But no luck.

I get a tensorflow warning saying 
```
I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
```

However I'm not sure that is related to what I'm experiencing. What could I be missing?

**Comment by awjuliani** [comment]
HI @ErikSvedin 

I am sorry to hear you are having these issues. That tensorflow message you see does not affect training, and can be safely ignored. 

Are you able to see output in the console regarding agent performance, and is the agent behavior in the test scene improving?

**Comment by ErikSvedin** [comment]
@awjuliani no I'm not seeing any output in the console regarding any agent performance. After I press play in unity I get a message that the training starts succesfully and all the hyperparameters and so on. But I dont get any periodic updates about agent performance. Ill provide a dump:

```
'Ball3DAcademy' started successfully!
Unity Academy name: Ball3DAcademy
        Number of Brains: 1
        Number of Training Brains : 1
        Reset Parameters :

Unity brain name: 3DBallLearning
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 8
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): [2]
        Vector Action descriptions: ,
2019-02-15 09:00:58.333516: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:mlagents.envs:Hyperparameters for the PPO Trainer of brain 3DBallLearning:
	batch_size:	64
	beta:	0.001
	buffer_size:	12000
	epsilon:	0.2
	gamma:	0.995
	hidden_units:	128
	lambd:	0.99
	learning_rate:	0.0003
	max_steps:	100
	normalize:	True
	num_epoch:	3
	num_layers:	2
	time_horizon:	1000
	sequence_length:	64
	summary_freq:	10
	use_recurrent:	False
	summary_path:	./summaries/test-0_3DBallLearning
	memory_size:	256
	use_curiosity:	True
	curiosity_strength:	0.01
	curiosity_enc_size:	128
	model_path:	./models/test-0/3DBallLearning
```

And regarding agents in the scene I cant say that they improve at all. They keep dropping the ball. 

I'm running the `mlagents-learn ...` command from a virtualenv where I have python3 whereas my standard python installation is 2.7 if that has anything to do with it. However I guess not since it seems to be able to connect to unity, but no actual training seems to be done.

**Comment by ErikSvedin** [comment]
Hello again @awjuliani!

I was able to fix this by manually switching all the agents brains to the LearningBrain. I'm not sure if that is in the documentation or if I missed it. But swapping out the playerbrains to learningbrain for each agents started the training successfully!
