### ISSUE TITLE
frozen model not loading

### ISSUE THREAD

**Issue by Amanpradhan** [Unity-Technologies/ml-agents#1713]
I have made an object detector in mobilenet ssd but when I freeze it and use it in unity, I am getting the error:
TFException: Input 0 of node save/Assign_89 was passed float from BoxPredictor_5/ClassPredictor/biases/ExponentialMovingAverage:0 incompatible with expected float_ref.
TensorFlow.TFStatus.CheckMaybeRaise (TensorFlow.TFStatus incomingStatus, System.Boolean last) (at <1fe2de69842a4a4ba15256b83cca05f3>:0)
TensorFlow.TFGraph.Import (TensorFlow.TFBuffer graphDef, TensorFlow.TFImportGraphDefOptions options, TensorFlow.TFStatus status) (at <1fe2de69842a4a4ba15256b83cca05f3>:0)
TensorFlow.TFGraph.Import (TensorFlow.TFBuffer graphDef, System.String prefix, TensorFlow.TFStatus status) (at <1fe2de69842a4a4ba15256b83cca05f3>:0)
TFClassify.Detector..ctor (System.Byte[] model, System.String[] labels, System.Int32 inputSize) (at Assets/Scripts/Detector.cs:41)
PhoneCamera.LoadDetector () (at Assets/Scripts/PhoneCamera.cs:163)
PhoneCamera.LoadWorker () (at Assets/Scripts/PhoneCamera.cs:146)
PhoneCamera.Start () (at Assets/Scripts/PhoneCamera.cs:53)

**Comment by awjuliani** [comment]
Hi @Amanpradhan 

This looks like an issue with TensorFlowSharp. I would recommend posting in their GitHub issues. https://github.com/migueldeicaza/TensorFlowSharp
