### ISSUE TITLE
The communicator was unable to connect error in unity and unityenv took too long to respond in anaconda promp

### ISSUE THREAD

**Issue by Torosentao6969** [Unity-Technologies/ml-agents#1714]
I can train the 3dballbrain in anaconda promp, i have been looking for solutions here but i cant found mine.

So i have followed the instructions of getting started with 3dball, i had to reinstall the same version of (numpy) using "conda install" and install (pywin32) to avoid some errors and see in the anaconda promp  that mlagents-learn works, but then it does conect with the unitySDK when i hit play. Please if need more info tell me.

![prueba](https://user-images.githubusercontent.com/45673270/52862608-ee25e780-3135-11e9-8485-989b77cf0e79.png)

**Comment by awjuliani** [comment]
Hi @Torosentao6969 

Did you ensure that you launched the python command before clicking play? Doing the two in the wrong order would give you the current error.

**Comment by Torosentao6969** [comment]
yea, i first launch the mlagents-learn and then i go to unity and press play

**Comment by awjuliani** [comment]
Hi @Torosentao6969 

There may be an issue with your firewall settings. Please ensure that port 5005 is open and available for communication between the Unity Editor and the python process. Alternatively you can try building the environment, and launching it from the `mlagents-learn` command directly.

**Comment by Torosentao6969** [comment]
Hi, i can confirm that the function mlagents-learn opens a local port on 5005, and unity is on firewall exceptions.
I also tried a very basic listener made in python, puted in port 5005 and pressed play in the unity 3dball scene, it didnt conected with anything. I dont know if this makes sense lol.
i dont know what to do so im gona go to the create executable tutorials and see what hapens there, ty for your help

**Comment by benfknzen** [comment]
I had this working in older versions.

I am getting this same issue now as you did in your original post, ran through and did the same things as mentioned in your posts. Recloned the repository.

Thoughts?

**Comment by chriselion** [comment]
@benfknzen This is a really old issue - can you create a new one and add your logs there?
