### ISSUE TITLE
ML-Agents Play Mode Immediately Ends?

### ISSUE THREAD

**Issue by benmadinebuisness** [Unity-Technologies/ml-agents#1715]
Hi Guys, so I'm trying to do imitation learning, I had a couple of issues before this, relating to not enough cameras in the scene for the agent to learn (Not sure if this could be related, that why Im mentioning it) but I fixed that by placing in cameras and linking them to the brains. 
But know when I try to play the game in order for the agents to learn the scene automatically stops as soon as I hit play and I havent got a clue what is causing it...
This is the picture from the cmd: 
![brain errors](https://user-images.githubusercontent.com/46612079/52873132-30efbb80-3146-11e9-99a6-fba0d382740f.JPG)
Thanks for any help, much appreciated!

**Comment by awjuliani** [comment]
Hi @benmadinebuisness 

It looks like you need change the parameter of your `.yaml` file to point `brain_to_imitate` to the brain you'd like to imitate, rather than `<Your Brain Asset Name>` which is just a placeholder.

**Comment by benmadinebuisness** [comment]
> Hi @benmadinebuisness
> 
> It looks like you need change the parameter of your `.yaml` file to point `brain_to_imitate` to the brain you'd like to imitate, rather than `<Your Brain Asset Name>` which is just a placeholder.

Hi thanks for the reply but that was my first try. In the image ive set the brain imitate brain to the correct one called teach: 
![brainerror2](https://user-images.githubusercontent.com/46612079/52879825-1aeaf680-3158-11e9-8503-057ba0b18ead.JPG)
 Thanks
