### ISSUE TITLE
RayPerception in 2D simulation

### ISSUE THREAD

**Issue by Raf0** [Unity-Technologies/ml-agents#1716]
Hi,

I wanted to use RayPerception in my 2D simulation:
```
float rayDistance = 20f;
float[] rayAngles = { 0f, 45f, 90f, 135f, 180f, 110f, 90f, 70f };
string[] detectableObjects = {"Target", "Obstacle"};
AddVectorObs(rayPer.Perceive(rayDistance, rayAngles, detectableObjects, 0f, 0f));
```
but I am always getting vector "00100010001000100010001000100010" (not detected anything).

I looked into code and I think it is working only for 3D simulations.

Am I right?
Are you planning to add support for 2D simulations?

**Comment by awjuliani** [comment]
Hi @Raf0 

The current `RayPerception` code is designed exclusively for use in 3D environments similar to the ones provided as examples. It is certainly possible to modify the functions we provide to create a 2D version however. If you or someone in the community would like to do this, we would be happy to accept it as a contribution to the repository.

**Comment by awjuliani** [comment]
Thanks again for the PR! Closing this issue for now. Please feel free to re-open if you deem it necessary.
