### ISSUE TITLE
In Basics Guide sections should be switched

### ISSUE THREAD

**Issue by borisneal** [Unity-Technologies/ml-agents#1719]
In the docs/Basic-Guide.md:

The getting-started Jupyter notebook runs a 3DBall env that depends on Ball 3D Academy component "Control" box being checked. However, instructions to do that are located in the section that follows the notebook section. Could the sections be re-arranged or this crucial step mentioned earlier?

**Comment by awjuliani** [comment]
Hi @borisneal 

Thanks for pointing this out. Would you be willing to make a PR to our documentation to address this?

**Comment by awjuliani** [comment]
Thanks again for the PR! Closing this issue for now. Please feel free to re-open if you deem it necessary.
