### ISSUE TITLE
UnityEnvironmentException : Unity environment took too long to respond.

### ISSUE THREAD

**Issue by TheChrizZly** [Unity-Technologies/ml-agents#172]
#Hello,

I tried the 3DBall Tutorial. But when I try to load the environment I get the error:
![error](https://user-images.githubusercontent.com/9589769/33902768-5f30f612-df76-11e7-855a-743d5049e811.png)

As the issue was often solved by selecting the Brain Type in Ball3DBrain as external I want to add that I did this and double checked it.

I am using Windows 10 with Anaconda Python 3.6

EDIT: I don't get any prompt to Accepts incomming communication. Unity opens with the 3D Balls Tutorials and the balls just fall down. After a few seconds Unity quits and I get this error

**Comment by awjuliani** [comment]
Hi @TheChrizZly,

Can you try building the 3DBall binary in "Development" mode (https://docs.unity3d.com/560/Documentation/Manual/PublishingBuilds.html). When you launch it, you can see whether there are errors on the Unity side, which might be responsible for the lack of connection.

**Comment by NinaMaz** [comment]
Hello! Have you been able to solve this?

**Comment by TheChrizZly** [comment]
Here is what helped me:
1) Change brain to external.
2) save the scene and the project.
3) exit unity. and open the project again.
4) check if the brain is still on external (if not repeat 1-4) (I guess it have some issues with saving it properly)
5) delete (or move it away) all the 3d ball data folder and the exe from your previous builds.
6) build the project 
7) check if its working (if not repeat 5-7 (if brain isnt on external repeat from 1)).

For some strange reason it worked for me at the 4th build without changing anything (just by deleting it and rebuilding it).
