### ISSUE TITLE
Access to brain script through other script

### ISSUE THREAD

**Issue by MrGitGo** [Unity-Technologies/ml-agents#1720]
I have a GameManager script and I wanted to change the graph model while the game is running through script: 

```
public GameObject brain;

void function(){
    brain.GetComponent<????>()
}
```

And here I noticed that I can't have access to the script like this. Do you know how to do this? And would I get problems if I change the Graph model while the game is running? My intention is to increase the degree of difficulty of the game.

**Comment by awjuliani** [comment]
Hi @Semih67 

This is an interesting use-case, and it should definitely be possible. What version of ML-Agents are you using? As of v0.6, Brains are not gameobjects, but rather scriptable objects. You will want to access the learning-brain you are using, and grab the model variable to change it.

**Comment by Semih67** [comment]
I know this is a little bit late but could write the code line of how I can access the scriptable object? @awjuliani

**Comment by awjuliani** [comment]
Hi @Semih67 

Here is the line where the model is defined: https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Scripts/LearningBrain.cs#L42. It is publicly accessible, so you should be able to set it from another script.

**Comment by eshvk** [comment]
Hi @MrGitGo, I am going to close this issue for now due to inactivity. Hopefully you were able to resolve your issue.  Please feel free to reopen if you still have issues.
