### ISSUE TITLE
Relative position

### ISSUE THREAD

**Issue by MrGitGo** [Unity-Technologies/ml-agents#1722]
I have a shooter game and I want to get the relative position from my agents to the player. I tried it with this but I'm not sure if it's the correct way to do it:

```
AddVectorObs(gameObject.transform.InverseTransformPoint(academy.player.transform.position));
            AddVectorObs(gameObject.transform.InverseTransformDirection(academy.player.transform.position));
```

I'm using both to collect observations

**Comment by awjuliani** [comment]
Hi @Semih67

I would recommend debugging these values to ensure they correspond to the values you expect. You can use `Debug.Log()` to print them out in the console/log.

**Comment by awjuliani** [comment]
Due to inactivity, I am closing this issue for now. Please feel free to re-open if you deem it necessary.
