### ISSUE TITLE
`env.render()` with the Python API

### ISSUE THREAD

**Issue by MoMe36** [Unity-Technologies/ml-agents#1723]
Hi ! 
Is there a way to visualize the agent performance after training if an external python script has been used for training ? In other words, what is the way to call `env.render()` ?

Thanks !

**Comment by awjuliani** [comment]
Hi @MoMe36 

We don't have `env.render()`, but we do have `env.reset(train_mode=False)`. This will run the environment in "inference mode," allowing you to see this happening in the window in realtime.

**Comment by awjuliani** [comment]
Due to inactivity, I am closing this issue for now. Please feel free to re-open if you deem it necessary.
