### ISSUE TITLE
Using my own Keras/TF Model

### ISSUE THREAD

**Issue by jkim447** [Unity-Technologies/ml-agents#1726]
I collected a dataset using Python API, and trained a custom network using Keras. Now, I want to bring this model inside Unity Editor for inference. The less-preferred way is to do inference using the Python API as well, but I want it to be more interactive and use it inside Unity.

My model takes-in multiple  images AND vector observations as input.  A question arises here - how would Unity editor be able to know  how different image/vector input should be channeled to  my network? 

If I'm not mistaken, it looks like I might have to make some changes in trainer.py or learn.py. If you have some quick pointers on implementing this at a design level, that would be GREAT.

**Comment by MarcoMeter** [comment]
You can use TensorflorSharp. You pretty much have to make sure that the graph, which you created with keras, is compatible with the current version of TensorflowSharp.

**Comment by awjuliani** [comment]
Hi @jkim447 

You will have to make sure the input and output nodes have the same names as the ones produced by our `mlagents.trainers` package. See here for names of nodes we use: https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Scripts/InferenceBrain/TensorNames.cs

**Comment by mattinjersey** [comment]
interested to see how you did the custom training, if possible. Did you use the Python API.

**Comment by mattinjersey** [comment]
actually I see the Jupyter notebook in the docs, that is quite helpful.

**Comment by eshvk** [comment]
Hi @mattinjersey, I am going to close this issue for now due to inactivity. Hopefully you were able to resolve your issue.
