### ISSUE TITLE
How to use a saved trained model to run the game in unity

### ISSUE THREAD

**Issue by Usmaniatech** [Unity-Technologies/ml-agents#1729]
I have trained a model in unity ML agents. I have a saved model file in my models folder. If I press the run button in unity, I does not work. If the model is trained, how can I give that model to someone else so that he add it in their project and run the game.

**Comment by TashaSkyUp** [comment]
They need to import the Tensorflow sharp plugin. then they need to set the
agent and academy up and point the agent to the .bytes file. there are
instructions somewhere in the documentation.

**Comment by Usmaniatech** [comment]
Thankyou. Its working.
