### ISSUE TITLE
Support for Deep Q Learning for FlappyBirdLike

### ISSUE THREAD

**Issue by samre12** [Unity-Technologies/ml-agents#173]
I am trying to train an agent to play FlappyBirdStyle (as followed from the official tutorial) using Deep Q Learning. For that purpose a new action is chosen after every 4 frames and the same action is taken for interim frames. 
I need to get the frame snapshots for the past 4 frames as the state of the agent to decide the next action. Please guide me how to feed this as a state to the learning algorithm (The dimensionality will be quite high of the order of millions for decent screen resolution). To be specific, how to implement `CollectState()` function of the agent to achieve the above mentioned use case.
 Any help is appreciated 😄 .

**Comment by MarcoMeter** [comment]
You could solve this by saving the inputs to a list inside your agent class. Whenever CollectState is triggered  you add the inputs (ideally as a struct) to that list (or array). As soon as you got 3/4 frames collected (the array/list should not grow continuously), you can consider these past inputs for your state space.

**Comment by samre12** [comment]
I plan to use `RenderTexture` and `Texture2D` to capture the frame images in  TemplateAgent.cs and store them in a suitable struct. 
The issue remains is how to emit this state back to the learning algorithm? One naive approach is to just cast all the pixel values into float arrays, concatenate them and generate gigantic state vector of floats and pass it to the learning algorithm. 
Is there any other alternative to this?

**Comment by awjuliani** [comment]
Hi @samre12,

There are a few possible solutions. The simplest is to do the frame stacking on the python side, as is typically done with the Atari Learning Environment. This isn't as automated a solution though. We are actually planning on implementing state/observation stacking in the near future, but if you get something working, feel free to contribute it as a PR, and we would be happy to incorporate it.

**Comment by awjuliani** [comment]
Another simpler solution which might work is to simply take the difference between the current and previous frame, which might capture all the temporal information you need for flappy bird.

**Comment by samre12** [comment]
Thanks @awjuliani for the reply. Can you guide me through frame stacking at the pyhton side as how to implement using the Unity ML Agents API?
Any help will be highly appreciated 😄 .

**Comment by MarcoMeter** [comment]
@awjuliani That would look similar introducing a temporal window, which is used in DQN, right?

**Comment by awjuliani** [comment]
@MarcoMeter yep. Collect the past `n` observations and concatenate them together along the depth dimension. Something equivalent can be done as well for state vectors.
