### ISSUE TITLE
Is there a multi-agent version of Curiosity available? 

### ISSUE THREAD

**Issue by salimoha** [Unity-Technologies/ml-agents#1730]
Is there a multi-agent version of Curiosity available? Even maybe with heterogeneous agents?

**Comment by awjuliani** [comment]
Hi @salimoha 

We do not have a version of Curiosity specifically designed to take advantage of information from other agents. That being said, it is possible to train multiple heterogeneous agents within a single environment using Curiosity on each.

**Comment by awjuliani** [comment]
Due to inactivity, I am closing this issue for now. Please feel free to re-open if you deem it necessary.
