### ISSUE TITLE
Demonstration Recorder

### ISSUE THREAD

**Issue by whiteGhost333** [Unity-Technologies/ml-agents#1731]

**Comment by whiteGhost333** [comment]
Have to ask an embarrassing question.  What did I miss here.  The recorder script is added to teacher agent in banana collector.  Press play and click the box and then ...
 
NullReferenceException: Object reference not set to an instance of an object
MLAgents.DemonstrationRecorder.WriteExperience (MLAgents.AgentInfo info) (at Assets/ML-Agents/Scripts/DemonstrationRecorder.cs:51) 

Created a folder Assets/Demonstrations

**Comment by vincentpierre** [comment]
Hi @whiteGhost333 
Thank you for your comment, I was able to reproduce your issue.
Unfortunately, it is not possible to check the `Record` box at runtime, the box has to be checked at initialization. So you must 1. Click the box 2. Press Play

**Comment by whiteGhost333** [comment]
hey, thanks didn't catch that it needed to be initialized in that state.  I
would assume then that it should be unchecked in every other circumstance.
