### ISSUE TITLE
Env soccer can't restart

### ISSUE THREAD

**Issue by wwxFromTju** [Unity-Technologies/ml-agents#1741]
I used the latest version of mlagents, simple bulid soccer and Hallway, then ran the getting-started notebook and found that they were stuck in the reset` ( more specifically: outputs = self.communicator.exchange( Self._generate_reset_input(train_mode, config) ) )`
For other environments, I have tried both environments under the crawler，it is ok.

**Comment by vincentpierre** [comment]
It seems to be working for me. Could you give more information? What Operating System are you using? Did you make sure there was no error in the environment (You can do so by doing checking __Development Build__ in the build options)? Are you able to perform in editor training for those environments ?

**Comment by wwxFromTju** [comment]
/xxxxxxxx/anaconda3/envs/uagent/bin/python /xxxxxxxx/codes/ad_hoc_teamwork/unity_soccer/test_env.py
Python version:
3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Mlagens version:
API-6

CrashReporter: initialized
Mono path[0] = '/xxxxxxxx/codes/ad_hoc_teamwork/unity_soccer/env/Soccer-normal.app/Contents/Resources/Data/Managed'
Mono config path = '/xxxxxxxx/codes/ad_hoc_teamwork/unity_soccer/env/Soccer-normal.app/Contents/MonoBleedingEdge/etc'
PlayerConnection initialized from /xxxxxxxx/codes/ad_hoc_teamwork/unity_soccer/env/Soccer-normal.app/Contents/Resources/Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55500
Multi-casting "[IP] 10.242.222.208 [Port] 55500 [Flags] 2 [Guid] 4223844885 [EditorId] 1602455005 [Version] 1048832 [Id] OSXPlayer(xxxxxx.local) [Debug] 0 [PackageName] OSXPlayer" to [225.0.0.222:54997]...
Started listening to [0.0.0.0:55500]
PlayerConnection already initialized - listening to [0.0.0.0:55500]
INFO:mlagents.envs:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 2
        Number of Training Brains : 2
        Reset Parameters :
		
Unity brain name: StrikerLearning
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 112
        Number of stacked Vector Observation: 1
        Vector Action space type: discrete
        Vector Action space size (per agent): [7]
        Vector Action descriptions: 
Unity brain name: GoalieLearning
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 112
        Number of stacked Vector Observation: 1
        Vector Action space type: discrete
        Vector Action space size (per agent): [5]
        Vector Action descriptions: 

 I can see the graphics, but it can move. env stuck in reset func.

**Comment by wwxFromTju** [comment]
It seen that the python can't connect the env. And when I run the env in Unity:
![image](https://user-images.githubusercontent.com/14865611/53214263-f24a8b80-3686-11e9-9700-4d3e2931a844.png)
I find the python can connect this env, and than:
`Traceback (most recent call last):
  File "/xxxxx/test_env.py", line 29, in <module>
    env_info = env.reset(train_mode=train_mode)[default_brain]
  File "/xxxxx/ml-agents/mlagents/envs/environment.py", line 262, in reset
    self._n_agents[_b] = len(s[0][_b].agents)
KeyError: 'HallwayLearning'`

**Comment by wwxFromTju** [comment]
It seem that:
`s = self._get_state(rl_output)`  in reset func get wrong:
print(s) --> ({}, False)

**Comment by vincentpierre** [comment]
I do not understand what you mean by 
> I can see the graphics, but it can move. env stuck in reset func.

If the agents are moving in the game window but the python env is stuck in reset, my guess is that the agents do not have the right Brain or that the Control checkbox in the academy is not set.

**Comment by wwxFromTju** [comment]
this set is fine?

<img width="470" alt="image" src="https://user-images.githubusercontent.com/14865611/53215326-1c9e4800-368b-11e9-9057-75c0122d8228.png">

**Comment by wwxFromTju** [comment]
oh, I foget set the brain in Prefabs!
