### ISSUE TITLE
player brain does not work

### ISSUE THREAD

**Issue by xiumin1** [Unity-Technologies/ml-agents#1742]

**Comment by xiumin1** [comment]
Hi, I've recreated the Reacher scene and extended it a little bit with obstacles around. So I want to try it with player brain, but the keyboard does not work at all. Can any one help me for this?

**Comment by vincentpierre** [comment]
Your settings look okay, are you sure the Brain is connected to the right agent? 
Are you sure the actions the agent receives are correct? (You can use debug statements in AgentAction)
I very quickly made a player brain for the demo reacher and it was working for me, could you try to use the demo reacher scene as a starting point?

**Comment by xiumin1** [comment]
Yes, I forgot to mention that, I had tried it in Reacher scene with a player brain, and it worked fine. It just did not work in my own scene. 

I have selected my player brain in both xxagent script component and xxacademy component. I thought this is the way to setup a player brain. 

I am not sure how to check the actions the agent receives are correct or not, but I do add debug statements in the agentaction function, and there is no output in console.

**Comment by vincentpierre** [comment]
If there are no outputs in the console, then it means the AgentAction method is not called at all. Are there any errors being logged in the console? What is the DecisionFrequency of the Agent? There is probably something that is different between the demo crawler scene and the scene you created, this can help you track the problem down. Maybe compare the component's values in the inspector?
