### ISSUE TITLE
Windows environment: Unity environment took too long to respond

### ISSUE THREAD

**Issue by mhr** [Unity-Technologies/ml-agents#1749]
Hi all,

I'm trying to follow https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md, but when I switch from Player to Learning Brain (https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md#training-the-environment) and hit Play, Unity freezes, and I receive a "mlagents.envs.exception.UnityTimeOutException" error.

Unity (with Learning Brain enabled for the Agent) freezes on Play irrespective of if I've called `mla-agents`, but I'm suspicious that the network issue that `mla-agents` outputs is related to the freezing issue. Perhaps Unity expects to be able to read/write to a socket, and when that socket isn't available, it freezes. If `mla-agents` opensed sockets properly, maybe there wouldn't be a freeze. I'm not sure.

Below is my CLI output. I'm on Windows 10 with Unity version 2018.3.5f1. The `mlagents-learn` command doesn't appear to have a --version flag, but I only installed Unity ML-Agents a few days ago, so it should be fresh. Please let me know if you need any further information.

```
C:\Users\mhr\Documents\Jobs\2019 - Spring\ml-agents>mlagents-learn ./config/trainer_config.yaml --run-id=test --train
c:\programdata\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


                        ▄▄▄▓▓▓▓
                   ╓▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
          ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
          ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓▌
                        ¬`▀▀▀█▓


INFO:mlagents.trainers:{'--curriculum': 'None',
 '--docker-target-name': 'None',
 '--env': 'None',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--no-graphics': False,
 '--num-runs': '1',
 '--run-id': 'test',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': False,
 '--train': True,
 '--worker-id': '0',
 '<trainer-config-path>': './config/trainer_config.yaml'}
E0222 13:31:17.193000000 16108 src/core/ext/transport/chttp2/server/insecure/server_chttp2.cc:40] {"created":"@1550860277.193000000","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":307,"referenced_errors":[{"created":"@1550860277.193000000","description":"Failed to add port to server","file":"src/core/lib/iomgr/tcp_server_windows.cc","file_line":508,"referenced_errors":[{"created":"@1550860277.193000000","description":"OS Error","file":"src/core/lib/iomgr/tcp_server_windows.cc","file_line":200,"os_error":"Only one usage of each socket address (protocol/network address/port) is normally permitted.\r\n","syscall":"bind","wsa_error":10048}]}]}
INFO:mlagents.envs:Start training by pressing the Play button in the Unity Editor.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "c:\users\mhr\documents\jobs\2019 - spring\ml-agents\ml-agents\mlagents\trainers\learn.py", line 114, in main
    run_training(0, run_seed, options, Queue())
  File "c:\users\mhr\documents\jobs\2019 - spring\ml-agents\ml-agents\mlagents\trainers\learn.py", line 46, in run_training
    docker_target_name, trainer_config_path, no_graphics)
  File "c:\users\mhr\documents\jobs\2019 - spring\ml-agents\ml-agents\mlagents\trainers\trainer_controller.py", line 117, in __init__
    no_graphics=no_graphics)
  File "c:\users\mhr\documents\jobs\2019 - spring\ml-agents\ml-agents\mlagents\envs\environment.py", line 67, in __init__
    aca_params = self.send_academy_parameters(rl_init_parameters_in)
  File "c:\users\mhr\documents\jobs\2019 - spring\ml-agents\ml-agents\mlagents\envs\environment.py", line 493, in send_academy_parameters
    return self.communicator.initialize(inputs).rl_initialization_output
  File "c:\users\mhr\documents\jobs\2019 - spring\ml-agents\ml-agents\mlagents\envs\rpc_communicator.py", line 79, in initialize
    "The Unity environment took too long to respond. Make sure that :\n"
mlagents.envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
         The environment does not need user interaction to launch
         The Academy and the External Brain(s) are attached to objects in the Scene
         The environment and the Python interface have compatible versions.
```

**Comment by vincentpierre** [comment]
Hi,
Is there an error in the Unity Environment ? You can check that by either training in the Editor or by checking `Development Build` when building the executable. If there is an error, it could be the reason why the Environment is unable to connect and it would result in a TimeOut. 
Also, did you check the Control checkbox in the Academy ?

**Comment by mhr** [comment]
Hi.

Thank you so much for your help!

I did check the Control checkbox in the Academy. Below are screenshots of the settings I thought may be relevant (Agent Brain and Academy Broadcast Hub Brains / Control).

![image](https://user-images.githubusercontent.com/1429247/53274147-37d97980-36c4-11e9-8755-b93f3d041195.png)
![image](https://user-images.githubusercontent.com/1429247/53274171-4d4ea380-36c4-11e9-9090-dce2bed4cf1f.png)

When I built the project using the Development Build option, I got the following errors: 
![image](https://user-images.githubusercontent.com/1429247/53275262-53468380-36c8-11e9-999e-6e8fa7abdd93.png).

**Comment by vincentpierre** [comment]
Hi, 
The error you are getting does not seem to be ML-Agents related at all. See [here](https://forum.unity.com/threads/unable-to-build-my-projects-in-2018-2-0b7-after-receiving-fatal-build-error.535810/).
Did you get the chance to try in editor training ?

**Comment by mhr** [comment]
Hi,

Despite not changing anything since last week, I was able to train in-editor without crashing. I don't know why, but there is no longer a time-out issue. I'm now having a separate issue where the model doesn't appear to be training (loss is not decreasing and cumulative reward is not increasing), so I might open a separate issue for that.

Thank you!

**Comment by mhr** [comment]
Never mind, it was just a hyperparameter issue.
