### ISSUE TITLE
What kind of instance type is suitable for learning on AWS

### ISSUE THREAD

**Issue by dora-gt** [Unity-Technologies/ml-agents#175]
Hi,

I'm interested in learning on AWS, reading the [document](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-on-Amazon-Web-Service.md), and I have a question.

What kind of instance type is suitable for learning on AWS?
GPU Instances? General ones?

Could you give me advice?

and...is it more efficient than iMac (3.2GHz i5 / 32GB)??

**Comment by awjuliani** [comment]
Hi @dora-gt,

An instance with a GPU would provide the biggest boost in performance over a computer without one. Generally speaking neural network training is speed up on GPU.

**Comment by dora-gt** [comment]
@awjuliani Thank you!

I'm wondering if my iMac does GPU acceleration or not...🤔
