### ISSUE TITLE
Training doesn't make any progress

### ISSUE THREAD

**Issue by RK4444** [Unity-Technologies/ml-agents#1752]
Hi guys

I have a little problem with training the 3DBalls example when I upgraded to MLAgents version 0.6.

I had some other problems but I thought I fixed them. Now when I start training this example, everything seems to start correct, however nothing happens. I can't see any summaries or progress. It looks like that
![issue_ml0 6_1](https://user-images.githubusercontent.com/37285455/53287443-7c285080-377c-11e9-8f14-aa9272cbb474.PNG)

After I trained an hour or so(I stopped it then, because I remembered that the training for this example shouldn't last so long) it looked the same. But when I stopped the training I got this warning:
![issue_ml0 6_2](https://user-images.githubusercontent.com/37285455/53287466-ce697180-377c-11e9-8e47-c39b79415ef4.PNG)

I still don't know, what I did wrong, maybe you could help me?

**Comment by RK4444** [comment]
I'm so sorry, I've found, what I did wrong

I overlooked a little but very important detail, please close this issue

**Comment by HyVong007** [comment]
I am having the same issue as you. I didnot find the solution yet. Please help me !

**Comment by RK4444** [comment]
Alright, my problem was, that i forgot to switch out the brains. When you open this project, every agent has a player brain. After I changed the player brain with the learning brain, everything worked just fine
