### ISSUE TITLE
Discrete Brain does nothing

### ISSUE THREAD

**Issue by FranticPotato** [Unity-Technologies/ml-agents#1753]
My intent is for the Agent to output the following for a simple 7-player turn-based proposal game (Agents make proposals for who get what resources, and only those that the majority vote Yes for happen, and the player with the most points at the end wins):

**Desired Output (8 outputs)**
Vote:
* Yes / No

Proposal:
* Player that this turn's resource 1 goes to 
* Player that this turn's resource 2 goes to
(...)
* Player that this turn's resource 7 goes to

However, while I can successfully hook up the python to Unity and all, the brains just do... nothing. Please let me know what I am doing wrong. I have set the brain (all seven) to Discrete and I get no errors.

```
public override void AgentAction(float[] vectorAction, string textAction)
    {
        //Energy Cost
        AddReward(-0.01f);

        //Proposing
        for (int i = 0; i < vectorAction.Length - 1; i++)
        {
            vectorAction[i] = Mathf.Clamp(vectorAction[i], 0f, 7f);
        }

        for (int y=0; y < 7; y++)
        {
            currentproposal[y] = (int)vectorAction[y];
        }

        vectorAction[7] = Mathf.Clamp(vectorAction[7], 0f, 1f);
        //voting
        if ((int)vectorAction[7] == 0)
            currentvote = 0;
        else
            currentvote = 1;
   
    }
```
I'd appreciate any help. Thank you in advance.

**Comment by mattinjersey** [comment]
I think using round would be better than using (int) to cast it because I looked it up and int is like floor.

**Comment by vincentpierre** [comment]
Hi @FranticPotato,
You say the problem is that the brains are doing nothing and I would like to try and figure out why. 
 * Could you put some debug statements in the AgentAction method ? This way we will know if the method is called at all. If the method is not called, it could be because the Agent does not have a Brain or that the agent or Academy are not initialized properly.
 * Could you print the values you get for the `vectorAction`? This way we will know if the brain always outputs the same "No action" value. This scenario seems unlikely because when connected to Python, the initial policy is random, so your agents should behave randomly. If that is not the case, it could be that the BrainParameters have been set incorrectly.

**Comment by FranticPotato** [comment]
@vincentpierre thank you! I appreciate the help.

I did as told, changing the code to this (just adding debug.logs):

```
 public override void AgentAction(float[] vectorAction, string textAction)
    {
        Debug.Log("Before vectoraction:" + vectorAction[0] + " - " + vectorAction[1] + " - " + vectorAction[2] + " - " + vectorAction[3] + " - " + vectorAction[4] + " - " + vectorAction[5] + " - " + vectorAction[6] + " - " + vectorAction[7]);

        Debug.Log("Choosing!");
        //Energy Cost
        AddReward(-0.01f);

        //Proposing
        for (int i = 0; i < vectorAction.Length - 1; i++)
        {
            vectorAction[i] = Mathf.Clamp(vectorAction[i], 0f, 7f);
        }

        for (int y=0; y < 7; y++)
        {
            currentproposal[y] = (int)vectorAction[y];
        }

        vectorAction[7] = Mathf.Clamp(vectorAction[7], 0f, 1f);
        
        //voting
        if ((int)vectorAction[7] == 0)
            currentvote = 0;
        else
            currentvote = 1;

        Debug.Log("After vectoraction:" + vectorAction[0] + " - " + vectorAction[1] + " - " + vectorAction[2] + " - " + vectorAction[3] + " - " + vectorAction[4] + " - " + vectorAction[5] + " - " + vectorAction[6] + " - " + vectorAction[7]);

    }
```

And the results I've gotten, is this:

```
Before vectoraction:0 - 0 - 0 - 0 - 0 - 0 - 0 - 0
Choosing!
After vectoraction:0 - 0 - 0 - 0 - 0 - 0 - 0 - 0

Before vectoraction:0 - 0 - 0 - 0 - 0 - 0 - 0 - 0
Choosing!
After vectoraction:0 - 0 - 0 - 0 - 0 - 0 - 0 - 0

(etc)
```

Every turn. It's never random, it's always set to zero. The default vote is a "1" (value it's initialized with), yet it changes it to a zero. The default proposal is {0,1,2,3,4,5,6}, yet it changes that to zero as well.

Maybe it's getting the inputs wrong? I don't know. Just in case, this is how that code looks:

```
    public override void CollectObservations()
    {
        
        AddVectorObs(myGameControl.VictoryAmount);
        AddVectorObs(myGameControl.CurrentPlayerTurn);
        AddVectorObs(ID);

        for (int i = 0; i < myGameControl.Players.Count; i++)
        {
            AddVectorObs(myGameControl.Players[i].GetComponent<PlayerAgent>().Score);
            AddVectorObs(myGameControl.CurrentProposal[i]);
        }

```
Maybe I should print what the Obs vector is? I don't know how to do that, but maybe the system is just blind?

The Brain Parameters look like this:

[https://i.imgur.com/oO6uheP.png](url)

Sorry for the troubles and thank you in advance for your help.

**Comment by vincentpierre** [comment]
In the Brain Parameters, Branch X size should be 2 because there are 2 options : 0 and 1

**Comment by FranticPotato** [comment]
@vincentpierre That worked! Thank you very much!
