### ISSUE TITLE
Brain will not get reset after scene switch

### ISSUE THREAD

**Issue by MeTheOo** [Unity-Technologies/ml-agents#1754]
I tested the sample scene, first time entering the scene the sample works fine.
But when I added logic to switch to another scene and come back to the sample scene, the agent stop moving. 
Further digging the logic, the Brain.cs _isInitialized won't get reset after scene switch.

**Comment by tkggwatson** [comment]
https://github.com/Unity-Technologies/ml-agents/pull/1758

**Comment by vincentpierre** [comment]
Feature was merged successfully.
