### ISSUE TITLE
Python API: Calling GameObject.FindTag inside AgentReset() keeps Jupyter Notebook Running

### ISSUE THREAD

**Issue by jkim447** [Unity-Technologies/ml-agents#1756]
I have a piece of code of the following inside AgentReset():
 
```csharp
target = GameObject.FindWithTag("Target")
```

FYI: target is not an agent, it's just an Unity primitive object.

If I leave this code out, everything runs fine whenever I call env.reset(). However, with this code included, env.reset() does not work and I cannot do anything (i.e. Jupyter Notebook is constantly running on that line). 

If I interrupt the kernel, it shows where it left off, which is line 255 in ml-agents/ml-agents/mlagents/envs/environment.py

Any reason as to why? Is it possible for some reason that it doesn't make sense to call "FindWithTag" at the start of the game, which I presume when AgentReset is first called?

**Comment by vincentpierre** [comment]
Hi, the Python code hanging like this is usually symptomatic of an error that happened in the Unity environment. You can look at the [logs](https://docs.unity3d.com/Manual/LogFiles.html) that are generated by the environment or look at the console when doing in editor training. This way you can isolate the Unity Error that is blocking the Environment.

**Comment by jo3w4rd** [comment]
FindWithTag() returns null if it doesn't find anything. Make sure that you check that target is a valid object before using it. Given that you are reseting the environment, it seems plausible that no target currently exists when the function happens to be called.

**Comment by jkim447** [comment]
@vincentpierre 
To clarify, I export the game first THEN interface with the game using Python API. I am not interfacing with the Unity editor at all. So I'm not sure if I can access the logs as you mentioned. 

As a follow-up, I tried interfacing directly with the editor using Python API with the following code: 
`env = UnityEnvironment(file_name=None)`
with NOTHING inside AgentReset(). When I call AgentReset() twice, it just hangs. This might be a separate issue, but I have a hunch that this is somehow a bug.

@jo3w4rd 
FindWithTag() is the only thing I'm calling inside AgentReset(), and I'm not doing anything with the returned variable as I understand it can return Null.  If I add a Debug.Log statement directly after FindWithTag(), it doesn't get executed. So something seems to get stuck when FindWithTag() is executed.

**Comment by jkim447** [comment]
I found that I had an Debug.Break() statement somewhere, which was making it stop. 
Issue resolved. Thank you.
