### ISSUE TITLE
How to know valid action range for an env?

### ISSUE THREAD

**Issue by chihoxtra** [Unity-Technologies/ml-agents#1757]
I am trying to write a PPO solution for Crawler. I wonder if there is any way I could check the accepted valid range of values for action for the Crawler env?

**Comment by BlueFisher** [comment]
I use `vector_action_descriptions` in brain parameters.

**Comment by chihoxtra** [comment]
thank you so much. the brain.vector_action_descriptions I am using returns the followings:

['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

Wonder if anyone happens to know the valid range of actions for the Crawler envs?

**Comment by vincentpierre** [comment]
Like @BlueFisher said, the BrainParameters contain the information you are looking for. `vector_action_space_size` can tell you the dimension of the action that is expected. In the case of continuous control (you can check this with `vector_action_space_type`) `vector_action_space_size` will be a single value corresponding to the number of continuous actions expected. The range of these actions is assumed to be [-1, 1]

**Comment by chihoxtra** [comment]
Thank you very much!
