### ISSUE TITLE
Unity Empty error message

### ISSUE THREAD

**Issue by LBerth** [Unity-Technologies/ml-agents#176]
Hi !
I'm new to Unity and I wanted to try the 3D Ball example, but each time I launch the editor i get this weird empty error message : 
![image](https://user-images.githubusercontent.com/19271957/33987622-6298d03a-e076-11e7-9fe0-3b797e195607.png)
I can't build the project or try the playmode.
I'm running Unity 2017.3.0f1 on Ubuntu 16.04 .
Any help would be great :)

**Comment by MarcoMeter** [comment]
Maybe try Unity version 2017.1.0, because this repository is based on that version.

**Comment by LBerth** [comment]
It worked, thank you ! :)
