### ISSUE TITLE
Memory overflow during training

### ISSUE THREAD

**Issue by Abluceli** [Unity-Technologies/ml-agents#1763]
When I was training, my environment took up more and more memory as the training time increased.

**Comment by vincentpierre** [comment]
Hi, Could you give us more information on the type of environment you are running and what platform you are training on ?

**Comment by Abluceli** [comment]
Hi, I need your help please! I am training my environment on unity. The version of my unity is  2018.2.19f1 and ML-agents is 0.6. When i train my brain , the memory unity environment used  going to increased and can not stop!
![image](https://user-images.githubusercontent.com/29014390/53457407-48e00d00-3a6d-11e9-9a5e-fc220b530228.png)
![image](https://user-images.githubusercontent.com/29014390/53457431-5ac1b000-3a6d-11e9-9f71-a9d291759306.png)
![image](https://user-images.githubusercontent.com/29014390/53457439-63b28180-3a6d-11e9-91e3-3610df103229.png)

**Comment by vincentpierre** [comment]
Hi, are you only seeing this memory increase when training or does this also happen when using a Player or Heuristic Brain ? Are you using visual observations. Does this also happen on any of our demo environments ?

**Comment by Abluceli** [comment]
This memory increase when i training my env. And i am not using visual. I have try your demo, and find that  it has not the memory problem. But i don't kown why, and i can find the problem of  my env. I am follow the doc of ml-agents.

**Comment by vincentpierre** [comment]
Does this problem persist with a Player Brain? Does it persist when you remove the Academy from the scene ? If This is the case it is probably an environment issue and not an ML-Agents issue. I would advise looking for lists or dictionaries that are never cleared. Using the deep profiler might help you figure out what is taking all of the memory.

**Comment by Abluceli** [comment]
Hi, I have try your method, and find that it is the problem of my env. There are lots of Objects not cleared on time. So thanks for your help, sir. Profiler is a really great tool in Unity!!!!  ^_^ ^_^
