### ISSUE TITLE
What happens when use --load and --curriculum at the same time

### ISSUE THREAD

**Issue by dora-gt** [Unity-Technologies/ml-agents#177]
Hi,

What happens when use `--load` and `--curriculum` at the same time?

Does it start from the last lesson? (I rather like it)

**Comment by dora-gt** [comment]
and...

please write some explanation about `--num-layers` .
I can imagine because I have read the code, but I want to know how it works exactly.

**Comment by awjuliani** [comment]
Hi @dora-gt.

You can use the curriculum along with the load function.

As for `num-layers`, here is the description in the documentation: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/best-practices-ppo.md#number-of-layers

**Comment by dora-gt** [comment]
@awjuliani Hi,

I want to know, whether "it starts from the last lesson or not".
It matters a lot I think...

Thank you for the description about `num-layers`!

**Comment by dora-gt** [comment]
@awjuliani I made a PR. Please check.

https://github.com/Unity-Technologies/ml-agents/pull/179
