### ISSUE TITLE
run more than one envs at the same time on mac

### ISSUE THREAD

**Issue by chihoxtra** [Unity-Technologies/ml-agents#1778]
I am a poor student. I have to keep my existing env (crawler) running/training while starting to develop an agent for another env (tennis). I could currently only work on my local machine because of budget constraint. I wonder if it is possible to run 2 envs at the same time in the same local machine (mac)?

**Comment by Sohojoe** [comment]
yes - you need to set a unique worker id for each instance using `worker-id=XX`

**Comment by chihoxtra** [comment]
Praise the Lord! Praise Unity! Thank you Joe!

**Comment by Sohojoe** [comment]
@eshvk  - i think you can close this now
