### ISSUE TITLE
Drastic performance drop using 0.7 and Barracuda

### ISSUE THREAD

**Issue by 13Flo** [Unity-Technologies/ml-agents#1780]
I was looking forward to finally be able to use IL2CPP to build my game prototype and increase performance, but I'm actually very disappointed because the new version drastically make it worst.

You'll find below a comparison of both builds profiling. Both builds are using the exact same code. The only difference is Mono versus  IL2CPP. I've trained a new .nn model in the exact same conditions. I used CPU inference when using Barracuda. 

![screenshot_2](https://user-images.githubusercontent.com/146405/53686380-1e938700-3cdb-11e9-8e42-7753af1d9314.jpg)

Any feedback would be welcome. But I guess I'm going to stick with TensorflowSharp for now :[

Edit: I should have mentioned that those profiling were done on Oculus Go (Android).

**Comment by 0lento** [comment]
Default 0.7 installation isn't utilizing Barracuda.Burst yet which might help on the performance figures (I haven't benchmarked it myself, just got it running myself the other day).

Currently Barracuda.Burst package is only at staging: https://bintray.com/unity/unity-staging/com.unity.barracuda.burst so there could be reasons why Unity didn't include it by default on 0.7.

How I did it myself was that I removed Barracuda.Core from the ML-Agents plugins and added that com.unity.barracuda.burst into my projects manifest along with staging registry configuration.

**Comment by 0lento** [comment]
Also worth noting that on your images you are comparing percentages, not the actual CPU time which would be "Time ms" few columns to the right. It doesn't really change the outcome this time (as TensorFlowSharps 22% out of 17ms is ~3.7ms when your Barracuda version took 9.8 ms) but still better compare to actual cpu time as that percentage alone doesn't tell much.

**Comment by 13Flo** [comment]
Thanks for your reply. I guess it's probably too early to build with Burst.
Does that mean 0.7 / IL2CPP / Barracuda is just not an option until Burst gets available?

I should have mentioned that those profiling were done on Oculus Go (Android).

**Comment by mantasp** [comment]
Hi @13Flo, I believe we already spoke on Unity Discord server. Could you please share your profiling data in raw "ms" spent on specific task, so we could easier establish baseline and check on side if we can reproduce it. Thanks!

**Comment by 13Flo** [comment]
@mantasp This is in the back of my mind since then but I unfortunately didn't have time to take care of it yet.

**Comment by eshvk** [comment]
Hi @13Flo, I am going to close this issue for now due to inactivity. Hopefully you were able to resolve your issue.  Please feel free to reopen if you still have issues.
