### ISSUE TITLE
[0.7] Cannot drag trained model into the LearningBrain's model property

### ISSUE THREAD

**Issue by MarcoMeter** [Unity-Technologies/ml-agents#1782]
Hi,
I updated to 0.7 from 0.6a on my Windows machine.
After training my environment, I imported the resulting nn-file.
After that I tried to add it to the model property of the LearningBrain, but that is forbidden, which is determined by the crossed circle icon.
Also, that file is not available if try to select it from list in order to assign it to the model property.

**Comment by ShaneCaler** [comment]
I'm also experiencing this. My understanding is that it has to do with Unity moving from Tensorflow to their Unity Inference Engine (though I could be wrong). But it seems that for whatever reason, importing ml-agents into my current project caused the model field to only accept text assets. However, it accepts .nn files when opening a new project directly from the UnitySDK folder (I've even tried dragging and dropping those folders into my current project and it still only accepts text assets). Both are on the same version of unity, using the same player settings.

**Comment by MarcoMeter** [comment]
I think reimporting all Assets solved this for me.
At least the field asks now for an (NN-Model) and not a (Text Asset).

**Comment by bjmolitor** [comment]
Oh! You guys helped me, being under pressure, out a great deal. As soon as I changed ENABLE_TENSORFLOW to ENABLE_BARRACUDA and hit the return button really hard, the reference requirement changed to NN-file and it worked like a charm.
