### ISSUE TITLE
Link to TensorflowSharp plugin is dead

### ISSUE THREAD

**Issue by mbaske** [Unity-Technologies/ml-agents#1783]
Getting 404 error at https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-TensorFlow-Sharp-in-Unity.md

**Comment by eshvk** [comment]
@mbaske That is because we are switching to our own native inference engine in new versions of ML-Agents. This is by intent.

**Comment by jgcbrouns** [comment]
What does this mean and what are the resulting effects of this? Does this mean that all Tensorflow support will not be possible anymore?

**Comment by eshvk** [comment]
This means that you can _train_ or write code that uses the TensorFlow API but when you deploy the model on a device, inference is done via our native inference engine.

**Comment by Cliwo** [comment]
If you don't mind, Can you replace those link with a information .md file something like 'We have a plan to bring a new our inference engine' ? 
I tried to find the plugin almost an hour and I finally found this issue.

**Comment by unityjeffrey** [comment]
thanks @Cliwo - I've added this and will be updated in the 0.8 release.

https://github.com/Unity-Technologies/ml-agents/pull/1893

**Comment by georgechen1** [comment]
What do you mean by inference being done using the built in inference?
Wouldn't we just train our models and then use them?

**Comment by Oceania2018** [comment]
@mbaske @eshvk @unityjeffrey TensorFlow.NET can **build** graph, **train** model and **inferring**. One library for all tensorflow related tasks. There are many [examples](https://github.com/SciSharp/TensorFlow.NET-Examples) you can take.
