### ISSUE TITLE
Action branching implementation

### ISSUE THREAD

**Issue by MarcoMeter** [Unity-Technologies/ml-agents#1785]
Hi,

I've got a question on your action branching implementation.

Is the loss function affected by the branching architecture or is the whole implementation simply done in the [create_dc_actor_critic()](https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents/mlagents/trainers/models.py#L333)?

**Comment by awjuliani** [comment]
@vincentpierre Wrote this piece of code, and can provide the most accurate answer.

**Comment by vincentpierre** [comment]
Hi @MarcoMeter 
The loss function is not affected since it only depends on the true return and the value estimate of the model (which does not take action as input)
You are right, the code lives in create_dc_actor_critic

**Comment by MarcoMeter** [comment]
Merci Beaucoup!
