### ISSUE TITLE
TensorFlowSharp Unity "'TensorflowSharp' does not exist in the current context"

### ISSUE THREAD

**Issue by SharawatChirag** [Unity-Technologies/ml-agents#1787]
I'm new to using TensorFlowSharp. I'm trying to work in Unity with Image Classification, but this is the error that keeps coming up. I did find a similar thread over here: https://github.com/migueldeicaza/TensorFlowSharp/issues/379
I have the exact same problem as the one in issue mentioned above.

But the solution doesn't work for me since I can't find an older version of TFSharp due to 'switching to native inference engine in new versions of ML-Agents' reason. Help will be really appreciated.

**Comment by eshvk** [comment]
Perhaps, you can try using an older version of ML-Agents that does use TensorFlowSharp?

**Comment by swegassus** [comment]
Hey i found the solution here:
[http://upschannel.eu/watch/Q6ERFwQNkzo/MACHINE+LEARNING+and+AUGMENTED+REALITY.html](url)
Instead of `#if UNITY_ANDROID` change it to `#if (UNITY_ANDROID  && !UNITY_EDITOR)`

**Comment by SharawatChirag** [comment]
Hey, thanks a lot! This worked.
