### ISSUE TITLE
Model is only created for one training run

### ISSUE THREAD

**Issue by MarcoMeter** [Unity-Technologies/ml-agents#1799]
Hi,

if I use more than one run (e.g. --num-runs=10 --run-id=run), I expect each run to output a model.
However, only one model is saved throughout all sessions.

With the given run-id, I'd expect 10 sub-directories in the models directory named like this:
- run-0-Brain
- run-1-Brain
- ...
- run-9-Brain

It works as expected for the summaries.

I observed this behavior for v0.7.0 on Windows and Ubuntu 16.04.

**Comment by Amanpradhan** [comment]
Can you please redirect me to a tutorial describing how to use unity inference engine? I am new to unity and I don't know where to start to integrate my deep learning model in unity.

**Comment by MarcoMeter** [comment]
In learn.py:52 I changed
`model_path = './models/{run_id}'.format(run_id=run_id)`
to
`model_path = './models/{run_id}'.format(run_id=run_id) + '-' + str(sub_id)`
to fix this issue.

**Comment by xiaomaogy** [comment]
Hi @MarcoMeter , thanks for raising this, I've logged this bug.

**Comment by xiaomaogy** [comment]
Since we've deprecated --num-runs option, this bug no longer exist, so I'm going to close it for now. Feel free to reopen if you find more issues with it.
