### ISSUE TITLE
Windows and Python API

### ISSUE THREAD

**Issue by wjoyce62** [Unity-Technologies/ml-agents#18]
Hi,

Will you be adding Python install dependencies for Windows (10).

Thanks

**Comment by romerocesar** [comment]
The python dependencies are in the [requirements.txt](https://github.com/Unity-Technologies/ml-agents/blob/master/python/requirements.txt) file, so I'm not sure exactly what you mean. Some users installed the dependencies using pip, others have used [anaconda](https://www.anaconda.com/download/). Is there a step you're having trouble with?

**Comment by AlVoReinDeer** [comment]
Stuck at this stage. tell me please what is the problem.
https://image.ibb.co/gW3FJk/image.png
