### ISSUE TITLE
how to train a custom object detector?

### ISSUE THREAD

**Issue by Amanpradhan** [Unity-Technologies/ml-agents#1800]
I want to train and deploy a custom object detector using Unity Inference Engine. How do I go about the process?

**Comment by mantasp** [comment]
Typically you would train object detector in TensorFlow and then convert model using 'mlagents/trainers/tensorflow_to_barracuda.py' to Unity Inference Engine format. Later you can invoke Unity Inference Engine as provided in examples in 'UnitySDK/Assets/ML-Agents/Plugins/Barracuda.Core/Barracuda.md'
