### ISSUE TITLE
Is there anyway I can connect the mlagent to a unity-3D game in javascript?

### ISSUE THREAD

**Issue by lxqlxq21** [Unity-Technologies/ml-agents#1802]

**Comment by mattinjersey** [comment]
Just my $0.02 this may be tricky especially because javascript running in browser has security limitations. for example, you cannot dump UDP data from javascript.

**Comment by lxqlxq21** [comment]
I’m not sure what’s the difference between JavaScript and C# in unity-3D. We have a few games written in JavaScript and C# mixed. It seems they can be compiled together without problem in unity-3D. But there is definitely very strick rules to follow as which folder to put the scripts. I’m assuming there must be a workaround so I don’t need to rewrite all my JavaScript games in C# to use mlagent.

**Comment by mattinjersey** [comment]
Ah I see your point. Seems like it should be possible. Especially if you can write the mixed game, because then the only necessary thing is to pass the observations and rewards and actions between javascript and c#.

**Comment by lxqlxq21** [comment]
It would be most helpful if an example is provided to use mlagaent with JavaScript game, since a lot of the games were written in JavaScript in old days. It’s not very realistic to rewrite all of them in C# to use mlagent.

**Comment by xiaomaogy** [comment]
I don't think we will be working on this in the near future. You are welcome to try to make this work yourself if you are interested.

**Comment by awjuliani** [comment]
Hi all. I am closing this issue as it is something we don't expect to be adding anytime in the near future, as Unity is moving to be 100% C# based.
