### ISSUE TITLE
Is it possible to change an agent's script and resume training again ?

### ISSUE THREAD

**Issue by moonsh** [Unity-Technologies/ml-agents#1815]
Hi, Here is my question.

I trained the Rollerball example and I wanted to add some code in the agent's script.

For example, changing reward values or relocation of the agent's position whenever it called reset. 

However, after changed these values, I couldn't resume my training.

So my question is that is there a way to resume training again?

Because I don't want to spend time training from the beginning again.

**Comment by mattinjersey** [comment]
I think the --load parameter works...as long as you don't change the fundamental structure of the network.

**Comment by moonsh** [comment]
@mattinjersey So if I change some part of the environment, should I start training again always?

**Comment by mattinjersey** [comment]
In my understanding...
Lets assume you make changes to the environment. 
But these changes do not affect the neural network structure. 
Then you can use the --load parameter to continue (resume) training.  Do not need to restart training.

**Comment by moonsh** [comment]
@mattinjersey  Ah yes. I see.  I wonder can we start with training a simple environment and add more things like curriculum training.  I think I can't touch the observation and action functions but it is fine with other things, right?

**Comment by mattinjersey** [comment]
this seems correct to me, although I have not tried the curriculum training.

**Comment by ervteng** [comment]
@mattinjersey is correct, you can use --load as long as none of the network structure changes. This means the observations, actions, whether or not you have memory, etc. need to stay the same.

**Comment by moonsh** [comment]
Thank you for all the comments. I will close this issue.
