### ISSUE TITLE
Memory leak in Inference mode

### ISSUE THREAD

**Issue by caioc2** [Unity-Technologies/ml-agents#1817]
Running agents while in inference mode (Academy control unchecked) leads to memory leak.

I have created a test scene which collect statistcs of my agent and in a hour it run out of memory.
I also tested it with the provided example scene 3DBall, it presents the same behavior.
While training this behavior does not happen.

System:
Windows 10 Starter build 17134
i7 7700 HQ, GTX 1060, 16GB RAM
Unity 2018.1.9f2
edit: ml-agents **0.6**

How to reproduce:
Load the 3DBall scene, plug a trained model to its brain, in the academy parameters set the inference time scale to 100 and let it run for a long period.

**Comment by ervteng** [comment]
@caioc2 If I understand correctly - you're taking a trained .bytes/.nn file and putting into your Learning Brain, correct? Did the memory leak happen in training?

@vincentpierre have you seen an issue like this with Barracuda?

**Comment by caioc2** [comment]
> you're taking a trained .bytes/.nn file and putting into your Learning Brain, correct?

Yes, I take the .bytes/.nn setup the learning brain and let it run.

> Did the memory leak happen in training?

No, while training it does not happen. I left it training for days without problem.

I have tested both with my own agent and with the provided 3DBall example, both have the same leaky behavior. So I believe it may be a general problem with the ml-agents or my system.

**Comment by ervteng** [comment]
Hey @caioc2, I've been unable to reproduce your memory leak in inference, at least with 0.7. From prior experience we've run inference for hours on a mobile phone, and it did not crash. Are there any other changes to the 3DBall scene or the other scripts that you made?

**Comment by caioc2** [comment]
No change to the 3DBall scene, I'm going to create another environment to try to reproduce it, if it does not happen atleast I know it maybe something specific with that machine/env.
 Any news I'll keep this issue updated.

Thanks.

**Comment by caioc2** [comment]
Hi, sorry for late reply.

I have re-tested everything:
The version 0.7 works perfectly, no leak.
In the other hand the 0.6 presents the leak, but since the 0.6 is replaced by the 0.7 it may not worth to fix it in the 0.6.

**Comment by ervteng** [comment]
Great that it works in 0.7! 0.7 is much better for inference anyways, please use that going forward. If you're still having issues, feel free to open again. Thanks!
