### ISSUE TITLE
how fast is it to use gpu compare to use cpu instead?

### ISSUE THREAD

**Issue by tanakataiki** [Unity-Technologies/ml-agents#1820]
mlagents v7 has gpu option in  Learninig Brain but in previous version gpu is useless and not reccomended to speed up. 
but to search into inference device in LeaningBrain.cs eather compute fast or CS sharpfast is selected .
So I assume if CPU mode Script excution time is shorten while GPU mode enhance backpropagate time.
Am I right about it?

Thanks

**Comment by ervteng** [comment]
Hi @tanakataiki, two different things. In previous versions, inference _only_ supported CPU. In 0.7, inference supports both CPU and GPU. Typically, for small networks, CPU is OK and not worth the overhead of sending the data into GPU memory and taking it out again. The mode in the script _only affects inference._

For training, (e.g. for backpropagation), the version of ML-Agents is irrelevant, as it is entirely done in Tensorflow. You can use either Tensorflow or Tensorflow-GPU with ML-Agents; both will work.

**Comment by tanakataiki** [comment]
@ervteng 
Does inference mean the out put of net work and net work is also constructed in C#?
I am wondering what gpu helps so far.
As for the back propagation does gpu helps for training large net work such as 1024 or 512 of two or more layer?
Thanks

**Comment by MarcoMeter** [comment]
Inference means that you are not training your model any further. Instead you use it for production (i.e. producing actions in real-time).

GPU training needs lots of data. As PPO generates data on the fly, the overhead, caused by the interface between CPU and GPU, slows done the training process.

**Comment by tanakataiki** [comment]
Thanks @MarcoMeter 
I closed this issue
