### ISSUE TITLE
RayPerception - Question

### ISSUE THREAD

**Issue by moonsh** [Unity-Technologies/ml-agents#1830]
Hi, Here is my question.

If I don't define a tag name in detectable objects, I think an agent doesn't receive any information from this object.

However, it didn't work as my expectation. The agent moves to touch this object even though the object is not on the detectable object list.

I can't understand this.

In my example, two agents have each target position so they should go to their own target but they just go to any nearest target.

Thank you,

**Comment by Usmaniatech** [comment]
And my issue is, my agent dont move towards target even I have add the target tag.

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using MLAgents;

public class RayPerceptionPlane : Agent
{

public float speed = 70.0f;

Rigidbody m_Rigidbody;

RayPerception rayPer;

public GameObject Target;
public GameObject Obstac;
public GameObject Obstac2;

public bool useVectorObs;



void Start()
{
    Debug.Log("Plane Perception script added" + gameObject.name);
    m_Rigidbody = GetComponent<Rigidbody>();
    rayPer = GetComponent<RayPerception>();
}

public override void AgentReset()
{


    if (this.transform.position.x < 0)
    {
        // If the Agent fell, zero its momentum
        this.m_Rigidbody.angularVelocity = Vector3.zero;
        this.m_Rigidbody.velocity = Vector3.zero;
        this.transform.position = new Vector3(502.38f, 11.11f, 504.48f);
    }
    if (this.transform.position.x > 650)
    {
        // If the Agent fell, zero its momentum
        this.m_Rigidbody.angularVelocity = Vector3.zero;
        this.m_Rigidbody.velocity = Vector3.zero;
        this.transform.position = new Vector3(Random.value * 10 - 4,
                                  10.1f,
                                  Random.value * 10 - 4);
    }

    this.transform.position = new Vector3(Random.value * 15 - 4,
                                  10.1f,
                                  Random.value * 10 - 4);

}


public override void CollectObservations()
{
    if (useVectorObs)
    {
        var rayDistance = 35f;
        float[] rayAngles = { 20f, 90f, 160f, 45f, 135f, 70f, 110f };
        var detectableObjects = new[] { "Target", "Obstac", "Obstac2" };
        AddVectorObs(rayPer.Perceive(rayDistance, rayAngles, detectableObjects, 0.5f, 0f));

    }


    
}

public override void AgentAction(float[] vectorAction, string textAction)
{

    // Actions, size = 2
    Vector3 controlSignal = Vector3.zero;
    controlSignal.x = vectorAction[0];
    controlSignal.z = vectorAction[1];
    controlSignal.y = vectorAction[2];

    m_Rigidbody.AddForce(controlSignal * 100);

    
    transform.Rotate(Input.GetAxis("Vertical"), 0.0f, -Input.GetAxis("Horizontal"));
    
    float distanceToTarget = Vector3.Distance(this.transform.position,
                                              Target.transform.position);

    

    if (distanceToTarget < 2.42f)
    {
        AddVectorObs(this.transform.position);
        SetReward(1.0f);
        Done();
    }
    

}

void OnCollisionEnter(Collision col)
{
    
    if (col.gameObject.name == "Obstac")
    {
        SetReward(-0.5f);

    }

    if (col.gameObject.name == "Obstac2")
    {
        SetReward(-0.5f);

    }
}
}

**Comment by moonsh** [comment]
@Usmaniatech Have you tried Hallway example?
If the example doesn't work then it might be not your script problem.
