### ISSUE TITLE
demonstration recorder has wrong actions?

### ISSUE THREAD

**Issue by erikfrey** [Unity-Technologies/ml-agents#1833]
Hi all - in Agent.cs, in the `SendInfoToBrain()` function you write out a demonstration recorder experience:

```
   brain.SendState(this, info);

   if (recorder != null && recorder.record && Application.isEditor)
   {
      recorder.WriteExperience(info);
   }
```

But you are still in the Academy `AgentSendState` and have not yet called the `DecideAction` methods on any brains.  I think this means you are recording actions from the previous step, but attributing them to the current step's observations.

Solution would be to move the call to `recorder.WriteExperience` to some point after decision has been made.  Is that right?  What am I missing?

**Comment by erikfrey** [comment]
Oh, you know what, I answered my own question!  I just found this code in `demo_loader.py`:

```
def make_demo_buffer(brain_infos, brain_params, sequence_length):
...
   demo_buffer[0]['visual_obs%d' % i] \
                .append(current_brain_info.visual_observations[i][0])
...
  demo_buffer[0]['actions'].append(next_brain_info.previous_vector_actions[0])
```

So you are grabbing the next info's actions and adding them to the current info's observations.  OK.  Please take this as a request to simplify this in a future version of mlagents, brain infos have the current observation and action together - this is confusing for a developer otherwise!

Besides that, feel free to close this issue.  Thanks.

**Comment by ervteng** [comment]
Hi @erikfrey, thanks for the feedback! I agree with you, the order of actions, rewards, and states can get very confusing. Hopefully we can clear this up in future releases.
