### ISSUE TITLE
Training agent at runtime

### ISSUE THREAD

**Issue by RocKIn0X** [Unity-Technologies/ml-agents#1834]
I have an idea to train agent at runtime like black and white game. 

In that game, the player can train an agent to help him. If it does the right thing, he can give a positive reward. But if it does the wrong thing, the player can punish it (give negative reward).
So Is it possible unity-ml can help me in this case?

Thank you!

**Comment by ervteng** [comment]
Hi @RocKIn0X, in principle this should be possible but it will require some work. What you can do is use On Demand Decisions (https://github.com/Unity-Technologies/ml-agents/docs/Learning-Environment-Design-Agents.md), and in your game code, only call SetReward and RequestDecision after the player takes an action. 

Alternatively, you could set reward = 0 for most of the time, and set it to 1 or -1 depending on the player's action. But the agent may have trouble learning on such a sparse signal. You'll have to play around with the reward structure to get it to work.

**Comment by RocKIn0X** [comment]
Thank you for your suggestion @ervteng :)

I will try it first.

**Comment by RocKIn0X** [comment]
I stuck something. 

I realized I didn't want to train the agent to get the model and put it into the agent before building the game,  but the agent should be trained in the real game.

At first of this game, I want the agent to knows nothing. The player should train it to become a useful agent. So I'm curious if I build a game, can I train the agent in the real game?

Thank you.

**Comment by xiaomaogy** [comment]
Hi @RocKIn0X , no you can't play the game as you do the training. we currently don't support that because 1) It is technically difficult to put the trainable model on all of the devices (what we embed into the game build for inference is a freezed model) 2) It will require a lot of data to actually make the model work, just playing won't provide as much data as needed.

**Comment by RocKIn0X** [comment]
Ok, thank you, everybody. I'll find another way.
