### ISSUE TITLE
[Question] Batch, Buffer, Epoch, Time Horizon ?

### ISSUE THREAD

**Issue by moonsh** [Unity-Technologies/ml-agents#1837]
Hi, I am struggling to understand these parameters (Batch, Buffer, Epoch, Time Horizon).

These values seem to be correlated with each other.

I know this website explaining these parameters ( https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-PPO.md).

However, I am still confused.

From my understanding, the model is updated at every epoch. 
Batch size is the number of experience used for one iteration.

Buffer size seems to store batch to update the model. 
Also, the time horizon parameter is how many steps to collect before adding it to buffer size.

Then, how we define how many iterations we will use for one epoch?
and what is the difference between buffer size and time horizon?

Thank you,

**Comment by ervteng** [comment]
Hi @moonsh, we update the model every time we get `buffer_size` number of timesteps. During this update, we divide the buffer into `batch_size` sized batches, and perform model updating on each of these batches one at a time. This process is repeated `num_epoch`s number of times. 

Independently of that, `time_horizon` refers to how long before a sequence of states, actions, and rewards are added to the buffer. Usually it should be less than the buffer size, so that data is added to the buffer multiple times before it is full.

**Comment by moonsh** [comment]
@ervteng Thank you for the reply.

If there is max 10000 steps and I set buffer size 1024 and batch size as 128. 

This means one epoch will be processed after 1024 steps, right?

If I set epoch number just three, what will happen after three epochs (= after 3072 steps)?

It seems like after three epochs there is no updating for a model.

If I want to increase the max step for training then should I increase epoch size as well or should I restart training?

Thank you,

**Comment by ervteng** [comment]
Hi @moonsh, If you set epoch number to three, it will iterate over the 1024 steps in your buffer 3 times. It won't want until 3072 steps. 

Epoch size won't affect the max step for training. You shouldn't have to restart training to change most of these parameters.

**Comment by moonsh** [comment]
@ervteng I am sorry. I can't get it. So every update will occur 3 times when the model reaches every 1024 steps? like 1024, 2048, 3072, 4096... ?

**Comment by TashaSkyUp** [comment]
A very very detailed explanation of all of these parameters would definitely help this project.

**Comment by xiaomaogy** [comment]
Hi @moonsh, epoch just means how many times you update the model with your data in the buffer with. In your example, once you fill your buffer with 1024 steps of data, if you have epoch as 3, you update your model for 3 times (or 3 times back propagation of the weights of your model) with this 1024 steps of data.
