### ISSUE TITLE
Embedding model in Learner Brain

### ISSUE THREAD

**Issue by Plrac** [Unity-Technologies/ml-agents#1838]
Hi, I have tried dragging the .nn file that was created after training to the model placeholder in the learning brain but I can't seem to drag the file even tho the .nn file is already in the assets nor can I even search for it.
![PinguProblem](https://user-images.githubusercontent.com/48695992/54562345-bcb36c80-49be-11e9-84eb-930c6143ca8d.JPG)
![PinguProblem2](https://user-images.githubusercontent.com/48695992/54562347-bcb36c80-49be-11e9-81f9-a5f590d0acec.JPG)

**Comment by ervteng** [comment]
Hi @Plrac, what happens when you drag the model into the box? Does it throw an error in the bottom lefthand corner of the editor?

**Comment by MarcoMeter** [comment]
Duplicate #1782

**Comment by Plrac** [comment]
Wasn't searching hard enough but the solution worked in #1782 thanks!
