### ISSUE TITLE
Headless mode not an option 

### ISSUE THREAD

**Issue by bonniesjli** [Unity-Technologies/ml-agents#1842]
Hello, 

Headless mode doesn't appear to be an option when I try to build an executable environment. It would show me something like this:
![image](https://user-images.githubusercontent.com/33984611/54584761-91e10c80-49ee-11e9-9c49-3a8cf180e902.png)
which is similar to what's shown on the doc as well (https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Executable.md). What do I do to enable headless mode? 

Help appreciated!

**Comment by MarcoMeter** [comment]
Which Unity version are you using?

**Comment by bonniesjli** [comment]
@MarcoMeter I'm using 2018.3.0f2 and 2018.3.8f1, both don't seem to have headless mode. 
I wonder if it's something during installation (it seemed quite straight forward tho) or some configuration that needs to be done.

**Comment by MarcoMeter** [comment]
During installation you can add the Linux Build Package.
However, if it wasn't installed, Linux would not show up in the Target Platform field.

Could you try Unity version 2018.2.20f?

**Comment by awjuliani** [comment]
Hi @bonniesjli 

"Headless mode" was removed in 2018.3. It is still available for earlier versions. In 2019.2 or 2019.3 we will be introducing native headless rendering on Linux, which will replace the previous option.

**Comment by MikeWise2718** [comment]
I am now using "mlagentprogram -nographics -batchmode" to run things on a non-GPU DSVM on Azure.

**Comment by ugurkanates** [comment]
Any update on this?
@awjuliani

**Comment by MarcoMeter** [comment]
Hi @awjuliani 
I hope that we will be able to omit X in the future, because the clusters that I'm working with do not want to provide X support.

Did you guys take EGL into account and have made any experiences with that as an X alternative?

**Comment by awjuliani** [comment]
Hi @MarcoMeter 

I know it is somewhat disappointing. We were hoping to have an alternative by this time, but things move somewhat slowly when they are part of the Unity Engine itself, rather than a package like ML-Agents. I'll follow back and see how possible it is for us to get an experimental build of Obstacle Tower out with some form of GPU acceleration without the need for X.

**Comment by MarcoMeter** [comment]
That would be amazing @awjuliani .
And what about EGL?
