### ISSUE TITLE
AgentAction

### ISSUE THREAD

**Issue by SHornoiu** [Unity-Technologies/ml-agents#1844]
Hello,

I developed a model using ml-agents.

When I use the model inside Unity the values for actions are:
OUT: -0.04273732 for a 
vector_observation:0.5734265, 0.36625, 0.63375, 0.0979021, 0, 0.9766667

If I use the model in a python program, for the same vector_observation I obtain:
PY: 6.8379264

Could somebody to explain why?

Thank you!

**Comment by mantasp** [comment]
Hi, I believe most of the models made with ML-Agents v0.7 also take "epsilon" as an input. Are you passing the same value of "epsilon" in both environments?

**Comment by SHornoiu** [comment]
Yes, “vector_observation” and “epsilon” are the same when are transferred to Unity or python environment.

**Comment by SHornoiu** [comment]
The output considered in python is: “action”. It’s this correct?

**Comment by mantasp** [comment]
Yes, "action" should be the output. Any chance you could share your model for testing?
Thanks

**Comment by SHornoiu** [comment]
[frozen_graph_def.pb.zip](https://github.com/Unity-Technologies/ml-agents/files/3013242/frozen_graph_def.pb.zip)
[iSiloBrain-V01.nn.zip](https://github.com/Unity-Technologies/ml-agents/files/3013243/iSiloBrain-V01.nn.zip)

**Comment by SHornoiu** [comment]
I attached both models (.nn used in UNITY and .pb used with a python program in order to use in a Docker).

Using “vector_observation” and “epsilon” when I obtain the "action" value is different in Unity with the one in Python

Thank you
Sorin

**Comment by mantasp** [comment]
what "epsilon" value are you using for testing?

**Comment by SHornoiu** [comment]
During the training I used epsilon=0.2

Please find below the python used to test and compare the values obtained outside Unity. Only when I used epsilon=20. I received "action" close to the one in Unity 

[load_model_and_predict.py.zip](https://github.com/Unity-Technologies/ml-agents/files/3018378/load_model_and_predict.py.zip)

**Comment by mantasp** [comment]
unfortunately I can't reproduce your issue, on my machine output of your script matches my test with Barracuda.
**Python TF output:**
value_estimate:  [[-6.743287]]
action_probs: [[0.18574142]]
--------> Action: [[-1.]]
**Barracuda CSharpFast output:**
value_estimate -6.743277 
action_probs 0.1857414 
action: -1 
**My C# test code:**
```
model = ModelLoader.Load(srcModel.bytes);
        worker = BarracudaWorkerFactory.CreateWorker(BarracudaWorkerFactory.Type.CSharpFast, model, false);
        
        var input_vector_obs = new Tensor(1,1,1,6, new float[] {0.5734265f, 0.36625f, 0.63375f, 0.0979021f, 0f, 0.9766667f});
        var input_eps = new Tensor(1,1,1,1, new float[] {0.2f});
        
        var dict = new Dictionary<string, Tensor>();
        dict["vector_observation"] = input_vector_obs;
        dict["epsilon"] = input_eps;
        
        worker.Execute(dict);
        
        worker.Fetch("value_estimate").PrintDataPart(24, "value_estimate");
        worker.Fetch("action_probs").PrintDataPart(24, "action_probs");
        worker.Fetch("action").PrintDataPart(24, "action:");
```

**Comment by SHornoiu** [comment]
As mentioned, if the MODEL is through c# (Barracuda) (.nn) the results are OK.
If I use the MODEL (.pb) through python (as in my example, the results are different.
Should not be identical the two models? .nn and .pb? There is something wrong in my python code?
Thanks

**Comment by mantasp** [comment]
I mean I get the **same values on Python** with script you provided

**Comment by SHornoiu** [comment]
sorry ... I just realised that you referred to python ...
In the case I don't understand why on my computer I have different values :(((
I will tray to test on other computer ...
Thank you
