### ISSUE TITLE
isInference flag

### ISSUE THREAD

**Issue by F-Brar** [Unity-Technologies/ml-agents#1847]
Hi,
I am just quickly reporting this.
The isInference flag is always true in my current project. (Where it should be false in training mode right?)
I did not try to reproduce this in a fresh project yet.

I am on mlagents v7.0 and Unity2018.3.7f1

**Comment by awjuliani** [comment]
Hi @F-Brar 

Can you confirm that the speed of the simulation does not change between running from the Python api and running from the editor directly?

**Comment by F-Brar** [comment]
Hi @awjuliani 
I'm not sure if I get your question right. The project is definitely running as expected and the academy is in training configuration, when it should be. (same goes for inference mode)
I just realized this when i tried to check for training/inference mode from my agent.
Right now i worked around it, so it's not a big issue for me.
Thank you!

**Comment by eshvk** [comment]
I am closing this issue assuming you got your issue resolved. Please feel free to re-open if you have issues.
