### ISSUE TITLE
TF 2.0 support?

### ISSUE THREAD

**Issue by SetoKaiba** [Unity-Technologies/ml-agents#1850]
TensorFlow 2.0 is released. It would be great to support it. There're many improvements.

**EDITED:**
https://github.com/SetoKaiba/ml-agents/tree/tf2
I make a tf2 branch for it.
The training is tested working with 3DBall.
And the generated nn file is working with Barracuda as well.

https://github.com/SetoKaiba/ml-agents/tree/tf2-develop
And also, the develop branch splits ml-agents into two packages.
I made a tf2-develop branch for it.
The training is tested working with 3DBall.
And the generated nn file is working with Barracuda as well.

**Comment by awjuliani** [comment]
Hi @SetoKaiba 

TensorFlow 2.0 is still in alpha, and therefore not supported at this time. That being said, it looks like the error you are getting is related to the buffer, rather than tensorflow directly. It may be that this new version is outputting things in a different shape than in 1.0. 

Could you also share your numpy and python versions?

**Comment by SetoKaiba** [comment]
Hi @awjuliani 

Yes. I know that. So I just tried to migrate to tf2 myself. But I encounter this problem.
I tried to print out the buffer and get this output. It seems that the dimension of advantages is incorrect. But the problem doesn't occur in the previous 9000 steps. It's strange.
The output is the last two iteration including the problem case.
Previous iteration is correct (45,), But it's incorrect int that iteration (1,12018)

> key:vector_obs,value:(45, 8)
> key:next_vector_in,value:(45, 8)
> key:actions_pre,value:(45, 2)
> key:random_normal_epsilon,value:(45, 2)
> key:actions,value:(45, 2)
> key:prev_action,value:(45, 2)
> key:masks,value:(45,)
> key:rewards,value:(45,)
> key:action_probs,value:(45, 2)
> key:value_estimates,value:(45,)
> key:advantages,value:(45,)
> key:discounted_returns,value:(45,)
> key:actions,value:(12018, 2)
> key:vector_obs,value:(12018, 8)
> key:next_vector_in,value:(12018, 8)
> key:actions_pre,value:(12018, 2)
> key:random_normal_epsilon,value:(12018, 2)
> key:prev_action,value:(12018, 2)
> key:masks,value:(12018,)
> key:rewards,value:(12018,)
> key:action_probs,value:(12018, 2)
> key:value_estimates,value:(12018,)
> key:advantages,value:(1, 12018)
> previous:12018,current:1
> Traceback (most recent call last):
>   File "C:\Users\Seto\Anaconda3\envs\ml-agents-2\Scripts\mlagents-learn-script.py", line 11, in <module>
>     load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
>   File "e:\seto\github\unity-technologies\ml-agents\ml-agents\mlagents\trainers\learn.py", line 234, in main
>     run_training(0, run_seed, options, Queue())
>   File "e:\seto\github\unity-technologies\ml-agents\ml-agents\mlagents\trainers\learn.py", line 88, in run_training
>     tc.start_learning(env, trainer_config)
>   File "e:\seto\github\unity-technologies\ml-agents\ml-agents\mlagents\trainers\trainer_controller.py", line 210, in start_learning
>     new_info = self.take_step(env, curr_info)
>   File "e:\seto\github\unity-technologies\ml-agents\ml-agents\mlagents\trainers\trainer_controller.py", line 281, in take_step
>     trainer.update_policy()
>   File "e:\seto\github\unity-technologies\ml-agents\ml-agents\mlagents\trainers\ppo\trainer.py", line 338, in update_policy
>     self.training_buffer.update_buffer.shuffle()
>   File "e:\seto\github\unity-technologies\ml-agents\ml-agents\mlagents\trainers\buffer.py", line 185, in shuffle
>     raise BufferException("Unable to shuffle if the fields are not of same length")
> mlagents.trainers.buffer.BufferException: Unable to shuffle if the fields are not of same length

**Comment by SetoKaiba** [comment]
The version of numpy is 1.16.2. The version specified for tf 1.7 is not compatible with tf 2. So I updated to the latest. The version of python is 3.6.

**Comment by SetoKaiba** [comment]
I found that the mean & std is with problem of dimension.

> (ml-agents-2) E:\Seto\GitHub\Unity-Technologies\ml-agents>mlagents-learn config\trainer_config.yaml --train
> 
> 
>                         ▄▄▄▓▓▓▓
>                    ╓▓▓▓▓▓▓█▓▓▓▓▓
>               ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
>             ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
>           ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
>         ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
>         ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
>           ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
>             '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
>                ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
>                    `▀█▓▓▓▓▓▓▓▓▓▌
>                         ¬`▀▀▀█▓
> 
> 
> WARNING: Logging before flag parsing goes to stderr.
> I0321 17:28:46.626744 29836 learn.py:220] {'--curriculum': 'None',
>  '--docker-target-name': 'None',
>  '--env': 'None',
>  '--help': False,
>  '--keep-checkpoints': '5',
>  '--lesson': '0',
>  '--load': False,
>  '--no-graphics': False,
>  '--num-runs': '1',
>  '--run-id': 'ppo',
>  '--save-freq': '50000',
>  '--seed': '-1',
>  '--slow': False,
>  '--train': True,
>  '--worker-id': '0',
>  '<trainer-config-path>': 'config\\trainer_config.yaml'}
> e:\seto\github\unity-technologies\ml-agents\ml-agents\mlagents\trainers\learn.py:134: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
>   trainer_config = yaml.load(data_file)
> I0321 17:28:46.692147 29836 environment.py:60] Start training by pressing the Play button in the Unity Editor.
> I0321 17:29:08.274095 29836 environment.py:93]
> 'Ball3DAcademy' started successfully!
> Unity Academy name: Ball3DAcademy
>         Number of Brains: 1
>         Number of Training Brains : 1
>         Reset Parameters :
> 
> Unity brain name: 3DBallLearning
>         Number of Visual Observations (per agent): 0
>         Vector Observation space size (per agent): 8
>         Number of stacked Vector Observation: 1
>         Vector Action space type: continuous
>         Vector Action space size (per agent): [2]
>         Vector Action descriptions: ,
> 2019-03-21 17:29:08.286833: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
> W0321 17:29:08.333994 29836 deprecation.py:323] From e:\seto\github\unity-technologies\ml-agents\ml-agents\mlagents\trainers\models.py:128: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.dense instead.
> W0321 17:29:08.411369 29836 deprecation.py:506] From C:\Users\Seto\Anaconda3\envs\ml-agents-2\lib\site-packages\tensorflow\python\ops\init_ops.py:1257: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
> Instructions for updating:
> Call initializer instance with the dtype argument instead of passing it to the constructor
> W0321 17:29:08.523690 29836 deprecation.py:323] From C:\Users\Seto\Anaconda3\envs\ml-agents-2\lib\site-packages\tensorflow\python\keras\optimizer_v2\learning_rate_schedule.py:417: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Deprecated in favor of operator or tf.math.divide.
> W0321 17:29:09.033878 29836 deprecation.py:506] From C:\Users\Seto\Anaconda3\envs\ml-agents-2\lib\site-packages\tensorflow\python\training\slot_creator.py:187: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
> Instructions for updating:
> Call initializer instance with the dtype argument instead of passing it to the constructor
> I0321 17:29:09.503119 29836 trainer_controller.py:196] Hyperparameters for the PPO Trainer of brain 3DBallLearning:
>         batch_size:     64
>         beta:   0.001
>         buffer_size:    12000
>         epsilon:        0.2
>         gamma:  0.995
>         hidden_units:   128
>         lambd:  0.99
>         learning_rate:  0.0003
>         max_steps:      5.0e4
>         normalize:      True
>         num_epoch:      3
>         num_layers:     2
>         time_horizon:   1000
>         sequence_length:        64
>         summary_freq:   1000
>         use_recurrent:  False
>         summary_path:   ./summaries/ppo-0_3DBallLearning
>         memory_size:    256
>         use_curiosity:  True
>         curiosity_strength:     0.01
>         curiosity_enc_size:     128
>         model_path:     ./models/ppo/3DBallLearning
> I0321 17:29:17.505132 29836 trainer.py:168]  ppo-0: 3DBallLearning: Step: 1000. Mean Reward: 1.142. Std of Reward: 0.732. Training.
> ======================================================================================
> before b0:<class 'numpy.ndarray'>
> before b0:<class 'numpy.float64'>
> before b1:(12055,)
> before b2:2.292943551826049
> before b3:1.0055129334506214
> after:(12055,)
> ======================================================================================
> I0321 17:29:26.316777 29836 trainer.py:168]  ppo-0: 3DBallLearning: Step: 2000. Mean Reward: 1.200. Std of Reward: 0.753. Training.
> ======================================================================================
> before b0:<class 'numpy.ndarray'>
> before b0:<class 'numpy.float64'>
> before b1:(12027,)
> before b2:0.7968503772151181
> before b3:0.665763761068578
> after:(12027,)
> ======================================================================================
> I0321 17:29:35.059876 29836 trainer.py:168]  ppo-0: 3DBallLearning: Step: 3000. Mean Reward: 1.514. Std of Reward: 0.997. Training.
> ======================================================================================
> before b0:<class 'numpy.ndarray'>
> before b0:<class 'numpy.float64'>
> before b1:(12020,)
> before b2:0.5939766128731345
> before b3:0.7103289391344811
> after:(12020,)
> ======================================================================================
> I0321 17:29:43.666561 29836 trainer.py:168]  ppo-0: 3DBallLearning: Step: 4000. Mean Reward: 2.107. Std of Reward: 1.419. Training.
> ======================================================================================
> before b0:<class 'numpy.ndarray'>
> before b0:<class 'numpy.float64'>
> before b1:(12020,)
> before b2:0.697332252839317
> before b3:0.8941000903062155
> after:(12020,)
> ======================================================================================
> I0321 17:29:52.248859 29836 trainer.py:168]  ppo-0: 3DBallLearning: Step: 5000. Mean Reward: 2.688. Std of Reward: 2.070. Training.
> ======================================================================================
> before b0:<class 'numpy.ndarray'>
> before b0:<class 'numpy.float64'>
> before b1:(12009,)
> before b2:0.8424811963872444
> before b3:1.2097246845169307
> after:(12009,)
> ======================================================================================
> I0321 17:30:00.663214 29836 trainer.py:168]  ppo-0: 3DBallLearning: Step: 6000. Mean Reward: 4.180. Std of Reward: 3.095. Training.
> ======================================================================================
> before b0:<class 'numpy.ndarray'>
> before b0:<class 'numpy.float64'>
> before b1:(12079,)
> before b2:1.3726466131042312
> before b3:1.6438097316610996
> after:(12079,)
> ======================================================================================
> I0321 17:30:09.199036 29836 trainer.py:168]  ppo-0: 3DBallLearning: Step: 7000. Mean Reward: 7.322. Std of Reward: 5.792. Training.
> ======================================================================================
> before b0:<class 'numpy.ndarray'>
> before b0:<class 'numpy.float64'>
> before b1:(12037,)
> before b2:2.325449693525608
> before b3:2.1559397201042985
> after:(12037,)
> ======================================================================================
> I0321 17:30:17.932440 29836 trainer.py:168]  ppo-0: 3DBallLearning: Step: 8000. Mean Reward: 13.388. Std of Reward: 11.418. Training.
> ======================================================================================
> before b0:<class 'numpy.ndarray'>
> before b0:<class 'numpy.float64'>
> before b1:(12295,)
> before b2:3.6422524510421366
> before b3:2.307802560012203
> after:(12295,)
> ======================================================================================
> I0321 17:30:26.818201 29836 trainer.py:168]  ppo-0: 3DBallLearning: Step: 9000. Mean Reward: 23.168. Std of Reward: 18.091. Training.
> ======================================================================================
> before b0:<class 'numpy.ndarray'>
> before b0:<class 'numpy.float64'>
> before b1:(12167,)
> before b2:[[4.801101]]
> before b3:[[1.9151376]]
> after:(1, 12167)
> ======================================================================================
> Traceback (most recent call last):
>   File "C:\Users\Seto\Anaconda3\envs\ml-agents-2\Scripts\mlagents-learn-script.py", line 11, in <module>
>     load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
>   File "e:\seto\github\unity-technologies\ml-agents\ml-agents\mlagents\trainers\learn.py", line 234, in main
>     run_training(0, run_seed, options, Queue())
>   File "e:\seto\github\unity-technologies\ml-agents\ml-agents\mlagents\trainers\learn.py", line 88, in run_training
>     tc.start_learning(env, trainer_config)
>   File "e:\seto\github\unity-technologies\ml-agents\ml-agents\mlagents\trainers\trainer_controller.py", line 210, in start_learning
>     new_info = self.take_step(env, curr_info)
>   File "e:\seto\github\unity-technologies\ml-agents\ml-agents\mlagents\trainers\trainer_controller.py", line 281, in take_step
>     trainer.update_policy()
>   File "e:\seto\github\unity-technologies\ml-agents\ml-agents\mlagents\trainers\ppo\trainer.py", line 356, in update_policy
>     self.training_buffer.update_buffer.shuffle()
>   File "e:\seto\github\unity-technologies\ml-agents\ml-agents\mlagents\trainers\buffer.py", line 185, in shuffle
>     raise BufferException("Unable to shuffle if the fields are not of same length")
> mlagents.trainers.buffer.BufferException: Unable to shuffle if the fields are not of same length

**Comment by SetoKaiba** [comment]
```Python
 def update_policy(self):
        """
        Uses demonstration_buffer to update the policy.
        """
        n_sequences = max(int(self.trainer_parameters['batch_size'] / self.policy.sequence_length), 1)
        value_total, policy_total, forward_total, inverse_total = [], [], [], []
        advantages = self.training_buffer.update_buffer['advantages'].get_batch()
        print("======================================================================================")
        print("before b0:{0}".format(type(advantages)))
        print("before b0:{0}".format(type(advantages[0])))
        print("before b1:{0}".format(advantages.shape))
        print("before b2:{0}".format(advantages.mean()))
        print("before b3:{0}".format(advantages.std()))
        # test = (advantages - mean) / (std + 1e-10)
        test = (advantages - advantages.mean()) / (advantages.std() + 1e-10)
        print("after:{0}".format(test.shape))
        self.training_buffer.update_buffer['advantages'].set(test)
        print("======================================================================================")
```

**Comment by SetoKaiba** [comment]
After some deep dig in the cause, I found that `value_next = self.policy.get_value_estimate(bootstrapping_info, idx)` in `process_experiences` from `ppo/trainer.py` returns an array instead of a float before the error occurs.

**Comment by SetoKaiba** [comment]
The problem is still on TF side instead of the numpy. Because the `get_value_estimate` method is use the tf session to compute the reward itself. So the problem is after 9000 steps. The value estimate became an array instead of a scalar float.

**Comment by SetoKaiba** [comment]
@awjuliani Finally I got it working. And I tested the nn model it generates. I fix it by a trick.
`
        if not isinstance(value_estimate, float):
            value_estimate = value_estimate[0][0]
`
https://github.com/SetoKaiba/ml-agents/blob/tf2/ml-agents/mlagents/trainers/ppo/policy.py#L199-L200

**Comment by SetoKaiba** [comment]
And it's successfully training. And I try the nn file generated as well. It's working.
The next step may be change in eager style of 2.0.
> I0402 21:14:33.795373  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 1000. Mean Reward: 1.181. Std of Reward: 0.661. Training.
> I0402 21:14:48.256214  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 2000. Mean Reward: 1.223. Std of Reward: 0.755. Training.
> I0402 21:15:03.462997  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 3000. Mean Reward: 1.241. Std of Reward: 0.688. Training.
> I0402 21:15:19.293986  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 4000. Mean Reward: 1.484. Std of Reward: 0.919. Training.
> I0402 21:15:33.623183  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 5000. Mean Reward: 1.979. Std of Reward: 1.400. Training.
> I0402 21:15:48.050157  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 6000. Mean Reward: 2.823. Std of Reward: 2.238. Training.
> I0402 21:16:02.446742  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 7000. Mean Reward: 4.902. Std of Reward: 4.836. Training.
> I0402 21:16:16.705037  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 8000. Mean Reward: 8.218. Std of Reward: 7.453. Training.
> I0402 21:16:30.973583  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 9000. Mean Reward: 15.682. Std of Reward: 15.856. Training.
> I0402 21:16:45.239661  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 10000. Mean Reward: 22.523. Std of Reward: 22.240. Training.
> I0402 21:16:59.680299  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 11000. Mean Reward: 33.677. Std of Reward: 31.949. Training.
> I0402 21:17:14.158347  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 12000. Mean Reward: 54.709. Std of Reward: 38.311. Training.
> I0402 21:17:28.422827  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 13000. Mean Reward: 70.453. Std of Reward: 37.913. Training.
> I0402 21:17:42.778805  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 14000. Mean Reward: 67.481. Std of Reward: 37.354. Training.
> I0402 21:17:56.015239  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 15000. Mean Reward: 83.757. Std of Reward: 33.100. Training.
> I0402 21:18:16.710064  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 16000. Mean Reward: 91.315. Std of Reward: 26.183. Training.
> I0402 21:18:34.961805  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 17000. Mean Reward: 82.100. Std of Reward: 23.276. Training.
> I0402 21:18:50.216350  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 18000. Mean Reward: 87.307. Std of Reward: 24.372. Training.
> I0402 21:19:04.895818  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 19000. Mean Reward: 84.821. Std of Reward: 25.064. Training.
> I0402 21:19:23.605824  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 20000. Mean Reward: 100.000. Std of Reward: 0.000. Training.
> I0402 21:19:39.572229  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 21000. Mean Reward: 100.000. Std of Reward: 0.000. Training.
> I0402 21:19:55.228630  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 22000. Mean Reward: 97.300. Std of Reward: 8.955. Training.
> I0402 21:20:10.517631  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 23000. Mean Reward: 99.417. Std of Reward: 1.935. Training.
> I0402 21:20:25.389780  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 24000. Mean Reward: 93.831. Std of Reward: 21.371. Training.
> I0402 21:20:40.405708  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 25000. Mean Reward: 100.000. Std of Reward: 0.000. Training.
> I0402 21:20:54.933419  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 26000. Mean Reward: 88.800. Std of Reward: 27.110. Training.
> I0402 21:21:09.945354  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 27000. Mean Reward: 97.342. Std of Reward: 8.817. Training.
> I0402 21:21:24.742134  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 28000. Mean Reward: 72.911. Std of Reward: 37.831. Training.
> I0402 21:21:39.403289  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 29000. Mean Reward: 88.950. Std of Reward: 27.259. Training.
> I0402 21:21:53.736311  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 30000. Mean Reward: 90.254. Std of Reward: 26.652. Training.
> I0402 21:22:08.063346  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 31000. Mean Reward: 86.069. Std of Reward: 30.419. Training.
> I0402 21:22:23.146596  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 32000. Mean Reward: 88.807. Std of Reward: 24.430. Training.
> I0402 21:22:37.639866  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 33000. Mean Reward: 81.775. Std of Reward: 34.057. Training.
> I0402 21:22:52.187232  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 34000. Mean Reward: 90.500. Std of Reward: 25.045. Training.
> I0402 21:23:07.060214  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 35000. Mean Reward: 97.192. Std of Reward: 9.314. Training.
> I0402 21:23:21.779124  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 36000. Mean Reward: 100.000. Std of Reward: 0.000. Training.
> I0402 21:23:36.245430  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 37000. Mean Reward: 68.153. Std of Reward: 40.803. Training.
> I0402 21:23:51.253537  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 38000. Mean Reward: 89.762. Std of Reward: 23.634. Training.
> I0402 21:24:03.767476  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 39000. Mean Reward: 89.177. Std of Reward: 27.120. Training.
> I0402 21:24:18.185374  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 40000. Mean Reward: 100.000. Std of Reward: 0.000. Training.
> I0402 21:24:33.363767  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 41000. Mean Reward: 86.923. Std of Reward: 29.122. Training.
> I0402 21:24:48.717121  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 42000. Mean Reward: 84.760. Std of Reward: 31.210. Training.
> I0402 21:25:05.385900  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 43000. Mean Reward: 97.225. Std of Reward: 8.534. Training.
> I0402 21:25:20.480203  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 44000. Mean Reward: 77.807. Std of Reward: 36.498. Training.
> I0402 21:25:35.126723  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 45000. Mean Reward: 85.686. Std of Reward: 29.017. Training.
> I0402 21:25:50.300158  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 46000. Mean Reward: 81.007. Std of Reward: 33.306. Training.
> I0402 21:26:05.132381  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 47000. Mean Reward: 95.008. Std of Reward: 17.294. Training.
> I0402 21:26:19.626146  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 48000. Mean Reward: 83.053. Std of Reward: 34.592. Training.
> I0402 21:26:34.123156  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 49000. Mean Reward: 91.446. Std of Reward: 20.070. Training.
> I0402 21:26:50.629204  3764 trainer_controller.py:87] Saved Model
> I0402 21:26:50.648164  3764 trainer.py:169]  ppo-0: 3DBallLearning: Step: 50000. Mean Reward: 100.000. Std of Reward: 0.000. Training.
> I0402 21:26:52.473239  3764 trainer_controller.py:87] Saved Model
> I0402 21:26:52.769763  3764 policy.py:193] List of nodes to export for brain :3DBallLearning
> I0402 21:26:52.769763  3764 policy.py:195] 	is_continuous_control
> I0402 21:26:52.769763  3764 policy.py:195] 	version_number
> I0402 21:26:52.769763  3764 policy.py:195] 	memory_size
> I0402 21:26:52.769763  3764 policy.py:195] 	action_output_shape
> I0402 21:26:52.769763  3764 policy.py:195] 	action
> I0402 21:26:52.769763  3764 policy.py:195] 	action_probs
> I0402 21:26:52.770262  3764 policy.py:195] 	value_estimate
> W0402 21:26:52.927511  3764 deprecation.py:323] From C:\Users\Seto\Anaconda3\envs\ml-agents-2\lib\site-packages\tensorflow\python\tools\freeze_graph.py:127: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use standard file APIs to check for files with this prefix.
> I0402 21:26:53.616407  3764 saver.py:1280] Restoring parameters from ./models/ppo/3DBallLearning\model-50001.cptk
> W0402 21:26:53.769163  3764 deprecation.py:323] From C:\Users\Seto\Anaconda3\envs\ml-agents-2\lib\site-packages\tensorflow\python\tools\freeze_graph.py:232: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use `tf.compat.v1.graph_util.convert_variables_to_constants`
> W0402 21:26:53.769163  3764 deprecation.py:323] From C:\Users\Seto\Anaconda3\envs\ml-agents-2\lib\site-packages\tensorflow\python\framework\graph_util_impl.py:247: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use `tf.compat.v1.graph_util.extract_sub_graph`
> I0402 21:26:53.832060  3764 graph_util_impl.py:270] Froze 20 variables.
> I0402 21:26:53.847037  3764 graph_util_impl.py:303] Converted 20 variables to const ops.
> Converting ./models/ppo/3DBallLearning/frozen_graph_def.pb to ./models/ppo/3DBallLearning.nn
> IGNORED: Cast unknown layer
> IGNORED: StopGradient unknown layer
> GLOBALS: 'is_continuous_control', 'version_number', 'memory_size', 'action_output_shape'
> IN: 'vector_observation': [-1, 1, 1, 8] => 'sub_3'
> IN: 'epsilon': [-1, 1, 1, 2] => 'mul_1'
> OUT: 'action', 'action_probs', 'value_estimate'
> I0402 21:26:53.933398  3764 policy.py:184] Exported ./models/ppo/3DBallLearning.nn file
> DONE: wrote ./models/ppo/3DBallLearning.nn file.

**Comment by SetoKaiba** [comment]
https://github.com/SetoKaiba/ml-agents/tree/tf2
I make a tf2 branch for it.
The training is tested working with 3DBall.
And the generated nn file is working with Barracuda as well.

https://github.com/SetoKaiba/ml-agents/tree/tf2-develop
And also, the develop branch splits ml-agents into two packages.
I made a tf2-develop branch for it.
The training is tested working with 3DBall.
And the generated nn file is working with Barracuda as well.

**Comment by PeterJaq** [comment]
@SetoKaiba Thank you for your work! And I also still try to implement ml-agent to tf2. The work is all finished？

**Comment by SetoKaiba** [comment]
@PeterJaq It's a working migrated version. But it's not modified to eager execution yet.

**Comment by SetoKaiba** [comment]
https://github.com/tensorflow/tensorflow/issues/27669
And here's the related issue for TF 2.0. My migrated version is solved by a workaround. But it's indeed a bug from TF 2.0. When it's fixed, it will be ok to remove the workaround.

**Comment by StepNeverStop** [comment]
Does ml-agents support TF 2.0? I also want to migrate my code to TF2.0, need I modify some file in ml-agents/envs or ml-agents/trainers??

**Comment by chriselion** [comment]
Now that TF2.0 is officially released, we plan to add support for it soon. Out internal tracker ID for this is MLA-51.

**Comment by harperj** [comment]
I'm going to close this issue since it's captured in our internal tracker, but we’ll ping back with any updates.

**Comment by chriselion** [comment]
@SetoKaiba Thanks for doing the initial work on this. I merged https://github.com/Unity-Technologies/ml-agents/pull/2665 to the develop branch, which has support (via tf.compat.v1) for tensorflow2 library.
