### ISSUE TITLE
Simulation much slower using Python

### ISSUE THREAD

**Issue by rafvasq** [Unity-Technologies/ml-agents#1859]
Whether I run using a build or in the Editor using the Python API, the simulation is much slower than when using mlagents-learn. I'm using a PyTorch implementation of DDPG and using Cuda10.1. Is this expected behaviour?

**Comment by rafvasq** [comment]
I guess this is expected behaviour for more expensive learning algorithms. By raising the decision frequency, frame rate is much better. 

I also noted that only CUDA v9.0 and cuDNN v7.0.5 is supported right now according to the [installation docs](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation-Windows.md), but this wasn't related to my performance issues in the end.

**Comment by Usmaniatech** [comment]
I am facing the same issue and furthermore, I am generating a score graph calculating the scores using DDPG, how can I create a model that can be used as internal brain. @rafvasq
