### ISSUE TITLE
Curiosity Training Help

### ISSUE THREAD

**Issue by benmadinebuisness** [Unity-Technologies/ml-agents#1864]
Hi there, im currently trying out curiosity training and I've basically copied all the same parameters from the pyramid example but my results after half a million steps are pretty poor and I'm not sure why... 
I have already made 4 agents navigate to the end of a maze using imitation learning but I am now trying to create an agent that hunts down these agents by exploring the maze, so using curiosity for that. 

Here is what my environment looks like: 

![help](https://user-images.githubusercontent.com/46612079/54938352-1ddac300-4f1e-11e9-8d7a-bbec6052c639.JPG)

The red agent, bottom right, should be exploring the maze but it is only moving around the bottom room (which is it located) and the room above it. Here is the code im using for it(probally gone over the top with the ray angles but I dont think that is the issue):

`#region Agent Methods
    public override void InitializeAgent()
    {
        _RayPerception = GetComponent<RayPerception>();
        _Rigidbody = GetComponent<Rigidbody>();
    }

    public override void CollectObservations()
    {
        const float rayDistance = 35f;
        float[] rayAngles = { 20f, 90f, 160f, 45f, 135f, 70f, 110f };
        float[] rayAngles1 = { 25f, 95f, 165f, 50f, 140f, 75f, 115f };
        float[] rayAngles2 = { 15f, 85f, 155f, 40f, 130f, 65f, 105f };
        float[] rayAngles3 = { 120f, 180f, 240f, 300f, 360f };
        float[] rayAngles4 = { 130f, 190f, 250f, 310f, 350f };
        float[] rayAngles5 = { 140f, 200f, 260f, 320f, 340f };
        string[] detectableObjects = { "Floor", "waypoint", "agent" };

        AddVectorObs(_RayPerception.Perceive(rayDistance, rayAngles, detectableObjects, 0f, 0f));
        AddVectorObs(_RayPerception.Perceive(rayDistance, rayAngles1, detectableObjects, 0f, 5f));
        AddVectorObs(_RayPerception.Perceive(rayDistance, rayAngles2, detectableObjects, 0f, 10f));

        AddVectorObs(_RayPerception.Perceive(rayDistance, rayAngles3, detectableObjects, 0f, 15f));
        AddVectorObs(_RayPerception.Perceive(rayDistance, rayAngles4, detectableObjects, 0f, 20f));
        AddVectorObs(_RayPerception.Perceive(rayDistance, rayAngles5, detectableObjects, 0f, 25f));
        AddVectorObs(transform.InverseTransformDirection(_Rigidbody.velocity));
    }

    public void MoveAgent(float[] act)
    {
        Vector3 controlSignal = Vector3.zero;
        controlSignal.x = act[0];
        controlSignal.z = act[1];
        _Rigidbody.AddForce(controlSignal * 5.5f);
    }

    public override void AgentAction(float[] vectorAction, string textAction)
    {
        AddReward(-1f / agentParameters.maxStep);
        MoveAgent(vectorAction);
    }

    public override void AgentReset()
    {
        _Rigidbody.angularVelocity = Vector3.zero;
        _Rigidbody.velocity = Vector3.zero;
        transform.rotation = Quaternion.identity;
    }
    #endregion

    #region Collision Method
    private void OnCollisionEnter(Collision collision)
    {
        if (collision.gameObject.tag == "agent")
        {
            SetReward(2f);
            Done();
            transform.position = _Spawn.transform.position;
        }
        //if (collision.gameObject.tag == "Floor")
        //{
        //    SetReward(-1f);
        //    Done();
        //    transform.position = _Spawn.transform.position;
        //}
    }
    #endregion`

Any help would be great, not sure why my agent isn't exploring well, thanks in advance

**Comment by awjuliani** [comment]
Hi @benmadinebuisness 

The curiosity parameters will need to be fine-tuned for this specific environment. The default parameters we provide were fine-tuned for the pyramids example, and likely won't transfer well. In particular the `curiosity_strength` will likely be important to balance with some extrinsic reward.

**Comment by benmadinebuisness** [comment]
> Hi @benmadinebuisness
> 
> The curiosity parameters will need to be fine-tuned for this specific environment. The default parameters we provide were fine-tuned for the pyramids example, and likely won't transfer well. In particular the `curiosity_strength` will likely be important to balance with some extrinsic reward.

Hi there, thanks for the reply! Yea I was thinking that as well, just wasn't sure what the best values would be, but I guess that is down to testing. Just out of curiosity, would you suggest a very high strength, maybe past 10 considering the pyramid is 0.01... Not sure how the scaling is effected for the strength.
