### ISSUE TITLE
Velocity Problem with MLAgent learningBrain vs. PlayerBrain

### ISSUE THREAD

**Issue by AdhamAlHarazi** [Unity-Technologies/ml-agents#1871]
Is there a hidden difference between the normal game (also PlayerBrain) vs LearningBrain in MLAgents? I have an object-throwing projectile by changing its velocity; it works normally in PlayerBrain mode but it behaves differently with LearningBrain mode.

Is there anything I am missing regarding velocity in MLAgents?

I use the below function to calculate the desired velocity to apply to my object 
   
```
private Vector3 CalculateDesiredVelocity(Vector3 target, Vector3 origin, float time){

        Vector3 distanceTargetOrigin = target - origin;
        Vector3 distanceTargetOriginXZ = distanceTargetOrigin;
        distanceTargetOriginXZ.y = 0f;
        

        float Sy = distanceTargetOrigin.y;
        float Sxz = distanceTargetOriginXZ.magnitude;

        float Vxz = Sxz / time;
        float Vy =  Sy / time + 0.5f * Mathf.Abs(Physics.gravity.y) * time;

        Vector3 desiredVeloctiy = distanceTargetOriginXZ.normalized;
        desiredVeloctiy *= Vxz;
        desiredVeloctiy.y = Vy;

        return desiredVeloctiy;

	}

```

**Comment by xiaomaogy** [comment]
Hi @AdhamAlHarazi, there is no hidden difference between these two brains. How do you know they behaves differently?

**Comment by AdhamAlHarazi** [comment]
Thanks for replying. When I use the player brain the object (projectile) hit the target point, but when I use the learning brain the object (projectile) extends its travel trajectory and hit another further point.

**Comment by xiaomaogy** [comment]
@AdhamAlHarazi You mean given the exact same action, they behave differently?

**Comment by AdhamAlHarazi** [comment]
Yes, exactly.

**Comment by AdhamAlHarazi** [comment]
@xiaomaogy After reinstalling Unity and importing MLAgent, the problem is gone. I do not know the reason yet since I modified other things in the code as well before reinstalling, but I wanted you to know it is solved. Thank you!

**Comment by xiaomaogy** [comment]
@AdhamAlHarazi Nice! Yes sometimes reinstalling everything helps.
