### ISSUE TITLE
can't load TF model after training

### ISSUE THREAD

**Issue by lintongoxbotica** [Unity-Technologies/ml-agents#1873]
I cant seem to be able to load the trained TF .nn file into the learning brain. I checked and the previous trained file was in .bytes format. Can anybody answer this? 
<img width="196" alt="Screenshot 2019-03-28 at 22 50 10" src="https://user-images.githubusercontent.com/47388833/55197888-e6814600-51ab-11e9-86be-8f139e326a64.png">
<img width="413" alt="Screenshot 2019-03-28 at 22 50 16" src="https://user-images.githubusercontent.com/47388833/55197893-e8e3a000-51ab-11e9-8ee1-7c06b963c3d1.png">

**Comment by xiaomaogy** [comment]
Maybe you are in a older version of ml-agents? The v0.7 ml-agents should generate .nn file.

**Comment by lintongoxbotica** [comment]
@xiaomaogy , I first set up my project when in v0.6, and recently pulled master to 0.7. After this, i cant drop the .nn file into the model box. How can I load it? or there is something incompatible with V0.6?

**Comment by MarcoMeter** [comment]
#1782 
Potential duplicate

**Comment by lintongoxbotica** [comment]
Thank you @MarcoMeter. I was stuck on this for so long!

**Comment by oseq** [comment]
@lintongoxbotica  so how did you solve the problem? I Have simmilar after migration from v0.6 to v0.81. I pulled lastest version from git hub so dont know what migh cause this problem. How i can check version of SDK i am using?

**Comment by lintongoxbotica** [comment]
@oseq You need to use ENABLE_BARRACUDA rather than ENABLE_TENSORFLOW in your player settings. There are many ways to find out the SDK version, you can simply do "git log" and find out.

**Comment by unityjeffrey** [comment]
hi @lintongoxbotica - closing this issue as it appears to be solved.
