### ISSUE TITLE
Loading trained model from gym

### ISSUE THREAD

**Issue by kaiolae** [Unity-Technologies/ml-agents#1875]
Hi!
I'm following the instructions to train a model in gym, generating the unity_model.pkl file (I assume there is a tensorflow model in there?). Is there any way to load this trained model in the unity interface. Normally, I would load a .nn network there, is there some way to convert the pickled model to a .nn file?
Thanks!

**Comment by xiaomaogy** [comment]
You can but it will need some customization, basically the model you trained using openai baseline will have a different graph compared with our model graph, so you will need to map their graph nodes into ours.

**Comment by kaiolae** [comment]
Thanks for the info! Given this reply, I found it was more convenient to just visualize this in openAI gym by loading the model and environment again there.
