### ISSUE TITLE
How to run env with my own model in jupyter

### ISSUE THREAD

**Issue by OneFiveChen** [Unity-Technologies/ml-agents#1879]
I follow the [getting-started.ipynb](https://github.com/Unity-Technologies/ml-agents/blob/master/notebooks/getting-started.ipynb) use hierarchical rl to train multi soccer agents which differ from the example soccer env given by ML-Agents(Observations and Actions have totally been changed). 
I want to see the final performance not just only from the reward curve in tensorboard. How could I get the game frames? Run it like that I add the model file to Internal Brain in unity editor so that I can record some videos ：) 

ML-Agent version : 0.5

**Comment by xiaomaogy** [comment]
If you want to see the game frame, you could reshape the image observation, and then visualize that image in python.

**Comment by OneFiveChen** [comment]
OK，I change the time scale in Academy and load my model in windows system. That works. Maybe some things wrong in X server that it cannot open the game window automatically.
