### ISSUE TITLE
BarracudaModelParamLoader - unresolved using/import compile error

### ISSUE THREAD

**Issue by TheDozMan** [Unity-Technologies/ml-agents#1881]
Background:

After following "Installation-Windows.md" and "Getting-Started-With-Balance-Ball.md" running the 3D ball (both training and inference) was successful.  I could train a NN and apply it back to the brain to run in inference mode.

Problem:

However I was unable to complete steps for "Learning-Environment-Create-New.md".  Steps for "Implement Academy" (would not recogize/compile Academy script) and "Add Brain Assets" (Assets->Create->ML Agents  Menu option was not available).

Stuff I tried:

-Deleted, then re-cloned the ml-agents repo  (April 2nd, 2019 : no improvement)
-From my anaconda environment, re-installed (pip install -e .) with and without cache. (April 2nd, 2019 : no improvement)
-Upgraded Unity (from 2018.3.9f to 2018.3.11) - (April 2nd, 2019 : No change)

-After noticing a message in the unity console about an un-used import, I edited the BarracudaModelParamLoader.cs and commented out the "using System.Runtime.Remoting.Messaging;" line and saved (from VS 2017). This resolved the console error (now only shows a warning) and the Unity menu item (Assets->Create->ML Agents) is now available. My Academy script is now recognized.

Not sure if something needs to be changed in the codebase or if I have done something wrong. Seems to be working now so not urgent, more of an FYI.

THanks

Environment:

Windows 7 Pro (SP 1)
3rd Gen Core i7, 16GB RAM, SSD (100GB+ free space)
Installed without GPU support

**Comment by ervteng** [comment]
Hi @TheDozMan, this seems like an issue with the Barracuda loader. @mantasp, have you seen this on newer builds of Unity?

**Comment by ervteng** [comment]
Hi @TheDozMan, this seems like an issue with the Barracuda loader. @mantasp, have you seen this on newer builds of Unity?

**Comment by mantasp** [comment]
This should be already fixed in master branch. Please re-open if you still see the issue.
