### ISSUE TITLE
Shadows not showing up in visual_observations

### ISSUE THREAD

**Issue by markpwoodward** [Unity-Technologies/ml-agents#1889]
Shadows are not showing up in the visual_observations. I see them clearly in the game display of the visual editor, but the same visual observation for the same camera, when it comes out of mlagents, does not render the shadows. Any idea what the problem might be?

I was able to reproduce this with the unmodified VisualBanana environment.

os: linux (debian laptop)
editor: Unity2018.3.5f1
mlagents-envs: 0.6.2
UnitySDK: 0.6.0-24-ge5b578a (e5b578a96167292e23e063da67b35626190576b4)

**Comment by awjuliani** [comment]
Hi @markpwoodward 

This is likely because you are using different quality settings for training and inference mode (set in the Academy component).

**Comment by markpwoodward** [comment]
@awjuliani Thank you so much for the quick response. Would it be the "Quality Level" setting, I see for Visual Banana, that Training is set to 0, but Inference is set to 5.

Also, how do I specify which configuration to use? I don't see it in the constructor for UnityEnvironment constructor arguments.

**Comment by awjuliani** [comment]
These values (0-5) correspond to the "Quality Settings" for the project: https://docs.unity3d.com/Manual/class-QualitySettings.html. `Training` is used by default when connecting from the python api, and `inference` is used otherwise.

**Comment by markpwoodward** [comment]
That makes sense, thank you. And changing the "Quality Level" for the Training Configuration in the Academy inspector did solve the problem, as you suggested. Thanks!
