### ISSUE TITLE
Python API with Editor play mode

### ISSUE THREAD

**Issue by buntyke** [Unity-Technologies/ml-agents#189]
Hi ML-Agents Community,

Thank you for starting this great project! 

I am working on a project where I am getting sensory data from an Iphone using the Unity Remote app to control an agent. For this reason, I can only run the game using the Editor play mode and cannot build an executable. 

My question is if its possible to integrate the python API with the editor play mode. Specifically I would like to broadcast my demonstration data to the python API. 

Thanks,
Nishanth

**Comment by awjuliani** [comment]
Hi @buntyke,

Thanks for your question. Unfortunately we don't currently support connecting to python from the editor. This is something we are experimenting with though, and hope to have ready in the coming months.

**Comment by buntyke** [comment]
Thank you for letting me know. This enhancement would be great!

**Comment by MarcoMeter** [comment]
@awjuliani 
Do you have a roadmap or a little more detailed list of features, which you are currently working on and which you want to approach in the future? I'm still focusing a lot on building environments right now, but soon I'd like to work on the python and interface side. My major intention is of course to solve more complex environments, so some features like frame stacking are desirable.

**Comment by awjuliani** [comment]
Hi @MarcoMeter,

We've got an internal roadmap we are working from. I plan to implement frame/state stacking within the next couple weeks. We would like to move development into the open as much as possible though, so that people like you who might be interested in helping out can.
