### ISSUE TITLE
High GC Alloc for communicator based on gRPC

### ISSUE THREAD

**Issue by SetoKaiba** [Unity-Technologies/ml-agents#1890]
Currently the communicator use gRPC to exchange the data with Unity and TensorFlow. gRPC C# is mostly managed and it GC Alloc for KBs of data. Then a GC Collect will be triggered after just a few seconds. And for RNN training, the GC Alloc per frame is up to 100KB.
It seems that the GC Alloc will affect some kind of training. For example, there is an agent and npc with a blade. It hurts by the animation. When GC Collect is triggered for too many times, the animation fps is dropped. The hurt will be calculated incorrectly. So I can't make a high concurrent agents training due to the GC Alloc issue for communicators.
Is there a plan to replace the communicator with unmanaged stuffs? I think maybe it's not only the issue for my game.
And also, is there a place to discus with guys developing ml-agents or developing with ml-agents in a more real-time way? I mean maybe a connect messenger, irc, Slack, Discord or something similar.

**Comment by SetoKaiba** [comment]
Maybe a pool for communication will solve the problem as well.

**Comment by SetoKaiba** [comment]
And also, for RayPerception, I rewritten with NativeList from Unity.Collections. I can prevent GC Alloc for Collection Observations. But It's still high GC Alloc for communicator.

**Comment by ervteng** [comment]
Hi @SetoKaiba, this is the main place as of this moment to discuss development - our email address (on the main readme) would be the other place we check regularly. 

I think the ultimate goal is to remove the need for gRPC at all - for fast-running environments, the serialization/deserialization of large observations quickly becomes CPU-hungry. But in the meantime, it would be great to discuss ways to optimize gRPC. 

Adding @vincentpierre, our resident gRPC expert.

**Comment by ervteng** [comment]
Thank you for submitting this request. We’ve added it to our internal tracker with the ID MLA-76. I’m going to close this issue for now, but we’ll ping back with any updates.
