### ISSUE TITLE
Discrete Action Always Chosen Equal to Action Size

### ISSUE THREAD

**Issue by mdm373** [Unity-Technologies/ml-agents#190]
I have a scene with a single brain training a single agent. The brain's action type is set to "discrete" and its size is 5. So I thought that when running external, I could expect integer actions ranging from 0-4.

However, I'm always seeing the agent step called with "5", the action size. If I lower it to 4, its always called with 4. I had another example with a smaller state working earlier, but after making some changes I'm hitting this issue. Any help would be awesome.

Inspector of Brain:
![inspector](https://user-images.githubusercontent.com/5975669/34147634-6a2350c4-e46c-11e7-985a-14216429e6fb.png)

Load Message:
![load-env](https://user-images.githubusercontent.com/5975669/34147642-6d7f05ec-e46c-11e7-94d0-cc386eabf313.png)

Log Output showing Action taken and Action Length:
![log-message](https://user-images.githubusercontent.com/5975669/34147646-6f044c06-e46c-11e7-834e-962b15d595c3.png)

Log Code:
![log-action](https://user-images.githubusercontent.com/5975669/34147914-60bc438c-e46d-11e7-8bfb-7d9c291f684b.png)

**Comment by MarcoMeter** [comment]
Hi @mdm373 
if you use discrete actions, the chosen action is represented by the first element in act (i.e. act[0]).

Here is an example:

```
public override void AgentStep(float[] act)
    {
                int action = (int)act[0];
                if (action == 0)
                {
                    // Move Left
                    _rigidbody.velocity = new Vector3(-1 * _agentSpeed, 0, 0);
                }
                else if (action == 1)
                {
                    // Move Right
                    _rigidbody.velocity = new Vector3(1 * _agentSpeed, 0, 0);
                }
                else
                {
                    // Don't/Stop move
                    _rigidbody.velocity = Vector3.zero;
                }
}
```

**Comment by mdm373** [comment]
Hi @MarcoMeter 

Thanks for the reply. I am evaluating the 0th action in the provided float array. My issue is that the 0th action seems to always be chosen, in every agent step as equal to the size of the action state (in my case 5). I had everything working in a previous iteration of the project, but it seems like, if I up the state size to be larger than the action size, the chosen action is always 5.

**Comment by awjuliani** [comment]
Hi @mdm373,

This seems like some kind of bug. Your intuition is correct, that when the discrete action size is set to 5, it should only ever produce values ranging between 0 and 4. Does it happen on the example environments for you?

**Comment by mdm373** [comment]
Hey @awjuliani,

No I didn't have this issue in the examples I think I just figured this out.

For my new state fields, I I provided float.MaxValue (An indicator for "no hit" rather than distance). It seems like that was what was causing the problem. I updated the state logic to instead provide -1 for "no hit" and now everything is working as expected. I must have caused some kind of overflow issue in the unity to python communications but I didn't catch anything in any logs.

**Comment by MarcoMeter** [comment]
@mdm373 Make sure that you normalize all your inputs, so that they in the range -1 to +1 or 0 to +1.

This is one approach for normalization:
![normalization](https://user-images.githubusercontent.com/6996955/34198524-f5b43fa0-e56a-11e7-8b6e-55dc4f9bc434.png)

**Comment by mdm373** [comment]
@MarcoMeter I'll give that a shot as well, that should also help my ray cast "no hit" scenario since I could leave that as the upper limit of the normalized value.

**Comment by TashaSkyUp** [comment]
I'm having the same issue. out of range observation vectors are not the problem.. Ill test some things and get back to you if i figure it out.

**Comment by TashaSkyUp** [comment]
After some testing. This appears to be because my time_horizon setting in the yaml file was greater than the buffer_size
