### ISSUE TITLE
Error CS0234: The type or namespace name 'Remoting'

### ISSUE THREAD

**Issue by atom182** [Unity-Technologies/ml-agents#1900]
Hi, i download the ml-agents and i follow the tutorial from the proyect.
When drag the ml-agents and gizmos folders in unity apear an error, and they said:
"Assets\ML-Agents\Scripts\InferenceBrain\BarracudaModelParamLoader.cs(7,22): error CS0234: The type or namespace name 'Remoting' does not exist in the namespace 'System.Runtime' (are you missing an assembly reference?)"
i don't know if a don't install something. 
plsease help me.
the scripting runtime version is .net 4x equivalent

**Comment by xiaomaogy** [comment]
Hi @vincentpierre does this look familiar to you?

**Comment by vincentpierre** [comment]
This was addressed in #1869 
This fix was simply to remove [this line](https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Scripts/InferenceBrain/BarracudaModelParamLoader.cs#L7)
