### ISSUE TITLE
Learning time for Imitation Learning

### ISSUE THREAD

**Issue by moonsh** [Unity-Technologies/ml-agents#1903]
I set up imitation learning using my own environment.

Even I played a teacher agent for 30 minutes it seems that there is no progress at all.

I thought that imitation learning can surprisingly handle with a complex environment 

Is time-consuming for imitation learning depending on the complexity of the environment?

**Comment by ervteng** [comment]
Hi @moonsh, the current implementation of Imitation Learning does not work well for complex environments, as it simply directly imitates player behavior (Behavioral Cloning). So unless you have enough player data to cover a large number of possible states, you won't get a good policy out of it. Stay tuned for a better IL algorithm - or try out an early version on the branch called `develop-irl-pre-training`.

**Comment by moonsh** [comment]
@ervteng  Thank you for the answer. I will try both suggestions.
