### ISSUE TITLE
Area for releasing and sharing ML-Agents stuff

### ISSUE THREAD

**Issue by caioc2** [Unity-Technologies/ml-agents#1904]
Hello,

I took a (superficial) look  and couldnt find a specific place to share ML-Agents related stuff, like experiences, projects and games. As much as there exists the unity forum, I think that not everyone is interested in RL and a proper place for ML-Agents related stuff would be interesting. IMHO the github issues is not the place for that.

If I'm mistaken and there exists a place for it, please point me out.

In the other hand I would like to share my first experience with both (D)RL and ML-Agents for solving the rubiks cube 2x2 using only RL, no search algorithms, pattern match databases, etc.

You can read a bit of it [here](https://github.com/caioc2/RSolver/blob/master/README.md)
and try out the mini-game [here](https://caioc2.github.io/RSolver/game/)

Thanks

**Comment by ervteng** [comment]
Hi @caioc2, thank you for sharing your game! This is really cool. 

Currently Github Issues is the most active place that people share information. But I agree there should be a better place for discussions and sharing rather than just bugs/problems. @unityjeffrey do we have a better place for doing this?

**Comment by unityjeffrey** [comment]
hi @caioc2 - the predominant community activity is here in Github issues.  Unity also hosts our own Discord channels, which also includes [ML](https://discordapp.com/channels/489222168727519232/502171346503991307).  However, it is not actively monitored compared to Github issues.  We do have several folks share their experiences, including RL and developing games, on Github issues.  I would encourage to continue the discussion here.  

I checked out your Rsolver project and its pretty cool.  Did you have any trouble with the inference engine on WebGL?

**Comment by unityjeffrey** [comment]
Also - feel free to provide us feedback in our survey.  We actively monitor this as well - https://docs.google.com/forms/d/e/1FAIpQLSfVnER5i5YiE748MjyI7Ts3gIgpfzXZjSrDGPKR7s2Ydeb9tg/viewform

**Comment by caioc2** [comment]
Hi, 

The inference engine worked perfectly for PC and WebGL.

If here is the right place I'll continue to share any progress and related stuff here, thanks.

**Comment by unityjeffrey** [comment]
Absolutely - we look forward to checking it out!
