### ISSUE TITLE
Imitation learning online is running too fast

### ISSUE THREAD

**Issue by MLaroucheLaSalle** [Unity-Technologies/ml-agents#1907]
I don't know what's happening, but when I train my AI using imitation learning online the speed of the simulation is way too fast.

The academy setting said to run with a timescale of 1 and I launched the training process with mlagents-learn config/online_bc_config.yaml --train **--slow**

but it doesn't feels slow, it feel fast and the more i restart the training the faster it seems to get.
Is there something I'm doing wrong?

**Comment by Nunukuluk** [comment]
I had the same problem. For me it worked to play around with the  "Time Scale" under "Training Configuration" from the Academy script attached to my Academy Game Object inside of Unity, while also passing the --slow line in the command prompt.

**Comment by vincentpierre** [comment]
Hi, sorry for the late reply. I think this bug was addressed in version 0.8
