### ISSUE TITLE
Why do the devs convert booleans to integers in the Banana Collectors example?

### ISSUE THREAD

**Issue by ShaneCaler** [Unity-Technologies/ml-agents#1908]
In this example, why are the frozen/shoot boolean variables converted to integers before being passed as observations? (using System.Convert.ToInt32()) Is there any benefit to this?

I'm currently trying to train an agent to play what I'm calling "shape runner" which is just an endless runner mixed with tetris (agent has to decide when to be a cube, rectangle, etc. to fit through the obstacles). So I'm wondering if I should be converting my "isWhateverShape" bools to ints?

**Comment by awjuliani** [comment]
Hi @ShaneCaler,

All values passed as observations need to be set to a numerical value. If you pass bools they will be automatically converted to ints anyway. Doing this manually in the banana collector was because it was implemented before the automatic conversion was a part of ML-Agents.

**Comment by ShaneCaler** [comment]
@awjuliani gotcha, that's kind of what I figured but just wanted to make sure. Thank you!
