### ISSUE TITLE
No TFmodels file after training such as Ball3DBrain.bytes?

### ISSUE THREAD

**Issue by yangjob** [Unity-Technologies/ml-agents#1914]
The version is 0.5. And I did not get this problem before! It appears strangely!
When I finish training, the last line of output is "You need to supply the name of a node to --output_node_names." and I do not get the .bytes file.I do not have much experience about ML, DL, DRL and tensorflow.

![捕获](https://user-images.githubusercontent.com/33831043/55792545-7780e700-5af3-11e9-8afa-a1685ad43cdc.PNG)

**Comment by yangjob** [comment]
I have checkpoint file and .pb file in PyramidBrain dir. But why do not  have .byte file in ppo-0 dir?
![捕获](https://user-images.githubusercontent.com/33831043/55792779-f4ac5c00-5af3-11e9-8324-dd7c794335e7.PNG)

**Comment by yangjob** [comment]
Does it mean I have not got any training models? Or I failed to train? Or the agent learn nothing？

**Comment by xiaomaogy** [comment]
Hi @yangjob , this is a known issue on v0.5 that on Windows, if you pause the training by ctrl+c, if won't generate the .bytes file.  Please update to v0.7.  If your issue continues, please let us know.

**Comment by yangjob** [comment]
> Hi @yangjob , this is a known issue on v0.5 that on Windows, if you pause the training by ctrl+c, if won't generate the .bytes file. Please update to v0.7. If your issue continues, please let us know.
Thank you! However,  I didn't pause the training by ctrl+c. I have finished my training or command line "mlagents-learn ...", though the agent learned nothing(max_steps is 5e5). The first picture show the final output.And in the last line of output is "You need to supply the name of a node to --output_node_names."  I search it in Baidu, it seems about tensorflow settings!

**Comment by yangjob** [comment]
Hi @xiaomaogy ,Thank you! However, I didn't pause the training by ctrl+c. I have finished my training or command line "mlagents-learn ...", though the agent learned nothing(max_steps is 5e5). The first picture show the final output.And in the last line of output is "You need to supply the name of a node to --output_node_names." I search it in Baidu, it seems about tensorflow settings!

**Comment by xiaomaogy** [comment]
@yangjob Again, we won't help you debug the issues that happened on v0.5. Please upgrade to v0.7!
