### ISSUE TITLE
Cannot add official .nn file to LearningBrain

### ISSUE THREAD

**Issue by zbrnwpu** [Unity-Technologies/ml-agents#1918]
There are officially available in TFModels . nn model，i can‘t drag the 3DBallLearning model file from the Assets/ML-Agents/Examples/3DBall/TFModels folder to the Model field of the 3DBallLearning Brain in the Inspector window

**Comment by zbrnwpu** [comment]
> There are officially available in TFModels . nn model，i can‘t drag the 3DBallLearning model file from the Assets/ML-Agents/Examples/3DBall/TFModels folder to the Model field of the 3DBallLearning Brain in the Inspector window

**Comment by khaledbnmohamed** [comment]
Hi , I have the same Issue , How did you solve it ?

**Comment by oseq** [comment]
I have same issue. What is the solution?
