### ISSUE TITLE
**Unity Inference Engine Survey**

### ISSUE THREAD

**Issue by unityjeffrey** [Unity-Technologies/ml-agents#1927]
Your opinion matters a great deal to us. Only by hearing your thoughts on the Unity Inference Engine can we continue to improve and grow. Please take a few minutes to let us know about it.

[Fill out the survey](https://docs.google.com/forms/d/e/1FAIpQLSe9mWiunsYZLexkMtYZZ6q1tmDzKWW_bY97FaMU8E3nwq3QHQ/viewform)

@mantasp @rejunity

**Comment by Guidosalimbeni** [comment]
Hi great new addition. Thank you for providing this. Can I use it also to load model that I develop and trained outside of Unity in python? For instance a cnn made in keras to recognise digit from minst dataset?  It is only a question to use nn file extensions instead of bytes...?

**Comment by unityjeffrey** [comment]
hi @Guidosalimbeni - right now we only support models that are developed or created with ML-Agents.  However, we are potentially looking at adding support for other models.  @mantasp

**Comment by 0lento** [comment]
I like the new inference engine but would also request getting the actual source code with the barracuda packages.

Right now if I put "com.unity.barracuda": "0.1.6-preview" or "com.unity.barracuda.burst": "0.1.6-preview" on my projects manifest on 2019.2.0a11 project, it will trigger API upgrade tool each time I start the editor with this project. API upgrade tool can't do anything either as the barracuda files are in managed precompiled dll so it just keeps spamming the dialog =)

**Comment by mantasp** [comment]
@Guidosalimbeni full package of Barracuda is available here: https://github.com/mantasp/barracuda-release, it additionally includes ONNX and Keras converters.

**Comment by mantasp** [comment]
@0lento API update issue should be fixed with new Barracuda builds, you can use them as package by adding these lines to your manifest.json:
“com.unity.barracuda”: “https://github.com/mantasp/barracuda-release.git#0.2.1-preview” for Barracuda.Core and optionally Burst plugin
“com.unity.barracuda.burst”: “https://github.com/mantasp/barracuda-burst-release.git#0.2.1-preview”.
