### ISSUE TITLE
Question - Visual observation training usually takes more time?

### ISSUE THREAD

**Issue by moonsh** [Unity-Technologies/ml-agents#1935]
I am training my environment using one camera from one agent's.

Even though 3 or 4 hours passed there is no big difference.
( I got a good result without using visual observation )

Should I wait more time to get a good result?

Thank you,

**Comment by zheyangshi** [comment]
I also tried to train the agent in PyramidVisual, and I found that the reward was keeping -1 before step 1.6 * e6 (--num-envs=4). Compared to training with vector observation, visual observation seems not to be a good input for this environment.

**Comment by xiaomaogy** [comment]
Hi @moonsh @zheyangshi , the training on the visual observation will generally take much longer. To increase the training speed, you can also increase the number of agents.

**Comment by moonsh** [comment]
@zheyangshi @xiaomaogy Thanks a lot.  I will close this issue.
