### ISSUE TITLE
Error after installing ToolKit V0.8 IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by Fadroni** [Unity-Technologies/ml-agents#1957]
Hey,
After I could successfully train my agent on my PC I wanted to start training on my work desktop. (because it has a GTX 1080 so I could train on GPU instead of CPU). Note that I could train on GPU on my PC 
Version PC: 
* ML-Agent Toolkit v0.6
* Anaconda: Anaconda3-2018.12-Windows-x86_64 (Pyhton version 3.6.8)
* NVIDEA CUDA: 10.1 Cudann 10.1
* Windows 10 (Desktop Windows 10 Home)

So, I installed the same version of Anaconda, Unity and ML-ToolKit on the destop but then I got this error see FILE.txt 
[FILE.txt](https://github.com/Unity-Technologies/ml-agents/files/3093263/FILE.txt)

Found the solution for that here on Github somewhere, it said by installing a newer version of ML-ToolKit in my case v0.8 the problem should be solved, it solved that problem but it gave me a new one.
I installed it, imported the new “ML-Agents” & “Gizmos” file into my project and deleted the old ones. Then I deleted the “ENABLE_TENSORFLOW” in my player settings. But when I try and train it, I get this error (in LogFile) see FILE1.txt
[FILE1.txt](https://github.com/Unity-Technologies/ml-agents/files/3093262/FILE1.txt)

Any idea how to fix it? Any help would be great. 
I have no visual observations selected in my brain, only vector observations. Any help would be great.
(Could be that can’t use the work desktop till after the weekend)

**Comment by mattinjersey** [comment]
are you sure that there is no error in your code, for example using an index in an array that exceeds the dimension of the array. It might be interesting to run the code even without MLAgents to make sure it is working correct.

**Comment by Fadroni** [comment]
The code works on my PC portable computer, I can train the agent there. I just wanted to be able to train my agent on the desktop from work cause it has more GPU.
So, yup I’m like 99% sure there is nothing wrong with the code. 

Do you have any idea how to fix it?

**Comment by vincentpierre** [comment]
I think I have an idea of what could be wrong. I think you have a camera attached to your agent. Your BrainParameters say there is 0 visual observations but there is a camera dragged into the camera properties of your agent. Let us know how this goes.

**Comment by Fadroni** [comment]
Thanks for the respons @vincentpierre I'll check it after the weekend (it's on desktop at work )

**Comment by Fadroni** [comment]
Thanks @vincentpierre , there was indeed a camera (Thought I deleted that but apparently not). 
Just out curiosity why didn't it gave an error in the v0.6? Cause there was a camera too and not error.

**Comment by vincentpierre** [comment]
Ok, great, I will label this a s bug since the error needs to be more graceful.

**Comment by Fadroni** [comment]
So problem is fixed I'll close this
