### ISSUE TITLE
[Solved] Cumulative reward/ episode length not updating

### ISSUE THREAD

**Issue by andreaBassich** [Unity-Technologies/ml-agents#196]
Hi,

When i train my model all the data about the agent's performance is collected correctly at first, but then it stops displaying the mean reward, and stops updating cumulative reward and episode length on TensorBoard. A typical example of this is below, with the model saving every 50k steps and the results updating every 5k:

Step: 5000. Mean Reward: -1.46849992063. Std of Reward: 0.464499920865.
Step: 10000. Mean Reward: -1.04049990218. Std of Reward: 0.0.
Saved Model
Saved Model
...

Any clue on how to fix this problem or on what caused it?

Also as a little side note, are there any plans of training as fast as possible, without having to be bound to a time scale of 100?

Cheers

**Comment by awjuliani** [comment]
Hi @andreaBassich,

Is this perhaps linked to the length of the episodes in your environment? 

We are working on unlocking timescale, but it will take a little time to come to realization, since it is tied closely to the game engine itself.

**Comment by andreaBassich** [comment]
Hi @awjuliani,

I capped the length of my episode to 1k game steps in the academy, at the moment I don't even get the initial info at 5 and 10k steps, but only the save model is displayed when I train my net.

Following your question I tried a mock run with maxsteps = 100 in the academy, the environment does reset correctly after 100 game steps, but I didn't have any luck with the logs.

Any idea on what could cause this besides the episode length?

Cheers

**Comment by awjuliani** [comment]
Do you get the same issue when running the example environments?

**Comment by andreaBassich** [comment]
No, I think it might be a problem specific to my environment, in fact today i tried to run the Basics notebook on my environment and it raises the following exception:
UnityActionException: The episode is completed. Reset the environment with 'reset()'
Although the PPO notebook doesn't give me any exceptions.
How would i go about fixing this?

**Comment by andreaBassich** [comment]
Turns out all the issues I've been having were because for some reason at the end of the AgentReset method i decided to set done = false. Thank you for your help.
