### ISSUE TITLE
Problem to train agents v: 0.8.0

### ISSUE THREAD

**Issue by franvf** [Unity-Technologies/ml-agents#1960]
Hi everybody, i make a little game for try to learning how works the ml-agents, but when i execute the command:  mlagents-learn ./unity-volume/Test/Test.x86_64 --train
 to train the agents appears the next error: 
```
Traceback (most recent call last):
  File "/usr/local/bin/mlagents-learn", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "/media/fran/Data/ml-agents/ml-agents/ml-agents/mlagents/trainers/learn.py", line 262, in main
    run_training(0, run_seed, options, Queue())
  File "/media/fran/Data/ml-agents/ml-agents/ml-agents/mlagents/trainers/learn.py", line 73, in run_training
    trainer_config = load_config(trainer_config_path)
  File "/media/fran/Data/ml-agents/ml-agents/ml-agents/mlagents/trainers/learn.py", line 146, in load_config
    .format(trainer_config_path))
mlagents.envs.exception.UnityEnvironmentException: Parameter file could not be found at ./unity-volume/Test/Test.x86_64.
```

**Comment by vincentpierre** [comment]
Here is a [link](https://github.com/Unity-Technologies/ml-agents/blob/0.8.1/docs/Training-ML-Agents.md#training-with-mlagents-learn) to the documentation.

The basic command for training is:

```sh
mlagents-learn <trainer-config-file> --env=<env_name> --run-id=<run-identifier> --train
```

where

* `<trainer-config-file>` is the file path of the trainer configuration yaml.
* `<env_name>`__(Optional)__ is the name (including path) of your Unity
  executable containing the agents to be trained. If `<env_name>` is not passed,
  the training will happen in the Editor. Press the :arrow_forward: button in
  Unity when the message _"Start training by pressing the Play button in the
  Unity Editor"_ is displayed on the screen.
* `<run-identifier>` is an optional identifier you can use to identify the
  results of individual training runs.

The API changed in a recent version, the environment path must be specified with `--env=` and the config file argument must be passed as argument

**Comment by franvf** [comment]
Thx @vincentpierre !
