### ISSUE TITLE
How should I calculate an episodic reward for the CRAWLER env?

### ISSUE THREAD

**Issue by chihoxtra** [Unity-Technologies/ml-agents#1962]
Dear professionals,

I am a new learner of RL. I am trying to implement PPO to solve the CRAWLER env. I am a bit puzzled by how to calculate an episodic reward. 

One way is to check if all agents 'done' status are true. that is:
`if np.all(done):  
                self.episodic_rewards.append(np.mean(self.running_rewards))
                break`
but then I found that the number of steps resulting in all done are always 1000.

I have seen other fellows using a t_max limit as the break condition, that is:
`            if ep_len >= T_MAX: 
                self.episodic_rewards.append(np.mean(self.running_rewards))
                break`
where the done status are ignored and rewards will continue to be accumulated. This one obviously will increase the episodic reward if t_max is great. 

I am not sure what should be the official way to calculate an episodic reward. Can anyone please shed light on this?

**Comment by vincentpierre** [comment]
Hi @chihoxtra 
Unfortunately, this repository is not meant to teach people reinforcement learning. I would recommend looking at the [PPO paper](https://arxiv.org/pdf/1707.06347.pdf). There are a lot of resources online to help you : here is a [blog post](https://medium.com/emergent-future/simple-reinforcement-learning-with-tensorflow-part-8-asynchronous-actor-critic-agents-a3c-c88f72a5e9f2) by @awjuliani  
In Actor Critic like methods, when the episodes are very long the cumulative reward is estimated beyond a certain time horizon using the critic.

**Comment by chihoxtra** [comment]
thank you so much. Sorry for asking the wrong question. I will do some more researches by myself. Thanks.

Sam
