### ISSUE TITLE
Reset in multi-agent environments in UnityEnv

### ISSUE THREAD

**Issue by inconst** [Unity-Technologies/ml-agents#1963]
Documentation for env.step() says that 
> When end of episode is reached, you are responsible for calling `reset()` to reset this environment's state.

But how can I reset separate environments in case of multi-agent setup?

**Comment by vincentpierre** [comment]
Hi @inconst 
I am not sure I understand your question fully. In our definitions, an environment can contain multiple agents. When calling `env.reset` the environment (an all of the agents it contains) will reset. When the Academy of an environment is `Done` then the Python `env` will no longer be able to step and `env.reset` must be called to continue the simulation.
In the case of multi-agent setup, there is still a single environment.

**Comment by inconst** [comment]
So whenever any of agents finish its episode, `Done` is called, right? But other agents may need more time to finish theirs, so they can't be reset yet because env.reset() will reset all agents. Is this handled somehow?

**Comment by vincentpierre** [comment]
There are 2 levels of Done flags : One on the Agents and one on the Environment / Academy. 
When the Environment / Academy is Done, everything must reset : Academy and Agents alike.
When an Agent is done, it is labeled as Done and the simulation can go on. (The Environment is no Done and can proceed)
