### ISSUE TITLE
Reward function in python gym interface

### ISSUE THREAD

**Issue by inconst** [Unity-Technologies/ml-agents#1966]
I'm trying to implement HER ([link](https://arxiv.org/pdf/1707.01495.pdf)) algorithm using Unity gym interface. This algorithm requires the ability to get reward function for arbitrary state. Is there a way I can get reward from Unity environment without performing env.step() ?

**Comment by vincentpierre** [comment]
Hi @inconst 
In order to calculate the reward an agent receives, the Unity Environment must simulate it. It is currently not possible to request a reward given a state, action, goal triplet.
I would recommend creating this reward on the Python side.
