### ISSUE TITLE
Unity ML-Agents Gym Wrapper On Windows

### ISSUE THREAD

**Issue by KDUNAS** [Unity-Technologies/ml-agents#1968]
Hi,

 Dopamine and gym didn't support Windows.
 So how could I use the Unity ML-Agents Gym Wrapper and the environments built by unity to train?

**Comment by vincentpierre** [comment]
Hi @KDUNAS 
You can use our PPO trainer to train UnityEnvironments as it does not require Gym to work. If you really want to train using Dopamine and Gym, this sounds more like a feature request for their project.

**Comment by MarcoMeter** [comment]
Google Dopamine pretty much works on Windows.
If you want to use the Atari environments on Windows then you have to install this
`pip install --no-index -f https://github.com/Kojoley/atari-py/releases atari_py`

**Comment by KDUNAS** [comment]
Thank you for the replay.
