### ISSUE TITLE
Forces from AgentStep or collision still being applied after AgentReset

### ISSUE THREAD

**Issue by goncharom** [Unity-Technologies/ml-agents#1972]
Hi! I'm working on a rocket learning to land on a specific zone. To steer the rocket I use AddForceAtPosition() and to reset the agent I check the Done() flag and set the rewards using onCollisionEnter() (more reward for landing on the landing pad), however, after I reset the agent, some random forces are applied to the rocket making it spin instead of being still. I suspect said forces are from the collision itself. To avoid dumping the entire code, here's how roughly everything works on the agent script. (I can share the entire code if needed of course).
```
public override void AgentReset(){
        transform.position = new Vector3(Random.value * 500, 500, Random.value * 500);
        transform.rotation = Quaternion.identity;
        rBody.velocity = new Vector3(0f, 0f, 0f);
        rBody.angularVelocity = new Vector3(0f, 0f, 0f);
        //Also set the landing pad on a random location
}
void OnCollisionEnter(Collision col){
      //Check what is it colliding with and if the rocket has the right angle
      if(speed>10){

      SetReward(5f);
      Done();

      }else{
     Done();

    }
public override void AgentAction(float[] action, string textAction){
       if (action[0] == 5f){
    		rBody.AddForceAtPosition(main_thruster*15, main_thruster_position);

            main_thruster_particles.Play();

    	}
    	if (action[0] == 1f){
            rBody.AddForceAtPosition(side1_thruster, side1_thruster_position);

            side1_thruster_particles.Play();
    	}
    	if (action[0] == 2f){
            rBody.AddForceAtPosition(side2_thruster, side2_thruster_position);
            side2_thruster_particles.Play();
    	}
    	if (action[0] == 3f){
    		rBody.AddForceAtPosition(side3_thruster, side3_thruster_position);
            side3_thruster_particles.Play();
    	}
    	if (action[0] == 4f){
            rBody.AddForceAtPosition(side4_thruster, side4_thruster_position);
            side4_thruster_particles.Play();
    	}


}

}
```
I tried to set the object to kinematic when it collides and turning it off on the first AgentStep(), but the problem seems to persist. 
Thanks a lot in advance!

**Comment by vincentpierre** [comment]
I am not sure if I can help with this information. I think AgentAction might be called after reset and that this could be the cause of the problem. Can you check with `IsDone()` if the agent is done when calling AgentAction ?

**Comment by goncharom** [comment]
Hi. I checked with a simple log in `AgentAction()` checking `IsDone()` and nothing gets printed. I think I figured out the problem though, but I am having trouble fixing it. I checked the terrain as trigger so no collision forces are applied when the rocket collides, but I still have the same problem. Since I calculate the positions where I add the forces on that step on `AgentStep()`, maybe the forces are being added after the reset, but on positions before the reset?

**Comment by goncharom** [comment]
Okay I seem to have found a way around it. I simply added a step variable, which I set to zero on every reset, and on the `AgentStep()` has the following logic:
```
if (step < 1){
        rBody.velocity = new Vector3(0f, 0f, 0f);
        rBody.angularVelocity = new Vector3(0f, 0f, 0f);
        step +=1;
}else{
        step += 1;
        //Same agentStep as above
}
```
