### ISSUE TITLE
Object Detection

### ISSUE THREAD

**Issue by Amanpradhan** [Unity-Technologies/ml-agents#1973]
I originally wanted to convert my model into barracuda to use for object detection. Seeing as it is not very easy to do it right now, is there any way to train the model inside unity by providing data to it?

**Comment by vincentpierre** [comment]
Hi,
The Inference Engine does not support back-propagation so it is not possible to do the training in C# at this time. You can convert your model from python using [this script](https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents/mlagents/trainers/tensorflow_to_barracuda.py) but some operators might be missing.

**Comment by mantasp** [comment]
As mentioned in our e-mail discussion: Mobilenet+SSD is currently not supported by inference engine, but we added it to our wishlist. Thanks for feedback!

**Comment by unityjeffrey** [comment]
Thank you for your comments.  We’ve documented your feedback and will prioritize when appropriate.

**Comment by LedStarr** [comment]
Hey, just wanted to know how serious you are considering this? I am working on a Project that needs to implement Mobilenet+SSD till the end of year for a Demo. Should I wait for the next release or should I make it work with the older TensorFlowSharp Plugin? I just need Object Detection in a WebCam and Baracuda would make it quite simple.
