### ISSUE TITLE
Using Agents to personalise player experience

### ISSUE THREAD

**Issue by JeroenBoesten** [Unity-Technologies/ml-agents#1977]
Hi, 

I want to create a personal experience for the players of my game, by adapting the difficulty specific for that player. 

To understand what I'm trying to achieve some context. The game is a 2d game where people have to answer questions with yes or no, there are a couple of settings that the agent can decide on making the game harder or easier like the duration of the question, number of tests, amount of categories.

I want to base rewards on the percentage of question that are correctly answered, something like; 
0-30% correct -> -1
31-60% correct -> -0.5
61-70% correct -> +1
71-100% correct -> -0.5

But the problem where I can't seem any information about is that for this the training of the agent has to be done after every completed level and the decision making on the start of a level. That means the training needs to be embedded into the actual playing of the game, does anyone have a idea if this is even possible at all.

Thanks in advance,
Greetings,

**Comment by harperj** [comment]
Hi @JeroenBoesten -- we haven't done much work at this time with ML-Agents training with humans in the loop. It would likely require substantial code changes.  At this time ML-Agents is probably not the best solution for this use-case.  You might want to read some about other approaches for training models with slow feedback loops -- one tool I know of is [Horizon](https://research.fb.com/wp-content/uploads/2018/10/Horizon-Facebooks-Open-Source-Applied-Reinforcement-Learning-Platform.pdf).

**Comment by JeroenBoesten** [comment]
Hi! Thank you so much for your answer and thereby confirming my presumption. 

I didn't know Horizon so thank you for that I will definitely check it out!
