### ISSUE TITLE
[Question] About "log_sigma_squared"

### ISSUE THREAD

**Issue by seaswander** [Unity-Technologies/ml-agents#1980]
While reading code, I only found:
`log_sigma_sq = tf.get_variable("log_sigma_squared", [self.act_size[0]], dtype=tf.float32,
                                       initializer=tf.zeros_initializer())`
How is this variable get calculated and assigned? Is it affected by optimizer BP process?
Many thanks for your help.

**Comment by harperj** [comment]
Hi @seaswander, this statement is creating a variable to represent the log of the variance for the action outputs of the policy.  This is the continuous control case, and each action output is modeled by a gaussian with a given mean and stddev/variance.  Then each action value is produced by generating a value from this distribution mean and standard deviation scaled by the epsilon hyperparam (https://github.com/Unity-Technologies/ml-agents/blob/2cccc2c9f337e36aef969122066b52002ee800da/ml-agents/mlagents/trainers/models.py#L286).  The variable will be updated by the optimizer based on the loss.

**Comment by harperj** [comment]
I think I've answered your question here, so I'm going to close this issue -- but please feel free to reopen or create a new issue if you run into any more problems.

**Comment by seaswander** [comment]
@harperj Thanks for your explanation!
