### ISSUE TITLE
Can not use trained brain

### ISSUE THREAD

**Issue by tzoiker** [Unity-Technologies/ml-agents#1985]
I am following the guide from here https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Basic-Guide.md#after-training. Using version 0.7.

I have trained the model and placed `CopterBrain.nn` file in the `TFModels` directory. Now, according to the guide, I need to drag `CopterBrain.nn` to the model placeholder of the `LearningBrain` in the inspector. However, nothing happens and I only get the warning (see screenshot). What am I doing wrong? Model seems to be trained successfully as I have cptk files with the names corresponding to the number of total steps.

![image](https://user-images.githubusercontent.com/6230141/56757370-b4f49e00-679c-11e9-98e7-ddb6e0926c3b.png)

**Comment by oseq** [comment]
I have the same problem after migration to v0.81. In 0.6 version models were not .nn files, now i cannot choose model or drag it even on freshly created (after migration) brain :)

**Comment by harperj** [comment]
Hi @tzoiker -- can you confirm that you're using v0.7 for both the Unity plugin and the Python library?  It looks like the model is looking for a "Text Asset" -- the format we used for v0.6.  From v0.7 on this should say "NN Model".

**Comment by oseq** [comment]
Ok, this problem was presented couple of times before. I had same issue, you need to change from ENABLE_TENSORFLOW to ENABLE BARRACUDA in project settings and reload Unity. You can find better descrition for this solution in other issues.

**Comment by harperj** [comment]
This issue has been inactive for some time so I'm going to close it, but if you need additional assistance feel free to reopen the issue.
