### ISSUE TITLE
Neural Network

### ISSUE THREAD

**Issue by MrGitGo** [Unity-Technologies/ml-agents#1987]
I don't know if I can read it in the docu, but I couldn't find it. So my question is: What kind of neural network is ml-agents using (recurrent, convolutional,...)?

**Comment by MarcoMeter** [comment]
This is dynamic and configurable.
If your agent has visual observations, a CNN is used.
If there is only a vector observation, than it is just a feed forward network.
If you set use_recurrent to true in the trainer_config, an LSTM layer will be added.

**Comment by harperj** [comment]
@MrGitGo -- what @MarcoMeter said is correct, the network used depends on the settings you choose.  Since I think the direct question is answered, I'm going to close this issue but please feel free to reopen or create a new issue if there's something we can help with.
