### ISSUE TITLE
Issue on Rollerball training

### ISSUE THREAD

**Issue by JuhaVuorenalho** [Unity-Technologies/ml-agents#1988]
I've followed this tutorial for creating the learning environment with the ball on a plane. https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md

When I have entered the command _**mlagents-learn C:\Users\Juha\ml-agents\config\trainer_config.yaml --run-id=RollerBall-1 --train**_ I get the prompt saying that I have to press play in Unity. However, when I do so, I receive following error in Unity: 

UnityAgentsException: The Communicator was unable to connect. Please make sure the External process is ready to accept communication with Unity.
MLAgents.Batcher.SendAcademyParameters (MLAgents.CommunicatorObjects.UnityRLInitializationOutput academyParameters) (at Assets/ML-Agents/Scripts/Batcher.cs:91)
MLAgents.Academy.InitializeEnvironment () (at Assets/ML-Agents/Scripts/Academy.cs:345)
MLAgents.Academy.Awake () (at Assets/ML-Agents/Scripts/Academy.cs:250)

This is what gets then printed to the prompt:

![Prompt](https://user-images.githubusercontent.com/22168022/56804190-8e327800-682d-11e9-84c7-c91aed425608.PNG)

I'm using Python 3.6.8 with 64-bit Anaconda prompt. I don't know if it makes any difference, but before I'm able to run any ml-agents train, I have to use the command **_set CONDA_DLL_SEARCH_MODIFICATIONS_ENABLE=1_**

I was able to follow the tutorial for balancing balls and to train it, so it seems a bit weird.

Any help is appreciated. Thanks in advance.

**Comment by buddha314** [comment]
I am following that same tutorial on Windows and when I press Play, it simply does not respond.  I'm using the 2017 LTS version of Unity.

**Comment by harperj** [comment]
Hi @JuhaVuorenalho -- could you double check that you've clicked the "Control" box for the brain you're using in the Academy GameObject?  Sometimes this error can occur because the game isn't actually attempting to connect to the trainer.

There is a timeout on both the side of the game and the side of the trainer, so timing does matter to some extent.

**Comment by buddha314** [comment]
My issue was resolved here: https://github.com/Unity-Technologies/ml-agents/issues/1888#issuecomment-487629739 but I have experienced the "control" problem as well.

**Comment by harperj** [comment]
Thanks for the update @buddha314 -- glad you've resolved the problem.  I'm going to close this issue, but please feel free to reach out if you run into any more trouble!
