### ISSUE TITLE
mlagents

### ISSUE THREAD

**Issue by antonio1234567891011** [Unity-Technologies/ml-agents#1990]
Hi guys
i can only install tensorflow cpu from version 13 upwards in anaconda 3.7
when is a version of mlagents going to work with this?
or how can i  make this work? 
thanks

**Comment by MarcoMeter** [comment]
use Python 3.6

**Comment by harperj** [comment]
Hi @antonio1234567891011 -- as @MarcoMeter said at this time we are only supporting Python 3.6.  We've had a number of requests for 3.7 support and have plans to look into this in the near future.

**Comment by antonio1234567891011** [comment]
Thanks guys @harperj  @MarcoMeter
