### ISSUE TITLE
How to convert to *.nn file?

### ISSUE THREAD

**Issue by aaronvdbrugge** [Unity-Technologies/ml-agents#1991]
Hi guys,

We've created a model in Python, it is a .pb file.

Could you please advise on how we can convert this to a model file that can be used by Unity Inference?

Also, how far along is Unity Inference for working on Android and iOS?

We're currently using an outdated TF# but the accuracy within Unity is worse than regular TF, strangely. Also our latest model made with TF 12.0 does not run on TF#.

Thanks.

**Comment by harperj** [comment]
Hi @aaronvdbrugge -- you might give the included [tensorflow_to_barracuda.py](https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents/mlagents/trainers/tensorflow_to_barracuda.py) script a go to convert your model.

**Comment by ManjitBedi** [comment]
Hi @harperj.  I am working with @aaronvdbrugge.  I just installed Python 3.6.8 etc on a Mac.

I am getting errors in the conversion process:

```
IGNORED: PlaceholderWithDefault unknown layer
IGNORED: Switch unknown layer
IGNORED: Switch unknown layer
IGNORED: Shape unknown layer
IGNORED: Switch unknown layer
IGNORED: Merge unknown layer
IGNORED: Switch unknown layer
IGNORED: Switch unknown layer
IGNORED: Shape unknown layer
IGNORED: Switch unknown layer
IGNORED: Merge unknown layer
Traceback (most recent call last):
  File "tensorflow_to_barracuda.py", line 23, in <module>
    tf2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
  File "/Users/manjitbedi/Projects/TensorFlow & ML/Unity/ml-agents-0.8.0/ml-agents/mlagents/trainers/tensorflow_to_barracuda.py", line 940, in convert
    process_model(i_model, args)
  File "/Users/manjitbedi/Projects/TensorFlow & ML/Unity/ml-agents-0.8.0/ml-agents/mlagents/trainers/tensorflow_to_barracuda.py", line 887, in process_model
    process_layer(l, o_context, args)
  File "/Users/manjitbedi/Projects/TensorFlow & ML/Unity/ml-agents-0.8.0/ml-agents/mlagents/trainers/tensorflow_to_barracuda.py", line 746, in process_layer
    shapes = klass.out_shapes([x.shape for x in o_l.tensors])
  File "/Users/manjitbedi/Projects/TensorFlow & ML/Unity/ml-agents-0.8.0/ml-agents/mlagents/trainers/tensorflow_to_barracuda.py", line 51, in <lambda>
    [shapes[0][0], 1, 1, shapes[0][1]],  # W
IndexError: tuple index out of range
```

**Comment by harperj** [comment]
Hi @ManjitBedi @aaronvdbrugge you may want to check out #1986.  A new release of Barracuda has come out which may convert a broader range of models, though we can only offer limited help for converting models which aren't generated by ML-Agents at this time.

**Comment by ManjitBedi** [comment]
Thanks for the info.  I may try it soon.  We can close the issue for now.

**Comment by rash1994** [comment]
Did you get the conversion of .pb to .nn ?

**Comment by aaronvdbrugge** [comment]
Hi guys,

At the moment we are on a break from this as our client paused the project.
We thank you very much for your support and we'll let it know when we can
pick up the work.

Sincerely / Met vriendelijke groeten,
Aaron van der Brugge
