### ISSUE TITLE
UnityEnvironmentException: Couldn't launch the 3DBall environment. Provided filename does not match any environments.

### ISSUE THREAD

**Issue by shengtianzhu** [Unity-Technologies/ml-agents#200]
Hi
I tried the 3DBall Tutorial. But when I try to load the environment I get the error:

![image](https://user-images.githubusercontent.com/7135752/34294463-a6fa6756-e743-11e7-9465-06a771918ee2.png)

I use Unity to Build the exe file named"3DBall".And Copy this flie to python folder.But it's show error.
on the Tutorial step:
![image](https://user-images.githubusercontent.com/7135752/34294778-0ad21f98-e745-11e7-818b-f686b42b05ba.png)
I think the "environment" is "3DBall.exe"  flie and  "3DBall_Data" folder. Copy this two flie to python folder.
What is error on my step?

**Comment by shengtianzhu** [comment]
I am using Windows 10. other environment like the Tutorial say

**Comment by Izhmael** [comment]
Hello,
I tried only on MAC. On it i have to save build in unity-environment folder, and next in the Jupyter notebook change env_name = "name_of_the_file" in Basics.ipynb. 

<img width="1130" alt="zrzut ekranu 2017-12-22 11 33 14" src="https://user-images.githubusercontent.com/3924185/34295155-09c36cf8-e70c-11e7-8aff-aa09cbaaae29.png">

**Comment by shengtianzhu** [comment]
Hi @Izhmael  
Thanks! I try on your step. But still error
![image](https://user-images.githubusercontent.com/7135752/34316546-8f6959d6-e7d3-11e7-9ea9-fc81d44c3ea4.png)
I don't think I know how to use the jupyter. I'll learn how to use the jupyter, first

**Comment by awjuliani** [comment]
Hi @shengtianzhu,

It seems that you are running one ipython notebook from another. Is there a reason for this?

**Comment by Fangh** [comment]
you have to put your build name 3DBall.exe in python directory. (mine is called build) :

![image](https://user-images.githubusercontent.com/6020679/34326279-20f2ee1e-e8a9-11e7-836d-29c2e4f12df1.png)

**Comment by shengtianzhu** [comment]
Hi @Fangh 
this is my python directory screenshot
![image](https://user-images.githubusercontent.com/7135752/34330621-e20a9f1a-e959-11e7-9083-d3bd3e178cad.png)
and my Basics.ipynb screenshot is
![image](https://user-images.githubusercontent.com/7135752/34330726-e773ecc6-e95a-11e7-827c-dd2e74ff7b2d.png)

**Comment by shengtianzhu** [comment]
Hi @awjuliani 
I run this ipython notebook like this.In Jupyter Home view. Click the Python3 button jump to the Untitled1 page. In the Untitled1 page, I run this command
 “%run C:/Users/Sheng/Downloads/ml-agents-master/python/Basics.ipynb”。The python directory screenshot and Basics.ipynb screenshot in the above reply
All the steps are shown in the  screenshot
![image](https://user-images.githubusercontent.com/7135752/34330862-64aa1ab6-e95c-11e7-88dd-d9f2cbbb2f67.png)

![image](https://user-images.githubusercontent.com/7135752/34330870-824cf35e-e95c-11e7-8e78-adbd15eff9e2.png)

**Comment by awjuliani** [comment]
Hi @shengtianzhu,

I believe the issue is that you need to launch jupyter notebook itself from your `ml-agents/python directory`. It seems that it is being launched from another directory, whichever one contains the two `Untitled` notebooks.

**Comment by jglazman** [comment]
Had some trouble with this in OSX Sierra. Fix for me was:
- as awjuliani says, run notebook from `ml-agents/python` dir
- put your `Foo.app` unity build in that same `ml-agents/python` dir
- now if you run e.g. Basics in notebook then set `env_name = "Foo"`

**Comment by tananuka** [comment]
Hi @jglazman, i have the same problem and tried as you said, but that didn't help(
<img width="1051" alt="screen shot 2018-01-06 at 23 43 25" src="https://user-images.githubusercontent.com/175611/34643813-304bd234-f33c-11e7-9b97-9082ce9a6828.png">
<img width="441" alt="screen shot 2018-01-06 at 23 42 01" src="https://user-images.githubusercontent.com/175611/34643814-306f0d08-f33c-11e7-9c30-800bb2803296.png">
<img width="831" alt="screen shot 2018-01-06 at 23 41 39" src="https://user-images.githubusercontent.com/175611/34643815-309084b0-f33c-11e7-934b-e54e6d5d4dc6.png">
-----------------------------
I am using Unity 2017.3.0f3 Personal and macOS High Sierra 10.13.2
I Installed tensorflow cpu  setup through anaconda.

**Comment by jeremyPLR** [comment]
@tananuka it looks like your app file is named Foo, but it should be named Foo.app

`ml-agents/python/Foo.app`

**Comment by tananuka** [comment]
@jeremyPLR 
It named, just filename extension hided
<img width="878" alt="screen shot 2018-01-07 at 13 22 56" src="https://user-images.githubusercontent.com/175611/34648659-ba245158-f3ae-11e7-9672-69ec4de5ae36.png">

**Comment by tananuka** [comment]
Thanks to @wouterhardeman. When i opened the application (Foo.app) by right-clicking and selecting 'Show Package Contents' and then go to 'Contents/MacOS', the file is called 'test2'. I renamed it from "Foo" to "test2" and `env_name="test2"`. That helped because it is first name of build. 'Ball3DAcademy' started successfully!
All glory to @wouterhardeman 👍

**Comment by awjuliani** [comment]
Glad you were able to figure out the problem @tananuka! OSX is somewhat tricky in that changing the name of the .app does not change the name of the actual binary file itself. Our UnityEnv code currently assumes that the name of the `.app` and the name of the binary are the same. Now that I think about it though, this doesn't necessarily need to be the case... I will add to our to-do list making this more flexible.

**Comment by awjuliani** [comment]
Thanks to @wouterhardeman, the renaming `.app` issue has been fixed! https://github.com/Unity-Technologies/ml-agents/commit/a2f8ef564471cef99fde5b594daf1368a50d9b95

**Comment by mustfkeskin** [comment]
In windows 10 you give your application.exe path

![image](https://user-images.githubusercontent.com/5824559/48534634-b6e73680-e8b9-11e8-8ff2-c59f7a8858e0.png)

For example "E:\ml-agents-master\envs\MLFirst\Sample Project\"
