### ISSUE TITLE
Integrating heuristic and learning brains

### ISSUE THREAD

**Issue by edthink** [Unity-Technologies/ml-agents#2008]
I am looking to develop an agent that integrates both heuristic and learning brains. The heuristic brain would control aspects of locomotion (e.g. speed), and the learning brain would control navigation (e.g. direction). However, I am not clear whether this is possible. Within the Unity interface only one brain can be specified per agent, and I am unable to find an interface for passing observations to different brains or for handling 'disagreement'. Can anyone advise whether this can be done (or whether it _should not_ be done), or if there is a workaround that could achieve this?

I am only new to Unity and ml-agents, so the best way I can see would be to force a Heuristic decision from AgentAction() using a copy of the vectorObs, and handle the additional actions there. But a more elegant approach would be preferred if available.

**Comment by ervteng** [comment]
Hi @edthink, this should be possible, and there are several ways to do it. You could, for instance, add two agents to your GameObject - one that controls locomotion and one that controls navigation. Then, the navigation agent uses the vectorObs, while adding its instructions (e.g. go forward, go left) as observations to the locomotion agent. Or your approach within AgentAction should work as well. 

Is there a reason why the heuristic brain needs to be a Brain at all (heuristic brains aren't trainable)? Or are you planning on training the Heuristic Brain as a Learning Brain then using the trained model to control locomotion?

**Comment by edthink** [comment]
Thanks @ervteng, it's good to know I'm not completely off-track. You're right that in this case the heuristic rules can be coded rather than put into a brain structure. I will have a look at the option of adding two agents to a GameObject.

I do still wonder if the solution would be tidier if two or more sets of rules (learnt or coded) could be combined within a single brain 'superstructure' (perhaps this is possible within the GameObject). The aim I have would be to allow interaction and competition between rulesets, and selection of different brains and actions depending on context.

**Comment by ervteng** [comment]
Hi @edthink, it is possible within GameObject by adding an additional Brain to your Agent (by adding, e.g., a public Brain and dragging it in in the editor). You can then easily swap brains in the Agent code this way. But there's no easy way to have multiple Brains simultaneously in one Agent yet, aside from calling this second Brain's Decision and Initialization manually. 

We'll look into a better way to structure this - it seems to have a lot of use cases!

**Comment by edthink** [comment]
Thanks @ervteng that's been very helpful. The two brain approach would seem to allow differences in decision frequency, which I would like to include, and as far as I can see, isn't possible via AgentActions().
