### ISSUE TITLE
How to get result after fetch code line?

### ISSUE THREAD

**Issue by KozykinRoman** [Unity-Technologies/ml-agents#2020]
I want to classify my wheel images by type with Barracuda platform.
And here is my code.

void Start()
    {
        Invoke("FuncTest", 1f);
    }
    
    private void FuncTest()
    {
        var model = ModelLoader.Load("D:\\model.bytes");
        var worker = BarracudaWorkerFactory.CreateWorker(BarracudaWorkerFactory.Type.CSharpFast, model);
        var inputs = new Dictionary<string, Tensor>();
        inputs["Placeholder"] = new Tensor(m_Sprite.texture);
        worker.Execute(inputs);

        var O = worker.Fetch("loss");
        O.Print();
        O.Dispose();
        worker.Dispose();
    }

So the publisher explained the O(tensor object) contains the result of the classification.
But when I call O.Print() : the result is (1,1,1,7)
It doesn't make sense what it is to me.
Plz help me how to get result with sample codes. 
Regards.

**Comment by ervteng** [comment]
@mantasp 

It looks like O.Print() is getting the size of the tensor (the loss, probably over some batch).

**Comment by KozykinRoman** [comment]
Thanks very much. ervteng.
