### ISSUE TITLE
tf-agents

### ISSUE THREAD

**Issue by mattinjersey** [Unity-Technologies/ml-agents#2021]
I wonder if you have considered collaboration with tf-agents. they are also building a reinforcement library.

**Comment by roboserg** [comment]
You have the Python API. With that, you can use whatever library you want. Also, see their gym interface, then you can copy paste any library / tutorial online.

**Comment by ervteng** [comment]
Thanks for the heads-up @mattinjersey! When we first looked at TF-Agents, it was in (very) early forms. But definitely worth another look now that it's semi-official. If anything, a shim between tf-agents and the ML-Agents Python API (or Gym wrapper) shouldn't be too hard.

**Comment by unityjeffrey** [comment]
thanks @mattinjersey and @roboserg - we've added this in our backlog to further explore.  thanks for bringing it up
