### ISSUE TITLE
Discrete or continuous

### ISSUE THREAD

**Issue by MrGitGo** [Unity-Technologies/ml-agents#2029]
I am not sure which one I should pick. I trained with descrete before but I read, when the agent has more complex movements or problems to solve, i should select continuous. 
I have a shooter game, where the agents can shoot and move around. So what would be suitable discrete or continuous?

**Comment by roboserg** [comment]
Think about how a human would control an agent. Can a human control an agent with discrete? Yes, we do it by playing on a keyboard. So yes, you can use discrete, it will train faster, since fewer parameters (actions space is much much less).

**Comment by xiaomaogy** [comment]
@ervteng

**Comment by harperj** [comment]
Hi all -- this issue has been inactive for some time so I'm going to close it.  Feel free to reopen or create a new issue if you have more to discuss.
