### ISSUE TITLE
I am writing a blog about my experience

### ISSUE THREAD

**Issue by Fangh** [Unity-Technologies/ml-agents#203]
I hope you have some fun with ML-agent because I do. I wanted to share my blog in which I explain what I did to have a working ML-agent and the issues I faced and how I resolved them.

https://brickbreaker-ai.tumblr.com/

**Comment by Aarsh-Singh-Vishen** [comment]
Hmm helped me out quite a bit. Bookmarked :)

**Comment by awjuliani** [comment]
Very nice!

**Comment by MDReptile** [comment]
@Fangh It would be great if you could write up a how-to post for getting the CPU based tensorflow going instead of the GPU based tensorflow shown in the tutorial video.

Cool blog!

**Comment by mmattar** [comment]
Folks, closing the issue as it has been inactive for 30 days. Feel free to reopen to continue the discussion of anything else comes up.
