### ISSUE TITLE
Unable to train 3D ball

### ISSUE THREAD

**Issue by Kadarach** [Unity-Technologies/ml-agents#2031]
I'm unable to train the 3Dball example because the brain type don't showed up in the inspector.
Even if I drag the .nn pretrained file in the model and press play nothing happen, the balls fall on the ground. Control is tick in the Academy.
I'm using Python 3.6
ML-agents 0.8.1
Unity 2019.1.1f1

I have this error too:
![Capture](https://user-images.githubusercontent.com/25883677/57585754-ade3c480-74ec-11e9-8c97-0f00fd0f6882.PNG)
Here is my inspector on 3DBallLearning:
![Capture2](https://user-images.githubusercontent.com/25883677/57585765-df5c9000-74ec-11e9-9661-476bc6e3daf7.PNG)
Here is my inspector on Ball3DAcademy:
![image](https://user-images.githubusercontent.com/25883677/57585824-a53fbe00-74ed-11e9-8561-93a19a221abb.png)

And the player settings: 
![Capture3](https://user-images.githubusercontent.com/25883677/57585770-e97e8e80-74ec-11e9-89f5-d821382bb1cc.PNG)

The only related issue I've found is : https://stackoverflow.com/questions/47502739/brain-type-internal-not-showing-unity3d

But TensorFlow plugin is not necessary, there is Inference Engine since 0.7.0 so I didn't put ENABLE_TENSORFLOW.

**Comment by roboserg** [comment]
I had that problem. If everything else fails - restart Unity and the cmd console.

**Comment by ervteng** [comment]
Hi @Kadarach, for training you don't need the .nn file. You have to use mlagents-learn on the CMD first, then hit the play button, otherwise you'll get that error.

For inference mode (with the .nn file, no training) uncheck the control box, and it should work.

**Comment by Kadarach** [comment]
> For inference mode (with the .nn file, no training) uncheck the control box, and it should work.
>
This worked, thanks !

>Hi @Kadarach, for training you don't need the .nn file. You have to use mlagents-learn on the CMD first, then hit the play button, otherwise you'll get that error.
>
But I still can't change the brain type in order to train it. 
![Capture](https://user-images.githubusercontent.com/25883677/57727309-719d9900-7691-11e9-8b47-aa84664958bf.PNG)

**Comment by kakimochi** [comment]
I'm in the same situation with "Unity 2018.3.14f1".
I suspect that Unity - Python communication was not established.
I'm wonder how I can check this.
