### ISSUE TITLE
Possible problem with window instructions for "Learning-Environment-Executable.md"

### ISSUE THREAD

**Issue by ParkerShamblin** [Unity-Technologies/ml-agents#2033]
Please refer to: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Executable.md

"6. Click Build:
-  In the File dialog, navigate to your ML-Agents directory.
- Assign a file name and click Save.
- **(For Windows）With Unity 2018.1, it will ask you to select a folder instead of a file name. Create a subfolder within the ML-Agents folder and select that folder to build.** In the following steps you will refer to this subfolder's name as env_name."

After following the instructions in bold, I received the following error: "UnityEditor.BuildPlayerWindow+BuildMethodException: Building to the Assets folder is not allowed."

I tested creating the sub folder in the UnitySDK directory instead and it worked without a hitch.

All the best,
Parker

**Comment by unityjeffrey** [comment]
Hi @ParkerShamblin - thank you for pointing that out.  I've created a PR to update the documentation. https://github.com/Unity-Technologies/ml-agents/pull/2037
