### ISSUE TITLE
Can I run this project on a laptop with AMD Radeon GPU?

### ISSUE THREAD

**Issue by GuruLahima** [Unity-Technologies/ml-agents#204]
I have an amd radeon GPU, but the installation setup asks for CUDA. How can I make this work, or is it not meant to work on amd?

**Comment by Fangh** [comment]
Yes you can. Don't install CUDA. And instead of installing "tensorflow-gpu" install "tensorflow"

**Comment by GuruLahima** [comment]
Yes I found out about it only after posting this :D but still a bit odd that Unity is linking a post that goes on about  CUDA toolkit and CUDNN for half of its content as if its an official documentation. Thanks though, puts my mind at ease :)
