### ISSUE TITLE
Done() is not done after several steps afterwards

### ISSUE THREAD

**Issue by roboserg** [Unity-Technologies/ml-agents#2040]
So if you have a simple code of:

```
if (pos.y > 10)
  AddReward(100);
  Done();
```

You would expect to have a reward of 100 and the episode should end since we call Done(). What happens is ` AddReward(100); `gets called several more times. It sounds like a bug to me and it also makes training very hard, since rewards are added wrong and randomly

In the video, you can see the reward bottom right and the console output - https://puu.sh/Ds4Hr/921c0fbd74.mp4

The code that prints the console etc https://puu.sh/Ds4HA/ec8fde8d29.png

I had also the SAME behavior in completely another project. 

p.s. more proof:

https://puu.sh/Dquh3/1a9785e691.png or video - https://puu.sh/Dqufs/9eada1fae3.mp4

I am logging the reward in the AgentAction like this - https://puu.sh/DquhI/2e16286c1b.png

The agent should only get -1 as a reward for falling down and not -3. Its as if the Unity is lagging and not registering the position < 0 immediately.

**Comment by tjad** [comment]
Perhaps make sure that multiple agents don't exist - and if multiple agents exist, that they all call Done()
Perhaps put an if statement asserting not IsDone()  
`if(!IsDone()) { 
  //Add reward
}
`

I can't tell what your Academy, Brain, Agent configuration is from the imagery.

**Comment by roboserg** [comment]
I only have one agent with one brain - https://puu.sh/Ds6JV/2b7974cd6d.png + https://puu.sh/Ds6K3/0f19aef049.png

**Comment by tjad** [comment]
If you add the `IsDone()` check, does the error go away at least  ?
- understand it's not ideal for intuition

**Comment by roboserg** [comment]
like this?

Done();
if(IsDone())
   AddReward(200)

**Comment by tjad** [comment]
Would have to negate that 

`if( ! IsDone())`

And the reward would never be added in that sequence of code - Done is always called before the the IsDone() check

**Comment by roboserg** [comment]
> And the reward would never be added in that sequence of code - Done is always called before the the IsDone() check

Are you sure? I have it like this and I see the reward.

**Comment by tjad** [comment]
Yes, what I mean is, that if statement is the same as doing

`if(true)`

It's always true as the code executed just set done=true, hence IsDone() will return `true`

**Comment by tjad** [comment]
In your rocket example, there are 2 places a reward is added, but only 1 where the `Done()` is called (after it receives a negative reward)

**Comment by tjad** [comment]
So add the 
`if( ! IsDone())` check to the first if statement  (assuming this is when the reward was intended to be given)

**Comment by tjad** [comment]
Apologies, that's the ball example https://puu.sh/DquhI/2e16286c1b.png

**Comment by roboserg** [comment]
@tjad your workaround with checking IsDone worked, but its messy and still seems like a bug. The agent does  2-10 steps after Done() is called before finally ending the episode.

For the Ball example is by design, I only end an episode after the agent falls down (game over)

**Comment by tjad** [comment]
Cool, glad some progress is made. I am not entirely familiar with the Unity Editor - yet-, but what the code is saying, is that there are more agents registered within your environment.

The image sent of the Unity Editor config looks sort of like there are nested agents ? Not sure though, hopefully somebody can confirm.

**Comment by roboserg** [comment]
Academy has an agent and the player brain. And there is only one agent with the script agent attached. What would make you say there are more?

**Comment by tjad** [comment]
The behaviour of the environment. The Academy will run until *all* agents are "done"

**Comment by roboserg** [comment]
Sure, but I only have one agent in the scene

**Comment by tjad** [comment]
I do hear what you're saying regarding how you've intended your configuration. Might be a bug, but more likely a config problem - as there are multiple working examples provided with ml-agents

**Comment by tjad** [comment]
You should be able to debug log the number of agents and brains within the academy - that should clear up as to whether it is a bug or not

**Comment by roboserg** [comment]
Workaround is 
if ( ! isDone()) { }

Will close since I cant reproduce it 100% of the time, but it happens from time to time.
