### ISSUE TITLE
Change Brain model on script runtime 0.8.1

### ISSUE THREAD

**Issue by DannyFriky** [Unity-Technologies/ml-agents#2046]
Hi, I'm doing a game with different levels of difficulty, depending on models trained differently, I've seen that I can change the brain from the script with MLAgents.brain but I have not seen how to change the model of a brain, is it currently possible? but my solution is to create different brains and assign to each one the model that I want to use.

Thanks for your attention.

**Comment by xiaomaogy** [comment]
Yes that's also how we do it (create different brains). You can see how we did it in walljump example environment. @DannyFriky

**Comment by DannyFriky** [comment]
Thanks you so much ^^
