### ISSUE TITLE
Tensorflow Lite support

### ISSUE THREAD

**Issue by decoybitch** [Unity-Technologies/ml-agents#2050]
Do you guys plan to include tensorflow lite support in Barracuda in near future?

**Comment by xiaomaogy** [comment]
@mantasp

**Comment by mantasp** [comment]
@decoybitch no such plans at the moment.

**Comment by ayaz-amin** [comment]
There already seems to be a TFLite plugin by the Tensorflow team themselves [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/examples/unity/TensorFlowLitePlugin/). Keep in mind though that it has only been tested on Linux and is experimental.
