### ISSUE TITLE
how can i convert h5 from keras to bytes ?

### ISSUE THREAD

**Issue by khailArt** [Unity-Technologies/ml-agents#2053]
hello guys i'am new to tensorflow and i just retrained a simple cnn model and i want to export it to unity , i found this code online but i have no idea about this error :/
thank you very much for the help
![Untitled-2](https://user-images.githubusercontent.com/50366122/57918174-bdb12f00-7885-11e9-8379-1ab4a0b7a1e4.png)

also tried this method but i can't convert to json
![aa](https://user-images.githubusercontent.com/50366122/57918189-c3a71000-7885-11e9-8aca-dddc1f874481.png)

**Comment by xiaomaogy** [comment]
This code doesn't seem to be related to ml-agents...I understand you want to use a model you trained inside Unity @mantasp

**Comment by mantasp** [comment]
This seems to be issues with Keras/TF tools and not directly related to Unity, I would like to suggest reaching out Keras/TF maintainers.

**Comment by khailArt** [comment]
yes actually i had to freeze the model and save it as .pb not h5 , then
convert it from .pb to bytes :)
