### ISSUE TITLE
Tensorflow speech recognizer sample not properly converting to barracuda format

### ISSUE THREAD

**Issue by Amanpradhan** [Unity-Technologies/ml-agents#2056]
I am trying to convert tensorflow audio recognition model into barracuda format but 3 ops are being ignored and some are skipped as pattern is too long. I am using the development branch : develop-barracuda-0.2.0

Tensorflow link - https://www.tensorflow.org/tutorials/sequences/audio_recognition
Model link - http://download.tensorflow.org/models/speech_commands_v0.02.zip
Logs : 
python tensorflow_to_barracuda.py /home/aman/Downloads/conv_actions_frozen.pb  nn
IGNORED: DecodeWav unknown layer
IGNORED: AudioSpectrogram unknown layer
IGNORED: Mfcc unknown layer
IN: 'wav_data': [] => 'Reshape'
OUT: 'labels_softmax'
DONE: wrote nn/conv_actions_frozen.bc file.

**Comment by xiaomaogy** [comment]
@mantasp

**Comment by mantasp** [comment]
@Amanpradhan unfortunately these operations aren't supported by Barracuda and we have no near term plans for them. Here is rough list of what we support for Ops:
```
Dense
MatMul
BiasAdd
Conv2D
DepthwiseConv2dNative
Conv2DBackpropInput
Pad
ResizeNearestNeighbor
ResizeBilinear
ResizeBicubic
MaxPool
AvgPool
GlobalAveragePool
GlobalAvgPool
Activation
BatchNormalization
FusedBatchNorm
BatchNormalizationRuntime
InstanceNormalization
LRN
RandomStandardNormal
RandomUniform
Multinomial
OneHot
Add
Sub
Mul
RealDiv
Pow
Minimum
Maximum
Max
Mean
Min
Prod
Sum
Flatten
Reshape
Concat
StridedSlice
Nop
```
And here is a list of activations we support:
```
Linear
Relu
Softmax
Tanh
Sigmoid
Elu
Relu6
LeakyRelu
Selu
Swish
LogSoftmax
Softplus
Softsign
Abs
Neg
Ceil
Floor
Sqrt
Exp
Log
Acos
Acosh
Asin
Asinh
Atan
Atanh
Cos
Cosh
Sin
Sinh
Tan
```
