### ISSUE TITLE
Ball3DAcademy loads in my custom agent training HELLLP!

### ISSUE THREAD

**Issue by Aarsh-Singh-Vishen** [Unity-Technologies/ml-agents#206]
Hi guys,
So my executables name is numberdemo1 and the brain in that is called "Brains" (original I know),but the problem is that instead of that all I can get to load is the Ball3DAcademy no matter how many times I start a new project HELP!!
![image](https://user-images.githubusercontent.com/31087556/34327646-97b69b6c-e904-11e7-822b-8e18c6abd6cb.png)

**Comment by MarcoMeter** [comment]
Hi @Aarsh-Singh-Vishen 

make sure that you have the selected the right scene for your build.

![settings](https://user-images.githubusercontent.com/6996955/34327662-64f3bf78-e8ca-11e7-9231-6852e689ca56.png)

 I suspect that the example scene of the 3D Ball Example is indexed as 0.

**Comment by Aarsh-Singh-Vishen** [comment]
Wo! Thanks for the amazingly quick reply :) . I'll check it out and get back to you !

**Comment by Aarsh-Singh-Vishen** [comment]
You were right thanks !!!
