### ISSUE TITLE
Possible to load .nn file into Tensorboard?

### ISSUE THREAD

**Issue by DVonk** [Unity-Technologies/ml-agents#2062]
I'm not familar with Tensorboard at all, so excuse me if this is a stupid question. But since the .nn file is a Tensorflow data graph, is it somehow possible to load this into the 'Graphs' tab from Tensorflow and see the network visualization from there?

**Comment by IanSwire** [comment]
I am not sure if this totally answers your question, but the documentation has a section on connecting to Tensorboard. From the looks of it, it gives you a graphical UI to display how the training session went.
I have provided the link for convince: https://bit.ly/30ydqry

**Comment by DVonk** [comment]
> 
> 
> I am not sure if this totally answers your question, but the documentation has a section on connecting to Tensorboard. From the looks of it, it gives you a graphical UI to display how the training session went.
> I have provided the link for convince: https://bit.ly/30ydqry

Thank you, but that's not what I'm looking for. I'm already observing the training in Tensorboard. I'm looking to get the actual .nn file into there to get the data graph visualization: https://www.tensorflow.org/tensorboard/r1/graphs

**Comment by xiaomaogy** [comment]
@DVonk Yes that's possible, you just need to change the python code yourself to write out the graph file, then visualize it using tensorboard.

**Comment by strikeman1** [comment]
have you solved the problem?

**Comment by surfnerd** [comment]
Hi @strikeman1,
If you'd like to quickly visual the network you can also grab the .pb file and use this tool https://github.com/lutzroeder/netron
