### ISSUE TITLE
Installation of mlagents python package failed

### ISSUE THREAD

**Issue by danksky** [Unity-Technologies/ml-agents#2065]
During the installation of ml-agents, I ran
`pip3 install mlagents`
Which failed with the following message:
`  Could not find a version that satisfies the requirement tensorflow==1.7.1 (from mlagents) (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 2.0.0a0)
No matching distribution found for tensorflow==1.7.1 (from mlagents)`

I followed [an Issue to this post](https://github.com/tensorflow/tensorflow/issues/9680#issuecomment-407278974), changed **0.12.0 --> 1.7.1** and FUTILY ran the following:

`python3 -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.7.1-py3-none-any.whl`

which evoked the following **error** response:
`AttributeError: module 'pip' has no attribute 'main'`

So, instead, I ran this:
`pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.7.1-py3-none-any.whl`
which worked!

**Comment by vincentpierre** [comment]
Were able to install mlagents or are you still facing an issue?

**Comment by danksky** [comment]
Just posting in case anyone else ran across the same issue. It's installed.

**Comment by antisquark** [comment]
Thanks for this.

**Comment by MajidMoghadam** [comment]
awesome...helped me out ;)

**Comment by hale445566** [comment]
Thanks, help me a lot!

**Comment by ineooh** [comment]
hey, thanks a lot

**Comment by praveenswamy65** [comment]
Thank you for this comment, It helped !!!

**Comment by Rahul1947116** [comment]
Thank you so muchhh !!
