### ISSUE TITLE
Cannot run mlagents-learn: "zsh: command not found: mlagents-learn"

### ISSUE THREAD

**Issue by danksky** [Unity-Technologies/ml-agents#2066]
I was able to successfully install mlagents, but, following the [Basic Guide](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Basic-Guide.md), I was unable to run 
`mlagents-learn config/trainer_config.yaml --run-id=firstRun --train`
because I got the following error:
`command not found: mlagents-learn`

**Comment by vincentpierre** [comment]
Hi @danksky Can you try closing and reopening a terminal. Sometimes after installing you need to close the terminal so the `mlagents-learn` endpoint registers.

**Comment by danksky** [comment]
@vincentpierre 
That didn't work for me.

**Comment by vincentpierre** [comment]
Can you try `pip3 show mlagents` and post the message that is displayed ?

**Comment by danksky** [comment]
Hi @vincentpierre sorry the Unity-Technologies organization was down last night, so I couldn't post. 

`➜  ~ pip3 show mlagents`
`Name: mlagents`
`Version: 0.4.0`
`Summary: Unity Machine Learning Agents`
`Home-page: https://github.com/Unity-Technologies/ml-agents`
`Author: Unity Technologies`
`Author-email: ML-Agents@unity3d.com`
`License: Apache License 2.0`
`Location: /usr/local/lib/python3.7/site-packages`
`Requires: docopt, pyyaml, grpcio, protobuf, numpy, jupyter, pytest, tensorflow, matplotlib, Pillow`
`Required-by:`

**Comment by vincentpierre** [comment]
Ok, I thought you were on v0.8. Since you are using v0.4, you need to either update or look at the [documentation for the right version](https://github.com/Unity-Technologies/ml-agents/blob/0.4.0/docs/Training-ML-Agents.md#training-with-learnpy).
In your case, you need 

```
python3 learn.py ../../projects/Cats/CatsOnBicycles.app --run-id=cob_1 --train
```

**Comment by danksky** [comment]
That did the trick to get rid of the issue driving this thread 👍 (unfortunately encountered another 👎 ). Thanks!

**Comment by Berenice2018** [comment]
Hello @vincentpierre , 
I am also getting this error message: 
`command not found: mlagents-learn`

I have just installed ML Agents and restarted the Terminal, I am on MacOS Mojave. 
After `pip3 show mlagents` , the following is printed:
`administrator ~ $ pip3 mlagents-learn --help
ERROR: unknown command "mlagents-learn"
administrator ~ $ pip3 show mlagents
Name: mlagents
Version: 0.9.0
Summary: Unity Machine Learning Agents
Home-page: https://github.com/Unity-Technologies/ml-agents
Author: Unity Technologies
Author-email: ML-Agents@unity3d.com
License: UNKNOWN
Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requires: matplotlib, numpy, pytest, jupyter, docopt, mlagents-envs, protobuf, tensorflow, grpcio, pyyaml, Pillow` 

It would be great, if you could help me with this problem. Many thanks in advance!
