### ISSUE TITLE
Proposal: trainer_controller should always increment step+reward regardless of training mode flag

### ISSUE THREAD

**Issue by tjad** [Unity-Technologies/ml-agents#2073]
Proposing that the trainer_controller now always increments a step regardless of training mode flag ( --train )

This will allow writing to tensorboard for an evaluation with more useful data. Currently as the step never increments all values are recorded to step 0  (this is a bug in my opinion). In fact it could be that during eval it should never write to the board. However, then thought perhaps summary should always be written to tensorboard, regardless of --train flag. This would mean that incrementing the step should always be done. 

This introduces a new feature, and required documentation. It would then be expected that the checkpoint and model data be copied to a new folder within the models, so as to write summary values to a new series.

Seems useful? What does the community think ?

I've got the patch ready, it's a simple change.

**Comment by vincentpierre** [comment]
Hi, 
We were considering these steps as training steps. We decided not to increment at inference time so that the step count would not be changed if the user tries to see how the model performs (inference) before resuming training. 
It is an interesting question and maybe we should reconsider this. If you can make a PR with your commit, we will evaluate it.

**Comment by tjad** [comment]
Hi @vincentpierre 

Apologies for the delay - this proposal was made during a time where I was quite busy

Thanks for your feedback. I'll re-access the code base, and reconfirm my thoughts. I do see quite a bit has changed in ml-agents since this proposal.
Perhaps you guys had some considerations in the interim as well.

**Comment by surfnerd** [comment]
Hi @tjad,
Thanks for you interest and feedback to ML-Agents.  This issue has been inactive for a while and we will close this issue.  Please reopen it if you have more information to share or a PR related to your request.
