### ISSUE TITLE
KeyError: '<3DBallPlayer>'

### ISSUE THREAD

**Issue by mnsmuts** [Unity-Technologies/ml-agents#2079]
This seems like a really obvious problem but I can't find the source -

Windows 10, setup with a fresh environment created with conda 3.5.1

The 3DBall example setup with only 2 platforms active, one a learner brain with control checked in the academy and the other a player brain.

All starts well and then online_trainer.py has a fit because it can't find the brain error code below. This seems like a simple setup issue but after reinstalling and following all the instructions plus running the unity environment from different places, I am at a loss.

Anyone any ideas?

Mike

============== error message ======================
(ml-agents) C:\Users\Michi\ml-agents>mlagents-learn online_bc_config.yaml --train --slow

                        ▄▄▄▓▓▓▓
                   ╓▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
          ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
          ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓▌
                        ¬`▀▀▀█▓

INFO:mlagents.trainers:{'--base-port': '5005',
 '--curriculum': 'None',
 '--debug': False,
 '--docker-target-name': 'None',
 '--env': 'None',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--no-graphics': False,
 '--num-envs': '1',
 '--num-runs': '1',
 '--run-id': 'ppo',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': True,
 '--train': True,
 '<trainer-config-path>': 'online_bc_config.yaml'}
c:\users\michi\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py:141: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  trainer_config = yaml.load(data_file)
INFO:mlagents.envs:Start training by pressing the Play button in the Unity Editor.
INFO:mlagents.envs:
'Ball3DAcademy' started successfully!
Unity Academy name: Ball3DAcademy
        Number of Brains: 2
        Number of Training Brains : 1
        Reset Parameters :

Unity brain name: 3DBallLearning
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 8
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): [2]
        Vector Action descriptions: ,
Unity brain name: 3DBallPlayer
        Number of Visual Observations (per agent): 0
        Vector Observation space size (per agent): 8
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): [2]
        Vector Action descriptions: ,
2019-05-26 20:13:34.082908: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
INFO:mlagents.envs:Hyperparameters for the Imitation Trainer of brain 3DBallLearning:
        brain_to_imitate:       <3DBallPlayer>
        batch_size:     64
        time_horizon:   64
        summary_freq:   1000
        max_steps:      5.0e4
        batches_per_epoch:      10
        use_recurrent:  False
        hidden_units:   128
        learning_rate:  0.0003
        num_layers:     2
        sequence_length:        32
        memory_size:    256
        model_path:     ./models/ppo-0/3DBallLearning
Traceback (most recent call last):
  File "c:\users\michi\anaconda3\envs\ml-agents\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\michi\anaconda3\envs\ml-agents\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Michi\Anaconda3\envs\ml-agents\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>
  File "c:\users\michi\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 262, in main
    run_training(0, run_seed, options, Queue())
  File "c:\users\michi\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 95, in run_training
    tc.start_learning(env, trainer_config)
  File "c:\users\michi\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 218, in start_learning
    new_info = self.take_step(env, curr_info)
  File "c:\users\michi\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 291, in take_step
    take_action_outputs[brain_name])
  File "c:\users\michi\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\bc\online_trainer.py", line 57, in add_experiences
    info_teacher = curr_info[self.brain_to_imitate]
KeyError: '<3DBallPlayer>'

**Comment by mnsmuts** [comment]
I should have said in the description:
Using ml-agents 0.8
The online trainer does not seem to find the [self.brain_to_imitate]

**Comment by DooblyNoobly** [comment]
@mnsmuts what did you do to resolve this?

**Comment by mnsmuts** [comment]
it was an error in the online_bc file probably caused by me messing around with the configurations. Fresh file from the new dist v0.9 and all seems to be fine. M
