### ISSUE TITLE
Agents are not learning properly

### ISSUE THREAD

**Issue by MrGitGo** [Unity-Technologies/ml-agents#2081]
I have described my game here: https://github.com/Unity-Technologies/ml-agents/issues/2061

So I put the agents incrementally in the game (1st phase: 1 vs 1, 2nd 2 vs 2, ..). I did this until 3 vs. 3 and I was at step 9 million. After a while I made the observation, that I am getting mean rewards: 0.0 and std rewards: 0.0. And that the whole time. When I changed the spawnpoints I had again sometimes positive rewards and sometimes negative. I realised when the agents avoid each other and don't kill anyone they get the 0.0 reward. Maybe I am doing it wrong with the 3 vs. 3 agents.

My main goal is, after I successfully trained the agents, to play with one character vs. 3 other agents. So it is 1 human vs. 3 agents. My question is, is it correct to train like that? Should I put 3 agents and one character that is randomly moving and shooting? I could put the agent also one after another. 

The reason why I have 3 vs 3 agents is, that I thought, that it would be better for the training. The more agents I have the better and faster they would train. But I failed at this I guess. So how and what should I do next to reach my goal? The last thing my agents were doing was to avoid each other until I changed the spawnpoints. But I guess after a while they will avoid each other again. I guess it is because of the rewards: when one agent is killing an other, the one will get positive reward and the other negative. And both are connected to one brain. So in order to get no negative reward, they try to avoid each other.

**Comment by unityjeffrey** [comment]
hi @MrGitGo - can you put your comment into [#2061](https://github.com/Unity-Technologies/ml-agents/issues/2061)?  it'll be better to have the discussion instead of branching.  closing for now
