### ISSUE TITLE
The associated scirpt can not be loaded.

### ISSUE THREAD

**Issue by jackwrx** [Unity-Technologies/ml-agents#2092]
No MonoBahaviour scripts in the file. or their names do not match the file name.
![ML-Agents Error](https://user-images.githubusercontent.com/15922736/58690852-17087a80-83bd-11e9-82fe-267831cc4bae.PNG)

Thanks all!

**Comment by jackwrx** [comment]
Hi jeffrey:
              I reload the unity and the issue solved. 

Jack

**Comment by unityjeffrey** [comment]
thanks @jackwrx - closing this as it is resolved.
