### ISSUE TITLE
Possible bug in RayPerception3D endOffset

### ISSUE THREAD

**Issue by SungbinChoi** [Unity-Technologies/ml-agents#2095]
https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Examples/SharedAssets/Scripts/RayPerception3D.cs

Hi. 
'endOffset' is described as 'Ending height offset of ray from center of agent', 
so it should be a relative offset value from center of agent.
But in RayPerception3D.cs  line number 36, 
   endPosition.y = endOffset;
it is assigned as absolute y value.
Is this a bug or is it intended?

**Comment by awjuliani** [comment]
Hi @SungbinChoi,

It is indeed a relative value. If you look further in the script, when performing the ray cast, we add the agent position and the endPosition together to define where the sphere cast should be sent.

**Comment by SungbinChoi** [comment]
Hi @awjuliani 
I see. I got it wrong. Thanks.
