### ISSUE TITLE
ML-Agents depended on each other

### ISSUE THREAD

**Issue by Azurnox** [Unity-Technologies/ml-agents#2096]
Hi,
 I'm currently working on a 2D platform ml-agents project, I have an issue that when training multiple agents with the same brain and one of them calls the Agents.Done() method, all the other agents are reset.
Any clue how to fix this issue?

**Comment by mattinjersey** [comment]
I wonder how 3DBall does it, in the examples. They have 9 agents running simultaneously.

**Comment by Azurnox** [comment]
Ye, I copied their settings but still had the same issue.

**Comment by TashaSkyUp** [comment]
lets see your agent code.

**Comment by rsfutch77** [comment]
What exactly did you copy? Each agent has a "training area" game object that contains its environment in the 3DBall example. The training area is a prefab that is instantiated multiple times. I tried this with this example and it worked just fine. 
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md

**Comment by Azurnox** [comment]
Hi, thanks a lot your help and sorry I have bothered you. It turned out to be a silly mistake, the condition which called the Agent.Done() method was static.

**Comment by mattinjersey** [comment]
by the way does anyone have thoughts on when to use multiple environments to speed up training? I think in some examples, multiple environments would not help.
Perhaps its just works for the case where there is a small amount of data being sent, like in 3dBall.
