### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGALRM'

### ISSUE THREAD

**Issue by Demonweb** [Unity-Technologies/ml-agents#21]
I get the following error when running the  Jupyter Notebook step.
This happens in PPO and Basic versions.
I have windows 10 and latest unity 2017.2.0b6 Personal

The Game opens up and the balls drop, but the tables do not move.
The brain is set to external.

I build the unity environment  and put the .exe here : ....\ml-agents-master\python

ppo.py
setup.py
3DBall.exe
3DBall_data
-------------
here is what I updated in the Jupyter Notebook

### General parameters
max_steps = 10000 # Set maximum number of steps to run environment.
run_path = "ppo" # The sub-directory name for model and summary statistics
load_model = False # Whether to load a saved model.
train_model = True # Whether to train the model.
summary_freq = 10000 # Frequency at which to save training statistics.
save_freq = 50000 # Frequency at which to save model.
env_name = "3DBall" # Name of the training environment file.

---------------------------

ERROR MESSAGE
==================
Load the environment
In [3]:

env = UnityEnvironment(file_name=env_name)
print(str(env))
brain_name = env.brain_names[0]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-48ea1f1caab6> in <module>()
----> 1 env = UnityEnvironment(file_name=env_name)
      2 print(str(env))
      3 brain_name = env.brain_names[0]

C:\Users\mpliszka\Documents\UnityProjects\ml-agents-master\python\unityagents\environment.py in __init__(self, file_name, worker_id, base_port)
     86                     str(file_name)))
     87 
---> 88         old_handler = signal.signal(signal.SIGALRM, timeout_handler)
     89         signal.alarm(30)  # trigger alarm in x seconds
     90         try:

AttributeError: module 'signal' has no attribute 'SIGALRM'

**Comment by awjuliani** [comment]
Hi @Demonweb,

Sorry you encountered this issue. It has been fixed in master (see https://github.com/Unity-Technologies/ml-agents/pull/9). Please try downloading the newer package, and let me know if the issue persists.
