### ISSUE TITLE
Proper way to use agent in Unity after training with external Python API

### ISSUE THREAD

**Issue by batu** [Unity-Technologies/ml-agents#2116]
Hello, 

I am currently using my own implementation of SAC to train my agents through the openAI Unity wrapper instead of going through the notebooks.

The pipeline is working nicely when the agent is driven externally through python, however I want to be able to put my agents inside Unity.

I am currently looking at the `export_model` function in `policy.py`. However, due to using a different architecture I do not have the same `possible_output_nodes`. 

Is the only way I can get the .nn to have my network tensor names mimic the given in ml-agents or is there any other cleaner method? If not, is there place where I can look at the contract for the NN instead of trying to put it together from the code?

thank you very much and thank you for the great library

**Comment by harperj** [comment]
Hi @batu -- unfortunately we don't provide support at this time for using networks built with other trainers with ML-Agents inference.  You're right that you would need to change your network to mimic the one that we use or write some sort of wrapper.  We don't have a spec at this time for the network structure but I agree that it would be useful in the future.

**Comment by batu** [comment]
Thank you for your response--thats fair.

I will keep an eye out for the specs as it will make it easier to bundle and share more custom models!
