### ISSUE TITLE
Reward on reset/done

### ISSUE THREAD

**Issue by stalkermustang** [Unity-Technologies/ml-agents#212]
Hello. I use this for training my agent:

`
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MyAgent : Agent 
{

	[Header("Specific to MyGame")]
	public List<GameObject> walls = new List<GameObject>();
	Vector3 prev_coord;
	Vector3 cur_coord;
	float dist;

	public override List<float> CollectState()
	{
		List<float> state = new List<float>();

		for(int i = 0; i < walls.Count; i++)
		{
			state.Add(Vector3.Distance(walls[i].GetComponent<Transform>().position, gameObject.GetComponent<Transform>().position)/50.0f - 1.0f);
		}
		state.Add(Mathf.Abs(gameObject.GetComponent<Rigidbody>().velocity.x / 10.0f)-1.3f);
		state.Add(Mathf.Abs(gameObject.GetComponent<Rigidbody>().velocity.z / 10.0f)-1.3f);
		state.Add(gameObject.GetComponent<Rigidbody>().velocity.magnitude / 15.0f - 0.9f);
		state.Add(gameObject.GetComponent<Transform>().rotation.y);
		return state;
	}

	public override void AgentStep(float[] act)
	{
		int cur_act = Mathf.FloorToInt(act[0]);
		switch(cur_act)
		{
			case 0:
				gameObject.GetComponent<Rigidbody>().velocity -= transform.forward * 1.1f;
				break;
			case 1:
				gameObject.GetComponent<Rigidbody>().velocity += transform.forward * 0.9f;
				reward += -0.00075f;
				break;
			case 2:
				gameObject.transform.Rotate(0.0f, -5.0f, 0.0f);
				reward += -0.002f;
				break;
			case 3:
				gameObject.transform.Rotate(0.0f, 5.0f, 0.0f);
				reward += -0.002f;
				break;
			default:
				break;
		}
		cur_coord = gameObject.transform.position;
		dist = Vector3.Distance(cur_coord, prev_coord);
		reward += (dist / 120.0f);
		prev_coord = gameObject.transform.position;
		Debug.Log(CumulativeReward);
	}
	private void OnCollisionEnter(Collision collision)
	{
		if (collision.gameObject.tag == "wall")
		{
			Debug.Log("OOPS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
			reward += -1.0f;
			gameObject.transform.position = new Vector3(0.0f, 0.0f, 0.0f);
			gameObject.GetComponent<Rigidbody>().velocity = new Vector3(0.0f, 0.0f, 0.0f);
			prev_coord = new Vector3(0.0f, 0.0f, 0.0f);
			cur_coord = new Vector3(0.0f, 0.0f, 0.0f);
			done  = true;
		}
	
	}
	public override void AgentReset()
	{
		gameObject.transform.position = new Vector3(0.0f, 0.0f, 0.0f);
		gameObject.GetComponent<Rigidbody>().velocity = new Vector3(0.0f, 0.0f, 0.0f);
		prev_coord = new Vector3(0.0f, 0.0f, 0.0f);
		cur_coord = new Vector3(0.0f, 0.0f, 0.0f);
		Debug.Log("HOW ARE YOU, HUH?????????????????????????");
		Debug.Log(CumulativeReward);
	}
}`
but in console i see:
![image](https://user-images.githubusercontent.com/26546178/34363083-fcd92ccc-ea89-11e7-8989-29b7b6db115b.png)
ResetOnDone is turned on. I think the reward does not count the previos iteration -> agent doesn't know, for that he was fined
I try set a bool flag in OnCollisionEnter, and in agentstep check flag and  decrement reward (-=1.0f) if he was active(true). 
Still did not work - after training agent just accelerates and crashes into the wall

**Comment by stalkermustang** [comment]
https://pastebin.com/J2tbHg8C
![image](https://user-images.githubusercontent.com/26546178/34363633-f33d1584-ea8e-11e7-8587-c02763d1d23f.png)

**Comment by kwea123** [comment]
Maybe you should set every reward in `AgentStep` ? Like 
```
 if (colls.Count>0)
        {
            done=true;
            reward = -1.0f; //add reward here instead of in OnCollisionEnter()
            colls = new List<GameObject>();
        }
```
and as far as I understand, you can just use `reward = ` instead of `+=` or `-=` (as suggested in the documentation and the example codes), don't know if that makes any difference.

**Comment by stalkermustang** [comment]
@kwea123 i try this one(in step) too. Nope, not working. 
reward - float number, =0 on begin step. I can write -= and += and they correct working. 

I think, problem in libary(see 'bug' issues on second page this repo, month ago) - on done current reward not + to CumReward. And + to next "round" reward(on step 2 i fave cumRew -0.97).

sorry for Eng

**Comment by stalkermustang** [comment]
Hey @atamahjoubfar ! Can you comment this? This is bugor I armless?And can we count on fix this before ML-challenge ends?

**Comment by atamahjoubfar** [comment]
I am not sure where this issue is arising from either.

**Comment by vladimiroster** [comment]
Hi @stalkermustang , are you still having trouble with this issue? We'd like to help!

**Comment by stalkermustang** [comment]
Hi @vladimiroster ! I dont know: after get this bug i don't find path to fix & leave unity ML libary. Currently i see 0.3.0 version with reworked system.  I delete scene & sources ;(

**Comment by mmattar** [comment]
Hi @stalkermustang - please upgrade to v0.3 next time you decide to try ML-Agents, several new features and improvements have been made. I'm closing this out and please feel free to create a new issue if you run into any problems.
