### ISSUE TITLE
my Unity project

### ISSUE THREAD

**Issue by mattinjersey** [Unity-Technologies/ml-agents#2126]
Hello guys I made this video showing the project that I made in Unity and trained with ML-Agents.
Hope you will enjoy.
[Matt's youtube video](https://www.youtube.com/watch?v=50oMJ1dNB_o&feature=youtu.be)

**Comment by awjuliani** [comment]
Hi @mattinjersey 

Thanks for sharing this video with the community!

**Comment by mattinjersey** [comment]
sure thanks to you and mlagents team for all your work to make this amazing tool available to us.
