### ISSUE TITLE
Loader is deprecated

### ISSUE THREAD

**Issue by MrGitGo** [Unity-Technologies/ml-agents#2127]
I am running this command: `mlagents-learn config/trainer_config.yaml --run-id=Lernen_1_0 --train --load` and I get this:

```
lib\site-packages\mlagents\trainers\learn.py:141: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  trainer_config = yaml.load(data_file)
```

I looked on the page and there is written that I should run this: `PYTHONWARNINGS=ignore::yaml.YAMLLoadWarning`

or

`yaml.load(input, Loader=yaml.FullLoader)`

which one should I run and will this stop the warning to appear? Or do I have to run other commands?

**Comment by chriselion** [comment]
I actually just made a PR to fix this yesterday: https://github.com/Unity-Technologies/ml-agents/pull/2124 . Should have it merged today and in the next release.

**Comment by unityjeffrey** [comment]
Closing the issue as it appears to have been addressed.

**Comment by chriselion** [comment]
Yeah, forget to close this when 0.8.2 was released - that contains the fix.
