### ISSUE TITLE
Can't find trainer config file

### ISSUE THREAD

**Issue by Datguypotato** [Unity-Technologies/ml-agents#2131]
Hello guys,

I'm following this guide ml-agents/docs/Basic-Guide.md. But I'm stuck on actually training the AI. I looked here more but I can't seem to fix it

`(ml-agents) C:\Users\Gordon Cheung>mlagents-learn config/trainer_config.yaml --run-id=firstRun --train

                        ▄▄▄▓▓▓▓
                   ╓▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
          ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
          ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓▌
                        ¬`▀▀▀█▓

INFO:mlagents.trainers:{'--base-port': '5005',
 '--curriculum': 'None',
 '--debug': False,
 '--docker-target-name': 'None',
 '--env': 'None',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--no-graphics': False,
 '--num-envs': '1',
 '--num-runs': '1',
 '--run-id': 'firstRun',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': False,
 '--train': True,
 '<trainer-config-path>': 'config/trainer_config.yaml'}
Traceback (most recent call last):
  File "d:\anaconda\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 140, in load_config
    with open(trainer_config_path) as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config/trainer_config.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anaconda\envs\ml-agents\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda\envs\ml-agents\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\envs\ml-agents\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>
  File "d:\anaconda\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 262, in main
    run_training(0, run_seed, options, Queue())
  File "d:\anaconda\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 73, in run_training
    trainer_config = load_config(trainer_config_path)
  File "d:\anaconda\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 146, in load_config
    .format(trainer_config_path))
mlagents.envs.exception.UnityEnvironmentException: Parameter file could not be found at config/trainer_config.yaml.`

My yaml file is in D:\Unity project\SpecialIO\config. If there isn't enough information please tell.

**Comment by Datguypotato** [comment]
Update

I copied my config to C:\Users\Gordon Cheung. And it seems to be working but I don't if I should do this

**Comment by awjuliani** [comment]
Hi @Datguypotato 

You are free to copy your trainer config to whatever file you need it to be. As you realized, it is typical to have the config in the working directory that you are using to launch the training.
