### ISSUE TITLE
Decision Interval benefits

### ISSUE THREAD

**Issue by testContributor12** [Unity-Technologies/ml-agents#2132]
What are the actual benefits of using a Decision Interval that is more than 1?

As far as i understand if we assign the Decision Interval to 5 , then it will make 5 different actions, and after they are complete the agent will get the new observations and make another 5 actions.
eg. action1:movetox , action2:rotate and moveY, etc..

I feel like i am wrong somewhere ,because in that case using a Decision Interval of 1 will always lead to a more accurate calculations.

**Comment by mbaske** [comment]
With decision interval set to 5, the agent actually _repeats the same action_ 5 times before making the next decision step. You could implement this behaviour using on-demand-decisions and request a new decision every 5th time the agent's FixedUpdate method executes. Setting the decision interval to greater than 1 is just a convenient way for spreading out decisions without having to write your own interval code. Longer decison intervals can be beneficial if an agent doesn't need updates on every frame, e.g. for deciding which direction to move in.

**Comment by testContributor12** [comment]
I see, thank you very much for the explanation!
