### ISSUE TITLE
Can we use ML algorithms other than PPO in unity mlagents for multi agent like ddpg

### ISSUE THREAD

**Issue by Usmaniatech** [Unity-Technologies/ml-agents#2134]
I want to use multiple algorithms for a multi agent situation including PPO but I can't find any support for other algorithms like DDPG. If it's applicable how can I start working on it, what will be the procedure. How much changes do I have to make in other libraries in PPO.

**Comment by awjuliani** [comment]
Hi @Usmaniatech 

It is possible to extend our training code to include other algorithms. For an example of this, you can see this experimental implementation of Soft Actor Critic: https://github.com/Unity-Technologies/ml-agents/tree/develop-sac/ml-agents/mlagents/trainers/sac/

It is also possible to use ML-Agents environment with any external training code designed to work with the OpenAI gym interface: https://github.com/Unity-Technologies/ml-agents/tree/master/gym-unity

**Comment by Usmaniatech** [comment]
Thanks @awjuliani

**Comment by Usmaniatech** [comment]
I am able to use MADDPG in mlagents 0.4 but it's not working with 0.8.1.

**Comment by harperj** [comment]
Hi all -- this issue has been inactive for some time so I'm going to close it.  Feel free to reopen or create a new issue if you have more to discuss.
