### ISSUE TITLE
Game runs too fast in inference mode in 2018.3.0f2

### ISSUE THREAD

**Issue by sebjf** [Unity-Technologies/ml-agents#2139]
Hi,

In 2018.3.0f2 I see odd behaviour with the Academy and speed. In inference mode the game appears to run "too fast". It is as if FixedUpdate is being called faster than it should be.

When the Academy is disabled (by disabling the GameObject to which it is attached) the problem goes away.

The symptoms are independent of framerate (tested by turning VSync on and off). The Academy timescale and target frame rate settings have no effect on the graphics frame rate or the symptom.

This happens in the UnitySDK project. I have verified by adding a script that prints the period between calls to FixedUpdate to console and see that they are ~0.0085 while they should be 0.02.

(PS. I am assuming its not only 2017 that has official support - I couldn't see  in the docs or main page. Apologies if that's the case!)

**Comment by awjuliani** [comment]
Hi @sebjf 

Can you try removing this line from your `Academy.cs` file, and see if that helps? https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Scripts/Academy.cs#L432

**Comment by sebjf** [comment]
Thank you @awjuliani, that has resolved the issue.
