### ISSUE TITLE
Problems with training

### ISSUE THREAD

**Issue by Higemori** [Unity-Technologies/ml-agents#2140]
I am trying to teach an agent for a simple game. Tank needs to shoot a target. It's happening in only 2 axis space. The tank shoots every 2s with the same power, the only thing agent needs to do is to set the right angle to hit the target. I set 1.0f reward for shooting the target and small penalty for existing 0.0001f. The problem is the agent seems to not care if he gets the reward or not. At the beginning of training he is shooting just fine. Then at some point he just starts shooting floor and looses all interest in hitting target. Or starts shooting air randomly. Can you plz give me any advice?

**Comment by mattinjersey** [comment]
can you show the tensorboard results? does it have the reward increasing, and then decreasing?

**Comment by Datguypotato** [comment]
And how long have you trained the AI for? I had the same issue until I just kept training the AI.

**Comment by awjuliani** [comment]
Hi @Higemori 

Unfortunately the Unity staff do not have the resources to help with specific issues related to implementing ML-Agents in games. Hopefully someone in the community can help. 

That being said, I would ensure that the tank hitting the target ends the episode (i.e. calls `Done()`). If not, then the negative penalty for existing will only confuse the learning agent.

**Comment by mbaske** [comment]
@Higemori Try setting your reward proportional to the distance between the target and the shot's point of impact. The better your agent aims, the higher the reward.

**Comment by mattinjersey** [comment]
Yes mbaske has good idea. because otherwise maybe there will be no rewards and in this case the agent can make no progress.

**Comment by Higemori** [comment]
Thank you all for help. I figured if out. So in order to solve this issue I added a small reward if ball went near the target and also i started to control the angle of rotation to be in range of 90 degree in front of the tank. Agent started to learn just fine.
