### ISSUE TITLE
Use trained model on real tensorflow prediction

### ISSUE THREAD

**Issue by cTatu** [Unity-Technologies/ml-agents#2141]
Hello, brief question. I'm developing a robot so I'm using unity to create a environment so that the simulated robot could train and then use the trained model on the real robot with tensorflow. It's possible to get in some way the model architecture used by unity ml agent so I can reproduce it later on the real robot?

Thank you!

**Comment by awjuliani** [comment]
Hi @cTatu 

You can indeed take the trained model and transport it somewhere else. Our `mlagents-learn` creates both a `.nn` file which can be used to run the model in Unity, as well as a `.pb` file which is just a serialized tensorflow model, and can be transported to any other platform where tensorflow models can be run.

**Comment by cTatu** [comment]
Great, thank you very much!
