### ISSUE TITLE
ML-Agents stucks at training with PPO

### ISSUE THREAD

**Issue by AbdulkadirGul** [Unity-Technologies/ml-agents#2142]
Hello,

When I'm trying to train example projects ml-agents just stucks at: 

![11](https://user-images.githubusercontent.com/46901065/59614519-9a4dfe00-9129-11e9-9d46-8fe88fd66532.png)

And unity stucks too.

I'm using `mlagents-learn config/trainer_config.yaml --run-id=t_1 --train` to start training process.

I'm waiting your help, thank you so much :)

**Comment by awjuliani** [comment]
Hi @AbdulkadirGul 

Your issue seems to be a duplicate of this one: https://github.com/Unity-Technologies/ml-agents/issues/1940. Perhaps the solution presented there is applicable to you here as well.

**Comment by AbdulkadirGul** [comment]
@awjuliani Thank You! :)

in #1940 @jinzhaochaliang answer helped me. I solved problem installing Unity 2019.1.0f2, reinstalling Anaconda and downgraded ML-Agents to v0.8.0
