### ISSUE TITLE
Barracuda IndexOutOfRangeException: Index was outside the bounds of the array. Error when I use Tensorflow Model

### ISSUE THREAD

**Issue by Praptobala** [Unity-Technologies/ml-agents#2143]
I am using Pretrained tensorflow CPM model for pose detection, the model is loading properly and showing the names of input/output layers. But crashing with "IndexOutOfRangeException: Index was outside the bounds of the array" error at the inference API.

Please let me know what would be cause, I found its some upsampling layer issue. But I cant change the model now. Any advice to fix the issue witout tweaking the model?

**Comment by awjuliani** [comment]
Hi @Praptobala 

We currently do not officially support models not trained using our `mlagents-learn` package. That being said, we are looking to expand support to more model types in the future.

@mantasp May also be able to help, as he is one of the lead developers of the inference API.

**Comment by Praptobala** [comment]
Thanks @awjuliani !

@mantasp Could you please help me on this issue? I can even send you the model file to look upon.

Thanks,
Bala

**Comment by mantasp** [comment]
@Praptobala could you please share model (both TF and nn) + sample input?
Thanks

**Comment by Praptobala** [comment]
Hi @mantasp, sorry for late response.

Here's the link of .tflite model: 
https://drive.google.com/open?id=19mG6NgdJXUTyO7FWBB4Uu9IHYq1Y82Ua

Sample input is WebCam feed as scaled down input [1,192,192,3] + output [1, 96, 96, 28]
