### ISSUE TITLE
RuntimeError: CUDA error (10): invalid device ordinal

### ISSUE THREAD

**Issue by Usmaniatech** [Unity-Technologies/ml-agents#2148]
I am using cuda to work on MADDPG and it gives following error:

> CUDA error (10): invalid device ordinal

I am using:

> device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
> #device = "cpu"

to train on cuda. but i get the error.

I have checked:

> torch.cuda.device_count()
> 1

> torch.cuda.is_available()
> True

> torch.cuda.current_device()
> 0

**Comment by awjuliani** [comment]
Hello @Usmaniatech 

This issue is not related to ML-Agents. I would recommend posting in the PyTorch github issues instead.
