### ISSUE TITLE
Error using observations : AttributeError: 'ContinuousControlModel' object has no attribute 'observation_in'

### ISSUE THREAD

**Issue by gerardsimons** [Unity-Technologies/ml-agents#215]
Hey guys,

Hoping you can quickly help me out with this one. I am getting an error when trying to use observations in my custom scene (a boat drone simulator): 

```
Traceback (most recent call last):
  File "ppo.py", line 150, in <module>
    new_info = trainer.take_action(info, env, brain_name, steps, normalize)
  File "ml/ppo/trainer.py", line 60, in take_action
    feed_dict[self.model.observation_in] = np.vstack(info.observations)
AttributeError: 'ContinuousControlModel' object has no attribute 'observation_in'
```

I added the camera resolution to the brain (32x32) and the camera to the agent's observation, so I am not sure what I am doing wrong here?

**Comment by MarcoMeter** [comment]
Hi @gerardsimons 

does the same exception occur if you train the GridWorld example. GridWorld uses one observation.

**Comment by gerardsimons** [comment]
@MarcoMeter : Yeah that one does work...

**Comment by MarcoMeter** [comment]
So the observation to be collected is defined on the brain component and the according camera is referenced on the agent.

Maybe there is something wrong that particular camera. Is the camera component and the GameObject activated? I suspect that inside of Unity the collected texture is null.

**Comment by gerardsimons** [comment]
Ah I fixed it, it was because I had two brains exported. I was playing around with a new brain and I disabled the old brain but it was still being exported (and found by the ppo.py), messing everything up. 

Might be nice if in future releases disabled brains are not found by the ppo.py? Thanks for the help @MarcoMeter !
