### ISSUE TITLE
Difference between `ResetOnDone` and `AgentReset` func

### ISSUE THREAD

**Issue by gzrjzcx** [Unity-Technologies/ml-agents#2154]
I am new here, and now facing a problem that when I checked the `ResetOnDone` box in the agent inspector, everything works well for me.
  
However, I want to called the `AgentReset` manually. So I unchecked `ResetOnDone` box and called `Done()` function at `AgentAction()` function. Then I called `AgentReset()` explicitly and I am sure that `AgentReset()` has been executed correctly. But them it works not as expected.
  
It looks like I have terminated this episode, and I cannot step into the Agent script, the monitor stops as well. Then after checking the document, it said that `ResetOnDone` property just automatically reset the agent when agent is 'done', but why there are two different results in terms of two methods?

**Comment by xiaomaogy** [comment]
AgentReset() should not be called by you, it is a place that you put your reset logic code, and when Done() is called, the AgentReset() logic will be executed afterwards. @gzrjzcx

**Comment by gzrjzcx** [comment]
Hi @xiaomaogy ,
That is to say, `AgentReset()` is intended to reset our own logic code for our specific case? In fact, it includes some other underlying implementations for some stuff like reseting the `Done` flag to initial state etc? 
  
In addition, if unchecked the `ResetOnDone()` box, how to reset the agent correctly?

**Comment by xiaomaogy** [comment]
@gzrjzcx Oh if you uncheck ResetOnDone(), then AgentReset() won't be called at all, and you shouldn't call it yourself. In that case Agent won't be reset until the AcademyReset() is called, and you should put your logic to reset everything inside AcademyReset().
