### ISSUE TITLE
ArgumentException: An item with the same key has already been added. Key: Car (CarAgent)

### ISSUE THREAD

**Issue by pratham751** [Unity-Technologies/ml-agents#2156]
So after I trained my model with ML-Agents, I took the .nn file and I set it in the Model section of the Learning Model
Initially it was set to text asset and thats why I changed `ENABLE_TENSORFLOW` to `ENABLE_BARRACUDA`
and set the control in Academy next to the learning model as false
After that, I get the errors:
I get this initial error:
`ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.

Parameter name: index
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
MLAgents.InferenceBrain.VectorObservationGenerator.Generate (MLAgents.InferenceBrain.Tensor tensor, System.Int32 batchSize, System.Collections.Generic.Dictionary`2[TKey,TValue] agentInfo) (at Assets/ML-Agents/Scripts/InferenceBrain/GeneratorImpl.cs:77)
MLAgents.InferenceBrain.TensorGenerator.GenerateTensors (System.Collections.Generic.IEnumerable`1[T] tensors, System.Int32 currentBatchSize, System.Collections.Generic.Dictionary`2[TKey,TValue] agentInfos) (at Assets/ML-Agents/Scripts/InferenceBrain/TensorGenerator.cs:95)
MLAgents.LearningBrain.DecideAction () (at Assets/ML-Agents/Scripts/LearningBrain.cs:196)
MLAgents.Brain.BrainDecideAction () (at Assets/ML-Agents/Scripts/Brain.cs:99)
MLAgents.Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:628)
MLAgents.Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:655)
`

And then I get this repeated error:
`ArgumentException: An item with the same key has already been added. Key: Car (CarAgent)
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <1f0c1ef1ad524c38bbc5536809c46b48>:0)
MLAgents.Brain.SendState (MLAgents.Agent agent, MLAgents.AgentInfo info) (at Assets/ML-Agents/Scripts/Brain.cs:56)
MLAgents.Agent.SendInfoToBrain () (at Assets/ML-Agents/Scripts/Agent.cs:650)
MLAgents.Agent.SendInfo () (at Assets/ML-Agents/Scripts/Agent.cs:1038)
MLAgents.Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:626)
MLAgents.Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:655)`

Note: The model works completely fine if I change the ML-Agent object in the Agent script to a Player Model Meaning Manual control works perfectly

Please help this is the biggest problem I can find

Also here is the Agent code (Because I suspect there may be an error with that):
`
using MLAgents;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;

public class CarAgent : Agent
{
    
    CarMoveScript carMove;
    RayCastDetection rayCast;

    CarArea carArea;

    public GameObject textObject;
    TextMeshPro text;

    
    public void Start()
    {
        carMove = gameObject.GetComponent<CarMoveScript>();
        rayCast = gameObject.GetComponent<RayCastDetection>();
        carArea = gameObject.GetComponent<CarArea>();
        text = textObject.GetComponent<TextMeshPro>();
    }
    
    public override void CollectObservations()
    {
        base.CollectObservations();
        
        AddVectorObs(rayCast.leftDistance);
        AddVectorObs(rayCast.upleftDistance);
        AddVectorObs(rayCast.forwardDistance);
        AddVectorObs(rayCast.uprightDistance);
        AddVectorObs(rayCast.rightDistance);
        AddVectorObs(carMove.velocity);
        
    }

    public override void AgentAction(float[] vectorAction, string textAction)
    {
        base.AgentAction(vectorAction, textAction);

        if (vectorAction[0] == 1)
        {
            carMove.GoForward();
        }
        if (vectorAction[1] == 1)
        {
            carMove.TurnLeft();
        }
        else if (vectorAction[1] == 2)
        {
            carMove.TurnRight(); ;
        }

        rayCast.update_rays();
        
        if (carArea.hasdied)
        {
            carArea.hasdied = false;

            Done();
        }
        else if(GetCumulativeReward() <= -5f)
        {
            carArea.respawn();
            carArea.hasdied = false;
            Done();
        }
        else
        {
            AddReward(rayCast.reward);
            text.text = GetCumulativeReward().ToString("0.0000");
        }
    }
}
`

**Comment by xiaomaogy** [comment]
I think the error `ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. should be your true error message. The exception message "An item with the same key has already been added" is just a catch all message after that. 

Regarding the solution to this, I'm not sure what caused the out of range exception to occur, but hopefully knowing this is the right place to track down the issue will help you.

**Comment by pratham751** [comment]
> I think the error `ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. should be your true error message. The exception message "An item with the same key has already been added" is just a catch all message after that.
> 
> Regarding the solution to this, I'm not sure what caused the out of range exception to occur, but hopefully knowing this is the right place to track down the issue will help you.

Thank you very much although I think that the problem lies in the library because when I comment out this part:

`public override void CollectObservations()
{
    base.CollectObservations();
    
    AddVectorObs(rayCast.leftDistance);
    AddVectorObs(rayCast.upleftDistance);
    AddVectorObs(rayCast.forwardDistance);
    AddVectorObs(rayCast.uprightDistance);
    AddVectorObs(rayCast.rightDistance);
    AddVectorObs(carMove.velocity);
    
}`

the problem goes away

but the thing is that none of the variables I am sending through the AddVectorObs() command are non-negetive and float which worked perfectly while training with the same code.

**Comment by xiaomaogy** [comment]
I think you didn't match your agent's observation size with the number of observation you added.

**Comment by pratham751** [comment]
Actually I have set the agent's observation size the same as while it was training

**Comment by xiaomaogy** [comment]
Sorry in that case I don't know what happens.

**Comment by pratham751** [comment]
Its okay cause now I am trying to directly use a reinforcement learning model on python which will communicate with unity via socket so I can run both the scripts together like ml-agents does
Thanks for the help BTW but would still love to see a solution to this issue
I want to use ml-agents as it is much simpler.

**Comment by harperj** [comment]
Hi all -- this issue has been inactive for some time so I'm going to close it.  Feel free to reopen or create a new issue if you have more to discuss.

**Comment by SufiahA** [comment]
I am currently getting this same error. I've managed to narrow it down to find that the root problem is inside of the Brain.cs script when it calls this function.
![image](https://user-images.githubusercontent.com/35203126/63051122-683eeb00-be91-11e9-97fd-fdb0bc4eed00.png)

![image](https://user-images.githubusercontent.com/35203126/63051063-4a718600-be91-11e9-943c-c6061bbff7f2.png)

**Comment by akTwelve** [comment]
This happened to me and I figured it out. You probably grabbed a .nn file from a training run that had a greater number of observations than your current LearningBrain. For example, in my case, when I dragged a .nn model from a training run where I had 85 vector observations into a LearningBrain with only 54 vector observations, it gave me this error.

Here's a breakdown of what was happening in my case. The agentInfos dictionary is supposed to be cleared out at the end of LearningBrain.DecideAction(), however that line is never reached because _tensorGenerator.GenerateTensors() fails several lines earlier. The error message "An item with the same key has already been added." happens because the dictionary was never cleared.

The reason GenerateTensors() fails with an ArgumentOutOfRangeException is because of this part in GeneratorImpl.Generate(), line 96:
```
for (var j = 0; j < vecObsSizeT; j++)
{
    tensorProxy.Data[agentIndex, j] = vectorObs[j];
}
```
vecObsSizeT is pulled from the .nn file by Barracuda in LearningBrain, line 115:
`_barracudaModel = ModelLoader.Load(model.Value);`

So essentially, if your current agent has X vector observations but the .nn file was actually trained with Y vector observations and X < Y, you will get this error. If X >= Y, you may not get an exception, but the agent won't work right because it's the wrong trained model.

**Comment by palomagr** [comment]
Does this mean that the .nn models that come with the sdk like for example in pyramids, only work for the pyramids, and not for the visual pyramids? It would be great that a disclaimer is included in the instructions so we don't just assume that the model would work, which is fine and logical
