### ISSUE TITLE
Save Separate Model at Reward or Step Milestones

### ISSUE THREAD

**Issue by brandonhotdog** [Unity-Technologies/ml-agents#2162]
So let's imagine at the start my agent will average 0 total reward and that the best possible agent will average 100 total reward. 

Is there a way I could start training my agent and when it reaches average 20 total reward it'll save a model and continue training, repeating this for 40, 60, 80 and 100? That way I end up with several models and can then put them into Unity to essentially see how my agents' behaviour has evolved over time, (so I do not mean override the model, I want a separate model for each save).

If that cannot be done with total reward is it possible to save a separate model every certain number of steps?

**Comment by gzrjzcx** [comment]
Sounds pretty good.
I guess it can be achieved by Python API?  In fact all of the examples provided by them have set a benchmark. I am not sure how the benchmark will influence the training progress.

**Comment by xiaomaogy** [comment]
@brandonhotdog I think right now you have two ways of doing this. 

1. Doing this manually, do the training, and when it reaches 20, stop the training and save the model. Then use --load to continue training....

2. You tweak our python code to convert the tensorflow checkpoints into the .nn models, tensorflow can save multiple of the checkpoints, and each of them correspond to a raw file, which we use to convert to .nn model file.

**Comment by harperj** [comment]
Hi all -- this issue has been inactive for some time so I'm going to close it.  Feel free to reopen or create a new issue if you have more to discuss.
