### ISSUE TITLE
Intern layer of LSTM

### ISSUE THREAD

**Issue by odannis** [Unity-Technologies/ml-agents#2164]
Hi,

i would like to know the type of LSTM you use and the correspondence between the name of layer from the LSTM model and the name of layer used in Barracuda. 

I used the [Lstm page of wikipedia](https://en.wikipedia.org/wiki/Long_short-term_memory) with the name, the shape of the intern layer in Barracuda to guess a diagram of how are connected the layers. Is it correct ? Can you help about what is surrounded in red  ?
![lstm](https://user-images.githubusercontent.com/51485575/59945851-dbe6ed80-9436-11e9-809c-fa4337c65b05.png)

Thank you for your help.

Ps : i give you my configuration

    batch_size: 2048
    beta: 1.0e-2
    buffer_size: 4096
    gamma: 0.995

    hidden_units: 512
    lambd: 0.98

    max_steps: 5.0e6

    num_epoch: 5
    num_layers: 3
    time_horizon: 128

    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 256

    use_recurrent: false  #Parametre pour LTSM
    sequence_length: 64
	memory_size: 256

**Comment by xiaomaogy** [comment]
Hi @odannis We use BasicLSTMCell, here is the relevant code. 

```
    def create_recurrent_encoder(input_state, memory_in, sequence_length, name="lstm"):
        """
        Builds a recurrent encoder for either state or observations (LSTM).
        :param sequence_length: Length of sequence to unroll.
        :param input_state: The input tensor to the LSTM cell.
        :param memory_in: The input memory to the LSTM cell.
        :param name: The scope of the LSTM cell.
        """
        s_size = input_state.get_shape().as_list()[1]
        m_size = memory_in.get_shape().as_list()[1]
        lstm_input_state = tf.reshape(input_state, shape=[-1, sequence_length, s_size])
        memory_in = tf.reshape(memory_in[:, :], [-1, m_size])
        _half_point = int(m_size / 2)
        with tf.variable_scope(name):
            rnn_cell = tf.contrib.rnn.BasicLSTMCell(_half_point)
            lstm_vector_in = tf.contrib.rnn.LSTMStateTuple(
                memory_in[:, :_half_point], memory_in[:, _half_point:]
            )
            recurrent_output, lstm_state_out = tf.nn.dynamic_rnn(
                rnn_cell, lstm_input_state, initial_state=lstm_vector_in
            )

        recurrent_output = tf.reshape(recurrent_output, shape=[-1, _half_point])
        return recurrent_output, tf.concat([lstm_state_out.c, lstm_state_out.h], axis=1)
```

**Comment by harperj** [comment]
Hi all -- this issue has been inactive for some time so I'm going to close it.  Feel free to reopen or create a new issue if you have more to discuss.
