### ISSUE TITLE
RayPerception logic

### ISSUE THREAD

**Issue by gregnz** [Unity-Technologies/ml-agents#2165]
hi, a query about `RayPerception` logic, it's currently implemented as:

```
perceptionBuffer = [0000...]
for each angle:
             hit = circle cast
             if (hit): 
                   if hit detectable objects: subList = [1, 0,1]
                   if hit something else: subList = [0, 0, 0]
             else (didnt hit anything): sublist = [0 1 0]

```

So a  'non detectable hit' event gives a different vector to a 'didnt hit anything' event. Is that intentional? It seems to me that those vectors should be identical, ie `[0,0,0]`

**Comment by xiaomaogy** [comment]
"Hit something unknown " vs "didn't hit anything" is two different event, so they should be treated differently. @gregnz

**Comment by gregnz** [comment]
Thanks @xiaomaogy - the code is pretty unclear, so when the observations come back, its pretty confusing to see a `1` when the sphere cast didn't hit anything.

Maybe if the `1` in the line `subList[detectableObjects.Length] = 1f;` was a zero, and the `subList[detectableObjects.Length] = 1f;` was moved to the bottom of the `if (hit) {` block... ?

**Comment by xiaomaogy** [comment]
If you think some doc will help, feel free to issue a PR, and some of us will review it. @gregnz

**Comment by gregnz** [comment]
happy to do that, can you add me as a contributor?

The major 'issue' is that the code sets a '1' for a 'no hit' event, which is a bit odd.

**Comment by xiaomaogy** [comment]
You don't need to be a contributor to issue a PR. @gregnz
