### ISSUE TITLE
Std of Reward not decreasing

### ISSUE THREAD

**Issue by MrGitGo** [Unity-Technologies/ml-agents#2168]
I have these values:

![cmdSchritte](https://user-images.githubusercontent.com/33628476/59960741-04212b80-94cd-11e9-859a-db83f9836bbf.PNG)

And I wanted to ask, which parameters I can change, to decrease the std of reward. And I guess the std of reward is not displayed on TensorBoard am I right?

**Comment by xiaomaogy** [comment]
@MrGitGo It is not displayed, but when you look at the reward curve, the std correspond to the noisiness of the curve. 

The std of reward is mainly related to your environment, if your environment's reward changes a lot between different runs, the std of rewards will be large.

**Comment by harperj** [comment]
Hi all -- this issue has been inactive for some time so I'm going to close it.  Feel free to reopen or create a new issue if you have more to discuss.

**Comment by noshaba** [comment]
Is there an option to display the std in Tensorboard?

**Comment by AsadJeewa** [comment]
@noshaba I am looking for the same thing
