### ISSUE TITLE
Gym Wrapper TypeError

### ISSUE THREAD

**Issue by Taikatou** [Unity-Technologies/ml-agents#2169]
I am setting up the gym wrapper to work with the GridWorld I tried both sample python scripts on the tutorial however I get the same error referencing back to the visual observations.

Script 1
`File "C:\Users\conor\Anaconda3\envs\ml-agents\lib\site-packages\baselines\deepq\deepq.py", line 242, in learn
    obs = env.reset()
  File "C:\Users\conor\Anaconda3\envs\ml-agents\lib\site-packages\gym_unity\envs\unity_env.py", line 121, in reset
    obs, reward, done, info = self._single_step(info)
  File "C:\Users\conor\Anaconda3\envs\ml-agents\lib\site-packages\gym_unity\envs\unity_env.py", line 173, in _single_step
    self.visual_obs = self._preprocess_single(info.visual_observations[0][0, :, :, :])
TypeError: list indices must be integers or slices, not tuple`

Script 2
`File "C:\Users\conor\Anaconda3\envs\ml-agents\lib\site-packages\gym_unity\envs\unity_env.py", line 173, in _single_step
    self.visual_obs = self._preprocess_single(info.visual_observations[0][0, :, :, :])
TypeError: list indices must be integers or slices, not tuple`

Any help would be greatly appreciated thank you :D

**Comment by xiaomaogy** [comment]
@awjuliani

**Comment by Taikatou** [comment]
Just fixed this on windows you need to use pip3 install for baseline
