### ISSUE TITLE
Curriculum Reset Parameters for starting lesson

### ISSUE THREAD

**Issue by Royoyoo** [Unity-Technologies/ml-agents#217]
It seems that reset parameters for starting lesson is set by Unity's Academy script("Default reset parameters" Dictionary) instead of first set of parameters in JSON-file.
The other lessons take their parameters correctly from JSON-file.

I can simply set these parameters to the same values, but it's hard to remember to maintain them in two places.

**Comment by awjuliani** [comment]
Hi @Royoyoo,

We've released a new version of ML-Agents which should have resolved this issue. As such we will be closing this. If the issue still exists, please feel free to reopen.
