### ISSUE TITLE
Transfer learning in Barracuda

### ISSUE THREAD

**Issue by MoMe36** [Unity-Technologies/ml-agents#2171]
Hi, 
I'm trying my hand at transfer learning and I have a few questions: 
* What would be the best way to clone a .nn model and change only the last layer?  I was thinking of simply reinitialize randomly the weights of the last layer. 
* Is there any way to freeze the weights of some layers during training ? 

Thanks !

**Comment by xiaomaogy** [comment]
@MoMe36 Yes you can definitely do that, you can look into our trainers/models.py and modify the corresponding tensorflow code to achieve that.

**Comment by MoMe36** [comment]
Hey, thanks for looking into it !
Any specific tips on how I should do it ? Or should I just go ahead and add the functions I need ?

**Comment by xiaomaogy** [comment]
I think just modify our model layers inside the models.py, and change the way layers are set to freeze some of them.

**Comment by MoMe36** [comment]
Hi, 
I've been working on this idea and I've made some progress, but there's a point that blocks me and I'd like to know what you think. 

I figured out how to exclude weights from the optimization using the scope and variables names, however, the fact that the implementation relies on `tf.layers.dense` makes it harder to figure out how to load the weights of a specific layer. 

Initially, I was thinking that the process would: 
1. Create the model with the new input and output layers size 
1. Load the previous model 
1. Set the previous model hidden weight in the new one 
1. Train the new one. 

But I'm not sure anymore. Would it be easier to: 
1. Load the old model 
1. Change the input placeholder and the action dimension ? 

Any ideas ? Thanks a lot !

**Comment by MoMe36** [comment]
I figured it out. I think it works. Would you guys be interested by a PR ?

**Comment by ervteng** [comment]
@MoMe36 if you've gotten transfer learning working, absolutely!

**Comment by ervteng** [comment]
Since the issue was resolved and has been inactive for some time, I'm closing it. @MoMe36 if you'd like to submit a PR for your changes, they're definitely welcome!
