### ISSUE TITLE
Not able to run trainer.py after creating executable (mlagents 0.7)

### ISSUE THREAD

**Issue by palladiun** [Unity-Technologies/ml-agents#2173]
I created a linux executable  of 3Dballs and decided to trainer.py  but I am getting the following error. whats the issue here?
![Screenshot from 2019-06-24 14-11-03](https://user-images.githubusercontent.com/8285098/60017849-11374980-968a-11e9-9b60-3dbedcee5da9.png).

**Comment by xiaomaogy** [comment]
@palladiun It seems that you are pointing to 3dball.x86_64 as your trainer_config file.
