### ISSUE TITLE
ArgumentException: An item with the same key has already been added. (agentInfos)

### ISSUE THREAD

**Issue by mhr** [Unity-Technologies/ml-agents#2175]
I'm receiving the following error with ML-Agents version 8:

```
ArgumentException: An item with the same key has already been added. Key: BPAgent (BPAgent)
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
MLAgents.Brain.SendState (MLAgents.Agent agent, MLAgents.AgentInfo info) (at Assets/ML-Agents/Scripts/Brain.cs:57)
MLAgents.Agent.SendInfoToBrain () (at Assets/ML-Agents/Scripts/Agent.cs:650)
MLAgents.Agent.SendInfo () (at Assets/ML-Agents/Scripts/Agent.cs:1038)
MLAgents.Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:626)
MLAgents.Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:655)

```

I found the `Brain.SendState()` method. Because it's called every frame in Academy's FixedUpdate(), it's entering my agent into the brain's `Dictionary agentInfos` every frame. This seems to cause the error, because Dictionaries in C# are not allowed to Add a new key-value pair if the key already exists.

It looks like the line that causes the error is `agentInfos.Add(agent, info);`, so I rewrote the code to be `agentInfos[agent] = info` to add-or-update. This fixed the error for me. However, I'm not confident that this Add()-at-every-frame behavior wasn't intended, and thus I didn't submit a pull request. Thoughts?

**Comment by xiaomaogy** [comment]
This error message is a catch all error message once some error happens. So you should go to the first error message, which would be your real problem. @mhr

**Comment by mhr** [comment]
I don't quite understand what you mean. This stack trace is the only error message that gets logged, and it's logged every frame. If you mean I should look at Academy.FixedUpdate(), all that told me was that the EnvironmentStep() function gets called every frame, which itself calls SendInfo(), and on and on until the Brain's dictionary gets added to. That's all what the stack trace says, though.

Is it not the case that the Academy is, through this series of function calls within function calls within..., trying to add the Agent's information to the Brain's dictionary at each new frame?

**Comment by xiaomaogy** [comment]
You should go to you first error message and check. It will be a different error message. @mhr

**Comment by mhr** [comment]
Please see below. There is not a different error message.

![image](https://user-images.githubusercontent.com/1429247/60211732-b63e5780-982d-11e9-9843-3db35e92164a.png)

**Comment by xiaomaogy** [comment]
Then I'm not sure what happens here...Sorry I'm not able to help you on this. If you are using your custom code, I would suggest you first try out some of the example environment. If you are able to reproduce this bug in our example environment in a consistent way, feel free to post a new issue.

**Comment by harperj** [comment]
Hi all -- this issue has been inactive for some time so I'm going to close it.  Feel free to reopen or create a new issue if you have more to discuss.

**Comment by conceptfac** [comment]
The same issue on 2019.3 version

**Comment by palomagr** [comment]
This is the whole text I'm getting: 

ArgumentException: An item with the same key has already been added. Key: Agent (PyramidAgent)
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <567df3e0919241ba98db88bec4c6696f>:0)
MLAgents.Brain.SendState (MLAgents.Agent agent, MLAgents.AgentInfo info) (at Assets/ML-Agents/Scripts/Brain.cs:56)
MLAgents.Agent.SendInfoToBrain () (at Assets/ML-Agents/Scripts/Agent.cs:653)
MLAgents.Agent.SendInfo () (at Assets/ML-Agents/Scripts/Agent.cs:1039)
MLAgents.Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:556)

**Comment by muafakul** [comment]
oh yeah ,,,plesease how to fix it

**Comment by chriselion** [comment]
@muafakul This issue has been fixed for several releases; I would recommend upgrading to the latest release (0.14.1).

In general, this problem happened after another exception was raised; you should look at the first error in the logs and try to resolve that first.
