### ISSUE TITLE
The API number is not compatible between Unity and python. Python API : API-4, Unity API : API-8.

### ISSUE THREAD

**Issue by JunaidRana** [Unity-Technologies/ml-agents#2182]
I am following udacity reinforcement learning project.
I have installed the required packages for the project, all things are setup as per given setup.py file. But im getting this error.

`UnityEnvironmentException: The API number is not compatible between Unity and python. Python API : API-4, Unity API : API-8.`

i am using ml-agents 0.8.1. Importing unity agents which have support till 0.4.0.

@awjuliani  
Need help to resolve this.

**Comment by xiaomaogy** [comment]
Hi @JunaidRana, as this error message said, you need to upgrade your python code to version 0.8, or downgrade your Unity environment to v0.4 to make them compatible.

**Comment by JunaidRana** [comment]
> Hi @JunaidRana, as this error message said, you need to upgrade your python code to version 0.8, or downgrade your Unity environment to v0.4 to make them compatible.

@xiaomaogy   How we can upgrade python code to 0.8. We are using following repository for this project.

`https://github.com/kotogasy/unity-ml-tennis`

**Comment by CicieChen** [comment]
in your terminal:
in case of the uncertainty, I suggest you 'pip uninstall mlagents'
then 'pip install mlagents==0.8.2'

**Comment by harperj** [comment]
Hi all -- this issue has been inactive for some time so I'm going to close it.  Feel free to reopen or create a new issue if you have more to discuss.
