### ISSUE TITLE
Multiple visual observations and vector observations?

### ISSUE THREAD

**Issue by shakenes** [Unity-Technologies/ml-agents#2183]
Hi everybody, 
I was trying to build an environment with the Gym interface that provides 3 visual observations (one from each camera) and some additional numbers like the position of the agent as a vector observation. But apparently, it is not intended, that the gym_unity package processes more than one visual observation per agent. The others simply get discarded. Same for the vector observations. 
I modified some lines in the gym_unity code and now it works. But I'm wondering why the interface is designed in such a way? If there are no special reasons for it, I would be happy to submit a PR to solve this problem.

**Comment by xiaomaogy** [comment]
@ervteng @awjuliani

**Comment by awjuliani** [comment]
Hi @shakenes 

The interface was originally designed to mimic as closely as possible the atari and mujoco wrappers for maximum compatibility. We are happy to take a look at PRs though which can improve the code.

**Comment by harperj** [comment]
Hi all -- this issue has been inactive for some time so I'm going to close it.  Feel free to reopen or create a new issue if you have more to discuss.
