### ISSUE TITLE
Any news on headless rendering?

### ISSUE THREAD

**Issue by MarcoMeter** [Unity-Technologies/ml-agents#2185]
Hey,

are there any news concerning headless builds that can render visual observations without using an x server?

**Comment by xiaomaogy** [comment]
Hi @MarcoMeter, we have someone (not in our team though) actively working on that, it might be available on some Unity 2019 version.

**Comment by harperj** [comment]
Hi all -- this issue has been inactive for some time so I'm going to close it.  Feel free to reopen or create a new issue if you have more to discuss.

**Comment by AntonRaichuk** [comment]
Any updates on headless rendering? 2019 is almost at its end
