### ISSUE TITLE
how to export the model to use outof unity?

### ISSUE THREAD

**Issue by vxgu86** [Unity-Technologies/ml-agents#2187]
how to export the model to use outof unity?
expecially with unity inference engine?

**Comment by xiaomaogy** [comment]
@mantasp

**Comment by mantasp** [comment]
Unity inference engine works only as part of Unity runtime, as it depends on Unity APIs. But you still can make your project's standalone build for Mac/Windows/Linux/other platform and deploy where you need it to run.
