### ISSUE TITLE
3DBall Linux Executable rejecting python connection inside Docker.

### ISSUE THREAD

**Issue by batu** [Unity-Technologies/ml-agents#2189]
Hello, 

I just wanted to ask if you faced an issue similar to mine. I am currently trying to train from an executable (3DBall) within docker, from the interactive console.

My host machine is Windows, and I am on the 0.8.2 release of ml-agents.

I almost fully follow the docker instructions from the document, the only difference being the addition of the line ```COPY unity-volume /unity-volume```  to the DOCKERFILE which allows me to see the unity-volume within the interactive mode.

I run the docker image in the interactive mode using: ```docker run -it -p 5005:5005 --entrypoint bash unity```.

From here I run (inside the unity-volume directory that has both the executable and the .yaml) ```mlagents-learn trainer_config.yaml  --env=ball-training.x86_64 --train``` to attempt training. Unfortunatly this step fails with the 

```
UnityAgentsException: The Communicator was unable to connect. Please make sure the External process is ready to accept communication with Unity.
at MLAgents.Batcher.SendAcademyParameters (MLAgents.CommunicatorObjects.UnityRLInitializationOutput academyParameters) [0x0002d] in
<bc4b2621a7f8425688b779e29a854f47>:0
at MLAgents.Academy.InitializeEnvironment () [0x00228] in <bc4b2621a7f8425688b779e29a854f47>:0
at MLAgents.Academy.Awake () [0x00000] in <bc4b2621a7f8425688b779e29a854f47>:0 
``` 
error followed by a timeout.

Here are a few things I know:
1) If I change the platform to Windows, without making any changes to the environment, I can reliably train (both with and without server mode), outside of docker. This leads me to believe the env is configured correctly: The learning brains are attached, control is checked etc.
2) I can use my Unity Edior running on host machine to train with the python code within the docker. This leads me to believe the python side inside docker is working correctly. 
3) I can build and play a headless linux 3DBall env with an internal brain, and log the cumulative result to debug working in docker. This leads me to believe the linux build process is working.
4) Made sure no proxies are set as per this [issue](https://github.com/Unity-Technologies/ml-agents/issues/929).

Yet, I still am failing to train from an executable within docker. 

Is this something you have faced before? And/or would you be able to point to me to a possible pain point?

thank you very much and enjoy life, 
batu

**Comment by unityjeffrey** [comment]
hi @batu - your setup seems to be working.  we recently upgraded to 0.8.2 so there might be a regression.  Can you try the docker container using this release - https://github.com/Unity-Technologies/ml-agents/releases/tag/0.8.1

CC: @xiaomaogy

**Comment by xiaomaogy** [comment]
@batu To run executable within the docker, you need to manually use xvfb to start the whole training.

**Comment by batu** [comment]
thank you jefferey, unfortunately the previous behavior persists on 0.8.1, consistent with num [1-4]. 

Maybe the following log will help? I don't recall seeing the ```Waiting for connection from host on [0.0.0.0:55380]... ``` line but I might be mistaken.

Any pointers would be appreciated and thank you for trying to solve my arcane problems! 

```
root@50ad28b269d5:/unity-volume# mlagents-learn --env LinuxHeadless/linux-headless.x86_64 trainer_config.yaml --train

<UNITY LOGO>

Found path: /unity-volume/LinuxHeadless/linux-headless.x86_64
Mono path[0] = '/unity-volume/LinuxHeadless/linux-headless_Data/Managed
Mono config path = '/unity-volume/LinuxHeadless/linux-headless_Data/MonoBleedingEdge/etc'
PlayerConnection initialized from /unity-volume/LinuxHeadless/linux-headless_Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55380
Multi-casting "[IP] 172.17.0.2 [Port] 55380 [Flags] 3 [Guid] 2773673625 [EditorId] 206784593 [Version] 1048832 [Id] LinuxPlayer(172.17.0.2) [Debug] 1 [PackageName] LinuxPlayer" to [225.0.0.222:54997]...   Waiting for connection from host on [0.0.0.0:55380]... 
Waiting for connection from host on [0.0.0.0:55380]...
Remaining time:8s
Remaining time:7s
Remaining time:6s
Remaining time:5s
Remaining time:4s
Remaining time:3s
Remaining time:2s
Remaining time:1s
Remaining time:0s
Timed out. Continuing without host connection.
Started listening to [0.0.0.0:55380]
Using monoOptions --debugger-agent=transport=dt_socket,embedding=1,server=y,suspend=n,address=0.0.0.0:56625
Preloaded 'libgrpc_csharp_ext.x64.so'
PlayerConnection already initialized - listening to [0.0.0.0:55380]

< FALLBACK HANDLER WARNINGS > 

UnityAgentsException: The Communicator was unable to connect. 
Please make sure the External process is ready to accept communication with Unity.
at MLAgents.Batcher.SendAcademyParameters (MLAgents.CommunicatorObjects.UnityRLInitializationOutput academyParameters) [0x00028] 
in D:\TrainingGrounds\Homebrew\UnityEnvFactory\Assets\ML-Agents\Scripts\Batcher.cs:91
at MLAgents.Academy.InitializeEnvironment () [0x0025e] in D:\TrainingGrounds\Homebrew\UnityEnvFactory\Assets\ML-Agents\Scripts\Academy.cs:345 
at MLAgents.Academy.Awake () [0x00001] 
in D:\TrainingGrounds\Homebrew\UnityEnvFactory\Assets\ML-Agents\Scripts\Academy.cs:250 
```

**Comment by batu** [comment]
Solved my issue! It indeed was a proxy problem as mentioned in this [issue](https://github.com/Unity-Technologies/ml-agents/issues/929).

However, for some reason, 
```
set HTTP_PROXY=
set HTTPS_PROXY=
```
wasn't enough in my case.

For others possibly facing the same issue, ```env | grep -i proxy``` will give you any proxy related environment variables. From then onwards  ````export MYVAR=``` will allow you to set the proxies to null.
