### ISSUE TITLE
Do I still need Rewards in internal mode?

### ISSUE THREAD

**Issue by MrGitGo** [Unity-Technologies/ml-agents#2193]
If I am not training the brain and start to play the actual game, do I still need rewards there? Or can I delete them? I mean the code lines where I implemented the reward()

**Comment by gzrjzcx** [comment]
I guess you can just use the brain with trained model and specific observations to inference actions, no need for rewards?

**Comment by unityjeffrey** [comment]
hi @MrGitGo - i was wondering if you could elaborate on why you would want to what you described?

**Comment by harperj** [comment]
Hi all -- this issue has been inactive for some time so I'm going to close it.  Feel free to reopen or create a new issue if you have more to discuss.
