### ISSUE TITLE
Barracuda MobileNet transfer learning from Keras

### ISSUE THREAD

**Issue by Guidosalimbeni** [Unity-Technologies/ml-agents#2203]
Hi,
I have been trying to Barracuda for inference but I am having a lot of issues and I wonder if there is an example available that I can study?

I wrote a notebook that uses MobileNet in Keras and adapted (transfer learning) for my specific needs of classification. It ends with a softmax activation and predict 2 classes. All is working fine in Jupyter Notebook and the predictions are corrects. I converted the saved model in ONNX format and then I used you script ONNX to NN so that I would be able to use with Barracuda. But the I am having all sort of issues and the conversation is not working. this is the latest error [](https://www.screencast.com/t/MGDo5D7f)
https://www.screencast.com/t/MGDo5D7f
If you have a sort of example that would be so useful for me...

thank you

**Comment by Guidosalimbeni** [comment]
I went ahead and I implemented a very basic CNN to test with barracuda. When I try to convert both a onnx and a pb model with the script provided I got this error (see picture)
Can you point me to the right direction? that would be really appreciated

https://www.screencast.com/t/rcmQZFdl1sF

**Comment by unityjeffrey** [comment]
hi @Guidosalimbeni - thank you for your note.  unfortunately, this is outside of the scope of ML-Agents.  Supporting mobilenet is on the inference engine team's roadmap.  CC: @mantasp

**Comment by Guidosalimbeni** [comment]
Hi @unityjeffrey really appreciate that is the roadmap and that you CC @mantasp . Just would like to add that I would be very happy also with an example that does not involve MobileNet and just a basic CNN, For my project a couple of CNN layers are just enough but I cannot find a way to convert it into a .NN format. Everytime I got a different type of error. the most recent was:  UnboundLocalError: local variable 'data' referenced before assignment.

I appreciate that this is outside the score of ML-agents , and I am trying to follow the instruction provided here for Barracuda : https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Plugins/Barracuda.Core/Barracuda.md

**Comment by mantasp** [comment]
@Guidosalimbeni could you please share your test network? Thanks!

**Comment by Guidosalimbeni** [comment]
Dear @mantasp , thank you very much for your support!! (below the code) in the next post I will try to paste the model.summary()

```
import keras
import tensorflow as tf
import numpy as np
from keras.layers import Dense,GlobalAveragePooling2D, Flatten, Input, Dropout
from keras.preprocessing import image
from keras.applications.mobilenetv2 import MobileNetV2
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Model
from keras.optimizers import Adam
from keras.applications.mobilenet import preprocess_input
from keras import backend as K


# * tensorflow version: '1.7.1'
# * Keras: '2.2.4'
# * python 3.6.5 (Anaconda)
# * windows 64 bit 

input_shape = (224,224,3)

def build_model( ):
    input_tensor = Input(shape=input_shape)
    base_model = MobileNetV2(
        include_top=False,
        weights='imagenet',
        input_tensor=input_tensor,
        input_shape=input_shape,
        pooling='avg')

    for layer in base_model.layers:
        layer.trainable = False  # trainable has to be false in order to freeze the layers
        
    op = Dense(256, activation='relu')(base_model.output)
    op = Dropout(.25)(op)
    
    output_tensor = Dense(2, activation='softmax')(op)

    model = Model(inputs=input_tensor, outputs=output_tensor)


    return model


model = build_model()
model.compile(optimizer=Adam(),
              loss='categorical_crossentropy',
              metrics=['categorical_accuracy'])


train_datagen=ImageDataGenerator(preprocessing_function=preprocess_input) 

train_generator=train_datagen.flow_from_directory('./train/',
                                                 target_size=(224,224),
                                                 color_mode='rgb',
                                                 batch_size=32,
                                                 class_mode='categorical',
                                                 shuffle=True)


step_size_train=train_generator.n//train_generator.batch_size
model.fit_generator(generator=train_generator,
                   steps_per_epoch=step_size_train,
                   epochs=1)


model_name = 'MorandiMobileNetv4July.h5'
model.save(model_name)

def freeze_session(session, keep_var_names=None, output_names=None, clear_devices=True):

    graph = session.graph
    with graph.as_default():
        freeze_var_names = list(set(v.op.name for v in tf.global_variables()).difference(keep_var_names or []))
        output_names = output_names or []
        output_names += [v.op.name for v in tf.global_variables()]
        input_graph_def = graph.as_graph_def()
        if clear_devices:
            for node in input_graph_def.node:
                node.device = ""
        frozen_graph = tf.graph_util.convert_variables_to_constants(
            session, input_graph_def, output_names, freeze_var_names)
        return frozen_graph


frozen_graph = freeze_session(K.get_session(),
                              output_names=[out.op.name for out in model.outputs])

tf.train.write_graph(frozen_graph, "", "morandiMobileNet4JulyV2.pb", as_text=False)
```

**Comment by Guidosalimbeni** [comment]
[ModelSummary.txt](https://github.com/Unity-Technologies/ml-agents/files/3359216/ModelSummary.txt)

**Comment by Guidosalimbeni** [comment]
I have:
# * tensorflow version: '1.7.1'
# * Keras: '2.2.4'
# * python 3.6.5 (Anaconda)
# * windows 64 bit

**Comment by Guidosalimbeni** [comment]
![2019-07-04_1333](https://user-images.githubusercontent.com/32448955/60667034-cfb45480-9e68-11e9-93f6-2631bd232886.png)

**Comment by Guidosalimbeni** [comment]
Dear @mantasp ,
just wondering if you need extra information or the above is what you needed. thanks
Guido

**Comment by stefanpantic** [comment]
Bumping this
