### ISSUE TITLE
Starting UnityEnvironment in Inference Configuration from the Python API

### ISSUE THREAD

**Issue by batu** [Unity-Technologies/ml-agents#2204]
Hello again,

Whenever I am demo'ing my agents I build another executable with the training time scale set to a reasonable amount. I want to get around this and just start my env in the inference configuration from the python API.

Is there a hook/flag for that?

Thank you very much,

**Comment by unityjeffrey** [comment]
hi @batu - can you describe your scenario a bit more.  are you wanting to change the timescale from python or looking for in-editor training?

**Comment by batu** [comment]
I am using the Python API to train my agents.

```c#
from mlagents.envs import UnityEnvironment
UnityEnvironment(file_name="<MyUnityEnvPath>")
```

When use this method, the environment opens up in the Training Configuration:
![image](https://user-images.githubusercontent.com/6670976/60362255-6cc94600-99ae-11e9-9e49-9d2ee800f7c2.png)
I was wondering if there was a flag that I could pass to UnityEnvironment class to open it up in the Inference Configuration.

The use case is demoing my agents, mainly with slower timescale and higher quality. I guess I can just addd some GetKeyDown's to change the timescale from within unity whenever I am demoing... 

Okay. In writing this response I found a way to fix my issue but still let me know if booting in Inference is possible and thank you @unityjeffrey !
