### ISSUE TITLE
Compatibility with DOTS

### ISSUE THREAD

**Issue by mschneider** [Unity-Technologies/ml-agents#2206]
Thank you for the great work on documenting more of the codebase, it definitely got easier to understand how to build your own learning environment etc.

I am currently using the new physics engine based on DOTS for a crowd sim project. Going forward I am planning to have super tiny RL models work inside of it.

Did you try already or are you planning to adapt the Joint Drive Controllers etc to the new physics engine? 

Are there any know complications from the interaction?

Are there known limitations to the number of simultaneous agents? I was thinking of 100s or even 1000s.

**Comment by unityjeffrey** [comment]
hi @mschneider - we are in early prototyping for integrating ML-Agents with DOTS.  We do plan to support DOTS in the future.  Unfortunately, the prototype is not in a condition where we could share.

**Comment by mschneider** [comment]
Hi Jeffrey,

thank you for your quick answer. I'm excited to hear that you are planning to integrate with DOTS, could you share what the goal of that plan would be in terms of MLA users? Interop. / perf. / new features(?) 

Also, could you give a bit more detail with regards to my previous questions. I'm especially interested to hear just a rough estimation of complexity, and your high level input on scalability as I am trying to evaluate, if it makes sense from my side to move forward with an implementation of my own - skipping ahead of your work on this integration.

Best,
Max

**Comment by unityjeffrey** [comment]
hi @mschneider - we will publish a technical blog post on ml-agents and dots in the next several weeks.  at a high level, there are some nice benefits for DOTS, like the ability to add a lot of agents in a single scene for training.  cc: @VilmantasBal

**Comment by SetoKaiba** [comment]
When will it be available? Looking forward to it.

**Comment by surfnerd** [comment]
Hi all,
We area currently figuring out our roadmap for DOTS compatibility.  We will share it once we have nailed down a plan.  We have logged this request internally as MLA-83.  We will close this issue and update it when we can answer your questions.

**Comment by GProulx** [comment]
Hi @unityjeffrey and @surfnerd !

We are also looking to move to DOTS while using ml-agents. Can you give us an update on where your are now with that topic on your side? Have you seen any hybrid DOTS/non-DOTS implementations that used ml-agents?

**Comment by surfnerd** [comment]
Hi @GProulx, 
We have an internal repo that we aren't ready to share yet.  The timeline is still up in the air since we are getting ready to release the current package through Unity's Package Manager.   We will definitely update this thread when we have more information to share.

**Comment by GProulx** [comment]
Good. Thanks for the quick answer @surfnerd !  Looking forward for an update.  We could be available for testing that if needed in the future.

**Comment by surfnerd** [comment]
@unityjeffrey
