### ISSUE TITLE
what is meaning of "Added Keras converter as part of distribution." in barracuda releases note

### ISSUE THREAD

**Issue by DeusExMachina1993** [Unity-Technologies/ml-agents#2217]
hi,
in ml-agent release note (https://github.com/Unity-Technologies/ml-agents/releases)
you mentioned "The Unity Inference Engine upgraded to version 0.2.2"
and in Unity Inference Engine release note for version 0.2.2 you mentioned "Added Keras converter as part of distribution"
(https://github.com/Unity-Technologies/ml-agents/blob/release-v0.8.2/UnitySDK/Assets/ML-Agents/Plugins/Barracuda.Core/ReleaseNotes.md)
what is this meaning? how to use Keras converter?

**Comment by xiaomaogy** [comment]
@mantasp

**Comment by mantasp** [comment]
@DeusExMachina1993 it's part of full Barracuda release, which can be found here: https://github.com/Unity-Technologies/barracuda-release
