### ISSUE TITLE
NameError: name 'UnityEnvironment' is not defined

### ISSUE THREAD

**Issue by Selzier** [Unity-Technologies/ml-agents#222]
I'm at the point where I'm trying to run the python/Basics Jupyter Notebook, or the PPO notebook. On either one of these, I get the error:
NameError: name 'UnityEnvironment' is not defined

This happens during the "Load the Environment" section.

What can I do to fix the error?

Unity 2017.3.0f3
Using the commit from Dec 23, 2017.

**Comment by MarcoMeter** [comment]
Hi @Selzier 
did you start the Jupyter Notebook inside the the python directory? It looks like that importing the python interface didn't work out.

**Comment by Selzier** [comment]
I missed the step of running this line in Python:
_from unityagents import UnityEnvironment_

As outlined here:
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Unity-Agents---Python-API.md

Closing issue!
