### ISSUE TITLE
Typo in Python API Docs:  env.reset(train_model=True) --> env.reset(train_mode=True)

### ISSUE THREAD

**Issue by batu** [Unity-Technologies/ml-agents#2223]
There is a small typo in the documentation of the [python API](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Python-API.md).

The first argument passed into ```env.reset``` should be ```train_mode``` instead of ```train_model``` as implemented [here](https://github.com/Unity-Technologies/ml-agents/blob/9b1a39982fd03de8f40f85d61f903e6d972fd2cc/ml-agents-envs/mlagents/envs/environment.py#L308).

**Comment by xiaomaogy** [comment]
Hi @batu, thanks for your finding. Could you issue a PR on this please? We would be happy to merge it in. Remember to target towards the develop branch.

**Comment by chriselion** [comment]
I fixed this on the develop branch.
