### ISSUE TITLE
Is the curriculum lesson number saved somewhere?

### ISSUE THREAD

**Issue by XBLDev** [Unity-Technologies/ml-agents#223]
It seems that if I restart the training with a saved model it will restart from the very first lesson, even the training already passed 2nd or 3rd lesson. Is there a parameter I can set to make the training restart from the latest lesson? Or am I misunderstanding something here?

**Comment by MDReptile** [comment]
In the PPO, you set the "max_steps" higher, and make sure to set "load_model" to true:


![](https://i.gyazo.com/775b4f0d595b4910a6fb470939c60cf6.png)

**Comment by XBLDev** [comment]
Hi @MDReptile thanks for the reply, I think I did set "load_model" to true, but the curriculum lesson number seems to start from 0? I could be wrong here but I don't think it saves the lesson number along with the model?

**Comment by MDReptile** [comment]
Oh okay, I misunderstood. Sorry, I haven't tried doing curriculum learning yet - so I can't help with this.

**Comment by awjuliani** [comment]
Hi, @XBLDev,

The lesson number curren't is not saved. However, in the 0.3 development branch we've added the ability to load a partially trained model and specify the desired starting lesson: https://github.com/Unity-Technologies/ml-agents/commit/6c48f5602711e317600325bcb74e7d61adceb0e8

**Comment by XBLDev** [comment]
@awjuliani Hey thanks for the reply, so that will be at least part of the future plan right? As long as it will be included in the coming releases then it's all good. Thanks for the amazing work!
