### ISSUE TITLE
How to adjust difficult level automatically by RL?

### ISSUE THREAD

**Issue by gzrjzcx** [Unity-Technologies/ml-agents#2230]
Hi community,
  
I am working on help people play games better, and I focus on the difficult level adjustment automatically now.  I know there are some traditional heuristic  methods for this via pre-defined factors which can represent the environments and player's playing skill. 
  
However, I am curious that is this task can be solved by ML-Agents? My basic idea is training an adaptive agent to make decision for taking a certain action to change environments so that the requirement of current game task is reduced. For example, if the agent observed the human player is difficult to jump over a trap, then the agent can narrow the size of this trap.
  
Furthermore, is this possible to make the agents more adaptive for each player? In other word, it is able to recognize different players or different kinds of players, so that it can take different actions for them? For example, give words prompt for 'normal' players to tell them there is a trap, and directly cancel this trap for very 'newbie'.
  
Maybe the problem is that how it can recognize the players via RL? Maybe it is more suitable for supervised machine learning? But the labeled data is also a problem. And the ML-agents doesn't allow training at mobile device?
  
I can just image the final result is that once the human player 'A' playing it, the agent(maybe a NPC) with trained model can learn/recognize the behaviour of the 'A' player, and give specific assistance for 'A', which is suitable for 'A'.
  
Any idea?

**Comment by roboserg** [comment]
you can see how a player performs and adjust the difficulty of RL by code via adjusting randomness of the agent's actions and / or adding reaction delays.

**Comment by gzrjzcx** [comment]
Thanks @roboserg. In other words, I also need to define something to represent the player's skill, and estimate it at runtime, then choose action via RL trained models.  A problem is that how to train the RL model because there is not so much evidence for training.

**Comment by roboserg** [comment]
yes, you have to measure the player's skill somehow.

If your agent doesnt learn start with tutorial examples and work from there.

**Comment by gzrjzcx** [comment]
Hi @awjuliani, I have watched your [video](https://unity3d.com/machine-learning) said using agent to adjust game difficulty level dynamically. 
How to do that? Can u give me some advise? I am working on this now but a little confused about how to train agents.

**Comment by awjuliani** [comment]
Hi @gzrjzcx 

In this video we were talking about projects we have going on at Unity in general. We do not provide a specific example of how to use ML-Agents for adaptive difficulty tuning. That being said, it is possible to do, however ML-Agents may not be the best solution.
