### ISSUE TITLE
Barracuda latest version 0.2.2 Tensor reading Slow down the process

### ISSUE THREAD

**Issue by Praptobala** [Unity-Technologies/ml-agents#2234]
I just used your latest commit Barracuda 0.2.2, its slow on fetching the data from Tensor. Please let me know is there any way around to access the data quickly!! @mantasp

**Comment by xiaomaogy** [comment]
@mantasp

**Comment by Praptobala** [comment]
@mantasp  I found a new update on this issues. 
The problem is not getting Tensor buffer to CPU, rather I used worker.ExecuteAndWaitForCompletion(input_tensor);
instead of 
worker.Execute(input_tensor);

This takes long time to process a frame, let me know what's the difference between these two.

Thanks,
Bala

**Comment by mantasp** [comment]
worker.Execute(input_tensor) + worker.Peek() is the right choice for most applications, 
ExecuteAndWaitForCompletion is mostly used for profiling GPU implementation.
