### ISSUE TITLE
Can Agent directly reference reset parameters from Academy?

### ISSUE THREAD

**Issue by jglazman** [Unity-Technologies/ml-agents#224]
Is there any reason that an `Agent` should not be able to reference reset parameters directly from the `Academy`?

For example, if I have an `Agent` that makes decisions based on an awareness of it's own size in the world (for collision avoidance), and that Agent's size is a reset parameter `agent_size` in my curriculum.  So, my `Agent` maintains a reference to the `Academy` and on `AgentReset()` it reads the value for `agent_size`.   The 3DBall example is basically setup this way, where the `Ball3DAgent` ends its own simulation if it detects that the ball is out of bounds.

However, many of the other example environments tend to use an `Area` pattern instead, where a separate object (called the `Area`) configures the Agents and ends the simulation with an invisible hand outside the awareness of the Agents.

I guess the question is: is there a reason why an `Agent` should not have direct awareness of the `Academy`? Or is this issue handled differently as required per implementation?

**Comment by awjuliani** [comment]
Hi @jglazman,

There is nothing wrong with allowing an agent direct read access to an academy's reset parameters. The `Area` abstraction is used to allow multiple instances of a single environment to exist within a Unity scene.
