### ISSUE TITLE
There is a bug in Examples/VisualBanana Scene

### ISSUE THREAD

**Issue by LuoYouRen** [Unity-Technologies/ml-agents#2240]
**Describe the bug**
In "BananaLogic.cs", the "respawn" part  cause all the banana respawn in the first Area.
The setting of new banana position should add the code  below.
>  "+ myArea.transform.position;"

**To Reproduce**
1. Using mlagent to train VisualBanana Agent will found that the second bananaArea will end up with no banana.

**Screenshots**

**Environment (please complete the following information):**
- OS + version: Windows 10
- _ML-Agents version_:ML-Agents v0.8
- _Environment_: VisualBanana

**Comment by unityjeffrey** [comment]
hi @LuoYouRen - thanks for the issue.  Would you be open to proposing a fix on develop and submitting a PR?  Thanks!

**Comment by LuoYouRen** [comment]
> hi @LuoYouRen - thanks for the issue. Would you be open to proposing a fix on develop and submitting a PR? Thanks!

I have already submitted (PR #2277).
