### ISSUE TITLE
exe file hangs after training

### ISSUE THREAD

**Issue by Usmaniatech** [Unity-Technologies/ml-agents#2244]
After training the exe file using jupyter notebook, the exe file hangs and I am not able to see the trained exe file. I am storing the weights of actor and critic in .pth file. I have tried training the tennis example, but facing the same issue.
Is there any way that I can generate .pb and .bytes model using jupyter notebook ?

**Comment by unityjeffrey** [comment]
hi @Usmaniatech - can you provide your jupyter notebook?  and also what you mean by "trained exe file"?
