### ISSUE TITLE
Help with imitation learning

### ISSUE THREAD

**Issue by ImBackAgain** [Unity-Technologies/ml-agents#2249]
![image](https://user-images.githubusercontent.com/31423836/61078135-9db16e00-a3e5-11e9-920f-fb8f0a35da47.png)
The issue is the above exception being thrown when I try to use the Inference Engine on a model generated through online imitation learning.

Here's what I did:
1. I created an empty scene
1. I created an empty GameObject, to which I attached Ball3DAcademy
1. I added two instances of the 3D ball Game prefab
1. I changed one of the instances to use a 3D Ball Player brain
1. I added 3DBallLearning and 3DBallPlayer to the Academy's broadcast hub.
1. I copied the online bc config file, and set the appropriate value for `brain_to_imitate`
1. I ran `mlagents-learn` with `--slow` and `--train` (pretty sure it worked, as the student's behaviour did change to reflect mine). I did end training by stopping play mode in Unity.
1. Oh, I also changed the player brain's axes to Mouse X and Mouse Y. I don't expect that's where the issue is, but I thought I'd mention.
1. I retrieved the generated model and attached it to 3DBallLearning.
1. I unchecked the Control box for the 3DBallLearning in the Academy.

I have also checked that the original 3DBallLearning model still works fine for inference. It's the model generated that seems to have issues.

Anyone have any advice?

**Comment by unityjeffrey** [comment]
hi @ImBackAgain - the only thing I can think of is there might have been some issues with the mapping between using a mouse to actions that the agent will use.  Have you tried to do the imitation learning without the mouse and see if that works?

**Comment by ImBackAgain** [comment]
Just tried switching it back to the Horizontal and Vertical axes. Trying to use the model generated thus yields the same result.

Anything else? (And thanks for your reply, @unityjeffrey!)

**Comment by unityjeffrey** [comment]
not sure on that... CC: @ervteng - any thoughts on the thread and inference error using IL with the 3dball?

**Comment by chriselion** [comment]
I'm going to close this due to inactivity. 

That particular error log is fixed on the development branch right now. It is generally caused by another error, so if you're hitting problems, you should look earlier in the output logs.
