### ISSUE TITLE
3DBall error when ENABLE_TENSORFLOW

### ISSUE THREAD

**Issue by ccgitgit** [Unity-Technologies/ml-agents#226]
I followed youtube tutorial [Building and Training the First Example-3DBall](https://www.youtube.com/watch?v=-YWts_GlHCY)  then I got "ball.bytes" and imported TFSharpPlugin successfully. 
After that , I opened  player-other settings: NO Scripting Runtime Version:Experimental (.NET 4.6 Equivalent) for me to select
![image](https://user-images.githubusercontent.com/15956861/34551465-04e3731a-f155-11e7-9632-9f477f386cea.png)

After "ENABLE_TENSORFLOW" ,I got ` Assets/ML-Agents/Scripts/CoreBrainInternal.cs(12,7): error CS0246: The type or namespace name `**TensorFlow** `could not be found. Are you missing an assembly reference?`
so as  **TFGraph**  ,**TFSession** .  There is no "internal" option  in Brain Type . Can anybody help?

**Comment by ccgitgit** [comment]
Problem solved by Reinstall unity 2017.3.0f3

**Comment by mrabbah** [comment]
Got the same error with the version 2018.1.0b8

**Comment by andrew-huang** [comment]
Had this same problem, found this question, and was able to resolve it by updating my Scripting Runtime to "Experimental (.NET 4.6 Equivalent)" https://docs.unity3d.com/Manual/ScriptingRuntimeUpgrade.html

**Comment by shohan4556** [comment]
I am having the same error, by default my scripting runtime is set to "Experimental (.NET 4.6 Equivalent)" but nothing solved.

**Comment by swburchill** [comment]
I also get Assets/ML-Agents/Scripts/CoreBrainInternal.cs(12,7): error CS0246: The type or namespace nameTensorFlow could not be found. Are you missing an assembly reference?
same as TFGraph ,TFSession 
I do have the option to set .NET 4.6 experimental and I am on 2017.4
