### ISSUE TITLE
Separate resetParameters by each brain's name

### ISSUE THREAD

**Issue by sufaming** [Unity-Technologies/ml-agents#2269]
The resetParameters would be overriden by another which with the same key when I trained multiple brains at the same time.

Separate the reset parameters by each brain's name, just as what we do with the curricula config files.

I've tried making the key name different by adding prefix words. But it is sometimes not very convenient.

And if there could be a "Lession" property in the Acadamy, it would be more convenient.

**Comment by unityjeffrey** [comment]
cc: @xiaomaogy @chriselion

**Comment by ervteng** [comment]
Thank you for submitting this request. This should be achievable through the Sampling feature released in v0.9. I’m going to close this issue for now, but feel free to resubmit an issue if you're still having problems.
