### ISSUE TITLE
procedure/steps to use a trained unity ml-agent brain to provide real time guidance.

### ISSUE THREAD

**Issue by rajatpaliwal** [Unity-Technologies/ml-agents#2278]
I am working on a project that requires using unity ML agent to provide real time guidance. I am not able to find the procedure/steps to use a trained unity ml-agent brain to provide real time guidance. It would be great if anyone can guide me towards the steps.

**Comment by ervteng** [comment]
Hi @rajatpaliwal, what do you mean by real time guidance? You'll have to frame your problem as a Markov decision process (i.e., at each timestep, the agent sees a state, takes an action, and receives a reward) to use ML-Agents.

**Comment by rajatpaliwal** [comment]
Hi Ervin,

Thanks for replying.
By real time guidance I meant that If I have trained a brain to perform a
particular task and after it is trained properly, if I am performing that
same task, how can the trained brain can guide me to take the right steps
to successfully complete the task?

Thanks,
Rajat

**Comment by ervteng** [comment]
This should be possible. But it will take some Unity knowledge - you'll have to make two Agents, one for training, and one for the guidance. In the guidance agent you can implement the AgentAction method to just show the action it would take, rather than actually taking the action, while adding the observations as usual.

**Comment by rajatpaliwal** [comment]
Thanks @ervteng  for the answer. Will definitely try it.

**Comment by rajatpaliwal** [comment]
Hi @ervteng ,
I am trying to provide real time guidance using the trained brain. I believe by your previous comment you mean to create two agents in the same environment where one agent controlled by the player brain is controlled by the user , while other agent being controlled by the trained brain will provide instructions for guidance. It is not like online behavioral cloning where we have two agents in two different environment.
Kindly correct me if I am saying this wrong.

**Comment by ervteng** [comment]
Hi @rajatpaliwal you are correct it's not like online BC. In online BC the two agents perform the same task (hence behavioral cloning) but in your task they do different things.

**Comment by ervteng** [comment]
You can use text actions, though our trainer won't support it. If you're writing your own using the Python API, it should work.

**Comment by rajatpaliwal** [comment]
I want this textual instructions to be displayed by agent after the training is done when I am using an already trained brain to control the agent. I don't think I will need the trainer to perform this action.. Do you think textAction is the best way to go ahead for this problem or would you suggest any other approach.

**Comment by ervteng** [comment]
textAction seems OK for this scenario. You won't be able to do Barracuda inference with that either, though. I'd give it a discrete action and pick from a list of texts

**Comment by rajatpaliwal** [comment]
Hi @ervteng , Sorry to bug you again . I have a query in response to your previous comment regarding creating two agents one for moving around and one for guidance.
So my question is how will the guidance agent will be in the same state as the agent which is moving around to provide guidance to it.
The possible answer I am able to think is attaching both the agents to the same gameobject which is moving around. But then two brains will be attached to the same gameobject at the same time.  I am not sure how those two brains will provide actions(one brain should provide make the agent  move , other one which is the trained brain should provide guidance by textual instructions on the screen ).
I hope I am able to describe my problem properly. If any confusion kindly ask. Any suggestion would be helpful.
