### ISSUE TITLE
[Barracuda]Limited layer support

### ISSUE THREAD

**Issue by stefanpantic** [Unity-Technologies/ml-agents#2281]
**Is your feature request related to a problem? Please describe.**
My issue is related to the limited support for TensorFlow operations in Barracuda. I'm mainly referring to the following ops:
* ```FloorMod```
* ```Range```
* ```ExpandDims```
* ```Cast```
* ```Less```
* ```FloorDiv```
* ```Squeeze```
* ```FusedBatchNormV2```
* ```Pack```
* ```SpaceToBatchND```

**Describe the solution you'd like**
Expand Barracuda by adding support for these operations. An alternative would be to make a detailed contribution guide (maybe even add a template of some kind) for implementing new ops.

**Describe alternatives you've considered**
I've tried to implement some ops myself but have no idea where to begin.

**Additional context**
N/A

cc: @unityjeffrey @mantasp

**Comment by mantasp** [comment]
cc: @rejunity

**Comment by stefanpantic** [comment]
@mantasp Any info on this?

**Comment by mantasp** [comment]
@stefanpantic we will use it as input for our roadmap planning, but I yet don't have specific timeframes when it could be actually implement.

**Comment by FlorentGuinier** [comment]
@stefanpantic did you had a specic models or papers in mind using those layer?

**Comment by stefanpantic** [comment]
Yes, I want to use Nvidia's Jasper speech recognition model from here https://arxiv.org/pdf/1904.03288.pdf

**Comment by FlorentGuinier** [comment]
Could you link the paper please?

**Comment by stefanpantic** [comment]
Sorry for the late reply. The paper in question is DeepSpeech https://arxiv.org/abs/1412.5567
