### ISSUE TITLE
Problems with executable environment on Windows using Unity 2019.1.4f1

### ISSUE THREAD

**Issue by KristianLN** [Unity-Technologies/ml-agents#2284]
Hi,

I have created a environment where an agent is trying to navigate to a target, and everything works as intended in the editor. However, when building an executable environment, the agent gets stuck at the wall right away and as so, no episode is completed. 
I have tried using a player brain instead, but that makes little difference, in the sense that the players doesn't get stuck but the movement is really strange (never moves forward, only left/right and really fast).

I intend to use curriculum learning but I have even tried dropping that with no luck. 

I saw this [issue](https://github.com/Unity-Technologies/ml-agents/issues/2033) but that didn't sort it out. 

As a final note, after the build and running the environment through the terminal, the application window that appears is really small, like 2x2 cm..

I use the following to execute the executable environment (Note if the build is done directly in the ml-agents folder of mine, "UnitySDK/" is disregarded in --env=):

mlagents-learn config/trainer_config.yaml --env=UnitySDK/Dissertation --curriculum=config/curricula/env-4.0/ --run-id=BaseEnvironment-DI3

All help is appreciated,

**Comment by ervteng** [comment]
HI @KristianLN, can you post your Training and Inference Configuration (in Academy) and your Player Settings (Under Build Settings -> Player Settings, shows up in the inspector).

The resolution can be fixed in the Player Settings. The movement issues shouldn't happen - are you seeing similar things when building an example environment?

**Comment by KristianLN** [comment]
Hi @ervteng,

Yes, most certainly!

Training Configuration:
Width: 84
Height: 84
Quality Level: 1
TImeScale: 20
TFR: -1

Inference Configuration:
Width: 1280
Height: 720
Quality Level: 5
TImeScale: 1
TFR: 60

I haven't done any inference yet, by used a trained model, so I haven't played with those settings.

**Player settings:**

**Resolution and Presentation:** 
Fullscreen mode: Fullscreen Window
Default is Native Resolution: Checked
Max Retina Support: Checked
Run in background: Checked

Capture single screen: Unchecked
Display Resolution Dialog: Disabled
Use Player Log: Checked
Resizable Window: Unchecked
Visible in Background: Checked
Allow Fullscreen Switch: Checked
Force Single instance: Unchecked
Supported Aspect Ratios: All Checked

Do you need information of the other categories within Player settings?

I haven't tried to build an example environment, I'll try that shortly.

**Comment by KristianLN** [comment]
@ervteng There appears to be no problems when I build the 3DBall example.

**Comment by ervteng** [comment]
Those settings should work - it doesn't seem like it's an RL problem since the player brain also exhibits the same behavior, and it doesn't seem to be a settings problem since you can build 3DBall OK. How are you moving the agent?

**Comment by KristianLN** [comment]
Using continous actions, clamped between -1 and 1, which makes up a rotation and then moving the agent forward with an constant speed.
The AgentAction function looks the following:

`  public override void AgentAction(float[] vectorAction,string textAction)
    {
      Vector3 rotateDir = Vector3.zero;
      if(brain.brainParameters.vectorActionSpaceType == SpaceType.continuous)
      {
        rotateDir = transform.up * Mathf.Clamp(vectorAction[0],-1f,1f);
      }

      // Rotate
      transform.Rotate(rotateDir,Time.deltaTime * 150f);

      // Move
      rbd.velocity = transform.forward * speed;

      // Time penalty
      AddReward(-0.0005f);
    }`

**Comment by ervteng** [comment]
This looks pretty standard, it should be similar to our cube environments (e.g. Hallway, PushBlock, Pyramids) - I'd try to build one of those and see if you have the issue. The only thing I can think of is if the timescale is affecting the physics, but AFAIK the rotate doesn't use physics.

**Comment by KristianLN** [comment]
Okay, I just tried setting timeScale to 1 and 50 respectively, without luck.
I'll try to build one of the suggested environments now, and if that one is good, I'll go over differences.
I'll update within a couple of hours.

**Comment by KristianLN** [comment]
I got the final issue solved as well! I was trying to export data to a folder there didn't existed, from the builds point of view, which prevented the Done() being reached. 

Thank you for your time @ervteng - I'll close this issue now.
