### ISSUE TITLE
Unity was unable to read the arguments passed at launch.

### ISSUE THREAD

**Issue by tananuka** [Unity-Technologies/ml-agents#229]
Please Help.
I am using Unity 2017.3.0f3 Personal and macOS High Sierra 10.13.2
I installed Python 2.7 from package ver. 9.0.1, that downloaded from official [site](https://www.python.org/downloads/mac-osx/) 
Then i performed in terminal: `pip install tensorflow`
that's all what i installed, maybe i missed something?
Because when i am trying to launch Balance Ball Example i get exception:
`UnityAgentsException: The brain Ball3DBrain was set to External mode but Unity was unable to read the arguments passed at launch.
CoreBrainExternal.InitializeCoreBrain () (at Assets/ML-Agents/Scripts/CoreBrainExternal.cs:27)
Brain.InitializeBrain () (at Assets/ML-Agents/Scripts/Brain.cs:187)
Academy.Awake () (at Assets/ML-Agents/Scripts/Academy.cs:124)`

**Comment by MDReptile** [comment]
That error means the brain was set to external mode, and the game wasn't able to connect to the Anaconda/PPO for some reason when it launched. If you want to test an environment you can't have brain set to external, that is only for when the PPO stuff drives the agents, I test with it set to player.

**Comment by tananuka** [comment]
thanks @MDReptile ,
i installed anaconda from official site and setup tensorflow using this [guide](https://www.tensorflow.org/versions/r0.12/get_started/os_setup#anaconda_installation)
but i have new [problem](https://github.com/Unity-Technologies/ml-agents/issues/200))

**Comment by MDReptile** [comment]
You need to edit the PPO when you open it in your browser, where it has "env_name" you put the name of your built exe. Like "MyTestBuild.Exe" would be "MyTestBuild" (without .exe)

**Comment by jeremyPLR** [comment]
You get the `unable to read the arguments passed at launch` error if you try to play the scene inside of the Unity editor with your `brain type` set to `external`.  These are the steps that I follow:

1. Open the scene in the Unity editor and set the `brain type` to `external`.
2. Save and build the scene (e.g. 3dball.app).
3. Train your brain from python on your command line (or jupyter notebook).
4. Follow the instructions to embed the trained model into Unity.
5. Now, back in Unity, set the `brain type` to `internal` and set the `graph model` to the bytes file you exported from python.
6. Play the scene in Unity and you should be able to observe the results of your training.

**Comment by tananuka** [comment]
@MDReptile  @jeremyPLR 
i did as like you had said, but i still have that [problem](https://github.com/Unity-Technologies/ml-agents/issues/200#issuecomment-355808356) with filename: Provided filename does not match any environments

**Comment by wouterhardeman** [comment]
@tananuka Have you placed the executable (like 'Game.exe') in the root of the 'python' folder?

**Comment by tananuka** [comment]
@wouterhardeman  yes, i did

**Comment by wouterhardeman** [comment]
@tananuka I just saw your comment on [the other issue](https://github.com/Unity-Technologies/ml-agents/issues/200) and I think I found the problem. When you open the application (Foo.app) by right-clicking and selecting 'Show Package Contents' and then go to 'Contents/MacOS', is the file called 'Foo' or 'foo'? This could be the problem, since UNIX systems (like MacOS) are case-sensitive.

You could try to rename to file to 'foo' and change the 'env_name' in the settings to 'foo' aswell.

**Comment by tananuka** [comment]
dear @wouterhardeman 
When i opened 'Contents/MacOS' the file called "test2" and i renamed it to "test2". That helped because it is first name of build. 'Ball3DAcademy' started successfully!
Thanks a lot!
