### ISSUE TITLE
cannot train multi agent using Gym: Box object has no attribute 'n'

### ISSUE THREAD

**Issue by Usmaniatech** [Unity-Technologies/ml-agents#2292]
I am training Tennis example using GYM following this link
https://github.com/Unity-Technologies/ml-agents/tree/master/gym-unity

I want to train a multi agent example but it's not working. I have tried other multi agent examples that use the same brain.

Error is:
![error](https://user-images.githubusercontent.com/14370981/61542134-603e8780-aa5a-11e9-962f-8ecb6724830b.PNG)

Code :
> import gym
> 
> from baselines import deepq
> from baselines import logger
> 
> from gym_unity.envs.unity_env import UnityEnv
> 
> def main():
>     env = UnityEnv("./envs/Tennis",0, use_visual= False, multiagent=True)
>     logger.configure('./logs') # Çhange to log in a different directory
>     act = deepq.learn(
>         env,
>         "cnn", # conv_only is also a good choice for GridWorld
>         lr=2.5e-4,
>         total_timesteps=1000,
>         buffer_size=50000,
>         exploration_fraction=0.05,
>         exploration_final_eps=0.1,
>         print_freq=20,
>         train_freq=5,
>         learning_starts=20000,
>         target_network_update_freq=50,
>         gamma=0.99,
>         prioritized_replay=False,
>         checkpoint_freq=1000,
>         checkpoint_path='./logs', # Change to save model in a different directory
>         dueling=True
>     )
>     print("Saving model to unity_model.pkl")
>     act.save("unity_model.pkl")
> 
> if __name__ == '__main__':
>     main()

**Comment by ervteng** [comment]
Hi @Usmaniatech, to the best of my knowledge, the OpenAI gym API for multi-agent isn't fixed, and is implemented differently for different trainers (and changes with gym versions). You might have to adapt our interface to work with Baselines DQN, or adapt DQN to work with our interface.

**Comment by Usmaniatech** [comment]
So currently in the latest MLAgents repo 0.8.2 installs the 0.4.2 version of GYM Unity. Does it not support that version. I am following this link to train gridworld problem.
https://github.com/Unity-Technologies/ml-agents/tree/master/gym-unity
@ervteng

**Comment by ervteng** [comment]
@Usmaniatech, gridworld should work fine. Multi-agent might not though.

**Comment by harperj** [comment]
This issue has been inactive for some time, so I'm going to close it due to inactivity.  Feel free to reopen it if there's more to discuss.
