### ISSUE TITLE
Cannot connect with Academy on macOS Catalina

### ISSUE THREAD

**Issue by spaggi** [Unity-Technologies/ml-agents#2306]
**Describe the bug**
Specs: macOS Catalina, Unity 2019.1
When running my project, I'm getting the following error message:

„libgrpc_csharp_ext.x64.bundle“ kann nicht geöffnet werden, da Apple darin nicht nach Schadsoftware suchen kann.

-> Loosely translated: cannot be opened because Apple cannot search the file for malicious software

**To Reproduce**
1. Import ml-agents
2. Add Academy GO
3. Run Play

I'm unable to connect my mlagents-learn to Unity, I assume this is due to this

**Comment by spaggi** [comment]
To specify, it's this error:

https://www.fireebok.com/resource/how-to-fix-that-app-can-not-open-on-macos-catalina.html

Seems that the program libgrpc_csharp_ext.x64.bundle needs to be notarized

**Comment by ervteng** [comment]
Hi @spaggi, we can't comment on Catalina since it's unreleased. But you may have to disable some of the security settings in System Settings -> Security and Privacy, at least until libgrpc is updated for Catalina.

**Comment by spaggi** [comment]
Thanks for your response @ervteng. You can disable this check by disabling Gatekeeper with the following terminal command:

`sudo spctl --master-disable`

However I would advice to update libgrpc_csharp_ext.x64.bundle before Catalina becomes public, as every Mac user will face this issue then.

I'd love to help but this is beyond my knowledge unfortunately - I don't even understand what this bundle is....

**Comment by surfnerd** [comment]
Hi @spaggi,
Looks like we will need to code sign these binaries for use on macOS Catalina.  We'll update you when we have done so.  Thanks for the report!

**Comment by surfnerd** [comment]
Hey @spaggi,
I now have Catalina installed on my machine and have not run into these issues.  If you can still reproduce this issue, please reopen this issue. Thanks for your input.
