### ISSUE TITLE
Custom ops

### ISSUE THREAD

**Issue by iBicha** [Unity-Technologies/ml-agents#2310]
Are customs ops possible?
Something like https://www.tensorflow.org/lite/guide/ops_custom
I've seen #2281 but I wanted to make sure.

**Comment by ervteng** [comment]
Custom ops will work during training and inference using Python. Currently they're unsupported in the Unity Inference Engine (Barracuda), though.

**Comment by iBicha** [comment]
It would be interesting to have Barracuda extensible this way.

**Comment by mantasp** [comment]
Currently there are no specific plans for custom ops, but there is plan to open more of the source code. So it might be possible to insert custom code in the future.
