### ISSUE TITLE
.nn model conversion with tensorflow_to_barracuda.py problems

### ISSUE THREAD

**Issue by AkhilRaja** [Unity-Technologies/ml-agents#2318]
I am trying to create a .nn openpose model by using an openpose.pb model and use it with the barracuda worker factory and use the model without having to create a plugin for android or ios. 

I am encountering the following error on using the conversion script

> Converting openpose.pb to Models/openpose.bytes
IGNORED: Shape unknown layer
IGNORED: Pack unknown layer
Traceback (most recent call last):
  File "tensorflow_to_barracuda.py", line 26, in <module>
    tf2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
  File "/Users/apappu/Downloads/ml-agents-master/ml-agents/mlagents/trainers/tensorflow_to_barracuda.py", line 1537, in convert
    i_model, args
  File "/Users/apappu/Downloads/ml-agents-master/ml-agents/mlagents/trainers/tensorflow_to_barracuda.py", line 1366, in process_model
    nodes, var_tensors, const_tensors, o_context
  File "/Users/apappu/Downloads/ml-agents-master/ml-agents/mlagents/trainers/tensorflow_to_barracuda.py", line 472, in <lambda>
    inputs[0],
IndexError: list index out of range
> 

Is there any other image detection or posenet .nn model that I could try out if my methods are wrong  ? 

**Note**: The ML-Agents team has limited resources for education and community discussion.  We'll participate as we are able, but encourage members of the community to support one another to discuss and support one another.

**Comment by Deepak-HpyAda** [comment]
Hi bro,
Please follow this first
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation-Windows.md

Install all the requirements.
Then Clone the project to your location..

then follow this step 
**Converting TensorFlow and ONNX models to Barracuda format**
here
https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Plugins/Barracuda.Core/Barracuda.md

All the best

**Comment by AkhilRaja** [comment]
The error posted is after i followed the steps mentioned in the blog. @Deepak-HpyAda  I got the errors after doingg all the steps mentioned in the blog and further. @xiaomaogy  I cannot repoen the issue, could you please do that and discuss further on how to solve this issue ? I see a lot of people facing similar issues.

**Comment by xiaomaogy** [comment]
@mantasp

**Comment by mantasp** [comment]
@AkhilRaja could you please share your model?
