### ISSUE TITLE
UnityAgentsException: The tensorflow graph needs an input for epsilon  of type DT_FLOAT ??

### ISSUE THREAD

**Issue by mikecann** [Unity-Technologies/ml-agents#232]
Hi Guys,

I have just trained a simple agent for my game, training seems to have gone okay. So as usual I exported the model and tried to import it into my game. I set the Brain to internal, drag the .bytes file into the correct area (like I have done on previous projects) then press play and I get the following exception:

```
UnityAgentsException: The tensorflow graph needs an input for epsilon  of type DT_FLOAT
CoreBrainInternal.DecideAction () (at Assets/ML-Agents/Scripts/CoreBrainInternal.cs:285)
Brain.DecideAction () (at Assets/ML-Agents/Scripts/Brain.cs:332)
Academy.DecideAction () (at Assets/ML-Agents/Scripts/Academy.cs:249)
Academy.RunMdp () (at Assets/ML-Agents/Scripts/Academy.cs:342)
Academy.RunMdp () (at Assets/ML-Agents/Scripts/Academy.cs:333)
Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:259)
```

Any idea what this means? What am I missing?

**Comment by wouterhardeman** [comment]
As explained [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Getting-Started-with-Balance-Ball.md#embedding-the-trained-model-into-unity), you need to add the placeholder float value 'epsilon' when using a continuous action space. 👍

**Comment by mikecann** [comment]
Ahh yes! So sorry, I must have done that on my last examples but totally forgot about it. 

Much appreciated!
