### ISSUE TITLE
Can the game know if currently it's being trained or using a trained model but not training?

### ISSUE THREAD

**Issue by XBLDev** [Unity-Technologies/ml-agents#233]
Hi

Is there anyway the game/Unity 3D can know if python is training a model or using a trained model but not training? 

I want to reset my goal in Unity 3D in different ways based on whether it is being trained: if it's being trained the goal resets in one way, and if it's not being trained it resets in another way.

In Jupyter Notebook I can set "LoadModel" to True and "Training" to False, but I don't think the RL Agent knows that? I've read through the code base for Academy, Communicator, Brain, Agent etc, and I don't think that's mentioned anywhere, maybe I missed something.

Thanks in advance for answers!

**Comment by mikecann** [comment]
Couldn't you just look for the Brain and check its "Brain Type" property?

**Comment by MarcoMeter** [comment]
Hi @XBLDev 
you can check the `isInference` property of the Academy. It is true if the models is being used for prediction and not training.

**Comment by awjuliani** [comment]
@MarcoMeter's answer is the correct one. We added the `isInference` property exactly for this purpose. It is also possible to check for an external brain, but that brain could be in inference mode, and as such isn't quite as reliable. 

Hope that makes things clear for you, @XBLDev.

**Comment by XBLDev** [comment]
Hey @MarcoMeter @awjuliani Thanks for the reply!
