### ISSUE TITLE
Barracuda: Incorrect Clip parameters when converting from ONNX.

### ISSUE THREAD

**Issue by danielrothmann** [Unity-Technologies/ml-agents#2336]
**Description**
I have a model based on MobilenetV2 built and trained with PyTorch, subsequently converted to the ONNX format. I have converted the model to a .nn using `onnx_to_barracuda.py` which runs without errors.

The model loads and runs fine using the Barracuda plugin in Unity. However, the `Clip` activations seem to have gotten the parameters `min=1, max=0`. For this reason, these layers always produce ones regardless of input. 

Looking through the ONNX specification for this model, the parameters should be `min=0, max=6`. 

I suspect this issue is related to model conversion but looking through `onnx_to_barracuda.py` it is not clear to me how parameters are assigned to the activations during conversion.

If you can give me a pointer on where to start with the conversion script, I am happy to have a look for myself! Let me know if you 

**To Reproduce**
1. Save a PyTorch model using a pretrained MobilenetV2 model from Torchvision.
2. Export this model to ONNX.
3. Run `onnx_to_barracuda.py` on ONNX model.
4. Run the .nn model in Unity using Barracuda with the Worker in verbose mode.

**Environment:**
- Training+conversion: Debian GNU/Linux 9. 
- Inference: Unity3D on Windows 10.
- Barracuda version: 0.2.4

**Comment by mantasp** [comment]
CC: @rejunity

**Comment by janimator0** [comment]
I am also trying to get a PyTorch model to load into an MLAgent. I got stuck after converting to Onnx then Barracuda. After completing the conversion successfully I noticed I was not able to drag the model into the MLAgents inspector.

Is this "Barracuda" plug-in the solution to my problem? Does it allow MLAgents to accept Barracuda models?
