### ISSUE TITLE
How to use Barracuda ML agents in unity with the .nn Model

### ISSUE THREAD

**Issue by Deepak-HpyAda** [Unity-Technologies/ml-agents#2337]
Hi, 

The conversion of **.pb file to .nn file** is successfully done.
So, I have .nn file with me now.

I'm using this model **.nn file** in unity to detect with TENSORFLOW.
My issue here is "How to detect the model in the script?"
I tried with the Input array value and output array value.

I followed this procedure to do...

https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Plugins/Barracuda.Core/Barracuda.md

I'm not able to figure out how to use them in my script.
Unity comes up with this error : 

**Kernel TextureToTensor is missing
Barracuda.ComputeFunc..ctor (UnityEngine.ComputeShader[] cs, System.String kn) (at <6ba7dff58fb8417ba62c5da08dee7ed8>:0)
Barracuda.ComputeFunc..ctor (UnityEngine.ComputeShader cs, System.String kn) (at <6ba7dff58fb8417ba62c5da08dee7ed8>:0)
Barracuda.ReferenceComputeOps.TextureToTensorData (Barracuda.TextureAsTensorData texData, System.String name) (at <6ba7dff58fb8417ba62c5da08dee7ed8>:0)
Barracuda.ReferenceComputeOps.Pin (Barracuda.Tensor X) (at <6ba7dff58fb8417ba62c5da08dee7ed8>:0)
Barracuda.ReferenceComputeOps.Prepare (Barracuda.Tensor X)**

**Comment by mantasp** [comment]
How did you integrate Barracuda in your project? And what platform are you targeting?
