### ISSUE TITLE
[Solved] Error while running the "Basics" notebook

### ISSUE THREAD

**Issue by andreaBassich** [Unity-Technologies/ml-agents#234]
When I run the Basics notebook on my environment, it raises the following exception when line 8 is executed:
UnityActionException: The episode is completed. Reset the environment with 'reset()'

How would i go about fixing this?

**Comment by awjuliani** [comment]
Hi @andreaBassich,

This message simply means that the episode ended (either because the global done flag was set, or the max number of steps in the academy was reached), and that you need to call `env.reset()` to reset it.

**Comment by andreaBassich** [comment]
Turns out all the issues I've been having were because for some reason at the end of the AgentReset method i decided to set done = false. Thank you for your help.
