### ISSUE TITLE
Issues with training (not responsive after 10 min)

### ISSUE THREAD

**Issue by fast8wild** [Unity-Technologies/ml-agents#235]
As the title suggest, after attempting to train the AI for about 10 min, the program becomes irresponsive, slowing down my pc in the process with no more updates being registered in the Jupyter notebook. I have no idea what is causing this issue, but im willing to provide any necessary information in order to get a solid answer.

**Comment by awjuliani** [comment]
Hi @fast8wild,

Can you try training with a new build of your environment that has the `Time Scale` property of `Training Configuration` under the Academy's inspector window set to something less than 100, such as 5 or 10?

**Comment by fast8wild** [comment]
Hi @awjuliani,
I actually have the Time Scale property set to 1 so I don't think that's what is causing the issue. I'll try 5 or 10 right now though just to be sure.

**Comment by vincentpierre** [comment]
It could be a bug in the environment. Do you see the same behavior on the balance ball ? I would recommend playing in the editor with a player brain for a while an have an eye on the profiler to make sure there are no issues.

**Comment by fast8wild** [comment]
So after a lot of tinkering I found out that the problem does indeed lie with the environment. It is actually a puzzle game clone, and as a result there are a lot of object instating and destroying, which caused the performance issues I described earlier. Due to the nature of this game object pooling is not an option, so I will be looking into how to properly optimize this situation.

**Comment by awjuliani** [comment]
Glad you were able to track down the issue. Hopefully you are able to find a fix. I am going to close the issue for now, since it seems to not be ML-Agents specific.
