### ISSUE TITLE
Transfer Learning

### ISSUE THREAD

**Issue by ScriptBono** [Unity-Technologies/ml-agents#2357]
I would like to achieve a simple transfer learning. My idea is to train on a source task and then use the `--load` parameter to continue learning on the target task. The questions I have now are:

Is there a way to reset the number of steps to 0 instead of continuing training at the last point in time?  

Or is there another way to copy the final weights of the neurons and use them as initial values for a new model?

**Comment by harperj** [comment]
Hi @ScriptBono -- unfortunately we don't currently have a way to do either of these.  It sounds useful, so I will bring it up to the team.

**Comment by tatolevicz** [comment]
Hey @ScriptBono I think you can do a little trick that is to increase the number of steps in the trainer_config.yaml of that brain and keep training from there.

**Comment by surfnerd** [comment]
Hi @ScriptBono,
Thanks for your feedback.  We have logged this request internally as ID MLA-82.  We will be closing this issue for now, and will update this issue when we have any updates to share.

**Comment by idenc** [comment]
Is there any update on transfer learning with ml-agents?
