### ISSUE TITLE
Kernel TextureToTensor is missing MLAgents

### ISSUE THREAD

**Issue by faizanophobia** [Unity-Technologies/ml-agents#2363]
Hey there,
I am trying implement my pre trained tensorflow model into unity for object detection.I used the https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Plugins/Barracuda.Core/Barracuda.md method for conversion.
I am using .nn model now with a .txt file.
But it throws this error
**ArgumentException: Kernel TextureToTensor is missing
Barracuda.ComputeFunc..ctor (UnityEngine.ComputeShader[] cs, System.String kn) (at <6ba7dff58fb8417ba62c5da08dee7ed8>:0)
Barracuda.ComputeFunc..ctor (UnityEngine.ComputeShader cs, System.String kn) (at <6ba7dff58fb8417ba62c5da08dee7ed8>:0)
Barracuda.ReferenceComputeOps.TextureToTensorData (Barracuda.TextureAsTensorData texData, System.String name) (at <6ba7dff58fb8417ba62c5da08dee7ed8>:0)
Barracuda.ReferenceComputeOps.Pin (Barracuda.Tensor X) (at <6ba7dff58fb8417ba62c5da08dee7ed8>:0)
Barracuda.ReferenceComputeOps.Prepare (Barracuda.Tensor X) (at <6ba7dff58fb8417ba62c5da08dee7ed8>:0)
Barracuda.GenericWorker.AddInput (System.String name, Barracuda.Tensor x) (at <6ba7dff58fb8417ba62c5da08dee7ed8>:0)
Barracuda.GenericWorker.Execute (System.Collections.Generic.IDictionary`2[TKey,TValue] inputs) (at <6ba7dff58fb8417ba62c5da08dee7ed8>:0)** even after initialising the inputs.
Also I am using webcam for detection.
The version for unity and mlagents is right.
**What exactly should be defined for TextureToTensor?**

Thank You

**Comment by Deepak-HpyAda** [comment]
I have the same issue 

https://github.com/Unity-Technologies/ml-agents/issues/2337

**Comment by faizanophobia** [comment]
Thanks for replying.
Which model did you deploy for training your data?
**As the Mobilenet+SSD is currently not supported by inference engine.**
I tried with a different model as well but the same error persists though!

**Comment by mantasp** [comment]
@faizanophobia how did you integrate Barracuda into your project? And what platform are you targeting?

**Comment by faizanophobia** [comment]
Hi @mantasp I have cloned the github file from the link provided by Unity i.e.https://github.com/Unity-Technologies/ml-agents 
Also I got my code by referring to the **LearningBrain** script available in the examples bundle. I am trying to access webcam input and using the nn model along with a labels TextFile using the  **model** & **worker** API from https://github.com/Unity-Technologies/ml-agents/blob/e3b86a27a2547cdd177bf9e848b4337aa71b887a/UnitySDK/Assets/ML-Agents/Plugins/Barracuda.Core/Barracuda.md 
Now I have my code loading my trained model and creating model but when it comes to 
**worker.Execute(inputs);** 
It throws the error as posted above.
My target platform is iOS.

**Comment by RobertoE90** [comment]
same problem here

**Comment by mantasp** [comment]
@RobertoE90 this error usually means that GPU compute is disabled on your platform. If you see this happening on Android device, please check your Player Settings and make sure that either Vulkan on GLES 3 is picked as preferred GFX API. In case it's GLES 3, please also make sure that "Requires GLES 3.1" checkbox is also checked.
If you see this error in Editor while Android platform is selected make sure that Edit->Graphics Emulation is set to "No Emulation" (sometimes editor restart might be needed after changing it)

**Comment by RobertoE90** [comment]
Hello @mantasp. Thanks for the response.
Done, and same error. Including Graphics Emulation set to No Emulation.

Also if I switch to Standalone or Windows Universal Platform I get 
![image](https://user-images.githubusercontent.com/35074359/67007470-7558a000-f0b5-11e9-921a-c7b38c576f1e.png)

Does that mean that my model is not supported by barracuda?
