### ISSUE TITLE
capturing custom statistic for agent actions while training?

### ISSUE THREAD

**Issue by gameanimation3d** [Unity-Technologies/ml-agents#2368]
Is it possible to write out custom values for agent action statistic in tensorboard or in a csv way out of unity.
For example to see how often the Agent hit a wall or the ball has flown over net relative the reward.
This would allow for better diagnoising and debugging the training over graphs.
Writing out an csv and counting the values while training for every training instance isn't a problem.

Which function or event can be used to write out these values every 1.000 steps aliging with the tensorboard statistic.
Because the Agent Done() function terminates only one episode which can consists of many different steps.
Would be amazing if somebody could help or have an idea on that.

**Comment by harperj** [comment]
Hi @gameanimation3d -- unfortunately we don't have any function for adding custom stats within ML-Agents at this time.  I think this is a good suggestion for the future and we'd welcome the contribution if you end up adding this functionality.

**Comment by chriselion** [comment]
Sorry for the late notice, but added support for custom metrics in tensorboard a few months ago. See the StatsRecorder (which is part of the Academy): https://github.com/Unity-Technologies/ml-agents/blob/latest_release/com.unity.ml-agents/Runtime/StatsRecorder.cs
