### ISSUE TITLE
When is nn optomized

### ISSUE THREAD

**Issue by EnthusedDragon** [Unity-Technologies/ml-agents#2379]
Describe what you'd like to discuss.

**Note**: The ML-Agents team has limited resources for education and community discussion.  We'll participate as we are able, but encourage members of the community to support one another to discuss and support one another.

**Comment by awjuliani** [comment]
Hi @EnthusedDragon 

Can you please provide detail in your issue? It seems that you simply copied the template without changing anything.

**Comment by EnthusedDragon** [comment]
Hey,
I must have accidentally clicked submit.

I found my answer. :)
