### ISSUE TITLE
Can I change brain's model in script(rumtime)?

### ISSUE THREAD

**Issue by hanseoup** [Unity-Technologies/ml-agents#2382]
Describe what you'd like to discuss.

**Note**: The ML-Agents team has limited resources for education and community discussion.  We'll participate as we are able, but encourage members of the community to support one another to discuss and support one another.

![image](https://user-images.githubusercontent.com/53593292/62346100-d1d50600-b52f-11e9-9fe3-0763e450da9b.png)

I want to make a my custom auto self training system. 
so, I want to know the way to change the model of brain in script. 
I already knew that i can change brain object, that has pre-loaded model, in script by 
using "GiveBrain( )" function(in wall Jump example). But I want to change model of Brain(.nn file) in script! Is it possible?(I can't find any member variable or function related with this issue)

**Comment by gzrjzcx** [comment]
Same problem.
What I do now is creating more brains to load different models.

**Comment by awjuliani** [comment]
Hi @hanseoup 

It is possible to change the model. You will need to access the brain object, and change the model property. This is not an officially documented part of ML-Agents, but there is nothing which prevents this. I would however suggest that the simpler method is to use multiple brains with different models, and switch them that way, as each brain is meant to correspond to a specific behavior.

**Comment by hanseoup** [comment]
Ah! I just found that there is "LearningBrain" class... And It has model property :)  (but not in Brain class) Thank you
