### ISSUE TITLE
Azure and Headless Linux Builds

### ISSUE THREAD

**Issue by MikeWise2718** [Unity-Technologies/ml-agents#2386]
Documentation bug:

 the using ml-agents on Azure asks you to build a linux exe with headless mode checked, but that was removed in 2018.3. 

You now need to simply start the build using the **-nographics** and **-batchmode** flag. 

link: [ml-agents on Azure](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-on-Microsoft-Azure.md)

The doc should cover this, it takes awhile to figure it out as it is not that common a scenario, and might otherwise force people to get a much more expensive GPU equiped DSVM which is neither necessary or advantageous for training.

**Comment by brandonhotdog** [comment]
Alternatively you can specify "--no-graphics" as an option to the ml-agents command. But yeah that should be put into the Azure docs.

**Comment by MikeWise2718** [comment]
Err, yeah, that is actually what I did. The other options are for running the command line version of unity directly, as opposed to letting the python wrapper do it.

**Comment by unityjeffrey** [comment]
thanks @MikeWise2718 for catching this. would you be open to updating the document on the develop branch and opening a PR?  https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-on-Microsoft-Azure.md document?
