### ISSUE TITLE
RayPerception2D returns 0 observations

### ISSUE THREAD

**Issue by AidinD** [Unity-Technologies/ml-agents#2388]
**Describe the bug**
RayPerception2D returns 0 observations.

**To Reproduce**
1. Add a RayPerception2D component to the agent
2. Use rayperception.Perceive in your agent script

Expected:
Number of observations to return be rayAngles*(2 + detectableTargets)

Actual:
Number of observations returned = 0

Vector observation size mismatch ... received 0

**Environment (please complete the following information):**
Running on Windows 10 and tried on Unity 2019.1x and 2019.2.0
Using ml agents Release v0.9.0

When using RayPerception2D in a 2D project I don't seem to be getting any observations. However, if I don't change anything except changing the component on the agent to be a RayPerception3D instead, I get the expected amount of observations.

With code below I received 3 observations when using RayPerception3D and 0 with RayPerception2D.

`

    public override void CollectObservations() {

        float rayDistance = 20f;   
        float[] rayAngles = { 90f };    
        string[] detectableObjects = { "wall" };
        AddVectorObs(rayPerception.Perceive(rayDistance, rayAngles, detectableObjects, 0f, 0f));

    }
`

**Comment by awjuliani** [comment]
Hi @AidinD 

Just to confirm, when you use the 2D ray perception, you don't pass those additional two zero float values, correct?

**Comment by AidinD** [comment]
Oh dear...my bad as I was actually sending in those two additional values... Thanks for pointing that out.
But why isn't it giving me an error saying it can't find an overloaded method for those parameters?

**Comment by awjuliani** [comment]
This is because it is defaulting to the base class method which simply returns 0 https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Examples/SharedAssets/Scripts/RayPerception.cs

**Comment by AidinD** [comment]
I see, well thank you again for pointing out my mistake.
