### ISSUE TITLE
Demonstration Recorder, Camera Resolutions: 0 

### ISSUE THREAD

**Issue by mbaske** [Unity-Technologies/ml-agents#2395]
Hi - When recording an agent with cameras, the resulting .demo file's info says `Camera Resolutions: 0`

I ran the Visual Pyramids example with the VisualPyramidsPlayer brain. Logging the `brainProto` object in the `DemonstrationStore.WriteBrainParameters` method shows

`{ "numStackedVectorObservations": 1, "vectorActionSize": [ 5 ], "cameraResolutions": [ { "width": 84, "height": 84 } ], "vectorActionDescriptions": [ "" ], "brainName": "VisualPyramidsPlayer" }`

So the camera appears to be there... Is this just an issue with displaying the correct .demo info in the inspector? Or are camera feeds actually being ignored during recording?

Windows 10, ml-agents v0.9

**Comment by awjuliani** [comment]
Hi @mbaske 

Thanks for bringing this to our attention. The visual observations are indeed being recorded, there is just an issue with correctly reporting the resolution in the inspector.

**Comment by mbaske** [comment]
> The visual observations are indeed being recorded

Thanks @awjuliani, good to know.

**Comment by chriselion** [comment]
@mbaske This was fixed on the develop branch a few weeks ago, and the fix is in version 0.10.0. Closing this issue.
