### ISSUE TITLE
TFException: Shape [-1,24] has negative dimensions

### ISSUE THREAD

**Issue by sterlingcrispin** [Unity-Technologies/ml-agents#24]
I was running a training session in the PPO notebook and stopped it , then exported the graph 
```
INFO:tensorflow:Restoring parameters from ./models/ppo/model-400000.cptk
Converted 4 variables to const ops.
20 ops in the final graph.
```
but when I use this .bytes file in Unity I get

`TFException: Shape [-1,24] has negative dimensions
	 [[Node: epsilon = Placeholder[dtype=DT_FLOAT, shape=[?,24], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
TensorFlow.TFStatus.CheckMaybeRaise (TensorFlow.TFStatus incomingStatus, System.Boolean last) (at <6ed6db22f8874deba74ffe3e566039be>:0)
TensorFlow.TFSession.Run (TensorFlow.TFOutput[] inputs, TensorFlow.TFTensor[] inputValues, TensorFlow.TFOutput[] outputs, TensorFlow.TFOperation[] targetOpers, TensorFlow.TFBuffer runMetadata, TensorFlow.TFBuffer runOptions, TensorFlow.TFStatus status) (at <6ed6db22f8874deba74ffe3e566039be>:0)
TensorFlow.TFSession+Runner.Run (TensorFlow.TFStatus status) (at <6ed6db22f8874deba74ffe3e566039be>:0)
CoreBrainInternal.DecideAction () (at Assets/ML-Agents/Scripts/CoreBrainInternal.cs:244)
Brain.DecideAction () (at Assets/ML-Agents/Scripts/Brain.cs:308)
Academy.DecideAction () (at Assets/ML-Agents/Scripts/Academy.cs:250)
Academy.RunMdp () (a`

not sure why this has a -1 value, I've stopped training prematurely on the Ball3D demo without any problems, anyone have any ideas?

**Comment by vincentpierre** [comment]
Hi, Thank you for you question. It seems to me that you forgot to add a custom placeholder in your Internal Brain. In [Embedding the trained model itself](https://github.com/Unity-Technologies/ml-agents/wiki/Getting-Started-with-Balance-Ball#embedding-the-trained-model-itself) it says you need to add a float placeholder called `epsilon` with values ranging from 0 to 0.
The inspector image [here](https://github.com/Unity-Technologies/ml-agents/wiki/Agents-Editor-Interface#internal-brain) might help.

**Comment by awjuliani** [comment]
Please let us know if you are able to get the epsilon parameter to work for you to run the agent natively.

**Comment by sterlingcrispin** [comment]
Ah yep sure enough that's the problem. I remember setting that on the Ball3Ddemo but overlooked it on my own scene, it would be awesome if there was a warning about that built in

**Comment by codmw44** [comment]
I have similar issues with "Shape [-1,24] has negative dimensions", and after set "graph placeholders" like in Ball3D I get from unity console this error: TFException: Attempting to use uninitialized value dense/kernel
	 [[Node: dense/kernel/read = Identity[T=DT_FLOAT, _class=["loc:@dense/kernel"], _device="/job:localhost/replica:0/task:0/cpu:0"](dense/kernel)]]
TensorFlow.TFStatus.CheckMaybeRaise (TensorFlow.TFStatus incomingStatus, System.Boolean last) (at <6ed6db22f8874deba74ffe3e566039be>:0)
TensorFlow.TFSession.Run (TensorFlow.TFOutput[] inputs, TensorFlow.TFTensor[] inputValues, TensorFlow.TFOutput[] outputs, TensorFlow.TFOperation[] targetOpers, TensorFlow.TFBuffer runMetadata, TensorFlow.TFBuffer runOptions, TensorFlow.TFStatus status) (at <6ed6db22f8874deba74ffe3e566039be>:0)
TensorFlow.TFSession+Runner.Run (TensorFlow.TFStatus status) (at <6ed6db22f8874deba74ffe3e566039be>:0)
CoreBrainInternal.DecideAction () (at Assets/ML-Agents/Scripts/CoreBrainInternal.cs:244)
Brain.DecideAction () (at Assets/ML-Agents/Scripts/Brain.cs:308)
Academy.DecideAction () (at Assets/ML-Agents/Scripts/Academy.cs:250)
Academy.RunMdp () (at Assets/ML-Agents/Scripts/Academy.cs:337)
Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:260)

Maybe I make mistakes in get Graph Model after learning?
![image](https://user-images.githubusercontent.com/10564511/30916702-b87db544-a3a2-11e7-9848-fc9757ab4a22.png)
