### ISSUE TITLE
Curriculum Learning - How can I properly use it?

### ISSUE THREAD

**Issue by srcnalt** [Unity-Technologies/ml-agents#240]
Hello, since many people are asking how-tos here I won't hesitate.

I wanted to try curriculum learning on a simple project but failed to get it working. Then tried to train [wall](https://github.com/Unity-Technologies/ml-agents/tree/master/unity-environment/Assets/ML-Agents/Examples/Area) example since it was the main example given for cirruculum learning feature in the Unity's [blog](https://blogs.unity3d.com/2017/12/08/introducing-ml-agents-v0-2-curriculum-learning-new-environments-and-more/). Sadly it did not work as well.

Even though `last_reward `exceeds the value from json file as threshold ppo does not switch lessons. I debbugged and compared the numbers from `env._curriculum.data['thresholds'][env._curriculum.lesson_number]` it did exceed, but to call `env.reset` I will need `env.global_done` set to `true`. My assumption is `global_done` is the done variable of academy class. At this point I got lost, since I am supposed to reach curriculum json content from ppo but need to decide when to mark academy done from unity project.

I am most probably missing something but example project not working made me dig into .py files and investigate. I'd love to get some help on this if possible.

**Comment by vincentpierre** [comment]
When using curriculum learning, the environment must reset (so the parameters of the environment can be changed). This means that the academy must reset (you are right) and it is not enough to reset the agents. Usually, one sets the `Max Steps` in the academy inspector to a non-zero value. When the academy resets, all agents reset as well. In some scenarios, you can also have the academy reset when certain conditions are met (game over) this is where you would set the done flag of the academy to true. The wall example has a Max Steps parameters of 50000 for me. Maybe you need to wait longer for the academy to reset with the proper parameters ? I hope this helps. Let us know.

**Comment by srcnalt** [comment]
Thank you @vincentpierre, the solution is the academy `max steps` value. From the json file I expected ppo to do the academy resetting and switch the lesson when `last_reward` exceeds the threshold given in the json file. I'd like this implemented in the future releases actually, but some lucky reward spikes might get the lesson switched too early.

**Comment by billatarcat** [comment]
Somewhat related issue ... I am an ML and Python newb and I am not hooking up the academy parameters correctly.  I am getting this error:
`UnityEnvironmentException: The parameter <parameter name> in Curriculum <JSON filename> is not present in the Environment`
I know I am forgetting something simple.  Thanks for the help.

**Comment by zstbackcourt** [comment]
> 
> 
> Somewhat related issue ... I am an ML and Python newb and I am not hooking up the academy parameters correctly. I am getting this error:
> `UnityEnvironmentException: The parameter <parameter name> in Curriculum <JSON filename> is not present in the Environment`
> I know I am forgetting something simple. Thanks for the help.



> 
> 
> Somewhat related issue ... I am an ML and Python newb and I am not hooking up the academy parameters correctly. I am getting this error:
> `UnityEnvironmentException: The parameter <parameter name> in Curriculum <JSON filename> is not present in the Environment`
> I know I am forgetting something simple. Thanks for the help.

Hey dear bro,I have met the same problem,have u ever solved it?

**Comment by billatarcat** [comment]
Hey,

I did not fix this.  I ended up making my own learning code.  It works,
basically, the way the unity code worked.  But, I gave up on this all soon
after.  On to other side jobs.  Sorry, I can't help you.

Good luck,

Bill
