### ISSUE TITLE
/usr/bin/python: No module named object_detection GCloud Platform

### ISSUE THREAD

**Issue by faizanophobia** [Unity-Technologies/ml-agents#2403]
Hi there,
I am training a custom object detection model through google cloud sdk following https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193 , https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md/the data is successfully added into the bucket and all the commands worked without any errors, but when I arrived to the training step and submited the data to gcloud it throws this error everytime
 **/usr/bin/python: No module named object_detection**
**Command '['python', '-m', u'object_detection.model_tpu_main', u'--tpu_zone', u'us-central1', u'--model_dir=gs://tftraining/train', u'--pipeline_config_path=gs://tftraining/data/pipeline.config', '--job-dir', u'gs://tftraining/train']' returned non-zero exit status 1.**
It's not able to find the directory of the folder.
The tensorflow **python object_detection/builders/model_builder_test.py** test also ran successfully in the **Command Line**
I have set the PYTHONPATH as **export PYTHONPATH=$PYTHONPATH:/Users/new/Downloads/TensorFlow/models/research:/Users/new/Downloads/TensorFlow/models/research/slim**
I compiled the proto using the commands from the same website.I tried with deploying the object_detection folder in the python/lib/site-packages but didn't resolve.
Also ran python build and setup in the research folder but the issue still persists.

**Comment by owi160152** [comment]
Hi @faizanophobia how did you resolve this issue?
