### ISSUE TITLE
Is there any recommended way to load .nn file from external directory of Unity(not in "Asset" folder)

### ISSUE THREAD

**Issue by hanseoup** [Unity-Technologies/ml-agents#2407]
Hi :)
I have plan to make my custom self training system with ml-agent.
and I've made simple Battle environment. (1 vs 1) 
The self training system's step that i can imagine now is following. 

step 1. prepare 2 brain objects ( learningBrain, fixedLearnedBrain )and give same pre-trained model (model_v1.nn file) 

step 2. set condition that only "learningBrain" can learn, but "fixedLearnedBrain" can't. And If it reaches some condition (ex. Agent1[learningBrain] has win rate over 55% to Agent2[fixedLearnedBrain] ) Save this model as "model_v2.nn" 

step 3. repeat step1, step 2 until I can get "model_vN.nn" that i want.  

But I have problem at step 2. A trained model(.nn file) is saved in outside of "Asset" folder...
So I can't use Resources.Load( ) to load model(.nn file) as Unity Asset properly. 

Is there any recommend way to solve this issue?
In addition, i want to make my custom self training system that can be training through 
build program(.exe) for running multiple experiments at the same time. 

so, this build program might get model(.nn file) from external path(~/ml-agents/models/simpleBattle/simpleBattleLearning.nn) and set this model 
to Agent1, Agent2 each. and can run step1~3 "automatically!"

please give me your advice :)

**Comment by hanseoup** [comment]
Oh..! my team leader has just found that we can load model(.nn file) from external folder of unity("Asset" folder) !
Here is one of solution he told me! :)
![image](https://user-images.githubusercontent.com/53593292/62691010-bc1c8080-ba08-11e9-9c61-35da364514e9.png)
1. we use "WWW" to load external file(.nn file) 
2. and extract byte[] by using "www.bytes"
3. and just set equal to (Barracuda.NNModel)preloadedModel.Value !
4. It works!
![image](https://user-images.githubusercontent.com/53593292/62691454-afe4f300-ba09-11e9-99d4-264fc7dc54d9.png)
It would be possible "NNModel" class only have its byte array(byte[] value)!

But i still need your advice about "auto self training system"(build program version!)

**Comment by ervteng** [comment]
You might be able to pass through the path to the .nn file as a reset parameter, and trigger a model reload on reset, then call the reset with the right path from Python. 

Related: a fellow contributor implemented self-play in ML-Agents, you can check out his branch here: https://github.com/Unity-Technologies/ml-agents/pull/1975

**Comment by surfnerd** [comment]
Hi,
Thank you for the discussion.  This conversation seems to be idle so we will close it for now.  Feel free to reopen it if you have further questions related to this topic.
