### ISSUE TITLE
Issue with barracuda and 'Compute' worker on not supporting gpu mobile

### ISSUE THREAD

**Issue by olympus12** [Unity-Technologies/ml-agents#2417]
**Describe the bug**
During barracuda runtime I get the following message:
"compute shaders are not support on current platform. falling back to csharpfast"

**To Reproduce**
Run barracuda on mobile device using **Compute** worker type.

**Environment (please complete the following information):**
Huawei Honor running on Kirin 620, emui 4.1.3.
Barracuda 0.2.4
Android

**NOTE:**
The barracuda worker works with CSharp as I select it manually.
It seems like it tries to change the worker to CSharpFast, but it doesn't work afterwards.

As much as I'm acknowledge with barraduca - it CSharpFast have changed to CSharp, 
I would suggest that fixing this reference would solve the problem.

**Comment by ervteng** [comment]
Adding @mantasp

@olympus12, does Barracuda work with desktop/Windows/Mac builds in your setup?

**Comment by olympus12** [comment]
Hi Ervin,
Barracuda works with Editor (Windows) and both Android and iOS builds. It
tested with different devices, but this specific phone model didn't work
with "Compute" worker, so I had to change it to "CSharp".

**Comment by mantasp** [comment]
@olympus12 Kirin 620 comes with old generation Mali450 GPU, which doesn't support OpenGL ES 3.1 / Compute Shaders, so Barracuda won't work on this GPU.
