### ISSUE TITLE
'command line arguments' feature does not work 

### ISSUE THREAD

**Issue by Sohojoe** [Unity-Technologies/ml-agents#2418]
**Describe the bug**
The new feature 'support for command line arguments' #2243 does not work

**To Reproduce**
`mlagents-learn config/my_config.yaml --train  --run-id=my-id  --my-custom-opton=value`

**Environment (please complete the following information):**
- _ML-Agents version_: v0.9

**Notes / Observations**
* learn.py does not support options which are not defined in the `_USAGE` string. Its not clear if docopt supports this.
* learn.py does not pass options through to UnityEnvironment via `args`

**Comment by ervteng** [comment]
Hi @Sohojoe, big thanks for spotting this issue! It's an error on our part in the release notes - the PR enabled the parameters to be passable when creating a `UnityEnvironment` class, but it was never intended to pass down through `learn.py`. We're looking into doing this properly - but basically I would add a parameter to the docopt, turn it into a list of strings, and pass it into the `create_environment_factory` method in `learn.py`.

**Comment by chriselion** [comment]
This is fixed on develop and will be available in the next release. See https://github.com/Unity-Technologies/ml-agents/pull/2594
