### ISSUE TITLE
Question: Reward Per Step or at End?

### ISSUE THREAD

**Issue by raeldor** [Unity-Technologies/ml-agents#242]
Should rewards be per step or at the end for best results, and how does it affect the training.  For example I'm trying to teach my robot to walk.  I have at the moment a positive reward for forward movement and for keeping upright at each step.  If it falls over I reward -1 and terminate the episode.  Should I remote the positive forward reward per step and replace with a reward at the end dependent on distance?  How does this affect the training?

Thanks!

**Comment by MarcoMeter** [comment]
HI @raeldor 
signaling a reward for each step has to be done carefully. In general, the intent of deep reinforcement learning is to solve problems where rewards are sparse and delayed. Just try to avoid the pitfall of ending up doing supervised learning by trying to evaluate each step (that's what I mean by approaching this carefully, it's just the mindset). Instead of signaling a reward at the very end, you could add reward signals like checkpoints.

You can checkout this [related work](https://arxiv.org/abs/1707.02286) from DeepMind. They actually had a reward function for each step which is majorly based on the forward velocity.

**Comment by awjuliani** [comment]
Hi @raeldor,

As @MarcoMeter mentioned, what is typically done for locomotion tasks is a reward at every step which corresponds to forward velocity in the direction you'd like the agent to walk.

**Comment by raeldor** [comment]
Thanks for the response guys.  Just unsure how this affects training.  Ie, if I reward at the end (say, negatively -1 for failure), yet the steps leading up to it had a reward totalling more than +1 then does this mean the system sees this as an overall success even though it fell over?

**Comment by awjuliani** [comment]
@raeldor, The agent is always being reinforced to "do better," so to speak. If it receives 10 reward one episode and 11 another episode, it will adjust its actions in order to be more likely to get the 11 rather than the 10 going forward.

**Comment by raeldor** [comment]
So, does that mean that adding the rewards to a private variable each step and presenting at the end of the episode has the same result as presenting at each step?  Ie, When you assign rewards at each step it's not indicative of any particular behavior AT THAT POINT IN TIME?

**Comment by vincentpierre** [comment]
@raeldor I would say that if the agent does something worth rewarding before the end, you should reward it right away. There is no benefit to hold the rewards until the end if they were available earlier. But in a lot of cases, the reward are **ONLY** available at the end like in chess or go.
It is different to add rewards along the way and at the end. If the rewards are given along the way, it will be easier to assign credit to past actions.

**Comment by raeldor** [comment]
Ah, so rewards given along the way DO reflect actions close to the time the reward was given?  That's worth knowing.  Is there a time window that represents the actions that may have contributed to the reward?

**Comment by MarcoMeter** [comment]
Reinforcement Learning typically employs a value function, which approximates the cumulative expected future reward for tacking a certain action. Each reward for each step is multiplied by a discount factor (lambda). So if that factor is set to 1, the algorithm will take all future rewards into account whereas a factor of 0 takes only the immediate signal.

**Comment by raeldor** [comment]
Interesting.  Seems I need to dig under the covers a little more.  So, in relation to the overall reward for the episode.  My bot falling over returns a reward of -1 and terminates the episode.  But if the motion reward over the course of the episode totals to largers numbers, say over 30 on average does this means the falling over isn't really such a big penalty in comparison?  Should I be either penalizing more or reducing the step-based rewards?

**Comment by MarcoMeter** [comment]
That's totally fine. The algorithm always targets to maximize the expected future reward. If the agent is not able to achieve that, it might didn't explore the environment properly or it is not facing appropriate inputs. But in the end, reward signals are hyperparameters as well, which have to be tuned.
