### ISSUE TITLE
Problem with MLAgent and Anaconda

### ISSUE THREAD

**Issue by SirSundays** [Unity-Technologies/ml-agents#2423]
Hi guys,

im trying to get into Machine Learning and MLAgent. I got so far that im able to train something and look at what it does in tensorboard. But when I end the learning phase, I get an error. I can still look at the tensorboard charts and I get a .nn file. But im not able to drag this one into unity. 

```
`DONE: wrote ./models/penguin_02-0/PenguinoLearning.nn file.
INFO:mlagents.trainers:Exported ./models/penguin_02-0/PenguinoLearning.nn file
Traceback (most recent call last):
  File "c:\users\sariu\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)

  File "c:\users\sariu\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)

  File "C:\Users\sariu\Anaconda3\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>

  File "c:\users\sariu\anaconda3\lib\site-packages\mlagents\trainers\learn.py", line 319, in main
    run_training(0, run_seed, options, Queue())

  File "c:\users\sariu\anaconda3\lib\site-packages\mlagents\trainers\learn.py", line 118, in run_training
    tc.start_learning(env, trainer_config)

  File "c:\users\sariu\anaconda3\lib\site-packages\mlagents\trainers\trainer_controller.py", line 316, in start_learning

    env_manager.close()

  File "c:\users\sariu\anaconda3\lib\site-packages\mlagents\envs\subprocess_env_manager.py", line 219, in close

    env_worker.close()

  File "c:\users\sariu\anaconda3\lib\site-packages\mlagents\envs\subprocess_env_manager.py", line 62, in close

    self.conn.send(EnvironmentCommand("close"))

TypeError: __new__() missing 1 required positional argument: 'payload'`
```

I do not even know where to start with this error. Does anyone have seen this before or knows where I can search for a solution?

Versions:
Anaconda 4.3.14
tensorflow 1.7.1
tensorboard 1.7.0
mlagent 0.9.0
Unity 2017.4.10f

I hope someone here can help...

**Comment by SirSundays** [comment]
Updating Conda and/or Unity to a newer version do not help to fix this problem.

**Comment by SirSundays** [comment]
I fixxed it!
I just did the good old: "Hm dont know what this line does. Lets comment it out"-thing and after that it worked. I can now train my model and afterwards I can drag my model into unity and use it.

If someone else get this error:
Just change this file with the one I uploaded below
C:\Users\%YOUR_USERNAME%\Anaconda3\Lib\site-packages\mlagents\envs\subprocess_env_manager
[Typeerror Fix.zip](https://github.com/Unity-Technologies/ml-agents/files/3490222/Typeerror.Fix.zip)

**Comment by akTwelve** [comment]
Glad you fixed it, @SirSundays! For anyone else that hits this error but doesn't want to download the zip file, this was his workaround. Hopefully no big side effects. :)
subprocess_env_manager.py -- Comment out line 62:
```
    def close(self):
        try:
            #self.conn.send(EnvironmentCommand("close"))
        except (BrokenPipeError, EOFError):
            pass
        self.process.join()
```
He also added the note: 'In the official version this line is executed: self.conn.send(EnvironmentCommand("close")). In this unofficial version this isnt executed. Seems to work anyway. Have nice time with MLAgent. SirSundays'
