### ISSUE TITLE
Visual observation showing no learning , game like bubble shooter

### ISSUE THREAD

**Issue by narayan907** [Unity-Technologies/ml-agents#2424]
Hi,
i am working on a game similar to bubble shooter, for observation i am using visual observation,
using on demand request for decision and using vector action discrete for action with 120 values for angles and 2 values to switch ball, setting time scale at 5, i see no learning happening in training since the reward value remains mostly same even after 100000 steps of training.

**Comment by ervteng** [comment]
Hi @narayan907, what's your reward structure for the game? We do have some experience doing bubble shooters with ML-Agents (see https://blogs.unity3d.com/en/2019/04/15/unity-ml-agents-toolkit-v0-8-faster-training-on-real-games/ for an example) so in theory it's a learnable problem.

**Comment by narayan907** [comment]
hello @ervteng  , yes i have seen that blog of snoopy pop game, my reward structure looks like
0.001 for switching ball,
0.01*no of balls for match hit,
-0.001 for no match hit
I am training at 10 scale time, with one environment but i see no improvement in reward even after 150000 steps.
I have tried the multi environment concept, explained in blog but i see crashes happening in that.

**Comment by ervteng** [comment]
@narayan907 is there a reason you give a positive reward for switching? The agent will be incentivized to switch continuously. 

I'd try to simplify the problem a bit and see if it learns. For instance, you could reduce the angle number or make the game board smaller. Also, be sure to check your visual observations and make sure they're being read properly.

**Comment by narayan907** [comment]
Thanks @ervteng to reply,
How can i check visual observation output, where does the images get stored.

**Comment by ervteng** [comment]
They're sent over as numpy arrays - you can see them in the `environment.py` file. 

But usually just viewing the camera is enough.
