### ISSUE TITLE
Cannot read the last action during training.

### ISSUE THREAD

**Issue by srcnalt** [Unity-Technologies/ml-agents#243]
I set up my example to have 4 actions for movement, and in the inspector I set the default state to be 0 which goes to default case and returns. Here is how actions look, how it plays in heuristic mode and the code. (Academy frame to skip is 10 frames, thus default is returned)

![heuristic_4_action](https://user-images.githubusercontent.com/3163281/34846177-ffee03cc-f71f-11e7-8245-49bad291406f.PNG)

![heuristics_4_actions](https://user-images.githubusercontent.com/3163281/34846319-6e34b934-f720-11e7-9d87-2a56325b3981.gif)

```
switch ((int) action[0])
{
    case 1:
        rb.velocity = new Vector3(-velocity, 0, 0);
        break;
    case 2:
        rb.velocity = new Vector3(velocity, 0, 0);
        break;
    case 3:
        rb.velocity = new Vector3(0, 0, velocity);
        break;
    case 4:
        rb.velocity = new Vector3(0, 0, -velocity);
        break;
    default:
        return;
}
```

When I run it in this settings, the example never moves down which corresponds to last item of the action list.

![external_4_actions](https://user-images.githubusercontent.com/3163281/34846285-50981be6-f720-11e7-9739-6fab27980b71.gif)

But when I add a new action set to key none and value 5, then run it with the same code (where it still goes to the default state) it can actually move downwards.

![5_actions](https://user-images.githubusercontent.com/3163281/34846372-9ed125dc-f720-11e7-9f80-3d289943a129.PNG)

![external_5_actions](https://user-images.githubusercontent.com/3163281/34846484-0419838a-f721-11e7-9b25-7092bad81720.gif)

I tried it many times and getting the same results, never moving the last action. Will try to check this on other examples too.

**Comment by awjuliani** [comment]
Hi @srcnalt,

The `act[]` output of the network is indexed starting at 0, rather than 1. So if you have an action space of 5, then the `act[]` array should only ever contain numbers from 0 to 4.

**Comment by srcnalt** [comment]
Thank you @awjuliani as far I see from the single brain examples, `act[0]` keeps the value of the next action to take. I assumed, when I didn't have an action with the value of `0` the system would not appoint the value 0 to `act` array. The actual problem was C# `Random.Range` method in my decision class, I didn't notice it excluded the maximum parameter if parameters are integer. I better be more careful :0)
