### ISSUE TITLE
Offline Behavioral Cloning:  The provided demonstration is not compatible with the brain being used for performance evaluation.

### ISSUE THREAD

**Issue by tillmusshoff** [Unity-Technologies/ml-agents#2434]
Hi! I am trying to get my environment running with BC. I did everything like the Imitation Learning Guide suggested. I recorded a .demo file while playing with the PlayerBrain. Then I changed to the learning brain, checked "Control" and inserted the path to the demo file into the offline_bc_config.yaml. However, when I start the training in the editor or as a built I get this error:  "The provided demonstration is not compatible with the brain being used for performance evaluation." See the full error message in the screenshot below.

![b1f7f51475e8798472acabd037e2a8a0](https://user-images.githubusercontent.com/53266983/63000453-7846d280-be71-11e9-9337-6a43c1c714f2.png)

Unity also gives me this error: 
NullReferenceException: Object reference not set to an instance of an object
MLAgents.Batcher.SendAcademyParameters (MLAgents.CommunicatorObjects.UnityRLInitializationOutput academyParameters) (at Assets/ML-Agents/Scripts/Batcher.cs:96)
MLAgents.Academy.InitializeEnvironment () (at Assets/ML-Agents/Scripts/Academy.cs:345)
MLAgents.Academy.Awake () (at Assets/ML-Agents/Scripts/Academy.cs:250)

The environment was previously used with PPO without a problem. Do I need to discard any types of rewards or observations or anything else?

This is the Academy/Agent Setup:

![2cf5a2e17b9f2f18acb644d5a37aaa83](https://user-images.githubusercontent.com/53266983/63000579-c9ef5d00-be71-11e9-9e03-87d001e672c6.png)

![772f8d212ae105851f4f02cddcf9ed8d](https://user-images.githubusercontent.com/53266983/63000587-ce1b7a80-be71-11e9-978e-ce71018d4228.png)

![eaa86c893fac3162b65792ca31d2a822](https://user-images.githubusercontent.com/53266983/63000709-1aff5100-be72-11e9-9664-7e76aed3af14.png)

Thanks in advance!

**Comment by vincentpierre** [comment]
Hi,
The error `The provided demonstration is not compatible with the brain being used for performance evaluation` arrises when the parameters of the brain used to record the demonstrations are not strictly identical to the parameters of the learning brain. These parameters are : 

 - vector_observation_space_size
 - num_stacked_vector_observations
 - number_visual_observations
 - camera_resolutions
 - vector_action_space_size
 - vector_action_descriptions
 - vector_action_space_type

Please make sure that all of these were identical to the learning brain when recording demonstrations.

**Comment by tillmusshoff** [comment]
Thanks for helping out. There was a typo in the vector_action_description. Never thought that this causes the issue. Thanks again!

**Comment by banish09** [comment]
@tillmusshoff 
I have just started working with the Unity ML-Toolkit. I see there are plenty of examples in the ML agents for most of the algorithms, however, none for the behavioral cloning.

I am trying to use offline behavioral cloning method to train a NPC in a FPS game. I don't know how to go around the Academy and Agent Scripts for this and have found neither proper documentation nor remotely close example to be able to understand and reciprocate something similar.

Any help would be appreciated.
