### ISSUE TITLE
Curriculum learning parameter is not present in the Environment

### ISSUE THREAD

**Issue by Lei-Wei** [Unity-Technologies/ml-agents#2436]
Hi, 
During Curriculum Learning I got this Error:
`mlagents.trainers.exception.CurriculumError: The parameter <parameter name> in Curriculum config/curricula/<JSON filename> is not present in the Environment`

I did follow the [Curriculum-Learning](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-Curriculum-Learning.md) to set up all the stuffs.

ML-Agents version: 0.8.2
Unity version: 2018.2.f21
Python version 3.6

Can anyone help, thx

**Comment by vincentpierre** [comment]
Hey,
Just to be sure, your parameter is not actually called `<parameter name>` right ?
This error arrises when the parameter name in the curriculum file does not match EXACTLY the reset parameter name in the Academy. Please make sure the two match.
If they do and you still have this error, please post a screenshot of your Academy inspector, your curriculum file and your full console output.

**Comment by Lei-Wei** [comment]
> Hey,
> Just to be sure, your parameter is not actually called `<parameter name>` right ?
> This error arrises when the parameter name in the curriculum file does not match EXACTLY the reset parameter name in the Academy. Please make sure the two match.
> If they do and you still have this error, please post a screenshot of your Academy inspector, your curriculum file and your full console output.

sadly it still does not work for me, these are the screen shots.
I also checked the coding of json file, it is utf-8. In VS 2019 it should be utf-8 by default too.

![console](https://user-images.githubusercontent.com/30424884/63092930-aad0f800-bf63-11e9-8a63-782a4afe9efd.PNG)
![academy](https://user-images.githubusercontent.com/30424884/63092932-aad0f800-bf63-11e9-831e-73b6e77895b2.PNG)
![json](https://user-images.githubusercontent.com/30424884/63092933-aad0f800-bf63-11e9-9f84-9c8aed55efb1.PNG)

**Comment by Lei-Wei** [comment]
ok I know it...
I must also manually set up in Academy inspector...

thanks for help!
