### ISSUE TITLE
[Idea] ML as a Unity service

### ISSUE THREAD

**Issue by iBicha** [Unity-Technologies/ml-agents#244]
I see great potential in this repo, but this is just how I imagine Unity doing things in the future.

Having machine learning as service, which can join all the services Unity provides such as cloud build, multiplayer, analytics, etc.

The idea is to allow a centralized knowledge base that can be updated and consumed by multiple clients, allowing different algorithms and configurations.

Another advantage of this model is automating the learning, and having the client download and consume the result data.

Just my $.02, feel free to close this if it doesn't help or make sense.

**Comment by srcnalt** [comment]
I'd love to see Unity provide a cloud service for ml-agents users for doing their trainings. Since I use a junk pc it takes a bunch of time to finish the trainings 😂

**Comment by unityjeffrey** [comment]
Thank you for your comments.  We’ve documented your feedback and will prioritize when appropriate.
