### ISSUE TITLE
mlagents: API # not compatible

### ISSUE THREAD

**Issue by sdr152** [Unity-Technologies/ml-agents#2444]
I'm using Unity version 2018.3.0.
I when try to open the Unity Environment(Executable) through Jupyter, I retrieve the following message:
**`The API number is not compatible between Unity and python. Python API : API-9, Unity API : API-8.
Please go to https://github.com/Unity-Technologies/ml-agents to download the latest version of ML-Agents.`**

I have reinstalled mlagents once and over again, but this error, but this error keeps coming up. I honestly do not know what to do. 

I need help to install the latest mlagents version please!

**Comment by vincentpierre** [comment]
From the error, your python version of ML-Agents is the most recent one (API-9) but your Unity SDK is out of date. You need to replace the [C# code of ML-Agents](https://github.com/Unity-Technologies/ml-agents/tree/master/UnitySDK/Assets/ML-Agents) in your project.
