### ISSUE TITLE
Tensorflow gpu with cuda 10 

### ISSUE THREAD

**Issue by leobol96** [Unity-Technologies/ml-agents#2446]
Hello,

I Have an RTX 2060 gpu and i'd like to use it for training my env.

How can i do it if ml-agents supports only cuda 9 with tensorflow 1.7.1 and my gpu supports only cuda 10 with tensorflow 1.13? 

If it's not possible to run ml-agents on the RTX 2060 , wich gpu do you recommend ?

**Comment by vincentpierre** [comment]
Hi, 
We have been experimenting internally with TensorFlow 1.13 and newer versions of CUDA on cloud machines. We have seen some results but we do not have a guide at this time.

**Comment by surfnerd** [comment]
I believe you should be able to run CUDA 9 on your GPU according to [this thread](https://devtalk.nvidia.com/default/topic/1055573/cuda-setup-and-installation/does-cuda-9-0-support-rtx-2060-/).
 i.e. running CUDA 9 on a GPU that has a newer driver should still work.  Note that the GPUs driver version is different than the CUDA version you have installed.

Have you run into errors when trying to make this work?

**Comment by leobol96** [comment]
Hi @vincentpierre 
Can you tell me how you did it?

**Comment by sstream17** [comment]
I am attempting to install ML Agents on an Nvidia Jetson Nano with CUDA 10.

Whenever I run `pip3 install mlagents` I get the error:
```
Could not find a version that satisfies the requirement tensorflow<1.8,>=1.7 (from mlagents) (from versions: )
No matching distribution found for tensorflow<1.8,>=1.7 (from mlagents)
```

Would that be related to this issue in anyway?

**Comment by surfnerd** [comment]
Hi, we have relaxed the restrictions on pip version constraints.  Please try the 0.10 release and let us know if this solved your issue.

**Comment by RyushoYosei** [comment]
I just had been trying to do this myself and I have had to go download cuda 9 to try to run this MLAgents mess, as it says that Tensorflow itself can't find the right assets since ML Agents requires the 1`7.1 tensorflow, so you have to have 9.0 cuda to use it, as it can't find things it needs in  10.0 cuda X_X
