### ISSUE TITLE
Not able to add reward signals using gail_config.yaml

### ISSUE THREAD

**Issue by rajatpaliwal** [Unity-Technologies/ml-agents#2452]
Hello,
While trying to add reward signals in gail_config.yaml I am receiving an error saying 

```
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
in "config/gail_config.yaml", line 126, column 1
```
I tried removing tab characters to 2 spaces but didn't work.

Kindly help.

**Comment by xiaomaogy** [comment]
I think posting your .yaml file would help us see where the issue is.

**Comment by rajatpaliwal** [comment]
Hi @xiaomaogy ,
Here is the part of gail_config.yaml file specific to my project.
`RL_ExpertLearningBrain:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
	pretraining:
        demo_path: ./UnitySDK/Assets/Demonstrations/RLExpertrecordin_1.demo
        strength: 0.5
        steps: 10000
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256
        gail:
            strength: 0.01
            gamma: 0.99
            encoding_size: 128
            demo_path: ./UnitySDK/Assets/Demonstrations/RLExpertrecordin_1.demo`

**Comment by xiaomaogy** [comment]
Your file seems correct. Maybe there is some hidden \t that's not showing up. I would recommend taking one of our existing .yaml and replace the fields directly in that file to fine out what's wrong.

**Comment by rajatpaliwal** [comment]
Yes, the problem was I was editing the .yaml file in visual studio that was adding \t instead of spaces and was giving out error. Editing in Notepad++ solved the issue.

Query regarding gail_config:
We are performing offline behavioral cloning with added reward signals by using "gail_config" file. But I don't see any reward points being added while the training is taking place , also the student agent is barely learning anything compared to training with offline_bc_config.yaml file.
Any views on this point.

**Comment by ervteng** [comment]
@rajatpaliwal reward signals only work with the "ppo" trainer, as you need PPO to learn to maximize the reward signal. To use BC with reward signals, you could use the `pretraining` feature of PPO with a 0 `steps` parameter.

**Comment by aikeonnkyauk** [comment]
What is going on
