### ISSUE TITLE
Query regarding command line training option --load

### ISSUE THREAD

**Issue by rajatpaliwal** [Unity-Technologies/ml-agents#2456]
Hello,

I am using training option

>  --load

 to restore the parameters of a previously trained model and continue the training . My query is can I select a particular trained model which is not the last iteration . If not does the --load options selects the parameter to be loaded randomly or it selects the parameters from previously saved model.

**Comment by xiaomaogy** [comment]
Hi @rajatpaliwal, --load will restore the model from the latest saved one. However you can also tweak one of the file within the models/ folder to change another model as the latest model (I don't remember which file, but you should be able to figure it out by looking at the files).

**Comment by rajatpaliwal** [comment]
Got it. It's the checkpoint file in the models/folder . Changed the model name and is able to load any model of my choice.Thanks @xiaomaogy
