### ISSUE TITLE
Behavioural Cloning: TypeError: increment_step() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by Santorayo3** [Unity-Technologies/ml-agents#2462]
I'm trying to teach my agent a demonstration file but the training fails with this error:
  File "c:\program files\python\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 297, in start_learning
    n_steps = self.advance(env_manager)
  File "c:\program files\python\envs\ml-agents\lib\site-packages\mlagents\envs\timers.py", line 210, in wrapped
    return func(*args, **kwargs)
  File "c:\program files\python\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_controller.py", line 383, in advance
    trainer.increment_step(len(new_step_infos))
TypeError: increment_step() takes 1 positional argument but 2 were given

The brains of the demonstration and the learning brain have the exact same parameters and I use the example config yaml for offline training. The brain is using stacked vectors and visual observations.

PPO training works fine with the same configuration.

**Comment by arixlin** [comment]
@Santorayo3  You can use 0.9.1，this bug has fixed

**Comment by Santorayo3** [comment]
Thanks, that helped a little. Unfortunately I've run straight into the next error:
  File "c:\program files\python\envs\ml-agents\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "c:\program files\python\envs\ml-agents\lib\site-packages\tensorflow\python\client\session.py", line 1116, in _run
    str(subfeed_t.get_shape())))

ValueError: Cannot feed value of shape (2, 32, 80, 100, 3) for Tensor 'visual_observation_0:0', which has shape '(?, 80, 100, 3)'

The player and learning brain both have one visual observation with a 100x80 resolution.

**Comment by arixlin** [comment]
@Santorayo3  Can you  let me see brain settings and CollectObservations() ？

**Comment by Santorayo3** [comment]
I've made several changes over time and don't know the settings I used there. All I can say that the brains had a visual observation with 100x80px (color) and some vector observations like their position, health, ammo and so on. Those vector observations were stacked to about 15-30 as far as I remember. Both brains had the same settings.

**Comment by arixlin** [comment]
@Santorayo3  You are input tensor error， the input need set [n, 80, 100, 3], do you set Stacked Vectors?

**Comment by xiaomaogy** [comment]
I tried to set up something similar to reproduce the bug, but I wasn't able to on the latest version, so I guess this is no longer an issue. Feel free to reopen if this still occurs.
