### ISSUE TITLE
The hyper-parameter Gamma could not be found for the <class 'mlagents.trainers.ppo.trainer.PPOTrainer'> trainer of brain RubixLearner.

### ISSUE THREAD

**Issue by skamal16** [Unity-Technologies/ml-agents#2463]
I get the error described in the heading when I try to run ml-agents-learn and then press play. The console window gets stuck and the unity editor window also seems to get stuck. I have to Ctrl-C to interrupt the console to do anything else.

Note: This is the first time I am running ML-Agents so I am probably missing something obvious. Any guidance would be appreciated.

Update: It's not just my scene that this doesn't work on, it is the same whether I run on any of the example scenes. So it shouldn't be related to the way I've set my learning brain.

Update: Reinstalling ml-agents and reimporting ml agent assets seems to have solved the problem. I'm assuming the problem had something to due with a mismatch of versions of ml agents of where the trainer file was and of the brain assets I was using in my project. Anyways I'll be closing this now.

**Comment by Coookiez** [comment]
I'm using the newest version cloned from the repo so when I deleted the ML-Agents folder and reimported it - nothing changed. Any other suggestions on how to fix that problem?

**Comment by skamal16** [comment]
Your assets may be of the newest version, but when last did you install/update your ml agents environment? I think my main issue was the need to update my ml agents environment, in which case I just deleted it and installed it from scratch. If this doesn't fix it then I'm not sure what the problem may be.

**Comment by Coookiez** [comment]
I did it like 2-3 days prior to running the agents.
