### ISSUE TITLE
How can i convert bytes/nn to pb file?

### ISSUE THREAD

**Issue by jjangshan** [Unity-Technologies/ml-agents#2466]
How can i convert bytes/nn to pb file?
I want to use a model created by unity ml-agents in a non-Unity environment. Is it possible?

Thank you for comments.

**Comment by jjangshan** [comment]
Hi @zako42 , Thank you for your help. I found both nn, pb and ckpt files.

May i ask you one more question?

There is Game A, which is difficult to repeat for learning but, available inference/test using tensorflow  (Not based on Unity)

In Unity, I create a small testbed B similar to Game A, and learn by ml-agent using equalized input (observation) and output (action).

If then, can I use that model file(bytes/nn) in Game A? (Not using Unity)

**Comment by jjangshan** [comment]
@zako42 Sorry for the late reply.
I think we have confirmed the possibilities based on your opinion and I think it's worth a try also.
Thank you for your kind explanation. I hope you get good results in your case too.

**Comment by rajatpaliwal** [comment]
Hi @zako42 ,
Can you tell me how are you opening .pb files outside unity . What tensorflow tools are you using . Is there to configure these pb files according to our need.

**Comment by surfnerd** [comment]
Hello all,
Thank you for your questions.  This discussion has been idle for a few weeks and we are closing the issue.  Please reopen it if there are further questions.
