### ISSUE TITLE
KeyError During Curriculum Training

### ISSUE THREAD

**Issue by HappySlice** [Unity-Technologies/ml-agents#247]
This only happens during curriculum training. I'm not sure where to begin to solve this issue.
I already made sure that the default reset parameters in the academy match the first parameters in the json curriculum file.

The first part of the traceback appears to be lines 132-136 in the ppo.py script

```
INFO:unityagents:
Lesson changed. Now in Lesson 1 : 	target_or_enemy -> 1, area_size -> 40.0, pillar_column_count -> 1
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-fea09393b070> in <module>()
     58         new_info = trainer.take_action(info, env, brain_name, steps, normalize)
     59         info = new_info
---> 60         trainer.process_experiences(info, time_horizon, gamma, lambd)
     61         if len(trainer.training_buffer['actions']) > buffer_size and train_model:
     62             # Perform gradient descent with experience buffer

~\Documents\ShootersML\python\ppo\trainer.py in process_experiences(self, info, time_horizon, gamma, lambd)
    114         """
    115         for l in range(len(info.agents)):
--> 116             if (info.local_done[l] or len(self.history_dict[info.agents[l]]['actions']) > time_horizon) and len(
    117                     self.history_dict[info.agents[l]]['actions']) > 0:
    118                 if info.local_done[l]:

KeyError: 2140
```

**Comment by MarcoMeter** [comment]
Hi @HappySlice 
does this error occur while trying to train the Area Wall example, too?

Could you share your curriculum file?

Based on the traceback, the lookup for data (based on a certain key) from the history dictionary did not work out. `self.history_dict[info.agents[l]]['actions']`

**Comment by HappySlice** [comment]
It does not happen when I train the Area Wall example.
Maybe an issue is that I am activating adversarial agent gameobjects in the newer lesson? Is there a way to safely create or introduce new agents?

```
{
    "measure" : "reward",
    "thresholds" : [10.0, -10.0, -10.0, -10.0, -10.0, -10.0],
    "min_lesson_length" : 2,
    "signal_smoothing" : true, 
    "parameters" : 
    {
        "area_size" : [40.0, 40.0, 60.0, 60.0, 80.0, 80.0, 100.0],
        "target_or_enemy" : [0, 1, 1, 1, 1, 1, 1],
        "pillar_column_count" : [1, 1, 1, 2, 2, 4, 4]
    }
}
```

**Comment by MarcoMeter** [comment]
Dynamically adding/removing agents is likely the problem which causes the malicious dictionary lookups.
There is already an ongoing discussion in issue #228

**Comment by unityjeffrey** [comment]
This issue is a duplicate and there is an ongoing discussion in issue [228](https://github.com/Unity-Technologies/ml-agents/issues/228)
