### ISSUE TITLE
Can I have two academies in one scene?

### ISSUE THREAD

**Issue by EnthusedDragon** [Unity-Technologies/ml-agents#2477]
Is it possible to have two academies in the same scene with different brains?
One will have Control on and the other will have it off.

I'm training my one brain first and once it's ready it will play a part in the training of the next brain.

I'm currently training my AI Player brain first.
But once that's ready I will be training another brain to generate game content, based off how well the AI Player is performing.

**Comment by arixlin** [comment]
@EnthusedDragon  Hi， you can let other brain run on internal.

**Comment by vincentpierre** [comment]
As @arixlin is saying, you can indeed have multiple brains in the Academy Hub at once. You can put several learning brains in it and only the ones with the `Control` checkbox will be trained.

**Comment by EnthusedDragon** [comment]
Fantastic, thank you for confirming that.
Looking forward to testing it out.
