### ISSUE TITLE
Error when "Reset On Done" set to true for some agents but not others

### ISSUE THREAD

**Issue by whalefood** [Unity-Technologies/ml-agents#2479]
**Describe the bug**
Mixing agents where some are "Reset on Done" and some aren't causes PPO training to crash on Done

**To Reproduce**
1. Open one of the examples with multiple agents.  I used the Soccer example.  And set one of the agents to not reset on done.
2.  Start PPO training.
3.  When that agent reaches the Done state, the training will crash

**Screenshots**
![bug](https://user-images.githubusercontent.com/1223828/64070026-7dec3880-cc25-11e9-8173-77949e3f1030.PNG)

**Environment (please complete the following information):**
- Windows 10
- _ML-Agents version_: 0.9.1

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by whalefood** [comment]
Nevermind.  Seems to be fixed in 0.9.2

**Comment by whalefood** [comment]
Actually, it is still an issue.  But only if curiosity is turned on.

**Comment by vincentpierre** [comment]
Hi, 
We removed the "Reset On Done" option is the current master branch. To terminate an agent without resetting it, you can destroy its game object directly.
