### ISSUE TITLE
Tests in the Editor folder depend on scripts in the Example/Shared assets folder

### ISSUE THREAD

**Issue by jo3w4rd** [Unity-Technologies/ml-agents#2481]
Since a "real" project might not want extraneous example content in its build, nothing outside the Example folder should depend on scripts or other assets inside Examples.

If I delete the Example folder, the Editor Ray Perception tests fail to compile.

**Comment by vincentpierre** [comment]
We have made ml-agents a package on the master branch. Doing so, we isolated the code to test it better (including raycasts). This should resolve the issue.
