### ISSUE TITLE
After agents hit max Fitness, it's slowly becomming worse by far.

### ISSUE THREAD

**Issue by Avoca-do** [Unity-Technologies/ml-agents#2484]
So i was trying to do ml agents.
and i made 1e7 steps.

after 1e6 steps.
i got the results of 4k fitness.
at 2e6.
the agent was avr around 8k - max fitness.
and then it just went down hills.

from 190k
to 220k the agents went from avg fitness of 8k to avg fitness of 2k.

with much much worse results.
and i just cant figure it out.

why? how is that possible?

**Comment by chriselion** [comment]
Hi @Avoca-do,
Are you seeing this behavior in a provided example environment? Unfortunately we don't have the resources to help debug issues with custom environments.

**Comment by Avoca-do** [comment]
well i might actually figured out what was causing the issue,
i miss understood the GetReward and SetReward methods.

i was sure that SetReward actually rewrite the reward of the entire run,
but there is the occomulative reward,
so, i was using to much SetReward, at the end of the run by multiplying my GetReward, value.
and that caused the issue (i guess).

still wierd that at first it worked perfectly fine with the desired result, and after a while ,it "degenerated" simply because of miss use of SetReward.

**Comment by chriselion** [comment]
Glad you figured out the problem. I'll close this issue.
