### ISSUE TITLE
Material's texture is missing in external mode

### ISSUE THREAD

**Issue by maystroh** [Unity-Technologies/ml-agents#2486]
In only external mode with visual observation input, a texture image added to a material disappeared (it becomes black at runtime) in the image treated by the CNN.

1. Add a texture image to a material
2. Attach this material to a game object in your scene
3. Add this line of code in `_process_pixels` in `UnityEnvironment` class:
`image.save(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S") + ".png") `
 4. Set visual observation size in the Brain object to 1
 5. Set Brain type to External
 6. Launch the training and double check the image saved in your directory. You would see that the texture image is lost as you can see in the screenshots below. 

**Screenshots**
Image captured of the Gridworld environment where I just added an image texture for a material for the moving box:
![3](https://user-images.githubusercontent.com/4221393/64180047-677ff000-ce64-11e9-917e-d0c16a0b83cd.png)
GridWorld environment at runtime: the blue box is completely lost; it is black.
![2019-09-03 16:00:04](https://user-images.githubusercontent.com/4221393/64180189-a615aa80-ce64-11e9-8b67-57f821af828e.png)

I've tried as well on my own environment so here is how it should look
![1](https://user-images.githubusercontent.com/4221393/64178603-0d7e2b00-ce62-11e9-9d9d-f4859612450a.png)
Here is how it looks at runtime: the circular blue shape is completely black.
![2019-09-03 15:19:16](https://user-images.githubusercontent.com/4221393/64178609-0fe08500-ce62-11e9-987c-c3aed13bd80a.png)

It is clear that textures are not rendered properly and this is a problem for those who use visual observation as input for the agents.  

**Environment:**
- OS + version: Ubuntu 16.04
- _ML-Agents version_: ML-Agents v0.5
- _Environment_: GridWorld and my own environment (as you can see in this  [example](https://github.com/maystroh/RL_cataract/blob/master/README.md))

Thanks in advance for checking it.

**Comment by vincentpierre** [comment]
I tried to reproduce this bug but I did not succeed. I think it is because I do not know how to : 

> Add a texture image to a material

Is this different from what we do with the Checker materials in PushBlock ? How is this different from the Materials present in "UnitySDK/Assets/ML-Agents/Examples/SharedAsset" ?
It could be that the Material or texture you are using have different settings.

**Comment by maystroh** [comment]
Actually, the material I use was different from those used "UnitySDK/Assets/ML-Agents/Examples/SharedAsset" but I modified it to have the same settings as the ones used in the SharedAsset but it is still showing black at runtime. Here are the settings I'm using for my material:
![Screenshot from 2019-09-03 22-58-06](https://user-images.githubusercontent.com/4221393/64208389-01648e80-ce9f-11e9-9760-d3f0f89356a1.png)

**Comment by vincentpierre** [comment]
If I cannot reproduce the issue, I will not be able to help. The fact that the materials in the Shared Assets are working indicates there might be something wrong with the texture. I encourage you to experiment with different textures and try to identify what is causing the issue. It might be resolution.

**Comment by maystroh** [comment]
Ok now I see where the problem is coming from. If I run the training on my local machine using my local X server linked to my physical monitor (my display hardware), it works properly, however, if I run it on a distant machine with no display hardware using my singularity image (see this [link] (https://github.com/maystroh/RL_cataract/blob/master/README.md) for more details about it), the textures becomes black as you can see in the following images:
1. Local machine
![2019-09-04 09:51:05](https://user-images.githubusercontent.com/4221393/64245923-25aa8480-cf0c-11e9-8e7e-e46ca1f7d357.png)
2. Distant machine 
![2019-09-04 11:55:48](https://user-images.githubusercontent.com/4221393/64245941-2ba06580-cf0c-11e9-8696-0c815099b46c.png)

In this singularity image, I installed Xvfb which is the X server you proposed to run on machines with no display hardware and no physical input devices. It turns out the problem is in Xvfb but not sure why!! Still checking it and will keep you posted.

**Comment by maystroh** [comment]
I spent a couple of days trying to figure out what is happening without success. It's really annoying to have such problem when working with visual observation. Not sure how to proceed. Any help would be appreciated.
