### ISSUE TITLE
Calling All Game Developers

### ISSUE THREAD

**Issue by unityjeffrey** [Unity-Technologies/ml-agents#2493]
Hello!

If you are a game developer and looking to use ML-Agents in a game (for any purpose at any stage of development), we want to hear from you!

Please send us a note to ml-agents@unity3d.com and include your name, studio (or independent), and a short description of your project.

Thank you!

Unity ML-Agents Team

**Comment by JaggedNail** [comment]
Hey,
I am looking at implementing this into my current project. Which is a Xcom inspired turnbased tactical shooter.
