### ISSUE TITLE
I want to change Soccer Example.

### ISSUE THREAD

**Issue by WannyWanny** [Unity-Technologies/ml-agents#2495]
Describe what you'd like to discuss.

**Note**: The ML-Agents team has limited resources for education and community discussion.  We'll participate as we are able, but encourage members of the community to support one another to discuss and support one another.

In Soccer Example, field size is 30 * 15. 
I changed size to 161.8 * 100.
As a result, it doesn't work as well as it did before. Agents can't touch the ball properly.
I've analyzed the script for a few days, but I'm not sure of the solution.
Is it correct to change the startoffset and endoffset of the perceive function? if not, should i change  rayAngles[] or rayDistance?
If you know the solution, ask for help.

**Comment by chriselion** [comment]
Hi @WannyWanny,
As mentioned in the template, we have limited resources and can't help much with custom environments like yours.

That being said - I would definitely increase the ray distance to make sure the agents can "see" the other objects.

Another option might be to try using curriculum learning (https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-Curriculum-Learning.md) to gradually increase the size of the field once the agents have learned to play on a smaller field.

**Comment by surfnerd** [comment]
Hi @WannyWanny,
This issue has been idle for several days so we are going to close it.  Please feel free to reopen it if you have further questions.
