### ISSUE TITLE
AttributeError: 'OnlineBCTrainer' object has no attribute 'step'

### ISSUE THREAD

**Issue by mnsmuts** [Unity-Technologies/ml-agents#2496]
New installation of 0.9.2 with new conda py env.
-using the UnitySDK and running the 3DBall
-player brain on one of the agents Learning brain on the rest, academy with two brains (player and learner)
Nothing unusual with the setup or command (mlagents-learn config\online_bc_config.yaml --train --slow)

Obviously I changed the brain to imitate line in the default onlineBC yaml file to 3DBallPlayer
![mlagents0 9 2error](https://user-images.githubusercontent.com/22680369/64345952-26fdaf00-cfe9-11e9-87fb-56dc5774aef8.PNG)

Windows 10 ML-Agents 0.9.2 3DBall

Any ideas?

Just tried 0.9.1 with the hotfix and can get offline training working, then switched back to 0.9.2 and tried the same (with the correct env) and received the attrib error again.

**Comment by mnsmuts** [comment]
![mlagents0 9 2error2](https://user-images.githubusercontent.com/22680369/64347272-878deb80-cfeb-11e9-88b7-4604e0d4449a.PNG)
Same error with offline training using the basic model and a demo file.

**Comment by chriselion** [comment]
Hi @mnsmuts - thanks for the bug report. I think I see the problem, I'll work on a fix today.

**Comment by chriselion** [comment]
Fixed in https://github.com/Unity-Technologies/ml-agents/pull/2498 - during a refactor, the step initialization got moved to `RLTrainer` instead of `Trainer` which explains why it didn't affect PPO training.

We'll work on some more automated testing to make sure there's better coverage on the BC Trainer code.

**Comment by mnsmuts** [comment]
Many thanks

**Comment by chriselion** [comment]
We're going to be doing a bugfix release on Monday with the fix for this.

**Comment by chriselion** [comment]
Version 0.9.3 was released yesterday, which contains the fix for this. I'll close this issue now.
