### ISSUE TITLE
pip3 install PermissionError: [Errno 13] Permission denied: '/usr/local/bin/jupyter'

### ISSUE THREAD

**Issue by erwincoumans** [Unity-Technologies/ml-agents#25]
The docs mention: pip install . but it gives an error here (Mac OSX).
pip install PermissionError: [Errno 13] Permission denied: '/usr/local/bin/jupyter'

pip install . --user solves it (better than sudo pip install .), perhaps update the doc or add a note?

**Comment by erwincoumans** [comment]
This was using the brew version of python3. This version of Python doesn't install jupyter on Mac properly
When using Anaconda python3 there are no such issues. I guess you are using Anaconda on Mac?

**Comment by eagleEggs** [comment]
This bring up a good point. Python and python installs add a learning curve in just setting these types of environments up. Although there are a lot of platform variations and wouldnt expect to cover them all, a somewhat thorough walkthrough for common ones may make this project more accessible to many that arent familiar.

Banging your head trying to set it up builds character, but whatever :D

Have you thought of writing it up and pushing it here?

**Comment by erwincoumans** [comment]
Not yet, wrapping up the 3D Ball tutorial.
"Type of Brain to Internal." -> there is just "External, Player and Heuristic' choices...

**Comment by eagleEggs** [comment]
Read the bottom of the Unity Setup readme. You have to enable_tensorflow in settings and import a package I believe.

**Comment by awjuliani** [comment]
Hi @erwincoumans,

In particular, this section of the wiki: https://github.com/Unity-Technologies/ml-agents/wiki/Getting-Started-with-Balance-Ball#setting-up-tensorflowsharp-support-experimental should walk you through what is needed to add internal TF support. Please let me know if you run into any other issues.

**Comment by erwincoumans** [comment]
??? I have no problem with TF support, did I mention that anywhere?

This thread brings up 2 issues: 
1) pip install has permission issues, unless using Anaconda.
2) There is no 'Internal' for brain,.

**Comment by awjuliani** [comment]
The internal brain mode is only available once the Tensorflow sharp plugin is added to the project, the `ENABLE_TENSORFLOW` flag is added to the scripting symbols, and the editor is reset.

**Comment by erwincoumans** [comment]
ah, ok. I missed that piece of information, must have skipped that sentence in the docs.

**Comment by awjuliani** [comment]
No worries. I'll edit the document to make it more explicit that the `Internal` mode will only appear once those prior steps are completed.

**Comment by erwincoumans** [comment]
To be more precise: I skipped the experimental TF paragraph and went right into "Embedding the trained model itself". It would be good to say you cannot skip that TF paragraph.

**Comment by erwincoumans** [comment]
One more little tidbit, relating to saving to the 'bytes' file:

You HAVE to terminate the PPO training, not just CAN. "you can stop the training process".
I left it running, and then ran the last step, and it doesn't save the bytes file. Only when you hit the STOP button you can run the last step. Pretty obvious to jupyter users probably, but I barely use that tool.

**Comment by awjuliani** [comment]
I appreciate the suggestions, and have rewritten parts of the final wiki section to hopefully make it more clear: https://github.com/Unity-Technologies/ml-agents/wiki/Getting-Started-with-Balance-Ball#embedding-trained-brain-into-unity-environment-experimental

**Comment by erwincoumans** [comment]
I got it to work finally. Step 6 was a bit tricky, since I hadn't use Unity before.

"Drag the <env_name>.bytes file from the Project window of the Editor to the Graph Model placeholder in the 3DBallBrain inspector window."

You need to drag it exactly into one of the boxes in that inspector window.

I think some video of the 3D Ball would be easier to follow for newcomers, but that would take time/resources to create.

Anyway, it works! (https://www.youtube.com/watch?v=NX1DmSWmqYE)

**Comment by awjuliani** [comment]
Glad you were able to get it working! 

I'll close the issue for now, but will make a point of making python instructions more clear. I also agree that a video walkthrough would be ideal, and we have it on our to-do list.

**Comment by saporter** [comment]
This thread really helped me.  Yes, @erwincoumans, some simple updates to the doc would really save a lot of time.  Specifically:
1. brew version of python3 doesn't properly install Jupyter on a mac (I switched to Anaconda it works great now), and
2. `pip install --user .` was needed to properly install dependencies
