### ISSUE TITLE
Changing Dimension of Non-primitive Objects

### ISSUE THREAD

**Issue by jkim447** [Unity-Technologies/ml-agents#2500]
Hi, I am trying to do domain randomization, where the object dimensions are changed every episode. 

I originally modeled the object in Solidworks. However, after it is imported to Unity it becomes a mesh file. Any chance there might be a way to access the original dimensions of the object and be able to change them? I know changing the scale can be another option, but was wondering if ML-Agents offered some magical feature..

**Comment by chriselion** [comment]
Hi @jkim447,
Sorry for the delay on this. There's nothing special in ML-Agents to get the original dimensions. However, you could use custom reset parameters to scale the object around each axis (say between .9x and 1.1x of its original size), for example
https://github.com/Unity-Technologies/ml-agents/blob/72088537f9ce3a3fde5ab21940d2027a42cae0fc/UnitySDK/Assets/ML-Agents/Examples/BananaCollectors/Scripts/BananaAgent.cs#L289
