### ISSUE TITLE
Memory is linearly increasing when I use model inference mode.

### ISSUE THREAD

**Issue by hanseoup** [Unity-Technologies/ml-agents#2501]
https://github.com/Unity-Technologies/ml-agents/issues/1817
Because i think above issue can solve memory leak issue. 
I changed my ml-agent version to 0.9.2

as above url said,I checked that it can solve the issue of "3DBall" sample example.
![image](https://user-images.githubusercontent.com/53593292/64423563-cdc57680-d0e1-11e9-9200-85f056ce9dba.png)

But it still has memory leak issue, when it comes to run other sample example
(Especially sample with "ray Perception!" ex.pushBlock, Hallway)

could you check this issue? I think it would be serious problem, when I run my 
"custom self training system". Because it should use at least one inference mode for 
counter part agent. please help me....   :(

=============================
following is how to reproduce my issue.

1. open the "Hallway"(pushBolck) example scene.
![image](https://user-images.githubusercontent.com/53593292/64424171-48db5c80-d0e3-11e9-9602-59e6a41681db.png)

2.  change the "Time Scale" to 100 in academy Inspector window. 
An do not check Control check box.
![image](https://user-images.githubusercontent.com/53593292/64424083-10d41980-d0e3-11e9-88bb-938e8d56befe.png)
![image](https://user-images.githubusercontent.com/53593292/64424559-652bc900-d0e4-11e9-9cbb-0789a4881caa.png)

3. Give the pre-learned model to agent in "HallwayArea" prefab. 
(It is already loaded, if you don't edit this example after installing the ml-agent)
![image](https://user-images.githubusercontent.com/53593292/64424526-53e2bc80-d0e4-11e9-9cfd-bbdf9e5573d4.png)

4. play! & press "Ctrl + Shift + Esc" and watch memory state increasing.

**Comment by chriselion** [comment]
Hi @hanseoup,
I observed similar behavior to what you described, using the Unity profiler to track the memory usage. However, the memory usage eventually levels out (about maybe 30 seconds of real time) and stays flat after this.

![image](https://user-images.githubusercontent.com/6877802/64447724-e9546100-d090-11e9-8d6f-040adc3f383d.png)

Can you confirm (preferably in the profiler) whether the memory growth eventually stops? If you're still concerned, we should be able to dig some more and see where the growth is coming from.

**Comment by hanseoup** [comment]
Thank you for your reply. as you said, i track the memory state, and i want to see the point that memory eventually stop. But, in my environment, the memory state is just linearly increasing. 
following are snapshots... for checking the issue.

1. at start
![start](https://user-images.githubusercontent.com/53593292/64497776-d38ea800-d2eb-11e9-8ec5-f9fcde2e2698.PNG)
2. after 2min
![2min](https://user-images.githubusercontent.com/53593292/64497778-d9848900-d2eb-11e9-8d5b-4849b7817819.PNG)
3.after 8min
![8min](https://user-images.githubusercontent.com/53593292/64497782-df7a6a00-d2eb-11e9-9138-072e80197301.PNG)
4.after 20min
![20min](https://user-images.githubusercontent.com/53593292/64497785-e43f1e00-d2eb-11e9-8084-ca97742e11c4.PNG)

The example i used is "HallWay" in same configuration, as i explained above.
and here is etc...
ml-agent version: 0.9.2v
unity version: 2018.3.14
os: Window 10(x64)
cpu: i7-8700K
gpu: 2080RTX
ram: 32.0GB


+) could you tell me, your unity version & ml-agent version?

**Comment by hanseoup** [comment]
Thank you, chriselion! I hope that we could solve the issue soon. please comment it, if you find some clues :)

**Comment by chriselion** [comment]
Still investigating - at the moment it appears there might be a bug with our reuse (or lack thereof) of tensors in Barracuda.

**Comment by surfnerd** [comment]
Hi @hanseoup, 
Thank you for providing feedback on this issue.  #2541 should fix the memory leak.  Please let us know if you have further issues.

**Comment by hanseoup** [comment]
Thank you @surfnerd ! I checked my memory issue solved, also in my custom environment!
Thanks a lot!
