### ISSUE TITLE
Identify custom actions vector action space type & size

### ISSUE THREAD

**Issue by TSTsankov** [Unity-Technologies/ml-agents#2503]
Greetings!

I am probably asking a silly question, yet can someone help me out here:

After following the instructions provided [here](https://github.com/Unity-Technologies/ml-agents/blob/master/protobuf-definitions/README.md) && [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Creating-Custom-Protobuf-Messages.md) in order to setup ["Discrete and Continuous Actions in one Agent"](https://github.com/Unity-Technologies/ml-agents/issues/2101) I have the following issue:

In unity, when **setting up the Learning Brain** it asks you to select either **Continuous** or **Discrete** action space. Which one should I select and what size value should I put there, assuming my custom action setup is the following:

`syntax = "proto3";

option csharp_namespace = "MLAgents.CommunicatorObjects";
package communicator_objects;

message CustomAction {
    enum Direction {
        FWD=0;
        FWDLEFT=1;
        FWDRIGHT=2;
        BACKWD=3;
        BACKWDLEFT=4;
        BACKWDRIGHT=5;
        LEFT=6;
        RIGHT=7;
        JUMPFWD=8;
        JUMPFWDLEFT=9;
        JUMPFWDRIGHT=10;
        JUMPBACKWD=11;
        JUMPBACKWDLEFT=12;
        JUMPBACKWDRIGHT=13;
        JUMPLEFT=14;
        JUMPRIGHT=15;
	JUMP=16;
        NONE=17;
    }
    float xAmount = 1;
    float yAmount = 2;
    Direction direction = 3;
}`

Thanks in advance!

Edit*
Even after building and running with an arbitrary size for the continuous/discrete actions, I get the following problem - _AgentAction (float[] vectorAction, string textAction, MLAgents.CommunicatorObjects.CustomAction customAction)_ is never called.

The issue seems to be happening around the  _AgentStep ()_ function when _AgentAction (action.vectorActions, action.textActions, action.customAction)_ is called.

`Exception
NullReferenceException: Object reference not set to an instance of an object
MLAgents.Agent.AgentStep () (at <c7fcd04796164102ab4179d1a124ffd1>:0)
MLAgents.Academy.EnvironmentStep () (at <c7fcd04796164102ab4179d1a124ffd1>:0)
MLAgents.Academy.FixedUpdate () (at <c7fcd04796164102ab4179d1a124ffd1>:0)`

**Comment by chriselion** [comment]
Hi,
Sorry for the delay on this.

I would strongly discourage you from using CustomActions. Just updating the protobuf definitions isn't enough; you would also need to make several customizations to the Trainer in order to tell it how to produce the CustomActions. The documentation is misleading on the amount of effort required, and I'm going to update this soon.

In your case, I would recommend breaking down the direction and jumping actions into 3 components, for example forwardAmount (to handle FWD/BACKWD), turnAmount (to handle LEFT/RIGHT) and jumpAmount (to handle JUMP). Then, for example, use JUMPBACKWDLEFT if `(jumpAmount > .5) && (forwardAmount < -.5) && (turnAmount > .5)`

**Comment by TSTsankov** [comment]
Many thanks for the reply! I'll just take things back to my previous setup and play around with the recurrent neural network parameters.

```
bool moveFwd = vectorAction[0] > 0;
bool moveBack = vectorAction[0] < 0;
bool moveLeft = vectorAction[1] > 0;
bool moveRight = vectorAction[1] < 0;
float xAxis = vectorAction[2];
float yAxis = vectorAction[3];
bool jump = vectorAction[4] > 0.5f;		
surfComp.UpdateMoveData (moveFwd, moveBack, moveLeft, moveRight, jump);
surfComp.UpdateRotation (xAxis, yAxis);
```

**Comment by Sohojoe** [comment]
@TSTsankov  - I did some research around creating a controller for a 2d ml character. I found that discrete input trained better / has a better feel that continuous input (the discrete input drives an analog-style controller simular to 8bit/NES Mario)

you can see my code and experiments here - https://github.com/Sohojoe/ActiveRagdollControllers
