### ISSUE TITLE
No Example for Behavioral Cloning offline/online training

### ISSUE THREAD

**Issue by banish09** [Unity-Technologies/ml-agents#2508]
I have just started working with the Unity ML-Toolkit. I see there are plenty of examples in the ML agents for most of the algorithms, however, none for the behavioral cloning.

I am trying to use offline behavioral cloning method to train a NPC in a FPS game. I don't know how to go around the Academy and Agent Scripts for this and have found neither proper documentation nor remotely close example to be able to understand and reciprocate something similar.

Anyone who has experience with behavioral cloning, please reach out. Any help would be appreciated. Thanks in advance.

**Comment by chriselion** [comment]
Hi @banish09 
The scene in `UnitySDK/Assets/ML-Agents/Examples/BananaCollectors/Scenes/BananaIL.unity` should be usable with Behavioral Cloning. 

There are some sections in the docs https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/Training-Behavioral-Cloning.md and a related section on recording demonstrations https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/Training-Imitation-Learning.md#recording-demonstrations that might be helpful.

Note that there was a bug in the 0.9.2 release that broke BC. We just released a bugfix release (0.9.3) that addresses this.

You may also want to look into GAIL as an alternative to BC: https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/Reward-Signals.md#gail-reward-signal
