### ISSUE TITLE
[Documentation] Tutorial linked in the doc for setting tensorflow up and running

### ISSUE THREAD

**Issue by ZephyrRaine** [Unity-Technologies/ml-agents#251]
Hey there, thanks for making ml-agents usable by and for everyone.

I had to get everything needed in order to work from a different computer and went through the tutorial once again, but I noticed it mentions installing Cuda and Cudnn. But I think I noticed earlier that ml-agents doesn't use Tensorflow-GPU?

I've skipped this step because I only got 100kB/s and everything seems to be running smoothly, no much speed difference.

Am I missing on something here?

Cheers! <3

**Comment by HappySlice** [comment]
The PPO algorithm isn't really currently optimized for GPU. 
Explained in detail here: https://github.com/Unity-Technologies/ml-agents/issues/239
