### ISSUE TITLE
Address error when manual input

### ISSUE THREAD

**Issue by laarroyo** [Unity-Technologies/ml-agents#2510]
Address error when manual input. Have to pick from Google address options for correct pin

**Comment by chriselion** [comment]
Is this a problem with ML Agents? If so, please create a Bug report issue and fill in the requested information. If not, we are unable to provide any additional help.

**Comment by surfnerd** [comment]
Hi @laarroyo,
Since you haven't update this issue with any information, we will close it for now. Please reopen it if you can clarify your problem and give us additional information in order to help you.
