### ISSUE TITLE
Academy::maxSteps is private

### ISSUE THREAD

**Issue by ulyssesp** [Unity-Technologies/ml-agents#2529]
**Is your feature request related to a problem? Please describe.**
Making `Academy::maxSteps` private forces users to use agent's max steps to do rewards over episode.

**Describe the solution you'd like**
Make `Academy::maxSteps` public or provide a public accessor.

**Describe alternatives you've considered**
Using Agent::maxSteps

**Additional context**
It's been requested before in https://github.com/Unity-Technologies/ml-agents/issues/1263

**Comment by chriselion** [comment]
Hi @ulyssesp,
Thanks for the suggestion. We'll take it under consideration, but Academy::maxSteps is likely going to be removed soon (in https://github.com/Unity-Technologies/ml-agents/pull/2519/files).

**Comment by ulyssesp** [comment]
Nevermind then! I'll switch to using agent maxSteps. Thank you.
