### ISSUE TITLE
Imitation learning(online and offline ) too slow

### ISSUE THREAD

**Issue by rajatpaliwal** [Unity-Technologies/ml-agents#2538]
Hi,
While doing online or offline behavioral cloning  training is taking place too slowly. As per tensorboard for completing 1000 steps it is taking around 4min and 30 seconds. I tried clearing the buffer by pressing "C" during training.
Earlier it was faster but as I started doing more iterations of training it has suddenly became lot slower.

Any suggestion would be helpful!!

**Comment by awjuliani** [comment]
Hi @rajatpaliwal 

This is expected behavior, as there is a large amount of training which takes place between steps of the simulation during behavioral cloning. Does your agent improve?

**Comment by rajatpaliwal** [comment]
Yes, slowly it starts doing imitation . But earlier it used to show the similar behavior with training steps being completed faster. What might have changed now?

**Comment by awjuliani** [comment]
Do you mean with a previous version of ML-Agents?

**Comment by rajatpaliwal** [comment]
Yes, earlier I was using v0.8
