### ISSUE TITLE
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by barotdhrumil21** [Unity-Technologies/ml-agents#254]
---------------------------------------------------------------------------
ConnectionResetError                      Traceback (most recent call last)
<ipython-input-9-7956f08e80bc> in <module>()
     49     steps, last_reward = sess.run([ppo_model.global_step, ppo_model.last_reward])
     50     summary_writer = tf.summary.FileWriter(summary_path)
---> 51     info = env.reset(train_mode=train_model, progress=get_progress())[brain_name]
     52     trainer = Trainer(ppo_model, sess, info, is_continuous, use_observations, use_states, train_model)
     53     if train_model:

C:\Users\user\Documents\tf\Assets\ml-agents-master\python\unityagents\environment.py in reset(self, train_mode, config, progress)
    258 
    259         if self._loaded:
--> 260             self._conn.send("RESET")
    261             try:
    262                 self._conn.recv(self._buffer_size)

ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

This is insane.Any idea why the hell this is happening.

**Comment by vincentpierre** [comment]
This is the first time I see this error. What command were you running and what branch are you on ? Can you give additional details ?
I would first try changing the worker_id, there might be something happening on the port you are using.

**Comment by barotdhrumil21** [comment]
Go to Edit -> Project Settings -> Player

    Ensure that Resolution and Presentation -> Run in Background is Checked.
    Ensure that Resolution and Presentation -> Display Resolution Dialog is set to Disabled.

Expand the Ball3DAcademy GameObject and locate its child object Ball3DBrain within the Scene hierarchy in the editor. Ensure Type of Brain for this object is set to External.


forgot this part totally.now it's working.but why the hell winerror

**Comment by ElliotWood** [comment]
I am experiencing this also after a few minutes of training. 

> INFO:unityagents: CrusherBrain: Step: 600. Mean Reward: 575.249. Std of Reward: 430.425.
> Traceback (most recent call last):
>   File "learn.py", line 62, in <module>
>     tc.start_learning()
>   File "C:\Users\gigaf\source\repos\tensorflow\ml-agents\python\unitytrainers\trainer_controller.py", line 253, in start_learning
>     text_action=take_action_text)
>   File "C:\Users\gigaf\source\repos\tensorflow\ml-agents\python\unityagents\environment.py", line 470, in step
>     self._send_action(vector_action, memory, text_action)
>   File "C:\Users\gigaf\source\repos\tensorflow\ml-agents\python\unityagents\environment.py", line 345, in _send_action
>     self._conn.recv(self._buffer_size)
> ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "C:\Users\gigaf\source\repos\tensorflow\ml-agents\python\unityagents\environment.py", line 485, in close
>     self._conn.send(b"EXIT")
> ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
> 
> C:\Users\gigaf\source\repos\tensorflow\ml-agents\python>

Config

> CrusherBrain:
    use_recurrent: true
    sequence_length: 64
    num_layers: 2
    hidden_units: 128
    memory_size: 4096
    beta: 1.0e-2
    gamma: 0.99
    num_epoch: 3
    buffer_size: 1024
    batch_size: 512
    max_steps: 5.0e5
    summary_freq: 300
    time_horizon: 64
