### ISSUE TITLE
Significant delay only in inference decisions (Barracuda.Dense)

### ISSUE THREAD

**Issue by FlimFlamm** [Unity-Technologies/ml-agents#2546]
EDIT:  solution has been found: **GPU inferencing**

It looks like the problem is down to C# optimization. another fix that was suggested was [barracuda burst](https://github.com/Unity-Technologies/barracuda-burst-release) because it optimizes c# which helps with CPU inferencing in barracuda. But because the GPU fix is so fantastic, I wont even need to try it. I had assumed that i needed a cuda enabled GPU for inferencing, but it is only training which requires it. Huzzah! (big big thanks to Mantasp from the discord!)

I'll leave the discussion open for a few days in-case anyone would like to comment or add their thoughts. (mods, please feel free to close it at your leisure should I tarry)

------------------------------------

Has anyone else noticed that training mode is faster than inference mode?

Ive been training a network that is 2048 hidden units wide and 3 hidden layers deep (not using normalization, recurrence, or curiosity), with an observation space of about 350 floats and an output space of 40 continuous floats.

I've had recent successes with training, but in inference mode there is a really significant lag that occurs on decision steps (from Barracuda.Dense according to the profiler). I'm guessing that this is because of the layer and observation size, but why would training mode be so much faster( without lag entirely)?

I'm wondering if this is simply down to optimization in the external trainer vs the barracuda inference engine.

Thoughts?

EDIT: the delay is significant with even a single agent, but it does not drastically increase as additional agents are added.

**Comment by FlimFlamm** [comment]
![demspikes](https://user-images.githubusercontent.com/24987395/64755993-81c06a80-d503-11e9-92cf-24e1d15a1c27.png)

**Comment by FlimFlamm** [comment]
Did some quick testing and it looks like layer width is the main culprit.

At 1024 width the lag from the dense layers is about 51 ms, which is hard to notice, but with a layer size of 2048 the lag from Barracuda.Execute is 170 ms, which is game-ruining.

**Comment by mantasp** [comment]
we are working on faster matrix multiplication across CPU platforms, for present moment GPU inference is the best choice for bigger models / more agents in single batch
