### ISSUE TITLE
Tensorflow 1.5 support

### ISSUE THREAD

**Issue by NinaMaz** [Unity-Technologies/ml-agents#255]
Hello! Does ml-agents support tensorflow-gpu 1.5? I am also using CUDA 9 and cuDNN 7 with it as well as Python 3.5.2.
From what I have seen so far, when I run "pip install ." from python sup-directory, it tries to download tensorflow 1.4. Is there any way to avoid that and somehow reconfigure it to use 1.5 version instead?

**Comment by HappySlice** [comment]
While you're waiting for a response from the devs here, I'd say in the meantime just set up a special environment in Anaconda.
https://conda.io/docs/user-guide/tasks/manage-environments.html

**Comment by vincentpierre** [comment]
When I try to pip install tensorflow, the default version is r1.4
Maybe r1.5 is not yet the default pip package.
I have not tested ML-Agents with r1.5, some methods may have changed
slightly and might need to be updated but it should be working.
I would try remove the first line (tensorflow>=1.0) in
requirements.txt in the python folder of ML-Agents, this should
prevent the download of tensorflow r1.4.

**Comment by NinaMaz** [comment]
Thank you for the answer! It works!
