### ISSUE TITLE
TestPerception3d test fails Window->Test Runner with 3D ball scene loaded

### ISSUE THREAD

**Issue by andrewcoh** [Unity-Technologies/ml-agents#2558]
The unit test TestPerception3d fails (Window->Test Runner) with 3D ball scene loaded.

To reproduce on branches master or develop:
1. Load 3D ball scene
2. Window->Test Runner
3. Run all.

**Comment by awjuliani** [comment]
Thanks @andrewcoh 

I'll look into this one.
