### ISSUE TITLE
Unity logo problem

### ISSUE THREAD

**Issue by haoxiangli6** [Unity-Technologies/ml-agents#2565]
Hello, guys. When I try to use mlagents in Windows, Unity logo become weird in the console. 
Anyone know how to resolve it?
![logoerror](https://user-images.githubusercontent.com/25996824/64942170-f9dbb700-d89a-11e9-8b0a-36ef9150a3aa.PNG)

**Comment by awjuliani** [comment]
Hi @haoxiangli6 

This seems to be an issue caused by the font being used in your console. The logo is designed to display with certain fixed-width fonts, which yours seems to not be one of.

**Comment by TheMartianLife** [comment]
Weirdly, it actually doesn't look like that font's character width is too inconsistent, but it is likely still the cause.

![64942170-f9dbb700-d89a-11e9-8b0a-36ef9150a3aa](https://user-images.githubusercontent.com/25126921/65198697-6fc46600-dac7-11e9-8d52-4888a4af4663.PNG)

To change the font in Windows 10 CMD:

1. search "Command Prompt" in the start bar
2. right click the result > 'Open File Location'
3. right click the Command Prompt executable (now shown in the File Explorer) > 'Properties'
4. click the 'Fonts' tab and select something monospaced (generally anything with Mono or Console in the name, or if there's a default selection)

Hope that helps! + Either way the logo is not going to affect the framework performance 🙃

**Comment by awjuliani** [comment]
Sorry for the delayed response. Thanks for checking on this. We will try to see how we might resolve it so that we can avoid people seeing the deformed logo :)
