### ISSUE TITLE
ERROR: mlagents 0.9.3 has requirement mlagents-envs==0.9.3, but you'll have mlagents-envs 0.8.2 which is incompatible.

### ISSUE THREAD

**Issue by avatcc** [Unity-Technologies/ml-agents#2578]
when i try to pip install -e .
It shows:
> ERROR: mlagents 0.9.3 has requirement mlagents-envs==0.9.3, but you'll have mlagents-envs 0.8.2 which is incompatibl

what should i do ?

**Comment by awjuliani** [comment]
Hi @avatcc 

Please uninstall your old version of `ml-agents-envs`, and then try to reinstall `ml-agents`.

**Comment by surfnerd** [comment]
Hi @avatcc,
Thank you for your question.  We hope the advice from @awjuliani has solved your problem.  We will close this issue for now, but if you have further questions about this issue, please feel free to reopen it.
