### ISSUE TITLE
<Product Name> incompatible with mlagents-learn

### ISSUE THREAD

**Issue by TiNovTec** [Unity-Technologies/ml-agents#2588]
**Describe the bug**
The Unity Editor -> Project Settings -> Product Name: "Unity Environment" is incompatible with mlagents-learn with build apps. ( for example mlagents-learn config/trainer_config.yaml --env=BuildFolder/Unity Environment.exe --run-id=RunIdentifier --train ).

The learning simply doesn't start without any warning or error message!

The Product Name should be "UnityEnvironment" instead of "Unity Environment".

**To Reproduce**
1. Use any example and try to train it with a build app and the default demo settings.

**Console logs / stack traces**
none

**Environment (please complete the following information):**
- OS: Windows 10
- _ML-Agents version_: latest `develop`

**Comment by harperj** [comment]
Hi @TiNovTec -- we regularly train builds with that product name, so I think it's unlikely that is what's causing the issue.  Does anything at all come up in the console after you enter your command?

One issue I see as a potential problem is that your `.exe` file is two words.  You may need to escape the space in your path to `BuildFolder/Unity\ Environment.exe`

**Comment by TiNovTec** [comment]
Yes, @harperj. It's the white space. And no, escaping doesn't work and wouldn't be user-friendly at all. So please just change the name to contain no white space! xD

[Here is what I see.](url=https://imgur.com/a/KUAGqqX)

**Comment by harperj** [comment]
Hi @TiNovTec, request noted to share with the team.  In the meantime you can create your build with a different name (without the space) or escape the space in a different way.  I think my suggestion of the forward slash was incorrect, on Windows I believe [you can escape with ^](https://stackoverflow.com/questions/32457007/how-to-escape-space-in-file-path-in-windows-run).

**Comment by chriselion** [comment]
This was fixed in our examples in https://github.com/Unity-Technologies/ml-agents/pull/3612. Closing this.
