### ISSUE TITLE
White Space & Python

### ISSUE THREAD

**Issue by TiNovTec** [Unity-Technologies/ml-agents#2589]
Windows 10 with Unity 2018.4 and latest development version of ML

I have tried to add the parameters
`use_recurrent: true`
`sequence_length: 64`
`memory_size: 256`
to the GridWorld demo scene, simply with camera observation instead of the render texture, and get errors like:
`...
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "config/trainer_config.yaml", line 261, column 1`
Line 261 is sequence_length.
Why doesn't it work ?

**Comment by TiNovTec** [comment]
OK. My fault.
Visual Studio adds invisible tabs to the text document.
With Edit -> Advanced -> View White Space this can be seen.
Just use Spacebar key several times instead of Tab key.
xD

**Comment by TiNovTec** [comment]
I think it would be nice to have this is this section:
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-ML-Agents.md#training-config-file

Most developers use C# and are not familiar with Phyton's bitchiness.

**Comment by harperj** [comment]
Hi @TiNovTec -- glad you were able to figure out the problem.  We're looking into better ways of surfacing white space issues in our config files.  I'm going to close this Github issue since you've figured it out
