### ISSUE TITLE
Currently which is better CPU or GPU for training?

### ISSUE THREAD

**Issue by ewan15** [Unity-Technologies/ml-agents#2597]

**Comment by harperj** [comment]
GPU training is generally better (depending on hyperparameters) but never worse in our tests.  If you use the SAC trainer you should see substantial improvement using GPU for training.

**Comment by Phantomb** [comment]
@harperj is that only the case when using visual (camera) observations, or also in general with non-visual states?

**Comment by harperj** [comment]
@Phantomb with non-visual observations you'll likely see less of a benefit (possibly no benefit).  You'll start to see more of a benefit as the batch/buffer size increase or if you use a larger neural network.  That's the reason SAC usually benefits sooner than PPO -- the network is larger.

**Comment by ewan15** [comment]
> 
> 
> GPU training is generally better (depending on hyperparameters) but never worse in our tests. If you use the SAC trainer you should see substantial improvement using GPU for training.

When will ml-agents support a new version of CUDA as my 2080 Ti is not compatible with the current version of CUDA?

**Comment by harperj** [comment]
@ewan15 we don't have any explicit plans around supporting certain CUDA versions, but if you explain what problems you're running into in a separate issue we may be able to suggest workarounds or plan for how to support it in the future.

**Comment by Sohojoe** [comment]
@ewan15 that doesn't sound right - I have a 2080Ti and it works ok with ml-agents. you need to install the right version of CUDA that Tensorflow was built against.

**Comment by ewan15** [comment]
@Sohojoe Thank you! I didn't realise but I was installing the patches instead of the base installer!

**Comment by surfnerd** [comment]
Hi all, thank you for your discussion.  It seems like the question has been answered.  We have shared this feedback with the team and will close this issue for now.  Feel free to re-open it if more discussion on this topic is needed.
