### ISSUE TITLE
pip install -e . ERROR

### ISSUE THREAD

**Issue by mhadji05** [Unity-Technologies/ml-agents#2599]
here

![image](https://user-images.githubusercontent.com/22151801/65315621-1892c400-dba1-11e9-919d-ccc7924d42f0.png)

i get this 

   ERROR: Command errored out with exit status 1:
     command: 'c:\users\marios\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Marios\\Downloads\\ml-agents-master\\ml-agents\\setup.py'"'"'; __file__='"'"'C:\\Users\\Marios\\Downloads\\ml-agents-master\\ml-agents\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: C:\Users\Marios\Downloads\ml-agents-master\ml-agents\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Marios\Downloads\ml-agents-master\ml-agents\setup.py", line 1, in <module>
        from setuptools import setup, find_namespace_packages
    ImportError: cannot import name 'find_namespace_packages'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

![image](https://user-images.githubusercontent.com/22151801/65315731-45df7200-dba1-11e9-86c3-dd0fb1a140ef.png)

**Comment by harperj** [comment]
Hi @mhadji05 -- thanks for reporting this to us.  Could you update `setuptools` and try again?

```
pip install -U setuptools
```

**Comment by slightperturbation** [comment]
Just ran into this also with setuptools 28.8.0. Upgrading (to 41.4.0) seems to fix it. I suspect anything past [40.1.0 when find_namespace_packages() was introduced](https://setuptools.readthedocs.io/en/latest/history.html#v40-1-0) would work.
