### ISSUE TITLE
documentation - Observing Training Progress

### ISSUE THREAD

**Issue by ssatguru** [Unity-Technologies/ml-agents#26]
for some reason the following command does not work in windows 10
tensorboard --logdir='./summaries'

You get "No scalar data was found."  on localhost:6006

the following works
tensorboard --logdir=./summaries
or
tensorboard --logdir summaries

**Comment by awjuliani** [comment]
Thanks for pointing this out @ssatguru! I've just amended the documentation: https://github.com/Unity-Technologies/ml-agents/commit/fcf535cbfe73f7e3cb516623f9d62389870b80ed
