### ISSUE TITLE
set initial values for reset parameters

### ISSUE THREAD

**Issue by Fuseques** [Unity-Technologies/ml-agents#2602]
Is there a way to set initial values for the academy's reset parameters in a unity build using mlangents-learn?
Currently I can use curricula with a single difficulty to achieve that but it is a bit of an overkill especially with multiple brains in the scene (requires duplicating of the parameter value files for each of the brains)

**Comment by harperj** [comment]
Thanks for submitting this request. I’ve added it to our internal tracker with the ID MLA-86. I’m going to close this issue for now, but we’ll ping back with any updates
