### ISSUE TITLE
UWP build with ML-Agents

### ISSUE THREAD

**Issue by weizhuang-93** [Unity-Technologies/ml-agents#2605]
i tried to use ML-Agents with UWP, in order to run a TF Model on HoloLens (Version1). but the build failed.
how to reproduce, copy .\UnitySDK\Assets\ML-Agents to a new unity project and build. i have the following error:

`Assets\ML-Agents\Scripts\UnityAgentsException.cs(23,69): error CS0234: The type or namespace name 'SerializationInfo' does not exist in the namespace 'System.Runtime.Serialization' (are you missing an assembly reference?)`

using:
Scripting Runtime Version: Experimental .Net 4.6 Equivalent
Scripting Backend: .Net
Api Compatibility Level: .Net 4.6
unity 2017.4
Unity Build UWP

**Comment by harperj** [comment]
Hi @weizhuang-93 -- I can't seem to reproduce this with our example environments.  If you try just opening the `UnitySDK` project and building one of the example environments does it work?

**Comment by weizhuang-93** [comment]
Hi, it succeeded in IL2CPP but not .NET. i really should switch my Project scripting backend to IL2CPP.
