### ISSUE TITLE
[Error] 3Dball

### ISSUE THREAD

**Issue by jaehosung** [Unity-Technologies/ml-agents#261]
When running PPO.pynb,"train the agents" creates  an error

lper(self, op_type_name, name, **keywords)
    568                   "List argument '%s' to '%s' Op with length %d shorter "
    569                   "than minimum length %d." %
--> 570                   (input_name, op_type_name, len(values), num_attr.minimum))
    571           # All tensors must have the same base type.
    572           if any([bt != base_types[0] for bt in base_types]):

ValueError: List argument 'values' to 'ConcatV2' Op with length 0 shorter than minimum length 2.

**Comment by vincentpierre** [comment]
Thank you. @awjuliani pushed a fix. Let us know if you face this error after pulling. Thank you!
