### ISSUE TITLE
Cannot load generated nn to learning brain

### ISSUE THREAD

**Issue by maxirejlis** [Unity-Technologies/ml-agents#2623]
Hi,

I have been struggling a few days with this, so any help is appreciated.

The problem is that im not able to **assign the nn model I generated on the Learning Brain**.

These are the main things that might be useful to find the problem (if you need more info just tell me) are the following:

- **On the Inspector (Brain)**: When I try to add the model to the brain, there's a message saying: There is no model for this Brain, cannot run inference. (But can still train)
  - *Note that this message only appears after I try to drag the generated nn.*
- **On the Inspector (NN):** in the lower section it has in script (None) and a compile error.
- **On the player settings:** I copied the sample project (that you clone and have a lot of examples)
- **On the anaconda prompt:** I also get this message when training the ball, I can still train without problems.

`2019-09-25 19:02:11.235799: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
INFO:mlagents.envs:Hyperparameters for the PPOTrainer of brain RollerBallBrain:`

Im trying to set up a simple project following the documentation files.
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md

**Comment by chriselion** [comment]
Hi @maxirejlis 
> in the lower section it has in script (None) and a compile error.

What's the compiler error that you're seeing? It's probably important to fix that first.

> `2019-09-25 19:02:11.235799: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2`

This is a warning from tensorflow but it's safe to ignore. There's some more info here https://stackoverflow.com/q/47068709/224264. Definitely don't spend any time on it until you get the basics working 😄 

> `INFO:mlagents.envs:Hyperparameters for the PPOTrainer of brain RollerBallBrain`

This is just some diagnostic information output by ml-agents. It's safe to ignore too.

**Comment by maxirejlis** [comment]
I cannot particularly find where is the compile error, I'm not super experienced with Unity, if there's a specific log folder I can find or anything I'll add any additional data.
(See attached images)

![no error](https://user-images.githubusercontent.com/8903187/65651049-96acfb80-dfe3-11e9-958d-e42669859cae.png)


![no error vs](https://user-images.githubusercontent.com/8903187/65651050-96acfb80-dfe3-11e9-9265-5511f3720396.png)

I'll add additional information about the setup to see if you see something weird too.
I followed Windows install documentation but skipped step 4:
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation-Windows.md

Also, I installed Anaconda at this location: C:\Users\Maxi\Anaconda3
And use the following line to train the model (I dont think here's the problem as I seem to be able to create the nn file without problems...)
`C:\Users\Maxi\Documents\Unity ML\ML-Project\ML>mlagents-learn trainer_config.yaml --run-id=test1 --train`

**Comment by surfnerd** [comment]
Hi @maxirejlis,
In order to help us diagnose your issue could you follow these steps:

- Close unity.
- Reopen Unity.
- Do the same steps you are currently doing to attach the NN to the brain.
- Find the editor log and attach it to this issue.  (You can find your editor log by looking at [this page](https://docs.unity3d.com/Manual/LogFiles.html)).  

Based on the information you've given I can't say exactly what the issue is.  Have you by any chance modified the `NNModelImporter.cs` file?  Could you check that file and make sure that the file name matches the class name **exactly**.   Thank you.

**Comment by surfnerd** [comment]
Also, it looks like you may be missing the Barracuda plugin.  I don't see the NNModel script in your editor screen shot.  Can you verify that your Barracuda plugin is in the right place?

**Comment by maxirejlis** [comment]
I ended up replacing the Library Folder with the sample project and that seemed to fix the issue, personally I think the problem was that I think I didnt drag the ML-Agent folder but copy/pasted it.

So at the very least if someone else is having this problem, they might try to do that,

Thanks a lot for the help.

**Comment by chriselion** [comment]
Glad you got it working!
