### ISSUE TITLE
ml-agents versions vs unity versions

### ISSUE THREAD

**Issue by wardVD** [Unity-Technologies/ml-agents#2628]
Is it possible to document which unity versions are compatible with each ml-agents versions. We believe we have problems with ml-agents 0.9.3 and unity 2019.1.8f, but don't know if these versions support each other.

**Comment by dietervh** [comment]
I would love to see documentation that shows compatible versions of Unity for each ml-agents version. Unity 2019.2 broke my ml-agents projects so had to revert them to Unity 2019.1.14

**Comment by chriselion** [comment]
Hi @wardVD and @dietervh,
As a general rule, we support the Long Term Support (LTS) versions here https://unity3d.com/unity/qa/lts-releases and newer versions.

I do know of one issue that affected some newer versions, which was fixed here: https://github.com/Unity-Technologies/ml-agents/pull/2580

Is that the same issue you both encountered, or was there another issue? Can you provide more details?

**Comment by wardVD** [comment]
Hi @chriselion,

Thank you for the reply. We encountered the same error, yes.

Still, I believe it should be made more clear that in general lTS versions and later are supported. Can this be added more clearly in the documentation?

**Comment by chriselion** [comment]
Agreed, we should make this clearer. I'll log this as a task; hopefully we'll get to it in our next sprint...

**Comment by surfnerd** [comment]
Hi @wardVD,
Thanks for your feedback.  We've logged this internally with ID MLA-78.  We will close this issue for now and ping back when we have any updates.
