### ISSUE TITLE
Running MLAgents on Linux with visual observations

### ISSUE THREAD

**Issue by koryakinp** [Unity-Technologies/ml-agents#2631]
I have build a custom environment with visual observations using **MLAgents 0.9.2** and I have no problem running it on Windows.

However, when running it inside a docker container I have the following error:

> mlagents.envs.exception.UnityTimeOutException: The Unity environment took too long to respond.

I have created a [simple repository](https://github.com/koryakinp/mlagents-issue) to reproduce that issue. Any help would be greatly appreciated.

Pavel

**Comment by chriselion** [comment]
Hi @koryakinp,
Unfortunately we're not able to help debug custom environments.

Can you provide more logs from the trainer and environment? That might help diagnosing the issue. I doubt that visual observations are the problem here, but it might be worth disable them to simplify the problem.

I'm not that familiar with Docker, but can you make sure that the trainer and the environment can communicate over the right port? This defaults to 5005, but you might need to configure Docker to enable this.

**Comment by koryakinp** [comment]
@chriselion, I am not asking to help me with debugging the environment. In fact, there is nothing wrong with the environment as I was able to run it on Windows. I just need some help with configuring to run it inside Docker container. 

5005 port is enabled in Docker configuration: 

> EXPOSE 5005 

Here is a full stack trace of the exception:

> Found path: /mlagents-issue/environments/mldriver-discrete-steering.x86_64
> Mono path[0] = '/mlagents-issue/environments/mldriver-discrete-steering_Data/Managed'
> Mono config path = '/mlagents-issue/environments/mldriver-discrete-steering_Data/MonoBleedingEdge/etc'
> Preloaded 'libgrpc_csharp_ext.x64.so'
> Unable to preload the following plugins:
> 	ScreenSelector.so
> Display 0 '0': 128x128 (primary device).
> PlayerPrefs - Creating folder: /root/.config/unity3d/DefaultCompany
> PlayerPrefs - Creating folder: /root/.config/unity3d/DefaultCompany/Cars
> Logging to /root/.config/unity3d/Editor/Player.log
>   File "main.py", line 4, in <module>
>     file_name="environments/mldriver-discrete-steering", worker_id=1)
>   File "/usr/local/lib/python3.6/dist-packages/mlagents/envs/environment.py", line 101, in __init__
>     aca_params = self.send_academy_parameters(rl_init_parameters_in)
>   File "/usr/local/lib/python3.6/dist-packages/mlagents/envs/environment.py", line 676, in send_academy_parameters
>     return self.communicator.initialize(inputs).rl_initialization_output
>   File "/usr/local/lib/python3.6/dist-packages/mlagents/envs/rpc_communicator.py", line 84, in initialize
>     "The Unity environment took too long to respond. Make sure that :\n"
> mlagents.envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
> 	 The environment does not need user interaction to launch
> 	 The Academy's Broadcast Hub is configured correctly
> 	 The Agents are linked to the appropriate Brains
> 	 The environment and the Python interface have compatible versions.

And here what I have in **/root/.config/unity3d/Editor/Player.log:**

> Error loading /mlagents-issue/environments/mldriver-discrete-steering_Data/Plugins/x86_64/ScreenSelector.so: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
> Desktop is 128 x 128 @ 0 Hz
> Unable to find a supported OpenGL core profile
> Failed to create valid graphics context: please ensure you meet the minimum requirements
> E.g. OpenGL core profile 3.2 or later for OpenGL Core renderer
> Vulkan detection: 0
> No supported renderers found, exiting
>  #0 ???
>  #1 ???
>  #2 ???
>  #3 __libc_start_main
>  #4 ???
>  
> (Filename: ./PlatformDependent/LinuxStandalone/main.cpp Line: 639)

**Comment by chriselion** [comment]
Hi,
This
> No supported renderers found, exiting

makes it sound like Unity is quitting before it can start trying to communicate with the python trainer. I think you need to resolve that problem first.

**Comment by koryakinp** [comment]
@chriselion I was able to make it run on ubuntu **16.04**, apparently **xvfb** tool does not work well with ubuntu 18.
In case anyone have difficulties with running **MLAgents** with visual observations inside docker I have created a [branch](https://github.com/koryakinp/mlagents-issue/tree/mlagents-issue-fixed) with the working setup for Docker.

**Comment by chriselion** [comment]
Glad you were able to get it working.
Do you have any more information on the problems between xvfb and ubuntu 18? If so we can add it to the documentation.

**Comment by koryakinp** [comment]
@chriselion [Here](https://github.com/Unity-Technologies/ml-agents/issues/1786) is much bigger discussion regarding xvfb on ubuntu 16/18.

**Comment by anupambhatnagar** [comment]
A solution for using xvfb with ubuntu 18.04 has been posted [here](https://github.com/Unity-Technologies/ml-agents/issues/1786)
