### ISSUE TITLE
Error on Unity 2019.2.6

### ISSUE THREAD

**Issue by albertbuchard** [Unity-Technologies/ml-agents#2633]
**Describe the bug**
I cannot run ml agent example in 2019.2.6. 

**To Reproduce**
Install 2019.2.6
Clone ml-agent
Run 3DBall scene

**Console logs / stack traces**
```
ArgumentException: An item with the same key has already been added. Key: Platform (Ball3DAgent)
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
MLAgents.Brain.SendState (MLAgents.Agent agent, MLAgents.AgentInfo info) (at Assets/ml-agents/UnitySDK/Assets/ML-Agents/Scripts/Brain.cs:56)
MLAgents.Agent.SendInfoToBrain () (at Assets/ml-agents/UnitySDK/Assets/ML-Agents/Scripts/Agent.cs:655)
MLAgents.Agent.SendInfo () (at Assets/ml-agents/UnitySDK/Assets/ML-Agents/Scripts/Agent.cs:1048)
MLAgents.Academy.EnvironmentStep () (at Assets/ml-agents/UnitySDK/Assets/ML-Agents/Scripts/Academy.cs:626)
MLAgents.Academy.FixedUpdate () (at Assets/ml-agents/UnitySDK/Assets/ML-Agents/Scripts/Academy.cs:655)
```

**Environment (please complete the following information):**
- OS + version: OSX Mojave
- _ML-Agents version_: latest
- _Environment_: 3DBall

**Comment by chriselion** [comment]
HI @albertbuchard,
I can reproduce something similar. Can you scroll up in the logs a bit? I think you'll see something like
```
No model was present for the Brain 3DBallLearning.
UnityEngine.Debug:LogError(Object)
MLAgents.LearningBrain:DecideAction() (at Assets/ML-Agents/Scripts/LearningBrain.cs:143)
MLAgents.Brain:BrainDecideAction() (at Assets/ML-Agents/Scripts/Brain.cs:98)
MLAgents.Academy:EnvironmentStep() (at Assets/ML-Agents/Scripts/Academy.cs:558)
MLAgents.Academy:FixedUpdate() (at Assets/ML-Agents/Scripts/Academy.cs:583)
```
(the `An item with the same key has already been added` error should no longer appear after https://github.com/Unity-Technologies/ml-agents/pull/2629)

You can resolve this for now by setting the model for the 3DBallLearning brain:
![image](https://user-images.githubusercontent.com/6877802/65789886-2a311a00-e113-11e9-9322-43e3fa771fa3.png)

But I'll look into why this isn't working in newer versions.

**Comment by chriselion** [comment]
Unfortunately, we never found the root cause of the missing models. We have since increased the min version to 2018.x and updated the assets accordingly, and they no longer exhibit this problem.
