### ISSUE TITLE
visual observations with image segmentation

### ISSUE THREAD

**Issue by zako42** [Unity-Technologies/ml-agents#2634]
Is it possible to render to an agent camera with colors based on gameobject tag or collision layer?  Is it possible to do this with a shader?  I think a c# script could change the materials of gameobjects, but that would affect all cameras.  I still want to have other "normal" cameras.

I would like to do kind of like an easy version of image segmentation and try sending that as a visual observation to the agent to see if it helps training.  I was thinking this is similar to earlier questions about using depth shaders and sending that to the agent.  I don't know how much this might help, but wanted to try it out.

**Comment by chriselion** [comment]
Hi @zako42,
This is definitely something we don't support out of the box; I can't give you much guidance on the rendering side of things. But if you can get your results to a RenderTexture, you can pass that onto an Agent as a VisualObservation.

Based on quick Google search for "Unity image segmentation", this might give you some pointers 
https://bitbucket.org/Unity-Technologies/ml-imagesynthesis/src/master/ 
http://www.immersivelimit.com/tutorials/unity-image-segmentation

Hope that's helpful...

**Comment by zako42** [comment]
@chriselion Thank you very much -- both resources have great info!  It's a huge help!

**Comment by chriselion** [comment]
Great, glad it was useful!
