### ISSUE TITLE
Add tensorboard images of all examples

### ISSUE THREAD

**Issue by wardVD** [Unity-Technologies/ml-agents#2639]
ML-agents RL is extremely powerful and cool to do, but I've often hit a wall when trying to design a new environment. I haven't succeeded in building something that works, aside from the examples that are provided by your community.

Is it possible to add tensorboard images of all the examples and describe some of the features? It would be even nicer to have a page of failures and how these got solved. Right now, we only have previous issues to look through, and most of the time, the answer is something like "you'll need to experiment with the hyperparameters if you're sure your code is correct". Examples, failures, and fixes would be very helpful in learning!

**Comment by chriselion** [comment]
Hi @wardVD,
I can't promise when we'll get to this, but I logged this as a feature request in our internal tracker (MLA-47).
