### ISSUE TITLE
Depth/opticalFlow/object segmentation images as visual observation

### ISSUE THREAD

**Issue by maystroh** [Unity-Technologies/ml-agents#2644]
For visual observation, the code supports rendered image(s) from single/multiple cameras, but there is no direct way to get the depth maps. Two issues were closed (#329 and #562) requesting the depth feature. I'm wondering if it is done or not? In addition, I think depth image alone won't be enough to train an agent, rather, it would be great to have the frame stack feature that DeepMind used in the atari games (4 stacked grayscale images). 

For the first part, I already did an environment that can generate depth/opticalFlow/object segmentation images along with RGB image... something similar to this [project](https://bitbucket.org/Unity-Technologies/ml-imagesynthesis/src/master/) but not still not sure how can I use these images to train an agent using ml-agents.. I'm looking for hints/tips that can help me understand more what are the things that should be modified in ml-agents to stack multiple images of different type.

Thanks in advance.

**Comment by chriselion** [comment]
Hi @maystroh,
There hasn't been any additional work on this since the previous requests. Someone else asked something similar the other day: https://github.com/Unity-Technologies/ml-agents/issues/2634 (I found the same project that you linked to). As mentioned there, if you can get your results into a RenderTexture, ML Agents will convert it to a bitmap for visual observations.

**Comment by chriselion** [comment]
There's no support for stacking right now. You'd probably need to do some hacking around how we set up the inputs here
https://github.com/Unity-Technologies/ml-agents/blob/9370b635cb52320e0d3b73829d239f1273929021/ml-agents/mlagents/trainers/models.py#L146
and something similar when we read the protobuf and convert to np arrays here: https://github.com/Unity-Technologies/ml-agents/blob/develop/ml-agents-envs/mlagents/envs/brain.py#L188-L194

**Comment by chriselion** [comment]
I've added the request for stacking visual observations to our internal tracker with the ID MLA-52. I’m going to close this issue for now, but we’ll ping back with any updates.
