### ISSUE TITLE
cannot import name 'UnityEnvironment' from 'mlagents.envs'

### ISSUE THREAD

**Issue by BlueFisher** [Unity-Technologies/ml-agents#2653]
I just updated to Beta 0.10.0 and I noticed that the file __init__.py in mlagents/envs was empty. I recevied error `cannot import name 'UnityEnvironment' from 'mlagents.envs'` when running `from mlagents.envs import UnityEnvironment`. Is that a bug or mlagents changed the `import` way?

**Comment by StepNeverStop** [comment]
have the same issues, 'cause `__init__.py` in envs and trainers are empty.

**Comment by StepNeverStop** [comment]
a lot of problems about file references, i.e. no `.py` file named tensorflow_to_barracuda in trainers fold.

**Comment by ervteng** [comment]
Hi @BlueFisher, @StepNeverStop, which install path are you using? Are you installing from pip or from source? We haven't changed the imports from 0.9.2 in 0.10.0.

**Comment by JMFox** [comment]
I got the same error installing via pip.

**Comment by ervteng** [comment]
Hi @JMFox, which platform are you on (Windows, Linux, Mac), and which Python version? I've tried a fresh pip install on Mac with Python 3.6.5 and haven't been able to replicate

**Comment by JMFox** [comment]
I installed it using Anaconda on Windows, Python 3.6.1. I followed the installation guide in the repo. The error appears when I ran the getting_started notebook in Jupyter. I ran some of the demos in Unity and things seemed to work fine.

**Comment by ervteng** [comment]
Got it, I think I know what's going on. We'll look at the issue in more depth, but for now you should be able to import it by using `from mlagents.envs.environment import UnityEnvironment`.

**Comment by JMFox** [comment]
That worked. Thanks @ervteng

**Comment by BlueFisher** [comment]
@ervteng That worked for now. Thanks.

**Comment by chriselion** [comment]
Ah, we removed some of the `import *`'s in this PR: https://github.com/Unity-Technologies/ml-agents/pull/2584/files#diff-829b0b865c5a9e2ea85ed647b3012702L1

**Comment by jithin-pal** [comment]
use  from mlagents_envs.environment import UnityEnvironment
thanks!

**Comment by jithin-pal** [comment]
use ` from mlagents_envs.environment import UnityEnvironment`
