### ISSUE TITLE
Hindsigt Experience Replay

### ISSUE THREAD

**Issue by wardVD** [Unity-Technologies/ml-agents#2667]
I've recently read the following article regarding HER: https://arxiv.org/abs/1707.01495v3

This seems like a promising technique, but I'm not sure this is feasible to combine with PPO. Are there plans to incorporate this algorithm or similar ones in ml-agents?

**Comment by ervteng** [comment]
HI @wardVD, HER is definitely on our radar. The main change you'll have to make is that you need to output a goal state as well as a reward from your Unity environment. This isn't very generalizable as in many cases the goal state isn't defined or is a set of states (e.g. the agent should be close to an item). Welcome to give it a go and submit a PR!

**Comment by batu** [comment]
@wardVD 
You can consider using HER with the Soft-Actor Critic. As ervteng said, it is very environment-specific, yet, in certain navigation tasks, I had significant performance increases with my HER implementation. One benefit is that it reduces the dependence on reward-shaping.

**Comment by wardVD** [comment]
@batu @ervteng Thanks a lot for your feedback!

Would you be willing to show us an example you've made, @batu ?

**Comment by batu** [comment]
@wardVD Sorry I didn't respond to this at the time! Unfortunately, the code I wrote isn't public, but I can try to answer some questions if you are still working on it.
