### ISSUE TITLE
The namespace 'MLAgents' already contains a definition for 'CommunicatorParameters'

### ISSUE THREAD

**Issue by luizbalestreri** [Unity-Technologies/ml-agents#2668]
Assets\ML-Agents\Scripts\ICommunicator.cs(6,19): error CS0101: The namespace 'MLAgents' already contains a definition for 'CommunicatorParameters'

It seems to have a conflict between the Communicator interface and the Communicator file.

**To Reproduce**
Opened the UnitySDK folder on Unity 2018.3.1f1, the error showed as soon as Unity starts.

**Environment (please complete the following information):**
- OS + version: Windows 10
- _ML-Agents version_: ML Agents 0.10

**Comment by surfnerd** [comment]
Hi @luizbalestreri,
We renamed the Communicator.cs file to ICommunicator.cs to be more closely aligned with Unity's coding conventions.  If you've copied the UnitySDK folder over, and didn't delete the old files this will happen.  Please delete the old UnitySDK folder and then copy the new one over.  This should solve your issue.

**Comment by luizbalestreri** [comment]
thank you very much
