### ISSUE TITLE
Using GPU is better than CPU now?

### ISSUE THREAD

**Issue by Hongsungchan** [Unity-Technologies/ml-agents#2682]
What's better for GPU and CPU now when using ML Agent?

PPO cpu better?
SAC GPU better?

I want to reinforce learning in an environment like Dota or League Of Legend.

**Comment by ervteng** [comment]
It really depends on your setup. Generally GPU is faster, but for small networks you'll see little improvement. For large networks (e.g. visual observations, lots of vector obs) GPU will give a big gain, and especially on SAC.
