### ISSUE TITLE
Does Ml Agent support hierarchical reinforcement learning ???

### ISSUE THREAD

**Issue by Hongsungchan** [Unity-Technologies/ml-agents#2683]
I'm going to make a MOBA game(in unity)and apply ML agent.

Does Ml Agent support hierarchical reinforcement learning?

I'm trying to make an AD carry that only likes to kill enemies.

And I'm going to create an agent (Tank, Support) to help AD carry to win.

I'm experimenting with the possibility of assisting aggressive gamers like Adcarry with machine learning.

**Comment by ervteng** [comment]
You can assign different Brains for the different levels of the hierarchy. However, there's no special treatment for HRL (all brains will train at the same time) in the training, so you'll have to be clever about it to get it to train stably.
