### ISSUE TITLE
Building and Training on COLAB

### ISSUE THREAD

**Issue by taesiri** [Unity-Technologies/ml-agents#2684]
Hi Everyone,

I'd like to share my own setup for training ml-agents on COLAB. It is a fairly simple setup but it helped me save some time. I make changes to the environment I want locally and push the changes to Github. After that, I build the environment in the COLAB and train the model I want. I should mention that installing Unity on COLAB and building a project taking 5 up to 15 minutes.

[Here is the link to my COLAB notebook](https://colab.research.google.com/drive/1ip21G7MKqVbmmtdQ8Km7Rax0Cxi-eKrT)

![Screen Shot 2019-10-07 at 12 31 42 AM](https://user-images.githubusercontent.com/588431/66276170-2339a280-e89d-11e9-8384-2b0a120cbad7.png)

I used some scripts from [unity3d-gitlab-ci-example](https://gitlab.com/gableroux/unity3d-gitlab-ci-example) for building the Unity project. For example, I copied and modified [BuildCommand.cs](https://gitlab.com/gableroux/unity3d-gitlab-ci-example/blob/master/Assets/Scripts/Editor/BuildCommand.cs) into my project. The modification is in the ``GetEnabledScenes`` method and it's only 1 line. I only return the name of the scene I want to get build.

The whole setup is very simple at the moment. If anyone from ml-agent team is interested, I can make a PR with an appropriate ``BuildCommand`` file and a sample notebook.

**Comment by ervteng** [comment]
Hi @taesiri, thank you for sharing! This will be useful for others for sure. @unityjeffrey perhaps we can look into linking the tutorial in some way?

**Comment by xiaomaogy** [comment]
Hi @taesiri, this looks really nice! I've tried to walk through your notebook, but on the step of "Activate Unity" I got a few error messages saying "invalid option -- o" etc, so I wasn't able to proceed. 

![image](https://user-images.githubusercontent.com/5985076/66784099-53c99f80-ee8e-11e9-8ebc-76b3a45cdc4a.png)

**Comment by taesiri** [comment]
@xiaomaogy, I think you haven't installed Unity yet. Either ``$UNITY_EXEC`` is pointing to the wrong path or you've forgotten to accept the License Agreement.

![Screen Shot 2019-10-15 at 1 52 15 AM](https://user-images.githubusercontent.com/588431/66786956-f6b20600-eeee-11e9-879b-51becf7e545d.png)

After executing the above cell, you have to accept the License Agreement by pressing ``y`` in the textbox which appeared bellow the cell.

That being said, It is better to activate Unity using the second method. For some reason passing the password in the command line is problematic.

**Comment by taesiri** [comment]
[Here](https://youtu.be/KeLCMV7Larw) is a video demo of the notebook

**Comment by xiaomaogy** [comment]
@taesiri Thanks for the video, I will try again. I was really confused by "Upload ulf file in colab using the left side-bar.", because I wan't able to see the Files tab and switch to it, and the video helped me find it.

**Comment by xiaomaogy** [comment]
I was able to go through the whole process, it looks really good! I was especially impressed by the convenience of this solution, everything is laid out nicely in just one place. The tensorboard, training console and the files can all be managed in one place (if we can somehow visualize the unity, that would be even better). 

Regarding the setup part, aside from a little bit confusion in the license activation part(and the video helped a lot), all of the other steps are really smooth. We've been using Unity's Cloud Build internally for CI, which does the build process for us. Your demo shows us how to do this in the cloud by ourselves. 

One thing I'm curious about is you mentioned that this setup helps you save time. Could you please elaborate more on this if you don't mind?

**Comment by taesiri** [comment]
@xiaomaogy 
I am glad you liked it. I prepared this notebook very quickly, and surely, we can add a better explanation for each cell to reduce confusion.

I also had some thoughts about visualizing Unity's output. I am pretty sure we can add it either through some sort of ``xvbf`` hack or a minor modification in the ml-agents.

About the time-saving part,  I like to modify/create different environments, and training agents on them can be time-consuming (I only have two computers). With this setup, I can use COLAB to train more agents simultaneously. The training power part aside, I think it is really convenient to push your C# code changes to the GitHub and let the scripts do the compiling job for you. (After installing Unity in one COLAB session, you can reuse it until the session expires.) Surely one can make a Linux build locally and upload the binaries in COLAB (or in any other Linux servers), but it time consuming compared to automatic builds. (I also have bad internet connection which makes upload process painful)

**Comment by xunyiljg** [comment]
Thank you for sharing. I have also successfully used colab.

**Comment by taesiri** [comment]
@xunyiljg I'm glad you liked it 😊.

Just a quick update:

- I was able to stream Unity's graphical output to Twitch directly from a COLAB notebook. In my early attempts  ``xvbf`` gave me a headache so I switched to Xorg virtual desktop. My current notebook is a mess but I will share it after I cleaned it up.
- I also wrote a script to alter a scene before building the game. It comes handly to change few things like mark a ``Brain`` as trainable in the ``BroadcastHub`` directly in COLAB.
- I saw other people have some struggle running Unity in headless server with graphical output (**without** ``--no-graphics`` flag). For example #1786 marked as closed without any solution or workaround. I will write a tutorial for this later.
- The choice of Twitch is totally optional. I used ``ffmpeg`` to capture the screen. You can just save the video on Google Drive instead.
- The current setup is super inefficient! I will do some benchmark to find good parameters for broadcasting. 



![Screen Shot 2019-10-24 at 10 41 30 PM](https://user-images.githubusercontent.com/588431/67517467-899d2e00-f6af-11e9-85ee-f6f36df4833a.png)

**Comment by taesiri** [comment]
Here is the [Link](https://colab.research.google.com/drive/1mVIuqSCmgWVA84kMsWPKmh8ygbhERWfn) to my updated notebook. It works with the latest beta version of [ml-agents 0.11](https://github.com/Unity-Technologies/ml-agents/releases/tag/0.11.0). I should mention that I am really happy with the changes made in this version.



- Now you can build any scene from the ml-agents repository and train it on COLAB. I used the ``input`` interactive widget and let the user choose which see he or she wants to build.

![Screen Shot 2019-11-05 at 8 54 30 AM](https://user-images.githubusercontent.com/588431/68180701-e4852e00-ffa9-11e9-8f74-5c9f61e70c2d.png)

- You can either train in headless (no graphics) mode or stream the output to Twitch.  You can get your stream key [here](https://www.twitch.tv/taesiri/dashboard/settings).

- I used ``i3`` for managing windows as its super lightweight and easy to work with. You can interact with it through the ``i3ipc`` python package.

![training](https://user-images.githubusercontent.com/588431/68180622-ac7deb00-ffa9-11e9-83f2-f8e4b133afb3.jpg)


Happy Coding!

**Comment by vwxyzjn** [comment]
@taesiri It doesn't work anymore. See

![image](https://user-images.githubusercontent.com/5555347/74548229-75f62b80-4f1b-11ea-9434-78db134316c7.png)

I think `list_of_scenes` needs to be adjusted
```
# list_of_scenes = list(Path('/content/my-agents/UnitySDK/Assets/ML-Agents/Examples/').rglob('*.unity'))
list_of_scenes = list(Path('/content/my-agents/Project/Assets/ML-Agents/Examples/').rglob('*.unity'))
``` 

But then when I try to build it, I have another error

![image](https://user-images.githubusercontent.com/5555347/74548385-bd7cb780-4f1b-11ea-80a9-cd85318bfd7b.png)

I feel like there should be a guide on how to build all example envs headlessly... What if I want to train everything in the server where no GUI is available? The current guides do not seem to cover these instructions.

**Comment by taesiri** [comment]
Hi @vwxyzjn.

I do not maintain that notebook anymore as there was little to no feedback from the community. I have a version of this notebook that works with my own fork of ``mlagents``. You are more than welcome to copy my notebook and fix the issue you mentioned. The master branch is changing rapidly; I strongly suggest to switch to one of the stable release branches. 

**Some notes for you:**
* Upgrade the version of Unity to 2019.3, Here is the [URL](https://beta.unity3d.com/download/27ab2135bccf/UnitySetup-2019.3.0f6) for latest Linux version of Unity

* You'll probably run into more issues when compiling a project, I strongly suggest to take a look at [this repository](https://gitlab.com/gableroux/unity3d/). For example, [this issue](https://gitlab.com/gableroux/unity3d/issues/35) will help you to solve a problem related to the sound card.

* Instead of TensorBoard in Colab, Try [Tensorboard.dev](https://tensorboard.dev/). (Or you can use [WandB](www.wandb.com))

Cheers,
M
