### ISSUE TITLE
ML-Agents Beta 0.10.0 , The API number is not compatible between Unity and python

### ISSUE THREAD

**Issue by graybob** [Unity-Technologies/ml-agents#2685]
*
Hi ,
 
First of all Thanks to Unity for providing this Splendid ML-Agents . 

Getting below error with latest version , please help.

1) Checked out latest ML-Agents Beta 0.10.0  .

2) As mentioned in release note "ML-Agents is now compatible with Python v3.7 and newer versions of Tensorflow up to 1.14"  , used Python3.7 and Tensorflow 1.14 to create a new Anaconda Env.

mlagents                      0.10.0                   pypi_0    pypi
mlagents-envs             0.10.0                   pypi_0    pypi
tensorboard                1.14.0                   pypi_0    pypi
tensorflow                   1.14.0                   pypi_0    pypi
python                         3.7.4                    h5263a28_0

3) Getting Error -> mlagents.envs.exception.UnityEnvironmentException: The API number is not compatible between Unity and python. Python API : API-10, Unity API : API-9.

Thanks
M ANILKUMAR

**Comment by surfnerd** [comment]
Hi @graybob,
It looks like you need to upgrade your UnitySDK folder in your unity project based on this line:
```
Getting Error -> mlagents.envs.exception.UnityEnvironmentException: The API number is not compatible between Unity and python. Python API : API-10, Unity API : API-9.
```

Please replace your UnitySDK folder with the one in the 0.10.0 release.  This should fix your issue.

**Comment by graybob** [comment]
Thanks a lot Chris for the solution , it works.
Closing issue.
