### ISSUE TITLE
Anyway to embed ml training to players?

### ISSUE THREAD

**Issue by kamicazer** [Unity-Technologies/ml-agents#2686]
I'd like to make a game where players can interact with agents and have the agents learn from the interactions.
Is there any way to achieve this?

**Comment by ervteng** [comment]
Hi @kamicazer, do you want to do training in a deployed game (e.g. on a phone)? If so, that isn't currently supported.

You can interact with the game during training on your local machine, however, just as you would any Unity game.

**Comment by kamicazer** [comment]
Hi @ervteng , more like a PC game. Would it be possible to somehow save the interations with players and send it to an online server, where the result would be processed by ml and the agent could be updated this way?

**Comment by ervteng** [comment]
We don't currently support this, though it should be possible using Soft Actor-Critic. You can save the agent's interactions using the demonstration recorder (Modify DemonstrationRecorder.cs and remove all mention of `Application.isEditor`, and your game build will record `.demo` files) - then, what you'd have to do is load these interactions into the training buffer during training. 

If you'd like to give it a go I can provide some pointers to where in the code you could do this. I started something similar on the `develop-humanil` branch but it's pretty out of date.

**Comment by kamicazer** [comment]
Thank you @ervteng, I will develop my game further and when I get to a point where I can implement that I will try your solution and contact you if necessary.
