### ISSUE TITLE
Training multiple agents with Training-Imitation

### ISSUE THREAD

**Issue by AdhamAlHarazi** [Unity-Technologies/ml-agents#2687]
I have multiple agents connected to a single brain that cooperate together. I want to bootstrap their training with a pretraining. However, the trainer_config file can only take one demonstration!. How can I use imitation-learning with multiple agents in an environment? If I create a brain for every agent the problem remains.

In summary, can the "trainer_config.yaml" accepts multiple demonstrations and map every demo to a specific agent?

**Comment by ervteng** [comment]
Hi @AdhamAlHarazi, if the agents share the same brain, then they learn the same thing regardless of how many agents are there (they behave the same way). So it doesn't make sense to map demonstrations to multiple agents with the same brain. You can put multiple demo files in a directory and pass a directory in your trainer_config.yaml if you want to use multiple recordings. 

you can give the agents different brains if you want them to learn different behaviors.

**Comment by AdhamAlHarazi** [comment]
Thank you @ervteng for replying. So, if I give agents different brains, how can I map each demonstration to a brain in the config file?

**Comment by ervteng** [comment]
You can put a different demo file under each brain name in the config file. The config file is organized by brain name (e.g. 3DBallLearning) and you can put two entries with different names and options.

**Comment by AdhamAlHarazi** [comment]
Thank you @ervteng
