### ISSUE TITLE
Visual and Vector observation

### ISSUE THREAD

**Issue by Kugelkopf** [Unity-Technologies/ml-agents#2692]
Hello everyone!

I would like to know if using vector observations (Ray perception) and visual observations together is possible this way.
I would like to have an agent in an academy where there are multiple obstacles having only one tag eg.: "obstacle"' and there is one "goal" object which is either not tagged or tagged as "obstacle" as well.  The agent has to find it and hit it. I would like to have 1 camera for the agent and use some filterings with EMGUCV so that the image input is mainly just the "goal" object. Im not quite sure how I should setup the environment.

Should I tag the "goal" object as obstacle or not tag it at all? Would the agent be able to solve the task even without filtering the camera image input? Should filtering (gray scale) improve the learning?

I would be glad for any advice!

**Comment by xiaomaogy** [comment]
Why don't you just use ray perception and give two tags to the "obstacle" and the "goal" object?

**Comment by Kugelkopf** [comment]
I have already done tagging and right now the environment works like with these 2 tags.  Though i would like to take a step further and make it more realistic, so that the rayperceptions work like lasers giving information only about the distance of objects. Therefore i put a camera on my agent but  so that it should find its goal object with the camera input.  The rayperceptions would only give distance information. Also I would use grayscaling to filter the input image. The goal object is quite unique from the obstacles regarding its color.
Im just not sure If its possible because this makes the task too complex for the PPO.
