### ISSUE TITLE
python & unity version problem

### ISSUE THREAD

**Issue by avatcc** [Unity-Technologies/ml-agents#2696]
Hi developers,
My teammate and I are trying to use Unity Collaborate for our RL project. I downloaded the newest Unity ml-agent plugin, which is version 10. However, my teammate uses ml-agent version 9 in her project. I tried to run her project on my computer using Unity Collaborate but failed. The project's example file and SDK are both the 9th version. What could we do to downgrade/upgrade the ml-agent file without messing up with the current project? (We tried to replace the SDK file but it doesn't work).
Please send help!

**Comment by DooblyNoobly** [comment]
If she is using windows just get her to create a new conda environment with the latest ml-agents installed. Or you can downgrade by removing ml-agents and installing an earlier version of ml-agents from pip: https://pypi.org/project/mlagents/#history

**Comment by avatcc** [comment]
Hi,
Thank you for your information. However, if I try to downgrade from 0.10.0 to 0.9.2, when I use git clone https://github.com/Unity-Technologies/ml-agents.git, I think it will automatically download ml-agents==0.10.0, what is the write git clone for version 0.9.2?

**Comment by avatcc** [comment]
@DooblyNoobly 
Or when I try to update the envs setting by doing 
`cd ml-agents-envs
pip install -e .`
It shows that: ERROR: mlagents 0.9.2 has requirement mlagents-envs==0.9.2, but you'll have mlagents-envs 0.10.0 which is incompatible.
I don't know how to change the envs into 0.9.2

**Comment by DooblyNoobly** [comment]
hmm not sure why you are trying to set up for development. Are you using windows? Just remove mlagents from your conda environment i.e. `pip uninstall package name` and install the mlagents version you want to replace it. `pip install mlagents==0.9.2` the only thing you need from the github repo (if you are not actively contributing to the development of mlagents) is the sdk and the config folder (if you are using the examples found in the sdk) you install mlagents itself from pip.  

So basic rule if you want to upgrade or downgrade your project:

- Remove sdk from your project
- Download the release you want from here
- Copy sdk over to your project
- Create a new conda environment and install the version of mlagents you need. Or use an existing conda environment and just pip uninstall the packages you want to replace and reinstall the version you need

**Comment by avatcc** [comment]
@DooblyNoobly 
Thank you! I finally got it working!
