### ISSUE TITLE
Can I give arguments for standalone build, with command line starting with "mlagents-learn ..."?

### ISSUE THREAD

**Issue by hanseoup** [Unity-Technologies/ml-agents#2697]
Hello :)
As I asked in title, I want to give argument for standalone build. 
To explain it easily, I instinctively though following command line.

command line> mlagents-learn config/trainer_config.yaml --run-id=argTest --train 
--env="C:\simpleBattleEnvironment\simpleBattle.exe 1"

the above one is that i want to give a argument "1" for standAlone build "simpleBattle.exe"
but it's , of course, not working. 

Is there any recommended way to solve my issue? 
Thank you :)

+) I will use it to load different scene at start. (if arg is "1" It could load learning Scene, or arg is "2" It could load validation Scene) so I also will appreciate to get another way that can load selected scene at start!

**Comment by chriselion** [comment]
If you pass `--env-args`, everything after that will be passed to the environment (https://github.com/Unity-Technologies/ml-agents/blob/a7c1fccd9a86045dece3206604fa93064aac58ea/docs/Training-ML-Agents.md#command-line-training-options)

So in your example,  `mlagents-learn config/trainer_config.yaml --run-id=argTest --train --env=C:\simpleBattleEnvironment\simpleBattle.exe --env-args 1` should do what you need.

**Comment by hanseoup** [comment]
OH!!! @chriselion Thanks a lot!!!
But I can't find "--env-args" option in ML Agent official documents... where I can find the
more detail option like "--env-args"?

**Comment by hanseoup** [comment]
And I use ml-agents version 0.9.3
Is it still possible to use `--env-args` option on my version?

**Comment by hanseoup** [comment]
Oh.. I checked `--env-args` option is newly updated after 0.10.0
Thank you. I will add a comment, if there any problem after version up!

**Comment by chriselion** [comment]
Oh sorry, I should have mentioned that it was added for the 0.10 release.

**Comment by hanseoup** [comment]
Thank you. I've checked that `--env-args` option worked well !

**Comment by AsadJeewa** [comment]
When I run the standalone executable with args it works perfectly.
![image](https://user-images.githubusercontent.com/27775903/80421331-97d93a80-88dc-11ea-9b3b-ab20103b6bef.png)
When I run it with the mlagents-learn command it does not work
mlagents-learn config/myconfig.yaml --env=env/CurriculumRoller --run-id=tresterch121323232s --inference --env-args=NOWALL

In my C# code
 if(args[1]=="NOWALL")//args[0] is name
        {
            walls.SetActive(false);
        }
it does not run this code with mlagents-learn -env-args

 Version information:
  ml-agents: 0.16.0.dev0,
  ml-agents-envs: 0.16.0.dev0,
  Communicator API: 0.16.0,
  TensorFlow: 2.0.1

**Comment by AsadJeewa** [comment]
It works now. It turns out that the NOWALL arg was not at index 1 so I just iterated through all args
