### ISSUE TITLE
Making video of agent behavior

### ISSUE THREAD

**Issue by kaiolae** [Unity-Technologies/ml-agents#2699]
Hi!

I have trained an agent using the gym-interface, and I would like to store a video of its behavior. Is there any way to do this in Python with the gym-interface, or would I have to use the Unity GUI?
The challenge I have with using the GUI is that the agents' behavior depend not only on a deep neural network, but also on a few other self-adapting parameters, which I am not sure I would be able to transfer to the GUI.

Another alternative could be to store deterministic descriptions of the environment and the agents' actions, and visualize these in the GUI. Is something like this available?

Thanks for the assisstance!

**Comment by xiaomaogy** [comment]
Hi @kaiolae, we have video recorder (here)[https://github.com/Unity-Technologies/video-recorder]which is pretty easy to use. You can't use it in python with the gym interface though. 

For experience reply, I think you will have to store everything yourself and replay it in a customized way. We don't offer any solution right now.

**Comment by kaiolae** [comment]
Thanks for the answer! I think I will go for just recording what the agent sees in this case, which will not be too tricky. However, I would be very interested in a Python video recorder if that is something you are considering to add in the future :)

Tanks again!
