### ISSUE TITLE
We don't need TensorFlowSharp anymore right?

### ISSUE THREAD

**Issue by yjcnbnbnb200** [Unity-Technologies/ml-agents#2714]
I just follow the instruction of latest version of ML, I found I don't need to install TensorFlowSharp, I just need to run a python shell and generate a NN model, load the model back into Unity and run it, that's all, so my understand is, we don't need to install TensorFlowSharp anymore like before, right?

**Comment by xiaomaogy** [comment]
@yjcnbnbnb200 We've deprecated the usage of TensorFlowSharp, and now we are using Barracuda, which is already included in the repo.

**Comment by jorezy** [comment]
@xiaomaogy Why did you guys give up TensorflowSharp? A substitute called Tensorflow.NET might be your choice too.
