### ISSUE TITLE
Training not starting (I'm probably overlooking something simple)

### ISSUE THREAD

**Issue by devedse** [Unity-Technologies/ml-agents#2715]
**Describe the bug**
I installed ml-agents in my Anaconda environment on Windows. I tried doing this directly from github and using pip. The issue I'm running into happens for both.

**To Reproduce**
1. Open samples from ML-Agents in Unity 2019.1.14f
2. Open the 3D ball sample scene
3. I removed the NN model from the learningbrain
4. Started CMD
5. activate mlagents (conda environment)
6. I ran command `mlagents-learn config/trainer_config.yaml --run-id=ball_1 --train`
7. It asks me to press the play button
8. Unity simply starts without a model loaded, so the balls start rolling of the heads

Unity seems to never connect to the training mlagents command prompt.

![image](https://user-images.githubusercontent.com/2350015/66579730-8f5a2600-eb7d-11e9-8d45-ea613ef85f87.png)

The command prompt itselfs waits for a few more seconds and then throws this error:

```
INFO:mlagents.trainers:CommandLineOptions(debug=False, num_runs=1, seed=-1, env_path=None, run_id='ball_1', load_model=False, train_model=True, save_freq=50000, keep_checkpoints=5, base_port=5005, num_envs=1, curriculum_folder=None, lesson=0, slow=False, no_graphics=False, multi_gpu=False, trainer_config_path='config/trainer_config.yaml', sampler_file_path=None, docker_target_name=None, env_args=None)
INFO:mlagents.envs:Start training by pressing the Play button in the Unity Editor.
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\davy.davidse\.conda\envs\mlagents\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\davy.davidse\.conda\envs\mlagents\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "c:\xgitml\ml-agents\ml-agents-envs\mlagents\envs\subprocess_env_manager.py", line 82, in worker
    env = env_factory(worker_id)
  File "c:\xgitml\ml-agents\ml-agents\mlagents\trainers\learn.py", line 368, in create_unity_environment
    args=env_args,
  File "c:\xgitml\ml-agents\ml-agents-envs\mlagents\envs\environment.py", line 103, in __init__
    aca_params = self.send_academy_parameters(rl_init_parameters_in)
  File "c:\xgitml\ml-agents\ml-agents-envs\mlagents\envs\environment.py", line 671, in send_academy_parameters
    return self.communicator.initialize(inputs).rl_initialization_output
  File "c:\xgitml\ml-agents\ml-agents-envs\mlagents\envs\rpc_communicator.py", line 86, in initialize
    "The Unity environment took too long to respond. Make sure that :\n"
mlagents.envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
         The environment does not need user interaction to launch
         The Academy's Broadcast Hub is configured correctly
         The Agents are linked to the appropriate Brains
         The environment and the Python interface have compatible versions.
Traceback (most recent call last):
  File "C:\Users\davy.davidse\.conda\envs\mlagents\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] The pipe has been ended

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\xgitml\ml-agents\ml-agents-envs\mlagents\envs\subprocess_env_manager.py", line 59, in recv
    response: EnvironmentResponse = self.conn.recv()
  File "C:\Users\davy.davidse\.conda\envs\mlagents\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Users\davy.davidse\.conda\envs\mlagents\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\davy.davidse\.conda\envs\mlagents\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "c:\xgitml\ml-agents\ml-agents\mlagents\trainers\learn.py", line 417, in main
    run_training(0, run_seed, options, Queue())
  File "c:\xgitml\ml-agents\ml-agents\mlagents\trainers\learn.py", line 219, in run_training
    options.sampler_file_path, env.reset_parameters, run_seed
  File "c:\xgitml\ml-agents\ml-agents-envs\mlagents\envs\subprocess_env_manager.py", line 225, in reset_parameters          return self.env_workers[0].recv().payload
  File "c:\xgitml\ml-agents\ml-agents-envs\mlagents\envs\subprocess_env_manager.py", line 62, in recv
    raise UnityCommunicationException("UnityEnvironment worker: recv failed.")
mlagents.envs.exception.UnityCommunicationException: UnityEnvironment worker: recv failed.

(mlagents) C:\XGitML\ml-agents>
```

**Environment (please complete the following information):**
- OS + version: Windows 10
- _ML-Agents version_: Latest develop from source
- _Environment_: Unity 2019.1.14f -> 3DBalls

**Comment by devedse** [comment]
I found the issue, I simply had to check the "Control" checkbox in the Academy. Is this something we'd want to add to the documentation?

**Comment by xiaomaogy** [comment]
Hi @devedse, I believe this is already included in the documentation. For example https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Basic-Guide.md#setting-up-the-environment-for-training

**Comment by devedse** [comment]
@xiaomaogy , I think I used this guide which doesn't seem to include it:
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Getting-Started-with-Balance-Ball.md

**Comment by mikeruddy** [comment]
I'm getting the exact same issue but I'm not seeing the "control" checkbox @xiaomaogy 

Is training from docker supported? Why was the docker getting started guide removed? Thanks

**Comment by devedse** [comment]
@mikeruddy The control checkbox was removed as of version 0.11.0 of the ml-agents framework. If you now configure the rest correctly it should be as simple as running your train command from the command line and then pressing the play button.

**Comment by xiaomaogy** [comment]
@devedse Thanks for answering that for me.

**Comment by xiaomaogy** [comment]
@mikeruddy Also we "removed" the docker doc page because we wish to have one guide (The venv guide) for all of the platforms (Mac, Windows and Linux). It seems that some people are saying the venv guide doesn't work quite well for them https://github.com/Unity-Technologies/ml-agents/issues/2854 on the conda side, so we are planning to bring the conda page back.  If you feels that you also have some need for the docker page, please open another issue on it, then our team will discuss accordingly.

**Comment by mikeruddy** [comment]
@xiaomaogy (and Devedse) I appreciate the response. I think I may have things configured properly but that the docker image included isn't working properly. It doesn't seem to connect to my linux host with Unity Editor and errors out when running the headless linux build. (Yes I opened up the ports). 

@xiaomaogy there's currently references to docker sprinkled throughout your docs which makes things very confusing. The readme says `Simplified set-up with Docker`. The installation doc says `If you would like to use our Docker set-up (introduced later)`. There's a dockerfile in the root of the repo. You would think Docker is supported. If anything the maintainers should remove the references until it is supported. 

I'd open a ticket but I'm really just evaluating this for now. But it's a real head scratcher why docker isn't the default platform. I'd much rather run `docker build .` than muck around with python environments. Whoevers calling the shots at Unity, if you'd rather spend less time on support, and more time making progress - then docker should be the default. Build a GUI around it and pretend docker never existed. Cheers

**Comment by xiaomaogy** [comment]
Hi @mikeruddy I have the same feeling as you do. If you could open up a new issue on that with the title like "Why was the docker doc being removed", and see if the community have the same feeling as you do, that would help a lot for us to gauge the interest in that kind of doc (and potentially bring it back). 

Also I agree with you that in the installation doc we should not have a reference to a removed doc. If you could mention that also in the issue, that would be really helpful. 

Regarding your docker error, I would recommend opening up a separate issue, and give details there.
