### ISSUE TITLE
Running sample from GIT show 2 errors.

### ISSUE THREAD

**Issue by devedse** [Unity-Technologies/ml-agents#2720]
**Describe the bug**
I just started a fresh project on Windows 10 with Unity 2019.1.14f1. When I run one of the samples the following 2 errors pop up:

![image](https://user-images.githubusercontent.com/2350015/66647228-a144d300-ec28-11e9-91a1-a58d3d02a975.png)

**Error 1: No model loaded:**

```
No model was present for the Brain 3DBallLearning.
UnityEngine.Debug:LogError(Object)
MLAgents.LearningBrain:DecideAction() (at Assets/ML-Agents/Scripts/LearningBrain.cs:143)
MLAgents.Brain:BrainDecideAction() (at Assets/ML-Agents/Scripts/Brain.cs:98)
MLAgents.Academy:EnvironmentStep() (at Assets/ML-Agents/Scripts/Academy.cs:558)
MLAgents.Academy:FixedUpdate() (at Assets/ML-Agents/Scripts/Academy.cs:583)
```

![image](https://user-images.githubusercontent.com/2350015/66647581-92125500-ec29-11e9-958f-eafabd4fb951.png)

Can be simply fixed by modifying the brain to load the .nn file. I think this should be committed to the repository.

**Error 2: An item with the same key has already been added. Key: Agent (Ball3DAgent)**

```
ArgumentException: An item with the same key has already been added. Key: Agent (Ball3DAgent)
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <7d97106330684add86d080ecf65bfe69>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <7d97106330684add86d080ecf65bfe69>:0)
MLAgents.Brain.SendState (MLAgents.Agent agent, MLAgents.AgentInfo info) (at Assets/ML-Agents/Scripts/Brain.cs:56)
MLAgents.Agent.SendInfoToBrain () (at Assets/ML-Agents/Scripts/Agent.cs:653)
MLAgents.Agent.SendInfo () (at Assets/ML-Agents/Scripts/Agent.cs:1039)
MLAgents.Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:556)
MLAgents.Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:583)
```

This issue can be fixed by changing the SendState method in the Brain.cs file from:
```
        public void SendState(Agent agent, AgentInfo info)
        {
            LazyInitialize();
            m_AgentInfos.Add(agent, info);
        }
```

to
```
        public void SendState(Agent agent, AgentInfo info)
        {
            LazyInitialize();
            m_AgentInfos[agent] = info;
        }
```

I'm not sure if this is the desired solution though? (Reason being is that I'm not able to start training, see: https://github.com/Unity-Technologies/ml-agents/issues/2715)

**Environment (please complete the following information):**
- OS + version: Windows 10
- _ML-Agents version_: Latest from github
- _Environment_: Ball3D sample running in Unity 2019.1.14f1

**Comment by chriselion** [comment]
Hi @devedse,
Thanks for the bug report. We're currently investigating the missing models on import (originally reported in https://github.com/Unity-Technologies/ml-agents/issues/2633) - this only appears to affect Unity versions 2019.x.

For the SendState fix, great minds think alike - I already made the change in https://github.com/Unity-Technologies/ml-agents/pull/2629 a few weeks ago 😄  Unfortunately it was too late for the 0.10.0 release.

**Comment by devedse** [comment]
@chriselion , cool  thanks :). Keep me posted

**Comment by chriselion** [comment]
@devedse Unfortunately, we never found the root cause of this. We have since increased the min version to 2018.x and updated the assets accordingly, and they no longer exhibit this problem.
