### ISSUE TITLE
Help wanted: Parallel training for different scenarios

### ISSUE THREAD

**Issue by sunirisgrace** [Unity-Technologies/ml-agents#2725]
Hi, I have some questions about parrel training in different scenarios:

I wonder whether there is one brain or there are multiple brains after parrel training is finished.
Whether there is one policy or there are multiple policies during the process of parrel training.
How to implement parrel training in different scenarios. If I have two scenarios, should I write one line of command for training or I need to write two commands for training. such as: mlagents-learn < trainer- config-file > --num-envs=<2> --env = < env_name1 > --run-id = --env = < env_name2 > --run-id = --train.
During the process of the training for one scenario, we can see the value of the reward. How to differentiate the rewards for two scenarios if I train two scenarios concurrently.

**Comment by xiaomaogy** [comment]
Hi @sunirisgrace, you can set one brain or multiple brain in a certain scene, and that will correspond to one or multiple policies. This is not relevant to whether you are using parallel training. 

When we use the parallel environment feature, the only purpose here is to collect more samples from the simulation, and we will only allow one kind env and launch multiple of them to speed up the collection speed. Two scenarios are not allowed.

**Comment by sunirisgrace** [comment]
@xiaomaogy On your official blog website, it mentioned that "Today, we are introducing the ability to train faster by having multiple concurrent instances of Unity on a multi-core machine". and " The changes we provide in v0.8 enable a training speedup of 5.5x on easy levels and up to 7.5x on harder levels by leveraging **16 Unity simulations**. Generally speaking, the gains of utilizing multiple Unity simulations are greater for more complex levels and games." Does it mean that ML agents train 16 simulations in one scenario concurrently and finally get one policy to make agent be able to solve many levels?

**Comment by xiaomaogy** [comment]
Yes, your understanding is correct, we have 16 simulations of the exact same scenes with one policy being updated by the samples generated from these simulations.
