### ISSUE TITLE
Help wanted: RayPerception 3d - only one raycast returns value

### ISSUE THREAD

**Issue by skwosh1** [Unity-Technologies/ml-agents#2727]
I have a problem with RayPerception3d.

Only one of the 8 raycast lines detects a collision with objects. Have you already encountered such a problem?

<img width="1207" alt="Screen Shot 2019-10-13 at 10 46 42" src="https://user-images.githubusercontent.com/51817399/66713866-7b920800-eda7-11e9-909f-4d77cae9affa.png">

Only one raycast works:
<img width="1129" alt="Screen Shot 2019-10-13 at 10 44 58" src="https://user-images.githubusercontent.com/51817399/66713868-8187e900-eda7-11e9-889b-4470dc6b8b55.png">

Rest of them return signal informing the ray missed everything:
<img width="1128" alt="Screen Shot 2019-10-13 at 10 45 40" src="https://user-images.githubusercontent.com/51817399/66713873-8f3d6e80-eda7-11e9-9cae-d1f94b3c89be.png">

**Comment by hanseoup** [comment]
As you can see "rayobs.Count" value is 56.
But you just see the value rayobs[0]~rayobs[7]. 
It maybe only contain ray detail info that attached with "0"angle. (rayobs[0]~rayobs[6]) 

One ray info made up with size of ( size of detectable objects + 2 ).
For example, if you detect "firstRed" at 6.0f depart from agent center.(with "angle 0f" attached ray) 
rayobs[0] : 0 (wall)
rayobs[1] : 0 (agent)
rayobs[2] : 1 (firstRed)
rayobs[3] : 0 (secondRed)
rayobs[4] : 0 (human)
rayobs[5] : 0 (it turns on 1, when ray detect nothing.) 
rayobs[6] : 0.5 ( 6.0f / 12.0f) 

So if you want see "angle 90f" attached ray, you have to see the value of
rayobs[14]~ rayobs[20].

**Comment by skwosh1** [comment]
Thank you very much for your answer. I now understand how RayPerception3d works. A super helpful explanation. Thanks Hanseoup!
