### ISSUE TITLE
ML agents as a Package with asmdef ?

### ISSUE THREAD

**Issue by marwie** [Unity-Technologies/ml-agents#2728]
**Is your feature request related to a problem? Please describe.**
Hello, I'm building a UI Frontend for configuring my training and also for starting, stopping training and copying trained brains to my Project. 
The frontend is built as a package to be easily shared between projects. In some cases it would be nice to reference ML-Agents classes/objects but I'm using amsdefs so I can not reference them. 

**Describe the solution you'd like**
ML-Agents being a package with asmdefs

**Describe alternatives you've considered**
ML-Agents just using asmdefs

**Comment by marwie** [comment]
![image](https://user-images.githubusercontent.com/5083203/66785894-d8440e80-eede-11e9-85ec-c2758c7f9d3d.png)

**Comment by cakeslice** [comment]
> I would like to second this request. It would be even better if ML-Agents was available as a package through Unity's new package manager.

Yes please!!!

**Comment by DanJBower** [comment]
> I would like to second this request. It would be even better if ML-Agents was available as a package through Unity's new package manager.

Looking at the roadmap, I think this may be the plan??

But if you can't wait for that, with the new refactoring of the project, in Unity 2020.1.a21+, and Unity 2019.3.4f1+ (not released yet :/) you will be able to add the package from this git repo using the sub-directory in the repo. See [this forum post](https://forum.unity.com/threads/some-feedback-on-package-manager-git-support.743345/) for more info :)

**Comment by DanJBower** [comment]
Coming back to this, Unity 2019.3.6f1 is out. I added the line below to my `manifest.json` and it seems to work :)

    "com.unity.ml-agents": "https://github.com/Unity-Technologies/ml-agents.git?path=/com.unity.ml-agents#7507a5d3f5515ae7877eb3a3e9abaa2e2a270930",

**Comment by chriselion** [comment]
Sorry for the late followup on this. ML-Agents is available as a preview package currently, and will be a verified package in 2020.2.
