### ISSUE TITLE
Train command not working in anaconda command prompt

### ISSUE THREAD

**Issue by albertodcm** [Unity-Technologies/ml-agents#2737]
Hello, I am new to this and I am following a tutorial on how to use ml-agents, but when I hist the part where I want to start training my agent, I enter into the anaconda prompt: 

mlagents-learn config/trainer_config.yaml --curriculum=config/curricula/penguin/ --run-id=penguin_01 --train

And I get the unity logo and then this messages: 
FileNotFoundError: [Errno 2] No such file or directory: 'config/trainer_config.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\alber\anaconda3\envs\ml-agents\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\alber\anaconda3\envs\ml-agents\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\alber\Anaconda3\envs\ml-agents\Scripts\mlagents-learn.exe\__main__.py", line 9, in <module>
  File "c:\users\alber\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 417, in main
    run_training(0, run_seed, options, Queue())
  File "c:\users\alber\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 205, in run_training
    trainer_config = load_config(trainer_config_path)
  File "c:\users\alber\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\trainer_util.py", line 120, in load_config
    f"Config file could not be found at {config_path}."
mlagents.envs.exception.UnityEnvironmentException: Config file could not be found at config/trainer_config.yaml.

Thank you for your time.

**Comment by chriselion** [comment]
Hi @albertodcm,
What directory are you running the command from? The examples generally assume that you're in the root directory of the ml-agents repo, in which case this file https://github.com/Unity-Technologies/ml-agents/blob/master/config/trainer_config.yaml would be at `config/trainer_config.yaml` . If you're running from a different directory, you'll have to point it to a different path, or copy the file near where you're running from.

**Comment by albertodcm** [comment]
directory in the command is: (ml-agents) C:\Users\alber\ml-agents>

Which the folder config is inside ml-agents folder

**Comment by chriselion** [comment]
Hi,
Not sure how else to debug this. mlagents-learn just takes the argument and passes it to `open()`, but it's possible that anaconda is doing something weird with the working directory. Can you try passing the absolute path, like "C:\users\alber\anaconda3\envs\ml-agents\config\ trainer_config.yaml" instead?

**Comment by albertodcm** [comment]
Tried but it also didnt work :( I am not sure if it has to do with something wrong with the installation?

**Comment by chriselion** [comment]
It's possible that the permissions are incorrect on the file, although I would expect a different exception in that case. Can you make sure the config directory and the yaml file are readable? More details [here](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc754344(v=ws.11)?redirectedfrom=MSDN)

If that doesn't work, you could start doing things like editing learn.py to print out `os.getcwd()` (https://docs.python.org/2/library/os.html#os.getcwd) to make sure you're actually running in the directory that you think you are...

**Comment by marcosecchi** [comment]
Hello @chriselion I'm getting the same error as @albertodcm. I checked the _trainer_config.yaml_ file and it's not read only (but the config folder is, although I can't change the property with the _attrib_ command)

**Comment by marcosecchi** [comment]
I just tested it on macOs and I get the same issue I have on Windows.
