### ISSUE TITLE
how do you train 2 diffrent brain at the same time?

### ISSUE THREAD

**Issue by orenong** [Unity-Technologies/ml-agents#2739]
Hi, I LOVE ml-agents so far!!! I saw few projects with 2 brains that are competing against each other? but how do I do it? how do I train 2 diffrent brains at the same time?

**Comment by chriselion** [comment]
Hi,
The tennis example that we have is actually cooperative - the "players" get rewards for keeping the ball in the air as long as possible. The soccer example might be a better example, but in this case both the goalies (on different teams) share a brain, and do the strikers.

We're planning on expanding support for team and competitive play soon, but there's nothing officially available right now. But you can try out the "ghost trainer" here https://github.com/Unity-Technologies/ml-agents/pull/1975 which some other people have gotten to work with their games.

Hope that helps...
