### ISSUE TITLE
errors after prompt "Start training by pressing the play button in the unity editor" 

### ISSUE THREAD

**Issue by SavedTheWorld77** [Unity-Technologies/ml-agents#2743]
whenever I start pressing the play button, it doesn't take too long for the errors to show up. I followed every step on the Basic_Guide.md
![image](https://user-images.githubusercontent.com/46953162/66958405-b0010f00-f09a-11e9-9d3a-f41f8f9b29dc.png)

**Comment by SavedTheWorld77** [comment]
I'm so sorry for even creating this issue. I just forgot to check the control beside the brain. I'm really sorry. It's working fine now.

**Comment by chriselion** [comment]
No worries, glad you got it figured out. For what it's worth, this should get simpler in the next release.
