### ISSUE TITLE
Migrate from v0.8 to v0.10 : How to set num_env steps equivalent?

### ISSUE THREAD

**Issue by LibraryAI** [Unity-Technologies/ml-agents#2746]
Hi I was training agent in multi-environment setting in v0.8.
When moving to v0.10, the migrating documentation notices

> The steps in the command line console corresponds to a single step of a single environment. Previously, each step corresponded to one step for all environments (i.e., num_envs steps).

The question is how to set equivalent step in two versions. 
v0.8 : max_steps = 1.0e6, num_envs = 128, save_freq = 100000
v0.10 : max_steps = 1.2e8, num_envs = 128, save_freq = 10000000

are these two equivalent training setting?

**Comment by chriselion** [comment]
Hi @LibraryAI,
Yes, those should be roughly equivalent.

**Comment by LibraryAI** [comment]
Hi, @chriselion 
Thanks for the comment. Is there any reason v0.10 multi environment should be slow?
Looking at the[ trainer_controller.py](https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents/mlagents/trainers/trainer_controller.py) line 202, I thought synchronous update in v0.8 changed to asynchronous, and multi environment speed should be faster.

However, toy training on v0.10 took 
11723 sec total
128 env
1.0e6 max steps

Previous training on v0.8 took
6914 sec total
128 env
1.0e4 max steps.

I just want to be sure if my testing codes were wrong or is jt correct that it should be slower.
