### ISSUE TITLE
Flag to force training with CPU

### ISSUE THREAD

**Issue by caioc2** [Unity-Technologies/ml-agents#2751]
Hi,

When using visual observations and big batch size GPU's make a lot of sense and improve the training speed considerably, in the other hand, when using vector observations with small batch size (ie 32 and alike) using GPU can make it a lot slower than CPU. 

Currently, as far as I know, you cant select which device (CPU/GPU) you want to use for training, either you have to install the tensorflow with/out GPU, disable your GPU to use CPU only or create multiple environments each one with the desired configuration.

It could be made easier by adding for example a flag "--cpu" to the ml-agents for using CPU only.

So far I've been using my hackish solution on the "learn.py" file like the following:

`parser.add_argument(
        "--cpu",
        default=False,
        action="store_true",
        help="Run with CPU only",
    )
`

`if options.cpu:
        os.environ['CUDA_VISIBLE_DEVICES'] = '-1'`

It get the job done without needing seriously changes to code, if it can be useful for other people I would like to see something like this in the ml-agents.

Thanks.

**Comment by chriselion** [comment]
Hi @caioc2,
Thanks for the feedback. I'll log it as a feature request, but if you want to submit a pull request with the change, I can try to get it merged in.

As a side note, does running with `CUDA_VISIBLE_DEVICES=-1 mlagents-learn ...` work too?

**Comment by caioc2** [comment]
I could not run with `CUDA_VISIBLE_DEVICES=-1 mlagents-learn` but probably one can set in another way, the only drawback is this variable may not be known by many people (I didn't know about it until now), while the flag is easier and would be in the documentation about training.

Anyway, I made the pull request.
