### ISSUE TITLE
Inference Engine not working properly or model not correctly saved

### ISSUE THREAD

**Issue by InsaneMonster** [Unity-Technologies/ml-agents#2758]
Hi everyone!

I'm opening this as a question/discussion since I don't know if I'm doing something wrong of if it's a bug.

I was training RollerBall environment. I made some changes to the setting and let's say that now the mean reward for the optimal solution would be around 100.0f. I trained the whole system for 500000 steps and this is the screenshot of the end of training:

![immagine](https://user-images.githubusercontent.com/51710669/67128763-f66e7f00-f1fc-11e9-9c5d-9cad9a8506dd.png)

A good enough result for what I was seeking, around 85.0f. I then took the .nn model and put it in the brain of my learning agent. I unchecked control and pressed play button. I noticed the agent played badly, not random but almost. I then tried to run from python removing the --train flag. And I got the following results:

![immagine](https://user-images.githubusercontent.com/51710669/67128970-8f9d9580-f1fd-11e9-998c-195dfda2b46c.png)

As you can see now the mean reward was around 0.0f, just like at the beginning of training. How can that be? It seems the model has not been saved. 

What am I doing wrong? I really need an answer since I got this working with TensorflowSharp but not with the new Unity Inference Engine...

Thanks in advance!

**Comment by InsaneMonster** [comment]
Update: I've retrained the same exact environment using tensorflow 1.14.0 instead of 1.15.0 (which is the one ml-agents installs automatically). This results in much less warnings and in the model to work correctly in inference mode. Also, I stopped training early to test this out, so it could be related to that. I will do further test during the week to confirm what this is about (if there is no official response from the devs).

Cheers!

**Comment by chriselion** [comment]
What version of tensorflow were you using initially? I see a message about `AddV2` in the logs; so far I've only seen that with tensorflow 2.0, but it's possible that 1.15 produces it too.

Anyway, the fix is here https://github.com/Unity-Technologies/ml-agents/pull/2703

**Comment by InsaneMonster** [comment]
Thanks! Yes, I can confirm Tensorflow 1.14 works fine. I had installed 1.15 but just because that is the dependency your pip package installs automatically (in setup.py you have something like <2, >1.7). 

Good to know it is now fixed!
