### ISSUE TITLE
Can I use AddVectorObs in Coroutine?

### ISSUE THREAD

**Issue by Hongsungchan** [Unity-Technologies/ml-agents#2759]
Hello I'm Goint to use ML_Agent for my Personal MOBA(Like LOL, DOTA)game

I'm going to use AddVectorObs using Coroutine.

Can I use AddVectorObs in Coroutine(0.25second)?

I have 117 Vector Observations.

Not all 117 work in Coroutine(maybe 95?)

Oh and

Can I use AddVectorObs as a for statement in Void Start?

Used to get the position value of an object (the position value never changes).

private void Start()
{
        for (int i = 0; i <= 4; i++)
        {
            blueBuilding[i] = OM.BlueObject[i].gameObject;
            purpleBuilding[i] = OM.PurpleObject[i].gameObject;
      
            AddVectorObs(Mathf.Round(blueBuilding[i].transform.position.x * 10) * 0.1f);
            AddVectorObs(Mathf.Round(blueBuilding[i].transform.position.z * 10) * 0.1f);

            AddVectorObs(Mathf.Round(purpleBuilding[i].transform.position.x * 10) * 0.1f);
            AddVectorObs(Mathf.Round(purpleBuilding[i].transform.position.z * 10) * 0.1f);
            
        }
}

**Comment by chriselion** [comment]
Hi @Hongsungchan,
This isn't supported right now. The list of observations is cleared right before Agent.CollectObservations() is called:
https://github.com/Unity-Technologies/ml-agents/blob/9314f243493ef65709b738bca51ff26634edc37f/UnitySDK/Assets/ML-Agents/Scripts/Agent.cs#L562-L567

One option would be to accumulate the observations in another list inside the coroutines, and then use `AddVectorObs(IEnumerable<float> observation)` inside Agent.CollectObservations()
