### ISSUE TITLE
This errors show up whenever I drag the gizmos and ml-agents folders to my project assets

### ISSUE THREAD

**Issue by SavedTheWorld77** [Unity-Technologies/ml-agents#2761]
![image](https://user-images.githubusercontent.com/46953162/67158352-a3fea100-f369-11e9-9385-454f828aa4ac.png)

This is my first time learning machine learning. Is there any other way to import?

**Comment by chriselion** [comment]
Closing this as a duplicate of https://github.com/Unity-Technologies/ml-agents/issues/2766
