### ISSUE TITLE
Doubt about cumulate the rewards

### ISSUE THREAD

**Issue by franvf** [Unity-Technologies/ml-agents#2762]
Hi everyone, I work a little with mlagents for make a game where an agent touch one cube, if touch the correct cube done() and reward +1, but if touch the incorrect cube (there is mor than one cube) I call AgentReset() and reward -1. 

Well, the problem it's that my agent "dont learn" he touch the incorrect cube 9/10 times, but when touch the correct cube the final reward is positive, I guess that AgentReset() not only reset the scenario of game, but also reset the rewards, and when touch the bad cube 9 times don't acumulate in the total of reward. 

How can I acumulate this total rewards?

THX!

**Comment by chriselion** [comment]
Hi,
This is pretty similar to the setup in the Basic scene (with slightly different reward values):
https://github.com/Unity-Technologies/ml-agents/blob/a6e8a64fd80ccd7a8040252695ff6575a88eb8bb/UnitySDK/Assets/ML-Agents/Examples/Basic/Scripts/BasicAgent.cs#L50-L62
So you might want to check that you're doing the same thing there.

You might also want to check the tensorboard results https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-Tensorboard.md to track that the reward gradually increases over time.
