### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by smkplus** [Unity-Technologies/ml-agents#2763]
I don't know why I have Traceback (most recent call last) error

![image](https://user-images.githubusercontent.com/16706911/67163320-5b031880-f37a-11e9-8fad-51242b056f6f.png)

tensorflow 1.4

![image](https://user-images.githubusercontent.com/16706911/67163687-d666c900-f37e-11e9-8bdb-b875285548fc.png)

**Comment by chriselion** [comment]
Next time, please copy the logs and paste them (using ```) instead of taking screenshots. This makes them easier for us to read, and makes it easier for other people to find related issues in the future.

For the warnings regarding `cudart`, this is something to do with your tensorflow setup and not coming from ml-agents. We don't provide support for this here.

The `KeyError: "default"`is because we expect a "default" section in the config yaml (for example https://github.com/Unity-Technologies/ml-agents/blob/9314f243493ef65709b738bca51ff26634edc37f/config/trainer_config.yaml#L1-L3). You can fix this error by adding that in. I'll log a feature request on our side to make this error clearer.

For the last set of errors, it's hard to tell what's going on because some of the text is cut off. One possibility is that you start the trainer but didn't start training from the Unity editor within the timeout of 30 seconds.
