### ISSUE TITLE
How can I import ml-agents to existing projects? Every time I do import it, it shows errors. 

### ISSUE THREAD

**Issue by SavedTheWorld77** [Unity-Technologies/ml-agents#2766]

**Comment by chriselion** [comment]
What are the errors?

**Comment by SavedTheWorld77** [comment]
![image](https://user-images.githubusercontent.com/46953162/67179963-a8c76180-f40a-11e9-8d9b-75414cde7e1b.png)

I've managed to remove the pre-compiled assembly errors by removing the ads in the package manager. But the 'google.protobuf' persists.

**Comment by SavedTheWorld77** [comment]
I managed to find the problem. It appears I do have two google.protobuf both in ml-agents and ARCore SDK plugin. Now I don't know if I should remove it or not.

**Comment by chriselion** [comment]
OK, can you try removing one of them?
