### ISSUE TITLE
How do I build to android? Pre-trained models works fine in unity editor but every time I build it into android the models doesn't show the training. 

### ISSUE THREAD

**Issue by SavedTheWorld77** [Unity-Technologies/ml-agents#2768]

**Comment by chriselion** [comment]
Hi,
What version of tensorflow are you training with? We've seen some problems with tensorflow==1.15 generating graphs that tensorflow2barracuda doesn't know how to process; this might explain what you're seeing.

Can you please try installing 1.14 instead? We hope to have a better fix soon, but that's the best solution for now.

**Comment by SavedTheWorld77** [comment]
Thanks, I'm gonna install it now.

**Comment by SavedTheWorld77** [comment]
It seems that the tensorflow I installed is already at 1.14. I'm trying to make the 3dball in ARCore. It really doesn't show the training like it did in the unity editor.

**Comment by chriselion** [comment]
Sorry that changing tensorflow didn't fix it.

Can you please explain what you mean by "doesn't show the training"? Do you mean that the python trainer doesn't connect? If so, that's expected; we don't support training on mobile devices currently.

**Comment by SavedTheWorld77** [comment]
sorry if I can't explain my self well, What I meant was I was using a pre-trained .nn file. The pre-trained file works fine in the unity editor but everytime I try to build it to android the pre-trained file doesn't seem to work.

**Comment by SavedTheWorld77** [comment]
I';m devoloping an ARCore project.

**Comment by surfnerd** [comment]
Do you see any errors in the android logs? Any information you can give us will help us diagnose the problem.

**Comment by surfnerd** [comment]
@mantasp are there any know limitations for `.nn` files on Android?

**Comment by mantasp** [comment]
@SavedTheWorld77 are your running the agent brain on CPU or GPU?

**Comment by SavedTheWorld77** [comment]
Sorry for not responding to your questions faster, @surfnerd I will post my android logs later, @mantasp Sorry, I don't know the answer to that. I don't know where I can find the CPU or GPU option. can you point me where?

**Comment by SavedTheWorld77** [comment]
@mantasp I'm using CPU on my learningbrain if that was what you were looking for.

**Comment by mantasp** [comment]
@SavedTheWorld77 could you please share simple project setup that shows the issue?
Thanks!
