### ISSUE TITLE
Help wanted: Can one policy be saved and updated for the next training？

### ISSUE THREAD

**Issue by zhaijinfeng** [Unity-Technologies/ml-agents#2774]
Hello! I have some questions to ask for help:
1. If I get a policy from the training of a simple scenario, can I save this policy and update and optimize it in the new training of a complex scenario to make it adapt to complex scenarios?
2. For one Academy, I find there are several areas for one scene during the training, can the scenario for each area be different?

**Comment by AcelisWeaven** [comment]
Hi @zhaijinfeng ,

I haven't used them much, but I think you can achieve your first goal using [curriculum learning](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-Curriculum-Learning.md). Basically, you split your training in multiple "levels" of increasing difficulties (or even, totally different task that gradually reach your goal) and you define a condition to get from one level to another. (eg. if my averaged reward over my last 100 episodes is more than 5, go to the next level. You can see which lesson (level) is being player in Tensorboard.

For your second point, yes you could but you'd be best using [generalized training](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-Generalized-Reinforcement-Learning-Agents.md). It should play really well with curriculum learning (it also seems to use academy parameters, like the size of a ball, gravity force, ...).

Good luck!
