### ISSUE TITLE
Is raycast the best way to observe?

### ISSUE THREAD

**Issue by Hongsungchan** [Unity-Technologies/ml-agents#2780]
I immediately delivered the coordinates and distances to the agent.

But it's so dumb.

I'm guessing why, is it because of too much observation information?(120 addvectorobs)

**Comment by surfnerd** [comment]
Hi @Hongsungchan,
I'm not sure I understand your question.  RayCasts are one way to observe, and depending on how you use them, easier to get them to train in some cases.  

Can you elaborate on what you are trying to achieve and what specific problems you are having?
