### ISSUE TITLE
Model works poorly after training

### ISSUE THREAD

**Issue by itsyaboyleroy** [Unity-Technologies/ml-agents#2790]
I have followed the Making a New Learning Environment tutorial and I have been able to train models while observing them in tensorboard. During the training, the model looks great. High cumulative rewards and is performing well from what I can see in the editor. But, when I import the model, put it into the brain and turn off the control in the academy, it begins to act randomly and most of the time just walks off the platform. 

Does anyone have ideas about why a model would work really well in training, but immediately start to work poorly when put into use?

Thanks for the help.

**Comment by itsyaboyleroy** [comment]
I just noticed that in the console when I begin training, there are a lot of messages about deprecated tensorflow commands. I'm going to verify I have the correct version of tensorflow.

**Comment by LiuquanReal** [comment]
have you solved this problem? Could you tell me how you solved it?thanks
