### ISSUE TITLE
gym_unity:Could not seed environment AcademyDiscrete

### ISSUE THREAD

**Issue by emarche** [Unity-Technologies/ml-agents#2791]
**Describe the bug**
As the title explains, it seems not possible to set the seed of my custom gym environment, built with Unity.
This causes my environment to spawn the same sequence of targets in every run.

It looks like the same issue reported in the obstacle-tower environment in this report https://github.com/Unity-Technologies/obstacle-tower-env/issues/91, however, it seems not fixed in the toolkit.

**Console logs / stack traces**
WARNING:gym_unity:Could not seed environment AcademyDiscrete

**Environment:**
- Ubuntu 16.04
- _ML-Agents version_: v0.10
- _TensorFlow version_: 1.13.1
- _Environment_: custom environment, very similar to the one in the documentation  (https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Readme.md)

**Additional info:**
Manually setting a seed in the Agent script (UnityEngine.Random.seed = value;) solve the problem, but this way, one should build a different version of the environment for each seed.

**Comment by surfnerd** [comment]
Hi @emarche,
We have logged this bug in our internal tracking system with ID MLA-230.  We will notify you on this thread when we have found a fix for it. Thank you for your report.

**Comment by surfnerd** [comment]
Hi @emarche, 
Since we've logged this internally, I will close this issue for now.  When this functionality is added, we will post back to this issue to update you.  Thank you for your report.
