### ISSUE TITLE
Would it be too old to still use cuda 9 cudnn7 and tf1.7.1?

### ISSUE THREAD

**Issue by daqulazhang** [Unity-Technologies/ml-agents#2794]
Hello,
I am newbie here, after followed the instruction of setting up dev environment one day, I am relly exhausted： when installing cuda, it told me my graph card driver is newer than current installing cuda.. alough I definitely installed visualstudio, it told me didn't find any VS.. until I tried to install tensorflow-gpu.. it told me can't find any available version..
I know maybe I did a lot turnning back maybe I can resolve those.. but  just wonderring why we just support cuda 10 tf 2.0 and py7..
Is it already in progress? If does, that's great~ and I really want to know when it can be done?

**Comment by surfnerd** [comment]
Hi @daqulazhang,
There is a work in progress branch for tf2.0 but it isn’t ready yet.  You should be able to install the latest Nvidia driver and it will work with earlier versions of tensorflow.  Please try installing the latest Nvidia driver for your card, and the CUDA version that it compatible with it.  Older versions of CUDA are *mostly* forwards compatible.
