### ISSUE TITLE
Improvement of HeuristicBrain by sending m_AgentInfos[agent].actionMasks

### ISSUE THREAD

**Issue by jacobson** [Unity-Technologies/ml-agents#2797]
**Is your feature request related to a problem? Please describe.**
While using `HeuristicBrain`, I have access to DecideAction which updates `vectorActions` so the agent still uses the same `AgentAction` to work; but there is something missing here. While imitating the task of a `Learning Brain`, `ActionMasks` are ignored. So the original `HeuristicBrain` has to use observations with direct knowledge of which value corresponds to what.. To make it similar to `LearningBrain` (as the architecture), it should not have that knowledge + it should use the same observations and those observations should not be used to pass `actionMasks` according to me. I am working on a game with discrete actions and decisions on demand and I **always** set `actionMasks`, I need access to `actionMasks` inside `HeuristicBrain` too.

**Describe the solution you'd like**
Inside `HeuristicBrain` class and `DecideAction` method, `Decision script `should have the knowledge of m_AgentInfos[agent].actionMasks

**Describe alternatives you've considered**
I created my own Brain after cloning and modifying Decision and HeuristicBrain scripts.
```
protected override void DecideAction() {

            if (decision == null) {
                throw new UnityAgentsException(
                    "The Brain is set to ExtendedHeuristicBrain, but no decision script attached to it");
            }
            foreach (var agent in m_AgentInfos.Keys) {
                agent.UpdateVectorAction(decision.Decide(m_AgentInfos[agent]));
                agent.UpdateMemoriesAction(decision.MakeMemory(m_AgentInfos[agent]));
            }
            m_AgentInfos.Clear();
        }
    }
}
```

**Comment by surfnerd** [comment]
Hi @jacobson,
This is currently being refactored.  You can check out the latest code on the develop branch.  The HeuristicBrain has ben renamed to HeuristicPolicy, and it now takes an `Agent` instance in the `RequestDecision` method.  Does this address your concerns?

**Comment by jacobson** [comment]
I have not try it yet; but I checked it and yes, as AgentInfo variable of Agent class is now exposed through a getter, this has to work. Thank you!
