### ISSUE TITLE
Help wanted: Trying to teach basic human needs to agent, but it prefers to chill and take penalties.

### ISSUE THREAD

**Issue by Tobbse** [Unity-Technologies/ml-agents#2798]
Hello everyone,

thanks for this awesome framework! Really enjoy playing around with it.
In my first bigger project I am trying to teach an agent to take actions based on basic human needs like thirst, hunger, sleep, etc. My problem is that this agent seems to always pick an action that will grant a penalty over some very obvious actions that would grant a high reward, meaning that my training doesn't seem to work.
The needs slowly decrease from 1 (no need) to 0 (high need) over the course of a few minutes. Taking an action that satisfies a high need will be rewarded while taking an action that satisfies a need that has a high value will be punished (like being not hungry at all and then eating a lot of food is bad). The **observations** I collect are the floats for the agent's needs.

I am using **19 discrete on-demand decisions** that the agent can pick from to fullfill those needs, like "go-to-restaurant-and-eat", "go-home-and-sleep", etc. The agent will move to the desired location, then get the reward and request a new decision right away.
Now I added another function "relaxing". This function always punishes the agent, but less then it would punish him for satisfying a need that is already fulfilled. So the idea is basically that when all its needs are satisfied, it would relax until one of the needs reaches a level where it makes sense for him to stop relaxing.

Somehow this guy is kind of like me in high school though. Even in cases where all of his needs are somewhat critical he decides to relax and take a penalty instead of satisfying his needs. So I guess in other words, I cannot manage to teach him that relaxing is only good when all his needs are fullfilled.
Mathematically this problem seems not so difficulty to me, as there are not too many actions and not too many observations to create a meaningful relation. Maybe that's where I'm wrong.

**Is this even a valid approach or is this maybe somewhat naive?**
Could anyone think of a way to improve my setup? Would it make sense to play around with curiosity and recurrent networks?

I tried playing around with the rewards and adjusting my yaml file to change parameters like the amount of layers etc. I've been training for a few hours and a few 100k steps.

I would be really glad to receive some advice. If any additional information is required I'd be happy to provide, but I didn't want to overload this with a wall of text right away.

**Thanks!**

**Comment by jacobson** [comment]
May that be possible for you to share a pseudo code for your actions and rewards, we can share more ideas. Otherwise, you may want to try teaching your AI slowly, 1 by 1, each time one thing and make it complex and include everything in the final stage. ([https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-Curriculum-Learning.md](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-Curriculum-Learning.md))

**Comment by Tobbse** [comment]
Thanks for providing that link @jacobson ! I will take a look at Curriculum Learning and see if I can somehow apply it to my problem. I can also provide some code:

In my agent's update functions the needs of the agent are reduced using `Time.deltaTime` and the function
```
    public void updateNeeds(float deltaTime)
    {
        float needReductionPerSecond = 1f / FULL_NEED_CYCLE_SECONDS;  // A full cycle is 200 seconds.
        float currentNeedReduction = needReductionPerSecond * deltaTime;

        Hunger = Mathf.Max(0f, Hunger - currentNeedReduction);
        Thirst = Mathf.Max(0f, Thirst - currentNeedReduction);
        // same with a few more needs ...
    }
```

The agent is only actually moved to a location during inference. When training, the reduction of the needs is simulated by calculating the duration it would take the agent to move by using the length of the full path and the agents speed. Otherwise the `NavMeshAgent` will get stuck and training will take forever. Basically like this:
```
private void _handleMoveDuringTraining()
{
    float duration = _getPathLength() / _npcAgentMono.navAgent.speed;
    _npcAgentMono.learningAgent.updateNeeds(duration);
    _npcAgentMono.transform.position = _destination;
}
```

When the "moving" or rather teleporting is done, a reward is added based on the needs of the agent.
So what this does is the following:
If the need value of the agent exceeds the satuation threshold (in this case 0.7f), the part of the gained need that exceeds that threshold will be a penalty. So if the the current hunger value is 0.5f and the action grants 0.5f, we will be 0.3f above the threshold, so there will be a penalty, as the agent "ate too much" now.
```
_getEatingReward()
{
    const float SATUATION_THRESHOLD = 0.7f;
    const float NEED_GAINED = 0.5f;
    float currentNeed = _npcAgent.getHunger();
    if (currentNeed + NEED_GAINED > SATUATION_THRESHOLD ) {
        // Calculate the reward or penalty based on how much we stepped over the threshold
        // If we ate only a little too much, there might still be a reward.
        // If we ate 3 hamburgers while already stuffed, there will be a large penalty.
        return someRewardOrPentalty;
    } else {
        return NEED_GAINED;
    }
}
```

Now for the relaxing function, the only thing the agent does it wait for 10 seconds (meaning he will calculate the decrease of needs for that 10 seconds) and then get a penalty:
```
_getRelaxingReward()
{
    return -0.5f;
}
```

So the agent will get a penalty when it over-satisfies its needs. Relaxing will always result in a penalty.
All of my needs have a `_getReward` function and work the same way.

The observations I make:
```
public override void CollectObservations()
{
    AddVectorObs(NeedHunger);
    AddVectorObs(NeedThirst);
    AddVectorObs(NeedSleep);
    AddVectorObs(NeedEducation);
    AddVectorObs(NeedHobby);
    AddVectorObs(NeedCommunication);
    AddVectorObs(Money);

    _maskTooExpensiveActions();
}
```

I also have a money value. One of my 18 actions is `working` which will not give a reward but reset the money value to the maximum of 1.0f. Some actions require money to be executed. If there is not enough money for an action I will mask them and stop them from being executed. Most of the actions do not require money.

I am incrementing a counter each time after an action was executed and after a few hundred actions I reset the agent. If the limit was not reached I request a new decision. So after an `AgentAction` was called and the action was performed (meaning the agent was moved and the reward was given etc. etc.), then this is called:
```
if (_numActions >= MAX_ACTIONS && !IsInference)
{
    Done();
} else
{
    _numActions++;
    RequestDecision();
}
```
This is what happens on reset:
```
public override void AgentReset()
{
    _setRandomAgentValues(); // Resets needs, money etc to `Random.value`
    _numActions = 0;
}
``` 

I really hope this somewhat understandable.
I just can't understand why it always ends up with a policy where relaxing is almost always chosen over rewarding actions.

**Comment by Tobbse** [comment]
Update: I still have some questions but I managed to (somewhat) get it working by introducing an additional penalty.
At the end of each action, the agent will be punished for having very low need levels. This encourages him to take action rather than relaxing.
I'm still not sure why the agent did not learn to take actions that might grant a reward over relaxing in the first place, but this seems to have fixed it.

I also prevent the same actions to be executed twice in a row. **Is this generally a bad practice?**

I seem to have fixed my issue, but **I would still love get some feedback** as to whether or not my whole setup makes sense for a scenario like this.
It seems a bit hard for a beginner like me to decide about things like what hyperparameters to set in the .yaml config and for example whether or not curiosity and memory are needed in a scenario.

Also about this whole Curriculum Learning, **how would I start setting it up?**
Is it possible to start training with a fixed number of decisions and increase that number, so that additional possible actions can be executed?
In the curriculum example it seems very straightforward to adjust the wall height during training, but I'm not sure how to apply that to my situation.

I would like to extend my project and introduce things like currency and resources so that my agent learns that it first has meet some predconditions like gathering some resources before it can execute an action.

Thanks for helping! :)
