### ISSUE TITLE
Is it possible to plot the trained network?

### ISSUE THREAD

**Issue by wrd90** [Unity-Technologies/ml-agents#2802]
I was wondering if it's possible to plot the model in any way. I was thinking the tensorboard graph might be a possible solution, but apparently there are no graphs being saved in the summaries directory.

Can someone point me in the right direction? Do I have to modify some python code for this?

**Comment by surfnerd** [comment]
Hi @wrd90,
It looks like this was requested previously in #2518 and #1992.  We have logged it internally as a request and will bump up its priority in our internal tracker.  Internally we are tracking it with ID MLA-19.  I am going to close this issue for now, and will update this thread when we have added support for this.

**Comment by wrd90** [comment]
@surfnerd thank you, that's helpful already

**Comment by wrd90** [comment]
Hi @surfnerd,

I'm sorry for bothering you again with this, but I was hoping you could help me with this. 

I was able to plot the tensorflow graphs in tensorboard thanks to your references to issues #2518 and #1992, however, I can't seem to find the structure of the model, including the trained weights. Can you maybe tell me how or where I can find this? is this part of `raw_graph_def.pb` or `frozen_graph_def.pb`?

I can see two subgraphs which contain the layers, but inside the layers I don't see the actual structure or the weights. Is this just my ignorance? I would be very grateful for your help.

The reason why I am asking, is the inference of the model on a rover, and for documentation purposes.

Best,
David

![graph](https://user-images.githubusercontent.com/3441341/67637149-d19e9980-f8d7-11e9-93c7-0f51d801441d.png)
![Hidden layers subgraph](https://user-images.githubusercontent.com/3441341/67637164-f72ba300-f8d7-11e9-9e2d-2b2cc68ecaed.png)
