### ISSUE TITLE
Robot building & Reacher example playerBrain manipulation

### ISSUE THREAD

**Issue by hongluck** [Unity-Technologies/ml-agents#2803]
Hello, I am currently working on unity to train robotic manipulators. 

Thanks to the  ML Agent package which has variety of examples including the Reacher example.

I made a virtual robot in the environment, which I can control just by using rotation in the coordinates.

![image](https://user-images.githubusercontent.com/52731362/67604803-9a4eb200-f74a-11e9-8592-f7305ad6146e.png)

I am not using rigidbody component, just rotating it using 

Rotate(Vector3(0f,1f,0f);

It is because the hinge joint, configuration joint has compliance in shear. Also, I could not find a way to have two rigidbodies connected together which has to move depending on each other(without shear compliance)!

I have tested through a simple code in Unity code by just mapping key using

void Update()
{
Input.GetKey(KeyCode.Q)
joint.Rotate(new Vector3(0f,1f, 0f);
}
Using just Unity, made pretty good results so that I can manipulate a robot inside Unity.

However, when it comes to ML Agents, it seems like the AgentAction code is not working.
![image](https://user-images.githubusercontent.com/52731362/67606046-34642980-f74e-11e9-82eb-283515de20c0.png)

I found out that the AgentAction code is not working.
Even though I use Debug.log inside the AgentAction code, there are no response.  
![image](https://user-images.githubusercontent.com/52731362/67605484-7f7d3d00-f74c-11e9-883d-60770f1f8350.png)

I do not have any response with the playerBrain.
I have 7 transform. position VectorObs, resulting in 21.
Also I have connected 6 joints with +1, -1 values so need 12 key continuousPlayerActions Size.
the vectorAction[] should have a size of 6 index.
![image](https://user-images.githubusercontent.com/52731362/67606012-1d253c00-f74e-11e9-9a6d-4dafd32948d8.png)

I do not know what to do since, basic control of the robot with the Brain is not working. 
I was going to use the PlayerBrain reference in the Reacher example but in the ML Agent Package, there are no player Brain in the Reacher example. 

It does not have any compile errors.

Please help me fix the issue.

**Comment by surfnerd** [comment]
Hi @hongluck, 
Would you be able to share your project?  Without knowing how your scene and objects are setup, it's hard to know what the issue is.

**Comment by hongluck** [comment]
This is the link to my project
https://drive.google.com/open?id=1fu4ii0XNlpPKA1o_GoRyTx7Rn9ydmUMc

The goal of this project is to make a robot reach a random target(without using IK).
I did not finish the code yet so the resetting and others are still in progress. 
The main problem for me right now is that the robot itself is not controllable with the player brain.

The project consists of a Agent, Goal, Academy with other environmental objects.
Agent object is the robot with a hierarchy. The robot is modeled just using transform(not RigidBody). In the Agent there are two scripts which is Doosanmachinesetting.cs and SDoosanAgent1105.

Doosanmachinesetting.cs is a file that I was testing the robot constraint when I first built the robot.
SDoosanAgent1105 is the file I was going to do ML. 

The Doosanmachinesetting.cs script works fine which you can control the robot joint 1 to 6 with QAWSED keys respectively. But whenever I use the SDoosanAgent1105.cs, it will not be able to control the robot. I do not know why because it is almost the same as the previous mentioned file.

I used ReacherAgent example as a reference without using joints. 
In the player brain I should be able to control the robot but I cannot. I think the AgentAction function is not working. I do not know why and please help me fix the issue.
For your convenience, copied and pasted the previous issue below.









Hello, I am currently working on unity to train robotic manipulators. 

Thanks to the  ML Agent package which has variety of examples including the Reacher example.

I made a virtual robot in the environment, which I can control just by using rotation in the coordinates.

![image](https://user-images.githubusercontent.com/52731362/67604803-9a4eb200-f74a-11e9-8592-f7305ad6146e.png)

I am not using rigidbody component, just rotating it using 

Rotate(Vector3(0f,1f,0f);

It is because the hinge joint, configuration joint has compliance in shear. Also, I could not find a way to have two rigidbodies connected together which has to move depending on each other(without shear compliance)!

I have tested through a simple code in Unity code by just mapping key using

void Update()
{
Input.GetKey(KeyCode.Q)
joint.Rotate(new Vector3(0f,1f, 0f);
}
Using just Unity, made pretty good results so that I can manipulate a robot inside Unity.

However, when it comes to ML Agents, it seems like the AgentAction code is not working.
![image](https://user-images.githubusercontent.com/52731362/67606046-34642980-f74e-11e9-82eb-283515de20c0.png)


I found out that the AgentAction code is not working.
Even though I use Debug.log inside the AgentAction code, there are no response.  
![image](https://user-images.githubusercontent.com/52731362/67605484-7f7d3d00-f74c-11e9-883d-60770f1f8350.png)

I do not have any response with the playerBrain.
I have 7 transform. position VectorObs, resulting in 21.
Also I have connected 6 joints with +1, -1 values so need 12 key continuousPlayerActions Size.
the vectorAction[] should have a size of 6 index.
![image](https://user-images.githubusercontent.com/52731362/67606012-1d253c00-f74e-11e9-9a6d-4dafd32948d8.png)



I do not know what to do since, basic control of the robot with the Brain is not working. 
I was going to use the PlayerBrain reference in the Reacher example but in the ML Agent Package, there are no player Brain in the Reacher example. 

It does not have any compile errors.

Please help me fix the issue.

**Comment by surfnerd** [comment]
Hi, I've requested access to your project on google drive.

**Comment by hongluck** [comment]
Just accepted. Thank you for your help

2019년 11월 6일 (수) 오후 2:06, Chris Goy <notifications@github.com>님이 작성:

**Comment by hongluck** [comment]
Maybe you checked the box in the machine setting script? If you uncheck the
upper script it will not move. I mean only with the SDoosan script does it
move?

2019년 11월 6일 (수) 오후 3:02, Chris Goy <notifications@github.com>님이 작성:

**Comment by surfnerd** [comment]
![Screen Shot 2019-11-06 at 1 48 48 PM](https://user-images.githubusercontent.com/1356616/68340958-40c87a80-009c-11ea-8b9e-85d209adb01f.png)

This is the configuration of the object in the Hierarchy.  The upper script is unchecked, and the robot joints were moving.

**Comment by hongluck** [comment]
I guess this is a bug in my computers? You can move the robot without QAWSED?

I even tried with another PC and started all over again and it is not moving.
What version of Unity are you using?

What do you think may be the cause of this problem?

**Comment by surfnerd** [comment]
I am using QAWSED to move the robot.  I didn't find a `.nn` file in the project to try running inference.  I haven't tried training it either.

**Comment by surfnerd** [comment]
It looks like your learning brain isn't setup with the same action/observation space as your player brain.  I'm not sure why it's not working for you.  Very peculiar.

**Comment by hongluck** [comment]
There should be no .nn file because I did not train the learning brain yet. What version of Unity are you using?

**Comment by surfnerd** [comment]
I used 2019.2.3f1

**Comment by hongluck** [comment]
I have tried it with your version and it works perfectly fine.
Thank you for your help.

I was using 2019.3.0a8 , 2019.3.0b9 which gave no errors but failed to use player brain.
 2017.4.32f1 and 2018.4.7f1 failed to load the setting.

Thank you I will close the issue
