### ISSUE TITLE
Some questions about step and visual observation.

### ISSUE THREAD

**Issue by xunyiljg** [Unity-Technologies/ml-agents#2805]
I'd like to know what exactly step represents in training. If fixedupdate is set to 50, then 0.02 seconds is calculated once. Is this step? Does that mean that I use 8 agents to train 1 million steps less than 16 agents to train 1 million steps? Or is every decision interval a step?

My second question is, if I use visual and length 8 LSTM with decision interval of 5, then there are eight graphs in one input. Is the interval of each graph 5? If my requirement is that although I only make a decision once in 0.02 * 5 seconds, my input needs to have more graphs (for example, there are 3 graphs in total in the current time and the first two times, as the observation of the current time, (t-0.04, t-0.02, t)), does the current toolkit support this function?

I hope you can answer my doubts.

**Comment by surfnerd** [comment]
Hi @xunyiljg,
A step, the way it is implemented in ML-Agents, is one FixedUpdate loop in an environment.  It doesn't matter how many agents you have.

Let me talk to my team about the second question at I am not familiar with all of the details.

**Comment by xunyiljg** [comment]
@surfnerd, Thank you for your reply. 
On the second problem, if the decision interval also affects the input interval, there are limitations.
