### ISSUE TITLE
Using supervised learning pretrained models using ml-agents

### ISSUE THREAD

**Issue by dhiabhr** [Unity-Technologies/ml-agents#2806]
Hello all,

I have a question. I trained a keras/tensorflow model to detect different motions in images, and  i wanted to use it in unity.  Is it possible to do using the ml-agent toolkit?

Thanks in advance.

**Comment by surfnerd** [comment]
Hi @dhiabhr,
While we only support ML-Agents trained networks for inferences, you can try converting your model with the [tensorflow_to_barracuda.py](https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents/mlagents/trainers/tensorflow_to_barracuda.py) script.  There is no guarantee that it will work.
