### ISSUE TITLE
Why is it that it works well in training, but the effect of using the trained model is poor? 

### ISSUE THREAD

**Issue by LiuquanReal** [Unity-Technologies/ml-agents#2816]
I trained an official case where the effect was good at the end of the training, but the effect was poor when using the training-completed model?

**Comment by chriselion** [comment]
This sounds like this known issue: https://github.com/Unity-Technologies/ml-agents/issues/2775 Can you try downgrading tensorflow to 1.14.0?

**Comment by LiuquanReal** [comment]
> This sounds like this known issue: #2775 Can you try downgrading tensorflow to 1.14.0?
I've changed the version to 1.14.0, but I still can't solve the problem

**Comment by LiuquanReal** [comment]
The problem was solved when I upgraded my python to 3.7

**Comment by lukemadera** [comment]
I am having the same issue. I did the RollerBall example and it trains to an average reward of 0.99 to 1.0 yet when I run it live it rolls off the platform probably 50% of the time. I was on Python v3.6.9 and I updated to v3.7.4 - no change. Any suggestions or ideas of why the training looks great but the resulting model is far worse?

**Comment by chriselion** [comment]
Hi @lukemadera,
My recommendation is to wait for the 0.11.0 release of ML Agents, which will be out today. That contains the fix for the conversion to barracuda for tensorflow 1.15.

**Comment by lukemadera** [comment]
Ah, great, thanks @chriselion ! As I did more reading on gpu, I saw many mentions that GPU either wasn't implemented for MLAgents, or if it was, it didn't run any faster. But then I saw some other posts saying it was now ready and faster, and that a flag for cpu or gpu was coming? What is the current status of GPU training (e.g. with CUDA 10 and one or more RTX 2070 or RTX 2080 Ti GPU(s))?

**Comment by chriselion** [comment]
Hi @lukemadera,
Unfortunately, I don't think there's a better guideline than "it depends". I think the consensus is that GPUs will help with visual observations, but probably not much with vector observations unless you have a lot of them.

Multi-GPU support was added a few releases ago; you can enable it with `--multi-gpu` from the command line.

**Comment by lukemadera** [comment]
Gotcha. So in "real world" we usually are using cameras to capture data and GPU shines there, but in Unity ray casting (vectors) are used instead, so we don't need to use convolutional layers and images, and thus GPU doesn't shine as much? Or something along those lines? Any idea why OpenAI Five (which I thought used Valve's API (rather than images) for Dota2, and GPU) was different?

**Comment by chriselion** [comment]
I haven't gotten deep into tensorflow to know where it benefits from running on the GPU. I think if you have large vectors of observations it will still speed things up, but not for dozens of observations.
