### ISSUE TITLE
Viewing the specs/summaries of ML-Agents pre-trained neural networks

### ISSUE THREAD

**Issue by pnut7** [Unity-Technologies/ml-agents#2819]
I'm looking to understand the pre-trained models (for example: PushBlockLearning.nn) included with the ML-Agents toolkit. Are they proprietary? If not, how do I view their specs or at least their summaries? 

I have yet to discover a way to view the .nn details in the Unity Editor. Visual Studio cannot open the .nn files at all, and I see lots of garbage text when opening the files using text editors -- is there a specific tool or maybe Python/C# code that can allow me to view these files? 

The .nn's are included in 'TFModels' directories so I'm assuming this can be achieved via Tensorflow?....is there a Barracuda to Tensorflow conversion feature? 

Sorry for all the questions, but any help with this would be appreciated.

**Comment by rajatpaliwal** [comment]
Hi @pnut7 ,
The .nn files are the files that basically contain trained neural net . I believe the best way to interpret what's inside .nn files i.e. the neural net architecture, how data is flowing through different layers , data type etc. can be seen by plotting graph of trained neural net in Tensorboard. You can find a lot of insight by going through this issue #2518 . Hope this helps.

**Comment by pnut7** [comment]
Hi @rajatpaliwal -- 

I agree with your sentiments in issue #2518 and I will definitely look into this. Thanks for the reference!
