### ISSUE TITLE
Adding ML Agents to existing projects

### ISSUE THREAD

**Issue by zako42** [Unity-Technologies/ml-agents#2820]
Sorry for the potentially dumb question, but what is the recommended path to using ML Agents in a Unity project?

Up until now, I've been cloning the ml-agents repo, and then adding my own environment to `UnitySDK/Assets/ML-Agents/Examples/myproject`.  This has been fine for testing things out and training agents.  But if I wanted to add ML Agents to an existing project, what is the recommended way to do this?

I'm thinking I could just copy over the `UnitySDK/Assets/ML-Agents` folder and then delete all the examples.  But is there any plan to make this into like a package we can pull through the package manager or something like that?  Having a package would also let us specify version number in the manifest.

**Comment by akTwelve** [comment]
You're correct. You can copy the ML-Agents and Gizmos directories into the Assets directory of your project. Be aware that if you delete the Examples folder, you lose some useful scripts, like RayPerception, so you may want to delete the Examples selectively.
