### ISSUE TITLE
Can I reset specific agent when using multiple agents through python API ?

### ISSUE THREAD

**Issue by HugeKangroo** [Unity-Technologies/ml-agents#2829]
Hello,

I have build an environment with four robot arms and trainning the robot arms through Python API.
Now, I can control the arms by `env.step()` and I would like to reset a specific arm when it is done . 
How can make the specific arm reset ? 

Thank you.

**Comment by harperj** [comment]
Hi @HugeKangroo -- we don't support the ability to reset individual agents from Python at this time.

**Comment by HugeKangroo** [comment]
That's OK, the current version is good enough for me :)
