### ISSUE TITLE
Support for Tensorflow 2.0

### ISSUE THREAD

**Issue by leonardoaraujosantos** [Unity-Technologies/ml-agents#2835]
There is any roadmap on when we will be able to use TF2? Thanks guys

**Comment by harperj** [comment]
Hi @leonardoaraujosantos -- we have a WIP pull request (#2665) to explore support for TF2, but I believe we don't have any specific dates set for when it will be available at this time.

**Comment by leonardoaraujosantos** [comment]
Cool thanks @harperj I will give a try on this PR as well.

**Comment by chriselion** [comment]
Sorry for the late update. Recent versions of ML Agents support tensorflow 2.0.0.
