### ISSUE TITLE
how to communicate with  training code write by C# (tensorflow.net ), not python

### ISSUE THREAD

**Issue by BenDerPan** [Unity-Technologies/ml-agents#2838]
Describe what you'd like to discuss.

#### C# is more convenient to maintance or debug than python for me , and I know there is [tensorflow.net](https://github.com/SciSharp/TensorFlow.NET) which allow C# programmer to write training model with C# language.
Is there any guides for build tranning model with other languages? or can I just build a grpc communicate channel to do that?

**Note**: The ML-Agents team has limited resources for education and community discussion.  We'll participate as we are able, but encourage members of the community to support one another to discuss and support one another.

**Comment by Esther2013** [comment]
Related issue https://github.com/SciSharp/TensorFlow.NET/issues/438

**Comment by jorezy** [comment]
Why should we have to create a ML agent in Python? If we had enough AI solutions in .NET, the AI agent ought to be created in .NET, am I right? Microsoft is integrating Tensorflow.NET to solve this problem, I think this should be the future. Unity 3D developers are going to be able to use C# to develop their AI applications without relying on Ml-Agent created in Python.

**Comment by flo-wolf** [comment]
Any updates on this?
