### ISSUE TITLE
Outdated UnityTimeOutException in v0.11

### ISSUE THREAD

**Issue by akTwelve** [Unity-Technologies/ml-agents#2841]
I'm having training issues, specifically getting the RPC Communcation to work in the release-0.11.0 branch. I'm still trying to debug that, but while doing that I realized that an exception message is no longer relevant due to the removal of the Broadcast Hub and Brains. Figured that should be updated so that the next person to have a connection issue isn't confused. 🙂

Here's the error message:
  File "c:\users\ak12\anaconda3\envs\ml-agents_0.11\lib\site-packages\mlagents\envs\rpc_communicator.py", line 86, in initialize
    "The Unity environment took too long to respond. Make sure that :\n"
mlagents.envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
         The environment does not need user interaction to launch
         **The Academy's Broadcast Hub is configured correctly
         The Agents are linked to the appropriate Brains**
         The environment and the Python interface have compatible versions.

**Comment by akTwelve** [comment]
Ok, I fixed my problem and in the process realized why I was getting the out-dated exception too.
I used pip install mlagents, which installed from PyPi, instead of installing the new version from the 0.11 branch folder. Training started working and that error message has been updated when I followed the [Installing for Development instructions](https://github.com/Unity-Technologies/ml-agents/blob/release-0.11.0/docs/Installation.md#installing-for-development). Oops!

**Comment by kumarict** [comment]
I'm receiving this same error when running on Ubuntu 16.04. Has v0.11 been confirmed to work on Ubuntu 16.04? I've made sure I'm running the developer code.

**Comment by surfnerd** [comment]
Hi @kumarict,
Please make sure you've installed the python package and UnitySDK from the 0.11.0 release.  The gRPC service definition changed and is not backwards compatible with previous versions.

**Comment by kumarict** [comment]
Hi @surfnerd,

I just installed from the repository and followed the instructions to load the python libraries from the ml-agents-envs and ml-agents directories. When I run ml-agents-learn, it works fine and connects to Unity. However, when I try to use a Jupyter notebook, the connection does not occur when I try the getting started notebook. And again, I'm using Ubuntu 16.04. Has this been confirmed to work? If so, any idea where to look for issues? Thank you.
