### ISSUE TITLE
Can I use only Player Brain to learn the Agent?

### ISSUE THREAD

**Issue by WannyWanny** [Unity-Technologies/ml-agents#2843]
I want to use ML-Agent to study deep learning in my environment.
In order to use Learning Brain, functions such as AgentAction and CollectObservations must be written. Is this the same when using Player Brain? I wonder if I can learn by receiving the user input value without creating a function

**Comment by harperj** [comment]
Hi @WannyWanny -- you'll need to implement the Agent interface even when you just want to use the Player brain to record demonstrations.

**Comment by WannyWanny** [comment]
@harperj -- I know that Player Brain only learns at the user's input value. Can i record user input if i just implement the Agent Interface as you say? I'd like to see an example of that, if you don't mind.

**Comment by harperj** [comment]
Sorry, I don't have an example for you handy.  You can see the [imitation learning docs](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-Imitation-Learning.md) for more about how to record demonstrations though.
