### ISSUE TITLE
The Agent will terminate when ResetOnDone unchecked and OnDemandDecision checked.

### ISSUE THREAD

**Issue by HugeKangroo** [Unity-Technologies/ml-agents#2844]
**Describe the bug**

Hello,
I am using LearningBrain with external Python script to train a robot arm. I prefer to use `env.reset()` on Python side to reset the academy. But I found that when I check the OnDemandDecision and leave the ResetOnDone unchecked the Agent will terminate after ActionAct() and the Python script will stop at that point.

**Environment (please complete the following information):**
- OS + version: Ubuntu18.04
- _ML-Agents version_: 0.10
- _TensorFlow version_: 1.15.0

**Comment by HugeKangroo** [comment]
Hello @harperj 
Sorry for delayed reply. I was on a business trip.
I made a minor changes on the `ResetIfDone` in `Agent.cs` code and it works for me
```
 void ResetIfDone()
        {
            // If an agent is done, then it will also
            // request for a decision and an action
            if (IsDone())
            {
                if (agentParameters.resetOnDone)
                {
                    if (agentParameters.onDemandDecision)
                    {
                        if (!m_HasAlreadyReset)
                        {
                            // If event based, the agent can reset as soon
                            // as it is done
                            _AgentReset();
                            m_HasAlreadyReset = true;
                        }
                    }
                    else if (m_RequestDecision)
                    {
                        // If not event based, the agent must wait to request a
                        // decision before resetting to keep multiple agents in sync.
                        _AgentReset();
                    }
                }
                else {
                    if(agentParameters.onDemandDecision){
                        RequestDecision();
                    }
                    else{
                        m_Terminate = true;
                        RequestDecision();
                    }
                }

                // else
                // {
                //     m_Terminate = true;
                //     RequestDecision();
                // }
            }
        }

```
Hope these can help you or others who may meet the same problem.

**Comment by harperj** [comment]
This problem is fixed in recent releases of ML-Agents, in which we updated `AgentOnDone` and logic around resetting agents.  I'm going to close this issue, but please feel free to re-open if you have any more trouble.
