### ISSUE TITLE
Jobs and ECS Agents

### ISSUE THREAD

**Issue by HoomanJCode** [Unity-Technologies/ml-agents#2846]
hello, I am using unity Jobs and ECS to control more than thousands of agents. ml-agents system based on mono behavior. then I can not use ml-agents at my project easily.
I don't want to process all of them at the main thread. because I'm implementing my game server and the deadline is important.
is there any way to implement agents on Unity ECS? can I use the NeuralNetwork math model or any kind of ai math model at my project directly (not for learning, I want use trained data from ml-agent)? is it possible?

**Comment by harperj** [comment]
Hi @HoomanJCode -- we don't currently have an ECS-based solution for ML-Agents, but it's something we're working on.  I can't give you a specific timeline but know that it is on our roadmap.
