### ISSUE TITLE
Making a New Learning Environment Behavior Parameters?

### ISSUE THREAD

**Issue by kevtan** [Unity-Technologies/ml-agents#2856]
Hello! I was trying my best to follow the tutorial about how to create my own Unity RL environment but got really stuck at the "Final Editor Setup" portion. **Where can I set the Behavior Parameters of the Agent?**

I've looked in the Academy GameObject, RollerAgent GameObject, and every other place in my editor but I just can't seem to find it. It also asks us to override the Heuristic() method of the RollerAgent but I get an error saying that there is no suitable method to override. Any help would be appreciated!

**Comment by OliverMathias** [comment]
Having the same problem here, could it be down to the version of MLAgents?

**Comment by kevtan** [comment]
@OliverMathias So I did some more snooping around and was finally able to figure things out. I think it does have to do with the version of MLAgents that we're using. Essentially, some things have changed about the Agents and Brains since the onboarding readme was last updated (I'm thinking of contributing a new, updated one in the near future!).

Here's what I did to fix my problems regarding the behavior parameters:
1. First right click in the Project window and click Create>ML-Agents>Learning Brain (maybe call it RollerBallLearningBrain) in order to create a new brain to attach to our agent to train. This is the thing that you're going to be setting parameters for.
2. Click on the Learning Brain in the Project window and you should see a bunch of parameters you can set in the Inspector window. Here is where you can specify the `Vector Observation Space Size`, `Vector Action Space Type` and `Vector Action Space Size`.

Here's what I did to fix the issues regarding the `Heuristic()` method:
1. It looks like there isn't a `Heuristic` method in the base class to override. What you actually need to do is the create a "Player Brain" in the same manner as creating the Learning Brain (from above).
2. Then click on the newly created Player Brain and set the `Vector Observation Space Size`, `Vector Action Space Type` and `Vector Action Space Size` parameters to match up with how you designed your environment. 
3. Lastly, you need to define some keyboard mappings. Under where you set the parameters, there is a place to "Edit the [discrete/continuous] inputs for your actions." Here, change the `Key Continuous Player Actions` parameter to 4 (we want to have 4 movement keys WASD). Then you can specify the `Key`, `Index`, and `Value` for a player action. The index refers to the index inside of the `vectorAction` array that `AgentAction()` receives and the value is just the number at the index inside that array.
4. After setting up these keyboard mappings, I was able to get everything to work!

**Comment by OliverMathias** [comment]
Thanks for the instructions @kevtan! I also managed to get it working. All I did was add a default "Behaviour Parameters" script to the RollerAgent game object. My scene is in a subfolder of ml-agents so it auto-populated the script.

**Comment by kevtan** [comment]
@OliverMathias Wow! That's a much simpler solution. I just tried it though and I don't think I was able to get it working. I created a new script component to the RollerAgent game object called "BehaviorParameters" and then I got the following auto-populated script:
```c#
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class BehaviorParameters : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
```
Is this what you were working with? How do I set the different parameters once I'm at this point?

**Comment by OliverMathias** [comment]
@kevtan Sorry for the miscommunication, I was kind of vague when describing the "auto population". I meant that if your scene folder is under the ml-agents/Examples folder in the unity project, and you start to type in "Behavior Parameters" unity should let you use the default script they already have written for the other examples.
 
To give a better visual, imagine the picture below, but instead of "Game Setup" it lets you select a "Behavior Parameters" script. 

![50917-unity-problem](https://user-images.githubusercontent.com/44181723/68549646-7c6e8780-03af-11ea-9d5d-40179309f27e.png)

Hope this helps :)

**Comment by kevtan** [comment]
@OliverMathias Thanks for following up, but I still don't think I'm able to replicate what you're doing. I tried it in my own project but also the example project folders found in UnitySDK. I've attached a screenshot for reference. Are you doing anything special that's allowing your Unity to find the "Behavior Parameters" component?

<img width="449" alt="Screen Shot 2019-11-10 at 6 30 11 PM" src="https://user-images.githubusercontent.com/33914892/68556760-67621a80-03e8-11ea-8b30-76916065cfb3.png">

**Comment by OliverMathias** [comment]
Hmmm, that's really weird @kevtan. For me the "BehaviorParameters" script is under 
"ml-agents\UnitySDK\Assets\ML-Agents\Scripts\Policy\BehaviorScript.cs" 

There is also a "BehaviorParametersEditor" script under the 
"ml-agents\UnitySDK\Assets\ML-Agents\Editor\BehaviorParametersEditor.cs" path.

 I don't think I'm doing anything different, do you have these scripts in your project?

**Comment by kevtan** [comment]
@OliverMathias I just pulled from the remote repository and now I have these scripts and it's all working. Thanks!

**Comment by himanshi4693** [comment]
@kevtan , @OliverMathias : I'm working on the same version of ML_Agents and have these behavior parameters set up. I'm able to train in editor using the mlagents-learn command. However, I want to train with my own algorithm implementation so I'm trying to interact with the environment build on jupyter notebook. When I try printing the environment information, I get the following:
![Screenshot_2](https://user-images.githubusercontent.com/38923623/69057830-c17b6500-0a12-11ea-9a72-356180391fab.png)

Any idea on how to proceed? Thanks in advance!

**Comment by OliverMathias** [comment]
@himanshi4693 Hmmm I don't have any experience trying to get ML-Agents working with external models. Were you able to figure it out?

**Comment by kevtan** [comment]
@himanshi4693 As long as you get the message that the academy has started successfully (and the environment executable should launch as well) then you should be golden. For me, it also said that the number of training brains was 0, but I was still able to call `step()` on the environment with actions, get observations, and progress the agent through the environment. Ultimately, these are the things you need to train your RL agent.

**Comment by chriselion** [comment]
@himanshi4693 - it's OK to ignore the `Number of Training Brains : 0` message. That log is obsolete; starting in the most recent version, we don't send brain parameters until later, so that list of brains is always empty. I'm cleaning it up in https://github.com/Unity-Technologies/ml-agents/pull/2950
