### ISSUE TITLE
SAC training on single environment instance ? 

### ISSUE THREAD

**Issue by MoMe36** [Unity-Technologies/ml-agents#2857]
Hey, just a quick question about the SAC best pratices.  

Given that SAC is an off-policy algorithm, unlike PPO, it doesn't need several cloned environment instances, does it ? 

Thanks !

**Comment by anupambhatnagar** [comment]
@ervteng do you have any thoughts on this?

**Comment by ervteng** [comment]
Hi @MoMe36, it's less critical for SAC to have many cloned instances, but it still benefits from the increased data throughput, especially if the environment takes a while to step.

**Comment by MoMe36** [comment]
Thanks ! I was used to use a single instance, given the other github implementations, but that's really good to know ! Thanks a lot ! ((: 
Closing the issue !
