### ISSUE TITLE
Cannot GetValueEstimate when in Inference mode

### ISSUE THREAD

**Issue by Phong13** [Unity-Technologies/ml-agents#2860]
**Describe the bug**

This is something that worked in Version .8 but not in version .10. If I call GetValueEstimate on a trained brain in inference mode, the returned value is always 0.

**To Reproduce**

Train a brain using PPO
Switch the Academy "control" setting for the brain to unchecked
Try to call "GetValueEstimate()" in AgentAction. The value will be zero.

I have been looking through the code in "LearningBrain.cs" which is responsible for retreiving the action value. When I print out the m_OutputNames from the tensor model after it is loaded the output names are:

- action
- value_estimate

However if I try to fetch the Tensor for "value_estimate" in FetchBarracudaOutputs

var output = m_Engine.Peek("value_estimate");

Then a "KeyNotFound" Exception is thrown.

**Console logs / stack traces**
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
- Windows 10
- _ML-Agents version_: (e.g. ML-Agents v0.10)
- _TensorFlow version_: 1.7
- _Environment_: 3DBallHard

I added GetValueEstimate() at the beginning of AgentAction. It always returns 0 if the brain is in inference mode.

If I try to add "value_estimate" to the outputs in BarracudaModelParams.GetOutputNames, then a "KeyNotFound" Exception is thrown.

In Version .8 this worked. I could get the value estimate when in inference mode. This is very useful.

**Comment by anupambhatnagar** [comment]
@Phong13 could you please update to the latest version (ml-agents 0.11) and try this again?

**Comment by Phong13** [comment]
Yes it happens with version 0.11 too.

To reproduce
     Clean install of ML-Agents v 0.11
     Open the 3DBallHard.Unity scene
     Edit the Ball3DHardAgent.cs so that at the beginning of AgentAction
          Debug.Log("Value= " + GetValueEstimate());

Run the scene in inference mode. The console will print "Value= 0"

**Comment by anupambhatnagar** [comment]
@Phong13 apologies for the delay in replying. this feature has been removed from our code base and there is no equivalent of this anymore. I recommend upgrading to the latest version of ML-Agents as we have introduced several new features and many bugs have been fixed.
