### ISSUE TITLE
Save the .nn file every checkpoint

### ISSUE THREAD

**Issue by devedse** [Unity-Technologies/ml-agents#2865]
Hi all,

Would it be possible to automatically save a .nn file every time a checkpoint is made. That way I can have one PC training until infinity and basically develop the game further using the latest .nn model.

**Comment by anupambhatnagar** [comment]
@devedse this sounds like a useful feature. I have added it as a feature request into our backlog.

**Comment by devedse** [comment]
@anupambhatnagar , what I'm running into currently is that the training process crashes sometimes. Sometimes due to something I can't really pinpoint and also a few times due to an out of memory exception.

Is it possible to manually generate a .nn file from the last snapshot without starting to train? (I noticed some issues when I continued training, but lets leave that for another day)

**Comment by anupambhatnagar** [comment]
@ervteng do you have any insights into generating a .nn file from the last saved checkpoint? Due to the training process crashing @devedse would like to extract the model from the saved checkpoint.

**Comment by ervteng** [comment]
Yes, that can be done pretty easily by running mlagents-learn and adding the `--load` parameter, with the same run-id, and quitting immediately using Ctrl+C when the agents start training. This should load the latest saved checkpoint and then export to barracuda.

**Comment by devedse** [comment]
Would it be possible to add the logic to save it every checkpoint?

**Comment by Tobbse** [comment]
I'm wondering if there might be a way to export a .nn file from checkpoints that are not the latest checkpoint?
This would be very useful to me as I would sometimes after a long training session like to use policies at specific points of time during the training.
For example, I have a project that involves some very unstable training, which is likely my own fault. But nevertheless I would like to use the policy given at the checkpoint with the highest reward which is not nessecarily the latest one.

**Comment by devedse** [comment]
Well, if the tooling would generate a .nn file during creation of a snapshot then your issue would also be tackled :)

**Comment by Tobbse** [comment]
True, but then we'd end up with a whole bunch of .nn files :)

**Comment by devedse** [comment]
Well, now we have a whole bunch of snapshot files so I couldn't really see one file making the difference. Besides that a CLI option could be added to enable/disable this feature.

**Comment by devedse** [comment]
I totally agree on the need of having to solve this for @Tobbse 's issue as I'm also running into that problem:

![image](https://user-images.githubusercontent.com/2350015/71351723-b1f0be00-2574-11ea-9996-8ed79030e730.png)

In the example above I'd want to get the .nn model of one of these peaks as apparently the model performed best there.

Now it's almost like following the stock trade market 😆

**Comment by devedse** [comment]
Or well, basically have some way to pick out the best .nn models would be good.

**Comment by ervteng** [comment]
It's a bit tricky to export `.nn` more than once b/c of how Tensorflow handles frozen graphs, but possible. 

There is a workaround however. Without making changes to ML-Agents, it IS possible to save `.ckpt` files more than once (in fact, if you look in your models folder, there should be a bunch of them named by step, and you can increase the number with `the --keep-checkpoints` commandline option. 

Now, in the folder that these are all saved, edit the text file called `checkpoint` and replace `model_checkpoint_path` with the one you want. Then run `mlagents-learn` with the `--load` parameter, it will then load THIS checkpoint instead of the latest, and quitting using Ctrl+C immediately after it starts training will export it to `.nn`.

**Comment by Tobbse** [comment]
Thank you @ervteng! This is really helpful.

**Comment by DanJBower** [comment]
This would be a helpful feature for me as the model was at one point much better than it was at the final point, like Devedse's example

> I totally agree on the need of having to solve this for @Tobbse 's issue as I'm also running into that problem:
> 
> ![image](https://user-images.githubusercontent.com/2350015/71351723-b1f0be00-2574-11ea-9996-8ed79030e730.png)
> 
> In the example above I'd want to get the .nn model of one of these peaks as apparently the model performed best there.
> 
> Now it's almost like following the stock trade market 😆

**Comment by ys-yamashita** [comment]
Only v0.13.0
ckpt to nn converter

https://github.com/ys-yamashita/cptk2barracuda

**Comment by DanJBower** [comment]
> Only v0.13.0
> ckpt to nn converter
> 
> https://github.com/ys-yamashita/cptk2barracuda

Seems interesting and could be really useful. Is there any reason it wouldn't work with other versions such as 15.0?

**Comment by ys-yamashita** [comment]
Coincidentally my project was v0.13.0, so I made that converter. I don't think it will support other versions

**Comment by alonsorobots** [comment]
I would absolutely love the feature to automatically save .nn files, particularly if one of them was always the one with the highest current reward for this session.

**Comment by ys-yamashita** [comment]
OK for v0.16.1
https://github.com/ys-yamashita/cptk2barracuda

**Comment by harperj** [comment]
Just wanted to give an update -- we recently added an export to `.nn` for each checkpoint. It was merged in #4127 and should land in the next release.

**Comment by Tobbse** [comment]
Awesome! Thanks for letting us know @harperj . This will be quite useful.

**Comment by devedse** [comment]
Awesome thanks guys!!
