### ISSUE TITLE
A better way for ML-Agents to handle multiprocessing

### ISSUE THREAD

**Issue by J-Travnik** [Unity-Technologies/ml-agents#2866]
After looking closely at the way mlagents manages the multiprocessing of unity game builds, I think there could be a better way to handle the subprocesses.

From what I gather, the parent process doesn't call `wait` or `waitpid` and, as far as I can see, isn't acting like a "watchdog" in the case that the child processes crash.

This means that these processes are "zombied", staying alive indefinitely so that the parent process doesn't end either.
Has anyone else noticed something similar happening?

**Comment by anupambhatnagar** [comment]
@J-Travnik From where are you able to infer that the parent process doesn't call `wait` or `waitpid`? It would be great if you could provide information on what you ran and the setup you are using. Thanks!

**Comment by chriselion** [comment]
Hi @J-Travnik,
I *think* this should have gotten better in the 0.11.0 release. We added a timeout on the communication between C# and python here: https://github.com/Unity-Technologies/ml-agents/pull/2812

We also changed the shutdown behavior slightly to wait a bit before killing the spawned process: https://github.com/Unity-Technologies/ml-agents/pull/2620/files (although this means we'll end up waiting for `timeout_wait` twice, which is arguably not ideal).

So if I'm reading this all correctly, when the we try to step the environment here:
https://github.com/Unity-Technologies/ml-agents/blob/5194664db8a078a2673edef2cbd82a90975a9b59/ml-agents-envs/mlagents/envs/subprocess_env_manager.py#L99

If the other process is dead, we'll raise the exception here
https://github.com/Unity-Technologies/ml-agents/blob/5194664db8a078a2673edef2cbd82a90975a9b59/ml-agents-envs/mlagents/envs/environment.py#L527

which will get caught here
https://github.com/Unity-Technologies/ml-agents/blob/5194664db8a078a2673edef2cbd82a90975a9b59/ml-agents-envs/mlagents/envs/subprocess_env_manager.py#L119-L130

and `env.close()` will (eventually) kill the process.
