### ISSUE TITLE
Limitations When Using Multiple Brains In Inference Mode

### ISSUE THREAD

**Issue by Phong13** [Unity-Technologies/ml-agents#2867]
**Is your feature request related to a problem? Please describe.**

I have trained multiple brains for controlling a powered ragdoll character's movements (walking, get-supine, getup-prone, jumping, airborn, swimming, etc...) I switch between these brains on the agent.

I would like the ability to query brains that are not the "active" brain. For example when the character has fallen I need to decide how to get up (one of "getup-supine" or "getup-prone). I would like to be able to get the Value_Estimate for both the getup-supine and getup-prone brains and choose the brain with the greatest reward estimate. 

Another need is for blending actions. For example I might train an archery brain that handles the arm movements for controlling a bow. I would like to mix this brain with a walking brain. I would use a mask to apply the walking brain to the legs and torso and the archery brain for controlling the arms and head. 

Another need is for brains that do not need to be tied to the Update loop. For example a visual-recognition brain that is trained to recognized an categorize a set of objects. A developer might want to query this brain occasionally as part of some larger process.  The current ML-Agents architecture requires the Brain to be contained in an Agent and stepped by the Academy. The brain can only be queried asynchronously requiring at least one FixedUpdate step. Using such a brain requires very complicated asycnronous programming.

It is difficult with the current architecture of ML-Agents to have more than one active brain. The problems are:

- The brain is tightly coupled to an Agent and the Academy. It can only CollectObservations, DecideAction and AgentAction as part of an Agent and stepped by the Academy. 
- Features/Observations and Actions/Outputs belong to the brains, but they are stored in the Agent. It is not possible to query a brain for its Outputs/Actions without loading the Features (Collect Observations) into an Agent. Then an agent is required to read the outputs. An Agent can have only one set of Features/Observations and Outputs/Actions.
- Querying a brain is tightly coupled to the Agent, Academy and FixedUpdate loop. It is very difficult (requires a lot of hacking) to query a brain outside this loop. If you need to query a brain then asynchronous processing is required. Yielding until a FixedUpdate loop has fired and outputs are available.

**Describe the solution you'd like**
IMO querying a brain in Inference mode using Barracuda should be possible outside the context of an Academy and an Agent and the FixedUpdate-loop.

- Features/Observations and Values/Actions should be part of the Brain, NOT the Agent.
- There should be a way to step/query a Brain in inference mode outside the context of an Academy, Agent and FixedUpdate-loop. Perhaps a class called InferenceBrainRunner that has a method similar to Academy EnvironmentStep. 

**Describe alternatives you've considered**
I am currently using Multiple "Agents" on the same GameObject. This is not as flexible as I would like because they are all Stepped at the same time as part of FixedUpdate.

I have tried to write an InferenceBrainRunner but it requires considerable hacking of the ML-Agents install which I would rather not do. 

**Additional context**
N/A

**Comment by Phong13** [comment]
I have given this a bit more thought:

Basically IMO the Brain should be a low level API that is consumed by the Academy. Observations and Actions should be part of the Brain, not the Agent.

Also, why do brains need to be tied to agents? There are many, many use cases for training and using brains outside the context of an Agent and the FixedUpdate loop.

For example:

- A typed text interpreter (player types some input and the brain tries to understand what the player wants).
- An image categorizer that reads Mamograms

Why do these need to be tied to an Agent and the FixedUpdate loop? As a developer I would like to query these on demand.


-

**Comment by Phong13** [comment]
Turns out it is fairly easy to decouple the Agent from the Brain. Agent needs to implement an interface:

`    public interface IBrainInputOutputSource
    {
        Agent GetAgent();

        void UpdateVectorAction(float[] actions);

        void UpdateValueAction(float action);

        void UpdateMemoriesAction(List<float> actions);

        List<float> GetMemoriesAction();
    }`

Then the m_agentInfo Dictionary is Dictionary<IBrainInputOutputSource, AgentInfo>.

Everything works and I can use the Brain with any class that implements the IBrainInputOutputSource methods.

**Comment by Phong13** [comment]
I could submit a PR with the solution if that would be useful.

**Comment by anupambhatnagar** [comment]
@Phong13 I have raised the issue of adding multiple brains with the team. at present this feature is under discussion.

**Comment by Phong13** [comment]
Thanks for considering it :)

**Comment by caioc2** [comment]
Those ideas to query a brain without the need of being tied to an agent would be excelent and extend ML-Agents usage for many other cases which actually are impossible or very hack.

It would be amazing to have those features available.
