### ISSUE TITLE
Weird error comunicate after upgrading to 0.11.0

### ISSUE THREAD

**Issue by BlonskiP** [Unity-Technologies/ml-agents#2868]
**Describe the bug**
When I want to lunch learning I get a weird error in anaconda console. It seems that i can't use tensorboard too.

**Console logs / stack traces**
```2019-11-07 22:57:33.771290: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2019-11-07 22:57:33.777471: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



                        ▄▄▄▓▓▓▓
                   ╓▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
          ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
          ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓▌
                        ¬`▀▀▀█▓


INFO:mlagents.trainers:CommandLineOptions(debug=False, num_runs=1, seed=-1, env_path=None, run_id='0110test', load_model=False, train_model=True, save_freq=50000, keep_checkpoints=5, base_port=5005, num_envs=1, curriculum_folder=None, lesson=0, slow=False, no_graphics=False, multi_gpu=False, trainer_config_path='config/warrior.yaml', sampler_file_path=None, docker_target_name=None, env_args=None, cpu=False)
INFO:mlagents.envs:Start training by pressing the Play button in the Unity Editor.```


```
**Screenshots**
![image](https://user-images.githubusercontent.com/26842884/68431348-44e6bc00-01b2-11ea-9913-cfc0d7350538.png)

![image](https://user-images.githubusercontent.com/26842884/68431579-d5250100-01b2-11ea-867c-ddf38ca83b72.png)

**Environment (please complete the following information):**
- OS + version: Windows10
- _ML-Agents version_:ML-agnets 0.11.0
- _TensorFlow version_: 
Name: tensorflow
Version: 1.15.0
- _Environment_: NONE

**Comment by albertoxamin** [comment]
did you update the python package with 

```bash
pip install --user --upgrade mlagents
```

**Comment by BlonskiP** [comment]
> may i ask if you updated the python package with
> 
> ```shell
> pip install --user --upgrade mlagents
> ```

I was using anacond env. I have deleted old env and installed a new one. Should I use ```pip install --user --upgrade mlagents ``` too?

**Comment by albertoxamin** [comment]
Use `pip list` to view the installed version, I had the same problem and after upgrading mlagents I managed to solve it 


Before upgrading
```bash
→ pip list
Package               Version
--------------------- --------
...
mlagents              0.10.1
mlagents-envs         0.10.1
...
```

After upgrading 
```bash
→ pip list
Package               Version
--------------------- --------
...
mlagents              0.11.0
mlagents-envs         0.11.0
...
```

**Comment by BlonskiP** [comment]
It seems that i have mlagents 0.11.0 version installed.
![image](https://user-images.githubusercontent.com/26842884/68472761-7b0f5480-0221-11ea-961d-61aeda1f03aa.png)

**Comment by BlonskiP** [comment]
I have downgraded Tensorflow to 1.14.0
![image](https://user-images.githubusercontent.com/26842884/68535662-0eda4100-0346-11ea-967e-05cd3f1339c8.png)
Is this version OK with ML-agents 0.11.0 ?

**Comment by chriselion** [comment]
@BlonskiP What's the actual problem? The deprecation warnings from tensorflow are safe to ignore. Overall, it looks like training is working and your reward is increasing over time.

I'm not sure about the cuda warnings; worst case is that you'll use CPU training instead of GPU. If you want to resolve those, you'll need to look around on tensorflow or cuda support.

Tensorflow 1.14.0 is supported on ML Agents 0.10 and 0.11. Tensorflow 1.15 is only supported on ML Agents 0.11.0

**Comment by anupambhatnagar** [comment]
@BlonskiP Could you please provide a screenshot of the error message you are receiving and what you did to get the error message. Thanks.

**Comment by Peng2017** [comment]
It seems you installed tensorflow 1.15 by default, which is incompatible with your old version tensorflow dependencies. (for example, if you installed tensorflow 2.0 before, and switch your CUDA version to 10.1, you'll get these error messages, because CUDA 10.1 is not compatible with tensorflow 1.15)
To check this, just open your Anaconda Prompt, type in "python", and then type in  "tensorflow", you'll probably get error messages such as "Could not load dynamic library..."
