### ISSUE TITLE
[development-0.3] Strange behaviour while instantiating agents

### ISSUE THREAD

**Issue by ferpica** [Unity-Technologies/ml-agents#287]
EDIT: I discarded my original question, it was fixed in a new commit. Of course, i'm playing with the dev branch, sorry.

Hi! I'm testing the development-0.3 branch because I need to instantiate and destroy agents from script, and I couldn't do it from master.

I noticed a strange behaviour while instantiating agents following the [docs](https://github.com/Unity-Technologies/ml-agents/blob/development-0.3/docs/Instantiating-Destroying-Agents.md), it says we should Instantiate new agents like this:

```
agentPrefab.GetComponentInChildren<Agent>().GiveBrain(brain);
GameObject newAgent = Instantiate(agentPrefab);
newAgent.GetComponentInChildren<Agent>().AgentReset();
```

It calls GiveBrain on the Agent component from the prefab (the one in assets resources), and it seems that agent gets registered in the brain, as well as the agent from the instantiated gameobject.
I instantiated 4 agents and the brain had 5 agents in its list.
It also called CollectState on that agent, which in my case threw an error because my agent needs an external reference after being instantiated.
I tried to use GiveBrain on the instantiated agent, but it didn't work. I think it has something to do with the usage of the brain property on the OnEnabled of Agent.
I got it working by doing this, but I don't think its very nice:

```
var agent = agentPrefab.GetComponentInChildren<Agent>();
agent.GiveBrain(Brain);
GameObject newAgent = Instantiate(agentPrefab);
agent.RemoveBrain();
var myAgent = newAgent.GetComponentInChildren<SenteAgent>();
myAgent.AgentReset();
```

Also, correct me if I'm wrong, but if I destroy the agent's GameObject in OnAgentDone it removes it from the brain, causing it not to send the result and the reward to the Python API, right?

Thank you for your time!

**Comment by vincentpierre** [comment]
Hi, thank you for testing this out. This feature is experimental and I am glad you could provide feedback on it. Removing the brain from the prefab is the right way to fix it. We hope to provide a simpler way to instantiate agents. Unfortunately as of now, destroying the gameObject will prevent it from sending its reward and state. Another quick fix would be to use [Destroy](https://docs.unity3d.com/ScriptReference/Object.Destroy.html) and passing a float argument to delay the destruction.

**Comment by ferpica** [comment]
Hi @vincentpierre.
I didn't know Destroy had a delay argument, nice!
I wrote a little ugly workaround and it works, but the delay is a much better solution.
Instantiating and destroying agents works perfectly.
Thank you very much! Your project is awesome
