### ISSUE TITLE
Menu Option: Assets -> Create -> ML-Agents is Missing

### ISSUE THREAD

**Issue by tmddnrdl** [Unity-Technologies/ml-agents#2870]
Hi,
I've tried to get my ML project in Unity.
When I want to get my learning brain,
so I click the Assets -> Create, but there is no 'ML-Agent' button.
I'm using 2019.2.11f1.
What is the problem? and how can I fix it?
Thanks.

**Comment by bharathk005** [comment]
@tmddnrdl did you find a solution for this?

**Comment by anupambhatnagar** [comment]
@vincentpierre Was this change affected by a recent code refactor?

**Comment by vincentpierre** [comment]
Brains have been deprecated in v0.11. According to the [Migration guide](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Migrating.md#migrating-from-ml-agents-toolkit-v010-to-v011) 
 > Since Brain ScriptableObjects have been removed, you will need to delete all the Brain ScriptableObjects from your Assets folder. Then, add a Behavior Parameters component to each Agent GameObject. You will then need to complete the fields on the new Behavior Parameters component with the BrainParameters of the old Brain.
