### ISSUE TITLE
Curriculum Learning set up

### ISSUE THREAD

**Issue by the-zer07** [Unity-Technologies/ml-agents#2872]
I read the documentation about CL but I don't understand how to implement in my project. I'm doing a vehicle AI in a racing game, so actually there are 4 cars that must drive in a track. 
I'm using camera e raycast sensor to determine other vehicles and the walls.
I saw that classic RL it's too hard, for each car it's very difficult concurrently learning the steering, accelerating/breaking and collision avoidance, so I think using CL could be a solution but I don't know what to write in my code.
I thought before the cars should learn how to steer, accelerate and break and then collision avoidance. Maybe I should training the cars ignoring the collisions among them during the x% of the max steps, in this case the cars should learn how to steer and at the same time the correct value of acceleration and break. In the end after x% max steps activate the collisions and the cars should learn the collision avoidance.
Could someone help me?

**Comment by hvpeteet** [comment]
Hi thanks for the interest. If you are still looking for advice on CL I would recommend the forums https://forum.unity.com/forums/ml-agents.453/ where other users can help you out with their experience as well.

**Comment by hvpeteet** [comment]
Closing since this has been stale for over a year and was just a redirect to the forums.
