### ISSUE TITLE
Behavior Parameters are not taking in Visual Observations

### ISSUE THREAD

**Issue by pranavvaidik** [Unity-Technologies/ml-agents#2881]
Describe what you'd like to discuss.

**Note**: The ML-Agents team has limited resources for education and community discussion.  We'll participate as we are able, but encourage members of the community to support one another to discuss and support one another.

Hi all, I was working on a project and suddenly started having problems with getting ML-Agents to work. I just found out that there have been a lot of changes in the new releases that are not backward compatible. I tried to update my code as much as possible, but my agent uses visual observations. Now, the behavior parameters only take in vector observtions, not visual observations, which is looking very bad for my project right now. Apparently ML-Agents is not very updated with documentation either, so the documentation is not upto speed with the latest updates.

Can someone tell me how to get the behavior parameters to take in the visual observations? Or, suggest a way to revert to previous M-Agents version until this new release is stable.

Thank you very much for your help!

**Comment by chriselion** [comment]
Hi @pranavvaidik,
Visual observations are no longer configured in the behavior parameters, you need to add CameraSensorComponents or RenderTextureSensorComponents to your agent. This is addressed in the [Migration Guide](https://github.com/Unity-Technologies/ml-agents/blob/release-0.11.0/docs/Migrating.md#steps-to-migrate-1):
> If your Agents used visual observations, you must add a CameraSensorComponent corresponding to each old Camera in the Agent's camera list (and similarly for RenderTextures).

You can also check out the GridWorld example scene, which uses Cameras and a RenderTexture to do visual observations.
