### ISSUE TITLE
Using CNN as input in the main RL NN during inference

### ISSUE THREAD

**Issue by Tylawoj** [Unity-Technologies/ml-agents#2883]
Hello everyone. Sorry if this is a bit off-topic.

I am planning on using two visual observations from the Unity environment in my machine learning project, which will serve as inputs to my reinforcement learning neural network. The RL network will be trained using an external trainer, by wrapping the Unity environment in a gym.

The first one will be used in a CNN for object recognition (trained on a small dataset beforehand), where later the output from the CNN will serve as input (in a numerical form) to the main RL NN, while the second visual observation will just be processed via the canny edge detection algorithm, and then also thrown as input.

Originally I was planning on using Keras to do the first part, and OpenCV for the second, however after going through the documentation I understand that only sole (and not all) TF/Keras code, as well as pure Python, can be transferred from a .pb/.h5 file to a .nn format that the Barracuda inference library supports.

Therefore I would like to know if I am right in understanding that:

1. The only way to use output from a CNN as input/observation for an Agent is to:
- train my CNN using TF/Keras, performing convolutions only by using TF/Keras functions
- convert the model using Barracuda
- then in the CollectObservations() function of my Agent (to ensure it runs right before collecting data) use Barracuda to run the converted model by providing a RenderTexture from a Camera as a Tensor for the model
- store output from the CNN by using the Peek() function
- finally provide it as a vector observation to my RL NN

2. To preprocess the second visual observation before the RL NN takes it as input, I will have to:
- store a RenderTexture from another Camera
- implement the whole Canny edge algorithm in C#, as I cannot transfer any OpenCV code from training to inference
- finally provide it as a visual observation to my RL NN

Many thanks for any answers.

**Comment by MarkTension** [comment]
Interested in this as well! In the same situation here

**Comment by MarkTension** [comment]
I've implemented everything like in 1 , and it works
