### ISSUE TITLE
Can't override Heuristic on inherited Agent class

### ISSUE THREAD

**Issue by NickPowers43** [Unity-Technologies/ml-agents#2884]
[this](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md#testing-the-environment) section of the documentation seems to be out of date. I can't find the virtual member function "Heuristic" on the Agent class. Is there an alternative?

**Comment by chriselion** [comment]
Hi @NickPowers43,
It's on the Agent class: https://github.com/Unity-Technologies/ml-agents/blob/3d7c4b8d3c1ad17070308b4e06bb57d4a80f9a0c/UnitySDK/Assets/ML-Agents/Scripts/Agent.cs#L516-L529
(master branch is current the same as the 0.11.0 release branch(

**Comment by NickPowers43** [comment]
Thanks. Pulled the latest master and it is available.
