### ISSUE TITLE
Feed agent with output from custom pre-trained barracuda-embedded network possible?

### ISSUE THREAD

**Issue by MarkTension** [Unity-Technologies/ml-agents#2886]
Hi all!

How will it work if I make an agent that doesn't get input directly from the unity scene, but from a pre-trained CNN that I embed into unity via Barracuda? The barracuda network would basically output a big feature-vector that I want to feed into the agent as a Vector observation.

Thanks in advance

**Comment by Zilch123** [comment]
It should work just fine. 
You have to create your .nn file from the .pb file as shown in the [Barracuda documentation](https://github.com/Unity-Technologies/ml-agents/blob/master/UnitySDK/Assets/ML-Agents/Plugins/Barracuda.Core/Barracuda.md) given below. Just manually load the file and give the vector action manually. Have implemented it and the code is [this](https://github.com/Zilch123/Custom-Barracuda-Implementation/tree/master).
