### ISSUE TITLE
Imitaion Learning with Multiple Demos, Demo Recording via Build

### ISSUE THREAD

**Issue by Yunao-Shen** [Unity-Technologies/ml-agents#2889]
Hi everyone,
Currently, I'm training wihth GAIL. Is there any way I can train an agent with multiple demos. How can I add mutiple demo paths in my trainer_config?
@ervteng Hi, sorry to bother you. I found a closed issue in which you mentioned that "You can put multiple demo files in a directory and pass a directory in your trainer_config.yaml if you want to use multiple recordings." How should I do it, is there any example? Thank you.

**Comment by Yunao-Shen** [comment]
Another problem, is it able to record demo in build? It seems to be only available in editor.

**Comment by ervteng** [comment]
Hi @Yunao-Shen, just put the folder name and put only the demo files you want in there. For instance, if you have `demo1.demo` and `demo2.demo` you can put them in a folder called `./demos` and put that in your `trainer_config`.

You can record demos in the build but you'll have to edit DemonstrationRecorder.cs. Remove all mentions of `Application.isEditor` in the if statements and the build will record.

**Comment by Yunao-Shen** [comment]
Yeah it works good. Now I can train the agent with multiple demos. Thank you a lot!

**Comment by Yunao-Shen** [comment]
> Hi @Yunao-Shen, just put the folder name and put only the demo files you want in there. For instance, if you have `demo1.demo` and `demo2.demo` you can put them in a folder called `./demos` and put that in your `trainer_config`.
> 
> You can record demos in the build but you'll have to edit DemonstrationRecorder.cs. Remove all mentions of `Application.isEditor` in the if statements and the build will record.

Hi @ervteng , it seems that recording demo in build doesn't work. I modified the DemostrationRecorder.cs . It could generatate .demo file but it's almost empty, only including first line. I tried development build but it didnt solve the problem.

**Comment by ervteng** [comment]
Hmm, as this is an unsupported feature at the moment, I'm not sure the current state of this functionality. But I have gotten it to work simply by removing `Application.isEditor` - you might have to modify it in `Agent.cs` too - in `SendInfoToBrain()`

**Comment by Yunao-Shen** [comment]
Ye after modifying the Agent.cs it could know record the data. Thank you a lot!

**Comment by chriselion** [comment]
We removed the requirement for recording demonstrations from the editor a while ago in this PR: https://github.com/Unity-Technologies/ml-agents/pull/3488/files
