### ISSUE TITLE
Is it possible to have an Agent without being a specific GameObject?

### ISSUE THREAD

**Issue by MarkTension** [Unity-Technologies/ml-agents#2891]
In the documentation it is said that an agent and academy subclass need to be linked to a specific GameObject. I guess that means that the Agent also needs to have a certain manifestation in physical space.  

However, I'm thinking of a non-physical agent that only returns a vector (containing coordinates) based on its visual input. 

Is this possible?

**Comment by anupambhatnagar** [comment]
@surfnerd Do you have any idea on this one?

**Comment by surfnerd** [comment]
Hi @MarkTension,
You should be able to instantiate a Policy without the agent subclass.  The `Agent` just calls into the `BehaviorParameters.GeneratePolicy` method.  This, indeed, does use the `Academy` to see if training is happening.  

In short, it is possible, you just need to write some extra code to hook it up.  If you have any specific questions, please feel free to follow up on this thread.
