### ISSUE TITLE
New instalation guide not working for windows

### ISSUE THREAD

**Issue by PabloOlinav** [Unity-Technologies/ml-agents#2895]
Hi, 

It happens to me that the new instalation guide for windows is not working correctly, I get to install python 3.6.0 and the pip3, but when i try to execute "python3 -m venv python-envs\sample-env" on the console it does not give me an error but it also does not do anything, so the next comand "python-envs\sample-env\Scripts\activate"  tells that it can not find the route.

Before you ask, yes, python 3.6.0 was correctly installed and even on the same disk as the rest, and the system variable are made correctly.

**Comment by anupambhatnagar** [comment]
Thanks fro the feedback @PabloOlinav We will look into this issue and update the docs accordingly.

**Comment by Ziache** [comment]
I had this issue, I fixed it by moving my env.

The path had a '[' character, and it seems like Windows doesn't like it !

**Comment by DVonk** [comment]
Try 'python' instead of 'python3'.

**Comment by PabloOlinav** [comment]
Thanks! Using only 'python' made it works! Don't know why i haven't tryed it before.

Now, I have the problem while installing the ml-agents, cause it gives me an error whith tensorboard, i dont know if the installation was completed after that.
![Captura](https://user-images.githubusercontent.com/20268684/68946761-0c4b7180-07b4-11ea-94cd-5b23c588b8b4.PNG)

**Comment by chriselion** [comment]
Hi @PabloOlinav,
ml-agents doesn't have any specific requirements on tensorboard or setuptools, so it's coming from one of the other packages. You might try installing `setuptools == 41.0.0` first and see if that helps resolve it.

PS - in the future, please paste the errors and use triple-backticks (```) instead of screenshots - it makes the errors easier for others to search for in the future.
