### ISSUE TITLE
Resetting agents to get rid of mean reward nan error

### ISSUE THREAD

**Issue by niskander** [Unity-Technologies/ml-agents#2899]
I've been getting the "Mean reward: nan" error during training. I read this in the [FAQ](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/FAQ.md):
"In order to address this, set Max Steps for either the Academy or Agents within the Scene Inspector to a value greater than 0"

Initially, I had the Academy steps set to a large positive number and the agent steps set to 0. After reading the FAQ, I set the agent steps to 5000 and this seems to have indeed gotten rid of the nan mean reward error. But my environment has sparse rewards and is not easy to "win", so setting the max steps seems counter-intuitive to me, since my reset function resets the agent to a point where they have to start all over again. 

e.g. Let's say an agent needs to get from point A to B to win, and I keep resetting the agent halfway through to get rid of this error... isn't that counterproductive?

**Comment by ervteng** [comment]
Hi @niskander, you shouldn't be getting the `Mean reward: nan` error regardless of the agent steps. Rather, it should say "no episode was completed" if the episode doesn't terminate. If you see a NaN reward found warning, that means one of the rewards was actually a NaN, usually a divide-by-zero. 

You're right, resetting too early makes learning harder. I wouldn't worry if the episodes don't finish in the beginning of training; as the agent learns, the episode will get shorter and you'll see the mean reward being reported. I'd set agent steps to much larger than you think the agent needs to solve the level, and lengthen `summary_freq` in the `trainer_config.yaml` file.

**Comment by niskander** [comment]
Hi @ervteng , thanks for the response. It's actually both issues, I've attached a screenshot to demonstrate: 
![noepisodecompleted_LI (2)](https://user-images.githubusercontent.com/1988272/68895155-c54b7680-06f6-11ea-915f-9e3b2af5c8f4.jpg)

It looks like it's trying to update the policy before any episode completes and thus getting nan as a result? Do you know a solution to this other than setting max steps on the agents?

**Comment by niskander** [comment]
I should also mention that setting the max steps to a positive number does seem to resolve the error (but if I set it to a large number sometimes I still see this). In the screenshot it's uncapped.

**Comment by niskander** [comment]
My solution right now is to set max steps on the agents, and _not_ reset them on done, with no max steps on the environment. This does work around the issue. Just want to make sure it's normal to have to do that?

**Comment by ervteng** [comment]
From the screenshot it looks like your environment is not outputting NaNs, which is good. 

This is nearly an "infinite horizon" problem - what you're doing seems to be good. The Trainer will recognize that the agents hit a max step and treat it as if the episode kept going.

**Comment by niskander** [comment]
Sounds good. Thanks for your input @ervteng
