### ISSUE TITLE
IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by anktplwl91** [Unity-Technologies/ml-agents#29]
While running the 3DBall example, I am getting IndexOutOfBounds exception for the Platform agent. Here's the snippet for the error
![capture](https://user-images.githubusercontent.com/13707940/30741470-8708a846-9fb2-11e7-9801-20beeb6f7a48.PNG)

I thought changing the value of Action Size parameter in Inspector window to 8 might solve the issue, but that just gives me another error
![capture1](https://user-images.githubusercontent.com/13707940/30741571-edcae594-9fb2-11e7-97cd-be45843a30c2.PNG)

**Comment by eagleEggs** [comment]
While putting together custom agents, Im seeing the same issue reported only though the Jupyter training function though (PPO book). Would love to figure this out :D

No matter how many states or changing state total within the inspector - it's returning the same result.

**Comment by vincentpierre** [comment]
@anktplwl91 It seems to me your brain has `State Size` set to 0 when it should be 8 and `Action Size` set to 0 when it should be 2. In the Inspector on your `Brain` component, what are the `Brain Parameters` set to?

**Comment by anktplwl91** [comment]
Hi @vincentpierre, the brain parameters ```State Size``` and ```Action Size``` were indeed set wrong. But now that I changed these to 8 and 2 respectively, I am still getting below ```NullPointerException```.

![capture](https://user-images.githubusercontent.com/13707940/30897340-53bede32-a373-11e7-98f5-5984504d325e.PNG)

**Comment by vincentpierre** [comment]
@anktplwl91 I think you must change your action space type from discrete to continuous in your brain parameters. Let me know if this helps.

**Comment by anktplwl91** [comment]
Hi @vincentpierre, changing the action space to continuous has worked and the game is working fine now. Thanks a lot.
