### ISSUE TITLE
Q-learning vs Evolution algorithm

### ISSUE THREAD

**Issue by svLimones** [Unity-Technologies/ml-agents#290]
Greetings
I'm trying to train a navigation agent. A simple field algorithm. But I can not understand why training is so ineffective. The genetic algorithm allows to find a good agent for 1000 steps. Q-learning does not reach such a result and for 200,000 steps. Tried various parameters of training.
1) Q-learning is real less effective for such an environment?
2) Is it possible to integrate an evolutionary algorithm into the training process?
3) Is it possible to teach a previously trained agent?
thanks for the interesting framework

**Comment by awjuliani** [comment]
Hi @svLimones,

Thanks for reaching out. The relative performance of these kinds of algorithms can vary quite a bit based on the implementation and the problem you are trying to solve. We are actively examining whether to include DQN variants or ES algorithms. If you have a particular algorithm you'd like to see implemented, please feel free to create a new issue an tag it with `request`.
