### ISSUE TITLE
Missing BroadcastHub options in v.011

### ISSUE THREAD

**Issue by mbaske** [Unity-Technologies/ml-agents#2904]
> "The BroadcastHub has been deprecated. If there is a training Python process, all LearningBrains in the scene will automatically be trained. If there is no Python process, inference will be used."

Hi - How can I train agent A while running inference for agent B in v0.11? I have a hierarchical setup, where it's important that A can rely on B's pretrained behaviour while learning its own. Thanks!

**Comment by mbaske** [comment]
I've added a `m_UseBarracuda` bool to the `BehaviorParameters` script, which allows me to skip the `IsCommunicatorOn` check for a given agent and return a `BarracudaPolicy` anyway. This seems to be doing what I want, but I'm not sure if it has any other unintended effects. 
However, combining training and inference in a multi-agent environment seems like a rather basic requirement. I wonder why this feature was removed?

**Comment by vincentpierre** [comment]
Hi @mbaske 
T=You are right, we removed the capacity to do training and have a brain running inference at the same time. This was to make it easier to get started with the toolkit (removing the broadcast hub). The fix you did is exactly what I would have done and I do not think there would be any side effects.

**Comment by DVonk** [comment]
> Hi @mbaske
> T=You are right, we removed the capacity to do training and have a brain running inference at the same time. This was to make it easier to get started with the toolkit (removing the broadcast hub). The fix you did is exactly what I would have done and I do not think there would be any side effects.

Are you planning on making this more intuitive? As said, I find this to be a very basic requirement. Removing the capacity for training and inference at the same time, just to make things slightly easier to use, doesn't sound like a very good idea.
