### ISSUE TITLE
Can't find Behavior Parameters on Agent?

### ISSUE THREAD

**Issue by StuckinPhD** [Unity-Technologies/ml-agents#2905]
Hi,

I'm following the tutorial of making a new environment here: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md

and in the ``Final Editor Setup`` step point 4 mentions to set the following parameters on the agent:

```
Modify the Behavior Parameters of the Agent :
Behavior Name to RollerBallBrain
Vector Observation Space Size = 8
Vector Action Space Type = Continuous
Vector Action Space Size = 2
```

But I cant find these values on my Agent script?
![1221](https://user-images.githubusercontent.com/44167893/68808671-283efe00-0662-11ea-9394-60a7030b3699.PNG)

Where do I set these values?

**Comment by Tylawoj** [comment]
Check this link:
https://github.com/Unity-Technologies/ml-agents/issues/2871#issuecomment-552179615

**Comment by StuckinPhD** [comment]
> Check this link:
> [#2871 (comment)](https://github.com/Unity-Technologies/ml-agents/issues/2871#issuecomment-552179615)

Thank you. 
Maybe they should add this to the beginner tutorial?
