### ISSUE TITLE
Reward based on past

### ISSUE THREAD

**Issue by dorog** [Unity-Technologies/ml-agents#2907]
Hi!

I need an advice.

I'm working on a tower game and I wanted to add a good AI, so I decided to use ML-agent. 

In my game there is a tower in the middle of the scene and I want to teach the tower how to shoot down the moving or static objects. I have a problem with the moving objects. They can move, so I can't decide for sure the result (hit or miss). I tried the instant feedback (if the object was in the range and the tower aimed it I gave a reward - it didn't work with the moving object) and the "time difference" feedback (if the bullet hit the object I gave a reward) but none of them was good. Is there any way to handle the situations like that or should I predict the result and give reward based on the prediction?

**Comment by ervteng** [comment]
Hi @dorog, from what it sounds like, the second option (if the bullet hit the target, give a reward) is the better option. What you need to make sure is that the tower has some way to observe the velocity of the target. This can be done in two ways: adding the velocity of the target explicitly to the observations, or using Stacked Vectors (will need a bigger network/will take longer to train). What's the observations look like?

**Comment by dorog** [comment]
Hi @ervteng

Thank you your response. 

Right now I add 6 float to the tower. (One tower and one objects are in the scene)
1. Can fire? (0 or 1)
2. Distance between the tower and the object
3. Angle (tower should rotate, it can shoot only forward)
4-5. Object's forward (x, z) (object can move only forward)
6. Object's speed

And I set the stacked vectors to 40 (the bullet will die in 32 fix update + 8 stacks just in case)

**Comment by ervteng** [comment]
This should be sufficient, but stacked vectors 40 is quite a lot. I'd try stacked vectors 3 or 4 - or even no stacked vectors since you have the object's velocity as part of the observation. 

Also make sure your observations are normalized either by making them between -1 and 1, or turning on `normalize: true` in the trainer config.

**Comment by dorog** [comment]
Thank you! :)

The tower improved quite a lot. I have one more question. The std of Reward is high. What can be the problem? Should I change the config parameters or brain's settings / inputs?

Right now I use continuous space type with two output (one for rotate, one for shoot).

**Comment by ervteng** [comment]
Continuous should be OK for this problem. Is there a lot of variation in your episodes? std of reward being high isn't necessarily bad as long as it's hitting the target :P

You can try lowering beta for more deterministic behavior if entropy is also high.

**Comment by dorog** [comment]
I changed a few parameters and a reward system. It became an op tower :) 

Thank you! You can close the issue :)

**Comment by ervteng** [comment]
Good to hear! Glad you were able to train your tower.
