### ISSUE TITLE
Visual sensor shape dimensions are swapped in v0.11

### ISSUE THREAD

**Issue by mbaske** [Unity-Technologies/ml-agents#2914]
The shape dimensions of `CameraSensor` and `RenderTextureSensor` are swapped in v0.11.

To reproduce, set non-quadratic shape size like 96x48 in sensor component.
Python console log:
`ValueError: Cannot feed value of shape (1, 48, 96, 3) for Tensor 'visual_observation_0:0', which has shape '(?, 96, 48, 3)'`

The problem appears to be the line
`m_Shape = new[] { width, height, grayscale ? 1 : 3 };`
in `CameraSensor`  and `RenderTextureSensor` constructors.
The error disappears after changing it to
`m_Shape = new[] { height, width, grayscale ? 1 : 3 };`

**Comment by chriselion** [comment]
Thanks for catching this. I'll update our examples to use non-square visuals to hopefully prevent anything like this from happening again.

**Comment by chriselion** [comment]
PR here: https://github.com/Unity-Technologies/ml-agents/pull/2919

**Comment by chriselion** [comment]
This is fixed on the develop branch now, and will be in the next release.
