### ISSUE TITLE
Error while installing mlagents

### ISSUE THREAD

**Issue by ralph367** [Unity-Technologies/ml-agents#2918]
While trying to install mlagents using pip3 install mlagents, I'm getting this error

ERROR: Could not find a version that satisfies the requirement tensorflow<2.0,>=1.7 (from mlagents) (from versions: none)
ERROR: No matching distribution found for tensorflow<2.0,>=1.7 (from mlagents)

**Comment by chriselion** [comment]
@ralph367 What version of python are you using? Tensorflow doesn't yet support python3.8 (see https://github.com/tensorflow/tensorflow/issues/33374) so you'll need to either downgrade to python 3.7, or wait for them to build new packages.

**Comment by ralph367** [comment]
> @ralph367 What version of python are you using? Tensorflow doesn't yet support python3.8 (see [tensorflow/tensorflow#33374](https://github.com/tensorflow/tensorflow/issues/33374)) so if you're using 3.8, you'll need to either downgrade to python 3.7, or wait for them to build new packages.

I installed python 3.7.5 and still facing the same error, is there any needed version for pip as well?

**Comment by chriselion** [comment]
Sorry, I'm not sure. There are binary wheels of tensorflow for 3.7: https://pypi.org/project/tensorflow/1.15.0/#files
so I would expect it to work. What platform are you on? I've heard of some people accidentally using 32-bit python on windows, which might explain it.

You need to be able to do `pip install "tensorflow<2.0"`, but if that doesn't work, this isn't the best place to troubleshoot it.

**Comment by ralph367** [comment]
@chriselion you were right I was using a 32-bit version, it is working now thanks.

**Comment by chriselion** [comment]
Glad that worked. I've got a PR to update the FAQ with this (and few related issues we've been seeing): https://github.com/Unity-Technologies/ml-agents/pull/2920

**Comment by ShivamMukherjee** [comment]
If I run `mlagents-learn --help`, this shows up:

`Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\mlagents-learn.exe\__main__.py", line 4, in <module>
  File "c:\python37\lib\site-packages\mlagents\trainers\learn.py", line 15, in <module>
    from mlagents import tf_utils
  File "c:\python37\lib\site-packages\mlagents\tf_utils\__init__.py", line 1, in <module>
    from mlagents.tf_utils.tf import tf as tf  # noqa
  File "c:\python37\lib\site-packages\mlagents\tf_utils\tf.py", line 3, in <module>
    import tensorflow as tf  # noqa I201
ModuleNotFoundError: No module named 'tensorflow'`

Where my Tensorflow version is 2.0.0 (<2.1, >=1.7) and I'm running 64-bit Python 3.7.3.

**Comment by R-I-S-H-A-B-H-S-I-N-G-H** [comment]
> @ralph367 What version of python are you using? Tensorflow doesn't yet support python3.8 (see [tensorflow/tensorflow#33374](https://github.com/tensorflow/tensorflow/issues/33374)) so if you're using 3.8, you'll need to either downgrade to python 3.7, or wait for them to build new packages.

it worked!!thanks for suggestion
