### ISSUE TITLE
curriculum learning with scenes instead of scripts

### ISSUE THREAD

**Issue by Irekter** [Unity-Technologies/ml-agents#2921]
Hi,

I am working on a curriculum learning for my agents. Right now, each level has a specific mechanic that the agent has to learn. Is there any way to use the a same model to learn in different levels? ie. in different scenes?

**Comment by ervteng** [comment]
Hi @Irekter, we currently don't support switching scenes during training at the moment, as the Academy object is required to communicate with Python and would get destroyed if the scenes are switched. 

There are workarounds, e.g. setting a Don't Destroy On Load for the Academy and instantiating it only on the first scene, but they're not officially supported.

**Comment by Irekter** [comment]
@ervteng So If I train an agent for 10000 steps and have 5 levels, Do I change scenes every 10000/5 levels?

**Comment by ervteng** [comment]
Yes
