### ISSUE TITLE
Problem with dynamically spawned agents in 0.11

### ISSUE THREAD

**Issue by robinerd** [Unity-Technologies/ml-agents#2927]
Hi ML Agents team!
We just upgraded from 0.9 to 0.11 to try out the SAC training for our procedurally generated monsters in Source of Madness (we met at Unite).

While upgrading I realized that since you now automatically pick agents from the scene, our training setup no longer works.
We are training an AI to walk with a randomized body, meaning that we spawn monsters dynamically, and also respawn agents periodically during training. 
When we launch the training we get a message in python that there are 0 brains and it then terminates. How can we approach this problem? I don't mind tweaking the code if needed.

Thanks in advance
Robin
Carry Castle

**Comment by robinerd** [comment]
Possibly two things going on here. Is it expected to show 0 brains learning in the academy, in python console? I'm running another test now in a new project and getting the same, but it proceeds and trains.

It might be that my issue is related to #2844 since we're using both ResetOnDone and OnDemandDecisions. But I can't test right now.

**Comment by ervteng** [comment]
Hey @robinerd, fantastic stuff with the monsters in Source of Madness! I wasn't at Unite but saw some of the demos - really cool. 

We did change the way brains are instantiated in 0.11 - we'll look into this issue (@vincentpierre). If you just want to get SAC running right away, try 0.10.1 - that one doesn't contain the change in brain spawning but does have the latest algorithms. Will keep you posted on what we find.

**Comment by ervteng** [comment]
Hi @robinerd, are you using the latest ML-Agents UnitySDK in the project? We've seen similar issues when the UnitySDK version is from an older release (0.10 and below) and is used with Python 0.11. 

The respawning during training should be no issue as long as the behavior name stays the same. Even with a different behavior name, a new Trainer would be spawned, just as before.

**Comment by robinerd** [comment]
Hi, and thanks! I am using the latest unitysdk folder, but I can double check to remove it and add again tomorrow to make sure I didn't mess anything up while trying to fault find. I did realize today that I forgot to initialize the vector action descriptions array. The thing we do is to add our agent script with AddComponent and then initialize values in the agent parameters script that gets auto-added. All this initialization is done on a game object which is not active, and after that we do SetActive(true). That's to avoid issues with onenable and start being called before initialization is done.

Anyhow, after I fixed that issue I got rid of the error message in unity, and the training seems to start but then immediately i get a crash in python. I will get back to you with logs soon, but it crashes due to a missing key (our behaviour name) in the _brains in environment.py. I added some debug prints in update_brain_params and I see that most of our behaviours are not added to _brains since they have 0 agent infos. I'm a bit unsure of the order stuff gets initialized, maybe we miss some step in the Unity code.
We're using on demand decisions, about 10 times per second from a coroutine.
Sorry if some of the script names above are wrong, I don't have the code in front of me right now.

Maybe @vincentpierre could point us in the right direction of the general approach to spawn an agent and init it, with code. I know we're doing things a bit out of the ordinary :stuck_out_tongue:

**Comment by robinerd** [comment]
So I have been looking into this more now, and I almost got it to work.
I saw that I had done a tweak in the Agent.cs code to get inference mode working so I reverted that and started again:

**First try for inference:**
- disable game object
- Add component MonsterAgent
- Initialize variables in BehaviorParameters and AgentParameters.
- GiveModel("TrainedTentacles")
- enable game object.
Result: Give model crashes since the m_PolicyFactory is still null at that time

**Try two for inference:**
Do GiveModel AFTER enabling the object.
**Result: Inference works!**

Next step: trying to make training work. As soon as I call GiveModel the python fails with KeyError: 'My Behavior' in environment.py, in _get_state. It makes no sense to do give model in the training, but that's the only way to set different behaviour names on different monster types.
So I edited BehaviorParameters.behaviorName to be settable also. Then I can init my agents properly from script.

So in training mode, we set the behaviorName to a dynamic string how we want the model name to be. And in inference we do GiveModel with the actual name of the trained behaviour.
For that logic I had to also extend our academy like this:
```
public class MadnessAcademy : Academy {
    public static bool isTraining = false;
    public override void AcademyReset()
    {
        isTraining = !GetIsInference();
    }
}
```

It also works with respawning agents as @ervteng pointed out. However since we use multiple behaviours and randomize enemies, we might have agent behaviours disappearing or being added to the scene as we train, based on randomness. This causes the same KeyError in python code as mentioned above.
It is possible though for us to know all agent behavior names at start, but I'm not sure what to do with that information. I suppose we need to keep all the brains active in some way even when they're not in the scene. Maybe we could make sure to always have at least one monster of each behaviour name. Is there any better way?

**Comment by ervteng** [comment]
> Anyhow, after I fixed that issue I got rid of the error message in unity, and the training seems to start but then immediately i get a crash in python. I will get back to you with logs soon, but it crashes due to a missing key (our behaviour name) in the _brains in environment.py. I added some debug prints in update_brain_params and I see that most of our behaviours are not added to _brains since they have 0 agent infos. I'm a bit unsure of the order stuff gets initialized, maybe we miss some step in the Unity code.

@robinerd I think I know what's going on here - is it correct that when the environment starts up there might not be any Agents in the scene? The way the code is written currently, it assumes there is at least one Agent in the scene at startup, otherwise it won't spawn the right trainers on the python side. Adding new Agents with new behavior names should be no problem once the first one is initialized. So the quick workaround might be to have an agent with some dummy behavior name in the scene (not dynamically instantiated). If this works, we can fix the problem in the Python code pretty easily and push a patch.

**Comment by robinerd** [comment]
Hi @ervteng and thanks for the suggestion! Yes we have no agents in the scene at start. Right now it works like 50% of the time while sometimes I get the KeyError at start. So I suppose it depends a bit on the timing of whether an agent had time to run a step first.
I will give it a try with a dummy agent and get back to you :+1:

**Comment by robinerd** [comment]
I tried putting a dummy agent in the scene, always there. With 1 observation and 1 action.
My problem is still happening. Python gives KeyError sometimes when I start to train, but it's about 1 out of 3 times so I just restart.

**Comment by robinerd** [comment]
I finally figured out the reason!
The problem happens when an agent is added to the scene but doesn't request any decisions at start. Our agents use on demand decisions, and a coroutine that requests decisions several times per second.
When the error happens, the python environment doesn't even print out the hyper parameters. It crashes before that with a "KeyError [my-behavior-name]". I suspect that python gets notified about the behavior and then it starts to use it in some way before there is any data. As said above the crash happens in environment.py, in _get_state.

I hope this is something you could be able to reproduce, and perhaps handle in a better way somehow.

**Comment by ervteng** [comment]
Hey @robinerd, glad you figured it out! This seems to be related to the fact that the code expects a decision on the first step. We'll look into fixing it - it should be fixable on the Python side. I've logged the issue with internal reference MLA-392.

**Comment by robinerd** [comment]
@ervteng thanks for the reply! I'm closing this issue then since you have added internal tracking and I can work around the problem
