### ISSUE TITLE
Want to be able to specify which brains to train, as of 0.11

### ISSUE THREAD

**Issue by robinerd** [Unity-Technologies/ml-agents#2928]
In our game Source of Madness we are using ML agents to train our monsters, with reinforcement learning.

We are now looking into the possibility to also train an agent that plays the main character, using imitation learning. This could help us out with some basic QA and testing.
As of 0.11, we can not train the player agent while having inference for the monsters.
Training everything at the same time is not an option as it takes a long time for monsters to learn.

I saw a code change work-around mentioned in another thread, but I would like to request this as a feature also. Training everything in the scene is still a good default and I like how the framework is easier to use now. Maybe a way to override which "brains" to include in the training would work. That could possibly also solve my issues in #2927.

Thanks!
Robin
Carry Castle

**Comment by mbaske** [comment]
> I saw a code change work-around mentioned in another thread, but I would like to request this as a feature also.

Hi @robinerd, the code change you're referring to is actually really minor. I've created a gist here 
https://gist.github.com/mbaske/64a0e261f02aa7daff459cc1afef0198

**Comment by robinerd** [comment]
Hi, Thanks for that! I will give it a try, should be enough for now.

**Comment by PinataMostGrim** [comment]
This was a feature I also used in previous versions of the MLAgents toolkit and would like to second the request for it to return as an official feature.

**Comment by chriselion** [comment]
@mbaske Just a heads up that we changed the "Use Heuristic" bool to an enum in 0.12.0, which is equivalent to your change. Going to close this.
