### ISSUE TITLE
Does encoding_size of Curiosity Reward Signal must be smaller than observation size?

### ISSUE THREAD

**Issue by BAXMAY** [Unity-Technologies/ml-agents#2930]
From the reward signal's doc, the default value of encoding_size of curiosity reward is 64. 

But, my environment collect vector observation of size 20 so I'm curious that the encoding_size should be smaller than observation size or not?

**Comment by ervteng** [comment]
It's OK for curiosity encoding size to be bigger than observation size. It corresponds to the complexity of information encoded by the curiosity module, not necessarily the dimension.
