### ISSUE TITLE
The communicator was unnable to connect

### ISSUE THREAD

**Issue by watarigasu** [Unity-Technologies/ml-agents#2934]
I have searched in all of the github issues pages, reset my proxy http and https. I have reinstalled anaconda and made sure python was 3.6 and tensorflow was compatible. I have checked my control box in academy and yet it still shows this error, even with the example packages. 
![image](https://user-images.githubusercontent.com/57238559/69159036-3916c600-0adf-11ea-972b-0e5c4c2ce23b.png)

**Comment by ervteng** [comment]
Hi @watarigasu, can you share your ML-Agents SDK version (the UnitySDK folder) and your Python version?

**Comment by watarigasu** [comment]
> Hi @watarigasu, can you share your ML-Agents SDK version (the UnitySDK folder) and your Python version? If you're using the latest 0.11 Python code you'll have to update the UnitySDK folder.

ITS OKAY but thank you 
I uninstalled and updated from version 0.6.0 to 0.10.0. 
I went through mountains of hell to install CUDA and the right grpc files and finally am working something. but thank you so much @ervteng
