### ISSUE TITLE
Record agent observations and actions in a different file format and then convert to .demo files

### ISSUE THREAD

**Issue by gauravspatil** [Unity-Technologies/ml-agents#2938]
Hello,
Is there any way to convert, let's say, .csv file into a .demo file? 
I want to record the observations, actions, and rewards in a different file format so that I can tune my human(teacher) player controls to make them more playable but then convert them into actions that the neural network would learn.
Or, it will also help if the agent can be controlled outside of the control options in the playerBrain while still recording the actions in the .demo file.
Thanks!

**Comment by chriselion** [comment]
Hi @gauravspatil,
We don't provide any utilities for this. But the demo file format is pretty simple, it contains
1) A DemonstrationMetaProto protobuf message.
2) A BrainParametersProto protobuf message.
3) A sequence of `AgentInfoProto` protobuf messages.
There are a few other details like padding after the DemonstrationMetaProto and encoded size before each of the protos.

I was recently writing some demo files in python and wrote a small utility that handles the extra details; here's the relevant part:
https://gist.github.com/chriselion/3714d05255eea2f9132b96a182fbdcaa#file-convert_demo-py-L101-L115
(you can ignore more of the rest of the file)

So if you're comfortable forming the protobuf objects, that should be enough to get you going.

**Comment by gauravspatil** [comment]
Thanks @chriselion. I just started looking into protobuf and will see if I can figure it out. 
Can you provide an example of how the data string will look like before getting encoded by protobuf?
Also, Is the .demo file just a binary file created from the protobuf encoding?

**Comment by chriselion** [comment]
You shouldn't need to work with the data string directly. You can create DemonstrationMetaProto, BrainParametersProto, and AgentInfoProto objects and pass them to the code that I linked to above. The imports for them are at the top of the file: https://gist.github.com/chriselion/3714d05255eea2f9132b96a182fbdcaa#file-convert_demo-py-L12-L16

Yes, the .demo file is just a binary file with protobuf messages in it.
