### ISSUE TITLE
URGENT: Brains Missing under Hierarchy and Project tab

### ISSUE THREAD

**Issue by Bhairevi** [Unity-Technologies/ml-agents#2939]
I am new to Unity and have installed it on my laptop. I am currently using 2017.4.34 version of Unity. 
I have clearly followed the documentation for installation given on the github page and whenever I start Unity I can't see Brains under Hierarchy and Project tab(check the screenshots below). Furthermore, while training from the command line it shows number of Brains as 0. I haven't installed CUDA  and I am currently using RTX2060 as GPU. Can't seem to get around it. Please help.

**Environment **
- Windows 10
- _ML-Agents version_: ML-Agents Beta 0.11.0
- _TensorFlow version_: 1.15.0
- _Environment_: 3D Ball and every other example
![Screenshot_1](https://user-images.githubusercontent.com/54612505/69214753-c284d180-0b8d-11ea-96ce-acc19cef8ed3.png)
![Screenshot_2](https://user-images.githubusercontent.com/54612505/69214755-c284d180-0b8d-11ea-986b-f619c0518e2b.png)

**Comment by Smileynator** [comment]
In a recent version, "brain" files were removed. Instead you now add an extra script to an agent, to give ot the previous "brain" settings, also check your academy setting to see if you are actually training, or just going from a NN file

**Comment by himanshi4693** [comment]
@Smileynator : any ideas on how to train a simulation with my own learning algorithm, using the mlagents env API on jupyter notebook? Details here : https://github.com/Unity-Technologies/ml-agents/issues/2940
