### ISSUE TITLE
Working with Behavior Parameters for training Unity simulation with own learning algorithm 

### ISSUE THREAD

**Issue by himanshi4693** [Unity-Technologies/ml-agents#2940]
I'm working with the latest version of ML-Agents, on an existing Unity simulation which has behavior parameters set up. There is no longer an entity named 'Brain' but the brain parameters are defined in this BehaviorParametersEditor.cs. I'm able to train in editor using the mlagents-learn command. However, I want to train with my own algorithm implementation, so I'm trying to interact with the environment build on jupyter notebook. When I try printing the environment information, I get the following:

![Screenshot_2](https://user-images.githubusercontent.com/38923623/69238391-28765680-0b98-11ea-90c1-d16c95c53018.png)

Any idea on how to proceed with training? Thank you in advance

**Comment by wengzehang** [comment]
Also get this problem ...

**Comment by chriselion** [comment]
Hi,
The "Number of Training Brains" log was misleading, and was cleaned up in the 0.12.0 release. Closing this issue.
