### ISSUE TITLE
Visual Observation + Demo Recorder, still uses camera in scene

### ISSUE THREAD

**Issue by robinerd** [Unity-Technologies/ml-agents#2944]
**Describe the bug**
While training with offline behavioral cloning and a CameraSensor, the agent seems to use the camera in scene rather than the camera data from the demo file.
Could be that I'm using it wrong, I would love any pointers/help you may have :)

**To Reproduce**
1. Create an agent with a visual observation
    (I also had some vector observation from heuristic script, not relevant)
2. Play the scene to record demo file.
3. Start training the agent with the demo file.
4. Test to move around the camera in the scene while training.
**Expected:** Agent keeps learning independently of the manual camera movement.
**Actual**: Agent actions are directly affected by how I move the camera in the scene, and learns poorly/not at all.

**Environment (please complete the following information):**
- OS + version: Windows 10
- _ML-Agents version_: 0.11.0
- _TensorFlow version_: 1.7.1
- _Environment_: Custom Project

Maybe I am just using this in the wrong way. If you think this might be an actual bug though, I will try reproducing this in an example environment instead.

**Comment by dylansc** [comment]
Moving the camera around during training will impact agent actions based on the policy learned from the demo files. This will not impact model training since the only interaction between the environment and model during behavioral cloning is for inference.

**Comment by robinerd** [comment]
Aha then it makes sense, I have maybe just misunderstood the offline behavior cloning. From reading the documentation I didn't realize that it is also running inference at the same time as it is learning. Do I still need to have my agent in the scene? Thank you very much for your clarification!

**Comment by robinerd** [comment]
We can close this issue now. Based on your reply in the other thread I got my question answered.
