### ISSUE TITLE
Instructions are inadequate

### ISSUE THREAD

**Issue by CarlBinneman** [Unity-Technologies/ml-agents#2947]
I had incredible difficulty setting up an environment for the ml agents, being new to Python (I have done C# and Unity stuff for around a decade)
For example, non python scripters don't know to not include $ at the start of quoted code.
They may also not know that this is all done via cmd with admin privileges.
They may want to know that where you have said python3, the only working input is python.
They may also be stuck at the beginning because they used the latest python, not the latest version of 3.6

**Here are the instructions as I was required to follow instead :** 

Get Python on Windows ;
1. Install 64 bit version of 3.6.8 WITH path variables (take note where it installs to or set it yourself)
2. Restart your computer
3. **Run CMD as Admin. use cd to change the directory to your python36 folder**
Step 3 needs to happen once before you use any of the commands below

Get pip
1. Download the get-pip.py file: `curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`
2. Run the following: `get-pip.py`
3. Check pip version using: `pip3 -V`

Set up the virtual environment:
1.    `md python-envs`
2.    `python -m venv python-envs\sample-env`
3.    `python-envs\sample-env\Scripts\activate`
4.    `pip3 install --upgrade pip`
5.    `pip3 install mlagents`
6.    `deactivate`

**Comment by DVonk** [comment]
I already talked about this in other posts, but I agree with this so much. The Windows instructions especially feel like nobody even tested them before release. I think this issue should have the highest priority out of anything right now.

**Comment by unityjeffrey** [comment]
Hi @CarlBinneman @DVonk thank you for your feedback. Apologies that you are having issues, we recognize that the instructions are unclear for new python users. We are in process of making sure Conda is properly tested as part of our releases, put those instructions back for Anaconda + Win, and improve the venv instructions  . For now - refer to the previous Installation instructions for Windows https://github.com/Unity-Technologies/ml-agents/blob/0.10.1/docs/Installation-Windows.md

**Comment by CarlBinneman** [comment]
So, to be clear : 
The instructions that I posted as working, are not the correct way.
One must follow the instructions provided in your link relating top Anaconda.

Is the above correct? @unityjeffrey

**Comment by unityjeffrey** [comment]
Hi @CarlBinneman - i haven't tried your instructions, but known @anupambhatnagar is working to update them with clearer instructions.  a user doesn't necessarily need to use venvs or conda, but it makes it easier if you have multiple python projects locally.

@anupambhatnagar see insntructiosn above from Carl

**Comment by CarlBinneman** [comment]
Thanks, I will be using venvs but am tempted to try conda. Not sure which is less of a pain.
Was just curious as to whether I would see issues down the line with current method of setup.

Not to worry, I will await the updated instructions. Many thanks to all involved

**Comment by anupambhatnagar** [comment]
@CarlBinneman Thanks for the feedback. We assume that installing python3 is responsibility of the user. There is clear documentation on python.org for installing python3, hence we do not provide documentation towards that end.

Secondly, the user may have multiple versions of python installed on the work environment. E.g. python 2.7 and python 3.6. In this case the usual alias for python 2.7 and python3.6 are `python` and `python3` respectively. Since you installed Python on your system for the first time the system set `python` as an alias for Python3 in your case. We will update the docs keeping this use case in mind.

Lastly, venv is the recommended way for the following reasons:
- It works on all platforms i.e. Mac, Linux, Windows
- It supports maintaining multiple python environments for projects
- Since its already included in Python3, it is fairly straightforward to setup

**Comment by CarlBinneman** [comment]
Thanks. Let me know when it's up top date.

P.S : I find it hilarious that Python is so commonly used for its ease in actual script creation, yet most interfaces rely on cmd/terminal at some point.  It's literally just a bunch of numbers for setup and a text interpreter if one must have python. Probably a 600 line unity editor script. This would bring a lot more usage of ML in the general community.
