### ISSUE TITLE
gridworld renderCamera question

### ISSUE THREAD

**Issue by MarkTension** [Unity-Technologies/ml-agents#2953]
Hi all,

I'm using Gridworld as an example to make my own environment. I've got a question about the Agent's visual observation input. The agent as a gameObject receives a Render Texture Component (Script) in the inspector, where the renderTexture can be assigned.

However, in the GridworldAgent.cs code, it also receives a 
`public Camera renderCamera;
`
This is not referring to the RenderTexture is it? Because when viewed from the inspector, no camera is assigned to it. Why is nothing assigned to it?

Additionally, how destructive for the agent will it be without the this 

public Camera renderCamera; 
, and the inference time waiting part of the script?

Thanks!

**Comment by chriselion** [comment]
Hi @MarkTension ,
There are actually two types of Agents in the scene:
* the one under the AreaRenderTexture uses a Render Texture Sensor Component. This agent has its Camera's TargetTexture set to the RenderTexture that the sensor uses.
![image](https://user-images.githubusercontent.com/6877802/69447582-a9a22a80-0d0b-11ea-9267-fe0d68a102ad.png)
* the Agents in Area, Area (1), etc. are configured from the prefab and use a Camera Sensor Component. These agents don't have GridAgent.renderCamera set.
![image](https://user-images.githubusercontent.com/6877802/69447687-de15e680-0d0b-11ea-9a2a-64e3311415ab.png)

I'm not sure about the relative performance of these two approaches; I believe the Camera -> RenderTexture approach is mainly to show an example of how a RenderTexture can be used (and also for display in the scene).

> Additionally, how destructive for the agent will it be without the this

It's fine for most of the agents, but would break the Agent using the RenderTexture

**Comment by MarkTension** [comment]
Thank you for pointing that out. Makes sense.
