### ISSUE TITLE
Unstable training 

### ISSUE THREAD

**Issue by ralph367** [Unity-Technologies/ml-agents#2963]
Hello, well I'm having an unstable training, I just have a sphere in the space that most pass through walls with a window in order to reach a target in the end. 
Here is the training's result http://puu.sh/EIxDo/2b3de36ae7.png
As you can see it is varying too much and in my code when the ball reach the target SetReward(1f); when it hits a wall AddReward( - distanceToTarget / 50f ); and finally when the ball leaves the limits 
 AddReward( - distanceToTarget / 100f );
It is like, the ball reaches the target for 2 3 times then on the 4th time it never finds the windows just keeps on moving in the same position without then due to the max steps it resets and soo on, sometimes it hits a wall or leaves the limit

**Comment by robinerd** [comment]
Since you give rewards very seldom ("sparse rewards") the agent will take long time to learn and might never find its way unless you use certain things like curiosity and long batches.

For this case I don't think you need any of that though.

I would recommend trying to have a more continuous reward function to let the agent know all the time if it gets better or worse.
Try to do a small punishment every frame which is based on how far away from the correct direction it is. Maybe something like

AddReward(-distance_to_next_window * 0.01f)

Also try to add a reward for getting through a window successfully.

Also, do you restart the agent if it hits a wall? Or what happens?

**Comment by ralph367** [comment]
Yea when the ball hits the wall or leave the limit everything resets ( wall/target position )
Do you think that Rayperception distance might affect the training ? I mean like should it be larger or smaller ?

**Comment by robinerd** [comment]
Can you tell a bit more about how the agent observes its world? The agent needs to have enough data about the environment to understand which direction the window is. Maybe you could give the agent the vector between itself and the next window, unless you consider that "cheating".

**Comment by ralph367** [comment]
Yea sure I will show you my code 
`
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using MLAgents;

public class SpaceAgent : Agent{
    public Transform Target;
    public Transform Ball; 
    public GameObject wall_prefab;
    public int wall_Count = 1;
    public float wall_distance = 5f;
    public float wall_random = 2f;

    const float rayDistance = 1.5f;
    string[] detectableObjects = {  "wall" };

    private RayPerception ray;
    private Rigidbody r;

    private List<Transform> walls;


    float[] rayAngles = { 20f-90f, 90f-90f, 160f-90f, 45f-90f, 135f-90f, 70f-90f, 110f-90f };

    void Awake(){
        walls = new List<Transform>();
        for(int i = 1 ; i <= wall_Count; i++){
            GameObject go = Instantiate(wall_prefab);
            walls.Add(go.transform);
        }
    }

    public override void InitializeAgent(){
        base.InitializeAgent();
        r = GetComponent<Rigidbody>();
        ray = GetComponent<RayPerception>();
    }

    public override void AgentReset(){

        for(int i = 1 ; i <= wall_Count; i++){
            walls[i - 1].position = new Vector3(i * wall_distance ,  Random.Range(-wall_random,wall_random) , Random.Range(-wall_random,wall_random) );
        }
        Target.position = new Vector3(29.5f,  Random.Range(-wall_random,wall_random) , Random.Range(-wall_random,wall_random) );
        Ball.position = new Vector3(0.6f,  0f, 0f);
    }

    public override void CollectObservations(){
        AddVectorObs(ray.Perceive(rayDistance, rayAngles, detectableObjects, 0f, 0f));
        AddVectorObs(ray.Perceive(rayDistance, rayAngles, detectableObjects, 0f, 1f));
        AddVectorObs(ray.Perceive(rayDistance, rayAngles, detectableObjects, 0f, -1f));
        AddVectorObs(Target.position);
        AddVectorObs(this.transform.position);
    }

    public override void AgentAction(float[] vectorAction, string textAction){
        Vector3 controlSignal = Vector3.zero;
        controlSignal.x = vectorAction[0];
        controlSignal.y = vectorAction[1];
        controlSignal.z = vectorAction[2];
        controlSignal.Normalize();
        controlSignal *= Time.deltaTime;
        transform.Translate(controlSignal);
    }
    
    public override float[] Heuristic(){
        var action = new float[3];
        action[0] = Input.GetAxis("Horizontal");
        action[1] = Input.GetAxis("Vertical");
        action[2] = Input.GetAxis("Zaxis");
        return action;
    }

    private void OnCollisionEnter(Collision collision){
        float distanceToTarget = Vector3.Distance(transform.position, Target.position);
        if (collision.gameObject.CompareTag("target")){
            SetReward(1f);
            Done();
        }
        if (collision.gameObject.CompareTag("wall")){
            AddReward( - distanceToTarget / 50f );
            Done();
        }
    }

    private void OnTriggerExit(Collider col){
        if ( col.gameObject.CompareTag("block")){
            float distanceToTarget = Vector3.Distance(transform.position, Target.position);
            AddReward( - distanceToTarget / 100f );
            Done();
        }
    }
}


`

**Comment by robinerd** [comment]
Okay so what I can suggest based on that is to 1. Make sure the agent has enough detailed understanding of the world with its observations. Think of it like, based on that data, does the agent have any possibility to figure out where the window is? What happens if the ray observations don't hit the window for a while?
If that is alright consider trying my previous suggestions for the improved rewards
