### ISSUE TITLE
Multienvironment training in the editor is too slow

### ISSUE THREAD

**Issue by rajatpaliwal** [Unity-Technologies/ml-agents#2967]
I am running 10 identical environments in the unity editor to speed up the training process. But, instead of speeding up the steps are being updates very slowly and agents are also moving with a slower speed then expected. Is this something usual or if I am missing anything to speed up my process kindly advise.

Edit : 3000 steps in the command prompt window are being updates in 762 secs.

**Comment by unityjeffrey** [comment]
hi @rajatpaliwal - have you tried to create a build of the unity game, and run the training via the command line instead?  You could also use --num-envs=N to see if that helps as well.

**Comment by rajatpaliwal** [comment]
Hi @unityjeffrey  . I tried by creating multiple environment in the scene, but it resulted in very slow training. I will try by creating a build of the unity game . 
Is creating multiple environment in the scene is not advised?
