### ISSUE TITLE
Delay/Laggy when using 1024 Width and 576 Height as Observation Resolution size.

### ISSUE THREAD

**Issue by Lakrix** [Unity-Technologies/ml-agents#297]
Hi, 

During training my screen keeps lagging when using a larger width and height for my camera resolution. Right now I'm using a resolution of 1024 Width and 576 Height. If I change my resolution to a smaller one like 64x64 everything works as expected. 

Anyone else having this problem?

**Comment by MarcoMeter** [comment]
Hi @Lakrix 
your desired resolution sounds way too high in my opinion.

**Comment by kwea123** [comment]
Yes I also experienced this problem. The maximum size I use without lagging is 300x200 FYI

**Comment by Lakrix** [comment]
@MarcoMeter I do agree with you. Im investigating if my reward differs when adjusting the size of the observation.

I also found a bug in ppo->trainer. On line 126:

for i in range(self.info.observations):

the trainer dosent contain any info variable.

**Comment by bschantz** [comment]
The bug in ppo/trainer.py is fixed in #340

**Comment by puneets2811** [comment]
Hey,

How Do i set the resolution while training  ? 
3D ball example is running at a convenient resolution but the application i built is running at very small resolution as small as a Icon file .

 Thanks

**Comment by MarcoMeter** [comment]
Hi @puneets2811 
I believe your question is off-topic.
You might want to check the settings of your Academy GameObject.

**Comment by awjuliani** [comment]
The current bottleneck is the communication protocol we are using. We are currently looking into this to expand this in order to enable using larger images more effectively.
