### ISSUE TITLE
Replacement of PlayerBrain for imitation and testing

### ISSUE THREAD

**Issue by AdhamAlHarazi** [Unity-Technologies/ml-agents#2971]
- Prior to 0.11, I enjoyed the capability of the "player brain" to test the implementation (by mapping keys to action) and also to record demonstrations for imitation. Now there is no player brain anymore only the "Behavior Parameters" component, which acts as a learning brain. Therefore, my question is: what is the replacement of the player brain for imitation and testing purposes?

- Also, the decision class, with its decide function, is removed, and I was using it for heuristics so I can record demonstrations. So, what is the replacement for that also?

**Comment by dylansc** [comment]
Regarding your first question, to control the agent yourself, just set the Model field under behavior parameters to none.

**Comment by AdhamAlHarazi** [comment]
@dylansc Thank you for your reply. The model field is already set to None. However, I cannot control the agent. it gives the following error:-

`UnityAgentsException: The Heuristic method was not implemented for the Agent`

 Also, where to map actions to keys?

**Comment by dylansc** [comment]
Have you defined the Heuristic() method in your agent class? Ctrl-f heuristic() in [this doc](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design-Agents.md) for more details.

**Comment by AdhamAlHarazi** [comment]
@dylansc Thank you. I have defined the Heuristic() method and mapped keys to actions, and everything is working as expected. Also, this method answers my second question as well.
Thank you again. 

Unity should add such changes in the migrating guide.
