### ISSUE TITLE
Always use heuristic whether choose "use Heuristic" check box

### ISSUE THREAD

**Issue by D-Hsueh** [Unity-Technologies/ml-agents#2972]
When i import 'ML-Agents' file into my project and migrate my project into 0.11 version, i run this python script and click the play button, but it seems like my unity editor cannot communicate with my python script.

```
from mlagents.envs.environment import UnityEnvironment
env = UnityEnvironment(file_name=None, worker_id=0, seed=1)
info = env.reset()
```

And then i found that whether i choose "use Heuristic" check box, my agent always action by my "heuristic" action.

By the way, i think this message may be helpful to find out my problem's solution, but i can't understand it.

> Assets\ML-Agents\Scripts\Policy\BehaviorParameters.cs(19,57): warning CS0649: Field 'BehaviorParameters.m_UseHeuristic' is never assigned to, and will always have its default value false

I alerady update my unitySDK and mlagents to 0.11

**Comment by MarkTension** [comment]
Hi there! I had the same problem, and for me it was because I didn't set a brain yet. 
If you don't set a brain in the agent's Behavior parameters, ml-agents will always use Heuristics. 
This is only the case when you're running it in play mode.
Hope that helps

**Comment by D-Hsueh** [comment]
> Hi there! I had the same problem, and for me it was because I didn't set a brain yet.
> If you don't set a brain in the agent's Behavior parameters, ml-agents will always use Heuristics.
> This is only the case when you're running it in play mode.
> Hope that helps

But in 0.11 version, i don't know how to set a brain, my Begavior parameters inspector is like this

![捕获](https://user-images.githubusercontent.com/16350176/69688882-48f76100-1102-11ea-97be-6da39e2c5ccc.PNG)

the only one thing that i think is related to brain is 'Behavior Name', but it doesn't work.

**Comment by MarkTension** [comment]
You can put the brain .nn file in Model

**Comment by D-Hsueh** [comment]
> You can put the brain .nn file in Model
> See # 3 of [this guide in the docs](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Basic-Guide.md#running-a-pre-trained-model)

Thank you very much for your reply, I solved the problem with your method.
