### ISSUE TITLE
Help with rendering 3D Balance Ball in notebook?

### ISSUE THREAD

**Issue by alexisbcook** [Unity-Technologies/ml-agents#298]
Currently setting up the 3D Balance Ball environment and testing the API with the `python/Basics` Jupyter notebook.  The instructions are incredibly clear - thank you!

All cells run without error (giving expected output - so I see `'Ball3DAcademy' started successfully!` (along with some statistics about the environment), the total reward from different episodes, etc), with the exception of the visualization of the environment.

The visualization pops up in a very small window outside of the notebook.  It's too small to see anything, but it appears that it's stuck on a still frame that does not respond to the commands in Step 5 of the notebook.  It does close with `env.close()` at the end of the notebook.  Any tips to fix?

**Comment by MarcoMeter** [comment]
Hi @alexisbcook 

the behavior which you describe is completely normal. The environment is supposed to run as fast as possible and is controlled by the python program. Thus the Unity instance gets unresponsive.

To get a bigger window, you can change the resolution in the training settings of the Academy. There is a training and an inference mode. The inference mode is selected if the model is out to action and not training.

**Comment by alexisbcook** [comment]
Ah yes, I see - makes sense, and thanks for the quick response!  Setting to inference mode does yield the nice visualization.

**Comment by tomitrescak** [comment]
Sorry to act on a closed call, but what do you mean by:

> The inference mode is selected if the model is out to action and not training.

Why does inference mode even exist? Can it adapt to current player settings? I am just not clear on the inference mode, I got the preview running just fine.
