### ISSUE TITLE
No improvement in training and is very unstable

### ISSUE THREAD

**Issue by rajatpaliwal** [Unity-Technologies/ml-agents#2980]
Hello all,
I need help in improving my training. I am trying to train an agent that can move in  an environment(like a tunnel which has an upward slope, downward slope and straight path). I want my agent to reach to the end of the tunnel while maintaining the proper orientation according to the slope in the tunnel and without colliding with the walls of the tunnel. 
I have placed a cube at the end of the tunnel as the final target. I have also provided 16 mini-targets in the tunnel which provides the positive reward for the agent reaching those positions with the correct orientations.  
Observations provided are --
1). Mini-target positions.
2). Mini-target orientations.
3). Target position.
4). Agent position
5). Agent Direction
6). Vector directing the agent current position to the target position.

Actions provided are --
All the actions provided are discrete . Total 5 actions are provided : go forward, rotate up, rotate down, rotate left, rotate right.

Rewards provided:
1). Reward for moving toward target(i.e. at the end of the tunnel).
m_DirToTarget = target.position - this.gameObject.transform.position;
m_movingTowardsTarget = Vector3.Dot(agent.velocity, m_DirToTarget.normalized);
SetReward(0.003f*m_movingTowardsTarget);

2). Reward for agent facing the target.
m_FacingTarget = Vector3.Dot(m_DirToTarget.normalized, this.gameObject.transform.up);
        SetReward(0.001f * m_FacingTarget);
3). Time penalty
SetReward(-1f / agentParameters.maxStep);
maxStep = 700,000

4). Reward for reaching the mini-target position with the required orientation.
SetReward(0.8f);

5). Negative reward for reaching the min-Target position now with the required orientation.
SetReward(-0.5f);

6). Negative reward for colliding with the walls of the tunnel.
SetReward(-0.8f);

7). Negative reward for reaching the final target.
SetReward(1.0f);

I tried with PPO and the training results were as follows(Max steps : 700000):
(https://user-images.githubusercontent.com/30369775/69670050-e2ae0800-1047-11ea-8ecd-18e806a36b2e.PNG)
Clearly the training was very unstable and reward also did not improved much.

In the next training iteration I tried PPO+Curiosity and the training results were as follows (Max Steps : 800000)
![RL_ExpertLearning BrainJ](https://user-images.githubusercontent.com/30369775/69673076-5fdc7b80-104e-11ea-9617-0faaee94a937.PNG)
![RLExpertLearning Brain J 1](https://user-images.githubusercontent.com/30369775/69673087-65d25c80-104e-11ea-89a1-d660ea934e74.PNG)

It got even worse with curiosity enabled. Currently, I am trying different combinations but I don't have any concrete clue about what is making my training unstable and how can I improve the performance.
Any suggestions will be helpful.
Thanks in advance.

**Comment by mattinjersey** [comment]
I found better results when I provided the ML with images rather than coordinates.

**Comment by rajatpaliwal** [comment]
Hi @mattinjersey . Thanks for replying.
I think what you mean is providing visual observation instead of vector observation. I did not went with that approach as it was mentioned in the documentation that visual observations are not much effective and takes much more longer time to train.
Was your ML problem similar to mine , and does using visual observations improved your performance.

**Comment by mattinjersey** [comment]
Well I tried a Space Invaders game with many invaders. It did not train well with Vector Observation, and it trained quite well with Visual Observation. I think its worth a shot... it is not too difficult to implement. Generate a low-resolution of the scene so that the datasize is not too big.

**Comment by rajatpaliwal** [comment]
Sure, will definitely give it a try. Just a query , did you use single environment or multiple environment in a single scene and what were the maximum number of steps you chose for your problem.

**Comment by mattinjersey** [comment]
I used single environment. Max num Steps didn't seem critical but I did force the game to end after 1 minute, in Unity.
My code is on GitHub if you are interested. Also there I made a video, its in the GitHub readme.
https://github.com/mattinjersey/laserDefenser_ML

**Comment by rajatpaliwal** [comment]
Thanks for sharing . Awesome work and explanation in the video. I will try visual observation in my project and will update you on the result.

**Comment by mattinjersey** [comment]
Great, good luck! Also note the time horizon which I note in the video may be an important hyperparameter. 


Sent from Yahoo Mail for iPhone


On Tuesday, November 26, 2019, 5:31 PM, Rajat Paliwal <notifications@github.com> wrote:


Thanks for sharing . Awesome work and explanation in the video. I will try visual observation in my project and will update you on the result.

**Comment by rajatpaliwal** [comment]
Hi @mattinjersey ,
I tried a combination of visual+vector observation . I provided one visual observation. But the training results were not much great. Would you suggest just doing training with visual observation?

**Comment by mattinjersey** [comment]
Is all the necessary information for the agent present in each visual observation? For example are the mini targets visible?

**Comment by rajatpaliwal** [comment]
No the mini targets were just the position vectors in the list. They were not visible in the scene. The final target at the end of tunnel is visible. 
Also, is there a way to debug what visual observation is being sent to the brain?

**Comment by mattinjersey** [comment]
I am not sure how to debug it but I did display the image in Visual Studio, so I could see it. 
Anyways I can't really know how to solve your problem. If you post some images or post the code on GitHub that could help to give more information.

**Comment by rajatpaliwal** [comment]
Due to proprietary issues I can't share code or images of the environment. But I wonder how did you displayed the images in Visual Studio.

**Comment by mattinjersey** [comment]
I forget the exact command but in unity you can create a view to show an image.


Sent from Yahoo Mail for iPhone


On Thursday, November 28, 2019, 6:05 PM, Rajat Paliwal <notifications@github.com> wrote:


Due to proprietary issues I can't share code or images of the environment. But I wonder how did you displayed the images in Visual Studio.
