### ISSUE TITLE
Mlagents-learn train not seeing unity project

### ISSUE THREAD

**Issue by Tikoshido** [Unity-Technologies/ml-agents#2981]
Hello everyone,
I am trying to write my own game using ml-agents for AI and I obviously want to train it, but when I try to I see only this:
![obraz](https://user-images.githubusercontent.com/31181594/69674252-6265c200-109c-11ea-9702-3875fe37a1b4.png)
I tried to run 3dBall example project and everything is running fine when I train it. I did everything according to basic guide in documentation of ml-agents and I don't know what am I doing wrong. I have ML-Agents assets imported into my project some simple code for Agent and empty Academy.

Okay, so this is my project structure.
![obraz](https://user-images.githubusercontent.com/31181594/69749006-db6f2300-1149-11ea-8a47-91c7f4924dd5.png)
Where Player has the Agent script:
![obraz](https://user-images.githubusercontent.com/31181594/69749073-f93c8800-1149-11ea-9823-1590ac34d40c.png)
This is my Academy Class:
![obraz](https://user-images.githubusercontent.com/31181594/69749148-2721cc80-114a-11ea-9668-73630f8d8e70.png)
And Agent Class:
![obraz](https://user-images.githubusercontent.com/31181594/69749204-44ef3180-114a-11ea-8d27-cf036fd6ae49.png)

Any help would be appreciated :)
Thanks in advance

**Comment by unityjeffrey** [comment]
hi @Tikoshido - i think for folks in the community to help, we would need to see details on how you have implemented the academy and agents.  it's hard to debug on just on the command line alone

**Comment by robinerd** [comment]
Are you training inside of unity editor or build? They have changed how you train in a build.

Could you provide a screenshot of your settings on the GlobalAcademy component?
Did you remember to add your academy in the scene you're running?

Which unity version are you using?

**Comment by Tikoshido** [comment]
I am training inside unity editor.
![obraz](https://user-images.githubusercontent.com/31181594/69911462-1e681980-141c-11ea-8ea1-0764ceef5312.png)
Yes the Academy is in the same scene in which I try to train.
And the version of unity is: Unity 2019.2.14f1 (64-bit)

Actually I copied my whole project to UnitySDK project, and it works, actually it "connected" even without any agents on. But it is not working if I have another project. I am missing something for sure.

**Comment by robinerd** [comment]
Strange.. I wonder if it's still needed to have the ENABLE_TENSORFLOW in script defines? In the build settings. I thought it is not used any more but that's one thing that might differ

**Comment by unityjeffrey** [comment]
seems like a few issues on this.  will take a look

**Comment by unityjeffrey** [comment]
hi - we think the problem is that we switched the port for training in 0.11.  And if you had a version mismatch between the C# SDK and Python, it would never hit the error because of the port change.

Can you make sure both the C# code and Python code is updated using the same version and see if that fixes your issue?
