### ISSUE TITLE
Team-Based AI

### ISSUE THREAD

**Issue by Taikatou** [Unity-Technologies/ml-agents#2983]
What recommendations would people have for team AI

I want to develop AI for a team-based asymmetric shooter (think Overwatch) Is there any algorithm or adjustment to PPO or soft critic that would facilitate communication and strategy.

Thank you for the Help 😄

**Comment by unityjeffrey** [comment]
hi @Taikatou - we are currently working on more multi-agent.  However, you can check out Arena (uses ML-Agents from a team at Oxford).  https://sites.google.com/view/arena-unity/home?authuser=0
