### ISSUE TITLE
Missing Binary files for Envs

### ISSUE THREAD

**Issue by beluis3d** [Unity-Technologies/ml-agents#2986]
**Describe the bug**
commit: 99a3fc11ca60c7166d4666da0bd36433ca18ca0d
Commit from Aug 2018
"Be sure to set `env_name` to the name of the Unity environment file you want to launch. Ensure that the environment build is in `../envs`"

I do not see any binary files or a directory with "../envs"

**Environment (please complete the following information):**
- MacOS High Sierra 10.13.6
- _ML-Agents version_: master (#1083) ; 0.11.0 ; 0.5.0a
- _TensorFlow version_: Version: 1.15.0

**Comment by caioc2** [comment]
"../envs" is just an example path, where you should replace it with your own path. When you see something "inside" or <inside> it means you should replace it with your own values ​​and remove the "" or <>.
 
It makes no sense to ship binaries (for the examples) when you provide the entire unity project itself, if not, one would need to provide binaries for different OS'es.

If you want to test any example scenes you can use the training command without --env and it will ask you to press "Play" in the editor or build any of the examples yourself and setup the --env according.

**Comment by unityjeffrey** [comment]
hi, as @caioc2 mentioned, we do not ship the Unity project binaries as part of the repo.  However, you can go to File -> Build Settings in Unity to build our example projects to the platform you are trying to run on (in this case, it should be MacOS).  Attaching a screenshot for you.  Let me know if this addresses your issue. 
<img width="623" alt="Screen Shot 2019-11-27 at 9 39 09 AM" src="https://user-images.githubusercontent.com/34355042/69746746-cff40b80-10f9-11ea-8303-818d0c29b091.png">

**Comment by beluis3d** [comment]
Thanks! I found it now. Really appreciate the feedback: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Executable.md

**Comment by unityjeffrey** [comment]
awesome.  going to close for now, but feel free to re-open or a new issue.
