### ISSUE TITLE
Zero Brains (Agents/Policies) in getting_started notebook

### ISSUE THREAD

**Issue by beluis3d** [Unity-Technologies/ml-agents#2992]
**Describe the bug**
It looks like Brains are being transitioned into Agents & Policies:
https://github.com/Unity-Technologies/ml-agents/pull/2729
But I do not have access to the Design Doc for these changes
https://docs.google.com/document/d/1hBhBxZ9lepGF4H6fc6Hu6AW7UwOmnyX3trmgI3HpOmo/edit#

Issue:
There are 0 brains in the getting-started notebook

**To Reproduce**
There is a reference to Brain in this Notebook:
https://github.com/Unity-Technologies/ml-agents/blob/master/notebooks/getting-started.ipynb

I'm trying to run this notebook, and I have my environment executable file in the right place now.
But (based on my research), it looks like I need to set my Brain to "external"

The error is that there are 0 brains:
"Unity Academy name: Ball3DAcademy; Number of Training Brains : 0"
And the code expects at least one brain:
"env = UnityEnvironment(file_name=env_name); default_brain = env.external_brain_names[0]; brain = env.brains[default_brain]"

Notes:
I believe the resolution when Brain's existed was to make sure that the Brain was set to External and to set the Control tickmark, but I do not see any of those options in Unity's Ball3dAcademy example now. If Brain's no longer exist (as I'm understanding), then what is the solution to this now?

**Environment (please complete the following information):**
- MacOS High Sierra 10.13.6
- _ML-Agents version_: master (#1083) ; 0.11.0 ; 0.5.0a
- _TensorFlow version_: Version: 1.15.0

**Comment by HugeKangroo** [comment]
Hello,
I have got same problem in my ml-agent project. I found that the behaviorparameters has failed when :
https://github.com/Unity-Technologies/ml-agents/blob/8a08bc4306dfa897b780afc79ee2bce47c76d47f/UnitySDK/Assets/ML-Agents/Scripts/Policy/BehaviorParameters.cs#L40-L43

I also checked the Academy, It failed at :
https://github.com/Unity-Technologies/ml-agents/blob/8a08bc4306dfa897b780afc79ee2bce47c76d47f/UnitySDK/Assets/ML-Agents/Scripts/Academy.cs#L294-L307

It looks like ml-agent try to detect python process and result with an exception.

**Comment by unityjeffrey** [comment]
hi @beluis3d and @HugeKangroo - refer to this issue - https://github.com/Unity-Technologies/ml-agents/issues/2856

We also cleaned up the logging here.  https://github.com/Unity-Technologies/ml-agents/pull/2950

We just pushed out release 0.12 that has these fixes.  Please re-open if this is still persistent.  Than you.
