### ISSUE TITLE
Training uses the wrong ciriculum level for the first ephisode when using --load

### ISSUE THREAD

**Issue by Phong13** [Unity-Technologies/ml-agents#2993]
**Describe the bug**
When I restart training that uses ciriculum training. learn.py first loads the curricula and chooses a ciriculum (steps is set to 1). Then learn.py loads the model, now steps is set to whatever the progress is, but does not adjust the ciriculum level. It is possible that learn.py should be using a curriculum level greater than 1 when it starts training. The cirriculum level doesn't get considered again until after one episode has completed.
 

**To Reproduce**
Set up ciriculum training for one of the examples using "progress" (number of steps) as the criteria for switching to a different curriculum level. Train until the progress is in level 2 or greater.
Stop the training CTRL-C
Restart using the --load parameter
Notice that the first episode is trained using the first curriculum level. Learn.py does not switch to the second ciriculum level until 

Expected value. Training should continue at the correct curriculum level. 

**Console logs / stack traces**
```


**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**
Windows 10
ML-Agents v.10
Tensoflow 1.7

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by chriselion** [comment]
Sorry for the late reply on this. I belive this issue was fixed a few releases ago:
> When using Curriculum, the current lesson will resume if training is quit and resumed. As such, the --lesson CLI option has been removed. (#4025)

See https://github.com/Unity-Technologies/ml-agents/blob/latest_release/com.unity.ml-agents/CHANGELOG.md#110-preview---2020-06-10 for more details.
