### ISSUE TITLE
How can i resolve this error?

### ISSUE THREAD

**Issue by UmeHabibasaleem** [Unity-Technologies/ml-agents#2997]
C:\Users\Abubakar>cd Downloads  C:\Users\Abubakar\Downloads>Activate ml-Agents  (ml-Agents) C:\Users\Abubakar\Downloads>mlagents-learn config/trainer_config.yaml --env=C:\Users\Abubakar\Downloads\ExeFileOfUnity\FinalUnityProject --run-id=firstRun --train                           ▄▄▄▓▓▓▓                    ╓▓▓▓▓▓▓█▓▓▓▓▓               ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌             ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄           ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌         ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌         ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓           ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`             '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌                ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀                    `▀█▓▓▓▓▓▓▓▓▓▌                         ¬`▀▀▀█▓   INFO:mlagents.trainers:{'--base-port': '5005',  '--curriculum': 'None',  '--debug': False,  '--docker-target-name': 'None',  '--env': 'C:\\Users\\Abubakar\\Downloads\\ExeFileOfUnity\\FinalUnityProject',  '--help': False,  '--keep-checkpoints': '5',  '--lesson': '0',  '--load': False,  '--no-graphics': False,  '--num-envs': '1',  '--num-runs': '1',  '--run-id': 'firstRun',  '--save-freq': '50000',  '--seed': '-1',  '--slow': False,  '--train': True,  '<trainer-config-path>': 'config/trainer_config.yaml'} Traceback (most recent call last):   File "c:\users\abubakar\downloads\ml-agents\ml-agents\mlagents\trainers\learn.py", line 140, in load_config     with open(trainer_config_path) as data_file: FileNotFoundError: [Errno 2] No such file or directory: 'config/trainer_config.yaml'  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "C:\Anaconda3\envs\ml-Agents\Scripts\mlagents-learn-script.py", line 11, in <module>     load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()   File "c:\users\abubakar\downloads\ml-agents\ml-agents\mlagents\trainers\learn.py", line 262, in main     run_training(0, run_seed, options, Queue())   File "c:\users\abubakar\downloads\ml-agents\ml-agents\mlagents\trainers\learn.py", line 73, in run_training     trainer_config = load_config(trainer_config_path)   File "c:\users\abubakar\downloads\ml-agents\ml-agents\mlagents\trainers\learn.py", line 146, in load_config     .format(trainer_config_path)) mlagents.envs.exception.UnityEnvironmentException: Parameter file could not be found at config/trainer_config.yaml.

**Comment by caioc2** [comment]
`UnityEnvironmentException: Parameter file could not be found at config/trainer_config.yaml.`

Your working directory is:

`C:\Users\Abubakar\Downloads>`

config/trainer_config.yaml file is located at ml-agents root directory.

If you want to run from "Downloads" you need to use the correct path, In you case it looks like /ml-agents/config/trainer_config.yaml

**Comment by UmeHabibasaleem** [comment]
Thanks.it resolved issue.
