### ISSUE TITLE
Add random projection neural networks and associative memory?

### ISSUE THREAD

**Issue by S6Regen** [Unity-Technologies/ml-agents#3]
Or not because there has been no comparison done with "conventional" neural networks.
[https://github.com/S6Regen/EvoNet](url)
[https://randomprojectionai.blogspot.com/](url)

**Comment by awjuliani** [comment]
Hi @S6Regen,

Thanks for the suggestion! If you'd like to provide a Pull-Request with compatibility for this network, along with experiments showing it's viability here, I would be interested in incorporating it. For now I will be closing this issue though.
