### ISSUE TITLE
The agent does not move and just stands still.

### ISSUE THREAD

**Issue by SERGZV** [Unity-Technologies/ml-agents#3000]
Hello, I have the same problem as this guy. https://github.com/Unity-Technologies/ml-agents/issues/2981

I am learning this lesson. https://www.youtube.com/watch?v=axF_nHHchFQ

However, that lesson is for version 0.8 and I have version 0.11
And since these versions have significant differences, namely, they removed the brain and replaced it with the BehaviourParametrs script. I most likely did something wrong.

When I launch nn through the console, the startup goes fine (I suppose)
![Unity launch](https://user-images.githubusercontent.com/31069610/69887410-30ed3080-1300-11ea-87f7-266a83ace855.jpg)

Then I press the start button and the agent (penguin) does not move without giving any errors.
Further in the console I get an error. UnityEnviroment worker: recv failed
![Unity errors](https://user-images.githubusercontent.com/31069610/69887474-89bcc900-1300-11ea-80ae-3ba19f5bf7bf.jpg)

Here are the project screenshots>

Inspector & Hierarhy
![Inspector   Hierarhy](https://user-images.githubusercontent.com/31069610/69887520-cb4d7400-1300-11ea-8a62-ff5351b0f238.jpg)

PenguinAcademy
![PenguinAcademy](https://user-images.githubusercontent.com/31069610/69887539-e28c6180-1300-11ea-8a41-a2039ed64fc5.jpg)

PenguinArea
![PenguinArea_1](https://user-images.githubusercontent.com/31069610/69887554-f20baa80-1300-11ea-9b4f-46dc66a95bc7.jpg)
![PenguinArea_2](https://user-images.githubusercontent.com/31069610/69887557-f46e0480-1300-11ea-878e-8f58803b80b1.jpg)

PenguinAgent
![PenguinAgent_1](https://user-images.githubusercontent.com/31069610/69887581-1d8e9500-1301-11ea-834f-4332d7ec798f.jpg)
![PenguinAgent_2](https://user-images.githubusercontent.com/31069610/69887583-1f585880-1301-11ea-9e7c-9719734aade5.jpg)
![PenguinAgent_3](https://user-images.githubusercontent.com/31069610/69887587-21bab280-1301-11ea-8126-e3b54d2c25ff.jpg)

TrainerConfig.yaml
![TrainerConfig yaml](https://user-images.githubusercontent.com/31069610/69887634-63e3f400-1301-11ea-9cd4-7f59bea5bae6.jpg)

PenguinLearning.json
![PenguinLearning(json)](https://user-images.githubusercontent.com/31069610/69887683-97268300-1301-11ea-9c66-bf1d358e4448.jpg)

Here https://github.com/Unity-Technologies/ml-agents/issues/2981 they said that there is not enough data, but I honestly did not understand the screenshot of what else that guy should have done. If you need any more data, tell me. 

Please help.

**Comment by unityjeffrey** [comment]
hi @SERGZV - taking a look.

**Comment by SERGZV** [comment]
@unityjeffrey - Hello, look at what?

**Comment by unityjeffrey** [comment]
hi - we think the problem is that we switched the port for training in 0.11.  And if you had a version mismatch between the C# SDK and Python, it would never hit the error because of the port change.

Can you make sure both the C# code and Python code is updated using the same version and see if that fixes your issue?

**Comment by SERGZV** [comment]
So. For training "ML-Agents" I use unity version 2019.2.12f1
In Project settings> Player: I changed "NET 2.x" to "NET 4.x"
Using the "unity hub" downloaded and installed a new version of unity jdk sdk and ndk
(cool done now no need to go and download from external pages, if only ML-Agents and the right version of Python could also be installed)
The python version was installed 3.6.6 since everywhere where I didn’t read it was advised to install this particular 3.6.x. However, since you said python, you also need to update
I uninstalled the old python version and installed the python version 3.8.0.
And launched the console again. Now in the console when entering commands:
<<mlagents-learn config/trainer_config.yaml --curriculum=config/curricula/Penguin --run-id=Project_0 --train>> & <<pip3 install mlagents.>>
I get an error: Is not an internal or external command, executable program or batch file.
Now no matter what version of python I install, I get the same error in the console :-(

**Comment by unityjeffrey** [comment]
hi @SERGZV - which version of the C# code from ML-Agents are you using (i.e. 0.8, 0.9, etc..)?  When you upgrade to 0.11, you will need to upgrade both the C# scripts and Python.

**Comment by SERGZV** [comment]
I wrote the code for the lesson version 0.8. However, I originally used version 0.11 since there is no video tutorial for version 0.11. The comments in the video tutorial indicated what changes need to be made to work in version 0.11. Namely, the override virtual method "Heuristic" in the agent class, which inherits from the agent class. What changes I need to make to the code to work in version 0.11 I honestly don’t know.

**Comment by unityjeffrey** [comment]
hi @SERGZV - if you are upgrading to 0.11, make sure to copy the files from /ml-agents/UnitySDK/Assets/ML-Agents/Scripts/ from the 0.11 release to your project as well.

**Comment by SERGZV** [comment]
I did not upgrade to version 0.11. I immediately started working in it.

**Comment by SERGZV** [comment]
And right at the beginning I copied the ML-agents folder in unity assets which contained scripts as well as training examples that worked, except for those that required the "Heuristic" method
