### ISSUE TITLE
Questions related to mlagent configuration.

### ISSUE THREAD

**Issue by jinhueck** [Unity-Technologies/ml-agents#3003]
Hello.
I am a student who started studying mlagent.
I have a problem while practicing with mlagent and ask a question.

I was originally implemented in Unity of mlagent.
However, due to incorrect setup, I erased the Anaconda3 and the ml-agent on C and installed it.
Since then, such an issue has begun to emerge.

Currently, Anaconda3 was downloaded to the Anaconda3-5.1.0 version, and the generation of ml-agents was python=3.6.

Subsequently entering the command to learn mlagent will output the following screen.

![image](https://user-images.githubusercontent.com/22291453/69916310-e94fdb80-149c-11ea-98f5-544e1f660087.png)

Anaconda propt said, "INFO:mlagents.envs:Start training by pressing the Play button in the Unity Editor."
So I tried to run the Unity engine

Since then, the engine has failed to run due to the following error.

UnityAgentsException: The Communicator was unable to connect. Please make sure the External process is ready to accept communication with Unity.
MLAgents.Batcher.SendAcademyParameters (MLAgents.CommunicatorObjects.UnityRLInitializationOutput academyParameters) (at Assets/ML-Agents/Scripts/Batcher.cs:91)
MLAgents.Academy.InitializeEnvironment () (at Assets/ML-Agents/Scripts/Academy.cs:345)
MLAgents.Academy.Awake () (at Assets/ML-Agents/Scripts/Academy.cs:250)

Since then, I have downloaded and executed versions of mlagent0.8.2 and mlagent master, but the same error has continuously occurred.

I think I've set up a similar environment as before, but I don't know why this issue is happening.
If you could give me the answer, I would really appreciate it.

**Comment by Taikatou** [comment]
I have this issue too. It works on versions 8.0 and earlier but not not 10 or 11 or 12

**Comment by chriselion** [comment]
@jinhueck @Taikatou - if you're using version 0.8.2 of the python library, you'll also need to use the same version of the C# code. You can find that here https://github.com/Unity-Technologies/ml-agents/tree/0.8.2 - there's an option to download the the repo at that revision.

**Comment by Taikatou** [comment]
@chriselion I have the up to date python mlagents installed its just updating from 0.8 to 10 or even using any version of 10 -> breaks a lot of the python api on windows and the jupyter notebook doesnt seem to want to work with a blank project

**Comment by chriselion** [comment]
Please take a look at the suggestions I made on https://github.com/Unity-Technologies/ml-agents/issues/3033#issuecomment-562321239 - I think they apply here too. It's possible that even if you `pip install` a specific version of mlagents, running `mlagents-learn` will run a different version.
