### ISSUE TITLE
tensorflow2: tensorflow_to_barracuda.py google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by MarkTension** [Unity-Technologies/ml-agents#3006]
Hi all,

When trying to convert my tensorflow .pb models to .nn format with tensorflow_to_barracuda.py,
I get the error 

```
Converting models/saved_model.pb to siamese_mnist1.nn
WARNING:tensorflow:From /Users/schmark/Unity_Projects/shapeNetwork/tensorflow_to_barracuda.py:1539: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

Traceback (most recent call last):
  File "tensorflow_to_barracuda.py", line 26, in <module>
    tf2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
  File "/Users/schmark/Unity_Projects/shapeNetwork/tensorflow_to_barracuda.py", line 1540, in convert
    i_model.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message
```

Any ways to find the cause of this? 
I'm using tensorflow 1.15 to convert to run tensorflow_to_barracuda
Previously it has worked with models trained via tensorflowhub

Notes: I've built a super simple model with tensorflow 2 like this:

```
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=1)

model.evaluate(x_test,  y_test, verbose=2)
```

and saving it with 

`model.save('saved_model/my_model')
`

that can't possibly be the problem right?

**Comment by unityjeffrey** [comment]
CC: @mantasp - see above

**Comment by mantasp** [comment]
Added this issue to our internal tracker.

**Comment by mantasp** [comment]
@MarkTension `model.save('saved_model/my_model') ` will save model in Keras format, if you want to feed it to Barracuda TF converter you have to convert it to Tensorflow format.
Here are some discussions on how this can be done: https://stackoverflow.com/questions/45466020/how-to-export-keras-h5-to-tensorflow-pb
