### ISSUE TITLE
Tensorboard is showing Sporadic graphs not Illustrating any Type of Recognizable Training

### ISSUE THREAD

**Issue by elanrosen** [Unity-Technologies/ml-agents#301]
![training going worn](https://user-images.githubusercontent.com/20825717/35706838-54980e26-0775-11e8-92da-adb4cccb6e06.PNG)
Clearly, there must be something wrong with the way I am using Tensorboard or the Jupyter Notebook in my own ml agent(worked fine w/ examples). When I use the Jupiter notebook, I keep getting "saved model" logs, while no "mean reward" log shows. 
The only time the graphs resemble anything that looks remotely like training occurs when I set the y-axis as "wall". The spikes shown were when I activated the training.
![wall](https://user-images.githubusercontent.com/20825717/35706993-ffaa6688-0775-11e8-9c16-7368efd99d91.PNG)
Any suggestions?

**Comment by vincentpierre** [comment]
There is an argument called --run-path
You need to give it a different value every time you use ppo or else the graphs in tensorboard will overlap (The graphs are not automatically deleted)

**Comment by elanrosen** [comment]
oh thanks
