### ISSUE TITLE
Can't override Heuristic in Agent Class

### ISSUE THREAD

**Issue by 745976804** [Unity-Technologies/ml-agents#3015]
sorry,my English is not good, I use the 0.10 Unity ml-agent,But when i followed the tutorial ,i can't find the Heuristic checkbox and can't override Heuristic in Agent Class. anyone knows ?

**Comment by 745976804** [comment]
is the cause only 0.11version and below have this function? if update to 0.11,where is the brain checkbox

**Comment by chriselion** [comment]
If you're using 0.10, you should follow the documentation from that version: https://github.com/Unity-Technologies/ml-agents/tree/0.10.0/docs

The "Use Heuristic" checkbox and Heuristic() method were added in 0.11.0.

Which brain checkbox do you mean? The guide for upgrading from 0.10.0 to 0.11.0 is here: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Migrating.md#migrating-from-ml-agents-toolkit-v010-to-v0110

**Comment by 745976804** [comment]
thanks very much for your answer.it helps a lot.

**Comment by 745976804** [comment]
@chriselion thanks very much for your answer.it helps a lot.
