### ISSUE TITLE
Neural Networks structure when using both visual and vector observation?

### ISSUE THREAD

**Issue by BAXMAY** [Unity-Technologies/ml-agents#3016]
Just curious that if I use both visual and vector observation , how will the Neural network structure look like?

**Comment by caioc2** [comment]
Something like:

VisualObservation ----->  VisualEncoder -----> Visual
VectorObservation -----> VectorEncoder -----> Vector

Concat(Visual, Vector) ----> Output Stream(s)

You can dig exacly how it is [here](https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents/mlagents/trainers/models.py)

**Comment by mbaske** [comment]
Could someone give me a hint on how to set up my NN when using both, visual and vector observations? My agent only has a few vector observations and actions that initially don't require anything larger than 2 x 128 hidden units. Do I need to considerably increase the NN size after adding 84x84 pixel visual observations on top of that? Is there some rule of thumb along the lines of "adding visual observations of a given size is equivalent to amount x of additional vector observations"? Thanks!
