### ISSUE TITLE
Swapping NNmodels at runtime in v0.11

### ISSUE THREAD

**Issue by mnsmuts** [Unity-Technologies/ml-agents#3025]
Hi, Now there is no brain scriptable object, how do we change the NN model while the program is running?

**Comment by chriselion** [comment]
I think Agent.GiveModel() will do what you want: https://github.com/Unity-Technologies/ml-agents/blob/3d7c4b8d3c1ad17070308b4e06bb57d4a80f9a0c/UnitySDK/Assets/ML-Agents/Scripts/Agent.cs#L329-L349

**Comment by surfnerd** [comment]
WallJump has an example of this: https://github.com/Unity-Technologies/ml-agents/blob/3d7c4b8d3c1ad17070308b4e06bb57d4a80f9a0c/UnitySDK/Assets/ML-Agents/Examples/WallJump/Scripts/WallJumpAgent.cs#L319-L352

**Comment by mnsmuts** [comment]
Yes that is perfect, many thanks.
