### ISSUE TITLE
Communicator wont connect with my unity

### ISSUE THREAD

**Issue by sekne18** [Unity-Technologies/ml-agents#3033]
HI,
Im stuck with my problem and i cant figure it out... I just started with unity ml-agents and im not sure how things need to work correctly. Now when i start my code "mlagents-learn config/trainer_config.yaml --curriculum=config/curricula/penguin/ --run-id=penguin1 --train", everything works great, but when i press play button in unity an error comes and says "UnityAgentsException: The Communicator was unable to connect. Please make sure the External process is ready to accept communication with Unity.
MLAgents.Batcher.SendAcademyParameters (MLAgents.CommunicatorObjects.UnityRLInitializationOutput academyParameters) (at Assets/ML-Agents/Scripts/Batcher.cs:99)
MLAgents.Academy.InitializeEnvironment () (at Assets/ML-Agents/Scripts/Academy.cs:327)
MLAgents.Academy.Awake () (at Assets/ML-Agents/Scripts/Academy.cs:231)".

Can someone exactly explain me what im doing wrong?

Regards,
Jan

**Comment by chriselion** [comment]
Hi Jan,
A common cause of this is a mismatch between the versions python and c# code. Can you please tell me 
* the version number when you run `pip show mlagents` (or `pip3`)
* the value of `Academy.kApiVersion` or `k_ApiVersion` - this should be something like "API-123"
?

I'm not sure exactly what versions the penguin tutorial uses, but if you have a specific version of the python package, you can get the corresponding C# code from https://github.com/Unity-Technologies/ml-agents/tree/x.y.z/, where `x.y.z` is the version.

**Comment by sekne18** [comment]
> Hi Jan,
> A common cause of this is a mismatch between the versions python and c# code. Can you please tell me
> 
> * the version number when you run `pip show mlagents` (or `pip3`)
> * the value of `Academy.kApiVersion` or `k_ApiVersion` - this should be something like "API-123"
>   ?
> 
> I'm not sure exactly what versions the penguin tutorial uses, but if you have a specific version of the python package, you can get the corresponding C# code from https://github.com/Unity-Technologies/ml-agents/tree/x.y.z/, where `x.y.z` is the version.

Hi,
1) So my version is: 0.10.0, i have installed ml-agents 0.8.2 because i just wanted to learn basics of this and most tutorials are in older versions.

2) My kApiVersion is "API-10";

Okay, so i tried training my agent without curriculum and it didnt start again. Although i was able to train my agents in the past.

**Comment by chriselion** [comment]
Hi,
If I change my setup so that I have version 0.12.0 of the python library, and version 0.10.0 of the C# code, I get this same error.

One thing that could be happening is that you might have multiple versions of mlagents installed, one in a virtual environment (like venv or conda) and another "system" install. So even if `pip show mlagents` says 0.10.0, when you run `mlagents-learn` it might be executing a different version of the script.

I would recommend
* run `pip uninstall -y mlagents`
* run `mlagents-learn` - this should give an error like "No such file or directory" (I'm on mac but it would be similar on windows). If it doesn't give an error, you need to figure out what is being run and remove it. On mac and linux, you can run `which mlagents-learn` to get the path of the executable (I believe `where` is the equivalent windows command)
* run `pip install mlagents==0.10.0` (preferably using venv or conda)

**Comment by sekne18** [comment]
> Hi,
> If I change my setup so that I have version 0.12.0 of the python library, and version 0.10.0 of the C# code, I get this same error.
> 
> One thing that could be happening is that you might have multiple versions of mlagents installed, one in a virtual environment (like venv or conda) and another "system" install. So even if `pip show mlagents` says 0.10.0, when you run `mlagents-learn` it might be executing a different version of the script.
> 
> I would recommend
> 
> 1. run `pip uninstall -y mlagents`
> 2. run `mlagents-learn` - this should give an error like "No such file or directory" (I'm on mac but it would be similar on windows). If it doesn't give an error, you need to figure out what is being run and remove it. On mac and linux, you can run `which mlagents-learn` to get the path of the executable (I believe `where` is the equivalent windows command)
> 3. run `pip install mlagents==0.10.0` (preferably using venv or conda)

Hi,

I did all the steps you wrote and the problem is still there. Do you think deleting ml-agents completely and installing it again could solve problem?

**Comment by sekne18** [comment]
Okay, I've reinstalled everything and made new enviroment, however i still recieve the same error.

**Comment by chriselion** [comment]
Can you paste the results from running `pip freeze`?  If you're installing things with `pip install mlagents==...` then you shouldn't need to do `pip install -e` - the first one installs the packages from the python package repository, the second one makes an "editable" install from the local source.

Besides that and the https://github.com/Unity-Technologies/ml-agents/blob/master/docs/FAQ.md#environment-connection-timeout I'm running out of ideas...

**Comment by sekne18** [comment]
What's wierd is that is used to work and i didn't change anything. Is it possilbe that there's an error in my script or smth? The error shows that the line 99 was triggered and it should recieve parameters, so is it just because it can't connect or it could also be the script?
And this are my results from pip freeze:
`
absl-py==0.8.1
astor==0.8.0
attrs==19.3.0
backcall==0.1.0
bleach==3.1.0
cachetools==3.1.1
certifi==2019.11.28
chardet==3.0.4
cloudpickle==1.2.2
colorama==0.4.1
cycler==0.10.0
decorator==4.4.1
defusedxml==0.6.0
entrypoints==0.3
gast==0.2.2
google-auth==1.7.2
google-auth-oauthlib==0.4.1
google-pasta==0.1.8
grpcio==1.25.0
h5py==2.10.0
idna==2.8
importlib-metadata==1.2.0
ipykernel==5.1.3
ipython==7.10.1
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.15.1
Jinja2==2.10.3
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.0.0
jupyter-core==4.6.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.2
mistune==0.8.4
# Editable install with no version control (mlagents==0.10.0)
-e c:\ml-agents-0.10.0\ml-agents
# Editable install with no version control (mlagents-envs==0.10.0)
-e c:\ml-agents-0.10.0\ml-agents-envs
more-itertools==8.0.1
nbconvert==5.6.1
nbformat==4.4.0
notebook==6.0.2
numpy==1.17.4
oauthlib==3.1.0
opencv-contrib-python==4.1.1.26
opt-einsum==3.1.0
pandocfilters==1.4.2
parso==0.5.1
pickleshare==0.7.5
Pillow==6.2.1
prometheus-client==0.7.1
prompt-toolkit==2.0.10
protobuf==3.11.1
pyasn1==0.4.8
pyasn1-modules==0.2.7
Pygments==2.5.2
pyparsing==2.4.5
pypiwin32==223
pyrsistent==0.15.6
python-dateutil==2.8.1
pywin32==227
pywinpty==0.5.7
PyYAML==5.2
pyzmq==18.1.1
qtconsole==4.6.0
requests==2.22.0
requests-oauthlib==1.3.0
rsa==4.0
Send2Trash==1.5.0
six==1.13.0
tensorboard==1.15.0
tensorflow==1.15.0
tensorflow-estimator==1.15.1
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
tornado==6.0.3
traitlets==4.3.3
urllib3==1.25.7
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.16.0
widgetsnbextension==3.5.1
wincertstore==0.2
wrapt==1.11.2
zipp==0.6.0
`
And thank you for your time and help really.

**Comment by sekne18** [comment]
So after days of fthinking what could went wrong in my ml-agents.. i ended up creating a project from start and its working perfectly now... Not sure what was wrong, however i did manage to make it work so for enyone have the same issue you problem might be in your vesions Good luck.

**Comment by sekne18** [comment]
Okay... I actually don't know why am i having so much issues with this but im so confiused right now. I uninstalled mlagents and it still shows me its installed. in fact i found out it is installed right after i create new enviroment. I literally don't know what to do, is there any way i can uninstall this and get rid of it completely?
![Error](https://user-images.githubusercontent.com/25244849/71121963-d436b480-21df-11ea-89bc-7d1ff0256e48.PNG)

**Comment by chriselion** [comment]
This is what I was trying to get at in https://github.com/Unity-Technologies/ml-agents/issues/3033#issuecomment-562321239 - I think you have mlagents installed outside of the current virtual environment, which could happen if you ran `pip install mlagents` outside of the virtual environment. You should be able to see where it's installed with `where mlagents-learn`.

**Comment by sekne18** [comment]
Finally, I managed to delete it, thanks... But the error is still there. Unity still throws me "The communicator was unable to connnect..." error.

**Comment by StepNeverStop** [comment]
Same error with @sekne18 
In 0.14.1, everything is installed well, but still cannot connect with python terminal.
The editor of Unity just throw 'Couldn't connect to trainer on port 5004 using API version API-14. Will perform inference instead.', And this is no response in terminal, it always show 'INFO:mlagents_envs:Listening on port 5004. Start training by pressing the Play button in the Unity Editor.'

OS: MacOS 10.15.3
Unity: 2018.4.17f1 or 2019.3.2f1
