### ISSUE TITLE
Barracuda model works in update, but fails when called from agentAction() or other Agent functions

### ISSUE THREAD

**Issue by MarkTension** [Unity-Technologies/ml-agents#3044]
Hi all,

I have written a piece of code that gets two render textures, and feeds them into a barracuda-embedded object classifier model.

`            // prepare model
            var worker = BarracudaWorkerFactory.CreateWorker(BarracudaWorkerFactory.Type.ComputePrecompiled, model);
 
            var textures = new[] {texture_1, texture_2};
            var tensor = new Tensor(textures, channelCount);
           
            worker.Execute(tensor);
            var Out = worker.Peek();
            List<double> vector1 = new List<double>(128);
            List<double> vector2 = new List<double>(128);
 
            for (int i = 0; i < 128; i++)
            {
                vector1.Add(Out[0, 0, 0, i]);
                vector2.Add(Out[1, 0, 0, i]);
            }`

I've placed this in the Update() function, and the two different textures inputed into the barracuda .nn model generate different model outputs (vector1 & vector2), which is what I expect.

However, when I put this piece of code in my own function and call it from the
public override void AgentAction(float[] vectorAction, string textAction) {} function, I get no difference between the two outputs.

When I look inside the render Texture's pixels just before they're put into the tensor, they are really different, so it must have something to do with either the Tensor, or the model. Is this an issue with timing? Or Could this be a bug?

**Comment by surfnerd** [comment]
Hi @MarkTension,
According do the barracuda docs, it looks like you might need to pass two tensors in a Dictionary.
https://docs.unity3d.com/Packages/com.unity.barracuda@0.3/manual/index.html#execute-the-model

Could you try this and let us know if you get the results you are expecting?
Thanks.

**Comment by surfnerd** [comment]
Otherwise, you may need to have your tensor in `NHWC` format.  Which means you'll need to add the batch size to the beginning.

**Comment by surfnerd** [comment]
Sorry, I retract what I had said. It looks like you are using a another supported way to invoke barracuda.  I should have kept reading :P.   Maybe @mantasp could help out here.

**Comment by MarkTension** [comment]
Thanks anyway! Yeah I think It really has to do with when I call this piece of code in Unity instead of how the model works, because it does work within the update loop. 

Already tried things like calling the model with  [WaitForEndOfFrame ](https://docs.unity3d.com/ScriptReference/WaitForEndOfFrame.html) , but that didn't help either

**Comment by mantasp** [comment]
Added to our investigation list

**Comment by MarkTension** [comment]
Update, I've found a solution. 

One thing I did before executing the model was (like in the grid-world example) force-rendering the camera's to the rendertextures with:

```
if (targetCamera != null && agentInput != null)
{
    targetCamera.Render();
    agentInput.Render();
}
```

I thought this'd be sufficient, but apparently I needed to wrap that in a coroutine to make sure it's done before feeding it in the model:

```
IEnumerator renderFrame()
{
  if (targetCamera != null && agentInput != null)
  {
      targetCamera.Render();
      agentInput.Render();
  }
}
```

Call it before the barracuda model execution
`StartCoroutine("renderFrame");`

That did the trick or me
