### ISSUE TITLE
RollerBall tutorial - model not created during training

### ISSUE THREAD

**Issue by fredleefarr** [Unity-Technologies/ml-agents#3050]
Am following the tutorial here: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md

This is the command I'm using the launch the training process:
`mlagents-learn config/rollerball_config.yaml --train`

The learn process then starts:
![image](https://user-images.githubusercontent.com/1110286/70396421-c83d3c80-1a00-11ea-8e34-d586f2c1ae68.png)

After clicking Play and watching the Unity editor I can see the target cube move once, so some interaction is taking place. After about 40 seconds (during which time CPU activity increases and the laptop fans start) I see the following:

![image](https://user-images.githubusercontent.com/1110286/70396452-089cba80-1a01-11ea-8849-4335dc8ead45.png)
No model is created, and I would expect to see more output during the training phase.

Agent settings:
![image](https://user-images.githubusercontent.com/1110286/70396473-38e45900-1a01-11ea-8659-253020592a04.png)
I see that no Model has been assigned - I couldn't see the step to do that in the tutorial, and so I assumed it was created during the training process (is that correct?)

Here is my Agent code:
![image](https://user-images.githubusercontent.com/1110286/70396516-b0b28380-1a01-11ea-865c-fb26b407c172.png)

I've created a python virtual environment running version 3.6.8. Unity is version 2019.3.0f1. I've downloaded the latest ml-agents from github, and have installed the mlagents python package: `pip3 install mlagents`

**Comment by fredleefarr** [comment]
Versions:

ML-Agents: 0.12.0
Python: 3.6.8
Unity: 2019.3.0f1
TensorFlow: 2.0.0
MacOS Catalina

**Comment by chriselion** [comment]
Hi @fredleefarr - the model file doesn't get updated automatically. There's a better description of how to set it here: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Basic-Guide.md#after-training

**Comment by fredleefarr** [comment]
Thanks @chriselion - I realised that I still had the "Behavior Type" drop-down set to "Heuristic Only". I switched to "Default" and now the training is racing along nicely.
