### ISSUE TITLE
Is the provided Jupyter Notebook out of date?

### ISSUE THREAD

**Issue by DVonk** [Unity-Technologies/ml-agents#3051]
I've re-installed ML-Agents and tried to connect to a build of the 3DBall environment with the provided Jupyter Notebook. This leads to the build launching, not responding, and this error in the notebook:

> INFO:mlagents.envs:
> 'Ball3DAcademy' started successfully!
> Unity Academy name: Ball3DAcademy
>         Reset Parameters : scale -> 1.0
> 		mass -> 1.0
> 		gravity -> 9.8100004196167
> 
> ---------------------------------------------------------------------------
> IndexError                                Traceback (most recent call last)
> <ipython-input-7-be9daf053292> in <module>
>       2 
>       3 # Set the default brain to work with
> ----> 4 default_brain = env.external_brain_names[0]
>       5 brain = env.brains[default_brain]
> 
> IndexError: list index out of range

I'm guessing that the Python API has changed since there are no longer any brains. If this is the case - what's the fix? I have absolutely no idea how to train from python code anymore since 0.11.

If I change the env_name to None to learn in the Editor it also doesn't work. After it waits for me to press Play nothing happens (the rest of the code after that doesn't even produce output). And after a while I just get a timeout with "The Unity environment took too long to respond".

**Comment by chriselion** [comment]
Hi @DVonk,
Sorry for the problem. You're correct that the notebook is out of date.

If you run
```python
env.step()
```
after creating the `UnityEnvironment`, the brain information will be synced and `env.external_brain_names` will be non-empty.

We'll make sure the notebook gets tested more automatically in the future, to prevent things like this.

**Comment by DVonk** [comment]
Great, thank you. By the way - are you planning on providing a notebook that does some actual training in the future? I vaguely remember there existing one for PPO at some point, but I can't find it anymore.

**Comment by chriselion** [comment]
We don't have any plans to do training in notebooks.
