### ISSUE TITLE
CPU vs GPU inference results

### ISSUE THREAD

**Issue by fog9001** [Unity-Technologies/ml-agents#3052]
Hi,

I updated my environment from 0.11 to 0.12 and TF from 1.14 to 2.0. 

No issues training at all, but GPU inference is not working as before (same performance (as cpu inference) and poor results).

CPU inference -> https://www.youtube.com/watch?v=rumkVXGpP-8
GPU -> https://www.youtube.com/watch?v=R-VYv9gbqck

Cheers

**Comment by chriselion** [comment]
Hi @fog9001,
Can you share a copy of the frozen graph that is output from training? Even if it just has random weights (no training run), that should help us diagnose the differences.

cc @mantasp

**Comment by fog9001** [comment]
Hi,

Sure, sharing Zip file containing ´frozen_graph_def.pb´ and model (.nn).

https://drive.google.com/file/d/1lQ6JmyLSGdHcpRyK88wQIbQhr93wtAp0/view?usp=sharing

Thank you @chriselion

**Comment by chriselion** [comment]
Thanks @fog9001 - I'll take a look today and see if anything jumps out, but it will probably need the Barracuda team to look into this, and they're all at the NeurIPS conference this week.

**Comment by fog9001** [comment]
Tanks, Cpu inference is perfectly fine for me now, no rush 👍

**Comment by chriselion** [comment]
Nothing surprising from the barracuda conversion:
```
Converting ./gpu_inference.pb to ./gpu_inference.nn
WARNING:tensorflow:From /Users/chris.elion/code/ml-agents/ml-agents/mlagents/trainers/tensorflow_to_barracuda.py:1541: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

IGNORED: StopGradient unknown layer
GLOBALS: 'is_continuous_control', 'version_number', 'memory_size', 'action_output_shape'
IN: 'vector_observation': [-1, 1, 1, 894] => 'main_graph_0/hidden_0/BiasAdd'
IN: 'epsilon': [-1, 1, 1, 2] => 'mul'
OUT: 'action', 'action_probs'
DONE: wrote ./gpu_inference.nn file.
```
I'm going to have to let the Barracuda folks handle this after the conference.

**Comment by mantasp** [comment]
Issue added to our internal tracker.

**Comment by mantasp** [comment]
Issue was fixed on Barracuda side and fix should appear in the next release of Barracuda

**Comment by fog9001** [comment]
Thank you @mantasp

**Comment by mantasp** [comment]
@fog9001 Barracuda 0.4.0-preview shipped yesterday. Could you please try to update your Barracuda version to this one (via Unity Package Manager) and see if it fixed your issue.
**Note:** that you might need to "re-import" .nn files in you project after this upgrade. You can do it by right-clicking on .nn file and picking "Reimport".

**Comment by fog9001** [comment]
Updated to 0.4.0-preview and it worked with no issues, thank you so much @mantasp .
