### ISSUE TITLE
Dispatch model on two graphics card

### ISSUE THREAD

**Issue by Peamon** [Unity-Technologies/ml-agents#3054]
**Is your feature request related to a problem? Please describe.**
With barracuda, i have 2 model to run in parallel and i have 2 graphics cards but i can't choose to dispatch one model on each graphics card to avoid performance issue.

One graphics card is 100% full and the other is 0%, I have an SLI configuration active but it seems Unity/Barracuda does not use it.

**Describe the solution you'd like**
I would like to choose on witch graphics card the compute shader behind the barracuda model are dispached.

**Describe alternatives you've considered**
Now i use a python program with tensorflow, it works but i need to upload and dowload data to the model at each frame....

**Additional context**
I've tryed this code in unity to run the two model in parallel but it change nothing. i think it's because the compute shader are dispatched on the same graphics card.
```
var enum_l = worker_l.ExecuteAsync(intensor_l);
var enum_r = worker_r.ExecuteAsync(intensor_r);
while (enum_l.MoveNext() || enum_r.MoveNext()) { }
```

**Comment by Peamon** [comment]
Hello, Someone could add barracuda label ?

**Comment by mantasp** [comment]
Unity engine currently supports only one GPU at the time, the same limitation applies to Barracuda. The only way to use both cards is to run two instances of Unity standalone build and assigning them to different cards, but if you need outputs from both networks in the same instance of application, then you would need to do some sort of IPC and send data between them.

**Comment by Peamon** [comment]
Is it possible to share some kind of graphics context between two unity instance ?

**Comment by mantasp** [comment]
Technically you could access Unity graphics context from the native rendering plugin and pass it to the other app, but for the starters it would be easier just to grab compute buffer data to the CPU memory and share that memory region with other application.
