### ISSUE TITLE
Alternative to online training

### ISSUE THREAD

**Issue by eliofreitas** [Unity-Technologies/ml-agents#3064]
Greetings,
First let me give you all a praise for this amazing library. 
Now lets follow unto my problem.
Recently I have been developing my thesis around behavioural cloning using this package.
I was going to update my branch to the latest but I stumble upon that the online_training mode was deprecated. I found an issue (https://github.com/Unity-Technologies/ml-agents/issues/2901) talking about it saying it was limited, because it could only learn from example and that's the justification for deprecating, I understand the need for deprecation however the complete elimination sounds like a hard decision without having an alternative at hand at least for the time being.

As for my thesis for what I was checking I can rollback to 0.10.0 for now. However, for future developments will there exist any alternative?. 

In the other issue (https://github.com/Unity-Technologies/ml-agents/issues/2901) you talk about using Gail is that something that can be done or will be done?

**Comment by chriselion** [comment]
Hi @eliofreitas,
Unfortunately we don't have a timeline for if/when online imitation learning will be brought back. I added your feedback to our internal tracker (MLA-422).

**Comment by eliofreitas** [comment]
Understood. Thank you for the response.

**Comment by Ro-tico** [comment]
@eliofreitas have you worked around this problem?
