### ISSUE TITLE
Curriculum is unclear on multiple brains

### ISSUE THREAD

**Issue by unixunion** [Unity-Technologies/ml-agents#3074]
When I run the WallJump, I see the agent flipping to different brains all the time depending on no-wall, small wall or large wall. But I thought the end goal would be to have a single brain trained through the Curriculum program that could adapt to the environment.

How should this be used in in practice, as the brain switching is not something that is done from adapting to environment, but rather the agent is setting the environment to be Big wall, and choosing the big wall brain.

**Comment by anupambhatnagar** [comment]
@ervteng Do you have any thoughts on this?

**Comment by harperj** [comment]
Hi @unixunion -- what you're calling out are two separate features we take advantage of in the WallJump environment: 1) using different brains based on changes in the environment and 2) using curriculum learning to gradually make the environment more difficult over time.

In this case each of the brains has its own curriculum.  You might consider a different version of the environment where we don't use separate brains at all, and use a curriculum to train a single "WallJumpBrain".

As far as what to use in practice -- it really depends on your use case.  If you have multiple distinct behaviors you'd like to learn, and you can programmatically determine when a different behavior should be used, multiple brains/behaviors might be appropriate.

If you have a complex environment where learning is initially very slow (for example if the rewards are sparse) it might be beneficial to use curriculum learning to guide training.

**Comment by unixunion** [comment]
Thanks for your replies, I still feel that the current example does not quite make sense. 

WallJump is training multiple different brains with the curriculum system. And it is engaging the next level of the curriculum based on progress which is not relevant in the new brains. How is this different from not just training 3 separate brains entirely? Because I thought the curriculum system was about progressing a single brain in a more guided manner. 

Perhaps a second simple example can be made to demonstrate iteratively training a single brain via curriculum.

**Comment by harperj** [comment]
I agree that this isn't the simplest example.  However I would disagree that the curriculum is being advanced based on progress not relevant to each brain.  The curriculum for each of the brains is advanced based only on data relevant to that brain.  Each brain will have its own trainer, and the data from the trainer is used to advance the curriculum.

**Comment by nlantz** [comment]
I believe the confusion is because curriculum learning is not operational in the current example.  The reset parameters in the academy do not adjust based on the curriculum.  For example, the large wall always has a height of 8 even at the beginning of training.
