### ISSUE TITLE
calling RequestDecision() every x frames to increase speed a good idea?

### ISSUE THREAD

**Issue by MarkTension** [Unity-Technologies/ml-agents#3082]
I've mimicked the gridworld On Demand Decisions implementation for my agent's training cycle.
Instead of using Time, I'm calling RequestDecision() every **x** frames.

I'm doing this because my training goes faster for some reason, and I think it has to do with that  I'm running heavy computation through an additional barracuda model, which starts messing with my CPU when it's called too often.

It seems that a step is one cycle in an agent's Update() or FixedUpdate() loop. Because when I set max steps to 100, and RequestDecision() once every  **x** frames, my agent resets after 100/ **x** decisions. This makes me have to correct maxSteps every time I change **x** .

Is there a better way to do this than using requestDecision every **x** frames?

**Comment by anupambhatnagar** [comment]
@ervteng Any thoughts on this?

**Comment by ervteng** [comment]
Hi @MarkTension, you're right, when OnDemandDecisions isn't enabled, an agent takes a step every FixedUpdate, but only asks the Barracuda model/Python code for a new action every DecisionInterval steps, repeating the action in between. 

Depending on how CPU-intensive the AgentAction method is, you might see some speedup when switching to OnDemandDecisions as you're seeing.
