### ISSUE TITLE
Wrong path for `envs` subdirectory

### ISSUE THREAD

**Issue by igor-susic** [Unity-Technologies/ml-agents#3085]
Documentation bug:

At `docs` for [Python-API](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Python-API.md) in the section for [loading-a-unity-environment](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Python-API.md#loading-a-unity-environment) it states that the `UnityEnvironment` is located at `ml-agents/mlagents/envs` but the subdirectory `envs` does not exists there, should the path be `ml-agents-envs/mlagents/envs` insted?

**Comment by chriselion** [comment]
Thanks for the report. I've got a PR to fix the location here https://github.com/Unity-Technologies/ml-agents/pull/3093
