### ISSUE TITLE
How does obsevations work with RayPerceptionSensorComponent?

### ISSUE THREAD

**Issue by unixunion** [Unity-Technologies/ml-agents#3086]
I cant deduce from the doc how the new RPSC works, does it automatically add to my agents observations, or do I need to call it during Observe like old Perceive method in the previous versions?

**Comment by chriselion** [comment]
Yes, it will automatically add to the agents observations; you don't need to account for it the Behavior Parameters' Space Size.

**Comment by chriselion** [comment]
There's a section in the Migration Guide on this, let me know if there's anything that could be made clearer https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Migrating.md#steps-to-migrate-1
