### ISSUE TITLE
Check if all agents are done (3DBall)

### ISSUE THREAD

**Issue by valentinmace** [Unity-Technologies/ml-agents#3091]
I am learning with the 3DBall environment, using only 2 agents to simplify my task

I want to make my agents to play one and only one game, i.e. the agent plays with the ball until it falls and waits until the other agent also loses its ball

So I'm runing a loop similar to the notebook example: At each step I check if all my agents are done, if so the game is over

I also unchecked **'Reset On Done"** in the Agent from Unity, since I don't want them to start playing again when they lose, I want them to do nothing

```
unity_env = UnityEnvironment(file_name=env_name, worker_id=0, seed=1, no_graphics=False)
env_info = unity_env.reset(train_mode=True, config=None)

unity_brain_names = unity_env.external_brain_names
unity_brain = unity_env.brains[unity_brain_names[0]]

done = [False, False]
actions = [0,0,0,0]
while not all(done):
    env_info = unity_env.step(vector_action=actions)
    done = env_info[unity_brain_names[0]].local_done
```
_Note 1: My agents don't act at all in this code since it's just for test_

_Note 2: I stop the loop only if all agents have their local_done = True, since `done` contains a list of all agents local_done (at least in my understanding)_

**My problem is:**

The game starts, both agents don't move (which is normal), and printing `done` yields [False, False] which is coherent. But as soon as one of them drops its ball, `done` yields [True]. Which is weird, because it implies there's only one agent left with its local_done set to True, and it shouldn't be True since it hasn't lose its ball yet

Thanks for your time

**Comment by kevtan** [comment]
I pulled in the latest changes, ran the same experiment as described in the issue and was able to replicate the same problem. It seems like once one of the ball drops the environment only registers the information of the agent that dropped the ball. In particular, the `max_reached` and `rewards` fields of the BrainInfo object also collapse to length-one lists. I'm not sure what's going on though. Can someone more knowledgeable let us know what the root cause of this issue is?

**Comment by valentinmace** [comment]
I also tried with the latest changes and I noticed the same behavior. If it can help, the agent_list (containing agent ids and all their info) contains only one agent at the step when the agent is done.

More importantly, when I’m playing with different seeds for the environment, this behavior sometimes disappear for no reason.
