### ISSUE TITLE
PPO and SAC references

### ISSUE THREAD

**Issue by beluis3d** [Unity-Technologies/ml-agents#3098]
Hello - Are the PPO and SAC implementations the same ones as the OpenAI implementations?
If not, why did Unity choose to re-implement it? Also, is there anything different about the Unity implementation than the OpenAI implementations?

Additionally, which papers are suitable for references for Unity's PPO and SAC implementations?
Just the usual ones by Schulman and Levine?
https://arxiv.org/abs/1707.06347
https://arxiv.org/abs/1801.01290

Any relevant feedback is highly appreciated!

**Comment by andrewcoh** [comment]
Fundamentally, the implementations are the same. The majority of the differences stem from the fact that we have to support the many different types of action/observation spaces that can be built in Unity.  These references are exactly what I'd recommend to understand the basics of PPO/SAC.

Good luck.
