### ISSUE TITLE
Using visual observation for training, agent only taking one action

### ISSUE THREAD

**Issue by rajatpaliwal** [Unity-Technologies/ml-agents#3099]
Hello,
I am using visual observation for training. Using camera  for collecting the visual observation. Everything works fine but it seems agent uses only one action(i.e. forward movement) while training out of 5 action options available. 
Vector action structure is ::
switch(forward movement)
  case 1: forward axis
switch(updown rotation)
  case 1: up rotation
  case 2: down rotation
switch (leftright rotation)
  case 1: left rotation
  case 2: right rotation

Normally, the agent should take random actions like a combination of actions (eg, forward movement + left rotation, forward movement + right rotation) and figure out the best combination of actions to get the maximum reward but it seems it is taking only action of going forward throughout the training. I am not using vector observation , I am using just the visual observation. 
I am not able to figure out the reason behind this behavior,  any suggestions would be helpful.
Unity version : 2018.2.13f1
ML Agents version : 0.10.0

**Comment by andrewcoh** [comment]
Hi,

Can you copy the actual code from your AgentAction function?

**Comment by rajatpaliwal** [comment]
Hi,
@andrewcoh . Thanks for replying. The problem is solved , the issue was in the case number defined under each branch for every action. They were not starting from 1 but were numbered something else so, the agent was not able to reach those actions.
Sorry for bothering you.

Thanks ,
Rajat

**Comment by andrewcoh** [comment]
No problem! Good luck.
