### ISSUE TITLE
Unable to get tensorboard reporting to find event file on windows 10 - help request

### ISSUE THREAD

**Issue by seattlefella** [Unity-Technologies/ml-agents#31]
I have been successful in executing the ppo notebook including importing a bytes file into unity and having it run both in the editor and in building a new standalone instance.

I am successful in having the tensorboard menu display at localhost:6060 but I am unable to get tensorboard to find my event files and to display  results -  on windows 10, Python3.

// this command from the help file causes an error
tensorboard -- logdir DIRECTORY_PATH --debug
// I can see event files in ./summaries and I have tried using the fully qualified both have localhost:6060 tell me that the files cannot be found.
tensorboard --logdir='./summaries'

**Comment by ASPePeX** [comment]
Using `tensorboard --logdir='./summaries'` didn't work for me either, but `tensorboard --logdir=summaries` does. Not sure if Windows is bothered by the singlequotes or the `./`, I stoped trying when it worked ;).

**Comment by seattlefella** [comment]
Thank you that worked for me to.

**Comment by awjuliani** [comment]
Thanks for pointing this out @ASPePeX, I'll amend the documentation to make this change.
