### ISSUE TITLE
Visual / Raycast Tandem

### ISSUE THREAD

**Issue by afewvowels** [Unity-Technologies/ml-agents#3100]
The documents describe raycasts as an "alternative system" after describing visual sensors. I've had success training on raycasts alone, but when I try to layer on a visual sensor I have not had good results. Is it possible to use these two systems at the same time or will I need to use CollectObservations to input information about the environment to agents that use either a camera or a render texture?

Thanks so much!

**Comment by andrewcoh** [comment]
You should be able to add both CameraSensor and RayPerception scripts to an agent without any problem. 

Can you be more specific regarding not having good results?

**Comment by afewvowels** [comment]
Sure, you can see by [this footage](https://github.com/afewvowels/unity_00_07_ml-agents_warehouse) that I'm not getting very good performance. That's a standalone scene with a single agent in it with a camera sensor @ 128x128px (that image on the billboard is a render texture of the agent camera) and I can't even get 24fps playback, let alone for training. Here's [my repo](https://github.com/afewvowels/unity_00_07_ml-agents_warehouse) for the project.

I had a lot of success working with the RayPerception component alone both with performance and results, but only with PPO. I've had a lot of problems with agents only doing a single action with SAC. I'll post some pictures from [this repo on chameleon agents](https://github.com/afewvowels/unity_00_09_ml-agents_chameleon) where the agents picked a favorite color (green) and ignored the reward structure and immediately changed to the green color from the randomized start color.

Unfortunately in the warehouse scene I've changed my Agent script a bit and the old models I trained on SAC aren't using the same inputs and vector spaces (I'll have to retrain) but across 2 or 3 training sessions the agent settled on rotating in a single direction and doing no other actions after about 50k-100k steps.

**Comment by andrewcoh** [comment]
For how many timesteps did you let the agent with visual obs/raycasts run?

**Comment by afewvowels** [comment]
Most likely the agent was trained for the base 50k steps, the _timers.json file says 50,001 but I haven't looked at this type of file before so I'm not sure if that's where the model's trained step count lives. I've got a fresh run going now for 500,000 steps and I'll let you know if the newly trained model exhibits the same performance and behavioral issues discussed above.
