### ISSUE TITLE
QOL | Camera Controls

### ISSUE THREAD

**Issue by afewvowels** [Unity-Technologies/ml-agents#3102]
I thought it would be neat to add a simple camera control script to the example scenes. It could cycle through the scenes and provide rotation controls in case the agent / goal is off-screen with the current viewing angle. I made one that I use in my implementations of ml-agents as I like to peek in on the different training arenas. I also put statistics on a canvas like step count and goals scored per agent per arena.

[Simple camera control script example](https://github.com/afewvowels/unity_00_07_ml-agents_warehouse/blob/master/mlagents%20warehouse/Assets/Warehouse/Scripts/CameraControls.cs)

[Complex camera control to cycle between orthographic & perspective projection modes](https://github.com/afewvowels/unity_00_10_ml-agents_maze_solver/blob/master/maze%20solver/Assets/Scripts/CameraController.cs)

I'd make a pull request but I've never actually done anything like that before and I'm not sure if adding all that information would just be needlessly complicating things. Also I guess I should be migrating to the shiny new Input System you guys are putting so much effort into?

**Comment by andrewcoh** [comment]
If you've found this useful, it's possible others would too. Feel free to submit a pull request following our contributing guidelines https://github.com/Unity-Technologies/ml-agents/blob/master/CONTRIBUTING.md
