### ISSUE TITLE
how to use the Engine Configuration?

### ISSUE THREAD

**Issue by xunyiljg** [Unity-Technologies/ml-agents#3103]
![{KAJKU`ZDDI5715J} L$9%2](https://user-images.githubusercontent.com/28186769/71103556-4d8cd200-21f5-11ea-9645-88853e6ac3ea.png)
After upgrading to the latest version,  speed recommended to be modified on the command line. But it doesn't work.

**Comment by andrewcoh** [comment]
Hi,

I assume you're looking at the docs on master.  Try these instead https://github.com/Unity-Technologies/ml-agents/tree/latest_release

**Comment by cafragachan** [comment]
I am having the same issue with the latest release...when I pass a --time-scale argument it is giving me the same error. Has anyone found a solution?
