### ISSUE TITLE
Depricate the --load parameter and a new --restart parameter

### ISSUE THREAD

**Issue by Phong13** [Unity-Technologies/ml-agents#3104]
**Is your feature request related to a problem? Please describe.**

The default behavior for the --load parameter creates a dangerous workflow in which it is easy to loose work or training doesn't start. The default behavior is destructive (learn.py will try to overwrite previous work unless explicitly instructed not to). It is an error to tell learn.py not to overwrite previous work if there is no work.

The problem is that the --load parameter cannot be used the for the first run of a new model, but MUST be used after that. A batch file used for starting training must be regularly edited.

- It has happened to me 4-5 times over the last three months that I have resumed training of a model overnight only to discover in the morning that I had accidentally started fresh training (omitted --load).
- It has happened to me 4-5 times over the last three months that I have started a fresh Training model at the end of the day. Typed the command then walked away from the computer. I use --num-envs = 16 so it takes several minutes before training starts. When I return to the office the next morning I discover that training didn't start because I had included the --load parameter in the script. 

Consider the following scenarios: A developer sets up a new training scene and tests it with a new model. They omit the --load parameter for this because they would be blocked if they included it. When they are ready to train they need to generate a command line for launching the Trainer. Typically this will be put in a script/batch file because ml-agents requires a lot of parameters and it is tedious and error prone to re-type this each time. Do I include the load parameter or not? If I include it then I cannot run the batch file the first time. If I don't then I cannot use the batch file to resume training for a partly trained model. If I omit --load then I need to remember to edit (add --load) after the first start because if I don't then if I use the script to restart it will loose all progress.

The --load parameter forces the developer to constantly be thinking: "Is this a fresh run or resume? do I need --load?" and fiddling with their script.

**Describe the solution you'd like**
Solution 1: The default behavior of learn.py should be "always reloads if a checkpoint file/model is present otherwise start a fresh training run". Deprecate the --load parameter and add a new --restart parameter. . The developer would not need to think about "is this a fresh start or reload". IMO it is rare that someone wants to restart training at the beginning with the same --run-id. If they do want to do this (overwrite previous work). Then they could include the --restart parameter.

Solution 2: It should not be an error that prevents learn.py from launching to: "include --load when there is no model". Learn.py should start training a new model. Why is this an error that prevents learn.py from starting? The only downside is that a dev might think they are resuming training when they are starting fresh. Training may run for a while before they notice from the step count that this is a new run. IMO this is less harmful. No work has been lost, it is rare that this would happen if the dev is using a script to restart training.

**Describe alternatives you've considered**
You could omit the --load parameter. Switch the default behavior to "always reloads if a checkpoint file/model is present otherwise start a fresh training run". Don't add a new parameter. If someone wants to start a new fresh run then the would need to either:

- Manually delete the checkpoint file and saved checkpoints. I like this because it is obvious that they will be loosing previous work.
- Use a new --run-id

**Additional context**

**Comment by andrewcoh** [comment]
Thank you for the feedback. I will bring up some alternatives for the load/run-id functionality in our next team meeting.

**Comment by chriselion** [comment]
The behavior of the command line parameters was changed a few releases ago, so that we'll never overwrite existing runs unless you pass --force
