### ISSUE TITLE
[Help] MultiAgent competitive Environment

### ISSUE THREAD

**Issue by RespawnFreddy** [Unity-Technologies/ml-agents#3106]
### **Hey guys!**

I'd like to do something like the Unity Evangelists. But since their repo is very outdated I'll ask here. 

Let's say I have an agent as opponent who can do the same as the player in a **3D top down** world. For example, he can do these states:
- idle
- run to the right
- turn left
- run forward
- back 
- attacks[]

The only goal of the agents should be to defeat other agents or the player and get exp. 

Could someone give me a hand or something. You would need your own. yes continious because you could also press the W-key and the A-key to run up diagonally to the left. Would it also work to pass the following parameters to the agent?

- Cam (to detect enemys and items **or should i give it something like RayCasts each 10° but they should behave like humans, like they got a cam**) 
- CurrentHealth
- exp
- mana

Would be very grateful for any help!

**Comment by afewvowels** [comment]
I've had limited success training on visual algorithms and found agents that use the RaycastPerception component to converge on a solution much faster but you'll have to experiment with that for yourself.

The items you listed could be passed to the agent in the CollectObservations method. Just remember to set the space size under vector observations in the Behavior Parameters (visible in the Unity editor) to match the number of ```AddVectorObs(obs)``` you add in ```CollectObservations()```!:
```c#
public override void CollectObservations()
{
     AddVectorObs(currentHealth);
     AddVectorObs(currentMana);
     AddVectorObs(experience);
}
```

You could control the agent with a vector action space, just use 3 branches.

```c#
public override float[] AgentAction(float[] vectorAction)
{
     var moveAction = Mathf.FloorToInt(vectorAction[0]);
     var rotateAction = Mathf.FloorToInt(vectorAction[1]);
     var attackAction = Mathf.FloorToInt(vectorAction[2]);

     switch (moveAction)
     {
          case 1:
               agentRB.AddForce(transform.forward, ForceMode.VelocityChange);
               break;
          case 2:
               agentRB.AddForce(-transform.forward, ForceMode.VelocityChange);
               break;
     }

     switch (rotateAction)
     {
          case 1:
               transform.Rotate(0.0f, 5.0f, 0.0f);
               break;
          case 2:
               transform.Rotate(0.0f, -5.0f, 0.0f);
               break;
     }

     switch(attackAction)
     {
          case 1:
               DoAgentAttack(1);
               break;
          case 2:
               DoAgentAttack(2);
               break;
          ...
          case n:
               DoAgentAttack(n);
               break;
     }
}
```

 The agent can perform a single action on each branch per agent action. So technically the agent moves, turns, and attacks every time this function is called, but we use a branch size 1 greater than the supplied number of actions so there's an empty action in case the agent only wants to perform a single action. In the example below if the agent just wanted to move forwards, its vectorAction would look like this:

```c#
vectorAction[0] = 1.0f; // This moves forward
vectorAction[1] = 0.0f; // This is an undefined rotation action so nothing happens
vectorAction[2] = 0.0f // This is an undefined attack action so nothing happens
```

**Comment by RespawnFreddy** [comment]
Thank you! @afewvowels ♥
