### ISSUE TITLE
Clarification on episode length and decision interval

### ISSUE THREAD

**Issue by niskander** [Unity-Technologies/ml-agents#3107]
Hi, I'd like to confirm if the episode length only reflects the number of decisions or not, i.e.
If the episode length is 1000, and decision interval is 10, that means a total of 10,000 calls to AgentAction (in csharp) were made. Is that correct?

**Comment by andrewcoh** [comment]
For an episode with 1000 steps, the total number of calls to AgentAction is 1000.  The decision interval is the number of FixedUpdates called in your scene between agent decisions.

**Comment by niskander** [comment]
@andrewcoh Did you mean to make a distinction between AgentAction and FixedUpdate? AgentAction is called every environment step which is called on FixedUpdate. 

I briefly looked through the code, and it looks like the episode length is the sum of the lengths of "trajectories" which are lists of `AgentExperiences`. In `Agent.cs`, the agent experience is recorded only when `m_RequestDecision `is true, so I think my initial assumption is correct.

**Comment by andrewcoh** [comment]
Are you referring to the line 

`AgentAct?.Invoke();`

in EnvironmentStep() (which is called every FixedUpdate() in Academy.cs)?  Effectively, this calls AgentStep() per EnvironmentStep().  In AgentStep(), AgentAction() is called if m_RequestAction is true which occurs when RequestDecision() is called.  RequestDecision is called after the number of FixedUpdates as specified by the decision interval on line 1008 of Agent.cs.

```
1005                 if (academyStepCounter %
1006                     agentParameters.numberOfActionsBetweenDecisions == 0)
1007                 {
1008                     RequestDecision();
1009                 }
```
where numberOfActionsBetweenDecisions corresponds to the decision interval. I agree that this is a misleading name and should more appropriately be numberOfUpdatesBetweenDecisions, which we are going to fix right now.  

Thanks for pointing this out.

**Comment by andrewcoh** [comment]
Sorry, your original assumption is correct.  AgentAction is called every FixedUpdate.  The action that is executed is changed at every request for a decision which occurs every x FixedUpdates where x = Decision Interval.  So, in your original question, yes AgentAction would be called 10,000 times and the action would change every 10 FixedUpdates.

**Comment by niskander** [comment]
@andrewcoh cool, thanks for confirming!
