### ISSUE TITLE
Query regarding using render texture for visual observation

### ISSUE THREAD

**Issue by rajatpaliwal** [Unity-Technologies/ml-agents#3114]
Hello all, 
I am using agent render texture to debug the visual observation . I need to confirm whether the Raw image size we define inside the canvas as shown in the image,
![image](https://user-images.githubusercontent.com/30369775/71301183-fef44a80-2350-11ea-92cf-928997be9953.png)
 Should be same as the width and height that we set in the brain parameter in the visual observation as shown in the image shown below.
![image](https://user-images.githubusercontent.com/30369775/71301207-3531ca00-2351-11ea-85eb-b0bf1d0d2be1.png)
.
Thanks in advance,
Rajat

**Comment by kevtan** [comment]
Hi @rajatpaliwal were you able to figure this out? It also looks like you're using an old version of the Unity ML-Agents SDK (seeing as you have a Learning Brain, which has now been replaced in favor of the Behavior Parameters component attached to Agents).

**Comment by chriselion** [comment]
As @kevtan mentioned, this is an older version. The latest version has a different (and IMHO simpler, but I'm biased) setup for this; the observation will always be the size of the rendertexture and there's no other dimension parameters that need to be set.

Two other things to note:
* In older versions, the size mismatch probably would lead to a problem, but I'm not sure if it would have complained immediately or more subtly further down the pipeline.
* There's a lower bound to the size of visual observations that we can support (20x20 by default). Some better error messages for this were just added last week.

**Comment by rajatpaliwal** [comment]
@kevtan and @chriselion  thanks for replying.  Yes,  I am using Ml agents (0.10.0) which is an older version. I am going forward with setting the same size of visual observation and rendertexture as @chriselion  suggested.
