### ISSUE TITLE
[Help]👀pkg_resources.DistributionNotFound: The 'tensorflow<2.1,>=1.7' distribution was not found and is required by mlagents

### ISSUE THREAD

**Issue by mosquitoam** [Unity-Technologies/ml-agents#3115]
Hi,
Something wrong had happened when i was test the RollerBall with tensorflow-gpu in windows. I have tried `pip uninstall tensorflow-gpu==2.0` and `pip install tensorflow-gpu==2.0` several times, but it dose not work. 

![image](https://user-images.githubusercontent.com/50072690/71307170-6085e900-2425-11ea-95a0-32ca4ceecb43.png)

And this is  the packages in my virtual envs:

![image](https://user-images.githubusercontent.com/50072690/71307291-13a31200-2427-11ea-88ab-f5b7daf0a25f.png)
![image](https://user-images.githubusercontent.com/50072690/71307312-78f70300-2427-11ea-9db7-b2d61c7bb4a2.png)

**Comment by capra314cabra** [comment]
You can see how to fix it on #1534 .

**Comment by mosquitoam** [comment]
> You can see how to fix it on #1534 .

Thanks for your advice. It worked！
