### ISSUE TITLE
[Error no 2] No such file or directory: 'config/trainer_config.yaml'

### ISSUE THREAD

**Issue by RogueCMD** [Unity-Technologies/ml-agents#3116]
Hello everyone, I'm new to Python and this Unity new feature, things going fine during installation but when I'm entering the training command it gave me an error message that I couldn't understand like this. Since I'm complete newb to this any help will greatly be appreciated

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\system32>cd\

C:\>cd D:\Program DLL\GDev\ml-agents-master\ml-agents

C:\>D:

D:\Program DLL\GDev\ml-agents-master\ml-agents> mlagents-learn config/trainer_config.yaml --run-id=BouncerTrain --train
WARNING:tensorflow:From c:\users\enpetigai\appdata\local\programs\python\python36\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:65: disable_resource_variables (
from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

                        ▄▄▄▓▓▓▓
                   ╔▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓█
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓█▄ ▄▄▄    ,▄▄
          ▄▓▓▓▀        ▄▓▓▀   █▓▓█     ▓▓█   █▓▓ █▓▓▓▀▀▀▓▓█ ▓▓▓ ▀▓▓█▀ ^▓▓█  ╔▓▓█
        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓█   █▓▓ █▓▓    ▓▓▓ ▓▓▓  ▓▓█   █▓▓▄ ▓▓█
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓█   █▓▓ █▓▓    ▓▓▓ ▓▓▓  ▓▓█    █▓▓█▓▓
          ^█▓▓▓        ▀▓▓▄   █▓▓█     ▓▓▓▓▄▓▓▓▓ █▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    █▓▓█
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓█
                        ¬`▀▀▀█▓

 Version information:
  ml-agents: 0.12.1,
  ml-agents-envs: 0.12.1,
  Communicator API: API-12,
  TensorFlow: 2.0.0
INFO:mlagents.trainers:CommandLineOptions(debug=False, num_runs=1, seed=-1, env_path=None, run_id='BouncerTrain', load_model=False, train_model=True, save_freq=50000, keep_che
ckpoints=5, base_port=5005, num_envs=1, curriculum_folder=None, lesson=0, no_graphics=False, multi_gpu=False, trainer_config_path='config/trainer_config.yaml', sampler_file_pa
th=None, docker_target_name=None, env_args=None, cpu=False, width=84, height=84, quality_level=5, time_scale=20, target_frame_rate=-1)
Traceback (most recent call last):
  File "d:\program dll\gdev\ml-agents-master\ml-agents\mlagents\trainers\trainer_util.py", line 160, in load_config
    with open(config_path) as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config/trainer_config.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\enpetigai\AppData\Local\Programs\Python\Python36\Scripts\mlagents-learn-script.py", line 11, in <module>
    load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')()
  File "d:\program dll\gdev\ml-agents-master\ml-agents\mlagents\trainers\learn.py", line 472, in main
    run_training(0, run_seed, options, Queue())
  File "d:\program dll\gdev\ml-agents-master\ml-agents\mlagents\trainers\learn.py", line 250, in run_training
    trainer_config = load_config(trainer_config_path)
  File "d:\program dll\gdev\ml-agents-master\ml-agents\mlagents\trainers\trainer_util.py", line 163, in load_config
    raise TrainerConfigError(f"Config file could not be found at {config_path}.")
mlagents.trainers.exception.TrainerConfigError: Config file could not be found at config/trainer_config.yaml.

D:\Program DLL\GDev\ml-agents-master\ml-agents>

Also, Unity give me this notification: 
Couldn't connect to trainer on port 5004 using API version API-12. Will perform inference instead.
UnityEngine.Debug:Log(Object)
MLAgents.Academy:InitializeEnvironment() (at Assets/ML-Agents/Scripts/Academy.cs:228)
MLAgents.Academy:LazyInitialization() (at Assets/ML-Agents/Scripts/Academy.cs:147)
MLAgents.Agent:OnEnable() (at Assets/ML-Agents/Scripts/Agent.cs:255)

**Comment by abhilash1910** [comment]
Hi @RogueCMD, I am assuming you git cloned or downloaded the master branch .In the root folder there will be a config folder and a trainer_config.yaml file ( '..\\ml-agents-master\\ml-agents-master\\config\\trainer_config.yaml').Have you tried checking whether it is present.Alternatively you can try out building a sample executable  Unity file and then set the environment to /path/to/buildfile ('https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Executable.md') .Otherwise you can try out running mlagent_learn command('https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Basic-Guide.md').Im guessing you have properly setup the mlagent_envs ,ml_agent via the setup instructions provided at readme.

**Comment by andrewcoh** [comment]
config/trainer_config.yaml is specifying the path to the config file _from the current directory_.  Make sure you are in the directory that contains the config folder when you execute the command.

**Comment by surfnerd** [comment]
hi @RogueCMD, 
from your command prompt you are in a directory below the root directory:
```D:\Program DLL\GDev\ml-agents-master\ml-agents```
you should be in
```D:\Program DLL\GDev\ml-agents-master\```

Please try from that directory and reopen this issue if you still have this same issue.

**Comment by ssshammi** [comment]
Hello I too can't find config/trainer_config.yaml with release 12 under the config folder I have pop, imitation, sac folder. I am trying to follow the tutorial from this page https://github.com/Unity-Technologies/ml-agents/blob/release_2_verified_docs/docs/Getting-Started.md
