### ISSUE TITLE
Unity Editor freezes

### ISSUE THREAD

**Issue by sonfiree** [Unity-Technologies/ml-agents#3117]
The editor hangs when learning.
Windows 10
Tensorflow 2.0 CPU
Unity 2019.2.15.f1

**Comment by sonfiree** [comment]
Downgrade TF to 1.14

**Comment by chriselion** [comment]
Do you have any more information on what it was doing when it froze? Was there an exception on the python side? Tensorflow shouldn't directly affect anything that happens with the editor.
