### ISSUE TITLE
Command line arguments for Unity don't work

### ISSUE THREAD

**Issue by dimok135** [Unity-Technologies/ml-agents#3118]
**Describe the bug**
When I pass --time-scale=100 to Unity as written in the documentation, I get the message "mlagents-learn: error: unrecognized arguments: --time-scale=100".

mlagents-learn "ML_AGENTS\config\trainer_config.yaml" --run-id=Ml_Agents_2019_unity_proj --train --time-scale=100

I'm using Portable Python 3.6.5 Basic (x64) R2. Learning works well without time-scale parameter.

**To Reproduce**
1. Download Portable Python 3.6.5 Basic (x64) R2 from here: [https://sourceforge.net/projects/portable-python/files/Portable%20Python%203.6.5/](https://sourceforge.net/projects/portable-python/files/Portable%20Python%203.6.5/)
2. Install ml-agents. Copy cuda libraries (cublas64_100 and other) to python dir.
3. Create bat file   path_to_python\App\Python\Scripts\mlagents-learn "ML_AGENTS\config\trainer_config.yaml" --run-id=Ml_Agents_2019_unity_proj --train --time-scale=100

**Console logs / stack traces**

```
C:\Portable_Py3.6.5_with_mlagents_(Must_be_on_disk_C)>App\Python\Scripts\mlagent
s-learn "ML_AGENTS\config\trainer_config.yaml" --run-id=Ml_Agents_2019_unity_pro
j --train --time-scale=100
WARNING:tensorflow:From c:\portable_py3.6.5_with_mlagents_(must_be_on_disk_c)\ap
p\python\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:65: disabl
e_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated a
nd will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term


                        ▄▄▄▓▓▓▓
                   ╓▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄

          ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌

        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
          ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓▌
                        ┐`▀▀▀█▓


 Version information:
  ml-agents: 0.12.1,
  ml-agents-envs: 0.12.1,
  Communicator API: API-12,
  TensorFlow: 2.0.0
usage: mlagents-learn [-h] [--env ENV_PATH] [--curriculum CURRICULUM_FOLDER]
                      [--sampler SAMPLER_FILE_PATH]
                      [--keep-checkpoints KEEP_CHECKPOINTS] [--lesson LESSON]
                      [--load] [--run-id RUN_ID] [--num-runs NUM_RUNS]
                      [--save-freq SAVE_FREQ] [--seed SEED] [--slow] [--train]
                      [--base-port BASE_PORT] [--num-envs NUM_ENVS]
                      [--docker-target-name DOCKER_TARGET_NAME]
                      [--no-graphics] [--debug] [--multi-gpu] [--env-args ...]
                      [--cpu] [--version]
                      trainer_config_path
mlagents-learn: error: unrecognized arguments: --time-scale=100
```

**Environment**
Windows 7 x64 SP1
Unity 2017.4.34 f1

Version information:
  ml-agents: 0.12.1,
  ml-agents-envs: 0.12.1,
  Communicator API: API-12,
  TensorFlow: 2.0.0

**Comment by andrewcoh** [comment]
Hi,

I assume you're looking at the docs on master. Try these instead https://github.com/Unity-Technologies/ml-agents/tree/latest_release

**Comment by dimok135** [comment]
Thank you! I really confused releases. The latest one works fine.

**Comment by hikariakio** [comment]
I am having same problem..how do you solve it?

**Comment by dimok135** [comment]
> I am having same problem..how do you solve it?

Hi. I used "UnitySDK" from latest_release. Then use speed slider in Academy component in Unity.
