### ISSUE TITLE
On demand decisions - help highly appreciated

### ISSUE THREAD

**Issue by skwosh1** [Unity-Technologies/ml-agents#3119]
Hey, I am trying to apply the decision on the demand in the agent, but the documentation on this issue is not too extensive.  After selecting the decision on demand bool in the interface,  agent does not initialise.  

On demand decisions have been added in the fixed update as I found in the example.  Do you have any idea where to look for errors in my code? 

<img width="574" alt="Screen Shot 2019-12-22 at 11 08 43" src="https://user-images.githubusercontent.com/51817399/71328591-d53a4f80-2519-11ea-9ad0-edf176b2281d.png">

**Comment by kevtan** [comment]
Could you be a little bit more specific when you say "the agent does not initialize?" It sounds like nothing is crashing, but I'm not quite sure. Are you training with your environment using the low-level Python API or the `mlagents-learn` command line tool?

**Comment by skwosh1** [comment]
Thanks Kevtan for answer, I tried through Python API and found my mistake. Thanks.
