### ISSUE TITLE
Project Organization and Documentation

### ISSUE THREAD

**Issue by aaronflippo** [Unity-Technologies/ml-agents#312]
Hey folks, the way the project is laid out here on Github is very confusing for beginners:

1. There is a github repo here that contains a variety of samples, and does *not* contain the Tensorflow plugin that's needed to actually run trained brains in a runtime.

2. The documentation links to a Unity package, which contains TensorflowSharp, and the same samples as the repo, and none of the python necessary to do the training.

So the setup process for someone who wants to get started with TensorflowSharp, seems to be:
a. Clone the repo, and open the Unity project in it.
b. Download the Unity project linked in the documentation and import it, replacing the samples etc.

Might I suggest adding TensorflowSharp to the git repo so that it contains everything someone needs to get started, and then updating the instructions?

**Comment by vincentpierre** [comment]
Hi, 
The documentation regarding the In Editor inference is [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-TensorFlow-Sharp-in-Unity-(Experimental).md#requirements) It contains a link to the TensorflowSharp plugin alone which can be imported to your cloned project by using `Assets -> Import Package -> Custom Package` in the Unity Editor. It is true that the process is currently quite long to get started. We originally though of TensorflowSharp as an add-on to be added after training in Python was successful. Thank you for your feedback.
