### ISSUE TITLE
How to create a multi player(brain?) game?

### ISSUE THREAD

**Issue by TheoLvs** [Unity-Technologies/ml-agents#3120]
Hello everyone, 

I am a real beginner with Unity & ML agents, so please point it out if the answer is obvious and I missed it. 

I am looking to create a game/environment for an AI class I am teaching with the following goals:
- Creating a core environment for a **1 player vs 1 player game** (could be chess or really any 1v1 game) and _run it on a server_
- Connecting 2 separate Python scripts controlling each player _to be run on 2 local machines_

The ultimate goal is for the students to create their AI to fight each other, and for the best AI to win. AIs would not necessarily be RL-controlled, some students would probably create simple symbolic ones. 

I use to have myself a teacher who created such a game with a Java engine and sockets for each player to connect to the main game, but I was wondering if it could be simply created with Unity + ML-Agents. 

Thanks a lot for your answers! 😎
Theo

**Comment by andrewcoh** [comment]
Related to issue [2739](https://github.com/Unity-Technologies/ml-agents/issues/2739). Our Tennis and Soccer example environments may be helpful.  Additionally, we are working on adding a self-play feature to the toolkit for exactly this case.  The issue referenced above contains a link to a self-play PR that people have had luck with.

**Comment by harperj** [comment]
@TheoLvs Regarding using custom training scripts from multiple sources-- you could use the low-level [environment API](https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents-envs/mlagents_envs/environment.py) or the gym wrapper to split observations out to multiple trainers and merge them back into a single message to the environment.  The environment APIs are what you'd use if you want this type of custom control.
