### ISSUE TITLE
Tail RayPerception Sensor

### ISSUE THREAD

**Issue by borisneal** [Unity-Technologies/ml-agents#3123]
**Is your feature request related to a problem? Please describe.**
An agent has eyes on the back and should be able to use RayPerception sensor which currently doesn't support "tail" cones.

**Describe the solution you'd like**
A parameter in RayPerception-based components that would allow the sensor to flip backwards

**Describe alternatives you've considered**
Using legacy perception right now

**Additional context**
The particular problem is a simulation where a car is taught to park. It can detect/enter a spot driving forward or backward.

**Comment by ervteng** [comment]
This will be added in the next release, and is already possible on the `master` branch. You can apply the changes to the Unity-side SDK from this PR: https://github.com/Unity-Technologies/ml-agents/commit/ebad90f564bc03678da167ea40e6ec2fc1574a87

Basically this change allows you to add a RayPerceptionSensor to a child gameobject - so you could add a "BackwardsSensor" child to the agent, and flip the transform 180 degrees.

**Comment by borisneal** [comment]
Perfect, thanks.
