### ISSUE TITLE
'Google' could not be found when building for iOS

### ISSUE THREAD

**Issue by chechulinYuri** [Unity-Technologies/ml-agents#3125]
Can't build for iOS
I get a lot of errors like:
> Assets/ML-Agents/Scripts/DemonstrationStore.cs(3,7): error CS0246: The type or namespace name 'Google' could not be found (are you missing a using directive or an assembly reference?)

Barracuda is installed 0.3.2-preview
Unity 2019.2.17 and 2018.4.14 both have the same errors
macOS Catalina 10.15.1
ml agents 0.12.1 #latest_release  
TensorFlow 1.7.1

I tried to build the project with custom environment or with just empty project with UnitySDK only
I tried with and without the ENABLE_TENSORFLOW Scripting defined symbol
I selected .NET 4.x

I successfully trained the network on my Mac, but I can't build the project for iOS. I want to train bots for my game and use the behaviour in iOS game.

**To Reproduce**
1. Go to File->Build settings->Build
2. See a lot of errors in the console right after click

I have 145 errors in the console. There are some of them:

> Assets/ML-Agents/Scripts/Grpc/CommunicatorObjects/AgentAction.cs(8,20): error CS0400: The type or namespace name 'Google' could not be found in the global namespace (are you missing an assembly reference?)

> Assets/ML-Agents/Scripts/Grpc/CommunicatorObjects/AgentAction.cs(10,21): error CS0400: The type or namespace name 'Google' could not be found in the global namespace (are you missing an assembly reference?)

> Assets/ML-Agents/Scripts/Grpc/CommunicatorObjects/AgentAction.cs(9,21): error CS0400: The type or namespace name 'Google' could not be found in the global namespace (are you missing an assembly reference?)

> Assets/ML-Agents/Scripts/Grpc/CommunicatorObjects/BrainParameters.cs(173,28): error CS0115: 'BrainParametersProto.ToString()': no suitable method found to override

> Assets/ML-Agents/Scripts/Grpc/CommunicatorObjects/DemonstrationMeta.cs(137,26): error CS0115: 'DemonstrationMetaProto.Equals(object)': no suitable method found to override

**Comment by chechulinYuri** [comment]
Anyone using ml-agents on iOS or Android?

**Comment by surfnerd** [comment]
Hi @chechulinYuri,
Could you turn off `dead code stripping` in your Xcode project?  This may prevent these build errors from popping up.  We are tracking a similar issues for ML-Agents not working with IL2CPP, and this sounds related.  Thanks for your feedback.

**Comment by surfnerd** [comment]
Please follow this issue for updates on this bug. #2595

**Comment by surfnerd** [comment]
I am going to close this in favor of #2595 and have updated our internal issue MLA-94 with this issue.

**Comment by chechulinYuri** [comment]
@surfnerd  thank you for the reply, but there is nothing similar with my issue.

> Could you turn off dead code stripping in your Xcode project
I don't have an Xcode project because errors pop up right after I press the Build button in unity

**Comment by chechulinYuri** [comment]
I think the issue should be opened because I don't have any solution of my problem

**Comment by surfnerd** [comment]
Hi @chechulinYuri,
Have you installed the Barracuda plugin from package manager?  It includes the google protobuf library and is required for ml-agents to work.

**Comment by surfnerd** [comment]
Hi @chechulinYuri,
Please refer to #3167,  It seems to be a barracuda related issue.  My apologies for the miscategorization.

**Comment by surfnerd** [comment]
Hey @chechulinYuri,
Please refer to https://github.com/Unity-Technologies/ml-agents/issues/3167#issuecomment-571351815

for a potential workaround for this issue.

**Comment by surfnerd** [comment]
Hi @chechulinYuri,
This was fixed in barracuda version 0.6.0-preview.  You can find their changelong [here](https://docs.unity3d.com/Packages/com.unity.barracuda@0.6/changelog/CHANGELOG.html) and will be in the 0.15.0 release of ML-Agents.
