### ISSUE TITLE
How to "retrain" starting from a model?

### ISSUE THREAD

**Issue by bwubrian** [Unity-Technologies/ml-agents#3127]
This is a pretty naive question but is it possible to begin training a new model based off of a previous model instead of from scratch? In training I find that sometimes the environment just stops before finishing, but saves its latest .nn model. When I give this model to the agent and just run in the Editor, it behaves as expected(agent not optimal but clearly trained to some degree). But when I try to train again, even with the partially-complete model on the agent, it seems like its just starting from scratch rather than starting from the given model and improving upon it.

**Comment by markus-weiss** [comment]
Hey, 

if I understand u right u need to load a already trained model. See the [https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-ML-Agents.md](doc) on command line training options `--load` to:

```
--load: If set, the training code loads an already trained model to initialize the neural network before training. The learning code looks for the model in models/<run-id>/ (which is also where it saves models at the end of training). When not set (the default), the neural network weights are randomly initialized and an existing model is not loaded.
```

**Comment by mbaske** [comment]
Please also see this issue
https://github.com/Unity-Technologies/ml-agents/issues/1047#issuecomment-409660869

**Comment by bwubrian** [comment]
Thanks, this is what I was looking for!
