### ISSUE TITLE
Testing demo_loader.py

### ISSUE THREAD

**Issue by kevtan** [Unity-Technologies/ml-agents#3130]
Hi, I'm interested in benchmarking the performance of the demonstration loading utilities, but am having trouble actually running the functions. I went to the `ml-agents` directory and ran `pip install .` in order to install the python package from the git repository and then tried to run `python mlagents/trainers/demo_loader.py` but am getting the following error message:

```
Traceback (most recent call last):
  File "demo_loader.py", line 6, in <module>
    from mlagents.trainers.buffer import AgentBuffer
ModuleNotFoundError: No module named 'mlagents.trainers'
```

I was wondering why it can't find `mlagents.trainers`?

**Comment by harperj** [comment]
Hi @kevtan -- did you follow the full [installation guide](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md) and specifically the part about installation for development?

Another issue I see with what you're doing here is that `demo_loader.py` has no main function; so nothing will be executed when you run this file.  If you're looking to benchmark it you'd need to have a script that imports `mlagents.trainers.demo_loader.XYZ` and then uses/times it.

**Comment by kevtan** [comment]
Hi @harperj thanks for the link to the installation guide! I hadn't seen it before but it seems to be exactly what I need. I've followed the instructions carefully but, regrettably, am still running into issues. I created a brand new Anaconda environment (Python 3.7.4), cloned the `latest_release` tagged version of the repository (0.12.1), and performed the `pip3 install -e ./` steps for both the `mlagents` and `mlagents_envs` subdirectories but still am getting errors. For instance,

```
➜ python
Python 3.7.4 (default, Nov 22 2019, 15:36:53) 
[Clang 7.3.0 (clang-703.0.31)] :: Intel(R) Corporation on darwin
Type "help", "copyright", "credits" or "license" for more information.
Intel(R) Distribution for Python is brought to you by Intel Corporation.
Please check out: https://software.intel.com/en-us/python-distibution
>>> import mlagents
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'mlagents'
>>> ^D
```

Here are the results of running `pip list` and `conda list`, respectively. I don't see the mlagents packages being listed here. Are they supposed to be?

```
➜ pip list          
Package     Version            
----------- -------------------
certifi     2019.9.11          
mkl-fft     1.0.15             
mkl-random  1.1.0              
mkl-service 2.3.0              
numpy       1.17.4             
pip         19.1.1             
setuptools  41.0.1.post20191122
six         1.12.0             
TBB         0.1                
wheel       0.31.0 
```

```
➜ conda list          
# packages in environment at /Users/tankevin/anaconda3/envs/unity:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                         0    intel
certifi                   2019.9.11                py37_0    intel
icc_rt                    2020.0                intel_166    intel
intel-openmp              2020.0                intel_166    intel
intelpython               2020.0                        1    intel
libffi                    3.2.1                        11    intel
mkl                       2020.0                intel_166    intel
mkl-service               2.3.0                    py37_0    intel
mkl_fft                   1.0.15           py37ha68da19_3    intel
mkl_random                1.1.0            py37ha68da19_0    intel
numpy                     1.17.4           py37ha68da19_4    intel
numpy-base                1.17.4                   py37_4    intel
openssl                   1.1.1d                        0    intel
pip                       19.1.1                   py37_0    intel
python                    3.7.4                         3    intel
setuptools                41.0.1                   py37_0    intel
six                       1.12.0                   py37_0    intel
sqlite                    3.29.0                        0    intel
tbb                       2020.0                intel_166    intel
tbb4py                    2020.0             py37_intel_0    intel
tcl                       8.6.4                        24    intel
tk                        8.6.4                        29    intel
wheel                     0.31.0                   py37_3    intel
xz                        5.2.4                h1de35cc_7    intel
zlib                      1.2.11               h1de35cc_7    intel
```

Also, I know that `demo_loader.py` has no main function; I was just trying to run it to try to figure out all the import issues. Thanks for the suggestion about importing and then timing it though! That's precisely what I plan to do once I figure this out.

**Comment by kevtan** [comment]
Okay, I was able to fix the issue by changing `pip3` to `pip`.  Now, `pip list` yields the following:

```
➜ pip list         
Package              Version             Location                                                 
-------------------- ------------------- ---------------------------------------------------------
...
mlagents             0.12.1              /Users/tankevin/Documents/GitHub/ml-agents/ml-agents     
mlagents-envs        0.12.1              /Users/tankevin/Documents/GitHub/ml-agents/ml-agents-envs
...
```

And `conda list` yields the following:
```
➜ conda list        
# packages in environment at /Users/tankevin/anaconda3/envs/unity:
#
# Name                    Version                   Build  Channel
...
mlagents                  0.12.1                    dev_0    <develop>
mlagents-envs             0.12.1                    dev_0    <develop>
...
```

After doing some more digging, I found that the reason I was having errors was because my `pip3` was not installing into my anaconda environment. A quick `which` check gave the following:

```
➜ which pip 
/Users/tankevin/anaconda3/envs/unity/bin/pip
➜ which pip3
/usr/local/bin/pip3
```

I hope this helps anyone who's interested in installing these packages in the future!
