### ISSUE TITLE
Spelling of Behaviour/Behavior inconsistent with Unity

### ISSUE THREAD

**Issue by MHDante** [Unity-Technologies/ml-agents#3131]
**Describe the bug**
Spelling of Behavior in `BehaviorParameters` and `BehaviorType` is inconsistent with unity's `MonoBehaviour`

**Comment by chriselion** [comment]
Hi @MHDante,
The Unity coding standard 
```
Spell words using correct US-English spelling. Note that there are a few legacy exceptions that use GB-English that we must preserve, but do not add new ones.
```
(sorry, I don't know of a public version of this for reference). MonoBehaviour is one of these legacy exceptions, but ML-Agents shouldn't use that spelling.
