### ISSUE TITLE
Request: Curriculum Training Overrides Academy Reset Parameters

### ISSUE THREAD

**Issue by afewvowels** [Unity-Technologies/ml-agents#3132]
Hello, I would like to make a request that when using a curriculum, that the curriculum overrides the academy's initial reset parameters. As it currently is, I have to make sure my academy reset parameters match the first set of parameters in my curriculum when I build the scene. Changing later stages of the curriculum is no problem, just tweak the curriculum json file and I'm good to go. However if I want to change the initial settings of the ~~academy~~ curriculum, I need to rebuild the environment.

If this is not possible, I would like to make a request to modify the docs to include a note that the academy parameters will override the curriculum learning if they do not match stage 1 of the curriculum json file.

Thanks for these awesome tools!

EDIT: Said 'academy' instead of 'curriculum'

**Comment by harperj** [comment]
Hi @afewvowels, this sounds like a bug if I'm understanding what you wrote correctly.  Could you share an example of the curriculum config you're using and the behavior you see?

**Comment by afewvowels** [comment]
Sure here's the [config file](https://github.com/afewvowels/unity_00_15_ml-agents_infinite_road/blob/master/infinite%20road/Assets/Config/CarAgent.json) that I'm currently training on:

```json
{
    "measure" : "progress",
    "thresholds" : [0.05, 0.1, 0.15, 0.3, 0.5],
    "min_lesson_length" : 100,
    "signal_smoothing" : true,
    "parameters" :
    {
        "horizontal" : [0.0, 1.0, 1.0, 1.0, 1.0, 1.0],
        "vertical" : [0.0, 0.0, 0.0, 0.0, 1.0, 1.0],
        "hDist" : [0.0, 5.0, 5.0, 8.0, 10.0, 12.0],
        "vDist" : [0.0, 1.0, 1.0, 1.0, 1.0, 1.5],
        "nMin" : [5.0, 15.0, 20.0, 25.0, 30.0, 35.0],
        "nMax" : [20.0, 20.0, 25.0, 35.0, 40.0, 50.0],
        "rMin" : [4.0, 4.0, 5.0, 5.0, 5.0, 5.0],
        "rMax" : [5.0, 5.0, 7.0, 7.0, 7.0, 7.0],
        "minLength" : [3.0, 3.0, 4.0, 8.0, 12.0, 15.0],
        "maxLength" : [4.0, 4.0, 7.0, 12.0, 18.0, 25.0]
    }
}
```

If I set my academy reset parameters to match the first stage of the curriculum values and then do a build, then the curriculum training proceeds according to the documentation. At set intervals in the training progress the academy reset parameters are changed to the values listed in the curriculum, and the scene rebuilds using these values and the scene grows in complexity.

![Good Params](https://raw.githubusercontent.com/afewvowels/unity_00_15_ml-agents_infinite_road/master/images/params_good.png)

If I use parameters (like below) that differ from the initial values in the curriculum and do a build, then the curriculum values are overridden by the build's academy reset parameters and the curriculum never takes place, I just get to the `max_steps` as set in the `trainer_config.yaml` on only one set of academy reset parameters (the parameters set on the academy in the scene when it was built).

![Bad params](https://raw.githubusercontent.com/afewvowels/unity_00_15_ml-agents_infinite_road/master/images/params_bad.png)

So here is the terminal output (sorry, the terminal output is using a build that uses different float values than the one that I listed above so there's a bit of a mismatch in exact values!). It looks like ml-agents loads the scene along with it's parameters (red box) then overrides with the curriculum values (blue box) but the end result (last image) is definitely not stage 1 of the training but instead a very twisty and difficult road to drive:

![Override?](https://raw.githubusercontent.com/afewvowels/unity_00_15_ml-agents_infinite_road/master/images/mismatch.png)

![Definitely not easy mode](https://raw.githubusercontent.com/afewvowels/unity_00_15_ml-agents_infinite_road/master/images/difficult.png)

Let me know if anything else you'd like to know, thanks for your help!

**Comment by harperj** [comment]
Hi @afewvowels -- I've checked and double checked on the latest release of ML-Agents (v0.14) and it seems that if this was an issue at some point it has been resolved.  I'm going to close this issue, but please feel free to re-open and we can try to resolve it together if you are still having trouble with this.
