### ISSUE TITLE
BUG?  gym wrapper's step() returns "BatchedStepResult" instead of "dict" for the fourth param.

### ISSUE THREAD

**Issue by weiziqian** [Unity-Technologies/ml-agents#3133]
the 4th. return parameter ("info") for function step() should be "dict";
however in a recent update (2019 dec 10) it was changed into "BatchedStepResult".

which at least caused troubles when training with baseline,
e.g.:
File "/xxx/stable-baselines/stable_baselines/td3/td3.py", line 343, in learn
    maybe_ep_info = info.get('episode')
AttributeError: 'BatchedStepResult' object has no attribute 'get'

**Comment by chriselion** [comment]
Thanks @weiziqian - this does look like a bug. I've logged it as MLA-486 in our internal tracker, and we should have a fix for it soon.

**Comment by chriselion** [comment]
I believe https://github.com/Unity-Technologies/ml-agents/pull/3136 will fix this, but I want to run it by some other folks that are more familiar with the gym interface.

**Comment by chriselion** [comment]
@weiziqian - this is fixed on `master` branch now, and will be in the next release. Thanks for the report!

**Comment by chriselion** [comment]
I also logged a longer-term issue for us to add better testing around this; we have a few unit tests but no integration tests that run training with the gym wrapper.

**Comment by weiziqian** [comment]
hi Chris, thank you so much for such a prompt response!
