### ISSUE TITLE
Cant load .nn model

### ISSUE THREAD

**Issue by nic126** [Unity-Technologies/ml-agents#3134]
Hi,
I have finished the tutorial on how to create a new environment. 
I am running the following versions:
**ml-agents: 0.12.1**
**ml-agents-envs: 0.12.1**
**Communicator API: API-12**
**TensorFlow: 1.15.0**
**Unity Version 2017.4.35f1**
My own file structure is created as described in the docs.
![ml2](https://user-images.githubusercontent.com/35842664/71554677-c88a8f80-2a22-11ea-90c3-d8a82a1ebd16.PNG)

But I get the following error in my agent:
![ml3](https://user-images.githubusercontent.com/35842664/71554752-d856a380-2a23-11ea-95bc-94f6884504dd.PNG)

I can't load the model file that is created into the agent.
The training process seems to be working fine.

![Shell1PNG](https://user-images.githubusercontent.com/35842664/71554776-2075c600-2a24-11ea-990f-0bde99a4c4b5.PNG)

![ml4](https://user-images.githubusercontent.com/35842664/71554777-25d31080-2a24-11ea-8831-7d32668b0c35.PNG)

I'm not sure if I'm missing something or if the file structure is so correct.
I would appreciate some help. Thanks in advance

**Comment by chriselion** [comment]
Hi @nic126,
You should see something like this in the logs after training is done:
```
Converting ./models/testNoWallDir-0/noWallChaserBrain/frozen_graph_def.pb to ./models/testNoWallDir-0/noWallChaserBrain.nn
```
(I might not have the names exactly right). You'll need to copy that `noWallChaserBrain.nn` into your TFModels directory, then you should be able to assign it in the Behavior Parameters > Model (click on the little circle next to the field).

**Comment by nic126** [comment]
Unfortunately, that didn't work either. I couldn't pull the model into the intended place. The field always remained empty. 
I reset everything back to vanilla and reinstalled it. I must have made a mistake in the installation. Now everything seems to work as it should.
Thank you and Happy New Year.
