### ISSUE TITLE
Way forward for exposing Unity game for evolutionary algorithms that require no training

### ISSUE THREAD

**Issue by zergy** [Unity-Technologies/ml-agents#3139]
Hi, 
I would like to try evolution/genetic algorithm (https://arxiv.org/abs/1704.07075) which require no training a .nn model. My thought is to use gym as an environment and just perform the env.step based on calculating the reward using a forward model.

Anyways, it all works until i want to visualize what is happening, I think the steps are happening too fast, is there a way to slow it so i can see what is happening?

I know mlagents is probably treating it as a training process, but I believe these algorithms can be put directly into the brain without training.

ps. i'm on mlagents 0.10.1 right now, and using the gym-unity folder that came with that version.
I can't do --slow (like https://github.com/Unity-Technologies/ml-agents/issues/833) since i'm not training. I don't think the train_model = true still applies.

**Comment by surfnerd** [comment]
Hi @zergy,
You can change the training configuration in the Academy of the environment you are using by clicking on it in the scene view.  The timeScale property could be set to 1 in order for you to run the simulation in real time instead of sped up time.

**Comment by zergy** [comment]
thanks!
