### ISSUE TITLE
On-Demand Decision issue (No episode was completed since last summary) by Design or Bug?

### ISSUE THREAD

**Issue by crzdg** [Unity-Technologies/ml-agents#3142]
Hi!

I wanted to create an on-deman decision agent which performs a simple throwing task. The task is similiar to the TF-Jam example with a basketball environement. I my scenerio the basketball is replaced with a disc and the basket is replace with a simple target with a receiveing range.

I tried to implement the agent as On-Demand decision agent with the latest **ml-agents release 0.12.1** 

For my understanding I can implement the problem with a On-Demand decision agent as following.

1. Initialize **Agent**
1.1 Get the Components of the Flying Disc (**Disc**)
1.2 Set the **Agent** reference on the **Disc**

2. In the _FixedUpdate_ Method of **Agent**
2.1 Check if the **Agent** __canThrow__
2.1.1 If _True_ he can throw, Call _RequestDecision_ Method
2.1.2 If _False_ he can't throw, check if the _throwIsOver_
2.1.3 If _True_ a throw is over, call _Done_ method
2.1.4 If _False_ a throw is not over, do nothing;

3. In the _FixedUpdate_ method of **Disc**
3.1 Move the disc along the positions of the throw
3.2 If the disc has an _endstate_ **Grounded**, **OutOfBounce** or **Catched**. This calls a **DiscEndstate** on the **Agent**

4. The **DiscEndstate** do _AddReward_ to the **Agent** in respect to the _Discs_ endstate
4.1 At the end the **DiscEndstate** sets _throwIsOver_ to _True_. So _Done_ is called for the next _FixedUpdate_ in **Agent**

The Behavior Parameters settings are,

Observation Space Size: _2_ (x and y Position of receiver, Normalized)
Stacked Vectors: _1_

Vector Action Size: _6_ (Continuous)
Max Step: _0_
ResetOnDone: _True_
On Demand Decisions: _True_

So the implementation is near to the _Bouncer_ example.

**Problem I'm expiricing**

When I start training with the _mlagents-learn_ I get the error of.

`No episode was completed since last summary.`

**However**, the first step summary does include a Episode, but only the first. The _Std. of Reward_ is _0.00_

As investigating I can say if calling _GetEpisodeCount_ on the Academy before a _RequestDecision_ the count does stay on _1_ after the call of the _Done_ a first time.

I tried to implement the tricks mentioned #988, #1169 and #2109. 

How can the Academy by forced to end the episode. The check of the _Academy_ if all agents are _Done_ doesn't same to properly end the Episode in my environment.

Could this problem be cause by a bug of _ML-Agents_ or do I have an error in my design?

**Code Snippet for Disc**

```
    public void Grounded()
    {
        ResetAiredAndThrowPositions();
        agent.DiscGrounded();
    }

    public void Catch()
    {
        ResetAiredAndThrowPositions();
        agent.DiscCatched();
    }

```

**Code Snippet for Agent**

```
    public void DiscGrounded()
    {
        Vector3 distance = onlineDisc.transform.localPosition - receiverTarget.transform.localPosition;
        float distanceReward = (1 - distance.magnitude / 50f);
        if (-50f <= distance.magnitude && distance.magnitude >= 50f)
        {
            distanceReward = -1f;
        }
        AddReward(distanceReward);
        throwIsOver = true;
    }

    public void FixedUpdate()
    {
        transform.LookAt(receiverTarget.transform.localPosition);
        if (canThrow)
        {
            RequestDecision();
            return;
        }

        if (throwIsOver)
        {
            Done();
            return;
        }
        
    }

    public override void CollectObservations()
    {
        AddVectorObs(receiverTarget.transform.position.x - (-49.75f) / (49.75f - (-49.75f)));
        AddVectorObs(receiverTarget.transform.position.z - (-18.25f) / (18.25f - (-18.25f)));
    }


    public override void AgentAction(float[] vectorAction)
    {
        if(canThrow)
        {
            canThrow = false;
            ThrowDisc(vectorAction);
        }

    public void DiscCatched()
    {
        AddReward(1.0f);
        throwIsOver = true;
    }
```

**Comment by surfnerd** [comment]
Hi @crzdg,
Thanks for sharing your issue.  Is there any reason you are calling AgentReceivingAction instead of overriding AgentAction?  I’m not sure what the purpose of this function is.  Usually all of the observations happen in CollectObservations, and the actions happen in AgentAction.  It sounds like you are doing some things outside of this.  In the bouncer example, requestDecision is called inside of the FixedUpdate method, but not much else is done there.  

Can you ensure that you are doing your actions and observations in the appropriate methods?  
Cheers,
Chris

**Comment by crzdg** [comment]
Hi @surfnerd!

Thanks for the quick reply. Sorry not clarifying _ReceivingAction_ Method is used to tell the **Agent** the disc has been receiveid. Receiveid means either **Catched**, **Grounded** or **OutOfBounce**.

For example the disc has touched ground and therefore is **Grounded**, the **Disc** calls _DiscGrounded_ on the Agent. The _DiscGrounded_ does _AddReward_ an sets the _throwIsOver_ flag.


**Code Snippet for Disc**


```
    public void Grounded()
    {
        ResetAiredAndThrowPositions();
        agent.DiscGrounded();
    }

    public void Catch()
    {
        ResetAiredAndThrowPositions();
        agent.DiscCatched();
    }

```

**Code Snippet for Agent**

```
    public void DiscGrounded()
    {
        Vector3 distance = onlineDisc.transform.localPosition - receiverTarget.transform.localPosition;
        float distanceReward = (1 - distance.magnitude / 50f);
        if (-50f <= distance.magnitude && distance.magnitude >= 50f)
        {
            distanceReward = -1f;
        }
        AddReward(distanceReward);
        throwIsOver = true;
    }

    public void FixedUpdate()
    {
        transform.LookAt(receiverTarget.transform.localPosition);
        if (canThrow)
        {
            RequestDecision();
            return;
        }

        if (throwIsOver)
        {
            Done();
            return;
        }
        
    }

    public override void CollectObservations()
    {
        AddVectorObs(receiverTarget.transform.position.x - (-49.75f) / (49.75f - (-49.75f)));
        AddVectorObs(receiverTarget.transform.position.z - (-18.25f) / (18.25f - (-18.25f)));
    }


    public override void AgentAction(float[] vectorAction)
    {
        if(canThrow)
        {
            canThrow = false;
            ThrowDisc(vectorAction);
        }

    public void DiscCatched()
    {
        AddReward(1.0f);
        throwIsOver = true;
    }
```

**Comment by crzdg** [comment]
I did some further research


**Trying to _AddReward_ and _Done_ in the _AgentAction_ Method.**

```
    public override void AgentAction(float[] vectorAction)
    {
           AddReward(Random.Range(-1f, 1f));
           Done()
    }
```

Does lead to the same outcome. Only one episode is completed.

**Trying to set _ResetOnDone_ to _False_ and manually call _AgentReset_**

```
    public void FixedUpdate()
    {
        transform.LookAt(receiverTarget.transform.localPosition);
        if (canThrow)
        {
            canThrow = false;
            RequestDecision();
            return;
        }

        if (throwIsOver)
        {
            Done();
            AgentReset();
            return;
        }
        
    }

```

In this case one episode is done as well. 
Weirdly only the _CollectObservations_ Method gets called the second time when reaching _RequestDecision_. There is no second _AgentAction_ executed.

Can you confirm the correctness of those behaviours?

**Comment by surfnerd** [comment]
Hey @crzdg,
I think you need to reward your agent for behavior you want to encourage it to perform.  Giving it a random reward will give it random behavior.  
Calling done in AgentAction will not help either since your local episode will be completed every step.  

Without your code I cannot effectively help you debug what’s happening with your environment.
Is your repository public? Could you share your code somehow?

**Comment by crzdg** [comment]
Hey @surfnerd,

Sorry for the delay.

I will setup a git repo with my code for review as soon as possible. 
I need to refacctor my code in advance.

I appreciate your help! Thanks for the support!

**Comment by findlabjie** [comment]
Hi, @crzdg 
I got the same error."the first step summary does include a Episode, but only the first. The Std. of Reward is 0.00"
I looked at all the relevant issue(#988, #1169 and #2109.)，but not help.
I always thought the problem was the rewards. Finally,i fixed it, i find that function Done() can't be called immediately after function AddReward(). If you want reset some state after function AddReward(), just call function AgentReset() even though you checked the Reset On Done.  then call function RequestDecision() to next step.
hope that works for you.

**Comment by findlabjie** [comment]
Hi @crzdg 
Have you solved this problem？
I got the same error.
hope your reply and help.

**Comment by crzdg** [comment]
Hi @findlabjie!

I had no time to push this project further. But I will get back to it the next week and will try to tackle the problem once more.

Didn't you provide a solution to this issue?! Somebody told calling Done() right after AddReward() is not working properly and instead of using Done() using AgentReset() should do the trick. Somehow the comment about this isn't here anymore... Did you do an edit? If yes, how come?

**Comment by findlabjie** [comment]
> Hi @findlabjie!
> 
> I had no time to push this project further. But I will get back to it the next week and will try to tackle the problem once more.
> 
> Didn't you provide a solution to this issue?! Somebody told calling Done() right after AddReward() is not working properly and instead of using Done() using AgentReset() should do the trick. Somehow the comment about this isn't here anymore... Did you do an edit? If yes, how come?

Sorry, I misunderstood last time, so I deleted it. but I just had a new idea.
I think:
step means : RequestDecision() ->  CollectObservations() -> AgentAction() -> (next)RequestDecision() -> ......
episode means : A period of the Done() and the next Done().
so, i find your code have the same error as mine.  You call function Done() in every step. That's wrong. when you get Positive reward，you don't need to call function Done(), just reward and reset the state you want. 
In your code , DiscCatched() might look something like this:
`
public void DiscCatched()
    {
        AddReward(1.0f);
       //call reset player position function()
       //call reset disc position function()
      //reset some state
      canThrow = true;
    }
`
I thought it might work for you.
