### ISSUE TITLE
No reward showing on tensorboard when decision interval is greater than 1

### ISSUE THREAD

**Issue by guillefix** [Unity-Technologies/ml-agents#3156]
**Describe the bug**
I have two behaviours in the environemnt, and whenever the decision interval is set to be >1 for either of them, the reward of that one doesn't show on Tensorboard (and indeed it isn't present on the summaries folder). But when the decision interval is set to 1, it does show.

**Environment (please complete the following information):**
- OS + version: Ubuntu 18.10
- _ML-Agents version_: develop branch at commit ebad90f564bc. EDIT: I've tested on latest dev branch, and it seems to have the same issue
- _TensorFlow version_: 1.14.0

**Comment by surfnerd** [comment]
Hi @guillefix,
Thanks for the report.  This, indeed, sounds like a bug.  I've logged this in our internal tracker as  MLA-490.  Any updates to the issue will be posted here.

**Comment by ervteng** [comment]
Hi @guillefix, this bug should have been fixed by PR #3181 and it should work now in both `master` and the new 0.13.0 release.
