### ISSUE TITLE
multiple agents working together

### ISSUE THREAD

**Issue by MinneStephanie2** [Unity-Technologies/ml-agents#3159]
Hey,

I'm trying to make an ai with 4 agent, but the agents need to work as a team. 
I made the 4 different agents with the samen brain parameters, but i'm thinking that they do there onw thing and don't care about the other agents.
What is the best way to make a team of agents?

**Comment by kevtan** [comment]
Hi @MinneStephanie2, I'm doing my best to answer with my limited reinforcement learning knowledge, but I'm not sure you can explicitly _force_ your 4 agents to work as a team. The best thing you can do is to implement a reward schedule that incentivizes the agents to work together. That is, dish out rewards in such a way that the optimal strategy would involve some degree of cooperation with the other agents. If designed correctly, the agents would (hopefully) learn a policy that resembles cooperation.

For reference, consider [OpenAI's Hide and Seek paper](https://openai.com/blog/emergent-tool-use/) where the agents were playing a team-based version of hide and seek. There was no explicit programming to tell the agents to interact with (or cooperate with for that matter) each other, but the rewards given were team-based.

> Agents are given a team-based reward; hiders are given a reward of +1 if all hiders are hidden and -1 if any hider is seen by a seeker. Seekers are given the opposite reward, -1 if all hiders are hidden and +1 otherwise.

In addition to having team-based rewards/penalties, another feature that could encourage inter-agent cooperation is if the agents had access to the state of the other agents on their team. Again, you can find a great example of this in the Hide and Seek paper referenced above. Hope this helps!

**Comment by surfnerd** [comment]
Maybe @andrewcoh could provide some input here as well.

**Comment by andrewcoh** [comment]
Unfortunately, we don't yet have an explicitly multiagent algorithm for cooperative settings.  If you include something that captures the other agents in an agent's observations though (i.e. raycasts that detect the tag of an agent), you may get emergent cooperative behavior. This is basically what is done in the hide and seek paper referenced in @kevtan's comment.
