### ISSUE TITLE
Tennis training mean reward and STD of reward

### ISSUE THREAD

**Issue by cxovrika** [Unity-Technologies/ml-agents#316]
Hello

I am trying to train tennis agent, and i have a question about training, what should mean reward and STD of reward be during the training process? Should they change? And how can i tell if the training goes well or is it enough?

I think my main question is what does mean reward show during the training? Mean reward of all the agents in the scene? If it is so then mean reward should be 0 i guess and std of reward some positive number, but i'm not sure so i'm still asking.

During training both the mean reward and the STD of reward were very close to zero and there was almost no changes during the training. Is this how it is supposed to be?

**Comment by vorrin** [comment]
yeah, seriously, nearly two months on, how can this be so difficult to answer?

**Comment by awjuliani** [comment]
Hi @cxovrika,

In the v0.3 release of ML-Agents we included the hyperparameters we used to train all the example environments, including Tennis. You can find that here: https://github.com/Unity-Technologies/ml-agents/blob/master/python/trainer_config.yaml. We've also additionally updated Tennis to be simpler to train.
