### ISSUE TITLE
Problem Setting up Unity Project with ML-Agents

### ISSUE THREAD

**Issue by kevtan** [Unity-Technologies/ml-agents#3160]
**Describe the bug**
Dragging the `UnitySDK/Assets/ML-Agents` folder into new Unity project leads to compilation errors.

**To Reproduce**
Follow the instructions found [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md).

**Console logs / stack traces**
```
Assets/ML-Agents/Examples/WallJump/Scripts/WallJumpAgent.cs(6,7): error CS0246: The type or namespace name 'Barracuda' could not be found (are you missing a using directive or an assembly reference?)
Assets/ML-Agents/Scripts/Academy.cs(8,7): error CS0246: The type or namespace name 'Barracuda' could not be found (are you missing a using directive or an assembly reference?)
Assets/ML-Agents/Scripts/Agent.cs(4,7): error CS0246: The type or namespace name 'Barracuda' could not be found (are you missing a using directive or an assembly reference?)
...
```

**Environment**
- OS + version: macOS Catalina
- _ML-Agents version_: latest `master` branch from source

**Comment by surfnerd** [comment]
Hi @kevtan,
The installation instructions linked to from the instructions in the link in your comment tell users to install the Barracuda package from Package Manager.  Would you suggest we add a reminder on the Setting up a learning environment page?

**Comment by kevtan** [comment]
This fixed my problem! Yes, that would hopefully save people time in the future. I've created a pull request!

**Comment by muzaffaragha1** [comment]
I tried replacing "using Barracuda;" with "using Unity.Barracuda;" in the scripts where it was showing errors. It solved most of the errors related to barracuda error. I am using unity version 2019.3.0f6. Hope it helps!
