### ISSUE TITLE
Is it possible to "update" a model?

### ISSUE THREAD

**Issue by fredleefarr** [Unity-Technologies/ml-agents#3162]
If I'm training a new model, I can generate one with the following example settings:

<img width="200" alt="NewModel" src="https://user-images.githubusercontent.com/1110286/71783429-88a54880-2fde-11ea-8658-5c70fc6bb559.png">

`mlagents-learn config/mybehavior_config.yaml --train`

I can then drag the generated "testbehavior.nn" into the "Model" section and can see the results of learning by clicking play in the Unity editor.

If I keep the "TestBehavior" in the Model:

<img width="200" alt="NewModel2" src="https://user-images.githubusercontent.com/1110286/71783467-16813380-2fdf-11ea-8647-df7e94aada76.png">

And then re-run the training command again:

`mlagents-learn config/mybehavior_config.yaml --train`

Does the model get updated? I tried testing this and it didn't appear to be "adding" to the model. Is it just a case that models are created once during training, and once done they cannot be changed?

**Comment by Rodnyy** [comment]
Hi, as far as I know, it is possible to continue training the model but not the way you tried. You simply have to run the training command again and add "--load" at the end also do not forget to increase the max steps in the configuration if you already hit it. during previous learning. If you still have any questions regarding this topic I am sure I have seen more detailed answers about this topic here.

**Comment by fredleefarr** [comment]
Many thanks @Rodnyy, will look at the --load option.

**Comment by surfnerd** [comment]
Hi @fredleefarr,
The model that you highlighted in the editor was added there after training.  If you'd like to update your NN model in the editor, look for the end of the training log to see where it is.  You can then drag that file into the editor and use it for inference if you'd like.

**Comment by fredleefarr** [comment]
Thanks @surfnerd - I realise that I need to be careful about using the correct terminology with ML. By "update" I meant "continue to train the model" after initial training. I'll investigate the --load option @Rodnyy mentioned.

**Comment by surfnerd** [comment]
Ah, sorry for my misunderstanding.  I hope you were able to get it to work.
