### ISSUE TITLE
TensorFlow Version 1.5

### ISSUE THREAD

**Issue by alibatiste** [Unity-Technologies/ml-agents#317]
Hello,

I'm using Tensor Flow to do supervised learning. My version of Tensorflow is 1.5 so the graph i'm producing are not compatible with the Unity version which is 1.2. Is there a way to access the plugin Tensorflow 1.5 or 1.4 for unity or to compile it?

Thank  you

**Comment by vincentpierre** [comment]
Hi,
If you need to, you can try to update the TensorFlow libraries in the TensorFlowSharp Plugin. This would require  you to compile TensorFlow with bazel for the appropriate platforms and maybe update the TensorFlowSharp bindings. Here is a link to the [TensorFlowSharp project](https://github.com/migueldeicaza/TensorFlowSharp)  
If you can do the same work on TensorFlow r1.5 and r1.4, I would recommend downgrading your tensorFlow version.
I hope this helps.

**Comment by alibatiste** [comment]
That was my last solution. I start to downgrade my code. It's almost working now, i had to rewrite the importation of data and the export of the "brain".
Thanks you for your answer ;-)
