### ISSUE TITLE
Getting an Error while using tensorflow_to_barracuda.py

### ISSUE THREAD

**Issue by Robin2091** [Unity-Technologies/ml-agents#3172]
Describe what you'd like to discuss.

I have the yolov3 tiny model saved as a .pb file using TensorFlow 2. In the tensorflow_to_barracuda.py file I added this code:

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

When I run the file I get this error:

Traceback (most recent call last):
  File "tensorflow_to_barracuda.py", line 23, in <module>
    tf2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
  File "C:\Users\sudes\Documents\barracuda-release\Tools\tensorflow_to_barracuda.py", line 1331, in convert
    i_model.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message

The model is built in Tensorflow 2 and I have saved the model to a pb file in tensorflow 2. I am running python 3.7. 

Can someone explain what can be causing this issue and how I can solve it? 

**Note**: The ML-Agents team has limited resources for education and community discussion.  We'll participate as we are able, but encourage members of the community to support one another to discuss and support one another.

**Comment by surfnerd** [comment]
Hi @Robin2091,
Unfortunately, TensorFlow 2 isn't officially supported by ML-Agents at the moment.

**Comment by Robin2091** [comment]
@surfnerd Thank you for your reply. Just some things I need to clarify. So Barracuda supports Tensorflow 2 and custom models? Can I use:
https://github.com/onnx/tensorflow-onnx to convert my TF2 model to onnx, or can Barracuda do that.
Thanks

**Comment by surfnerd** [comment]
You will need to convert your model to ONNX yourself to import with Barracuda.
