### ISSUE TITLE
TypeLoadException: Could not find method due to a type load error 

### ISSUE THREAD

**Issue by tomret** [Unity-Technologies/ml-agents#3173]
HI ,
 when i use TFplugin in unity,the unity will show that
TypeLoadException: Could not find method due to a type load error
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at D:/unity/Runtime/Export/Coroutine) ,i could't locate the detail

**Comment by surfnerd** [comment]
Hi @tomret,
What are you using the TFPlugin for?  It is not supported by ML-Agents.  Do you have any more information about when this happens?  Have you added any code?  Please provide more information for us, or the community to help you.
