### ISSUE TITLE
Error in documentation ml-agents

### ISSUE THREAD

**Issue by IRiViI** [Unity-Technologies/ml-agents#3174]
I noticed an issue in the documention: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md

It has the following line:

`public override void AgentAction(float[] vectorAction)`

However this gave me an error due to wrong inputs

So I changed it to:

`public override void AgentAction(float[] vectorAction, string textAction)`

Maybe this is because changes to the new version of ml agents. I downloaded te most recent one with a clean install of Unity3D (2019.2 17f1).

[Error in document ml-agents.pdf](https://github.com/Unity-Technologies/ml-agents/files/4030822/Error.in.document.ml-agents.pdf)

**Comment by surfnerd** [comment]
Hi @IRiViI,
The latest version of ML-Agents doesn't have textActions anymore.  You can find the documentation from the latest release [here](https://github.com/Unity-Technologies/ml-agents/tree/latest_release/docs)

**Comment by IRiViI** [comment]
> Hi @IRiViI,
> ML-Agents on master doesn't have textActions anymore. You can find the documentation from the latest release [here](https://github.com/Unity-Technologies/ml-agents/tree/latest_release/docs)

A thank you! my bad.
