### ISSUE TITLE
Is it possible to capture key presses from executable called by python?

### ISSUE THREAD

**Issue by Solliet** [Unity-Technologies/ml-agents#3175]
I am working on ObstacleTower Challenge and I would like to be able to start and capture keypresses from a user to create demonstrations. Is this possible?

**Comment by surfnerd** [comment]
Hi @Solliet,
Please see the [Imitation Learning Docs](https://github.com/Unity-Technologies/ml-agents/blob/latest_release/docs/Training-Imitation-Learning.md) on how to create demonstrations for learning.  Let me know if that helps you at all.

**Comment by Solliet** [comment]
Hi @surfnerd, thank you for the reply. Unfortunately not much. You see, through IL i'd need a way to parse the demonstrations from python. If I understood this correctly, the demonstrations are used from unity which is a no go for me.

I resorted to using a window from pyglet to capture the keys but I am wondering if there is a more appropriate way to do this.

**Comment by surfnerd** [comment]
Hi @Solliet,
The demonstrations are made in used, and then used by the trainer in python.  This sounds very much like what you are trying to achieve.  Once you record your demo file in unity you can specify it in your training config for pre-training the GAIL network.

**Comment by Solliet** [comment]
Hi @surfnerd 
I am not using the ML-agents scripts to train models as I am working on a custom architecture. I suppose I will either use what I've written or try using the ml-agents/mlagents/trainers/demo_loader.py . Thank you though.

**Comment by Solliet** [comment]
Is it possible to retrieve initialization parameters from the demonstrations file?
