### ISSUE TITLE
RayCast Observations get stopped by agents collider

### ISSUE THREAD

**Issue by Laporasus** [Unity-Technologies/ml-agents#3176]
I'm trying to train some agents using the RayPerceptionSensorComponent2D. After checking the example given in the WallJump Environment, i thought it would suffice to add only the tags of objects, that the ray should actually be able to detect, to the detectable tags. However the rays always stop and "detect" their origin (so the middle of the Agent).
When I disable the collider, the raycast works fine, the agent just falls through the stage.

Does anyone know, how to solve this issue? The agent has a different tag, which should not be detected.

Here's a screenshot of the Agent and the small red indicator, that the raycast hit something.
![Unity_2020-01-07_18-36-22](https://user-images.githubusercontent.com/57869049/71915750-b32d0800-317c-11ea-9abf-c7c99723afcc.png)
Please ask, if you need additional information, I'm not sure what would be helpful here.

**Comment by surfnerd** [comment]
Hi @Laporasus, 
A quick google search revealed [this solution](https://answers.unity.com/questions/756380/raycast-ignore-itself.html) to a similar problem.  Please let me know if that helps.

**Comment by Laporasus** [comment]
Yes, that worked perfectly!
I only searched through the recent issues in here, since i thought this might be a MLAgents-only issue.
Thank you!
