### ISSUE TITLE
Is using the path of the Checkpoint the correct way to freeze_graph as described in the tutorial?

### ISSUE THREAD

**Issue by lagidigu** [Unity-Technologies/ml-agents#318]
Hi,

In the tutorial, freezing the graph in tensorflow is done as follows: 

`freeze_graph.freeze_graph(input_graph = model_path +'/raw_graph_def.pb',
              input_binary = True,
              input_checkpoint = last_checkpoint,
              output_node_names = "action",
              output_graph = model_path +'/your_name_graph.bytes' ,
              clear_devices = True, initializer_nodes = "",input_saver = "",
              restore_op_name = "save/restore_all", filename_tensor_name = "save/Const:0")`

For input_checkpoint = last_checkpoint, is the path to the ckpt file meant? That's the one I am using. 

Every time I export, i get the error Message: 

> google.protobuf.message.DecodeError: Error parsing message

There is no problem if I leave input_binary = False, but obvisouly we need it to be true. 

Thanks a lot in advance for any help!

**Comment by vincentpierre** [comment]
Hi, can you try with this before using freeze_graph?
```python
ckpt = tf.train.get_checkpoint_state(model_path)
last_checkpoint = ckpt.model_checkpoint_path
```
If you are using ppo.py, you should not need to use freeze graph on your own, It is handled automatically.
I hope this helps.

**Comment by lagidigu** [comment]
Still not working :/

`model_name = "ShallowConvNet.pb"
    model_path = tf.train.write_graph(session.graph_def, "", model_name)

    ckpt = tf.train.get_checkpoint_state(model_path)
    last_checkpoint = ckpt.model_checkpoint_path

    freeze_graph.freeze_graph(input_graph = model_path,
                              input_binary = True,
                              input_checkpoint = last_checkpoint,
                              output_node_names = "action",
                              output_graph = "frozen_shallow_convnet_meditation.bytes",
                              clear_devices = True,
                              initializer_nodes = "",
                              input_saver = "",
                              filename_tensor_name = "save/Const:0",
                              restore_op_name = "save/restore_all")`

I then get the error: 

> 'NoneType' object has no attribute 'model_checkpoint_path'

**Comment by mmattar** [comment]
Hi @lagidigu - are you still having this issue or were you able to resolve?
