### ISSUE TITLE
How do you determine the exact Vector Observation Space Size & Stacked Vectors? 

### ISSUE THREAD

**Issue by lazyvainglory** [Unity-Technologies/ml-agents#3190]
![Behavior Param](https://user-images.githubusercontent.com/45304248/72049558-24de9080-32fa-11ea-9e60-43191c312da3.png)

So I modified the basic example and made some changes on BasicAgent script. The script below will randomize the position of the large and small goal. The main objective is that the agent will always go to the large goal. 

 ` public override void InitializeAgent()
    {
        m_Academy = FindObjectOfType(typeof(BasicAcademy)) as BasicAcademy;
    }

    public override void CollectObservations()
    {
        //AddVectorObs(m_Position, 20);
        AddVectorObs(gameObject.transform.localPosition);
        AddVectorObs(largeGoal.transform.localPosition);
    }

    public override void AgentAction(float[] vectorAction)
    {
        var movement = (int)vectorAction[0];

        var direction = 0;

        switch (movement)
        {
            case 1:
                direction = -1;
                break;
            case 2:
                direction = 1;
                break;
        }

        m_Position += direction;
        if (m_Position < m_MinPosition) { m_Position = m_MinPosition; }
        if (m_Position > m_MaxPosition) { m_Position = m_MaxPosition; }

        //gameObject.transform.position = new Vector3(m_Position - 10f, 0f, 0f);
        gameObject.transform.position = new Vector3(m_Position - 10f, transform.parent.position.y, 0f);

        AddReward(-0.01f);

        if (m_Position == m_SmallGoalPosition)
        {
            Done();
            //AddReward(0.1f);
            AddReward(-1f);
        }

        if (m_Position == m_LargeGoalPosition)
        {
            Done();
            AddReward(1f);
        }
    }

    public override void AgentReset()
    {
        m_Position = 10;
        m_MinPosition = 0;
        m_MaxPosition = 20;
        //m_SmallGoalPosition = 7;
        //m_LargeGoalPosition = 17;
        //smallGoal.transform.position = new Vector3(m_SmallGoalPosition - 10f, 0f, 0f);
        //largeGoal.transform.position = new Vector3(m_LargeGoalPosition - 10f, 0f, 0f);

        if (Random.value > .5f) {
            m_SmallGoalPosition = 7;
            m_LargeGoalPosition = 17;
        } else {

            m_SmallGoalPosition = 17;
            m_LargeGoalPosition = 7;
        }

        smallGoal.transform.position = new Vector3(m_SmallGoalPosition - 10f, transform.parent.position.y, 0f);
        largeGoal.transform.position = new Vector3(m_LargeGoalPosition - 10f, transform.parent.position.y, 0f);

    }`

![Observation Size](https://user-images.githubusercontent.com/45304248/72050210-8d7a3d00-32fb-11ea-9743-7a440e0d8469.png)

The script works, the agent will train and it will learn. However, I get a warning message in the console. So I change "Space Size" from 20 to 6 the warning disappear but, when I train, the agent became dumb. It would keep on moving to the left and eventually just stop doing anything. I tried other values like 7 and 8 and got the same warning and behavior. However, I found out that when I change the value to 9 the agent is smart again but I still get the warning.  So is their any way to figure out the correct "Space Size" and "Stacked Vectors," cause the warning message ain't helping.

**Comment by xiaomaogy** [comment]
In this case, you are adding two positions, and each position would have 3 observations, so the correct size is 6. 

Not sure why when you change 6 to 20, it would train, but when it is 6 it doesn't train. Probably something else in your setup that is misconfigured.
