### ISSUE TITLE
UnityAgentsException: The Communicator was unable to connect.

### ISSUE THREAD

**Issue by derwal** [Unity-Technologies/ml-agents#3191]
Hi there, i have an older ml-agents project wich used to work fine about a year ago.
Now im trying to run it on my new mac, but cant figure out why i get this issue.
It must be something simple ?

Unity Tells me:
"UnityAgentsException: The Communicator was unable to connect. Please make sure the External process is ready to accept communication with Unity.
MLAgents.Batcher.SendAcademyParameters (MLAgents.CommunicatorObjects.UnityRLInitializationOutput academyParameters) (at Assets/ML-Agents/Scripts/Batcher.cs:93)
MLAgents.Academy.InitializeEnvironment () (at Assets/ML-Agents/Scripts/Academy.cs:345)
MLAgents.Academy.Awake () (at Assets/ML-Agents/Scripts/Academy.cs:250)"

Im starting the Terminal (iMac OSX 10.15.2).
I run this line "mlagents-learn config/trainer_config.yaml --run-id=myCreatures --train"
And it seems to work fine.
I hit the Playbutton in Unity and i get the error exception from above. 
After a while the terminal goes timeout.
Firewall is turned off.
I set the Unity Playersettings to NET 4.x and the Control (Academy) is checked on.
I dont have a Brain Type to select that i could switch to "external". (dont know why?)
I use a Learning Brain and like i mentioned it used to work fine.

Terminal tells me this:
"Version information:
  ml-agents: 0.13.0,
  ml-agents-envs: 0.13.0,
  Communicator API: API-13,
  TensorFlow: 2.0.0
INFO:mlagents.trainers:CommandLineOptions(debug=False, num_runs=1, seed=-1, env_path=None, run_id='myCreatures', load_model=False, train_model=True, save_freq=50000, keep_checkpoints=5, base_port=5005, num_envs=1, curriculum_folder=None, lesson=0, no_graphics=False, multi_gpu=False, trainer_config_path='config/trainer_config.yaml', sampler_file_path=None, docker_target_name=None, env_args=None, cpu=False, width=84, height=84, quality_level=5, time_scale=20, target_frame_rate=-1)
INFO:mlagents_envs:Listening on port 5004. Start training by pressing the Play button in the Unity Editor.
Process Process-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mlagents/trainers/subprocess_env_manager.py", line 100, in worker
    worker_id, [shared_float_properties, engine_configuration_channel]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mlagents/trainers/learn.py", line 425, in create_unity_environment
    side_channels=side_channels,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mlagents_envs/environment.py", line 125, in __init__
    aca_output = self.send_academy_parameters(rl_init_parameters_in)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mlagents_envs/environment.py", line 512, in send_academy_parameters
    return self.communicator.initialize(inputs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mlagents_envs/rpc_communicator.py", line 101, in initialize
    self.poll_for_timeout()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mlagents_envs/rpc_communicator.py", line 94, in poll_for_timeout
    "The Unity environment took too long to respond. Make sure that :\n"
mlagents_envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Agents are linked to the appropriate Brains
	 The environment and the Python interface have compatible versions.
INFO:mlagents.trainers:Learning was interrupted. Please wait while the graph is generated.
INFO:mlagents.trainers:Saved Model
WARNING:mlagents.trainers:Unable to save to ./summaries/myCreatures-0_timers.json. Make sure the directory exists"

What could be the issue?

Thank you :)

**Comment by sekne18** [comment]
ml-agents had major updates in 1 year, I doubt it will work until you create a new project or try to migrate it.

**Comment by derwal** [comment]
> ml-agents had major updates in 1 year, I doubt it will work until you create a new project or try to migrate it.

thx yea maybe but i downloaded the latest master and everything is fresh (python, mlagents, tf, unity ...). the only thing i kept was the scripts that i wrote for the agent,academy,area and they have no errors.

**Comment by sekne18** [comment]
It's possible that you have mlagents installed outside of the current virtual environment. Try to run` where mlagents-learn`, this will show you if you have installed mlagents outside of the current enviroment or in my case i had 2 versions. Basically it's an installation problem. Other than that try solutions from here: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/FAQ.md#environment-connection-timeout

**Comment by derwal** [comment]
thx for your answers :)
it says "/Library/Frameworks/Python.framework/Versions/3.6/bin/mlagents-learn"
i dont even know what environment means in this context ?

i assume that i have only one and its somewhat global ? or does unity only look inside its own project-folder or something ?

**Comment by derwal** [comment]
it seems that i need to have the barracuda package and that there is no brains anymore ?
so i have to update myself on that first maybe thats the issue :)
sorry to bother
