### ISSUE TITLE
All the gpu memory is occupied in the beginning of training

### ISSUE THREAD

**Issue by SungbinChoi** [Unity-Technologies/ml-agents#3192]
All the gpu memory is occupied in the beginning of training if I experiment with mlagents 0.13.0.
This phenomenon didn't happen until 0.12.1. 
I experimented with 3DBall example on CentOS7, tensorflow 1.13.1.
I both tried PPO and SAC.

**Comment by xiaomaogy** [comment]
Do you know if you are using the tensorflow cpu or the gpu version? Also are you using the xvfb or no graphics mode or xserver to render?

**Comment by SungbinChoi** [comment]
I'm using tensorflow gpu version.
I'm experimenting on my local linux machine. 
It happens in both '--no-graphics mode' is turned on or off.

**Comment by chriselion** [comment]
This was a bug that was fixed in the 0.13.1 release; see https://github.com/Unity-Technologies/ml-agents/pull/3219 for the fix.
