### ISSUE TITLE
Pretraining/Behavioral Cloning doesn't seem to do anything with SAC trainer

### ISSUE THREAD

**Issue by niskander** [Unity-Technologies/ml-agents#3193]
Hi, I'm wondering if Behavioral Cloning is supposed to work with a SAC trainer? The docs only mention that it can be used with PPO, but I took a quick glance at the code and it looks like the "behavioral_cloning" option is at least being parsed by the SAC trainer, so I tried it, but it doesn't seem to do anything, e.g. the Cloning-specific graph doesn't appear in tensorboard.
Is it supposed to work?

**Comment by xiaomaogy** [comment]
Yes it should work. You can refer to the pyramids environment here: https://github.com/Unity-Technologies/ml-agents/blob/master/config/sac_trainer_config.yaml

**Comment by niskander** [comment]
@xiaomaogy That's GAIL not behavioral cloning

**Comment by xiaomaogy** [comment]
We've deprecated BC, and we are push everyone to use GAIL.

**Comment by mnsmuts** [comment]
In case it helps, I think also you have to effectively disable Extrinsic rewards by setting their strength to 0. Extrinsic rewards are enabled by default, as a result I have found that you have to include them in your reward config but set them to 0.
