### ISSUE TITLE
[Help] NullPointerException AddVectorObs

### ISSUE THREAD

**Issue by RespawnFreddy** [Unity-Technologies/ml-agents#3197]
Hey fellas, 

I just added in my CollectObservations() several floats and bools to detect **Version 0.12**

``public override void CollectObservations()
    {
        // Give the enemy Attacking Cooldown information
        AddVectorObs(isAttackingCD);

        // Give the enemy their currentHealth and currentMana information
        AddVectorObs(health);
        AddVectorObs(mana);

        // Give the enemy their Exp and Level
        AddVectorObs(exp);
        AddVectorObs(level);
    }
``

![image](https://user-images.githubusercontent.com/59046164/72132744-06bb7380-3380-11ea-9277-8cc5a9b5baf9.png)

What can i do?

**Comment by RespawnFreddy** [comment]
> 
> 
> Hey fellas,
> 
> I just added in my CollectObservations() several floats and bools to detect **Version 0.12**
> 
> `public override void CollectObservations()
> {
> // Give the enemy Attacking Cooldown information
> AddVectorObs(isAttackingCD);
> 
> ```
>     // Give the enemy their currentHealth and currentMana information
>     AddVectorObs(health);
>     AddVectorObs(mana);
> 
>     // Give the enemy their Exp and Level
>     AddVectorObs(exp);
>     AddVectorObs(level);
> }`
> ```
> 
> ![image](https://user-images.githubusercontent.com/59046164/72132744-06bb7380-3380-11ea-9277-8cc5a9b5baf9.png)
> 
> What can i do?

**Comment by xiaomaogy** [comment]
You can scroll to the top of these exceptions, and you will probably find the true error.
