### ISSUE TITLE
Assertion Error when converting from tensorflow to barracuda

### ISSUE THREAD

**Issue by Robin2091** [Unity-Technologies/ml-agents#3198]
I have a frozen graph file of YOLOv3 tiny model and I am using tensorflow_to_barracuda.py to convert it. 

However, I get this error: 

IGNORED: FusedBatchNormV3 unknown layer
Traceback (most recent call last):
  File "tensorflow_to_barracuda.py", line 26, in <module>
    tf2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
  File "C:\Users\sudes\Documents\barracuda-release\Tools\tensorflow_to_barracuda.py", line 1347, in convert
    process_model(i_model, args)
  File "C:\Users\sudes\Documents\barracuda-release\Tools\tensorflow_to_barracuda.py", line 1209, in process_model
    process_layer(node, o_context, args)
  File "C:\Users\sudes\Documents\barracuda-release\Tools\tensorflow_to_barracuda.py", line 1084, in process_layer
    assert(all_elements_equal(input_ranks))
AssertionError

Note: The model is trained and created on TF2. I created a frozen graph of the model in TF 1.15 and I am using that for the conversion script. 
Does this mean that the model cannot be converted?
Also, I tried to convert to onnx using tf2onnx but when I try to import the .onnx file I get this error on unity 
OnnxLayerImportException: Expected ONNX shape with all dimensions known, instead got 0, 1, 1, 1
Barracuda.ONNXModelImporter.ConvertShapeToBarracuda (System.Int64[] onnxShape, System.String onnxLayout) 
**Note**: The ML-Agents team has limited resources for education and community discussion.  We'll participate as we are able, but encourage members of the community to support one another to discuss and support one another.

**Comment by xiaomaogy** [comment]
@mantasp

**Comment by mantasp** [comment]
@Robin2091 any chance you could share frozen graph of your model (or ONNX file)? no need for trained one, random weights are good enough. Thanks!
