### ISSUE TITLE
Custom ~Agent.cs error - Cannot reshape array

### ISSUE THREAD

**Issue by eagleEggs** [Unity-Technologies/ml-agents#32]
I must be overlooking something, anyone know what this is pointing to? :D

<img width="1073" alt="valueerror_index_uml" src="https://user-images.githubusercontent.com/29800532/30757134-833cb4ee-9f9b-11e7-8b82-0aac26dd3cd1.png">

Maybe this works better...
<img width="1005" alt="valueerror_uml" src="https://user-images.githubusercontent.com/29800532/30757233-e5112f7e-9f9b-11e7-8dad-00f0d053dea8.png">

It occurs no matter how many states I have within the code, and no matter what values I change in the state parameter within inspector.

Also, when states are set to 0 within inspector, there are no errors except for in game - Where it expects 8, which brings us back to the issue :( :

<img width="533" alt="statesexpectederror_uml" src="https://user-images.githubusercontent.com/29800532/30759069-bca08c54-9fa2-11e7-8098-e8482b5420fa.png">

**Comment by awjuliani** [comment]
Hi @eagleEggs, is the state space for the brain set to discrete or continuous? If it is discrete, it will expect a single variable, whose value corresponds to the state (ie `5` corresponds to actions `being in the 5th room` or something like that). If it is continuous, it will expect a list of n variables.

**Comment by awjuliani** [comment]
For all but the most simple environments you likely want to use `continuous` states.

**Comment by eagleEggs** [comment]
Ok, so I do have a list of floats however had it set to discrete. When I changed it to continuous I then get a timeout when loading the environment within Jupyter. Switching back to discrete puts me back to the origin of this issue. So something is hanging it up with the continuous state modes.

**Comment by awjuliani** [comment]
Are you able to run the environment using a player brain for your agent within the editor?

**Comment by eagleEggs** [comment]
Continuous state modes do work in editor however. Super awesome :D I really hope to get this working today so I can develop more logic this weekend >.<

**Comment by vincentpierre** [comment]
You said you get a timeout error when you use continuous states. Are you sure you had your brain set to external ?

**Comment by eagleEggs** [comment]
yes, it is definitely external

**Comment by eagleEggs** [comment]
So I loaded up a few old builds that worked with continuous and they also timeout. Rebooting everything and will test again. Maybe things got locked up over days of building and running these services :/

**Comment by SoylentGraham** [comment]
I get this error if I switch state to discreet. (In case that helps)

**Comment by eagleEggs** [comment]
Back to functioning status...

Not sure why, but adding the build export to my local firewall exception has resolved this (OSX).
Didn't have to do it before Friday - but it was the first time I switched networks since working with this so maybe that had something to do with it.

Also, continuous is working properly thanks to your advice @awjuliani 
I guess when I switched to continuous, it was in the midst of this issue evolving :/

Kind of strange...... But thanks for the help! :D

<img width="377" alt="continuous_mean_reward" src="https://user-images.githubusercontent.com/29800532/30784223-76267562-a11f-11e7-8d0c-b22fbd81737c.png">

**Comment by awjuliani** [comment]
Glad you were able to solve the problem @eagleEggs! 

I will add the OSX firewall recommendation to the Common Issues section of the documentation in case others run into the same issue.

**Comment by eagleEggs** [comment]
If you have a bit more time, I have a general question (I can make a new post if you want).

I'm referencing the Ball3DAgent.cs in order to convert it into a transform.position x/y as opposed to rotation. During the course of the training, nothing changes and the reward mean stays the same. The object keeps redoing a movement that gives a -reward and doesn't adjust itself. I must be missing a key thing here.

**Comment by vincentpierre** [comment]
Can you send us the CollectState method you implemented for the `Ball3DAgent.cs` script? Also, are you sure you are in training mode ? If you were using ppo.py, did you specify `--train`? And if you are using the notebook, did you specify `train_model = True` ?

**Comment by eagleEggs** [comment]
Within the Brain I'm configuring 2 states and 2 actions in the inspector.
(I've attempted more as well).

The collect state has two states:

public override List<float> CollectState(){
List<float> state = new List<float>();
state.Add(this.transform.rotation.x);
state.Add(this.transform.rotation.z);
return state;}

I'm using notebook with PPO.py, train_model = true;

I'm not sure that I'm structuring the action states correctly.
Based on the example, I should be able to specify within agentStep (which seems the easiest method):

if(act[0] ==0f){transform code x);
if(act[0] ==1f){transform code z);

However with debugging, act[0] is always 0f.

**Comment by eagleEggs** [comment]
Kind of confused because with similar code, I can train the demos :/

**Comment by eagleEggs** [comment]
Also, when I map the controls to player actions, they work perfectly. Something is missing to have it step through the actions properly on it's own.

**Comment by eagleEggs** [comment]
No issues now. I needed to rewrite some of my action code.
Thanks for your time, and for developing this cool project :D
