### ISSUE TITLE
is ML agent able to generate neural network graph(layers with weight distribution)???

### ISSUE THREAD

**Issue by smartcharith** [Unity-Technologies/ml-agents#3200]
![layerrs](https://user-images.githubusercontent.com/23386448/72154757-81fc4400-33d7-11ea-866b-e3c3f326e348.png)
is ML agent able to visualize neural network graph(layers with weight initialization)?
I'm doing Research about Autonomous vehicles using ML agent.

need to detailed summaries about the project to present in my research project report.

**Comment by chriselion** [comment]
Hi @smartcharith,
We don't have any built-in visualization of the graph currently. There's a discussion here https://github.com/Unity-Technologies/ml-agents/issues/2518 of how to modify the model saving and visualize with Tensorboard (https://github.com/tensorflow/tensorboard/blob/master/docs/r1/graphs.md)
