### ISSUE TITLE
Demonstration only using 1 vector observation

### ISSUE THREAD

**Issue by mnsmuts** [Unity-Technologies/ml-agents#3205]
Hi, I am creating demonstrations for use in imitation learning. I noticed that the meta data on my demo files always says vector observation size: 1 (should be 212 in this case).
![image](https://user-images.githubusercontent.com/22680369/72227086-62f4e200-3590-11ea-956c-fe509637a278.png)

To test this I tried the example scenes and had the same result with pyramids and walker?

Does anyone have any ideas what might cause this?

Brain parameters:
![image](https://user-images.githubusercontent.com/22680369/72227118-c121c500-3590-11ea-8b55-e4c4fba61c96.png)

System: mlagents 0.12.1, Windows 10, Unity 2019.2.0f1

**Comment by chriselion** [comment]
Hi @mnsmuts,
This is a known bug in the display of demonstration files. Sorry for the trouble...

**Comment by mnsmuts** [comment]
OK thanks, so just the display, not the actual demonstration?

**Comment by chriselion** [comment]
Right, just the display is incorrect.
