### ISSUE TITLE
Installing ML-Agents 

### ISSUE THREAD

**Issue by benmadine** [Unity-Technologies/ml-agents#3208]
Hi there,

I have just installed the most recent ML-Agents package as well as python(3.8.1) and I am making my way through the Installation documentation (https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md). I am currently on the line 'To install the mlagents Python package, run from the command line: xxxx'.

After running the line in the python launcher I receive the error:
 `pip3 install mlagents
  File "<stdin>", line 1
    pip3 install mlagents
         ^
SyntaxError: invalid syntax`

Therefore I tried running on command prompt and received another error: 
`>pip3 install mlagents
'pip3' is not recognized as an internal or external command,
operable program or batch file.`

Is anyone able to help me out or offer some guidance please?

Thanks

**Comment by reubenwong97** [comment]
Hello, are you on Windows OS? If you are using windows, then using pip will do, do not use pip3. Try pip install mlagents and see if it works!

**Comment by benmadine** [comment]
Hi reubenwong97, yea I'm using windows... I will try that and thanks for the help!

If this doesnt resolve the problem, can you think of anything else which may cause this? E.g file locations? 
All my files are being stored in C:\Users\NAME

**Comment by reubenwong97** [comment]
Nope, I don't think so. I believe your main issue is because windows does not recognize pip3. Let me know if the above solution works for you!

**Comment by benmadine** [comment]
Just been able to try it and no luck. Ive attached pictures as well of the console.
![pipinstallmlagents](https://user-images.githubusercontent.com/14904154/72366419-217c4800-36f2-11ea-8299-ddaca55fd5d0.PNG)

**Comment by xiaomaogy** [comment]
I would recommend that you follow the windows guide. https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation-Windows.md

**Comment by benmadine** [comment]
Yea that sorted it, thanks for all your help!
