### ISSUE TITLE
Players training neural networks during gameplay

### ISSUE THREAD

**Issue by kpurens** [Unity-Technologies/ml-agents#3211]
Hello,

First of all - amazing job on the ML framework for Unity! I've been enjoying it very much.

Just a quick question:
Would it be possible for players to train their own Neural Network during gameplay?

I would like to create a game where players could train their own agents, experiment with different parameters, and visually see the results without closing the game.

**Comment by flo-wolf** [comment]
Hello, I was planning on creating a similar application to play around with some cool behaviours. Any update on this?
