### ISSUE TITLE
Is it possible to train the agent while playing the game (real time)?

### ISSUE THREAD

**Issue by iuridosanjos** [Unity-Technologies/ml-agents#3212]
I wanted to do an incremental training while the game is running. Is it possible?
Even if it's needed to train offline first (lots of iterations) and then slowly train while the game is running.

**Comment by xiaomaogy** [comment]
For all of the ppo and sac, we are training while the game is running. We just speed up the game so that the training become faster.

**Comment by iuridosanjos** [comment]
I guess I've expressed myself poorly. I was thinking about real time learning, while the player plays with the agent (bot) and makes the agent learn from the player at that moment.

**Comment by xiaomaogy** [comment]
That's something we've deprecated (Online BC). Usually the learning would require lots of data, and  real time playing is a little bit too slow to generate enough data for learning.
