### ISSUE TITLE
NaN in SAC training

### ISSUE THREAD

**Issue by mnsmuts** [Unity-Technologies/ml-agents#3214]
After 92k steps an agent training to copy a demonstration starts to report:
WARNING:mlagents_envs:An agent had a NaN observation in the environment
and show this in tensorboard:
![image](https://user-images.githubusercontent.com/22680369/72335699-54edb100-36b7-11ea-8988-f31df1d6f92e.png)

Environment has 1 agent with 47 observations and 1 stacked vector, space type is continuous and action space is 4.

mlagents v13, windows 10, config file designed to imitate only:
![image](https://user-images.githubusercontent.com/22680369/72335968-c3cb0a00-36b7-11ea-89a4-489aeed11e5a.png)

I have not seen this before, could it be something to do with the upgrade to v13?

**Comment by chriselion** [comment]
@mnsmuts 
If there is a NaN in your observations, you should definitely try to find out where it's coming from and fix it. I just added some better NaN checks on the C# side (https://github.com/Unity-Technologies/ml-agents/pull/3221), so if you apply those changes, you should get the callstack for where the observations are being added.

**Comment by mnsmuts** [comment]
Great thanks
