### ISSUE TITLE
How can I train an existing model?

### ISSUE THREAD

**Issue by MasterNoob77** [Unity-Technologies/ml-agents#3215]
Hello,

does anyone know how I train an existing model? With this statement:
` mlagents-learn <trainer-config-file> --run-id=<run-identifier>  --train`
I will get a new model, but how can I train the same model i.e. two days later again?
Thank you for your help,
MasterNoob

**Comment by xiaomaogy** [comment]
You could use --load option.

**Comment by MasterNoob77** [comment]
Hey xiaomaogy,
thanks for your reply! So instead of --train, --load, and do I have to name the model?
`mlagents-learn <trainer-config-file> --run-id=<run-identifier> --load` this would be correct?

**Comment by xiaomaogy** [comment]
You could refer to https://github.com/Unity-Technologies/ml-agents/blob/ac4b1a4b91b48cf498c17913b9a68222208a9661/docs/Training-ML-Agents.md for more details. You don't need to name the model.
