### ISSUE TITLE
Unable to retrace demonstrations from python

### ISSUE THREAD

**Issue by Solliet** [Unity-Technologies/ml-agents#3216]
**Describe the bug**
I am loading demonstrations from python using the `from mlagents.trainers.demo_loader`. If I try to retrace the trajectory, i.e. reset and select same action as what is in demo, the agent fails to follow the demonstration.

**To Reproduce**
1. Record a demonstration
2. Replay Demonstration from python

**Environment (please complete the following information):**
- MacOS 10.15.2
- _ML-Agents version_: 0.10.0
- _Environment_: Obstacle Tower

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by xiaomaogy** [comment]
What do you mean by "if I try to retrace the trajectory"? Could you provide more detailed steps?

**Comment by Solliet** [comment]
I can give you code actually

```python
def replay(path, **other_params):
    brain_params, brain_infos, total_expected = demo_loader.load_demonstration(str(path))
    #some initialization and setting up
    env.reset()
     #starting from 1 because it has the previous_action
    for binfo in brain_infos[1:]:
        #process_info extracts the vector of the previous_action
        _,_,_, info = process_info(binfo)
        _,_,_, newinfo = env.step(info.previous_action)
```

**Comment by xiaomaogy** [comment]
In this case you are assuming the environment will always be fixed. In that case if you take the exact same action for every steps, you will be able to retrace the demonstration. 

However the obstacle tower environment is not a fixed environment. So you won't be able to retrace the demo unless you fix the seed that varies the generation of the environment(and maybe other things that might vary, for example physics in unity).

**Comment by Solliet** [comment]
Yes I have it fixed to the same seed as the one from the demo. Hence I posted this as a bug.

**Comment by xiaomaogy** [comment]
Maybe there are something else you need to keep fixed.
