### ISSUE TITLE
Why TensorFlowSharp?

### ISSUE THREAD

**Issue by rygo6** [Unity-Technologies/ml-agents#322]
Using deep learning for AI in games on mobile devices is a subject I have been reading about and experimenting with for the past year. My interest is to come up with a production ready means to deploy ML trained AI on mobile games.

I was very happy to see this ml-agents project from Unity-Technologies, as I presume this means internally you all probably had a similar train of thought. I have cloned the project and run through your documentation and got the example scenes working, I am very impressed by all of it, but one question came to mind.

Why TensorFlow? As I understand TensorFlow is ideally suited for on the server, research, use cases. Whereas something like Caffe2 has been designed around production deployment in consumer apps, on mobile devices. The ml-agents project being built around TensorFlow makes me wonder, is this project not intended to turn into a production ready framework to do AI in deployed games? Is this project more of a research experiment not intended to be used in an actual game? Is it more intended to turn unity into an ML research tool to be used in a lab?

I have been tinkering with getting Caffe2 connected to unity, and built to iOS. My current thought is, if my intention is to get an ML AI running on a released game in iOS, that is probably still the route I should continue on. Is that correct? Or am I misunderstanding something about TensorFlow, Caffe2 and this ml-agents project?

**Comment by eshvk** [comment]
Thank you for your comments. We have taken this feedback into account and we will consider all options as we move towards getting this ready for production.
