### ISSUE TITLE
Is it important to keep the agents visible in the game view?

### ISSUE THREAD

**Issue by lazyvainglory** [Unity-Technologies/ml-agents#3225]
Lets say I have 100 agents training in the scene. But only 6/100 are visible in the game view. Would this affect how fast the agent learn compare to when all 100 are visible in the game view?

**Comment by andrewcoh** [comment]
The number of visible agents would increase the complexity of what needs to be rendered, but not the complexity of the physics solver/training. So, more visible agents might add some rendering overhead.

**Comment by markus-weiss** [comment]
If u want to increase ur training speed with unvisible agents u alternativly use "--no-graphics" in ur training-command.
[https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-ML-Agents.md](Training ML-Agents)

**Comment by lazyvainglory** [comment]
Thank you guys.
