### ISSUE TITLE
Brains file seem to be missing from UnitySDK

### ISSUE THREAD

**Issue by ChunWayne** [Unity-Technologies/ml-agents#3227]
Hello, I was trying to follow the tutorial on making my own environment to train. I am pretty sure that I have set up the installation correctly as there are no red flags from the console.

However I cannot find any "Brain" file in any of the examples. 

![image](https://user-images.githubusercontent.com/59901029/72432950-41376d00-37d3-11ea-8eb2-f2bbd112d7de.png)

I also cannot find the files in the GitHub repo.

Much help will be very appreciated:)

**Comment by ChunWayne** [comment]
Also, when I want to create a brain by right clicking, I do not see an ML-agents option as well as compared to this tutorial I found online.

![image](https://user-images.githubusercontent.com/59901029/72436446-629c5700-37db-11ea-8f41-fab44e7fb2ad.png)

is there something wrong with my installation?

Thank you!

**Comment by chriselion** [comment]
@ChunWayne The tutorial is out of date - Brain ScriptableObjects were removed in version 0.11. If you're following https://www.immersivelimit.com/tutorials/unity-ml-agents-penguins, that originally used 0.8.2, which you can download from here https://github.com/Unity-Technologies/ml-agents/releases/tag/0.8.2. They also have directions on how the tutorial has been changed in recent versions.

**Comment by ChunWayne** [comment]
@chriselion Hi Chris thanks for pointing me to the right direction!
