### ISSUE TITLE
how to post unity3d mlagent

### ISSUE THREAD

**Issue by strikeman1** [Unity-Technologies/ml-agents#3228]
em...I want to know how to issue a exe about mlagent with Trained results

**Comment by andrewcoh** [comment]
Can you clarify? Do you mean you've trained an agent and you'd now like to release a game with the trained agent embedded in it?

**Comment by strikeman1** [comment]
yes,and I made in windows,but I want ti post into linux

**Comment by strikeman1** [comment]
I have try it,but it works well in windows,but when post in linux ,it has an error"Infinity or NaN floating point numbers appear when calculating the transform matrix for a Collider. Scene hierarchy path "trianArea (4)/53a2b34d56e1b"
 
(Filename: ./Modules/Physics/Collider.cpp Line: 226)"

**Comment by andrewcoh** [comment]
This seems like an issue with unity and not ml agents.  You can try posting on the unity physics forums [here](https://forum.unity.com/forums/physics.78/)
