### ISSUE TITLE
Bug in SoccerTwos-Example: The Heuristic method was not implemented

### ISSUE THREAD

**Issue by markus-weiss** [Unity-Technologies/ml-agents#3236]
Hello,
I have cloned the ml-agents-repo and opened the SoccerTwos-Example and hit the play-button but the editor paused and I recived the following errormessage:

```
UnityAgentsException: The Heuristic method was not implemented for the Agent on the PurpleGoalie GameObject.
MLAgents.Agent.Heuristic () (at Assets/ML-Agents/Scripts/Agent.cs:473)
MLAgents.HeuristicPolicy.DecideAction () (at Assets/ML-Agents/Scripts/Policy/HeuristicPolicy.cs:35)
MLAgents.Agent.DecideAction () (at Assets/ML-Agents/Scripts/Agent.cs:909)
MLAgents.Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:407)
MLAgents.AcademyFixedUpdateStepper.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:32)
```

I tested it on "0.12-version", "0.13-version" and with "git clone --branch latest_release" like in the installation-instuction.

Will the heuristic function be implement in future, or does the error lie elsewhere?

Greeting,

markus

**Comment by andrewcoh** [comment]
We currently do not have a model trained for the soccer environment and there is no heuristic method implemented.
