### ISSUE TITLE
NullException with `academy` variable in custom environment guide

### ISSUE THREAD

**Issue by jazzchipc** [Unity-Technologies/ml-agents#3238]
When I run the custom environment I created following [this Unity tutorial](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md) I get the following exception:

```NullReferenceException: Object reference not set to an instance of an object MLAgents.Agent.OnEnable () (at Assets/ML-Agents/Scripts/Agent.cs:255)```

This happens when I try to Play the scene to test the environment using the heuristic (no training involved yet).

When I debug I see that the `academy` variable is null in the following lines (`Agent.cs`, lines 254-255):

```cs
var academy = FindObjectOfType<Academy>();
academy.LazyInitialization();
```

I'm using Unity 2019.2.17f1, Windows 10, Anaconda, MLAgents 0.13.0, TensorFlow 2.0.0 and Python 3.7.

This is a screenshot of the components in my Agent:

![issue-mlagents](https://user-images.githubusercontent.com/12103950/72541760-012bc500-387b-11ea-875c-33e1974a5451.PNG)

The code in the agent's script is the same as the guide provides. Maybe I'm missing something in the scene? Running example environments such as the `3DBall` environment works for me.

Thanks!

**Comment by chriselion** [comment]
The documentation you linked to is for the very latest development version of ml-agents. Please use https://github.com/Unity-Technologies/ml-agents/blob/latest_release/docs/Learning-Environment-Create-New.md instead. The directions are mostly the same, but the section on [Add an Empty GameObject to Hold the Academy](https://github.com/Unity-Technologies/ml-agents/blob/latest_release/docs/Learning-Environment-Create-New.md#add-an-empty-gameobject-to-hold-the-academy) is still necessary in all the released versions of ml-agents.

**Comment by jazzchipc** [comment]
Thank you very much! I'll look into it, and probably tomorrow I can say if it worked :D

Just to understand where I went wrong, the problem was that I installed `ml-agents` from PyPi (which has the `latest_release` tag) instead of installing the `ml-agents` package from the repository directly (using `pip install -e ./`), then I followed the documentation in `master`, correct?

**Comment by chriselion** [comment]
No worries, glad you got it sorted out
