### ISSUE TITLE
Controlling Agents Using Heuristic Is Not So Responsive?

### ISSUE THREAD

**Issue by lazyvainglory** [Unity-Technologies/ml-agents#3245]
Whenever I try to test the controls of my agent it felt so laggy. Sometimes I need to press the key multiple times before it register the action.

`      //My Code For A Four Directional Movement On A Grid
       public override float[] Heuristic() {

        if (Input.GetKeyDown(KeyCode.W)) { // Up
            return new float[] { 1 };
        } 
        
        if (Input.GetKeyDown(KeyCode.A)) { // Left
            return new float[] { 2 };
        }
        
        if (Input.GetKeyDown(KeyCode.S)) { // Down
            return new float[] { 3 };
        }
        
        if (Input.GetKeyDown(KeyCode.D)) { // Right
            return new float[] { 4 };
        }

        return new float[] { 0 };
    }`

But when I use them on Update method it's so responsive. Is this a correct behavior or is something wrong with my implementation?

**Comment by andrewcoh** [comment]
Policies can only change the action after a decision interval has elapsed which corresponds to the number of fixed updates that occur (1 fixed update per frame).  So, the Heuristic function will only be called every n fixed updates. On the other hand, update is called far more frequently than fixed update, so it makes sense that you observe this behavior.  Try turning the decision interval down to 1 and maybe your agent will seem more responsive.

**Comment by lazyvainglory** [comment]
Thank you
