### ISSUE TITLE
Java does not start when I run the executable

### ISSUE THREAD

**Issue by MasterNoob77** [Unity-Technologies/ml-agents#3246]
Hello guys,

I want to build an executable of my game. But if I build one Java does not start, so one of my agents is not walking. But if I click on "Build and Run" it is working. So which options do I have to set to get the executable running?

![grafik](https://user-images.githubusercontent.com/59874993/72613690-9046e480-3930-11ea-8e6d-dcc4bce0acb7.png)

Thanks for your help!

**Comment by andrewcoh** [comment]
Just to be sure, have you followed the instructions in [this doc](https://github.com/Unity-Technologies/ml-agents/blob/latest_release/docs/Learning-Environment-Executable.md)?

**Comment by MasterNoob77** [comment]
Hello, yes, I followed these instructions. But it is still not working.

**Comment by surfnerd** [comment]
Hi @MasterNoob77,
What you mean by "Java doesn't start"?

**Comment by MasterNoob77** [comment]
Hey @surfnerd,
in Unity-Editor my game is working fine. Like I said if I click on "build and run" the game works also fine (because Java starts - one Agent needs Java to play). But if I build a executable the agent who needs Java is not moving (because Java doesn´t start). Is there a problem with my navmash-agent
