### ISSUE TITLE
Typos on Installation.md

### ISSUE THREAD

**Issue by TheSilvandre** [Unity-Technologies/ml-agents#3248]
**Describe the bug**
On the Installation.md file there are a few typos.

**To Reproduce**
Where to find the typos:
1. Go to https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md#package-installation
2. Scroll down to the second paragraph ("To install the Barrcuda")
3. See errors ("Barrcuda" and "Adavanced")

**Screenshots**
Screenshot of the location of the typos:

![Untitled](https://user-images.githubusercontent.com/9055613/72648809-e7ba7400-3973-11ea-9c34-4a040a1e8c7a.png)

**Comment by surfnerd** [comment]
Thanks for your report.  Those are my typos.  I’ll fix them quick.  Thanks 😂

**Comment by surfnerd** [comment]
Fixes are here #3250

**Comment by surfnerd** [comment]
Fixes have been merged into master.  I will close this now.  Thank you again for your feedback.
