### ISSUE TITLE
Requirments tensorflow==1.4.1

### ISSUE THREAD

**Issue by njon336** [Unity-Technologies/ml-agents#325]
New users following https://unity3d.college/2017/10/25/machine-learning-in-unity3d-setting-up-the-environment-tensorflow-for-agentml-on-windows-10/ install guide are having issues with the new requirements.txt
Should the recent change be tensorflow>=1.4.1 ?
My install wasn't working so i changed it back to tensorflow>=1.0 and this solved the problem.
Regards.

**Comment by jorrit5477** [comment]
Same here. On Windows I get the following:
  ```
Could not find a version that satisfies the requirement tensorflow==1.4.1 (from unityagents==0.2.0) (from versions: 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.6.0rc0)
No matching distribution found for tensorflow==1.4.1 (from unityagents==0.2.0)
```

**Comment by vincentpierre** [comment]
Hi, at what part of the tutorial are you facing this issue ?

**Comment by njon336** [comment]
Windows 10 install. Running the command

> pip install .

under the heading **Downloading the Sample Project.**
Error message received is, _Could not find a version that satisfies the requirement tensorflow==1.4.1 (from unityagents==0.2.0) (from versions: 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.6.0rc0)
No matching distribution found for tensorflow==1.4.1 (from unityagents==0.2.0)_

I changed the requirements.txt file back to tensorflow>=1.0 and it worked.

**Comment by vincentpierre** [comment]
Does it work if you replace with `tensorflow==1.4.0` ? 
Could you try it out ?

**Comment by njon336** [comment]
When I installed tensorflow 1.4.0 and changed requirements.txt back to tensorflow>=1.0 it automatically updated to tensorflow 1.5.* after I ran pip install . on the ml agents folder. It worked without the previous error.

**Comment by alibatiste** [comment]
If the plugin of Unity is tensorflow 1.2.0. Shouldn't the version of tensorflow install on the computer be 1.2.0.

**Comment by eshvk** [comment]
Hi @alibatiste, for now even though we are using tensorflow 1.4, the operators we are using for inference are compatible with 1.2 so it is fine. Closing this for now.
