### ISSUE TITLE
What's the lowest and highest reward?

### ISSUE THREAD

**Issue by lazyvainglory** [Unity-Technologies/ml-agents#3252]
I'm trying to fine tune my curriculum, currently I can train my agent to do a task up to 25% of what I want. So I'm trying to find out 

1 What is the lowest positive reward and highest negative reward an agent can get by calling `AddReward();` 
2 What is the lowest and highest accumulated reward?
3 Is it possible to know the accumulated reward on a specific agent?

**Comment by MinneStephanie2** [comment]
Hey,

When you use AddReward than the value has to be between -1 and 1.

**Comment by mbaske** [comment]
> When you use AddReward than the value has to be between -1 and 1.

AFAIK, it is _recommended_ to keep rewards in this range, but training still seems to work fine if I don't. What's the reasoning behind this recommendation?

**Comment by mbaske** [comment]
> Is it possible to know the accumulated reward on a specific agent?

You can call an agent's `GetCumulativeReward()` method.

**Comment by lazyvainglory** [comment]
@MinneStephanie2  > 
> When you use AddReward than the value has to be between -1 and 1.

I guess that makes 1 the highest but what about the lowest? Is 3 decimal place -0.001 or could I go to 6 decimal place -.0.000001?

**Comment by andrewcoh** [comment]
There is no bound on what can be passed to AddReward.  The range of -1 to 1 is recommended for learning stability purposes.

**Comment by MinneStephanie2** [comment]
@lazyvainglory 
> Let me change the question. What is the highest negative reward and the lowest positive reward. Is it 3 decimal +/- .001 or 6 decimal +/- 000001?

Your agent will always try to get a reward as high as posible. You can go as low in that reward as you want.

**Comment by lazyvainglory** [comment]
@andrewcoh @MinneStephanie2  Thank you
