### ISSUE TITLE
Reward doesn't not increase

### ISSUE THREAD

**Issue by MinneStephanie2** [Unity-Technologies/ml-agents#3254]
Hey,

I'm making an ai to control traffic lights. But my reward doen't increase.
![image](https://user-images.githubusercontent.com/32354170/72665896-2cdeb480-3a0d-11ea-998e-a8aa59a32286.png)
My reward systeem:
+1 for 60 cars that cross the intersection
-1/1000 for every stap taken
-1/amountCars point for the amount of cars that wait for green
+0.001 for every car that cross

I don't know what to do to make the reward increase.
any suggestions?

**Comment by lazyvainglory** [comment]
Try using a curriculum 

https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-Curriculum-Learning.md

The idea is you start with a simple task then slowly scale to the main objective.

**Comment by andrewcoh** [comment]
A time step penalty (2nd bullet) may not be right for this type of problem. This is often used if an agent's goal is to end an episode as quickly as possible (find a goal state etc). Also, I don't completely understand the the 3rd bullet.  

Can you describe the problem you're trying to solve and possible give some more info on how you're building the observation/action space?

**Comment by MinneStephanie2** [comment]
@andrewcoh, The 3rd bullet is for giving negative reward to the agent if there are a lot of cars that have a speed of 0. It's for forcing the agent to let the cars drive without stopping. 

The goal of the ai is to make an intersection as efficient as possible. 

The observation are the amount of cars in front of the traffic light, the state of the light (green, red, yellow) and the average waiting time of the cars in front of the light.

The states are 8 different options. The agent has to set the int between 0 and 7 to choose the state.

**Comment by andrewcoh** [comment]
I'd suggest just a positive bonus for every car that crosses (like .01) and some penalty for collisions/cars waiting for green.
