### ISSUE TITLE
Possible Bug with Curriculum Learning on version 0.12.0

### ISSUE THREAD

**Issue by MSauerM** [Unity-Technologies/ml-agents#3255]
Hello,

I want to use curriculum learning on my  custom environment, so I tried to implement it as it is described in the documentation, but getting the error that the parameter is not present in the environment. So I tried to test the curriculum learning with the WallJump environment without any changes, but getting the same CurriculumConfigError as with my custom environment. 

**To Reproduce**

So just using  the WallJump environment  with the console command ``` mlagents-learn config/trainer_config.yaml --curriculum=config/curricula/wall-jump/ --run-id=curriculum-walljumptest --train ``` and running the open scene in the editor is causing the error. No changes made to the curricula-JSON-file.

I think the curriculum learning for the WallJump environment should work without any adjustments or do I have to manually add the parameters somewhere?

**Console logs / stack traces**
The following log is printed for the WallJump environment:

```
File "c:\users\User\anaconda3\envs\ml-agents\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\User\anaconda3\envs\ml-agents\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\Anaconda3\envs\ml-agents\Scripts\mlagents-learn.exe\__main__.py", line 7, in <module>
  File "c:\users\User\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 422, in main
    run_training(0, run_seed, options, Queue())
  File "c:\users\User\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 232, in run_training
    curriculum_folder, env, options.lesson
  File "c:\users\User\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\learn.py", line 300, in try_create_meta_curriculum
    meta_curriculum = MetaCurriculum(curriculum_folder, env.reset_parameters)
  File "c:\users\User\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\meta_curriculum.py", line 43, in __init__
    curriculum = Curriculum(curriculum_filepath, default_reset_parameters)
  File "c:\users\User\anaconda3\envs\ml-agents\lib\site-packages\mlagents\trainers\curriculum.py", line 50, in __init__
    "the Environment".format(key, location)
mlagents.trainers.exception.CurriculumConfigError: The parameter small_wall_height in Curriculum config/curricula/wall-jump/SmallWallJump.json is not present in the Environment
```

**Environment:**
- OS + version: Windows 10
- _ML-Agents version_:  ML-Agents v0.12
- _TensorFlow version_: 1.7.1
- _Environment_: WallJump-Environment

Thank you.

**Comment by andrewcoh** [comment]
Can you tell me what names of the reset parameters are in your Wall Jump Academy script attached to your academy in the wall jump environment?  It should look like this 

![walljumpreset](https://user-images.githubusercontent.com/54679309/72832596-08b3eb00-3c3a-11ea-9e20-118232a9c0c0.png)

**Comment by MSauerM** [comment]
I don't have any of these parameters. Training and Inference Configuration are also not available in my version.

This is the inspector of the academy in my project:
![walljump_academy](https://user-images.githubusercontent.com/32358434/72851484-0d18ec00-3cac-11ea-897b-9d4f7b67b600.PNG)

**Comment by andrewcoh** [comment]
You don't seem to be on the correct tag for version 0.12.

Try 
`git checkout 0.12.0`
and then try running again.

**Comment by MSauerM** [comment]
On branch ```release-0.12.0``` the parameters are there and it works. Thank you for your support.
