### ISSUE TITLE
Reward Design

### ISSUE THREAD

**Issue by TanteVonDante** [Unity-Technologies/ml-agents#3257]
Hi Guys,

I hope you can help me with my question.

I want to do some tests, how the agent behaves on different rewarding systems.

My First reward system was like this:

        float distanceToTarget = Vector3.Distance(this.transform.localPosition, Target.localPosition);

        if (distanceToTarget < 0.4f)
        {

            SetReward(1.0f);

            Done();
        }
        else
        {
            SetReward(-0.01f * distanceToTarget);
        }

So my reward is dependent from the total distance.
But now I want to see what will happen if I change it like this:

        float distanceToTargetx = Vector3.Distance(this.transform.localPosition.x, Target.localPosition.x);
        float distanceToTargety = Vector3.Distance(this.transform.localPosition.y, Target.localPosition.y);
        float distanceToTargetz = Vector3.Distance(this.transform.localPosition.z, Target.localPosition.z);

        if (distanceToTargetx < 0.4f && distanceToTargety < 0.4f && distanceToTargetz < 0.4f)
        {

            SetReward(1.0f);

            Done();
        }
        else
        {
            SetReward(-0.1f * distanceToTargetx);
            SetReward(-0.1f * distanceToTargety);
            SetReward(-0.1f * distanceToTargetz);
        }

It doesn't work. Can someone help me?

**Comment by andrewcoh** [comment]
The `SetReward` function is to set the reward of an entire episode.  You may be expecting the behavior of `AddReward` which accumulates the per time step reward over an agent's episode.

**Comment by TanteVonDante** [comment]
my agent can move in a 3-dimensional space. His task is to touch a surface that appears randomly somewhere. If he succeeds, both agent and target are repositioned randomly. If he does not, both will be randomly repositioned as well. In the ml-agents examples, set reward was used, so I thought that would suit my task, wouldn't it?

I also think that my codelines are wrong?
``` 
float distanceToTargetx = Vector3.Distance(this.transform.localPosition.x, Target.localPosition.x);
float distanceToTargety = Vector3.Distance(this.transform.localPosition.y, Target.localPosition.y);
float distanceToTargetz = Vector3.Distance(this.transform.localPosition.z, Target.localPosition.z);```

thx for your help andrewcoh

**Comment by mbaske** [comment]
> I also think that my codelines are wrong?

Yes, they are. You're passing floats where Vector3s are expected. Try this
`Vector3 targetOffset = Target.localPosition - transform.localPosition;`
`float distanceToTarget = targetOffset.magnitude;`
`float directionToTarget = targetOffset.normalized;`
`float distanceToTargetX = Mathf.Abs(targetOffset.x);`
`float distanceToTargetY = Mathf.Abs(targetOffset.y);`
`float distanceToTargetZ = Mathf.Abs(targetOffset.z);`

**Comment by TanteVonDante** [comment]
thank you very much mbaske. it works!

Do you know if it would make more sense to use "SetReward" or "AddReward"?

**Comment by andrewcoh** [comment]
In this case, AddReward makes more sense.
