### ISSUE TITLE
UnityTimeOutException: The Unity environment took too long to respond

### ISSUE THREAD

**Issue by abhincho** [Unity-Technologies/ml-agents#3258]
Hi 
I  created the RollerBall game environment using this [Create-Environment](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md). I  trained it using `mlagents-learn trainer_config.yaml --run-id=RollerBall --train`. The training was successful and the  brain was saved in  `./models/RollerBall-0/RollerBallBrain`. I wanted to interface this environment with Gym so I built the game using [Build](https://docs.unity3d.com/560/Documentation/Manual/PublishingBuilds.html) and created the .exe for the game. No errors were shown while building the game. 

Now when I try to render the game using gym 
```
env_name = "E:/UnityProjects/RBall/build_env2/RBall"  # Name of the Unity environment binary to launch
env = UnityEnv(env_name, worker_id=0, no_graphics=True)
```
I get the following error:
![image](https://user-images.githubusercontent.com/8470532/72680157-ad201b00-3adc-11ea-9708-ae48fb91a7c0.png)

I am able to see the game  when I set no_graphics=False , but after a time the above error occurs.
I have looked at the following issues [172](https://github.com/Unity-Technologies/ml-agents/issues/172), [929](https://github.com/Unity-Technologies/ml-agents/issues/929) and [1749](https://github.com/Unity-Technologies/ml-agents/issues/1749), but none have been able to solve my problem. 

I have also built both 3DBall and GridWorld and face the same issue in both of them. 
One thing that has been commonly states in all the answers was set 

> brain to external.

 But I am unable to find it in Unity 2019.2.3.f1. 
![image](https://user-images.githubusercontent.com/8470532/72680294-54518200-3ade-11ea-973a-6a9f552557b8.png)

My specifications are as follows:
Unity 2019.2.3.f1 
Windows 10
Python 3.6.10
mlagents==0.13.0
mlagents-envs==0.13.0
gym==0.15.4
gym-unity==0.13.0

**Comment by MinneStephanie2** [comment]
hey,
You can try to set env_name none. Then you have to press play in unity itself.

**Comment by abhincho** [comment]
@MinneStephanie2 : Thank you for your help. I set the env_name to None. Then I pressed play in unity. But I got the following error: `Couldn't connect to trainer on port 5004 using API version API-13. Will perform inference instead.` So I looked into issue [3128](https://github.com/Unity-Technologies/ml-agents/issues/3128). But, I am still facing the same error.
