### ISSUE TITLE
What are the ways to cast Ray Perception Sensor Component 2D forward?

### ISSUE THREAD

**Issue by lazyvainglory** [Unity-Technologies/ml-agents#3259]
Aside from rotating the transform to -90 degrees, is their another way to effective cast the sensor forward?

![image](https://user-images.githubusercontent.com/45304248/72680430-adc4ab80-3af4-11ea-9dc4-16f42ee99a95.png)

**Comment by andrewcoh** [comment]
You can do this by adding a GameObject as a child of the agent, rotate the child 90 degrees in the appropriate direction and then add a raycast script to the child.  In the BehaviorParameters script on the agent, check the box "Use Child Sensors." This way, the agent will use observations collected by its children too.

**Comment by lazyvainglory** [comment]
@andrewcoh Thank you so much, it made things so much easier
