### ISSUE TITLE
Is it possible to get the editor's real time while training?

### ISSUE THREAD

**Issue by lazyvainglory** [Unity-Technologies/ml-agents#3270]
I know I could see the time in the command line, but what about in the editor? Is their a way to get the real time since the training started? And if it's possible how?

Example when not in training I can log the time as a float/double by adding `time += Time.deltaTime`  on update.

**Comment by lazyvainglory** [comment]
@chriselion Thanks. But they get affected too. If I could figure out the speed of the training maybe I could do a `time += (Time.deltaTime * trainingSpeed)`

**Comment by surfnerd** [comment]
Hi @lazyvainglory,
The realTimeSinceStartup property on the Time class explicitly states it’s not affected by timeScale.  If you are seeing this, can you file a bug?  Please test it out.
Cheers,
Chris

**Comment by lazyvainglory** [comment]
@surfnerd My bad! You are right. I was just using the values wrong. Thanks.

**Comment by surfnerd** [comment]
glad you were able to get it working :)
