### ISSUE TITLE
WebGL Build

### ISSUE THREAD

**Issue by benfknzen** [Unity-Technologies/ml-agents#3274]
I cannot get WebGL working properly.

This issue has been mentioned before but with the newer versions I do not know where to go. I can get a windows build working, but not a WebGL build working properly.

I suspect that Unity is trying to communicate with the trainer so I selected all my agents and changed the behavior type to inference only to avoid communicating to anything but Unity.

This message still shows up
Couldn't connect to trainer on port 5004 using API version API-13. Will perform inference instead.

When I build this message shows up.
Assets\ML-Agents\Scripts\Grpc\CommunicatorObjects\AgentAction.cs(9,21): error CS0400: The type or namespace name 'Google' could not be found in the global namespace (are you missing an assembly reference?)

Thanks in advance.

**Comment by Guidosalimbeni** [comment]
same issue... did you find the solution?

**Comment by benfknzen** [comment]
No unfortunately :(

I am taking a break from ML Agents, if you find anything about WebGL build I would appreciate it if you could message me. Thanks Guido

**Comment by Guidosalimbeni** [comment]
I will certainly do it. I think several people are having this issue, so I think I will wait to the next release..
