### ISSUE TITLE
Is it possible to remove the slight pause while training?

### ISSUE THREAD

**Issue by lazyvainglory** [Unity-Technologies/ml-agents#3277]
I don't know why it's necessary to briefly pause the training every couple of second. But I'm just wondering if their is a way to remove it so that the training look smoother?

**Comment by MarcoMeter** [comment]
Do you mean that the environments visually pause for a moment?

If so, this is due to the flow of the training algorithm.
Talking in the case of PPO, at first data is sampled from every agent.
The collected data is then used to update the agent's policy (this is the observed break).
Data is always collected with the most recent policy.

**Comment by lazyvainglory** [comment]
@MarcoMeter Yes that's exactly what I mean. Thanks now it all make sense. Anyways do you know if their is a way to reduce it? Maybe instead of every other second it would happen every minute?

**Comment by MarcoMeter** [comment]
This depends on how much data is being collected for training. In the trainer_config the parameter "buffer_size" specifies how much data is going to be gathered.
And of course the more epochs (num_epochs) are used for training, the longer the optimization process takes.

However, changing these values to shift or shrink the break is not comes of course with a high impact on how the training algorithm performs.

**Comment by lazyvainglory** [comment]
I will try to play with those values. Thanks.

**Comment by MarcoMeter** [comment]
Just be aware that these parameters are only of use for the training algorithm.
They are not intended to give you a better view on the agents training inside your environment.
