### ISSUE TITLE
Periodically Restart Executable Training Option

### ISSUE THREAD

**Issue by GabHook** [Unity-Technologies/ml-agents#3280]
Would be nice to have a command line training option for restarting the Unity executable after every <n> steps.
We are not perfect and our executable currently runs out of memory after like 2 million steps. So it would be nice to have a fresh start of the executable after each <n> steps so I could let the training go overnight without worrying it will crash.
Probably it wouldnt be hard to add either.

**Comment by vincentpierre** [comment]
Thank you for your comments.  We’ve documented your feedback and will prioritize when appropriate.

**Comment by vincentpierre** [comment]
For reference, our internal tracking for the issue : [MLA-558](https://jira.unity3d.com/browse/MLA-558)
