### ISSUE TITLE
Question - Gym .step doesn't make sense

### ISSUE THREAD

**Issue by zergy** [Unity-Technologies/ml-agents#3286]
Hi,

I have the unity environment running in gym. 
I don't quite understand the .step method.I set a break point before the .step and the location can be at (-4.5, -2), and an action is supposed to move it to (-3.5, -2), but a break point after the step moves it to something random like (2.5,0). 

Is this due to the game moving too fast?
Is there a way to see/verify that the agent is behaving the way it is supposed to step by step?

**Comment by vincentpierre** [comment]
Hi,
If you think this is a bug, could you fill out the bug report form?
I do not have enough information to reproduce the error you are describing.

**Comment by zergy** [comment]
Hi I decided to just use Unity as opposed mlagents to solve my problem. closing.
