### ISSUE TITLE
Agent.DecideAction makes up 90+% of update time

### ISSUE THREAD

**Issue by HPlumley** [Unity-Technologies/ml-agents#3288]
I have been attempting to speed up learning as for my game it took about 30M steps to reach near optimal performance which took about 30 hours.

After decreasing the time taken by the game engine to about 1/10th I expected to see a large boost in learning speed however it is only about 30% faster.

I ran training in the editor with profiling and then deep profiling on, this shows that the majority of my update time is being spent on Agent.DecideAction()

Is 4-6ms the normal length of time for the agent to perform decide action? Can anything be done to speed up these calls or reduce how frequently they have to happen?

**Comment by vincentpierre** [comment]
Hi,
Agent.DecideAction is very expensive when training as Data must be sent to Python and back at every call. Unity must also wait for Python to pick an action for each Agent as well as training the neural network of the Agents. 
One way to reduce this time is to batch all Agents decision request together (calling request decision for all Agents at the same fixed update) This allows for fewer (although larger) messages to be sent.
Sending fewer messages is also an option (decreasing the number of calls to RequestDecision per seconds) although this can negatively affect your training (making it harder for Agents to learn since the decisions will be further apart)
Reducing the size of the neural network being trained is also an option but the Agents might not be as good.

**Comment by HPlumley** [comment]
Hi Vincent, thanks for the info.

Is 5ms the typical length of one of these requests? So 200 steps/sec is the max one environment can manage.

I'm using num-envs to speed up training but only saw a 2x to 3x speed up even with 8 or 16 envs running. Does this mean that the limiting factor is the speed python can process and send out actions and there is nothing I can do to speed that up without reducing the complexity of the model?

My environment can only support a single agent so I don't think I can do any batching of RequestDecision. It also requires a decision at every update as it is turn based. I do use action masking and sometimes there is only one action available to the agent in a specific state. Could I choose that action for the agent and still have it learn from the decision or would it not be able to learn anything if I don't call RequestDecision that update?

Thanks again for your support

**Comment by vincentpierre** [comment]
The communication time depends a lot on the amount of data that needs to be exchanged between Unity and Python. Python needs time to select actions and we have ongoing efforts to make the training faster. Unfortunately, there is not much you can do by modifying the game to speed Python up (besides reducing the amount of data exchanged).
When doing reinforcement learning, the Agent must be making the decisions. If you want, you can record some demonstrations and use them to do [behavioral cloning](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-Imitation-Learning.md).

**Comment by HPlumley** [comment]
Thanks for the extra response, I'll have a go with behavioral cloning and see if that makes a significant difference.

I have one last question about the training performance: Looking at my CPU, GPU and memory utilisation, it is not clear what is constraining the training speed. CPU usage for each environment is between 0.5 and 1%, CPU usage for the main Python process is around 17%, less than 1% for the others. GPU cuda usage is around 30% and copy around 15%. Memory is only using a few GB.

What is the limiting factor that prevents any of this from running faster and using more of my system resources? I thought maybe Python was stuck on one core, but CPU usage is fairly evenly spread between all 8 cores - none are near 100%.
