### ISSUE TITLE
[Question/Feature Request] I would like to get Depth Image for observation

### ISSUE THREAD

**Issue by intuinno** [Unity-Technologies/ml-agents#329]
Hello, 

First, thank you for the great environment.  I was using ViZDoom and I would like to build my next environment on unity.  However, one issue that I could not find an answer is how I can get a depth image, depth buffer as an observation. Is it possible in current ml-agents 2.0? Or not, may I request this as an additional feature for a future release? 

Thanks.

**Comment by eshvk** [comment]
Thank you for your request, we’ve added this into our backlog and will prioritize when appropriate
