### ISSUE TITLE
Basic-Guide.md refers to 3DBallLearning and Model that don't exist

### ISSUE THREAD

**Issue by ForrestTrepte** [Unity-Technologies/ml-agents#3292]
[Basic-Guide.md](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Basic-Guide.md) says `In the Project window, drag the 3DBallLearning Model located in Assets/ML-Agents/Examples/3DBall/TFModels into the Model property under Ball 3D Agent (Script) component in the Inspector window.`

However, under [3DBall/TFModels](https://github.com/Unity-Technologies/ml-agents/tree/master/UnitySDK/Assets/ML-Agents/Examples/3DBall/TFModels) I only see 3DBall.nn and 3DBallHard.nn with no 3DBallLearning.nn.

Also, this refers to a Model property under the Ball 3D Agent (Script) component, but I don't see a Model property there in the inspector.

Is the documentation out of date regarding this step?

**Comment by chriselion** [comment]
Thanks for catching this. We updated the relevant documentation.
