### ISSUE TITLE
Can this be used to run pre-trained Tensorflow model in unity (not reinforcement learning)

### ISSUE THREAD

**Issue by cyz2727327** [Unity-Technologies/ml-agents#3293]
Hi,

I'm pretty new here and am very interested to explore more about the AI capability in Unity. 

I really want to run some pre-trained Tensorflow models (computer vision application that uses the camera for image classification, detection, and so on) in the Unity environment. I am aware of the previous approaches but it was a PAIN. 

Now that unity has its own Inference Engine, I'm very excited about this and wondering if it's finally capable of achieving that. 

Is there any official examples that explain how to set it up for camera-image based ML application? So far every example seems to be about Reinforcement Learning in the virtual gaming environment.

Any suggestions would be greatly helpful!

Thanks in advance!!!

**Comment by chriselion** [comment]
Hi @cyz2727327,
Sorry for the delay on this. This team doesn't support Barracuda (the inference engine); you can find more information about it here https://docs.unity3d.com/Packages/com.unity.barracuda@0.4/manual/index.html

If you have problems converting/loading a model, the best place to as is at their github repo: https://github.com/Unity-Technologies/barracuda-release/issues
