### ISSUE TITLE
Checkers Agent

### ISSUE THREAD

**Issue by nrvllrgrs** [Unity-Technologies/ml-agents#330]
I'm implementing an agent to learn checkers (i.e. draughts). There are two choices that are made during turn: the piece to move and the direction to move. Does this require two brains -- one for each choice?

I'm early in my ML adventure. Any insight would be appreciated. Thanks in advance.

**Comment by nrvllrgrs** [comment]
More broadly, what is the best way to set up actions for a checkers brain(s)?

**Comment by eshvk** [comment]
@nrvllrgrs, unfortunately implementing an agent with variable number of actions is not supported in ml-agents right now.
