### ISSUE TITLE
Learning-Environment-Create-New.md refers to materials that don't exist: LightGridFloorSquare, Block, CheckerSquare

### ISSUE THREAD

**Issue by ForrestTrepte** [Unity-Technologies/ml-agents#3307]
**Describe the bug**
At various points in [Learning-Environment-Create-New.md](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Create-New.md) it says to use materials that I wasn't able to find: LightGridFloorSquare, Block, and CheckerSquare.

Perhaps materials have changed names and the intended materials are LightGridFloor, GoalLit, and Checkers_Ball? However, in the latest master branch, the instructions say to use the ml-agents package and it looks like none of those Examples materials would be available.

**Comment by anupambhatnagar** [comment]
@ForrestTrepte If you look under Assets in the Unity Project panel you will find these materials there. They might be under a modified name. In case the materials are not there could you please submit a PR with the updated documentation?

**Comment by ForrestTrepte** [comment]
@anupambhatnagar: I was thinking of updating the names, but then I noticed that in the latest master branch Learning-Environment-Create-New.md says to use the com.unity.ml-agents inside a new Unity project. When I tried this, none of the example materials were pulled into my project. So I'm not sure how this should work.

Did something go wrong on my end when I was testing this? Should examples be included with com.unity.ml-agents? Or should there be a separate examples package? Or should Learning-Environment-Create-New.md be modified to avoid using examples content?

**Comment by anupambhatnagar** [comment]
@ForrestTrepte we decided to not include examples in the package. you can find the examples in the Project folder in the repo.

**Comment by ForrestTrepte** [comment]
This answers my question and I can work around it.

Do you intend to leave the documentation as-is? It seems like that is confusing for users trying to follow these instructions.

**Comment by surfnerd** [comment]
Hi @ForrestTrepte, 
I will be updating the docs to reflect these changes.
