### ISSUE TITLE
com.unity.ml-agents package missing in latest_release branch

### ISSUE THREAD

**Issue by ShivamMukherjee** [Unity-Technologies/ml-agents#3314]
**Describe the bug**
After providing the file link in `UnitySDK/Packages/manifest.json`, the editor spits an error saying that it doesn't recognise the package.

**To Reproduce**

1. Clone the repo as shown in [the Installation guide.](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md)
2. Observe that no directory called `com.unity.ml-agents` exist.
3. Try cloning the master/checking out to master.
4. Observe that the directory exists, and once provided in the `manifest.json` file, the ML-Agents package is detected succesfully.

**Console logs / stack traces**
```An error occurred while resolving packages:
  Project has invalid dependencies:
    com.unity.ml-agents: The file [C:\dev\UnityProjects\ml-agents\com.unity.ml-agents\package.json] cannot be found

A re-import of the project may be required to fix the issue or a manual modification of C:/dev/UnityProjects/ml-agents/UnitySDK/Packages/manifest.json file.
```
**Screenshots**
![image](https://user-images.githubusercontent.com/12777564/73391823-b5f3c680-42fe-11ea-8e33-9e53cb9d56cc.png)

**Environment (please complete the following information):**
- OS + version: Windows 10, 1903
- _ML-Agents version_: 0.13.1
- _TensorFlow version_: 2.0.1
- _Environment_: any among the given examples

**Comment by surfnerd** [comment]
Hi @ShivamMukherjee,
please follow [the instructions from the latest release](https://github.com/Unity-Technologies/ml-agents/blob/latest_release/docs/Installation.md).  The master branch is the branch we actively develop in.  The instructions for installation on the master branch will be updated over the next couple of days.  Thank you.

**Comment by surfnerd** [comment]
I will close this issue for now.  If you run into other installation issues, please post to the [Unity ML-Agents Forum](https://forum.unity.com/forums/ml-agents.453/).
Cheers.
