### ISSUE TITLE
How to STOP tranining and export the partial model?

### ISSUE THREAD

**Issue by tomitrescak** [Unity-Technologies/ml-agents#332]
Sorry, a NOOB here. I am playing around with the 3D Ball example and I would like to stop the training process to play around with the imperfect model.

In your documentation you mention to:

> Once the training process displays an average reward of ~75 or greater, **and there has been a recently saved model (denoted by the Saved Model message) you can choose to stop the training process** by stopping the cell execution.

When I stop the cell (I guess you mean to *Interrupt the kernell*) and then I try to export I receive following message:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-51bd14d78db4> in <module>()
----> 1 export_graph(model_path, env_name)

~/Github/learning/ml-agents/python/ppo/models.py in export_graph(model_path, env_name, target_nodes)
     52     freeze_graph.freeze_graph(input_graph=model_path + '/raw_graph_def.pb',
     53                               input_binary=True,
---> 54                               input_checkpoint=ckpt.model_checkpoint_path,
     55                               output_node_names=target_nodes,
     56                               output_graph=model_path + '/' + env_name + '.bytes',

AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'
```

This probably relates to your instruction: `and there has been a recently saved model`. So, the model is saved after 50.000 as per instructions, 

BUT:

The exported model is the previously fully trained one, not the new partial one. Is there any way to get the partial model out? Thanks!

**Comment by SPINACHCEO** [comment]
Hi there,
I don't think there is a code here to actually help you to do that.
The autosave is to save Tensorflow checkpoint, not the bytes model file that you can use within Unity.

I think you can try end the training process after checkpoint saved to use `--load` with a closer `max-step`, when the training end, the model will be exported.

Hope this will help :)

**Comment by vladimiroster** [comment]
Hi,
There is a way to export an earlier model. The code in 'export_graph' grabs the latest model according to the 'checkpoint' text file:

```
model_checkpoint_path: "model-200000.cptk"
all_model_checkpoint_paths: "model-50000.cptk"
all_model_checkpoint_paths: "model-100000.cptk"
all_model_checkpoint_paths: "model-150000.cptk"
all_model_checkpoint_paths: "model-200000.cptk"
```

You can alter this file to export any model you'd like. In addition, by using:
```
tf.train.get_checkpoint_state('checkpoints').all_model_checkpoint_paths
```
you can programmatically select and freeze any model you'd like.

Hope this helps!

Vlad

**Comment by tomitrescak** [comment]
Thanks guys! Both approaches are valid for us. Thanks.
