### ISSUE TITLE
mlangets_envs API retrieve action names

### ISSUE THREAD

**Issue by MarcoMeter** [Unity-Technologies/ml-agents#3322]
**Is your feature request related to a problem? Please describe.**
In ml-agents v0.10.0 it was possible to retrieve the names of each action branch:
`brain.vector_action_descriptions`
It looks like that something similar is not available anymore.
I'd like to use that information for generically rendering agent behaviors like this:
https://youtu.be/P2rBDHBHxcM?t=201

**Describe the solution you'd like**
It would be great if you could reintroduce it and add it to the group_spec.

**Describe alternatives you've considered**
The alternative would be to hard-code this into a wrapper, but this is not a generic solution to any Unity environment.

**Comment by anupambhatnagar** [comment]
@MarcoMeter please upgrade ml-agents to the latest version and let us know if the bug still exists. We have made some major changes since 0.10 and the issue may have been resolved in one of the later versions.

**Comment by anupambhatnagar** [comment]
@MarcoMeter thanks for your input. We shall discuss this design choice with the team at large.

**Comment by MarcoMeter** [comment]
@anupambhatnagar 
Any news on that?
