### ISSUE TITLE
Run Unity build in inference mode while interacting with mlagents.envs

### ISSUE THREAD

**Issue by MarcoMeter** [Unity-Technologies/ml-agents#3323]
Hello,

what's the equivalent approach to run a Unity build in inference mode, while the interaction is done via mlagents.envs.

In v0.10.0 this was done by setting an argument during reset `env.reset(train_mode=not self.realtime_mode)[brain_name]`.
Now I cannot seem to find a solution in v.0.13.1.

I tried to initialize the environment with `no_graphics = False` and setting the target frame rate inside the engine configuration to 60.

**Comment by anupambhatnagar** [comment]
@MarcoMeter we have decided to move discussions to the new ML Agents forum. Github will be used for bugs and feature requests only. Could you please post your question in the unity forum? Here's the link https://forum.unity.com/forums/ml-agents.453/

**Comment by MarcoMeter** [comment]
The issue has not been solved yet.
https://forum.unity.com/threads/run-unity-build-in-inference-mode-while-interacting-with-mlagents-envs.821757/
