### ISSUE TITLE
continue curriculum on --load

### ISSUE THREAD

**Issue by MarkTension** [Unity-Technologies/ml-agents#3325]
When my curriculum training is prematurely stopped, and I want to continue training by setting the --load argument, my agent has to run through the entire curriculum again. So every time I have to change the curriculum .json file to make sure it can continue training from where it was. 

It would be great if step in the curriculum was remembered, and loaded when starting a training with the --load argument.

**Comment by anupambhatnagar** [comment]
@MarkTension thanks for sending the request. I'll discuss this feature with the team at large and let you know if we plan to add it in the future.

**Comment by vincentpierre** [comment]
Hi,

There was a refactor of the curriculum learning feature and in the current release, using the `--resume` argument will reload the curriculum in the lesson it was in when training was interrupted.
