### ISSUE TITLE
Using --load rewrite the entire csv status summary making it useless

### ISSUE THREAD

**Issue by caioc2** [Unity-Technologies/ml-agents#3326]
**Describe the bug**
Using --load rewrite the entire csv status summary making it useless. When using  --load option it should either create another .csv with the newer data (much like tensorflow does) or append to the exiting .csv file.
If it doesn't, all stats saved before --load are lost which makes it pretty useless for generating any graphics or statistics.

**To Reproduce**
1. Run any environment for a while and cancel it
2. Start it again with --load option
3. the summaries/ *.csv will be rewritten containing only the steps after the --load.

**Console logs / stack traces**
No logs or stack-trace

**Environment (please complete the following information):**
- OS + version:  Windows 10
- _ML-Agents version_:  0.13+

[My currently work around](https://github.com/caioc2/ml-agents/commit/56df6bbfc364d1fc088d776a838521339241e4fd)

**Comment by anupambhatnagar** [comment]
This is not a bug, it is the intended behavior.

**Comment by caioc2** [comment]
Then I kindly ask to review its design.

Is it any usefull to have a csv that is not complete and **overrides** the older when --load clearly is a continuation of a training and not really a new one?

For any purposes of ploting a graph or garthering statistics, having half a the points makes no sense.

**Comment by TanteVonDante** [comment]
hey caioc2,

I have exactly the same problem. There is no use for --load in my opinion. I thought it will continue my session, but its starts a new one. If I would like to start a new session I would do it without --load.
Is there another option to continue the training?

Thank you for your help.

**Comment by caioc2** [comment]
Hi @TanteVonDante,

Here I mean the ".csv is unusable after a --load because it is overwritten", yet it works for the model, note that the model starts from where it stopped,  the environment starts fresh.

You can get the data from the tensorflow generated summary (opening it and converting to csv), but them, there is no point in having it to save a unusable .csv just to bloat the disk.

**Comment by TanteVonDante** [comment]
maybe I do something wrong, but when I use --load the model acts like it never trained before.

I wanted to use it instead of curriculum learning. I wanted to train like 50.000 steps and change the environment afterwards. So the training will get harder step by step. Is this possible?

**Comment by dlindmark** [comment]
> 
> 
> maybe I do something wrong, but when I use --load the model acts like it never trained before.
> 
> I wanted to use it instead of curriculum learning. I wanted to train like 50.000 steps and change the environment afterwards. So the training will get harder step by step. Is this possible?

What mlagents version are you using? 0.13.0 had a bug which made the step count reset in the tensorboard summaries. The model continued training as intended though (I think). Fixed in 0.13.1.

**Comment by TanteVonDante** [comment]
Where can I check the version? I just started last december with ml and coding, so I'm a total beginner.

**Comment by anupambhatnagar** [comment]
@TanteVonDante to verify the version numbers please see the links under the Warning section on this page. https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Migrating.md
