### ISSUE TITLE
3D Balls Confusion

### ISSUE THREAD

**Issue by tomitrescak** [Unity-Technologies/ml-agents#333]
Hi. Am a bit confused with the 3D ball project. It would be great to improve the documentation and once I'll clarify some thing I will be very happy to do the PR to help other NOOBS in need.

In Ball3DDecision.cs you make complex comparation that are not documented and they have no effect. Thus your following code:

```cs
public float[] Decide(List<float> state, List<Camera> observation, float reward, bool done, float[] memory)
{
    if (gameObject.GetComponent<Brain>().brainParameters.actionSpaceType == StateType.continuous)
    {
        List<float> ret = new List<float>();
        if (state[2] < 0 || state[5] < 0) // why ?
        {
            ret.Add(state[5]); // same
        }
        else
        {
            ret.Add(state[5]); // same
        }
        if (state[3] < 0 || state[7] < 0)
        {
            ret.Add(-state[7]);
        }
        else
        {
            ret.Add(-state[7]);
        }
        return ret.ToArray();

    }
    else
    {
        return new float[1]{ 1f };
    }
}
```

Can be written like this

```cs
public float[] Decide(List<float> state, List<Camera> observation, float reward, bool done, float[] memory)
{
    if (gameObject.GetComponent<Brain>().brainParameters.actionSpaceType == StateType.continuous)
    {
        List<float> ret = new List<float>();
        ret.Add(state[5]);
        ret.Add(-state[7]);
     }
}
```

Second, in your `Ball3DAgent.cs` you decide following:

```cs
float action_z = act[0];
if (action_z > 2f)
{
    action_z = 2f;
}
if (action_z < -2f)
{
    action_z = -2f;
}
if ((gameObject.transform.rotation.z < 0.25f && action_z > 0f) ||
    (gameObject.transform.rotation.z > -0.25f && action_z < 0f))
{
    gameObject.transform.Rotate(new Vector3(0, 0, 1), action_z);
}
```

Why you have chose 2 and -2. Is this empirical? What about 0.25 and -0.25 ? Thanks!

**Comment by xiaomaogy** [comment]
Regarding your first question. You are right. The logic can be written like yours. Actually we've just cleaned this part of the code in development-0.3 branch. 

Regarding your second question, 2 is empirically chosen. If you make it 0.25, the rotation speed would be too slow and the performance would be worse than 2.

**Comment by tomitrescak** [comment]
Thanks for your answers, good effort guys! Keep it up!
