### ISSUE TITLE
Error with latest Version of Barracuda 0.5.0 on MacOS

### ISSUE THREAD

**Issue by Sebastian-Schuchmann** [Unity-Technologies/ml-agents#3336]
**Error**: 
`Assets/ML-Agents/Scripts/InferenceBrain/ModelRunner.cs(56,57): error CS1061: 'NNModel' does not contain a definition for 'Value' and no accessible extension method 'Value' accepting a first argument of type 'NNModel' could be found (are you missing a using directive or an assembly reference?)`

**System**: macOS Catalina 10.15.3
**Unity Versions, I have tried**: 2019.3.0f6, 2018.4.14f1

### Steps to reproduce:
- Start an empty 3D Unity project
- Import ML-Agents
- Install the **latest** version of Barracuda (0.5.0)
- Error appears

Using Barracuda 0.4.0 works fine for me. But in your Docs, it is stated.
>  Search for or select the Barracuda package and install the latest version.

So I wanted to report that.

**Comment by otikna** [comment]
I had same problem, and this solution works fine for me.
**System:** Windows 10
**Unity Versions:** 2019.3.0f6
It can be associated with Unity Versions. I dont find any information about this problem in Docs

**Comment by samartIT** [comment]
I had the same with Baracuda 0.5.0 on Unity 2019.2, Win 10.
Return to 0.4.0 works fine.

**Comment by surfnerd** [comment]
Hey all, 
I will fix the documentation.  0.4.0 is the version to use for the latest release.  Thanks.

**Comment by NuclearDev0** [comment]
Thanks for all of you guys !

**Comment by fredleefarr** [comment]
Just came across this, many thanks.

**Comment by chriselion** [comment]
If you really want to use the 0.13.1 release with barracuda 0.5.0, I put the fixes on the `hotfix-0.13.1-barracuda0.5.0` branch.

**Comment by zhanshenlc** [comment]
Using 0.4.0 did work, thanks a lot.
