### ISSUE TITLE
Can I include unsupported operations in tensorflow_to_barracuda.py ? Or does Unity Inference engine have limitations?

### ISSUE THREAD

**Issue by MarkTension** [Unity-Technologies/ml-agents#3338]
Hi all,

In my environment it works best when my agent uses 3D convolutions. 
I got those successfully implemented in models.py, and they work great. 

However, when trying to export the graph to .nn , I get the IGNORED: Conv3D unknown layer error.

I've looked into the tensorlow_to_barracuda.py file, and it seems I can add some Conv3D functionality. However, before going down that rabbit-hole, I was wondering: Is this even possible by only changing this script? Or doesn't the Unity inference engine support conv3D operations anyway?

If all works out I can share the scripts if anyone is interested?

Many thanks

**Comment by chriselion** [comment]
Hi @MarkTension,
The best place to discuss this would be on [barracuda's github issues](https://github.com/Unity-Technologies/barracuda-release/issues). We just copy their conversion script.

BTW, The eventual plan is to have everything go through ONNX; ml-agents will hopefully have beta support for ONNX export in the next release.
