### ISSUE TITLE
jupyter notebook used to train crawler?

### ISSUE THREAD

**Issue by MLAgentsLearner** [Unity-Technologies/ml-agents#334]
I'm trying to make some walkers similar to Crawler, but I'm having some trouble with my training.  I'm trying to debug if it's something wrong with my hyperparameters, or if I've made a mistake in how I've created my model.  For myself and for the sake of others trying to create some models inspired by the examples, can you guys share the jupyter notebooks / hyperparameters for the examples, as well as the timings it took to train them?

**Comment by mmattar** [comment]
Hi @MLAgentsLearner (great username!) - thanks for your feedback. We are currently planning to release the optimal hyperparameters and additional comments for all the demo environments for our 0.3 release (March timeframe).

**Comment by MLAgentsLearner** [comment]
Thank you!  I'll keep an eye out for it ;)
