### ISSUE TITLE
Linking a Siraj Raval video in README.md is probably not a good idea

### ISSUE THREAD

**Issue by benprofessionaledition** [Unity-Technologies/ml-agents#3359]
Siraj has been proven to be a complete fraud many times over at this point, and referring to one of his videos in an official capacity severely undermines the legitimacy of Unity ML-Agents. His complete lack of credentials and repeated theft/fraud are so well-known that association with him suggests a fundamental lack of familiarity with the very field that this project is attempting to create a bridge to. Kinda like providing a homeopathic doctor's testimony as evidence of your new drug's efficacy.

just, you know, fyi

**Comment by andrewcoh** [comment]
Thank you,  we appreciate the feedback.  Your suggestion will be considered internally.
