### ISSUE TITLE
development-0.3: Errors when not specifying a seed for learn.py

### ISSUE THREAD

**Issue by Fallscout** [Unity-Technologies/ml-agents#336]
When trying to train the 3DBall agent with the learn.py script from the development-0.3 branch, the following error occurs:
```
Traceback (most recent call last):
  File "learn.py", line 34, in <module>
    seed = int(options['--seed'])
ValueError: invalid literal for int() with base 10: 'None'
```
This is because the seed in the usage string is set to 'None' by default and there is no validity check before the cast to int happens. Moreover, if I implement such a check and set the seed to None if it is not specified in the arguments, the code runs into another error when trying to set the seed to the current datetime in the init method of the TrainerController, because datetime.now() does not return an int, but a datetime object.
```
if seed is None:
    seed = datetime.now()
self.seed = seed
np.random.seed(self.seed)
```

**Comment by mmattar** [comment]
Hi @Fallscout -there is a pending PR that fixes this issue that will be merged this week. Just a heads up that in the short-term the development-0.3 branch shouldn't be viewed as a stable branch.
