### ISSUE TITLE
Outdated use_curiosity still in documentation

### ISSUE THREAD

**Issue by JPhilipp** [Unity-Technologies/ml-agents#3387]
I understand "use_curiosity" is superseded by the "reward_signals: ... curiosity: ..." syntax in config yaml files, but it still gets mentioned in the [Hallway example docs](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Examples.md#hallway).

**Comment by AcelisWeaven** [comment]
This is not yet merged into master, by it seems it has been fixed in #3386 (10 minutes before your issue :) )

**Comment by chriselion** [comment]
Whoops, the PR was in response to @JPhilipp's forum post https://forum.unity.com/threads/does-use_curiosity-still-exist.824040/

I'll close this off, since it will be merged into master sometime this week (after the release is completed)
