### ISSUE TITLE
Can't load external model to agent (from .pth convert to .onnx and then to .nn)

### ISSUE THREAD

**Issue by ghost** [Unity-Technologies/ml-agents#3398]
**Bug:**
I followed these steps to convert a model from Pytorch (.pth) to Barracuda (.nn):

Convert to pytorch to onnx
https://pytorch.org/docs/stable/onnx.html then
to nn with onnx_to_barracuda
https://github.com/mantasp/barracuda-release/tree/release/0.2.4/Tools

But when I have to drag my model into the agent in Unity I have this following error:

"NullReferenceException: Object reference not set to an instance of an object"

![Captura](https://user-images.githubusercontent.com/44144188/74099093-452f8400-4b20-11ea-9e27-7a23e197f6d1.PNG)

**Versions:**
· Windows 10
· ML-Agents v0.13.1
· Pytorch 1.3.1
· Unity 2018.4.16f1 
· Barracuda 0.3.2 (in Unity)
*but to convert from onnx to nn I use the scripts of barracuda 0.2.4 because if I use 0.3.2 or higher I have this error:

Traceback (most recent call last):
File "onnx_to_barracuda.py", line 20, in
onnx2bc.convert(args.source_file, args.target_file, args.trim_unused_by_output, args)
File "C:\Users\Ocin\Desktop\pytorch to unity model\onnx_to_barracuda.py", line 570, in convert
lambda tensor: get_tensor_data(tensor))
File "C:\Users\Ocin\Desktop\pytorch to unity model\barracuda.py", line 221, in setup_constants
data = np.reshape(get_tensor_data_lambda(tensor), shape).astype(np.float32))]
File "C:\Users\Ocin\Desktop\pytorch to unity model\onnx_to_barracuda.py", line 570, in
lambda tensor: get_tensor_data(tensor))
File "C:\Users\Ocin\Desktop\pytorch to unity model\onnx_to_barracuda.py", line 336, in get_tensor_data
floats = struct.unpack('<'+str(int(elems))+'f', tensor.raw_data)
**struct.error: unpack requires a buffer of 4 bytes**

Do you know the reasons what is causing these errors (mainly the first error I described)?
Because I have no idea and I don't know what I have to modify to solve it.

Thanks in advance !

**Comment by chriselion** [comment]
Recent versions of the barracuda plugin support importing onnx files directly (no need to convert to .nn).

For other questions about models that weren't created with ML-Agents, please ask on the barracuda project: https://github.com/Unity-Technologies/barracuda-release/issues

If you want to use your model for inference on ML-Agents, this isn't well documented or fully supported right now. There are several constants that need to be present in the model file, and there's a naming convention that we use to map inputs and outputs to their corresponding tensors.

**Comment by noocin** [comment]
Hello @chriselion !

Thank you very much for your quick reply. 

Is there any guide for that:

 "**There are several constants that need to be present in the model file, and there's a naming convention that we use to map inputs and outputs to their corresponding tensors**"

Do you have plans to support that? Or make the conversion/implementation easier?

**Comment by chriselion** [comment]
It's something we can look into (we should at least raise a nice error message instead of a null reference exception). In the meantime, you can see the strings for the layer names that we're looking up here:
https://github.com/Unity-Technologies/ml-agents/blob/d4f764487b57602b4f7c746d67ca37d66dbc60bf/com.unity.ml-agents/Runtime/InferenceBrain/TensorNames.cs#L8-L27

And the constants are used here:
https://github.com/Unity-Technologies/ml-agents/blob/d4f764487b57602b4f7c746d67ca37d66dbc60bf/com.unity.ml-agents/Runtime/InferenceBrain/BarracudaModelParamLoader.cs#L140-L144


Stepping back a minute - are you trying to use your model for ML-Agents inference, or do you just need to be able to run Barracuda (general inference)? If it's the latter, you don't need to follow these conventions.

**Comment by noocin** [comment]
I just want to drag my model here:

![image](https://user-images.githubusercontent.com/44144188/74474557-0e51c900-4ea6-11ea-8de3-63727da3ab4e.png)

My model is created from pytorch (.pth) and converted to .onnx (or .nn).

Do I need the names and constants to do that? If the answer is yes, is there any example how to do it?

**Comment by ervteng** [comment]
Hi @noocin, there currently isn't a supported path to get PyTorch models into ML-Agents - we only support the models created with our toolkit, so we don't have any working examples.

With that said, it is possible - you're right in that the names and constants need to match. If you're able to create a model with the tensor names specified, it *should* work. You may be able to omit the `recurrent_in` ones if you're not using an LSTM, and the "value_estimate" one if you don't need that.

**Comment by JJHAirylin** [comment]
I converted a trained tensorflow model to Barracuda, and that went successfully. But the same error occurred when I tried to drag the .nn model from asset to the agent's component. I can't use my model in Unity. So is it also because of the names and constants?

**Comment by JayGameHive** [comment]
I'm here looking for the same answers. Not sure if anyone was successful in figuring out how to name the consts

**Comment by chriselion** [comment]
The names are in https://github.com/Unity-Technologies/ml-agents/blob/master/com.unity.ml-agents/Runtime/Inference/TensorNames.cs

**Comment by Segelzwerg** [comment]
Hi everyone, we tried to import a converted TF-1, TF-2 / and Keras models. We could import into Unity but failed upon drag&drop to Model Attribute in Behaviour Parameters. It seems like the error above.
```NullReferenceException: Object reference not set to an instance of an object
Unity.MLAgents.Inference.BarracudaModelParamLoader.CheckModel (Unity.Barracuda.Model model, Unity.MLAgents.Policies.BrainParameters brainParameters, Unity.MLAgents.Sensors.SensorComponent[] sensorComponents, System.Int32 observableAttributeTotalSize, Unity.MLAgents.Policies.BehaviorType behaviorType) (at Library/PackageCache/com.unity.ml-agents@1.1.0-preview/Runtime/Inference/BarracudaModelParamLoader.cs:152)
Unity.MLAgents.Editor.BehaviorParametersEditor.DisplayFailedModelChecks () (at Library/PackageCache/com.unity.ml-agents@1.1.0-preview/Editor/BehaviorParametersEditor.cs:128)
Unity.MLAgents.Editor.BehaviorParametersEditor.OnInspectorGUI () (at Library/PackageCache/com.unity.ml-agents@1.1.0-preview/Editor/BehaviorParametersEditor.cs:71)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass55_0.<CreateIMGUIInspectorFromEditor>b__0 () (at /home/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorElement.cs:521)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /home/builduser/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:187)
```
We actually manage to add a constant, but we still got the same error.
![image](https://user-images.githubusercontent.com/25705862/87227282-4c421300-c39a-11ea-9aa4-b544097e8377.png)

So our question is, did anyone manage to add these constant and got the onnx network imported. We would really appreciate any help as we are stuck and the project depends on importing the network. For this project, it is not an option to train directly with ml-agents as we need the Keras models elsewhere.

**Comment by chriselion** [comment]
@Segelzwerg I believe something changed in the Barracuda ONNX importer recently; we changed the model export to store the constants as outputs (https://github.com/Unity-Technologies/ml-agents/pull/4073). Unfortunately, we didn't have a good test for this, so I'm not sure when the change in Barracuda actually happened.

I think after this thread was originally created, we clarified our [policy on models that were generated outside of ML-Agents](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Unity-Inference-Engine.md#unity-inference-engine), namely that we do not provide support for them. You're still welcome to try, but chances are you're going to have to read through the code (especially in BarracudaModelParamLoader) to determine how to get your model hooked up.

**Comment by Segelzwerg** [comment]
@chriselion thanks for the reply. We created a simple onnx-net by hand and it has an output `version_number` and we still getting the error. So we are a bit lost what to do. Do you have any idea on what we could try?

![image](https://user-images.githubusercontent.com/25705862/87458482-5b2efc80-c60a-11ea-992b-68cd8be3b745.png)
The shape seems to be wrong as well, but this shouldn't matter in line 152.

Thank you very much in advance.

**Comment by BYJRK** [comment]
Has anyone found the answer to solve this NullReferenceException problem? I'm still encountering this problem when trying to drag the .onnx to Model in 2021.

**Comment by vinicassol** [comment]
Hi, any updates about the NullReferenceException? Just trained an agent today but I'm not able to drag the .onx.

```
NullReferenceException: Object reference not set to an instance of an object
Unity.MLAgents.Inference.BarracudaModelParamLoader.CheckModel (Unity.Barracuda.Model model, Unity.MLAgents.Policies.BrainParameters brainParameters, Unity.MLAgents.Sensors.SensorComponent[] sensorComponents, Unity.MLAgents.Policies.BehaviorType behaviorType) (at Library/PackageCache/com.unity.ml-agents@1.0.7/Runtime/Inference/BarracudaModelParamLoader.cs:152)
Unity.MLAgents.Editor.BehaviorParametersEditor.DisplayFailedModelChecks () (at Library/PackageCache/com.unity.ml-agents@1.0.7/Editor/BehaviorParametersEditor.cs:108)
Unity.MLAgents.Editor.BehaviorParametersEditor.OnInspectorGUI () (at Library/PackageCache/com.unity.ml-agents@1.0.7/Editor/BehaviorParametersEditor.cs:68)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass59_0.<CreateIMGUIInspectorFromEditor>b__0 () (at /Users/bokken/buildslave/unity/build/External/MirroredPackageSources/com.unity.ui/Editor/Inspector/InspectorElement.cs:546)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)
```

**Comment by chriselion** [comment]
@BYJRK @vinicassol Please make sure that the versions of the python package and Unity plugin are compatible with each other. In particular, the v0.26.0 python release (and later) will generate model files that are incompatible with 1.x versions of `com.unity.ml-agents`. If you can't upgrade to `com.unity.ml-agents` 2.0, you'll need to downgrade your version of the python packages to something between 0.16.1 and 0.20.0.

These new errors are separate from the original issue; I'm going to close and lock this issue. Please submit a new bug report (with all the relevant version information) if you're still having problems.
