### ISSUE TITLE
Running speed get slow in the later timesteps

### ISSUE THREAD

**Issue by tingfx4yu** [Unity-Technologies/ml-agents#3399]
The version of my mlagents is 0.10.1 and Ubuntu18.04
I build the game and test other algorithms written by myself to train (like TD3)
At the very beginning, everything is OK and the training speed is normal but in the later timesteps like 1m timestep, the training speed gets very slow. I also check the GPU , memory and CPU, the usage of them are pretty low but I don't know why
Most of the time It's OK since most of the time 1m timestep is enough for training a good behavior but I still want to know the reason of getting slow in the later timesteps

It will be very helpful if someone can point out the reasons !!

**Comment by ervteng** [comment]
Hi @tingfx4yu, does the slowdown happen with your environment using our PPO or SAC implementation? This sounds like a memory issue either in the trainer or in the environment, so doing that test would help us debug. Thanks!

**Comment by tingfx4yu** [comment]
> Hi @tingfx4yu, does the slowdown happen with your environment using our PPO or SAC implementation? This sounds like a memory issue either in the trainer or in the environment, so doing that test would help us debug. Thanks!

Thanks for your replay! I don't use the sac and ppo
Implementation in mlagents but using the algorithms done by pytorch, mlagents was just used as a bridge connect the environment and algorithms.

**Comment by ervteng** [comment]
Hi @tingfx4yu, can you try running your environment with PPO or SAC and see if you get the same slowdown? If it is, it's in either ML-Agents or the game - otherwise it's likely in your PyTorch code. Thanks!

**Comment by tingfx4yu** [comment]
> Hi @tingfx4yu, can you try running your environment with PPO or SAC and see if you get the same slowdown? If it is, it's in either ML-Agents or the game - otherwise it's likely in your PyTorch code. Thanks!

Yes, currently I use sac to train pushblock environment, the slowdown will also happen. I think it's better for me to check log maybe I can find something wrong with it
Thanks a lot!

**Comment by ervteng** [comment]
If you have the printout from the console of the Pushblock run, that would be super helpful. And the `timers.json` file from the `summaries` directory as well.

**Comment by tingfx4yu** [comment]
> If you have the printout from the console of the Pushblock run, that would be super helpful. And the `timers.json` file from the `summaries` directory as well.
 I will check again, Thanks for your information!
