### ISSUE TITLE
Passing Agent to Decision

### ISSUE THREAD

**Issue by SSS135** [Unity-Technologies/ml-agents#34]
Currently, there is no way to know for which agent Decision.Decide or Decision.MakeMemory is called. Knowing it may help in some cases. For example, when agent's state is a large vector for training neural network and can not be easily used to make decision. Agent itself may contain some sort of high level API, which greatly simplifies decider's task.

**Comment by awjuliani** [comment]
Hi @SSS135,

Could you give a little more context to the kind of problem you are interested in solving?

**Comment by SSS135** [comment]
Hi @awjuliani,
Right now I'm trying to apply deep reinforcement learning to Russian Mini AI Cup. To do this I've implemented my own version of the environment used in competition with ML Agents. Environment contains 8 elevators in 9 floor building. You and enemy control 4 elevators. Also you must tell people to which elevator they should go. The goal is to transfer more people than enemy.
I'm planning to do initial training of neural network against some baseline stragegy which is implemented as a Decision. Writing this strategy is much simpler if you know which elevators you control and have access to their methods / fields, than using a state vector. Right now I'm doing it with two brains, and specifying Agent in Decision via inspector.

**Comment by vincentpierre** [comment]
@SSS135 An immediate solution would be to add a state that corresponds to an agent's id number. You could ignore this state in your neural networks and only use it in Decision. 
Hope this helps.  
The project you are working on sounds amazing, I am looking forward to see how these experiments go.
