### ISSUE TITLE
Optional auto-setting of ray sensor names

### ISSUE THREAD

**Issue by JPhilipp** [Unity-Technologies/ml-agents#3401]
Hi! It might be nice if `RayPerceptionSensorComponentBase's` sensorName string would, if `string.IsNullOrWhiteSpace(sensorName)`, take the `gameObject.name` as sensorName. This way, one could avoid the data maintenance redundancy when setting up a whole bunch of sensor gameObjects and naming the gameObject e.g. "ForwardSensor1", "ForwardSensor2", "SideSensor", "ForwardDownSensor" etc., but then also having to name the sensorName field to the same. (As it'd be optional to make the string empty, one could still use names distinct from the `gameObject.name` as before, though.)

If this is not a good idea and has more cons than pros, please ignore, thanks!

**Comment by chriselion** [comment]
Hmm, not a bad idea. I've thought about this before (and made similar mistakes) when adding multiple SensorComponents - what I'd really like is that when you add a new SensorComponent, it defaults to a unique name like RayPerceptionSensor_0, RayPerceptionSensor_1, etc.

I'll log something to revisit this and try to improve the workflow.

**Comment by chriselion** [comment]
The internal tracker for this is MLA-618.

**Comment by JPhilipp** [comment]
@chriselion Thanks! One aspect to consider when finding a best solution: A developer may (I know I do) use heavy gameObject node copy & pasting & dragging around in the Hierarchy pane when setting up the original rays -- like set up the first ray, then copy it and rotate it for the second ray (if the Direction slider on the first ray isn't sufficient). And that beyond that, many devs may not care about the internal ray name given to it (but there's probably a use case for needing to know it, and have it be exposed in the inspector). Not sure if whatever Unity uses internally for node Ids in the hierarchy could be reused here as name.
