### ISSUE TITLE
com.unity.ml-agents missing from branch tagged latest_release

### ISSUE THREAD

**Issue by joosephook** [Unity-Technologies/ml-agents#3409]
**Describe the bug**
Executing `git clone --branch latest_release https://github.com/Unity-Technologies/ml-agents.git` results in a cloned repository without `com.unity.ml-agents` package, so that ml-agents cannot be installed according to the [instructions supplied here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md).

**To Reproduce**
Run `git clone --branch latest_release https://github.com/Unity-Technologies/ml-agents.git`

**Console logs / stack traces**
```bash
MINGW64 ~/Documents/ml-agents ((0.13.1))$ ls -1
CODE_OF_CONDUCT.md
config/
CONTRIBUTING.md
demos/
Dockerfile
docs/
gym-unity/
LICENSE
markdown-link-check.fast.json
markdown-link-check.full.json
ml-agents/
ml-agents-envs/
notebooks/
protobuf-definitions/
README.md
run-standalone-build-osx.sh*
run-tests-editmode-osx-editor.sh*
setup.cfg
SURVEY.md
test_constraints_max_tf1_version.txt
test_constraints_max_tf2_version.txt
test_constraints_min_version.txt
test_requirements.txt
UnitySDK/
unity-volume/
utils/
```

**Environment (please complete the following information):**
- Windows 10
- Ubuntu 18.04.1

**Comment by Al-Skaf** [comment]
same here

**Comment by ervteng** [comment]
The `com.unity.ml-agents` package only exists in the current `master` and will be released in the following ML-Agents release. If you want to install the package, clone `master` rather than `latest_release`. Otherwise, follow the install docs from the `release-0.13.1` branch.
