### ISSUE TITLE
Some information about the raycast observations

### ISSUE THREAD

**Issue by sahandrez** [Unity-Technologies/ml-agents#3411]
Hello, 

I have a few questions about the raycast observations. First, I would like to know what is the reason of the addition of 2 to the number of tags in this equation:
`(Observation Stacks) * (1 + 2 * Rays Per Direction) * (Num Detectable Tags + 2)`
Is this some sort of padding? What happens if I remove that from the code?

Second, can you please give some information on how the raycast information is collected in the observation states? Is it added after or before the vector observations? Also what is the order of collection of the raycasts (e.g. does the beginning of the data correspond to the forward of the agent)? I'm interested to know these because I am planning to use CNN on the raycast and without information on the spatial representation of the data, the CNN would become useless. 

Thank you.
Sahand

**Comment by jewis123** [comment]
So, What does (Num Detectable Tags + 2) mean？..

**Comment by chriselion** [comment]
For each ray, either
* it hits an object with one of the tags in `m_DetectableTags`
* it hits an object with another tag that isn't in `m_DetectableTags`
* it doesn't hit anything.

So there are `m_DetectableTags.Count + 2` possible results.
