### ISSUE TITLE
Making sensor gizmo rays 3D position & direction more understandably

### ISSUE THREAD

**Issue by JPhilipp** [Unity-Technologies/ml-agents#3429]
(Again, loving ML Agents.) As gizmo rays and spheres are not covered by objects, it makes it difficult to understand their position, direction and hit point in 3D. A downward laser looks, when seen from a specific angle, the same as a sideways laser.

As having lasers shine through is also a bonus to see them, maybe it's possible to get a best of both worlds visualization here, like by having one lower opacity line drawn shining through, and one full opacity line drawn over it that gets 3D-occluded. Same for hit point spheres.

Maybe the lines could also have 3D thickness that would let one better gauge where they're further away from the view. And maybe the hit normal could be used to somehow draw an actual rectangle. If some of these advanced visuals would require LineRenderers or actual 3D gameObjects to be used which lowers performance, they could be ticked off again if not needed.

In Machine Learning, where the neural network is so much of a blackbox, careful debugging that all systems are in place is often crucial before starting a training -- any error could lead to multiple hours or a whole night lost. That's why such systems as gizmo rays are so important to have highly intuitive visuals.

Thanks!

**Comment by harperj** [comment]
Hi @JPhilipp -- thanks for the request.  I'll share this with the team; of course we agree that it's helpful to have intuitive ways to visualize your observations :-)
