### ISSUE TITLE
Doxygen Input Path Not Updated

### ISSUE THREAD

**Issue by Xiromtz** [Unity-Technologies/ml-agents#3430]
The Doxygen config file still uses the Project/ filepath for scripts, even though they were recently moved to com.unity.ml-agents.

When compiling the doxygen config file, only warnings are output. Opening the index.html shows that there is no content, since it couldn't find any of the scripts.

I am using version 0.14.0 of mlagents.

**Comment by surfnerd** [comment]
I'll fix this.  Thanks for finding it.

**Comment by mmattar** [comment]
Hi @Xiromtz - thanks for calling out this issue. We just updated the doxygen config file to point to the correct directory. This is currently fixed on the `master` (unreleased branch) and will be pushed to our next release. You can find the change in this PR: https://github.com/Unity-Technologies/ml-agents/pull/3490/
