### ISSUE TITLE
ML Agents, combine raycast detection with visual observation?

### ISSUE THREAD

**Issue by smartcharith** [Unity-Technologies/ml-agents#3431]
In Unity machine learning, is it possible to combine raycast detection with visual observation, to train the agent?

Specifically I want to use raycast detection to detect fast-moving physics objects like a ball, and other AI agents. I'd also like to use visual observation (like in Snoopy Pop) to teach the agent about the current tile-based level, which would be especially helpful for things like detecting different tile types (floor, wall, ice, lava etc). Ideally I'd like both running simultaneously.

Thank you!

**Comment by harperj** [comment]
Hi @smartcharith -- yes, it is possible to use a combination of visual and vector observations.

**Comment by smartcharith** [comment]
is there any example project available for study??

**Comment by harperj** [comment]
@smartcharith no, unfortunately at this time none of our environments combine raycast and visual observations.

**Comment by smartcharith** [comment]
Thanks For Help!
