### ISSUE TITLE
How to get reward after using AddForce?

### ISSUE THREAD

**Issue by mushketer888** [Unity-Technologies/ml-agents#344]
Hello all!
How to get reward after using AddForce? (or other physics stuff: addTorque etc)
As i understood reward is reseting each step.

Where I need to put addForce,addTorque? In AgentStep or in FixedUpdate?
All variants seems useless.

public override void AgentStep(float[] act)
    {
        action = Mathf.FloorToInt(act[0]);

        if (action == 0) body.AddForce(new Vector3(0.1f*speed, 0, 0));
        if (action == 1) body.AddForce(new Vector3(-0.1f*speed, 0, 0));
        if (action == 2) body.AddForce(new Vector3(0, 0, 0.1f * speed));
        if (action == 3) body.AddForce(new Vector3(0, 0, -0.1f * speed));

        float dist = Vector3.Distance(goal.transform.position, body.transform.position);
        float rez = Mathf.Abs(dist); //cant get reward so quickly because of fisedupdate
}

As useless as:

void FixedUpdate () {
        if (agent.action== 0) body.AddForce(new Vector3(0.1f*speed, 0, 0));
        if (agent.action== 1) body.AddForce(new Vector3(-0.1f*speed, 0, 0));
        if (agent.action== 2) body.AddForce(new Vector3(0, 0, 0.1f * speed));
        if (agent.action== 3) body.AddForce(new Vector3(0, 0, -0.1f * speed));
//also cant get reward so quickly
}

So the better question is this: if using addForce,addTorque - how to obtain reward?
Please say any advice. Thanks

**Comment by mmattar** [comment]
Hi @mushketer888,

Note that the reward is the signal you give the agent at each step of the environment (i.e. each call to AgentStep). Currently, reward is a local variable in the Agent class that you should modify directly from within AgentStep. 

Hope this helps.

**Comment by mushketer888** [comment]
So if I will give immediate reward after applying force (but not waiting for result) - is it OK?
Something like:
`
...addForce(...)
if (!done) reward=0.1f;
`

**Comment by vincentpierre** [comment]
You could compute the reward in AgentStep before applying the force. This could correspond to rewarding the previous action that was taken.
I recommend using AgentStep over FixedUpdate.
Can you try with a Player Brain and see if the force is applied ? 
I am concerned by what `speed` is. Make sure it is not 0 or debut this by hard coding the value of the force to something you know will work
```
if (agent.action== 0) body.AddForce(new Vector3(1000f, 0, 0));
```

**Comment by mushketer888** [comment]
> This could correspond to rewarding the previous action that was taken.

Tried that. It works! Thanks all!
