### ISSUE TITLE
checkpoint file extension is .cptk, not .ckpt

### ISSUE THREAD

**Issue by yosider** [Unity-Technologies/ml-agents#3456]
The extension of my checkpoint files are .cptk, not .ckpt.
Is this a typo at this line?
https://github.com/Unity-Technologies/ml-agents/blob/66c9f765f8ec81557216f81560d8d112a0ec7cc7/ml-agents/mlagents/trainers/tf_policy.py#L325

**Comment by harperj** [comment]
Hi @yosider -- I think you're right that the checkpoints should be `.ckpt`.  I'll bring this issue up with the team.

**Comment by harperj** [comment]
Thanks for the report @yosider.  I've made the fix in #3470.  Going to close this issue, but please let us know if you run into any more problems.
