### ISSUE TITLE
v.0.14.0 .demo files showing incorrect number of episodes / mean reward

### ISSUE THREAD

**Issue by AidanNelson** [Unity-Technologies/ml-agents#3461]
I'm trying to record a demonstration file for the *Basic* example scene to work with BC/Gail training.  The resulting .demo file shows a correct number of experiences, but incorrect number of episodes and incorrect mean reward.  Over the course of my demonstration, the agent script called `Done()` 65 times, and reset correctly in the Game window, which is not reflected in the demonstration.  See screenshot below:

<img width="524" alt="Screen Shot 2020-02-17 at 9 24 02 PM" src="https://user-images.githubusercontent.com/6486359/74698458-da3f1680-51cb-11ea-9e04-9cad63cd2546.png">

Maybe this is related to #3205 ?

**Environment (please complete the following information):**
- OS + version: Mac OS 10.13.6
- _ML-Agents version_: v.0.14.0

**Comment by harperj** [comment]
Hi @AidanNelson -- yes, this issue seems to be related to the other issues we're having with demo files in 0.14.0.  We're working on a fix for this and will update when this is fixed.

**Comment by harperj** [comment]
This issue was fixed in the [v0.14.1 release](https://github.com/Unity-Technologies/ml-agents/releases/tag/0.14.1).  Feel free to give it a try and see if it works for you.  I'm going to close this issue, but feel free to reopen if you continue to have trouble.
