### ISSUE TITLE
Using --load in mlagents-v0.14 causes the reward to drop

### ISSUE THREAD

**Issue by albertoxamin** [Unity-Technologies/ml-agents#3478]
**Describe the bug**
When I resumed training with --load the reward decreased to even lower than the inital reward 

This is the command that I used for starting the training
```bash
mlagents-learn sac_trainer_config.yaml --run-id=run --env='/Users/alberto/Downloads/build.app' --num-envs=14 --train
```
This is the command that I used for resuming the training 
```bash
mlagents-learn sac_trainer_config.yaml --run-id=run --env='/Users/alberto/Downloads/build.app' --num-envs=14 --load --train
```

**Screenshots**
The dot represents when I stopped training 
![image](https://user-images.githubusercontent.com/6067659/74941642-a9412a80-53f3-11ea-8a0d-81b1b12055ee.png)

**Environment (please complete the following information):**
- OS + version: MacOS Catalina 10.15.3 (19D76)
- _ML-Agents version_: ML-Agents v0.14
- _TensorFlow version_: 2.0.0
- _Environment_: Custom, but it shouldn’t matter

**Comment by unityjeffrey** [comment]
hi @albertoxamin - can you set the option to save the replay buffer for SAC (save_replay_buffer)?
