### ISSUE TITLE
how do I manually call CollectObservations and AgentAction

### ISSUE THREAD

**Issue by xtc002007** [Unity-Technologies/ml-agents#3482]
hi,
currently, when I add DecisionRequester script and call CollectObservations and AgentAction, they are called according to the frequency of FixedUpdate (). If I make a Turn-Based Strategy game, I want to be able to send CollectObservations and get AgentAction only after I press the button. Is this possible? What should I do?
Thank you!

**Comment by unityjeffrey** [comment]
hi @xtc002007 - can you open your request on our forum instead?  https://forum.unity.com/forums/ml-agents.453/

**Comment by unityjeffrey** [comment]
Per our guidelines, we are moving "help wanted" requests to forums

**Comment by xtc002007** [comment]
@unityjeffrey ok
