### ISSUE TITLE
Total steps doubling upon --load

### ISSUE THREAD

**Issue by rjstange** [Unity-Technologies/ml-agents#3485]
**Describe the bug**
Example: if I resume training from a checkpoint at 150k steps, the next step that shows up in TensorBoard and the console will be 310k steps.

**To Reproduce**

**Environment (please complete the following information):**
- OS + version:  Windows 10 Home 64
- _ML-Agents version_: 0.14.0
- _TensorFlow version_: 2.0.1
- _Environment_: Custom Environment

**Comment by unityjeffrey** [comment]
hi @rjstange - please provide more details to reproduce the behavior, including which environment and any other relevant information.

**Comment by rjstange** [comment]
I will try to first reinstall my python environment for ml-agents and update to the version that 0.14.0 uses and try again with one of the sample learning environments to see if the problem happens again.
