### ISSUE TITLE
Setting behavior type to inference error (ML-Agents 12)

### ISSUE THREAD

**Issue by wightwhale** [Unity-Technologies/ml-agents#3516]
The error doesn't appear to be coming from my code. The error shows up when I set my agents to inference only.

mlagents-learn config/trainer_config.yaml --curriculum=config/curricula/MyEnv/ --run-id=myenv --train

NullReferenceException: Object reference not set to an instance of an object
MLAgents.InferenceBrain.ModelRunner.DecideBatch () (at Assets/ML-Agents/Scripts/InferenceBrain/ModelRunner.cs:129)
MLAgents.BarracudaPolicy.DecideAction () (at Assets/ML-Agents/Scripts/Policy/BarracudaPolicy.cs:53)
MLAgents.Agent.DecideAction () (at Assets/ML-Agents/Scripts/Agent.cs:1006)
MLAgents.Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:535)
MLAgents.Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:567)

**Comment by wightwhale** [comment]
There's actually two errors. 

NullReferenceException: Object reference not set to an instance of an object
MLAgents.InferenceBrain.ModelRunner.DecideBatch () (at Assets/ML-Agents/Scripts/InferenceBrain/ModelRunner.cs:129)
MLAgents.BarracudaPolicy.DecideAction () (at Assets/ML-Agents/Scripts/Policy/BarracudaPolicy.cs:53)
MLAgents.Agent.DecideAction () (at Assets/ML-Agents/Scripts/Agent.cs:1006)
MLAgents.Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:535)
MLAgents.Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:567)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at C:/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)

**Comment by xiaomaogy** [comment]
hi @wightwhale  - can you open your request on our forum instead? https://forum.unity.com/forums/ml-agents.453/
