### ISSUE TITLE
Collecting N steps is longer with a higher Decision Period

### ISSUE THREAD

**Issue by Procuste34** [Unity-Technologies/ml-agents#3523]
Increasing the Decision Period of the Decision Requester of an agent makes the collect of N steps longer than the collect of N steps with a Decision Period set to 1. It seems counterintuitive as having a higher Decision Period should reduce the number of C# <=> Python interactions and thus reduce the time needed to simply collect N steps. I observed the results using N=10000, and using both mlagents-learn and the Python API (UnityEnvironment) on the 3DBall env. (No training involved here, just pure steps collecting)

**To Reproduce**
_For simplicity, I disabled every agent except one._

- Using mlagents-learn:
1. Set Decision Period to 5 (default value) in the 3DBall env
2. Run `mlagents-learn` on this env (no need to set `--train`)
3. Observe time needed to step through 10k steps (in my case about 60s)
4. Set Decision Period to 1 in the 3DBall env
5. Run `mlagents-learn` on this env (no need to set `--train`)
6. Observe time needed to step through 10k steps (in my case about 24s)

- Using the Python API:
1. Build two versions of the 3DBall env : one version with Decision Period = 1, another with Decision Period = 5
2. Run the following code for the env with Decision Period = 1: (I got 9 seconds)
```
import random
import time
import numpy as np

from mlagents_envs.environment import UnityEnvironment
from mlagents_envs.side_channel.engine_configuration_channel import EngineConfigurationChannel
from mlagents_envs.base_env import BatchedStepResult

engine_configuration_channel = EngineConfigurationChannel()
env = UnityEnvironment(base_port = UnityEnvironment.DEFAULT_EDITOR_PORT, worker_id=0, file_name="../../../../unitydev/builtenvs/3DBall_dp1", side_channels = [engine_configuration_channel])

engine_configuration_channel.set_configuration_parameters(time_scale = 20.0)

env.reset()

group_name = env.get_agent_groups()[0]
step_result = env.get_step_result(group_name)

start_time = time.time()

for timestep in range(10000):
    if step_result.n_agents() == 2:
        action = np.array([[0, 0], [0, 0]]).reshape(2, 2)
    else:
        action = np.array([[0, 0]]).reshape(1, 2)
        
    env.set_actions(group_name, action)
    env.step()
    step_result = env.get_step_result(group_name)
    
env.close()
print(time.time() - start_time)
```
3. Run the code for the env with Decision Period = 5 (I got 18 secondes)

**Results**
To wrap up, here are the results obtained for 10k steps : 
* with `mlagents-learn` : 61 seconds with a decision period of 5, only 24 seconds with a decision period of 1.
* with the Python API : 18 seconds with a decision period of 5, only 9 seconds with a decision period of 1.

**Environment:**
- OS + version: Ubuntu 18.04.4
- _ML-Agents version_: v0.14
- _Environment_: 3DBall

**Comment by xiaomaogy** [comment]
Hi @Procuste34, this is not a bug. As noted in https://github.com/Unity-Technologies/ml-agents/blob/93a419715022336bc1af06cf3f067f7f575fd842/com.unity.ml-agents/Runtime/DecisionRequester.cs. The decision period means: The frequency with which the agent requests a decision. A DecisionPeriod of 5 means that the Agent will request a decision every 5 Academy steps."

Here Academy step is different from the step on the "step" on the python side (and what you see in the command line). On the python side,  every time the agent request a decision, we call that as one step. So longer the decision period, longer one step will take (because for each step, we need to wait for decision period).

**Comment by Procuste34** [comment]
Thank you for your answer, I didn't take into account that. Now I understand ;)
