### ISSUE TITLE
Latest Build Unity Package using API-15 but mlagents-learn using API-14 

### ISSUE THREAD

**Issue by AndyGisby** [Unity-Technologies/ml-agents#3526]
`(mlagents-env) c:\unity\ml-agents-latest_release>mlagents-learn config/trainer_config.yaml --run-id=Tripod001 --train
WARNING:tensorflow:From c:\python-envs\mlagents-env\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

                        ▄▄▄▓▓▓▓
                   ╓▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
          ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
          ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓▌
                        ¬`▀▀▀█▓

 Version information:
  ml-agents: 0.14.0,
  ml-agents-envs: 0.14.0,
  Communicator API: API-14,
  TensorFlow: 2.0.1
WARNING:tensorflow:From c:\python-envs\mlagents-env\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
INFO:mlagents_envs:Listening on port 5004. Start training by pressing the Play button in the Unity Editor.
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python-envs\mlagents-env\lib\site-packages\mlagents\trainers\subprocess_env_manager.py", line 97, in worker
    worker_id, [shared_float_properties, engine_configuration_channel]
  File "c:\python-envs\mlagents-env\lib\site-packages\mlagents\trainers\learn.py", line 425, in create_unity_environment
    side_channels=side_channels,
  File "c:\python-envs\mlagents-env\lib\site-packages\mlagents_envs\environment.py", line 134, in __init__
    f"The API number is not compatible between Unity and python. "
**mlagents_envs.exception.UnityEnvironmentException: The API number is not compatible between Unity and python. Python API: API-14, Unity API: API-15-dev0.**
Please go to https://github.com/Unity-Technologies/ml-agents/releases/tag/latest_releaseto download the latest version of ML-Agents.`

Using Win10 and Unity 2019.3.3f1

**To Reproduce**
1. Download GIT latest release (also tried Master)
2. Unzip to folder. 
3. Install package from disk in Unity project
4. Run documented mlagents-learn config/ ...etc.. (see above)
5. Start in Unity Editor
6. See error

This version mismatch is down to (I guess) the package the document says to install in Unity (Wanting to use v15, but python commands launch in v14)?

**Environment (please complete the following information):**
- OS + version: Windows 10
- _ML-Agents version_: lastest_release
- _TensorFlow version_: 2.0.1
- _Environment_: Unity Editor

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by surfnerd** [comment]
Hi @AndyGisby,
Please checkout the [latest release](https://github.com/Unity-Technologies/ml-agents/blob/latest_release/docs/Installation.md#clone-the-ml-agents-toolkit-repository) of ML-Agents.  It looks like you have checked out master.

**Comment by AndyGisby** [comment]
Hi @surfnerd - I did download latest_release (and Master) originally. Have cleaned packages and installed unity package from disk "latest-release" again. C# compiler is now complaining about CollectObservations signature in my agent so guessing parent class has regressed to 0.14 signatures?

**Comment by surfnerd** [comment]
Yes, the signature of this method has changed in master.

**Comment by AndyGisby** [comment]
@surfnerd Yep, that's doing something now.. thanks! :)
