### ISSUE TITLE
Agent does not learn from recorded demonstration in 0.14.1

### ISSUE THREAD

**Issue by AdhamAlHarazi** [Unity-Technologies/ml-agents#3530]
**Describe the bug**
I tried to teach the pyramid's agent from Pyramids Expert demo file, and it does ok, although not quite as good as the docs https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-Imitation-Learning.md.

However, when I teach it from my own recorded demonstration in ml-agents 0.14.1 version, its performance is similar to learning without imitation despite my recording has 23 episodes with 1.72 mean reward.

**To Reproduce**
- Record a demonstration in 0.14.1 and test it against ExpertPyramid.demo that comes with the pyramid example.

**Console logs / stack traces**
**Using ExpertPyramid.demo that comes with the example**
```
INFO:mlagents.trainers: pyramidExpert: Pyramids: Step: 30000. Time Elapsed: 80.721 s Mean Reward: -0.742. Std of Reward: 0.734. Training.
INFO:mlagents.trainers: pyramidExpert: Pyramids: Step: 60000. Time Elapsed: 199.465 s Mean Reward: -0.838. Std of Reward: 0.634. Training.
INFO:mlagents.trainers: pyramidExpert: Pyramids: Step: 90000. Time Elapsed: 293.943 s Mean Reward: -0.260. Std of Reward: 1.072. Training.
INFO:mlagents.trainers: pyramidExpert: Pyramids: Step: 120000. Time Elapsed: 378.909 s Mean Reward: 0.124. Std of Reward: 1.219. Training.
INFO:mlagents.trainers: pyramidExpert: Pyramids: Step: 150000. Time Elapsed: 461.501 s Mean Reward: 0.017. Std of Reward: 1.154. Training.
```
**Using non-imitation**
```
INFO:mlagents.trainers: pyramidNormal: Pyramids: Step: 30000. Time Elapsed: 66.028 s Mean Reward: -1.000. Std of Reward: 0.000. Training.
INFO:mlagents.trainers: pyramidNormal: Pyramids: Step: 60000. Time Elapsed: 125.697 s Mean Reward: -0.999. Std of Reward: 0.000. Training.
INFO:mlagents.trainers: pyramidNormal: Pyramids: Step: 90000. Time Elapsed: 181.045 s Mean Reward: -1.000. Std of Reward: 0.000. Training.
INFO:mlagents.trainers: pyramidNormal: Pyramids: Step: 120000. Time Elapsed: 240.325 s Mean Reward: -0.859. Std of Reward: 0.546. Training.
INFO:mlagents.trainers: pyramidNormal: Pyramids: Step: 150000. Time Elapsed: 302.729 s Mean Reward: -0.848. Std of Reward: 0.604. Training.
```

**From my recorded demo**
```
INFO:mlagents.trainers: pyramidAdham2: Pyramids: Step: 30000. Time Elapsed: 75.724 s Mean Reward: -1.000. Std of Reward: 0.000. Training.
INFO:mlagents.trainers: pyramidAdham2: Pyramids: Step: 60000. Time Elapsed: 142.331 s Mean Reward: -0.999. Std of Reward: 0.000. Training.
INFO:mlagents.trainers: pyramidAdham2: Pyramids: Step: 90000. Time Elapsed: 208.649 s Mean Reward: -1.000. Std of Reward: 0.000. Training.
INFO:mlagents.trainers: pyramidAdham2: Pyramids: Step: 120000. Time Elapsed: 275.414 s Mean Reward: -1.000. Std of Reward: 0.000. Training.
INFO:mlagents.trainers: pyramidAdham2: Pyramids: Step: 150000. Time Elapsed: 348.947 s Mean Reward: -0.999. Std of Reward: 0.000. Training.

```

**Environment
- OS: Mac Catalina version 10.15.3
- Unity version: 2019.3.1f1
- _ML-Agents version_: 0.14.1
- _TensorFlow version_: 1.14.0
- _Environment_: Pyramid (with rays)

Please look into it.

**Comment by xiaomaogy** [comment]
Hi @AdamPalmarUnity , this really depends on how you recorded the demonstration. How did you record your own demonstration?

**Comment by AdhamAlHarazi** [comment]
I followed these steps to record the demonstration: 
- added the Demonstration Recorder component
- checked the record checkbox
- removed the NN model 
- Switched to Heuristic only  
- Hit play and started playing with WASD keys.

The resulting .demo file has:
Number Experiences: 4430
Number Episodes: 23
Mean Reward: 1.722

Which is higher than the ExpertPyramid which has:
Number Experiences: 1984
Number Episodes: 13
Mean Reward: 1.694


I do not know how to playback the demo file.

**Comment by xiaomaogy** [comment]
Hi @AdhamAlHarazi thanks for posting this! I raised your issue within the team, and it seems that for now we don't have an easy way to help you debug this problem. We are thinking about adding more metrics to understand the differences between two demo files to get more insight into it, but for now you've tried everything we have. 

(Also I realized that you can't play back an export demo file since there is randomness in the pyramids environment).
