### ISSUE TITLE
gym-unity cannot connect to Unity Editor because DEFAULT_EDITOR_PORT is not defined.

### ISSUE THREAD

**Issue by xXZetserXx** [Unity-Technologies/ml-agents#3534]
When trying to use the gym-unity library to communicate with an open Unity Editor rather than a pre-built Unity binary, I am receiving an attribute error because `gym-unity.envs.UnityEnv` is attempting to use `UnityEnvironment.DEFAULT_EDITOR_PORT` but this is never defined anywhere, and is only referenced on this one line.

**To Reproduce**
```
import matplotlib.pyplot as plt
import numpy as np
import sys

from gym_unity.envs import UnityEnv

%matplotlib inline

print("Python version:")
print(sys.version)

if (sys.version_info[0] < 3):
    raise Exception("ERROR: ML-Agents Toolkit (v0.3 onwards) requires Python 3")

multi_env_name = None 
multi_env = UnityEnv(multi_env_name, worker_id=0, 
                     use_visual=False, multiagent=True)

# Examine environment parameters
print(str(multi_env))
```

**Screenshot**
![image](https://user-images.githubusercontent.com/11846700/75587925-8d6a0400-5a45-11ea-8b06-8f1e2f636698.png)

**Environment:**
- Ubuntu 18.04
- ML-Agents 0.14.0 and ML-Agents 0.14.1
- This occurs while attempting to load the environment

FWIW, I have replaced the call to `UnityEnvironment.DEFAULT_EDITOR_PORT` locally with the actual value (5004) and it seems to work fine afterwards.

**Comment by xiaomaogy** [comment]
Hi @xXZetserXx Does this only happen on Ubuntu? I tried on mac and it seems to use 5004 by default.

**Comment by xXZetserXx** [comment]
@xiaomaogy I don't currently have Unity and ML-Agents setup on another operating system, but I do know of other people who have used the library (although not necessarily the gym-unity portion) on Windows without issue. Is it possible that I need some OS level environment variable needs to be set or something like that?

**Comment by xiaomaogy** [comment]
@xXZetserXx Just realized that you are trying to connect to a Unity Editor on Ubuntu OS. Is this Unity Editor running under Ubuntu or Windows, and how do you ensure the port gets forwarded?

**Comment by chriselion** [comment]
Looks like this issue has been idle for a while. You're right that the usage of `UnityEnvironment.DEFAULT_EDITOR_PORT` was added in [0.14.0](https://github.com/Unity-Technologies/ml-agents/blob/0.14.0/gym-unity/gym_unity/envs/__init__.py#L62), but that appears to be before it was added in [0.15.0](https://github.com/Unity-Technologies/ml-agents/blob/0.15.0/ml-agents-envs/mlagents_envs/environment.py#L66). I'm not exactly sure how that happened (maybe a bad merge or cherry-pick) but everything should be OK now, so I'm going to close this issue.
