### ISSUE TITLE
Ray Gizmos is not available in Heuristic mode

### ISSUE THREAD

**Issue by BlueFisher** [Unity-Technologies/ml-agents#3536]
The Gizmos of RayPerceptionSensorComponent is not available in Heuristic mode. 

When the NN model is None and I click the play button, ML-Agents will get into the Heuristic mode. But I find the `RayPerceptionSensor` will not work. Specifically the `int Write(WriteAdapter adapater);` in `ISensor` will never be called, thus the `m_RaySensor.debugDisplayInfo.rayInfos` will always be `Null`.

BTW, I sometimes need `m_RaySensor` to draw rays with `LineRender`. Could you just make the `m_RaySensor` in `RayPerceptionSensorComponentBase` be `protecetd`.

- _ML-Agents version_: v0.14.0

**Comment by chriselion** [comment]
Hi @BlueFisher,
The gizmo problem has already been reported (https://github.com/Unity-Technologies/ml-agents/issues/3412), plus there were some other requests to draw the gizmos outside of play mode. This was resolved in https://github.com/Unity-Technologies/ml-agents/pull/3484. If you want a "smaller" workaround, https://github.com/Unity-Technologies/ml-agents/pull/3542 (just merged) will step the sensors in Heuristic mode, which should also be enough to get the gizmos drawing.

I'll look into making the sensor more accessible - would a public `get` property be enough instead of making it `protected`?

**Comment by chriselion** [comment]
BTW, I'm curious what you're doing for the line rendering. Are you using https://docs.unity3d.com/Manual/class-LineRenderer.html or something else?

**Comment by BlueFisher** [comment]
Hi @chriselion ,
Thanks for your reply. The Gizmos only shows in the "scene" window of Unity editor but not in the "game" window or in executables. I sometimes need to record the inference process and want to visualize all the rays. So LineRenderer might help me achieve this.

Actually, it would be great if you guys decide to integrate this kind of visualization into `RayPerceptionSensorComponent`. Otherwise, I can implement a simple visualization by myself if I can access to the some properties of `RayPerceptionSensorComponentBase` like `m_RaySensor`.

**Comment by chriselion** [comment]
Sorry, I forgot to update:
There's now a `get` property for the RayPerceptionSensor:
https://github.com/Unity-Technologies/ml-agents/blob/97e4feae106813c0fcbeb2e160a52043fe682b11/com.unity.ml-agents/Runtime/Sensors/RayPerceptionSensorComponentBase.cs#L147-L150

and I made the method for getting the RayPerceptionInput public:
https://github.com/Unity-Technologies/ml-agents/blob/97e4feae106813c0fcbeb2e160a52043fe682b11/com.unity.ml-agents/Runtime/Sensors/RayPerceptionSensorComponentBase.cs#L238-L254

Hopefully that should have you covered.

I'm not sure what other packages like ours do for visualization; do you have any other good examples of "in-game" visualization?

**Comment by BlueFisher** [comment]
Hi @chriselion, Thank you so much.
As for "in-game" visualization, I am so sorry that I'm new to Unity. All I know is the simple LineRenderer. Sorry that I can't give you a good recommendation.

**Comment by chriselion** [comment]
OK, in that case I don't think we'll plan on adding that as a feature; in general, I think we should provide debug visualization via gizmos, but shouldn't draw anything in the "game'.
