### ISSUE TITLE
unity ml-agents not work with newer CUDA version and tensorflow-gpu

### ISSUE THREAD

**Issue by VAD37** [Unity-Technologies/ml-agents#354]
I try to install lastest version of tensorflow-gpu (1.5.0). Python immediately say wrong CUDA version when import tf
`  File "C:\ProgramData\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\platform\self_check.py", line 82, in preload_check
    % (build_info.cudart_dll_name, build_info.cuda_version_number)) `
` ImportError: Could not find 'cudart64_90.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 9.0 from this URL: https://developer.nvidia.com/cuda-toolkit `

Then I saw tutorial install video use CUDA 8.0 && tensorflow-gpu 1.3.0 .
This has really bug me since I took quite some time to find archive version of tensorflow-gpu.

Since we do not have any forum, so, can someone explain if it is possible to update to better version and ml-agents still possible work.

**Comment by awjuliani** [comment]
Hi @VAD37,

Our TensorFlowSharp binaries currently only support models built with TensorFlow 1.4 or earlier. We are working to update them for a future release, but for the time being you will need to train using TF1.4 if you plan on embedding the model into Unity.

**Comment by VAD37** [comment]
Current version only work with Tensorflow 1.4.
Got it thks
