### ISSUE TITLE
Timeout exception when launching with docker

### ISSUE THREAD

**Issue by ReinforcedMan** [Unity-Technologies/ml-agents#3553]
**Describe the bug**

I use UnityEnvironment to train my agents on 3D_Ball by passing it a path to the Unity executable. When building and launching both on windows 10, everything works fine and I'm able to train well. However, when building a linux image from windows and launching the training with the **same config** with a docker on a linux machine, I get a timeout exception:

> mlagents_envs.exception.UnityTimeOutException: The Unity environment took too long to respond. 

**To Reproduce**
1. Pull docker image tensorflow/tensorflow:2.1.0-gpu-py3-jupyter
2. Install all else as in https://github.com/Unity-Technologies/ml-agents/blob/master/Dockerfile
3. Build the environment from windows for linux 
4. Try to create the gym environment

**Console logs / stack traces**

```INFO:mlagents_envs:Environment timed out shutting down. Killing...
Traceback (most recent call last):
  File "/jobdata/job_folder/script/mylib/mylib/main.py", line 323, in 
    sys.exit(main())
  File "/jobdata/job_folder/script/mylib/mylib/main.py", line 168, in main
    env = get_env_initializer(args, worker_id=0, no_graphics=True)()
  File "/jobdata/job_folder/script/mylib/mylib/utils/env.py", line 22, in get_env
    no_graphics=no_graphics, docker_training=docker_training,)
  File "/root/ml-agents/gym-unity/gym_unity/envs/__init__.py", line 78, in __init__
    docker_training=docker_training,
  File "/root/ml-agents/ml-agents-envs/mlagents_envs/environment.py", line 125, in __init__
    aca_output = self.send_academy_parameters(rl_init_parameters_in)
  File "/root/ml-agents/ml-agents-envs/mlagents_envs/environment.py", line 512, in send_academy_parameters
    return self.communicator.initialize(inputs)
  File "/root/ml-agents/ml-agents-envs/mlagents_envs/rpc_communicator.py", line 101, in initialize
    self.poll_for_timeout()
  File "/root/ml-agents/ml-agents-envs/mlagents_envs/rpc_communicator.py", line 94, in poll_for_timeout
    "The Unity environment took too long to respond. Make sure that :\n"
mlagents_envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Agents are linked to the appropriate Brains
	 The environment and the Python interface have compatible versions.
```

**Environment (please complete the following information):**
- OS + version: Windows 10 & Ubuntu 18.04
- _ML-Agents version_: 0.14.1
- Unity version: 2019.3.3f1
- _TensorFlow version_: Doesn't matter as I train with the gym wrapper, but it's 2.1.0
- _Environment_: 3D_Ball

**What I've tried:**
- Running the environment with docker_training=True
- Exposing the port 5005
- Building in headless mode (server mode)

**Comment by xiaomaogy** [comment]
HI @ReinforcedMan, currently our docker feature has been deprecated. As you could imagine with various version of OS and tensorflow version and training configuration and gym versions, it would be super hard to maintain. 

The error you get means the unity environment didn't get connected to the python process within a certain amount of time, but the reason behind it is unclear without further digging into it.
