### ISSUE TITLE
How are the values plotted on the tensorboard graphs calculated?

### ISSUE THREAD

**Issue by elanrosen** [Unity-Technologies/ml-agents#359]
What do they exactly mean and how are they calculated? The documentation just said the trends they should follow.

**Comment by vincentpierre** [comment]
The cumulative rewards and episode lengths are averaged across the episodes since the last summary.
The entropy and value estimates are averaged across the actions taken since the last summary.
The losses are averaged across the network updates since the last summary.

I hope this helps.

**Comment by elanrosen** [comment]
thanks
