### ISSUE TITLE
Configure for real-time object recognition

### ISSUE THREAD

**Issue by VajiraPrabuddhaka** [Unity-Technologies/ml-agents#36]
Is there a possibility to configure this as to create an Augmented Reality application with real-time object recognition??

**Comment by awjuliani** [comment]
Hi @VajiraPrabuddhaka. It is indeed possible.

You would just need to create an agent whose actions correspond to classifying the objects it sees as its observations. So instead of taking an action "jump" it would take an action "dog" when the image is a dog. Hope that makes sense.

**Comment by VajiraPrabuddhaka** [comment]
Hello @awjuliani  Thank you very much for replying me. 
Further I would like to ask whether it is possible to let the application to learn from real-time (operating time) and smooth it's perception by experience??

**Comment by awjuliani** [comment]
Hi @VajiraPrabuddhaka, it is possible to run the simulation at real-time. Instructions to do this are available here: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Agents-Editor-Interface.md#academy

I am not sure what you mean by "smooth its perception by experience" though. Could you give a little more detail?

**Comment by VajiraPrabuddhaka** [comment]
yes @awjuliani  I guess we have to use neural network for object recognition, so the neural network should be train in order to recognize images. I mean that "can we allow these agents to train this while its operating?" so that we can improve the accuracy (guessing probability) using this technique.

**Comment by eagleEggs** [comment]
In theory if you have a system that supports backend python and a custom Unity build stream component, you could have it crunching away while piping an updated unity build (somehow), and then replace the brain over time.... Interesting to think about anyway. Would be super intensive.

**Comment by VajiraPrabuddhaka** [comment]
@awjuliani  and @eagleEggs Can you suggest a way to integrate CNN based training agent into unity..

**Comment by awjuliani** [comment]
Hi @VajiraPrabuddhaka,

You can integrate a CNN using the same default ML-Agents features which are currently provided. The current PPO algorithm includes a CNN-based control agent, for example.

**Comment by VajiraPrabuddhaka** [comment]
@awjuliani can you provide me a coding example for how we can integrate CNN features with agent's brain.

**Comment by awjuliani** [comment]
@VajiraPrabuddhaka,

Please see the "GridWorld" example, which includes a camera used for observations. You can check out the PPO code for an example CNN model as well: https://github.com/Unity-Technologies/ml-agents/blob/master/python/ppo/models.py
