### ISSUE TITLE
.demo File Metadata

### ISSUE THREAD

**Issue by Cpache1** [Unity-Technologies/ml-agents#3601]
When I open the ml-agents Project in Unity and select one of the .demo files, I cannot see the metadata in the inspector. It has stopped showing me this. 

1. Open Project folder with Unity  (2018.4.16f)
2. Go to one of the example demos (Assets/ML-Agents/Examples/3DBall/Demos/Expert3DBall.demo
3. Select it to see it in the Inspector Window
4. I see blank 

**Screenshots**
![Capturar](https://user-images.githubusercontent.com/23500321/76311708-7212ba80-62c9-11ea-8e5c-25acc6c0c7f7.PNG)

I did notice there's a "Missing Mono Script" - I am wondering if that's the problem where is said script and how to add it?

**Environment:**
- Windows 10
- _ML-Agents version_: ML-Agents v0.14.1 (latest_release)
- _TensorFlow version_: 2.0.0
- _Environment_: 3DBall (and all others honestly)

**Comment by alphonsocrawford** [comment]
Hello @Cpache1, I've tried to reproduce this issue with no luck, the necessary `DemonstrationImporter` script is present after a fresh clone of the repository. The script your missing is located here `ml-agents/com.unity.ml-agents/Editor/`, but I would suggest re-cloning the repo as a whole to make sure you're not actually missing the file

**Comment by Cpache1** [comment]
I did have the script, although I don't understand why it wasn't doing what it was supposed to? I just downloaded the repo and copied over the "Project" folder. It fixed it. Thanks!
