### ISSUE TITLE
Timing issue in Heuristic

### ISSUE THREAD

**Issue by zako42** [Unity-Technologies/ml-agents#3609]
Hello, and thanks for all your hard work.

I am having an issue where I'm setting decisions in the Agent Heuristic() method.  I was stepping through the debugger and noticed that Heuristic() was being run multiple times (setting various decision values) but they were not getting to AgentAction().  I went through 5 calls to Heuristic() before the agent called AgentAction(), so it seems to have "missed" some of those decisions I was manually setting.

This is using ml-agents 0.13.1, Windows10, Unity 2018.4.x.

Reproduce by setting a breakpoint in the agent's Heuristic method, and another breakpoint in the agent's AgentAction method.  I thought it would be called one-to-one, meaning Heuristic sets the decision, and it gets used immediately afterwards in AgentAction.  Is this understanding incorrect?

I tried looking into the Agent code, and found that its timing is being triggered by Academy events, using the TimerStack class.  I haven't had time to look in depth yet, but I was hoping someone could correct my understanding, or give me some troubleshooting tips.

Thanks in advance for any assistance.

**Comment by andrewcoh** [comment]
Hi @zako42,

Is your decision period set to 5 in the decision requester component on your agent?  AgentAction is called after a decision period elapses.  A decision period corresponds to the number of fixed updates that occur between decisions.  You can think of AgentAction as setting the action that the agent will execute for the following decision period.  

Setting the decision period to 1 might give you the behavior you want.

**Comment by zako42** [comment]
@andrewcoh I don't have a decision requester component (is this in 0.13.1?).  But, I am using Agent's On Demand Decision.  And now that I thought about it, I realize that I'm calling the `RequestDecision()` in a state machine which is running in a Monobehaviour Update (not FixedUpdate)... This makes sense now.  I am fairly certain this is my bug -- thank you for helping me figure it out!
