### ISSUE TITLE
entropy flat (at zero) when using Colliders and Triggers

### ISSUE THREAD

**Issue by Dastyn** [Unity-Technologies/ml-agents#362]
Hi!

Without collider/trigger script, the learning on an agent does things fine.
But as soon as I introduce colliders and triggers in the game, the learning does the same scenario for ever (entropy is then flat, stuck at zero).

I then added to my agent a sub-GameObject with a collider, and coded in the related script file something like that:
 void OnTriggerEnter(Collider co)
    {   Vector3 p = co.gameObject.GetComponent<Collider>().ClosestPointOnBounds(transform.position);
        if (co.tag != "Finish")
        { print("Finish");
        }
    }

But then cumulative_reward is stuck to (+/-) the same value, and the entropy is null.

Tuning Training Configuration / Target Frame Rate from -1 to 60 does not fix the issue.
(FYI the game has discrete actions and continuous state space).

Any idea/hint please on why just introducing OnTriggerEnter in a separate script (in a sub GameObject to my agent) makes things go wrong?

Thanks in advance.
Dastyn

****** UPDATE *****
Indeed, after further investigations, it seems this does not come from the use of Colliders and Triggers but simply because the CollectState() function collects a "huge" value:
just try state.Add(1e6f); to figure out what occurs!
With state.Add(1e3f); the entropy starts to decrease drastically.
I do understand some normalization should be done on values, but in some cases "big" values should be necessary.
Thanks in advance to confirm or not this behavior with values>1e3f and even higher!
Best,
Dastyn

**Comment by vincentpierre** [comment]
Hi @Dastyn 
I recommend you keep your state between -1 and 1, it is necessary for the neural network to keep the inputs bounded. Can you explain why big values should be necessary in your case ?

**Comment by Dastyn** [comment]
Hello VincentPierre (and thanks for your support and quick answer).

_> Can you explain why big values should be necessary in your case ?_
Typically, by adding a state e.g. about distance on large terrain: 
State.Add((transform.position.x - target.transform.position.x).magnitude);
(that's not the only illustration!)

How to manage this kind of state?
Best,
Dastyn

**Comment by vincentpierre** [comment]
I would do a 
```
State.Add((transform.position.x - target.transform.position.x).magnitude / theLengthOfTheTerrain);
```
But chances are that the agent is not going to be able to use this value correctly to do very local tasks. Imagine I tell you to go to the grocery store next block using a map but I give you a world map. you will not have a good enough resolution. This state should however help the agent figure out if it is close to the edge of the world, or give it a `very general` idea of where he is.

**Comment by Dastyn** [comment]
Yes, this is why I was reluctant to use normalization.
I'm a bit puzzled at this time ...
Maybe, wrt the scope of the action (theLenOfTheTerrain), I could switch from one behavior to another: if possible from one brain to another ...?
Best,
Dastyn

**Comment by vincentpierre** [comment]
If you want your agent to perform a local action, you need to give it local information. Use Raycast, Images, position of the nearest interest point (an enemy for instance)... The network will be able to ignore the position on the map to perform the local task.
If you want to go with a brain switch, you will need to train an agent that can travel (using the global information) and an agent that can perform specific local actions (but you will need to train both)

**Comment by Dastyn** [comment]
OK thanks!
(yes, only one brain per agent, so let's go through activate/deactivate of multiple agents and good curricula!)

Thanks again!
Dastyn
