### ISSUE TITLE
Namespace MLAgents.Sensors does not exist

### ISSUE THREAD

**Issue by Max2x** [Unity-Technologies/ml-agents#3637]
I'm using the 1.14.1 release. when I install the ML-agents 1.14.1 package in Unity and write scripts following the documentation, Unity throws the following errors:

Assets\actionagent.cs(4,16): error CS0234: The type or namespace name 'Sensors' does not exist in the namespace 'MLAgents' (are you missing an assembly reference?)
Assets\actionagent.cs(30,46): error CS0246: The type or namespace name 'VectorSensor' could not be found (are you missing a using directive or an assembly reference?)
Assets\actionagent.cs(15,26): error CS0115: 'actionagent.OnEpisodeBegin()': no suitable method found to override
Assets\actionagent.cs(30,26): error CS0115: 'actionagent.CollectObservations(VectorSensor)': no suitable method found to override
Assets\actionagent.cs(41,26): error CS0115: 'actionagent.OnActionReceived(float[])': no suitable method found to override

These errors get fixed when I install the package from ml-agents-master (ver 1.15.0) but then I cant train because i cannot find python mlagents 0.15.0 anywhere
thank you in advance for any help

**Comment by chriselion** [comment]
Please use the 0.14.1 version of the documentation: https://github.com/Unity-Technologies/ml-agents/tree/0.14.1/docs. The version on the master branch is more recent, and not compatible with the 0.14.1 code.

**Comment by Blueeyesjt1** [comment]
I'm having the same issue. Any fix?

**Comment by jaminaveen** [comment]
I am having the same issues on opening any scenes. Any solution?

**Comment by surfnerd** [comment]
Please make sure your C# code is up to date.  The Sensor namespace was introduced in 0.15.0

**Comment by RamazanBakir** [comment]
Any Update about it ? 
error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Unity.MLAgents' (are you missing an assembly reference?)
I'm taking also like that but eveerything is clear in to the code

**Comment by phingermee** [comment]
Main problem is that current version of "ML-Agents package" in Unity doesn't include "ML-Agents Extensions" which is used in example project
To fix this:
First instal Package from Unity Manager
Then you have to download current release version from git
After it you got 2 ways to install needed package:
1. Instal using link to github
    In the Package Manager hit the "+" button, and select "Add package from git URL"  (<- This one wont solve problem at the moment cause git owner has to accept your request)
    Place there:
                 git+https://github.com/Unity-Technologies/ml-agents.git?path=com.unity.ml-agents.extensions
    Or in the your manifest.json file located in Project -> Packages add next line below "com.unity.ml-agents":
                 "com.unity.ml-agents.extensions": "git+https://github.com/Unity-Technologies/ml-agents.git?path=com.unity.ml-agents.extensions",
2. Local Instalation
    In the Package Manager hit the "+" button, and select "Add package from disk"
    Find "com.unity.ml-agents" in downloaded repo
    Select "package.json"
    Then same steps but with "com.unity.ml-agents.extensions" folder
    (After it you also may spot "UnityEditor.AsyncHTTPClient:Done(State, Int32)" error, it easily fixes by disabeling Edit -> Preferences -> Show Asset Store Search Hits )

**Comment by chriselion** [comment]
Installation instructions for the Extensions package (com.unity.ml-agents.extensions) is [here](https://github.com/Unity-Technologies/ml-agents/blob/master/com.unity.ml-agents.extensions/Documentation~/com.unity.ml-agents.extensions.md#installation).

**Comment by chriselion** [comment]
This discussion has gotten off topic from the original one. Please open a thread on the [Unity ML-Agents Forum](https://forum.unity.com/forums/ml-agents.453/) if you have further questions.

**Comment by RamazanBakir** [comment]
Thank you. I did as you said. I am using it now. I hadn't noticed that the extension wasn't going downloaded.
