### ISSUE TITLE
Specify checkpoint to load

### ISSUE THREAD

**Issue by guillefix** [Unity-Technologies/ml-agents#3638]
**Is your feature request related to a problem? Please describe.**
I think it would be useful to be able to specify the checkpoint to load when using the `--load` option in `mlagents-learn`

**Describe the solution you'd like**
Maybe could specify the checkpoint iteration as an argument after `--load`

**Describe alternatives you've considered**
I guess by default it loads the last checkpoint, so I could just manually delete any older checkpoint if I want to load an earlier one?

**Comment by mbaske** [comment]
I think this method still works: https://github.com/Unity-Technologies/ml-agents/issues/1047

**Comment by andrewcoh** [comment]
Hi @guillefix 

Implementing a robust command line option to support this feature has been in consideration for a while and is currently underway.
