### ISSUE TITLE
Train a "Trained Model" after reach max step.

### ISSUE THREAD

**Issue by we00037890** [Unity-Technologies/ml-agents#3639]
Hello !

I just start using ML-agent. Right now i have a model that reach "max step" and can not be trained anymore.

I can solve the problem by increasing the "max step" in file config. But i would like to ask if we have any other way to reset the "step" of the model back to 0 and train it again (still keep all previous data). 

Thank you in advance.

**Comment by andrewcoh** [comment]
You can resume training with the --load flag.  As it's implemented, --load will set the step count to whatever it was when the previous training session was cancelled.  So, to continue training after you've reached a max step, you can increase the max step in the trainer config, and also run with --load and the same run id.

**Comment by chriselion** [comment]
You can now also pass the `--initialize-from` flag, to restart training from an existing model.
