### ISSUE TITLE
Training mutliple agents against each other

### ISSUE THREAD

**Issue by StarWardo** [Unity-Technologies/ml-agents#3641]
Ml-agents is awesome, it has become my work and hobby! Thanks for that!

I am creating a "cat and mouse" environment , where one agent has to find treasures and the other has to hunt the agent down before he finds the treasure. I have trained one agents to run around and collect treasure. Now I want to add another agent to the env that chases the first agent. Similar to the Hide and Seek level from OpenAI.  

I would like to be able to train two brains in the same env to create a cat.nn model and mouse.nn model.

I checked out self play but in my case the agents have different goals and attributes. 

Would self play work in my case? 

What would be best approach to this? 

I hope I wrote my Issue properly please let me know if anything is missing, thanks.

**Comment by andrewcoh** [comment]
Hi @StarWardo 

The game you describe is an example of an asymmetric game which unfortunately the current implementation of self-play does not support.  It is high priority to extend the implementation to support this case. Keep an eye out over the next few weeks!

**Comment by StarWardo** [comment]
Hello @andrewcoh 

Thanks for the comment!

I will stick to traditional navigation agents as hunters for now.

**Comment by tqtran7** [comment]
Interestingly, I have the exact same use case! Would love to see this implementation as well. Counting down the days when it is ready.
