### ISSUE TITLE
There is no "Use heuristics" checkbox

### ISSUE THREAD

**Issue by jaros3** [Unity-Technologies/ml-agents#3648]
The documentation keeps saying, I need to check `Use Heuristics` check box in `Behavior Parameters`:

https://github.com/Unity-Technologies/ml-agents/blob/latest_release/docs/Learning-Environment-Create-New.md
https://github.com/Unity-Technologies/ml-agents/blob/latest_release/docs/Learning-Environment-Design-Agents.md

But there is no such checkbox:
![image](https://user-images.githubusercontent.com/25296058/76982114-1937c780-6944-11ea-944c-0ed6d76c1ff1.png)

Is documentation outdated? Am I missing something?

**Comment by chriselion** [comment]
No, you're not missing something -  the documentation was out of date. This was fixed on master a few days ago: https://github.com/Unity-Technologies/ml-agents/pull/3568  but is not in a release yet (soon though).

Anywhere it says to check the "Use Heuristic" checkbox, you should set the "Behavior Type" to "Heuristic Only".

**Comment by jaros3** [comment]
Thanks!
