### ISSUE TITLE
Run in batchmode but with initialized graphics

### ISSUE THREAD

**Issue by dlindmark** [Unity-Technologies/ml-agents#3657]
**Is your feature request related to a problem? Please describe.**
Run trainings in `batchmode` but with initialized graphics makes it possible to use visual observations while not rendering any "main camera". The `CameraSensor` calls `.render()` every time the agent needs an visual observation. It seems unnecessary to render a "main camera" at Unitys `Update()` frequency even if the agent might make decisions at a slower frequency.

**Describe the solution you'd like**
Add a `--batch-mode` argument when starting training. When using this argument the environment should be started with just `-batchmode`. I have tried this, and it seems to work,

**Comment by chriselion** [comment]
You should be able to add `--env-args -batchmode` to the commandline to pass the argument to the executable (and any other arguments to want).

**Comment by dlindmark** [comment]
Yes, this seems to work just as well.
