### ISSUE TITLE
ML-Agents v1.0 and Roadmap Update

### ISSUE THREAD

**Issue by unityjeffrey** [Unity-Technologies/ml-agents#3661]
Hi everyone,

We have released ML-Agents v0.15.0 on March 18th.

If you've been following the development of ML-Agents, you have probably noticed a lot of changes in recent months. We are proud to announce that 0.15.0 is our release candidate before we release v1.0.

We want your feedback on this and have a separate discussion thread for ML-A 1.0, click [here](https://forum.unity.com/threads/ml-agents-v1-0-and-roadmap-update-mar-19-2020-discussion-thread.850099/).

Please refer to the release notes for 0.15.0 here:
https://github.com/Unity-Technologies/ml-agents/releases/tag/0.15.0

As usual, please follow our guidelines on where to open issues, bugs, discussion. All feedback welcome and thank you again for your support of ML-Agents.

Jeff

**Comment by Blueeyesjt1** [comment]
I'm looking forward to it! You guys have done an outstanding job. I hope we'll get a lot of updated examples and maybe video tutorials for v1 once you have a stable release out! I know that you guys have been constantly working on this, so maintaining up-to-date tutorials would be quite challenging and wasteful when you're modifying it all the time. Super excited. You guys have helped developers of all ages comes closer to understanding the fundamentals of machine learning- if they didn't already. Thanks for all your guys's hard work.

**Comment by ShettyHarapanahalli** [comment]
This is really cool stuff, Is there a way to simulate robotic arm or a rover with arm (ex- Boston dynamics handle) which generating point cloud from the environment and train up.

**Comment by unityjeffrey** [comment]
hi @ShettyHarapanahalli - we did release a robotics env (UR3 arm) prototype a couple of weeks ago.  See the link here - https://github.com/Unity-Technologies/articulations-robot-demo/tree/mlagents
