### ISSUE TITLE
Migrating.md document missing an entry for v0.15.0

### ISSUE THREAD

**Issue by Xiromtz** [Unity-Technologies/ml-agents#3665]
Not really a bug, but I wanted to point out a missing entry in the Migrating.md file in the docs:

The academy functions "EnableAutomaticStepping()/DisableAutomaticStepping()" were made private and instead one must use "AutomaticSteppingEnabled = true/false".

I found the entry by skimming through the academy code relatively easily, but this should still be added to the docs to make migrating easier.

Thanks for the Help.

**Comment by chriselion** [comment]
Thanks for catching this. It's in the [changelog](https://github.com/Unity-Technologies/ml-agents/blob/master/com.unity.ml-agents/CHANGELOG.md) ("Automatic stepping for Academy is now controlled from the AutomaticSteppingEnabled property") but I forgot to put it in the Migration Guide.

**Comment by chriselion** [comment]
Fixed in https://github.com/Unity-Technologies/ml-agents/pull/3666
