### ISSUE TITLE
Base Port  with 3DBall example and getting started jupyter notebook

### ISSUE THREAD

**Issue by seboz123** [Unity-Technologies/ml-agents#3667]
I am new to ml-agents and unity.
When I tried to load the environment in the getting-started notebook, I found that it wasn't working, because the environment took too long to respond. I found out, that you need to set the base_port in the instatiation of the UnityEnvironment to must be set to 5004, it is not set properly by default. Is this intended?

**Comment by chriselion** [comment]
Hi,
I believe you're right; we currently default the base_port to 5005, regardless of whether an environment path is set or not. A better approach would be
*default base_port to None
*if base_port is None, use 5005 if file_name is specified, else DEFAULT_EDITOR_PORT (5004)

We have this logged in our internal tracker as MLA-709; I'll try to get a fix in for it soon...

**Comment by chriselion** [comment]
PR to clean this up: https://github.com/Unity-Technologies/ml-agents/pull/3673
