### ISSUE TITLE
General stacking of vector observations

### ISSUE THREAD

**Issue by dlindmark** [Unity-Technologies/ml-agents#3676]
**Is your feature request related to a problem? Please describe.**
All vector observations are now stacked the same amount of times, even though the properties between them could be very different. For example could one observation change very rapidly (thus benefiting from more stacked samples) and another might change very slowly (needing much fewer stacks to capture the dynamics). 

**Describe the solution you'd like**
An option to specify how many times each scalar in the vector observation is stacked. I have not updated to mlagents `0.15.0` yet, and saw that you made big changes to vector observations. So I have no input just how to include this change.

**Comment by chriselion** [comment]
Hi,
In theory, this should be possible using a [`StackingSensor`](https://github.com/Unity-Technologies/ml-agents/blob/0.15.0/com.unity.ml-agents/Runtime/Sensors/StackingSensor.cs) wrapped around a [`VectorSensor`](https://github.com/Unity-Technologies/ml-agents/blob/0.15.0/com.unity.ml-agents/Runtime/Sensors/VectorSensor.cs). Unfortunately, I think I went overboard cleaning up the API and made `StackingSensor` `internal`, so you can't do this at the moment.

I've got this logged as MLA-792 in our internal tracker, and will try to get it cleaned up soon.

**Comment by chriselion** [comment]
The class was made public. Closing this issue.
