### ISSUE TITLE
get BuildFailedException when I build with setting that target plaform is Linux

### ISSUE THREAD

**Issue by or350** [Unity-Technologies/ml-agents#3695]
**Describe the bug**

I can build with setting that target platform is Linux when I used ML-Agent (version = 0.10.1). 
However, I get a BuildFailedException when I tried building with ML-Agent (version = 0.14.1).

**To Reproduce**
1. set package ML-Agent (version 0.14.1)
2. Set Build setting like a below screenshot.
![1](https://user-images.githubusercontent.com/62693874/77630455-6cd29280-6f8e-11ea-8964-323dc908022b.PNG)
3. Build

**Console logs / stack traces**

> BuildFailedException: Burst compiler (1.1.1) failed running
stdout:
Burst requires gcc/clang toolchains to be correctly installed in order to build a standalone player for Linux with X64_SSE4
Unable to find /usr/bin/clang or /usr/bin/gcc, is the gcc/clang toolchain installed?
stderr: ...

**Screenshots**
![에러](https://user-images.githubusercontent.com/62693874/77631618-267e3300-6f90-11ea-9160-4e8c3a491772.PNG)

**Environment (please complete the following information):**
- OS + version: Windows 10
- _ML-Agents version_: ML-Agents v0.14.1
- _TensorFlow version_: 1.7.0
- _Environment_: 3DBall

**Comment by surfnerd** [comment]
Hi,
Burst cross-compilation (in your case from Windows to Linux) does not work with the version that you have installed.  This is installed through our dependency on the Barracuda package.
This inability to cross-compile is a known limitation of the Burst package at the version installed.  

You can disable burst compilation from the `Jobs -> Burst` menu to work around this issue.

![Screen Shot 2020-03-26 at 9 22 18 AM](https://user-images.githubusercontent.com/1356616/77670362-56531980-6f43-11ea-9c56-6af8638f0994.png)

I am going to close this for now as this is not an issue with ML-Agents.

**Comment by AsadJeewa** [comment]
disabling compilation does not have any effect. So it is impossible to build to Linux from Windows or are there any other workarounds?

**Comment by surfnerd** [comment]
what do you mean?  Do you still get a burst error? Or do you get another error?

**Comment by surfnerd** [comment]
If you have Unity 2019.1+ you can [disable burst per platform](https://docs.unity3d.com/Packages/com.unity.burst@1.1/manual/index.html#standalone-player-support) in the Unity Project settings.

**Comment by AsadJeewa** [comment]
I am using Unity 2019.2.5f1 and I still get burst error even when I have disabled burst. 

![burst2](https://user-images.githubusercontent.com/27775903/78844975-9c11e680-7a07-11ea-94a3-2a161de2c21c.png)
![burst1](https://user-images.githubusercontent.com/27775903/78844976-9caa7d00-7a07-11ea-8f91-f81a331bfb7d.PNG)

**Comment by AsadJeewa** [comment]
I have a project that I have been working on (Windows 10). Now that I have good results, I want to scale it and perform multiple runs on a high performance computer remotely i.e a Linux system, So I need to cross-build. Your assistance is greatly appreciated.

**Comment by surfnerd** [comment]
Hi @AsadJeewa,
Could you try to open up the Project settings by going to the menu -> Edit -> Project Settings... and disable burst for linux from there?

**Comment by AsadJeewa** [comment]
![image](https://user-images.githubusercontent.com/27775903/78944012-43048a00-7abd-11ea-9cd1-cbed2df1fb0c.png)

You mean here? I did this and it still gives exactly the same BuildFailedException

**Comment by AsadJeewa** [comment]
Another user had the same issue: 
https://forum.unity.com/threads/ive-disabled-burst-compiling-with-mono-still-get-burst-compilation-errors.795810/

**Comment by surfnerd** [comment]
Hi @AsadJeewa,
I'm reaching out to the Burst team now.  I'll get back to you when I get a response.

**Comment by AsadJeewa** [comment]
Thank you so much. Really appreciate it.

**Comment by surfnerd** [comment]
Hey @AsadJeewa,
According to the Burst team, this is a knew issue with Burst 1.1.  We just updated barracuda on our master branch which updates the Burst dependency.  This will allow you to disable it and not see the compile errors.  You can try it out now by checking out our master branch and trying to build for Linux with Burst disabled.  Unfortunately, the fix for cross-compilation with Burst won't be available until they release the 1.3 version of their package.  

You could also install the 0.6.3-preview Barracuda package into your project until you update ml-agents after the next release to get the Burst plugin update. 

Let me know if you run into any issues with these workarounds.

**Comment by AsadJeewa** [comment]
Thank you very much. I upgraded and it successfully builds when I disable Burst.

**Comment by surfnerd** [comment]
This issue is fixed in master since we are on barracuda 0.6.3.  I will close this now and please reopen if it the issue persists.
