### ISSUE TITLE
How do i create periodic reward

### ISSUE THREAD

**Issue by AntonShumin** [Unity-Technologies/ml-agents#37]
I am building an agent that periodically hits the ball. 

If the ball is not hit for a period longer than 2 sec, i would add a negative reward.
So i've added a float that tracks time

`private float m_time_since_last_hit = 0f;`

```
void Update()
{

   m_time_since_last_hit += Time.deltaTime;

   if ( m_time_since_last_hit >2 )
   {
     m_agent.reward = -0.1f;
     m_time_since_last_hit = 0f;    
   }

}
```

```
void RegisterHit()
{
    m_agent.reward = 1f;
    m_time_since_last_hit = 0f;
}
```

But during a simulation, where the time scale is up to a 100, 2 seconds can equal to over 3 minutes of simulated time. 

1. How to i account for the time scale? Can i use `m_time_since_last_hit += Time.deltaTime * Time.timeScale;` or is scaling of time done differently?

2. Should i pass `m_time_since_last_hit` to `CollectState() `?

**Comment by eagleEggs** [comment]
You are able to do it through the Academy:


```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class cavePeopleAcademy : Academy
{

	public float theTime=0f;

    public override void AcademyReset()
    {
    	theTime=theTime+Time.deltaTime;
    }

    public override void AcademyStep()
    {
    	theTime=theTime+Time.deltaTime;
    	Debug.Log(theTime);
    }
}
```

**Comment by awjuliani** [comment]
Hi @AntonShumin,

Thanks for the question, and @eagleEggs thanks for the reply. Please let us know if that solved your problem, and if so we can close the issue. If not, I am happy to look into it further.
