### ISSUE TITLE
Why is agent class instantiated twice?

### ISSUE THREAD

**Issue by MarkTension** [Unity-Technologies/ml-agents#3702]
**Describe the bug**
When printing some tensor shapes from model.py I observed that lines were printed out twice. Found this strange, and when debugging c# saw that the agent class is instantiated twice. I'm using ml-agents15, and this wasn't the case in ml-agents14. 

Can this be a bug?

![bandicam 2020-03-27 11-08-02-258](https://user-images.githubusercontent.com/16321685/77747653-50cb0180-701f-11ea-9438-2134932721f3.png)

**Comment by surfnerd** [comment]
Hi @marktension,
We don’t instantiate your agents for you.  I’m not sure why there are two `this` variables in your debugger.  Did you add a watch for `this`?  Could you add breakpoints in your initialize method in your Agent?  

Are you using the gym wrapper in python?

**Comment by MarkTension** [comment]
@surfnerd Aah Daim. You're right. I'm foolish and accidentally added a watch for this. Thank you for pointing out
