### ISSUE TITLE
API_VERSION in 0.15.1 release

### ISSUE THREAD

**Issue by fredleefarr** [Unity-Technologies/ml-agents#3711]
Small fix - in the 0.15.1 release the environment.py API_VERSION value is 0.15.0 - should be 0.15.1?

**Comment by surfnerd** [comment]
Hi @fredleefarr,
We are only changing the version based on changes in our communication API now.  The current version is correct.  They will no longer follow the release version.  If the API version has caused an issue for you, please open another GitHub issue with the details of the bug.  I am closing this issue for now.  Thank you for your feedback.
