### ISSUE TITLE
Accessing activations from the agent's brain?

### ISSUE THREAD

**Issue by MarkTension** [Unity-Technologies/ml-agents#3712]
**Is your feature request related to a problem? Please describe.**
For my project I'd like to visualize some of the raw activations of the agent's brain. 
For my own case, I'm mostly interested in obtaining the distributions of the action probabilities during runtime for artistic purposes. 
However, in other networks that I've trained I've used this functionality a lot for debugging as well. e.g. checking the activation pattern of the encoder's first layer to see if anything sensical is learned

**Describe the solution you'd like**
Would love to see a c# interface for accessing the brain's specific activations, so they can be experimented with.

**Describe alternatives you've considered**
I was [told](https://forum.unity.com/threads/any-possibilities-accessing-values-from-the-agents-brain.854836/#post-5649964) that this can theoretically already be done via barracuda but that this formal request might mark it for evaluation.

Getting the raw activations to build this kind of insight:
<img width="671" alt="screenshot" src="https://user-images.githubusercontent.com/16321685/78045893-c237e680-7376-11ea-8322-54cb2c9ce16c.png">

**Comment by surfnerd** [comment]
Hi @MarkTension,
Thanks for making a formal request.  This feature request has been brought up internally before.  Hopefully, we can get to it sooner rather than later.  We have logged this request internally as MLA-812.  All updates on this request will be posted on this thread.

**Comment by MarkTension** [comment]
Just checking: any updates in the meantime on this? Or work in progress to try?

**Comment by slantBoy** [comment]
@surfnerd I was following this thread for a while now and was wondering what the status on the topic is. It would be really helpful to get access to the agent's brain to use it for artistic interpretation.

**Comment by surfnerd** [comment]
Hi all,
We still have this feature in our backlog of things we want to do, and since we are a small team we haven't gotten to it yet.  I will post any updates here as they come.
Cheers,
Chris
