### ISSUE TITLE
mlagents-learn cannot show Unity logo and bring up error. how to solve it?? 

### ISSUE THREAD

**Issue by Parktaeryang** [Unity-Technologies/ml-agents#3713]
**Describe the bug**
**MLAGENTS**(anaconda3)

* pip version: pip 20.0.2 from C:\Users\username\anaconda3\envs\ml-agents\lib\site-packages\pip (python 3.6)
* Python version:3.6.7
* OS: window10

protobuf,anaconda3,nuget,python3 etc.

**Description**

**Expected behavior**

**How to Reproduce**

1. Get package from '...'
2. Then run '...'
3. An error occurs.

**Output**
```Traceback (most recent call last):
  File "C:\Users\skygv\anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "C:\Users\skygv\anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Users\skygv\anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (grpcio 1.18.0 (c:\users\skygv\anaconda3\envs\ml-agents\lib\site-packages), Requirement.parse('grpcio>=1.24.3'), {'tensorboard'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\skygv\anaconda3\envs\ml-agents\Scripts\mlagents-learn-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "C:\Users\skygv\anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 3258, in <module>
    @_call_aside
  File "C:\Users\skygv\anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 3242, in _call_aside
    f(*args, **kwargs)
  File "C:\Users\skygv\anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 3271, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Users\skygv\anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "C:\Users\skygv\anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "C:\Users\skygv\anaconda3\envs\ml-agents\lib\site-packages\pkg_resources\__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (grpcio 1.18.0 (c:\users\skygv\anaconda3\envs\ml-agents\lib\site-packages), Requirement.parse('grpcio>=1.24.3'), {'tensorboard'})```
```
Paste the output of the steps above, including the commands themselves and
pip's output/traceback etc.
```


**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Console logs / stack traces**
Please wrap in [triple backticks (```)](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make it easier to read.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**
- OS + version:window10
- _ML-Agents version_: (0.15.1)
- _TensorFlow version_: (pip 20.02 , and latest version)
- _Environment_: (which example environment you used to reproduce the error)

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by Parktaeryang** [comment]
**AND THEN IF I ADD --help Command** 
### output below
**(ml-agents) C:\ml-agents>mlagents-learn --help**
WARNING:tensorflow:From C:\Users\skygv\anaconda3\envs\ml-agents\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
usage: mlagents-learn [-h] [--env ENV_PATH]
                      [--curriculum CURRICULUM_CONFIG_PATH]
                      [--sampler SAMPLER_FILE_PATH]
                      [--keep-checkpoints KEEP_CHECKPOINTS] [--lesson LESSON]
                      [--load] [--run-id RUN_ID] [--save-freq SAVE_FREQ]
                      [--seed SEED] [--train] [--base-port BASE_PORT]
                      [--num-envs NUM_ENVS]
                      [--docker-target-name DOCKER_TARGET_NAME]
                      [--no-graphics] [--debug] [--env-args ...] [--cpu]
                      [--version] [--width WIDTH] [--height HEIGHT]
                      [--quality-level QUALITY_LEVEL]
                      [--time-scale TIME_SCALE]
                      [--target-frame-rate TARGET_FRAME_RATE]
                      trainer_config_path

positional arguments:
  trainer_config_path

optional arguments:
  -h, --help            show this help message and exit
  --env ENV_PATH        Name of the Unity executable (default: None)
  --curriculum CURRICULUM_CONFIG_PATH
                        Curriculum config yaml file for environment (default:
                        None)
  --sampler SAMPLER_FILE_PATH
                        Reset parameter yaml file for environment (default:
                        None)
  --keep-checkpoints KEEP_CHECKPOINTS
                        How many model checkpoints to keep (default: 5)
  --lesson LESSON       Start learning from this lesson (default: 0)
  --load                Whether to load the model or randomly initialize
                        (default: False)
  --run-id RUN_ID       The directory name for model and summary statistics
                        (default: ppo)
  --save-freq SAVE_FREQ
                        Frequency at which to save model (default: 50000)
  --seed SEED           Random seed used for training (default: -1)
  --train               Whether to train model, or only run inference
                        (default: False)
  --base-port BASE_PORT
                        Base port for environment communication (default:
                        5005)
  --num-envs NUM_ENVS   Number of parallel environments to use for training
                        (default: 1)
  --docker-target-name DOCKER_TARGET_NAME
                        Docker volume to store training-specific files
                        (default: None)
  --no-graphics         Whether to run the environment in no-graphics mode
                        (default: False)
  --debug               Whether to run ML-Agents in debug mode with detailed
                        logging (default: False)
  --env-args ...        Arguments passed to the Unity executable. (default:
                        None)
  --cpu                 Run with CPU only (default: False)
  --version             show program's version number and exit

Engine Configuration:
  --width WIDTH         The width of the executable window of the
                        environment(s) (default: 84)
  --height HEIGHT       The height of the executable window of the
                        environment(s) (default: 84)
  --quality-level QUALITY_LEVEL
                        The quality level of the environment(s) (default: 5)
  --time-scale TIME_SCALE
                        The time scale of the Unity environment(s) (default:
                        20)
  --target-frame-rate TARGET_FRAME_RATE
                        The target frame rate of the Unity environment(s)
                        (default: -1)

**Comment by awjuliani** [comment]
Hi @Parktaeryang 

Judging from that error, these seems to be an issue with your tensorflow installation. Can you share the version of TensorFlow you installed?

**Comment by Parktaeryang** [comment]
My tensorflow version is 2.0.1 and estimator is 2.0.1   tensorboard is 2.0.2

**Comment by Parktaeryang** [comment]
#2565 #1513 
And another problem is below

I've done  protobuf  https://github.com/Unity-Technologies/ml-agents/blob/master/protobuf-definitions/README.md 

And i add local package in unity
 
![두번](https://user-images.githubusercontent.com/62952298/78080911-ee278c00-73b7-11ea-8185-9224f577d717.png)
![세번](https://user-images.githubusercontent.com/62952298/78080915-eff14f80-73b7-11ea-8f98-fa577ed67694.jpg)
![google](https://user-images.githubusercontent.com/62952298/78080918-f1227c80-73b7-11ea-96cc-befea4a53696.jpg)

**Comment by awjuliani** [comment]
Hi @Parktaeryang 

Unless you want to use custom protobuf definitions, it is not necessary to build them yourself. Can you try a fresh installation of the ML-Agents package in a new Unity project?

**Comment by Parktaeryang** [comment]
> Hi @Parktaeryang
> 
> Unless you want to use custom protobuf definitions, it is not necessary to build them yourself. Can you try a fresh installation of the ML-Agents package in a new Unity project?
> 
> From your original error, it is also possible that there is a grpc/protobuf version mismatch between what is expected by TensorFlow and what you installed to rebuild the definitions.

I  tried everything . So I reinstalled everything and changed from 0.15.1 into 0.13.1 it worked. But still there is little problem .

**Comment by awjuliani** [comment]
@Parktaeryang 

Can you share a little more about what is still not working for you?
