### ISSUE TITLE
tensorflow 1.5 works?

### ISSUE THREAD

**Issue by Johnzdh** [Unity-Technologies/ml-agents#374]
Last day, I trained the 3DBall model with tensorflow 1.5(and CUDA 9), it seems pretty well. But today I saw somebody said that the tensorflowsharp binaries only support tensorflow <= 1.4. Is there something wrong?

**Comment by awjuliani** [comment]
Hi @Johnzdh,

Were you able to embed the trained model back into Unity using TensorFlowSharp? I believe the incompatibility is around TF# support for models running within the project using the internal brain.

**Comment by gururise** [comment]
@Johnzdh Tensorflow 1.5 worked for training; however, attempting inference using the 1.4 brain on a 1.5 trained model would usually fail for me.

**Comment by Johnzdh** [comment]
@gururise  emmm... What happened to you if you embedded the bytes file trained by 1.5 into Unity?

**Comment by gururise** [comment]
Unity would throw some type of error and it would not work.

**Comment by mmattar** [comment]
Brief update: we plan to upgrade our support to TF 1.5 soon. Closing out this issue.
