### ISSUE TITLE
Write out preliminary .nn models

### ISSUE THREAD

**Issue by lostandsupine** [Unity-Technologies/ml-agents#3740]
**Is your feature request related to a problem? Please describe.**
There can be a lot of iteration necessary with tuning the hyper-parameters and setting up correct rewards.  When using executable environments it would be really helpful to see how the agents are performing during training, whether they are narrowing in on some degenerate or unintended behavior, etc.  Especially when trying to learn a moderately complex game on a slow computer.

**Describe the solution you'd like**
A command line option or parameter in the yaml config to write out preliminary .nn models at set steps, e.g. "write_steps: 1e5"

**Describe alternatives you've considered**
Stopping early and restarting with --load, but this has other problems.  Leaving graphics on, but that would just slow things down and can be hard to actually see what is happening with the increased frame rate.  Manually running export_model() on a checkpoint in python, but I haven't tried and it wouldn't be as convenient.

**Additional context**
Or maybe I am just impatient and can't wait to see what the agents are doing :)

**Comment by awjuliani** [comment]
Hello @lostandsupine 

Thank you for making this request. We have actually had a number of people ask for this recently, and we are looking into a way of making this possible. Currently there is some difficulty based on how TensorFlow deals with "freezing" models (which is required to produce a `.nn` file), but we know how useful it would be for people, so we want to make it happen.

**Comment by chriselion** [comment]
.nn files are now saved at the same time as checkpoints (see https://github.com/Unity-Technologies/ml-agents/pull/4127). This will be in the next release (sometime in August).
