### ISSUE TITLE
Navigating a dynamic environment 

### ISSUE THREAD

**Issue by StarWardo** [Unity-Technologies/ml-agents#3744]
Hello, I am creating an experiment in which the agent has to learn to navigate (move) and avoid obstacles. The environment is generated randomly so that the objects to avoid are always in a different location and with a different size. I will give the agent raycast observations that collide with the obstacles and a goal that it has to reach. 

Goal:

When a user creates an environment the trained agent should be able to navigate in it and avoid obstacles. But the environment that the user creates could be different from the procedural environment in which the agent was trained. For example bigger or smaller, more or less obstacles, ... The user would also be able to change the environment and obstacles as the trained agent is navigating it. 

Now my questions: 

Will the agent learn to actually avoid obstacles as he moves around the environment to find the goals? Or will it start to remember different generated environment setups? (which are not unlimited) 

As far as I observed all the examples have static environments only the wall jump one changes the ramp position but since this environment is so small I could imagine the agent would remember all the different locations.

**Comment by awjuliani** [comment]
Hi @StarWardo 

When it comes to learning via RL, it can often be the case that the agent simply learns to memorize the environment, unless enough variation is included. 

To better discuss this issue, I recommend we move the discussion to the ML-Agents forums, as we are reserving the github issues just to bugs and feature requests: https://forum.unity.com/forums/ml-agents.453/. On the forums we have a large community of users who can provide additional help.

**Comment by StarWardo** [comment]
Done thanks!  Link: https://forum.unity.com/threads/navigating-a-dynamic-environment.861841/
