### ISSUE TITLE
Imitation learning: "ValueError: setting an array element with a sequence."

### ISSUE THREAD

**Issue by zain-noman** [Unity-Technologies/ml-agents#3753]
**Is your feature request related to a problem? Please describe.**
Hi, I was trying to train a model using imitation learning. But when i used the train command i got the error 
"ValueError: setting an array element with a sequence". 
It took me around a whole day to realize that my Heuristic function was returning an array of size greater than the size of vector observations. Fixing that solved my problem. 

Though the issue was a silly mistake, the problem is that there is no indication as to why the error is occurring. I would like if you would add a check of some sort that would notify users when they are making this mistake

PS: using ml-agents 0.14.1

**Comment by andrewcoh** [comment]
Hi @zain-noman 

Can you elaborate a little more on exactly the problem and your solution? I just want to make sure I understand it fully before addressing it.

**Comment by zain-noman** [comment]
Hi,
What happened was that I was recording a demo for imitation learning and I was controlling the character myself using the heuristic function. In my heuristic function i was creating a float array of length 5 (this was an accident and i meant to have length of 4) and returning it. My agent had a discrete Vector Action Space of size 4 with branch sizes of 2,3,3 and 1 respectively. The recording went fine. but when i started training I got the error

"ValueError: setting an array element with a sequence".

I fixed it by fixing my heuristic function which now returned an array of length 4. This solved the issue. Hope this cleared up any ambiguities

**Comment by chriselion** [comment]
@andrewcoh This was fixed by https://github.com/Unity-Technologies/ml-agents/pull/3821 right?

Also (possibly after you logged this) we changed Heuristic so that it takes a `float[]` argument to write to, instead of returning an array; this should make it harder to get the size wrong in the future.

**Comment by andrewcoh** [comment]
Yep, thanks for coming back around to this.
