### ISSUE TITLE
Cumulative Reward and Extrinsic Rewards graphs are different when only extrinsic rewards are used

### ISSUE THREAD

**Issue by niskander** [Unity-Technologies/ml-agents#3754]
Hi, I've brought up this issue before in #3563 but as mentioned there even though this changed behaviour/bug was introduced in the same update as self-play, it happens all the time. 

The issue is that the Cumulative Rewards graph and the Extrinsic Rewards graph no longer look the same even though I'm only using extrinsic rewards. (Before the update, they were always the same.) Example screenshot attached. Zero-sum rewards are used so the cumulative rewards graph is correct; I'm not sure how to interpret the other one. 
![75930654-0e0f7280-5e41-11ea-8a43-413d77a512b1](https://user-images.githubusercontent.com/1988272/78805564-8d87e880-798f-11ea-87ce-0b5ce6f30e74.jpg)

In the migration notes it was mentioned that steps are now counted per-agent rather than as environment steps. I thought maybe that's the reason but the x-axes are the same for both graphs and they appear to have the same number of data points.

Could you please verify whether this changed behavior is a bug or not?

**Comment by andrewcoh** [comment]
Hi @niskander 

The reason for this is that in release v0.15, rewards are averaged over all agents which share a behavior name. So, in zero sum games, this results in the figure you see.  Your concern (raised in the issue [3563](https://github.com/Unity-Technologies/ml-agents/issues/3563)) led us to modify this so that only trajectories collected by the learning agent will be logged in tensorboard.  This is currently on master and will be part of the next release.  

Thank you very much for using this feature and helping us refine it!

**Comment by fedetask** [comment]
What do `Cumulative Rewards` and `Extrinsic Rewards` represent when we have multiple agents in the same instance?

**Comment by niskander** [comment]
@andrewcoh That's great to hear. However, I think there has to be another issue there, because the graphs are not the same even when self-play is turned off and all agents have the same brain. 

Here's an example graph: 
![rewards3](https://user-images.githubusercontent.com/1988272/78999918-9dcbcf00-7b19-11ea-80a4-7103e9e2502b.png)

It looks like the cumulative environment rewards graph is summing the rewards while the extrinsic rewards graph is displaying each one as a separate data point. Again this behaviour is different from what it used to be. Could that be it?

**Comment by andrewcoh** [comment]
@niskander Do you have the same issue with PPO?

**Comment by fedetask** [comment]
I am using PPO with self-play. My environment has fixed episode length, +1 for winning, -1 for losing, and 0 for a draw. The cumulative reward is correct, always zero, while the extrinsic reward shows some spikes.

![extr](https://user-images.githubusercontent.com/32360377/79071223-d8c93080-7cda-11ea-984b-856078c9d545.png)
![cum](https://user-images.githubusercontent.com/32360377/79071224-d961c700-7cda-11ea-9115-6557fc56fb9d.png)

I am not sure I understand the extrinsic reward. Does It show only the reward of the learning team?

**Comment by niskander** [comment]
@andrewcoh Since @fedetask confirmed it for PPO I didn't try. Do you think it's a bug?

**Comment by niskander** [comment]
Issue doesn't exist in more recent versions, closing.
