### ISSUE TITLE
Better explanation of PPO batch and buffer

### ISSUE THREAD

**Issue by fedetask** [Unity-Technologies/ml-agents#3764]
The [PPO Paper](https://arxiv.org/pdf/1707.06347.pdf) says:

> Each iteration, each of `N` (parallel) actors collect `T` timesteps of data. Then we
construct the surrogate loss on these `NT` timesteps of data, and optimize it with minibatch SGD
(or usually for better performance, Adam [KB14]), for `K` epochs

In ML-Agents instead we have three parameters, `time_horizon`, `batch_size`, and `buffer_size`. From my understanding `buffer_size` should be just `N * time_horizon`, but since we can specify it I assume the training is actually performed as follows:

```
while buffer not full:
    for all actors:
        run policy and collect time_horizon timesteps
        put them in the buffer

train agent with batches of batch_size taken from the buffer
```

Is this correct? If yes, I think it should be stated more clearly in the documentation

**Comment by andrewcoh** [comment]
Hi @fedetask 

Buffer size should be a multiple of batch size but time horizon need not be.  One actor can contribute multiple trajectories of length `time_horizon` to a single buffer.
