### ISSUE TITLE
Need hook to unity input manager.

### ISSUE THREAD

**Issue by graybob** [Unity-Technologies/ml-agents#3768]
Hi ,

I request you to add hook from Unity ML to  Unity Input Manager  so that UnityML can generate keystrokes and mouse clicks in form of agent Actions .

The idea is that Unity ML can be a as layer above the core game controlling the Game Players . For example I want to select a bunch of characters and move it to a point , this I want to do from some action in UnityML WITHOUT disturbing the code .

I am sure we can do above action by tweaking some game logic but it would be great if we can do this from UnityML itself . 

Thanks

**Comment by andrewcoh** [comment]
Hi @graybob 

It seems to me that what you are looking for is the Heuristic() method in the agent script. The Heuristic() function enables you to send actions to your agent via keyboard etc. Please see some of our example environments for examples. 

Let me know if you are looking for additional functionality.

**Comment by graybob** [comment]
Hi ,

Heuristic() method is only sending Actions in non training mode to test actions (correct me if I am wrong ) , My request is  , in training mode from  OnActionReceived() , it would be great to have some hook to unity Input manager .

for Example instead of writing below in agent 

 public override void OnActionReceived(float[] vectorAction)
    {
case k_Right:
                targetPos = transform.position + new Vector3(1f, 0, 0f);
                break;
}

I would request something like 

 public override void OnActionReceived(float[] vectorAction)
    {
case k_Right:
                SetKey(A); // the logic corresponding to this action will be game but not in agent so from agent we only pass keystrokes , the game will receive this keystrokes and perform corresponding logic will be executed , this way we can keep ML as controller logic above game without modifying game files. 
                break;
}
