### ISSUE TITLE
Missing Ray Layer Mask description in docs

### ISSUE THREAD

**Issue by fedetask** [Unity-Technologies/ml-agents#3769]
In the Ray [Design Agents](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design-Agents.md) documentation the Ray Perception parameter `Ray Layer Mask` is not mentioned. I am a bit confused about what does it do and if it interacts with the `Detectable Tags` parameter.

![Screenshot from 2020-04-12 18-57-18](https://user-images.githubusercontent.com/32360377/79074916-89d9c600-7cef-11ea-9ee8-9ebef68c3675.png)

**Comment by andrewcoh** [comment]
Thank you for pointing this out. We will clarify this parameter in the documentation.

In Unity, you can associate each object with a 'layer'.  The layer mask in the ray perception script enables you to use raycasts that ignore certain layers i.e. if you want to have ray casts that only detect a ball and you want to prevent the raycasts from being obstructed by other agents.

**Comment by chriselion** [comment]
The documentation for this was updated a while ago. Closing this.
