### ISSUE TITLE
Heuristic method called but not implemented in Agent Roller

### ISSUE THREAD

**Issue by RLranger** [Unity-Technologies/ml-agents#3783]
Hi there, 

I tried to implement the Rolleragent with the latest version of Ml-agents (0.15.1). However, after I follow the step to build the environment, the roller agent doesn't move by using Heuristic mode.

There are two warnings appears here:

1.Heuristic method called but not implemented. Returning placeholder actions.
UnityEngine.Debug:LogWarning(Object)

2.Fewer observations (0) made than vector observation size (8). The observations will be padded.
UnityEngine.Debug:LogWarningFormat(String, Object[])
![snip](https://user-images.githubusercontent.com/39267665/79343244-c4966500-7f60-11ea-9b49-6154dbf5d485.PNG)

Do you have any ideas about this problem?

**Environment (please complete the following information):**
- Windows 10]
- _ML-Agents version_: 0.15.1 
- _Environment_: RollerAgent

**Comment by anupambhatnagar** [comment]
@RLranger looking at your screenshot this may not be a bug. Have you tried to resolve the warning message "the model expects 2 visual inputs, but only found 0 visual sensors." I encourage you to post the issue on our forum. https://forum.unity.com/forums/ml-agents.453/

**Comment by TristanBertin** [comment]
Have you fixed your error ? I have the same issue...

**Comment by RLranger** [comment]
> Have you fixed your error ? I have the same issue...

I didn't solve this, so I turn back to the previous version.

**Comment by chriselion** [comment]
@RLranger @TristanBertin - the file you have for your model (`continuous2vis8vec2action.nn`) is a sample file we use for unit tests; it's not supposed to be used for the example.

For the heurisitc, please make sure you have the Heuristic method defined for your Agent. Note that the signature of the method changed between the 0.15 release and the latest release (1.0.0):
https://github.com/Unity-Technologies/ml-agents/blob/0.15.1/docs/Learning-Environment-Create-New.md#testing-the-environment
https://github.com/Unity-Technologies/ml-agents/blob/release_1_docs/docs/Learning-Environment-Create-New.md#testing-the-environment
