### ISSUE TITLE
Gym wrapper: Could not pickle the task to send it to the workers.

### ISSUE THREAD

**Issue by Fabien-Couthouis** [Unity-Technologies/ml-agents#3788]
**Describe the bug**
Hi all and thanks for your work,

I am using gym wrapper 0.15.1 on default 3DBall environnement (12 agents) provided on mlagents 0.15.1.  Unfortunatly, I cannot use parallelisation due to a PicklingError. Is it a bug, or this functionnality is not supported yet? Maybe I missed something.

**To Reproduce**
Code to reproduce the behavior:
```python
from joblib import Parallel, delayed
from gym_unity.envs import UnityEnv

# Get environment
env_path = r"<PATH_TO_BUILT_ENV>"
env = UnityEnv(worker_id=0, no_graphics=True,
               environment_filename=env_path, multiagent=True)

def get_env(env):
    return env

Parallel(n_jobs=2)(delayed(get_env)(env=env) for i in range(2))
```

**Console logs / stack traces**
```
Exception has occurred: PicklingError
Could not pickle the task to send it to the workers.
```

**Environment (please complete the following information):**
- OS + version: Windows 10
- _ML-Agents version_: mlagents==0.15.1, mlagents-envs==0.15.1, gym-unity==0.15.1
- _TensorFlow version_: tensorflow==2.0.1
- _Environment_: 3DBall 

Thanks!

**Comment by anupambhatnagar** [comment]
@vincentpierre do you happen to have any input here?

**Comment by anupambhatnagar** [comment]
Hi @Fabien-Couthouis a couple of thoughts:
- the gym wrapper may not support more than one agent 
- it probably not possible to pickle the entire unity executable.

**Comment by Fabien-Couthouis** [comment]
Thanks for the answer!
I tried on 3DBall with only one agent  and  multiagent=False and still have the error so the problem should not come from the multiagent.

**Comment by anupambhatnagar** [comment]
As mentioned in the previous comment, I think its not possible to pickle the Unity executable.

**Comment by anupambhatnagar** [comment]
for further discussions about this issue, please reach out to us in the ML-Agent forum. https://forum.unity.com/forums/ml-agents.453/
