### ISSUE TITLE
Error while installing mlagents 15.0.1

### ISSUE THREAD

**Issue by Hsgngr** [Unity-Technologies/ml-agents#3794]
While following the installation instructions, I had an error at:

> install the mlagents Python package, activate your virtual environment and run from the command line:
> 
> pip3 install mlagents
 
When I try to install mlagents I am getting following error:

**ERROR: Could not find a version that satisfies the requirement tensorflow<2.1,>=1.7 (from mlagents) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3)
ERROR: No matching distribution found for tensorflow<2.1,>=1.7 (from mlagents)**

**To Reproduce**
1. Go to 'https://github.com/Unity-Technologies/ml-agents/blob/0.15.1/docs/Installation.md'
2. Do the parts until 'pip install mlagents'

**Environment:**
- OS + version: Windows 10
- _ML-Agents version_:latest stable release 15.0.1
- _TensorFlow version_:  I tried with 2.0.1 /2.2.0rc3/0.15.0/0.12.0
- _Environment_: I used anaconda to create the environment with python 3.7
-Python: Python 3.7.7 (default, Apr 15 2020, 05:09:04) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

Things that I tried:

- multiple tensorflow version

- checked that I am running my python in x64

**Comment by ninazrdl** [comment]
Same.
And I tried by git clone & pip install -e too. Not working.

**Comment by Hsgngr** [comment]
My error has been solved when I tried to use virtualenv instead of Anaconda.
The cmd commands that I used:

`virtualenv --python=.<your Python 3.7 file> <newEnvironment>`

Mine was like this:
`virtualenv --python=..\AppData\Local\Programs\Python\Python37\python.exe vnv`

this creates a new virtual environment called vnv.

![image](https://user-images.githubusercontent.com/32769732/79591551-5cbb5800-80e1-11ea-85a7-ceabb766588d.png)
