### ISSUE TITLE
Imitation Learning in multiple sesssions

### ISSUE THREAD

**Issue by Xiromtz** [Unity-Technologies/ml-agents#3795]
Hi,
I'm asking for a feature that I might have missed, but seems to not exist. I want to do some recording for my agent, though the recordings might take up to 20 minutes or longer.
Is there a way to record in multiple sessions, i.e. continue recording with the same file? Or can I somehow add multiple record files to the imitation learning algorithm? Additional problems may also be something crashing after 15 minutes of play. I'll have to do everything from the beginning, even if the recording was saved.
Also, Unity keeps on throwing errors about infinite loops when the demonstration recorder saves once i go out of play mode, although it doesn't seem to be affecting anything. I'm using v0.15.1 if that helps.

**Comment by anupambhatnagar** [comment]
Hi @Xiromtz based on conversations with my colleagues we recommend trying out the following:
"Adding multiple recording files to the imitation learning is possible. I think you need to put them all into a folder and then pass the path to the folder in the yaml file".

Let us know if this works.

**Comment by anupambhatnagar** [comment]
This documentation page may be of help
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Reward-Signals.md#gail-reward-signal

**Comment by Xiromtz** [comment]
I'll give it a try tomorrow, thanks for the reply!
I do have a quick question:
The GAIL algorithm is gone into detail and the original paper is referenced. 
Is there any literature the behavioral cloning algorithm is based on?

**Comment by Xiromtz** [comment]
And one more question: 
Is it possible to combine the demonstrations with curriculum learning? I.e. I have a recording for each curriculum and can change the used demonstration depending on the current curriculum?
Using a recording of the first curriculum makes my agent act really nicely in the first curriculum, but not in later curricula. Conversely, if I use longer recordings of multiple curricula, the agent just does not perform in the first one.

**Comment by Xiromtz** [comment]
Referencing a folder with multiple demonstrations seems to be working. Thanks!

**Comment by anupambhatnagar** [comment]
that's great! I'll close the request as it has been resolved.
