### ISSUE TITLE
CoreBrainInternal throws error when trying to use an internal brain with observations. 

### ISSUE THREAD

**Issue by ashwal** [Unity-Technologies/ml-agents#38]
This line (197) fails `runner.AddInput(graph[graphScope + placeholder.name][0], new float[] { Random.Range(placeholder.minValue, placeholder.maxValue) })`. 

I grabbed the latest script and it now throws an exception but I've confirmed that epsilon is set on the brain. `Debug.Log` shows that `graph` is failing to return anything, the other vars have values (except `graphScope`, could that be the problem?). 

I also noticed when trying to debug that the GridWorld example does not have an internal brain option, related? 

Brain screenshot attached.
<img width="313" alt="screen shot 2017-09-26 at 11 04 17 am" src="https://user-images.githubusercontent.com/433628/30876122-8a1194f8-a2aa-11e7-98ed-f2bea59afbf8.png">

**Comment by vincentpierre** [comment]
Hi! Can I ask you what is the error reported in the console ? What are the inputs and outputs of the `robot-env.bytes` graph? I think this error might occur because there is no placeholder called epsilon in the graph.

**Comment by ashwal** [comment]
@vincentpierre Now the Try Catch block snags it but before it was: 

> 
> NullReferenceException: Object reference not set to an instance of an object
> CoreBrainInternal.DecideAction () (at Assets/ML-Agents/Scripts/CoreBrainInternal.cs:198)
> Brain.DecideAction () (at Assets/ML-Agents/Scripts/Brain.cs:312)
> Academy.DecideAction () (at Assets/ML-Agents/Scripts/Academy.cs:250)
> Academy.RunMdp () (at Assets/ML-Agents/Scripts/Academy.cs:337)
> Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:260)

**Comment by vincentpierre** [comment]
My best guess is that  there are no placeholder called epsilon in your `robot-env.bytes` graph. Can you try removing the graph placeholder (set its size to 0) in the inspector and see if the error is different?

**Comment by awjuliani** [comment]
Hi @ashwal,

If you used discrete actions, then there won't be a need for an `epsilon` value, since that corresponds to continuous control models which need to sample noise in order to decide their action.

**Comment by ashwal** [comment]
@awjuliani yep that cleared it up 👍 Maybe a table in the docs that disambiguates the parameters/setup needed for each condition?

**Comment by awjuliani** [comment]
Agreed. We currently don't make it clear the reason `epsilon` is added to the 3DBall demo. Glad you were able to get it working.
