### ISSUE TITLE
'DecisionSteps' object has no attribute 'done'

### ISSUE THREAD

**Issue by MashiroCl** [Unity-Technologies/ml-agents#3809]
**Describe the bug**
I'm using the master branch because I need to build to Linux from Windows (In the issue 3695 said I should use the master branch), and when I'm trying to get 'done' of a 'DecisionSteps' I get an error:
 AttributeError: 'DecisionSteps', object has no attribute 'done'
And I found that none of 'DecisionSteps','DecisionStep','DecisionStep','TerminalSteps','TerminalSteps' has the field 'done'

**To Reproduce**
1. set package ML-Agent (0.16.0.dev0, the current master branch)
2. Using the python API and choose an Unity Environment(eg. named UnityEnvironment) exported by unity
3. code like
```
env_name=r"\UnityEnvironment"
import numpy as np
from mlagents_envs.environment import UnityEnvironment
from mlagents_envs.side_channel.engine_configuration_channel import EngineConfig, EngineConfigurationChannel

engine_configuration_channel = EngineConfigurationChannel()
env = UnityEnvironment(file_name=env_name)
env.reset()
agents=env.get_behavior_names()
group_name = agents[0]
group_spec = env.get_behavior_spec(group_name)

step_result=env.get_steps(group_name)
print(step_result[0].done)`

```
console error
```
AttributeError                            Traceback (most recent call last)
<ipython-input-1-7eb49134f8dd> in <module>
     54 print("step result is ",step_result)
     55 print("step.obs result is ",step_result[0].obs)
---> 56 print(step_result[1].done)
     57 
     58 

AttributeError: 'TerminalSteps' object has no attribute 'done'

```

**Environment (please complete the following information):**
- Windows 10
- current master branch (pip list told me it is 0.16.0)
- _Environment_: tennis

**Comment by anupambhatnagar** [comment]
Hi @MashiroCl there have been changes in the low level API and hence this error. I recommend 
to not use done and instead consider the agent done if it is in the TerminalSteps.

**Comment by MashiroCl** [comment]
Thank you for your reply. What do you mean by 'using the agent done'? I haven't found any information about agent done in the Python-API docs

**Comment by anupambhatnagar** [comment]
Agent Done is on the C# side. It is supposed to be called when the episode is finished.
