### ISSUE TITLE
SideChannelUtils Missing in Sidechannels

### ISSUE THREAD

**Issue by scerelli** [Unity-Technologies/ml-agents#3814]
**Describe the bug**
I'm trying to follow the Unity penguins tutorial that introduces to the use of ML-Agents, i was trying to migrate from 0.13 to 0.15.1.

What i did so far: 
replaced `FloatProperties` with ` SideChannelUtils.GetSideChannel<FloatPropertiesChannel>().RegisterCallback`. Unfortunately it seems that `SideChannelUtils` is not in the MLAgents namespace. I'm new to unity so maybe i did something wrong but i did nothing special so far.

**To Reproduce**
1. install last version of unity
2. creat a new project
3. import com.mlagents via package manager using local package
4. create a Academy class like: 

```
using MLAgentsExamples;
using MLAgents;
using MLAgents.SideChannels;

public class PenguinAcademy : MonoBehaviour
{
    public float FishSpeed { get; private set; }

    public float FeedRadius { get; private set; }

    public void Awake() {
        FishSpeed = 0f;
        FeedRadius = 0f;

        SideChannelUtils.GetSideChannel<FloatPropertiesChannel>().RegisterCallback("fish_speed", f => 
        {
            FishSpeed = f;
        });

        SideChannelUtils.GetSideChannel<FloatPropertiesChannel>().RegisterCallback("feed_radius", f => 
        {
            FeedRadius = f;
        });
    }
}
```

**Console logs / stack traces**
```
Assets\Scripts\PenguinAcademy.cs(24,9): error CS0103: The name 'SideChannelUtils' does not exist in the current context
Assets\Scripts\PenguinAcademy.cs(19,9): error CS0103: The name 'SideChannelUtils' does not exist in the current context
```

**Environment (please complete the following information):**
- OS + version: Windows 10
- _ML-Agents version_: 0.15.1
- _Environment_: anaconda, python 3.7, Unity 2019.3.10f1

Any Idea?

**Comment by MashiroCl** [comment]
I met this problem too, the unity console said 'SideChannelUtils' does not exist in the current context, have you solved this problem or get any other idea?

**Comment by scerelli** [comment]
@MashiroCl no luck yet
