### ISSUE TITLE
Latest_release Tag

### ISSUE THREAD

**Issue by noshaba** [Unity-Technologies/ml-agents#3859]
Maybe not a bug per se but why does the "latest_release" tag redirect you to tag 0.13.0 rather than to 0.15.1?

**Comment by vincentpierre** [comment]
Thank you for signaling this to us. (I think it does qualify as a bug)
We have made 0.15.1 the latest_release and we will be investigating why the latest_release was set to 0.13.0. 
For reference : MLA-956
