### ISSUE TITLE
CSV summaries are overwritten

### ISSUE THREAD

**Issue by Xiromtz** [Unity-Technologies/ml-agents#3861]
Hello,
When pausing and returning to the same training session via the --load parameter, the model is resumed and everything is summarized into a single graph in TensorBoard.

When looking at the .csv files though, I can only see a single file for my current training session. This single file seems to be overwritten everytime I resume training via --load.

Now the solution would be to simply move the .csv somewhere else before using --load, but this seems cumbersome and I have a lot of training data I want to output to matlab.

For now, it looks like TensorBoard supports converting charts to .csv. 
Still, the mlagents-learn outputted .csv getting overwritten looks to be a bug.

**Comment by vincentpierre** [comment]
Hi,
We were able to reproduce this issue. Unfortunately, we plan to deprecate the CSV export of data in a later release so we will not be addressing this issue now. 
Like you said, it is possible to directly download the CSV from tensorboard if that is a suitable substitute. For other users looking for a substitute : Check the `Show data download links` on tensorboard and you will be able to download a CSV for each curve.
