### ISSUE TITLE
15.0 and 15.1 won't show "Start training by pressing the play button in the Unity Editor" in console when initialising training

### ISSUE THREAD

**Issue by philippds** [Unity-Technologies/ml-agents#3862]
**Describe the bug**
When I initialize training with "mlagents-learn config/trainer_config.yaml --run-id=wall-jump-curriculum --train" for example, the console window is showing the usual unity logo and in version 14.1 the last lines say: "Start training by pressing the play button in the Unity Editor", unfortunately, that does not happen anymore in 15.0 or 15.1, the last lines show "Instructions for updating: non-resource variables are not supported in the long term", after that I hit play in the Unity Editor, and it works fine (training). Now I'm wondering, is this a known bug or did I set up incorrectly? Others reported similar issues. Thank you!

**To Reproduce**
Standard way of training an agent using the console and unity editor

**Console logs / stack traces**
Last line shown:
Instructions for updating: non-resource variables are not supported in the long term

**Environment (please complete the following information):**
- Windows 10
- _ML-Agents versions: ML-Agents v15.1
- _TensorFlow version_: 2.0.1
- _Environment_: any of example envs

**Comment by vincentpierre** [comment]
Hi,

We logged the bug (MLA-960) and pushed the following fix on our next release branch : #3874
