### ISSUE TITLE
TensorBoard does not output episodic information

### ISSUE THREAD

**Issue by Xiromtz** [Unity-Technologies/ml-agents#3863]
I have an agent that is supposed to navigate through a larger level. This agent receives a negative reward at every time-step and a positive reward in the case of it finding the goal.

Now using the cumulative reward statistic, I can *kind* of see the progression through the reward function. I believe the information I read through this progression over all time-steps is kind of falsified.

A much simpler and for me more readable statistic would be an episodic average of rewards. Where the x-axis is the episode count or an average of episodes (epochs) and the y-axis is the cumulative reward.

I understand that the current statistics are meant to work for both continuous and episodic tasks, though I would much prefer more detailed statistics.

Is there a way I can modify the mlagents-learn python files to add this functionality? I can't imagine this statistic being very hard to implement, even if I have to implement it myself.

FYI, I opened a similar issue a few weeks ago, but cannot reopen it, so I created a new one here after commenting on it and realizing i can't reopen.. (doh!). (issue number was #3737)

**Comment by vincentpierre** [comment]
Hi, 
I think this would be informative, unfortunately, all of our plots have "number of steps" on the x-axis right now. The plots on tensorboard must work for all environments trained with ML-Agents, plotting the number of steps seems to be the solution that fits most use cases at this time.

I think it might be possible to generate this type of graph by modifying these lines of code.
https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents/mlagents/trainers/trainer/rl_trainer.py#L58
If you would like to make a PR or a draft of a PR, we can have a look at it. 
Internal tracking : MLA-958

**Comment by Xiromtz** [comment]
Thanks for the reply!  I understand that its the more general approach.

I realized I can also just write to a .csv within Unity, since I manually restart episodes there anyway, I can just call GetCumulativeReward and track that in a file.

I wanted to plot the data in matlab anyway, so its not much of an effort difference for me.
