### ISSUE TITLE
How an agent can change its brain?

### ISSUE THREAD

**Issue by pooyanjamshidi** [Unity-Technologies/ml-agents#39]
In order to have a flexible cooperative architecture (e.g., ``Mergeable nervous systems for robots``, Nature 2017), the ability to chain the brain, at any point, seems essential. I was wondering whether it is possible for the agents to change their brain at ``runtime``? Also, is it possible to form a structure that can be changed at runtime for cooperative tasks?

**Comment by awjuliani** [comment]
Hi @pooyanjamshidi,

Thanks for your interest in ML-Agents. We've built in the ability to change brains during training. An agent can call its `GiveBrain()` function to replace the current brain with a different one.

I am curious what you mean by structure that can be changed? Does this apply to the structure of the agent itself, or the environment?

**Comment by pooyanjamshidi** [comment]
Hi @awjuliani,

Thanks for your prompt reply.
 
In the cooperative scenario, I assume several agents can interact to finish a task. In this scenario, one or several agents may fail for whatever reason. How might new agents be recruited in order to join the other agents for finishing the task? More specifically, is there any mechanisms through which we could define a structure (e.g., delegating sub-tasks) and change the structure over time, many examples of which can be seen in nature, the way birds travels, or fishes go for hunting, etc.

**Comment by awjuliani** [comment]
Hi @pooyanjamshidi, You can change the structure of the problem dynamically, so long as the state and action spaces remain fixed.
