### ISSUE TITLE
timeScale bug in EngineConfigurationChannel (gym_unity)

### ISSUE THREAD

**Issue by ghost** [Unity-Technologies/ml-agents#3918]
**Describe the bug:**
- I am using an environment with "gym_unity" and I can't modify timeScale value between 1 and 100.

**To Reproduce:**
- To edit timeScale value I modified this following file:
  - class UnityEnv(gym.Env): 
     - I added "side_channels: [] = None" in "def__init()"
     - I added "side_channels = side_channels" in "self._env = UnityEnvironment()"

- I call environment as follows:
     - channel = EngineConfigurationChannel()
     - self.env = UnityEnv(self.env_name, worker_id=0, use_visual=False, side_channels=[channel])

     If I execute environment in this way, timeScale = 1. 

- Otherwise if I inset this line below:
     - channel.set_configuration_parameters(time_scale = t)  # note: t is any value between 1 and 100

   timeScale = 100 regardless value of t.

- I tried also to edit directly "EngineConfigurationChannel.cs" in Unity before build the environment. But didn't work.

**Environment:**
- OS + version: Windows 10
- _ML-Agents version_: v0.13.1

**Comment by GProulx** [comment]
Hi @OcinProgrammer , 

It's working fine for me with version 0.15.1.  Possible for you to upgrade and test it?

**Comment by OcinProgrammer** [comment]
Hi @GProulx ,

Sorry for my late reply...

I can't upgrade, because I have to deliver this project soon, I dont'have time to upgrade and change some things to make it works.

Is it possible to know how do you fix it in version 0.15.1 to apply to my 0.13.1?

**Comment by surfnerd** [comment]
Hi @GProulx,
Sorry for the late response.  I hope you were able to resolve this issue in the version you were using.  Since this bug was fixed in a later release of ML-Agents, I am closing this issue.  Thank you for your feedback.
