### ISSUE TITLE
tensorboard:about how to display mlagent modle graph in tensorboard

### ISSUE THREAD

**Issue by strikeman1** [Unity-Technologies/ml-agents#3920]
Does anyone know how to display mlagent modle graph in tensorboard

**Comment by surfnerd** [comment]
Hi @strikeman1, this is not an appropriate request for github.  The `request` label is meant for feature requests.  Please ask these types of questions in the [ml-agents forum](https://forum.unity.com/forums/ml-agents.453/).  
Also this question has been answered in #2062 already.  Please search for answers before posting a new issue. 
Cheers,
Chris

**Comment by strikeman1** [comment]
but the question have not bean solved right now,do you know how to solve it?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chris Goy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月5日(星期二) 凌晨1:12
收件人:&nbsp;"Unity-Technologies/ml-agents"<ml-agents@noreply.github.com&gt;;
抄送:&nbsp;"奈何 瞧！"<1481902338@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Unity-Technologies/ml-agents] tensorboard:about how to display mlagent modle graph in tensorboard (#3920)





 
Hi @strikeman1, this is not an appropriate request for github.  The request label is meant for feature requests.  Please ask these types of questions in the ml-agents forum.
 Also this question has been answered in #2062 already.  Please search for answers before posting a new issue.
 Cheers,
 Chris
