### ISSUE TITLE
cant observe the model performing in external mode when load_model=true

### ISSUE THREAD

**Issue by ghost** [Unity-Technologies/ml-agents#393]
I want to see in what the brain has learned by loading the trained model
when I set the trainModel to **false** and loadModel to **true** in the PPO.ipynb and run the script, the unity environment opens and suddenly closes on its own I don't know what I am doing wrong
please guide.

**Comment by vincentpierre** [comment]
There might be an error in the unity Environment. Please look at the log files generated : [LogFiles](https://docs.unity3d.com/Manual/LogFiles.html). Was there an error in python ?
