### ISSUE TITLE
Learning doesn't work properly after loading

### ISSUE THREAD

**Issue by Fagin-H** [Unity-Technologies/ml-agents#3941]
When using --load to continue training, the resulting training stats seem to fail. E.G. the Elo suddenly plummets after loading.

![Screenshot (63)](https://user-images.githubusercontent.com/33319563/81479219-e4e0d900-9219-11ea-83d6-b62b974a4ece.png)

**Comment by andrewcoh** [comment]
Hi @Fagin-H 

When you resume an existing training run with self-play, the ELO is reset to the default value.  However, the loaded policy should still be correct.  We are aware that this is not ideal and are working on a fix. We have noted this as a limitation in this [README](https://github.com/Unity-Technologies/ml-agents/tree/release_1_branch/ml-agents). 

Also, if you are not already doing so, I encourage you to use the recent 1.0 release as there were some self-play bug fixes.
