### ISSUE TITLE
UnityTimeOutException: Couldn't start socket communication because worker number 10 is still in use. You may need to manually close a previously opened environment or use a different worker number.

### ISSUE THREAD

**Issue by ShivanshuPurohit** [Unity-Technologies/ml-agents#3942]
When I run the following code in colab
`env = UnityEnvironment(file_name='/content/Reacher_Linux_NoVis/Reacher.x86_64', worker_id=10, seed=10)`
I get the aforementioned error
UnityTimeOutException: Couldn't start socket communication because worker number 10 is still in use. You may need to manually close a previously opened environment or use a different worker number.

I get the error no matter what worker_id I set it just says the passed worker_id is in use.

**Comment by Locke637** [comment]
I encountered this bug too, I have to wait for about 20 seconds to run again.

**Comment by harperj** [comment]
Hi @ShivanshuPurohit @Locke637 -- there is a known issue with some Linux distributions where a port is reserved for up to 60 seconds after the application is closed.  We can't do much about that issue, unfortunately.

@ShivanshuPurohit are you instantiating the environment multiple times?  or will an environment never actually launch?  We'd appreciate any specific steps to reproduce the issue.

**Comment by ShivanshuPurohit** [comment]
Sorry for the delay.

Steps to reproduce the error (I encountered this error in colab):
`#get the Unity reacher environment for a "headless" version
!wget https://s3-us-west-1.amazonaws.com/udacity-drlnd/P2/Reacher/Reacher_Linux_NoVis.zip
!unzip "content/Reacher_Linux_NoVis.zip"
!pip install unityagents
from unityagents import UnityEnvironment
env = UnityEnvironment(file_name='Reacher_Linux_NoVis/Reacher.x86_x64', worker_id=5)`

**Comment by ay1011** [comment]
Hi ShivanshuPurohit, I managed to run it after shutting down run time on Colab and then running just env = UnityEnvironment(file_name='Reacher_Linux_NoVis/Reacher.x86_x64')

**Comment by hvpeteet** [comment]
I realize this has been stale for over a year, as a side effect of https://github.com/Unity-Technologies/ml-agents/pull/5553 this should not longer occur since it allows socket re-use. Once it is included in releases (release 19+) this should go away.
