### ISSUE TITLE
ImportError: cannot import name 'UnityToGymWrapper' from 'gym_unity.envs' 

### ISSUE THREAD

**Issue by seboz123** [Unity-Technologies/ml-agents#3944]
Hi,

I am trying to run the gym wrapper of ml-agents. I installed ml-agents release 1 from source. Then I went into the gym-unity folder and installed gym unity with:
`pip3 install -e .`
Unfortunately when I try to import the UnityToGymWrapper I run into this problem, python does somehow not find the package even so it is shown in pip list and I just start python from the same environment:

`>>> from gym_unity.envs import UnityToGymWrapper
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'UnityToGymWrapper' from 'gym_unity.envs' (C:\Users\...\Desktop\RLUnity\ml-agents\gym-unity\gym_unity\envs\__init__.py) `

I tried to install it normally with pip install gym_unity , but then my versions are not matching.
`ERROR: mlagents 0.15.1 has requirement mlagents_envs==0.15.1, but you'll have mlagents-envs 0.16.0 which is incompatible.`

Any help is appreciated, thanks!

**Comment by RedTachyon** [comment]
So are you trying to install 0.15.1 or 0.16.0? Either way maybe try reinstalling the packages specifying the correct version?

**Comment by seboz123** [comment]
Also the folder envs under `C:\Users\...\.conda\envs\tensorflow_2_src_gpu\lib\site-packages\gym_unity\envs\__init__.py` only contains an __init__.py and __pycache__ directory. Shouldn't there be the file UnityToGymWrapper?

**Comment by seboz123** [comment]
Ok, somehow this bug only happens when I install the repo with the source files. If I install it with pypi without the source files, it seems to work
