### ISSUE TITLE
Please Implement `env.render(mode='rgb_array') `

### ISSUE THREAD

**Issue by vwxyzjn** [Unity-Technologies/ml-agents#3954]
**Is your feature request related to a problem? Please describe.**
The current implementation does not always honor the standard rendering API of the gym environment. Namely, `env.render(mode='rgb_array') ` usually return `None` for the examples such as 3DBall or Basic. This API however, is commonly used to record a video of the agents'  performance (see https://github.com/openai/gym/blob/master/gym/wrappers/monitor.py). Here is an example:

```
import gym
from gym.wrappers import TimeLimit, Monitor
env = gym.make("CartPole-v0")
env = Monitor(env, 'video_demo')
observation = env.reset()
for _ in range(1000):
  env.render()
  action = env.action_space.sample() # your agent here (this takes random actions)
  observation, reward, done, info = env.step(action)

  if done:
    observation = env.reset()
env.close()
```

that produces these files:

![image](https://user-images.githubusercontent.com/5555347/81765294-6b5b1c00-94a1-11ea-84b6-f7a9819c5546.png)
![image](https://user-images.githubusercontent.com/5555347/81765358-98a7ca00-94a1-11ea-8884-6af5029d241e.png)

**Describe the solution you'd like**
The current solution has some game examples that use visual pixels as inputs, so perhaps it can be designed in ways that the visual pixels can always be requested regardless of the type of observation. This solution will allow me to do a simple interactive benchmark for all the mlagents games with videos demonstrating the agents performance throughout training like in http://cleanrl.costa.sh/.

Thanks.

**Comment by awjuliani** [comment]
Hi @vwxyzjn 

Thanks for making this request. Because of the way in which rendering takes place in Unity, it is not straightforward to pass the rendered screen to gym every step of the simulation. I agree though that this is a useful feature, and we will keep this request in mind going forward.

**Comment by yijiezh** [comment]
Hi,

Is there any progress in this feature?

**Comment by awjuliani** [comment]
Hi @yijiezh 

We have not started work on this feature, but it has been logged. Unfortunately there is not a "for free" way to get rendered images out of Unity, so we will have to make modifications to the toolkit and communication protocol in order to enable this.
