### ISSUE TITLE
Consider using pythonnet instead of socket for interfacing C# and Python

### ISSUE THREAD

**Issue by vwxyzjn** [Unity-Technologies/ml-agents#3958]
**Is your feature request related to a problem? Please describe.**
The current implementation uses socket to communicate betwen C# and python, which can be a major bottleneck to performance. I ran a simple profiling on the following example script 

```python
from mlagents_envs.environment import UnityEnvironment
from gym_unity.envs import UnityToGymWrapper
unity_env = UnityEnvironment(
    file_name="Project/Binaries/Basic.x86_64")
env = UnityToGymWrapper(unity_env, flatten_branched=True)

observation = env.reset()
for _ in range(1000):
  env.render()
  action = env.action_space.sample() # your agent here (this takes random actions)
  observation, reward, done, info = env.step(action)

  if done:
    observation = env.reset()
env.close()
```

![image](https://user-images.githubusercontent.com/5555347/81767782-436eb700-94a7-11ea-9b44-ed964f642998.png)

And it's evident that the script spent the majority of time to do communication between C# and Python.

**Describe the solution you'd like**
One possible solution is to replace socket with a solution that natively interfaces using CPython API internally. One such project is http://pythonnet.github.io, which allows the python to directly interact with the .NET Common Language Runtime (CLR). 

Unfortunately I am not very familiar with C# so I couldn't do an examble to benchmark the speed difference between pythonnet and socket, but I have personal experience doing something similar interfacing Java and Python. I have been working on a gym wrapper (https://github.com/vwxyzjn/gym-microrts) for MicroRTS (https://github.com/vwxyzjn/microrts). 

Initially, we were also using socket to do communication (https://github.com/vwxyzjn/gym-microrts/blob/cde0e1e25e6d123a41cccec7c632ce493066deca/gym_microrts/envs/base_env.py#L61-L96). Code is very difficult to read, hard to maintain, complicated to add new features, and need to consider low-level details such as how many bytes can I send. The current implmenetation uses Jpype (https://jpype.readthedocs.io/en/latest/) which, to my understanding, is the same kind of library as pythonnet. Jpype allows me to create a Java object in python and call its methods natively using JNI (Java Native Interface) internally. The core code that does communication roughly becomes

```
# setup
import jpype
from jpype.imports import registerDomain
import jpype.imports
from jpype.types import *
registerDomain("ts", alias="tests")
registerDomain("ai")
jpype.addClassPath(os.path.expanduser(os.path.join(self.config.microrts_path, "microrts.jar")))
jpype.startJVM(convertStrings=False)
from ts import JNIClient
from ai.rewardfunction import RewardFunctionInterface, SimpleEvaluationRewardFunction
rfs = JArray(RewardFunctionInterface)([SimpleEvaluationRewardFunction()])
client = JNIClient(rfs, os.path.expanduser(self.config.microrts_path), self.config.map_path)

# gym interaction
response = self.client.reset()
obs = np.array(response.observation)
action = np.array([1])
response = self.client.step(action)
obs = np.array(response.observation)
reward = response.reward[:]
done = response.done[:]
info = json.loads(str(response.info))
```
where the java side code is defined here https://github.com/vwxyzjn/microrts/blob/master/src/tests/JNIClient.java, which is significantly simpler than the socket version.

And here is the lottery. Consider a task that has 600x600 pixel observation space for 1000 timesteps. I don't remember the exact number, but the version that uses socket spent about 1 minutes, while the jpype version took seconds.  I remeber roughly it was **20-100x** speed up that actually makes a qualitative difference since the communication was the bottleneck. In addition, this improvement will also likely to help with #3954. So just think you guys might be interested in looking into this.

Have these thoughts in mlagents for quite some time and today finally wrote it up. Great work and great potential, but the current user experience for researchers who don't want to customize games could be improved (I spent days before figuring out how to compile binaries programmtically without using the editor, which has some displaying issues at linux under HiDPI, as shown below. But if I just want to run some test script on an example game, the whole process perhaps should be simplified)

![image](https://user-images.githubusercontent.com/5555347/81769670-330d0b00-94ac-11ea-8090-c42bfa5da472.png)

Thanks.

**Comment by awjuliani** [comment]
Hi @vwxyzjn 

We actually don't use bare sockets, but instead use gRPC to communicate protobuf objects. We have evaluated a number of different options, and decided on this as a good balance between usability, performance, and maintainability. We are of course always looking to improve performance, and will take this into account as we do so.
