### ISSUE TITLE
How to use different algrithms in an enviroment to train different models?

### ISSUE THREAD

**Issue by autoli** [Unity-Technologies/ml-agents#3982]
I find that the agents of examples in the mlagents are all designed by the same configurations, but it's necessary for us to train different agents using different algrithms , configuations ,different observations or rewards at the same time just in an enviroment.
For example,there are two different agents in an enviroment. While an agent  is needed to train by PPO, another agent is needed to train by SAC. So they're different models which have different configurations but must be trained at the same time. I read the mlagents docs completely but  I am still confused about the method to figure out the code. 
Please give some examples or demos to finish it in a simple task. I think it's an important point that most people cares about.

**Comment by awjuliani** [comment]
Hello @autoli 

This is very possible with the current ML-Agents. All you have to do is give different "Behavior Names" to your different agents within the Unity scene, and then in your `.yaml` configuration file, add separate entries for each of the behavior names. For example, if you have a soccer game with a goalie and striker behavior names, you can set the striker to use ppo and the goalie to use sac.

**Comment by dongruoping** [comment]
Since the issue has been resolved, I'll close the issue.
