### ISSUE TITLE
Google Collab version of Release 1.0

### ISSUE THREAD

**Issue by ugurkanates** [Unity-Technologies/ml-agents#3984]
Hello , not sure if this is right place but I saw removal of notebooks & probability of adding a Collab version.

I have created a Rainbow DQN with Categorical features working on Collab.

If anyone interested can look at my repository. I'm not sure If there is a plan to add them or should i clean them up and open a PR for it?

https://github.com/ugurkanates/MLAgents-Google-Collab

**Comment by awjuliani** [comment]
Hi @ugurkanates 

Thanks for sharing this. We are very open to PRs around collab notebooks to use as example for our users. I think we would want the notebook to be relatively simple and demonstrate basic functionality of the `mlagents` or `mlagents-envs` packages. If you are willing to create a modified version of the repo you shared with just that functionality, we'd be happy to take a look at a PR based on it.

**Comment by ugurkanates** [comment]
I have cleaned up my example code to work like old Unity ML agent notebooks. No training or agent related code.
Just showing how to make random moves in both discrete & continuous environments.

Though I have possible question where to store headless/server binaries. In current code I'm holding them in my repository. Obviously this has to change for PR related

https://github.com/Unity-Technologies/ml-agents/pull/3990
