### ISSUE TITLE
Typo: Sensor sizes much match

### ISSUE THREAD

**Issue by sangue18** [Unity-Technologies/ml-agents#3986]
Typo in SensorShapeValidatorTests.cs (and maybe others) feedback to console:
"Sensor sizes much match" > "Sensor sizes must match"

SensorShapeValidatorTests.cs Lines 115, 121, 143, .....

**Environment (please complete the following information):**
- _ML-Agents version_: Release 1 / April 30, 2020

**Comment by sangue18** [comment]
Sorry, can't downgrade the label from Bug to anything less dramatic.
Complete File reference is
 ml-agents/com.unity.ml-agents/Tests/Editor/Sensor/SensorShapeValidatorTests.cs

**Comment by chriselion** [comment]
Thanks @sangue18 for catching this. I've got a fix in https://github.com/Unity-Technologies/ml-agents/pull/3987

**Comment by chriselion** [comment]
Fixed, closing.
