### ISSUE TITLE
Couldn't connect to trainer on port 5004 using API version 1.0.0. Will perform inference instead.

### ISSUE THREAD

**Issue by xz-xiong** [Unity-Technologies/ml-agents#4007]
**Describe the bug**
when I play 3Dball example, has error ->
Couldn't connect to trainer on port 5004 using API version 1.0.0. Will perform inference instead.

**To Reproduce**
click play button

**Console logs / stack traces**
-

**Screenshots**
-

**Environment (please complete the following information):**
- Unity Version: Unity 2019.3.14f1
- OS + version: Mac 10.15.4
- _ML-Agents version_: ML-Agents  0.16.1
- _TensorFlow version_: 2.2.0
- _Environment_: I set virtual environment as installation described 

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by DanTulovsky** [comment]
Did you run the mlagents-learn script first?  That's what it's trying to connect to.

**Comment by xz-xiong** [comment]
> Did you run the mlagents-learn script first? That's what it's trying to connect to.

thanks, now I figure out it works now
