### ISSUE TITLE
Unity freezes when you press play in ML-Agents Basic example scene

### ISSUE THREAD

**Issue by mhr** [Unity-Technologies/ml-agents#4008]
**Describe the bug**
Unity freezes when you press play in ML-Agents Basic example scene

**To Reproduce**
1. `git clone --branch release_2 https://github.com/Unity-Technologies/ml-agents.git`
2. Launch Unity Hub
3. On the Projects dialog, choose the Add option at the top of the window.
4. Using the file dialog that opens, locate the Project folder within the ML-Agents Toolkit and click Open.
5. In the Project window, go to the Assets/ML-Agents/Examples/Basic/Scenes folder and open the Basic scene file.

**Console logs / stack traces**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/1429247/82613856-6595c280-9b94-11ea-96e1-bf66b240605c.png)

After pressing play, Unity remains stuck like this until I kill it with Windows Task Manager^

**Environment (please complete the following information):**
- Unity Version: Unity 2018.4.17f1
- OS + version: Windows 10
- _ML-Agents version_: ML-Agents v1.0.2-preview
- _TensorFlow version_: TensorFlow v2.2.0
- _Environment_: Basic

**Comment by unityjeffrey** [comment]
hi @mhr - to confirm, it does not look like you are running python process to start training.

**Comment by mhr** [comment]
Yes, but regardless of if I set Behavior Type to "Inference Only" (which shouldn't require a Python process for training, right?), it still freezes.

**Comment by mhr** [comment]
I can no longer reproduce this bug. I wish I knew why.
