### ISSUE TITLE
Create new behaviors while running 

### ISSUE THREAD

**Issue by fedetask** [Unity-Technologies/ml-agents#4009]
**Is your feature request related to a problem? Please describe.**
I am exploring evolutionary-RL training, where new agents need to be created on-line during training. 

**Describe the solution you'd like**
A way to instantiate -during training- a new Agent script with a different behavior name, that from that point will be trained. The new agent only needs to have a different behavior name, the rest of the parameters remain the same.

**Describe alternatives you've considered**
I'm going through the code to see whether this could be done, but I cannot find a way of doing it without modifying ml-agents code.

**Comment by unityjeffrey** [comment]
that is interesting - can you elaborate a bit more detail on the request for this type of functionality.  you are right in that you would likely need to modify the python and C# code.

CC @ervteng @awjuliani @andrewcoh

**Comment by fedetask** [comment]
We were developing a Terrarium with different creatures, predatory and preys, and we thought it would have been interesting to put together RL with evolutionary operators. In particular, each species has different reward functions for doing different things. When a new specie is created, I need to instantiate its new agents under a new behavior name, since their reward function is different. 

I can imagine it can require quite some changes in the code and I understand something like this is not a priority

**Comment by cabesd** [comment]
Couldn't this be done thru the side_channels (configuration or environment parameters)?

**Comment by andrewcoh** [comment]
I think that this will work if you use the Unity function `Instantiate` with the prefab/gameObject of the agent somewhere in your game code i.e. area controller.  The main training loop should recognize a new behavior name and create the new trainer etc.
