### ISSUE TITLE
How is the training affected by using one agent instead of multiple agents in PPO?

### ISSUE THREAD

**Issue by Lakrix** [Unity-Technologies/ml-agents#401]
Hi, 

What is the effect of using several agents instead of one in PPO? Is it just a matter of increasing learning speed?

**Comment by vincentpierre** [comment]
Using several agents connected to the same brain allows the python trainer to collect more information at every step. Note that if you have too many agents, you can run into slowdowns due to the communication between Unity and Python.
I hope this helps.

**Comment by Lakrix** [comment]
Thanks for the explanation

Cheers
