### ISSUE TITLE
Documentation: unclear how to find "ML-Agents Toolkit"

### ISSUE THREAD

**Issue by increpare** [Unity-Technologies/ml-agents#4010]
**Describe the bug**
There was a small gap in the installation instructions, where going from the installation guide to the getting started page, it assumes you've downloaded ml-agents (I can say this might seem obvious yes, but it was not obvious to me) .

**To Reproduce**
I'm on window. I followed https://github.com/Unity-Technologies/ml-agents/blob/release_2/docs/Installation.md exactly, omitting the optional step "Clone the ML-Agents Toolkit Repository (Optional)"

The next recommended page is https://github.com/Unity-Technologies/ml-agents/blob/release_2/docs/Getting-Started.md

However, all I've done up to this point (following the installation guide to the best of my abilities) are 
*installed unity
*installed python
*installed a unity package
*installed a python package

I don't have any local files.

Oh, am I meant to download the ml-agents package from https://github.com/Unity-Technologies/ml-agents if I don't clone the repo?  If this is the case, it'd be helpful if the installation guide said it explicitly something like "either you download a release of this repo, or you clone the entire repo".    It was not obvious to me, and would've saved me some confusion.

**Comment by unityjeffrey** [comment]
hi @increpare as of version Release 1, you technically do not need to install from the Github repo (you install the C# package from the Unity Package manager and the Python using PIP).

However, you are correct in that it is not clear.  I will update the documentation and copy / paste the PR here.
