### ISSUE TITLE
Instantiation of UnityEnvironment is blocking statement

### ISSUE THREAD

**Issue by cabesd** [Unity-Technologies/ml-agents#4014]
Hi there!

My pipeline used to use version 0.12 and now I'm upgrading to the Release 1. I only use the Python UnityEnvironment class to interact with the binary file. I don't use the mlagents trainer.

**Steps to Reproduce**
- I have downloaded the repo for Release 1
- Installed MLAgents 1.0.0 (tried both from local repo AND pip cloud package)
- Open the new Unity Project from the Release 1 with Unity Hub.
- Took out the model from the Agent Gameobject
- Verify the Project Settings given in [docs/Learning-Environment-Executable.md](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Executable.md). They look good on my end. Tried ILCPP but did not help.
- Build the Basic environment
- Open a notebook and instantiate the just builded binary, and for some reason the instantiation of the UnityEnvironment is a blocking statement.

I'm not very familiar with Unity and not finding any meaningful log that could point me in some direction. Could someone help me any direction where to look for the issue?

**Console logs / stack traces**
No outputs on the terminal where I use to see the errors. 
Is there any other log file that I could look at?

**Screenshot**
![Screen Shot 2020-05-22 at 4 24 27 PM](https://user-images.githubusercontent.com/9100535/82715963-1ad68200-9c4a-11ea-9bac-b433fe4f375d.png)
Note on the above image that the line `u.get_behavior_names()` is never executed. Or anything after the instantiation.

There's probably something else that I'm missing here...

**Environment**
MacBook Pro Mid 2015
Mac OS Catalina 10.15.2
Unity version 2019.2.15f1
Unity Hub 2.3.1
MLAgents Release 1

**Comment by cabesd** [comment]
Changed Unity version to 2018.4.23f1 and now 3DBall and PushBlock started working.
When I try to do Basic environment, the instantiation is still a blocking statment.

**Comment by unityjeffrey** [comment]
hi @cabesd - can you open you request on the forums for help (https://forum.unity.com/forums/ml-agents.453/)?  Unfortunately, we can't debug setups that are not standard (i.e. using a different trainer).
