### ISSUE TITLE
Learning-Environment-Create-New rollerball_config.yaml is missing sequence_length parameter

### ISSUE THREAD

**Issue by gregaton** [Unity-Technologies/ml-agents#4016]
https://github.com/Unity-Technologies/ml-agents/blob/release_2_docs/docs/Learning-Environment-Create-New.md#training-the-environment is missing the `sequence_length` parameter.

mlagents-learn is not able to run the config without it.

**Comment by unityjeffrey** [comment]
hi @gregaton - thanks for finding.  I created a PR for this.  
https://github.com/Unity-Technologies/ml-agents/pull/4023

**Comment by chriselion** [comment]
This was addressed in https://github.com/Unity-Technologies/ml-agents/pull/3936 - closing.
