### ISSUE TITLE
why I use GAIL to train, the  agent is easy to be Local convergence

### ISSUE THREAD

**Issue by 745976804** [Unity-Technologies/ml-agents#4017]
I'm new unity, when I use GAIL to train example the RollerBall, but the ball is easy to fall, and why is that? the code as follow.
Auv:
    normalize: true
    num_epoch: 3
    time_horizon: 1000
    batch_size: 2024
    buffer_size: 20240
    max_steps: 5.0e5
    summary_freq: 2000
    num_layers: 3
    hidden_units: 512
    reward_signals:
        gail:
            strength: 1.0
            gamma: 0.99
            encoding_size: 128
            demo_path: demos/AUV02.demo

**Comment by unityjeffrey** [comment]
hi @745976804 - please use the Unity Forum (https://forum.unity.com/forums/ml-agents.453/) and provide more details there on your issue.
