### ISSUE TITLE
RayPerceptionSensor list of colliders

### ISSUE THREAD

**Issue by kahabal** [Unity-Technologies/ml-agents#4018]
Hi, working on sensors and for the future would be very useful to have a list of colliders that the sensor perceived, like it works for Physics.Raycast when you can get the "out hit".

i had to recreate the same pattern with Physics.Raycast and it is time consuming, i checked the forums but could not find it

thanks,
D

**Comment by unityjeffrey** [comment]
thanks @kahabal.  cc @chriselion

**Comment by kahabal** [comment]
dear @unityjeffrey and @chriselion  is the Ray sensor based on the Physics.Raycast? if so, do you think it will be possible to have the same as Physics.SphereCast ? thanks

**Comment by chriselion** [comment]
Sorry for the delay. I think we could store the collider of the hit in the `RayOutput` struct. We wouldn't use it by default, but if you're using the static version of `Perceive()`, it could still be useful. Does cover what you need?

**Comment by kahabal** [comment]
dear @chriselion , i tried and i have one more question...

I created a very simple scene, my agent with a RayPerceptionSensorComponent3D in front of a tagged ball,

in start:
r1 = this.GetComponent<RayPerceptionSensorComponent3D>();
r2 = r1.GetRayPerceptionInput();

in update:
r3 = RayPerceptionSensor.Perceive(r2);
foreach (RayPerceptionOutput.RayOutput ro in r3.RayOutputs) {
            Debug.Log(ro.HasHit+" "+ro.HitTaggedObject+" "+ro.HitTagIndex);
}

and it works: True, True, 0 (is the number of the Tag of the ball)
False, False, -1 if i move the object away from the ball.

QUESTIONs:

a) in normal agent scripting, the Perceive is done automatically?

because i am trying since days to create an agent with several sensors (like a matrix of 5x5 sensors with just 1 ray) and i receive the same behaviour (the reward and learning curves of my agent on the TensorBoard) also WITHOUT the RayPerceptionSensorComponent3D... so i doubt that it is working... there are simple ways to verify if the sensors are capting something?

b) should i always use Perceive in the update (fixed?) to receive NEW infos from the sensors?

c) what is in case the difference between Perceive() and Update() that is in the RaySensor?

Thanks a lot,
Dario

**Comment by chriselion** [comment]
You didn't answer my question before - would storing the hit collider in `RayOutput` be helpful?

In response to your questions:

a) Perceive isn't called directly, but it does the equivalent work. RayPerceptionSensorComponent3D creates a RayPerceptionSensor, and RayPerceptionSensor.Write calls PerceiveSingleRay:
https://github.com/Unity-Technologies/ml-agents/blob/9d57ff95f36811d4710db3b41644e6c4fed4f6a2/com.unity.ml-agents/Runtime/Sensors/RayPerceptionSensor.cs#L316

This is the same method called inside Perceive:
https://github.com/Unity-Technologies/ml-agents/blob/9d57ff95f36811d4710db3b41644e6c4fed4f6a2/com.unity.ml-agents/Runtime/Sensors/RayPerceptionSensor.cs#L376

The difference is that in RayPerceptionSensor.Write, we convert the output to an array of floats right away.

b) You don't need to call Perceive if you have a RayPerceptionSensorComponent3D attached to the Agent. This will automatically result in an observation being created for the Agent, which will be used for training and inference.

c) RayPerceptionSensor.Update() is empty :)
https://github.com/Unity-Technologies/ml-agents/blob/9d57ff95f36811d4710db3b41644e6c4fed4f6a2/com.unity.ml-agents/Runtime/Sensors/RayPerceptionSensor.cs#L332-L334
but all of the raycasting work happens in the Write() method. As I said above, this should be identical to what happens in Perceive(), except that RayPerceptionSensor.Write also stores some debug information that the Gizmo drawing uses.

**Comment by kahabal** [comment]
thank you for your clarification !!!! it helped a lot

to your question: yes, RayOut can be a good place to store infos, in fact i checked and some infos are already there, the only different is that we don't know who's the collider that get the hits now

**Comment by kahabal** [comment]
one more question, the RaySensor.Update() is already called in the FixedUpdate() by default??
thanks

**Comment by chriselion** [comment]
Each ISensor.Update() is called in the Agent's update:
https://github.com/Unity-Technologies/ml-agents/blob/9d57ff95f36811d4710db3b41644e6c4fed4f6a2/com.unity.ml-agents/Runtime/Agent.cs#L920-L926
This gets called every time the Agent requests a decision, which could be less often than each FixedUpdate - if you're using DecisionRequester, it will be whatever the DecisionPeriod is.

ISensor.Write() (where the raycasting happens for RayPerceptionSensor) is also called each time a decision is requested. This is called from different locations, depending on whether you're doing training or inference.

**Comment by chriselion** [comment]
I created a PR here: https://github.com/Unity-Technologies/ml-agents/pull/4111
It turns out that storing the Collider isn't a great solution, because 2D raycasting would need a Collider2D. So instead I'm storing the GameObject, which you would be able to use to get the Collider if you wanted it.

**Comment by chriselion** [comment]
RayOutput now stores the hit GameObject.
