### ISSUE TITLE
ButtonUp or ButtonDown on Heuristic method doesn't work properly

### ISSUE THREAD

**Issue by rsta80** [Unity-Technologies/ml-agents#4019]
I'm training a 2D game, the problem es when the agent jumps, it needs to release the key when it jumps, in my heuristic method I have the following code:

public override void Heuristic(float[] actionsOut)
    {
        actionsOut[0] = Input.GetAxisRaw ("Horizontal");
		//Jumping
        actionsOut[1] = Input.GetButton("Jump") ? 1f : 0f;
        //Dashing
        actionsOut[2] = Input.GetButton("Dash") ? 1f : 0f;
        //Crouch
        actionsOut[3] = Input.GetButton("Crouch") ? 1.0f : 0.0f;
        //Shooting
        //actionsOut[4] = Input.GetButtonDown("Dash") ? 1.0f : 0.0f;

        bool shoottest = Input.GetButtonDown("Dash");
        if (shoottest)
            actionsOut[4] = 1f;

        bool jumpReleasetest = Input.GetButtonUp("Jump");
        if (jumpReleasetest)
        {
            actionsOut[5] = 1f;
        }

    }

But, when I test Input.GetButtonUp("Jump") in Update method it works perfectly, but I couldn't add to the OnActionReceived(float[] action) method

The problem happens only with GetButtonUp, GetButtonDown, GetKeyUp, GetKeyDown

Environment
- Unity 2018.4.22
- Windows 10
- _ML-Agents version_: ML-Agents 1.0 release
- _TensorFlow version_: 1.15

**Comment by surfnerd** [comment]
Hi @rsta80, 
What does your action function look like?

**Comment by surfnerd** [comment]
Also, looking at the docs for [`GetButtonDown`](https://docs.unity3d.com/ScriptReference/Input.GetButtonDown.html) it seems that it only works in the `Update` method.  This means you have to cache your action value in the update method and then set it when your `Heuristic` method is called.  For example:

```
void Update()
{
    m_JumpValue = Input.GetButtonDown("Jump") ? 1.0f : 0.0f;
    m_DashValue = Input.GetButtonDown("Dash") ? 1.0f : 0.0f;
    ...
}

void Heuristic(float[] actions)
{
    actions[4] = m_DashValue;
    actions[5] = m_JumpValue;
    ...
}
```

Let me know if this works for you. Thanks.

**Comment by rsta80** [comment]
Hi @surfnerd 

I tried caching it in update method, but when I test it, doesn't work properly

I did this:

```
void Update() {
        m_jumpHeld = Input.GetButton("Jump") ? 1.0f : 0.0f;
        m_jumpRelease = Input.GetButtonUp("Jump") ? 1.0f : 0.0f;
        if (m_jumpRelease == 1f)
        {
            Debug.Log("Button jump release pressed");
        }
}
```
And my heuristic method

```
public override void Heuristic(float[] actionsOut)
    {
        actionsOut[0] = Input.GetAxisRaw ("Horizontal");
        //Jumping
        actionsOut[1] = m_jumpHeld;
        //Jump Release
        actionsOut[3] = m_jumpRelease;
        if (actionsOut[3] == 1f)
        {
            Debug.Log("jump release action true");
        }
    }
```

When I run the game I have the following behavior:

![image](https://user-images.githubusercontent.com/20643610/83015852-5c3ba880-a021-11ea-8694-95137ac7fbdb.png)

I don't know if the both methods can work simultaneously, i was searching in the ml-agents examples but there are not this kind of implementation,  and why it happens  only with Input.GetButtonUp, Input.GetButtonDown, Input.GetKeyUp, Input.GetKeyDown

Thank you for your reply :)

**Comment by surfnerd** [comment]
Hi @rsta80,
Can you elaborate on what you mean when you say "it doesn't work properly?"

**Comment by rsta80** [comment]
I did the modifications you suggested me, but when I release the jump button, in most of the cases 
`actionsOut[3] = m_jumpRelease;
        if (actionsOut[3] == 1f)
        {
            Debug.Log("jump release action true");
        }`

Doesn't print in console, and the agent doesn't recieve in `OnActionReceived` the right value, I don't understand why it get 0 from actions[3], even if m_jumpRelease un `Update` method is equal to 1

**Comment by surfnerd** [comment]
Hi @rsta80,
If you look at the documentation, [`Input.GetButtonDown`](https://docs.unity3d.com/ScriptReference/Input.GetButtonDown.html) is only `true` during the frame where the button was first pressed.  Since ml-agents runs in the FixedUpdate loop, you may never get that event.  Instead, I recommend that you use [`Input.GetButton`](https://docs.unity3d.com/ScriptReference/Input.GetButton.html).  This method returns `true` if the button is currently being held down and `false` otherwise.  

I will close this for now.  In the future, please post questions like these to the [ML-Agents Forum](https://forum.unity.com/forums/ml-agents.453/)
Cheers,
Chris
