### ISSUE TITLE
How can I update ml-agents ? 

### ISSUE THREAD

**Issue by coreytaylor211** [Unity-Technologies/ml-agents#402]
Hi, I would like to konw how can i update the ml-agents scripts ? I can´t found any version history in my files ? 
an example : from version 0.2.1c to 0.2.1d

**Comment by vincentpierre** [comment]
Hi,
I think this is a git/github question. If you are using the git command line, you can pull the latest version of the branch with `git pull` or go to an other branch by doing `git checkout <branch>`.
If you just want to see how the files changed, you can download the repo at different versions by looking into the [releases](https://github.com/Unity-Technologies/ml-agents/releases) and download the appropriate `.zip` or `.tar.gz`. 
You can also look at the history of a file by going to the page of that file on git hub and click on history (on the top right corner of the page).
I hope this helps.

**Comment by coreytaylor211** [comment]
ok,` it works  with `git pull`
thanks
