### ISSUE TITLE
Reward 0

### ISSUE THREAD

**Issue by dkal3** [Unity-Technologies/ml-agents#4020]
Hi!!!
I try to train an agent to navigate from one initial point to another. Sometimes he reaches the goal, and sometimes he is trapped in a specific path far from the goal where the reward is 0 and he does not follow another path so as to take some reward.
The reward is 0 till the till of the training.

Isn't that a mistake?

**Comment by unityjeffrey** [comment]
hi @dkal3 - can you post your question on Forums and please include more information

https://forum.unity.com/forums/ml-agents.453/

**Comment by dkal3** [comment]
Hi!!! I had posted my question in the forum and  is ***HALF TRAINED NETWORK***.

**Comment by dkal3** [comment]
Αnd I came to the conclusion that this might be a bug, so I posted here.
