### ISSUE TITLE
Tutorial bug --> com.unity.ml-agents generates a not existent UI in 'UnityEditor.PackageManager'

### ISSUE THREAD

**Issue by Ordepedro** [Unity-Technologies/ml-agents#4022]
**Describe the bug**
I followed up the tutorial from the "Release 2" of ML-Agents and I can't start the "Getting Started Guide" because of an error that appears to me immediately after opening the project in Unity. 

**To Reproduce**
1. Open Unity Hub
2. Open the project in ml-agents/Project 
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/11221970/82875345-2fa76400-9f2f-11ea-9571-7ab043539475.png)

![image](https://user-images.githubusercontent.com/11221970/82875411-40f07080-9f2f-11ea-8c25-5af5024a74ce.png)

**Environment (please complete the following information):**
- Unity Version: Unity 2019.1.4f1
- OS + version: Windows 10
- _ML-Agents version_: Release 2
- _TensorFlow version_: 1.7.1
- _Environment_: 3DBall

I need to use this Unity version, and it is on the requirements: Install Unity (2018.4 or later)

**Comment by Ordepedro** [comment]
Hi @unityjeffrey ! Thank you for your help. 

I already did that but the same thing is happening: 

![image](https://user-images.githubusercontent.com/11221970/83023020-45e31c00-a024-11ea-9f4a-5057104ec004.png)
![image](https://user-images.githubusercontent.com/11221970/83023067-56939200-a024-11ea-97d1-9c94d587885f.png)
![image](https://user-images.githubusercontent.com/11221970/83023102-61e6bd80-a024-11ea-8931-ecf82ca2266b.png)

**Comment by unityjeffrey** [comment]
@Ordepedro are you using a clean project from the Unity hub?  I am not sure on your issue as it seems to be something with the package validation suite.

**Comment by surfnerd** [comment]
Hi @Ordepedro,
Is there a reason you are installing the package validation suite?  The documentation states that it is an internal tool and has no guaranteed support.

**Comment by Ordepedro** [comment]
Problem solved! I just uninstalled the package validation suite and it is running well! 
Thank you
