### ISSUE TITLE
Self-play does not resume correctly using --resume

### ISSUE THREAD

**Issue by fedetask** [Unity-Technologies/ml-agents#4029]
**Describe the bug**
When resuming a training that employes self-play, the training does not resume from the correct team.

**To Reproduce**
- Start a self-play training that has team 0 and team 1.
- Wait until team 0 finished the first training and the learning team is swapped to team 1
- Interrupt training with CTRL-C
- Run again the same `mlagents-learn` command using the `--resume` flag
The training now starts from team 0 again, instead of resuming from team 1 as it should. 

**Environment (please complete the following information):**
- Unity Version: Unity 2019.3.13f1]
- OS + version: Ubuntu 18.04
- _ML-Agents version_: 0.16.0
- _TensorFlow version_: 2.1.0
- _Environment_: Custom

**Note**
I haven't checked with one of the examples, and I'll do it as soon as possible. However, I feel this is not dependent on the environment, but rather on the training code.

**Comment by anupambhatnagar** [comment]
@ervteng do we store the active team when Ctrl-C is called? Should the user expect to resume training from team-0 or from the last active team?

**Comment by anupambhatnagar** [comment]
@fedetask if the training runs long enough after resuming there should be plenty of swaps between the teams. Would it really matter if the training does not resume from the team where it stopped.

**Comment by hvpeteet** [comment]
Closing as stale
