### ISSUE TITLE
 How to teach a walker to really walk?

### ISSUE THREAD

**Issue by Inza124** [Unity-Technologies/ml-agents#4046]
Hello, I have a problem with working on the walker environment. When I run the prepared (default) model, which I downloaded by cloning the repository. I see that it moves in a similar way to people. 
When I start learning with the ppo algorithm (all defaults, no code changes). He is still learning but not walking like a human. The learning process ends, and the learning was successful because there is no problem with getting through the route. But it doesn't "walk" anymore as in the demonstration model. 
Are any changes required to get the effect seen in the demonstration model?

Thank you in advance for all the tips

PS. Sorry for "bug" label, i can not choose 'help-wanted'

**Comment by anupambhatnagar** [comment]
@Inza124 the demo model is probably trained with a different set of parameters. I suggest trying `--num-envs=8` if your machine has the resources.
