### ISSUE TITLE
Errors on 3Dball Project

### ISSUE THREAD

**Issue by hecong97** [Unity-Technologies/ml-agents#4053]
**Describe the bug**
The 3Dball Project can't play in unity 2019.1.0a8
**To Reproduce**
1. drag the 3DBall Model located in Assets/ML-Agents/Examples/3DBall/TFModels into the Model property under Behavior Parameters (Script) component in the Agent GameObject Inspector window.
2. Click the Play button in the Unity Editor
3. See error

**Console logs / stack traces**
"Agent component was not found on this gameObject and is required.
UnityEngine.Debug:Assert(Boolean, String)"
"Couldn't connect to trainer on port 5004 using API version 1.0.0. Will perform inference instead.
UnityEngine.Debug:Log(Object)
Unity.MLAgents.Academy:InitializeEnvironment() (at C:/Users/Downloads/ml-agents-latest_release/com.unity.ml-agents/Runtime/Academy.cs:394)"

**Screenshots**
![IMG20200602_162056](https://user-images.githubusercontent.com/15817922/83497439-12553580-a4ed-11ea-8eb7-ed79c5b1428d.png)

**Environment (please complete the following information):**
- Unity Version: [e.g. Unity 2019.08a]
- OS + version: [e.g. Windows 10]
- _ML-Agents version_: (latest `develop` branch from source)

**Comment by StefanoCecere** [comment]
why should you use 2019.1.0a8 ? can't you at least try with a stable release like Unity 2019.1.14 ?

**Comment by andrewcoh** [comment]
From the stack trace, it seems like the `Agent script` is missing from your agent. In 3DBall, this is called `Ball 3D Agent`. Is this true?

**Comment by hecong97** [comment]
The problem is solved with the Unity 2018.4.17.   I am new to Unity and don't realize the incompatible between versions
