### ISSUE TITLE
The error when open the MLagents with Unity2019

### ISSUE THREAD

**Issue by hecong97** [Unity-Technologies/ml-agents#4057]
**Describe the bug**
The Unity2019pro can't open the project

**To Reproduce**
1. download the "ml-agents-latest_release"
2. Open with Unity 2019
3.  See error"Library\PackageCache\com.unity.barracuda@0.7.1-preview\Barracuda\Runtime\Plugins\Burst\BurstBLAS.cs(8,12): error CS0246: The type or namespace name 'AlwaysLinkAssemblyAttribute' could not be found"

**Console logs / stack traces**
"Library\PackageCache\com.unity.barracuda@0.7.1-preview\Barracuda\Runtime\Plugins\Burst\BurstBLAS.cs(8,12): error CS0246: The type or namespace name 'AlwaysLinkAssemblyAttribute' could not be found (are you missing a using directive or an assembly reference?)"
"Library\PackageCache\com.unity.package-validation-suite@0.7.15-preview\Editor\ValidationSuite\ValidationTests\UpdateConfigurationValidation.cs(53,68): error CS0117: 'CompilationPipeline' does not contain a definition for 'GetPrecompiledAssemblyPaths'"

**Screenshots**
![error](https://user-images.githubusercontent.com/15817922/83586638-92c47680-a57f-11ea-9001-b2312ed3315e.png)

**Environment (please complete the following information):**
- Unity Version: [Unity 2019.1.0a8]
- OS + version: [Windows 10]
- _ML-Agents version_: ( latest `develop` branch from source)

**Comment by hecong97** [comment]
I changed to the Unity 2018.4.17f and the problem is solved

**Comment by andrewcoh** [comment]
Currently, 2018.4 is the official version supported by ML-Agents.  Additionally, I see you're using `develop`. We have changed our gitflow and `develop` is no longer maintained. Our leading edge is `master`. We encourage you to use our official releases (or `master` to try new features before they are released). Closing this for now.

**Comment by andrewcoh** [comment]
For bookkeeping, would you mind letting us know which project you were trying to load?  Are you trying to load DevProject?

**Comment by hecong97** [comment]
No,I just try to open the "Project" Folder with Unity as the Guide describe.
