### ISSUE TITLE
Building  TensorFlow for mobile

### ISSUE THREAD

**Issue by happymarco** [Unity-Technologies/ml-agents#406]
I'd like to add some ops that appear missing on the TensorFlow build that came with `ML-Agents` (for instance, `NonMaxSuppressionV2` and other ops) so it would be amazing if you can share the instructions of how you compiled TensorFlow for iOS and Android to make it work with TensorFlowCSharp.

**Comment by marcomarchesi** [comment]
I was able to spend some time more and sort it out. The main thing to include is of course the C API (for the TensorFlowCSharp binding), as since TensorFlow 0.10.0 was removed on iOS (but reintroduced later on Android).

**Comment by happymarco** [comment]
I was able to spend some time more and sort it out. The main thing to include is of course the C API (for the TensorFlowCSharp binding), as since TensorFlow 0.10.0 was removed on iOS (but reintroduced later on Android).
