### ISSUE TITLE
Update steps out of sync when resuming a sac training.

### ISSUE THREAD

**Issue by dlindmark** [Unity-Technologies/ml-agents#4062]
**Describe the bug**
When you resume a sac training `SACTrainer.step` is initialized to the loaded policy step, `self.step = policy.get_current_step()`. But the `SACTrainer.update_steps` is initialized to `buffer_init_steps`. This means that the loop in `SACTrainer._update_sac_policy()` will run until catching up. As I understand that means that we update the policy using the loaded experience buffer until we catch up with `SACTrainer.step`. 

And by then the environment have stepped many new steps. Meaning that the next time we enter this function we are still very far behind.

We discovered this when our unity application started to freeze during training, after resuming an old training. It seems like that when the environment gets to far ahead of updating the policy it waits for ml-agents to keep up. And then the application starts again. 

I guess the same thing could happen if your environment is much faster then ml-agents.

I think that if you add

`self.update_steps = policy.get_current_step()`

in `SACTrainer.add_policy()` the problem is fixed.

**To Reproduce**
1. Resume old sac training session with the `--debug` flag.
2. See that the `logger.debug("Updating SAC policy at step {}".format(self.step))` starts writing without pause for a very long time. Without  `self.step` ever changing.

**Environment (please complete the following information):**
- Unity Version: Unity 2019.3.7.f1
- OS + version: Windows 10
- _ML-Agents version_: Version: 0.16.0
- _TensorFlow version_: Version: 1.15.0
- _Environment_: custom environment.

**Comment by ervteng** [comment]
Hi @dlindmark, you're absolutely right, this is a known bug. It has been fixed here: https://github.com/Unity-Technologies/ml-agents/pull/4038 and will be fixed in the next release. 
Your fix is also correct. Technically you should add `self.update_steps = policy.get_current_step()/self.steps_per_update()` and do the same for `self.reward_signal_update_steps`.

**Comment by dlindmark** [comment]
Check. We fix that locally then and wait for the next release. 

Thank you!
