### ISSUE TITLE
'UnityEnvironment' object has no attribute 'get_agent_groups'

### ISSUE THREAD

**Issue by rajanlagah** [Unity-Technologies/ml-agents#4079]
**Describe the bug**
```

from mlagents_envs.environment import UnityEnvironment
import mlagents_envs
env = UnityEnvironment(file_name="v1-ball-cube-game.x86_64", base_port=5004, seed=1, side_channels=[])
# env = UnityEnvironment(file_name=None, base_port=5004, seed=1,worker_id=0, side_channels=[])

print(mlagents_envs.__version__)  # 0.16.1
print(env.reset()) # None
print(env) # <mlagents_envs.environment.UnityEnvironment object at 0x7f3ed001c278>
print(str(env.get_agent_groups())) # error

```
The unity game console is opening and `env.reset()` is returning None (which is good sign) but it is saying `AttributeError: 'UnityEnvironment' object has no attribute 'get_agent_groups'`

**To Reproduce**
1. Followed [https://github.com/Unity-Technologies/ml-agents/blob/release-0.15.0/docs/Learning-Environment-Create-New.md](url)
2. Able to train the game with .yaml
3. Followed this to connect to python api [https://github.com/Unity-Technologies/ml-agents/blob/release-0.15.0/docs/Python-API.md](url)
4. Installation followed from here [https://github.com/Unity-Technologies/ml-agents/blob/release-0.15.0/docs/Installation.md](url)

**Console logs / stack traces**
full output of the code 
```
0.16.1
None
<mlagents_envs.environment.UnityEnvironment object at 0x7f3ed001c278>
Traceback (most recent call last):
  File "index.py", line 12, in <module>
    print(str(env.get_agent_groups()))
AttributeError: 'UnityEnvironment' object has no attribute 'get_agent_groups'
```

**Environment (please complete the following information):**
- Unity Version: Version 2019.3.15f1 (59ff3e03856d) Personal
- OS + version: ubuntu 18.04
- _ML-Agents version_: release-0.15.0
- _TensorFlow version_: Version: 1.14.0
- _Environment_: as mentioned the i follow the docs to create my own sphere - cube game

I also have asked the related issue on SO [https://stackoverflow.com/questions/62208330/unityenvironment-object-has-no-attribute-get-agent-groups-mlagents-envs-0](url)

**Comment by andrewcoh** [comment]
It looks like you're using version 0.16 of ml-agents-envs but reading the docs of 0.15. The `get_agent_group` function was removed.

**Comment by rajanlagah** [comment]
O yes that was the problem.
