### ISSUE TITLE
3DBall agents cheat physics because no kinematic Rigidbody

### ISSUE THREAD

**Issue by WazWaz** [Unity-Technologies/ml-agents#4088]
**Describe the bug**
The 3DBall example moves a collider that doesn't have a kinematic rigidbody. Apparently this allows some strange physics glitch cheat, because after a day's training, the agents were clearly getting fake results. You really need to add a Rigidbody to the 3DBall/Agent and set it as Kinematic to get more reliable physics.

**To Reproduce**
To make the problem "harder" in a different way, I changed the ball into a long capsule and added a grippy physic material, so they had to learn to balance a stick on the top of their heads. After 24 hours of learning, I noticed that quite often the capsule was embedded well inside their head.

I tried to reproduce this bug with the plain ball, but after a day they hadn't discovered the physics glitch. It should be possible for them to find it eventually. I guess that's a problem with this kind of software.

**Console logs / stack traces**
Can provide code and .nn, but the fix is simple - add Rigidbody and set it isKinematic. You may also want to set a Physic Material on the objects, but that's not related to this bug.

**Screenshots**
![2020-06-06](https://user-images.githubusercontent.com/7268071/83931772-cc94b780-a7e1-11ea-9a7f-2419c51f5e8b.png)

**Environment (please complete the following information):**
- Unity Version: 2019.3.4f1
- OS + version: Windows 10
- _ML-Agents version_: release_2_verified
- _TensorFlow version_: 2.2.0
- _Environment_: Ball3D modified

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by andrewcoh** [comment]
Hi @WazWaz 

Thank you for pointing this out. This is something of which we are aware. It's a holdover/artifact from earlier versions of ML-Agents. For the problem as it is, it doesn't cause an issue because things move slowly enough. However, as you point out, it doesn't support extensibility to more complex variants. 

I've logged this internally as issue #1060 and we will discuss a fix.  Thank you again!
