### ISSUE TITLE
sample training config files(any.yaml) cannot be loaded.

### ISSUE THREAD

**Issue by sobassy** [Unity-Technologies/ml-agents#4089]
I tried Sample program(3D Ball) along the getting start guide.
But an error occurred...

```
Traceback (most recent call last):
File "c:\users\sobassy\anaconda3\lib\site-packages\mlagents\trainers\trainer_controller.py", line 175, in _create_trainer_and_manager
trainer = self.trainers[brain_name]
KeyError: '3DBall'
```

So, I tried to remove `behavior: ` row from 3DBall.yaml, training was completed.

Why this error occurred?
I use these version.

- python 3.6.3
- tensorflow == 2.2.0
- mlagents == 0.16.1
- Unity 2018.4.11f1

**Comment by andrewcoh** [comment]
Hi @sobassy 

I believe you are using a .yaml from our `master` branch and not from the release branch.  If this is intended, can you please share the .yaml that you are using?
