### ISSUE TITLE
I can't reproduce your problem. I think your setting is not correct. Does your Unity stays open after running  ``env = UnityEnvironment(file_name=env_name)`` ?

### ISSUE THREAD

**Issue by wang88256187** [Unity-Technologies/ml-agents#4091]
who successfully build the unity default environments to .exe and run it via the python API? Can you share your concrete version of the Unity,  and mlagents python package? Thanks!

**Comment by wang88256187** [comment]
no

**Comment by andrewcoh** [comment]
Hi @wang88256187 

Please follow our installation instructions here: https://github.com/Unity-Technologies/ml-agents/blob/release_2/docs/Installation.md and instructions for running with an executable here: https://github.com/Unity-Technologies/ml-agents/blob/release_2/docs/Learning-Environment-Executable.md.

If you encounter any specific problems, feel free to raise them as issues.  For more general questions, please use the forums https://forum.unity.com/forums/ml-agents.453/

**Comment by wang88256187** [comment]
I want to create a unity environment and run my own RL algorithm, but it never succeeds in win10. whichever version of mlagents doc i followed , there always  show :
 "The Unity environment took too long to respond. Make sure that :\n"
unityagents.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Academy and the External Brain(s) are attached to objects in the Scene
	 The environment and the Python interface have compatible versions.
