### ISSUE TITLE
Is there a 2D environment or all of the example environments are 3D

### ISSUE THREAD

**Issue by Hsgngr** [Unity-Technologies/ml-agents#4103]
Many game developers use unity as 2D and they would like to add ML-agents to their projects however all the example environments are in 3D. 

Moreover there are some cases that one more dimension doesnt add anything benefical but complexity. Is it possible to add a really basic 2D environment like [this](https://cs.stanford.edu/people/karpathy/reinforcejs/waterworld.html). Is it possible to easily create something like that ?

**Comment by xiaomaogy** [comment]
Yes it is really easy to add that. Our GridWorld example environment is sort of our 2D Environment, you maybe you can take a look at that one. @Hsgngr

**Comment by DVonk** [comment]
I agree that it would be a good idea to include at least one simple 2D environment. Maybe something like in the link, or an agent that avoids obstacles. Or maybe Pong - I just implemented that and it worked quite well.

**Comment by Hsgngr** [comment]
Thank you can I use GridWorld as a continues environment, it looks discrete ? @xiaomaogy

**Comment by xiaomaogy** [comment]
Yes @Hsgngr
