### ISSUE TITLE
'mlagents-learn' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by MrStashley** [Unity-Technologies/ml-agents#4108]
I have created a ml environment on windows and I am trying to train my agent but I get 
`'mlagents-learn' is not recognized as an internal or external command,
operable program or batch file.` 
when I try to run mlagents-learn with my config file and a run id specified as parameters. I added the path to ml-agents/trainers/learn.py into my PATH environment variable and I followed the instructions for setting up a virtual environment but I get the same results. When I run learn.py from within the trainers directory with command
`learn.py config/Platformer.yaml --run-id=Platformer` 
I get a console window but it closes very quickly and it shows an error but it closes before I can read it. I'm sure I'm doing something simple wrong but I can't figure it out. I'm using 64 bit windows.
Can anyone help me? Thanks!

**Comment by xiaomaogy** [comment]
Hi @MrStashley, for installation issues like this, please open a forum post here: https://forum.unity.com/forums/ml-agents.453/
