### ISSUE TITLE
TrainerConfigError for invalid config file syntax even when using example config files

### ISSUE THREAD

**Issue by MrStashley** [Unity-Technologies/ml-agents#4110]
**Describe the bug**
when running the mlagents-train command with a config file the command properly reads the file but it gives the following error: 
(On my config file "Platformer.yaml")
`mlagents.trainers.exception.TrainerConfigError: The option Platformer was specified in your YAML file, but is invalid.`
The error persists if I copy the example BehaviorPPO configuration from the docs into my file and if I use training_config.yaml, the simplest of the example config files. In each case, the error is thrown on the first line of the config file. Removing the first line results in an error on the second line. I got the error message that "trainer: ppo" was invalid after removing the first line of my config file, even though I am fairly sure that that is a correct line. Is it possible that the config file syntax was changed and the docs were not updated?

**To Reproduce**
go to root of cloned github directory 
execute mlagents-learn config\trainer_config.yaml --run-id=Platformer

**Environment (please complete the following information):**
- Unity Version: 2019.3.15f1
- OS + version: Windows 10 64 bit (Python 64 bit as well, I checked)
- _ML-Agents version_: release 2 branch
- _TensorFlow version_: 2.2.0
 _Environment_: ? I tried it in a python3 venv and out of one and I got the same error

**Comment by federicocasares** [comment]
I am getting the same error while following the Getting Started guide in the repository.

Unity version 2019.3.13f1
Windows 10 64-bit
Python 3.8.3 64-bit
MLAgents release_2 branch

**Comment by DVonk** [comment]
The documentation seems to be outdated in parts - especially the example environments. It seems like you need to have a separate config for every environment now, and it has to say 'behaviors:' at the top. See here:
https://github.com/Unity-Technologies/ml-agents/blob/master/config/ppo/3DBall.yaml

**Comment by xiaomaogy** [comment]
@DVonk Yes the doc seems outdated, thanks for pointing him in the right direction.

**Comment by MrStashley** [comment]
that fixed the issue for me :) thank you
