### ISSUE TITLE
Facing Issue in Agent.cs

### ISSUE THREAD

**Issue by MWaqas1512** [Unity-Technologies/ml-agents#4123]
**Describe the bug**

**To Reproduce**

**Console logs / stack traces**
Please wrap in [triple backticks (```)](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make it easier to read.

**Screenshots**

**Environment (please complete the following information):**
- Unity Version: [e.g. Unity 2020.1f1]
- OS + version: [e.g. Windows 10]
- _ML-Agents version_: (e.g. ML-Agents v0.8, or latest `develop` branch from source)
- _TensorFlow version_: (you can run `pip3 show tensorflow` to get this)
- _Environment_: (which example environment you used to reproduce the error)

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by MWaqas1512** [comment]
Facing Issue in agent.cs file
NullReferenceException: Object reference not set to an instance of an object
MLAgents.Agent.OnEnable () (at Assets/ML-Agents/Scripts/Agent.cs:255)

**Comment by xiaomaogy** [comment]
Hi @MWaqas1512 please open up a new issue with filled template for the bug report, so that we can help accordingly.
