### ISSUE TITLE
Error: mlagents_envs.registry

### ISSUE THREAD

**Issue by yoheigon** [Unity-Technologies/ml-agents#4141]
**Describe the bug**
UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Agents are linked to the appropriate Brains
	 The environment and the Python interface have compatible versions.

**To Reproduce**
1. install mlagents-envs-0.17.0
2. execute this
from mlagents_envs.registry import default_registry
env = default_registry["Basic"].make()

**Console logs / stack traces**
UnityTimeOutException                     Traceback (most recent call last)
<ipython-input-11-4939096c6e21> in <module>()
----> 1 env = default_registry["Hallway"].make()

~/anaconda3/envs/python3/lib/python3.6/site-packages/mlagents_envs/registry/remote_registry_entry.py in make(self, **kwargs)
     69             args += self._add_args
     70         kwargs["additional_args"] = args
---> 71         return UnityEnvironment(file_name=path, **kwargs)

~/anaconda3/envs/python3/lib/python3.6/site-packages/mlagents_envs/environment.py in __init__(self, file_name, worker_id, base_port, seed, no_graphics, timeout_wait, additional_args, side_channels, log_folder)
    209         )
    210         try:
--> 211             aca_output = self._send_academy_parameters(rl_init_parameters_in)
    212             aca_params = aca_output.rl_initialization_output
    213         except UnityTimeOutException:

~/anaconda3/envs/python3/lib/python3.6/site-packages/mlagents_envs/environment.py in _send_academy_parameters(self, init_parameters)
    454         inputs = UnityInputProto()
    455         inputs.rl_initialization_input.CopyFrom(init_parameters)
--> 456         return self._communicator.initialize(inputs)
    457 
    458     @staticmethod

~/anaconda3/envs/python3/lib/python3.6/site-packages/mlagents_envs/rpc_communicator.py in initialize(self, inputs)
    102 
    103     def initialize(self, inputs: UnityInputProto) -> UnityOutputProto:
--> 104         self.poll_for_timeout()
    105         aca_param = self.unity_to_external.parent_conn.recv().unity_output
    106         message = UnityMessageProto()

~/anaconda3/envs/python3/lib/python3.6/site-packages/mlagents_envs/rpc_communicator.py in poll_for_timeout(self)
     95         if not self.unity_to_external.parent_conn.poll(self.timeout_wait):
     96             raise UnityTimeOutException(
---> 97                 "The Unity environment took too long to respond. Make sure that :\n"
     98                 "\t The environment does not need user interaction to launch\n"
     99                 "\t The Agents are linked to the appropriate Brains\n"

UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Agents are linked to the appropriate Brains
	 The environment and the Python interface have compatible versions.

**Environment (please complete the following information):**
- _TensorFlow version_: 1.15.2
mlagents-envs-0.17.0

**Comment by chriselion** [comment]
Can you try some of the suggestions here: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/FAQ.md#environment-connection-timeout ?

**Comment by yoheigon** [comment]
Thank you for your suggestion.
- Cause: There may be no agent in the scene 
This env is provided by default_registry so I assume there is an agent in the scene.

- Cause: On OSX, the firewall may be preventing communication with the environment. Solution: Add the built environment binary to the list of exceptions on the firewall by following instructions.
I have checked there is no firewall.

- Cause: An error happened in the Unity Environment preventing communication. Solution: Look into the log files generated by the Unity Environment to figure what error happened.
This was the log 
'''
Mono path[0] = '/tmp/ml-agents-binaries/binaries/Basic-b1b94a0ae13eef9d91f9d8db1e5770c5/Startup/Startup_Data/Managed'
Mono config path = '/tmp/ml-agents-binaries/binaries/Basic-b1b94a0ae13eef9d91f9d8db1e5770c5/Startup/Startup_Data/MonoBleedingEdge/etc'
PlayerConnection initialized from /tmp/ml-agents-binaries/binaries/Basic-b1b94a0ae13eef9d91f9d8db1e5770c5/Startup/Startup_Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55404
Multi-casting "[IP] 172.31.17.102 [Port] 55404 [Flags] 2 [Guid] 946481988 [EditorId] 429131514 [Version] 1048832 [Id] LinuxPlayer(172.31.17.102) [Debug] 0 [PackageName] LinuxPlayer [ProjectName] UnityEnvironment" to [225.0.0.222:54997]...
Started listening to [0.0.0.0:55404]
Preloaded 'libgrpc_csharp_ext.x64.so'
Unable to preload the following plugins:
	lib_burst_generated.so
PlayerConnection already initialized - listening to [0.0.0.0:55404]
Unable to load player prefs
Desktop is 0 x 0 @ 0 Hz
Invalid initial resolution 80 x 80 - forcing to 100 x 100
'''

- Cause: You have assigned HTTP_PROXY and HTTPS_PROXY values in your environment variables. Solution: Remove these values and try again.
I have checked the environment variables but they are not set.

**Comment by chriselion** [comment]
A few other questions:
* Are you on Mac or Linux?
* Can you try passing `no_graphics=True` to the `make()` method?

**Comment by yoheigon** [comment]
no_graphics=True worked on my linux environment.
Thank you!

**Comment by chriselion** [comment]
Glad that worked; I added a note to the FAQ in https://github.com/Unity-Technologies/ml-agents/pull/4159
