### ISSUE TITLE
UnityGymException: There can only be one Agent in the environment

### ISSUE THREAD

**Issue by redzhepdx** [Unity-Technologies/ml-agents#4142]
I have been trying to use new ml-agents and gym-unity wrapper but I couldn't make them work because of the specified error. I built Crawler Environment in UnityEditor and tried to run following python code : 

```
from gym_unity.envs import UnityToGymWrapper
from mlagents_envs.environment import UnityEnvironment
# Init Env
unity_env = UnityEnvironment(file_name="CrawlerCustom_June20/CrawlerCustomBuild.x86_64") env = UnityToGymWrapper(unity_env=unity_env,
                            flatten_branched=True,
                            uint8_visual=True,
                            allow_multiple_visual_obs=True)

env.reset()
print(env.action_space)
```

I don't want to remove 7 agents and re-built it. I also checked other similar problems but all the given answers were for older versions of unity-gym and ml-agents. I would like to learn if there is a way to do it in the current versions of those libraries.

_Specs : 
OS: Ubuntu 18.04
Unity Version : 2019.3.11f1
mlagents==0.15.0
mlagents-envs==0.16.1
gym-unity==0.16.1_

**Comment by chriselion** [comment]
Sorry, there aren't currently any workarounds for this.

**Comment by ProxyCausal** [comment]
I think someone has created a custom wrapper for this https://github.com/Procuste34/Unity-MLAgents/blob/master/gym_wrapper/gym_wrapper.py.

I'd like to see official support for it in the future though.

> I don't want to remove 7 agents and re-built it.
you might want to procedurally generate with script at runtime
