### ISSUE TITLE
DecisionRequester calls to RequestAction are out of sync after EndEpisode

### ISSUE THREAD

**Issue by mbaske** [Unity-Technologies/ml-agents#4156]
**Describe the bug**
The DecisionRequester component calls RequestDecision when academyStepCount % DecisionPeriod == 0. If an eposide is terminated during another step, the offset gets carried over to the next CollectObservations/OnActionReceived cycle.

This might be expected behaviour and not be considered a bug. But it threw me off, because I used to rely on Agent.StepCount % DecisionPeriod returning the current step in a decision cycle. 

**To Reproduce**
Add a custom stepCount field that gets nulled in CollectObservations and incremented in OnActionReceived.
Compare stepCount against Agent.StepCount with DecisionPeriod = 5

**Console logs / stack traces**
OnEpisodeBegin
CollectObservations
OnActionReceived - stepCount: 1, Agent.StepCount: 1 ( % 5 = 1 )
OnActionReceived - stepCount: 2, Agent.StepCount: 2 ( % 5 = 2 )
OnActionReceived - stepCount: 3, Agent.StepCount: 3 ( % 5 = 3 )
OnActionReceived - stepCount: 4, Agent.StepCount: 4 ( % 5 = 4 )
OnActionReceived - stepCount: 5, Agent.StepCount: 5 ( % 5 = 0 )
CollectObservations
OnActionReceived - stepCount: 1, Agent.StepCount: 6 ( % 5 = 1 )
OnActionReceived - stepCount: 2, Agent.StepCount: 7 ( % 5 = 2 )
OnActionReceived - stepCount: 3, Agent.StepCount: 8 ( % 5 = 3 )
OnActionReceived - stepCount: 4, Agent.StepCount: 9 ( % 5 = 4 )
OnActionReceived - stepCount: 5, Agent.StepCount: 10 ( % 5 = 0 )
CollectObservations
OnActionReceived - stepCount: 1, Agent.StepCount: 11 ( % 5 = 1 )
OnActionReceived - stepCount: 2, Agent.StepCount: 12 ( % 5 = 2 )
OnActionReceived - stepCount: 3, Agent.StepCount: 13 ( % 5 = 3 )
OnActionReceived - stepCount: 4, Agent.StepCount: 14 ( % 5 = 4 )
OnActionReceived - stepCount: 5, Agent.StepCount: 15 ( % 5 = 0 )
CollectObservations
OnActionReceived - stepCount: 1, Agent.StepCount: 16 ( % 5 = 1 )
EndEpisode
CollectObservations

OnEpisodeBegin
OnActionReceived - stepCount: 1, Agent.StepCount: 1 ( % 5 = 1 )
OnActionReceived - stepCount: 2, Agent.StepCount: 2 ( % 5 = 2 )
OnActionReceived - stepCount: 3, Agent.StepCount: 3 ( % 5 = 3 )
OnActionReceived - stepCount: 4, Agent.StepCount: 4 ( % 5 = 4 )
CollectObservations
OnActionReceived - stepCount: 1, Agent.StepCount: 5 ( % 5 = 0 )
OnActionReceived - stepCount: 2, Agent.StepCount: 6 ( % 5 = 1 )
OnActionReceived - stepCount: 3, Agent.StepCount: 7 ( % 5 = 2 )
OnActionReceived - stepCount: 4, Agent.StepCount: 8 ( % 5 = 3 )
OnActionReceived - stepCount: 5, Agent.StepCount: 9 ( % 5 = 4 )
CollectObservations
OnActionReceived - stepCount: 1, Agent.StepCount: 10 ( % 5 = 0 )
OnActionReceived - stepCount: 2, Agent.StepCount: 11 ( % 5 = 1 )
OnActionReceived - stepCount: 3, Agent.StepCount: 12 ( % 5 = 2 )
OnActionReceived - stepCount: 4, Agent.StepCount: 13 ( % 5 = 3 )
OnActionReceived - stepCount: 5, Agent.StepCount: 14 ( % 5 = 4 )
CollectObservations
OnActionReceived - stepCount: 1, Agent.StepCount: 15 ( % 5 = 0 )
OnActionReceived - stepCount: 2, Agent.StepCount: 16 ( % 5 = 1 )
EndEpisode
CollectObservations

OnEpisodeBegin
OnActionReceived - stepCount: 1, Agent.StepCount: 1 ( % 5 = 1 )
OnActionReceived - stepCount: 2, Agent.StepCount: 2 ( % 5 = 2 )
OnActionReceived - stepCount: 3, Agent.StepCount: 3 ( % 5 = 3 )
CollectObservations
OnActionReceived - stepCount: 1, Agent.StepCount: 4 ( % 5 = 4 )
OnActionReceived - stepCount: 2, Agent.StepCount: 5 ( % 5 = 0 )
OnActionReceived - stepCount: 3, Agent.StepCount: 6 ( % 5 = 1 )
OnActionReceived - stepCount: 4, Agent.StepCount: 7 ( % 5 = 2 )
OnActionReceived - stepCount: 5, Agent.StepCount: 8 ( % 5 = 3 )
CollectObservations
OnActionReceived - stepCount: 1, Agent.StepCount: 9 ( % 5 = 4 )
OnActionReceived - stepCount: 2, Agent.StepCount: 10 ( % 5 = 0 )
OnActionReceived - stepCount: 3, Agent.StepCount: 11 ( % 5 = 1 )
OnActionReceived - stepCount: 4, Agent.StepCount: 12 ( % 5 = 2 )
OnActionReceived - stepCount: 5, Agent.StepCount: 13 ( % 5 = 3 )
CollectObservations
OnActionReceived - stepCount: 1, Agent.StepCount: 14 ( % 5 = 4 )
OnActionReceived - stepCount: 2, Agent.StepCount: 15 ( % 5 = 0 )
OnActionReceived - stepCount: 3, Agent.StepCount: 16 ( % 5 = 1 )
EndEpisode
CollectObservations

OnEpisodeBegin
OnActionReceived - stepCount: 1, Agent.StepCount: 1 ( % 5 = 1 )
OnActionReceived - stepCount: 2, Agent.StepCount: 2 ( % 5 = 2 )
CollectObservations
OnActionReceived - stepCount: 1, Agent.StepCount: 3 ( % 5 = 3 )
OnActionReceived - stepCount: 2, Agent.StepCount: 4 ( % 5 = 4 )
OnActionReceived - stepCount: 3, Agent.StepCount: 5 ( % 5 = 0 )
OnActionReceived - stepCount: 4, Agent.StepCount: 6 ( % 5 = 1 )
OnActionReceived - stepCount: 5, Agent.StepCount: 7 ( % 5 = 2 )
CollectObservations
OnActionReceived - stepCount: 1, Agent.StepCount: 8 ( % 5 = 3 )
OnActionReceived - stepCount: 2, Agent.StepCount: 9 ( % 5 = 4 )
OnActionReceived - stepCount: 3, Agent.StepCount: 10 ( % 5 = 0 )
OnActionReceived - stepCount: 4, Agent.StepCount: 11 ( % 5 = 1 )
OnActionReceived - stepCount: 5, Agent.StepCount: 12 ( % 5 = 2 )
CollectObservations
OnActionReceived - stepCount: 1, Agent.StepCount: 13 ( % 5 = 3 )
OnActionReceived - stepCount: 2, Agent.StepCount: 14 ( % 5 = 4 )
OnActionReceived - stepCount: 3, Agent.StepCount: 15 ( % 5 = 0 )
OnActionReceived - stepCount: 4, Agent.StepCount: 16 ( % 5 = 1 )
EndEpisode

**Comment by ervteng** [comment]
Hi @mbaske, that is intended behavior - it's for improved efficiency in communication and inference, as it ensures all agents in a multi-agent scene can RequestDecision at the same time, even if they EndEpisode at different times. Otherwise, the agents would eventually not be in sync anymore.
