### ISSUE TITLE
Roller Ball Decision Requester issue and policy update

### ISSUE THREAD

**Issue by Jean-Diddy** [Unity-Technologies/ml-agents#4165]
Hello,
I have few questions about the decision requester. When I increase the period of decision in the RollerBall tutorial, it speeds up the game. Why is it happening ?
I also wanted to know if a policy adjustment for a PPO trainer is what we call a decision taken by the agent. 
If we set the decision requester period to 1, a decision is going to be taken at each steps ? Does it mean the PPO policy is going to be updated at each step ? 
Or, is the PPO policy updated only at the end of an episode ? 
Thank you for your help !

**Comment by ervteng** [comment]
Hi @Jean-Diddy, happy to answer your questions but since this isn't a bug report, would you mind posting it on the ML-Agents Forums? https://forum.unity.com/forums/ml-agents.453/ 

I can help you there. Thanks!

**Comment by hvpeteet** [comment]
Closing since I assume this was moved to the forums before it was assigned to me.
