### ISSUE TITLE
Config YAML Cannot be parsed at all.

### ISSUE THREAD

**Issue by alchemistake** [Unity-Technologies/ml-agents#4173]
**Describe the bug**
I just copy and paste a known, working, example config yaml and change behavior name to match behavior name in the Agent. Whenever I try to start a training with that It gives the "behavior was specified in your YAML file, but it is invalid." error.

**To Reproduce**
1. Copy Basic.yaml
2. Change the name of behavior
3. Try to train.

**Console logs / stack traces**
I cannot copy at this moment.

**Screenshots**
![image](https://user-images.githubusercontent.com/9083268/86053332-a2d55600-ba58-11ea-8150-bd3427f3aa06.png)

**Environment (please complete the following information):**
- Unity Version: 2018.4
- OS + version: Windows 10
- _ML-Agents version_: Release 3
- _TensorFlow version_: 2.2.0
- _Environment_: Custom Env

**Comment by alchemistake** [comment]
I created the yaml file using another application and it is working.
The first non-working yaml is created on "Rider"
I think this is a file encoding issue.

**Comment by ervteng** [comment]
It does seem like a file encoding issue given the funny characters printed with "behaviors" in the terminal. Try saving as `UTF-8` in your editor to get it to load properly.
