### ISSUE TITLE
Please make DecisionRequester extendable

### ISSUE THREAD

**Issue by mbaske** [Unity-Technologies/ml-agents#4180]
**Is your feature request related to a problem? Please describe.**
I've come across a few use-cases where I had to implement a custom DecisionRequester. Mostly though, I just needed to add some code to the MakeRequests method.

**Describe the solution you'd like**
Would be great if MakeRequests were protected virtual.

**Comment by chriselion** [comment]
Hi @mbaske,
Sorry this has been sitting around for a while. I'm looking at adding something for this but had a question about the proposed solution - do you actually need MakeRequests virtual, or would something like this be better?
```csharp
        void MakeRequests(int academyStepCount)
        {
            if (ShouldRequestDecision(academyStepCount))
            {
                m_Agent?.RequestDecision();
            }
            if (ShouldRequestAction(academyStepCount))
            {
                m_Agent?.RequestAction();
            }
        }

        protected virtual bool ShouldRequestDecision(int academyStepCount)
        {
            return academyStepCount % DecisionPeriod == 0;
        }

        protected virtual bool ShouldRequestAction(int academyStepCount)
        {
            return TakeActionsBetweenDecisions;
        }
```

**Comment by mbaske** [comment]
Hi @chriselion - This looks like a good solution. In cases when I write my own decision requester, it's mostly because I need to switch it on and off easily.

**Comment by chriselion** [comment]
@mbaske - cool, let me know if you have any feedback on the PR: https://github.com/Unity-Technologies/ml-agents/pull/5223

I changed things slightly to take a context struct instead, so that we can add information if needed in the future without changing the signature.
