### ISSUE TITLE
How to convert barracuda file to a onnx file

### ISSUE THREAD

**Issue by vra** [Unity-Technologies/ml-agents#4184]
**Is your feature request related to a problem? Please describe.**
As now I have a barracuda model downloaded from Internet. I wonder how can I convert it to onnx (or pytorch or tensorflow format ) to further use.

**Comment by Shubhamai** [comment]
Same issue

**Comment by Shubhamai** [comment]
> Same issue

But solved 🙂

**Comment by vra** [comment]
> > Same issue
> 
> But solved 🙂

Hi @Shubhamai , Could you please tell me how you solve this problem? Thanks in advance

**Comment by Shubhamai** [comment]
@vra For that, you need to run `pip install tf2onnx` and after installing that, whenever you complete training the Unity ML Agents, the `.onnx` file will be saved along with `.nn`. 

Also, i am having a bit issue currently, that i want to test trained models in unity into real world hardware, the main issue i am having is that how can i input the observations in `frozen_graph_def.pb` or any other output file and getting the actions back, is this possible ? You can get more info about this [here](https://github.com/Unity-Technologies/ml-agents/issues/4215) . Thanks a lot 🙂

**Comment by chriselion** [comment]
There is no support for converting `.nn` files to any other format. As @Shubhamai mentioned, if `tf2onnx` is installed, training will also produce an `.onnx` file and this will be importable into the editor.
