### ISSUE TITLE
ML agents in Real World

### ISSUE THREAD

**Issue by Shubhamai** [Unity-Technologies/ml-agents#4195]
I want to train a simple model and inference it in real-world environments & hardware like the raspberry pi.

Does unity ML-Agents can be used in a real-world environment? I think it can. But when I tried to do so, it is becoming much harder and harder to implement it in real-world, the main issue I am getting currently is that ML-Agents output model in `.nn`, `.oonx` and in `.pb`. I use `.pb` in that case but i a getting problem in inputting observations and getting the actions. 

It would be helpful if anyone can just show a method to make an inference for maybe `3D ball` environment `.pb` files and how to make inference in that using TensorFlow 2.0

**Comment by nullbyte91** [comment]
@Shubhamai Did you figure it out the deployment flow from the trained model?

**Comment by Shubhamai** [comment]
Nope, But I think I would try again soon because ML-Agents now supports PyTorch.

**Comment by chriselion** [comment]
Sorry this never got answered before. Using torch means that all models are output in .onnx format. You're welcome to try it, but we don't provide and support for doing inference outside of the Unity engine.

**Comment by Shubhamai** [comment]
awww :( . The thing is I think if ML-Agents can support the inference outside unity engine. This will make implementing reinforcement learning on real-world things ( robotics ) so so much easier @chriselion and powerful. This is my feedback for the Unity ML-Agents :)
