### ISSUE TITLE
Python client freezes if reset() called instantly after creating UnityEnvironment

### ISSUE THREAD

**Issue by SSS135** [Unity-Technologies/ml-agents#42]
```
from unityagents import UnityEnvironment
env = UnityEnvironment(file_name='3DBall')
env.reset()
```
This code freezes python client 4 of 5 times. If ```env.reset()``` is called with some delay (~2 seconds), everything will work as expected. This may happen because python client starting communication before game is fully loaded.
Tested on Python 3.6 / Jupyter / Windows 10 x64.

**Comment by awjuliani** [comment]
Hi @SSS135,

Does this happen both from Jupyter and directly running `ppo.py` from the command line? It may be Windows-specific behavior, in which case we can add a wait-timer for the "made with Unity" screen to finish before initializing the socket.
