### ISSUE TITLE
Train error in Penguin demo "self.trainers[] is empty. "

### ISSUE THREAD

**Issue by HulkMaker** [Unity-Technologies/ml-agents#4200]
When I run the train command (as below) and click the player button in unity editor:
$mlagents-learn config/trainer_config.yaml --curriculum config/curricula/penguin --run-id penguin_01 --train
The erroe would appear as below picture:
![image](https://user-images.githubusercontent.com/5285649/86945234-694ccb00-c17b-11ea-86a4-042b9fecd581.png)

For the log info, the self.trainers[] is empty. 
Traceback (most recent call last):
  File "d:\ai\ml-agents\ml-agents\mlagents\trainers\trainer_controller.py", line 204, in start_learning
    trainer = self.trainers[brain_name]

Anyone could help on this issue?

**Comment by andrewcoh** [comment]
Hi @HulkMaker 

Can you link your yaml?

Is it possible that you have removed the new lines from the yaml? Judging by the last line of the trace, it looks like your configuration is being read as a single line string.

**Comment by HulkMaker** [comment]
> Hi @HulkMaker
> 
> Can you link your yaml?
> 
> Is it possible that you have removed the new lines from the yaml? Judging by the last line of the trace, it looks like your configuration is being read as a single line string.

yes, wrong format of the yaml is exactly the root cause. 
Solved! I can train now.
Thanks for your help!
