### ISSUE TITLE
Output Keras .h5 Model after training

### ISSUE THREAD

**Issue by Shubhamai** [Unity-Technologies/ml-agents#4215]
**Is your feature request related to a problem? Please describe.**

I want to implement the neural networks that were trained in ML-Agents to real-world hardware like the raspberry pi. And with the trained model files (`.onnx` & `.nn`)

 I found there is no way to input the observations and getting the output actions in python. There are many other outputs after training like `fronzen_graph_def.pb` which looks like i could input the observation & getting actions in python but then i couldn't able to find anything to do it with TensorFlow 2.0 or previous versions.

**Describe the solution you'd like**

I solution i would love to get an output  `.h5` trained keras model after training in ML-Agents, because it is much easier for my to use Keras & input real-world observations & getting actions. 

**Describe alternatives you've considered**

Alternative i would like is that any docs or codes for how to use `frozen_graph_def.pb` file or another file to input the observations & getting actions using Tensorflow or simply Python.

Thanks.

**Comment by Shubhamai** [comment]
Hi @andrewcoh Thanks a lot of assigning yourself for this request. Are you working on this feature? Just asked because I didn't get any updates for this. Thanks Again!

**Comment by andrewcoh** [comment]
Hi @Shubhamai 

Sorry but I am not sure that this is an issue we can help solve since converting `.pb` to `.h5` is entirely outside of ML-Agents.

**Comment by Shubhamai** [comment]
That's completely fine @andrewcoh 🙂, but my alternative was that is there is any way to input the observations in `frozen_graph_def.pb` and get the actions. Is that possible ?

**Comment by andrewcoh** [comment]
Do you mean instead of loading the model from the .pb into a tensorflow graph?

**Comment by Shubhamai** [comment]
Yeah @andrewcoh Loading the .pb into TensorFlow and inputting the observations and getting the actions.
