### ISSUE TITLE
How to deal with local minimum for PPO training

### ISSUE THREAD

**Issue by sunirisgrace** [Unity-Technologies/ml-agents#4216]
Hi,
   I just to train an agent to reach the goal in a little complicated static  #environment. However, the agent stuck into the local minimum region and didn't explore the environment although I use curiosity feature. Furthermore, I wonder if the agent finds the target in multiple steps, how can I save the training parameters for good results and discard the bad results since I found that the agent doesn't know how to avoid the obstacles and reach the goals if it failed to find the target in most recent 100k steps though it succeeded  in the middle phase of training. How to make the agent remember the successful episodes so that it can reach the goals successfully every 2000 steps.
    Thanks!

**Describe the bug**

**To  #Reproduce**

**Console logs / stack traces**
Please wrap in [triple backticks (```)](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make it easier to read.

**Screenshots**

**Environment (please complete the following information):**
- Unity Version: [e.g. Unity 2020.1f1]
- OS + version: [e.g. Windows 10]
- _ML-Agents version_: (e.g. ML-Agents v0.8, or latest `develop` branch from source)
- _TensorFlow version_: (you can run `pip3 show tensorflow` to get this)
- _Environment_: (which example environment you used to reproduce the error)

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by andrewcoh** [comment]
Hi @sunirisgrace 

This type of problem may be better suited for the forums here https://forum.unity.com/forums/ml-agents.453/ since it is not so much a bug in ML-Agents but some issue with the way the problem is formulated. Please try sharing on the forums with a precise description of your reward function and the expected behavior.
