### ISSUE TITLE
Does it support distributed agents?

### ISSUE THREAD

**Issue by DazeHolic** [Unity-Technologies/ml-agents#4256]
I wan to train a model with multy agents for speed up trainning. I know it support  multi-agent in one scene. But my environment takes too much time to run and cost 60% CPU. So get more agents in one PC can't solve my problem. I want to train agents in several PCs.

How can I solve this problem?

Thanks!

**Comment by vincentpierre** [comment]
Hi,
Distributed training is on our roadmap and we are currently working on it. It was announced in this [blog post](https://blogs.unity3d.com/2020/05/12/announcing-ml-agents-unity-package-v1-0/) in the section **ML-Agents Cloud**. We do not yet have a release date...

**Comment by DazeHolic** [comment]
hey, vincentpierre.
I'll always be waiting for this.
Thank you for your efforts.

**Comment by Hsgngr** [comment]
We  are so excited about Distributed RL, please inform us a soon as you start to work on it.

**Comment by tjasmnz** [comment]
@vincentpierre I'm working on a distributed training and started to explore more into the ML agents python API; plan on this is to run AWS ECS cluster, and I wonder if you would be able to give us some directions on the best approach to handle this one? I appreciate the support. I am looking forward to getting some feedback.
