### ISSUE TITLE
XRSettings.asset error

### ISSUE THREAD

**Issue by AMGMNPLK** [Unity-Technologies/ml-agents#4258]
XRSettings.asset produce a Failed to load 'C:/Users/user/RiderProjects/Representador-Dev/Assets/ML-Agents/Project/ProjectSettings/XRSettings.asset'. File may be corrupted or was serialized with a newer version of Unity.

I proceed to delete this asset and seems to be fixed.

**To Reproduce**
Just trying load

**Console logs / stack traces**

0x00007FF6D8432CAD (Unity) AssetDatabase::ReSerializeAssetsIfNeededButNoImport<core::hash_set<UnityGUID,core::hash<UnityGUID>,std::equal_to<UnityGUID> > >
0x00007FF6D84464C7 (Unity) AssetDatabase::ReSerializeAssetsWithoutImportIfNeeded
0x00007FF6D851C458 (Unity) ImportAndPostprocessOutOfDateAssets
0x00007FF6D8523B6B (Unity) RefreshInternalV2
0x00007FF6D85267E6 (Unity) StopAssetImportingV2
0x00007FF6D8524396 (Unity) RefreshV2
0x00007FF6D8446C01 (Unity) AssetDatabase::Refresh
0x00007FF6D7A4A5A1 (Unity) Application::AutoRefresh
0x00007FF6D83C1D60 (Unity) ContainerWindow::ContainerWndProc
0x00007FFA8A7BE338 (USER32) CallWindowProcW
0x00007FFA8A7BDEBC (USER32) DispatchMessageW
0x00007FFA8A7D06A3 (USER32) SendMessageTimeoutW
0x00007FFA8AB2EBC4 (ntdll) KiUserCallbackDispatcher
0x00007FFA88AD1064 (win32u) NtUserPeekMessage
0x00007FFA8A7BA5C3 (USER32) PeekMessageW
0x00007FFA8A7B9AD0 (USER32) PeekMessageA
0x00007FF6D83CB67F (Unity) MainMessageLoop
0x00007FF6D83D5C58 (Unity) WinMain
0x00007FF6DB3C7792 (Unity) __scrt_common_main_seh
0x00007FFA89756FD4 (KERNEL32) BaseThreadInitThunk
0x00007FFA8AADCEC1 (ntdll) RtlUserThreadStart

**Environment:**
- Unity Version: 2019.4.4.f1
- OS + version: Windows 10
- _ML-Agents version_: ML-Agents Release 4

**Comment by awjuliani** [comment]
Hi @AMGMNPLK 

I just loaded a fresh version of the project with the same Unity version and did not get any errors. Had you perhaps upgraded from a previous version of Unity or ML-Agents?

**Comment by AMGMNPLK** [comment]
Yes, I was upgrading from 0.4b to 1 and before finishing I upgraded to 4. Now it is working without that file.
