### ISSUE TITLE
Depth image support

### ISSUE THREAD

**Issue by KevinWu57** [Unity-Technologies/ml-agents#4269]
I am building a project for embodied agent navigation using MLAgent toolkit. Currently the toolkit supports camera and rendertexture sensor. Do you have a plan to integrate depth maps as input to the model? It would act like a LIDAR sensor which can be useful for research about scene reconstruction. For now I am using a postprocessed rendertexture which outputs a depth map from the camera view using Unity's built-in depth buffer. It would be much more convenient if you have provide a support for depth map.
![image](https://user-images.githubusercontent.com/46989361/88434366-ddf74a80-cdb4-11ea-8c80-1f317f6a58f4.png)

**Comment by awjuliani** [comment]
Hi @KevinWu57 

Thanks for making this request.  It sounds like your workaround is the right one. I think the solution on our end would be to either extend the camera sensor, or add a new depth camera sensor. Others have asked for this before, and I believe it is something we on the team have internally explored, so I will make sure this request is properly logged.

**Comment by KevinWu57** [comment]
Hi @awjuliani 

Thank you for logging this request! I would be more than happy to see the integration of the depth map!
