### ISSUE TITLE
About Python-API

### ISSUE THREAD

**Issue by linliu0624** [Unity-Technologies/ml-agents#4271]
Hello I'm new in ml-agents.
Do you have any getting-started about python-API in Release_3 or 4?
I read [Unity ML-Agents Python Low Level API](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Python-API.md#unity-ml-agents-python-low-level-api) but still not sure how it work.
like the file ["getting-started.ipynb"](https://github.com/Unity-Technologies/ml-agents/blob/0.14.1/notebooks/getting-started.ipynb) in the 0.14.1 version.
Or can somebody recommend something simple code about python-API?

By the way, how to get the output from camera sensor? Can I train agent's vision by my self?
That will very helpful.
thanks.

**Comment by awjuliani** [comment]
Hello. We have a colab notebook which replaces the old getting-started notebook: https://colab.research.google.com/drive/1Qg6E5kmf9n4G8rc5lXHIM_cQzMUFGH-g#forceEdit=true&sandboxMode=true.

**Comment by linliu0624** [comment]
@awjuliani Thank you very much
I notice that the file name is "Colab-UnityEnvironment-1-Run.ipynb"
Is there have Colab-UnityEnvironment-2 or 3 ?
I tried to find them in github or search the name in google but i didn't found.
I can't even found Colab-UnityEnvironment-1-Run.ipynb in your github.
Is there exist? If yes, where are they placed.

**Comment by chriselion** [comment]
There are 3 colab notebooks; they're linked from this section in the docs:
https://github.com/Unity-Technologies/ml-agents/tree/release_5/docs#python-tutorial-with-google-colab
