### ISSUE TITLE
Expand documantation on Ray Perception Sensor, what do return values mean?

### ISSUE THREAD

**Issue by seanysull** [Unity-Technologies/ml-agents#4272]
The documentation (Learning Environment Design - Agents) as far as I have found does not explain what the returned observations for Ray Perception Sensor mean. It gives a formula for how many there will be and the parameter meanings for the editor but no more. For example with 1 ray per direction and 1 tag I have 3 rays and 9 return values. I have tried to work out what they mean by experimentation but it is not easy and does not scale well with multiple rays and tags.

The order in which the ray cast results appear in the returned vector and what each of them mean in a simple 1 ray per direction 1 tag case would be helpful for most users I believe. 

Thanks for all the hard work it is appreciated.

**Comment by awjuliani** [comment]
Hello @seanysull the docstring in the code here describes what I believe you are looking for https://github.com/Unity-Technologies/ml-agents/blob/master/com.unity.ml-agents/Runtime/Sensors/RayPerceptionSensor.cs#L170. Let me know if that makes sense.

**Comment by seanysull** [comment]
That does indeed explain things.
