### ISSUE TITLE
Update the documentation for first Training from skratch

### ISSUE THREAD

**Issue by alphonse92** [Unity-Technologies/ml-agents#4277]
**Is your feature request related to a problem? Please describe.**
This is not a problem, just for clarification for newbies (as me).

**Describe the solution you'd like**
I would like a description to address to the new people be able to train from scratch, setting the Behaviour Component properly in this doc:

https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Getting-Started.md#training-a-new-model-with-reinforcement-learning 

For example, the first time I was not able to train because my behavior type was "Heuristic Only" and not "Default". Obviously I could not train with "Inference Only" because I had no model to train.

Can I create a Pull Request for it? If yes, let me do it!

Thanks!

**Comment by awjuliani** [comment]
Hi @alphonse92 

For clarification, it wasn't any of our example environments which had the behavior parameter set to "Heuristic Only," rather it was your own environment? As far as I know, all our examples have "Default" set, and can be trained directly. If that is the case, it may not be the getting started that is the best place for this documentation note, but rather one of. the documents we have specifically about making new environments.
