### ISSUE TITLE
Using UnityEnvironment with customized environment binary

### ISSUE THREAD

**Issue by yijiezh** [Unity-Technologies/ml-agents#4284]
**Context**
I can successfully use the provided UnityEnvironment() to load the sample binary. However, when it come to some game binary I built myself, it throw errors that I don't know how to proceed.

```
Load Player Failed. Create new data. : System.IO.FileNotFoundException: Could not find file "/root/.config/unity3d/ABC/ABCDev/Save/d1050.dat"
File name: '/root/.config/unity3d/ABC/ABCDev/Save/d1050.dat'
  at BIJEncryptDataReader..ctor (System.String name, System.Text.Encoding encoding, BIJEncryptDataReader+MODE _mode) [0x0008f] in <32a6cb85fab44dcda629495958136a2b>:0
  at BIJEncryptDataReader..ctor (System.String name) [0x00007] in <32a6cb85fab44dcda629495958136a2b>:0
  at Data.UserData.LoadPlayerData () [0x00006] in <32a6cb85fab44dcda629495958136a2b>:0
```

Using ml-agent cli can successfully talk to the binary, but failed if I try to load it with UnityEnvironment()

I guess there might be some contract/routine that need to follow when building the binary?
a.k.a what should be included and what should not be included in the binary.

**Is your feature request related to a problem? Please describe.**
Can we add an example on how to load a customized game using UnityEnvironment().

**Describe the solution you'd like**
An example on how to load a customized game using UnityEnvironment().
Documentation on how the UnityEnvironment() talk to the binary might also be helpful.
Documentation on what should be included in the binary, what is the rule need to follow when building up the binary.

**Comment by chriselion** [comment]
> Using ml-agent cli can successfully talk to the binary

Do you mean when you pass it as the `--env` argument to `mlagents-learn`?

`mlagents-learn` uses a UnityEnvironment under the hood, so there shouldn't be anything different in how they launch the executable. You can see where it gets launched [here](https://github.com/Unity-Technologies/ml-agents/blob/release_4/ml-agents-envs/mlagents_envs/env_utils.py#L93-L101). 

Does the file it's trying to load actually? Maybe there's a difference in permissions between when you call mlagents-learn and when you use a UnityEnvironment?

**Comment by yijiezh** [comment]
> Do you mean when you pass it as the --env argument to mlagents-learn?

Yes. Hmm, interesting. Can you where the process use the UnityEnvironment() to wrap the binary?

> Does the file it's trying to load actually? Maybe there's a difference in permissions between when you call mlagents-learn and when you use a UnityEnvironment?

I think it's loading. And error throw out in the middle.

**Comment by chriselion** [comment]
> Can you where the process use the UnityEnvironment() to wrap the binary?

* learn.py creates a SubprocessEnvManager... https://github.com/Unity-Technologies/ml-agents/blob/8327ddcb2a65ccb0a76ce6390811212d1daebb6e/ml-agents/mlagents/trainers/learn.py#L129
* which starts a new subprocess using the `worker()` function: https://github.com/Unity-Technologies/ml-agents/blob/8327ddcb2a65ccb0a76ce6390811212d1daebb6e/ml-agents/mlagents/trainers/subprocess_env_manager.py#L231-L242
* that calls the env_factory callable that was passed to it: https://github.com/Unity-Technologies/ml-agents/blob/8327ddcb2a65ccb0a76ce6390811212d1daebb6e/ml-agents/mlagents/trainers/subprocess_env_manager.py#L138-L140
* which actually creates the UnityEnvironment: https://github.com/Unity-Technologies/ml-agents/blob/8327ddcb2a65ccb0a76ce6390811212d1daebb6e/ml-agents/mlagents/trainers/learn.py#L208-L217
