### ISSUE TITLE
Adding new event to Academy.Instance which calls delegate every training episode

### ISSUE THREAD

**Issue by HPRIOR** [Unity-Technologies/ml-agents#4288]
I have been trying to coordinate the spawning of multiple agents but have been running into difficulties. In most of the examples, the scene is coordinated from an agents OnEpisodeBegin( ). However, as far as I can tell there is no means to organise training at the Academy instance level. Trying to organise various agents, and the environment seems clumsy. All of the agents OnEpisodeBegin( )'s are called at the end of an episode, so if you want to spawn an environment, this needs to be coordinated by a single agent. This doesn't afford me the flexibility in setting up the training whereby I would maybe want to exclude this 'master' agent, to, for example, train another one in isolation.

The OnEnvironmentReset provides the kind of mechanism I would like, but it is only called once at the start of training. I would like a similar event system that would call delegates once at the start of an episode. Basically an OnEpisodeBegin for a training instance. 

My current workaround is to have every agent call the delegate I passed to OnEnvironmentReset manually at the end of each episode (apart from the first time, when the academy calls it for me). I check the number of times this has been called, and the rest of the method only proceeds when the last agent in the scene calls it - ensuring it is called once per episode.

**Comment by chriselion** [comment]
Out of curiosity, was [this](https://forum.unity.com/threads/problem-with-the-onenvironmentreset-delegate.942262/) you? (No problem posting in both, just want to check)

> Basically an OnEpisodeBegin for a training instance.

By "training instance", do you mean an independent area like we discuss [in the docs](https://github.com/Unity-Technologies/ml-agents/blob/release_5/docs/Learning-Environment-Design.md#multiple-areas)? There's currently no notion of this in the SDK, and I'm not sure we want to introduce it now.

If you have a class that manages the training instance, I would recommend putting the reset logic in this, instead of trying to have a single Agent coordinate it.

**Comment by HPRIOR** [comment]
> Out of curiosity, was [this](https://forum.unity.com/threads/problem-with-the-onenvironmentreset-delegate.942262/) you? (No problem posting in both, just want to check)

Yes that was me. 

> By "training instance", do you mean an independent area like we discuss [in the docs](https://github.com/Unity-Technologies/ml-agents/blob/release_5/docs/Learning-Environment-Design.md#multiple-areas)? There's currently no notion of this in the SDK, and I'm not sure we want to introduce it now.

Sorry for introducing my own terminology I was struggling to describe what I meant. 

> If you have a class that manages the training instance, I would recommend putting the reset logic in this, instead of trying to have a single Agent coordinate it.

Is there a way to do this without coordinating it with an agent? As far as I'm aware, when an episode ends, each agents OnEpisodeBegin is called. The feature I am after would be a method which can be called exactly once each time an episode ends.  I'm struggling to find a way to access the restart logic without first going through an agent - although this is probably a design issue on my end. I have a class which coordinates the spawning of agents and the environment each time an episode ends. I need a way to signal to it that the episode has ended, and I am currently doing that by calling the restart class in exactly one agents OnEpisodeBegin.

**Comment by HPRIOR** [comment]
I guess I could check for the Academies step count in an Update method and restart the environment once it has reached the max step count.
