### ISSUE TITLE
Log whole training statistics when using --resume flag

### ISSUE THREAD

**Issue by KevinWu57** [Unity-Technologies/ml-agents#4295]
**Is your feature request related to a problem? Please describe.**
I notices that when l started a training process using `--resume` flag, all the statistics saved in a csv file will be overwrittern by the new training process. I know that the statistics can be recovered from the checkpoint and tensorflow graph, but it would be much convenient if the whole training statistics can be logged, not just the most recent ones where the training resumes.

**Describe the solution you'd like**
Keep old training stats when resuming from an existing training in the csv file.

**Comment by chriselion** [comment]
Hi @KevinWu57,
The CSV stats have been deprecated (unofficially) for a while. There's a similar issue here https://github.com/Unity-Technologies/ml-agents/issues/3861 with a workaround on how to get the values from tensorboard.

**Comment by KevinWu57** [comment]
Hi @chriselion 
I see. Thanks for your response!
