### ISSUE TITLE
Unity Gym Wrapper: AttributeError: 'str' object has no attribute 'behavior_specs'

### ISSUE THREAD

**Issue by vtan05** [Unity-Technologies/ml-agents#4303]
**Describe the bug**
Hi. I'm trying to use the Unity Gym Wrapper with Stable Baseline. But importing the environment gives attribute errors.

**To Reproduce**
1. Built an executable environment with a single agent as instructed here: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Executable.md
2. Importing the environment as instructed here: https://github.com/Unity-Technologies/ml-agents/tree/master/gym-unity

**Console logs / stack traces**
'''AttributeError: 'str' object has no attribute 'behavior_specs''''

**Screenshots**
![mlagentbug](https://user-images.githubusercontent.com/42295449/89422008-5839ae80-d767-11ea-95a9-3615e58afdf3.png)

**Environment (please complete the following information):**
- Unity Version: 2019.4.f01
- OS + version: Windows 10
- _ML-Agents version_: 0.18.1
- _TensorFlow version_: 1.15.0
- _Environment_: 3D Ball Hard

**Comment by RedTachyon** [comment]
On the line where you're calling
`env = UnityToGymWrapper(env_name)`

try instead doing

`env = UnityToGymWrapper(UnityEnvironment(env_name))` as per the instructions you linked?

**Comment by vtan05** [comment]
@RedTachyon Oooh. It worked. Haha. Did not see the UnityEnvironment() part. Thank you!
