### ISSUE TITLE
The tensorflow graph needs an input for epsilon  of type DT_FLOAT

### ISSUE THREAD

**Issue by claychinasky** [Unity-Technologies/ml-agents#431]
Hello,

I'm getting an error 

`The tensorflow graph needs an input for epsilon  of type DT_FLOAT`

and when I add it, named ` epilson ` float type I'm getting another error  : 

`One of the Tensorflow placeholder cound nout be found.
                In brain KickBrain, there are no FloatingPoint placeholder named epilson`

What seems to be an issue ?

**Comment by claychinasky** [comment]
I TOTALLY misspelled that epsilon!

**Comment by awjuliani** [comment]
Hi @claychinasky,

I am going to assume that changing the spelling of the word fixed your issue and will close the issue as such. If not, please feel free to reopen. I am also happy to report that we are removing the need to add epsilon in the upcoming v0.3 release.
