### ISSUE TITLE
Demonstration Recorder Malfunction

### ISSUE THREAD

**Issue by prasengan** [Unity-Technologies/ml-agents#4313]
**Describe the bug**
Demonstration recorder stops recording if the agent gameObject is disabled. In my project (Shooter Battle Royale Game) agents need to die with time, I have simulated that using gameObject.SetActive(false). I was able to train my models through SAC and PPO, seems like there's a bug with Demonstration recorder as I am not able to record play through, say if I die by chance then the recording clears older data and the saved file has only content newer experiences if any.

**To Reproduce**
1. Go to FoodCollector example
2. Modify the code to Deactivate gameObject on "Freeze" and reset (GameObject.SetActive(true)) it on episode reset.
3. Attach demonstration recorder to one of the agents.
4. If this agent with demonstration recorder gets frozen then you will be able to see the bug.

**Console logs / stack traces**
Please wrap in [triple backticks (```)](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make it easier to read.

**Screenshots**

**Environment (please complete the following information):**
- Unity Version: Unity 2018.4.15f1
- OS + version: Windows 10 home 1909
- _ML-Agents version_: 0.17.0
- _TensorFlow version_: 1.15.0rc2
- _Environment_: FoodCollector (any environment where you can possibly deactive agent GameObject, read description)

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by anupambhatnagar** [comment]
@prasengan could you please provide details(logs) for the bug that you see?

**Comment by prasengan** [comment]
> @prasengan could you please provide details(logs) for the bug that you see?

There are no logs, no error, no warnings. BTW the above information should be sufficient and bug can be easily recreated and verified please follow the mentioned steps

**Comment by ervteng** [comment]
Hi @prasengan, have you resolved the issue?

**Comment by prasengan** [comment]
Yes

**Comment by ervteng** [comment]
Thanks, closing for now. Feel free to repost if you run into it again.
