### ISSUE TITLE
Curriculum learning doesn't work - and no warning is shown - when behavior is not set

### ISSUE THREAD

**Issue by Ihsees** [Unity-Technologies/ml-agents#4326]
**Is your feature request related to a problem? Please describe.**

From the docs:
[Training-ML-Agents.md](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-ML-Agents.md)
`behavior: Specifies which behavior is being tracked. There can be multiple behaviors with different names, each at different points of training. This setting allows the curriculum to track only one of them.`

This sounds like this parameter is optional.

However, if I don't specify this parameter, the next lesson will not be activated.

**Describe the solution you'd like**
My environment has two "behaviours" in it, although one of them is set to "Heuristic-Only". So I haven't tested if the code behaves more rationally if there is only one behaviour.

Ideally it would either use the only behaviour for tracking there is (if there is only 1 in the scene),
or give me a warning about a misconfigured config.yaml.

**Comment by anupambhatnagar** [comment]
Hi @Ihsees could you please provide some more details so that this can be answered accurately.

Environment name?
Unity version?
OS?
ML-Agents version?
Tensorflow version?

It would be great if you could share the config.yaml you are using.

**Comment by Hsgngr** [comment]
What should it change if you dont define a parameter in terms of Curriculum learning ?  I think you are misunderstanding the concept of it. You need to define values on your own for each lesson.

**Comment by Ihsees** [comment]
Haven't tested the commit on my codebase yet, but that if-clause looks exactly like what I've had in mind. Thank you!

**Comment by chriselion** [comment]
This was fixed in #4346 a few months ago, and is available in the 0.20.0 (and later) version of the mlagents package.
