### ISSUE TITLE
python connect to example environment(GridWorld) but the environments still making steps automatically.

### ISSUE THREAD

**Issue by Plussun** [Unity-Technologies/ml-agents#4332]
**Describe the bug**
Hi. 
I was testing DQN using pytorch and use env = UnityEnvironment(filename=None)  connect to the GridWorld environment.
After each episode end, the script would call env.reset() to reset. At this moment, env.get_steps(behavior_name) shouldn't get any steps, however I get terminal steps and they cause the program get error.
Then I found that although I connect the environment to the python, when env.reset() is called, the environment still generate steps and the agents receive actions.
I tried to remove the NN model or change the behavior type, but no use.
So how could I do to have a pure environment to be train?
\**To Reproduce**
1.` import mlagents_envs.environment import UnityEnvironment`
`env = UnityEnvironment(filename=None)`
2. go to GridWorld scene, press play button
3. `env.reset()`
4. 
```
behavior_name = list(env.behavior_specs)[0]
decision_steps, terminal_steps = env.get_steps(behavior_name)
print(list(terminal_steps),list(decision_steps))
```
5.get[6] [0, 1, 2, 3, 4, 5, 6, 7, 8] should be [] [] 

the DQN error code:
```
from mlagents_envs.registry import default_registry
import matplotlib.pyplot as plt
from mlagents_envs.environment import UnityEnvironment
import time
%matplotlib inline

env = UnityEnvironment(file_name=None)
print("GridWorld environment created.")

# Create a new Q-Network. 
qnet = VisualQNetwork((64, 84, 3), 126, 5)

experiences: Buffer = []
optim = torch.optim.Adam(qnet.parameters(), lr= 0.001)

cumulative_rewards: List[float] = []

# The number of training steps that will be performed
NUM_TRAINING_STEPS = 70
# The number of experiences to collect per training step
NUM_NEW_EXP = 1000
# The maximum size of the Buffer
BUFFER_SIZE = 10000

for n in range(NUM_TRAINING_STEPS):
  new_exp,_ = Trainer.generate_trajectories(env, qnet, NUM_NEW_EXP, epsilon=0.1)
  random.shuffle(experiences)
  if len(experiences) > BUFFER_SIZE:
    experiences = experiences[:BUFFER_SIZE]
  experiences.extend(new_exp)
  Trainer.update_q_net(qnet, optim, experiences, 5)
  _, rewards = Trainer.generate_trajectories(env, qnet, 100, epsilon=0)
  cumulative_rewards.append(rewards)
  print("Training step ", n+1, "\treward ", rewards)
  


env.close()

# Show the training graph
plt.plot(range(NUM_TRAINING_STEPS), cumulative_rewards)
```
get:

> 
> GridWorld environment created.
> Training step  1 	reward  -1.0033333158741395
> Training step  2 	reward  -0.20299998875707387
> Training step  3 	reward  -0.6059999864548444
> Training step  4 	reward  -0.7799999800821146
> Training step  5 	reward  -1.001111091218061
> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> <ipython-input-6-959c72c29382> in <module>
>      34 
>      35 for n in range(NUM_TRAINING_STEPS):
> ---> 36   new_exp,_ = Trainer.generate_trajectories(env, qnet, NUM_NEW_EXP, epsilon=0.1)
>      37   random.shuffle(experiences)
>      38   if len(experiences) > BUFFER_SIZE:
> 
> <ipython-input-5-476ee916d03f> in generate_trajectories(env, q_net, buffer_size, epsilon)
>      52         # Create its last experience (is last because the Agent terminated)
>      53         last_experience = Experience(
> ---> 54           obs=dict_last_obs_from_agent[agent_id_terminated].copy(),
>      55           reward=terminal_steps[agent_id_terminated].reward,
>      56           done=not terminal_steps[agent_id_terminated].interrupted,
> 
> KeyError: 5
> 
> 

**Environment (please complete the following information):**
- Unity Version: 2019.3
- OS + version: ubuntu 18.04
- _ML-Agents version_: 0.20.0
- _TensorFlow version_: 2.2.0
- _Environment_: GridWorld

**Comment by anupambhatnagar** [comment]
Hi @Plussun I'm unable to reproduce the bug you mentioned on ML-Agents 0.20.0 on a mac with the Gridworld environment. 
here's the output that I got:

```Python 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from mlagents_envs.environment import UnityEnvironment
>>> env = UnityEnvironment()
>>> env.reset()
>>> env.behavior_specs
<mlagents_envs.base_env.BehaviorMapping object at 0x7f8cf82076a0>
>>> name= list(env.behavior_specs)[0]
>>> name
'GridWorld?team=0'
>>> decision_steps, terminal_steps = env.get_steps(name)
>>> print(list(decision_steps))
[0]
>>> print(list(terminal_steps))
[]

**Comment by Plussun** [comment]
> Hi @Plussun I'm unable to reproduce the bug you mentioned on ML-Agents 0.20.0 on a mac with the Gridworld environment.
> here's the output that I got:
> 
> ```python
> [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from mlagents_envs.environment import UnityEnvironment
> >>> env = UnityEnvironment()
> >>> env.reset()
> >>> env.behavior_specs
> <mlagents_envs.base_env.BehaviorMapping object at 0x7f8cf82076a0>
> >>> name= list(env.behavior_specs)[0]
> >>> name
> 'GridWorld?team=0'
> >>> decision_steps, terminal_steps = env.get_steps(name)
> >>> print(list(decision_steps))
> [0]
> >>> print(list(terminal_steps))
> []
> ```

hi.
it will not happen at first, but after several env.reset() is called.here is the new code:
`from mlagents_envs.environment import UnityEnvironment`
`env = UnityEnvironment(file_name=None)`
press play button at Unity
```
for i in range(40):
    env.reset()
    behavior_name = list(env.behavior_specs)[0]
    decision_steps, terminal_steps = env.get_steps(behavior_name)
    print(list(terminal_steps),list(decision_steps))
```
result:

> [] [0]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [3] [0, 1, 2, 3, 4, 5, 6, 7, 8] this one
> [6] [0, 1, 2, 3, 4, 5, 6, 7, 8] this one
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [6] [0, 1, 2, 3, 4, 5, 6, 7, 8] this one
> [1] [0, 1, 2, 3, 4, 5, 6, 7, 8] this one
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [5] [0, 1, 2, 3, 4, 5, 6, 7, 8] this one
> [6] [0, 1, 2, 3, 4, 5, 6, 7, 8] this one
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [6] [0, 1, 2, 3, 4, 5, 6, 7, 8] this one
> [2, 8] [0, 1, 2, 3, 4, 5, 6, 7, 8] this one
> [] [0, 1, 2, 3, 4, 5, 6, 7, 8]
> [0] [0, 1, 2, 3, 4, 5, 6, 7, 8] this one

the GridWorld environment is download from this github, located at mlagents/Project/Assets/ML-Agents/examples/GridWorld
if i use env = default_registry["GridWorld"].make() it works well.
And use the mlagents-learn config/ppo/GridWorld.yaml --run-id=testGridWorld works well too.
But I build the executable x86_64 file, still has this terminal steps problem.

**Comment by anupambhatnagar** [comment]
I was able to reproduce the issue you are facing and have added it to our bug tracker. We will take a closer look at this issue. Thanks for bringing this to our attention.

**Comment by vincentpierre** [comment]
Hi,

I think the issue is resolved on the current master. I ran this code :
```
from mlagents_envs.environment import UnityEnvironment

env = UnityEnvironment()

name= list(env.behavior_specs.keys())[0]

for i in range(40):
    env.reset()
    behavior_name = list(env.behavior_specs)[0]
    decision_steps, terminal_steps = env.get_steps(behavior_name)
    print(list(terminal_steps),list(decision_steps))
```

And got the following result : 

```
[] [0]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
[] [0, 1, 2, 3, 4, 5, 6, 7, 8]
```

Please let me know if you are still facing this issue or if there is a problem with the way I am trying to reproduce the error.
Thank you.
