### ISSUE TITLE
Allow to train at runtime

### ISSUE THREAD

**Issue by Fax3D** [Unity-Technologies/ml-agents#4360]
A great features, imho, it would be the possibility to perfom an agent training not only offline via Unity-editor, but also during the game execution!
There are some ai-oriented game scenario, for example when you want to use imitation learning, in wich would be very useful to run a command to perform a train directly in-game, without rely on an external service.

What do you think about?

Thanks

**Comment by unityjeffrey** [comment]
hi @Fax3D - can you clarify your request?  You should be able to do both imitation learning and training via mlagents-learn.  Let me know if there is something I am missing in your request.  Thanks!

**Comment by Fax3D** [comment]
Hi @unityjeffrey,
mlagents-learn it's callable during gameplay?
I mean... it's possible for an user playing my game start a train of what he played using imitation learning? Or mlagents-learn it's callable only offline?
Thanks!

**Comment by unityjeffrey** [comment]
Hi @Fax3D - ah I think I see what you are asking.  If someone playing your game, could the agent learn while the person is playing the game.  Unfortunately, the trainer code is run in Python and not C#.  We are looking into potentially incorporating C# training in the future.
