### ISSUE TITLE
action_shape should be changed to action_size

### ISSUE THREAD

**Issue by Buczman** [Unity-Technologies/ml-agents#4393]
https://github.com/Unity-Technologies/ml-agents/blob/041c1f34f841bd1dd3f05e0e0f15e7e770c99133/gym-unity/gym_unity/envs/__init__.py#L107-L108

Hello, 
I think in this particular code line you should be referencing acition_size (to get the actual shape of action matrix) instead of action_shape (which returns  the number of discrete actions available to the agent). This conditional statement decides whether Discrete or MultiDiscrete action space sould be used.

CMIIW

**Comment by ervteng** [comment]
I think you're right - I've logged it internally as a bug and will run it by the team. Feel free to submit a PR if you'd like to fix it. Thanks!

**Comment by Buczman** [comment]
Okay, will do! :)

**Comment by ervteng** [comment]
This issue has been resolved (PR #4438) and will be in the next release. Thanks for reporting!
