### ISSUE TITLE
Allow to pass absolute path in UnityEnvironment constructor

### ISSUE THREAD

**Issue by SSS135** [Unity-Technologies/ml-agents#44]
Currently, if using Jupyter notebook to create UnityEnvironment, game.exe file and game_Data folder should be copied to the folder where notebook is located. It would be nice to pass absolute file system path to constructor.

**Comment by awjuliani** [comment]
Hi @SSS135,

This is a good idea for a feature. We will put it on our to-do list. If you happen to end up putting something like this together yourself though, we'd be happy to accept it as a pull request.

**Comment by awjuliani** [comment]
Hi @SSS135,

This feature is now included in our `development` branch on the repo, and will be in the next release of ML-Agents. Thanks for requesting it.
