### ISSUE TITLE
Hallway example scene fails to build "Failed to create Physics Mesh from source mesh "WallsOuter" (New Unity versions)

### ISSUE THREAD

**Issue by Aurimasp** [Unity-Technologies/ml-agents#4435]
1. Try to build the Hallway example scene with the latest 2020.1 Unity version

Result:
 - Build fails with error: 
"Failed to create Physics Mesh from source mesh "WallsOuter". One of the triangles is too large. It's recommended to tesselate the large triangles.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)"

Note: this is a regression from the Unity side. In previous Unity builds this would fail silently, after error handling update it will stop the build, so it should be fixed from the ML-agents example project side. 

Related to this issue: https://issuetracker.unity3d.com/issues/build-throws-one-of-the-triangles-is-too-large-when-an-object-with-mesh-collider-and-generate-colliders-enabled-is-present

**Comment by Hunter-Unity** [comment]
@Aurimasp I replaced the wall mesh with primitives. Can you try this branch and let me know if it fixes this?
https://github.com/Unity-Technologies/ml-agents/tree/hh/develop/hallway-wall-mesh-fix

**Comment by Aurimasp** [comment]
It works with this branch. Thank you!
