### ISSUE TITLE
colab notebooks fail to run Unity environment

### ISSUE THREAD

**Issue by zookae** [Unity-Technologies/ml-agents#4442]
**Describe the bug**
When running the `Colab-UnityEnvironment-2-Train.ipynb` colab notebook the step that runs the Unity environment hangs

from: https://github.com/Unity-Technologies/ml-agents/tree/release_6/docs#python-tutorial-with-google-colab

**To Reproduce**
1. Follow the link to the colab notebook for `Q-Learning with a UnityEnvironment`
1. Run each cell in succession.
1. Observe the output from the cell that loads the Unity environment from the registry (last cell for the Q-learning notebook)

**Console logs / stack traces**
From running the last cell of `Colab-UnityEnvironment-2-Train.ipynb`
```
---------------------------------------------------------------------------
UnityTimeOutException                     Traceback (most recent call last)
<ipython-input-6-5d3e3fee952c> in <module>()
     14 # Create the GridWorld Environment from the registry
     15 # env = default_registry["GridWorld"].make()
---> 16 env= UnityEnvironment(file_name = None)
     17 print("GridWorld environment created.")
     18 

3 frames
/usr/local/lib/python3.6/dist-packages/mlagents_envs/rpc_communicator.py in poll_for_timeout(self)
     95         if not self.unity_to_external.parent_conn.poll(self.timeout_wait):
     96             raise UnityTimeOutException(
---> 97                 "The Unity environment took too long to respond. Make sure that :\n"
     98                 "\t The environment does not need user interaction to launch\n"
     99                 '\t The Agents\' Behavior Parameters > Behavior Type is set to "Default"\n'

UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Agents' Behavior Parameters > Behavior Type is set to "Default"
	 The environment and the Python interface have compatible versions.
```

**Environment (please complete the following information):**
- _Machine_: Running colab from the link. I'm on a windows machine if that matters.
- _ML Agents version_: Used the version linked under the `release_6` tag. The notebook pip installs `mlagents==0.17.0`.
- _Environment_: GridWorld

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by zookae** [comment]
Couple updates:
1. The `Colab-UnityEnvironment-1-Run.ipynb` works.
1. I made a mistake. `Colab-UnityEnvironment-3-SideChannel.ipynb` also works.

The fix for `Colab-UnityEnvironment-2-Train.ipynb`:
1. go to the last cell
1. change the environment loading call to: 
```
env = default_registry["GridWorld"].make()
# env= UnityEnvironment(file_name = None)
```
(in the default code the two are flipped to:
```
#env = default_registry["GridWorld"].make()
env= UnityEnvironment(file_name = None)
```

**Comment by harperj** [comment]
Hi @zookae -- thanks for the bug report. I've updated the colab notebook to load from the registry.
