### ISSUE TITLE
GridSensor shape mismatch

### ISSUE THREAD

**Issue by mbaske** [Unity-Technologies/ml-agents#4456]
**Describe the bug**
I'm trying to retrain the GridFoodCollector demo and get a python error indicating a wrong observation shape.
I think the sensor observes 6 channels, while the PNG-compressed data only has 3.

**Console logs / stack traces**
mlagents_envs.exception.UnityObservationException: Decompressed observation did not have the expected shape - decompressed had (40, 40, 3) but expected [40, 40, 6]

**Environment (please complete the following information):**
- Unity Version: 2020.1.4f1
- Windows 10
- ML-Agents C# from master branch
- ML-Agent python 0.19.0

**Comment by surfnerd** [comment]
hi @mbaske,
I am unable to reproduce your issue. Can you give me more information?

**Comment by surfnerd** [comment]
i used ` mlagents-learn ./config/ppo/FoodCollector.yaml` to run my training session.

**Comment by surfnerd** [comment]
Hi @mbaske,
Did you happen to update the python package when you tried out these changes?

**Comment by surfnerd** [comment]
We will need to bump the communication minor version as this feature was recently added.

**Comment by mbaske** [comment]
Hi @surfnerd, here is my version info:
ml-agents: 0.19.0,
ml-agents-envs: 0.19.0,
Communicator API: 1.0.0,
TensorFlow: 2.2.0
Do I need to upgrade any of this?

**Comment by surfnerd** [comment]
Yes, you will need to install the python packages from master.

**Comment by surfnerd** [comment]
from the root directory of the repo:
```
$ python3 -m pip install -e ./ml-agents-envs/
$ python3 -m pip install -e ./ml-agents/
```

**Comment by mbaske** [comment]
Thank you! 
I updated the python files and I'm not getting the UnityObservationException any longer.
