### ISSUE TITLE
RenderTextureSensor exception at start of 2nd episode

### ISSUE THREAD

**Issue by Godatplay** [Unity-Technologies/ml-agents#4457]
**Describe the bug**
I have a RenderTextureSensorComponent on my agent, and in that agent's Start, I assign a RenderTexture generated at runtime to that component. In the editor, I can see the field updated correctly at start. However, at the start of the 2nd episode, I get an UnassignedReferenceException.

**To Reproduce**
1. Create an Agent following the documentation.
2. Assign RenderTextureSensor to the agent
3. In the Agent subclass's Start, assign a RenderTexture generated at runtime to the sensor.
4. Wait for the 1st episode to finish

**Console logs / stack traces**
```
UnassignedReferenceException: The variable m_RenderTexture of RenderTextureSensorComponent has not been assigned.
You probably need to assign the m_RenderTexture variable of the RenderTextureSensorComponent script in the inspector.
Unity.MLAgents.Sensors.RenderTextureSensor.ObservationToTexture (UnityEngine.RenderTexture obsTexture) (at Library/PackageCache/com.unity.ml-agents@1.3.0-preview/Runtime/Sensors/RenderTextureSensor.cs:104)
Unity.MLAgents.Sensors.RenderTextureSensor.GetCompressedObservation () (at Library/PackageCache/com.unity.ml-agents@1.3.0-preview/Runtime/Sensors/RenderTextureSensor.cs:64)
Unity.MLAgents.Policies.HeuristicPolicy.StepSensors (System.Collections.Generic.List`1[T] sensors) (at Library/PackageCache/com.unity.ml-agents@1.3.0-preview/Runtime/Policies/HeuristicPolicy.cs:134)
Unity.MLAgents.Policies.HeuristicPolicy.RequestDecision (Unity.MLAgents.AgentInfo info, System.Collections.Generic.List`1[T] sensors) (at Library/PackageCache/com.unity.ml-agents@1.3.0-preview/Runtime/Policies/HeuristicPolicy.cs:35)
Unity.MLAgents.Agent.NotifyAgentDone (Unity.MLAgents.Agent+DoneReason doneReason) (at Library/PackageCache/com.unity.ml-agents@1.3.0-preview/Runtime/Agent.cs:492)
Unity.MLAgents.Agent.AgentStep () (at Library/PackageCache/com.unity.ml-agents@1.3.0-preview/Runtime/Agent.cs:1185)
Unity.MLAgents.Academy.EnvironmentStep () (at Library/PackageCache/com.unity.ml-agents@1.3.0-preview/Runtime/Academy.cs:539)
Unity.MLAgents.AcademyFixedUpdateStepper.FixedUpdate () (at Library/PackageCache/com.unity.ml-agents@1.3.0-preview/Runtime/Academy.cs:34)
```

**Screenshots**
No errors while in the first episode, RT assigned
![image](https://user-images.githubusercontent.com/198019/92305314-bcf54e00-ef4b-11ea-886e-07ff1aad2fd0.png)

Error thrown at the start of 2nd episode
![image](https://user-images.githubusercontent.com/198019/92305332-d39ba500-ef4b-11ea-89c8-be0492a4f4f1.png)

**Environment (please complete the following information):**
- Unity Version: Unity 2019.4.8f1
- OS + version: Windows 10
- _ML-Agents version_: release 6 branch
- _TensorFlow version_: 2.3.0
- _Environment_: You can use this simple agent, which I used to repro the bug in 3DBall:

```
using UnityEngine;
using Unity.MLAgents;
using Unity.MLAgents.Sensors;

public class RTBugAgent : Agent
{
  public RenderTextureSensorComponent renderTextureSensorComponent;
  void Start ()
  {
    RenderTexture testRT = new RenderTexture(32, 32, 32);
    renderTextureSensorComponent.RenderTexture = testRT;
  }

  public override void OnEpisodeBegin ()
  {
  }

  public override void CollectObservations (VectorSensor sensor)
  {
  }

  public override void OnActionReceived (float[] vectorAction)
  {
  }
}
```

**Comment by surfnerd** [comment]
Hi @Godatplay,
The RenderTextureSensorComponent creates the underlying Sensor during agent initialization and uses the reference that is set in the inspector.  It is not expected that you set the render texture at runtime.

**Comment by surfnerd** [comment]
can you give us more information on your use case and perhaps turn this into a request instead of a bug?  Runtime updating of the RenderTexture is not supported at this time.

**Comment by Godatplay** [comment]
Aww that's unfortunate, but thanks for the heads up. IMO the most common use case for a RenderTexture, at least for newer Unity workflows, is to create it at runtime. Otherwise why not tie it to a camera like the older workflow and use that component instead?

But more specifically, if one is building something dynamically at runtime, especially in the case of procedural generation, one would generate the RT at runtime.

In my case I have a more complex art pipeline where I have a runtime baking system that resembles Blender's Eevee with soft shadows and near realtime AO baking. I then want to train an agent to regenerate that baked texture, but in a special procedural way that results in a specific visual style. The pipeline I'm setting up resembles some of Artomatix's tools, but for stylized art instead of photoreal art. Because I'm working at runtime, I'm naturally using RenderTextures, and therefore it seemed a safe assumption that I should be able to use the dedicated sensor for that.

**Comment by Godatplay** [comment]
I guess in a sense I'm trying to do something almost like style transfer, but more physically-simulated, and with more control than the existing style transfer solutions out there. It's exciting to see it all happening in realtime, at least time-sliced, but currently the generation is just not smart enough.
