### ISSUE TITLE
Improve the "Training Configuration File" documentation page to better highlight differences between training a single agent and multiple agents

### ISSUE THREAD

**Issue by NeonMika** [Unity-Technologies/ml-agents#4458]
**Is your feature request related to a problem? Please describe.**
I am currently learning how to use ml-agents step by step, and recently started to train multiple agents at once, i.e., having multiple independent agents in my Unity scene training at the same time.
Yet, the documentation (i.e., the page "Training Configuration File") is missing any advice on which settings (i.e., hyperparameters) to adjust when switching from single-agent to multi-agent training.
For example, `time-horizon` clearly states that it is *per-agent*, i.e., no changes are needed when switching to multi-agent.
Yet I think that we also should increase `buffer_size`, as it seems this is a shared buffer between all agents?
Also, I think it is a good suggestion to increase `max_steps` when training multiple agents at once in many cases.
As I am no expert, I could also imagine that other parameters should be adjusted when training with multiple agents at the same time (e.g., should I reconsider `batch_size` or anything?)

**Describe the solution you'd like**
I would like to see a section in the "Training Configuration File" document that states considerations to make when switch from single-agent training to multi-agent training (or what to consider in general when training multiple agents at once).

**Describe alternatives you've considered**
The description could also happen on another documentation page.
Then it should at least be linked from "Training Configuration File".
Yet, since the considerations mostly concern hyperparameter setting, I think the above mentioned page would fit best.

**Additional context**
I would love to provide a pull request for this, yet I do not have to expertise to write the requested section.
I hope that you also see the upside in having such a section and that you could provide some information for us beginners. 

Thanks you,
Markus

**Comment by surfnerd** [comment]
Hi @NeonMika,
I've logged this internally as MLA-1347. We will update this issue when this happens.  Thank you for our input.
