### ISSUE TITLE
Barracuda operators request. 

### ISSUE THREAD

**Issue by eublefar** [Unity-Technologies/ml-agents#4460]
**Is your feature request related to a problem? Please describe.**
I have been trying to import ONNX [Huggingface ](https://huggingface.co/transformers/master/index.html) GPT-2 pretrained transformer into barracuda. The problem seem to be that it does not support some operators (mostly opset 11). 

**Describe the solution you'd like**
I've loaded the model with "Treat Errors as Warnings" option and found all unknown operators (Unknown type warnings), there are just 3 of them: **Range**, **Split** and **Where**, none appear in supported ops page. Hopefully it should work after implementing those, hence the request :) 

**Additional context**
Am I missing something? Could there be more problems with loading ONNX GPT-2 into Barracuda?

**Comment by surfnerd** [comment]
Hi @eublefar,
Could you post this on the[ barracuda github repo](https://github.com/Unity-Technologies/barracuda-release/issues)?  This is repo is specifically for ml-Agents.  Thank you.

**Comment by eublefar** [comment]
Hi @surfnerd ,
I will, thanks. 
I wanted to do so at first but supported operators page says to post such requests here. https://docs.unity3d.com/Packages/com.unity.barracuda@1.0/manual/SupportedOperators.html
