### ISSUE TITLE
 While learning in curriculum learning, it would be nice to be able to see that the environment parameter changes as the lesson changes.

### ISSUE THREAD

**Issue by jwson97** [Unity-Technologies/ml-agents#4464]
During the training step, reward and mean reward are now displayed.
It would be nice to show environment parameter changes as well. 
And I would like to show the status of the lessons currently in progress.

**Comment by andrewcoh** [comment]
Hi @jwson97,

Just to be sure I understand, do you mean you'd like to see the actual value of the environment parameter during training in addition to the lesson number which is currently reported on tensorboard?

Please correct me if I'm misunderstanding. I'll bring this up to the team during the next meeting.

**Comment by jwson97** [comment]
Yes, that's what I want. Thanks.

**Comment by andrewcoh** [comment]
This may not be a feature we can support in general. Environment parameters are not always float values, they can also tuples that describe a sampler i.e. https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-ML-Agents.md#supported-sampler-types.  It's not clear how we could generalize to this and future controllers for environment parameters.
