### ISSUE TITLE
Adding BC and GAIL to previously trained agents

### ISSUE THREAD

**Issue by russellcaughey** [Unity-Technologies/ml-agents#4480]
**Is your feature request related to a problem? Please describe.**
I have an trained agent (200M+ steps) but I needed to makes some adjustments to the agents physics so it now needs some additional training to account for this. To help with training I added behavioral cloning, but I'm getting the error "Make sure the model is from the same version of ML-Agents, has the same behavior parameters, and is using the same trainer configuration as the current run."

I used bc in early training phases of this agent and I've tested initializing from these earlier models and training resumes as expected.

**Describe the solution you'd like**
Ability to add in behavioral cloning or GAIL to config file for previously trained agents

**Describe alternatives you've considered**
Future proofing config files by always adding BC and GAIL and setting the strength to 0 if it isn't needed in early training phases.

**Comment by andrewcoh** [comment]
Hi @russellcaughey 

Was this model trained with an earlier version of ML-Agents than the version you are currently trying to use?

**Comment by russellcaughey** [comment]
No, they are both using the same version of ML-Agents

**Comment by andrewcoh** [comment]
I was able to reproduce your issue using our pushblock example environment.  Thank you for raising this, I will try to get a fix out soon. This is being tracked internally as MLA-1376
