### ISSUE TITLE
m_Heuristic.Invoke issue

### ISSUE THREAD

**Issue by bbdscvr** [Unity-Technologies/ml-agents#4481]
This might be a me issue, but I'm really stumped here.

![image](https://user-images.githubusercontent.com/39332667/93027964-b9a54500-f664-11ea-90de-25205edbb7ad.png)

The DecideAction() function is running my heuristic script

![image](https://user-images.githubusercontent.com/39332667/93027992-e35e6c00-f664-11ea-8a07-e77efc812651.png)

The actionsOut is being reset to what it needs to be for the circumstances (last step of Heuristic function inside agent)

![image](https://user-images.githubusercontent.com/39332667/93028009-00933a80-f665-11ea-8db4-9c1abf604f5e.png)

But only ever can return 0,0. 

![image](https://user-images.githubusercontent.com/39332667/93028022-20c2f980-f665-11ea-9170-383de10b9882.png)

I can't get it to use actionsOut as the brain decision. Help?

**Comment by andrewcoh** [comment]
Hi @bbdscvr 

Are you just trying to run the agent in Heuristic mode or is there something else that you're trying to do?  Are you setting the behavior type in the behavior parameters script to "Heuristic only"?

**Comment by bbdscvr** [comment]
Hey Andrew,

Yes heuristic mode, parameters set to heuristic only. I'm creating
demonstrations for the nn via a minimax.

**Comment by bbdscvr** [comment]
![image](https://user-images.githubusercontent.com/39332667/93151899-4b8a7c00-f751-11ea-9d90-cbf256cc491f.png)

**Comment by bbdscvr** [comment]
![image](https://user-images.githubusercontent.com/39332667/93152403-cb651600-f752-11ea-9185-6fced09dc16a.png)
