### ISSUE TITLE
Actuator folder not present when installing from Package Manager

### ISSUE THREAD

**Issue by DanAmador** [Unity-Technologies/ml-agents#4487]
**Describe the bug**
I wanted to explore the available Examples but I  can't use the library whenever I install from the package manager as the `Unity.MLAgents.Actuators` namespace is never downloaded.

**To Reproduce**
Just download the latest version using the unity package manager.

**Screenshots**
![image](https://user-images.githubusercontent.com/7833567/93184735-e462cc80-f73c-11ea-8489-190bad8e6e2b.png)

**Environment:**
- Unity Version: Unity 2019.3.13f
- OS + version: Windows 10
- _ML-Agents version_: 1.0.4 but it also happened with every package version I tried (every single one available except the preview ones)

**Comment by andrewcoh** [comment]
The IActuator interface was added after the 1.3.0-preview release. You'll need to install from the master branch, or wait for 1.4.0-preview, which should be out this week.

Copied from https://forum.unity.com/threads/actuator-missing-from-package.969159/
