### ISSUE TITLE
Type of brain

### ISSUE THREAD

**Issue by Alpslee** [Unity-Technologies/ml-agents#45]
Can't find "internal"

**Comment by Alpslee** [comment]
#if ENABLE_TENSORFLOW
public enum BrainType
{
    Player,
    Heuristic,
    External,
    Internal
}
#else
public enum BrainType
{
Player,
Heuristic,
External,
}
#endif


But how can I enable tensorflow?

**Comment by MarcPilgaard** [comment]
In the guide here on Github it states in order to use the tensorflow model we have to set the brain type to internal, but that option is also missing for me.

**Comment by MarcPilgaard** [comment]
You properly missed the step in the guide that tells you to go into your "Player Settings" and write "ENABLE_TENSORFLOW" into your Scripting Define Symbols.

**Comment by eagleEggs** [comment]
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Making-a-new-Unity-Environment.md

There is also a Tensorflow package to import into Unity.

**Comment by awjuliani** [comment]
Hi @Alpslee,

This section of the Getting Started guide walks through the steps required to enable "Internal" mode: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Getting-Started-with-Balance-Ball.md#setting-up-tensorflowsharp-support
