### ISSUE TITLE
UnityEnvironment does not work. 

### ISSUE THREAD

**Issue by jithin-pal** [Unity-Technologies/ml-agents#4519]
**Describe the bug**
I am running udacity tennis environment program on windows 64bit pc, after the environment line comes, the simulator starts working and after completion it shows an error:

![image](https://user-images.githubusercontent.com/44967770/94372161-33373b80-0119-11eb-827a-a51c24554e64.png)

**To Reproduce**
1. Download udacity DRLND p3 
2. start jupyter notebook
3. Update import to latest (from unityagents --> from mlagents_envs.environment import UnityEnvironment)
4. Run env = UnityEnvironment(filename="Tennis.exe")

**Console logs / stack traces**
  File "j:\ud\2.drlnd\rl_env\ml-agents-master\ml-agents-master\ml-agents-envs\mlagents_envs\rpc_communicator.py", line 97, in poll_for_timeout     
    "The Unity environment took too long to respond. Make sure that :\n"
mlagents_envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
         The environment does not need user interaction to launch
         The Agents' Behavior Parameters > Behavior Type is set to "Default"
         The environment and the Python interface have compatible versions.

**Env:**
- Unity Version: Unity 2020.1f1
- OS + version: Windows 10
- _ML-Agents version_: latest  branch from source
- _TensorFlow version_: 2.3.1
- _Environment_: Tennis

**Comment by dongruoping** [comment]
As the error message suggested, this is likely either a wrong setting in the executable or the version of the executable and python communicator is incompatible.

From your description it looks like you downloaded a pre-built environment executable file but installed the latest ML-Agents package, which have different versions. I would suggest to first make sure you're using ML-Agent environment and python package from the same version.

**Comment by jithin-pal** [comment]
how do you suggest i process so that i can pass this error?

**Comment by dongruoping** [comment]
From what I see in the Udacity repository it's using 0.4.0 which is different than your settings.
This is a deprecated version of ML-Agents, and we don't guarantee it still run.
If it still doesn't work please refer to that repository of how to set up your environment since we no longer support it, thank you.
