### ISSUE TITLE
Forced small window size on Unity builds after training with executables

### ISSUE THREAD

**Issue by HPRIOR** [Unity-Technologies/ml-agents#4520]
After training my agents using an [environment executable](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Executable.md#using-an-environment-executable) all my other builds using the ML-Agents toolkit have their window sizes set to really small - the same size as when using the environment executable to train. Not only are they small but the window sizes cannot be changed or maximised. Previously these builds have defaulted to full screen, with the native resolution of the host computer. 

To reproduce, create a build for a game containing the ml-agents package. Create another build and use it for training. Now open the initial build, it it should have the same window size as the build used for training.

![image](https://user-images.githubusercontent.com/56833147/94375069-d16ed580-0108-11eb-8c83-7f793ef3240d.png)
This is the fixed and default size for my build after using an executable for training.

Unity Version: Unity 2019.4.0f1
OS + version: Windows 10
ML-Agents version:
ml-agents: 0.18.0,
ml-agents-envs: 0.18.0,
Communicator API: 1.0.0,
TensorFlow version: TensorFlow: 2.2.0
Environment: Custom environment

**Comment by dongruoping** [comment]
When starting training with the CLI, you can specify the window size in command line like `--width=1280 --height=720` to make the window bigger. There is also a checkbox in the PlayerSettings called `resizable window` that allows for the window size to be reshaped manually, please see [this doc](https://docs.unity3d.com/Manual/class-PlayerSettingsStandalone.html).
Although it is impossible to change the window size while the game is frozen/updating.
