### ISSUE TITLE
Accessing Academy.Instance when not playing leaks AcademyFixedUpdateSteppers and EnvironmentStep gets called multiple times per FixedUpdate

### ISSUE THREAD

**Issue by Phong13** [Unity-Technologies/ml-agents#4521]
**Describe the bug**
Any code that accesses "Academy.Instance" when not "playing" will cause a new hidden gameobject to get created with an AcademyFixedUpdateStepper component. There can easily be many of these objects in a scene. THEY ALL STEP THE ENVIRONMENT!!!. 

It is easy to do this. For example I often test code by writing a context menu function like this:

    _[ContextMenu("Do Some Validation")]
    public void ValidateSomeStuff()
    {
        ...
        Academy myAcademy = Academy.Instance;
        ...
    }_

Every time I validate using the "ContextMenu" a new, hidden, AcademyFixedUpdateStepper gets created.

**To Reproduce**
Add this to a MonoBehaviour and fire it several times when not in Playmode. Each time it is fired a new AcademyFixedUpdateStepper is created:

    _[ContextMenu("Do Some Validation")]
    public void ValidateSomeStuff()
    {
        Academy myAcademy = Academy.Instance;

        // Count the number of hidden Fixed Update Steppers
        Transform[] ts = (Transform[])Resources.FindObjectsOfTypeAll(typeof(Transform));
        int num = 0;
        foreach (var t in ts)
        {
            if (t.GetComponent<AcademyFixedUpdateStepper>() != null)
            {
                num++;
            }
        }

        Debug.Log("Found: " + num + " hidden fixed update steppers");
    }_

Also add a static variable to Academy:

_public static int numTimesEnvironmentStepIsStepped;_

And increment this variable in "EnvironmentStep". Print it out in FixedUpdate.

**Console logs / stack traces**

**Screenshots**

**Environment (please complete the following information):**
- Unity 2019.4
- Windows 10
- Release 6
- 1.7.1
- Any environment

**Comment by dongruoping** [comment]
In your code, a new Academy instance is instantiate every time the function is called by saying `Academy myAcademy = Academy.Instance;`, and that's why you ended up having multiple Academy instances. 

The Academy is initialized when the first time being accessed, so you should be able to call it directly instead of first creating your own `myAcademy`. Please refer to [this doc](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design.md) for example of accessing Academy.

**Comment by Phong13** [comment]
Hi dongruoping,

The problem is not "multiple Academy instances". There is actually only one Academy instance. The problem is that the training scene accumulates multiple, hidden GameObjects with the "AcadmeyFixedUpdateStepper" component on them (when Academy.Instance is accessed not-in-playmode). These hidden gameobjects are saved when the scene is saved. When the scene is trained, the environment is stepped multiple times per environment-step. The scene becomes untrainable, corrupt. It is fairly easy to repair... if you know that these extra, hidden AcadmeyFixedUpdateStepper's have been serialized in the scene. 

This bug is very serious because the training scene appears to be working correctly. There are no error messages in the Unity console or the Python console. Builds can be created. But the TensorBoard results are terrible and never improve no mater what you change. 

IMO accessing (when not in playmode):

Academy.Instance

Should not leak GameObjects with the "AcadmeyFixedUpdateStepper". There were 11 AcadmeyFixedUpdateStepper's in my scene.

**Comment by dongruoping** [comment]
Thanks for more detailed explanation, and I was able to reproduce this following your steps. Thanks for reporting this.
This is being tracked internally as MLA-1410. We will try to get a fix out soon.

**Comment by Phong13** [comment]
Thanks :)

**Comment by dongruoping** [comment]
This issue has been fixed in #4532 . Thanks for reporting this!
