### ISSUE TITLE
Webgl build error in Unity 2020.2.0a21 alpha 

### ISSUE THREAD

**Issue by anantsachin** [Unity-Technologies/ml-agents#4536]
**Describe the bug**
In Unity 2020.2.0a21 if you build Webgl project it will not play in your browser.

**Steps to Aviod the bug*
1. Go to 'player setting in project setting'
2. Change compression format from 'Gzip' or 'brotli' to 'disabled'
3. Build your project.
4.It will work succesfully

**Comment by hvpeteet** [comment]
Hi is this related to ml-agents or is this just a Unity bug? I see https://issuetracker.unity3d.com/issues/linux-editor-empty-webgl-project-fails-building?_ga=2.56422444.601106834.1601925801-1907819386.1597705242 for this alpha version.

**Comment by anantsachin** [comment]
Hi, Its an bug.

**Comment by hvpeteet** [comment]
Thanks for the confirmation.
