### ISSUE TITLE
Enable custom measure for completion_criteria for curriculum learning

### ISSUE THREAD

**Issue by ShirelJosef** [Unity-Technologies/ml-agents#4585]
**Is your feature request related to a problem? Please describe.**
Using curriculum learning for self-play, I find it troublesome to use reward/progress as measure for completion criteria. Reward often does not reflect learning as it fiddles around 0 for symmetric self-play games with +1 -1 reward.

**Describe the solution you'd like**
I would like to be able to define a measure for the completion_criteria of a lesson in curriculum learning. For example number of kills, percentage of accuracy and so. It can even be limited to [0,1] range.

**Describe alternatives you've considered**
Alternative solution is to define a very large number for team change and to write my own curriculum which gets statistics for the learning team (as the current learning team is not accessible to Academy instance). However, this solution is not really using the unity lessons system.

**Comment by vincentpierre** [comment]
Hi, I logged this request and we will prioritize appropriately. 
The current succcess_criteria we use are reward and progress and these are easy to access in Python. 
How do you think we should implement this feature? We would need to communicate custom data between C# and Python and we would probably need to create a new API to do so. Any suggestions?

**Comment by ShirelJosef** [comment]
I think that because need_increment in ml-agents/mlagents/trainers/settings.py cannot be changed by user and the user can't supply his own custom need_increment there should be a general custom value "lesson_objective_completed" between [0,1] which is calculated over the episode.
In each step the user provide a value "increment_custom_lesson_objective" between [0,1] which like reward is accumulated over the episode, to a maximum of 1.
Then like reward it can be averaged over several episodes and you can decide the threshold of lesson "pass" between [0,1] which is needed to pass the lesson.

From my understanding the only way is to add another field in 
ml-agents-envs/mlagents_envs/communicator_objects/agent_info_pb2.py
for "increment_custom_lesson_objective"

I also want to add why this is needed:
Lets assume we have 2 spaceships, and the objective is to shoot the other spaceship. (+1 for kill, -1 for getting killed)
However, the spaceship can hit obstacles and crash and then it gets -1 reward and opponent +1.
The lessons should not increment when opponent crashes but only when your spaceship correctly shoot opponent and therefore the reward criteria is somewhat misleading.
