### ISSUE TITLE
Neuroevolution

### ISSUE THREAD

**Issue by rdekleijn** [Unity-Technologies/ml-agents#4597]
The ml-agents README.md mentions neuroevolution next to RL and imitation learning as a training method. However, I haven’t been able to find an implementation of neuroevolution (e.g. NEAT) in ml-agents. Is this implemented and am I just missing something, or is this planned for a later release? Or does ml-agents just provide a framework in which I should implement it myself? It’s briefly mentioned [here](https://github.com/Unity-Technologies/ml-agents/pull/440#issuecomment-372723256), but wondering if there are any updates. Thanks!

**Comment by chriselion** [comment]
There are no implementations of this in ml-agents. The intent of the wording there was that you could use the [low-level python interface](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Python-API.md) to implement it yourself (but I don't like the wording personally).

**Comment by chriselion** [comment]
I reworded that section of the readme to clear up the ambiguity: https://github.com/Unity-Technologies/ml-agents/pull/4603
Thanks for pointing it out!
