### ISSUE TITLE
Active Object Tracking Environment Contribution

### ISSUE THREAD

**Issue by kirstenrichardson** [Unity-Technologies/ml-agents#4599]
Hello,

Was just taking a look at the contribution guidelines and it recommends posting to the issues page. 

I have just finished working on a custom environment involving two cubes. One, the target, moves around the platform randomly. The second, camera-fitted cube moves in response to applications of force and torque. The goal is to have the agent cube find and actively track the target cube, with the optimal behaviour being that the agent is set back from the target a little but following in it's wake, with the same horizontal positioning and facing direction. 

I have achieved successful tracking with both vector and visual observations, a discrete action space, the ml-agents implementation of ppo, and a straightforward reward function.

Before I move onto something else just wondered whether this would be a welcome addition to the example environments? There are problems surrounding navigating toward a static goal, but none that address following a moving target. If not, no worries, it was just a first step exercise within a larger project, but if so I will take the time to neaten everything up and make the cubes, platform etc consistent with the ML-Agents design. 

Thanks 

![Animated GIF-downsized_large](https://user-images.githubusercontent.com/36848785/96986724-f09b3000-1519-11eb-8c04-f6b0ca050721.gif)

**Comment by unityjeffrey** [comment]
thanks @kirstenrichardson - this is pretty neat!  unfortunately, we currently are not accepting environment contributions at this time.  However, you are correct in that we currently do not have an environment that tracks a moving target.  Would you be interested to put a personal repo and sharing with the community [forum](https://forum.unity.com/forums/ml-agents.453/)?

**Comment by kirstenrichardson** [comment]
@unityjeffrey yea absolutely, that's all I was checking, it was so close in design to existing environments I didn't want to not offer

**Comment by kirstenrichardson** [comment]
@unityjeffrey just wanted to check the use of the AgentCube_Blue and AgentCube_Purple prefab in this project https://github.com/kirstenrichardson/CubeTrack is ok before the associated article goes up on Towards Data Science?

**Comment by unityjeffrey** [comment]
hi @kirstenrichardson - just to confirm, are you asking in terms of licensing / branding? or something more specific techincally?

**Comment by kirstenrichardson** [comment]
@unityjeffrey licensing - purely the use of the colours, headband etc. - can change if would prefer. Thanks

**Comment by unityjeffrey** [comment]
@kirstenrichardson got it!  you are def free to use any of the colors, agents, and reference ML-Agents, the ArXiv paper and Unity.  

The only small change is the remove the Unity logo on the CubeTrack image (Unity prohibits use of the logo outside of company uses).  

I also read through your article (looks great!).  In the article, its okay to keep the image with the logos on the smaller examples (since that came from our repo and is licensed as such where you can use it).  Same comment as above, any of the images you generate with CubeTrack, if you can remove the logo.

Do let us know when it goes up on Towards Data Science.

**Comment by kirstenrichardson** [comment]
@unityjeffrey awesome will do, thanks for responding

**Comment by unityjeffrey** [comment]
hi @kirstenrichardson - would you be interested in being an alpha user for our cloud training service (specifically for the 2nd bullet on forums around visual encoder using resnet)? If so, I can provide some more details. can you shoot me an emai to jeffrey@unity3d.com?
