### ISSUE TITLE
Some rewards are missing when using frame skip.

### ISSUE THREAD

**Issue by SSS135** [Unity-Technologies/ml-agents#46]
When `Academy.frameToSkip > 0`  only rewards from non-skipped frames are sent to python. Instead rewards of skipped frames should be summed with last reward. Current behaviour may make some games unbeatable. 
For example, imagine if Montezuma's Revenge would be replicated in unity. Rewards in this game are very sparse, like 999 of 1000 frames have zero reward. Using current implementation frame skip, non-zero reward will be skipped most of time, and AI won't be able to beat the game at all.

**Comment by awjuliani** [comment]
Hi @SSS135,

When using frameskip, you can add to the reward variable, rather than set. This enables rewards to accumulate over the course of the skipped frames, rather than being rewritten by the last one.

**Comment by SSS135** [comment]
Thanks! This should work.
