### ISSUE TITLE
[discussion] grpc communication design choice

### ISSUE THREAD

**Issue by RachithP** [Unity-Technologies/ml-agents#4600]
Hi,

I've little knowledge of network programming. So, these questions might be basic.

I'd like to know why the current design for grpc server and client communication in the toolkit is as follows: In my current understanding, when you start training, the grpc server is on the python side(localhost/any system) and clients are on the unity side.

I've two simple questions:
- Why not have a grpc server on the Unity side and clients on the python side(eg. on a local system).
- Also, why use a single service and single rpc method? Are there any drawbacks to this that you currently see or foresee?

I've been thinking about it and not able to understand the reasoning. Again, I'm new here, so I could be missing the obvious. If someone can think of any possible pros and cons to the aforementioned questions, please do share your thoughts.

If my understanding is wrong, please correct me. Thanks!

Cheers!
[discussion]

PS: I'm not sure if I can edit labels!!

**Comment by chriselion** [comment]
Hi, sorry, I didn't have a chance to respond to your forum post until now. That's a better venue for this sort of discussion, so I'm going to close this issue.

**Comment by chriselion** [comment]
Forum post: https://forum.unity.com/threads/ml-agents-grpc-design-choice.992710/

**Comment by RachithP** [comment]
Thanks for your reply @chriselion !
