### ISSUE TITLE
Onnx model failing to import due to ConstantOfShape

### ISSUE THREAD

**Issue by grimli333** [Unity-Technologies/ml-agents#4609]
**Describe the bug**
I have switched over to using PyTorch instead of TF1 and the training seems to be working fine.  However, when I copy the resulting model into my Unity project, it fails to import the file, complaining that ConstantOfShape is an unknown type.
I have tried with the latest official package and with an imported version of the latest code on github as of today (Oct27-2020).

**To Reproduce**
1. Copy this .onnx file into a Unity project using the latest ML Agents package.
2. Allow Unity to attempt to import the model.
3. See error

**Console logs / stack traces**
Please wrap in [triple backticks (```)](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make it easier to read.
```
Probing Unity.Barracuda.BurstBLAS
Loaded: Unity.Barracuda.UnsafeMatrixBlockMultiplyUnrolled8xhJob
Baked node 42 into constant of shape (1, 1, 1, 1, 1, 1, 1, 2) and values: 0 -1 
OnnxImportException: Unknown type ConstantOfShape encountered while parsing layer 46.

Unity.Barracuda.ONNX.ONNXModelConverter.Err (Unity.Barracuda.Model model, System.String layerName, System.String message, System.String extendedMessage, System.String debugMessage) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:1511)
Unity.Barracuda.ONNX.ONNXModelConverter.ConvertOnnxModel (Onnx.ModelProto onnxModel) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:1230)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:82)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:60)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@1.1.2-preview/Barracuda/Editor/ONNXModelImporter.cs:44)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at <67055f1be3654e2a987254d5437ee5b8>:0)
Asset import failed, "Assets/ML-Agents/Brains/GoBC.onnx" > OnnxImportException: Unknown type ConstantOfShape encountered while parsing layer 46.
```

**Environment (please complete the following information):**
- Unity Version: Unity 2020.1.6f1
- OS + version: Windows 10
- _ML-Agents version_: latest from github
- _Torch version_: 1.6.0
- _Environment_: Custom (2 continuous actions, 10 observations + 3d ray perception sensor with 5 rays in each direction.) Observation Shapes: [ 33 ], [ 10 ].  

Attaching zip of the .onnx file that results in this error.

[GoBC.zip](https://github.com/Unity-Technologies/ml-agents/files/5447754/GoBC.zip)

**Comment by chriselion** [comment]
Hi @grimli333 - I think we just fixed this last night. Can you make sure you have up to commit 72492272ef6e749dd43f0c23a7b4176bb23d2af4 (PR https://github.com/Unity-Technologies/ml-agents/pull/4608)?

**Comment by grimli333** [comment]
Thank you for your help.  I was pretty sure I pulled the latest from master this morning, but I was uncertain enough that I went ahead and pulled again.

What fortuitous timing that this bug would be fixed the very day I encounter it!  After training a new model with the latest code, it imports properly.

Once again, thanks for your prompt attention.

**Comment by chriselion** [comment]
Cool, glad that fixed it. The bug was only introduced late last week, so you just had bad timing :)
