### ISSUE TITLE
TestTextureSensor.cs(55,33): error CS1061: 'ObservationWriter' does not contain a definition for 'WriteTexture'

### ISSUE THREAD

**Issue by mehrdad995gta** [Unity-Technologies/ml-agents#4624]
Just Imported the ML-Agents folder from the Assets folder into Unity and I got this Error:
Assets\ML-Agents\TestScenes\TestCompressedTexture\TestTextureSensor.cs(55,33): error CS1061: 'ObservationWriter' does not contain a definition for 'WriteTexture' and no accessible extension method 'WriteTexture' accepting a first argument of type 'ObservationWriter' could be found (are you missing a using directive or an assembly reference?)

I have the latest version of ml-agents 1.5.0 preview installed through the Package Manager.

**Comment by unityjeffrey** [comment]
hi @mehrdad995gta - when you imported ml-agents from the assets folder, which version in ML-A are you using?

**Comment by mehrdad995gta** [comment]
> hi @mehrdad995gta - when you imported ml-agents from the assets folder, which version in ML-A are you using?

hi @unityjeffrey I was using ml-agents 1.5.0 preview, installed from the package manager.

**Comment by vincentpierre** [comment]
Hi @mehrdad995gta 
The code on github is a later version on ML-Agents compared to the version on the Unity Package Manager. To make it work, you will need to get the `Project` folder that corresponds to the [version of the package](https://github.com/Unity-Technologies/ml-agents/tree/com.unity.ml-agents_1.5.0). The corresponding github tag is `com.unity.ml-agents_1.5.0`
