### ISSUE TITLE
Behaviour vs Behavior

### ISSUE THREAD

**Issue by 18goldr** [Unity-Technologies/ml-agents#4625]
**Is your feature request related to a problem? Please describe.**
This is not related to anything broken, just an annoyance. In the python side, its spelled behavi**or**. In the Unity side, its spelled behavi**our**. This isn't the biggest issue but it's kind of annoying and I sometimes forget which one is which.

**Describe the solution you'd like**
Switch every word that is "Behaviour" to "Behavior" or vice versa.

**Describe alternatives you've considered**
Not really any alternatives to this. 

**Additional context**
This just seems like bad practice to use multiple spellings of the same word.

**Comment by unityjeffrey** [comment]
hi @18goldr - thank you for raising this and certainly understand the annoyance.  this was primarily due to the international backgrounds and diversity across our community and core team members.

i have a ticket internally to see if we can resolve this in a straightforward and clean way.

**Comment by chriselion** [comment]
Hi @18goldr,
The Unity coding style guide (which I can't find a public reference to, so you'll just have to trust me) says:

> Spell words using correct US-English spelling. Note that there are a few legacy exceptions that use GB-English that we must preserve, but do not add new ones.

In particular, `MonoBehaviour` is one of those legacy exceptions. We should be using "Behavior" everywhere else in this repo.

Are there any other "Behaviour"s in the repo that you've found? The only ones I found were some comments in a test:
https://github.com/Unity-Technologies/ml-agents/blob/d4e0daeaea58f9610ac4a20dfaec157093a274d8/gym-unity/gym_unity/tests/test_gym.py#L143
(and another one in the same file).
