### ISSUE TITLE
My barracuda model(NN model) don't have input name

### ISSUE THREAD

**Issue by gkhj0516** [Unity-Technologies/ml-agents#4628]
Hi

I have h5 file and converted to barracuda model.
But, I can't find input name of NN model in unity.
[h5 model.zip](https://github.com/Unity-Technologies/ml-agents/files/5505942/h5.model.zip)

What can I do? Help me please

![image](https://user-images.githubusercontent.com/59754664/98459095-b2b92f80-21da-11eb-90f6-728a02098eec.png)

**Comment by unityjeffrey** [comment]
hi @gkhj0516 - unfortunately, we do not debug models generated outside of ML-Agents.  Please refer your questions to the Barracuda issues page [here](https://github.com/Unity-Technologies/barracuda-release) or the barracuda [forum](https://forum.unity.com/forums/barracuda.500/)
