### ISSUE TITLE
Get list of observations ->  make m_Observations  public get

### ISSUE THREAD

**Issue by markste-in** [Unity-Technologies/ml-agents#4634]
**Is your feature request related to a problem? Please describe.**
I often haven the issue that I want to troubleshoot the learning behaviour by inspecting the observations that I added with **sensor.AddObservation** in CollectObservations(VectorSensor sensor). Right now I would need to add all observations manually to a list or something else to output / troubleshoot them later on. 

**Describe the solution you'd like**
The class VectorSensor in Unity.MLAgents.Sensors has already a list with all observations called:
`private List<float> m_Observations;`
It would be nice if we can change the private to a public get. That would give direct access to the observation without the need of handcrafting a workaround.
`public List<float> m_Observations { get; private set; }`

**Describe alternatives you've considered**
None

**Additional context**
Even though the debugger gets you access to everything, it gives you just a snapshot in time and you have to manually click through every "hit" -> not really a solution especially if you have multiple agents

**Comment by Ihsees** [comment]
Does `Agent.GetObservations()` help you? 
[Changelog 1.1.0-preview](https://github.com/Unity-Technologies/ml-agents/blob/master/com.unity.ml-agents/CHANGELOG.md#comunityml-agents-c-20)

**Comment by markste-in** [comment]
ahh yes. Does exactly what I need... 
I don't know how I missed that.

Thanks!
