### ISSUE TITLE
save and resume from the best performing checkpoint

### ISSUE THREAD

**Issue by markste-in** [Unity-Technologies/ml-agents#4640]
**Is your feature request related to a problem? Please describe.**
Right now (if I don't miss anything) you can keep several different checkpoints during training but there is no way to save/resume the best checkpoint. If you run long training sessions you have to increase the "keep_checkpoints" number high enough in case the learning collapses and hope that one of them captured a time where the model was close to its best performance.

**Describe the solution you'd like**
It would be nice if either "mlagents-learn" or the training file gets an option to always save (resume from) the best checkpoint

**Describe alternatives you've considered**
Increase keep_checkpoints and "hope"?

**Comment by dongruoping** [comment]
Thanks for raising this, this is definitely one of the things that's on our list of features to add.
As you mentioned, the fastest temporary solution would be increasing the "keep_checkpoints" in config and track the best one with the training logs. 
I'll bring this up with the team and prioritize it when possible.

Similar request has been logged as MLA-553 internally.
