### ISSUE TITLE
Ability to launch a unity game and connect ml_agents env to it

### ISSUE THREAD

**Issue by armando-fandango** [Unity-Technologies/ml-agents#4650]
**Is your feature request related to a problem? Please describe.**
I am frustrated that ml-agents-env cant connect to a running binary game, it can only connect to a running editor.

**Describe the solution you'd like**
I run the binary game on port n and then tell the ml-agents-env to connect to the running binary game on port n

**Describe alternatives you've considered**
couldnt find any.

**Additional context**

from the code:

```
 # If the environment name is None, a new environment will not be launched
        # and the communicator will directly try to connect to an existing unity environment.
        # If the worker-id is not 0 and the environment name is None, an error is thrown
        if file_name is None and worker_id != 0:
            raise UnityEnvironmentException(
                "If the environment name is None, "
                "the worker-id must be 0 in order to connect with the Editor."
            )
        if file_name is not None:
            try:
                self._proc1 = env_utils.launch_executable(
                    file_name, self._executable_args()
                )
            except UnityEnvironmentException:
                self._close(0)
                raise
        else:
            logger.info(
                f"Listening on port {self._port}. "
                f"Start training by pressing the Play button in the Unity Editor."
            )
        self._loaded = True
```

I think here lies the problem that if filename is not supplied then it assumes that we want to connect to the editor. This code needs to be changed to allow to connect to running games.

**Comment by dongruoping** [comment]
Yes you're right, our current settings is that you have to specify `--env=PATH_TO_FILE` in order to train with binary build, otherwise it will connect to the editor.

Could you tell us a bit more about why that doesn't work for your case? Is there some specific reason you have to keep the binary running and then launch the training instead of letting the training session launch the game?

**Comment by armando-fandango** [comment]
Use case 1: I am working on a remote server where the training code is in notebooks, accessed by serverhost.com/training.ipynb. I launch a large game from an ssh session to remote server in the background with & and now I can continue interacting with that game from the python notebook, whenever I want to start from beginning, I can call env.reset()

Use case 2: The game is a huge simulation that takes several minutes to init/start but only seconds to reset(). So now if I am experimenting and fixing bugs in code, every time I restart my notebook kernel, I have to recreate the game as the env would launch the game. However if the game is running separately, then I can keep resetting the unity env and keep resetting my jupyter notebook kernel, without shutting down the large simulation and restarting it.

**Comment by dongruoping** [comment]
Thanks for the explanation, that does sound like a fair use case.
I'll bring it up with the team and see how we can incorporate this feature.

**Comment by dongruoping** [comment]
Hi, 

We're still looking into this and see if we can do this with our environment, but theoretically it should work as is.
You just need to put your game on a port and specify that port in python.

One thing you should be careful about is the initialization of the Academy in your environment. You should make sure your game is actively listening on the port when you launch python.
For example our examples environments will try to connect as soon as they start, then fail to connect and start running inference. In that case the python thread has no way to connect to the game.

Besides that we'll be looking more into this.

**Comment by armando-fandango** [comment]
@dongruoping Thanks, I will work with our Unity Developers to look into this aspect. Highly appreciate.
