### ISSUE TITLE
ONNX - ArgMax support

### ISSUE THREAD

**Issue by nauutilus** [Unity-Technologies/ml-agents#4657]
**Is your feature request related to a problem? Please describe.**
I'm trying to import an ONNX model but I can not do this because Barracuda doesn't support ONNX ArgMax operator

**Describe the solution you'd like**
Please add support for ArgMax operator

**Comment by dongruoping** [comment]
Hi,

Could you post this on the [barracuda github repo](https://github.com/Unity-Technologies/barracuda-release/issues)? This repo is specifically for ML-Agents, thank you.

**Comment by nauutilus** [comment]
I open it here because this is what [your documentations suggest](https://docs.unity3d.com/Packages/com.unity.barracuda@1.2/manual/SupportedOperators.html). 

![Screenshot 2020-11-17 at 10 49 02](https://user-images.githubusercontent.com/4004883/99374212-a6139600-28c2-11eb-9cf8-1cf93db51cec.png)

**Comment by chriselion** [comment]
@nauutilus Just to follow up, the barracuda team will be updating those instructions in their next release.

**Comment by nauutilus** [comment]
Thank you @chriselion
