### ISSUE TITLE
GridWorld: command line and use of expert demo

### ISSUE THREAD

**Issue by Dastyn** [Unity-Technologies/ml-agents#4671]
Hi There!

I'm a bit puzzled by GridWorld learning: the GridWorld.nn graph model provided with the example works perfectly.
But I'm absolutely not able to reproduce the same brain!
I tried for a few days with PPO and SAC, and I also added Gail and BC in configuration, but with no success at all.
The same with --num-envs up to 8 (the environment was generated with 1 agent, up to 8, with or without the agent using RenderTexture - but it has no impact as expected).

I do not even understand why the ExpertGrid.demo was present in the GridWorld folder, but not referenced to into the SAC and PPO yaml files.
I let the learning work for 500k and more steps. With no concluding results (in some cases, the mean reward vanished definitively after a while, the same for Beta and Entropy accordingly).

Please could you give some hints to:
- define the best (?) command line "mlagents-learn" which permitted to generate the so well performing GridWorld.nn provided in the GridWorld folder?
- tune the corresponding yaml configuration files? (what are the good parameters for BC and Gail (+ Curiosity) to make it learn correctly!)

The versions used currently:
  ml-agents: 0.21.1,
  ml-agents-envs: 0.21.1,
  Communicator API: 1.2.0,
  TensorFlow: 2.2.0
ML Agents Package version 1.6.0-preview

These hints/instructions could be added to the packages (at least as kind of regression tests?).
Thanks in advance for any help!

**Comment by andrewcoh** [comment]
Hi @Dastyn 

I'm not having any trouble retraining our GridWorld environment on the master branch. It is possible that you just got unlucky with a random seed. Are you running with the default `.yaml' file for GridWorld?

**Comment by Dastyn** [comment]
Hi @andrewcoh,

Yes, the distributed GridWorld yaml was used.
I tried, for hours, several times then with different seeds (using a GPU GTX 1080).

Could you be so kind to give me more details on the number of steps it required on your side,
and how many parallel environments (num-envs) were specified? Of course, it was certainly a different workstation, but it will help me figure what can be, and cannot be, done on my side in the hope to obtain +/- the same distributed .nn!!

Thanks in advance for that.

**Comment by andrewcoh** [comment]
Can you try just running `mlagents-learn config/ppo/GridWorld.yaml --force` and train in-editor?

**Comment by Dastyn** [comment]
Hello @andrewcoh,

I'll try this (once more!).

Indeed, so far, I tried with e.g.:
`mlagents-learn config/GridWorld.yaml --env gw.exe --run-id gw013 --force --no-graphics` 
in order to speed up the training.
But, in in-editor mode, it might be even much longer, AFAIK.

=> Then do you mean that it could be more efficient to do the learning through in-editor mode (i.e. visual obs could depend on "graphics" duly displayed on the screen)? 
Or is it just a way to visually check on my side that learning is evolving correctly through steps?

Thanks for your help.
