### ISSUE TITLE
Mecanim IK delays with observations

### ISSUE THREAD

**Issue by asolano** [Unity-Technologies/ml-agents#468]
Greetings,

we are experiencing some strange issues when combining observations and Mecanim avatars. 

We are using an agent Reset method to make the avatar look at the camera, setting a target transform variable. The avatar has a script with OnAnimatorIK calling SetLookAtPosition and SetLookAtWeight to actually update the mesh. When the animator is set to Normal update mode there is a (variable) delay until the head actually turns. 

Here is the observation after the reset:

![side](https://user-images.githubusercontent.com/2702742/37392382-55c0672e-27b1-11e8-9706-614b780cf02f.png)

And this is the expected result:

![front](https://user-images.githubusercontent.com/2702742/37392391-59fc38f4-27b1-11e8-8de4-fb430e517613.png)

When the animate mode is set to Animate Physics, the eyes and mouth meshes are updated properly but the rest of the mesh still lags:

![eyesout](https://user-images.githubusercontent.com/2702742/37392539-c0c11848-27b1-11e8-954d-0707b64265be.png)

This is only visible when rendering the observations, the scene runs as expected on the editor and as a standalone build.

Our current assumption is that on Normal mode the IK solver takes place after all the physics updates, where the Academy runs, so the observations show for a while the state before the complete mesh update. On Animate Physics the IK update would happen on the physics update phase too, so the observations show an incomplete update of the bones instead.

Any hints are very much appreciated.

Alfredo

**Comment by r-lipton** [comment]
I also have these problems.

**Comment by r-lipton** [comment]
Any news @asolano ?

**Comment by asolano** [comment]
Hi, @r-lipton 

More investigation pointed at the SkinnedMeshRenderer component being updated by Unity in LateUpdate, so the skin is always behind the bones, and only renders correctly at the end of a complete frame.

There seems to be no option to change it to FixedUpdate, so we ended up "fixing" it by changing the FixedUpate() method of Academy.cs to Update(). Training is slower, and there is still a frame of lag, but at least the models are learning again.

Hope it helps!

Alfredo

**Comment by unityjeffrey** [comment]
thanks for filing.  we've logged this bug and will report back once we have a resolution.
