### ISSUE TITLE
The documentation for the Curriculum settings is hard to find

### ISSUE THREAD

**Issue by Phong13** [Unity-Technologies/ml-agents#4684]
**Describe the bug**
There used to be a page documenting the curriculum settings in the config.yaml file but I can't find it anymore.

I am expecting the documentation for curriculum settings to be on the page "Training Configuration File". https://github.com/Unity-Technologies/ml-agents/blob/release_10_docs/docs/Training-Configuration-File.md The settings do go in this file. However there existence is not mentioned on that page, and there is no link.

Also looked in the page "Designing a Learning Environment". https://github.com/Unity-Technologies/ml-agents/blob/release_10_docs/docs/Learning-Environment-Design.md. This page has a paragraph about Environment Parameters and Curriculum learning but no link to the documentation.

**To Reproduce**

**Console logs / stack traces**

**Screenshots**

**Environment (please complete the following information):**
Release 10

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by andrewcoh** [comment]
Thank you for pointing this out. I will add links to the documentation here https://github.com/Unity-Technologies/ml-agents/blob/release_10_docs/docs/Training-ML-Agents.md#environment-parameters where appropriate.

**Comment by Phong13** [comment]
Thanks Andrew 👍
