### ISSUE TITLE
The type or namespace name 'Actuators' does not exist in the namespace 'Unity.MLAgents' 

### ISSUE THREAD

**Issue by QuXinghuaNTU** [Unity-Technologies/ml-agents#4689]
**Describe the bug**
Always met the error of 
"http://assets/ML-Agents/Examples/Reacher/Scripts/ReacherAgent.cs. The type or namespace name 'Actuators' does not exist in the namespace 'Unity.MLAgents' (are you missing an assembly reference?)

** The steps of using ML-agent examples.
1. Create a Project and install MLagents in the package manager.
2. Download the ml-agents-latest release.
3. Copy Assests/ML-Agents into the created project.

Then I met the error shown above

**Comment by chriselion** [comment]
Hi,
What version of the `com.unity.ml-agents` package are you using? I believe it's 1.0.6 (or another 1.0.x version), but the IActuator interface was added in the [`1.4.0-preview`](https://github.com/Unity-Technologies/ml-agents/releases/tag/release_7) package.

If that's the case, you should either:
* Update the package to a 1.4.0-preview or later (depending on your Unity version, you may need to change some package manager settings to be able to see preview packages).
* Get the examples from a tag that corresponds to the 1.0.x package, for example [`com.unity.ml-agents_1.0.6`](https://github.com/Unity-Technologies/ml-agents/tree/com.unity.ml-agents_1.0.6)

**Comment by QuXinghuaNTU** [comment]
> Hi,
> What version of the `com.unity.ml-agents` package are you using? I believe it's 1.0.6 (or another 1.0.x version), but the IActuator interface was added in the [`1.4.0-preview`](https://github.com/Unity-Technologies/ml-agents/releases/tag/release_7) package.
> 
> If that's the case, you should either:
> 
> * Update the package to a 1.4.0-preview or later (depending on your Unity version, you may need to change some package manager settings to be able to see preview packages).
> * Get the examples from a tag that corresponds to the 1.0.x package, for example [`com.unity.ml-agents_1.0.6`](https://github.com/Unity-Technologies/ml-agents/tree/com.unity.ml-agents_1.0.6)

Hi Chriselion,

Greeting. 
Thanks for the quick response. Following your answer, it works not. 

For anyone who might see the same problem, my solution is:
1. In package manager->advanced, choose show preview packages. Then install ML Agents 1.4.0.
2. Download the corresponding 1.4.0 package from https://github.com/Unity-Technologies/ml-agents/releases/tag/release_7

**Comment by DanielLSM** [comment]
> Hi,
> What version of the `com.unity.ml-agents` package are you using? I believe it's 1.0.6 (or another 1.0.x version), but the IActuator interface was added in the [`1.4.0-preview`](https://github.com/Unity-Technologies/ml-agents/releases/tag/release_7) package.
> 
> If that's the case, you should either:
> 
> * Update the package to a 1.4.0-preview or later (depending on your Unity version, you may need to change some package manager settings to be able to see preview packages).
> * Get the examples from a tag that corresponds to the 1.0.x package, for example [`com.unity.ml-agents_1.0.6`](https://github.com/Unity-Technologies/ml-agents/tree/com.unity.ml-agents_1.0.6)

If thats the case, would be amazing to update the tutorials that using using Unity.MLAgents.Actuators; like the second one on the documentation
