### ISSUE TITLE
Curriculum training isn't moving to next lesson

### ISSUE THREAD

**Issue by UsaidPro** [Unity-Technologies/ml-agents#469]
Hello! I've been trying to create a grid-based "critter world" where a agent learns to navigate to food. I'm trying to use curriculum-based learning to improve the learning process, where the grid starts small with only a single food and expands to having more food/larger grid.

Here is my curriculum file:
```
{
    "measure" : "reward",
    "thresholds" : [0.6, 0.7, 0.75, 0.75, 0.75],
    "min_lesson_length" : 2,
    "signal_smoothing" : true, 
    "parameters" : 
    {
        "gridSize" : [5, 7, 7, 9, 11, 15],
        "maxFood" : [1, 1, 2, 2, 3, 3]
    }
}
```
The file is at location: C:/Users/usaidpro/Documents/GitHub/ml-agents/python/curricula/critter_world.json

I fed in the direct filepath to the ppo algorithm (setting curriculum_file to the filepath) and trained, yet I don't see the lesson changing in Tensorboard.
![image](https://user-images.githubusercontent.com/7944753/37415551-b16747ba-2779-11e8-87f0-8946ea328632.png)

According to the curriculum file, it should have moved to the next lesson at 20k, yet doesn't switch for all 500k iterations. The max_steps I have is 200 (a bit high, considering it starts at a 5x5 grid). 

What could cause this?

**Comment by MarcoMeter** [comment]
Hi @UsaidPro 
the reward measure does not refer to the cumulative reward. It is the total amount of rewards, which is signaled throughout one entire episode.

**Comment by vincentpierre** [comment]
Do you have an Academy max step in your scene ? The lesson change can only happen at an academy reset.

**Comment by UsaidPro** [comment]
I do have an Academy max step of 200 (the agent's max step is 100). There are multiple agents playing (same brain) on different grids to accelerate learning. The "Reset on Done" box is checked for the agents - which seems to call the agent's reset. I don't see anything that would prevent the academy from resetting, unless an agent reset restarts the step timer for the academy.

**Comment by UsaidPro** [comment]
All my academy reset has:
```
public override void AcademyReset()
{
        gridSize = (int)resetParameters["gridSize"];
        maxFood = (int)resetParameters["maxFood"];
}
```
Those variables are used to determine what the environment for each agent is after each agent reset.

**Comment by MarcoMeter** [comment]
Does the curriculum update the lesson if you set the threshold to maybe 0.1?

**Comment by UsaidPro** [comment]
The curriculum doesn't update the lesson even if I set the threshold to 0.1. It just soars to 0.96 mean reward and stays there at lesson 0.
I tested using a already-trained graph and debugging agent resets vs academy resets and found that both were resetting (the agent obviously reset more often finishing its 'goal', but the academy also reset occasionally).

I'm now going to try training with the reset debugging in and seeing if it calls the reset while training.

**Comment by UsaidPro** [comment]
It does call Academy's reset while training. I put the debug statement as the first line in AcademyReset(), so there is no chance it is being erroneously called. Perhaps this is due to having multiple agents then? I'm going to retrain with a single agent, single brain.

**Comment by UsaidPro** [comment]
I upgraded to version 0.3 and the issue seems to be resolved! It is now switching the lessons. Thanks for the help!
