### ISSUE TITLE
Uncaught RunTimeError: memory access out of bounds: Agent.SetModel in IL2CPP

### ISSUE THREAD

**Issue by anubhav756** [Unity-Technologies/ml-agents#4692]
**Describe the bug**
Getting an error in WebGL build about memory access out of bounds.

**To Reproduce**
1. Set Scripting Backend as IL2CPP
2. Use Agent.SetModel() in code
3. Build and Run

**Logs**
Uncaught RunTimeError: memory access out of bounds

**Environment (please complete the following information):**
- Unity Version: Unity 2020.1f1
- OS + version: MacOS, Catalina
- _ML-Agents version_: Version 10
- _Torch version_: Using Tensorboard
- _Environment_: WebGL

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by chriselion** [comment]
I was unable to reproduce this with the WallJump example scene, which uses SetModel, on Unity 2020.1.5f1.

Can you please include the full callstack of the error, and some of the code around where you're calling SetModel from? Also, you probably need to check that the NNModel is non-null; I would imagine this this isn't handled as gracefully in IL2CPP builds as it normally.
