### ISSUE TITLE
torch installation

### ISSUE THREAD

**Issue by kajvan** [Unity-Technologies/ml-agents#4697]
this command does not work for me:
pip install torch==1.7.0 -f https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch===1.7.0
ERROR: No matching distribution found for torch===1.7.0

**Comment by kajvan** [comment]
it does work i did run cmd.exe now without administrator

**Comment by kajvan** [comment]
i am using python 3.7 and i activated my venv. when i try to download torch it does not work i do not no why and how to fix this problem. i am following this course https://www.youtube.com/watch?v=zPFU30tbyKs&t=132s 
the command that i use is provided by the github

**Comment by vincentpierre** [comment]
Hi, can you please provide the information required in the bug template? 


**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Console logs / stack traces**
Please wrap in [triple backticks (```)](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make it easier to read.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**
- Unity Version: [e.g. Unity 2020.1f1]
- OS + version: [e.g. Windows 10]
- _ML-Agents version_: (e.g. ML-Agents v0.8, or latest `develop` branch from source)
- _Torch version_: (you can run `pip3 show torch` to get this)
- _Environment_: (which example environment you used to reproduce the error)

It be useful for me to know what your Python and pip versions are. It is extremely strange that there is a triple = sign in the error you posted in your first message, there are suppose to be only two...

**Comment by kajvan** [comment]
it is fixed i deleted all the other python install and now it does work
