### ISSUE TITLE
UnityEnvironmentException: The Unity environment took too long to respond

### ISSUE THREAD

**Issue by MarcPilgaard** [Unity-Technologies/ml-agents#47]
Hi,

I am trying to run the ML Agent 3D Ball example project but I am receiving an error in Jupyter during the "Load the Environment" cell. The Unity application opens up and the balls  falls down on the plates and rolls down. The application runs for e.g. 30 seconds or so until it closes, and the following error can be seen in in Jupyter:

"UnityEnvironmentException: The Unity environment took too long to respond. Make sure environment does not need user interaction to launch and that the Academy and the external Brain(s) are attached to objects in the Scene."

The setup I am using is:
- Unity 2017.1.1f1
- Mac OSX Sierra 10.12.6
- Tensorflow 1.3
- Anaconda 4.3.27
- Python 3.6

The following trace was printed:

`---------------------------------------------------------------------------
timeout                                   Traceback (most recent call last)
~/Unity Projects/ml-agents/python/unityagents/environment.py in __init__(self, file_name, worker_id, base_port)
     84                 self._socket.listen(1)
---> 85                 self._conn, _ = self._socket.accept()
     86                 self._conn.setblocking(1)

~/anaconda3/lib/python3.6/socket.py in accept(self)
    204         """
--> 205         fd, addr = self._accept()
    206         # If our type has the SOCK_NONBLOCK flag, we shouldn't pass it onto the

timeout: timed out

During handling of the above exception, another exception occurred:

UnityEnvironmentException                 Traceback (most recent call last)
<ipython-input-15-48ea1f1caab6> in <module>()
----> 1 env = UnityEnvironment(file_name=env_name)
      2 print(str(env))
      3 brain_name = env.brain_names[0]

~/Unity Projects/ml-agents/python/unityagents/environment.py in __init__(self, file_name, worker_id, base_port)
     91                 "The Unity environment took too long to respond. Make sure {} does not need user interaction to launch "
     92                 "and that the Academy and the external Brain(s) are attached to objects in the Scene.".format(
---> 93                     str(file_name)))
     94         except UnityEnvironmentException:
     95             proc1.kill()

UnityEnvironmentException: The Unity environment took too long to respond. Make sure environment does not need user interaction to launch and that the Academy and the external Brain(s) are attached to objects in the Scene.`

**Comment by liuyihunter** [comment]
got same Errors 

---------------------------------------------------------------------------
timeout                                   Traceback (most recent call last)
D:\Unity Projects\ml-agents-master\python\unityagents\environment.py in __init__(self, file_name, worker_id, base_port)
     84                 self._socket.listen(1)
---> 85                 self._conn, _ = self._socket.accept()
     86                 self._conn.setblocking(1)

c:\users\liuyi08\appdata\local\programs\python\python35\lib\socket.py in accept(self)
    194         """
--> 195         fd, addr = self._accept()
    196         # If our type has the SOCK_NONBLOCK flag, we shouldn't pass it onto the

timeout: timed out

During handling of the above exception, another exception occurred:

UnityEnvironmentException                 Traceback (most recent call last)
<ipython-input-8-19bd9c6b2f7f> in <module>()
----> 1 env = UnityEnvironment(file_name=env_name)
      2 
      3 # Examine environment parameters
      4 print(str(env))
      5 

D:\Unity Projects\ml-agents-master\python\unityagents\environment.py in __init__(self, file_name, worker_id, base_port)
     91                 "The Unity environment took too long to respond. Make sure {} does not need user interaction to launch "
     92                 "and that the Academy and the external Brain(s) are attached to objects in the Scene.".format(
---> 93                     str(file_name)))
     94         except UnityEnvironmentException:
     95             proc1.kill()

UnityEnvironmentException: The Unity environment took too long to respond. Make sure 3DBall does not need user interaction to launch and that the Academy and the external Brain(s) are attached to objects in the Scene.

**Comment by MarcPilgaard** [comment]
Thank you, that did the trick for me!
