### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Krephix** [Unity-Technologies/ml-agents#4724]
After following the installation documentation and installing Python 3.7.9, pip's newest version, pytorch, and mlagents I get an error (see Screenshot) when running: "mlagents-learn --help" to see if the installation was successful. I hope someone can help me with that issue. I am sorry if I post this issue in the wrong section here - I am kind of new to this.

**Screenshot**
![image](https://user-images.githubusercontent.com/75696450/101532454-dcf63c80-3994-11eb-81b9-9ab46b4c9a17.png)

**Environment:**
- Unity Version: Unity 2019.3.15f1
- OS + version: Windows 10
- _ML-Agents version_: 0.22.0
- _Torch version_: 1.7.0+cu110
- _Environment_: own created virtual environment after following the installation documentation

**Comment by Krephix** [comment]
Also to add something: there were no errors while installing pytorch or mlagents with pip. Also, I can execute the line "from torch._C import *" (last line indicated by the error traceback) without any errors when I run python normally in the console.

**Comment by awjuliani** [comment]
Hi @Krephix 

Can you verify that numpy was correctly installed, and that you only have one version installed on the machine?

**Comment by Krephix** [comment]
Hi @awjuliani 

I had numpy previously installed outside the virtual environment with version 1.18.1. After your message I checked the installed numpy version inside the virtual environment and for some reason 1.19.4 was installed, which must have been done by either pip install pytorch or mlagents, because I didn't do anything else in the virtual environment. Even while 1.19.4 was installed pip install mlagents --use-feature=2020-resolver didn't throw any errors and also didn't reinstall numpy with a different verion. Maybe because of the installed numpy outside the virtual environment?

running: pip install numpy==1.18.5 manually solved the issue now and I can correctly see the output from the command "mlagents-learn --help". Thank you for pointing me in the right direction.

**Comment by awjuliani** [comment]
Glad you were able to get things fixed. Having multiple numpy versions on the same machine can sometimes conflict with one another, which was my hunch.
