### ISSUE TITLE
Poor naming with "Project"

### ISSUE THREAD

**Issue by clankill3r** [Unity-Technologies/ml-agents#4782]
I wanted to point out that I think it's a bit poor that the unity project is called Project:

![poor_naming](https://user-images.githubusercontent.com/738650/102789241-25095c00-43a4-11eb-922b-12465380ee6b.png)

my 2 cents

**Comment by surfnerd** [comment]
Hi @clankill3r,
I agree, that is my fault as I created that folder.  I have filed this as MLA-1663 internally and we will update this issue once we have resolved the issue.
Cheers,
Chris

**Comment by clankill3r** [comment]
.

**Comment by clankill3r** [comment]
.
