### ISSUE TITLE
Using Virtual Environment - Windows Setup

### ISSUE THREAD

**Issue by clankill3r** [Unity-Technologies/ml-agents#4787]
https://github.com/Unity-Technologies/ml-agents/blob/release_10_docs/docs/Using-Virtual-Environment.md#installing-pip-required

Step 3 of window setup is as follow:

> 3. To activate the environment execute `python-envs\sample-env\Scripts\activate`

This **Scripts** folder does not exist for me, I suspect someone typed **Scripts** out of a unity habbit to put scripts in a script folder... I really hope it has nothing todo with the shitshow python turned into.

I expect the line should be this:

> 3. To activate the environment execute `python-envs\sample-env\bin\activate`

That folder looks like this:

![python_still_sucks](https://user-images.githubusercontent.com/738650/102826929-ed210980-43e1-11eb-94a1-cd6e92723563.png)

And while at it, what is the right way to execute the activate script? I wan't to make sure I do it right the first time cause I have horrible memories of getting into python hell...

**Comment by surfnerd** [comment]
Hi @clankill3r,
You should be able to just type those commands into the cmd prompt on windows (with the correct paths, of course).  Let me know if you run in to other issues.  

I've tracked this internally as MLA-1665 and will update this issue once it's resolved.
Cheers,
Chris

**Comment by clankill3r** [comment]
The issue is gone, see here all the steps I did:
https://github.com/Unity-Technologies/ml-agents/issues/4808
