### ISSUE TITLE
Unable to set Graph Model in Balance Ball

### ISSUE THREAD

**Issue by gerardsimons** [Unity-Technologies/ml-agents#48]
I am following the instructions from https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Getting-Started-with-Balance-Ball.md. All is well until I want to incorporate the model into the Unity environment to see it play the game. 

When I follow these instructions : 

> Change the Type of Brain to Internal.
> Drag the <env_name>.bytes file from the Project window of the Editor to the Graph Model placeholder in the 3DBallBrain inspector window.

I get stuck at setting the Graph Model. I simply do not see such a property in the Inspector. This is on MacOS Sierra running Unity 2017.1.1f1

<img width="1440" alt="screen shot 2017-09-27 at 15 38 21" src="https://user-images.githubusercontent.com/4247845/30916553-fd01a3f0-a399-11e7-81c6-8f9c8a2234f2.png">

What am I missing here?

**Comment by eagleEggs** [comment]
Can you expand the console, and see what errors are going on in there with a screenshot? Might be a conflict regarding the Brain or adjacent scripts.

**Comment by awjuliani** [comment]
Hi @gerardsimons,

If you just enabled TensorFlow support (see https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Getting-Started-with-Balance-Ball.md#setting-up-tensorflowsharp-support), you might need to restart the Editor.

**Comment by gerardsimons** [comment]
@eagleEggs Here you go. Hope that helps. Thanks again.

<img width="1440" alt="screen shot 2017-09-27 at 18 55 20" src="https://user-images.githubusercontent.com/4247845/30926444-7e8cc97a-a3b5-11e7-848e-be203c019de1.png">

@awjuliani : I already did that at the time, and again now. Does not help unfortunately, thanks for trying though

**Comment by vincentpierre** [comment]
@gerardsimons I think a quick fix should be to delete the brain component from the game object and add a new Brain component with the same brain parameters. Let me know if that helps.

**Comment by gerardsimons** [comment]
@vincentpierre That works, should have tried that right of the bat obviously. Thanks for the quick help guys!

**Comment by gerardsimons** [comment]
Perhaps I cheered too soon. I can indeed get the parameters to show in the inspector now, and I then try to set them to the values I saw previously, but when I press play I do not see it play the game. Maybe I did not set some parameters properly? See screenshot below:

<img width="1440" alt="screen shot 2017-09-28 at 09 35 29" src="https://user-images.githubusercontent.com/4247845/30954648-3d5d3d00-a431-11e7-94c8-942cd5f97df6.png">

**Comment by gerardsimons** [comment]
@awjuliani : Can you help me out with this or should I raise a new issue? I have ensured the model is only exported to bytes once the reward threshold has been reached.

**Comment by vincentpierre** [comment]
Can you tell me if you get an error in the console ?
It seems the pause button is pressed (right next to the play button) have you tried clicking on it ?

**Comment by davidsellin** [comment]
I'm stuck at the same step. But I can't see the **Internal** option for **Type Of Brain**, only **Player**, **Heuristic**, and **External**. I don't have any errors in the Console. I'm on windows. Removing the Brain-script and adding it again didn't change anything.

**Comment by gerardsimons** [comment]
Sorry forgot about this, but yeah it seems sometimes you have to start it a few times before it actually starts.
