### ISSUE TITLE
embed python in the project

### ISSUE THREAD

**Issue by clankill3r** [Unity-Technologies/ml-agents#4808]
This project is so hard to get working.
If you have blender for example; it ships with python included cause everything around setting up python and all it's versions is a nightmare, and by this they avoid people having go threw this nightmare.

Please include python in this project aswell. The windows binary is around 11mb and they won't be much larger for osx and linux. It might add 35mb to the repository, which is small in relation to the size of unity projects.

To get ml-agents it should just be a simple clone of the project, and then installing the required packages threw the package manager. Everything beyond that should be unnecessary.

**Comment by clankill3r** [comment]
Ok, I removed all python versions from my machine and I will list al the crap I get into here.

I'm at the step:

> Install Python 3.6.1 or Higher

https://github.com/Unity-Technologies/ml-agents/blob/release_12_docs/docs/Installation.md#install-python-361-or-higher

I followed the link and installed 3.7, I also marked the option to add it to the path.
In case someone is wondering, it got installed here:
C:\Users\clank\AppData\Local\Programs\Python\Python37

`pip3` is not included.

**Comment by clankill3r** [comment]
Since `pip3` is not included I went to the link with instructions.

![pip3_instructions](https://user-images.githubusercontent.com/738650/103281717-decf8080-49d3-11eb-93a3-d4e675b3c5a3.png)

The link points to a page only usefull if you are using **linux**.

![installing_pip](https://user-images.githubusercontent.com/738650/103282598-96659200-49d6-11eb-8ba1-60b92e224839.png)

But if I go two headers higher in the table of contents I end up here:
https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/

Using this command:

`py -m pip --version`

I get:

> pip 20.1.1 from C:\Users\clank\AppData\Local\Programs\Python\Python37\lib\site-packages\pip (python 3.7)

So that seems to be good.

**Comment by clankill3r** [comment]
At this point the `pip3` command works.

I am now ready for the  **Install the mlagents Python package** step.
https://github.com/Unity-Technologies/ml-agents/blob/release_12_docs/docs/Installation.md#install-the-mlagents-python-package

Which detours me to the **guide on Virtual Environments** https://github.com/Unity-Technologies/ml-agents/blob/release_12_docs/docs/Using-Virtual-Environment.md

Here I am asked again to install pip. 

https://github.com/Unity-Technologies/ml-agents/blob/release_12_docs/docs/Using-Virtual-Environment.md#installing-pip-required

This time using `curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py` but since I already did a step to get pip working, I won't follow this step.
Note, at this point I don't have a `python3 ` command! But `python` just points at the python 3.7 version. This is, as told above after a fresh install of python 3.7 following the link provided.

I created a python-env using `python -m venv python-envs\ml-agents`.
I activated the env, not that this issue that I had before is gone at this point:
https://github.com/Unity-Technologies/ml-agents/issues/4787

Ok now i'm at step 4.

> 4. Upgrade to the latest pip version using `pip install --upgrade pip`

This goes wrong:

> 
> (ml-agents) PS C:\> pip install --upgrade pip
> Collecting pip
>   Using cached pip-20.3.3-py2.py3-none-any.whl (1.5 MB)
> Installing collected packages: pip
>   Attempting uninstall: pip
>     Found existing installation: pip 20.1.1
>     Uninstalling pip-20.1.1:
>       Successfully uninstalled pip-20.1.1
> ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\clank\\AppData\\Local\\Temp\\pip-uninstall-aq_460x2\\pip.exe'
> Consider using the `--user` option or check the permissions.

I continue in the next post.

**Comment by clankill3r** [comment]
Ok I tried the `--user` like this: 

> pip install --upgrade --user pip

Which gives me:

> ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.

Ok, now I did run Powershell as an administrator and did the command: `pip install --upgrade pip`.
Which resulted in 

> Requirement already satisfied: pip in c:\python-envs\ml-agents\lib\site-packages (20.3.3)

So that seems to be ok.

**Comment by clankill3r** [comment]
Ok, now I'm at the step **Install the mlagents Python package**

https://github.com/Unity-Technologies/ml-agents/blob/release_12_docs/docs/Installation.md#install-the-mlagents-python-package

Which states:

> On Windows, you'll have to install the PyTorch package separately prior to installing ML-Agents.

What is meant by ML-Agents is unclear, if it is the unity project then it is odd that we have to install the packages from within unity in one of the steps above.

I also installed the latest Visual C++ Redistributable.

Ok, I got it working now. I think the rest will also work. If not I will post here. I hope this post is helpfull to someone, and also shines light on how complicated this is to get working.
I really hope this repository ships someday with python and it's packages  included.
Just like blender, inkscape and more programs just include python within their program to avoid installation issues.

This whole thread is not really a issue with this repository itself, I think python is not in a healthy state in general.
It would however be a huge benefit if those problems could be encapsulated.

**Comment by unityjeffrey** [comment]
thanks @clankill3r for your note.  we def recognize that installing python, especially for Unity developers who do not actively use python, can be challenging.

We've made a note of your request and we are working on an internal prototype that could potentially wrap the entire installation process without having to install Python.
