### ISSUE TITLE
104 Compiler Errors

### ISSUE THREAD

**Issue by Graph-IKE** [Unity-Technologies/ml-agents#4809]
When I import the ML-agents folder into my project, it immediately gives me 104 compiler errors. All of them are either "CS0115", "CS0246" or "CS0234"

**Comment by ervteng** [comment]
Hi @Graph-IKE - you shouldn't have to import the ML-Agents folder into your project anymore. Have you tried installing it as a package using the Unity Package Manager? (under Window -> Package Manager)
