### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by tschmidt64** [Unity-Technologies/ml-agents#481]
I see from numerous posts/issues that the input space should be normalized to [0,1] or [-1,1]. Is the input space the only thing that should be normalized? Do rewards need to be normalized to this range as well? 

Right now I'm rewarding my plane at every step for its change in distance away from the target (usually ends up being between [0, 1] by coincidence, and then a large 1000 reward if it actually hits the target. I also do a -1000 reward and set done=true if it gets farther away from the target

**Comment by ruanrothmann** [comment]
I've read in quite a few dev responses on here that rewards should also be kept in the [-1,1] range.

**Comment by MarcoMeter** [comment]
It is recommended to normalize the input space and to keep the rewards in a similar range.
However, there are environments which signal rewards in a scale of thousands. For example a few ones from [OpenAI](https://blog.openai.com/competitive-self-play/).

**Comment by tschmidt64** [comment]
So then what should a case like mine look like, if I want to reward it for good actions along the way but then also _really_ reward it if it succeeds at hitting the target?

**Comment by tschmidt64** [comment]
Wait, to be clear @MarcoMeter, do you mean that the individual step rewards should be kept in the same range or that the CumulativeReward value should end up being in that same range?

**Comment by MarcoMeter** [comment]
Each individual reward shall be in that small range, regardless if it is signaled for many steps or not.

**Comment by roboserg** [comment]
> Each individual reward shall be in that small range, regardless if it is signaled for many steps or not.

I didn't quite understand. Should the CumulativeReward at the end of the episode be in the -1 to 1 range or it doesn't matter so long as a rewards in each step are in that range?
