### ISSUE TITLE
"Python Tutorial with Google Colab" example is does not work in latest version of mlagents(update it please)

### ISSUE THREAD

**Issue by soyaCat** [Unity-Technologies/ml-agents#4838]
I install ml_agents yesterday and try to write own python code with "Python Tutorial with Google Colab"  example.
But there is some problem with this examples

Here is my environment setting
(Just follow this guide: https://github.com/Unity-Technologies/ml-agents/blob/release_12_docs/docs/Readme.md)
- Unity 2020.1.3f1
- MLAgents Release 12
- python 3.8.5
- MLAgents API ver 0.23.0

Because I want to controll unity with python
I study MLAgent with "Python Tutorial with Google Colab" which is located here:
https://github.com/Unity-Technologies/ml-agents/blob/release_12_docs/docs/Readme.md

But this tutorial is little old
So there are some errors Just copy and use tutorial code
Here is a link to the tutorial I referenced.
1. https://colab.research.google.com/drive/1Qg6E5kmf9n4G8rc5lXHIM_cQzMUFGH-g#forceEdit=true&sandboxMode=true
2. https://colab.research.google.com/drive/1nkOztXzU91MHEbuQ1T9GnynYdL_LRsHG#forceEdit=true&sandboxMode=true

In referenced code 1. ,
This is first tutorial part that occurs error
```python
# Is the Action continuous or multi-discrete ?
if spec.is_action_continuous():
  print("The action is continuous")
if spec.is_action_discrete():
  print("The action is discrete")
```

But When I adjust tutorial code to my python code, spec object doesn't have is_action_continuous()
So  I solve this problem by this way:
```python
    #print action is_discrete
    print("Is action is discrete ?", spec.action_spec.is_discrete())

    #print action is_continuous
    print("Is action is continus ?", spec.action_spec.is_continuous())
```

And referenced code 2. ,
This part has error to adjust my python code
```python
      # Pick the best action using argmax
      actions = np.argmax(actions_values, axis=1)
      actions.resize((len(decision_steps), 1))
      # Store the action that was picked, it will be put in the trajectory later
      for agent_index, agent_id in enumerate(decision_steps.agent_id):
        dict_last_action_from_agent[agent_id] = actions[agent_index]

      # Set the actions in the environment
      env.set_actions(behavior_name, actions)
      # Perform a step in the simulation
      env.step()
```
set action only receive ActionTuple object,
Here is Link that I referenced:
https://github.com/Unity-Technologies/ml-agents/blob/release_12_docs/docs/Python-API.md

so In tutorial code, this part
```python
 env.set_actions(behavior_name, actions)
```
occurs error because 'actions' is not ActionTuple Object!

I solve this probelm by this way,
```python
    from mlagents_envs.base_env import ActionTuple
    _continuous = np.zeros((n_agents, spec.action_spec.continuous_size), dtype=np.float32)
    _discrete = np.zeros((n_agents, spec.action_spec.discrete_size), dtype=np.int32)
    action = ActionTuple(continuous=_continuous, discrete=_discrete)
    env.set_actions(behavior_name, action)
``` 

Unless I did the wrong installation,
colab example is outdated code to adjust it to latest ml_agents python code
so update example code please :)
Thanks

**Comment by andrewcoh** [comment]
Thank you very much for pointing this out. I will update the tutorial.

**Comment by andrewcoh** [comment]
The colabs have been updated to use version 0.23.0 of ML-Agents.
