### ISSUE TITLE
Error when training with RLlib and num_samples > 1

### ISSUE THREAD

**Issue by rallen10** [Unity-Technologies/ml-agents#4852]
**Describe the bug**
When trying to train an mlagents environment using rllib with num_samples > 1, I get the following error:

```raise UnityWorkerInUseException(self.worker_id)
mlagents_envs.exception.UnityWorkerInUseException: Couldn't start socket communication because worker number 1 is still in use. You may need to manually close a previously opened environment or use a different worker number.```

**Comment by vincentpierre** [comment]
I think you need to post this issue on the RLlib repo, this error happens when the base port specified to open the Unity environment is already in use. You will need to manually specify another base port, but I am not sure how RLlib allows you to do this.

**Comment by rallen10** [comment]
@vincentpierre I thought that might be the case, but was worried that they might say "you need to post this on ml-agents" so I figured I would open a thread here as well. 

If I learn anything there, I will add a link to it here.
