### ISSUE TITLE
Low level memory allocation every frame

### ISSUE THREAD

**Issue by szantner** [Unity-Technologies/ml-agents#4883]
**Describe the bug**
I detect seemingly low level memory allocations in the EnvironmentStep call every frame as seen in the screenshot using Deep Profile in Profiler

**To Reproduce**
Using multiple agents in inference mode.

**Console logs / stack traces**

**Screenshots**
![image](https://user-images.githubusercontent.com/170305/105715905-71edce80-5f1e-11eb-9edd-8f2c1a3df9c7.png)

**Environment (please complete the following information):**
- Unity Version: Unity 2020.2.2f1
- OS + version: Windows 10
- _ML-Agents version_: 1.0.6

**Comment by chriselion** [comment]
Hi,
I think you're right that we're allocating a BinaryWriter and MemoryStream on each step, even if there are no messages to process:
https://github.com/Unity-Technologies/ml-agents/blob/30bcb018bcac6dd73ed64d34016131d03cd6514d/com.unity.ml-agents/Runtime/SideChannels/SideChannelManager.cs#L121-L126

We can definitely early out in that case (or maybe reuse the objects). Is that the main allocation you're seeing?

**Comment by chriselion** [comment]
We've got this logged in our internal tracker as MLA-1720. I'll probably get to it this week, but it should be pretty straightforward if you want to submit a PR for it instead.

**Comment by szantner** [comment]
Hi Chris,

Thank you for the quick response. It is probably best if I leave the modifications for you! :) 

Btw - and maybe that should be a separate issue - but I saw a strange memory allocation too in another part of ml_agents, but that I managed to fix on my side. So if I did the following, that caused memory allocations:

`sensor.AddObservation(_observationLadarInfoOffRoad);`

where  `private List<float> _observationLadarInfoOffRoad;` 

When I added the observations in a for loop myself, the memory allocation disappeared:

`
for (int i = 0, length = _observationLadarInfoOffRoad.Count; i < length; i++) {
    sensor.AddObservation(_observationLadarInfoOffRoad[i]);
}
`

**Comment by chriselion** [comment]
I think I see what you're saying. This is happening in your Agent's`CollectObservations(VectorSensor sensor)` method, right? If you use `sensor.AddObservation(_observationLadarInfoOffRoad);` it would treat the List as an IEnumerable:
https://github.com/Unity-Technologies/ml-agents/blob/30bcb018bcac6dd73ed64d34016131d03cd6514d/com.unity.ml-agents/Runtime/Sensors/VectorSensor.cs#L167-L173
which _might_ allocate memory in the `foreach` loop; I need to look into it further. Your approach is equivalent but definitely doesn't need to allocate anything.

**Comment by chriselion** [comment]
Thanks, I was able to confirm that by modifying one of our examples:

![image](https://user-images.githubusercontent.com/6877802/105802954-302a4b80-5f51-11eb-988f-ffa99175e0fc.png)

I think we can add an `AddObservation(IList<float> observation)` overload to VectorSensor, which should help get rid of this allocation.

**Comment by szantner** [comment]
Hi Chris, great to hear that it wasn't a false alarm. Thank you for the super quick responses!

**Comment by chriselion** [comment]
No problem, thanks for pointing me in the right direction. I have MLA-1724 created for this.

**Comment by KevinWu57** [comment]
Just curious, how do you get this profiler windows? That looks pretty helpful in checking each function call.

**Comment by chriselion** [comment]
https://docs.unity3d.com/Manual/ProfilerWindow.html with Deep Profiling enabled.
![image](https://user-images.githubusercontent.com/6877802/105909206-1a159d00-5fdc-11eb-8691-393f28aca163.png)

**Comment by chriselion** [comment]
The SideChannel allocations are addressed in https://github.com/Unity-Technologies/ml-agents/pull/4886
I added an overload for VectorSensor.AddObservation in https://github.com/Unity-Technologies/ml-agents/pull/4887 (and also cleaned up a lot more garbage during inference).
