### ISSUE TITLE
How do you design around variable amount of states?

### ISSUE THREAD

**Issue by MarcPilgaard** [Unity-Technologies/ml-agents#49]
How do you design your agent in environments with variable amount of states?

To give an example: Say you have an agent that has to get from location A to location B. In the environment there is a range of "enemies". The agents job is to get from A to B while being rewarded for being as far as possible from the enemies. There will also be obstacles on the path, which the agent have to maneuver around. The tricky part is: While going from A to B more enemies and obstacles will spawn.

My initial thought was to append the "state" list with the spawned enemies and obstacles, but if each index in the list does not represent the same type of state, how does the brain differentiate between an obstacles and an enemy? 

How would you go about this? I am relatively new to machine learning so excuse me for my lack of lingo.

**Comment by awjuliani** [comment]
Hi @MarcPilgaard,

This is a good question. The answer is that you'd have to think through a way of representing what might be a variable gameworld in an ultimately fixed way. For example, in the GridWorld, we represent the state as the x and z positions of the agent, along with the x and z positions of the closest obstacle and goal. In this way the size is fixed, while the number of agents can increase. It is also possible to use visual observations, such as a camera looking down on the scene, which can capture an arbitrary number of enemies positions while remaining "fixed" in size. Hope that helps.
