### ISSUE TITLE
[Question] log_sigma_squared for PPO continuous control

### ISSUE THREAD

**Issue by edhyah** [Unity-Technologies/ml-agents#4901]
Hello, in the code I see the line `log_sigma_sq = tf.get_variable("log_sigma_squared", [self.act_size[0]], dtype=tf.float32, initializer=tf.zeros_initializer())`. Why is the variance initialized to zero? Doesn't this mean in the beginning of training the agent doesn't explore?

**Comment by ervteng** [comment]
It's the log of the variance that is initialized to 0, so the variance is actually initialized to 1.

**Comment by edhyah** [comment]
Ah, my mistake. Thank you!
