### ISSUE TITLE
Avoid 3D ball example agents to shake

### ISSUE THREAD

**Issue by aurelien78** [Unity-Technologies/ml-agents#4903]
**Is your feature request related to a problem? Please describe.**
Hi, this is not really a feature request.
I feel like you should modify reward for 3D ball example to avoid agents to shake.
(however, you may want to keep it simple on purpose)

**Describe the solution you'd like**
Compute a normalized "energy" value like :
var energy = (actionZ * actionZ + actionX * actionX) / 4.0f;

modify :
SetReward(0.1f);
with :
SetReward(0.1f - (energy / 10.0f));

Behaviour will be much smoother

**Comment by awjuliani** [comment]
Hi @aurelien78 

Thanks for pointing this out. I agree that such a modified reward would likely make the agent movement smoother. Our initial goal with this environment was to provide as simple an example as possible, and as such did not add an energy penalty. If you would like to make a PR with this change, we can take a look at it.
