### ISSUE TITLE
[Question] log_sigma_std for continuous control tasks

### ISSUE THREAD

**Issue by edhyah** [Unity-Technologies/ml-agents#4904]
Hello, so I realized in the code that the variance of a gaussian outputted by a continuous control network is a variable:

`self.log_sigma_sq = tf.get_variable("log_sigma_squared", [self.act_size[0]], ...)`

What does this mean during training? Is `self.log_sigma_sq` a trainable weight? Or is it a constant that's the same for every single network inference during test time?

If it is a constant or trainable weight, during curriculum training, shouldn't this weight be reinitialized to zero to encourage exploration again?

**Comment by awjuliani** [comment]
Hi @edhyah 

This is a trainable weight vector which gets updated during the learning process. We don't reset it during curriculum learning, as this would likely result in catastrophic forgetting. Instead, we use an entropy regularization term which is constantly pushing the variance to be larger. In cases where the task distribution has changed, like in curriculum learning, this entropy bonus should naturally allow the variance to increase again to explore more again.

**Comment by edhyah** [comment]
Got it. So during test time this weight doesn't change right? Meaning variance is independent of state? Meaning it's not really a measure of uncertainty of the model, but rather just an exploration parameter?

**Comment by awjuliani** [comment]
That is exactly right. The variance in the network is state-independent.
