### ISSUE TITLE
UserWarning: This overload of nonzero is deprecated -> mlagents-learn no longer generates action value variations

### ISSUE THREAD

**Issue by netcob64** [Unity-Technologies/ml-agents#4910]
**Describe the bug**
during the training of a model mlagents-learn report a  "UserWarning: This overload of nonzero is deprecated", and then the values received in OnActionReceived agent method in Unity session stay constant... No more variation for the training, and then the agent learns nothing...

**To Reproduce**
create a unity scene for agent training
the agent has a Behavior Parameters set as
Vector Observation:
  Space size: 8
  Stacked Vectors: 5
Actions
  Continous Actions: 12
  Discrete Branches: 0
Model : None

ATtached files : 2
Unity scene:
[nonzero-issue.zip](https://github.com/Unity-Technologies/ml-agents/files/5930953/nonzero-issue.zip)
POP configuration file: 
[MyWormAgent.zip](https://github.com/Unity-Technologies/ml-agents/files/5931073/MyWormAgent.zip)

  Inference Device: CPu
Behavior Type: Default
Team id: 0
Use Child Sensors: true
Observable Attribute Handling: Ignore
...
see attached unity package for full configuration

**Console logs / stack traces**
```2021-02-05 08:25:04 INFO [stats.py:139] MyWormAgent. Step: 2000. Time Elapsed: 15.349 s. Mean Reward: -0.122. Std of Reward: 0.000. Training.
2021-02-05 08:25:12 INFO [stats.py:139] MyWormAgent. Step: 4000. Time Elapsed: 22.612 s. No episode was completed since last summary. Training.
d:\programmes\python\python3.9\lib\site-packages\mlagents\trainers\torch\utils.py:243: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  ..\torch\csrc\utils\python_arg_parser.cpp:882.)
  res += [data[(partitions == i).nonzero().squeeze(1)]]
```
No error ni the trace...

**Screenshots**
N/A

**Environment (please complete the following information):**
- Unity Version: Unity 2020.2f1
- OS + version: Windows 8.1
- _ML-Agents version_: 1.7.2-preview
- _Torch version_: 1.7.1
- _Environment_: Python 3.9.1

**Comment by awjuliani** [comment]
Hi @netcob64 

Can you share your tensorboard output? I am curious about the entropy chart in particular.

**Comment by awjuliani** [comment]
Can you also share what your observation space is? As there may be some input there that the network is not able to handle gracefully.

**Comment by konyushkov** [comment]
Hello @awjuliani! 
Sorry for my English. I have this problems too (Only with SAC trainer_type. If I restart learning, session will work during 5-7k steps)

**Behavior Parameters:**
![image](https://user-images.githubusercontent.com/61820944/108106412-f4d9f300-709e-11eb-8c53-0778f8e51d78.png)

**GridSensor:**
![image](https://user-images.githubusercontent.com/61820944/108106491-1044fe00-709f-11eb-8b37-f48bd83f0144.png)

**Tensoboard enviroment**
![image](https://user-images.githubusercontent.com/61820944/108107483-5c447280-70a0-11eb-8887-0ddc44070031.png)


**Tensoboard policy**
![image](https://user-images.githubusercontent.com/61820944/108107437-48007580-70a0-11eb-976c-a46e2839c82e.png)


**Trainer config**
![image](https://user-images.githubusercontent.com/61820944/108106883-95c8ae00-709f-11eb-9afb-61bbdfe56c29.png)
