### ISSUE TITLE
Bug running in shared environment: UnauthorizedAccessException: Access to the path "<gamedata>/ML-Agents" is denied.

### ISSUE THREAD

**Issue by pt2302** [Unity-Technologies/ml-agents#4911]
It looks like this is caused by the Timer.cs code, which catches IOExceptions but not UnauthorizedAccessExceptions.

https://github.com/Unity-Technologies/ml-agents/blob/2352955052b30bbd5c7f13276e847f2ee5af5b8a/com.unity.ml-agents/Runtime/Timer.cs#L480

This happens when the file [gamedata]/ML-Agents/Timers/[GameName]_timers.json is owned by someone else.

**Comment by awjuliani** [comment]
Hi @pt2302 

Just to clarify, you'd like the code to also catch the `UnauthorizedAccessException` exception and log the same warning.

**Comment by pt2302** [comment]
@awjuliani, thanks for the response!

Yes, exactly. Currently, the (uncaught) exception triggers a `Unity.MLAgents.Academy.Dispose()` call, which then leads to `UnityEngine.Application.Internal_ApplicationQuit()`, interrupting the training process.

**Comment by awjuliani** [comment]
Hi @pt2302 

I've just merged a fix for this issue into master. https://github.com/Unity-Technologies/ml-agents/pull/4921. It should make it into the next release. I will close the issue for now. Thanks again for bringing it to our attention.
