### ISSUE TITLE
Heuristic Brain Not Returning Rewards

### ISSUE THREAD

**Issue by cxbxmxcx** [Unity-Technologies/ml-agents#494]
Is this code correct?
public void ResetDoneAndReward()
    {
        foreach (Agent agent in agents.Values)
        {
            if (!agent.done || agent.resetOnDone)  //**seems counter intuitive**
            {
                agent.ResetReward();
                agent.done = false;
            }
        }
    }

If I change the code to this it appears to work as expected, for a heuristics brain:
public void ResetDoneAndReward()
    {
        foreach (Agent agent in agents.Values)
        {
            if (agent.done && agent.resetOnDone)  //**code change**
            {
                agent.ResetReward();
                agent.done = false;
            }
        }
    }

I noticed that someone else had mentioned the same issue, but it was buried in another thread.

**Comment by xiaomaogy** [comment]
Where are you using this ResetDoneAndReward function? Could you please give more context on this?

**Comment by cxbxmxcx** [comment]
That issue was reported for .2 it is fixed in .3 on and can be closed.
