### ISSUE TITLE
Performance falls after --initialize-from or --resume 

### ISSUE THREAD

**Issue by gauravspatil** [Unity-Technologies/ml-agents#4940]
After using --initialize-from or --resume to load a previously saved model does not start at the same or even close level of performance.

To reproduce
1. Train the 3DBallHard environment with the default config.
2. After the training completes, change the max_steps in the config file to 1M
3. --resume training with the same run-id

OR
2. --initialize-from run-id and start a new run-id

In both cases the reward drops to almost the same level as when the intial training started. In the 3DBall environment, the agent quickly relearns but for some complex tasks that is not the case.

Image- Results of using both --initialize-from and --resume in the 3DBallhard example.
![image](https://user-images.githubusercontent.com/20603177/107715373-442cc600-6d23-11eb-8b51-bb9b32eea49a.png)

**Comment by dongruoping** [comment]
Hi, 

Can you provide the version (ML-Agent, OS, Unity) you're using? 
I wasn't able to reproduce the same performance drop on the latest branch.

Also please follow the issue template to submit an issue, thank you.

**Comment by gauravspatil** [comment]
> Hi,
> 
> Can you provide the version (ML-Agent, OS, Unity) you're using?
> I wasn't able to reproduce the same performance drop on the latest branch.
> 
> Also please follow the issue template to submit an issue, thank you.

Thanks for the reply. I was using ML-Agents Release 7. Looks like the issue was fixed between then and now.
