### ISSUE TITLE
Can an agent learn from players ?

### ISSUE THREAD

**Issue by Fangh** [Unity-Technologies/ml-agents#495]
Is there a way to make a brain learn by playing a lot against players instead of learning through python with external brain ?

(I am aware that the firsts lessons should be learn through the python process but to improve the AI over the time, it could be cool to learn from lots of players)

**Comment by MarcoMeter** [comment]
What you are referring to is imitation learning.


> (I am aware that the firsts lessons should be learn through the python process but to improve the AI over the time, it could be cool to learn from lots of players)

This is somewhat the opposite for imitation learning. It is used to create a basic behavior which can then be refined by the typical reinforcement learning procedure.

**Comment by Fangh** [comment]
Can we use imitation learning with the ML agent in Unity ?

**Comment by MarcoMeter** [comment]
It looks like that version 0.3 of ml-agents was released a couple of hours ago, so imitation learning should be available by now.

**Comment by Fangh** [comment]
I just read https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-Imitation-Learning.md

And I realize that I was not clear. I do not want the player to play the agent.
Imagine a game were the agent is a dot and the player's goal is to move the mouse to the dot.
The goal of the agent is to flee the mouse.

How the agent (the dot) can learn to flee the mouse (the player) without typical reinforcement learning procedure ? Only by playing against a lot of player.

**Comment by Fangh** [comment]
Also I'm wondering if making a game in which the player can call the AddReward() or SetReward() function by interacting with the game could work. (like the game Black & White or Creature)

**Comment by xiaomaogy** [comment]
Thank you for your comments.  We’ve documented your feedback and will prioritize when appropriate.
