### ISSUE TITLE
While using RequestDecision() manually, StepCount is still increasing

### ISSUE THREAD

**Issue by philippds** [Unity-Technologies/ml-agents#4960]
**Describe the bug**
Not sure if it is exactly a bug, but somehow I cannot get this to work properly. I am trying to request decisions on-demand using `RequestDecision()`, i.e. `OnActionRecieved` as well as `CollectObservations` are called correctly both once after `RequestDecision()`. Unfortunately, the `Agent.StepCount` is still recursively increased somehow in the background, while I would wish that would only increase by 1 once an action has been taken. Or maybe I don't understand what exactly `StepCount` is. Sorry if this is causing any unnecessary inconvenience.

**To Reproduce: Simple standard agent setup:** 

```css
using System.Collections;
using UnityEngine;
using Unity.MLAgents;
using Unity.MLAgents.Sensors;
using Unity.MLAgents.Actuators;

public class MyAgent : Agent
{
    public Transform target;
    int branch;
    int[] actionIndices;

    Unity.MLAgents.Policies.BehaviorType behaviorType;
    //Default = 0
    //HeuristicOnly = 1
    //InferenceOnly = 2

    public override void Initialize()
    {
        
    }

    // Start is called before the first frame update
    void Start()
    {
        // cache policy of agent
        this.behaviorType = GetComponent<Unity.MLAgents.Policies.BehaviorParameters>().BehaviorType;

        this.branch = 0;
        this.actionIndices = new int[0] {};
    }

    private void Update()
    {
        if (Input.anyKeyDown && this.behaviorType == Unity.MLAgents.Policies.BehaviorType.HeuristicOnly)
        {
            // if heuristic react to key presses
            Debug.Log("some button is pressed");
            RequestDecision();
        }
    }

    public override void Heuristic(in ActionBuffers actionsOut)
    {
        Debug.Log("Call Heuristic");

        ActionSegment<int> discreteActionsOut = actionsOut.DiscreteActions;

        if(Input.GetKey(KeyCode.W))
        {
            discreteActionsOut[0] = 0;
        }
        else if(Input.GetKey(KeyCode.A))
        {
            discreteActionsOut[0] = 1;
        }
        else if (Input.GetKey(KeyCode.S))
        {
            discreteActionsOut[0] = 2;
        }
        else if (Input.GetKey(KeyCode.D))
        {
            discreteActionsOut[0] = 3;
        }
        else
        {
            discreteActionsOut[0] = 4;
        }
    }

    public override void OnActionReceived(ActionBuffers actions)
    {
        Debug.Log("Call OnActionReceived");
        Debug.Log("Action number: " + this.StepCount);

        int movement = actions.DiscreteActions[0];
        Debug.Log("Action: " + movement);

        if (movement == 0)
        {
            StartCoroutine(SmoothMove(Vector3.forward,1f, 1f, 0.1f));
        }
        else if(movement == 1)
        {
            StartCoroutine(SmoothMove(Vector3.left, 1f, 1f, 0.1f));
        }
        else if (movement == 2)
        {
            StartCoroutine(SmoothMove(Vector3.back, 1f, 1f, 0.1f));
        }
        else if (movement == 3)
        {
            StartCoroutine(SmoothMove(Vector3.right, 1f, 1f, 0.1f));
        }

        // Reached target?
        float distanceToTarget = Vector3.Distance(this.transform.localPosition, this.target.localPosition);
        if (distanceToTarget < 0.01f)
        {
            // if yes, reward agent and reset environment
            SetReward(1.0f);
            EndEpisode();
        }

        // Check if agent fell off platform
        if (this.transform.localPosition.y < 0)
        {
            // if agent fell, reset environment
            EndEpisode();
        }
    }

    public override void CollectObservations(VectorSensor sensor)
    {
        Debug.Log("Call CollectObservations");

        // Target and Agent positions
        sensor.AddObservation(this.target.localPosition);
        sensor.AddObservation(this.transform.localPosition);
    }


    public override void OnEpisodeBegin()
    {
        Debug.Log("Call OnEpisodeBegin");

        // If the Agent fell of the plane, reset physics
        if (this.transform.localPosition.y < 0)
        {
            this.transform.localPosition = new Vector3(0, 0.5f, 0);
        }

        // Move target to new spot
        this.target.localPosition = new Vector3(Random.Range(-4.5f, 4.5f),
                                                0.5f,
                                                Random.Range(-4.5f, 4.5f));

        Debug.Log("Call OnEpisodeBegin: RequestDecision");
        RequestDecision();
    }

    IEnumerator SmoothMove(Vector3 dir, float distance, float totalTime, float timeStep)
    {
        // trigger Mask to not allow any movement
        int stepCount = (int)(totalTime / timeStep);
        float stepSize = distance / stepCount;

        this.actionIndices = new int[4] { 0,1,2,3 }; // just allowed to do nothing

        for (int i = 0; i < stepCount; i++)
        {
            this.transform.position += dir * stepSize;
            yield return new WaitForSeconds(timeStep);
        }

        this.actionIndices = new int[0] {}; // allow everything

        // if not heuristic request decision after coroutine has finished
        if (this.behaviorType != Unity.MLAgents.Policies.BehaviorType.HeuristicOnly)
        {
            Debug.Log("Requesting decision after coroutine");
            RequestDecision();
        }
    }

    /*
    public override void WriteDiscreteActionMask(IDiscreteActionMask actionMask)
    {
        
        string array = "";
        for(int i = 0; i < this.actionIndices.Length; i++)
        {
            array += this.actionIndices[i].ToString();
            if(i < this.actionIndices.Length - 1)
            {
                array += ",";
            }
        }

        Debug.Log("writing mask: " + array);
        

        actionMask.WriteMask(this.branch, this.actionIndices);
    }
    */
}

```

![image](https://user-images.githubusercontent.com/19360485/108281932-a3059b80-7178-11eb-8882-3eae5fefd3f8.png)

**Environment (please complete the following information):**
- Unity Version: Unity 2019.4.18f1
- OS + version: Windows 10
- _ML-Agents version_: ML Agents Release 12 - Version 1.7.2-preview

**Comment by andrewcoh** [comment]
Hi @philippds 

I see why this is confusing. The step counter on the agent is counting fixed update calls which is not necessarily 1 to 1 with actions. An action will be requested every `n` fixed updates where n corresponds to the `decision interval` specified in your decision requester component.

Let me know if I can clarify anything.

**Comment by philippds** [comment]
Ah okay, that's good to know. So the cumulated number of "fixed update calls" are the ones that the agent also compares against the Max Step count to decide wether to end the episode? In the example code, the agent basically moves on a grid, but with a smooth motion, so while the agent is moving, I don't want it to take any observations or try to request any actions. How would something like this be done? I understand that this might be quiet specific, but at the same time, this might be also helpful for others to understand and gain full control over when actions and observations are exactly happening and not flooding the "brain" with requests and observations in situations not needed. At this point obviously being ignorant here, in the context of my understanding of ML-Agents, this feels a bit like a black box and I really would like to crack it open :). This might be also interesting from a performance perspective. I hope what I'm trying to describe makes any sense. Thanks a lot in advance!

**Comment by philippds** [comment]
So I did some research and went through some code trying to understand what's going on under the hood. So to achieve what I described would it be a good idea to disable the `Fixed Update` in the `Academy.cs` internal class `AcademyFixedUpdateStepper` and use the `Academy.Instance.EnvironmentStep();` in my agent class after I manually requested a decision using `RequestDecision();` or will this be problematic on functionality I haven't yet considered in the `Academy.cs` code?

**Comment by andrewcoh** [comment]
It sounds like [on demand decisions](https://github.com/Unity-Technologies/ml-agents/blob/master/Project/Assets/ML-Agents/Examples/Bouncer/Scripts/BouncerAgent.cs#L79) might be what you're looking for. To enable this, you remove the DecisionRequester component from your agent and manually call `RequestDecision` based on game logic i.e. when your agent has reached a certain grid position.

**Comment by andrewcoh** [comment]
Actually, this is what we do in our Bouncer environment wherein we have _removed_ the decision requester component and call [RequestDecision manually.](https://github.com/Unity-Technologies/ml-agents/blob/master/Project/Assets/ML-Agents/Examples/Bouncer/Scripts/BouncerAgent.cs#L79) We call this 'On Demand decisions'. I am sorry that this isn't well documented.I will fix that.

**Comment by philippds** [comment]
Fantastic, this is great. Thank you very much!
