### ISSUE TITLE
Actions don't have expected standard-deviation when sampling from GaussDistInstance

### ISSUE THREAD

**Issue by Ihsees** [Unity-Technologies/ml-agents#4986]
**Describe the bug**

It seems to me like the actions that unity receives don't match the standard-deviation that GaussianDistInstance dictates.

In https://github.com/Unity-Technologies/ml-agents/issues/4866 I found that the standard-deviation of sampled actions will rise higher and higher in a sparse-reward environment due to the current calculation of entropy.

To come up with a approximation of entropy I've played around with the code in https://github.com/Unity-Technologies/ml-agents/blob/release_12/ml-agents/mlagents/trainers/torch/distributions.py . I changed this

```
class GaussianDistInstance(DistInstance):
    ...

    def sample(self):
        sample = self.mean + torch.randn_like(self.mean) * self.std
        return sample
```

to this - thus fixing the action-distribution in place to a mean value of 0, and a std-dev of 0.2:

```
class GaussianDistInstance(DistInstance):
    ...

    def sample(self):
        #sample = self.mean + torch.randn_like(self.mean) * self.std
        sample = 0 + torch.randn_like(self.mean) * 0.2  ### the only changes happen in this line 
        return sample
```

I use the previously posted environment to record the actions that Unity receives.
(there is only a single observations in every step. The observations always stays at 0. There are no rewards. Action-values are binned in increments of 10000 steps and written out to a file):

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Unity.MLAgents;
using Unity.MLAgents.Sensors;
using Unity.MLAgents.Actuators;

public class EntropyTestAgent : Agent
{


    int[] sampledActions = new int[401]; //actions will binned from -2 to 2 in increments of 0.01

    long myStepCount;
    

    // Start is called before the first frame update
    void Start()
    {
        myStepCount = 0;
        clearEntries();
    }


    void clearEntries()
    {
        //set all items to 0
        System.Array.Clear(sampledActions, 0, sampledActions.Length);
    }



    void saveSampledActionsToDisk()
    {
        //first best code I could find to write csv-files
               
        Debug.Log("writing to file " + Application.persistentDataPath + "\\sampledActions_" + myStepCount.ToString() + ".csv");

        System.IO.StreamWriter writer = new System.IO.StreamWriter(Application.persistentDataPath + "\\sampledActions_" + myStepCount.ToString() + ".csv");

        for (int i = 0; i < sampledActions.Length; i++)
        {

            writer.WriteLine(sampledActions[i]);
        }

        writer.Flush();
        writer.Close();

    }

    public override void CollectObservations(VectorSensor sensor)
    {
        sensor.AddObservation(0); //observation will never change
    }

    public override void OnActionReceived(ActionBuffers actions)
    {
        myStepCount++;
       

        //add action to sampledActions-array

        //get action
        float action;
        action = actions.ContinuousActions[0];

        //find index
        int indexToIncrease;
        indexToIncrease = (int)((action + 2)/0.01f);

        sampledActions[indexToIncrease]++;

        if ((myStepCount % 1000)==0)
        {

            EndEpisode();

            Debug.Log(base.CompletedEpisodes);

        }


        if ((myStepCount % 10000)==0)
        {
            saveSampledActionsToDisk();

            //clear all entries to get ready for next 10k actions
            clearEntries();
        }
    }

}
```

I would expect the actions to reflect a distribution that follows the previously specified mean=0, std=0.2. However, what I receive is this:

![grafik](https://user-images.githubusercontent.com/17814024/108771791-6a8d0580-755c-11eb-8679-a095793a8167.png)

**Environment (please complete the following information):**
- Unity Version:  Unity 2020.2.3f1
- OS + version: Windows 10
- _ML-Agents version_: Release_12 
- _Torch version_: 1.7.0+cu110
- _Environment_: 100-line-of-code custom-environment, see above

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by vincentpierre** [comment]
I **think** this is due to rescaling of the actions in the trainer.
When exporting the action, we actually clip between -3 and 3 and then divide by 3. (3 is very arbitrary)
I think this explains what you are seeing, with the actions having the same distribution but rescaled.
See here : https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents/mlagents/trainers/torch/action_model.py#L168

**Comment by Ihsees** [comment]
Ah, ok, that's easy enough to compensate. Thank you.

For reference, it also shows up here: https://github.com/Unity-Technologies/ml-agents/blob/b136878d4327c6bba8146f50ccb10862cad22570/ml-agents/mlagents/trainers/torch/agent_action.py#L36

Feel free to close this issue if it's desired behaviour or leave it open if you want to investigate. 
I for my part have the information I need.
