### ISSUE TITLE
Add an option to set the execution order of multiple agents

### ISSUE THREAD

**Issue by RedTachyon** [Unity-Technologies/ml-agents#4991]
Quick note: while I can't be 100% sure this is not possible right now, I haven't found any mentions of how to do that, hence I'm posting this as a feature request

**Is your feature request related to a problem? Please describe.**
My specific use case is that I have multiple agents in a shared scene, whose episodes need to be synchronized. To that end, I'm using a separate "fake" agent taking the role of a Manager which takes care of the whole scene, staying in sync with the other actual agents.

 Among other things, I use it to collect some statistics about the environment, so it's important to me that this happens either before other agents, or after them. However at the moment it's executed somewhere in the middle between them.

**Describe the solution you'd like**
What I'd imagine could work is adding something like a priority weight for each agent, so that when agents take actions in the same timestep (decision step), they are called in the order of e.g. ascending priority.

**Describe alternatives you've considered**
Currently I just put the manager activities into LateUpdate because none of the other agents use it.

**Comment by dongruoping** [comment]
Hi,

We are currently working on more features around multi-agent training and some of them will hopefully come in the next few releases. That includes a new interface that allows you to put agents into a group and enable collaborative behaviors. This should allow you to make sure the episodes are synchronized and do the management in a better way without creating a "fake agent".  

However, we have not yet supported synchronizing agent's action within a step but it does sound to be useful. Can you share a bit more about your use case and how does that help with your problem? Like is there any other use besides collecting statistics? How taking actions in specific order help with your case or you just need something happen before/after all agents have acted? We're actively working on a better support for multi-agent training and we'll put this in our road map. 

Internally tracked as [MLA-1797](https://jira.unity3d.com/browse/MLA-1797).

**Comment by RedTachyon** [comment]
So my original use case for a Manager agent was coordinating agents respawning after an episode ends. Each agent has some sort of objective of its own, but only after they're all achieved, the episode can end for everyone. This is no longer the case in my code, but I might very well come back to this at some point.

The other is collecting statistics - I want to log, at each decision step, the mean distance of an agent from its destination, whether or not the agent is in a collision right now, stuff like that. For consistency, it has to be either before any agents act and perhaps change their (internal) state, or after all of them do. Currently I'm still fighting with Unity to make this work consistently in CollectObservations, without any double measurements.

Why consistency is important - at the moment, each agent has a Collision flag, which is set to 0 during OnActionReceived, and to 1 whenever a collision happens. If I log statistics during OnActionReceived of the Manager, some agents may be prematurely "cleared". If I log statistics during CollectObservations, there's a double message when the episode ends (terminal step) and a new one begins (decision step). I'm still figuring out how to get around that.



FWIW, I'd extremely appreciate some more detailed description of the execution order, something like this but for ML-Agents https://docs.unity3d.com/Manual/ExecutionOrder.html

So far through reading obscure docs and experimentation I established the following (which I hope is correct):
1. Everything happens around FixedUpdates; therefore, using Update and LateUpdate will cause big troubles
2. First all agents collect observations, then all agents choose actions. Then I think the physics engine makes a step? And then collisions etc. are processed.
3. The order in which agents collect observations etc. is invariant, but arbitrary.

**Comment by dongruoping** [comment]
Thanks for the reply.

For coordinating agents respawning and controlling episode at a group level, the upcoming new interface `MultiAgentGroup` (not yet released) will be very helpful for that. It provides you a way to register/manage a collection of Agents to the group and handle episodes at the group level. Stay tuned and welcome to try it out and give us feedback once it's released!

The statistics collecting is a bit more tricky. Like you said doing it in either CollectObservations or OnActionReceived is kind of problematic. By default, the Academy steps during every FixedUpdate, but you can disable automatic stepping and manually call Academy.Instance.EnvironmentStep(). So the current best way to achieve what you're saying would be: disable the automatic Academy stepping and manually call Academy.Instance.EnvironmentStep(), collect the statistics, and then call the next EnvironmentStep(). In that case you can make sure the statistics is collected _after_ all agents executed the actions.

As to your summaries of the using of LateUpdate, if your scene and actions are very physics-based, you probably want the Agent stepping at a regular interval w.r.t. to the physics. The effect of that depends on your scene and it's probably ok in some cases. 

I see that the execution order might not be obvious to tell from the docs. I'll work on improving that.

**Comment by RedTachyon** [comment]
Thanks, this will be helpful. But I'm not exactly sure, where would I call Academy.Instance.EnvironmentStep()? Do I need a separate script that keeps track of everything, including the FixedUpdates etc?

**Comment by dongruoping** [comment]
Yes correct. You'll need a script like an environment controller that tracks the FixedUpdates or whatever stepping frequency in your case, and call Academy.Instance.EnvironmentStep() accordingly.

**Comment by dongruoping** [comment]
Update: the new interface `MultiAgentGroup` for multi-agent training is released our latest release (release 15)! You can find the API and examples of how to use it in our [documentation](https://github.com/Unity-Technologies/ml-agents/blob/release_15/docs/Learning-Environment-Design-Agents.md#groups-for-cooperative-scenarios). Welcome to checkout it out and leave us some feedback :)

Closing this issue since I think both your requests have been resolved (an interface to manage a group of agents, and collect stats after all agents taken their actions). If there's anything I'm missing, feel free to re-open it.
