### ISSUE TITLE
Windows : No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by gerardsimons** [Unity-Technologies/ml-agents#50]
On Windows 10 : When trying to run the 3DBall environment in the Jupyter Notebook I get this exception (showed in the game application when using a debug-enabled .exe). The Jupyter notebook then times out because of this
```

SocketException: No connection could be made because the target machine actively refused it.

  at System.Net.Sockets.Socket.Connect (System.Net.IPAddress[] addresses, System.Int32 port) [0x0011a] in <f044fe2c9e7e4b8e91984b41f0cf0b04>:0 
  at System.Net.Sockets.Socket.Connect (System.String host, System.Int32 port) [0x00007] in <f044fe2c9e7e4b8e91984b41f0cf0b04>:0 
  at ExternalCommunicator.InitializeCommunicator () [0x0004a] in C:\Users\XXXX\Git\ml-agents\unity-environment\Assets\ML-Agents\Scripts\ExternalCommunicator.cs:98 
```
I turned off Windows firewall so unsure what could cause this still? Do I need to run something as Administrator?

**Comment by seattlefella** [comment]
Have you properly configured the unity component?  External...  that is what caused this problem for me

**Comment by gerardsimons** [comment]
@seattlefella Yes I did..

**Comment by vincentpierre** [comment]
It might be because you have another program using the same port. Try changing the `worker_id` or the `base_port` when launching the environment.
```python
env = UnityEnvironment(file_name, worker_id=X, base_port=XXXX)
```

**Comment by gerardsimons** [comment]
Thanks that fixed it

**Comment by rubenaster** [comment]
I get the same error logged in the Unity ingame-console of the tennis-scene. Everything is set-up fine. Should something already listen to port 5005? 'Cause that's not the case. I've also tested several other free ports but none of them worked.
