### ISSUE TITLE
docs: improve mlagents python package version to install

### ISSUE THREAD

**Issue by StefanoCecere** [Unity-Technologies/ml-agents#5013]
since we are dealing with different package versions, it would be better in the docs to specify the version to be installed
for example in the 0.16.1 docs <https://github.com/Unity-Technologies/ml-agents/blob/release_2_verified_docs/docs/Installation.md>

```
pip3 install mlagents==0.16.1
```
instead of the generic
```
pip3 install mlagents
```

**Comment by chriselion** [comment]
I actually updated this a few months ago on the release_2_verified branch (https://github.com/Unity-Technologies/ml-agents/pull/4535) but must not have updated the `release_2_verified_docs` tag. That's updated now.

Thanks!
