### ISSUE TITLE
ZIP file is corrupted

### ISSUE THREAD

**Issue by alexArayaM** [Unity-Technologies/ml-agents#5016]
hi. i had donwloaded 5 times the zip file and every try to unzip to my local disk it shows me a message that tells 'the file is corrupted'. anybody else has the same problem ?. are there other url to download it ?.

**Comment by surfnerd** [comment]
Hi @alexArayaM,
If you are on Mac this might happen.  This isn't an ML-Agents bug, but an issue you have with GitHub.

**Comment by chriselion** [comment]
Which zip file are you trying to use, and what platform? As @surfnerd said, the zip files for releases or the `main` branch are generated by Github, not us. But I was able to download and unzip both `main` and `release_13` on mac and windows 10.

**Comment by alexArayaM** [comment]
Hi guys. Thanks for the reply. i tried to download from the main branch, on win 10. Now I am trying to download on other win 10 machine. Thanks and a last question: what is the size of the zip file on disk ?.
