### ISSUE TITLE
Can't add "com.unity.ml-agents.extensions" package from git url 

### ISSUE THREAD

**Issue by SlimGabsi** [Unity-Technologies/ml-agents#5022]
**Describe the bug**
unity is stuck in resolving packages when adding *com.unity.ml-agents.extensions* from git url instead of lcoally .

**To Reproduce**
( https://github.com/Unity-Technologies/ml-agents/blob/main/com.unity.ml-agents.extensions/Documentation~/com.unity.ml-agents.extensions.md)
1 Edit your project's `manifest.json` directly and add the following line to the `dependencies`
section:
```
"com.unity.ml-agents.extensions": "git+https://github.com/Unity-Technologies/ml-agents.git?path=com.unity.ml-agents.extensions",
```

**Console logs / stack traces**

**Screenshots**

**Environment (please complete the following information):**
- Unity Version: 2019.4.20f1
- OS + version: Windows 10 pro
- _ML-Agents version_: 1.7.2-preview
- _Torch version_:  1.7.0+cu110
- _Environment_: (which example environment you used to reproduce the error)

**Comment by surfnerd** [comment]
Hi @SlimGabsi,
Can you fill out the information in the issue template, please?  We need information like your version of Unity, OS, etc.
Cheers,
Chris

**Comment by SlimGabsi** [comment]
Hello *@surfnerd*  ,
info is filled 
ty

**Comment by surfnerd** [comment]
I am able to reproduce.  We recent switched our default branch to 'main' so maybe there is a bug in the package resolver.  I'll bring it up with their team and update this thread when I hear back.

**Comment by surfnerd** [comment]
Hi @SlimGabsi,
One of my fellow teammates was patient enough to wait for the resolution which completed in about 5 minutes.  The package manager team also notified us that they are landing optimizations that will (hopefully) make it into the next release of 2019.4.  I'm going to close this issue for now.  Thank you for your feedback and interest in ML-Agents.
Cheers,
Chris

**Comment by SlimGabsi** [comment]
Hi @surfnerd ,
Thank you for your quick respense , I will just add the package locally or create a repo for the package and add it via git url , both works for me . Cheers !
