### ISSUE TITLE
Documentation Bug: "vis_encoder_type" vs "vis_encode_type"

### ISSUE THREAD

**Issue by akTwelve** [Unity-Technologies/ml-agents#5037]
**Describe the bug**
The documentation says the parameter for the Visual Encoder Type is "vis_encoder_type" (encodeR), however the actual config parameter is "vis_encode_type" (encode) in all of the examples

**To Reproduce**
1. This page lists the parameter name as "vis_encoder_type" https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Training-Configuration-File.md
2. All of the config files use "vis_encode_type"

**Console logs / stack traces**
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
- Unity Version: N/A
- OS + version: N/A
- _ML-Agents version_: Release 1 through 13
- _Torch version_: N/A
- _Environment_: N/A

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by vincentpierre** [comment]
Fix made and merged (#5041). Thank you for raising this issue.
