### ISSUE TITLE
Sorter environment exception when training in Editor mode: Variable Length Observations are not supported by the trainer

### ISSUE THREAD

**Issue by Dastyn** [Unity-Technologies/ml-agents#5049]
**Describe the bug**
Attention mechanism is exactly what I was looking for, unfortunately the Sorter example environment and even so a new env of my own do not work properly, yielding the following exception:

`
UnityAgentsException: Variable Length Observations are not supported by the trainer
Unity.MLAgents.GrpcExtensions.GetObservationProto (Unity.MLAgents.Sensors.ISensor sensor, Unity.MLAgents.Sensors.ObservationWriter observationWriter) (at C:/Users/.../ml-agents/com.unity.ml-agents/Runtime/Communicator/GrpcExtensions.cs:424)
Unity.MLAgents.RpcCommunicator.PutObservations (System.String behaviorName, Unity.MLAgents.AgentInfo info, System.Collections.Generic.List`1[T] sensors) (at C:/Users/.../ml-agents/com.unity.ml-agents/Runtime/Communicator/RpcCommunicator.cs:330)
Unity.MLAgents.Policies.RemotePolicy.RequestDecision (Unity.MLAgents.AgentInfo info, System.Collections.Generic.List`1[T] sensors) (at C:/Users/.../ml-agents/com.unity.ml-agents/Runtime/Policies/RemotePolicy.cs:55)
Unity.MLAgents.Agent.SendInfoToBrain () (at C:/Users/.../ml-agents/com.unity.ml-agents/Runtime/Agent.cs:1126)
Unity.MLAgents.Agent.SendInfo () (at C:/Users/.../ml-agents/com.unity.ml-agents/Runtime/Agent.cs:1387)
Unity.MLAgents.Academy.EnvironmentStep () (at C:/Users/.../ml-agents/com.unity.ml-agents/Runtime/Academy.cs:573)
Unity.MLAgents.AcademyFixedUpdateStepper.FixedUpdate () (at C:/Users/.../ml-agents/com.unity.ml-agents/Runtime/Academy.cs:43)
`

If it may help a bit, until UnityRLCapabilities call, VariableLengthObservation is true, but then false at end of GetObservationProto (GrpcExtension.cs).

**To Reproduce**
mlagents-learn .\ml-agents\config\ppo\Sorter_curriculum.yaml
(change num_envs: 8 to 1, to make it work in editor mode).

**Environment:**
- Unity Version: Unity 2019.4.12f1
- OS + version: Windows 10
- _ML-Agents version_: latest `develop` branch from source
- _Torch version_: Version: 1.7.1+cu101
- _Environment_: Sorter
  ml-agents: 0.24.0,
  ml-agents-envs: 0.24.0,
  Communicator API: 1.4.0,
(Connected to Unity environment with package version 1.8.0-preview and communication version 1.5.0)

**Comment by surfnerd** [comment]
Hi, you need to install the trainers from the branch you got the sorter environment from.  It looks like you got the **last** release of the trainers.  Use `pip install -e ` syntax to install ml-agents-ebbs and ml-agents from the brach you are working with.

**Comment by Dastyn** [comment]
Thank you @surfnerd !
It is OK now.
