### ISSUE TITLE
No ppo file in the python folder

### ISSUE THREAD

**Issue by shovon421** [Unity-Technologies/ml-agents#505]
Where is the ppo file in the python folder, how can i train them, i was following udemy unity machine learning and cant find tyhe ppo file in inside the python folder of ml-agent.

**Comment by MarcoMeter** [comment]
Hi @shovon421 
I guess the Udemy Couse is not up-to-date since March 15th.
The PPO.ipynb has been removed.
Refer to the documentation on how to setup the environment and conduct the training:
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Getting-Started-with-Balance-Ball.md

**Comment by Fangh** [comment]
it's now called learn.py

**Comment by shovon421** [comment]
Would have been better if there would be video documentation of using learn.py

**Comment by eshvk** [comment]
Hi @shovon421, 
  We are happy to accept any suggestions you may have on improving the written docs for `learn.py`. Unfortunately, we don't have any plans right now to provide video documentation of that code.
