### ISSUE TITLE
In 3DBall project, code is different from github example explain page

### ISSUE THREAD

**Issue by Ladun** [Unity-Technologies/ml-agents#5051]
**Is your feature request related to a problem? Please describe.**
In 3DBall example, github description about reward is below.
"
Agent Reward Function:
+0.1 for every step the ball remains on it's head.
-1.0 if the ball falls off.
"
But actual code is not same that. In the actual code, it seems to be set as SetReward(0.1f), not AddReward(0.1f).

**Describe the solution you'd like**
It would be a good idea to replace the code SetReward(0.1f) in Ball3DAgent.cs and Ball3DHardAgent.cs with AddReward(0.1f).

**Additional context**
In the gridworld project with a similar description, I saw that the code is AddReward.
Gridworld Reward Description
"
Agent Reward Function:
-0.01 for every step.
+1.0 if the agent navigates to the goal position of the grid (episode ends).
-1.0 if the agent navigates to an obstacle (episode ends).
"

**Comment by vincentpierre** [comment]
Hi @Ladun 
Thank you for raising this issue. I think the confusion comes from the word step, which means different things in different contexts. Steps can be interpreted as a "decision point". In this case +0.1 per step for 3DBall is correct. 
I logged this issue as MLA-1838, and we will look into it.
