### ISSUE TITLE
Internal Brain with Visual Obs Error

### ISSUE THREAD

**Issue by NiloFreitas** [Unity-Technologies/ml-agents#506]
Hi, I am trying to run an Internal Brain with the .bytes file generated by my python implementation and the input placeholder receives a camera image that has shape [None,width,height, 1] (black and white). The vector obs size is 0.

However, I am getting the following errors:

```
> IndexOutOfRangeException: Index was outside the bounds of the array.
> (wrapper managed-to-managed) System.Object.ElementAddr_4(object,int,int,int,int)
> CoreBrainInternal.BatchVisualObservations (System.Collections.Generic.List`1[T] textures, System.Boolean BlackAndWhite) (at Assets/ML-Agents/Scripts/CoreBrainInternal.cs:535)
> CoreBrainInternal.DecideAction (System.Collections.Generic.Dictionary`2[TKey,TValue] agentInfo) (at Assets/ML-Agents/Scripts/CoreBrainInternal.cs:222)
> Brain.DecideAction () (at Assets/ML-Agents/Scripts/Brain.cs:241)
> Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:477)
> Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:507)

```

and 

```
> ArgumentException: An item with the same key has already been added. Key: IAgent (IAgent)
> System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at /Users/builduser/buildslave/mono/build/external/corert/src/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs:451)
> System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at /Users/builduser/buildslave/mono/build/external/corert/src/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs:234)
> Brain.SendState (Agent agent, AgentInfo info) (at Assets/ML-Agents/Scripts/Brain.cs:234)
> Agent.SendInfoToBrain () (at Assets/ML-Agents/Scripts/Agent.cs:566)
> Agent.SendInfo () (at Assets/ML-Agents/Scripts/Agent.cs:829)
> Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:475)
> Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:507)
```

Here is a print of the inspector:

![captura de tela de 2018-03-18 18-05-33](https://user-images.githubusercontent.com/26013740/37571107-f9e91b20-2ad6-11e8-88b9-f4b1b793023c.png)

Thank you for any help

**Comment by vincentpierre** [comment]
I think you have found a bug. Could you try an see if this [PR](https://github.com/Unity-Technologies/ml-agents/pull/509) solves your problem ?

**Comment by NiloFreitas** [comment]
That solved my problem! I'll be following the PR. Thanks.

**Comment by NiloFreitas** [comment]
Hi, 
That solved the errors, that now no longer appear.
However, the trained model when executed (play with the internal brain) does not behave as expected.
I'll be following the PR.
Thanks.

**Comment by awjuliani** [comment]
Hi @NiloFreitas,

One possibility for the decrease in performance from training to inference is that the visual quality settings in Unity may mean that the image the CNN receives changes. One quick way to test this is to set "Quality Settings" to the same number for both training and inference from within the Unity Academy component. A second way to test whether there is a bug in the Internal brain is to try running `learn.py` with `--load --slow` instead of `--train`.

**Comment by NiloFreitas** [comment]
Hi,
Of course! Thank you!
