### ISSUE TITLE
Remove Unity Analytics as a mandatory dependency of com.unity.ml-agents

### ISSUE THREAD

**Issue by JesseTG** [Unity-Technologies/ml-agents#5064]
**Is your feature request related to a problem? Please describe.**
I'm developing a game for a platform that Unity Analytics does not support. Since `ml-agents` depends on `com.unity.modules.unityanalytics`, this means that I can't use `ml-agents` on said platform.

**Describe the solution you'd like**
Only enable the features that use Unity Analytics if `com.unity.modules.unityanalytics` is installed in the project.

**Describe alternatives you've considered**
~~Manually removing the Unity Analytics DLL from the build pipeline. I don't know if this would work.~~ It wouldn't work as this is a compiler error. The only alternative is to work on something else while this issue is resolved.

**Additional context**
Setting aside the issue of compatibility, I'm removing unused core Unity modules from my project to keep the file size down. For example, my game doesn't use terrain so I'm excluding the terrain module.

**Comment by awjuliani** [comment]
Hi @JesseTG 

Thanks for bringing this to our attention. This package should only have an impact on the Editor, and not the builds containing ML-Agents. Can you share what error you are running into, and at what point it is occuring? It is when importing the package, or when trying to build for your platform? It would also be helpful to know the specific platform which you are having issues targeting, as that will help us to reproduce the issue.

**Comment by JesseTG** [comment]
> Hi @JesseTG
> 
> Thanks for bringing this to our attention. This package should only have an impact on the Editor, and not the builds containing ML-Agents. Can you share what error you are running into, and at what point it is occuring? It is when importing the package, or when trying to build for your platform? It would also be helpful to know the specific platform which you are having issues targeting, as that will help us to reproduce the issue.

The platform I'm using does not support Unity Analytics; when I set it to be the active build platform, all Unity Analytics APIs are simply unavailable, resulting in compiler errors. This occurs in the editor, so I assume it would be the same when building.

I get pretty much the same error in multiple places, all in `TrainingAnalytics` and `InferenceAnalytics`. Here's one of the errors:

```
[CompilerError] The type name 'AnalyticsResult' could not be found in the namespace 'UnityEngine.Analytics'. This type has been forwarded to assembly 'UnityEngine.UnityAnalyticsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' Enable the built in package 'Unity Analytics' in the Package Manager window to fix this error.
Compiler Error at Library\PackageCache\com.unity.ml-agents@1.8.0-preview\Runtime\Analytics\TrainingAnalytics.cs:67 column 17
65:               {
66:   #if UNITY_EDITOR
-->67:                   AnalyticsResult result = EditorAnalytics.RegisterEventWithLimit(eventName, k_MaxEventsPerHour, k_MaxNumberOfElements, k_VendorKey);
68:   #else
69:                   AnalyticsResult result = AnalyticsResult.UnsupportedPlatform;

The type name 'AnalyticsResult' could not be found in the namespace 'UnityEngine.Analytics'. This type has been forwarded to assembly 'UnityEngine.UnityAnalyticsModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' Enable the built in package 'Unity Analytics' in the Package Manager window to fix this error.
```

Unfortunately, I can't publicly say which platform I'm targeting as its details are confidential. However, there are other useful things I can say:

- You can easily reproduce this issue for any target platform by simply disabling `com.unity.modules.unityanalytics` in the package manager.
- My target platform doesn't offer the `UnityEngine.Analytics` assemblies, even if `com.unity.modules.unityanalytics` is enabled.
- I believe this issue affects multiple NDA-protected platforms and that the same fix should work for all of them.

**Comment by surfnerd** [comment]
Is the platform you are using under NDA?  Or is there a define that the analytics code uses that we aren't aware of?

**Comment by JesseTG** [comment]
> 
> 
> Is the platform you are using under NDA? Or is there a define that the analytics code uses that we aren't aware of?

The platform itself is under NDA. Well, its development details. The platform itself is quite famous (and odds are good you have one).

No unusual `#define`s are in use, to my knowledge; the Analytics DLLs are just not included in the compiler's search path when my platform is active.

**Comment by surfnerd** [comment]
Thanks for the info @JesseTG,
I'm going to create a PR that makes the analytics module an optional dependency.  This should address your problem and hopefully anyone else that is using an NDA platform.

**Comment by JesseTG** [comment]
> Thanks for the info @JesseTG,
> I'm going to create a PR that makes the analytics module an optional dependency. This should address your problem and hopefully anyone else that is using an NDA platform.

Thank you! I appreciate it.

**Comment by surfnerd** [comment]
@JesseTG, 
which version of unity are you using, and which version of the package are you using?

**Comment by surfnerd** [comment]
He @JesseTG,
#5109 was merged into `main`.  Please let us know if this fixes your issue.
Thanks,
Chris

**Comment by JesseTG** [comment]
> 
> 
> He @JesseTG,
> #5109 was merged into `main`. Please let us know if this fixes your issue.
> Thanks,
> Chris

With pleasure. When's the next release?

**Comment by surfnerd** [comment]
There is a release coming out this week, but it will not contain these changes. The changes will make it into the April release alongside the changes to make physics and physics2d optional dependencies as well.

**Comment by JesseTG** [comment]
> There is a release coming out this week, but it will not contain these changes. The changes will make it into the April release alongside the changes to make physics and physics2d optional dependencies as well.

Thank you! I'll report back if there are any problems.
