### ISSUE TITLE
Incomplete sentence in installation documentation

### ISSUE THREAD

**Issue by Musubee** [Unity-Technologies/ml-agents#5075]
**Describe the bug**

There is an incomplete sentence in the installation docs under the "Clone the ML-Agents Toolkit Repository (Optional)" section:
"The --branch release_14 option will switch to the tag of the latest stable release. Omitting that will get the main branch which is potentially"

I plan to submit a PR to change the Installation.md file, so that the above sentence reads "... which is potentially unstable."

**To Reproduce**
1. Go to docs/Installation.md
2. The sentence can be found in the second paragraph of the "Clone the ML-Agents Toolkit Repository (Optional)" section.

**Console logs / stack traces**
Please wrap in [triple backticks (```)](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make it easier to read.
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
- Unity Version: [e.g. Unity 2020.1f1]
- OS + version: [e.g. Windows 10]
- _ML-Agents version_: (e.g. ML-Agents v0.8, or latest `develop` branch from source)
- _Torch version_: (you can run `pip3 show torch` to get this)
- _Environment_: (which example environment you used to reproduce the error)
N/A

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by surfnerd** [comment]
Whoops, that's my fault.  If you want to submit a PR please do an assign me to it.

**Comment by surfnerd** [comment]
Merged in #5078
