### ISSUE TITLE
Performance with a large number of agents

### ISSUE THREAD

**Issue by RedTachyon** [Unity-Technologies/ml-agents#5086]
**Is your feature request related to a problem? Please describe.**

Disclaimer: I'm not an expert on Unity internals, so it's not impossible I'm missing something obvious.

I'm working with an environment with a large number of agents - at the moment it's 21 agents in a single copy of the environment, and to accelerate training I have 8 copies of the environment in my scene, so a total of 168 agents, but ideally I'd like to go even higher. The agents are mostly homogeneous, with one agent in each environment serving the role of a manager to collect statistics.

However, the action dispatching seems to be a bottleneck. When I'm looking through the Unity profiler, each agent separately (and sequentially) calls RequestDecision which takes about 0.05ms, and together that's about 8ms. The entire PlayerLoop step takes about 13ms, so it takes up a good majority of the runtime. 

One thing that confuses me is that the RequestDecision function seems to be rather simple, so I'm not sure what causes the relatively long runtime. 

**Describe the solution you'd like**
The first thing that comes to mind is that the RequestDecision step could be parallelized, at least within the same Behavior. I'm not sure how well that would work with environments that don't use a DecisionRequester, but my intuition is that mostly it is the DecisionRequester that controls the env?

**Describe alternatives you've considered**
What I'm considering, if I really need the performance, is just having a single centralized agent which handles actions and observations appropriately - but this would go against the whole point of having multiagent support in ML-Agents, and would require a lot of monkey-patching to handle everything appropriately. Alternatively, I might use a subprocess-based parallelization of the environment on the Python end, but I really wanted to abuse the possibility of having multiple copies of the env within a single Unity scene, with the physics efficiently parallelized by the engine.

**Comment by surfnerd** [comment]
Hi @RedTachyon,
are you experiencing this during training?  Don't forget that for every decision request during training, there is a batched call to the python process over gRPC to send observations and retrieve actions.  Could you provide more information about what your agent's action/observation space is? What sensors/actuators/onActionReceived/CollectObservations look like?

It's hard to diagnose issues without any of this information. 
Cheers,
Chris
