### ISSUE TITLE
Make both physics modules optional dependencies (com.unity.modules.physics and com.unity.modules.physics2d)

### ISSUE THREAD

**Issue by JesseTG** [Unity-Technologies/ml-agents#5104]
**Is your feature request related to a problem? Please describe.**
I'm working on a 2D game that uses ML-Agents. Since my game is 2D, I'm only using the 2D physics module (`com.unity.modules.physics2d`). I'd like to be able to remove the 3D physics module (`com.unity.modules.physics`) via the package manager to keep the file size of my game down.

If I were working on a 3D game, I'd want to do the opposite; keep the 3D physics while removing the 2D physics.

**Describe the solution you'd like**
Make both `com.unity.modules.physics` and `com.unity.modules.physics2d` optional dependencies, i.e. only use code from those modules if they're actually installed.

**Describe alternatives you've considered**
The alternative would be to simply leave both physics modules installed, even though I'm only using one of them. I can do this and it would work (and admittedly the impact wouldn't be huge), but I would feel kind of gross.

**Additional context**
This feature request is **not** related to #5064; that ticket concerns ML-Agents outright breaking for platforms that don't support a particular module. This ticket only concerns an optimization, namely the ability to reduce file size by removing unused dependencies.

**Comment by surfnerd** [comment]
Hi @JesseTG,
We have logged this request as MLA-1848 internally and will update this issue when work has been completed on this request.  Thanks for your feedback.
Cheers,
Chris

**Comment by surfnerd** [comment]
This was merged in #5112 Thanks!
