### ISSUE TITLE
no models (.bytes files) generated?

### ISSUE THREAD

**Issue by kurgandk** [Unity-Technologies/ml-agents#511]
Im running 0.3 on the beta2018.11  I run the training through jupyter, and it runs nicely, but it looks like no .bytes files are generated?

**Comment by awjuliani** [comment]
Hi @kurgandk,

Can you share information on what jupyter notebook you are using? In v0.3 we have removed training via jupyer, and now use `learn.py` for training instead. Please see here: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-ML-Agents.md for more information.

**Comment by kurgandk** [comment]
I followed the docs for windows 
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md
and installed the tf plugin (it works fine with the pre generated .bytes files)

and ran the notebook this way:
(ml-agents) C:\Users\kurgan\Downloads\ml-agents-master\python>jupyter notebook

**Comment by kurgandk** [comment]
I was following this:
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Getting-Started-with-Balance-Ball.md

anyway it looks like it is working from the command line. thanks!
