### ISSUE TITLE
Toggle for ignore trigger interactions on rayperception sensor

### ISSUE THREAD

**Issue by StevePeters-US** [Unity-Technologies/ml-agents#5153]
Physics ray and sphere casts have an option to disable trigger interactions. Adding a toggle to the rayperceptionsensor which would modify the QueryTriggerInteraction parameter for the ray and sphere casts in the

internal static RayPerceptionOutput.RayOutput PerceiveSingleRay(
RayPerceptionInput input,
int rayIndex,
out DebugDisplayInfo.RayInfo debugRayOut
)

method of the RayPerceptionSensor.cs class would be helpful for cases where a large trigger collider is used on our agents.

**Comment by surfnerd** [comment]
Hey @StevePeters-US,
Thanks for your request.  I have logged it internally as  MLA-1870 and will update this thread when work has been completed on it.
Cheers,
Chris
