### ISSUE TITLE
Reward based on dynamic number of decisions

### ISSUE THREAD

**Issue by mamaorha** [Unity-Technologies/ml-agents#5163]
**Is your feature request related to a problem? Please describe.**
Currently rewarding process is calculated when requesting new decision, in "turn based games" that doens't hold as the agent need to take multiple decisions on the same round based on the situation (it can be 1 action and it can be 5) and be rewarded for the entire "round".

**Player A**
decide how to use his cards (he can play multiple cards - number is dynamic based on the cards he gets).
end his turn

**Player B**
decide how to react using his cards (again number of actions is dynamic based on his cards)

when player B is done and the **Round** is over we can decide how to reward the agents.

**Describe the solution you'd like**
i see 2 ways this can be handled:
1. a "toggle" saying i want to manually report when to batch all of the decisions and reward based on that.

example:
toggle - "ManualDecisionBatching" / "TurnBased"
when this is set to true:
every decision request will be tied together by saving the observables + actions taken until there is a call to "SubmitBatch" / "EndTurn"

2. adding a new function:
public void RequestDecisions(Function<Boolean> predicate); - that will turn on a flag where the "fixedUpdate" / start a coroutine that can check the predicate and as long its true -> collect "observables + actions", when its false - accumulate the reward and clear it.

**Describe alternatives you've considered**
what i currently did is on the "fixedUpdate" i checked if its my turn, if so i "requestDecision".
my problem is with "addReward" as i need to reward the entire "round" outcome rather than the single actions made during the player turn.

**Additional context**
https://forum.unity.com/threads/turn-base-game.1071383/#post-6951131

**Comment by mamaorha** [comment]
another way to solve this is to request decisions with "identifier" for example
requestDecision(string identifier) -> in a turn base game that identifier can be the "round number"
add rewards are summed based on that identifier - when a new one arrives (exmaple next round) accumulate the reward for all the actions on that round and start accumolating new reward for the current round

**Comment by surfnerd** [comment]
Hi @mamaorha,
I have logged this feature request internally as  MLA-1877.  

Have you tried just setting the reward at the end of the round if the agent wins that round?  Or are you trying to give intermediate rewards before the round is over?

**Comment by mamaorha** [comment]
I have tried but it seems it didnt understand what it get the rewards for.
(Combination of mobs he buys / lanes he attack)
ran for few days and it still doesnt get any good vs real players.
Note the Elo is going up and the rewards mean as well but still feels like
it doesnt link why it geta rewarded.

בתאריך יום ג׳, 23 במרץ 2021, 00:52, מאת Chris Goy ***@***.***
