### ISSUE TITLE
Manually getting action

### ISSUE THREAD

**Issue by white-cold** [Unity-Technologies/ml-agents#5165]
Currently decisions can only be requested, they can not be directly controlled. This matters little when decisions are continually requested, but it becomes troublesome when one wants to investigate the output of a trained network to a specific input, since one needs to setup the input, request the decision, and then wait for another frame to actually see the action.

Would it be possible to add a function that allows immediate control of a model, getting the action as a function of a specific input sensor vector, without any delay?

**Comment by surfnerd** [comment]
Hi @white-cold,
You can do this with [barracuda manually](https://docs.unity3d.com/Packages/com.unity.barracuda@1.3/manual/ModelOutput.html), but we don't have an API at the ML-Agents level.

**Comment by surfnerd** [comment]
If you'd like to request a feature, please do so.  Otherwise, I think questions like these are better suited to the [ML-Agents Forum.](https://forum.unity.com/forums/ml-agents.453/)

**Comment by white-cold** [comment]
@surfnerd I would like to request this as a feature, I am afraid I can't find how to add the request label

**Comment by surfnerd** [comment]
Hi @white-cold,
I've logged this request internally as MLA-1876 and we will update this issue when work has been completed on it.
Cheers,
Chris
