### ISSUE TITLE
Python UnityEnvironment object missing behavior_specs

### ISSUE THREAD

**Issue by vinitrinh** [Unity-Technologies/ml-agents#5183]
Have created an environment and connected to python successfully, but there is no behavior_specs.
```
from mlagents_envs.environment import UnityEnvironment
env = UnityEnvironment(file_name='single_drone_build3/UnityEnvironment.exe')
list(env.behavior_specs)
Out[1]: []
```
When developing the game on the editor, I have ensured that there is a "Behavior Parameters" component added to my agent.
![image](https://user-images.githubusercontent.com/28703546/112294869-42650380-8cce-11eb-8091-eaca92d475fe.png)

Is there a step that I'm missing so that `list(env.behavior_specs)` is not empty?

**Environment (please complete the following information):**
- Unity Version: 2019.4.17f1
- OS + version: Windows 10
- _ML-Agents version_: 1.7.2-preview
- mlagents_envs: 0.25.0

**Comment by vinitrinh** [comment]
When I build the default environment e.g. Gridworld, I encounter the same problem.

**Comment by surfnerd** [comment]
I believe you have to call reset first.

**Comment by vinitrinh** [comment]
ah yes thats it, i knew i missed something out. Thanks.
