### ISSUE TITLE
Why the root.DecodeAction has so many GC?

### ISSUE THREAD

**Issue by stkman** [Unity-Technologies/ml-agents#5187]
![image](https://user-images.githubusercontent.com/6999099/112466194-89bbc480-8da0-11eb-85fd-53e3805ff228.png)

if i don't use ML,  my cpu main is 10ms,  but if the ML start working it's going to 1600ms......what should i do?

**Comment by stkman** [comment]
emm... I know what happen ,my game is match3, and has many different celltypes.... the more types the more gc...

**Comment by surfnerd** [comment]
Hi, 
The GitHub issues page is for feature requests or bugs you have found and want to report.  Could you please post this question in the [forums](https://forum.unity.com/forums/ml-agents.453/) and I'll answer you there.

**Comment by surfnerd** [comment]
And please provide more information about your environment, like what sensors/actuators are you using? What does your agent code look like?
