### ISSUE TITLE
Need some help with 3DBall example

### ISSUE THREAD

**Issue by karthikveeramani** [Unity-Technologies/ml-agents#52]
Setting up dependencies and building 3DBall example for the first time using readme ...

While running the PPO notebook "load the environment" step, there is a timeout. Have tried passing a different workerid and port but that doesn't help. Running all this on Windows 10. 

Could someone figure out what went wrong? I pretty much followed instructions in the readme and didn't get fancy with anything.

![image](https://user-images.githubusercontent.com/8732969/30993409-c095566c-a463-11e7-8fef-f8609c993ad2.png)

**Comment by eagleEggs** [comment]
Is the brain set to external within the inity project?

**Comment by karthikveeramani** [comment]
@eagleEggs  Yes it is

**Comment by karthikveeramani** [comment]
Anyone? Developers?

**Comment by FadhliSani** [comment]
I'm having this issue as well. not sure if it's the env_name that's making this issue.
now I'm stuck

**Comment by karthikveeramani** [comment]
@FadhliSani  I did change the env_name to "3DBall" or something like that. And the path as well (it was "ppo" by default).

**Comment by FadhliSani** [comment]
mine looks like this

![image](https://user-images.githubusercontent.com/24985345/31006972-78313124-a531-11e7-979b-c495fc20afe6.png)

**Comment by karthikveeramani** [comment]
Ping ... Devs, help please?

**Comment by vincentpierre** [comment]
@karthikveeramani Maybe one of these is the reason : 
 * It is not possible to rename the .exe file after it has been built.
 * Make sure you build the right scene when building
 * Make sure the brain is set to external like @eagleEggs said.
 * Make sure you build the unity game in the right folder and replace the old version
Could you also tell me what happens when you directly open the built environment ? (double click on it) 
Could you make a development build and tell us if there is an error in the C# code ?

**Comment by vincentpierre** [comment]
@FadhliSani  I think your issue is because your "game" has either been renamed or is not in the `python` folder since the error says the filename does not match. Also, make sure that when you build, you target the right platform and architecture.

**Comment by karthikveeramani** [comment]
@vincentpierre 

It is not possible to rename the .exe file after it has been built.
-- I tried renaming the exe to 3DBall.exe.renamed manually, it worked (screenshot below)

![unity_exe_renamed](https://user-images.githubusercontent.com/8732969/31037476-e4467e2a-a525-11e7-876a-53fec2f6b7fe.PNG)

Make sure you build the right scene when building
-- screenshot below to show that I'm building the 3DBall scene
![unity_build_settings](https://user-images.githubusercontent.com/8732969/31037496-f90e0454-a525-11e7-8d47-61ef5fa97817.PNG)

Make sure the brain is set to external like @eagleEggs said.
-- confirmed, see screenshot
![unity_brain_settings](https://user-images.githubusercontent.com/8732969/31037500-026d46b8-a526-11e7-91d6-748a8b4633fc.PNG)

Make sure you build the unity game in the right folder and replace the old version
-- I cleaned out the binaries and rebuilt to the same folder (ml-agents\python), no change

Could you also tell me what happens when you directly open the built environment ? (double click on it)
-- After the Made With Unity screen, it hangs. screenshot below.
![unity_env_hangs](https://user-images.githubusercontent.com/8732969/31037530-39b52046-a526-11e7-8b12-786636f7b74b.PNG)

Could you make a development build and tell us if there is an error in the C# code ?
-- I did enable Development Build settings (as in the earlier screenshot). As for the errors:
1) No error popped up as a dialog box when I double clicked the built exe, it appeared to be hanging with the spinner cursor. 
2) Within the editor, I tried hitting the play button and that appeared to run the scene without errors.
3) From the editor, when I hit Build & Run as opposed to going through the build settings menu, I saw a crash and a crash log. Same thing happened when I re-ran as administrator. Attached crash logs below. Opening the crash.dmp file with visual studio, I found this to be of interest:

![unity_crash](https://user-images.githubusercontent.com/8732969/31037755-6ba66dca-a527-11e7-855f-3c83b6a2e439.PNG)

[Crash_2017-09-29_145826.zip](https://github.com/Unity-Technologies/ml-agents/files/1345795/Crash_2017-09-29_145826.zip)

Now your turn :)

**Comment by karthikveeramani** [comment]
By the way, I noticed that when I double clicked the exe, memory usage goes to 98-99% while it hangs.

**Comment by vincentpierre** [comment]
@karthikveeramani I think I was not clear, when I said "It is not possible to rename the .exe file after it has been built." I meant that you can rename it but if you do, it would not work. But this does not seem to be you issue.  
Are you able to run the scene with a player brain in the editor? If you build with a player brain, does the game open ?

**Comment by eagleEggs** [comment]
Are you running this from a pre-existing project? Can you create a blank scene in that project, build it, and see if it runs? Also, try creating this in a new project if not already. Redownload the entire package, dont change PPO parameter, keep everything default and try to rebuild the ball example.

**Comment by karthikveeramani** [comment]
@vincentpierre Do you have some instructions on how to run the scene with a "player brain in the editor"? Sorry I am new to to machine learning and not that familiar with Unity.

@eagleEggs I did a git clone of your project and opened straight from there. I can check Monday and do a git reset to blow away anything that may have changed. I can also try creating a new project, but are you suggesting I copy the 3DBall scene into that from the existing project? I could use some details on that part.

**Comment by vincentpierre** [comment]
@karthikveeramani You sent a screen shot of your brain component in a previous message, change the `Type of Brain` to `Player` and then try to run the scene in the editor and finally, build the game for windows machine. I am trying to figure out if the "Thread tried to read from or write to a virtual address..." is an issue specific to ML-Agents or if it happens with every game you build.

**Comment by karthikveeramani** [comment]
@vincentpierre  got it. don't have that computer with me now but will do it Monday and report back.

**Comment by Adamage** [comment]
Hey. I have completely the same thing!

But for me, the first time I build the environment, it worked, though the simuilation launched in like 200x100 pixels resolution. THen I decided to turn on the Resolution Dialogue, changed the resolution. Unfortunately the timeout sprung. I turned it off again, and it cannot connect to Environment from Python again.

**Comment by awjuliani** [comment]
@Adamage,

It is better to adjust resolution from within the `Academy` inspector window (see here: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Agents-Editor-Interface.md#academy), rather than the resolution window, since this allows the resolution to automatically be set, and there is no risk of timeout from delayed response.

**Comment by Adamage** [comment]
Thanks @awjuliani . I found it. The PPO example works flawlessly, although I need to change worker Id often. Actually on time scale 1, it converged to a reward~500 in a matter of minutes. ML agents will be my go to from now on...

**Comment by karthikveeramani** [comment]
@vincentpierre  @eagleEggs   I tried your suggestions and found a few things ...

It looks like the access violation may be outside the scope of ML project. I created a blank project, added a blank scene. Built it with similar settings (run in background, disable resolution display dialog) and it crashed with a similar error. I tried reverting each of those changed player settings back and that didn't help. Tried running as admin and no luck there too. The crash appears to be inside UnityPlayer.dll.

"
UnityPlayer.dll caused an Access Violation (0xc0000005)
  in module UnityPlayer.dll at 0033:e4ec05d5."

Googling shows that that error is kinda broad and many people have faced it for various reasons. I'm stuck at this point. I realize it may be outside the scope of this project, but being Unity devs, if you have some wise words I would appreciate it. On the other hand if you don't want to pollute this thread with unrelated things, you can close it off, perhaps pointing me to some lead I can go investigate.

**Comment by karthikveeramani** [comment]
Btw, I use Unity 2017.3.0b2 Personal 64bit (DX11)

**Comment by karthikveeramani** [comment]
Hey guys, an update. I solved this problem.  I uninstalled Unity 2017.3.0b2, installed 2017.1, and I could run through the entire 3DBall example just fine. You may want to consider fixing the problem I saw in the newer version.

Thank you for all your support, I appreciate it!

**Comment by awjuliani** [comment]
Thanks @karthikveeramani for bringing this to our attention. We will look into it to ensure 2017.3 works properly with ML-Agents.

**Comment by srmojuze** [comment]
Hi the same issue is encountered in 2017.1.1 ...However 2017.1.0 works. Cheers.

**Comment by karthikveeramani** [comment]
I suggest adding a note to the readme page at the project root to install the specific version that works, until you guys fix this problem. It will save noobs like me a few days of debug time.

**Comment by krishnanpc** [comment]
Hey guys,
had the same error @karthikveeramani  had, but used 2017.1.0 , now the Basic works, but I get this error while training. The build is fine, (when i double click open the executable, it is working fine). The training throws this error leaving the executable running in a Not Responding condition.

![image](https://user-images.githubusercontent.com/3471153/32019668-3c1b477c-b9ce-11e7-8ffa-32fc0161b45f.png)

I then changed the instantiation of env to:
env = UnityEnvironment(file_name=env_name, worker_id=2, base_port=8080)
as @Adamage  suggested, but then get a different error 
![image](https://user-images.githubusercontent.com/3471153/32019958-01b0122e-b9cf-11e7-85c7-77da79090e17.png)

![image](https://user-images.githubusercontent.com/3471153/32019910-e5fde6b4-b9ce-11e7-961d-7c2fa87d54c3.png)

Any help is appreciated. :)

**Comment by Mohan-Zhang-u** [comment]
12/23/2017. It is not working in both 2017.1.0f3 and 2017.3.0.f3.
Already set to external, the unity window popped up, the ball failed to the pad and then the game stuck.

Error message is the same as above:
---------------------------------------------------------------------------
timeout                                   Traceback (most recent call last)
~\Desktop\ml-agents\python\unityagents\environment.py in __init__(self, file_name, worker_id, base_port, curriculum)
     98                 self._socket.listen(1)
---> 99                 self._conn, _ = self._socket.accept()
    100                 self._conn.settimeout(30)

d:\softwares\python3\lib\socket.py in accept(self)
    204         """
--> 205         fd, addr = self._accept()
    206         # If our type has the SOCK_NONBLOCK flag, we shouldn't pass it onto the

timeout: timed out

During handling of the above exception, another exception occurred:

UnityTimeOutException                     Traceback (most recent call last)
<ipython-input-15-a1598afa4a92> in <module>()
----> 1 env = UnityEnvironment(file_name=env_name, curriculum=curriculum_file)
      2 print(str(env))
      3 brain_name = env.external_brain_names[0]

~\Desktop\ml-agents\python\unityagents\environment.py in __init__(self, file_name, worker_id, base_port, curriculum)
    105                     "The Unity environment took too long to respond. Make sure {} does not need user interaction to "
    106                     "launch and that the Academy and the external Brain(s) are attached to objects in the Scene."
--> 107                     .format(str(file_name)))
    108 
    109             if "apiNumber" not in p:

UnityTimeOutException: The Unity environment took too long to respond. Make sure ball does not need user interaction to launch and that the Academy and the external Brain(s) are attached to objects in the Scene.

**Comment by zzzhacker** [comment]
same error as in 2017.2 @Mohan-Zhang-u

**Comment by aliBUT** [comment]
Hi, i am using Unity 2017.3.0f3 (64-bit). When I run Basics.ipynb it gives me this error
![capture](https://user-images.githubusercontent.com/36599640/36352496-605ebcda-14d3-11e8-991f-1d4f02381f86.PNG)

**Comment by Adamage** [comment]
Did you try to change this line?
 So that it looks like this

env = UnityEnvironment(file_name=env_name, **worker_id=2**, **base_port=8080**)

**Comment by sysmaya** [comment]
Uncheck DEFAULT IS FULL SCREEN
in Player Settings.
![sin titulo](https://user-images.githubusercontent.com/18316343/38169909-ceac99c6-353c-11e8-80ff-d09e3307d79e.png)
