### ISSUE TITLE
Problem with building the 3d ball example

### ISSUE THREAD

**Issue by cutecrimefighter** [Unity-Technologies/ml-agents#521]
When I use that command to build the 3d ball example:

python python\learn.py <F:\Pasta-para-projetos\Unity-Projects\ml-agents\python\basdg.exe> --train

i got this message:
Usage:
      learn (<env>) [options]
      learn --help

and then the terminal dont do anything. I sincerely don't know how to proceed

**Comment by jo3w4rd** [comment]
Don't put the <>'s around the path. (Those were in the docs to show what part of the command you had to replace with real values.)

**Comment by cutecrimefighter** [comment]
Thank you very much my dear friend
