### ISSUE TITLE
Self-Play Curriculum with Elo system

### ISSUE THREAD

**Issue by MagMueller** [Unity-Technologies/ml-agents#5224]
I want to combine Self-Play and Curriculum learning. The actual problem for me is the measurement in the curriculum file. I can just use reward or progress.
With "reward" I have problems in a competitive Multi Agent setting, because if one player wins, the other loses.  And because I use self play, they use the same brain. (Is it possible to use the same brain in competitive Multi Agent learning?)

Reward looks like this:
<img width="281" alt="Bildschirmfoto 2021-04-06 um 11 49 31" src="https://user-images.githubusercontent.com/67061560/113692761-2ac64b80-96ce-11eb-92b7-a42df133dce2.png">
So I can't use "reward" in the curriculum file. 

The other possibility is "progress", but it is defined as Steps/MaxSteps. This would just work if you want, that your agent needs long time in your environment. So it will jump in the next Level, if its above your threshold, but I want that my Agent is really fast, so it should upgrade, if it is below a threshold. (Would be one solution for me if i could specify that).

While thinking about my problem, i found this: https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Training-Configuration-File.md#note-on-reward-signals 
A Elo system for self play. (cool idea:)

The Elo progress in my run looks like this:
<img width="339" alt="Bildschirmfoto 2021-04-06 um 12 00 49" src="https://user-images.githubusercontent.com/67061560/113694196-bd1b1f00-96cf-11eb-9f0b-5271aa316410.png">

So i think this would be a cool measurement for my curriculum file. For Example if the agent is above a threshold of 1250 Elo, upgrade to the next level.

My game:
1. Level:
<img width="661" alt="Bildschirmfoto 2021-04-06 um 11 33 38" src="https://user-images.githubusercontent.com/67061560/113691498-c35bcc00-96cc-11eb-899e-58edea473d2b.png">
2 same agents, who have to catch each other. With a checkpoint system I detect who catches whom.

With a curriculum I want to increase size and level of difficulty, after they have learned some skills.

Conclusion:
Thank you for your amazing  work and it would be cool to have more options in the Curriculum file.

**Comment by dongruoping** [comment]
Hi,

Thanks for bringing up a good point. Using ELO as a lesson completion measure is more reasonable in this case.
We're considering adding more measures or even custom ones for more flexibility curriculum learning and we'll prioritize it when possible.

On the other hand, I think you have a bit misunderstanding of how "progress" works. The Steps/MaxSteps is referring to the current/max step in the trainer settings which you specified in trainer config, and not the agent's max step. It specifies what proportion of the whole training you want to spend on a lesson. For example you can to train on the first lesson for 20% of the steps, and the rest 80% on the second lesson.

**Comment by dongruoping** [comment]
Internally tracked as [MLA-1906](https://jira.unity3d.com/browse/MLA-1906).

**Comment by MagMueller** [comment]
Hey,
it sounds great 👍 😃

thank you for clarifying that, I will try it out.

**Comment by MagMueller** [comment]
Do you know in which python file I could implement it for myself?
