### ISSUE TITLE
getting started documentation does not get you started ;)

### ISSUE THREAD

**Issue by joslat** [Unity-Technologies/ml-agents#5232]
**Describe the bug**
Follow the getting started documentation, https://github.com/Unity-Technologies/ml-agents/blob/release_15_docs/docs/Getting-Started.md until you reach the installation steps.

- it does not indicate where is the unity project that contains the example environments. 
   - looking at external videos I figured out It is \ml-agents\Project
- Opening the Package manager and navigating to the ML-Agents package...  there is no way to find the "3D Ball" sample and importing it. image attached..
![image](https://user-images.githubusercontent.com/9831011/114069135-f1910580-989e-11eb-9919-e2136949c9a5.png)
  - Also, apart from "clicking it", there should appear a 3D Ball sample?   
  - But, if we open the sample it is already imported so... what are we doing with clicking it... clicking it where? 
- Step 3 cannot be followed (Find the 3D Ball Sample and click "import".
- Step 4 seems to be working, but steps 2 and 3 do not seem to make too much sense... and are pretty confusing. Or am I missing something? 

Attaching the installation section of https://github.com/Unity-Technologies/ml-agents/blob/release_15_docs/docs/Getting-Started.md
![image](https://user-images.githubusercontent.com/9831011/114069421-46348080-989f-11eb-85d4-1494e720f462.png)

**To Reproduce**
As described in the error, follow the "Installation" steps or better, try to follow them...

**Comment by surfnerd** [comment]
Hi @joslat,
I added this documentation and it is definitely misleading now that you've brought it up. If you have already opened up the `Project` Folder, the 3DBall example should be under `Assets/ML-Agents/Examples/3DBall`.  The sample will show up when the package is actually installed from the package manager, not when you clone the git repo and open up the `Project` project.  I'll update the documentation and have you review it for me along with another team member.  Thank you for the important feedback.
Cheers,
Chris

**Comment by joslat** [comment]
Thanks, outstandingly fast feedback!!

I'll keep a watch on it, let's see If I can get this working and train something that makes sense :)

**Comment by surfnerd** [comment]
Hey @Jconrad15,
The sample shows up in version 1.9.1-preview and later.  I will call that out in the docs when I get to the task of fixing this issue. Thank you for the feedback!

**Comment by Jconrad15** [comment]
Hi @surfnerd 

Thanks for the very fast reply.  That fixed my issue.

I've included another screenshot with the 3D ball import option for others who stumble across this thread:
![Capture2](https://user-images.githubusercontent.com/83470418/116737159-b79ab700-a9a5-11eb-98aa-dbb99e501609.PNG)

**Comment by i3games** [comment]
>  The sample shows up in version 1.9.1-preview and later. I will call that out in the docs when I get to the task of fixing this issue. Thank you for the feedback!

The sample does *not* show up in 2.1.0-exp.1 Preview on Unity 2020.3 for Mac. Installed through package manager.

<img width="792" alt="Screenshot 2021-09-03 at 02 54 51" src="https://user-images.githubusercontent.com/830492/131935182-17d9682d-329d-4cca-adcc-ff2c3ecea31d.png">
