### ISSUE TITLE
No field in Agent(Script) to drag and drop Target GameObject 

### ISSUE THREAD

**Issue by holohuang** [Unity-Technologies/ml-agents#5242]
**Describe the bug**
Though this issue may not be a bug but rather me lacking experience with Unity...
I followed the guide in ["Making a New Learning Enviroment"](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Learning-Environment-Create-New.md#making-a-new-learning-environment) to the second step of ["Final Agent Setup in Editor"](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Learning-Environment-Create-New.md#final-agent-setup-in-editor)

> Drag the Target GameObject in the Hierarchy into the Target field in RollerAgent Script.

I searched for [tutorial on Youtube](https://youtu.be/17fHVV3hoQc?t=977) and tried to do so but the mouse become banned icon on Inspector region. 
And found out that I don't even have the field to drag Target GameObject into like those in the tutorial.

↓The picture from tutorial
![The picture from my Unity](https://user-images.githubusercontent.com/77768344/114291134-8ec68680-9ab7-11eb-8abe-75b9965c4510.png)

↓The screenshot from my Unity
![圖片](https://user-images.githubusercontent.com/77768344/114291147-aef64580-9ab7-11eb-9727-988553e5a8ce.png)

I did some search for similar issue like [this one](https://github.com/Unity-Technologies/ml-agents/issues/2283) and do found some error on my console
![圖片](https://user-images.githubusercontent.com/77768344/114291328-1cef3c80-9ab9-11eb-9811-ee0ecf995562.png)
but [the answer from another issue to those error](https://github.com/Unity-Technologies/ml-agents/issues/957#issuecomment-403138553) seems out of date and not sure the relation with my main dragging problem.

**Environment (please complete the following information):**
- Unity Version: 2019.4.18f1
- Window 10 64x
- _ML-Agents version_1.7.2
- _Torch version_1.7.0 + cu110

Wish for hints pointing out where I made mistake, thanks you all!

**Comment by andrewcoh** [comment]
Hi @holohuang 

The slot for the game object will not appear until your scripts have compiled, which can't happen since there are errors.  Without seeing more of your code, it looks like you might be missing the `using Unity.MLAgents;`, `using Unity.MLAgents.Sensors;`, or `Unity.MLAgents.Actuators;`directives or are not inheriting from the Agent class.
