### ISSUE TITLE
NavMeshAgent does not work

### ISSUE THREAD

**Issue by r-lipton** [Unity-Technologies/ml-agents#526]
Hello

I am using a NavMeshAgent component in my environment, making a character to move to a target destination. Using the player brain, it works in Unity and it works also when I export it to Windows and Linux.
However, when I run the environment using python (in an Ubuntu instance), the character does not move. There is no error in the log file. The training can run, but the character does not move.

Any idea?
Thanks

**Comment by r-lipton** [comment]
Just tested in Windows using python, same results :(

**Comment by r-lipton** [comment]
I was using `CharacterController.Move` to move the character. A workaround is to modify directly the `transform.position`

**Comment by r-lipton** [comment]
It looks like the `NavMeshAgent` is updating periodically only every ~100 steps.

**Comment by RossMelbourne** [comment]
I am using NavMeshAgent but moving my character manually.  I call SetDestination and then using nextPosition and steeringTarget to navigate.

**Comment by unityjeffrey** [comment]
thanks for filing.  we've logged this bug and will report back once we have a resolution.

**Comment by xiaomaogy** [comment]
@r-lipton Do you see any error message when you tested it in the Windows platform? More information would be helpful here.

**Comment by r-lipton** [comment]
No, there is not error when tested on Windows neither on Linux

**Comment by xiaomaogy** [comment]
@r-lipton I'm not really familiar with NavMeshAgent, and so not able to reproduce what bug you have here. Maybe it would be helpful if you can share the steps and the source code you have, so that we can reproduce the bug you have.

**Comment by xiaomaogy** [comment]
@r-lipton I am closing this thread due to inactivity, but feel free to re-open it if you desire.
