### ISSUE TITLE
--results-dir training command line training option not working

### ISSUE THREAD

**Issue by fredleefarr** [Unity-Technologies/ml-agents#5268]
**Describe the bug**
Using the command line option "--results-dir" did not create a different results directory.

**To Reproduce**
Run an "mlagents-learn" command with --results-dir="myresults" to see if the myresults directory is created.

**Environment (please complete the following information):**
- Unity Version: 2020.2.2f1
- OS Windows 10
 Version information:
  ml-agents: 0.25.0,
  ml-agents-envs: 0.25.0,
  Communicator API: 1.5.0,
  PyTorch: 1.7.1+cpu

**To Fix**
I dug into the source code, and found the following in cli_utils.py (line 192):

    argparser.add_argument(
        "--results-dir", default="results", help="Results base directory"
    )

Adding "action=DetectDefault" resolved the issue for me:

    argparser.add_argument(
        "--results-dir", 
        default="results", 
        help="Results base directory",
        action=DetectDefault
    )

**Comment by dongruoping** [comment]
Hi,

Please follow our template for reporting a bug so that we are able to get all necessary information to look into the issue.

To your question, can you provide the ML-Agents version are you on?

**Comment by fredleefarr** [comment]
Hi, sorry, applied to both versions 15 & 16 (and probably earlier versions, but I haven't checked those)

**Comment by dongruoping** [comment]
Thanks, I'm able to reproduce it and it's indeed a bug in our code. I'll get a fix out soon.

Thanks for raising this!

**Comment by dongruoping** [comment]
Hey @fredleefarr this is fixed on the current main branch now.
The fix will go into the next release which is planned on next week.

Thanks again for reporting this!

**Comment by fredleefarr** [comment]
@dongruoping Glad I could help.
