### ISSUE TITLE
Error when launching ml-agent learning

### ISSUE THREAD

**Issue by Nilon123456789** [Unity-Technologies/ml-agents#5275]
**Describe the bug**
Geting this error 
```RuntimeError: The shape ObservationSpec(shape=(90,), dimension_property=(<DimensionProperty.UNSPECIFIED: 0>,), observation_type=<ObservationType.DEFAULT: 0>, name='StackingSensor_size5_VectorSensor_size18') for observation 0 in demonstration                         do not match the policy's ObservationSpec(shape=(42,), dimension_property=(<DimensionProperty.UNSPECIFIED: 0>,), observation_type=<ObservationType.DEFAULT: 0>, name='StackingSensor_size2_VectorSensor_size21').```

ML agent worked fine before

**To Reproduce**
1. run comand : mlagents-learn config.yaml --run-id=Test5 --force
2. press play
3. see error in terminal

**Console logs / stack traces**
Please wrap in [triple backticks (```)](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make it easier to read.
```RuntimeError: The shape ObservationSpec(shape=(90,), dimension_property=(<DimensionProperty.UNSPECIFIED: 0>,), observation_type=<ObservationType.DEFAULT: 0>, name='StackingSensor_size5_VectorSensor_size18') for observation 0 in demonstration                         do not match the policy's ObservationSpec(shape=(42,), dimension_property=(<DimensionProperty.UNSPECIFIED: 0>,), observation_type=<ObservationType.DEFAULT: 0>, name='StackingSensor_size2_VectorSensor_size21').```

**Screenshots**

**Environment (please complete the following information):**
- Unity Version: Unity 2020.3.1f1
- OS + version: Windows 10
- _ML-Agents version_: 0.25.0
- _Torch version_:1.7.1+cu110

**Comment by dongruoping** [comment]
Hi,

From the error message, it seems like you're using imitation learning and the demonstrations have different observation size than the the setup in the scene.
Please make sure you're using demonstrations from the training scene, with the exact same observations and actions setup.

Does that solve your problem?

**Comment by Nilon123456789** [comment]
Yes it solved my problem
