### ISSUE TITLE
--time-scale=1 runs FixedUpdate() too often

### ISSUE THREAD

**Issue by Ihsees** [Unity-Technologies/ml-agents#5284]
Before I start: I'm still running on an old version of ml-agents, but I didn't see any pull-requests about this topic

```
  ml-agents: 0.24.0,
  ml-agents-envs: 0.24.0,
  Communicator API: 1.4.0,
  PyTorch: 1.7.1+cu110
```

**Describe the bug**
When training an agent, FixedUpdate() is called more often than specified in Time.FixedTimestep. 
FixedDeltaTime as reported by Time.fixedDeltaTime remains at 0.01
timeScale as reported by Time.timeScale remains at 1

**To Reproduce**

For debugging I have this very simple agent, that does close to nothing: 
-It only provides a single (never-changing) observation of 0.
-It writes timing-info to the Log.

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Unity.MLAgents;
using Unity.MLAgents.Sensors;
using Unity.MLAgents.Actuators;

public class NullAgent : Agent
{

    long FixedUpdateCounter;
    long lastRenderedFrames;
    float lastFixedUpdateTime;

    long receivedActionCount;

    // Start is called before the first frame update
    void Start()
    {
        receivedActionCount = 0;
        FixedUpdateCounter =0;
    }

    public override void CollectObservations(VectorSensor sensor)
    {
        sensor.AddObservation(0); //observation will never change
    }

    public override void OnActionReceived(ActionBuffers actions)
    {
        receivedActionCount++;

        if ((receivedActionCount % 1000) == 0)        {
            EndEpisode();

            Debug.Log(base.CompletedEpisodes);
        }
    }

    private void FixedUpdate()
    {
        FixedUpdateCounter = FixedUpdateCounter + 1;

        if (FixedUpdateCounter % 100 == 0)
        {

            float renderedFPS = (Time.renderedFrameCount - lastRenderedFrames) / (Time.realtimeSinceStartup - lastFixedUpdateTime);
            float FixedUpdatesPerSecond = 100 / (Time.realtimeSinceStartup - lastFixedUpdateTime);

            //uncomment this if you still have the Monitor class in your code. 
            //Makes looking at the number a bit easier than in the console
            //Monitor.Log("renderedFrames per Second (100 steps average)", renderedFPS.ToString());
            //Monitor.Log("FixedUpdates per Second (100 steps average)", FixedUpdatesPerSecond.ToString());

            Debug.Log("renderedFrames per Second (100 steps average): " +  renderedFPS.ToString());
            Debug.Log("FixedUpdates per Second (100 steps average): " + FixedUpdatesPerSecond.ToString());

            lastFixedUpdateTime = Time.realtimeSinceStartup;
            lastRenderedFrames = Time.renderedFrameCount;

            //uncomment this if you still have the Monitor class in your code. 
            //Makes looking at the number a bit easier than in the console
            //Monitor.Log("fixedDeltaTime setting", Time.fixedDeltaTime.ToString());
            //Monitor.Log("timeScale setting", Time.timeScale.ToString());

            Debug.Log("fixedDeltaTime setting: " + Time.fixedDeltaTime.ToString());
            Debug.Log("timeScale setting: " + Time.timeScale.ToString());

        }
    }
}
```

I also have a decision-requester at Decision Period 1.

My default settings in the Project settings are these:
```
Fixed Timestep: 0.01
Maximum Allowed Timestep: 2
Time Scale: 1
Maximum Particle Timestep: 0.1
```

When I hit "Play" in the editor (without starting mlagents-learn from console) I get the expected behaviour:
```
FixedUpdates per Second (100 step average): 99,93
fixedDeltaTime setting: 0,01
timeScale setting: 1
```
I also get warnings that the Heuristic method is beeing called but not implemented. I can safely ignore this warning for this test.

I will now start training with this config file:
config\NullAgentTest_config_4.yaml
```
behaviors:
  NullAgentTest:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1000 
      buffer_size: 15000 
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 10
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 100000
    time_horizon: 100 
    summary_freq: 10000
    threaded: false
```

and this command:
`mlagents-learn config\NullAgentTest_config_4.yaml --run-id=bench_nullAgentTiming-005f-config4-Editor-tsUndefined-noThreading`

This gets me this (reasonable) output:
timeScale goes up to 20 (which must be the default for ml-agents) and I get more FixedUpdates per Second than before. I'm not getting 2000 (=20 * 100) FixedUpdates per Second, but that just means that my system performance is maxed out. Nothing unusual yet. 
```
FixedUpdates per Second (100 step average): 312,89
fixedDeltaTime setting: 0,01
timeScale setting: 20
```

However, if I start with a timescale-argument of 1...
`mlagents-learn config\NullAgentTest_config_4.yaml --run-id=bench_nullAgentTiming-006-config4-Editor-ts1-noThreading --time-scale=1`

... I get these timing infos:
```
FixedUpdates per Second (100 step average): 230,62
fixedDeltaTime setting: 0,01
timeScale setting: 1
```

What I had expected here is to get 100 FixedUpdates per Second, since I'm running at timescale 1. 
So this is definetely not expected behaviour. 

What I can't tell if it's potentially another problem (all the different Unity-time settings are sometimes still a mystery to me) is that Unity still reports a fixedDeltaTime setting of 0,01 - could that be messing with physics?

**Console logs / stack traces**
_None_

**Screenshots**
_None_

**Environment (please complete the following information):**
- Unity Version: 2021.1.2f1
- OS + version: Windows 10
- _ML-Agents version_: Release 13
- _Torch version_: 1.7.1+cu110
- _Environment_: simple "NullAgent" described above

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by dongruoping** [comment]
Hi,

The tricky thing I see from your description is that you're measuring "FixedUpdates per second" using `Time.realtimeSinceStartup`. How `FixedUpdate()` being called is configured by `Time.FixedDaltaTime` which is relative to the "in-game" time. So it's likely to get unexpected result if you're using real time since in-game time can differ a lot from wall-clock time. 

Btw anything you described isn't specific to ML-Agents - you can make an arbitrary MonoBehavior script and get the same  results without involving an Agent. How `FixedUpdate()` and `timeScale` work are determined by Unity engine and ML-Agents only provides options for you to configure those parameters. So I'd suggest that you would find better audience on the general Unity community forum instead of here for this type of questions.

**Comment by Ihsees** [comment]
> The tricky thing I see from your description is that you're measuring "FixedUpdates per second" using Time.realtimeSinceStartup. 

I disagree. From what I've read having a constant number of "FixedUpdates per Second" is exactly why it's there in the first place: to guarantee that physics can be calculated with a fixed time in between them - even if the FPS-numbers (rendered frames) are inconsistent. 
The fact that I get close to 100 "FixedUpdates Per Second" during inference shows me that FixedUpdate() is called every 10ms (as specified by fixedDeltaTime).
But during training the example above with its 100.000 steps would finish after around 300s.
If I had any objects in my scene they would move 3x as fast as during inference. So not at all at a "timescale of 1".

> Btw everything you described isn't specific to ML-Agents - you can make an arbitrary MonoBehavior script and get the same results without involving an Agent.

The described behavior only happens when I'm connecting to the Editor via mlagents-learn. I suspect that mlagents is somehow triggering FixedUpdate to be called faster. Which is nice for training speedups and wouldn't normally be a problem. But I'm *wanting* it to run at timescale=1 to benchmark some timings.

**Comment by dongruoping** [comment]
Ok I think I understand your question better now. The reason that you're seeing the difference between hitting play and connecting to the Editor via `mlagents-learn` is that the python trainer sets the engine parameters differently. Specifically it sets `Time.captureFrameRate` to 60 by default which is default as 0 in the editor. `Time.captureFrameRate` does not change the speed of the simulation at all, but it might affect the frequency on calling `Updates` and `FixedUpdates`. So you're seeing your measurements are changing but the physics are not moving x times faster compared to inference. If you set to 0 I would expect you to get similar results as in inference. For all the engine configuration set by `mlagents-learn` please see [this doc](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Python-API.md#engineconfigurationchannel).

FYI, [this graph](https://docs.unity3d.com/ScriptReference/Time.html) might give you more information about how time works in Unity. `FixedUpdate` guarantee that physics are calculated within a fixed time - which refer to Time.fixedDeltaTime and not necessary maps to Time.realtimeSinceStartup.

**Comment by Ihsees** [comment]
Yes! 

Thank you, adding `--capture-frame-rate=0` to my arguments brings FixedUpdateSteps/s close to 100. Thank you!
