### ISSUE TITLE
How can I create a custom observation sensor?

### ISSUE THREAD

**Issue by TimothyHo584** [Unity-Technologies/ml-agents#5286]
I'm using ML-agents 1.7.2, and I want to add an Occupancy Grid as a new observation.
Is there any sensor can show where is occupied (output an 2d array like a map) or how can I add my own script as a new ml-agents sensor?

Thanks.

**Comment by AREID221** [comment]
Add one hot observation for every grid square, make each square state be represented by a numeric (0 = empty, 1 = full, etc) as part of a larger structure like an Enum. You could then do a foreach loop (depending on how you set it up), observing the state of each and returning a square if it meets x condition (in your case, the learning algorithm would recognize 1 as occupied and 0 as unoccupied). As for how you are adding/removing occupants to a grid square, I cannot advise you further, but you should be changing the state either at a point in code where an addition/subtraction is made to a square or having each square observe objects within it and returning 0 or 1 to reflect that check.

**Comment by dongruoping** [comment]
Also for general ML-Agents questions (not bug report or feature request), our official forums are a preferred place for asking questions and getting discussions: https://forum.unity.com/forums/ml-agents.453//, thanks.

**Comment by mbaske** [comment]
> Is there any sensor can show where is occupied (output an 2d array like a map) or how can I add my own script as a new ml-agents sensor?

> If that doesn't fit your use case and you want to write your own, you should to derive your custom sensor form the ISensor interface and implement all the interface methods. Also you'll need to make your own SensorComponent to create the custom sensor and attach this SensorComponent to your agent.

@TimothyHo584 I've attempted something like this with my custom grid sensor https://github.com/mbaske/grid-sensor 
You can ignore all the gameobject specific stuff and just check out the basic sensor implementation, which seems to do what you are looking for.
