### ISSUE TITLE
UnityEnvironment seed not working

### ISSUE THREAD

**Issue by julienroyd** [Unity-Technologies/ml-agents#5297]
Hi,

Seeding of the environment does not seem to work properly. Two calls to env.action_space.sample() won't give the same result on two different runs.

**To Reproduce**

Here is the minimal example I used. I first created an executable of the 3DBall environment according to the directions given here: https://github.com/Unity-Technologies/ml-agents/blob/release_12_docs/docs/Learning-Environment-Executable.md.

I then ran this example below (replacing the path to the executable):
```
import numpy as np
import random
from mlagents_envs.environment import UnityEnvironment
from gym_unity.envs import UnityToGymWrapper

SEED = 123

random.seed(SEED)
np.random.seed(SEED)

exec_path = "/home/user1/Desktop/3DBall/build/3DBall"
unity_env = UnityEnvironment(file_name=exec_path, no_graphics=True, seed=SEED)
env = UnityToGymWrapper(unity_env, uint8_visual=False, flatten_branched=False, allow_multiple_obs=False)

print(env.action_space.sample())
```

**Environment (please complete the following information):**
- Unity Version: 2019.4.19f1
- OS + version: Ubuntu 20.04
- _ML-Agents version_: 1.8.0
- _Torch version_: 1.8.1
- _Environment_: 3DBall

**Comment by chriselion** [comment]
Hi @julienroyd,
`env.action_space` is a gym.Shape, so it has its own seeding scheme. It looks like they don't provide any way to set a global seed (I think it falls through to [here](https://github.com/openai/gym/blob/a5a6ae6bc0a5cfc0ff1ce9be723d59593c165022/gym/utils/seeding.py#L55) if a seed isn't specified).

We can change the `UnityToGymWrapper` code to set the `action_space` seeds after creation using the provided seed. In the meantime, I think you'll need to call `env.action_space.seed(SEED)`.

The internal tracker ID for this is MLA-1952; I'll try to get a fix today.

**Comment by chriselion** [comment]
@julienroyd - here's the PR: https://github.com/Unity-Technologies/ml-agents/pull/5303
Do you want to try that out and see if it solves the problem for you?

**Comment by julienroyd** [comment]
@chriselion, it works with your workaround (setting env.action_space.seed() manually) but when I run the same example above on the PR branch I get this error:

```
line 13, in <module>
    env = UnityToGymWrapper(unity_env, uint8_visual=False, flatten_branched=False, allow_multiple_obs=False)
  File "/home/user1/anaconda3/envs/cbp/lib/python3.7/site-packages/gym_unity/envs/__init__.py", line 77, in __init__
    if self._get_n_vis_obs() == 0 and self._get_vec_obs_size() == 0:
  File "/home/user1/anaconda3/envs/cbp/lib/python3.7/site-packages/gym_unity/envs/__init__.py", line 234, in _get_n_vis_obs
    for shape in self.group_spec.observation_shapes:
AttributeError: 'BehaviorSpec' object has no attribute 'observation_shapes'
```

Not sure what is going on here :/

**Comment by chriselion** [comment]
Hmm, I think you might have some weird combination of using the branch's code and an installed PyPI package. Line 234 on the branch is something different:
https://github.com/Unity-Technologies/ml-agents/blob/b394d2a2d6a4cb059833bc8faaf0e15fa3e4d17a/gym-unity/gym_unity/envs/__init__.py#L233-L235
