### ISSUE TITLE
After about a hundred thousand steps (hundreds of episode) error "No episode was completed since last summary. Training."

### ISSUE THREAD

**Issue by idzee** [Unity-Technologies/ml-agents#5304]
I was training my agent until after about 150 000 steps, it throws "No episode was completed..." error. Previously I got the same error but fixed after I fix the behaviour name in Unity editor and my training config. The previous error happened from the start of training but this one happened mid training.

Unfortunately I lost the training cmd log because I closed the wrong cmd prompt, but here is the screenshot of the Tensor Log 
![Screenshot 2021-04-22 203653](https://user-images.githubusercontent.com/27879091/115723906-a69ce500-a3aa-11eb-8e01-64e3ae473665.jpg)
![Screenshot 2021-04-22 203714](https://user-images.githubusercontent.com/27879091/115723920-a8ff3f00-a3aa-11eb-866c-0154048dd538.jpg)
![Screenshot 2021-04-22 203733](https://user-images.githubusercontent.com/27879091/115723925-a997d580-a3aa-11eb-8a66-92fd5b64c878.jpg)
![Screenshot 2021-04-22 203742](https://user-images.githubusercontent.com/27879091/115723929-aac90280-a3aa-11eb-9adb-c6b89e0fd7d2.jpg)

The flat part of the graphs is when the error happen. The error somehow disappear after I stop the training and resume the training but will reappear again as shown in the graph

**Environment**
- Unity Version: [Unity 2019.4.20f1]
- OS + version: [Windows 10]
- _ML-Agents version_: ML-Agents v2.0.0-exp.1 (copied from github at 30/3/2021)
- _Torch version_: 1.8.1+cpu
- _Environment_: Self created environment

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by idzee** [comment]
I changed the match max time from 30s to 60s mid training. I changed it after the error happened so I doubt that was the problem as indicated by the graph (changed max time at around step 200k error happened at 150k)

Error also happened after my monitor screen blacked, but it wasn't sleeping. I'm not sure whether this is the reason as the third time the error happened (step 500k) it happened right at the start of the training

**Comment by idzee** [comment]
This is my training config.
![Screenshot 2021-04-22 205334](https://user-images.githubusercontent.com/27879091/115726351-d9e07380-a3ac-11eb-8c1d-894aac476dde.jpg)

After the agent reached 500k step, I increased the max step to 700k

**Comment by chriselion** [comment]
The "No episode was completed since last summary" message is not necessarily an error, it just information that since the last summary (which is `summary_freq` agent steps, in your case 2000) no episodes were ended. You should make sure that the episodes are actually ending, by either
* setting Agent.MaxStep to a non-zero value
* calling Agent.EndEpisode() after a certain number of steps
* calling SimpleMultiAgentGroup.EndGroupEpisode() (if you're using groups).
Also note that `summary_freq` refers to the total number of agents' steps, so if you add more agents (for example, by running with --num-envs=8) you'll get to `summary_freq` faster, possibly before any agent reaches their `MaxStep`.

Aside from the error, it's not clear to me what problem you're having? Does the agent look like it's behaving well?

**Comment by idzee** [comment]
I kept the max step as 0 as I've set the EndEpisode() to trigger after a set of time with this script. "timeout" being the one that trigger the EndEpisode() and restart that reset agent position and everything.

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class scRestart : MonoBehaviour
{
    // Start is called before the first frame update
    public float maxGameTime;
    public float elapsedTime;

    void Start()
    {
        maxGameTime = 60f;
    }


    void FixedUpdate()
    {
        if(elapsedTime>maxGameTime){
            EventManager.TriggerEvent("timeout", new EventParam());
            elapsedTime = 0f;
        }else{
            elapsedTime += Time.deltaTime;
        }
    }

    void Update() {
        
        if (Input.GetKeyDown(KeyCode.R))
        {
            EventManager.TriggerEvent("restart1", new EventParam());
            EventManager.TriggerEvent("restart2", new EventParam());
        }
    }
    void OnMouseClick(){
        //SceneManager.LoadScene(SceneManager.GetActiveScene().buildIndex);
    }
}
```

I'm training symmetrical adverserial agent, does that count as a group. There are only 2 agent in total, one in each team. I didn't set the parameter for environment number so I assume it would be only 1.

As seen on the graphs, the episode length is +-350steps and +-700 steps (after change). I think this should be enough for the summary to catch up considering there's only two agent. And if they didn't it's weird that suddenly there's suddenly no episode summary after hundreds of episode and consistently none after. But, i will keep this in mind and try to increase the summary size.

My agent is learning, but it's still not up to what I intended them to do. I'm afraid, this error means that after a certain episode, my agent stop learning and the model just went haywire. Considering I'm planning to create my own custom learning algorithm, I wish I could get the agent learn with the already built algorithm. So I could minimize the window of where things went wrong.




Below is the screenshot of a new training session I did with some tweak to the hyperparameter and my agent action output. While tweaking, I tried to run the training, and it throws the No Episode, then I tweak again but still error, but then it somehow didn't in this version. I didn't change the behaviour name in the config nor unity editor.
![image](https://user-images.githubusercontent.com/27879091/115941300-068cac00-a4cf-11eb-8aba-05385cd1dfdd.png)

Also, this time it throws no episode from the start of training. Another thing I would note is, in this version the episode length is +-1400 steps and summary is 2000, so summary being less than episode length might be the case.
![image](https://user-images.githubusercontent.com/27879091/115941966-f0341f80-a4d1-11eb-95d6-94991dd430c7.png)


This is the training config
![image](https://user-images.githubusercontent.com/27879091/115941860-83208a00-a4d1-11eb-8c8c-408a60a699d4.png)


I will update on this with increased summary freq



Added : While writing this comment, I decided to review my agent code and tried to comment out the name of the agent when it end it's episode. Apparently only one agent actually end the episode. This seems to be caused by the other agent somehow doesn't receive the timeout trigger. I'm ashamed that I didn't thought of fixing the timeout trigger when I fixed my restart trigger. I will update on this after i fixed it.

**Comment by idzee** [comment]
It seems that that is the problem. No error appeared after I fixed the trigger and increased my summary freq to 10k.
![image](https://user-images.githubusercontent.com/27879091/115946980-ee2c8980-a4ee-11eb-8208-494c0843933d.png)

My agent is still not behaving how I wished it to be but I think that's another problem on it's own
