### ISSUE TITLE
Unity mlagent standalone keep crashing after training couple hours on Windows

### ISSUE THREAD

**Issue by xiumin1** [Unity-Technologies/ml-agents#5314]
**Describe the bug**
I made a customized Unity environment and also use customized RL algorithms to do the training, it is running on vscode. After 2 to 8 hours training, the training crashed in two different ways.
1, when I setup the training steps to 1,000~5,000 steps during each episode, the training just terminated with "The Unity environment took too long to respond" report.
2, when I setup the training steps to 10,000 steps each episode, the training freeze half way and nothing is reported, only the VSCode editor shows "The window is no longer responding, you can reopen or close the window or keep waiting". And the chrome browser also crashed. Need to reopen vscode and chrome to use them again.

**Environment (please complete the following information):**
- Unity Version: Unity 2020.1.0b16
- OS + version:  Windows 10
- _ML-Agents version_: mlagent release 12

com.unity.ml-agents (C#) | v1.7.2
ml-agents (Python) | v0.23.0
ml-agents-envs (Python) | v0.23.0
gym-unity (Python) | v0.23.0
Communicator (C#/Python) | v1.3.0

- _Torch version_: 1.7.1
- _Environment_: customized environment

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by chriselion** [comment]
It sounds like your environment is crashing or hanging, which is not a bug with ML-Agents. Are there any logs from it, or are you able to get a callstack from it when the python side stops?

**Comment by xiumin1** [comment]
![snapshot](https://user-images.githubusercontent.com/42013223/115974892-f4cdf780-a514-11eb-8584-5adef2126fb5.png)
Thanks for replying, for steps less than 10,000, it terminate in this way as shows in the pic, "The unity environment took too long to respond." For steps more than 10,000, it simply freezes half way during the training, no callstack shows.

**Comment by chriselion** [comment]
I think you need to attach a debugger or add some extra logging to your environment, and find out what's causing it to stop responding. A common case of this is an infinite loop in user code.

**Comment by xiumin1** [comment]
Thanks for the suggestion, the issue solved. I tried the memory profiler and found out that there is an old script I used to store log info has not setup a size limitation during training, which caused memory leak issue.

**Comment by chriselion** [comment]
Cool, glad you were able to figure it out.
