### ISSUE TITLE
Is it possible to resume training?

### ISSUE THREAD

**Issue by GeriBP** [Unity-Technologies/ml-agents#532]
So, if I do a trainnig session, lets say a 5.0e5 steps session. Can I do 5.0e5  more steps starting from the result of the previous training?

**Comment by Hengoo** [comment]
You can add --load to your command. For me it would be like this:
python learn.py name --run-id=13 --train --load

The run id has to be the same as the run you want to resume, and you have to increase the max steps to your new maximum (so 10e5 in your case)

**Comment by GeriBP** [comment]
Thats exactly how its done. Thanks!
