### ISSUE TITLE
Document how `MaxCount` in the yaml file and the gameobject in editor differ

### ISSUE THREAD

**Issue by buddha314** [Unity-Technologies/ml-agents#5321]
**Is your feature request related to a problem? Please describe.**
I have noticed that under a variety of circumstances, the `StepCount` get set to 1 and never increments.  I was trying to trouble shoot this when I noticed that the sample `yaml` and the Editor both have a `max_steps` parameter.  I don't see how they are related.

**Comment by vincentpierre** [comment]
`Max Step` in the Agent parameters corresponds to the number of Decisions the Agent will make before it will begin a new episode (regardless of wether or not EndEpisode() was called). This is to make sure the Agent will nit stuck itself and never be able to complete the task. Think of it as a timeout. See [here](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Learning-Environment-Design-Agents.md#agent-properties) for more information.

`Max Step` in the yaml config file corresponds to the total number of experience points collected for training. See [here](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Training-Configuration-File.md#common-trainer-configurations) for more information. (The choice of names for these two is unfortunate)

This does not look like a proper feature request issue, so I will close it. I encourage you to as in the forums if you have general questions about ML-Agents and to post a bug issue if you encounter a bug.
