### ISSUE TITLE
Cannot use generated .onnx model

### ISSUE THREAD

**Issue by lukebandy** [Unity-Technologies/ml-agents#5334]
When I drag the generated .onnx file into the agent's model field (after copying from results to assets) an error is instead produced:

```
NullReferenceException: Object reference not set to an instance of an object
Unity.MLAgents.Inference.BarracudaModelParamLoader.CheckModel (Unity.Barracuda.Model model, Unity.MLAgents.Policies.BrainParameters brainParameters, Unity.MLAgents.Sensors.SensorComponent[] sensorComponents, Unity.MLAgents.Policies.BehaviorType behaviorType) (at Library/PackageCache/com.unity.ml-agents@1.0.7/Runtime/Inference/BarracudaModelParamLoader.cs:152)
Unity.MLAgents.Editor.BehaviorParametersEditor.DisplayFailedModelChecks () (at Library/PackageCache/com.unity.ml-agents@1.0.7/Editor/BehaviorParametersEditor.cs:108)
Unity.MLAgents.Editor.BehaviorParametersEditor.OnInspectorGUI () (at Library/PackageCache/com.unity.ml-agents@1.0.7/Editor/BehaviorParametersEditor.cs:68)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass58_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <2f1c602eae0d45c293fff3e3aef759fa>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

Unity Version: 2019.4.17f1
OS: Windows 10
ML-Agents: 0.26
ML-Agents Package: 1.0.7
PyTorch: 1.7.1+cu110
Environment is freshly set up

**Comment by vincentpierre** [comment]
Hi @lukebandy 

It looks like the version of the trainers you use and the C# package you use are several versions appart. According to [this page](https://docs.unity3d.com/Packages/com.unity.ml-agents@1.0/manual/index.html) the version 1.0.7 of the ml-agents package only works with trainers on versions 0.16.1 to 0.20.0. You could either downgrade your trainers to version 0.20.0 or upgrade your Unity package to a newer version.

**Comment by lukebandy** [comment]
My mistake was not enabling preview packages in Unity's package manager, which was why everything was out of sync as you say!
