### ISSUE TITLE
Best practice for checking episode done

### ISSUE THREAD

**Issue by rapsealk** [Unity-Technologies/ml-agents#5338]
**Before we start..**
Currently, I am using `terminal_rewards` signal to check episode status(on going or done). It worked well with using only `Agent` class for single-agent environment, but something went wrong after using `SimpleMultiAgentGroup` for implementing multi-agent environment.
I'm not sure if this is a proper way to check episode done, so please let me know if there is a better method.

**Describe the bug**
Using Python Low-Level API, it seems that some `terminal_steps.group_reward` is missing.

**To Reproduce**
1. Set `GroupReward` and call `EndGroupEpisode` in Unity.
```cs
SimpleMultiAgentGroup agentGroup = new SimpleMultiAgentGroup();
agentGroup.RegisterAgent(myAgent);  // myAgent inherits "Agent" class.
...
agentGroup.SetGroupReward(1.0f);
agentGroup.EndGroupEpisode();
```
2. Call `UnityEnvironment.get_steps` to get next step state(`decision_steps`, `terminal_steps`).
```python
UnityEnvironment.get_steps(behavior_name='MyBehaviour')
```
3. Try to check if episode is done using `terminal_rewards` signal, which is from
```python
env = UnityEnvironment(**config)
decision_steps, terminal_steps = env.get_steps(behavior_name='MyBehaviour')
episode_done = (terminal_steps.group_reward.shape[0] > 0)
```
4. In some arbitrary cases, `Unity` calls `Agent.OnEpisodeBegin` so I'm sure of that `SimpleMultiAgentGroup.EndGroupEpisode` is called. However, `Python` side seems to not getting `terminal_steps.group_reward` properly.

**Environment (please complete the following information):**
- Unity Version: Unity 2020.3.6f1
- OS + version: Windows 10
- _ML-Agents version_: 1.9.0-preview
- _mlagents_envs version_: 0.25.0

...
Thank you for reading.

**Comment by vincentpierre** [comment]
I cannot reproduce this issue with the description provided. Can you send a working example or tell us how to modify the existing example environments to reproduce the bug? It is possible that Agent.OnEpisodeBegin is called even if no agent terminated an episode, it is called for example the first time an agent is spawned. If some Agents have max_step setting, it could also affect their episode terminations.
I also believe that doing `episode_done = (terminal_steps.group_reward.shape[0] > 0)` is equivalent to doing `episode_done = len(terminal_steps)>0` can you confirm?

**Comment by vincentpierre** [comment]
It is also possible that there is an issue with registering and deregistering Agents from the agentGroup. Can you try to reproduce your issue with Dungeon escape or colab push block ?

**Comment by rapsealk** [comment]
@vincentpierre Thank you for the reply. I will go check settings you mentioned above, and make a test to reproduce on Dungeon escape or push block environment. After the test is done, then I will comment about the result.

**Comment by rapsealk** [comment]
First of all, `MaxStep` field is currently set to `0`. According to the [official document](https://docs.unity3d.com/Packages/com.unity.ml-agents@1.0/api/Unity.MLAgents.Agent.html), this means `max_step` will never affect on calling `EndEpisode` by itself.

I will check about other settings..
