### ISSUE TITLE
Hi I have a problem with visual hallway

### ISSUE THREAD

**Issue by hyuDev** [Unity-Technologies/ml-agents#5349]
after I tried a non visual hallway example, I try to train a model with visual hallway.
I know I need to change this part of the function CollectObservations, but I don't know how.
There are so few reports about visual observation that I don't know how to fix it. Can you let me know if anyone succeeds?

**Comment by surfnerd** [comment]
Hi, this question is suited better to the[ ML-Agents forums](https://forum.unity.com/forums/ml-agents.453/).  In the future please only use the github issues for bug reports or feature requests.  Thanks.

**Comment by hyuDev** [comment]
@surfnerd hey could you help me?
I got a error msg in ubuntu18.04,unity 2019.4.18fi,tensorflow gpu 1.15.0.
the msg is mlagents_envs.exception.UnityEnvironmentException: Environment shut down with return code -6 (SIGABRT).
my behavior type is Default and all setting follows /docs/Learning-Environment-Executable.md

why I get that message??
