### ISSUE TITLE
Release 17 code vs. Python Package 0.26 code

### ISSUE THREAD

**Issue by armando-fandango** [Unity-Technologies/ml-agents#5366]
**Describe the bug**

In the docs, release 17 = python package 0.26, but code tags have the following inconsistency:
For example in the file: https://github.com/Unity-Technologies/ml-agents/blob/release_17/gym-unity/gym_unity/envs/__init__.py

Release 17 tag:

`class UnityToGymWrapper(gym.Env):
    """
    Provides Gym wrapper for Unity Learning Environments.
    """

    def __init__(
        self,
        unity_env: BaseEnv,
        uint8_visual: bool = False,
        flatten_branched: bool = False,
        allow_multiple_obs: bool = False,
        action_space_seed: Optional[int] = None,
    ):`

Python package 0.26 tag:

`class UnityToGymWrapper(gym.Env):
    """
    Provides Gym wrapper for Unity Learning Environments.
    """

    def __init__(
        self,
        unity_env: BaseEnv,
        uint8_visual: bool = False,
        flatten_branched: bool = False,
        allow_multiple_obs: bool = False,
    ):`

Which one is correct please?

**Comment by ervteng** [comment]
The release tag is correct - we'll fix the Python tag. Thanks for finding this!

**Comment by armando-fandango** [comment]
The python package on pypi is built and uploaded from release tag or python package tag ? If python package tag, then would you be pushing a new version to the pypi repo as 0.27 ?

**Comment by ervteng** [comment]
It should still be 0.26. This issue should be resolved  - feel free to reopen if you're still having issues.
