### ISSUE TITLE
no more support ImitationLearning?

### ISSUE THREAD

**Issue by hyuDev** [Unity-Technologies/ml-agents#5373]
I saw a post that Unity ml agents conducted an imitation learning. 
 It was used in the pyramid example, but when I looked at the docs folder, there was no related development document, so ask.
You don't support imitation learning anymore?

I use relaease 14 version.

**Comment by ervteng** [comment]
Imitation is still supported as GAIL and Behavior Cloning. Check out the docs here: https://github.com/Unity-Technologies/ml-agents/blob/release_17_docs/docs/ML-Agents-Overview.md#imitation-learning

Also, the [forums](https://forum.unity.com/forums/ml-agents.453/) are a good spot for general questions - other users might be able to help out there.
