### ISSUE TITLE
NullReferenceException in Behavior Parameters

### ISSUE THREAD

**Issue by takashida-takashi** [Unity-Technologies/ml-agents#5374]
!! I am using a translation site.

I have created some simple models to study ML-agents.
I created Main Camera, Floor, Target, Agent, and gave them coordinates.
The following error occurs.
This error occurs in ml-agents/com.unity.ml-agents/Editor/BehaviorParametersEditor.cs:109.
This error prevents you from setting the parameters.
Please let me know if there is a solution.

`NullReferenceException: Object reference not set to an instance of an object
Unity.MLAgents.Editor.BehaviorParametersEditor.DisplayFailedModelChecks () (at C:/anawork/ml-agents/ml-agents/com.unity.ml-agents/Editor/BehaviorParametersEditor.cs:109)
Unity.MLAgents.Editor.BehaviorParametersEditor.OnInspectorGUI () (at C:/anawork/ml-agents/ml-agents/com.unity.ml-agents/Editor/BehaviorParametersEditor.cs:81)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass59_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <ab574a2f598240d68c66d280c533b9d3>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)`

**Comment by dongruoping** [comment]
Hi,

Have you make sure your behavior parameter component is attached to the right game object? It should be attached to the same object as your Agent.

**Comment by takashida-takashi** [comment]
> Hi,
> 
> Have you make sure your behavior parameter component is attached to the right game object? It should be attached to the same object as your Agent.

返信ありがとうございます．
私はそれを解決することができませんでした．

日本語のサイトで申し訳ないですが，以下のサイトを参考に作成しています．
https://note.com/npaka/n/n660d5e9f7c43#tgqfT
このサイトではunity 2018を使用しています．
私はunity 2020.3.8f，ML-agents 2.0.0-pre3(リリース17)を使用しています．
HierarchyからRollerAgentを追加し，RigitBodyと同じようにInspectorからAdd Componentしています．

**Comment by takashida-takashi** [comment]
Thanks for the reply.
I was not able to solve it.

I'm sorry to say that this is a Japanese site, but I made it based on the following site.
https://note.com/npaka/n/n660d5e9f7c43#tgqfT
I am using unity 2018 in this site.
I am using unity 2020.3.8f, ML-agents 2.0.0-pre3 (release 17).
I added the RollerAgent from the Hierarchy and Add Component from the Inspector just like the RigitBody.

**Comment by dongruoping** [comment]
Sorry I don't understand Japanese, but from what I see there's something missing.

You'll need to add the Agent component first, and then add the behavior parameters.
The Agent component is the script inherit from the Agent class that implements your agent. I think the RollerAgent in your tutorial is just a game object named "RollerAgent".

I think the website is coming from our official roller ball tutorial. Here is the most up-to-date version (in English) that you can follow step by step: https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Learning-Environment-Create-New.md
