### ISSUE TITLE
ML Agent Toolkit Glossary Duplicated Term 

### ISSUE THREAD

**Issue by abdallahakrab** [Unity-Technologies/ml-agents#5378]
The Term "Policy" is duplicated in ML Agents Toolkit Glossary: 

![image](https://user-images.githubusercontent.com/37980706/119230314-ef67cb00-bb1b-11eb-931a-6cab5eb7d924.png)

**Comment by dongruoping** [comment]
Thanks for pointing this out, it was mistakenly duplicated.

We'll fix it soon, thanks!
