### ISSUE TITLE
AcademyAct() function.

### ISSUE THREAD

**Issue by dxbdxx** [Unity-Technologies/ml-agents#538]
I can't find the **AcademyAct()** function that mentioned in **Learning-Environment-Design.md**. If it exist, what I should do in this function? Thanks for the reply

**Comment by MarcoMeter** [comment]
Hi @dxbdxx 
I believe you are referting to `AcademyStep()`.
You can use that function to update your environment before any agent get to carry out an action.

**Comment by dxbdxx** [comment]
@MarcoMeter Yes, that's really helpful, thank you
