### ISSUE TITLE
Colab tutorials are currently broken

### ISSUE THREAD

**Issue by mattdeitke** [Unity-Technologies/ml-agents#5383]
The ML Agent's [Python Tutorials with Google Colab](https://github.com/Unity-Technologies/ml-agents/blob/61be82891241d2db25f09e9bb20644b8bc0082fe/docs/Readme.md#python-tutorial-with-google-colab) are no longer working. (Consider [this one](https://colab.research.google.com/drive/1Qg6E5kmf9n4G8rc5lXHIM_cQzMUFGH-g#forceEdit=true&sandboxMode=true) as an example.)

Digging into the `Install Rendering Dependencies` command:

```
!wget --output-document xvfb.deb http://security.ubuntu.com/ubuntu/pool/universe/x/xorg-server/xvfb_1.18.4-0ubuntu0.11_amd64.deb >/dev/null 2>&1
```
the link now goes to a 404 (http://security.ubuntu.com/ubuntu/pool/universe/x/xorg-server/xvfb_1.18.4-0ubuntu0.11_amd64.deb).

I tried replacing the link with an updated version of `xorg-xvfb` from [pkgs.org](https://pkgs.org/download/xvfb), (specifically http://archive.ubuntu.com/ubuntu/pool/universe/x/xorg-server/xvfb_1.19.6-1ubuntu4.9_amd64.deb), but it does not start the environment, raising:
![image](https://user-images.githubusercontent.com/28768645/119384417-87c79200-bc79-11eb-962e-8bd4bae67160.png)

**Comment by dongruoping** [comment]
Hi @mattdeitke Thanks for raising this - we're looking into this and will fix it as soon as possible.

**Comment by dongruoping** [comment]
We've fixed the installation links, it should be working now.

**Comment by mattdeitke** [comment]
Awesome! Thank you.
