### ISSUE TITLE
Parallel Training

### ISSUE THREAD

**Issue by tschmidt64** [Unity-Technologies/ml-agents#539]
What would be the best way to try a few different reward functions in parallel in order to compare them? My training is taking upwards of 24 hours, and trying 1 reward function at a time is slow work.

**Comment by Hengoo** [comment]
You might want to read the documentation for the command line parameters: 
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-ML-Agents.md

you can run multiple trainer at once with --worker-id=<n>
