### ISSUE TITLE
How to change UnityEnvironment Port so I could run two simulations simultaneously?

### ISSUE THREAD

**Issue by sarmientoj24** [Unity-Technologies/ml-agents#5402]
Is there a way to change the port so I could run two instances of training separately on the same machine?

**Comment by vincentpierre** [comment]
Hi @sarmientoj24 
This is not using the proper template for feature requests and I think this question is more appropriate for the [forum](https://forum.unity.com/forums/ml-agents.453/)
You can change the port when using the `mlagents-learn` command using the command line argument `--base-port`. See [here](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Training-ML-Agents.md#training-using-concurrent-unity-instances) for more information.

**Comment by sarmientoj24** [comment]
Hi @vincentpierre I am using UnityEnvironment in Python

**Comment by vincentpierre** [comment]
https://github.com/Unity-Technologies/ml-agents/blob/colab-CI/docs/Python-API.md#loading-a-unity-environment
I think what you need is the `worker_id` changed
