### ISSUE TITLE
Adding Number of completed Episodes to Tensorboard

### ISSUE THREAD

**Issue by jziegle4** [Unity-Technologies/ml-agents#5404]
Currently only the number of steps and the average episode length are logged in tensorboard. Since parallel setups will create more episodes per timestep than a singular setup. Since logging via StatsRecorder Class is not possible with num_workers>1, since Average and Most_Recent wont give a correct number, since it would require to add up Most Recent Numbers of all Workers, both Unity and Python side need to be adapted.

**Describe the solution you'd like**
Add a Most_Recent_Parallel_Sum Value to StatAggregationMethod. If this Value is used, All Workers will write there Most_Recent Value into an array using there Worker_Id as the position within the array.

**Describe alternatives you've considered**
It might be possible to count the Done Flags, but since I could not find any documentation regarding if the buffer is a singular object shared by all workers as well as it is a Buffer that just stores the most recent values this was not possible to use. The preferred solution described earlier would also allow to track the total number of events over all workers or other statistical values of interest.

**Comment by vincentpierre** [comment]
Hey, sorry for the late reply. Why won't average and most recent not give a correct number? According to [this code](https://github.com/Unity-Technologies/ml-agents/blob/main/ml-agents/mlagents/trainers/agent_processor.py#L424) average will be the average across all workers and most recent will be the latest value from worker 0 only (to avoid collisions).
I logged the request for a  Most_Recent_Parallel_Sum StatAggregationMethod.
(For internal tracking : MLA-2062)

**Comment by jziegle4** [comment]
Hey, if I try to log the current episode count using StatsRecorder, and us AVERAGE as the SummaryMethode, all numbers of all workers reported since the last summary will be averaged and returned. 

As an example let's take a Unity Instance containing 16 independent agents, that try to learn using each there own copy of an Environment. You can collect the cummulative episode count of all those agents in the same unity instance by using a single instance of an own class called recorder.cs that only collects those episode counts from all agents and every 100 fixedUpdate steps sends it to mlagents using StatsRecorder. 

If the summary frequence in the yaml file is set to 10000, and within 100 fixedUpdate steps each agent completes 2 episodes, this would mean after 100 fixedUpdate steps, Recorder.cs would use StatsRecorder to report 32 completed episodes or after 10000 fixedUpdate steps a total count of 3200. 

If StatsRecorder would use the StatAggregationMethod AVERAGE all numbers reported for the episode count would be averaged including the 32 from the beginning, instead of the reporting the correct number of 3200. 

MOST_RECENT would be correct in this case, but if you were to use 16 parallel workers or unity instances the number of MOST_RECENT would only report the number of the first worker. In Tensorboard the resulting graph would suggest that using the same buffer size, the number of episodes contained in the buffer (from which ppo is sampling its learning data) is lower then with one worker. 

This would mean to the untrained eye, that ppo may not have seen data from enough episodes to generalize during learning. If the workers don't preduce the same episode count within the summary frequence, which can happen due to statistical variance in the episode length or hardware limitations, just multiplying the number of MOST_RECENT by the num_envs will lead to a false episode count as well. 

Only the cummulative most recent value of all envs or all Recorder.cs instances will give the correct count of episodes. 

The total episode count of all instances will be helpful in determing the speed up generated by using num_envs > 1 and help to determine the required buffersize. The number of total steps can not provide this information as easily, since the episode length will change during training

**Comment by vincentpierre** [comment]
Hi, 
Sorry I am not following. I think it is because I do not know what the problem you are trying to solve is. If you want to know how many episodes were completed, could you use `SUM` for aggregation ? 
Maybe you could make a PR with the suggested change so we can review it with code.
I doubt the cumulative most recent value of all envs will give the correct count of episodes since the most recent could be overwritten (hence you will not have the exact count).
