### ISSUE TITLE
Can I use the output model of [imitation learning] to default model of [ppo learning]?

### ISSUE THREAD

**Issue by erotofaust** [Unity-Technologies/ml-agents#541]
I tried to train my AI but it didn't improve at some point.
maybe it's some saddle point of this AI.

so I used the imitation learning for making default model.

but when I use --load in prompt, train by ppo, it doesn't work well
because some key is missing in the imitated model.

how can I use imitated model?

**Comment by Lakrix** [comment]
Did u get this to work?

**Comment by Fallscout** [comment]
Did someone get this to work already? This feature is really important for my studies.

**Comment by dracolytch** [comment]
I just ran into this myself while working on my YouTube series. It would be amazing to do the "discovery" part of the ML as imitation learning, and then let PPO perform optimization.

**Comment by rgjones33** [comment]
@awjuliani @vincentpierre @unityjeffrey You guys have any comment on how one can start with imitation learning and use other forms of learning to improve?

**Comment by sidagarwal2805** [comment]
This would be really useful for me to thanks!

**Comment by kavousanos** [comment]
Yep, this feature makes a lot of sense!
Would be very interested in it.

**Comment by icaro56** [comment]
I'm trying to continue learning the agent with the PPO after training with Behavioral Cloning. But I lack knowledge.

**Comment by Ina299** [comment]
I also ran into this problem during my training.
Is there a way to solve?

**Comment by icaro56** [comment]
@Ina299 , there is another post where I share with all of you my way to continue the training with PPO. But I have not proved to continue learning with PPO is improving learning or previous training with BC only disrupts the learning of PPO.

**Comment by icaro56** [comment]
https://github.com/Unity-Technologies/ml-agents/issues/1032

**Comment by harperj** [comment]
Hi everyone, just wanted to give an update that this feature is on our roadmap.  Though we don't have a specific timeline, we understand this would be a valuable addition.

Without changing the existing trainers it won't be possible currently.

**Comment by ishaybe** [comment]
Hi,
I used ppo to "imitate" by giving proportional positive reward to the absolute difference between teacher and student action.
In addition I set the gamma hyperparameter to very low number (10e-8) to take in account in learning process only the last step reward.

**Comment by icaro56** [comment]
@ishaybe , I use a bomberman like game as my platform of researchs. The actions of my agent are discrete, so in my case, making the absolute difference of the actions did not work very well. I simply gave a positive reward when the student did the same, and a negative reward when he went wrong. It did not work very well. Later, when I tried to continue training with the normal ppo without mimicking the specialist, my agent did not take advantage of this previous training.

How would you make that difference with discrete actions?

**Comment by awjuliani** [comment]
Hi all. This is a feature we have in progress for a future release in the near future. I will close this issue for now due to inactivity.
