### ISSUE TITLE
Didn't you mean this when you used this code?(SoccerEnvController.cs)

### ISSUE THREAD

**Issue by xogur6889** [Unity-Technologies/ml-agents#5423]
**Describe the bug**
Isn't it meaningless if we divide the whole number into whole numbers?
![image](https://user-images.githubusercontent.com/55425599/121149461-a636ab80-c87d-11eb-9c5a-aac9d97c6133.png)

Isn't it right to change it like this?
m_BlueAgentGroup.AddGroupReward(1 -  **(float)m_ResetTimer** / MaxEnvironmentSteps);

Thank you.

**Comment by andrewcoh** [comment]
Yes, you are correct. Thank you for pointing this out. It was an error introduced when shifting soccer to the group manager. I have fixed this here https://github.com/Unity-Technologies/ml-agents/pull/5424
