### ISSUE TITLE
When I try to add trained model of brain, I get warning "required constant "is_continuous_control" was not found in the model". It is my first time working with ML-agents. And the second issue that I cannot show the way to YAML file. Wh

### ISSUE THREAD

**Issue by pavel7876** [Unity-Technologies/ml-agents#5432]
![Untitled-1](https://user-images.githubusercontent.com/81475567/121783566-c2618200-cbc8-11eb-88a0-fe509b0be467.png)

![23](https://user-images.githubusercontent.com/81475567/121783741-c8a42e00-cbc9-11eb-949c-22bdecf471a2.png)

**Comment by pavel7876** [comment]
When I add model every ML agent don't do any thing.

**Comment by mmattar** [comment]
Hi @pavel7876 - can you share a few more pieces of information:
- which ML-Agents version are you using?
- which platform (windows, mac, linux) are you training on?
- Have you tried training ML-Agents on any of our sample environments?
- I presume the environment you shared is a new one that you created. Which YML file are you using? Can you paste its contents?

**Comment by pavel7876** [comment]
Hello mmattar! I use 1.6.0 version of ML agents on windows. No, I only trained my own models. I use a YAML file of release 2.

**Comment by jesusthecreator017** [comment]
I am also new to ml agents and I am also having the same problem about the "is_continuous_control". I have been able to train the demo environments but when I go to add the brain model it still gives me the same problem.

**Comment by panosdimitrellos** [comment]
> I am also new to ml agents and I am also having the same problem about the "is_continuous_control". I have been able to train the demo environments but when I go to add the brain model it still gives me the same problem.

i have the same problem..has anyone found any solution to that problem?

**Comment by tianhengMa** [comment]
Same issue here, I followed the steps here: https://github.com/Unity-Technologies/ml-agents/blob/release_18_docs/docs/Getting-Started.md. When I put the trained onnx file as the Model for Behavior Parameters component, the warning "required constant "is_continuous_control" was not found in the model" shows up. When I try to Play the scene, the agent cubes don't move at all. 

I'm using Mac OS 11.5.2, Python 3.9, ml-agent-release7, and ML Agents version 1.4.0.
