### ISSUE TITLE
Add the ability to edit environment parameters while training

### ISSUE THREAD

**Issue by kkalera** [Unity-Technologies/ml-agents#5434]
Hi, I've been using ML-agents for a while now. Using curriculum learning because I'm trying to solve a complex environment that seems to train much better when taking baby steps. I have multiple parameters that increase the difficulty of the environment on every successful episode. 

It would be very nice to have these as environment parameters or as samplers that can be adjusted while training. In case of a training stop, this would allow to resume where the agent left off without having to rebuild the application with the correct parameters.

Please correct me if this is already possible, I couldn't find it in any of the documentation.

**Comment by mmattar** [comment]
Hey @kkalera - we support environment randomization. Can you check out this documentation and let us know if it acheives what you're looking for?
- https://github.com/Unity-Technologies/ml-agents/blob/main/docs/ML-Agents-Overview.md#training-robust-agents-using-environment-parameter-randomization
- https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Training-ML-Agents.md#environment-parameter-randomization

**Comment by kkalera** [comment]
Hey @mmattar , thanks for your reply. I know about parameter randomization, but I don't necessarily want to randomize between certain values. I would like to alter a parameter during training. I'll give an example;

Let's say for instance the wall-jump example.  Instead of having three different heights for the wall as in no wall, low wall and high wall, you could increase the wall height by a small amount every successful episode. I know this is possible to program into the environment itself, which is how I'm doing it right now, but this doesn't allow me to resume training without rebuilding the executable.

Please correct me if I'm wrong and this is already possible with parameter randomization.
