### ISSUE TITLE
Implementing support for a ConvLSTM operator.

### ISSUE THREAD

**Issue by willawebb** [Unity-Technologies/ml-agents#5437]
**Is your feature request related to a problem? Please describe.**
I've been wanting to implement a model in Unity but I realise that ConvLSTMs aren't supported by Barracuda yet.

**Describe the solution you'd like**

Convolutional LSTMs, as defined by Shi et al. [here](https://arxiv.org/pdf/1506.04214v2.pdf) is an evolution of the LSTM operator, capturing spatio-temporal correlations better and appearing to consistently achieve superior results to a standard fully-connected LSTM. I believe that ConvLSTMs will be a very useful operator to have as part of the ML-Agents / Barracuda toolkit, and would love to see it supported.

**Describe alternatives you've considered**

For now I intend on pushing ahead with normal LSTMs, though I imagine this will negatively affect the performance of the model I'm implementing. Not having to make that sacrifice would be nice.

**Additional context**
There appears to be [no shortage](https://paperswithcode.com/method/convlstm) of papers that make use of this operator, so I'm sure it would see some use if implemented.

Thanks in advance!

**Comment by ervteng** [comment]
Hi @willawebb, it's definitely possible for us to add ConvLSTMs. From my understanding they primarily benefit sequential image-type applications (e.g. video)? The vast majority of ML-Agents use-cases don't use visual observations, so it isn't currently on our roadmap.

**Comment by willawebb** [comment]
Hey ervteng,

You're correct in your understanding of their purpose. I don't know the complexity of adding this feature, but I genuinely think it would be a fantastic add. While it may not fit the current use-cases of ML-Agents, some of the most spectacular demos that I've seen of barracuda's capabilities, such as the [style-transfer demo](https://blogs.unity3d.com/2020/11/25/real-time-style-transfer-in-unity-using-deep-neural-networks/), are the sorts of things that could benefit from what a ConvLSTM has to offer. 

The use-case that I wanted to use this for was as part of a saliency model to help actively predict where a user might look next if they're using an eye-tracking VR headset. I can do it with a normal LSTM though it is much less performant and accurate, and without that layer then the predictions can only use the current frame for reference.

**Comment by ervteng** [comment]
Yeah, I can see it being super valuable to many Unity-related use-cases! I'll forward this to the Barracuda team and see what they think.

**Comment by AlexRibard** [comment]
@willawebb do you have a onnx model that uses ConvLSTM that you could share with us?

**Comment by willawebb** [comment]
Hi Alex, 

I apologise for the late reply. I also apologise for my own lack of due diligence, which I'm sure that you've already discovered yourself, as apparently the ONNX format itself does not support the ConvLSTM operator. I'll have to see about opening an issue over there first. Sorry for the bother.

**Comment by AlexRibard** [comment]
Yes, you are correct, ONNX does not support ConvLSTM.
What i was trying to say is, if you have a Keras/TF with ConvLSTM can you export it to ONNX?
That way I can test out locally if it does import :) 
Of course the ConvLSTM will be broken up into different layers, but it might just work without any work from our side.

Let me know
