### ISSUE TITLE
Academy Fixed Update Stepper Generating Garbage

### ISSUE THREAD

**Issue by ohernpaul** [Unity-Technologies/ml-agents#5438]
**Describe the bug**
I am working on running my agents in a virtual reality environment within the quest 2. I was doing some profiling and noticed that the Academy Fixed Update Stepper is generating some garbage. After going into the hierarchy mode of the profiler in unity, I found that a call to "GenerateTensors" within the fixed update stepper is calling a "LogStringToConsol". This log is taking up a majority of the time it takes to call this function. 18ms total for Fixed Update Stepper and 10ms just for that log.

I have made sure that I am not generating any Debug.Log calls in my scripts and am at a loss as to why this log string is being generated and was hoping I could get some guidance on how to track it down and or turn it off. I have attached a screenshot of my profiler result.

Note: the results captured here are from a build directly on the quest.

I also posted this in the forum - not sure where this belongs.
https://forum.unity.com/threads/academy-fixed-update-stepper-generating-garbage.1130209/

**Screenshots**
![FixedUpdateStepper_LogString_Issue](https://user-images.githubusercontent.com/13112890/123134414-98e4f980-d405-11eb-9d40-2e1c1cdd18bf.PNG)

![FixedUpdateStepper_LogString_Issue_Visual](https://user-images.githubusercontent.com/13112890/123134426-9bdfea00-d405-11eb-9ebd-6658a995c34a.PNG)

I was also curious if the ML-Agents team has plans to start leveraging the tensor hardware in XL2 chips?

**Environment (please complete the following information):**
Unity Version: [Unity 2019.4.18f]
OS + version: [Windows 10]
ML-Agents version: (Release 17)
Torch version: (torch==1.7.0+cu110)

**Comment by hvpeteet** [comment]
For completeness this seems to have been resolved in https://forum.unity.com/threads/academy-fixed-update-stepper-generating-garbage.1130209/ 

@ohernpaul is this sufficiently resolved for us to close this bug here?

**Comment by hvpeteet** [comment]
Closing since this seems resolved, please feel free to re-open if this is not the case.
