### ISSUE TITLE
Can not Save Model and Can not find the trained result

### ISSUE THREAD

**Issue by Maomao110** [Unity-Technologies/ml-agents#544]
I fellow the beginner's guide and Train the Ball3D project.
when the training is over, the project closed , and can not find any place to save model.
And I can not find the folder named "Model" as well.

Then I do not know what to do now !

**Comment by Lakrix** [comment]
You should find the models folder inside your python map.

**Comment by eshvk** [comment]
If you launch python from the top level directory of the github project, e.g. go into `ml-agents` and run:

```
python3 python/learn.py <env_file_path> --run-id=<run-identifier> --train
```
there should a directory inside `ml-agents` that contains `models`.
