### ISSUE TITLE
Loss is strange in multi-agent learning.

### ISSUE THREAD

**Issue by xogur6889** [Unity-Technologies/ml-agents#5440]
![BigHealthKim](https://user-images.githubusercontent.com/55425599/123290244-1286ff80-d54c-11eb-9da4-3479c92f85a5.PNG)

The picture above is a graph of a model learned in my environment. If you look at Loss, you can see it rising to the top right.

This Loss occurred equally in the multi-agent example you created. (ex. Push Block)

I saw the code and I don't know why the value is increasing when calculating Loss in PPO and MA-POCA are similar.

I would appreciate it if you could give me a detailed answer.

**Comment by ervteng** [comment]
These curves actually look successful. It is expected for the loss (value/baseline) to go up as the agent learns, as the value of the reward is continuously increasing. You'll see the same for PPO as well. Once the agent converges on a behavior, the loss will go back down.

**Comment by xogur6889** [comment]
> These curves actually look successful. It is expected for the loss (value/baseline) to go up as the agent learns, as the value of the reward is continuously increasing. You'll see the same for PPO as well. Once the agent converges on a behavior, the loss will go back down.

![image](https://user-images.githubusercontent.com/55425599/123724132-c2e76180-d8c6-11eb-83ce-7a05d7e77acf.png)
This is an example image of your Using-Tensorboard.md.
The reward is increasing but the loss is reduced, is this the opposite of what you said?
