### ISSUE TITLE
BehaviorParametersEditor OnInspectorGUI constantly recreates sensors

### ISSUE THREAD

**Issue by mbaske** [Unity-Technologies/ml-agents#5443]
[BehaviorParametersEditor](https://github.com/Unity-Technologies/ml-agents/blob/85dce4329601f214dcc3705c5a4cd149fef97704/com.unity.ml-agents/Editor/BehaviorParametersEditor.cs#L91)'s OnInspectorGUI() calls DisplayFailedModelChecks(), which then calls agent.InitializeSensors(). This causes the CreateSensors() code to be invoked on every OnInspectorGUI callback, even at runtime. The only way to stop repeated sensor instantiation is to hide the BehaviorParameters component inspector, so that its GUI is no longer updated.

**To Reproduce**
Open the FoodCollector example and place a Debug.Log in GridSensorComponent's CreateSensors() method. Select one of the agent gameobjects in the hierarchy and fold out its behavior parameters inspector settings. Enter play mode.

- _ML-Agents version_: Release 18
- _Environment_: FoodCollector

**Comment by mbaske** [comment]
Here's my workaround for hiding the inspector:
```
var tracker = UnityEditor.ActiveEditorTracker.sharedTracker;
var editors = tracker.activeEditors;
for (int i = 0; i < editors.Length; i++)
{
    // Can't check type because BehaviorParametersEditor is internal.
    if (editors[i].ToString() == " (Unity.MLAgents.Editor.BehaviorParametersEditor)")
    {
        tracker.SetVisible(i, 0);
    }
}
```

**Comment by ervteng** [comment]
Thanks for reporting this bug - i've recorded it in our internal tracker as MLA-2093, and it should be fixed in an upcoming release.
