### ISSUE TITLE
returning observations in cupy arrays

### ISSUE THREAD

**Issue by armando-fandango** [Unity-Technologies/ml-agents#5444]
**Is your feature request related to a problem? Please describe.**
Currently, unity returns observations as arrays. Can it return the observations in CUDA memory directly as cupy arrays?

**Describe the solution you'd like**
Returns observations as cupy arrays

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ervteng** [comment]
Thank you for your comments.  We’ve documented your feedback and will prioritize when appropriate.
