### ISSUE TITLE
Please add alpha channel support to ObservationWriter.WriteTexture

### ISSUE THREAD

**Issue by mbaske** [Unity-Technologies/ml-agents#5445]
**Is your feature request related to a problem? Please describe.**
Sometimes, ARGB32 render textures contain observable data in their alpha channel, for instance when using them with depth-normal texture shaders. 

**Describe the solution you'd like**
ObservationWriter.WriteTexture should handle alpha in addition to rgb. AFAIK, Texture.EncodeToPNG already supports alpha channels when compressing observations.

**Describe alternatives you've considered**
Mapping the alpha channel to an additional texture's rgb channels.

**Comment by ervteng** [comment]
Hmm, the main reason we haven't done this is it's not standard on the Python/training side to have the Alpha channel as input to the CNN. Still, we _do_ support more than 3 channels input for matrix observations (it encodes as multiple PNGs), maybe we can make a custom WriteTexture param that also includes the alpha fairly easily. cc: @dongruoping

**Comment by dongruoping** [comment]
Yes it should be fairly straight forward to implement. For now to use ARGB textures, you can use compressed observations and it should work as-is, as long as you set the correct observation size in your sensor. 

I've logged this request internally as [MLA-2111](https://jira.unity3d.com/browse/MLA-2111).
