### ISSUE TITLE
AttributeError: 'UnityEnvironment' object has no attribute '_communicator'

### ISSUE THREAD

**Issue by armando-fandango** [Unity-Technologies/ml-agents#5451]
**Describe the bug**

When I subclass from UnityToGymWrapper and implement my own close() function that calls super().close(), I get this error:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/conda/envs/navsim/lib/python3.8/site-packages/mlagents_envs/environment.py", line 424, in _close
    self._communicator.close()
AttributeError: 'UnityEnvironment' object has no attribute '_communicator'

```

**Environment (please complete the following information):**
- OS + version: Ubuntu 20
- _ML-Agents version_: 0.27

**Comment by ervteng** [comment]
Does the raw UnityToGymWrapper work on your machine? (just trying to narrow down the issue)

**Comment by armando-fandango** [comment]
Yes it does. Thx. Something within the interaction of _close and close functions is causing this probably

**Comment by mahon94** [comment]
Hi @armando-fandango, Do you still have this issue with UnityToGymWrapper? Can you provide more detail (possiblye a sample code) as to how you're overriding the `close()` method?
