### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by IvailoManolov** [Unity-Technologies/ml-agents#5458]
**Describe the bug**
When training an agent my program ran to 10GB of memory usage. I was writing everywhere for it ,unity forum , stackoverflow . I even tried to contact Code Monkey because I know that u have a collab. I thought the problem was in me , so I decided to test the Examples that come with the unity ML lib. 3D Ball , where the agent needed to balance the ball. I put that on heuristc and just let it ran for 30 minutes. When I came back the unity was taking 2GB of memory and continue forward in linear fashion.

**To Reproduce**
1. Open 3D Ball example
2. Remove the NN model and place the models in Heuristic only mode.
3. Open the memory profiler or task manager and just write the memory usage on a piece of paper.
4. You will see that it takes a lot of memory after some time. 

**Console logs / stack traces**
I don't get any errors in the console.

**Environment (please complete the following information):**
- Unity Version: Unity 2020.2.2f1
- OS Windows 10
- _ML-Agents version 2.0.0
- _Torch version_:1.7.1

**Comment by IvailoManolov** [comment]
Anyone ?

**Comment by hhhcwb38712** [comment]
@IvailoManolov 
Hi，I also met this issue，I use ML-Agent to train my own environment, at first, it took me about 200s to summay 10000 steps. After a night(about 7 or 8 hours), it took me 1000s to summary 10000 steps. And task manager shows the Unity.exe take 16GB memory usage. Is my environment has memory leak or ML-Agent has a bug?

**Comment by IvailoManolov** [comment]
ML-Agent has a bug for sure. If you go to their examples ,3D ball , place the mode on heuristic only . With the time you can see that memory is not stable. If their example has a memory leak , its not your fault .I recommend you downgrading to 1.7.0 , memory is stable there. I would like to ask you a question . How can you train for 7 or 8 hours ? I want to train my agent for a longer period of time . Should I just increase the max steps to 10mil for example ? How can i train for 24hours or 8 or just longer period of time?

**Comment by ervteng** [comment]
Hmm, I haven't been able to replicate the memory leak in 3DBall on 2.1.0. What is your Barracuda version?

For longer training - yes, just increase the max steps.

**Comment by IvailoManolov** [comment]
@ervteng Okay Gotcha , just how to see the Barracuda version currently ?

**Comment by hhhcwb38712** [comment]
@IvailoManolov 
I train the agent on my onw environment, I am pretty sure their examples have memory leak. And I find my own environment also have the same problem. What is the Barracuda? The version of ML-Agent?

**Comment by IvailoManolov** [comment]
I am pretty sure for the memory leak as well. Barracuda is their inference library

**Comment by ervteng** [comment]
You can see both the ML-Agents package version and Barracuda version in the Package Manager in the Unity editor

**Comment by IvailoManolov** [comment]
OOh never mind !! Library 1.7.0 Stops the memory leak during heurstic only. When I train I still have the memory leak ...

**Comment by mahon94** [comment]
> Library 1.7.0 Stops the memory leak during heurstic only

Do you still have this issue? Do you still observe it in more recent versions of ML-Agents?
