### ISSUE TITLE
Add additional notes for running ML-Agents on a server with a headless Unity instance

### ISSUE THREAD

**Issue by omarathon** [Unity-Technologies/ml-agents#5465]
**Is your feature request related to a problem? Please describe.**
I recently tried to setup ML-Agents on a server (with only access to a terminal - no graphics). But, the docs (https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Learning-Environment-Executable.md) did not mention that one should run `mlagents-learn` with `--no-graphics` in such cases. Without `--no-graphics`, `mlagents-learn` failed and it took a long time of sifting through debug messages to discover why. I had the exact same issue as in this forum post: https://forum.unity.com/threads/how-to-run-ml-agents-on-server.994678/.

**Describe the solution you'd like**
Add a note on  https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Learning-Environment-Executable.md saying to use the `--no-graphics` if one wishes to train headlessly (or, even elaborate that they could use xvfb if they need rendering, as mentioned in this forum post: https://forum.unity.com/threads/how-to-run-ml-agents-on-server.994678/).

**Describe alternatives you've considered**
None, besides maybe using xvfb in the future if I need rendering and not using the `--no-graphics` parameter.

**Comment by ervteng** [comment]
Duly noted, and we'll add it to the documentation. If you'd like to take a stab at it yourself, feel free to submit a PR. 

Another way to run headless (without --no-graphics) is to do a "server build" in Unity (there's a checkbox there).
