### ISSUE TITLE
Speed up the progress of training

### ISSUE THREAD

**Issue by PluteW** [Unity-Technologies/ml-agents#5473]
I want to train the intelligent agent with Unity as quickly as the gym does. Is it possible to interact with Unity without displaying the animation window? Similar to gym render?

**Comment by IvailoManolov** [comment]
Not entirely sure if this is what you mean but from the DOCS I found this : mlagents-learn <trainer-config-file> --env=<env_name> --run-id=<run-identifier>

"<env_name>(Optional) is the name (including path) of your Unity executable containing the agents to be trained. If <env_name> is not passed, the training will happen in the Editor. Press the Play button in Unity when the message "Start training by pressing the Play button in the Unity Editor" is displayed on the screen."

**Comment by ervteng** [comment]
You can run mlagents-learn with --no-graphics to turn off graphics. BTW, for usage questions, the [Unity Forums ](https://forum.unity.com/forums/ml-agents.453/) are usually a better place to ask, as there may be other users who have had the same issue.

**Comment by PluteW** [comment]
thank U for your replay,&nbsp;I may have found the wrong place before. Thanks for reminding me. Your reply has helped me solve the problem very well.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Unity-Technologies/ml-agents"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月27日(星期二) 上午9:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Unity-Technologies/ml-agents] Speed up the progress of training (#5473)





 
You can run mlagents-learn with --no-graphics to turn off graphics. BTW, for usage questions, the Unity Forums  are usually a better place to ask, as there may be other users who have had the same issue.
