### ISSUE TITLE
Add Erf operator to Barracuda

### ISSUE THREAD

**Issue by Peamon** [Unity-Technologies/ml-agents#5503]
Could this operator be added to Barracuda : https://github.com/onnx/onnx/blob/master/docs/Operators.md#erf
Could be usefull for ViT models like this one: [ViT_ade20k_seg_tiny_mask.zip](https://github.com/Unity-Technologies/ml-agents/files/7007541/ViT_ade20k_seg_tiny_mask.zip)
Exported from https://github.com/rstrudel/segmenter checkpoint.
![Capture](https://user-images.githubusercontent.com/36283606/129906832-f6af34fa-59b4-4b79-ac18-c294091f85be.PNG)

**Comment by andrewcoh** [comment]
Hi @Peamon 

We can only guarantee models will export properly to Barracuda if they are created with our trainers. Please try the Barracuda repo to get further guidance https://github.com/Unity-Technologies/barracuda-release/issues
