### ISSUE TITLE
Reset simulation to a different initial state

### ISSUE THREAD

**Issue by HainingLuo** [Unity-Technologies/ml-agents#5504]
Hi all, I have been trying to create a sample based controller with an unity gym environment. The controller samples several steps in different trajectories and finds the best route.

My problem is, after implementing one action, I need to sample actions based on the final state of last step, which means the simulation needs to be reset to a different initial state.

For example, suppose the initial state is 0, after implementing the first action, the state becomes 1. I would like to then set the initial state to 1, so that when the reset functions is called, the simulation will go to state 1 instead of 0. I hope my explaination makes sense.

Could I ask if this is possible to be achieved currently? If not, is it possible to add this feature to future releases? Many thanks.

**Comment by andrewcoh** [comment]
Hi @HainingLuo 

Do you mean after state 0, you enter state 1. Then rollout the trajectory to some termination condition. _And _then__ reset to state 1 and perform another rollout?

If the environment is simple enough, most of this logic can be put in the `OnEpisodeBegin` function. Again, if it's simple enough, you can save whatever you need to (e.g. gameobject velocity, position etc.) in the agent script. However, this is not very scalable.

**Comment by HainingLuo** [comment]
Hi @andrewcoh 

Thanks for your reply. It is a great idea to put the logic in `OnEpisodeBegin`, however, for me, the state 1 is not predefined but the result from one of the runs in state 0, depending on the reward from the python side. Therefore I need a mechanism to tell the agent what state 1 is. That is why I was thinking whether it is possible to implement a function that set the agent state according to input variable from the python side. 

Either way, I have switched to use ROS TCP Endpoint to bulld the connection so this is no longer needed now. Thanks again.
