### ISSUE TITLE
Using a Keras/Tensorflow Model as Brain

### ISSUE THREAD

**Issue by ohernpaul** [Unity-Technologies/ml-agents#551]
Does anyone know if you can export a previously trained model from Keras/Tensorflow into the bytes format required?

Ie: Train model in Keras using TF back end -> call TF to export -> place exported file into models/<run-identifier> in ml-agents folder.

**Comment by awjuliani** [comment]
Hi @ohernpaul,

Were you able to get it working? You are exactly right that you can use the `freeze_graph` function to concert a graph to a `.bytes`. By default the tensorflow function produces a protobuf file, which we rename to `.bytes` so that Unity asset importer can understand it.

**Comment by ohernpaul** [comment]
@awjuliani I'm currently working on it, will post soon.

**Comment by awjuliani** [comment]
Great to hear that it worked! I will close the issue for now. If you have additional questions, feel free to either re-open this issue or make another one.
