### ISSUE TITLE
The Unity environment took too long to respond 

### ISSUE THREAD

**Issue by tw0226** [Unity-Technologies/ml-agents#5517]
**Describe the bug**

I could learn and run in Unity environment with python mlagents-learn API in cmd.
next, I tried to apply Unity environment to python API in my code by (https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Python-API.md)
also I set my Behavior Parameters Behavior Type is "default",
but it makes error.

**To Reproduce**
1. Build Setting Unity
2. run with my unity_env.py

**Console logs / stack traces**

MoveToGoalAgent.cs

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Unity.MLAgents;
using Unity.MLAgents.Actuators;
using Unity.MLAgents.Sensors;

public class MoveToGoalAgent : Agent
{
    [ SerializeField ] Rigidbody rb;
    [ SerializeField ] Transform target;
    public override void OnEpisodeBegin()
    {
        transform.localPosition = new Vector3(0, 0.25f, 0);
        
        target.localPosition = new Vector3( Random.Range(-4, 4) , 0.25f, Random.Range(-4, 4));
        rb.velocity = Vector3.zero;

        //transform.velocity = Vector3.zero;
    }
    public override void CollectObservations(VectorSensor sensor)
    {
        sensor.AddObservation(transform.position);
        sensor.AddObservation(target.position);
    }

    
    public override void OnActionReceived(ActionBuffers actions)
    {
        Vector3 nextMove = new Vector3();
        int speed=4;
        nextMove.x = actions.ContinuousActions[0];
        nextMove.z = actions.ContinuousActions[1];
        transform.Translate( nextMove * Time.deltaTime * speed );
        // Debug.Log(transform.position);
        // Debug.Log(target.position);
    }

    private void OnCollisionEnter(Collision other) 
    {
        if  ( other.transform == target )    
        {
            SetReward(+1);
            EndEpisode();
        }
    }
}

```

unity_env.py

```

import mlagents
from mlagents_envs.environment import UnityEnvironment as UE

env = UE(file_name='UnityEnvironment', seed=1, side_channels=[])
env.reset()

```

error logs

```

Traceback (most recent call last):
  File "C:/Users/myname/PycharmProjects/RL_with_Unity/unity_env.py", line 4, in <module>
    env = UE(file_name='UnityEnvironment', seed=1, side_channels=[])
  File "C:\Anaconda3\lib\site-packages\mlagents_envs\environment.py", line 223, in __init__
    aca_output = self._send_academy_parameters(rl_init_parameters_in)
  File "C:\Anaconda3\lib\site-packages\mlagents_envs\environment.py", line 477, in _send_academy_parameters
    return self._communicator.initialize(inputs, self._poll_process)
  File "C:\Anaconda3\lib\site-packages\mlagents_envs\rpc_communicator.py", line 121, in initialize
    self.poll_for_timeout(poll_callback)
  File "C:\Anaconda3\lib\site-packages\mlagents_envs\rpc_communicator.py", line 112, in poll_for_timeout
    "The Unity environment took too long to respond. Make sure that :\n"
mlagents_envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Agents' Behavior Parameters > Behavior Type is set to "Default"
	 The environment and the Python interface have compatible versions.

Process finished with exit code 1

```

**Screenshots**

I could learn and run agent.

![image](https://user-images.githubusercontent.com/28804712/131082735-c861fff1-7697-4e7f-8c7a-affb5a81924f.png)

I builded my game like this.
![image](https://user-images.githubusercontent.com/28804712/131084563-de3d5393-9268-4a75-9641-d176b10cc476.png)

but error raises.

```
mlagents_envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Agents' Behavior Parameters > Behavior Type is set to "Default"
	 The environment and the Python interface have compatible versions.
```

I set my Behavior Type to "default".
![image](https://user-images.githubusercontent.com/28804712/131082287-c1c03613-f7d1-48a0-9b87-109a69ee55f3.png)

In my Settings, it doesn't work. 
also I tried to apply "3DBall", same results.
how can I fix this error?

**Environment (please complete the following information):**

OS : Windows 10
Python : Python 3.7 with Anaconda
Unity:  20.3.16.f1
Unity ML-Agent : Release 18 ( unity : 2.1.0, ml-agent : 0.27.0)

- Unity Version: 20.3.16.f1
- OS + version: Windows 10 python 3.7.9 with Anaconda3
- _ML-Agents version_: release 18(Unity 2.1.0, python 0.27.0)
- _Torch version_: 1.6.0 cuda 10.1
- _Environment_: (which example environment you used to reproduce the error)

**Comment by mmattar** [comment]
@tw0226 - to confirm, did you attempt to use the Python API with one of the environments in ML-Agents?

**Comment by tw0226** [comment]
yes. I used "3DBall" environment in ML-Agents.
but when I tested with another PC, it worked.
so I think some of python packages are conflicted.
thanks.
