### ISSUE TITLE
Possible race condition on EndEpisode

### ISSUE THREAD

**Issue by ykeuter** [Unity-Technologies/ml-agents#5520]
**Describe the bug**
While running some experiments with ML-Agents, I found two cases of what I suspect to be race conditions. I file one case here and will link the second one in a separate issue.

In this case we set a reward when the agent hits a trigger, and subsequently end the episode. One would thus expect to only see this non-zero reward in a terminal step (as opposed to decision step). Yet we sometimes see a decision step with a non-zero reward, following after a terminal step (with a non-zero reward).

It could be this is the case when the agent hits two triggers at the same time, in which case the reward of the first trigger ends up in the terminal step, while the reward of the second trigger for some reason ends up in the next decision step. This has not been verified though.

Fact is we see a non-zero reward in a decision step, with merely below reward setup.

**To Reproduce**
```
private void OnTriggerEnter(Collider other)
{
  AddReward(1);
  EndEpisode();
}
```

**Environment (please complete the following information):**
- Unity Version: Unity 2020.3.8f1
- OS + version: Windows 10 Pro
- _ML-Agents version_: ML-Agents v2.1.0-exp.1

**Comment by ykeuter** [comment]
Hi @hvpeteet , thanks for the reply. I am not sure if your suggestion totally prevents race conditions from happening. By setting a flag (and then the reward in some MLA method) we still don't know if the reward will end up in the terminal step as expected, or the next decision step.

We might just have to accept these kind of race conditions and make sure they only result in insignificant noise in the reward function.

Thanks for your help.

**Comment by hvpeteet** [comment]
Thanks, if you can reproduce a bug like this with any of our environments or a simple example I would love to see it in action.
