### ISSUE TITLE
Possible race condition on OnEnvironmentReset

### ISSUE THREAD

**Issue by ykeuter** [Unity-Technologies/ml-agents#5521]
**Describe the bug**
While running some experiments with ML-Agents, I found two cases of what I suspect to be race conditions. I file one case here and will link the second one in a separate issue.

In this case we reset the environment from our python code by calling `env.reset()` and subsequently collect the new initial observations with `env.get_steps("BehaviorName")`. One would expect the observations in the new decision step to be zero (based on the code below), yet occasionally it is non-zero!

It could be that a _buffered action_ is executed after the reset and before the next decision request, but I thought this should not be the case, since buffers are cleared during reset.

Fact is we see a non-zero observation in a decision step after reset and before sending any new actions.

**To Reproduce**
```
public class MyAgent: Agent
{
  private void Awake()
  {
    Academy.Instance.OnEnvironmentReset += ResetPlayer;
  }

  public void ResetPlayer()
  {
      transform.position = Vector3.zero;
  }

  public override void OnActionReceived(ActionBuffers vectorAction)
  {
    transform.position += transform.forward *vectorAction.ContinuousActions[0];
  }

  public override void CollectObservations(VectorSensor sensor)
  {
    sensor.AddObservation(transform.position.z);
  }
}
```

**Environment (please complete the following information):**
- Unity Version: Unity 2020.3.8f1
- OS + version: Windows 10 Pro
- _ML-Agents version_: ML-Agents v2.1.0-exp.1

**Comment by ykeuter** [comment]
link #5520

**Comment by Jmumford45** [comment]
Why not just add a check within this logic to confirm the buffer is null when assigning Vector3.zero in the Awake function?

**Comment by ykeuter** [comment]
Hi @Jmumford45 ! Thanks for your message. I guess you mean adding logic to the ResetPlayer function?

The point is one would expect the buffer to be cleared by OnEnvironmentReset in any case (without need to check). Your suggestion might work as a workaround though (right now I am adding some "empty steps" before a reset as a workaround).

**Comment by Jmumford45** [comment]
Thanks for the reply, I’m still reviewing the code outside this function and trying to run a debugging test to see when this happens
