### ISSUE TITLE
Query Stacked Vectors

### ISSUE THREAD

**Issue by gft-ai** [Unity-Technologies/ml-agents#5523]
**Is your feature request related to a problem? Please describe.**
I would like to be able to query stacked vectors with a simple call similar to Agent.GetObservations()

**Describe the solution you'd like**
A method called something like Agent.GetStackedObservations()

**Describe alternatives you've considered**
Manually storing the past N-number of observations and adding them using sensor.AddObservation() and then calling GetObservations() to get all of the observations.

**Additional context**
I am doing the inference outside of unity and that's why I need to get the observations so I can feed it to the model as inputs.

At the moment, I cannot find a function call where I can get stacked vectors. Therefore, I am manually adding them to the sensor observation vector and then getting all of the observations by calling GetObservations() function.

**Comment by mmattar** [comment]
Thanks for your request @gft-ai. I've logged this request internally (MLA-1782) and will follow up here when we are able to prioritize it.
