### ISSUE TITLE
Support for Torch 1.9

### ISSUE THREAD

**Issue by amogkam** [Unity-Technologies/ml-agents#5536]
Is support for PyTorch 1.9 on the roadmap for `mlagents`? Currently `torch` is constrained to be less than 1.9 in `setup.py`.

**Comment by TV4Fun** [comment]
Seconded, especially as the installation instructions for local development have you install the latest stable PyTorch, which is 1.10. Also, I am on an M1 mac and would like to run native ARM code, and a native ARM build of PyTorch is only available for 1.10 or later.

**Comment by StefanoCecere** [comment]
agree that changing the requirements to
"torch>=1.8.0,<=1.10.2;(platform_system!='Windows' and python_version>='3.9')"

it works well on m1, too!
