### ISSUE TITLE
Dynamically change Decision Period during Reset

### ISSUE THREAD

**Issue by MarcoMeter** [Unity-Technologies/ml-agents#5537]
**Is your feature request related to a problem? Please describe.**

Changing the Decision Period of the Decision Requester at runtime freezes the agent instead of firing an exception

**Describe the solution you'd like**
It would be great if the decision period could be changed upon runtime. The advantage of this is, that frame skipping can be setup much more efficiently if only a build of the environment is available.

**Describe alternatives you've considered**

In the case of using a custom Python environment wrapper, implementing naive frame skipping, the performance cost of the environment interaction is increased due to unnecessary socket communication. This could be avoided by treating the decision period as a reset parameter.

**Comment by vincentpierre** [comment]
Hi @MarcoMeter 
I was unable to reproduce this issue on `main` I tried to change the Decision Period on the decision requester of one of the 3DBall in the Editor but it worked as expected. Can you give some way to reproduce the freezing? How are you changing the Decision Period?
