### ISSUE TITLE
Error when trying to run docker image

### ISSUE THREAD

**Issue by Lakrix** [Unity-Technologies/ml-agents#554]
Hi, when trying out docker image from develop-feature-docker-improvements I get the following error.

Debug info from gdb:

mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb

Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.

Traceback (most recent call last):
File "python/learn.py", line 62, in 
tc.start_learning()
File "/execute/python/unitytrainers/trainer_controller.py", line 230, in start_learning
curr_info = self.env.reset(train_mode=self.fast_simulation)
File "/execute/python/unityagents/environment.py", line 276, in reset
return self._get_state()
File "/execute/python/unityagents/environment.py", line 287, in _get_state
state_dict, end_of_message = self._get_state_dict()
File "/execute/python/unityagents/environment.py", line 243, in _get_state_dict
state = self._recv_bytes().decode('utf-8')
File "/execute/python/unityagents/environment.py", line 219, in _recv_bytes
message_length = struct.unpack("I", bytearray(s[:4]))[0]
struct.error: unpack requires a buffer of 4 bytes

I run it on a Mac.
My target platform is Linux with x86_64 and I run it in headless mode.
I'm able to train using the same build file without using a docker.
I'm able to run train the grid world example using a docker.

**Comment by eshvk** [comment]
>  I run it in headless mode.

Does this simulation use visual observations? If so, you should not click on the headless option while building your linux `x86_64` executable.

**Comment by Lakrix** [comment]
Ye I'm using visual observation. Now Im not have headless option on then I get the following error instead.

mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

Traceback (most recent call last):
  File "/execute/python/unityagents/environment.py", line 107, in __init__
    self._conn, _ = self._socket.accept()
  File "/usr/local/lib/python3.6/socket.py", line 205, in accept
    fd, addr = self._accept()
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python/learn.py", line 61, in <module>
    worker_id, keep_checkpoints, lesson, seed, docker_target_name, TRAINER_CONFIG_PATH)
  File "/execute/python/unitytrainers/trainer_controller.py", line 78, in __init__
    curriculum=self.curriculum_file, seed=self.seed)
  File "/execute/python/unityagents/environment.py", line 115, in __init__
    .format(str(file_name)))
unityagents.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure /unity-volume/3Dball does not need user interaction to launch and that the Academy and the external Brain(s) are attached to objects in the Scene.

**Comment by eshvk** [comment]
Hi,
  Can you please share your code for this scene? I will try to see if I can replicate your problem and see what exactly is happening with containerization that is causing this to happen.

**Comment by Lakrix** [comment]
I figured it out. It works fine it was my environment. Thanks for fast feedback and help.

**Comment by Lakrix** [comment]
@eshvk is the docker working only on Mac and Windows and not on Linux?

**Comment by eshvk** [comment]
It works on all platforms. When you are running it on mac or windows, you are actually running a docker container inside a linux OS.
