### ISSUE TITLE
Does Unity Ml-agents support training using custom algorithms? How to do？

### ISSUE THREAD

**Issue by hxx1996** [Unity-Technologies/ml-agents#5541]
Does Unity Ml-agents support training using custom algorithms? How to do？

**Comment by vincentpierre** [comment]
Please use the template for submitting issues in the future.
The simplest way to use custom algorithms would be to use our [low-level api](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Python-API.md) for now. There is also a [notebook](https://github.com/Unity-Technologies/ml-agents/tree/main/docs#python-tutorial-with-google-colab) on how to implement Q-Learning with this API in the documentation, I would recommend starting with those.
