### ISSUE TITLE
What does "Std of Reward" mean?

### ISSUE THREAD

**Issue by jlanis** [Unity-Technologies/ml-agents#555]
I searched the docs but I didn't find any definition for the meaning of "Std of Reward" in the console output.

**Comment by awjuliani** [comment]
Hi @jlanis,

In this case `Std` corresponds to the standard deviation of the reward. It is a measure of the spread around the mean reward. A large value would indicate a lot of variation in rewards received, and a small value would indicate the opposite.

**Comment by jlanis** [comment]
@awjuliani Ah, thanks!

One other quick question I wanted to ask even though it's unrelated - I noticed that in the Balance Ball example, you had multiple instances of the agents running at the same time (connected to a single brain) to help speed up the learning process. Are there any plans to have this kind of setup unnecessary in the future - (i.e, instead of manually copy & pasting multiple instances in the Unity editor which seems a little sloppy, would it be possible to run multiple training sessions that all feed into a single brain?)

**Comment by awjuliani** [comment]
@jlanis Thanks for bringing this us. We do have plans to support more automated parallel training. Both from the perspective of allowing multiple unity processes to run at once, as well as easier tools for duplicating training areas within a scene.
