### ISSUE TITLE
index 8 is out of bounds for axis 0 with size 8

### ISSUE THREAD

**Issue by itss-K** [Unity-Technologies/ml-agents#5558]
**Describe the bug**

**To Reproduce**

**Console logs / stack traces**
Please wrap in [triple backticks (```)](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make it easier to read.

**Screenshots**

**Environment (please complete the following information):**
- Unity Version: [e.g. Unity 2020.1f1]
- OS + version: [e.g. Windows 10]
- _ML-Agents version_: (e.g. ML-Agents v0.8, or latest `develop` branch from source)
- _Torch version_: (you can run `pip3 show torch` to get this)
- _Environment_: (which example environment you used to reproduce the error)

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by itss-K** [comment]
am getting this error ..how to remove this

**Comment by andrewcoh** [comment]
Hi @itss-K 

Please provide more information so that I may better understand what is going on. Is this an example environment or your own custom environment? Are you using our trainers or your own custom trainer? Can you share the entire error trace?
