### ISSUE TITLE
Unity ML-Agents's Python library gets stuck at creating gRPC server

### ISSUE THREAD

**Issue by kenminglee** [Unity-Technologies/ml-agents#5559]
**Describe the bug**
This issue occurs while training on a headless HPC cluster (which uses the Slurm scheduler). For context, both `mlagents-learn` and using the Python API directly (with gym wrapper) works well on a local machine, but when both of these training methods were used on a HPC cluster, the code gets stuck at the point when a gRPC server is created. This behaviour was consistent across both methods of interacting with the environment. 

For convenience, the program gets stuck at `self.server = grpc.server(ThreadPoolExecutor(max_workers=10))` in `mlagents_envs > rpc_communicator.py`. The full stack trace can be found below.

**To Reproduce**
1. Build (any) environment as a Linux executable, and push it to the HPC cluster.
2. On the cluster, install all required dependencies (e.g., ML-Agents Python packages).
3. `chmod +x <executable>` on the cluster.
4. Submit job. This issue is reproducible regardless of how we choose to train the RL agent (either through `mlagents-learn` or the Python API + gym wrapper). 
5. When job gets executed, it gets stuck at the point where the gRPC server is created (refer to stack trace below). No exceptions are raised.

**Console logs / stack traces**
The following stack trace was obtained through the use of `mlagents-learn` to initiate the training process, followed by the `py-spy dump --pid <pid>` command to print out the stack trace.
```bash
Thread 36885 (active): "MainThread"
    __init__ (grpc/_server.py:958)
    create_server (grpc/_server.py:1003)
    server (grpc/__init__.py:2064)
    create_server (mlagents_envs/rpc_communicator.py:61)
    __init__ (mlagents_envs/rpc_communicator.py:51)
    _get_communicator (mlagents_envs/environment.py:252)
    __init__ (mlagents_envs/environment.py:187)
    create_unity_environment (mlagents/trainers/learn.py:175)
    worker (mlagents/trainers/subprocess_env_manager.py:160)
    run (multiprocessing/process.py:108)
    _bootstrap (multiprocessing/process.py:315)
    _launch (multiprocessing/popen_fork.py:75)
    __init__ (multiprocessing/popen_fork.py:19)
    _Popen (multiprocessing/context.py:277)
    _Popen (multiprocessing/context.py:224)
    start (multiprocessing/process.py:121)
    create_worker (mlagents/trainers/subprocess_env_manager.py:285)
    __init__ (mlagents/trainers/subprocess_env_manager.py:256)
    run_training (mlagents/trainers/learn.py:98)
    run_cli (mlagents/trainers/learn.py:246)
    main (mlagents/trainers/learn.py:250)
    <module> (mlagents-learn:8)
```

**Environment (please complete the following information):**
- Unity Version: Unity 2020.3.7f1
- OS + version: CentOS Linux 7 (Core)
- _ML-Agents version_: Release 18, v0.27.0 for both `mlagents` and `mlagents-env`
- _Torch version_: 1.8.1
- _Environment_: Any

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by sini** [comment]
Given that your log shows it as hanging in grpc's server method, it seems unlikely that this would be ML-Agents related. Looking though grpc's __init__ method called there, it's probably trying to call the C grpc library: https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_server.py#L955

I can suggest from personal experience trying to take a look at your networking -- specifically a look at your hostname and DNS and ensuring that you're able to resolve it/it exists in your /etc/hosts. That's not guaranteed to resolve your issue but you can at least rule it out.

**Comment by kenminglee** [comment]
Thanks for the reply, and for the pointers! Since this problem is unrelated to ML-Agents, I shall close this issue.
