### ISSUE TITLE
Feature Request: Configurable timeout for mlagents-learn to connect to the Unity editor

### ISSUE THREAD

**Issue by JesseTG** [Unity-Technologies/ml-agents#5561]
**Is your feature request related to a problem? Please describe.**
Unity takes a long time to start Play Mode, which is an issue in itself but not one in this project's scope. If I start Play Mode and `mlagents-learn` at the same time, `mlagents-learn` might time out before the training environment is ready.

**Describe the solution you'd like**
A command-line option that lets me decide how long I want `mlagents-learn` to wait for an editor (or player) connection before timing out.

**Describe alternatives you've considered**
Optimizing my training environment's startup. I intend to do this, but in the meantime this feature would simplify my life. Currently I wait a few seconds after clicking the Play Mode button before I start `mlagents-learn`.

**EDIT:** Another workaround is to insert a `sleep` command before `mlagents-learn`. On PowerShell, that would be...

```powershell
Start-Sleep -Seconds 60 ; mlagents-learn
```

...however, this workaround still involves an element of manual timing.

**Comment by andrewcoh** [comment]
Hi @JesseTG 

Thank you for your suggestion. I will bubble this up to the team.
