### ISSUE TITLE
IInputActionAssetProvider, IInputActionCollection2, both could not be found from importing MLAgents sample project on Unity 2020.3 LTS

### ISSUE THREAD

**Issue by chamx2** [Unity-Technologies/ml-agents#5563]
**Describe the bug**

**To Reproduce**
1. New unity project
2. Install ml agents in unity package manager
3. create venv in the project install latest pytorch and pip
4. import mlagents.extension json file from the git latest version to unity project ( https://github.com/Unity-Technologies/ml-agents/tree/main/com.unity.ml-agents.extensions)
5.  Copy https://github.com/Unity-Technologies/ml-agents/tree/main/Project and paste into the unity project file

**Console logs / stack traces**
```
Assets\ML-Agents\Examples\PushBlockWithInput\Scripts\PushBlockWithInputPlayerController.cs(20,66): error CS0246: The type or namespace name 'IInputActionAssetProvider' could not be found (are you missing a using directive or an assembly reference?)

Assets\ML-Agents\Examples\PushBlockWithInput\Scripts\PushBlockWithInputPlayerController.cs(108,31): error CS0246: The type or namespace name 'IInputActionCollection2' could not be found (are you missing a using directive or an assembly reference?)


```

**Screenshots**
![image](https://user-images.githubusercontent.com/18225573/135745218-58cf034c-1c6d-43ee-bdfb-444df5afe4f5.png)

**Environment (please complete the following information):**
- Unity Version: [e.g. Unity 2020.3.13f1]
- OS + version: [e.g. Windows 10]
- _ML-Agents version_: 2.1.0 preview
- _Torch version_: 21.1.2
- _Environment_: (which example environment you used to reproduce the error)

**Comment by hvpeteet** [comment]
Thanks for the report. Please complete the environment section as well so we can reproduce as accurately as posible.

**Comment by DY-Z** [comment]
I encountered the same errors with @chamx2 after importing example projects. But these errors disappeared after I upgraded the Input System package to the version 1.1.0-preview3. I guess this [link](https://github.com/Unity-Technologies/ml-agents/blob/d34f3cd6ee078782b22341e4ceb958359069ab60/com.unity.ml-agents.extensions/Documentation~/InputActuatorComponent.md) may also help.
