### ISSUE TITLE
Url to challenges doesn't exist anymore

### ISSUE THREAD

**Issue by Freshchris01** [Unity-Technologies/ml-agents#5569]
Hello! The following url does not exist anymore.
Sadly I didn't find the new link for the resources. Should the link be corrected or removed?
https://github.com/Unity-Technologies/ml-agents/blob/37a6aa2b1555beaca79bb93d5b5e0e326a4b364d/docs/Learning-Environment-Examples.md#L10

**Comment by mmattar** [comment]
@Freshchris01 - thanks for letting us know. You are correct that this should be removed. I'll create a PR for it.
