### ISSUE TITLE
Custom neural nets.

### ISSUE THREAD

**Issue by Andrealberti** [Unity-Technologies/ml-agents#5574]
Hi,
I am working on a project and I need to define a custom model of the neural network, in particular I need to set a conv1d configuration for the inputs. I didn't find so much about this, so I have been posting here hoping you could help me, is it possible to do that? How?. Thanks in advance.

**Comment by mmattar** [comment]
Hi @Andrealberti - unfortunately, we don't provide a mechanism to easily customize our trainers, but it is something we're currently exploring. Part of the challenge here is that we wouldn't be able to guarantee that the model you've trained will be supported by Barracuda (the inference library we use). One option which I think you're already exploring based on another GitHub Issue is to implement your own trainer directly using our ml-agents-env or gym-unity wrappers. Does this make sense?

**Comment by Andrealberti** [comment]
Hi @mmattar, 
Thanks for your reply, now it is all super clear, I just wanted to have a confirm of what I have seen both in forum and here in the issues. I know the problems of barracuda, but if I am not mistaken, the conv1d layers, which is the one I need, is supported by the library, isn't it? 
Then, talking about ml-agents-env or gym-unity wrappers, yes, at the moment I was exploring these options, but I have found the implementation very hard,  I have communication problems between my UnityEnv and the PythonAPI, here is the error: 

> mlagents_envs.exception.unitytimeoutexception: the unity environment took too long to respond. make sure that : 
> the environment does not need user interaction to launch the agents' 
> behavior parameters > behavior type is set to "default" 
> the environment and the python interface have compatible versions.

Anyway, now the challenge is trying add a class 1Dencoder here: https://github.com/Unity-Technologies/ml-agents/blob/003e8aed3be28c56ea6b9b7d784cc142d41e7c19/ml-agents/mlagents/trainers/torch/encoders.py#L177 
adding in it Conv1d layers, the aim is to process the output vector of the lidar as an audio signal, in case of good results I will let you know.
Feel free to give me your feedback on my last idea, I will appreciate it.
Thanks a lot.
Regards,
Andrea
