### ISSUE TITLE
Checking out main branch requires 2.37 GiB download

### ISSUE THREAD

**Issue by TV4Fun** [Unity-Technologies/ml-agents#5590]
**Describe the bug**
Cloning the full ml-agents repo is a giant download, using 2.6GB on disk, of which 2.4GB are in the `.git/objects/pack` folder. Obviously this is because of the binaries included in the repo, not just the current versions, but also all past versions. It would really be better to have a script to just download the current versions or build them for sources.

**To Reproduce**
1. Clone the main branch of the ml-agents repo.

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by miguelalonsojr** [comment]
@TV4Fun Thanks for bringing this to our attention. Changing the label to a request. We'll take a look.
