### ISSUE TITLE
Change TimeScale from Python

### ISSUE THREAD

**Issue by dracolytch** [Unity-Technologies/ml-agents#56]
Hey all, debugging my first custom environment. It'd be great if there were a fast/easy way to change the Academy's TimeScale from a setting in python, so that we could have things be really slow for debugging the ML interface, and then crank it up for actual training.

**Comment by awjuliani** [comment]
@dracolytch,

Thanks for your interested in ML-Agents! 

You can change the time scale from the Academy inspector window from within the Unity editor: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Agents-Editor-Interface.md#academy

If you want to change via python, it is possible to switch between training and inference models when restarting the environment by using `env.reset(train_mode=True/False)`.
