### ISSUE TITLE
How can I get `vector_observations`?

### ISSUE THREAD

**Issue by Lee-JaeWon** [Unity-Technologies/ml-agents#5607]
I am having difficulty learning by connecting the external API and the unity environment I have created.

I was looking DQN code of previous ml-agent version but i want to use the following code using current version.

```python
# reset the unity environment at the beginning of each episode
    env_info = env.reset(train_mode=True)[brain_name]     

    # get initial state of the unity environment 
    state = env_info.vector_observations[0]
```
How should I use this in the current ml-agents version?
And what exactly does this mean?
I mean, why is that becoming a 'state' of Environment?

I'm sorry to bother you.

**Comment by sini** [comment]
This support question is likely better suited for the official ML-Agents forums found here: [https://forum.unity.com/forums/ml-agents.453/](https://forum.unity.com/forums/ml-agents.453/)
