### ISSUE TITLE
CollectObservations() sensor is null when SpaceSize equals zero

### ISSUE THREAD

**Issue by vinzentp** [Unity-Technologies/ml-agents#5612]
**Description**
This is actually more about an unclear error message than a bug. 
When you call CollectObservations without having increased the VectorObservation.SpaceSize (in Behaviour Parameters) to >0, the sensor passed to the CollectObservations() method will be null and a NullPointer error is thrown. It took me some time to figure out where this error came from. Maybe you can display a warning when SpaceSize is zero and CollectObservations is overritten, that the user is supposed to increase the SpaceSize.

**Comment by jrupert-unity** [comment]
I think this is a good suggest and it has been added to Jira as MLA-2322.

**Comment by jrupert-unity** [comment]
Replying to remove stale label.
