### ISSUE TITLE
Strange behaviour for SAC and GAIL 

### ISSUE THREAD

**Issue by MrOCW** [Unity-Technologies/ml-agents#5613]
Hi,

I'm trying to train a car to drive in lane using GAIL but it seems that GAIL is disabled (?) after awhile.
![image](https://user-images.githubusercontent.com/67644448/141410805-5f978e67-7814-4766-8d91-99906f314327.png)
![image](https://user-images.githubusercontent.com/67644448/141410831-46014c5b-d9c8-4f9a-b236-bc339a8ea030.png)

Also, for SAC, the environment freezes for a long time (presumably for updating the network) and many summary steps get shown in batches
![image](https://user-images.githubusercontent.com/67644448/141411087-bd2819f5-e710-45d5-87c9-9feb55e15f70.png)
If i increase the batch size from 256 to 512, the environment freezes for as long as 5min 

**Environment (please complete the following information):**
- Unity Version: 2020.3.11f1
- OS + version: Ubuntu 18.04
- _ML-Agents version_: ML-Agents v2.1
- _Torch version_: 1.8.2 + cuda 11, RTX3070Ti
[configuration.txt](https://github.com/Unity-Technologies/ml-agents/files/7524978/configuration.txt)

**Comment by andrewcoh** [comment]
Hi @MrOCW 

Can you share your entire yaml file? It looks like the discriminator in GAIL is breaking but it's not clear why just from these curves.

Are you seeing other large time intervals between summaries or is the screenshot the only time this occurs? Does this screenshot coincide with the degradation of GAIL?

Can you share the other TB curves e.g. policy entropy? Are you seeing any NaNs either in C# or python?

**Comment by MrOCW** [comment]
@andrewcoh 
YAML
```
trainer_type:   sac
hyperparameters:    
  learning_rate:    0.0003
  learning_rate_schedule:   constant
  batch_size:   256
  buffer_size:  58000
  buffer_init_steps:    10000
  tau:  0.005
  steps_per_update: 4.0
  save_replay_buffer:   False
  init_entcoef: 0.5
  reward_signal_steps_per_update:   10.0
network_settings:   
  normalize:    False
  hidden_units: 256
  num_layers:   1
  vis_encode_type:  simple
  memory:   None
  goal_conditioning_type:   none
reward_signals: 
  extrinsic:    
    gamma:  0.99
    strength:   1.0
    network_settings:   
      normalize:    False
      hidden_units: 128
      num_layers:   2
      vis_encode_type:  simple
      memory:   None
      goal_conditioning_type:   hyper
  gail: 
    gamma:  0.99
    strength:   0.5
    network_settings:   
      normalize:    False
      hidden_units: 128
      num_layers:   2
      vis_encode_type:  simple
      memory:   None
      goal_conditioning_type:   none
    learning_rate:  0.0003
    encoding_size:  None
    use_actions:    True
    use_vail:   False
    demo_path:  ..................../Assets/Demonstrations
init_path:  None
keep_checkpoints:   5
checkpoint_interval:    200000
max_steps:  3000000
time_horizon:   64
summary_freq:   500
threaded:   True
self_play:  None
behavioral_cloning: None
```

For the time intervals, yes, it happens throughout training. To elaborate, printing of summary steps happens in batches after large time intervals. It does not seem to have any relation with the GAIL issue

![image](https://user-images.githubusercontent.com/67644448/143904460-d59674dd-24e3-4eb4-9882-31da95f9dabb.png)
![image](https://user-images.githubusercontent.com/67644448/143904557-7a0f0f21-ecae-4c03-9211-e1851b69fe6a.png)
![image](https://user-images.githubusercontent.com/67644448/143904645-619271da-e6e8-42bd-a362-16bd4b7ab1b7.png)

Have not seen any NaNs in anywhere.

**Comment by MrOCW** [comment]
@andrewcoh any updates on this issue?

**Comment by MrOCW** [comment]
@andrewcoh i noticed that this happens during checkpoint saving. it might be possible that the saving process has some conflicts with GAIL.
