### ISSUE TITLE
Dynamic feature and interface about ML-Agents.

### ISSUE THREAD

**Issue by gwc0111** [Unity-Technologies/ml-agents#5618]
1. I want to set Behavior Parameters dynamic, so that I can switch mode in running.
2. Could you add interface to get necessary information from sensors? I want to read RayPerceptionOutput.RayOutput from RayPerceptionSensorComponent2D so that I can dynamic programing, but I found there is no interface.

**Comment by andrewcoh** [comment]
Hi @gwc0111 

1. Which part of the Behavior Parameters script do you want to modify at runtime? These parameters all correspond to static components of a neural network so they should remain fixed and NOT modified at runtime.
2. I'm not sure I understand this question. Do you want to do some preprocessing of the rayperception output before it is sent to python?

**Comment by gwc0111** [comment]
@andrewcoh 
1. Actually, I want to sorting layer to train my agent (a brain agent and many subagents), so I want to change the model and all parameters(observations, actions, etc) before. After I found it don't support modify at runtime. I use another way to organize my agents.
2. Yeah, I want to preprocessing of the rayperception output before it is sent to python, such as the name of gameobject with special tags. I have written a new component from RayBase to get them.

**Comment by andrewcoh** [comment]
Ok, sounds like you were able to solve both of your problems. As for (2), this is a good solution as the sensor component system is intended to be extensible.
