### ISSUE TITLE
Use ELO as completion criteria of a curriculum lesson

### ISSUE THREAD

**Issue by hk1ll3r** [Unity-Technologies/ml-agents#5623]
**Is your feature request related to a problem? Please describe.**
I am training an agent using self-play and curriculum. Since the agent is playing itself, its reward will not increase but its ELO level will. Would be nice to be able to advance curriculum lessons by ELO rather than reward or progress (of steps as is currently supported).

**Describe the solution you'd like**
be able to use ELO as completion criteria for a curriculum lesson like below:
environment_parameters:
  my_environment_parameter:
    curriculum:
      - name: MyFirstLesson
        completion_criteria:
          measure: ELO # new criteria
          behavior: my_behavior
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1200
        value: 0.0

**Describe alternatives you've considered**
Right now I guestimate how many steps it takes to reach a certain ELO and use "progress" with those guesses.

**Additional context**

**Comment by jrupert-unity** [comment]
The request makes sense, a custom measure for advancing the curriculum training would be useful.  How does Elo rating change with self-play though?

**Comment by miguelalonsojr** [comment]
ELO should go up over time as agents increase their skill level when training with self-play.

**Comment by jrupert-unity** [comment]
I see.  Elo is an existing measure and the learning agent plays against an earlier version (frozen)?

**Comment by hk1ll3r** [comment]
> I see. Elo is an existing measure and the learning agent plays against a frozen (non-learning) opponent?

Yes Elo goes up meaning the AI is better but the reward per episode stays the same cause the agent is playing against itself and the game is a zero sum game (like soccer). The opponent is not fully frozen, but a few generations behind or ahead.

**Comment by jrupert-unity** [comment]
The changes on this branch allow you to drive curriculum steps with the Elo score.
https://github.com/Unity-Technologies/ml-agents/tree/dev_curriculum_with_elo

Example of environment_parameters I tested it with (added to SoccerTwos.yaml):

environment_parameters:
  ball_touch:
    curriculum:
      - name: Lesson0 # The '-' is important as this is a list
        completion_criteria:
          measure: Elo
          behavior: SoccerTwos
          signal_smoothing: false
          min_lesson_length: 100
          threshold: 1250.0
        value: 1.0    
      - name: Lesson1 # The '-' is important as this is a list
        value: 0.0

**Comment by hk1ll3r** [comment]
Thanks @jrupert-unity. Any plans to merge into master?
