### ISSUE TITLE
agent_id keeps increasing in Python API after setting activate(false) and activate(true)

### ISSUE THREAD

**Issue by YuxuanXie** [Unity-Technologies/ml-agents#5631]
**Describe the bug**
I am training agents through Python API. My environment requires death and respawn. In unity I create agents by using defined agent prefab. If an agent dies I call agent.gameobject.setActivate(false). Later the agent respawns and agent.gameobject.setActivate(false) is called. My issue is that when I access the environment through Python API, agent_id keeps increasing in Python API after calling agent.gameobject.setActivate(false) and agent.gameobject.setActivate(true).

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by jrupert-unity** [comment]
Thank you for reporting this, I will reply again after discussing this with the team.

Tracking the issue in Jira as MLA-2320.

**Comment by jrupert-unity** [comment]
Replying to remove the stale label.  This is still on the list of things to address.

**Comment by jrupert-unity** [comment]
Bump.
