### ISSUE TITLE
Is this a typo in documentation?

### ISSUE THREAD

**Issue by trsh** [Unity-Technologies/ml-agents#5633]
**Describe the bug**

https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Getting-Started.md states:

_"If the model is trained with Release 19 or later, you can select Deterministic Inference to choose actions deterministically from the model. Works only for inference within unity with no python process involved."_

When there is no such thing as "Release 19" > https://github.com/Unity-Technologies/ml-agents/releases . Its very confusing.

**Comment by jrupert-unity** [comment]
It isn't a typo, Release 19 just hasn't been cut yet but the documentation has been updated to reflect the state of main branch.  Release 19 will have this feature, and if you [install from a clone of the repo](https://github.com/Unity-Technologies/ml-agents/blob/main/com.unity.ml-agents/CHANGELOG.md) you should have it too.  You can see the changelog for the yet unreleased version [here](https://github.com/Unity-Technologies/ml-agents/blob/main/com.unity.ml-agents/CHANGELOG.md).

**Comment by jrupert-unity** [comment]
I agree that it is confusing in the (hopefully brief) stretch before Release 19 is out.

**Comment by trsh** [comment]
This is lot of confusion. Unity could:

a) Put a warning, that this is WIP version docs;
b) Handle docs in a way, that the default one corresponds to latest release;

**Comment by jrupert-unity** [comment]
Thank you for the feedback, I will discuss it with the team.

**Comment by miguelalonsojr** [comment]
Fixed with https://github.com/Unity-Technologies/ml-agents/pull/5637.
