### ISSUE TITLE
Unity inputsystem 1.2.0 Error

### ISSUE THREAD

**Issue by LuckyLeeLL** [Unity-Technologies/ml-agents#5635]
**Describe the bug**
When i load the project in unity， there has a bug:

Library/PackageCache/com.unity.inputsystem@1.2.0/InputSystem/Plugins/UnityRemote/UnityRemoteSupport.cs(284,49): error CS0252: Possible unintended reference comparison; to get a value comparison, cast the left hand side to type 'string'

**Screenshots**
As the picture shows:
![image](https://user-images.githubusercontent.com/48266412/145968648-ffe1eb21-cea8-40d9-95aa-d41f80b777f2.png)

I test the main version and the release 18, both have this issue.

**Environment (please complete the following information):**
- Unity Version: 2020.3.24.f1
- OS + version: ubuntu18.02

Thank you very much!

**Comment by pranavvaidik** [comment]
I get the same issue, but on Windows 10.

**Comment by maryamhonari** [comment]
Hi! Thanks for bringing this up. This is a known issue with InputSystem 1.2.0 package. You can clear `Project/Assets/csc.rsp` file to stop treating warnings as errors or downgrade to InputSystem 1.1.1 if that's an option.

**Comment by ZorroStardust** [comment]
@maryamhonari thanks a lot for solving this problem, it really works! I'm a total beginner, it took me whole day to find out why, I just couldn't figure it out. If I knew there was this issue on Github, I could have saved several god damn hours...
