### ISSUE TITLE
questions about activation functions

### ISSUE THREAD

**Issue by zxiaoyusq** [Unity-Technologies/ml-agents#5636]
I found that the activation functions of the dense layer are sigmoid, why not use relu?Can I use a custom activation function?Thank you!

**Comment by jrupert-unity** [comment]
Hi and thanks for the question.  You might be seeing a Swish activation, x*sigmoid(x)?  

There's no way to configure the activation functions without changing the Python code, but if you search for "Swish" in the mlagents/trainers/torch/ folder you find where you can do that.

**Comment by jrupert-unity** [comment]
Let me know if this helps or if you have further questions or requests.

**Comment by zxiaoyusq** [comment]
Thanks a lot, that's exactly what I'm looking for

**Comment by jrupert-unity** [comment]
Glad to help..
