### ISSUE TITLE
Unity Time Out Exception in modified PushBlockColab Environment

### ISSUE THREAD

**Issue by swagzinna** [Unity-Technologies/ml-agents#5647]
**Describe the bug**

Hi,
I changed the PushBlockColab environment by Unity  to a two team competitive Environment (see in Screenshots). In order to train faster, i wanted to firstly train the original env (worked just fine), then initialize the brain in the smaller Team environment (see also below) and finally use tha brain to initialize the final environment. Issue: The "smaller" environment is not working! After about 100.000-500.000 Steps the timeOutException occurs (also see below). The weird thing: The bigger environment works just fine, therefore it cant be a Problem with incompetible versions. Also: behaviour param is definetly set to "Default" and the environment does not need any interaction to launch.

**To Reproduce**
1. Got to https://github.com/swagzinna/PushBlockCollabTeams/tree/master and download Project from master branch
2. start Training using : srun mlagents-learn Project/config/PushBlock_selfPlay.yaml --run-id=easyEnvTest --base-port=5105 --env=Project/Builds/PBT_easy.x86_64 --num-envs=40
--> Error should occur afterabout 200.000 steps

**Console logs / stack traces**

```
[INFO] PushBlockCollab. Step: 160000. Time Elapsed: 500.124 s. Mean Reward: 0.000. Mean Group Reward: 0.179. Training.
[INFO] Exported results/PBTeasy3.30/PushBlockCollab/PushBlockCollab-160448.onnx
[INFO] Copied results/PBTeasy3.30/PushBlockCollab/PushBlockCollab-160448.onnx to results/PBTeasy3.30/PushBlockCollab.onnx.
[ERROR] SubprocessEnvManager had workers that didn't signal shutdown
[ERROR] A SubprocessEnvManager worker did not shut down correctly so it was forcefully terminated.
Traceback (most recent call last):
  File "/home/smleswaz/.local/bin/mlagents-learn", line 8, in <module>
    sys.exit(main())
  File "/home/smleswaz/.local/lib/python3.7/site-packages/mlagents/trainers/learn.py", line 250, in main
    run_cli(parse_command_line())
  File "/home/smleswaz/.local/lib/python3.7/site-packages/mlagents/trainers/learn.py", line 246, in run_cli
    run_training(run_seed, options)
  File "/home/smleswaz/.local/lib/python3.7/site-packages/mlagents/trainers/learn.py", line 125, in run_training
    tc.start_learning(env_manager)
  File "/home/smleswaz/.local/lib/python3.7/site-packages/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/home/smleswaz/.local/lib/python3.7/site-packages/mlagents/trainers/trainer_controller.py", line 176, in start_learning
    n_steps = self.advance(env_manager)
  File "/home/smleswaz/.local/lib/python3.7/site-packages/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/home/smleswaz/.local/lib/python3.7/site-packages/mlagents/trainers/trainer_controller.py", line 234, in advance
    new_step_infos = env_manager.get_steps()
  File "/home/smleswaz/.local/lib/python3.7/site-packages/mlagents/trainers/env_manager.py", line 124, in get_steps
    new_step_infos = self._step()
  File "/home/smleswaz/.local/lib/python3.7/site-packages/mlagents/trainers/subprocess_env_manager.py", line 310, in _step
    raise env_exception
mlagents_envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Agents' Behavior Parameters > Behavior Type is set to "Default"
	 The environment and the Python interface have compatible versions.
srun: error: cstd01-150: task 0: Exited with exit code 1
```

**Screenshots**

Original PushBlockColab Env:
<img width="406" alt="PBoriginal" src="https://user-images.githubusercontent.com/75215005/146751206-687bde9c-9c9b-44cc-8d43-6a1429dac107.png">

Modified Env, for two Opposing teams, simple in order to train faster (DOES NOT WORK!)
<img width="376" alt="PBT_easy" src="https://user-images.githubusercontent.com/75215005/146751209-2210d022-3f83-4bc7-a34b-a73d657a0f4d.png">

Modified Env, final environment (does work)
<img width="355" alt="PBT_final" src="https://user-images.githubusercontent.com/75215005/146751212-193eb88a-677c-4bc3-8569-55f8898a6238.png">

**Environment**
- Unity Version: 2021.1.22f1 (but also tried 2019.4.25f)
- OS + version: Windows 10, but learning is done on Linux Cluster (but also didnt work on own Windows PC)
- _ML-Agents version_: Release 18
- _Torch version_: 1.8.1

Any suggestion is welcome, i really need this to work for my bachelors thesis.
Thanks a lot in advance,
Leon

**Comment by hvpeteet** [comment]
Hi, and thanks for your interest in ml-agents. Our community is very helpful for these kinds of issues and I would recommend posting on our forums where many more people can help. I have removed the `bug` label since we try to reserve it for bugs with our repo rather than bugs in user code. Please feel free to add it back if a further investigation points to something wrong with our repo.

**Comment by miguelalonsojr** [comment]
We are now using the [Unity forums](https://forum.unity.com/forums/ml-agents.453/) to handle [discussions, installation issues, etc] like this. Please create a new thread there, in order to get the community involved in the discussion, and reply with the link to your forum thread. Closing this issue.
