### ISSUE TITLE
is it possible to train the agents while the player is playing ?

### ISSUE THREAD

**Issue by slender9168** [Unity-Technologies/ml-agents#565]
Hi,
right now all the training is done using python, is it possible to train the agents while the player is playing ?

Thanks.

**Comment by MarcoMeter** [comment]
Hi @slender9168 
check out the feature [Imitation Learning](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-Imitation-Learning.md)

**Comment by awjuliani** [comment]
Hi @slender9168 ,

We currently only support training using python. As we develop ML-Agents, our goal is to make it easier to work more from the editor, as well as to make installing and running python as simple as possible. We don't currently have plans for C# only training though.

**Comment by Fangh** [comment]
Can we use 
`python3 python/learn.py <env_name> --train --slow`

and have a button "AddReward" in the game and train an agent with this ?

**Comment by MarcoMeter** [comment]
I don't think this is not feasible with the current state-of-the-art of reinforcement learning, because an agent might need millions of learning steps and thorough exploration. Training in real-time would probably last for days, if not weeks.

**Comment by awjuliani** [comment]
Hi @Fangh.

That is an interesting idea. It would certainly be possible to do what you are suggesting. As @MarcoMeter mentioned though, you'd want to have a lot of patience with the process, as it would likely take quite a while.

I am going to close out this issue, but if you want to continue discussion, feel free to re-open it or to create a new issue.
