### ISSUE TITLE
Cant import package

### ISSUE THREAD

**Issue by XiYuan68** [Unity-Technologies/ml-agents#5651]
**Describe the bug**
Able to install, but cant import the package as [https://github.com/Unity-Technologies/ml-agents/blob/release_18_docs/docs/Getting-Started.md#installation](https://github.com/Unity-Technologies/ml-agents/blob/release_18_docs/docs/Getting-Started.md#installation) says

**To Reproduce**
1. Go to 'Package Manager'
2. Click on 'ML Agents'
4. See error: there is not a `import` button

**Console logs / stack traces**
none

**Screenshots**
![UnityMLAgentImport](https://user-images.githubusercontent.com/13471851/147175279-3aa809d4-9ed3-4cf8-8f43-0d541aa7d81e.png)

**Environment (please complete the following information):**
- Unity Version: [e.g. Unity 2020.3.10f1c1]
- OS + version: [e.g. Windows 10]
- _ML-Agents version_: (2.1.0-exp.1 (installed locally))
- _Torch version_: (1.7.1+cu110)
- _Environment_: (none)

I notice that there is a Not Responding `Baking shaders` at the right bottom of the editor, would that cause the problem? Thanks advance for any advice.

**Comment by jrupert-unity** [comment]
The way I've always used the examples is by following these steps:
1. From the Unity Hub, ADD a new project.
2. Navigate to the ml-agents folder you got from GitHub
3. Choose the "Project" folder there.
4. This should load a project with scenes for all of the Examples, including 3DBall, which you can open by navigating to the corresponding Scene folder for the example you want from the **Project** window.

I'll will follow up to understand why the documented steps do not work, but hopefully this helps in the meantime.

**Comment by XiYuan68** [comment]
Thank you for the help! This is a nice work-around, but being able to import individual small projects like 3DBall and such would be more flexible.

**Comment by xcao65** [comment]
The ask has been fulfilled by this commit: https://github.com/Unity-Technologies/ml-agents/commit/ed0aabc6780230eddc06fd53dd3250d8375ab161
