### ISSUE TITLE
No worker-id parameter, cannot run 2 simultaneous instances

### ISSUE THREAD

**Issue by zenith-jacob** [Unity-Technologies/ml-agents#5653]
**Describe the bug**

I cannot run 2 or more trainings at the same time. The parameter `worker-id` doesn't exist anymore (the documentation states we should use it) but it does nothing. When I typed `mlagents-learn --help` there's no worker-id parameter.

I've tried creating 2 separate python virtual environments (venv1 and venv2) but it doesn't work either. Throws this error when I try to run the second one:

_mlagents_envs.exception.UnityWorkerInUseException: Couldn't start socket communication because worker number Couldn't start socket communication because worker number 0 is still in use. You may need to manually close a previously opened environment or use a different worker number. is still in use. You may need to manually close a previously opened environment or use a different worker number._

This is the command I use:
`mlagents-learn /pathtoconfig/ml_config.yaml --env=/pathtoexecutable/build --force --num-envs=2 --env-args --worker-id=5 -logfile log1.txt startlevel 1 endlevel 10 --run-id=brain6`

**Comment by stephaneclotildegameloft** [comment]
Having the same issue. I did a hack by modifying environment.py to force worker_id and it worked but it's not very practical.

**Comment by miguelalonsojr** [comment]
Thanks for your reply. Since this still seems like a concern, I'm re-openning the issue.

**Comment by KareemSaysHi** [comment]
I'm having a similar issue
