### ISSUE TITLE
Bug:  Latest version that works is the Verified Package 1.0.8 (OLD Version) . Has anyone got a later version to work?

### ISSUE THREAD

**Issue by VirajVaitha123** [Unity-Technologies/ml-agents#5656]
Hi there,

You have a table on this website which indicated which files and unity packages to install.
https://github.com/Unity-Technologies/ml-agents/tree/release_18_docs

I followed the row for release 18 since this is the one you call stable and to get started with.

) I downloaded the repo through this webpage (release_18), and also tried cloning the release 18 branch when I faced errors
) I installed the MLAgents package 2.1.0 and the .extensions from the cloned repo (advanced installation steps)
) I pip installed pytorch 1.7.1 and python package ml-agents =0.27.0

This is 2 of 32 errors seen:
Assets\ML-Agents\Examples\PushBlockWithInput\Scripts\PushBlockActions.cs(15,19): error CS0234: The type or namespace name 'InputSystem' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)

Assets\ML-Agents\Examples\PushBlockWithInput\Scripts\PushBlockWithInputPlayerController.cs(54,26): error CS0246: The type or namespace name 'InputAction' could not be found (are you missing a using directive or an assembly reference?)

This looks like a common problem mentioned by others online on Youtube and stackoverflow, but I would think the issue is solved within the repo considering it is the latest stable version?

Thanks,

Viraj

**Comment by miguelalonsojr** [comment]
There was an issue with the previous version of the input manager, v1.2.0. v1.3.0 was released this week and **main** has been patched. Give it a shot. We're ramping up for release 19 now, which should be out in the next couple of weeks and will have this fix. For now, **main** should get you going.

**Comment by VirajVaitha123** [comment]
Thanks so much.

I actually got release 18 to work by simply removing the one enviroment (push block with input).

This led to the errors. For future builds you could  install the environment seperately or just keep in mind MLAgents is actually working fine but it's just the environment (game) that has some problems.

I'll use the version I have now until release 19.

Amazing project and thanks for your help.
