### ISSUE TITLE
PPO+GAIL performing worse than only PPO

### ISSUE THREAD

**Issue by MrOCW** [Unity-Technologies/ml-agents#5657]
Hi,
This is an agent learning to drive and keep in lane
Red = PPO
Grey = PPO+GAIL @ 0.5 reward strength
Demonstrations recorded by PPO (red) model with deterministic inference
Any suggestions as to why GAIL is not improving the learning process?
I believe it will not exceed the red graph since demonstrations are recorded with the PPO model (red graph)?
In this case, it should supposedly improve the learning speed?

Could this be a bug?

**Screenshots**
![image](https://user-images.githubusercontent.com/67644448/148012749-727782f5-bd1e-46d6-9f45-2b066172468a.png)

![image](https://user-images.githubusercontent.com/67644448/148012445-81322574-1a9d-4f25-92c2-0cf28188e08c.png)

**Environment**
- Unity Version: 2020.3.11
- OS + version: Ubuntu 18.04
- _ML-Agents version_: ML-Agents 2.1.0 (main branch)
- _Torch version_: 1.8.2

**Comment by miguelalonsojr** [comment]
Seems like you're using a custom environment. We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.
