### ISSUE TITLE
Can't add/import .onnx model created with raylib to assets

### ISSUE THREAD

**Issue by Freshchris01** [Unity-Technologies/ml-agents#5666]
**Describe the bug**
I trained my model with [raylib](https://docs.ray.io/en/latest/rllib/index.html) to make use of parallelization capabilities with a Unity3d  ml-agents environment.
I saved the model in the `.onnx` format and tried to import it into the editor to the model in action. During the import, I encounter an error.
From what I see, all the onnx operators are implemented, but I am not an expert in creating models/model structures.
I assume the model is valid since I can inspect it online with https://netron.app/.
I'm appreciating any help or tips how to import my model. You can find the model attached as [zip file](https://github.com/Unity-Technologies/ml-agents/files/7824845/saved_model.zip).
**To Reproduce**
1. Create new Unity project
2. Install Barracuda package version 2.0.0 (Package Manager -> Add package from git URL -> url: `com.unity.barracuda`)
3. Drag the model into the assets folder

**Console logs / stack traces**
```
Asset import failed, "Assets/saved_model.onnx" > OnnxImportException: Unexpected error while parsing layer TouchCubeVector/unstack:0 of type Split.
Unsupported default attribute `split` for node TouchCubeVector/unstack:0 of type Split. Value is required.

Json: { "input": [ "TouchCubeVector/Cast_7:0" ], "output": [ "TouchCubeVector/unstack:0", "TouchCubeVector/unstack:1", "TouchCubeVector/unstack:2", "TouchCubeVector/unstack:3", "TouchCubeVector/unstack:4", "TouchCubeVector/unstack:5", "TouchCubeVector/unstack:6" ], "name": "TouchCubeVector/unstack", "opType": "Split", "attribute": [ { "name": "axis", "i": "1", "type": "INT" } ] }
  at Unity.Barracuda.ONNX.ONNXModelConverter+<>c.<UseStandardImporter>b__23_10 (Unity.Barracuda.ModelBuilder net, Unity.Barracuda.ONNX.ONNXNodeWrapper node) [0x0001b] in /home/freshchris/Documents/ma/model_import_test/Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:353 
  at Unity.Barracuda.ONNX.ONNXModelConverter.ConvertOnnxModel (Onnx.ModelProto onnxModel) [0x003ec] in /home/freshchris/Documents/ma/model_import_test/Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:2798 

Unity.Barracuda.ONNX.ONNXModelConverter.Err (Unity.Barracuda.Model model, System.String layerName, System.String message, System.String extendedMessage, System.String debugMessage) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:3298)
Unity.Barracuda.ONNX.ONNXModelConverter.ConvertOnnxModel (Onnx.ModelProto onnxModel) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:2807)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:155)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:83)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Editor/ONNXModelImporter.cs:58)
UnityEditor.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext ctx) (at /home/bokken/buildslave/unity/build/Modules/AssetPipelineEditor/Public/ScriptedImporter.cs:22)

```

**Environment (please complete the following information):**
- Unity Version: Unity 2020.3.23f1.1294 Personal
- OS + version: Ubuntu 18.04 LTS
- Barracuda : 2.0.0
- _Environment_:  New Unity Project

**Comment by jrupert-unity** [comment]
The Barracuda ONNX implementation wants the split attribute on the Split operator to be given explicitly.  It looks like the first Split has it, but the second one does not.  You can make the ONNX model have the required split attribute or get Barracuda to handle the case when it isn't present.  

ml-agents\Project\Library\PackageCache\com.unity.barracuda@2.3.1-preview\Barracuda\Runtime\ONNX\ONNXModelConverter.cs  ~Line 1430

If instead of throwing an exception this is done, then there are no errors:
```
                try
                {
                    splits = node.GetRequiredIntArray("split");
                }
                catch (OnnxLayerImportException)
                {
                    splits = new int[] { 1, 1, 1, 1, 1, 1, 1 };
                    //throw new OnnxLayerImportException($"Unsupported default attribute `split` for node {node.Name} of type Split. Value is required.");
                }

```
You may want to raise this problem with the [Barracuda team](https://github.com/Unity-Technologies/barracuda-release/issues).

**Comment by jrupert-unity** [comment]
Once this problem is resolved you might want to look at the example [here](https://github.com/Unity-Technologies/ml-agents/blob/main/colab/Colab_UnityEnvironment_2_Train.ipynb) for how to export an ML-Agents model from PyTorch to comply with the expectations of Barracuda for inference.

**Comment by Freshchris01** [comment]
Thanks for your fast response! 
Closing this for now.
