### ISSUE TITLE
OnActionReceived always returns zero values

### ISSUE THREAD

**Issue by dimok135** [Unity-Technologies/ml-agents#5672]
When I start training 3DBall demo scene, OnActionReceived always returns zero values, so the cubes never rotate. Neither unity nor python shows any errors.
I'm using Unity 2020.3.25f1, ML Release 18 (v2.1.0-exp.1, Python Package 0.27.0)
Changing old Input system to the new version didn't help.

P.S. The same python package is working fine with an old version of mlagents on Unity 2018.

Video:
[https://www.youtube.com/watch?v=eQzFykqW3Ac](https://www.youtube.com/watch?v=eQzFykqW3Ac)

Unity project:
https://www.dropbox.com/s/ukd64sfjfqtiuw0/mltest2020.7z?dl=0

**Environment:**
- Unity Version: Unity 2020.3.25f1 Personal
- OS + version: Windows 10 Pro x64
- _ML-Agents version_: v2.1.0-exp.1
- _Torch version_: 1.10.1
- Python version: 3.7.6

**Comment by miguelalonsojr** [comment]
From the video it seems like you're using very old version of the ml-agents and ml-agents-env packages (0.17 for both versions.) 

![image](https://user-images.githubusercontent.com/76960110/148819187-44e5ef82-42e9-452c-9f75-5cc59ee779cb.png)

Version 2.1.0-exp.1 of the ML-Agents Unity package depends on v0.27.0 of the python packages. Also, we no longer support TensorFlow. Please update the python packages, as well as, switch to PyTorch for the best results.

**Comment by dimok135** [comment]
**miguelalonsojr**, Thank you very much! I had a mess in my python environment, so when I updated mlagents to 0.27, pip did something strange. I have checked it and now it works fine!
