### ISSUE TITLE
Cannot run Environement from Inside Spyder (UnityTimeOut)

### ISSUE THREAD

**Issue by Phoenix-surgere** [Unity-Technologies/ml-agents#5676]
**Describe the bug**
After quite a lot of hardship getting the built to complete, I've come across the "UnityTimeOutException" error while trying to create a custom environment with anaconda and spyder. I thought I was up-to-date with the versions but apparently, that is not the case and I do not understand what I should do to solve the issue.

Isn't the latest version of ml-agents, release 18, supposed to work with python version 3.7.11, or am I missing something? I am not sure how to ensure all these things from the Releases page in the GitHub match up, I just downloaded the latest version and got some example code following a tutorial to work (3d ball one) and thought it would also work if called from inside Spyder.

What exactly should I do? Does the screenshot I send just say to downgrade ml agents to an earlier version? Because I already have the latest. I also have Unity 2020.3.25f1 and going by the changelog [2.1.0-exp.1] for com.unity.ml_agents, which is in fact the recommended version 

```
    "The Unity environment took too long to respond. Make sure that :\n"
mlagents_envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
         The environment does not need user interaction to launch
         The Agents' Behavior Parameters > Behavior Type is set to "Default"
         The environment and the Python interface have compatible versions.

```

**Screenshots**
![version_issue](https://user-images.githubusercontent.com/20794711/149202516-0eb00aad-01a7-4567-bdcb-3364cfd20970.PNG)

![error_spyder](https://user-images.githubusercontent.com/20794711/149202543-40120809-5995-434b-9e90-d2b467fd77c7.PNG)

**Environment (please complete the following information):**
- Unity Version: [e.g. Unity 2020.3.25f1]
- OS + version: [e.g. Windows 10]
- _ML-Agents version_: (e.g. ML-Agents release 18)
- _Torch version_: '1.7.1+cu110'
- _Environment_: "Create your first custom environment" (https://github.com/Unity-Technologies/ml-agents/blob/release_18/docs/Learning-Environment-Create-New.md)

I mainly do not understand what more I am supposed to do after having downloaded the latest version, particularly since when running the vanilla PPO/SAC algorithms from the terminal works alright.

**Comment by Phoenix-surgere** [comment]
Hi,

No, unfortunately, that is not it since I took care in specifying the correct behavior type and then double-checked to ensure I did not mess that easy one up. I actually took a screenshot of the incompatibility issue which I still cannot understand, the one I linked in my post above, though by downgrading the ML-Agents to 0.20 seemed to do the trick, which also seems strange

**Comment by kkalera** [comment]
If you open the package manager in unity, does it also say you have version 2.1.0-exp.1 ? This is the com.unity.ml-agents package that is compatible with v0.27.0 according to [https://github.com/Unity-Technologies/ml-agents/releases](url)

Personally I am using the following versions without any issues using anaconda for a python environment:
Unity package: 2.0.1 (Release version listed in the package manager)
Python package: 0.26.0
Python version: 3.8.12
OS: Windows 11
