### ISSUE TITLE
Using ML agent on other engines

### ISSUE THREAD

**Issue by Ali-khn** [Unity-Technologies/ml-agents#5686]
**Is your feature request related to a problem? Please describe.**
Is it possible to integrate the Unity ML agents with other game engines?( like Godot game engine or Blender game engine?) What if some one has no access to the Unity and still wants to use the Unity ML agents? Is there any possible way? 

**Describe the solution you'd like**
As a suggestion, adding the ability to integrate ML agents with any game engine would be so grate.

**Describe alternatives you've considered**
Adding any documents related to possible solutions.

**Additional context**
Thanks for your time and consideration.

**Comment by maryamhonari** [comment]
Hi @Ali-khn,

Thank you for being an ML-Agents user. Adding support for external engines in not on the ML-Agents Roadmap right now. We are focused on adding support for custom trainers and expanding our imitation learning features. We love to hear about your feedback on how we can make our users lives easier when it comes to the above features I just mentioned and also when it comes to using ML-Agents in Unity.  
If you want to use ML-Agents but does not have access to Unity you can learn about our free Unity Personal license here ([https://unity3d.com/unity/activation/personal)/)](https://unity3d.com/unity/activation/personal)/))
