### ISSUE TITLE
add an option to change timeout before unity responds

### ISSUE THREAD

**Issue by dmitryponv** [Unity-Technologies/ml-agents#5694]
**Is your feature request related to a problem? Please describe.**

mlagents-learn times out when Unity play is not pressed. Sometimes unity play takes 30 seconds to start, and MLAgents-learn times out by then 

**Describe the solution you'd like**
Please add a --timeout or some similar option when starting mlagents-learn

**Comment by CubeMD** [comment]
Great suggestion. This is also useful as while debugging in Unity editor, the trainer might disconnect on pause

**Comment by miguelalonsojr** [comment]
Thanks for reaching out! We've logged this request internally as MLA-2401.

**Comment by AVOlight** [comment]
please also support turning the timeout off :)

**Comment by danielebanovaz** [comment]
I guess there's still no update on this, right?
Such a simple feature would be extremely useful, especially when starting a large batch of standalone builds

**Comment by danielebanovaz** [comment]
I see it has been now "closed as complete".
Does it mean that request MLA-2401 has been fully implemented and it's available in the upcoming release of ML-Agents?

**Comment by miguelalonsojr** [comment]
No. Thanks for reaching out. This was closed en masse to clean up old issues and requests. Re-opening as this should be an easy addition. No ETA on implementation though. But will keep open.

**Comment by danielebanovaz** [comment]
Thank you very much for clarifying!

**Comment by miguelalonsojr** [comment]
The update was easy enough. Here's the PR: https://github.com/Unity-Technologies/ml-agents/pull/5991

**Comment by miguelalonsojr** [comment]
This feature has been implemented.
