### ISSUE TITLE
Ask for documents about how to modify the network/model for research purpose

### ISSUE THREAD

**Issue by chenzhutian** [Unity-Technologies/ml-agents#5696]
**Is your feature request related to a problem? Please describe.**
Not a problem I think, but need some pointers.
I would like to modify the embedding networks to do some experiments. However, there are no documents about where to do it.

**Describe the solution you'd like**
A brefi instructruction about:
1. which files are about the embedding network
2. how to compile and run the modified code, e.g., by using the command `mlagent-learn`

Thanks!

**Comment by miguelalonsojr** [comment]
Hi! Thanks for reaching out. We've logged this request as MLA-2402.

**Comment by chenzhutian** [comment]
Thanks!
