### ISSUE TITLE
Couldn't connect to trainer on port 5004 using API version 1.5.0. Will perform inference instead.

### ISSUE THREAD

**Issue by yachty66** [Unity-Technologies/ml-agents#5697]
**Describe the bug**

when I play 3Dball  example, has error ->
Couldn't connect to trainer on port 5004 using API version 1.5.0. Will perform inference instead.

**To Reproduce**

mlagents-learn config/trainer_config.yaml --run-id=exampleID
click play button

**Console logs / stack traces**

<img width="1326" alt="Screen Shot 2022-02-02 at 10 48 19 AM" src="https://user-images.githubusercontent.com/68147541/152130570-dbfbcb2d-1e75-4091-90c6-ae83b8b32526.png">

**Environment:**

Unity Version: Unity 2021.2.8f1
OS + version: Mac 11.3.1
ML-Agents version: ml-agents-release_18
Environment: Anaconda virtual environment, installed all necessary package
-python version: 3.8.6

**Note:**

This issue appeared similar [here](https://github.com/Unity-Technologies/ml-agents/issues/4015#issuecomment-689518628) and the person was able to solve the issue with the Mac specific configurations for the bundle file. I don't see the alert so I cannot just follow his advice.

**Comment by yachty66** [comment]
I get the same command line output like you but I don't get the GUI with the alert. Did you have seen the error as GUI like in the post to which you reference?

**Comment by miguelalonsojr** [comment]
Hi @yachty66, are you on an M1 mac by any chance?

**Comment by yachty66** [comment]
I build with the following environment and everything worked fine now:

macOS Big Sur 11.3.1
Unity Editor = 2020.3.15f2
Unity-Hub = 3.0.1
Python = 3.8 
ML-Agents Release 19
