### ISSUE TITLE
API Compatibility issue between Unity and Python

### ISSUE THREAD

**Issue by eFuller96** [Unity-Technologies/ml-agents#570]
I've built my own learning environment in unity, an asteroids game, and have set everything up following tutorials. I am now at the point of training the Agent, and run this line in my command prompt:

**python/learn.py Asteroids.exe --run-id=train_1 --train**

I get some errors from  learn.py and trainer_controller.py, but in environment.py line 125, I get the following error:
**The API number is not compatible between Unity and python. Python API : API-3, Unity API : API-1.
Please go to https://github.com/Unity-Technologies/ml-agents to download the latest version of ML-Agents.**

However I downloaded the latest version of ML-Agents a few days ago. How do I go abouts upgrading my Unity API to match the Python API version number?

**Comment by eFuller96** [comment]
note that I get this with any project, I just tried the 3DBall example

**Comment by MarcoMeter** [comment]
Sounds like the Unity Project is out-dated.

The API check is done by the External-Communicator.cs. If you cloned the most recent state of the repository, API-3 should be defined [here](https://github.com/Unity-Technologies/ml-agents/blob/master/unity-environment/Assets/ML-Agents/Scripts/ExternalCommunicator.cs#L39).

Maybe you downloaded one of the older versions months ago and accidentally launched the old Unity project from the old location.

**Comment by eFuller96** [comment]
Ah yep exactly right. I knew you were spot on as soon as I read your comment and realised my mistake. Applied the necessary fixes and works a charm. Thank you !!
