### ISSUE TITLE
The training speed decreased over time( unity executable environment,using Python API)

### ISSUE THREAD

**Issue by hxx1996** [Unity-Technologies/ml-agents#5702]
I implemented training acceleration in unity executable environment(time-scale=20), but I found an obvious problem:the training speed decreased over time 

![image](https://user-images.githubusercontent.com/38696314/152906167-e7358060-9f29-4d08-8bd6-eed7287327b8.png)

The log information is printed only for a fixed number of runs. The data transfer rate is also displayed in parentheses. As the training interval becomes longer, the data transfer rate becomes smaller and smaller  

I would like to know what causes this problem and how to solve it. Before that, I also tried to train directly with ML agents. Without packing the environment, the training speed would still decrease.

BTW, I found the edit>project settings>time> time scale in the unity editor able to acclerate the simulation speed. Can I speed up both the Unity environment Settings and ML Agents at the same time? (Theoretically, should get training accelerometers multiplied?)

**Comment by miguelalonsojr** [comment]
Hi! There's not need to manage the time-scale yourself. The ML-Agents toolkit automatically accelerates the environment during training. You can also set the time scale through the config file: https://github.com/Unity-Technologies/ml-agents/blob/82a1114d83d43fed0b3078ab4cc90943e2804e02/docs/Training-ML-Agents.md.

**Comment by hxx1996** [comment]
Thank you for your replay! But you may not understand what I mean
What I'm trying to say is that I packaged the Unity environment I built and implemented the MADDPG algorithm myself for training. I used [UnityEnvRegistry](https://github.com/Unity-Technologies/ml-agents/blob/d34f3cd6ee078782b22341e4ceb958359069ab60/docs/Unity-Environment-Registry.md) to create an environment and set the time-scale=20:
![image](https://user-images.githubusercontent.com/38696314/153118095-4923e9e9-53cc-41c8-9e64-feb8e3041644.png)
After setting up the environment, I started training with the MADDPG algorithm, but as the training speed slowed down, I didn't change the time-scale at all . The relevant picture is in my original problem description.
I am looking forward to your reply as soon as possible, which is very important to me

**Comment by miguelalonsojr** [comment]
Is this using a custom environment? If so, we are unable to help reproduce bugs. Please attempt to reproduce this issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue. This would help us determine track the issue down and determine if it's within the ML-Agents toolkit. If you are using a custom environment, it may be a bug in your environment that is slowing it down over time.
