### ISSUE TITLE
Actuators and ActionBuffers do not exist.

### ISSUE THREAD

**Issue by theisen1337** [Unity-Technologies/ml-agents#5703]
**Environment**
Unity 2020.3.27
Python 3.7.9
Unity MLAgents 1.0.8

**Describe the bug**
Creating a new Unity project installing MLAgents 1.0.8, and trying import MLAgents.Actuators and does not work.

**To Reproduce**
1. Open Unity 2020.3.27 
2. Install MLAgents 1.0.8 via Unity Package Manager
4. Write up the follow script.

```C#
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Unity.MLAgents;
using Unity.MLAgents.Actuators;

public class MoveToGoalAgent : Agent{
    public override void OnActionReceived(ActionBuffers actions){
        //s
        Debug.Log(actions.DiscreteActions[0]);
    }
}
```

**Console logs / stack traces**
```
Assets\Scenes\mlagent_demo\MoveToGoalAgent.cs(5,22): error CS0234: The type or namespace name 'Actuators' does not exist in the namespace 'Unity.MLAgents' (are you missing an assembly reference?)
Assets\Scenes\mlagent_demo\MoveToGoalAgent.cs(8,43): error CS0246: The type or namespace name 'ActionBuffers' could not be found (are you missing a using directive or an assembly reference?)```
```
**Screenshots**

![image](https://user-images.githubusercontent.com/16194561/153339518-59ad10ef-1a66-4212-9f68-5db678ebae8c.png)

**Comment by hvpeteet** [comment]
Thanks, before digging in deeper can you please check if you have installed the com.unity.ml-agents.extensions extension? 

Pointers:

1. [InputActuatorComponent.md](https://github.com/Unity-Technologies/ml-agents/blob/release_19/com.unity.ml-agents.extensions/Documentation~/InputActuatorComponent.md#getting-started) 
2. Packaging [docs](https://github.com/Unity-Technologies/ml-agents/blob/release_19/com.unity.ml-agents.extensions/Documentation~/com.unity.ml-agents.extensions.md#about-ml-agents-extensions-package-comunityml-agentsextensions)

**Comment by hvpeteet** [comment]
Please note that if you want to get around this for the time being you can upgrade to 2.0.1, I will continue to look into this though since it impacts the verified release.

**Comment by hvpeteet** [comment]
It seems that Actuators were never available in 1.0.8 and are were added in https://github.com/Unity-Technologies/ml-agents/commit/1ccd8796c11394baf6c391f79e0d16720e71f706 which only targets 1.4.0 and higher. If you need to stick to 1.0.8 then please refer to the usage docs for that version at https://github.com/Unity-Technologies/ml-agents/tree/com.unity.ml-agents_1.0.8, otherwise I would highly recommend upgrading to 2.0.1.

**Comment by hvpeteet** [comment]
Whoops, I didn't mean to hit the close button. Please close this if this solved your issue / helped.

**Comment by Baldins** [comment]
I have the same error on version 2.1 - Any way to solve it?
