### ISSUE TITLE
Vector observations and coroutine do not work in unison? (NullReferenceException)

### ISSUE THREAD

**Issue by StellioKontos** [Unity-Technologies/ml-agents#5704]
-

**Comment by hvpeteet** [comment]
We are now using the [Unity forums](https://forum.unity.com/forums/ml-agents.453/) to handle usage-based discussions like this. Please create a new thread there, in order to get the community involved in the discussion, and reply with the link to your forum thread.

**Comment by StellioKontos** [comment]
Thanks for the heads-up :)
