### ISSUE TITLE
Visual observation inputs connected to wrong outputs

### ISSUE THREAD

**Issue by Fallscout** [Unity-Technologies/ml-agents#571]
I needed a visualization of the default neural network that is used by the PPO model, so I tried to plot the computation graph with TensorFlow. In my environment, I use three camera observations per brain. It was then that I noticed that all convolutional layers of the network are connected to the same _visual_observation_2_ node and that the other two nodes are not connected to any outputs.
![visual_observation_inputs](https://user-images.githubusercontent.com/8558936/38265474-513e437c-3776-11e8-8271-871f23a72e19.png)

I'm a beginner in TensorFlow, but I doubt this setup is correct. I had a look at the _create_visual_encoder_ method in the models.py file and found this line:

`conv1 = tf.layers.conv2d(self.visual_in[-1], 16, kernel_size=[8, 8], strides=[4, 4], activation=tf.nn.elu)`

Here it wraps a convolutional layer around the last item in _visual_in_, which seems incorrect to me if there are multiple visual observations. I hope someone can tell me whether this is a real error in the code, or if I missed something else which explains using only the last item of _visual_in_.

**Comment by vincentpierre** [comment]
Could you try again on `hotfix-0.3.0c`? I modified the line of code you mentioned.

**Comment by Fallscout** [comment]
Now it seems to be correct. Thank you for adressing this issue so quickly.

![visual_observation_correct](https://user-images.githubusercontent.com/8558936/38304059-4ff4cd28-3808-11e8-802b-ce5505e6683c.png)

**Comment by NonoLG** [comment]
Hi,

Do you have the full updated graph please ?

Cheers
