### ISSUE TITLE
multiple processes spawned when opening binary project

### ISSUE THREAD

**Issue by vittorione94** [Unity-Technologies/ml-agents#5711]
**Describe the bug**
Not sure if it's a bug but when I launch a training experiment from Python and then I check with htop my processes I see multiple processes listening to the same port.
And I believe after a while this leads to a crush on my aws server instance.

**To Reproduce**
Launch an experiment from python and check the number of processes.

**Screenshots**
<img width="1653" alt="Screenshot 2022-02-28 at 12 48 46" src="https://user-images.githubusercontent.com/11392217/155978527-54b8aade-c8cd-416e-bbe6-9dc770d036f6.png">

<img width="1653" alt="Screenshot 2022-02-28 at 12 49 38" src="https://user-images.githubusercontent.com/11392217/155978639-84ffc8d2-94ba-4df4-abc7-5cd994289264.png">

**Environment (please complete the following information):**
- Unity Version: 2020.3.25f1
- OS + version: Ubuntu 20.4
- _ML-Agents version_: develop
- _Torch version_:  Name: torch
Version: 1.8.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/ubuntu/anaconda3/envs/unityMLAgents/lib/python3.7/site-packages
Requires: numpy, typing-extensions
Required-by: mlagents
- _Environment_: 3DBall

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by jrupert-unity** [comment]
This isn't supposed to happen and does not happen in the general case.  Knowing the parameters you are running with might help.

**Comment by vittorione94** [comment]
After spending some time on this I realised that those are not processes but threads.
