### ISSUE TITLE
Xvfb incompatibility with MLagents?

### ISSUE THREAD

**Issue by sunchipsster1** [Unity-Technologies/ml-agents#5714]
Hello! I have xvfb installed, and I am trying to run the following command:

xvfb-run -a "-screen 0 1400x900x24" python run_gym.py

where run_gym.py is a pretty simple code:
![image](https://user-images.githubusercontent.com/56416888/156531311-bc721280-4a75-48eb-8e9b-d8475fa6bc93.png)

I get the following error:
![image](https://user-images.githubusercontent.com/56416888/156531361-006f9950-505a-4b97-b2cf-16bd0dc86fe8.png)

Does anyone know why this occurs and if this is due to a bug or incompatibility between xvfb and ML-agents -- or an error on my part? 
Thank you!

**Comment by jrupert-unity** [comment]
There are a couple of things you can try.

1.  Use the server-args parameter explicitly
e.g.  xvfb-run -a --server-args="-screen 0 1400x900x24" <call trainer with your env here>
2.  Specify Server Build in your build settings.

Let me know if either of these work for you.

**Comment by sunchipsster1** [comment]
Hi @jrupert-unity thank you so much for your kind advice :) 

If I interpreted your suggestions correctly: 
for 1. are you suggesting I run  **xvfb-run -a --server-args="-screen 0 1400x900x24" python run_gym.py on my Terminal** ? ... Where run_gym is the simple trainer that I displayed above (basically just calling on the env for now).  If this is what you meant, then yes, I have now tried this based on your suggestion, and unfortunately it does not succeed. It gives the same error output as displayed above. 

for 2. I tried this but this did not work as I require the use of graphics. The Server Build ends up ouputting OBS = grey screens, rather than scenes. this is why when I was building the exe file in Unity, I did not click Server Build.

I am a bit puzzled why running xvfb-run ... etc does not seem to work for me. Perhaps ... am I missing a command that I need to do? 

Alternatively, I tried out this colab: https://github.com/Unity-Technologies/ml-agents/blob/main/colab/Colab_UnityEnvironment_1_Run.ipynb

Unfortunately, this solution is not viable for me as it is a jupyter notebook, whereas my university's server can only seem to run python from a  terminal. Is there a simple way to **translate** the section for installing and running  " _ rendering dependencies_ " section in that google collab, into something that can be run by python and terminal? 

Thank you very much for your kind help in helping solve this situation, I really appreciate it :)

**Comment by kenminglee** [comment]
Hey @sunchipsster1, maybe give this script a try:
```sh
#!/bin/bash

port=0
while true; do
  export DISPLAY=:$((++port))
  Xvfb $DISPLAY -noreset &
  sleep 5
  jobs %% && break
done

python run_gym.py
```
The while loop looks for an unused display port so you don't have to hardcode it. Let me know if it works :)
