### ISSUE TITLE
Unity Package of Release 19 isn't in Package Manager

### ISSUE THREAD

**Issue by mrkgmr** [Unity-Technologies/ml-agents#5715]
**Describe the bug**
Unity Package of Release 19 isn't in Package Manager and link from documentation isn't work neither.

**To Reproduce**
1. Go to 'Window->Package Manager'
2. Click on 'MLAgents'
3. Version 2.2.1 doens't appear

**Screenshots**
![image](https://user-images.githubusercontent.com/17512467/156544942-63e6f3f5-9891-48c0-8c36-311ee6c729b2.png)
![image](https://user-images.githubusercontent.com/17512467/156544752-0d82e52f-503d-4fba-88ff-1ebbb849ff1b.png)

**Environment (please complete the following information):**
- Unity Version: Unity 2020.3.18f1
- OS + version: Windows 10
- _ML-Agents version_: ML-Agents release 19

**Comment by Nils-Michelberger** [comment]
Hey,
I have the same issue.
I think I found a workaround though. In the Package Manager you can press the '+' icon at the top left and click "Add package from git URL..." and then paste the following link: "git+https://github.com/Unity-Technologies/ml-agents.git?path=com.unity.ml-agents#release_19". Then it will install "Version 2.2.1-exp.1" and this is the version that they tell us to install here: https://github.com/Unity-Technologies/ml-agents/releases

But I got over a thousand warnings about signed/unsigned mismatch. But hopefully will work anyways... (haven't tested it yet)
Picture of warnings:
![image](https://user-images.githubusercontent.com/60349722/157041681-a11dc440-4d08-41dc-843e-ebb70028c1c1.png)

Can someone from the team tell me why there are so many warnings and if I can ignore this?

Thanks.

**Comment by maryamhonari** [comment]
Hi,
