### ISSUE TITLE
Multiple GPU support

### ISSUE THREAD

**Issue by Simple2Sample** [Unity-Technologies/ml-agents#5720]
Hello. I got a PC with several GPUs. At the moment I'm only using one for training, but is it still possible to use multiple GPUs? I have noticed there was support for it a while ago, but the multi-gpu feature seems to have been removed. Will the feature return? If not, then why?

**Comment by miguelalonsojr** [comment]
Hi! Thanks for reaching out. We do have plans to improve training performance on our roadmap for end of 2022/beginning of 2023. This would include adding support for, among many things, multi-GPU training. Thanks again!
