### ISSUE TITLE
libgrpc_csharp_ext.x64.bundle is not verifiable in MacOSX BigSur

### ISSUE THREAD

**Issue by rerngvit** [Unity-Technologies/ml-agents#5730]
**Describe the bug**
In MacOSX BigSur, it seems that libgrpc_csharp_ext.x64.bundle is not verifiable (tested on latest [release 19](https://github.com/Unity-Technologies/ml-agents/releases/tag/release_19) as well as [release 18](https://github.com/Unity-Technologies/ml-agents/releases/tag/release_18)). This would trigger an error box as shown in the attached screenshot below. The main problem for this is that it would prevent **any remote training** by other libraries, e.g., ray[rllib], to work. (This missing Apple certification seems to be a similar issue in Catalina with [#2306](https://github.com/Unity-Technologies/ml-agents/issues/2306).)

**To Reproduce**
1. Download the release, e.g., [release 19](https://github.com/Unity-Technologies/ml-agents/releases/tag/release_19), to a local machine
5. Open Unity Hub and click arrow next to "Open", followed by "Open remote project", and select the the project from the previous step
6. We will get the Unity editor open. Open the 3DBall scene by Assets -> ML-Agents -> Examples -> 3DBall -> Scenes -> 3DBall
7. Click "Play" button on the top of the screen
8. The security error dialog will be showed about "libgrpc_csharp_ext.x64.bundle"

**Screenshots**
![image](https://user-images.githubusercontent.com/815664/163677904-d26f7f3c-23de-4960-8811-d5ea593254ed.png)

**Environment (please complete the following information):**
- Unity Version: [Unity Editor version 2019.4.38f1, Unity Hub version 3.1.1]
- MacOSX Big Sur version 11.6.2 
- Hardware: Core i7
- ML-Agents version release 19 (or release 18)

**Comment by maryamhonari** [comment]
Hi, thanks for bringing this issue to our attention, I logged it under MLA-2517.
