### ISSUE TITLE
Action not reflected in rendering in UnityToGymWrapper with custom environment

### ISSUE THREAD

**Issue by mayukhghosh** [Unity-Technologies/ml-agents#5731]
I am trying to wrap a unity environment with the Gym wrapper. The environment consists of a quadcopter whose input is the four forces to its propellors. It seems that the actions given to the drone are not being reflected in the actual simulation. The drone keeps falling down even if maximum force is applied to all its propellers. I have checked it in Unity with manual input and it works there. The observations are 84*84 grayscale image stacked 4 times. I am using the following code:

```
unity_env = UnityEnvironment('Scenes_exec_single/', worker_id=0, seed=1)
env = UnityToGymWrapper(unity_env, uint8_visual=True)
env = Monitor(env, 'gym_results/')
env = DummyVecEnv([lambda: env])

obs = env.reset()
for i in range(1000):
    #action, _states = model.predict(obs)
    action = [[1, 1, 1, 1]]
    obs, rewards, dones, info = env.step(action)
```

I have provided a link to the unity executable. 
https://drive.google.com/drive/folders/1tvQc-QX1v-WSL5ObkzLP2IhKPABAQlPa?usp=sharing

- Unity Version:2020.3.32f1
- OS + version: Windows 10
- _ML-Agents version_: v0.28.0
- _Torch version_: 0.12
- _Environment_: Custom Environment

**Comment by maryamhonari** [comment]
Hi @mayukhghosh, 

We are now using the [Unity forums](https://forum.unity.com/forums/ml-agents.453/) to handle issues like this with custom environments. Please create a new thread there, in order to get the community involved in the discussion, and reply with the link to your forum thread.

**Comment by maryamhonari** [comment]
Hi @mayukhghosh, 

We are now using the [Unity forums](https://forum.unity.com/forums/ml-agents.453/) to handle issues like this with custom environments. Please create a new thread there, in order to get the community involved in the discussion, and reply with the link to your forum thread.

**Comment by maryamhonari** [comment]
Hi @mayukhghosh, 

We are now using the [Unity forums](https://forum.unity.com/forums/ml-agents.453/) to handle issues like this with custom environments. Please create a new thread there, in order to get the community involved in the discussion, and reply with the link to your forum thread.

**Comment by maryamhonari** [comment]
Hi @mayukhghosh, 

We are now using the [Unity forums](https://forum.unity.com/forums/ml-agents.453/) to handle issues like this with custom environments. Please create a new thread there, in order to get the community involved in the discussion, and reply with the link to your forum thread.

**Comment by maryamhonari** [comment]
Hi @mayukhghosh, 

We are now using the [Unity forums](https://forum.unity.com/forums/ml-agents.453/) to handle issues like this with custom environments. Please create a new thread there, in order to get the community involved in the discussion, and reply with the link to your forum thread.

**Comment by maryamhonari** [comment]
Hi @mayukhghosh, 

We are now using the [Unity forums](https://forum.unity.com/forums/ml-agents.453/) to handle issues like this with custom environments. Please create a new thread there, in order to get the community involved in the discussion, and reply with the link to your forum thread.

**Comment by maryamhonari** [comment]
Hi @mayukhghosh, 

We are now using the [Unity forums](https://forum.unity.com/forums/ml-agents.453/) to handle issues like this with custom environments. Please create a new thread there, in order to get the community involved in the discussion, and reply with the link to your forum thread.
