### ISSUE TITLE
Weights and Biases instead of Tensorboard (PR request)

### ISSUE THREAD

**Issue by alexge233** [Unity-Technologies/ml-agents#5733]
**Is your feature request related to a problem? Please describe.**
I'm working as part of a team that runs multiple `ml-agents` on our own PCs and also plan on placing them on VPS. We want to collate and compare results using `wandb` instead of `tensorboard` as this will allow us to work better as a team.

**Describe the solution you'd like**
I've implemented a `WandbWriter` in my local git clone under `ml-agents/mlagents/trainers/stats.py`. I've added a simple unit test in `ml-agents/mlagents/trainers/tests/test_stats.py`, and injected the writer in `ml-agents/mlagents/plugins/stats_writer.py` so it becomes available. I haven't actually tested it with the samples/examples, only locally.

**Describe alternatives you've considered**
I can imagine the alternative to be to package my version of `mlagents` and distribute it to my colleagues, but that's less than ideal. It also means I'll have to copy, merge and maintain an updated copy. I'd rather not do that.

**Additional context**
This repo seems to have reached its maximum forks, and therefore I could not Fork + PR. Hence opening this issue. Happy to have the changes reviews, rejected, commented on, etc. but I can't seem to do that as things stand.
Also, I may need some guidance on how exactly you expect the format for the kwargs being passed to the writer to look like.

**Comment by andrewcoh** [comment]
Hi @alexge233 

This does sound interesting and we would like to see the PR. I am not totally sure what you mean by

> This repo seems to have reached its maximum forks

Is it possible that is on your end i.e. your person github has reached maximum forks?

**Comment by alexge233** [comment]
Ha! This is interesting; when I tried to fork it through github it gave me an error of `max forks allowed for this repository`! Ok, this is just preliminary, I've had a look at the code and made some changes. [PR has been submitted](https://github.com/Unity-Technologies/ml-agents/pull/5741) let me know anything you don't like, including suggestions, coding style, documentation, etc.

**Comment by andrewcoh** [comment]
Thanks, I'll check it out soon.
