### ISSUE TITLE
goal signal and HyperNetwork

### ISSUE THREAD

**Issue by fdsafet** [Unity-Technologies/ml-agents#5736]
I had just read about "ML-Agents v2.0 release:Now supports training complex cooperative behaviors". I am  very interested in the part of One model to rule them all .Could you provide the example of this part of the case(an agent solving two tasks present in the ML-Agents examples(WallJump and PushBlock)?  Thank you !

<img width="620" alt="微信截图_20220425110304" src="https://user-images.githubusercontent.com/104335519/165013874-f8efe07f-68e4-4800-9df7-f032cc233f83.png">

**Comment by andrewcoh** [comment]
Hi @fdsafet 

That environment exists on a branch [here](https://github.com/Unity-Technologies/ml-agents/tree/walljump-pushblock/Project/Assets/ML-Agents/Examples/WallJumpAndPushblock) but it may be messy because we never ended up merging it into main.

Good luck!

**Comment by fdsafet** [comment]
> Hi @fdsafet
> 
> That environment exists on a branch [here](https://github.com/Unity-Technologies/ml-agents/tree/walljump-pushblock/Project/Assets/ML-Agents/Examples/WallJumpAndPushblock) but it may be messy because we never ended up merging it into main.
> 
> Good luck!

thank you!
