### ISSUE TITLE
Python package fails to install from pypi 

### ISSUE THREAD

**Issue by walchko** [Unity-Technologies/ml-agents#5739]
**Describe the bug**

Fails to install from pypi on python3.9.10, macOSX 12.2.1, intel. I am trying to use this package form pypi: https://pypi.org/project/unityagents

```
pip install unityagents
Requirement already satisfied: unityagents in ./dp/lib/python3.9/site-packages/unityagents-0.4.0-py3.9.egg (0.4.0)
Collecting unityagents
  Using cached unityagents-0.3.0.tar.gz (29 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/8m/htkq_jv500b_1yqyk33q6tzc0000gn/T/pip-install-b51ucz3c/unityagents_a60d8efc814740a09ba48496d52676d2/setup.py", line 6, in <module>
          with open('requirements.txt') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**To Reproduce**

pip install unityagents

**Comment by AKemendo** [comment]
Thank you @walchko I was also able to reproduce this on a different platform so we will look into this asap. 

I logged this internally as https://jira.unity3d.com/browse/MLA-2539. 

Please have a look at our contribution guidelines if you choose to hunt the bug down further: https://github.com/Unity-Technologies/ml-agents/blob/main/com.unity.ml-agents/CONTRIBUTING.md

**Comment by RedTachyon** [comment]
Isn't `unityagents` a very old version that hasn't been updated since 2018? You probably want to install `pip install mlagents` unless I'm missing something

**Comment by AKemendo** [comment]
@RedTachyon Yes it is and that is the correct solution here. I confirmed internally that unityagents is fully deprecated

@walchko try:

`pip install mlagents`

and let us know if you have any issues.
