### ISSUE TITLE
Mistake in 'Agent Observation' Documentation

### ISSUE THREAD

**Issue by leo2r** [Unity-Technologies/ml-agents#5745]
At the end of the Visual Observation section, specifically "Visual Observation Summary & Best Practices", you have the following sentence:

"Visual observations should generally be used unless vector observations are not sufficient."

I think you mean:

"Visual observations should generally *not* be used unless vector observations are not sufficient."

or

"Visual observations should generally *only* be used *when* vector observations are not sufficient."

**Comment by jrupert-unity** [comment]
Thank you, I think you are right.  I'll look into it and make any necessary corrections.

**Comment by jrupert-unity** [comment]
Change will be made soon.
