### ISSUE TITLE
demo_loader.py", line 210, DecodeError: Error parsing message with type 'communicator_objects.BrainParametersProto'

### ISSUE THREAD

**Issue by AVOlight** [Unity-Technologies/ml-agents#5750]
anyone ideas to workaround this:

demo_loader.py", line 210, in load_demonstration
    brain_param_proto.ParseFromString(data[pos : pos + next_pos])
google.protobuf.message.DecodeError: Error parsing message with type 'communicator_objects.BrainParametersProto'

my demo file is over 22GB...

**Environment (please complete the following information):**
- Unity Version: 2020.3.33f1
- OS + version: Windows 10
- _ML-Agents version_: 2.2.1-exp.1 - March 11, 2022
- _Torch version_: 1.7.1+cu110
- _Environment_: custom; just checking if there is an easy fix for now

**Comment by andrewcoh** [comment]
Hi @AVOlight 

Did you record your demo file with our [DemonstrationRecorder?](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Learning-Environment-Design-Agents.md#recording-demonstrations) ?

**Comment by AVOlight** [comment]
Hi @andrewcoh, yes; the built-in component;
found it works with smaller demo file sizes; but unfortunately they take longer to load then there worth.
