### ISSUE TITLE
Assets\ML-Agents\Examples\PushBlockWithInput\Scripts\PushBlockActions.The type or namespace name 'InputAction' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by danyow-cheung** [Unity-Technologies/ml-agents#5752]
**Describe the bug**
the new to unity ml agent,when i drag the release code into unity patform , and try to run the basic "3D ball" ,error happend

**Console logs / stack traces**

Assets\ML-Agents\Examples\PushBlockWithInput\Scripts\PushBlockActions.cs(15,19): error CS0234: The type or namespace name 'InputSystem' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)

Assets\ML-Agents\Examples\PushBlockWithInput\Scripts\PushBlockActions.cs(274,16): error CS0246: The type or namespace name 'InputAction' could not be found (are you missing a using directive or an assembly reference?)

**Screenshots**
![error](https://user-images.githubusercontent.com/76671016/170865655-c69bafb7-6d31-4b32-a2d1-d9306d19f0f6.jpg)

**Environment (please complete the following information):**
- Unity Version: Unity 2021.2.19
- OS + version: Windows 10
- _ML-Agents version_ :ml-agents-release_19
- _Environment_:python3.7

**Comment by simpleDev-core** [comment]
Have you figured out how to fix this yet? Having trouble with this.

**Comment by ramkumarkoppu** [comment]
Same issue with versions: Unity Hub 3.1.2, Unity 2021.2.4fq, ML Agents package 2.0.1, ml-agents-release_19
Assets\ML-Agents\Examples\PushBlockWithInput\Scripts\PushBlockActions.cs(274,16): error CS0246: The type or namespace name 'InputAction' could not be found (are you missing a using directive or an assembly reference?)
followed advice on above comment, but not resolved yet.

**Comment by jrupert-unity** [comment]
Hi!  I'd like to help resolve this issue, but I haven't been able to reproduce the problem.  Can those who are encountering the error confirm that they've followed these steps or tell me what they've done differently?

1) Download and unzip (or clone) ml-agents-release_19
2) Using in the Unity Hub, use Unity 2021.2.X to Add the ML-Agents Example projects (ml-agents-release_19/Project folder)
3) Open the 3DBall scene from Assets/ML-Agents/Examples/3DBall/Scenes/

**Comment by jrupert-unity** [comment]
Two possible fixes to try in the meantime:
- Remove the version of ML-Agents you have from the package manager and the use Install From Disk and install both the com.unity.ml-agents and com.unity.ml-agents.extensions packages.
- remove the PushBlockWithInput folder and PushBlockWithInput.meta file from \ml-agents-release_19\Project\Assets\ML-Agents\Examples

**Comment by danyow-cheung** [comment]
> *
thank for replying , i will look on it these day

**Comment by danyow-cheung** [comment]
> Two possible fixes to try in the meantime:
> 
> * Remove the version of ML-Agents you have from the package manager and the use Install From Disk and install both the com.unity.ml-agents and com.unity.ml-agents.extensions packages.
> * remove the PushBlockWithInput folder and PushBlockWithInput.meta file from \ml-agents-release_19\Project\Assets\ML-Agents\Examples

thank for replying , i will look on it these day

**Comment by danyow-cheung** [comment]
> Two possible fixes to try in the meantime:
> 
> * Remove the version of ML-Agents you have from the Package Manager and the use Install From Disk and install both the com.unity.ml-agents and com.unity.ml-agents.extensions packages that are in ml-agents-release_19.
> * Remove the PushBlockWithInput folder and PushBlockWithInput.meta file from \ml-agents-release_19\Project\Assets\ML-Agents\Examples

The method 2 work for me!After i deleting  files in  \ml-agents-release_19\Project\Assets\ML-Agents\Examples .
It print 
![error2](https://user-images.githubusercontent.com/76671016/174464629-676abbdc-8a83-4f7f-af0e-660e9821a960.jpg)

so i search google and find out how to fix this error:

 https://github.com/jilleJr/Newtonsoft.Json-for-Unity

the last ,3d box works!
![work!](https://user-images.githubusercontent.com/76671016/174464657-351f979a-b1c3-4dce-ab54-b44071001388.jpg)
