### ISSUE TITLE
Training Area Replicator, does not replicate Environments during Training

### ISSUE THREAD

**Issue by JulesVerny** [Unity-Technologies/ml-agents#5757]
ML Agents 1.9
Training Area Replicator, to avoid having to explicitly create multiple Training Area(With its Child Agents and Enemies etc) as multiple Training Area Game Objects in my Scene.

When I use Training Area Replicator, and set the number of Area (Num Areas) and simply Press Play directly in the Editor, the Multiple scenes are created, and are played through.

However when I execute Play following with a python mlagents-learn Training session prompt, the scene only creates and plays a single Training Area instance. I note that the Num Areas filed is set to Zero in the inspector, whilst the Training session is in play.

So the ML Agents Training Area Replicator does not seem to work with the python mlagents-learn sessions ?

**Comment by miguelalonsojr** [comment]
Hi @JulesVerny , if you'd like to use the training area replicator in python, you'll have to add the following, for example, to your trainer config file to replicate 8 training areas:

`env_settings:
     num_areas: 8
`
