### ISSUE TITLE
EndEpisode() dows not work and "No episode was completed since last summary" on terminal.

### ISSUE THREAD

**Issue by Baldins** [Unity-Technologies/ml-agents#5761]
Hi, 
 
When lunching the training I keep getting "No episode was completed since last summary" but I do also see that EndEpisode() is not ending the episode when my agent collides with other agents or reach the target. 

Any help to fix it ? 

Thank you! 

Francesca

**Comment by myszwa** [comment]
You must add it in if condition for example
`if(distanceFromTarget > distanceRequired {
AddReward(1.0f);
EndEpisode();
}`

**Comment by Qiming0303** [comment]
Hey, I have the same problem here,

        if (currentFrame[0] <= 0)
        {        
            CurrentState = StateIndicators.Win;
            float reward = 10.0f * initalWhite / (materialUsage + 1);
            SetReward(reward);
            Debug.Log(reward);
            Debug.Log("***************** Win *****************");
            EndEpisode();
            Debug.Log("test");

        }

this if condition is directly under OnEpisodeReceive(), and it is the only "*********win*********" signal in my code, but I keep getting test printed after having *********win*********. Dose any one have solution for this?

Huge thanks
Qim

**Comment by BonecoSinforoso** [comment]
I have the same problem.

My code:

```c#
public override void OnActionReceived(ActionBuffers _actionBuffers)
{
    Vector3 _controlSignal = Vector3.zero;
    _controlSignal.x = _actionBuffers.ContinuousActions[0];
    _controlSignal.z = _actionBuffers.ContinuousActions[1];
    rb.AddForce(_controlSignal * forceMultiplier);

    // Rewards
    float _distToTarget = Vector3.Distance(transform.localPosition, t_target.localPosition);

    // Reached target
    if (_distToTarget < 1.5f)
    {
        Debug.Log(_distToTarget);
        AddReward(1.0f);
        EndEpisode();
    }
    else if (transform.localPosition.y < 0) // Fell off platform
    {
        EndEpisode();
    }
}
``` 

Print:

![Image](https://github.com/user-attachments/assets/43f944ac-da2c-45ec-bf95-9a968a8dede5)

The episode only ends if I fall off the platform.

**Comment by BonecoSinforoso** [comment]
> I have the same problem.
> 
> My code:
> 
> public override void OnActionReceived(ActionBuffers _actionBuffers)
> {
>     Vector3 _controlSignal = Vector3.zero;
>     _controlSignal.x = _actionBuffers.ContinuousActions[0];
>     _controlSignal.z = _actionBuffers.ContinuousActions[1];
>     rb.AddForce(_controlSignal * forceMultiplier);
> 
>     // Rewards
>     float _distToTarget = Vector3.Distance(transform.localPosition, t_target.localPosition);
> 
>     // Reached target
>     if (_distToTarget < 1.5f)
>     {
>         Debug.Log(_distToTarget);
>         AddReward(1.0f);
>         EndEpisode();
>     }
>     else if (transform.localPosition.y < 0) // Fell off platform
>     {
>         EndEpisode();
>     }
> }
> Print:
> 
> ![Image](https://github.com/user-attachments/assets/43f944ac-da2c-45ec-bf95-9a968a8dede5)
> 
> The episode only ends if I fall off the platform.

Solved!
