### ISSUE TITLE
Support Headless Rendering

### ISSUE THREAD

**Issue by duongnb09** [Unity-Technologies/ml-agents#5763]
Hi,

I have seen multiple topics asking about the headless rendering capability with Unity. Here are a few of them: [https://github.com/Unity-Technologies/ml-agents/issues/2185](https://github.com/Unity-Technologies/ml-agents/issues/2185), [https://github.com/Unity-Technologies/ml-agents/issues/3261](https://github.com/Unity-Technologies/ml-agents/issues/3261), [https://github.com/Unity-Technologies/ml-agents/issues/1050](https://github.com/Unity-Technologies/ml-agents/issues/1050). Some folks mentioned in those threads that Unity has been working on it since 2019. Do we know if the feature is ready to use now in 2022? I know Unity Simulation Pro supports headless rendering with multiple GPUs which seems like the Unity team has already figured out how to make it work.

**Comment by leo2r** [comment]
+1 !! I desperately need to figure how to do this for my project 😇🙏🏽

**Comment by RedTachyon** [comment]
You can do headless rendering with pyvirtualdisplay, integrating it in MLA would be nice, but it's not too hard to make it work yourself

**Comment by duongnb09** [comment]
@RedTachyon Thanks for the info! But pyvirtualdisplay doesn't support GPU/Hardware Acceleration which means it will be very slow and the rendering quality sometime wouldn't be good enough.
