### ISSUE TITLE
GAIL+PPO+BC Suddenly Perform Worse

### ISSUE THREAD

**Issue by AbhijitBaruah** [Unity-Technologies/ml-agents#5765]
I am currently training my agent to do two things :- 1) Collect And Deposit Food 2) Take shelter on occurrence of certain things in the environment. I am using gail and Behavioral Cloning with PPO to speed up training. I observed that no matter what reward function I use, during the initial parts of training the Agent learns exactly what to do and does it pretty successfully, but all of a sudden the agent's "stop" doing those actions and diverge on to meaningless states / they get stuck in a local maxima and cannot maximize the reward function. I am super confused as to why this may be happening. Any help would be greatly appreciated.

My training parameters :- 
![image](https://user-images.githubusercontent.com/74203835/179152005-17a8c6b0-1dbb-4a34-a4fd-faa2fcb53db0.png)

**Comment by miguelalonsojr** [comment]
We are unable to help reproduce bugs with custom environments. Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by arlenTuring** [comment]
@AbhijitBaruah
I have same issue in my custom environment, do you have any suggestion if you have experience to made it better?

**Comment by Arlen0615** [comment]
@AbhijitBaruah
I have same issue in my custom environment, do you have any suggestion if you have experience to made it better?
