### ISSUE TITLE
Gym Wrapper produces Tuple instead of Dict for multiple observations (does not work with SB3)

### ISSUE THREAD

**Issue by leo2r** [Unity-Technologies/ml-agents#5766]
**Describe the bug**
I've used Unity and ml-agents to create a custom environment. I then built the exe file (binary file) to use the UnityToGymWrapper to create a Gym instance of the environment. I'm now trying to use stable-baselines3 to train my agent using 'MultiInputPolicy', since the observations are (image1, image2, image3, vector(ie 'direct' features)). However, I get the following error:

raise NotImplementedError(f"{observation_space} observation space is not supported")

When comparing the returned observation from my UnityToGymWrapper env and an example env, I spot this difference:

**UnityToGymWrapper env obs:**

Tuple(Box([[[0]
  [0]
  [0]
  ...
  [255]
  [255]
  [255]]], (84, 84, 1), uint8), Box([[[0]
  [0]
  [0]
  ...
  [255]
  [255]
  [255]]], (84, 84, 1), uint8), Box([[[0]
  [0]
  [0]
  ...
  [255]
  [255]
  [255]]], (84, 84, 1), uint8), Box([-inf ... -inf], [inf ... inf], (13,), float32))

**SB3 env obs:**

{'vec': array([0.72354802, 0.18255346, 0.62559858, 0.69045166, 0.03119092]), 'img': array([[[  6],
        [222],
        [204],
        ...,
        [237],
        [182],
        [209]]], dtype=uint8)}

So it seems like the UnityToGymWrapper env is returning a Tuple as multi observations whereas SB3 (and therefore Gym) want/need a dictionary. Is this the desired way to present multi observations? Seems like the Gym wrapper should create obs in the Gym format? How can I create a work around for this? Thank you :)

**To Reproduce**
1. env_exe = <Name_of_binary_file>
2. unity_env = UnityEnvironment(env_exe)
3. env = UnityToGymWrapper(unity_env, uint8_visual=True, allow_multiple_obs=True)3. 
4. from stable_baselines3 import PPO
5. model = PPO('MultiInputPolicy', gym_env)6. 
6. Error happens

**Environment (please complete the following information):**
- Unity Version: Unity 2021.3.5.f1
- OS + version: Ubuntu 20.04.4 LTS
- _ML-Agents version_: v0.27.0
- _Torch version_: 1.8.1
- _Environment_: Custom

**Comment by miguelalonsojr** [comment]
> Is that true that all people work for this project in Unity were fired?

No. There have been changes at Unity that have slowed our development substantially, but we're still alive! :) Thanks for reaching out. I'll have a look at this.

**Comment by aha85b** [comment]
I am having this issue, any one got it fixed?

**Comment by zbwby819** [comment]
Same issue, any updates?
