### ISSUE TITLE
Is buffer sensor observation parameters given wrongly?

### ISSUE THREAD

**Issue by x-mug** [Unity-Technologies/ml-agents#5783]
**Describe the bug**
the buffer sensor's observation spec is newed in this way:
` m_ObservationSpec = ObservationSpec.VariableLength(m_MaxNumObs, m_ObsSize);`
but the function is this
`public static ObservationSpec VariableLength(int obsSize, int maxNumObs)`
Does this mean the obsSize and maxNumObs are given reversedly

**Environment (please complete the following information):**
- Unity Version: Unity 2021.3.5f
- OS + version: Windows 10
- _ML-Agents version_: MLAgents 2.2.1exp
- _Torch version_: 1.7.1
- _Environment_: Nothing special

**Comment by jrupert-unity** [comment]
I think the parameters to the VariableLength function are misnamed but the functionality is correct (i.e. just swapping the parameters in the function declaration and where they are used in the function is the correct fix).  I will confirm this.  Thank you for pointing out the problem.
