### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by RedTachyon** [Unity-Technologies/ml-agents#5785]
I acknowledge that this is technically not the right place for this type of questions, but everywhere else seems (also) ignored.

What is the status of ML-Agents? Is the project completely dead? Are there plans for continued maintenance? Would the team be open to hand it off to the community to continue its maintenance?

ML-Agents is a tremendously useful project, especially as RL continues to progress into more and more complex environments, so it would be a shame if it just disappears like this.

**Comment by dps999** [comment]
"There was layoffs are reportedly focused in the AI and Engineering divisions" in 28 jun.  Approximately from that date no any tickets assigned. Hope I'm wrong

**Comment by johndevor** [comment]
+1

**Comment by miguelalonsojr** [comment]
ML-Agents has not been abandoned. We have had some changes at Unity that have slowed our development, but I'm happy to report that we're planning another release with a bunch of new features in Q4 of this year, sometime in October/November. Stay tuned!

**Comment by AleksanderWit** [comment]
I am definitely looking forward to this! I am really glad it has not stagnated for good!
