### ISSUE TITLE
Training environment freezes at buffer_size steps

### ISSUE THREAD

**Issue by MidnightGD** [Unity-Technologies/ml-agents#5786]
**Description**
Whenever the buffer_size is reached during the training the editor (or standalone build) with the training environment freezes for a few minutes. After this freeze the training resumes again until the buffer size is reached again. This repeats until training is stopped.

**To Reproduce**
1. In the dodgeball example project open the Capture The Flag Training scene.
2. Start training with mlagents-learn DodgeBall.yaml --run-id=test
3. Press play in the editor

**Environment:**
- Unity Version: 2021.3.8f1
- OS + version: macOS 12.6
- _ML-Agents version_: ml-agents 0.28.0; env 0.28.0; Communicator 1.5.0; "com.unity.ml-agents": "2.1.0-exp.1"
- _Torch version_: 1.8.1
- _Environment_: ml-agents.dodgeball-env-develop

**Comment by miguelalonsojr** [comment]
This is normal behavior. The "freezing" is due to the policy being update. Does training converge? Are you seeing any exceptions in the console window in the editor? If not, then this is normal.

**Comment by MidnightGD** [comment]
> This is normal behavior. The "freezing" is due to the policy being update. Does training converge? Are you seeing any exceptions in the console window in the editor? If not, then this is normal.

Thanks for the clarification. This freezing was new to me. Back when ML-Agents was using Tensorflow this didn't happen if I remember correctly.
