### ISSUE TITLE
Remove multinomial sample from ONNX model output

### ISSUE THREAD

**Issue by Houtamelo** [Unity-Technologies/ml-agents#5788]
On the model api version 1 the outputs where the log probabilities of each action and the ml-agents unity package would use a multinomial sample in order to provide the actions requested by the agent. If a user wanted to access the probabilities directly instead of using a multinomial they could with moderate difficulty do so by editing how the ActionBuffers are constructed.

Since model api version 2 the multinomial sample is embedded directly into the ONNX model. If a user wants to access those probabilities they would have to:
-  Edit the output of the ONNX model (by removing the multinomial sample at the end) using a tool like https://github.com/ZhangGe6/onnx-modifier or editing how it is generated in the python package itself.
- With a lot more difficulty, edit (and bugfix) the source code in order to make the LegacyDiscreteActionOutputApplier work with the edited ONNX model(which was made for the api version 1), this requires much deeper knowledge of how barracuda works and how the outputs in the tensors are layered.

### In which scenarios accessing the probabilities can be useful?
- Evaluate how good the model is, by accessing the probabilities the user can place the agent in pre-defined scenarios and check if the model is predicting the correct action, this is specially useful for discrete actions.
- Manually editing the probabilities after they have been generated, this gives more control on how we use the models at runtime.

**Comment by mpeschina** [comment]
Hi, I need this to implement difficulty scaling on an agent and would like to manually modify how the action gets sampled from the output of the neural network. I could not find how to access the action probabilities directly. 

As the issue is closed: Has this been implemented in the recent version of ML-Agents?
