### ISSUE TITLE
the unity3d.ai has an expired certificate

### ISSUE THREAD

**Issue by jussikuosa** [Unity-Technologies/ml-agents#5791]
**Describe the bug**
the repo has a link to [unity3d.ai](https://unity3d.ai/) for which the ssl cert has expired

**To Reproduce**
browse to [unity3d.ai](https://unity3d.ai/)

**Console logs / stack traces**
-
**Screenshots**
-
**Environment (please complete the following information):**
- OS + version: MacOS 12.4 Monterey

**Comment by unity-gummi** [comment]
Also the web content there is just a redirect to https://unity.com/products/machine-learning-agents so one option is to just link there directly, but we still need to look into the certificate issue since visitors to unity3d.ai can come from many sources
