### ISSUE TITLE
multi-agent get_steps() is not registering non-ended agents after a single agent has ended an episode

### ISSUE THREAD

**Issue by philippds** [Unity-Technologies/ml-agents#5792]
**Describe the bug**
I'm using `UnityEnvironment` class with a custom environment with multiple agents, i.e. [Rolling Ball](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Learning-Environment-Create-New.md) with 2 areas. If one of the two agents has fallen off the plane and the episode has ended, unfortunately the other, that is not terminated does not show up as part of the `decision_step` returned by `get_steps()`.

### Example steps
Let's say we print out the length of the decision step and the terminal step after each environment step, with 2 agents in the environment. This is what I get:
Step 1:
```
decision_step, terminal_step = self.env.get_steps(self.name)
print(decision_step.obs[0].shape[0]) Output: 2
print(terminal_step.obs[0].shape[0]) Output: 0
```
Step 2:
```
decision_step, terminal_step = self.env.get_steps(self.name)
print(decision_step.obs[0].shape[0]) Output: 2
print(terminal_step.obs[0].shape[0]) Output: 0
```
Step 3:
```
decision_step, terminal_step = self.env.get_steps(self.name)
print(decision_step.obs[0].shape[0]) Output: 0
print(terminal_step.obs[0].shape[0]) Output: 1
```

I'm assuming one agent has ended, but the other is not registered as part of the decision step, and therefore Step 3 should look like this instead:
Step 3:
```
decision_step, terminal_step = self.env.get_steps(self.name)
print(decision_step.obs[0].shape[0]) Output: 1
print(terminal_step.obs[0].shape[0]) Output: 1
```

### To add actual code:
```
decision_steps, terminal_steps = unity_env.get_steps(behavior_name)
print(f"decision_steps {decision_steps.obs[0].shape[0]}")
print(f"terminal_steps {terminal_steps.obs[0].shape[0]}")
```
This is the Output:
```
decision_steps 2
terminal_steps 0
decision_steps 2
terminal_steps 0
decision_steps 2
terminal_steps 0
decision_steps 0
terminal_steps 1
```

### Screenshot of the environment with 2 Agents
Shortly before the ball on the left environment drops of and the episode ends, only for the left agent. The right ball won't reset.

![image](https://user-images.githubusercontent.com/19360485/193335936-071a1364-5545-4afb-957e-e72995e5d7ee.png)

So another theory would be, the observation that is from the agent still on the platform, non-ended episode, is stored in the terminal_step, could that be possible? If yes, that would be very confusing.

### Just tested this also with 3 Agents

![image](https://user-images.githubusercontent.com/19360485/193430152-2f661549-ea6f-4e0d-a6bd-a6c08565bcff.png)

Unfortunately, same outcome:
```
decision_steps, terminal_steps = unity_env.get_steps(behavior_name)
print(f"decision_steps {decision_steps.obs[0].shape[0]}")
print(f"terminal_steps {terminal_steps.obs[0].shape[0]}")
```
This is the Output:
```
decision_steps 3
terminal_steps 0
decision_steps 3
terminal_steps 0
decision_steps 3
terminal_steps 0
decision_steps 0
terminal_steps 1
```

Additionally, it seems strange that the bool array in `interruped`, holds only one `False` but it is not clear why that is. From [here](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Python-API.md#terminalsteps-and-terminalstep), I can find out that "if the Agent reached the maximum number of steps" this will be `True`? But If I manually end the episode using `EndEpisode();`, shouldn't this be `True` as well?

Attached, screenshot of `terminal_steps` printed in debug console:

![image](https://user-images.githubusercontent.com/19360485/193430469-4848b2c2-ec49-454b-a350-6dc1b8be1676.png)

**Environment (please complete the following information):**
- Unity Version: Unity 2021.2.10f
- OS + version: Windows 10
- _ML-Agents version_: Release 19
- _Torch version_: as suggested in install guide for Release 19
- _Environment_: [Rolling Ball](https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Learning-Environment-Create-New.md)

**Comment by miguelalonsojr** [comment]
This is not a bug. In ML-Agents, the python process, i.e. the UnityEnv, is actually the server, serving decisions as the agents request them. Unity is the client. Agents are free to make decisions independently of each other at different decision frequencies, as well as, have their episodes terminated independently of each other. This results in a situation where the Unity environment will be sending information about agents , e.g. terminal state info, before other agents in the environment are ready for decisions. Hence that is why you see 0 agents requiring a decision when the other agent is in a terminal state. The agent that is still 'alive' doesn't need a decision yet. The terminal condition likely happened in between normal decision steps if you have the decision requestor period set to 10, for example, as it specifies in the roller ball tutorial. I wager that if you call step and get_steps again after you see the terminal state, you'll get the correct agent requiring a decision. To verify this, you can set the decision frequency to 1, which will force agents to make decisions at every academy step. This is a bit counter intuitive if you're used to the OpenAI gym api style of RL. step and get_steps do different things. You can read more about the low-level API and how step and get_steps works here: https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Python-API.md
