### ISSUE TITLE
Support for M1 Macs that can't install pytorch < 1.9.0

### ISSUE THREAD

**Issue by bbusche** [Unity-Technologies/ml-agents#5797]
**Is your feature request related to a problem? Please describe.**
Using python 3.9.13, I cannot get pip to install a version of pytorch < 1.9.0 on an M1 Mac Monterey 12.6

**Describe the solution you'd like**
If ml-agents can successfully use pytorch >= 1.9.0 as a dependency, please increase the required pytorch version number so pip doesn't error with this output:
`The conflict is caused by:
    mlagents 0.29.0 depends on torch<1.9.0 and >=1.8.0; platform_system != "Windows" and python_version >= "3.9"`

**Describe alternatives you've considered**
I have tried installing older versions of pytorch, within the torch<1.9.0 and >=1.8.0 constraint.  This fails on M1 Mac Monterey 12.6

**Additional context**

**Comment by automata** [comment]
@bbusche I got a working ml-agents on Apple M2 (Monterey) using Python 3.10.7 and PyTorch stable (1.12.1). I had to clone the ml-agents repos and change `ml-agents/ml-agents/setup.py` to:

```
"torch>=1.8.0,<=1.12.0;(platform_system!='Windows' and python_version>='3.9')"
```

Then `pip install -e path/to/clone/of/ml-agents`.

**Comment by hughperkins** [comment]
I feel like this has been fixed in `release_20`?  https://github.com/Unity-Technologies/ml-agents/blob/5b6cb9878c611d5c50585f6400ebb8fe16ee8f1f/ml-agents/setup.py#L71

<img width="732" alt="Screen Shot 2022-12-17 at 4 36 28 PM" src="https://user-images.githubusercontent.com/123560/208266846-4820ed85-2ee5-42fc-b54e-e40979f8406b.png">

**Comment by Eatin8** [comment]
I am getting the same issue

**Comment by Arlen0615** [comment]
I am getting the same issue
