### ISSUE TITLE
Visual studio doesn't identify the MLAgents library when i use it.

### ISSUE THREAD

**Issue by lede05** [Unity-Technologies/ml-agents#5803]
Visual Studio ignores when I puwrite down "using Unity.MLAgents;" what means not recognising classes such as agent.

It may not be a bug, in that case, I would thank it so much if someone explained me how to fis that issue.

**Comment by hughperkins** [comment]
Using VS Code, I had to quit VSCode at least once, and quit Unity at least once, in order for VSCode to recognize mlagents things. This is after installing the MLAgents package into Unity. I installed `release_20`, from downloading the github repo. (I agree that VSCode != VS, but just in case useful).

**Comment by EugenVasilachi** [comment]
I had the same problem and I spent hours to figure it out. Visual Studio didn't recognize anything related to Unity. But this helped me and I think it will work for you too (the answer from Geeky Quentin).
https://stackoverflow.com/questions/72841461/unity-namespaces-arent-available
