### ISSUE TITLE
Running ml-agents with visual observations on headless server with xvfb-run causes repeated frames

### ISSUE THREAD

**Issue by superkaiba** [Unity-Technologies/ml-agents#5804]
When I run my experiment locally it works perfectly and I am available to get a smooth movie of what my agent sees, but when I run it on a headless server with xvfb-run, the visual observations get repeated for 6-8 frames so that the movie that I generate is frozen for 6-8 frames at a time.

I know this is somewhat a vague description and it is with a custom environment so I won't provide reproduction steps but I was just wondering if anyone had ever encountered this bug or might have some idea what might be causing it.

The xvfb command I am using is `xvfb-run --auto-servernum --server-args='-screen 0 640x480x24:32' python run.py -batchmode`

(run.py is where I initialize the environment, collect the observations from the environment and turn them into a movie)

Thanks!

**Comment by RedTachyon** [comment]
My one piece of anecdata is that I generate videos in a similar way very often, and haven't had any such issues. I do it a bit differently though, by using `pyvirtualdisplay` inside of the python code before launching the Unity executable, and take snapshots within Python after each action, so maybe that will work better
