### ISSUE TITLE
"Creating a tensor from a list of numpy.ndarrays is extremely slow" warinig from the pytorch

### ISSUE THREAD

**Issue by iiiyx** [Unity-Technologies/ml-agents#5811]
**Describe the bug**
Here we have a description of the issue: https://github.com/pytorch/pytorch/issues/13918
Briefly: calling `torch.tensor(np.array(a))` is 200x faster than `torch.tensor(a)`

**To Reproduce**
1. Install the latest `mlagents`
2. Install the latest `pytorch` (1.13.0)
3. Run `mlagents-learn`
4. Start game process in Unity

**Console logs / stack traces**
```
/home/osob/miniconda3/envs/tf/lib/python3.8/site-packages/mlagents/trainers/torch/networks.py:91:
UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow.
Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor.
(Triggered internally at ../torch/csrc/utils/tensor_new.cpp:230.)
  enc.update_normalization(torch.as_tensor(vec_input))
```

**Environment (please complete the following information):**
- Unity Version: 2021.3.12f1
- OS + version: Windows 10 + WSL2 (running mlagents inside WSL)
- Version information:
  ml-agents: 0.29.0,
  ml-agents-envs: 0.29.0,
  Communicator API: 1.5.0,
  PyTorch: 1.13.0+cu117

(https://github.com/Unity-Technologies/ml-agents/blob/main/ml-agents/mlagents/trainers/torch/networks.py#L91)

I replaced this
```
enc.update_normalization(torch.as_tensor(vec_input))
```
with this
```
enc.update_normalization(torch.as_tensor(np.array(vec_input)))
```
and of course, added import in the begging of the file:
```
import numpy as np
```

And now I can see with my own eyes that my Unity objects started moving much faster during training

**Comment by TheRisenPhoenix** [comment]
This was fixed in mlagents 0.30.0
