### ISSUE TITLE
How to wrap the env like this?

### ISSUE THREAD

**Issue by thisisbaiy** [Unity-Technologies/ml-agents#5817]
Recently I want to do some research so I need to build an environment. I used found some projects that packed the environment  to an executable file. Which contains the whole details just like this:
![image](https://user-images.githubusercontent.com/96861449/202829341-9ec64fe2-879b-4671-adbc-81d2ef4674bc.png)
![image](https://user-images.githubusercontent.com/96861449/202829367-a9f72884-1e2b-465e-bc20-25e89fd8d7a6.png)

So I'd like to know how to package your sample environment into an executable file similar to the one shown above, so that it can be directly used to train the model similar to the scene built by gym?

**Comment by thisisbaiy** [comment]
The environment file :
![image](https://user-images.githubusercontent.com/96861449/202829518-e7d67714-7b41-4589-99bc-a29626546962.png)

**Comment by jrupert-unity** [comment]
If I'm understanding your question properly this might help:
https://docs.unity3d.com/Manual/PublishingBuilds.html

**Comment by thisisbaiy** [comment]
Ok, thank you for your help, I'm not familiar with unity, So I just wanna a demo about wrap the mlagents-env. But in any cases, thank you for your answer!
