### ISSUE TITLE
Where did the documentation go?

### ISSUE THREAD

**Issue by trsh** [Unity-Technologies/ml-agents#5829]
All links of documentation go to same index readme `https://github.com/Unity-Technologies/ml-agents/blob/release_20_docs/docs/Readme.md`

```
Our latest, stable release is Release 19
```

But its 20, and the link goes to one above with no docs at all

**Comment by maryamhonari** [comment]
Hi @trsh, 

Thanks for reporting this bug, it is fixed now (#5832).
