### ISSUE TITLE
Selfplay team change first action ignores actionmask

### ISSUE THREAD

**Issue by TheRisenPhoenix** [Unity-Technologies/ml-agents#5830]
**Describe the bug**
I'm training my agent in self-play, switching the team after 100.000 steps. It went well, but suddenly, at the next step after the team switch, it failed. 
I investigated the behavior with the editor and found out, that, in training mode, the first time the agent of the new team is triggered, it chooses an invalid action (that is, action 0, which happens to be masked by that time of the game). I tested it multiple times, but in each case the first move of the new team's agent would choose this masked action 0. I implemented a workaround in my game that handles those invalid action choices, and noticed, that once this first action was done, everything goes well. This is, that second and following choices of the new team are again respecting the action mask. 
Perhaps this might be a coincidence, but for me it looks like this might be related to switching teams.

**Environment (please complete the following information):**
- Unity Version: Unity 2021.3.12f1
- OS + version:  Windows 10
- _ML-Agents version_: 0.30.0
- _Torch version_: 1.18

**Comment by ArchageXIII** [comment]
I've been fighting with this for a week as well, i think it's def a bug.  It's not just self play even if you have 2 agents learning off each other you get the same issue with discrete actions.  I did loads of testing I have 0 100% masked all the time and I still get 0 passed across as an action every now and then.  I'm training turn based so it's really obvious when it goes out of sync, I don't think it would notice for more general actions.  I worked around it killing any episodes where 0 got passed but even then it was unstable.   I'm doing it manually and it's rock solid just takes longer, so train one agent against random/sample set heuristics then train the other again back against the brain from that and repeat.  Had a poke about in the source code, found a few if actionmask is null return empty array of 0 but couldn't pin down exactly where it was happening. 

33 : 1 : playerO : CollectObservations : observationAndMoveInProgress : True
33 : 1 : playerO : CollectObservations : postMoveObservationInProgress : False
33 : 1 : playerO : CollectObservations : PlayerO Observations : 0, 0, 0, 0.5, 0, 0, 0, 0, 0
33 : 1 : playerO : WriteDiscreteActionMask : Start
33 : 1 : playerO : WriteDiscreteActionMask : postMoveObservationInProgress : False
33 : 1 : playerO : WriteDiscreteActionMask : End
33 : 1 : playerO : ProcessAction : Start
38 : 1 : playerO : OnActionReceived : observationAndMoveInProgress : True : playerO : OnActionReceived : 0
38 : 1 : playerO : OnActionReceived : postMoveObservationInProgress : False : playerO : OnActionReceived : 0
38 : 1 : playerO : OnActionReceived: got unexpected value : 0
