### ISSUE TITLE
First episode: No episode was completed since last summary. Training.

### ISSUE THREAD

**Issue by philippds** [Unity-Technologies/ml-agents#5836]
**Describe the bug**
If the `summary_freq` in the config file is equal to the `Max Step` in the Agent Component, with a Decision Requester Component with `Decision Period` set to `1`, the initial episode won't get recorded and is either printing in terminal "No episode was completed since last summary. Training." or no message at all, e.g. starting at 200 steps when config `summary_freq` is set to 100. Is this behaviour intended? I tested this with my custom environment, but this can also be reproduced in 3DBall (with 1 Agent only) example. Of course I could change the `summary_freq` in the config to be `Max Step` + 1, but that doesn't feel clean. Either I'm missing something or this might be a bug. Thanks for your time!

**To Reproduce**
1. Open 3DBall example (with 1 Agent only)
2. Change Decision Requester Component `Decision Period` to `1`
3. Start training
4. No episode was completed since last summary. or no stats are printed

**Screenshots**
3DBall Env (with 1 Agent only), starting at 200, instead of 100 `MaxStep` 100, `Decision Period` set to `1`:
[INFO] 3DBall. Step: 200. Time Elapsed: 12.053 s. Mean Reward: 10.000. Std of Reward: 0.000. Training.
[INFO] 3DBall. Step: 300. Time Elapsed: 12.750 s. Mean Reward: 10.000. Std of Reward: 0.000. Training.
[INFO] 3DBall. Step: 400. Time Elapsed: 13.451 s. Mean Reward: 10.000. Std of Reward: 0.000. Training.

3DBall Env (with 1 Agent only), starting at 100 `MaxStep` 100, `Decision Period` set to `2`:
[INFO] 3DBall. Step: 100. Time Elapsed: 12.184 s. Mean Reward: -1.600. Std of Reward: 0.000. Training.
[INFO] 3DBall. Step: 200. Time Elapsed: 13.138 s. Mean Reward: 4.450. Std of Reward: 0.550. Training.
[INFO] 3DBall. Step: 300. Time Elapsed: 13.930 s. Mean Reward: -1.600. Std of Reward: 6.600. Training.

Custom Env:
[INFO] TurbineAgent. Step: 2000. Time Elapsed: 20.329 s. No episode was completed since last summary. Training.
[INFO] TurbineAgent. Step: 4000. Time Elapsed: 29.777 s. Mean Reward: 2000.000. Std of Reward: 0.000. Training.
[INFO] TurbineAgent. Step: 6000. Time Elapsed: 39.645 s. Mean Reward: 2000.000. Std of Reward: 0.000. Training.

**Environment (please complete the following information):**
- Unity Version: [e.g. Unity 2021.3.5f1]
- OS + version: [e.g. Windows 11]
- _ML-Agents version_: Release 19 (0.28.0)
- _Torch version_: 1.7.1+cpu
- _Environment_: 3DBall (with 1 Agent only)

**Comment by miguelalonsojr** [comment]
We just cut release 20. Can you update and check to see if the problem persists?
