### ISSUE TITLE
Can I Visualize the state-value-function?

### ISSUE THREAD

**Issue by likeygame** [Unity-Technologies/ml-agents#585]
Hi
I want to look over what value the ml-agent makes when given specific observation.
like 1:02:18~1:04:32 in David Silver Lecture

> https://www.youtube.com/watch?v=2pWv7GOvuf0&t=3249s

**Comment by vincentpierre** [comment]
We are planning to include this feature into the project soon.

**Comment by awjuliani** [comment]
Hi @likeygame,

We have an open PR related to this feature. You can view it here: https://github.com/Unity-Technologies/ml-agents/pull/934.
