### ISSUE TITLE
Memory leaks in vision sensors

### ISSUE THREAD

**Issue by trsh** [Unity-Technologies/ml-agents#5852]
**Describe the bug**
When using Render to texture or camera sensor, memory grows really fast until the learning crashes.

**To Reproduce**
Train attached project.
[AI_DIST_PERC.zip](https://github.com/Unity-Technologies/ml-agents/files/10294762/AI_DIST_PERC.zip)
Config is in Assets/MLConfig
For even faster memory growing uncheck `Grayscale`

**Console logs / stack traces**
Not required

**Screenshots**
Not required

**Environment (please complete the following information):**
- Unity Version: Unity 2022.2.1f1
- OS + version: Windows 11
- _ML-Agents version_: 
 Version information:
  ml-agents: 0.31.0.dev0,
  ml-agents-envs: 0.31.0.dev0,
  Communicator API: 1.5.0,
  PyTorch: 1.13.0+cu117
[INFO] Listening on port 5004. Start training by pressing the Play button in the Unity Editor.
[INFO] Connected to Unity environment with package version 2.3.0-exp.4 and communication version 1.5.0

**Comment by trsh** [comment]
Some people reported issues opening the scene, so I am including the project as package export:

**Comment by Wanfanel** [comment]
Your buffer is currently using 26GB of memory, leaving only 6GB for your editor and system. However, in reality, this amount may even be less. If your buffer and data are too large, you may run out of memory. To avoid this issue, you can try using a smaller buffer size such as 1024, which would only require 2.6GB of memory for the buffer.

**Comment by trsh** [comment]
> Your buffer is currently using 26GB of memory, leaving only 6GB for your editor and system. However, in reality, this amount may even be less. If your buffer and data are too large, you may run out of memory. To avoid this issue, you can try using a smaller buffer size such as 1024, which would only require 2.6GB of memory for the buffer.

Ouh. I see. You calculated the 26GB like in the example of your previous comment?

**Comment by miguelalonsojr** [comment]
> @miguelalonsojr this also still relevant.

This seems like a resource issue and not a bug. As @Wanfanel mentioned, depending on your environment settings and training configuration settings, you may run into memory issues. My suggestion is to profile the Unity environment separate from training to make sure that there are no memory leaks in Unity. As far as the python trainers go, all of the observations from the agent are converted to tensors and buffered. If you have torch compatible GPU installed in your system, the ML-Agents training pipeline will automatically use that GPU for training.

**Comment by trsh** [comment]
> > @miguelalonsojr this also still relevant.
> 
> This seems like a resource issue and not a bug. As @Wanfanel mentioned, depending on your environment settings and training configuration settings, you may run into memory issues. My suggestion is to profile the Unity environment separate from training to make sure that there are no memory leaks in Unity. As far as the python trainers go, all of the observations from the agent are converted to tensors and buffered. If you have torch compatible GPU installed in your system, the ML-Agents training pipeline will automatically use that GPU for training.

I already tested that. Memory is building up on python side. And yes I use my rtx 3060 with torch.

**Comment by trsh** [comment]
@miguelalonsojr I don't see an example project called Visual3D

**Comment by miguelalonsojr** [comment]
https://github.com/Unity-Technologies/ml-agents/tree/develop/Project/Assets/ML-Agents/Examples/3DBall/Scenes

All of our example environments are in one Unity project. It's the scene called Visual3DBall.
