### ISSUE TITLE
The documentation link is still Invalid

### ISSUE THREAD

**Issue by trsh** [Unity-Technologies/ml-agents#5853]
The documentation link is still Invalid

![2022-12-25_100713](https://user-images.githubusercontent.com/3727523/209461089-5d389575-f280-4f11-bbcf-f6050ff134c8.png)

This goes to same Index readme!

**Comment by TheRisenPhoenix** [comment]
Same for `Our latest, stable release is Release 20. Click [here](https://github.com/Unity-Technologies/ml-agents/tree/release_20_docs/docs/Readme.md) to get started with the latest release of ML-Agents.`, it references the same readme again, but should reference `https://github.com/Unity-Technologies/ml-agents/blob/release_20_docs/docs/Getting-Started.md`
(it's correct on the develop branch, but not in the main branch, where you usually start off)

**Comment by hughperkins** [comment]
@ Unity: note that you can add a link checker to your CI server using e.g. markdown-link-check https://github.com/tcort/markdown-link-check e.g. see following example:

https://github.com/hughperkins/VeriGPU/blob/501caddd100e5245658008bb42f17ef8e97d4192/cicd/check_markdown.sh

**Comment by hughperkins** [comment]
(oh, mind you, this won't detect links that go to the wrong place, that actually exists...)

**Comment by Xardas0327** [comment]
the link should be similar like the previous one.
https://github.com/Unity-Technologies/ml-agents/blob/release_19_docs/docs/Readme.md

**Comment by Xardas0327** [comment]
The link is still bad

**Comment by hughperkins** [comment]
the link is still broken, not fixed.

**Comment by miguelalonsojr** [comment]
will be fixed on next release.
