### ISSUE TITLE
Support for GPU acceleration in Apple silicon devices (Requires Python 1.13+)

### ISSUE THREAD

**Issue by bikcrum** [Unity-Technologies/ml-agents#5855]
Problem:
Starting Pytorch version 1.13, it can use GPU on Apple silicon devices but the latest release (at the time of this post) of mlagents which is 0.30.0 requires Pytorch to be <=1.11.0 which unfortunately does not support GPU acceleration on Apple silicon devices.

Possible solution:
I would want to request a new release of mlagents that is at least PyTorch 1.13 and also changes in the code that incorporates the "mps" device (GPU of Apple silicon).

Reason for change:
Training on the CPU leaving the GPU unused is significantly slower.

**Comment by bikcrum** [comment]
Temporarily, I installed mlagent library with --no-deps that omits Pytorch installation and installed Pytorch 1.13 manually. After that, I monkey patched the [torch.py](https://github.com/Unity-Technologies/ml-agents/blob/28ec36a74384f37eea75753b50a01436931dcaca/ml-agents/mlagents/torch_utils/torch.py) code in this repository. 

Changes: https://github.com/pytorch/pytorch/issues/82296#issuecomment-1367188432

**Comment by Eelam** [comment]
Hi,
I am curious to know how much gain you get when the GPU is used.
What is your Apple silicon Spec?
Thanks

**Comment by bikcrum** [comment]
> Hi, I am curious to know how much gain you get when the GPU is used. What is your Apple silicon Spec? Thanks

I have M1 Max 24-core GPU. However, the performance was worse than the CPU. My task was fairly simple so it might be true that GPU didn't have an advantage and probably be useful for the more complex tasks (like CNN layers). I tested the same task on RTX 3050 and it took a lead over M1. I am waiting for the official changes in the Pytorch and ml-agents library that incorporates apple silicon GPU and hopefully will be better than what workaround we have now.

**Comment by vincentzhou2013** [comment]
Thanks for the information provided. I managed to get it run but having below errors. not sure if able to find a way to move forward.  here is the log
`Version information:
  ml-agents: 0.30.0,
  ml-agents-envs: 0.30.0,
  Communicator API: 1.5.0,
  PyTorch: 1.13.1
[INFO] Listening on port 5004. Start training by pressing the Play button in the Unity Editor.
[INFO] Connected to Unity environment with package version 2.0.1 and communication version 1.5.0
[INFO] Connected new brain: myTest?team=0
[INFO] Hyperparameters for behavior name myTest:
	trainer_type:	ppo
	hyperparameters:
	  batch_size:	2048
	  buffer_size:	16384
	  learning_rate:	0.0001
	  beta:	0.005
	  epsilon:	0.1
	  lambd:	0.95
	  num_epoch:	4
	  shared_critic:	True
	  learning_rate_schedule:	linear
	  beta_schedule:	linear
	  epsilon_schedule:	linear
	network_settings:
	  normalize:	False
	  hidden_units:	256
	  num_layers:	3
	  vis_encode_type:	resnet
	  memory:
	    sequence_length:	128
	    memory_size:	512
	  goal_conditioning_type:	hyper
	  deterministic:	False
	reward_signals:
	  extrinsic:
	    gamma:	0.8
	    strength:	1.0
	    network_settings:
	      normalize:	False
	      hidden_units:	128
	      num_layers:	2
	      vis_encode_type:	simple
	      memory:	None
	      goal_conditioning_type:	hyper
	      deterministic:	False
	init_path:	None
	keep_checkpoints:	5
	checkpoint_interval:	500000
	max_steps:	16000000
	time_horizon:	128
	summary_freq:	20000
	threaded:	False
	self_play:	None
	behavioral_cloning:	None
loc("total derivative last state"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/9e200cfa-7d96-11ed-886f-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":228:0)): error: input types 'tensor<1x128x256xf32>' and 'tensor<1x16x256xf32>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
zsh: abort      mlagents-learn Assets/config/laserAgent.yaml --run-id=myTest0208
(gpu)  % [ERROR] UnityEnvironment worker 0: environment raised an unexpected exception.
Traceback (most recent call last):
  File "/opt/anaconda3/envs/gpu/lib/python3.10/site-packages/mlagents/trainers/subprocess_env_manager.py", line 175, in worker
    req: EnvironmentRequest = parent_conn.recv()
  File "/opt/anaconda3/envs/gpu/lib/python3.10/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/opt/anaconda3/envs/gpu/lib/python3.10/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/opt/anaconda3/envs/gpu/lib/python3.10/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError
Process Process-1:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/gpu/lib/python3.10/site-packages/mlagents/trainers/subprocess_env_manager.py", line 175, in worker
    req: EnvironmentRequest = parent_conn.recv()
  File "/opt/anaconda3/envs/gpu/lib/python3.10/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/opt/anaconda3/envs/gpu/lib/python3.10/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/opt/anaconda3/envs/gpu/lib/python3.10/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/gpu/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/anaconda3/envs/gpu/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/gpu/lib/python3.10/site-packages/mlagents/trainers/subprocess_env_manager.py", line 235, in worker
    _send_response(EnvironmentCommand.ENV_EXITED, ex)
  File "/opt/anaconda3/envs/gpu/lib/python3.10/site-packages/mlagents/trainers/subprocess_env_manager.py", line 150, in _send_response
    parent_conn.send(EnvironmentResponse(cmd_name, worker_id, payload))
  File "/opt/anaconda3/envs/gpu/lib/python3.10/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/opt/anaconda3/envs/gpu/lib/python3.10/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/opt/anaconda3/envs/gpu/lib/python3.10/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
/opt/anaconda3/envs/gpu/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 3 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '`

**Comment by davidceka** [comment]
Also waiting for native support for MPS device type. Hoping it will be implemented soon, subscribing to the thread for eventual updated

**Comment by vincentzhou2013** [comment]
Hi @bikcrum , it looks like the modification doesn't work anymore with the latest release.  Could you provide an updated one(to  use M1 GPU)? Thanks.
Here is the version information:

 Version information:
  ml-agents: 1.1.0.dev0,
  ml-agents-envs: 1.1.0.dev0,
  Communicator API: 1.5.0,
  PyTorch: 2.1.0
