### ISSUE TITLE
Hindsight Experience Replay (HER)

### ISSUE THREAD

**Issue by trsh** [Unity-Technologies/ml-agents#5861]
Why was this closed as completed https://github.com/Unity-Technologies/ml-agents/issues/2667 ?
Do we have [Hindsight Experience Replay (HER)](https://arxiv.org/abs/1707.01495) ?
If no, this is a valuable feature request and could stay open.

**Comment by miguelalonsojr** [comment]
Thanks for reaching out. This was closed en masse to cleanup old issues and requests for determining which issues are still relevant for the community. Re-opening.

**Comment by trsh** [comment]
I am still interest in this being implemented. Please reopen.
