### ISSUE TITLE
UserWarning: The use of x.T is deprecated

### ISSUE THREAD

**Issue by TheRisenPhoenix** [Unity-Technologies/ml-agents#5870]
**Describe the bug**
When training (no matter whether PPO or SAC), after a while, I get the following warning from
`mlagents\trainers\torch_entities\utils.py:289` 
I use ~400 observations and have 112 discrete actions. (One Branch with 112 fields).
After the warning appears, my environment slows down and I can feel everything getting slower.

This only happens with SAC, PPO is fine.

**To Reproduce**
Train anything with probably a number of observations and discrete actions. Use SAC.

**Console logs / stack traces**
```
mlagents\trainers\torch_entities\utils.py:289: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3281.)
  torch.nn.functional.one_hot(_act.T, action_size[i]).float()
```

**Environment (please complete the following information):**
- Unity Version: 2022.2.2f1
- OS + version: Windows 11
- _ML-Agents version_: 0.30.0
- _Torch version_: 1.13.1+cu117
- _Python version_: 3.10.9

**Comment by wspeiser27** [comment]
I have the same issue. I have 4 continuous actions and no discrete actions. I am using a camera sensor input. Latest MLAgents version.

**Comment by Gregeasts** [comment]
Anybody find an answer to this? I am struggling with the same issue

**Comment by william27a** [comment]
onehot_branches = [
            torch.nn.functional.one_hot(_act.T, action_size[i]).float()
            for i, _act in enumerate(discrete_actions.long().T)
        ]
return onehot_branches



I just followed the error message, and it seems to be working.

**Comment by domrice** [comment]
> onehot_branches = [ torch.nn.functional.one_hot(_act.T, action_size[i]).float() for i, _act in enumerate(discrete_actions.long().T) ] return onehot_branches
> 
> I just followed the error message, and it seems to be working.

Sorry, but could you please clarify what you did? If I look up the respective file under `...\anaconda3\envs\mlagents\Lib\site-packages\mlagents\trainers\torch_entities\utils.py`, I have the following method, which looks exactly like yours, but I am still getting the error? What do I have to change here?

```python
@staticmethod
    def actions_to_onehot(
        discrete_actions: torch.Tensor, action_size: List[int]
    ) -> List[torch.Tensor]:
        """
        Takes a tensor of discrete actions and turns it into a List of onehot encoding for each
        action.
        :param discrete_actions: Actions in integer form.
        :param action_size: List of branch sizes. Should be of same size as discrete_actions'
        last dimension.
        :return: List of one-hot tensors, one representing each branch.
        """
        onehot_branches = [
            torch.nn.functional.one_hot(_act.T, action_size[i]).float()
            for i, _act in enumerate(discrete_actions.long().T)
        ]
        return onehot_branches
```

**Comment by SmlHugod** [comment]
UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3641.)
  torch.nn.functional.one_hot(_act.T, action_size[i]).float()

Still happening with no solution but closed ? Why ?

Using ppo though

**Comment by Tokymin** [comment]
I had the same problem, and I even tried reinstalling conda's environment. Unfortunately, this issue still exists, and Unity can jam for several seconds when it happens, and the random actions feel irrational

**Comment by tybar01** [comment]
For anyone wondering about this I found a solution that worked. 

        """
        Takes a tensor of discrete actions and turns it into a List of onehot encoding for each
        action.
        :param discrete_actions: Actions in integer form.
        :param action_size: List of branch sizes. Should be of same size as discrete_actions'
        last dimension.
        :return: List of one-hot tensors, one representing each branch.
        """
        onehot_branches = [
            torch.nn.functional.one_hot(_act.permute(*torch.arange(_act.ndim - 1, -1, -1)), action_size[i]).float()
            for i, _act in enumerate(discrete_actions.long().T)
        ]
        return onehot_branches

adding .permute(*torch.arange(x.ndim - 1, -1, -1)) instead of .T like in the code I linked above.

If it isn't the same exact as yours I'd say look into the error message to see the function to replace it with.
My error message contained "add x.permute(*torch.arange(x.ndim - 1, -1, -1))" So I treated the "_act" as the "x" in their code for the adjustment above.

The path to this file was also included in the start of the error message, as well as the line it was on.
