### ISSUE TITLE
Why isn't training with --no-graphics faster than with graphics?

### ISSUE THREAD

**Issue by visuallization** [Unity-Technologies/ml-agents#5876]
**Describe the bug**
Training an agent without graphics (setting `--no-graphics` in mlagents-learn command)  isn't faster than training an agent with graphics.

So I am not sure if this is an actual bug but my intuition would say that training should be faster without graphics.
**To Reproduce**
1. Run `mlagents-learn [trainer-config-file] --env=[env_name] --no-graphics --run-id=[run-identifier]`
2. Run `mlagents-learn [trainer-config-file] --env=[env_name] --run-id=[run-identifier]`
3. Compare the training time of both runs
4. See there is no real difference in the training time

**Console logs / stack traces**
Please wrap in triple backticks (```) to make it easier to read.

**Screenshots**

<img width="558" alt="Screenshot_1" src="https://user-images.githubusercontent.com/6199277/218257828-a7985a8b-02bf-47e8-a62a-091fbb9f2bbe.png">

**Environment (please complete the following information):**
- Unity Version: Unity 2022.1.14f1
- OS + version: Windows 11
- _ML-Agents version_: ml-agents 2.0.1
- _Torch version_: torch 1.12.1 + cu116
- _Environment_: custom environment but I would guess you would experience the same issue in all environments

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by wbarteck** [comment]
You should also change the timescale if you want training to take less time, otherwise its running at the same pace just not rendering

you should be able to handle a higher timescale without rendering anything
