### ISSUE TITLE
How can I wrap Unity to Multi-agent Gym Environment? And where can I download gym_unity 0.30.0?

### ISSUE THREAD

**Issue by neulizhe** [Unity-Technologies/ml-agents#5878]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by neulizhe** [comment]
I want to wrap Unity to multi-agent gym environment, how can I do it?
Where can I download gym_unity 0.30.0?

**Comment by elliottower** [comment]
> I want to wrap Unity to multi-agent gym environment, how can I do it? Where can I download gym_unity 0.30.0?

I think this is probably what you're looking for: https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/Python-PettingZoo-API.md
Note that this uses an old version of pettingzoo and is not compatible with the current pettingzoo API (current version is 1.22.3, unity ml-agents codebase uses 1.15.0)
