### ISSUE TITLE
Tensorflow having issues teaching car how to drive

### ISSUE THREAD

**Issue by Myteq** [Unity-Technologies/ml-agents#588]
Hello.
I have tried to teach a car how to drive using 5 raycasters giving distances to obstacles. The car is always moving and could just steer left right or forward  , getting reward for staying for as long as possible. The problem is after teaching it, it just keeps steering left colliding almost immediatelly and I have no idea why :(.

Problem idea
![img2](https://user-images.githubusercontent.com/9040114/38459683-46da09ea-3aad-11e8-85a7-b1d71c18927b.jpg)

Tensorboard output
![1](https://user-images.githubusercontent.com/9040114/38459692-68681ea8-3aad-11e8-9813-c7f3d3d79595.jpg)

I have succesfully managed to train before the balance ball example as well as problem from Unity3d College tutorials(about moving to given number). In player mode everything seems to be working perfectly. Any help is much appreciated.

**Comment by Lakrix** [comment]
Do you use discrete or continuous input? Can you provide the code n your player class and your settings in your brain object in unity?

**Comment by Myteq** [comment]
Input is discrete.

Car agent code:
```C#
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class CarAgent : Agent
{
    private const int maxDuration = 300;    

    [SerializeField]
    private Rigidbody rigidbody;

    [SerializeField]
    private Vector3 startingCarPosition;

    [SerializeField]
    private Transform carTransform;
    public Text text;
    private float duration = 0f;
    int count = 0;

    public int count0 = 0;
    public int count1 = 0;
    public int count2 = 0;

    [SerializeField]
    private SimpleCarController simpleCarController;

    public override List<float> CollectState()
    {

        List<float> state = new List<float>();
        state.Add(RaycastCollisionDetector.leftDetectorState30);
        state.Add(RaycastCollisionDetector.leftDetectorState60);
        state.Add(RaycastCollisionDetector.forwardDetectorState);
        state.Add(RaycastCollisionDetector.rightDetectorState30);
        state.Add(RaycastCollisionDetector.rightDetectorState60);
        // state.Add(SimpleCarController.carSpeed);
        // state.Add(SimpleCarController.angle);

        return state;
    }
    public override void AgentStep(float[] action)
    {
        switch ((int)action[0])
        {
            case 0:
                SimpleCarController.turnLeft = true;
                SimpleCarController.turnRight = false;
                count0++;
                break;
            case 1:
                SimpleCarController.turnLeft = false;
                SimpleCarController.turnRight = false;
                count1++;
                break;
            case 2:
                SimpleCarController.turnLeft = false;
                SimpleCarController.turnRight = true;
                count2++;
                break;

            default:
                SimpleCarController.turnLeft = false;
                SimpleCarController.turnRight = false;
                break;
        }

        if (RaycastCollisionDetector.hasCollided)
        {
            done = true;
            reward = -10;
            count++;
            AgentReset();
        }
        else if (duration > maxDuration)
        {
            done = true;
            count++;
        }
        else
        {
            duration += Time.deltaTime;
            reward = duration;

        }
        text.text = "dur: " + duration + "rew: " + reward + "cout: " + count + "rew: " + reward + " " + "decisin: " + (int)action[0];

    }
    public override void AgentReset()
    {
        duration = 0;
        carTransform.position = startingCarPosition;
        carTransform.rotation = Quaternion.identity;
        rigidbody.velocity = Vector3.zero;
        rigidbody.angularVelocity = Vector3.zero;
        RaycastCollisionDetector.hasCollided = false;
        simpleCarController.ResetInputs();

    }
}
```

And the brain object settings:
![2](https://user-images.githubusercontent.com/9040114/38518949-a7624dbc-3c3e-11e8-957a-abe2e031e77e.jpg)

**Comment by Myteq** [comment]
Sorry for no response. After aplying suggestions from @Hengoo, the car moves more randomly, not just turning one way all the time. Also i found that my car has tendency to drive on 2 wheels, which causes collider detectors to wrongly measure distance(as it raycasts from rotating object). I will for sure try to fix it and se the results, but more likely towards the end of the week. I will let you know about the results when I have them.

**Comment by Myteq** [comment]
It works now :). Thanks for your help. Turns out there was also problem with physics being updated on Update and not FixedUpdate.
![tensorboard](https://user-images.githubusercontent.com/9040114/39085401-f4cc9f7a-4581-11e8-8f3f-dab2fe94f646.jpg)
