### ISSUE TITLE
Feature request: upgrade to gymnasium/update pettingzoo version

### ISSUE THREAD

**Issue by elliottower** [Unity-Technologies/ml-agents#5890]
**Is your feature request related to a problem? Please describe.**

Hi, would it be possible add compatibility with [Gymnasium](https://github.com/Farama-Foundation/Gymnasium) and newer versions of [PettingZoo](https://github.com/Farama-Foundation/PettingZoo)? 

Gymnasium and PettingZoo are compatible with current RL training libraries ([rllib](https://github.com/ray-project/ray/tree/master/rllib), [tianshou](https://github.com/thu-ml/tianshou) and [CleanRL](https://github.com/vwxyzjn/cleanrl) have already migrated, and [stable-baselines3](https://github.com/DLR-RM/stable-baselines3/blob/e5deeed16efb57c34ccdcb14692439154d970527/docs/guide/install.rst#bleeding-edge-version) will soon) as well as other tools such as Comet and WandB.

For information about upgrading and compatibility, see [migration guide](https://gymnasium.farama.org/content/migration-guide/) and [gym compatibility](https://gymnasium.farama.org/content/gym_compatibility/). The main difference is the API has switched to returning `truncated` and `terminated`, rather than `done`, in order to give more information and mitigate edge case issues. 

We would like to list this package in the third party environments lists ([PettingZoo](https://pettingzoo.farama.org/environments/third_party_envs/), [Gymnasium](https://gymnasium.farama.org/environments/third_party_environments/)), but are removing all libraries which do not plan to migrate to Gymnasium/recent versions of PettingZoo.

**Describe the solution you'd like**

This package would be updated to use gymnasium rather than gym, and use at least PettingZoo v1.20 (uses termination/truncation and gymnnasium rather than gym).

**Describe alternatives you've considered**

**Additional context**

**Comment by elliottower** [comment]
Hi, just bumping this as I would love to be able to use gymnasium/pettingzoo with unity ml-agents. I would be happy to contribute any help which is needed, just wanted to see if this is on the radar and how difficult it would be. 

We are cutting a new pettingzoo release shortly with some important fixes (no major breaking changes) and I was thinking after that is out it would be great to try and update this project to be compatible. Gymnasium had a new release V28 recently and I would be happy to contribute to make that compatible as well.

**Comment by miguelalonsojr** [comment]
Thanks for the request. We're planning these updates for our next release.

**Comment by elliottower** [comment]
> Thanks for the request. We're planning these updates for our next release.

Great to hear, thanks! We are planning a major pettingzoo release either this coming Tuesday or the following Tuesday. The only breaking change is removing the “return_info” argument for reset(), to match gymnasium and always return an info dict. We also fixed a number of bugs, and don’t intend to do any other major releases for a while, so it would be great if ml-agents could be compatible with it. 

I would be happy to help double check that things are fully compatible if you want help.
