### ISSUE TITLE
Can't run 

### ISSUE THREAD

**Issue by AM800Mats** [Unity-Technologies/ml-agents#5891]
**Describe the bug**
When I try to use MLAgents I get the error message: _failed to create process_
I believed something went wrong in the installation. I am trying to follow Code Monkey´s Tutorial to get MLAgents to work for a school project. I am not sure if and how the issue was fixed here: (https://github.com/Unity-Technologies/ml-agents/issues/1845)

**To Reproduce**
1. Start the virtual python environment
2. Try to use any MLAgents command
3. See error

**Console logs / stack traces**
```
C:\Users\Mats\UnityProjects\My project>venv\Scripts\activate

(venv) C:\Users\Mats\UnityProjects\My project>mlagents-learn
failed to create process.

(venv) C:\Users\Mats\UnityProjects\My project>
```

**Environment (please complete the following information):**
- Unity Version: 2021.3.21f1
- OS + version: Windows 11
- _ML-Agents version_: latest release
- _Torch version_: 2.0.0
- _Environment_: none, was following a tutorial.

**Comment by Blitshunter** [comment]
To fix this issue send me 10 euros on paypal 👍

**Comment by Blitshunter** [comment]
Do you want my paypal?

**Comment by miguelalonsojr** [comment]
That tutorial may be outdated. Please follow the installation instructions here: https://unity-technologies.github.io/ml-agents/Installation/ and our getting started guide here: https://unity-technologies.github.io/ml-agents/Getting-Started/

**Comment by AM800Mats** [comment]
Thanks! ill try it out
