### ISSUE TITLE
Unity Machine Learning on ppc64le

### ISSUE THREAD

**Issue by con-bren** [Unity-Technologies/ml-agents#5892]
Hello, my name is Connor Brennan. I'm a postdoctoral research working at the AI institute MILA. 

We are interested in large scale training of RL agents, and we were hoping to use Unity as our main training environment. However, the supercomputers that we are working on (SUMMIT and Frontier) run on the PowerPC architecture (ppc64le). 

Is it possible to build Unity projects for the ppc64le architecture?
If not, how reasonable would it be to add this functionality?

In this age of large scale models it would seem prudent for Unity's ML efforts to support the most powerful open access supercomputers, which (perhaps unfortunately) use the PowerPC architecture.

Thank you!

**Comment by miguelalonsojr** [comment]
Hello! The platforms that Unity supports are listed here: https://support.unity.com/hc/en-us/articles/206336795-What-platforms-are-supported-by-Unity- and here https://docs.unity3d.com/ScriptReference/BuildTarget.html. We support desktop for training, and all Unity supported platforms for inference/deployment. Unfortunately, PowerPC is not among the list of supported architectures.
