### ISSUE TITLE
Worst instructions ever

### ISSUE THREAD

**Issue by nyck33** [Unity-Technologies/ml-agents#5899]
https://github.com/Unity-Technologies/ml-agents/blob/main/docs/Learning-Environment-Executable.md#using-an-environment-executable

ML-Agents or ml-agents, it does not take too much time to ensure correct capitalization.  

Now when I click build I get 

![image](https://user-images.githubusercontent.com/25189545/229521460-2ef51107-84dd-42c1-8457-78f95b56050d.png)

It's a total joke how hard you made this to follow.  There should be way more images with circles on it to show what to look for at each step.

**Comment by nyck33** [comment]
I cloned this repo and tried: https://gamedev.stackexchange.com/q/205153/135208

**Comment by nyck33** [comment]
Here' s an example of how bad "Loading a Unity Environment

Python-side communication happens through UnityEnvironment which is located in [environment.py](https://unity-technologies.github.io/ml-agents/ml-agents-envs/mlagents_envs/environment.py). To load a Unity environment from a built binary file, put the file in the same directory as envs."  What is envs????

**Comment by nyck33** [comment]
(For Windows）With Unity 2018.1, it will ask you to select a folder instead of a file name. Create a subfolder within the root directory and select that folder to build. In the following steps you will refer to this subfolder's name as env_name. You cannot create builds in the Assets folder


I can't create builds in the Assets folder if I"m on Windows and Unity 2018.1 or regardless of OS and Unity version?  You need to be clear.

**Comment by nyck33** [comment]
Click Build:
In the File dialog, navigate to your ML-Agents directory.
Assign a file name and click Save.
(For Windows）With Unity 2018.1, it will ask you to select a folder instead of a file name. Create a subfolder within the root directory and select that folder to build. In the following steps you will refer to this subfolder's name as env_name. You cannot create builds in the Assets folder


That never happens, I only get to select a folder after clicking Build and then there is no opportunity to assign a file name.  
I end up with this (at the same level as Assets folder)

![image](https://user-images.githubusercontent.com/25189545/230011500-8114caa7-4a87-4e2d-937e-dad8ef072724.png)

**Comment by nyck33** [comment]
I try to use the name of the subfolder to which I built as env_name and get
```
(mlagents) nyck33@NyckLenovoIdeapad3:/mnt/c/Users/nobut/Documents/gameAI/ml-agents-rereleasrrrelease_18_branch/ml-agents-release_18_branch/Project$ mlagents-learn /mnt/c/Users/nobut/Documents/game
AI/ml-agents-release_18_branch/ml-agents-release_18_branch/config/ppo/3DBall.yaml --env=3DBallBuild --run-id=firstRunExec --resume


                        ▄▄▄▓▓▓▓
                   ╓▓▓▓▓▓▓█▓▓▓▓▓
              ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
            ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
          ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
        ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
        ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
          ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
            '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
               ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
                   `▀█▓▓▓▓▓▓▓▓▓▌
                        ¬`▀▀▀█▓


 Version information:
  ml-agents: 0.27.0,
  ml-agents-envs: 0.27.0,
  Communicator API: 1.5.0,
  PyTorch: 1.8.1+cu102
[INFO] Learning was interrupted. Please wait while the graph is generated.
Traceback (most recent call last):
  File "/home/nyck33/miniconda3/envs/mlagents/bin/mlagents-learn", line 8, in <module>
    sys.exit(main())
  File "/home/nyck33/miniconda3/envs/mlagents/lib/python3.7/site-packages/mlagents/trainers/learn.py", line 250, in main
    run_cli(parse_command_line())
  File "/home/nyck33/miniconda3/envs/mlagents/lib/python3.7/site-packages/mlagents/trainers/learn.py", line 246, in run_cli
    run_training(run_seed, options)
  File "/home/nyck33/miniconda3/envs/mlagents/lib/python3.7/site-packages/mlagents/trainers/learn.py", line 125, in run_training
    tc.start_learning(env_manager)
  File "/home/nyck33/miniconda3/envs/mlagents/lib/python3.7/site-packages/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/home/nyck33/miniconda3/envs/mlagents/lib/python3.7/site-packages/mlagents/trainers/trainer_controller.py", line 198, in start_learning
    raise ex
  File "/home/nyck33/miniconda3/envs/mlagents/lib/python3.7/site-packages/mlagents/trainers/trainer_controller.py", line 173, in start_learning
    self._reset_env(env_manager)
  File "/home/nyck33/miniconda3/envs/mlagents/lib/python3.7/site-packages/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/home/nyck33/miniconda3/envs/mlagents/lib/python3.7/site-packages/mlagents/trainers/trainer_controller.py", line 105, in _reset_env
    env_manager.reset(config=new_config)
  File "/home/nyck33/miniconda3/envs/mlagents/lib/python3.7/site-packages/mlagents/trainers/env_manager.py", line 68, in reset
    self.first_step_infos = self._reset_env(config)
  File "/home/nyck33/miniconda3/envs/mlagents/lib/python3.7/site-packages/mlagents/trainers/subprocess_env_manager.py", line 333, in _reset_env
    ew.previous_step = EnvironmentStep(ew.recv().payload, ew.worker_id, {}, {})
  File "/home/nyck33/miniconda3/envs/mlagents/lib/python3.7/site-packages/mlagents/trainers/subprocess_env_manager.py", line 98, in recv
    raise env_exception
mlagents_envs.exception.UnityEnvironmentException: Couldn't launch the 3DBallBuild environment. Provided filename does not match any environments.
```

**Comment by nyck33** [comment]
Then you contradict yourself

For example, if you are training with a 3DBall executable, and you saved it to the directory where you installed the ML-Agents Toolkit, run:

mlagents-learn config/ppo/3DBall.yaml --env=3DBall --run-id=firstRun

So I am using the folder name or the name of the executable????

As you can see, my executable is called UnityEnvironment it looks like, exactly the same for every ****ing build I do.

**Comment by nyck33** [comment]
So another document says use the full path but it's still not working: 
```
mlagents_envs.exception.UnityEnvironmentException: Couldn't launch the /mnt/c/nobut/Documents/gameAI/ml-agents-release_18_branch/ml-agents-release_18_branch/Project/MLAgentsBuilds/3DBall2/3DBall environment. Provided filename does not match any environments.
```
Why don't you say that everywhere?  Also give an example with pictures.  Or make a video.

**Comment by elliottower** [comment]
I’m not a maintainer of this repository but if you want help with something it’s probably not the best idea to be rude and make issues like this. If you have specific changes to documentation which you think would be helpful for other users you can spend the time you spent making this instead making a pull request.

**Comment by nyck33** [comment]
Hey I apologize my tone but it's incredibly frustrating that I can't even follow your suggestion if I can't decipher what is there to at least get it working one time.  It's beyond the level of making contributions which is really sad since Unity has alot going for it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by miguelalonsojr** [comment]
I understand your frustration and would love to help. We'd be happy to accept a contribution that improves our documentation and makes it easier to follow. Our code of conduct for the community (https://github.com/Unity-Technologies/ml-agents/blob/develop/CODE_OF_CONDUCT.md) helps keep everyone engaged in a positive manner. I'd recommend posting questions about how to use ML-Agents to our forums: https://forum.unity.com/forums/ml-agents.453/ Our github issues are for bugs and feature requests.
