### ISSUE TITLE
Multiple Example Scenes are now broken with updates and need to be updated.

### ISSUE THREAD

**Issue by RyushoYosei** [Unity-Technologies/ml-agents#5905]
**Describe the bug**

**To Reproduce**
1. Download the Github, 
2. Look at the console or try to open some scenes such as Walker
3. See errors and how some literally do not function because the setup of the neural network and other things are wrong.

LAtest ML Agents, 
Unity 2021.3.22f1

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by miguelalonsojr** [comment]
I'm unable to reproduce this issue. If you are using the latest version of ml-agents from github on the develop branch, you should install ml-agents-envs and ml-agents from the repo, not from pypi. If you're using ml-agents from pypi, you should make sure that you're using the example environments on the correct release branch. The latest release that was published to pypi is release 20: https://github.com/Unity-Technologies/ml-agents/releases/tag/release_20
