### ISSUE TITLE
gym complains about `Box bound precision lowered by casting to float32`

### ISSUE THREAD

**Issue by xixiha5230** [Unity-Technologies/ml-agents#5906]
**Describe the bug**

gym complains about `Box bound precision lowered by casting to float32`

**To Reproduce**

use `UnityToGymWrapper` then gym start warning

**Solution**

This is because this line of code：

[high = np.array([1] * self.group_spec.action_spec.continuous_size)](https://github.com/Unity-Technologies/ml-agents/blob/develop/ml-agents-envs/mlagents_envs/envs/unity_gym_env.py#L126) 

Because the default type is np.int, it needs to be changed to np.float32

`high = np.array([1.] * self.group_spec.action_spec.continuous_size, dtype=np.float32)`

**Comment by miguelalonsojr** [comment]
Please resubmit your bug report using our template. This will allow us to try to reproduce the error.
