### ISSUE TITLE
Other windows in Windows 11 start shaking uncontrollably while training and then Editor crashes

### ISSUE THREAD

**Issue by nyck33** [Unity-Technologies/ml-agents#5907]
Then I try to click on Editor and get

![image](https://user-images.githubusercontent.com/25189545/232266703-41fe3328-d1aa-4762-ba01-13e07a20ea28.png)

This was shaking uncontrollably.  

ie. I was working on my laptop while training and then my other window started shaking uncontrollably.  Then the Unity Editor was unresponsive and then I got the above instead of the Editor when I clicked on the Editor.

What's up?

**Comment by miguelalonsojr** [comment]
Please resubmit your bug report using our template https://github.com/Unity-Technologies/ml-agents/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md. This will allow us to try to reproduce the error. Also, We are unable to help reproduce bugs with custom environments. Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.
