### ISSUE TITLE
unable to train the agents. everytime i try i get this error: RuntimeError: Could not infer dtype of numpy.int32

### ISSUE THREAD

**Issue by starship17** [Unity-Technologies/ml-agents#5923]
i have no idea how to fix it and why it is happening. if you need further context then tell me.

**Comment by DragoRyu2001** [comment]
Hi, I also had this same issue. The solution which worked for me was by upgrading the numpy version to 1.22.0
The upgradation will give you an incompatibility error saying "mlagents-envs requires numpy==1.21.2", which you can just ignore.

**Comment by glpcc** [comment]
Hi, i get the same sort of error (numpy.float32 instead of int32) and upgrading to version 1.22.0 didnt work for me

**Comment by miguelalonsojr** [comment]
We are unable to help reproduce bugs with custom environments. Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue. Also, please fill out our bug report template: https://github.com/Unity-Technologies/ml-agents/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md
