### ISSUE TITLE
Entropy exploded when using SAC training

### ISSUE THREAD

**Issue by capoatguitar** [Unity-Technologies/ml-agents#5928]
MLAgent uses the SAC algorithm to train my project,  the entropy will quickly explode after a period of time,  then the reward will quickly drop to 0 or even a negative number, and then it will never get up again, everything is messed up. 
After a while, there will be an infinite or non number in the value loss and it will crash.
I tried changing the parameters and the problem persists, but I don't have any problems with PPO.
How to solve it?
Thanks!

**Screenshots**
![A54F5D40-9B72-49DA-AA6C-3159A23CDBED](https://github.com/Unity-Technologies/ml-agents/assets/136043571/dc1e92a5-0423-441b-a532-36a95ce4c445)

![D8DB1973-6941-41C5-9F05-FB0ECF3F8C1D](https://github.com/Unity-Technologies/ml-agents/assets/136043571/f3d4a37e-53ea-418d-a26e-6cb3b25de160)
![FFB5AD5F-226A-4608-A7C5-4B18073B484C](https://github.com/Unity-Technologies/ml-agents/assets/136043571/8900f90e-ff93-4c56-988c-8265a41da336)
![D75E587D-16C4-4CC5-B928-35C3698A9973](https://github.com/Unity-Technologies/ml-agents/assets/136043571/16ea6fdc-7a1d-4714-b124-fc928875e65a)

- Unity Version: Unity 2021.3.16f1]
- OS + version: Windows 10
- ml-agents: 0.28.0,
- ml-agents-envs: 0.28.0,
- Communicator API: 1.5.0,
- PyTorch: 1.7.1+cu110

**Comment by miguelalonsojr** [comment]
Please update to the latest version of ml-agents available on the develop branch of the repo. You're running on a very old version.
