### ISSUE TITLE
EndEpisode seams very slow on release 20 : total time of learning x5 comparing to release 19

### ISSUE THREAD

**Issue by ucacaxm** [Unity-Technologies/ml-agents#5932]
Hi,

**Describe the bug**
With the same env, release 19 is 5 time faster than release 20.
Release 20 get faster again if I comment the call to EndEpisode.
I cannot test with classical env since they do not call EndEpisode.

With the walkerAgent I do not have this performance between 19 and 20, 
but there is any call to EndEpisode in it.

**To Reproduce**
1. Install the release 19
2. Install the release 20
3. Find an env with several calls to EndEpisode
4. Compare the benchmark and the result

**Console logs / stack traces**

I did several tests with different versions of pytorch, also on CPU or GPU. It is always the same.

`
 Version information:

This is an example on CPU with 
num_envs: 12
num_areas: 512

* Release 19 (with calls to EndEpisode)
  ml-agents: 0.28.0,
  ml-agents-envs: 0.28.0,
  Communicator API: 1.5.0,
  PyTorch: 1.7.1+cu110
[INFO] Snow2L. Step: 50000. Time Elapsed: 27.736 s. Mean Reward: 10.653. Std of Reward: 10.544. Training.
[INFO] Snow2L. Step: 100000. Time Elapsed: 47.986 s. Mean Reward: 12.969. Std of Reward: 11.528. Training.
[INFO] Snow2L. Step: 150000. Time Elapsed: 69.152 s. Mean Reward: 13.370. Std of Reward: 11.415. Training.
[INFO] Snow2L. Step: 200000. Time Elapsed: 92.221 s. Mean Reward: 13.536. Std of Reward: 11.486. Training.
[INFO] Snow2L. Step: 250000. Time Elapsed: 112.348 s. Mean Reward: 13.585. Std of Reward: 11.489. Training.
[INFO] Snow2L. Step: 300000. Time Elapsed: 132.775 s. Mean Reward: 13.204. Std of Reward: 11.374. Training.
[INFO] Snow2L. Step: 350000. Time Elapsed: 152.801 s. Mean Reward: 13.183. Std of Reward: 11.394. Training.
[INFO] Snow2L. Step: 400000. Time Elapsed: 172.831 s. Mean Reward: 13.299. Std of Reward: 11.385. Training.

* Release 20 (with calls to EndEpisode)
  ml-agents: 0.30.0,
  ml-agents-envs: 0.30.0,
  Communicator API: 1.5.0,
  PyTorch: 1.8.0+cu111
[INFO] Snow2L. Step: 50000. Time Elapsed: 129.110 s. Mean Reward: 0.144. Std of Reward: 1.586. Training.
[INFO] Snow2L. Step: 100000. Time Elapsed: 207.920 s. Mean Reward: 0.329. Std of Reward: 2.752. Training.
[INFO] Snow2L. Step: 150000. Time Elapsed: 267.558 s. Mean Reward: 0.306. Std of Reward: 2.642. Training.
[INFO] Snow2L. Step: 200000. Time Elapsed: 327.412 s. Mean Reward: 0.307. Std of Reward: 2.636. Training.
[INFO] Snow2L. Step: 250000. Time Elapsed: 389.515 s. Mean Reward: 0.306. Std of Reward: 2.631. Training.
[INFO] Snow2L. Step: 300000. Time Elapsed: 452.282 s. Mean Reward: 0.305. Std of Reward: 2.637. Training.

The reward is also very different... which is strange also ...
The WalkerAgent trains similarly between 19 and 20. The difference between my code and the WalkerAgent is the many
calls to EndEpisode.

* Release 20 **by commenting EndEpisode: **
 Version information:
  ml-agents: 0.30.0,
  ml-agents-envs: 0.30.0,
  Communicator API: 1.5.0,
  PyTorch: 1.8.0+cu111
[INFO] Snow2L. Step: 50000. Time Elapsed: 66.539 s. Mean Reward: -40.264. Std of Reward: 11.260. Training.
[INFO] Snow2L. Step: 100000. Time Elapsed: 86.138 s. Mean Reward: -47.031. Std of Reward: 12.504. Training.
[INFO] Snow2L. Step: 150000. Time Elapsed: 101.245 s. Mean Reward: -51.682. Std of Reward: 14.352. Training.
[INFO] Snow2L. Step: 200000. Time Elapsed: 110.404 s. Mean Reward: -56.967. Std of Reward: 14.774. Training.
[INFO] Snow2L. Step: 250000. Time Elapsed: 119.076 s. Mean Reward: -62.821. Std of Reward: 17.106. Training.
[INFO] Snow2L. Step: 300000. Time Elapsed: 128.747 s. Mean Reward: -64.959. Std of Reward: 20.889. Training.

The reward is different since very negative reward causes an EndEpisode in my regular code.

In the migration page there is nothing special from 19 to 20:
https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/Migrating.md

Is there something new with EndEpisode in the release 20 ?
Has anyone experienced a similar bug between release 19 and release 20 ?

Thank you ...

**Environment (please complete the following information):**
- Unity Version: [e.g. Unity 2022.3.1f1
- Windows 11
- _ML-Agents version_: 19 and 20
- _Torch version_: 1.8.0
- _Environment_:  my own, sorry since it is related to EndEpisode

**Comment by miguelalonsojr** [comment]
Please update to the latest version of ML-Agents available on the develop branch of this repo.
