### ISSUE TITLE
Extending Imitation Learning model catalog with SQIL

### ISSUE THREAD

**Issue by stkovacevic94** [Unity-Technologies/ml-agents#5936]
**Is your feature request related to a problem? Please describe.**
BC algorithm can fall victim to covariate shifts. GAIL algorithm relies on min/max optimization and suffers from stability issues, and is harder to deploy.

**Describe the solution you'd like**
Implementing SQIL algorithm https://arxiv.org/pdf/1905.11108.pdf.

**Describe alternatives you've considered**
I have reviewed few offline RL algorithms, but nice thing about SQIL is that it is basically form of regularized BC that eliminates covariate shift problem. Also, its not hard to implement, and have better convergence properties than GAIL.

**Additional context**

**Comment by stkovacevic94** [comment]
I'm interesting in implementing this myself, with medium guidance and help from community (mainly to get onboarded, and some pointers in the code where i can add this) since i'm new to Unity ML Agents (but not IL and RL itself).

**Comment by Taikatou** [comment]
I really like this feature and inclusion and think it would be beneficial
