### ISSUE TITLE
.Net framework incompatible

### ISSUE THREAD

**Issue by Aarsh-Singh-Vishen** [Unity-Technologies/ml-agents#594]
"Warning:The primary reference "TensorFlowSharp" could not be resolved because it was built against the ".NETFramework,Version=v4.6.1" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6".	Assembly-CSharp "
How do I resolve this error?
How do I downgrade to .Net 4.6?
Thanks!

**Comment by entropia666** [comment]
I have the same issue after upgrading Tensorflow. Did you solve the issue?

**Comment by vincentpierre** [comment]
@Aarsh-Singh-Vishen I have never seen this error. Did you get the TensorflowSharp plugin from [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-TensorFlow-Sharp-in-Unity.md#requirements) ? Where do you this this error ? In Visual Studio or in the Unity Console? Is it a warning or an error ? Thank you,

**Comment by Aarsh-Singh-Vishen** [comment]
Well I'm guessing its because I have .net framework 4.7 installed. But there is no way to go back to .net 4.6.... so what should I do?

**Comment by Aarsh-Singh-Vishen** [comment]
Also yes I installed the TensorFlow plug in from the specified source.

**Comment by vincentpierre** [comment]
I think you have the same issue as #552 Can you confirm that? Unity can only use .NET 4.6, it does not have 4.7.

**Comment by Aarsh-Singh-Vishen** [comment]
Yup! Its the same issue.

**Comment by vincentpierre** [comment]
Let's continue the conversation there.
