### ISSUE TITLE
Multiple python versions recommended 

### ISSUE THREAD

**Issue by plop91** [Unity-Technologies/ml-agents#5944]
**Is your feature request related to a problem? Please describe.**
The documentation suggests two different python versions, "3.8.13 or higher" and "3.7.2 or higher"

**Describe the solution you'd like**
I would like there to see a single version recommended for download

**Comment by Draco18s** [comment]
I can confirm that the version downloadable with Unity's package manager (release 16?) works on Python 3.8.10 and that going too much newer than that won't work (3.8.13 is ok I think, but 3.9 is not).

**Comment by kodaxmax** [comment]
3.9.17 has been working for me so far. though i also had to change pytorch and protobuf versions. Of all the install instructions ive tested including the hummingbird, codmonkey and official guides : https://www.youtube.com/watch?v=RANRz9oyzko is the only one that was correct and working as of time of writing (3/8/23).
