### ISSUE TITLE
Stacking visual observations efficiently

### ISSUE THREAD

**Issue by gerardsimons** [Unity-Technologies/ml-agents#595]
Hi there,

I made an agent that has only a single visual observation, but it is very important that I stack these observations so it can deduce velocity. I understood the stacking algorithm does this for the vector space, but how do I do it for observations? 

There is an additional catch in that you do not usually want to pass all these pixel values directly into the hidden layers, but rather first through the convolutional layers. Is there anywhere where this is being done (possibly in a development branch) or do you have any pointers on doing this? 

A naive approach I was thinking of was storing the last observation and concatenating it with the current one and passing them as a single image to the network (I would have to override the get texture from camera for this).

PS: An RNN / LSTM would be overkill for this, as it is not long-term memory I am looking for.

**Comment by xiaomaogy** [comment]
@gerardsimons All the pixel values is passed to the python side then fed into a CNN encoder, which you can find in python/unitytrainer/models.py:116. 

@awjuliani Do we have visual observation stacking supported?

**Comment by awjuliani** [comment]
Hi @gerardsimons,

There is currently an open PR for this: https://github.com/Unity-Technologies/ml-agents/pull/955. Please let us know if it meets your needs.

**Comment by gerardsimons** [comment]
@awjuliani : Yep seems like it's exactly what I want, thanks for letting me know!
