### ISSUE TITLE
RuntimeError and module installation issue with maj/ase-walker branch

### ISSUE THREAD

**Issue by Aura-O** [Unity-Technologies/ml-agents#5959]
Describe the bug
During the training process with the maj/ase-walker branch of ML-Agents, I encountered a RuntimeError related to incompatible matrix shapes. This was followed by an error indicating that the onnx module is not installed, even though it is. However, there seems to be a conflict between the protobuf version required by onnx and the protobuf version required by mlagents-envs and mlagents.

To Reproduce

1. Git clone the maj/ase-walker branch of the ML-Agents repository.
2. Install using pip install -e .
3. Open the project in the Unity Editor.
4. Open the Example Walker Scene.
5. Set up the config file with the path to the demos.
6. Attempt training.
7. Encounter RuntimeError related to incompatible matrix shapes.
8. Encounter OnnxExporterError indicating that the onnx module is not installed.

**Console logs / stack traces**
Please wrap in triple backticks (```) to make it easier to read.

'''File "C:\Users\jb-ai\Projects\maj\ase-walker\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "C:\Users\jb-ai\Projects\maj\ase-walker\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\jb-ai\Projects\maj\ase-walker\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (22x256 and 1024x1)
'''
'''File "C:\Users\jb-ai\Projects\maj\ase-walker\lib\site-packages\torch\onnx\utils.py", line 1620, in _export
    proto = onnx_proto_utils._add_onnxscript_fn(
  File "C:\Users\jb-ai\Projects\maj\ase-walker\lib\site-packages\torch\onnx\_internal\onnx_proto_utils.py", line 221, in _add_onnxscript_fn
    raise errors.OnnxExporterError("Module onnx is not installed!") from e
torch.onnx.errors.OnnxExporterError: Module onnx is not installed!
'''
'''ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
onnx 1.14.0 requires protobuf>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
mlagents-envs 0.31.0.dev0 requires protobuf<3.20,>=3.6, but you have protobuf 3.20.0 which is incompatible.
mlagents 0.31.0.dev0 requires protobuf<3.20,>=3.6, but you have protobuf 3.20.0 which is incompatible.
'''

**Screenshots**
N/A

**Environment (please complete the following information):**
- Unity Version: 2021.3.11f1
- OS + Version: Windows 11
- ML-Agents version: 0.31.0.dev0
- Torch version: CUDA 11.7
- Environment: maj/ase-walker branch of the ML-Agents repo

Issue produced within Walker ASE example environment.

**Comment by miguelalonsojr** [comment]
This is a development branch for an unreleased feature. Closing.
