### ISSUE TITLE
CameraSensors. ObservationToTexture

### ISSUE THREAD

**Issue by ChengXIZhang666** [Unity-Technologies/ml-agents#5961]
**Describe the bug**
After integrating a CameraSensor to the robot model via the URDF importer, I faced an error during runtime: 'NullReferenceException: Object reference not set to an instance of an object' within Unity. The issue originates from Unity.MLAgents.Sensors.CameraSensors.ObservationToTexture(UnityEngine.Camera obsCamera, UnityEngine.Texture2D texture2D, System.Int32 width, System.Int32 height). It's important to note that I have already added a standard camera, [apk ](http://piikashowapk.com/)and all other properties remain at their default settings.

**Console logs / stack traces**
```
NullReferenceException: Object reference not set to an instance of an object
Unity.MLAgents.Sensors.CameraSensor.ObservationToTexture (UnityEngine.Camera obsCamera, UnityEngine.Texture2D texture2D, System.Int32 width, System.Int32 height) (at ./Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Sensors/CameraSensor.cs:158)
Unity.MLAgents.Sensors.CameraSensor.GetCompressedObservation () (at ./Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Sensors/CameraSensor.cs:92)
Unity.MLAgents.Policies.HeuristicPolicy.StepSensors (System.Collections.Generic.List`1[T] sensors) (at ./Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Policies/HeuristicPolicy.cs:137)
Unity.MLAgents.Policies.HeuristicPolicy.RequestDecision (Unity.MLAgents.AgentInfo info, System.Collections.Generic.List`1[T] sensors) (at ./Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Policies/HeuristicPolicy.cs:38)
Unity.MLAgents.Agent.SendInfoToBrain () (at ./Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Agent.cs:1099)
Unity.MLAgents.Agent.SendInfo () (at ./Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Agent.cs:1326)
Unity.MLAgents.Academy.EnvironmentStep () (at ./Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Academy.cs:573)
Unity.MLAgents.AcademyFixedUpdateStepper.FixedUpdate () (at ./Library/PackageCache/com.unity.ml-agents@2.0.1/Runtime/Academy.cs:43)
```

**Environment (please complete the following information):**
- Unity Version:Unity 2022.3f1
- OS + version:  Windows 11
- _ML-Agents version_:2.0.1

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by miguelalonsojr** [comment]
Please upgrade to the latest version of ML-Agents available on the develop branch of this repo and try again.

**Comment by ckirby19** [comment]
Could you please explain what the bug was here? I still get this issue even after installing ml-agents from the develop branch and using the package.json from this

**Comment by theorenstroud-tamu** [comment]
I am also running into this issue. Using Windows 10, Unity 6000.2.4f1, and ML-Agents 4.0.3. It was actually working just fine for me until the latest Windows 10 update in June 2026, but I'm not sure if that was what specifically caused it. Has there been a way to fix this?
