### ISSUE TITLE
[Bug] Demo files have cyclic imports at runtime, preventing recording of demos

### ISSUE THREAD

**Issue by Draco18s** [Unity-Technologies/ml-agents#5965]
When recording demo files, the editor attempts to import the demo more than once at runtime.

**To Reproduce**
1. Set up a scene to record a demonstration (from an existing agent model in inference mode)
2. Run the scene and record a demonstration
3. Wait about 2-3 minutes

**Console logs / stack traces**
> An infinite import loop has been detected. The following Assets were imported multiple times, but no changes to them have been detected. Please check if any custom code is trying to import them:
Assets/Demos/test.demo(modified date 2023-08-16T21:11:03.931104Z)

**Environment (please complete the following information):**
- Unity Version: e.g. Unity 2020.1f1
- OS + version: Windows 10
- _ML-Agents version_: ML-Agents v0.26.0
- _Torch version_: n/a
- _Environment_: Python 3.9.13, Command Prompt

**Comment by miguelalonsojr** [comment]
Please upgrade to the latest version of ML-Agents available on the develop branch of this repo and try again.
