### ISSUE TITLE
D3D11 Swapchain Unrecoverable Error

### ISSUE THREAD

**Issue by Draco18s** [Unity-Technologies/ml-agents#5966]
**Describe the bug**
![image](https://github.com/Unity-Technologies/ml-agents/assets/1750680/6cb3be4b-e965-4b54-abef-ea876acc4dd8)
AFAICT this is due to having training active while running another GPU-heavy task (in this case, it was Deep Rock Galactic) though it has occurred only twice and it isn't an immediate thing.

As Unity crashes to desktop, this can result in a loss of work.

**To Reproduce**
1. Unsure

**Environment (please complete the following information):**
- Unity Version: e.g. Unity 2020.1f1
- OS + version: Windows 10
- _ML-Agents version_: ML-Agents v0.26.0
- _Torch version_: n/a
- _Environment_: Python 3.9.13, Command Prompt

**Comment by miguelalonsojr** [comment]
This is likely not due to ML-Agents, but to running Unity with other workloads: https://forum.unity.com/threads/constant-crashes-failed-to-present-d3d11-swapchain-due-to-device-removed.987834/
