### ISSUE TITLE
Documentation inconsistency

### ISSUE THREAD

**Issue by okunamayanad** [Unity-Technologies/ml-agents#5967]
In `docs/Installation.md` It states both, Python version 3.8.13 and 3.7.2 is the minimum version of Python.

**To Reproduce**
1. Go to [docs/Installation.md](https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/Installation.md)
2. Look for "Consequently, to install and use the ML-Agents Toolkit you will need to:"
3. Scroll down to "Install Python (3.8.13 or higher)"
4. Then scroll down to "Install Python 3.7.2 or Higher"
5. See the error.

**Screenshots**
![image](https://github.com/Unity-Technologies/ml-agents/assets/108594296/510ebfd2-63ae-43f0-9574-a11a9adead23)

**Comment by miguelalonsojr** [comment]
This has been fixed on develop. Closing.
