### ISSUE TITLE
Inference performance worse than training performance

### ISSUE THREAD

**Issue by Thorce0** [Unity-Technologies/ml-agents#5969]
**Describe the bug**
The runtime performance is about 5-10 times better when my agent is training compared to when it is running in inference. 
This totally kills self play training performance.
(I am running ~100 agents in my scene)

**To Reproduce**
1. Look at performance when training
2. Look at performance when running inference
3. Compare

**Console logs / stack traces**
Please wrap in triple backticks (```) to make it easier to read.

**Environment (please complete the following information):**
- Unity Version: Unity 2022.2.19
- OS + version: Windows 11
- _ML-Agents version_: latest
- _Torch version_:  1.8.0 + cu111
- _Environment_: my own

**Comment by miguelalonsojr** [comment]
Please upgrade to the latest version of ML-Agents available on the develop branch of this repo and try again.
