### ISSUE TITLE
Error when running ML-Agents `RuntimeError: torch.cat(): expected a non-empty list of Tensors`

### ISSUE THREAD

**Issue by yamachann1647** [Unity-Technologies/ml-agents#5971]
Hello.
When I run ML-agents, I get the following error message:
**Describe the bug**
`File "c:\~~\downloads\ml-agents-release_20 (1)\ml-agents-release_20\ml-agents\mlagents\trainers\torch_entities\action_model.py", line 146, in _get_probs_and_entropy
    entropies = torch.cat(entropies_list, dim=1)
RuntimeError: torch.cat(): expected a non-empty list of Tensors`

**Environment**
- Unity Version: Unity 2022.3.7f1
- OS + version: Windows 11
- ml-agents: 0.30.0
- ml-agents-envs: 0.30.0
- Communicator API: 1.5.0 
- PyTorch: 2.0.1

Does anyone know how to solve this problem?

**Comment by miguelalonsojr** [comment]
Please upgrade to the latest version of ML-Agents available on the develop branch of this repo and try again. Also, as @JvanderKaaij noted, runtime instantiation of ML-Agents components is tricky if not done properly and can lead to instability. It's not recommended.
