### ISSUE TITLE
Huggingface integration in branch release_20

### ISSUE THREAD

**Issue by Lewy09-Tm25** [Unity-Technologies/ml-agents#5972]
Hi!
I am currently performing the hands-on exercise of the Deep-RL course on HuggingFace. Link:- https://huggingface.co/learn/deep-rl-course/unit7/hands-on. 
The installation process takes us from installing the toolkit to pushing the model to the Huggingface hub. However, I am facing this error while pushing the trained model.

```
mlagents-push-to-hf : The term 'mlagents-push-to-hf' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At line:1 char:1
+ mlagents-push-to-hf  --run-id="SoccerTwos" --local-dir=".\results\Soc ...
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (mlagents-push-to-hf:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

According to the documentation https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/Installation.md the recommended branch is release_20, because the main branch is quite unstable. 

So is it possible to add the feature of pushing and loading models from huggingface hub to the branch release_20? Like it is in the develop branch. Also if the develop branch is in fact the most stable one currently and not release_20, then wouldn't it be advisable to update the documentation?

**Comment by miguelalonsojr** [comment]
No. The HF integration is already on develop. It will be available in our official next release.
