### ISSUE TITLE
UnitySDK is missing, docs need update

### ISSUE THREAD

**Issue by Voyz** [Unity-Technologies/ml-agents#5975]
**Describe the bug**

All throughout the documentation the UnitySDK folder is being referenced. That folder doesn't exist anymore, and has been broken down in:

[[0.14.0-preview] - 2020-02-13](https://github.com/Unity-Technologies/ml-agents/blob/8bcedabd808ffb7097f88b800fc92dea82dfd610/com.unity.ml-agents/CHANGELOG.md?plain=1#L871)

> - UnitySDK folder was split into a Unity Package (com.unity.ml-agents) and our
  examples were moved to the Project folder (#3267)

This should be reflected in the documentation.

**Comment by miguelalonsojr** [comment]
You're looking at old documentation. Please use our current webdocs: https://unity-technologies.github.io/ml-agents/.
