### ISSUE TITLE
IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by wpss929** [Unity-Technologies/ml-agents#5977]
Yesterday I wrote a piece of code to get mlagents training and it ran successfully. But today when I tried to restart the training, I got this error:

![屏幕截图 2023-09-25 124052](https://github.com/Unity-Technologies/ml-agents/assets/51666751/3fe4f874-6100-430d-9117-7e293e1ba05f)

It looks like some sort of array out of bounds, so the first thing I checked was the number of observation vector space size and action branches and size in the Behavior Parameters and in the code, and it looks equal:

![image](https://github.com/Unity-Technologies/ml-agents/assets/51666751/4663dd91-08e8-4223-9db9-2c93f3bc82a0)

![image](https://github.com/Unity-Technologies/ml-agents/assets/51666751/b3e68d2e-4b47-4383-8182-62cdebe2e465)

![image](https://github.com/Unity-Technologies/ml-agents/assets/51666751/883644e4-b5bb-4c78-b6f5-dd38e5fbeef4)

![image](https://github.com/Unity-Technologies/ml-agents/assets/51666751/f1b08d81-df7f-49ff-aa8a-6b9e0284d31f)

I'm confused, what should I do about this problem?

**Comment by wpss929** [comment]
By the way, I also tried restarting the program and restarting the training, but neither solved the problem :(

**Comment by miguelalonsojr** [comment]
Please update to the latest version of ML-Agents available on the develop branch of this repo and try again.
