### ISSUE TITLE
gym -> gymnasium

### ISSUE THREAD

**Issue by desaibhargav** [Unity-Technologies/ml-agents#5995]
**Is your feature request related to a problem? Please describe.**
This feature request is not related to a problem as such. I imagine everything works fine with gym. However, gym is no longer maintained and has been handed over to the Farama Foundation for future development (now called gymnasium), see [here](https://farama.org/Announcing-The-Farama-Foundation).

**Describe the solution you'd like**
Add support for gymnasium with mlagents-envs

Side note:
I really appreciate the bug fixes, refactors, version bumps (especially torch) and all the work done in between to bring v1.0.0 of the codebase. Thank you for all your efforts, great job!

**Comment by wcy1231** [comment]
Good! The same question gym -> gymnasium.

**Comment by adrienJeg** [comment]
Hello, is there any news on this ?

**Comment by miguelalonsojr** [comment]
Nothing planned for now. MLA is in maintenance mode for now. Minor bug fixes, dependency updates, minor features. We are, however, accepting PRs, so if anyone from the community would like to make this upgrade and submit a PR, that would be amazing.
