### ISSUE TITLE
cant understand some docs

### ISSUE THREAD

**Issue by cuihee** [Unity-Technologies/ml-agents#6]
https://github.com/Unity-Technologies/ml-agents/wiki/Getting-Started-with-Balance-Ball#testing-python-api

I follow the doc's step and get here:
I can get "http://localhost:8888/tree" successfully
BUT i dont know how to next or understand what the doc says.
(English is not my mother tongue)

**Comment by AntonShumin** [comment]
I have the same problem (i think)

I've loaded up the` /tree` folder. Inside i can see the `Basics.ipynb`

![image](https://user-images.githubusercontent.com/5438507/30669587-2de68d2c-9e5f-11e7-96a3-4f60d40fd32c.png)

`import matplotlib.pyplot as plt` where do i write those commands?

**Comment by awjuliani** [comment]
The AttributeError should be addressed in master, see https://github.com/Unity-Technologies/ml-agents/issues/5.

**Comment by vincentpierre** [comment]
If you are confused about how to use jupyter once launched, here is a link that explains how to run the notebook:
https://jupyter-notebook-beginner-guide.readthedocs.io/en/latest/execute.html
You can run the cells inside the browser by pressing `shift` + `enter`

**Comment by romerocesar** [comment]
Thanks for trying it out! I added a link to the jupyter quick start guide from the getting started wiki. Feel free to reopen if you feel your issue hasn't been addressed
