### ISSUE TITLE
Inquiry About ML-Agents Support for Unity DOTS and Updates on ml-agents-dots.

### ISSUE THREAD

**Issue by hanxiaoxin778** [Unity-Technologies/ml-agents#6000]
Hello,

I've noticed that DOTS (Data-Oriented Technology Stack) has matured considerably within Unity and offers the potential for significant performance improvements. However, I also observed that the `ml-agents-dots` repository hasn't been updated for quite some time.

I'm curious to know if there are plans to update `ml-agents-dots`, or if the ML-Agents team has other plans for comprehensive DOTS support or optimization?

Any information would be greatly appreciated.

**Comment by miguelalonsojr** [comment]
Unfortunately, there are currently no plans for DOTS support or other optimizations.
