### ISSUE TITLE
Error Installing mlagents: "fatal: not a git repository (or any of the parent directories): .git"

### ISSUE THREAD

**Issue by domrice** [Unity-Technologies/ml-agents#6001]
**Describe the bug**
When installing mlagents, I always get this error: "fatal: not a git repository (or any of the parent directories): .git"
It appears when installing from the cloned repo but also when installing from pip. However, installing the mlagents-env worked without any issues. 

**To Reproduce**
1.1 python -m pip install mlagents==1.0.0
1.2 python -m pip install ./ml-agents
2. See error

**Console logs / stack traces**
```
Collecting onnx==1.12.0 (from mlagents==1.0.0)
  Using cached onnx-1.12.0.tar.gz (10.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/v9/r5c9qrvd6xlfnm_f27203c200000gn/T/pip-install-epowd4j0/onnx_74aaa8e6c57a4c8ea0f19f0cf84f4542/setup.py", line 81, in <module>
          assert CMAKE, "Could not find cmake executable!"
      AssertionError: Could not find cmake executable!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Screenshots**
<img width="890" alt="Screenshot 2023-10-23 at 13 27 09" src="https://github.com/Unity-Technologies/ml-agents/assets/58233897/8e86fc3b-4103-4bac-be3e-5da610e6d9ed">

**Environment (please complete the following information):**
- Unity Version: Unity 2022.3.11f1
- OS + version: macOS Sonoma 14.0
- _ML-Agents version_: latest
- _Torch version_: 2.1.0

**Comment by hitpp** [comment]
my solution:
numpy==1.23.5
ml-agents-envs \ setup.py -> numpy del

**Comment by domrice** [comment]
Solved it with a bit of trial and error. Installing CMAKE via Homebrew did the job (I guess)...
