### ISSUE TITLE
No project in Visual studio

### ISSUE THREAD

**Issue by Entretoize** [Unity-Technologies/ml-agents#6007]
In Unity when double clicking a script Visual Studio open the file but not in the project, then classes aren't recognized, project can't be debugged, intellisense isn't working.
In Unity preference, external tool is set to VS 2022 internal and there's no way to change, and there's no button to regenerate project files.

**To Reproduce**
1. Add the project to Unity
2. Open the prject
3. Double click a cs file attached to a game object
4. File is opened as a standalone file

**Environment (please complete the following information):**
- Unity Version: [e.g. Unity 2022.3.9f1]
- Windows 11

**Comment by Heidar-An** [comment]
This doesn't related to MLAgents but you can find some tips here: https://stackoverflow.com/questions/72340379/vs-code-doesnt-recognise-using-unityengine-as-a-valid-namespace-what-can-i-d

```
Delete all .csproj files on the project's root.

Then edit->preferences->external tools-> Regenerate project files.

On VSCode F1->Reload Window
```

If that doesn't work, try recreating another project and moving the files or perhaps you didn't install something in Unity properly.

**Comment by miguelalonsojr** [comment]
Unrelated to ml-agents. Closing.
