### ISSUE TITLE
Running multithreaded training with CUDA only works in a precarious way and should be better documented

### ISSUE THREAD

**Issue by AliBharwani** [Unity-Technologies/ml-agents#6009]
**Background** 
Unity ML-Agents allows an optional "threaded" argument that runs the training loop on a separate thread. It also allows training on CUDA kernels. Right now, enabling both options at once works for the provided algorithms, but it is in a very fragile situation.

PyTorch creates a new CUDA context for each thread. CUDA tensors cannot be shared between separate threads - they can only be shared via the PyTorch multiprocessing module. So you might think: "The trainer and its nn modules are being initialized in the main thread, how can the trainer thread access and update them?"

**Why does it work now?** 
Right now, the main thread does not allocate new CUDA tensors after starting the trainer thread. Since all the memory is in the same place, the trainer thread is able to work, though really this seems like undefined behavior. If you were to allocate new CUDA tensors in the main thread, PyTorch will shift its memory around behind the scenes, and what usually ends up happening is the trainer thread will start looking at a region of memory with all zeros for the weights. Then during the backward pass it will throw due to divide by zero errors or NaNs at various places in the output or optimizer.  

This is very easy to replicate. The main thread will call "evaluate" in TorchPolicy to gather actions that are sent to the environment(s). This function calls "get_action_and_stats" on the Actor class. If this function allocates any new CUDA tensors, the issue I mentioned above will occur and the training thread will break. 

**Solution**
The heavy lift solution is to change the threading implementation to use PyTorch's multiprocessing module instead. I've just completed this for my own project, which I plan to open source sometime next year. The main difficulty with this is that on Windows, new processes have their own memory, and can only be communicated with through Pipes. This requires rethinking some aspects of the codebase: the initialization of the modules on the training process; the way that the StatsReporter works (I ended up putting it on its own process); and the way model saving and loading works. 

For now, I suggest that this shortcoming should be mentioned in the docs for the "threaded" argument.

**Comment by miguelalonsojr** [comment]
Thanks for the detailed analysis. Can you submit a PR to add this note in the docs when using "threaded"?
