### ISSUE TITLE
Pytorch issue/outdated commands

### ISSUE THREAD

**Issue by marekkupa11** [Unity-Technologies/ml-agents#6011]
I have that command to install pytorch (in official installation docs)

pip3 install torch~=1.13.1 -f https://download.pytorch.org/whl/torch_stable.html 

and it showing this error 

ERROR: Could not find a version that satisfies the requirement torch~=1.13.1 (from versions: 2.0.0, 2.0.0+cpu, 2.0.0+cu117, 2.0.0+cu118, 2.0.1, 2.0.1+cpu, 2.0.1+cu117, 2.0.1+cu118, 2.1.0, 2.1.0+cpu, 2.1.0+cu118, 2.1.0+cu121) ERROR: No matching distribution found for torch~=1.13.1

Can I install version 2.0.0 or something like that to make it work properly?

**Comment by marekkupa11** [comment]
Or can you share me a YouTube video that tells how to download and setup mlagent, pytorch etc... but the newest version (realease) without this "pytorch issue" (that have a solution for this)

**Comment by nacorti** [comment]
What python version are you running?

**Comment by marekkupa11** [comment]
> What python version are you running?

3.11 because  in docs is "Install Python 3.10.12 or Higher" and 3.10.12 is not accesable (3.10.13 too): 

"No installers

According to the release calendar specified in [PEP 619](https://www.python.org/dev/peps/pep-0619/), Python 3.10 is now in the "security fixes only" stage of its life cycle: 3.10 branch only accepts security fixes and releases of those are made irregularly in source-only form until October 2026. Python 3.10 isn't receiving regular bug fixes anymore, and binary installers are no longer provided for it. Python 3.10.11 was the last full bugfix release of Python 3.10 with binary installers."

and I want to be near it to not cause any problems or sth

**Comment by mikehaojiang** [comment]
using conda and python 3.10.12 I managed to make it work with some minor modifications. Refer to: https://github.com/Unity-Technologies/ml-agents/issues/6016

**Comment by miguelalonsojr** [comment]
I'm working on an upgrade to pytorch 2.1.1 that should land soon on develop. It should fix this issue. Here's the upgrade branch: https://github.com/Unity-Technologies/ml-agents/tree/develop-pytorch-2

**Comment by marekkupa11** [comment]
Okay i will try it, thanks. If it will not work I will just wait for a more "official" upgrade, thanks for help.
