### ISSUE TITLE
TQC, REDQ, and DroQ

### ISSUE THREAD

**Issue by brandonki2023** [Unity-Technologies/ml-agents#6012]
Hi! First of all, thank you very much for this open-source, great-to-use, capable tool.

As you are probably well-aware, it seems to me that SAC is very useful but no longer state-of-the-art for certain applications. The claim is that [TQC](https://arxiv.org/abs/2005.04269) outperforms it on challenging locomotion tasks by reducing overestimation, [REDQ](https://arxiv.org/abs/2101.05982) is slow but more sample-efficient with high UTD, and [DroQ](https://arxiv.org/abs/2110.02034) combines the advantages of high UTD and few critics to create a computationally feasible, very sample-efficient method that is even applicable to [real-life robotics](https://www.roboticsproceedings.org/rss19/p056.pdf).

I couldn't find any request for the implementation of these improved methods so I'd like to ask if they are planned and/or in the works.

Improving sample efficiency while maintaining manageable computational demand seems to be a worthwhile goal in and of itself. But also for game development, highly sample-efficient methods could make feasible, for example, training intelligent opponents by having humans play against them for only a few hours.

I'm trying my hand at implementing TQC as it should only require few tweaks to the SAC trainer (namely the addition of the Huber loss function and the dropping of top quantiles), but it might take quite a while as I am still a learning developer. Much more capable developers may find the implementation of these methods a much more trivial task (comparatively).

**Comment by miguelalonsojr** [comment]
There are no plans to add any of these algorithms, but thank you for the suggestion. Feel free to submit a PR that adds these, as we are accepting community PRs.

**Comment by miguelalonsojr** [comment]
On second thought, I'll keep this open. I might noodle around some of these over the holidays.
