### ISSUE TITLE
Rigid Body Sensor Component not assigning root body properly

### ISSUE THREAD

**Issue by Wafeechan** [Unity-Technologies/ml-agents#6015]
**Describe the bug**
So basically I have tried to replicate the Crawler agent from the sample project example inside the ML Agents unity package, and instead tried to use it to a dog model instead. Everything seems fine so far, until I tried to assign the root body of the agent onto the Rigid body Sensor Component script which was from the ML Agent extension script. At first I thought it was just a problem on my part, but when I tried to do the same for the original crawler project, apparently it did the same. For this bug, I will just use the crawler example to be reproduced. It might be similar to the one in #5774

**To Reproduce**
1. Open up the project examples from the ML Agent projects.
2. There, choose the crawler from one of the many examples that are there. (ML-Agents > Examples > Crawler > Scenes > Crawler)
3. On the Hierarchy, open up one of the DynamicPlatform and choose CrawlerBase. Open up the CrawlerBase prefab.
4. On the inspector, scroll down until you reach the Rigid Body Sensor Component script, and remove it.
5. Then, add component Rigid Body Sensor Component and assign the Root Body. The Hierarchy will not assigned the joint root properly (leg and foreleg etc.).

**Console logs / stack traces**
```UnassignedReferenceException: The variable RootBody of RigidBodySensorComponent has not beed assigned.```
```You probably need to assign the RootBody variable of the RigidBodySensorComponent script in the inspector```
This is just probably because the variable wasn't assigned initially, and was just a spam of this error line inside the console

```NullReferenceException: Object reference not set to an instance of an object```
```Unity.ML.Agents.Extensions.Sensors.RigidBodyPoseExtractor.GetBodyPosesEnabled()(at D;/path_where_you_installed_ml-agents_folder/ml-agents-develop/com.unity.ml-agents.extensions/Runtime/Sensors/RigidBodyPoseExtractor.cs:169)```
This is the main error that I was concerned. Not too sure if its a bug or just something else that I don't know as I have only learnt using ML Agents for 5 months or so.

**Screenshots**
![image](https://github.com/Unity-Technologies/ml-agents/assets/104259934/2af9d0da-7dcf-4b07-b1ff-41a4e7262f01)
Supposedly the script should turn out like this.

![image](https://github.com/Unity-Technologies/ml-agents/assets/104259934/f2ca2aac-bfd5-4086-b443-977272d11e0f)
Instead it just initializes this, without the connected joints and such.
Do remember this bug was reproduced with the example crawler agent that was given, so reassigning the script and variables should make it that it will be assigned as if the original. Or at least that's what I would assume to be. At least it reduces my concerns that my project wasn't the main problem.

**Environment:**
- Unity Version: Unity 2022.3.9f1
- OS + version: Windows 10
- _ML-Agents version_: ML Agents 2.3.0-exp.4 & ML Agents Extensions 0.6.1-preview
- _Torch version_: torch version 1.7.1+cu110
- _Environment_: Crawler from the example ML Agent project

**NOTE:** We are unable to help reproduce bugs with custom environments.  Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

**Comment by miguelalonsojr** [comment]
Please see the note: We are unable to help reproduce bugs with custom environments. Please attempt to reproduce your issue with one of the example environments, or provide a minimal patch to one of the environments needed to reproduce the issue.

Please try to reproduce with one of the example environments.

**Comment by Wafeechan** [comment]
Im not sure if my understanding of example environment is wrong, but isn't the crawler one of the example environment? The bug is simply the rigid body sensor component not assigning the root body properly to the hierarchy.

So basically:
1. Just open up the crawler environment
2. Open up the CrawlerBase prefab
3. Remove the Rigid Body Sensor Component from the inspector
4.  Put a new rigid Body Sensor Component
5. Assign the root body with the body of the crawler
6. The hierarchy on the component won't assign the other connected joints (which is my current problem)

There's no other thing that I added to replicate this bug, maybe other than the fact that ML Agent Extension needed to be installed to the package manager also.

I hope maybe an explanation could be given on to why its behaving like that, or maybe just that my way is not the correct way to assign that component like that.

**Comment by miguelalonsojr** [comment]
Got it. I misunderstood and thought you were replicating crawler from scratch. This is a known bug with the Unity editor inspector component. If you close the scene and reopen it, the hierarchy should appear in the sensor.
