### ISSUE TITLE
Installation instructions issues for Release 21 [Windows]

### ISSUE THREAD

**Issue by mikehaojiang** [Unity-Technologies/ml-agents#6016]
Following instructions (https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/Installation.md) did not work for Windows 10 due to the following issues:

- conda create -n mlagents python=3.10 && conda activate mlagents --> This one should be the following instead: conda create -n mlagents python=3.10.**12** && conda activate mlagents 
- python -m pip install ./ml-agents-envs causes an error for numpy==1.21.2 (cannot build wheel). I had to change numpy==1.21.**3** in the ./ml-agents-envs/setup.py for it to work

**Comment by miguelalonsojr** [comment]
Fixed with https://github.com/Unity-Technologies/ml-agents/pull/6014
