### ISSUE TITLE
Images are missing in documentation

### ISSUE THREAD

**Issue by neilmendoza** [Unity-Technologies/ml-agents#6017]
**Describe the bug**
Images are missing in github.io rendering of documentation, markdown version is OK.

**To Reproduce**
Go to https://unity-technologies.github.io/ml-agents/Learning-Environment-Create-New/

**Screenshots**
![Screenshot 2023-11-22 at 10 26 43 AM](https://github.com/Unity-Technologies/ml-agents/assets/818571/26a6fb00-8945-47f8-97a4-e8a6d781a36a)

**Comment by miguelalonsojr** [comment]
The doc markdown files are made for our webdocs. Image links are coded for mkdocs. Have a look at the docs here: https://unity-technologies.github.io/ml-agents/

**Comment by neilmendoza** [comment]
On the page you just linked @miguelalonsojr, if you click on the "Toolkit Documentation" on the left and then "Making a New Learning Environment" in the center, you reach the page I linked to with broken images.

**Comment by miguelalonsojr** [comment]
Ah. I see it now. Thanks for pointing this out. Usually broken image link bugs are from folks using the docs directly on GH. Will reopen and fix.

**Comment by miguelalonsojr** [comment]
Fix: https://github.com/Unity-Technologies/ml-agents/pull/6024
