### ISSUE TITLE
Failed to build numpy - NumPy 1.21.2 may not yet support Python 3.10

### ISSUE THREAD

**Issue by Thomasphifer** [Unity-Technologies/ml-agents#6018]
I am trying to install ML Agents following these [instructions](https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/Installation.md#:~:text=python%20%2Dm%20pip%20install%20./ml%2Dagents%2Denvs)

```python -m pip install ./ml-agents-envs```

```Building wheel for numpy (pyproject.toml) ... error
error: subprocess-exited-with-error
× Building wheel for numpy (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [287 lines of output]
setup.py:63: RuntimeWarning: NumPy 1.21.2 may not yet support Python 3.10.
warnings.warn(
....
....
....
ils\ccompiler.py", line 88, in <lambda>
          m = lambda self, *args, **kw: func(self, *args, **kw)
      TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
Successfully built mlagents-envs
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
```

Possibly related to: https://github.com/Unity-Technologies/ml-agents/pull/5997

**Environment:**
- Unity Version:Unity 2022.3.13f1
- OS + version: Windows 11
- _ML-Agents version_: release_21
- _Torch version_: 1.13.1+cu117
- _Environment_: conda mlagents
- Python version: 3.10.12

**Comment by Thomasphifer** [comment]
Likely the setup file needs to have numpy bumped:

Before:
    install_requires=[
        "cloudpickle",
        "grpcio>=1.11.0,<=1.48.2",
        "Pillow>=4.2.1",
        "protobuf>=3.6,<3.20",
        "pyyaml>=3.1.0",
        "gym>=0.21.0",
        "pettingzoo==1.15.0",
        "numpy==1.21.2",
        "filelock>=3.4.0",
    ],

After:
    install_requires=[
        "cloudpickle",
        "grpcio>=1.11.0,<=1.48.2",
        "Pillow>=4.2.1",
        "protobuf>=3.6,<3.20",
        "pyyaml>=3.1.0",
        "gym>=0.21.0",
        "pettingzoo==1.15.0",
        **"numpy==1.24.0",**
        "filelock>=3.4.0",
    ],
    
    I did this and it seems to work so far...

**Comment by Thomasphifer** [comment]
Bumping the required version of numpy in the ml-agents\ml-agents-envs\setup file to 1.23.1 seems to have worked:

Before:
    install_requires=[
        "cloudpickle",
        "grpcio>=1.11.0,<=1.48.2",
        "Pillow>=4.2.1",
        "protobuf>=3.6,<3.20",
        "pyyaml>=3.1.0",
        "gym>=0.21.0",
        "pettingzoo==1.15.0",
        "numpy==1.21.2",
        "filelock>=3.4.0",
    ],

After:
    install_requires=[
        "cloudpickle",
        "grpcio>=1.11.0,<=1.48.2",
        "Pillow>=4.2.1",
        "protobuf>=3.6,<3.20",
        "pyyaml>=3.1.0",
        "gym>=0.21.0",
        "pettingzoo==1.15.0",
        "numpy==1.23.1",
        "filelock>=3.4.0",
    ],

**Comment by mikehaojiang** [comment]
After running >mlagents-learn --help
I get this error (NumPy doesn't initialize - do you have the same issue?):

[W ..\torch\csrc\utils\tensor_numpy.cpp:77] Warning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (function operator ())

**Comment by mikehaojiang** [comment]
After some digging: numpy==1.23.1 will fix it

**Comment by mikehaojiang** [comment]
@miguelalonsojr please update the setup.py in ml-agents/ml-agent-envs/ folder - thank you!

**Comment by sheslkw** [comment]
I got this problem today too. Thank you ! I think it is a mistake in the setup.py.

**Comment by miguelalonsojr** [comment]
This has been fixed on the develop branch.

**Comment by Thomasphifer** [comment]
Updated my comment to say numpy 1.23.1 worked best.  Thanks!

**Comment by quakerntj** [comment]
Thanks.  Changed to 1.23.1 work for my environment.

**Comment by f20500909** [comment]
thanks ,change numpy version to 1.23.1  in setup.py slove this problem!

**Comment by syuhei72** [comment]
Dear developer

Yet not changed in GitHub.
Today, three hours have melted away.

**Comment by Serch24** [comment]
1.23.1 works for me. 
The installation guide should at least mention that we have to modify setup.py and change it!
