### ISSUE TITLE
ERROR: Failed building wheel for numpy

### ISSUE THREAD

**Issue by krizantemum** [Unity-Technologies/ml-agents#6021]
**Describe the bug**
Hello, while following the steps, when I am doing python -m pip install ./ml-agents-envs it gives me error.

**To Reproduce**
1. python -m pip install ./ml-agents-envs

**Console logs / stack traces**
`Building wheel for numpy (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for numpy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [214 lines of output]
      setup.py:63: RuntimeWarning: NumPy 1.21.2 may not yet support Python 3.10.
        warnings.warn(
      Running from numpy source directory.
      Processing numpy/random\_bounded_integers.pxd.in
      Processing numpy/random\bit_generator.pyx
      Processing numpy/random\mtrand.pyx
      Processing numpy/random\_bounded_integers.pyx.in
      Processing numpy/random\_common.pyx
      Processing numpy/random\_generator.pyx
      Processing numpy/random\_mt19937.pyx
      Processing numpy/random\_pcg64.pyx
      Processing numpy/random\_philox.pyx
      Processing numpy/random\_sfc64.pyx
      Cythonizing sources
      blas_opt_info:
      blas_mkl_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries mkl_rt not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
        NOT AVAILABLE

      blis_info:
        libraries blis not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
        NOT AVAILABLE

      openblas_info:
        libraries openblas not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
      get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
      customize GnuFCompiler
      Could not locate executable g77
      Could not locate executable f77
      customize IntelVisualFCompiler
      Could not locate executable ifort
      Could not locate executable ifl
      customize AbsoftFCompiler
      Could not locate executable f90
      customize CompaqVisualFCompiler
      Could not locate executable DF
      customize IntelItaniumVisualFCompiler
      Could not locate executable efl
      customize Gnu95FCompiler
      Could not locate executable gfortran
      Could not locate executable f95
      customize G95FCompiler
      Could not locate executable g95
      customize IntelEM64VisualFCompiler
      customize IntelEM64TFCompiler
      Could not locate executable efort
      Could not locate executable efc
      customize PGroupFlangCompiler
      Could not locate executable flang
      don't know how to compile Fortran code on platform 'nt'
        NOT AVAILABLE

      accelerate_info:
        NOT AVAILABLE

      atlas_3_10_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries tatlas not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
        NOT AVAILABLE

      atlas_3_10_blas_info:
        libraries satlas not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
        NOT AVAILABLE

      atlas_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries ptf77blas,ptcblas,atlas not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
        NOT AVAILABLE

      atlas_blas_info:
        libraries f77blas,cblas,atlas not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
        NOT AVAILABLE

      C:\Users\yurek\AppData\Local\Temp\pip-install-hr33_e88\numpy_5686b95fa50041c4868e54a6f8a0d5da\numpy\distutils\system_info.py:2026: UserWarning:
          Optimized (vendor) Blas libraries are not found.
          Falls back to netlib Blas library which has worse performance.
          A better performance should be easily gained by switching
          Blas library.
        if self._calc_info(blas):
      blas_info:
        libraries blas not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
        NOT AVAILABLE

      C:\Users\yurek\AppData\Local\Temp\pip-install-hr33_e88\numpy_5686b95fa50041c4868e54a6f8a0d5da\numpy\distutils\system_info.py:2026: UserWarning:
          Blas (http://www.netlib.org/blas/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [blas]) or by setting
          the BLAS environment variable.
        if self._calc_info(blas):
      blas_src_info:
        NOT AVAILABLE

      C:\Users\yurek\AppData\Local\Temp\pip-install-hr33_e88\numpy_5686b95fa50041c4868e54a6f8a0d5da\numpy\distutils\system_info.py:2026: UserWarning:
          Blas (http://www.netlib.org/blas/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [blas_src]) or by setting
          the BLAS_SRC environment variable.
        if self._calc_info(blas):
        NOT AVAILABLE

      non-existing path in 'numpy\\distutils': 'site.cfg'
      lapack_opt_info:
      lapack_mkl_info:
        libraries mkl_rt not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
        NOT AVAILABLE

      openblas_lapack_info:
        libraries openblas not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
        NOT AVAILABLE

      openblas_clapack_info:
        libraries openblas,lapack not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
        NOT AVAILABLE

      flame_info:
        libraries flame not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
        NOT AVAILABLE

      atlas_3_10_threads_info:
      Setting PTATLAS=ATLAS
        libraries lapack_atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\lib
        libraries tatlas,tatlas not found in C:\Users\yurek\anaconda3\envs\mlagents\lib
        libraries lapack_atlas not found in C:\
        libraries tatlas,tatlas not found in C:\
        libraries lapack_atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\libs
        libraries tatlas,tatlas not found in C:\Users\yurek\anaconda3\envs\mlagents\libs
        libraries lapack_atlas not found in C:\Users\yurek\anaconda3\Library\lib
        libraries tatlas,tatlas not found in C:\Users\yurek\anaconda3\Library\lib
      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        NOT AVAILABLE

      atlas_3_10_info:
        libraries lapack_atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\lib
        libraries satlas,satlas not found in C:\Users\yurek\anaconda3\envs\mlagents\lib
        libraries lapack_atlas not found in C:\
        libraries satlas,satlas not found in C:\
        libraries lapack_atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\libs
        libraries satlas,satlas not found in C:\Users\yurek\anaconda3\envs\mlagents\libs
        libraries lapack_atlas not found in C:\Users\yurek\anaconda3\Library\lib
        libraries satlas,satlas not found in C:\Users\yurek\anaconda3\Library\lib
      <class 'numpy.distutils.system_info.atlas_3_10_info'>
        NOT AVAILABLE

      atlas_threads_info:
      Setting PTATLAS=ATLAS
        libraries lapack_atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\lib
        libraries ptf77blas,ptcblas,atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\lib
        libraries lapack_atlas not found in C:\
        libraries ptf77blas,ptcblas,atlas not found in C:\
        libraries lapack_atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\libs
        libraries ptf77blas,ptcblas,atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\libs
        libraries lapack_atlas not found in C:\Users\yurek\anaconda3\Library\lib
        libraries ptf77blas,ptcblas,atlas not found in C:\Users\yurek\anaconda3\Library\lib
      <class 'numpy.distutils.system_info.atlas_threads_info'>
        NOT AVAILABLE

      atlas_info:
        libraries lapack_atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\lib
        libraries f77blas,cblas,atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\lib
        libraries lapack_atlas not found in C:\
        libraries f77blas,cblas,atlas not found in C:\
        libraries lapack_atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\libs
        libraries f77blas,cblas,atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\libs
        libraries lapack_atlas not found in C:\Users\yurek\anaconda3\Library\lib
        libraries f77blas,cblas,atlas not found in C:\Users\yurek\anaconda3\Library\lib
      <class 'numpy.distutils.system_info.atlas_info'>
        NOT AVAILABLE

      lapack_info:
        libraries lapack not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
        NOT AVAILABLE

      C:\Users\yurek\AppData\Local\Temp\pip-install-hr33_e88\numpy_5686b95fa50041c4868e54a6f8a0d5da\numpy\distutils\system_info.py:1858: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      lapack_src_info:
        NOT AVAILABLE

      C:\Users\yurek\AppData\Local\Temp\pip-install-hr33_e88\numpy_5686b95fa50041c4868e54a6f8a0d5da\numpy\distutils\system_info.py:1858: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
        NOT AVAILABLE

      numpy_linalg_lapack_lite:
        FOUND:
          language = c
          define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]

      Warning: attempted relative import with no known parent package
      C:\Users\yurek\AppData\Local\Temp\pip-build-env-l8snrlfh\overlay\Lib\site-packages\setuptools\_distutils\dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running config_cc
      unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      build_src
      building py_modules sources
      creating build
      creating build\src.win-amd64-3.10
      creating build\src.win-amd64-3.10\numpy
      creating build\src.win-amd64-3.10\numpy\distutils
      building library "npymath" sources
      error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
Successfully built mlagents-envs
Failed to build numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects

(mlagents) C:\Users\yurek\ml-agents>cd ..

(mlagents) C:\Users\yurek>python -m pip install ./ml-agents-envs
ERROR: Invalid requirement: './ml-agents-envs'`

**Environment (please complete the following information):**
- Unity Version: Unity 2022.3.11f1
- Windows 10
- _ML-Agents version_: release_21
- _Torch version_: 1.13.1+cu117
- _Environment_:mlagents

**Comment by benzhangdragonplus** [comment]
我也是这个问题，提示：NumPy 1.21.2 may not yet support Python 3.10，但是1.21.2是有支持python3.10的
![image](https://github.com/Unity-Technologies/ml-agents/assets/112932125/9ceb6a06-5840-46ca-a3b9-7960495a8710)

**Comment by benzhangdragonplus** [comment]
> **Describe the bug** Hello, while following the steps, when I am doing python -m pip install ./ml-agents-envs it gives me error.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. python -m pip install ./ml-agents-envs
> 
> **Console logs / stack traces** `Building wheel for numpy (pyproject.toml) ... error error: subprocess-exited-with-error
> 
> × Building wheel for numpy (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [214 lines of output] setup.py:63: RuntimeWarning: NumPy 1.21.2 may not yet support Python 3.10. warnings.warn( Running from numpy source directory. Processing numpy/random_bounded_integers.pxd.in Processing numpy/random\bit_generator.pyx Processing numpy/random\mtrand.pyx Processing numpy/random_bounded_integers.pyx.in Processing numpy/random_common.pyx Processing numpy/random_generator.pyx Processing numpy/random_mt19937.pyx Processing numpy/random_pcg64.pyx Processing numpy/random_philox.pyx Processing numpy/random_sfc64.pyx Cythonizing sources blas_opt_info: blas_mkl_info: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils customize MSVCCompiler libraries mkl_rt not found in ['C:\Users\yurek\anaconda3\envs\mlagents\lib', 'C:\', 'C:\Users\yurek\anaconda3\envs\mlagents\libs', 'C:\Users\yurek\anaconda3\Library\lib'] NOT AVAILABLE
> 
> ```
>   blis_info:
>     libraries blis not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
>     NOT AVAILABLE
> 
>   openblas_info:
>     libraries openblas not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
>   get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
>   customize GnuFCompiler
>   Could not locate executable g77
>   Could not locate executable f77
>   customize IntelVisualFCompiler
>   Could not locate executable ifort
>   Could not locate executable ifl
>   customize AbsoftFCompiler
>   Could not locate executable f90
>   customize CompaqVisualFCompiler
>   Could not locate executable DF
>   customize IntelItaniumVisualFCompiler
>   Could not locate executable efl
>   customize Gnu95FCompiler
>   Could not locate executable gfortran
>   Could not locate executable f95
>   customize G95FCompiler
>   Could not locate executable g95
>   customize IntelEM64VisualFCompiler
>   customize IntelEM64TFCompiler
>   Could not locate executable efort
>   Could not locate executable efc
>   customize PGroupFlangCompiler
>   Could not locate executable flang
>   don't know how to compile Fortran code on platform 'nt'
>     NOT AVAILABLE
> 
>   accelerate_info:
>     NOT AVAILABLE
> 
>   atlas_3_10_blas_threads_info:
>   Setting PTATLAS=ATLAS
>     libraries tatlas not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
>     NOT AVAILABLE
> 
>   atlas_3_10_blas_info:
>     libraries satlas not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
>     NOT AVAILABLE
> 
>   atlas_blas_threads_info:
>   Setting PTATLAS=ATLAS
>     libraries ptf77blas,ptcblas,atlas not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
>     NOT AVAILABLE
> 
>   atlas_blas_info:
>     libraries f77blas,cblas,atlas not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
>     NOT AVAILABLE
> 
>   C:\Users\yurek\AppData\Local\Temp\pip-install-hr33_e88\numpy_5686b95fa50041c4868e54a6f8a0d5da\numpy\distutils\system_info.py:2026: UserWarning:
>       Optimized (vendor) Blas libraries are not found.
>       Falls back to netlib Blas library which has worse performance.
>       A better performance should be easily gained by switching
>       Blas library.
>     if self._calc_info(blas):
>   blas_info:
>     libraries blas not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
>     NOT AVAILABLE
> 
>   C:\Users\yurek\AppData\Local\Temp\pip-install-hr33_e88\numpy_5686b95fa50041c4868e54a6f8a0d5da\numpy\distutils\system_info.py:2026: UserWarning:
>       Blas (http://www.netlib.org/blas/) libraries not found.
>       Directories to search for the libraries can be specified in the
>       numpy/distutils/site.cfg file (section [blas]) or by setting
>       the BLAS environment variable.
>     if self._calc_info(blas):
>   blas_src_info:
>     NOT AVAILABLE
> 
>   C:\Users\yurek\AppData\Local\Temp\pip-install-hr33_e88\numpy_5686b95fa50041c4868e54a6f8a0d5da\numpy\distutils\system_info.py:2026: UserWarning:
>       Blas (http://www.netlib.org/blas/) sources not found.
>       Directories to search for the sources can be specified in the
>       numpy/distutils/site.cfg file (section [blas_src]) or by setting
>       the BLAS_SRC environment variable.
>     if self._calc_info(blas):
>     NOT AVAILABLE
> 
>   non-existing path in 'numpy\\distutils': 'site.cfg'
>   lapack_opt_info:
>   lapack_mkl_info:
>     libraries mkl_rt not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
>     NOT AVAILABLE
> 
>   openblas_lapack_info:
>     libraries openblas not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
>     NOT AVAILABLE
> 
>   openblas_clapack_info:
>     libraries openblas,lapack not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
>     NOT AVAILABLE
> 
>   flame_info:
>     libraries flame not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
>     NOT AVAILABLE
> 
>   atlas_3_10_threads_info:
>   Setting PTATLAS=ATLAS
>     libraries lapack_atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\lib
>     libraries tatlas,tatlas not found in C:\Users\yurek\anaconda3\envs\mlagents\lib
>     libraries lapack_atlas not found in C:\
>     libraries tatlas,tatlas not found in C:\
>     libraries lapack_atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\libs
>     libraries tatlas,tatlas not found in C:\Users\yurek\anaconda3\envs\mlagents\libs
>     libraries lapack_atlas not found in C:\Users\yurek\anaconda3\Library\lib
>     libraries tatlas,tatlas not found in C:\Users\yurek\anaconda3\Library\lib
>   <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
>     NOT AVAILABLE
> 
>   atlas_3_10_info:
>     libraries lapack_atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\lib
>     libraries satlas,satlas not found in C:\Users\yurek\anaconda3\envs\mlagents\lib
>     libraries lapack_atlas not found in C:\
>     libraries satlas,satlas not found in C:\
>     libraries lapack_atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\libs
>     libraries satlas,satlas not found in C:\Users\yurek\anaconda3\envs\mlagents\libs
>     libraries lapack_atlas not found in C:\Users\yurek\anaconda3\Library\lib
>     libraries satlas,satlas not found in C:\Users\yurek\anaconda3\Library\lib
>   <class 'numpy.distutils.system_info.atlas_3_10_info'>
>     NOT AVAILABLE
> 
>   atlas_threads_info:
>   Setting PTATLAS=ATLAS
>     libraries lapack_atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\lib
>     libraries ptf77blas,ptcblas,atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\lib
>     libraries lapack_atlas not found in C:\
>     libraries ptf77blas,ptcblas,atlas not found in C:\
>     libraries lapack_atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\libs
>     libraries ptf77blas,ptcblas,atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\libs
>     libraries lapack_atlas not found in C:\Users\yurek\anaconda3\Library\lib
>     libraries ptf77blas,ptcblas,atlas not found in C:\Users\yurek\anaconda3\Library\lib
>   <class 'numpy.distutils.system_info.atlas_threads_info'>
>     NOT AVAILABLE
> 
>   atlas_info:
>     libraries lapack_atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\lib
>     libraries f77blas,cblas,atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\lib
>     libraries lapack_atlas not found in C:\
>     libraries f77blas,cblas,atlas not found in C:\
>     libraries lapack_atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\libs
>     libraries f77blas,cblas,atlas not found in C:\Users\yurek\anaconda3\envs\mlagents\libs
>     libraries lapack_atlas not found in C:\Users\yurek\anaconda3\Library\lib
>     libraries f77blas,cblas,atlas not found in C:\Users\yurek\anaconda3\Library\lib
>   <class 'numpy.distutils.system_info.atlas_info'>
>     NOT AVAILABLE
> 
>   lapack_info:
>     libraries lapack not found in ['C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\lib', 'C:\\', 'C:\\Users\\yurek\\anaconda3\\envs\\mlagents\\libs', 'C:\\Users\\yurek\\anaconda3\\Library\\lib']
>     NOT AVAILABLE
> 
>   C:\Users\yurek\AppData\Local\Temp\pip-install-hr33_e88\numpy_5686b95fa50041c4868e54a6f8a0d5da\numpy\distutils\system_info.py:1858: UserWarning:
>       Lapack (http://www.netlib.org/lapack/) libraries not found.
>       Directories to search for the libraries can be specified in the
>       numpy/distutils/site.cfg file (section [lapack]) or by setting
>       the LAPACK environment variable.
>     return getattr(self, '_calc_info_{}'.format(name))()
>   lapack_src_info:
>     NOT AVAILABLE
> 
>   C:\Users\yurek\AppData\Local\Temp\pip-install-hr33_e88\numpy_5686b95fa50041c4868e54a6f8a0d5da\numpy\distutils\system_info.py:1858: UserWarning:
>       Lapack (http://www.netlib.org/lapack/) sources not found.
>       Directories to search for the sources can be specified in the
>       numpy/distutils/site.cfg file (section [lapack_src]) or by setting
>       the LAPACK_SRC environment variable.
>     return getattr(self, '_calc_info_{}'.format(name))()
>     NOT AVAILABLE
> 
>   numpy_linalg_lapack_lite:
>     FOUND:
>       language = c
>       define_macros = [('HAVE_BLAS_ILP64', None), ('BLAS_SYMBOL_SUFFIX', '64_')]
> 
>   Warning: attempted relative import with no known parent package
>   C:\Users\yurek\AppData\Local\Temp\pip-build-env-l8snrlfh\overlay\Lib\site-packages\setuptools\_distutils\dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
>     warnings.warn(msg)
>   running bdist_wheel
>   running build
>   running config_cc
>   unifing config_cc, config, build_clib, build_ext, build commands --compiler options
>   running config_fc
>   unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
>   running build_src
>   build_src
>   building py_modules sources
>   creating build
>   creating build\src.win-amd64-3.10
>   creating build\src.win-amd64-3.10\numpy
>   creating build\src.win-amd64-3.10\numpy\distutils
>   building library "npymath" sources
>   error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for numpy Successfully built mlagents-envs Failed to build numpy ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
> 
> (mlagents) C:\Users\yurek\ml-agents>cd ..
> 
> (mlagents) C:\Users\yurek>python -m pip install ./ml-agents-envs ERROR: Invalid requirement: './ml-agents-envs'`
> 
> **Environment (please complete the following information):**
> 
> * Unity Version: Unity 2022.3.11f1
> * Windows 10
> * _ML-Agents version_: release_21
> * _Torch version_: 1.13.1+cu117
> * _Environment_:mlagents

Enter the "./ml-agents-envs" directory and modify setup.py

like this: numpy=1.22.4

**Comment by krizantemum** [comment]
After changing setup.py to:
1.24.3 or 1.22.4 (I have numpy 1.24.3), I got this:
```
ERROR: Ignored the following versions that require a different python version: 1.10.0 Requires-Python >=3.6, <3.10; 1.11.0 Requires-Python >=3.6, <3.10; 1.11.1 Requires-Python >=3.6, <3.10; 1.11.2 Requires-Python >=3.6, <3.10; 1.12.0 Requires-Python >=3.6, <3.10; 1.13.0 Requires-Python >=3.7, <3.10; 1.13.1 Requires-Python >=3.7, <3.10; 1.14.0 Requires-Python >=3.7, <3.11; 1.15.0 Requires-Python >=3.7, <3.11; 1.16.0 Requires-Python >=3.7, <3.11; 1.17.0 Requires-Python >=3.7, <3.11; 1.18.1 Requires-Python >=3.7, <3.11; 1.19.0 Requires-Python >=3.7, <3.11; 1.20.1 Requires-Python >=3.7, <3.11; 1.21.0 Requires-Python >=3.7, <3.11; 1.22.0 Requires-Python >=3.7, <3.11; 1.22.1 Requires-Python >=3.7, <3.11; 1.22.2 Requires-Python >=3.7, <3.11; 1.4.0 Requires-Python >=3.6, <3.9; 1.4.1 Requires-Python >=3.6, <3.9; 1.4.2 Requires-Python >=3.6, <3.9; 1.5.0 Requires-Python >=3.6, <3.10; 1.5.1 Requires-Python >=3.6, <3.10; 1.5.2 Requires-Python >=3.6, <3.10; 1.6.0 Requires-Python >=3.6, <3.10; 1.6.1 Requires-Python >=3.6, <3.10; 1.7.0 Requires-Python >=3.6, <3.10; 1.8.0 Requires-Python >=3.6, <3.10; 1.8.1 Requires-Python >=3.6, <3.10; 1.8.2 Requires-Python >=3.6, <3.10; 1.9.0 Requires-Python >=3.6, <3.10
ERROR: Could not find a version that satisfies the requirement pettingzoo==1.15.0 (from mlagents-envs) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.22.3, 1.22.4, 1.23.0, 1.23.1, 1.24.0, 1.24.1, 1.24.2)
ERROR: No matching distribution found for pettingzoo==1.15.0
```

**Comment by miguelalonsojr** [comment]
Try to the installation again with the develop branch instead of the release_21 branch. This issue was fixed on develop.

**Comment by nyck33** [comment]
That's a terrible solution @miguelalonsojr 
I cloned release_21 because that is what docs say to do.
Then if I try to fetch and merge or pull branch `develop` I get git error messages about merge conflicts.
So please edit the documentation to say pull the `develop` branch rather than release_21.
