### ISSUE TITLE
Please add 2D environment examples

### ISSUE THREAD

**Issue by trsh** [Unity-Technologies/ml-agents#6022]
**Is your feature request related to a problem? Please describe.**
The bug report layout says: "Please attempt to reproduce your issue with one of the example environments", but we don't have ones for 2D.

**Describe the solution you'd like**
I want 2D environment examples, for beginners, but mostly for reporting bugs efficiently for 2D components, etc.

**Describe alternatives you've considered**
Provide custom 2D environment along with the bug report, that is mostly refused.

**Additional context**
I am initiating this, because I have some problems with 2D sensor components

**Comment by miguelalonsojr** [comment]
Which 2D sensor?

**Comment by trsh** [comment]
Ray perception 2D

**Comment by miguelalonsojr** [comment]
What's the issue with the sensor?

**Comment by trsh** [comment]
I have to do more tests, but it seems not distinguish between "Detectable tags" or doesn't take them in account at all. I will report back, when I have a proper min. repr. example. Be patient with me.
