### ISSUE TITLE
Change observation space size dynamically?

### ISSUE THREAD

**Issue by kkkkkom333** [Unity-Technologies/ml-agents#6026]
Dear @miguelalonsojr , thank you very much for the repo!

is it possible to change the observation space size dynamically during the training/inferencing process (e.g. set in OnEpisodeBegin)?

For example, I want to train an agent to dodge bullets, but the number of bullets will keep increasing. I guess one thing that can be done is to initialize with a big size that will be no less than the maximum number of bullets, and assign some dummy values during training if current number of bullets are less than the observation space size. But just wondering is it possible to have dynamic observation space size?

Another quick/dumb question is that reward can be negative, right?

**Comment by miguelalonsojr** [comment]
What you can do is use a buffer sensor, which allows you to add variable length observations and use an attention block to process the input. This is configured automatically if you just add a buffer sensor to the agent. It does have a maximum size. https://unity-technologies.github.io/ml-agents/Learning-Environment-Design-Agents/#variable-length-observations. And yes, rewards a scalar float, which can be negative. Closing as the buffer sensor is the solution for variable length observations.
