### ISSUE TITLE
Better Unity Integration

### ISSUE THREAD

**Issue by BrainSlugs83** [Unity-Technologies/ml-agents#6031]
# Context:
Reopening this from #4989 as it appears to have been closed as "Completed" by mistake(?), and there has been no engagement or response for the developers regarding the implementation. -- It seems that a developer was assigned, but the work is not integrated into any release build of Unity as far as I can tell, and there are no associated PRs. -- If I am incorrect in my assessment please let me know! 🙂

# Original Feature Request Follows:
### Is your feature request related to a problem? Please describe.

Setting up the environment is convoluted (at best), and extremely error prone -- and there's definitely a learning curve to getting it all setup correctly. -- (I watched several tutorials, dug through the documentation -- had to uninstall and reinstall everything a couple of times, and I'm still not confident that its utilizing my GPU correctly -- torch says it is, but mlagents is ignoring it...).

Then, every time you want to use it, you have to hand edit YAML files, and run command line commands. -- Even if you're just launching the editor again, you have to run another command line command... -- Nothing else in Unity makes you do any of that (even when special software environments or programming languages are required; e.g. Java and Gradle are required for Android Builds, but you don't have to manually set it up!)

### Describe the solution you'd like:
Currently the Unity installer packages up it's own Java and ADK components (optionally, of course), along with other third party tools (like gradle for example) -- and when it needs them it runs them in it's own little sandbox that doesn't screw up the rest of your computer or installed software or change any of your paths/environment variables (not permanently at least).  (i.e. you can even have your own Android studio and ADB installed and Unity won't mess with any of that.)

It would be absolutely AWESOME if installing ml-agents was as easy and accessible as everything else in Unity. -- If there was an option in the Unity Installer to have it install a packaged up version of Python (and all of the relevant components it needs) so that it could just invoke them for me.

It would be awesome if the training could happen by via the UI instead of having to swap back and forth from the command line... without having to manually run python scripts, etc.

Finally, it would be awesome if Hyper Parameters could be configured via a properties panel instead in your unity project, instead of hand editing YAML files and having to dig through mountains of documentation just to figure out where a specific parameter goes and what a valid value might be.

### Describe alternatives you've considered:
If it was an add-on that we installed that could also work (as long as it wasn't convoluted and you just added the package from the manager and didn't have to install anything) -- but I just mean like, literally everything else in Unity works this way.

Like if something you're doing needs Java, you have the option to either bring your own, or to use the one that's packaged into Unity. -- If you need ADK, you have the option to either bring your own, or to use the one that's packaged into Unity. -- If you need Gradle, again, you have the option to bring your own, or just use the built-in one... -- Why not continue with that pattern of making accessible software?

### Additional context:
![image](https://github.com/Unity-Technologies/ml-agents/assets/5217366/b0636f4e-ac95-4c0d-832a-a78f43a45bb7)

**Comment by cihadturhan** [comment]
I have spent literally hours and those python libraries. Their installation guide sucks. 

They "recommend" cloning their repository and conda installation and many more.

They should make a "bare minimum" installation guide first then explain what is needed and why.

Plus, no installation works on MacOS and all the tutorial videos are for Windows.

I was expecting more simple and smoother experience. I'm quite disappointed.

**Comment by BrainSlugs83** [comment]
Again, closed with no one even considering it.  Very sad.

Also to be clear -- the installation guide sucks, but I'm able to get it working -- it's just... "works on my machine... sometimes... when I follow an arcane guide exactly to the letter..." isn't really something useful to me.

In the end it makes using ml-agents more trouble than it's worth, and I certainly can't recommend it to anyone in this state. -- which is sad because it's such a good tool. -- I wish I could just keep using it in Unity on my dev box... but I don't want to spend 3 days setting it up every time.  You know? -- It's lame.  There's no reason python even needs to be required for any of this...
