### ISSUE TITLE
GetStepCount() and OnDemandDecisions() not synced

### ISSUE THREAD

**Issue by imankgoyal** [Unity-Technologies/ml-agents#604]
I am using the Agent.RequestDecision() to start one cycle (observation-decision-action-reward) for an RL agent. I enabled the OnDemandDecisions Flag for the Agent.  However, the Agent.GetStepCount() counter does not seem to be in sync with the number of times the Agent.RequestDecision() is called. And because of this, I am not getting the desired behavior when using the Agent.MaxStepCount().

This is my sample code: 
````	
// Place where I am requesting an action
if (moveComp)
{
    Debug.Log ("Requested Action");
    GetComponent<EgpAgent> ().RequestDecision ();
}
````

````
// My AgentAction script
public override void AgentAction (float[] vectorAction, string textAction)
{
    Debug.Log ("Doing Action");
    Debug.Log (this.GetStepCount());
}
````
A typical output that I get is:

````
Request Action
Doing Action
2
Request Action
Doing Action
104
Request Action
Doing Action
206
Request Action
Doing Action
307
````

The GetStepCount() value changes for each episode, indicating that it is somehow depended on the running speed. Also, note that currently I am using a 'Player' Brain.

To add further is it the case that StepCount is not supposed to be synced with OnDemandDecisions. One can build their own counter. However, in that case, I am not sure whether the Python API is called at each step or at each call of Agent.RequestDecision().

I might be doing something wrong or missing something. I would greatly appreciate any help.

Thanks

**Comment by mmattar** [comment]
@imankgoyal `GetStepCount()` returns the number of Engine FixedUpdates and not the number of decisions requested. Thus, the outputs you're seeing is the number of Engine FixedUpdates between `moveComp` being true. Lastly, the Python API is called when *any* agent requests a decision.

Let us know if this clarifies things for you.

**Comment by imankgoyal** [comment]
Thanks a lot! It clarifies things.
