### ISSUE TITLE
How to set the python interpreter??

### ISSUE THREAD

**Issue by Louis24** [Unity-Technologies/ml-agents#6057]
I got nowhere to set.
![image](https://github.com/Unity-Technologies/ml-agents/assets/18719360/5da9e943-a2ac-4f79-bc19-39484b55d68a)
Assets\Assets\ML-Agents\Examples\PushBlockWithInput\Scripts\PushBlockActions.cs(15,19): error CS0234: The type or namespace name 'InputSystem' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)

![image](https://github.com/Unity-Technologies/ml-agents/assets/18719360/c2dbc83b-9e9a-48ff-afa9-b015c1aba2ee)

And i have install this 2.

**Comment by CCCZING** [comment]
You can try go to Window ->Package Manager -> search InputSystem -> install.
See if error fixed.
