### ISSUE TITLE
MLAgents Camera Sensor Giving Mismatched Shape

### ISSUE THREAD

**Issue by SavorSauc3** [Unity-Technologies/ml-agents#6058]
**Describe the bug**
When attempting to train an agent using a camera sensor that is using a color image (84, 64) I get the following error
**mlagents_envs.exception.UnityObservationException: Decompressed observation did not have the expected shape - decompressed had (3, 64, 84) but expected [64, 84, 3]**
**To Reproduce**
1. Added camera sensor to agent
2. Non-grayscale width and height of 84x64
3. Run training using mlagents package version 2.0.1 and pip version 1.0.0

**Console logs / stack traces**
Please wrap in triple backticks (```) to make it easier to read.
```mlagents_envs.exception.UnityObservationException: Decompressed observation did not have the expected shape - decompressed had (3, 64, 84) but expected [64, 84, 3]```

**Screenshots**
![image](https://github.com/Unity-Technologies/ml-agents/assets/120876534/40a57b94-c522-475c-a3a0-2355f57830e1)

**Environment (please complete the following information):**
- Unity Version: 2022.3.18f1
- OS + version: Windows 11
- _ML-Agents version_: com.unity.ml-agents 2.0.1
- _Torch version_: 2.2.0

**Comment by An-u-rag** [comment]
How did you end up fixing this? I have the same problem.

**Comment by SavorSauc3** [comment]
I didn’t fix it, I just gave up. You could try changing the MLAgents version, if you keep having trouble you can remake the issue. Good Luck!
