### ISSUE TITLE
UnityToGymWrapper uninstallable in up to date Python environments due to gym dependency

### ISSUE THREAD

**Issue by vadim0x60** [Unity-Technologies/ml-agents#6059]
[OpenAI gym](https://github.com/openai/gym/) is unmaintained and deprecated in favour of [gymnasium](https://gymnasium.farama.org/index.html). [Recent updates to pip/setuptools have made OpenAI Gym uninstallable](https://stackoverflow.com/questions/77124879/pip-extras-require-must-be-a-dictionary-whose-values-are-strings-or-lists-of) in up to date Python environments and by proxy, so is `gym_unity`.
Is an update from `gym` to `gymnasium` planned?

**Comment by martkartasev** [comment]
I would like to express my support for updating the interface.
The change seems to be relatively straightforward, as intended by the maintainers of Gymnasium.
