### ISSUE TITLE
ML-AgentsWithPlugin.unitypackage Is not Updated to latest ml-agents

### ISSUE THREAD

**Issue by superjayman** [Unity-Technologies/ml-agents#607]
Where can I download the ml-agents unity package that is v0.3b which includes the hot-fixes?

Please make an Asset Store Page With The Latest ml-agents unity package.

**Comment by MarcoMeter** [comment]
The necessary files are located in the python folder and inside ml-agents/unity-environment/Assets/ML-Agents/ (you can omit the Examples directory).

**Comment by mmattar** [comment]
Thanks @MarcoMeter. @superjayman: we will be updating the unity packages on S3 in the next week or so as we have a new release planned. Regarding the Asset Store request, I've marked this Issue with a `request` tag accordingly.

**Comment by awjuliani** [comment]
Hi all. I am closing the issue for now, as we have moved to only keep the latest ML-Agents on our GitHub repo for the near future.
