### ISSUE TITLE
Using internal brain rises exception

### ISSUE THREAD

**Issue by vasaka** [Unity-Technologies/ml-agents#609]
I am trying to use internal brain and getting an exception, any suggestion what might be wrong with my settings?

I am using beta 0.3, and I believe I followed  each step in the doc on setting up TensorflowSharp , I have slightly modified model but it should be stored in .bytes file anyway.

Please let me know if you need more details.

> TFException: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: conv2d_2/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 4, 4, 1], use_cudnn_on_gpu=true](visual_observation_0, conv2d_2/kernel/read). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
TensorFlow.TFStatus.CheckMaybeRaise (TensorFlow.TFStatus incomingStatus, System.Boolean last) (at <6ed6db22f8874deba74ffe3e566039be>:0)
TensorFlow.TFGraph.Import (TensorFlow.TFBuffer graphDef, TensorFlow.TFImportGraphDefOptions options, TensorFlow.TFStatus status) (at <6ed6db22f8874deba74ffe3e566039be>:0)
TensorFlow.TFGraph.Import (System.Byte[] buffer, TensorFlow.TFImportGraphDefOptions options, TensorFlow.TFStatus status) (at <6ed6db22f8874deba74ffe3e566039be>:0)
TensorFlow.TFGraph.Import (System.Byte[] buffer, System.String prefix, TensorFlow.TFStatus status) (at <6ed6db22f8874deba74ffe3e566039be>:0)
CoreBrainInternal.InitializeCoreBrain (Communicator communicator) (at Assets/ML-Agents/Scripts/CoreBrainInternal.cs:123)
Brain.InitializeBrain (Academy aca, Communicator communicator) (at Assets/ML-Agents/Scripts/Brain.cs:209)
Academy.InitializeEnvironment () (at Assets/ML-Agents/Scripts/Academy.cs:230)
Academy.Awake () (at Assets/ML-Agents/Scripts/Academy.cs:208)

**Comment by vasaka** [comment]
@mmattar I have 1.7.0 installed will try downgrading to 1.4 and let you know if this works

**Comment by vasaka** [comment]
Switching to tensorflow 1.4 fixed things, are there plans to switch to a newer one in near future?

**Comment by baggyg** [comment]
I had the same problem. No need anymore to go all the way back to 1.4. Its enough to go to 1.7 and ensure you have the latest TensorFlowSharp. TensorFlow GPU 1.7 uses Cuda 9 whereas 1.4 would require 8.

I used the gpu version:

`pip install tensorflow-gpu==1.7`

I reran the training and all is now working fine.
