### ISSUE TITLE
Should amend README not to add large files to git

### ISSUE THREAD

**Issue by dora-gt** [Unity-Technologies/ml-agents#61]
I installed `ML-AgentsWithPlugin.unitypackage` and added it to my git, but the package contained large file that exceeded 100MB and then I became not able to push it.

We should amend README not to add such large files to git and to use git LFS.

**Comment by awjuliani** [comment]
Hi @dora-gt,

It should be that the `.gitignore` file lists all the large TensorFlow libraries included in that package.  If there is one in particular that is not there, please let us know.

**Comment by dora-gt** [comment]
I see, I installed ml-agents by `ML-AgentsWithPlugin.unitypackage`, not by copying this repo. So I think we should amend `unity-environment/README.md` to add appropriate lines on `.gitignore` not to add large files.
