### ISSUE TITLE
Fix the installation guide

### ISSUE THREAD

**Issue by irekkosek** [Unity-Technologies/ml-agents#6102]
**Describe the bug**
Installation guide is obviously flawed with numpy and python versions mismatch. 

**To Reproduce**
try following your own installation guide

**Console logs / stack traces**
```
 RuntimeWarning: NumPy 1.21.2 may not yet support Python 3.10.
       TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'
```

**Environment (please complete the following information):**
- Unity Version: Unity 2022.3.25f1
- OS + version: Windows 10
- _ML-Agents version_: (e.g. ML-Agents v1.0.0)
- _Torch version_: as in installation guide
- _Environment_: conda, pip etc.

**Comment by XRFrancois** [comment]
I had the same issue and fixed it by manually replicating the changes here: https://github.com/Unity-Technologies/ml-agents/pull/6082/files

Also, I think you need Unity 2023.2+ ?

**Comment by whisper3zzz** [comment]
I managed to fix the error that was reported about the numpy library.I changed numpy version to 1.22.4 in setup.py, and my python version is 3.10.12

**Comment by MrChenLearnSpace** [comment]
linux没有这个问题试过了，这个问题是window没有这个numpy的包，可以尝试使用pip官方的项目没问题的编译一次

**Comment by TuureKaunisto** [comment]
The installation guide also suggests you can use newer versions of Python than 3.10.12. That does not seem to be the case. I made a PR to fix the docs but the CLA form is not worth changing a single line in the docs.
https://github.com/Unity-Technologies/ml-agents/pull/6131/files

**Comment by polycrunchgames** [comment]
I got past this issue by changing numpy version in mlagent-env/setup.py to have a dependency on version 1.22.1 instead of 1.21.2. After that, following the instructions on their installation page (https://unity-technologies.github.io/ml-agents/Installation/) works.
