### ISSUE TITLE
GUI and Canvas elements in visual observations

### ISSUE THREAD

**Issue by emillarsson** [Unity-Technologies/ml-agents#611]
Hi,

Is there a way to have GUI rendered textures (through OnGUI in a separate script) show up on the visual observations set in the Brain?

Thanks for a great plugin!

**Comment by Lakrix** [comment]
Yes it is possible to create a Canvas object and add your camera to "Render Camera" in the game object.

**Comment by mmattar** [comment]
Thanks @Lakrix. @emillarsson let us know if this solves your issue.

**Comment by emillarsson** [comment]
@Lakrix @mmattar It works well for Canvas objects, thanks!

For context, I was using the OnGUI method to draw a texture, which did not work except if manually added on top of the camera texture of the agent. Changing this to drawing on a texture of a Canvas object and following @Lakrix tip worked like a charm. Thanks again!
