### ISSUE TITLE
Can't use a camera after being used in a camera sensor

### ISSUE THREAD

**Issue by SmlHugod** [Unity-Technologies/ml-agents#6113]
**Describe the bug**
I have an HUD with a Render Texture bind to a camera called Camera 2.  So in game, I have the main Camera View and a little view of Camera 2.
If I decide to use Camera 2 in a Camera Sensor, then in game my Camera 2 dissapears

**To Reproduce**
1. Create a simple project with 2 cameras displayed in the Game view (for example a main camera + a Raw Image using the other camera as a background texture in a Canvas).
2. Click on play : we see both cameras.
3. Now create an agent and add him a camera sensor using Camera 2.
4. Click on play : the camera dissapears.

**Environment (please complete the following information):**
- Unity Version: Unity 2023.2.25f1
- OS + version: Windows 11
- _ML-Agents version_: ML-Agents release 21
- _Torch version_:  2.2.2+cu121

**Comment by miguelalonsojr** [comment]
This is intended functionality. You can re-enable the camera to be used beyond collecting observations in the CameraSensor component by checking the "Runtime Camera Enable".

![Screenshot 2024-05-09 at 11 53 46 AM](https://github.com/Unity-Technologies/ml-agents/assets/76960110/1516aa96-040e-46f0-87d5-73a99e750bbe)

**Comment by SmlHugod** [comment]
Oh thank you so much. I feel so dumb !

**Comment by miguelalonsojr** [comment]
Glad it worked out. :)
