### ISSUE TITLE
Loosen pettingzoo version requirement

### ISSUE THREAD

**Issue by melvintzw** [Unity-Technologies/ml-agents#6118]
**Is your feature request related to a problem? Please describe.**
I am using a tool that depends on a version of pettingzoo (1.22.1) that is higher than the strict requirement (==1.15.0) specified for the mlagents-envs package.

**Describe the solution you'd like**
I would like to request that mlagents' requirement for pettingzoo is loosened to allow later versions of pettingzoo.

**Describe alternatives you've considered**
I have considered manually installing and modifying the ml-agents/ml-agents-envs/setup.py to loosen the pettingzoo requirements, but I am not sure what side effects this may have. Is there a particular reason why the pettingzoo requirement was specified strictly as 1.15.0?

**Additional context**
I am interested to try mlagents v0.30.0 or mlagents v1.0.0, however the pettingzoo requirement specified for mlagents is too restrictive and therefore not compatible with the (higher) pettingzoo version I require. I require a higher version of pettingzoo as my toolkit runs pettingzoo environments that are based on higher versions.

**Comment by weichengtao** [comment]
They are using the old gym/pettingzoo API which is not compatible with the new API
