### ISSUE TITLE
Having issue installing ml-agents 

### ISSUE THREAD

**Issue by onurkrsrml** [Unity-Technologies/ml-agents#6120]
File "/opt/anaconda3/envs/mlagents/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/opt/homebrew/bin/cmake', '--build', '.', '--', '-j', '8']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for onnx
  Running setup.py clean for onnx
Successfully built mlagents
Failed to build onnx
ERROR: Could not build wheels for onnx, which is required to install pyproject.toml-based projects

**Comment by bilalfomo** [comment]
You should install onnx python package 
`pip install onnx`

**Comment by onurkrsrml** [comment]
I already did but the error was same

**Comment by nobu-sh** [comment]
Just modify the numpy version in ml-agents-env/setup.py from 1.21.2 to 1.23.5
