### ISSUE TITLE
I want to edit rayperception sensor 3d outputs ! 

### ISSUE THREAD

**Issue by ujsain** [Unity-Technologies/ml-agents#6130]
I am making a snake AI . Where there will be lots of snake who will eat and dodge each other . 

Rayperception sensor 3d detects everything ! but there is a specific case where problem happens....

For example my snake has 30 cube child each having tags as beads . There are other snake similar to that.

I want rayperception to not detect these CHILD of it's own but to detect everything else !

How do you think will it happen ?

**Comment by quantum-shubham** [comment]
To achieve the behavior where the RayPerceptionSensor3D in Unity detects everything except the child objects of its own snake (tagged as "beads"), you can implement a custom filtering mechanism.

Use Layers for Filtering:
Assign a Unique Layer: Assign a unique layer to your snake and its child objects (e.g., MySnakeLayer). This way, you can easily filter out these objects from the ray perception.
RayPerception Layer Mask: Adjust the layer mask of the RayPerceptionSensor3D to exclude this specific layer. This will make the ray sensor ignore objects on that layer.

Custom Script for Tag Checking:
If you want to keep using tags and not just rely on layers, you can modify the ray perception script or create a wrapper around it. In the custom script, you can manually check the tag of each detected object and ignore the ones that belong to the same snake.

**Comment by ujsain** [comment]
NO that's not how it is . All my snake works on a similar pattern ! I can't
just make a unique tags with n number of snake . All those AI snake have
same properties they have to ! They compete with each other having the same
body. What I really want is to have a filtering system like filtering the
gameobjects that rayperception is giving
