### ISSUE TITLE
Learning Environment Create New.md images are bugged

### ISSUE THREAD

**Issue by true-king-al** [Unity-Technologies/ml-agents#6154]
**Describe the bug**
so in [Learning Environment Create New.md](https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/Learning-Environment-Create-New.md) the images will say stuff like {: style="width:250px"} and  style="width:400px"}
**To Reproduce**
1. Go to [Learning Environment Create New.md](https://github.com/Unity-Technologies/ml-agents/blob/develop/docs/Learning-Environment-Create-New.md)
2. look at like any image

**Screenshots**

![image](https://github.com/user-attachments/assets/30622340-145b-4e73-9133-dea620486d69)

**Environment (please complete the following information):**
- opera gx

**Comment by true-king-al** [comment]
also i know this isnt a bug with mlagents, but i idk what else i was suppost to label it

**Comment by jash-maester** [comment]
Hi,
Were you able to get the 3DBall demo running? For us couple of folks the Unity Engine throws bunch of Compile errors, the source C# code doesn't give super clear pointers. There is also an active issue mentioned in this repo's Issues.

If yes, could you mention your system configuration and any specific version details?
