### ISSUE TITLE
Attempting to debug with Monodevelop locks up both Monodevelop and Unity with 'Debugger operation failed'

### ISSUE THREAD

**Issue by dylanfries** [Unity-Technologies/ml-agents#62]
I'm not sure if this is the right place for this, but I've never seen this bug before using the ml-agents sample project. If I try to attach the debugger to the project, it fires up a ton of these 'Debugger operation failed' dialogues, then locks up both Monodevelop and Unity, requiring a forced reset. I'm on Windows 10 if that matters for anything. I've got this every time I've tried attaching in the project and I'm not sure if its expected behaviour, but its sure annoying. Otherwise, really enjoying the new tools, thanks!

Dylan
![debugger operation failed](https://user-images.githubusercontent.com/103104/31299882-4834b4d4-aab6-11e7-880b-c4940bcaf898.PNG)

**Comment by awjuliani** [comment]
Hi @dylanfries,

Thanks for pointing this out. It may have something to do with our using the new .NET 4.6 framework, as it is still under experimental support. Was .NET 4.6 turned on by chance?
