### ISSUE TITLE
Training multiple brains simultaneously using curricula

### ISSUE THREAD

**Issue by drArthur** [Unity-Technologies/ml-agents#634]
Hi, 
I'm looking into training multiple brains simultaneously while also using curriculum.
Is it even possible?
And if it is, which brain's reward is being measured in order to change the lesson?

**Comment by drArthur** [comment]
Thanks! 
This helps me a lot.
I'll probably try to edit the code a bit, so that the reward thresholds can  be set for both brains seperately, and the lesson is changed when each threshold is met.

**Comment by awjuliani** [comment]
This is a feature we are actively working on. Going to be closing this issue for now.
