### ISSUE TITLE
Having some trouble with the ball example(Jupyter PPO)

### ISSUE THREAD

**Issue by elanrosen** [Unity-Technologies/ml-agents#65]
When using the Jupyter Notebook and running the PPO algorithm. 
The error I received was ppo module not found. My first thought would be to add something like sys.path.append('C:\Users\elanr\Desktop\ml-agents-master\python'). I am unfamiliar with the jupyter repository. Does anyone more experienced know the quick fix to this. 

Also should i be connected my tensor-flow GPU environment to this or does tensor-flow automatically use it?

Thanks in advance to anyone who responds

**Comment by Maomao110** [comment]
I met the same problem with you .. Hope someone could help us solve the problem

**Comment by liuyihunter** [comment]
The easiest solution is that making sure executable and PPO.ipynb under same folder.  For the 3DBall example, put executable file into "/ml-agents-master/python/" and then change "env_name" to the name of your exe file.

**Comment by Maomao110** [comment]
if you can speak chinese , please tell me .
Now , the exe file are in the same folder of the PPO.ipynb.
and I have checked the env_name, it is the name of my exe file .. But it still doesn't work.

**Comment by Maomao110** [comment]
![image](https://user-images.githubusercontent.com/28225365/31326790-008993ae-acfd-11e7-8477-3ef5741b934a.png)

![image](https://user-images.githubusercontent.com/28225365/31326798-0c188c48-acfd-11e7-93e6-ab439801d75d.png)

**Comment by liuyihunter** [comment]
Literally, The error was No module name "ppo",

**Comment by Maomao110** [comment]
@liuyihunter  thanks for your help. I have solve the problem..Because I did not set the work folder in the jupyter .  After I set the default folder as the python, it works.

**Comment by elanrosen** [comment]
@Maomao110 I probally have the exact same issue how do you do that

**Comment by Maomao110** [comment]
![image](https://user-images.githubusercontent.com/28225365/31337168-a113b500-ad2c-11e7-9199-9b148df4f053.png)
find this content in the PPO.ipynb , and then set the value . the value is where your ppo lib located . mine is :E:\StudyProject\ml-agents-master_unity2017\python\ppo

you can try , if it doesn't work , I will show you another way.

**Comment by elanrosen** [comment]
Didn't work whats the other way?

**Comment by vincentpierre** [comment]
The `run_path` variable is the name of the folder that will contain the tensorflow graph checkpoints. When you will run your model, it will store the checkpoints into `python/models/ppo`. The fact that the ppo folder containing the scripts for training and the `run_path` have the same name is coincidence.  
Please make sure you start jupyter notebook **from the python folder** and also that the ppo folder inside python folder contains `__init__.py`, `history.py`, `models.py` and `trainer.py`   
Let me know if this helps.

**Comment by elanrosen** [comment]
**Wrong start folder**

Thanks
