### ISSUE TITLE
No explanation about how to start up process

### ISSUE THREAD

**Issue by dora-gt** [Unity-Technologies/ml-agents#66]
It seems that <env_name> should be the same as .app name, but there isn't any explanation about it. Noobs can't understand the implicit rule. We should write about it first.

**Comment by awjuliani** [comment]
Thanks for pointing this out, @dora-gt. I've updated the documentation accordingly: https://github.com/Unity-Technologies/ml-agents/blob/master/python/README.md

**Comment by dora-gt** [comment]
Thank you.
