### ISSUE TITLE
(iOS) UnityAgentsException: The tensorflow graph needs an input for random_normal/RandomStandardNormal  of type DT_FLOAT

### ISSUE THREAD

**Issue by TinyQubit** [Unity-Technologies/ml-agents#661]
I'm getting this error, even after adding random_normal/RandomStandardNormal to Graph Placeholders in the Brain.cs. I've tried many combinations and even changed the Type enum to DT_FLOAT to see if it would make a difference but nothing fixed it.

This error doesn't appear in the Unity Editor while built for iOS, but the error will appear in Xcode when building to iPhone.

I've also tried downgrading from 1.4.1 to 1.4, and to 1.2, but doesn't make a difference.

<img width="427" alt="screen shot 2018-04-20 at 12 25 56 pm" src="https://user-images.githubusercontent.com/28972222/39062653-323387c6-4496-11e8-9cf3-b3a4724b0831.png">

**Comment by vincentpierre** [comment]
I think this issue has been raised here #632 
Closing for now

**Comment by TinyQubit** [comment]
Thanks for the reference. I've seen that issue here, but no one has mentioned a fix for it. Even after downgrading the error persists.
