### ISSUE TITLE
Namespaces and Assembly definitions

### ISSUE THREAD

**Issue by m-ronchi** [Unity-Technologies/ml-agents#662]
Hi,
1) currently all the code is in the default namespace, and I noticed that some class names are generic enough that a conflict is not unlikely (e.g. System.Threading.Monitor exists in mono/.net class library)

2) are you planning to add asmdef to ml-agents? I use asmdefs in my project so I manually added them to use it.

**Comment by awjuliani** [comment]
Hi @m-ronchi,

We have included an `MLAgents` namespace in the v0.4 release. Thanks for brining this to our attention when you did.
