### ISSUE TITLE
Questions on ML-agents - Crawler Example

### ISSUE THREAD

**Issue by bybgr** [Unity-Technologies/ml-agents#667]
Hi all, 
I am new to Unity & the ML-agents, and now studying the example of 'ML-agents - Crawler'. 
In the script 'CrawlerLegContact.cs', the detection of the leg contacting is 
'    void OnCollisionStay(Collision other){
        if (other.gameObject.name == "Platform")
        {
            agent.leg_touching[index] = true;
        }
    }'

However, in its scene, I did not find the GameObject - "Platform", though the training seemed to work without any issue. I am wondering if I missed something? 
(On contrary, detection of game fail is by '  ...if (other.gameObject.name == "Ground"){...}...' , and I did see the GameObject "Ground" in the scene)

Thank you all!

**Comment by vincentpierre** [comment]
Hi,
You are right and this is a bug that is addressed in PR #589 and has been merged into `develop`. It seems that the crawler is able to learn how to walk even without knowledge of his leg's contact with the ground.
