### ISSUE TITLE
Academy.Done() doesn't work when called during agent action

### ISSUE THREAD

**Issue by m-ronchi** [Unity-Technologies/ml-agents#668]
Academy.Done() doesn't work when called during agent action.

I setup my agents to synchronously call academy.Done when their action causes the game to end.
this sets the done flag, which is immediately reset during EnvironmentStep and will not reset the academy (which happens earlier in the EnvironmentStep routine)

**Comment by m-ronchi** [comment]
for now I worked around it by starting a coroutine and yielding a frame.

**Comment by awjuliani** [comment]
@vincentpierre Was this issue ever addressed?

**Comment by harperj** [comment]
Sounds like you managed to get this working for your use case.  This issue has been closed for more than 30 days so I'm going to close it, but please feel free to reopen if you have any updates or further issues.
