### ISSUE TITLE
Tensorboard stats

### ISSUE THREAD

**Issue by m-ronchi** [Unity-Technologies/ml-agents#669]
Hi,
I setup the docker image as per your docs and started the training.

then I started tensorboard with (command line from repo root):
```tensorboard --logdir=unity-volume/summaries```
and navigated to localhost:6006.

from what I understand, I should see 8 graphs, but I only see 4:
- info/Lesson (const 0, I am not using curriculum learning)
- info/entropy (appears random, but y-axis has all values labelled 3.69)
- info/learning_rate (descending linearly)
- info/value_estimate (appears to go slowly up, currently around 0.059)

docs says I should also see:
- info/cumulative_reward
- info/episode_length
- info/policy_loss
- info/value_loss
but I don't see them.

am I doing something wrong? is it a problem with docker?

Hyperparameters:
```
	batch_size:	1024
	beta:	0.005
	buffer_size:	10240
	epsilon:	0.2
	gamma:	0.99
	hidden_units:	128
	lambd:	0.95
	learning_rate:	0.0003
	max_steps:	5.0e4
	normalize:	False
	num_epoch:	3
	num_layers:	2
	time_horizon:	64
	sequence_length:	64
	summary_freq:	1000
	use_recurrent:	False
	graph_scope:	
	summary_path:	/unity-volume/summaries/first
	memory_size:	256
```

![schermata 2018-04-23 alle 16 51 46](https://user-images.githubusercontent.com/35332423/39134384-c96b2388-4716-11e8-9ed9-9c8793fdecf9.png)

brain parameters:
- vector obs space: continuous, size 244, not stacked
- visual obs: none
- action space: discrete, 40

**Comment by m-ronchi** [comment]
I set academy.Done() after the game is finished.
now I am making a build that also sets all agent to Done() just before.
agents are using on-demand decisions, what value should I give to max step? (game ends in 40 moves)

there were no messages like that in the console.
tomorrow I will try another training.

ps: I changed the action space from discrete to continuous, and take the action that has the highest value, after filtering out illegal moves (only 3 actions are legal given a specific state in my game). is it a valid approach? or should I treat them as a probability distribution and extract a random (legal) action from that?

**Comment by vincentpierre** [comment]
I think because of this problem #668 You cannot call Academy.Done from the AgentAction method. I would call done from the AcademyStep method or call done on all the agents. I think that since the game you have has a fixed number of moves (40 moves) then using max_step seems appropriate.
Do not think using continuous action will work because the trainer needs to know what action was taken. We do not currently have a way to mask for impossible actions, I would train it by penalizing the illegal moves and do a random move if the chosen move was illegal at inference...

**Comment by m-ronchi** [comment]
Hi,
1) AcademyStep does not work, as it is between the EnvironmentStep call:
```if (done) // <- here done is false
        {
            EnvironmentReset();
        }

        AgentResetIfDone();

        AgentSendState();

        BrainDecideAction();

        AcademyStep(); // <- if I call Done here

        AgentAct(); // <- or here

        if (done)
        {
            done = false; // <- it gets cleared here, without calling EnvironmentReset() as it happens before in this function
            maxStepReached = false;
        }```

2) I have setup 100 max steps for both academy and agents (40 was not enough), and I now call agent.Done() for each agent instead of academy.Done().
in the editor it works, but if I build the environment and train it, python throws:
```Traceback (most recent call last):
  File "python/learn.py", line 62, in <module>
    tc.start_learning()
  File "/execute/python/unitytrainers/trainer_controller.py", line 252, in start_learning
    text_action=take_action_text)
  File "/execute/python/unityagents/environment.py", line 503, in step
    raise UnityActionException("The episode is completed. Reset the environment with 'reset()'")
unityagents.exception.UnityActionException: The episode is completed. Reset the environment with 'reset()'```

**Comment by m-ronchi** [comment]
I managed to view the environment unity logs with ```
docker exec -ti 03ef66131a31 /bin/bash
tail -f unity-environment.log 
```
and it seems the games are running (right now they all end with invalid moves)

main logs still did not display any ```INFO:unityagents:StudentBrain``` though.
(I start new games in AcademyReset(), therefore the acasemy is resetting properly, I assume)

ps: I noticed that in the editor I have logs like [New game -> end game -> new game -> end game -> ...] while in the training build I have [new -> new -> end -> new -> new -> end -> ...] like it calls Reset twice or half of the games do not reach the end.

**Comment by mmattar** [comment]
Hi @m-ronchi - are you still facing any issues?

**Comment by m-ronchi** [comment]
Hi @mmattar 
I pulled to the branch 'develop' and tried again (I refactored the rules to be job-friendly in the meantime).

I also started the training from the editor as I saw the updated instructions.

I don't seem to receive double reset anymore, but:
- calling `RequestDecision()` during `AcademyStep()` triggers `AgentAction` before `CollectObservations`. worked around by using a coroutine and `WaitForFixedUpdate`
- calling `academy.Done()` during `AcademyStep()` seem to work, but only for a couple games. after that, editor stops playing with no errors in console, and I get the following output from python (process is killed):

```
$ docker run --mount type=bind,source=/Users/***/Workspace/ml-agents/unity-volume,target=/unity-volume -p 5005:5005  briscola.v0.2:latest --docker-target-name=unity-volume --train --run-id=june
INFO:unityagents:{'--curriculum': 'None',
 '--docker-target-name': 'unity-volume',
 '--help': False,
 '--keep-checkpoints': '5',
 '--lesson': '0',
 '--load': False,
 '--run-id': 'june',
 '--save-freq': '50000',
 '--seed': '-1',
 '--slow': False,
 '--train': True,
 '--worker-id': '0',
 '<env>': None}
INFO:unityagents:Ready to connect with the Editor.
INFO:unityagents:
'BriscolaAcademy' started successfully!
Unity Academy name: BriscolaAcademy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		
Unity brain name: BriscolaBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 244
        Number of stacked Vector Observation: 1
        Vector Action space type: discrete
        Vector Action space size (per agent): 40
        Vector Action descriptions: , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , , 
2018-06-08 14:51:53.424677: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
INFO:unityagents:Hypermarameters for the PPO Trainer of brain BriscolaBrain: 
	batch_size:	1024
	beta:	0.005
	buffer_size:	10240
	epsilon:	0.2
	gamma:	0.99
	hidden_units:	128
	lambd:	0.95
	learning_rate:	0.0003
	max_steps:	5.0e4
	normalize:	False
	num_epoch:	3
	num_layers:	2
	time_horizon:	64
	sequence_length:	64
	summary_freq:	1000
	use_recurrent:	False
	graph_scope:	
	summary_path:	/unity-volume/summaries/june
	memory_size:	256
	use_curiosity:	False
	curiosity_strength:	0.01
	curiosity_enc_size:	128

    
                    ▄▄▄▓▓▓▓
               ╓▓▓▓▓▓▓█▓▓▓▓▓
          ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
        ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
      ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
    ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
    ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
      ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
        '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
           ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
               `▀█▓▓▓▓▓▓▓▓▓▌
                    ¬`▀▀▀█▓
                    

Traceback (most recent call last):
  File "python/learn.py", line 81, in <module>
    tc.start_learning()
  File "/execute/python/unitytrainers/trainer_controller.py", line 256, in start_learning
    text_action=take_action_text)
  File "/execute/python/unityagents/environment.py", line 370, in step
    s = self._get_state(rl_output)
  File "/execute/python/unityagents/environment.py", line 448, in _get_state
    memory_size = max([len(x.memories) for x in agent_info_list])
ValueError: max() arg is an empty sequence
```

**Comment by awjuliani** [comment]
Hi All,

I am closing this thread due to inactivity, but feel free to re-open it if you desire.
