### ISSUE TITLE
Unchecking Reset on Done disables Agent

### ISSUE THREAD

**Issue by RossMelbourne** [Unity-Technologies/ml-agents#671]
I am trying to start and stop training on the reset boundary by using Reset-On-Done flag as false.  I have read in a comment that you can call AgentReset in AgentOnDone when the Reset On Done is unchecked on the editor.  I have tried this in the GridWorld sample and after AgentOnDone is called, which then calls AgentReset, the agent receives no more input from the player (in player mode).

**Comment by RossMelbourne** [comment]
I think this is a bug or perhaps the documentation is out of date.  This problem is very easy to recreate, simply uncheck Reset on Done on Banana Imitation or GridWorld set in Player Mode.  When done() is called the agent stops receiving inputs.  If it is not a bug then I would like to know what to call in AgentOnDone to continue receiving keyboard inputs.

**Comment by RossMelbourne** [comment]
I think I have a work around or fix for this depending upon the original intent of Reset On Done.  After some experimentation it appears that when Reset On Done is set to False in the Editor then the Agent becomes disabled when Done() is called.  I am not sure if this is the intended behavior or not.  However if you want to Reset the agent manually, to say pause the learning, then comment out the following line in Agent.cs:

    void AgentStep()
    {
        if (terminate)
        {
            terminate = false;
            ResetReward();
            done = false;
            maxStepReached = false;
            requestDecision = false;
            requestAction = false;

            hasAlreadyReset = false;
	   // Comment next line out to be able to restart agent after Done() when Reset on Done = False
//          OnDisable();  
            AgentOnDone();
        }

Then when AgentOnDone() is called or when you are ready to restart the agent call base._AgentReset ();

**Comment by vincentpierre** [comment]
When an agent is done and has reset on done not checked, then the agent is terminated. You should usually destroy the agent in the AgentOnDone method. Once an agent is done and it cannot reset, then there is nothing left for it to do. You should not be calling AgentReset manually, you should just set the agent to done. If it resets on done then it will reset, else it will die. It does not make sense to me why you would want to reset an agent you explicitly told not to reset on done. 
If what you want is to change the brain from Internal to Player, you can use the GiveBrain method of the agent.
If you want to set an agent to Done and then have it continue to act later on, the simplest way would be to destroy the agent on done and then spawn a new one.

**Comment by RossMelbourne** [comment]
@vincentpierre Thank you for this clarification!  Now I understand the intent of unchecking reset on done and the AgentOnDone method.
