### ISSUE TITLE
Reacher Scene - Vector Action Descriptions Returning Empty

### ISSUE THREAD

**Issue by unityjeffrey** [Unity-Technologies/ml-agents#672]
Hi all - in the reacher scene, the vector action descriptions from the brain are returning empty.

![screen shot 2018-04-23 at 3 09 39 pm](https://user-images.githubusercontent.com/34355042/39155777-61ed6cf6-4708-11e8-9ecb-622ce19947fd.png)

**Comment by jo3w4rd** [comment]
In general, the Action descriptions haven't been provided in our examples. (They are informational and don't have any functional purpose.)
