### ISSUE TITLE
How to export the graph

### ISSUE THREAD

**Issue by devnio** [Unity-Technologies/ml-agents#676]
Tonight I let my computer train for some hours but I realised that my computer died when there was some steps left. 
So I wonder how can I export the bytes file manually? I saw some other pepole ask this question but I did't find someone explaining it clearly.
I hope I can find some help

Thanks.

**Comment by ruanrothmann** [comment]
You should simply be able to continue training with the --load parameter.

**Comment by eshvk** [comment]
@devnio If you exit before it has finished training by quitting `CTRL+C`, it should save the graph.

**Comment by devnio** [comment]
Thanks again for the prompt answer.
I haven't tried it already, because I don't want to stop the training. I would like to be able to export the graph from different checkpoints in order to have a better view form how my agents is training. 
And those graphs can also be used later on for testing, or used for a not expert agent in a game for example.

**Comment by jo3w4rd** [comment]
I haven't tried it, but you might be able to modify trainer_controller.py so that it both saves the checkpoint and exports the graph. It looks like calling _export_graph() at the end of _save_model() would work. I don't know whether the time it takes to export the graph will cause problems, though.

**Comment by devnio** [comment]
Yeah it's the whole day I'm trying to do that. I finally managed to find this link: https://github.com/Unity-Technologies/ml-agents/pull/292. 
I copy pasted the code into a file, named it export.py and placed it into the python folder. In the command line a opened a python shell and run 'import export' and 'export.export_graph(<model_path>, <env_name>)'
It seems to work this way.

**Comment by mmattar** [comment]
Hi @devnio - glad you found the working solution. I added the label `request/contributions-welcome` to indicate that we're open to fold such a PR into the repo.

**Comment by eshvk** [comment]
We don't use bytes files anymore, we have our own [custom inference engine](https://github.com/Unity-Technologies/ml-agents/blob/master/ml-agents/mlagents/trainers/tensorflow_to_barracuda.py) which tensorflow graphs are converted to.
