### ISSUE TITLE
Vector Observation size mismatch between discrete agent and brain.

### ISSUE THREAD

**Issue by al291708** [Unity-Technologies/ml-agents#682]
Hi everyone,

I have created an Agent with 38 discrete observations and 2 discrete actions as the following code:

```
public class TAJAgent : Agent {

    // some variables

    public override void InitializeAgent() {
	// some variables get initial values here
    }

    public override void CollectObservations() {
	AddVectorObs(life); //life is an integer
	AddVectorObs(enemiesAlive);   //enemies alive is an integer
	/*
         * SOME OTHER AddVectorObs() getting a total of 38 observations.
         * Every value passed to AddVectorObs() is an integer.
	*/		 
	SetTextObs("Testing " + gameObject.GetInstanceID());        
    }

    public override void AgentAction(float[] vectorAction, string textAction) {
	int action = Mathf.Clamp(vectorAction[0], 0, maxIntValueWantedHere);
	int gap = Mathf.Clamp(vectorAction[1], 0, maxIntValueWantedHere);		
	if(action == 0) {
	     // do action 0
	     SetReward(0.01f);
        }
	// etc.
    }

    public override void AgentReset() {
        // reset some variables values
    }
}
```

In the Unity scene I have created an Academy, a Brain as a child of it, and I have added the above TAJAgent to a gameobject (passing the Brain to the TAJAgent Script).

Brain parameters are:
![image](https://user-images.githubusercontent.com/22665088/39263386-46284b9c-48c2-11e8-9b52-8db19d373152.png)

The problem is that I am always getting:

> UnityAgentsException: Vector Observation size mismatch between discrete agent NertaNPC and brain Brain. Was Expecting 1 but received 38. 
Agent.SendInfoToBrain () (at Assets/ML-Agents/Scripts/Agent.cs:534)
Agent.SendInfo () (at Assets/ML-Agents/Scripts/Agent.cs:829)
Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:475)
Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:507)

I am stuck and I don't know what can happen since "Vector Observation" "Space Size" has the value of "38" (because I have 38 observations), as you can see in the picture above, but it is expecting just 1 observation.

¿Could you please help me?

Thanks a lot.

Cheers.

**Comment by jo3w4rd** [comment]
When you use a discrete observation space, what you pass as an observation is essentially an id into a table of states. Thus you only pass a single integer id for the agent's current state and that id can range from 0 up to Space Size - 1 (in your case 38-1=37).

It sounds like you should just change to the Continuous Space Type for your observations.

**Comment by al291708** [comment]
I've just changed to Continuous, it seems I misunderstood something.

Thanks for your fast answer.
