### ISSUE TITLE
Starting environment error 

### ISSUE THREAD

**Issue by hawkzey** [Unity-Technologies/ml-agents#683]
The error i get is:

UnityEnvironmentException: The API number is not compatible between Unity and python. Python API : API-3, Unity API : API-2.
Please go to https://github.com/Unity-Technologies/ml-agents to download the latest version of ML-Agents.

i have tried re grabbing the latest version of the Ml-Agents but it doesnt fix my problem.

Any ideas?

**Comment by vincentpierre** [comment]
#658
