### ISSUE TITLE
Increase max_steps

### ISSUE THREAD

**Issue by DanielSaG** [Unity-Technologies/ml-agents#686]
I know it may be a dumb question, but i can't find where to increase the max steps of the ppo algorithm. Hope someone can tell me.

**Comment by vincentpierre** [comment]
You must edit the `trainer_config.yaml` file as explained [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-ML-Agents.md).

**Comment by DanielSaG** [comment]
Thank you very much
