### ISSUE TITLE
Invalid links/Shortcuts

### ISSUE THREAD

**Issue by jgarza9788** [Unity-Technologies/ml-agents#687]
multiple links/shortcuts in Unity ML-Agents Documentation are invalid

**Comment by eshvk** [comment]
Hi @jgarza9788, thanks for bringing this to our attention. It'd be great if you could give us more specifics and we'd be happy to update those links.

**Comment by mmattar** [comment]
Closing this issue - please reopen if you can share the invalid links. Thanks.
