### ISSUE TITLE
Doesn't work for LTS Build

### ISSUE THREAD

**Issue by sinhadanish** [Unity-Technologies/ml-agents#688]
Hi!

I am unable to create a build using Unity 2017.4.1.f1 LTS. Will there be a fix/support for that?

**Comment by xiaomaogy** [comment]
@sinhadanish Can you provide more details on this? Like the operating system you used, towards which platform are you building, and which environment are you building(your custom one or one of our example environment. )

**Comment by sinhadanish** [comment]
Hmm, reverted back to the previous version and it worked correctly.
If it happens again I will share exact steps or errors messages.

**Comment by mmattar** [comment]
Thanks @sinhadanish. Closing out this issue, but do submit a new one if you face any additional problems.
