### ISSUE TITLE
Exception in python

### ISSUE THREAD

**Issue by m-ronchi** [Unity-Technologies/ml-agents#693]
Hi,
I am trying to train my game.
I made 2 builds whose only difference is that I override AgentReset.

if I override AgentReset, I get this error in python:
```Traceback (most recent call last):
  File "python/learn.py", line 62, in <module>
    tc.start_learning()
  File "/execute/python/unitytrainers/trainer_controller.py", line 252, in start_learning
    text_action=take_action_text)
  File "/execute/python/unityagents/environment.py", line 503, in step
    raise UnityActionException("The episode is completed. Reset the environment with 'reset()'")
unityagents.exception.UnityActionException: The episode is completed. Reset the environment with 'reset()'
```

if I don't override, there is no error but the behavior is wrong (see #692 )

relevant code:

```
    bool act;
    public void TakeTurn() {
        act = true;
    }
    void FixedUpdate() {
        if (act) {
            RequestDecision ();
            act = false;
        }
    }
    public override void AgentReset () {
        base.AgentReset ();
        act = false;
    }
```

**Comment by xiaomaogy** [comment]
Where does your TakeTurn function gets called?

**Comment by m-ronchi** [comment]
Hi,
I changed a lot of stuff since then (both my code and ml-agents version), if I remember right it was during `AcademyStep` for at most one agent at a time (it's a turn based game, so at most one of the agents was allowed to act at a given step).

now I don't need to override `AgentReset` anymore, so the problem does not appear.

**Comment by mmattar** [comment]
Hi @m-ronchi - since it seems that you've resolved your problem, we're closing out this issue. Feel free to create another issue if you need any additional support.
