### ISSUE TITLE
Big difference in performance between training and running byte file in Unity

### ISSUE THREAD

**Issue by Lakrix** [Unity-Technologies/ml-agents#700]
Hi,

has anyone the same problem where there is a big performance difference of the agent during training and when using the byte file inside Unity? 

The agent performance is really good when visualising it during training. After that I interrupt the training and a byte file is created. I set the brain type to internal and then I use this byte file as the Graph Model inside Unity. When starting the game the performance is totally different. The agent is just doing random stuff.

**Comment by xiaomaogy** [comment]
Hi Lakrix, have you tried to run learn.py with inference mode(which don't have --train flag and have --load flag), and see what happens?

**Comment by Lakrix** [comment]
Yes that works well but when I use the most recent byte file then It behaves random when I run it inside Unity.

**Comment by DSobscure** [comment]
#614 
Is this problem? 
image in internal brain is not normalized, add / 255f to solve it

**Comment by Lakrix** [comment]
Yes this was the problem. Thank you.

**Comment by xiaomaogy** [comment]
Closing the issue since it is solved.
