### ISSUE TITLE
Vector Observation size mismatch.

### ISSUE THREAD

**Issue by Aarsh-Singh-Vishen** [Unity-Technologies/ml-agents#701]
hi! I've set up a project and this is the error I get when I try to run it.
"UnityAgentsException: Vector Observation size mismatch between discrete agent Agent and brain Brain. Was Expecting 1 but received 3. "

There is no error during compilation.

**Comment by xiaomaogy** [comment]
Hi Aarsh, this error is exactly what it says, please check your Brain Script's Brain Parameters -> Vector Observations -> Space Size number, and make sure it matches your vector observation size defined in your Agent code's CollectObservations method.

**Comment by Aarsh-Singh-Vishen** [comment]
These are my Brain Script's parameters :
![1](https://user-images.githubusercontent.com/31087556/39540292-d9144292-4e5f-11e8-8752-7147a49a87ff.png)

and this is the CollectObservations method:
  public override void CollectObservations()
    {
        AddVectorObs(pos);
       
    }

> make sure it matches your vector observation size defined in your Agent code's CollectObservations method.
This means that the Vector Observation size and the number of Observations added in the CollectObservations methos must be the same, yes?

If so, I  still get the same error.
PS: Total ml noob here, so if I get anything wrong, I apologize in advance

**Comment by jo3w4rd** [comment]
The meaning of "Space Size" is different depending on whether you set the "Space Type" to **Discrete** or **Continuous**. 

Here you have chosen **Discrete**, so you only pass a single value as the observation. This represents the which state from a table of states (or similar construct) the agent is in. Typically, the **Discrete** observation type is only useful for very simple scenarios.  

Probably what you want is to choose the **Continuous** "Space Type" for your observations.

**Comment by Aarsh-Singh-Vishen** [comment]
Well thanks! That helped, the error is gone although I do get another one:

NullReferenceException: Object reference not set to an instance of an object
Follow.AgentAction (System.Single[] vectorAction, System.String textAction) (at Assets/ML-Agents/Scripts/Follow.cs:48)
Agent.AgentStep () (at Assets/ML-Agents/Scripts/Agent.cs:859)
Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:481)
Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:507)

**Comment by jo3w4rd** [comment]
That usually happens when you try to use a member of an object that is null at runtime. Look around line 48 in your Follow script for objects that might not be set as you expect.

**Comment by Aarsh-Singh-Vishen** [comment]
Thanks for the help!!

**Comment by animaleja32** [comment]
Thanks for asking & answering this question :)
