### ISSUE TITLE
Graph model not saved.

### ISSUE THREAD

**Issue by Aarsh-Singh-Vishen** [Unity-Technologies/ml-agents#706]
![1](https://user-images.githubusercontent.com/31087556/39594776-4832f616-4f2b-11e8-8302-7a7bbc41b016.png)

So I train as shown but I can't find an output file for the training session. i.e. no file of the same name as the application is in the models\ppo folder.

![1](https://user-images.githubusercontent.com/31087556/39594931-a4fc9b54-4f2b-11e8-9c2b-889cae4de680.png)

this is what the Anaconda prompt looks after the training is closed
Any ideas on where the file is?
Also the file is saved in step 6 of the training right?

**Comment by eshvk** [comment]
@Aarsh-Singh-Vishen Unless you have significantly modified the `Basics.ipynb` notebook, the code there is designed to take random actions in the environment. This doesn't involve using say PPO to train a Policy. This is why you are not generating a Brain. I'd suggest using the `learn.py` script to get started with training.

**Comment by eshvk** [comment]
Yes, if you need more clarification on how things have changed, please take a look at the updated version of the [Balance Ball tutorial](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Getting-Started-with-Balance-Ball.md).

**Comment by Aarsh-Singh-Vishen** [comment]
Thanks for the help!
