### ISSUE TITLE
[Doc] Incorrect function name in docs

### ISSUE THREAD

**Issue by jo3w4rd** [Unity-Technologies/ml-agents#707]
In Learning-Environment-Design.md, under The Simulation and Training Process, step 5 mentions AcademyAct() function. It should be AcademyStep().

Should probably make sure the Academy decision loop is still the same using On-Demand decisions.

**Comment by xiaomaogy** [comment]
@jo3w4rd Are you going to issue a PR to fix this?

**Comment by jo3w4rd** [comment]
When I have time.

**Comment by awjuliani** [comment]
Hi All. I just fixed this on `develop`. Thanks for pointing it out, @jo3w4rd!
