### ISSUE TITLE
How to do Online Learning?

### ISSUE THREAD

**Issue by icaro56** [Unity-Technologies/ml-agents#708]
Online learning: https://en.wikipedia.org/wiki/Online_machine_learning

I have an idea, where I want to train an agent with Imitation Learning and after he is already trained, I would like him to continue learning at runtime. How can we do this with ML-Agent plugin?

**Comment by eshvk** [comment]
Hi @icaro56, the policy implemented by BC in theory can be training by online supervised learning. Having said that, this is not something we have currently implemented in the current release. It is likely to be computationally expensive (depending on what your run time device is ).

**Comment by icaro56** [comment]
I would like the agent continue learning alone (unsupervised) at runtime. Like RL.
