### ISSUE TITLE
Best way to reset the scene

### ISSUE THREAD

**Issue by icaro56** [Unity-Technologies/ml-agents#711]
What is the best way to reset the scene?

I am developing a game like Bomberman. When an agent is in Done state, I need to reset the entire scene: return destroyed blocks, other agents and etc for initial position, But the academy reset only is called in the begging of execution or when the max step is reached.

If I implement a global reset on AgentReset then I need to manage each AgentReset.

Should I call this command?
SceneManager.LoadScene(SceneManager.GetActiveScene().name);

**Comment by jo3w4rd** [comment]
You could implement AcademyStep() to check to see if the conditions are such that you need to reset the entire scene. If so, call Academy.Done(), which I believe will then trigger the AcademyReset() on the next cycle.

Reloading the scene would destroy your Communicator object and break the connection to Learn.py process.

**Comment by icaro56** [comment]
Thanks @jo3w4rd .

**Comment by icaro56** [comment]
@jo3w4rd , on the documentation is write:
    ```
/// The done flag of the academy. When set to true, the academy will
    /// call <see cref="AcademyReset"/> instead of <see cref="AcademyStep"/>
    /// at step time. If true, all agents done flags will be set to true.
    bool done;
```
So, I did the above code in MyAcademy, but the AcademyReset function was not called.

```
public override void AcademyReset()
    {
        Debug.Log("Hello");
    }

public override void AcademyStep()
    {
        if (GetStepCount() == 100)
        {
            base.Done();
         
        }
    }
```
In step 100 the academy should be reset.

Can I force the academy reset?

**Comment by icaro56** [comment]
The problem is in EnvironmentStep(). The test to reset on done is made before AcademyStep.

 ```
if (done)
        {
            EnvironmentReset();
        }

        AgentResetIfDone();

        AgentSendState();

        BrainDecideAction();

        AcademyStep();

        AgentAct();

        if (done)
        {
            done = false;
            maxStepReached = false;
        }
```

Then, after I set Done() in AcademyStep, the done is flag is set to false.

**Comment by icaro56** [comment]
@vincentpierre , this is not a bug. I must change Academy status to done elsewhere. I just can not use AcademyStep to do this.

**Comment by vincentpierre** [comment]
I think the Environment step logic has changed in version 0.4 Does this error persist ?

**Comment by icaro56** [comment]
I did not test it anymore. But looking at the code, the flow is still the same.

**Comment by alessiabertugli** [comment]
Has anyone solved the problem? I still have this issue with the last version of ml-agents (v0.5).

**Comment by vincentpierre** [comment]
I just tested the following code in a new component : 
```
using UnityEngine;
using MLAgents;


public class AcademyResetTest : MonoBehaviour
{
	private int test = 0;
	// Use this for initialization
	void Start () {
		
	}
	
	// Update is called once per frame
	void Update ()
	{
		test++;
		if (test > 10)
		{
			FindObjectOfType<Academy>().Done();
			test = 0;
		}
	}
}
```
And the Academy was reseting every 10 steps as expected. I tried something similar in the Academy Step and Reset logic in version 0.5. What is the problem you are experiencing and how can I reproduce it ?
