### ISSUE TITLE
Cube does not move.

### ISSUE THREAD

**Issue by Aarsh-Singh-Vishen** [Unity-Technologies/ml-agents#712]
So I have a really simple setup where a cube needs to get to its destination from a random spawn point.
I've trained the model but the cube doesn't even move.

Here's my code, please let me know where I'm wrong.

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;
public class Follow : Agent
{
   
    private BasicAcademy academy;
    public float timeBetweenDecisionsAtInference;
    private float timeSinceDecision;
    public int position;
    Vector3 pos;
    Vector3 destination;
    NavMeshAgent nagent;
    [SerializeField] GameObject final;
    void Start() {
        pos = this.gameObject.transform.position;
        nagent = this.gameObject.GetComponent<NavMeshAgent>();
    }
    public override void InitializeAgent()
    {
       
        academy = FindObjectOfType(typeof(BasicAcademy)) as BasicAcademy;
    }

    public override void CollectObservations()
    {
        AddVectorObs(pos);
       
    }

    public override void AgentAction(float[] vectorAction, string textAction)
    {
        float movement = vectorAction[0];

        switch ((int)vectorAction[0]) {
            case 0:
                pos = new Vector3(this.gameObject.transform.position.x, this.gameObject.transform.position.y, this.gameObject.transform.position.z + 0.1f);
                break;
            case 1:
                pos = new Vector3(this.gameObject.transform.position.x, this.gameObject.transform.position.y, this.gameObject.transform.position.z - 0.1f);
                break;
            case 2:
                pos = new Vector3(this.gameObject.transform.position.x+0.1f, this.gameObject.transform.position.y, this.gameObject.transform.position.z);
                break;
            case 3:
                pos = new Vector3(this.gameObject.transform.position.x - 0.1f, this.gameObject.transform.position.y, this.gameObject.transform.position.z);
                break;
            default:
                return;
        }
      
            nagent.SetDestination(pos);
            AddReward(-0.01f);

        if (Vector3.Distance(this.gameObject.transform.position, destination) > 5)
        {
            
            AddReward(-0.001f);
        }

        if (Vector3.Distance(this.gameObject.transform.position, destination) < 5)
        {
            Done();
            AddReward(0.001f);
        }
        if (Vector3.Distance(this.gameObject.transform.position, destination) < 3)
        {
            Done();
            AddReward(0.1f);
        }

    }

    public override void AgentReset()
    {
        Debug.Log("reset");
       gameObject.transform.position = new Vector3(Random.Range(10, 20), Random.Range(10, 20), Random.Range(10, 20));
        destination = new Vector3(0, 0, 0);
      
    }

    public override void AgentOnDone()
    {

    }

    public void FixedUpdate()
    {
        WaitTimeInference();
    }

    private void WaitTimeInference()
    {
        if (!academy.GetIsInference())
        {
            RequestDecision();
        }
        else
        {
            if (timeSinceDecision >= timeBetweenDecisionsAtInference)
            {
                timeSinceDecision = 0f;
                RequestDecision();
            }
            else
            {
                timeSinceDecision += Time.fixedDeltaTime;
            }
        }
    }

}
`

**Comment by Aarsh-Singh-Vishen** [comment]
These are the main bits of the code I guess.

`public override void AgentAction(float[] vectorAction, string textAction)
{
    float movement = vectorAction[0];

    switch ((int)vectorAction[0]) {
        case 0:
            pos = new Vector3(this.gameObject.transform.position.x, this.gameObject.transform.position.y, this.gameObject.transform.position.z + 0.1f);
            break;
        case 1:
            pos = new Vector3(this.gameObject.transform.position.x, this.gameObject.transform.position.y, this.gameObject.transform.position.z - 0.1f);
            break;
        case 2:
            pos = new Vector3(this.gameObject.transform.position.x+0.1f, this.gameObject.transform.position.y, this.gameObject.transform.position.z);
            break;
        case 3:
            pos = new Vector3(this.gameObject.transform.position.x - 0.1f, this.gameObject.transform.position.y, this.gameObject.transform.position.z);
            break;
        default:
            return;
    }
  
        nagent.SetDestination(pos);
        AddReward(-0.01f);

    if (Vector3.Distance(this.gameObject.transform.position, destination) > 5)
    {
        
        AddReward(-0.001f);
    }

    if (Vector3.Distance(this.gameObject.transform.position, destination) < 5)
    {
        Done();
        AddReward(0.001f);
    }
    if (Vector3.Distance(this.gameObject.transform.position, destination) < 3)
    {
        Done();
        AddReward(0.1f);
    }




}

public override void AgentReset()
{
    Debug.Log("reset");
   gameObject.transform.position = new Vector3(Random.Range(10, 20), Random.Range(10, 20), Random.Range(10, 20));
    destination = new Vector3(0, 0, 0);
  
}`

**Comment by jo3w4rd** [comment]
Your AgentAction(), CollectObservation(), and AgentReset() functions look fine, but you could comment out your FixedUpdate() function and let your Academy drive the Agent normally. 

I also find it helpful to set the Brain to Player with appropriate keystrokes to make sure that the mechanics of the scene works before running training. And then when first training, you can set the Academy's Training Configuration Time Scale to 1 so you can watch what the Agent is doing in realtime. (If it is behaving normally, you can set it back to 100 and rebuild the app for a full training run.)

**Comment by Aarsh-Singh-Vishen** [comment]
![1](https://user-images.githubusercontent.com/31087556/39663988-e90be812-5099-11e8-908d-dcea931285b1.png)
Umm I tried setting the Brain to player and gave it values and hotkeys, but when I play it during player mode, the cube moves forward, slowly, by itself. pressing any of the hotkeys does not make the cube do anything. Any ideas?

**Comment by Aarsh-Singh-Vishen** [comment]
Changing the Default action during runtime with Brain set as player does make the cube change directions. But pressing the keys still does not help

**Comment by vincentpierre** [comment]
I would try to Debug.Log `(int)vectorAction[0]` just to see if the pressing the keys changes its value or not. If it is not the case, there is most likely a problem with the mapping from keys to actions. If `(int)vectorAction[0]` changes as expected, there might be a problem with `SetDestination`.
