### ISSUE TITLE
Unnecessary to auto-resolve 'brain' dependency

### ISSUE THREAD

**Issue by stevesan** [Unity-Technologies/ml-agents#714]
https://github.com/Unity-Technologies/ml-agents/blob/13beeac72759ccb57a872aadea96c3cacaeb5ffd/unity-environment/Assets/ML-Agents/Examples/PushBlock/Scripts/PushAgentBasic.cs#L53

I was modifying the agent for learning purposes, and this line caused me a couple of hours of confused debugging. Doesn't seem necessary for the example scenes, and definitely bad practice.

**Comment by awjuliani** [comment]
Hi @stevesan,

Thanks for pointing this out. I am tagging this issue as a bug, as this line should be removed from the code.

**Comment by awjuliani** [comment]
Hi @stevesan,

This issue has been fixed in v0.4. As such, I will be closing out this issue.
