### ISSUE TITLE
Error when i try to train any of examples

### ISSUE THREAD

**Issue by ToZaho** [Unity-Technologies/ml-agents#715]
I was trying to train some examples, until an error started to show in command prompt when running learn.py: https://pastebin.com/z0VvEcNv

And in output log of the game, that was started by learn.py, was this error: https://pastebin.com/Kz6ZDAYq

What is causing it and how can i fix it?

**Comment by xiaomaogy** [comment]
@ToZaho Which os platform are you running this on? Also which branch of ml-agents are you using?

**Comment by ToZaho** [comment]
@xiaomaogy I'm running Windows 10.
I don't know which branch I'm using. I didn't even know, that there are more of them. Could you tell me where I can find which I'm using?

Also, I don't know, if it was clear from the first comment, but few times I've been able to run it.

**Comment by xiaomaogy** [comment]
@ToZaho I think learning Git would be really helpful for you to know which branch you are using. Also just looking at your log file doesn't really help me debug the issue for you. Are you training using one of our example environment?

**Comment by vincentpierre** [comment]
@ToZaho I am looking at the error messages you get and I see 

```
Make sure Ball does not need user interaction to launch and that the Academy and the external Brain(s) are attached to objects in the Scene.
```
Did you set the brain to `External` in the scene ?

**Comment by ToZaho** [comment]
@xiaomaogy Ok, I thought that the error should tell you what's wrong...

This is **exactly** what i've done:
I've downloaded ml-agents, read how to use it, opened the **ball example**, imported TFSharpPlugin, set **ENABLE_TENSORFLOW** symbol, restarted Unity, set brain type to **External**, compiled it and trained it. It **worked**.

Then I tried to **change** some public **values of Ball3DAgent**.

But after few times doing the same thing again, **platforms did not moved** (it moved always while 
it was training) and **returned those errors**. I've checked everything, returned to the original example values, searched the error on the internet (I found that it could be becouse some libraries are damaged, so i tried to reinstall them), but nothing was useful. I've also tried some more examples, but it throws the same error. Lastly I wrote this issue and hoped, that someone can help me.

**Comment by xiaomaogy** [comment]
All of the steps you've done seems correct on my end, and it should work. Maybe you can clone a fresh repo and try again, since you said it worked for you initially. Once you've reached some places that make it no longer work, you tell us what that issue is, which will enable us to help you.

**Comment by ToZaho** [comment]
Well, I've installed everything from the beginning and it's now working again. I don't know where the problem was. The thing that helped was probably running the setup.py file. I done it before, but newer version is always better.
Thank you for the help.
