### ISSUE TITLE
Can't SerializeField a variable on my agent script.

### ISSUE THREAD

**Issue by Aarsh-Singh-Vishen** [Unity-Technologies/ml-agents#719]
I have an agent script but I can't get one of its variables to be seen in the inspector?

**Comment by vincentpierre** [comment]
Maybe [this](https://answers.unity.com/questions/361040/c-variables-not-showing-up-in-inspector.html) will help. I think this is more a Unity question than a ML-Agents question. I think you need to make your variable public for it to show up in the inspector.

**Comment by Aarsh-Singh-Vishen** [comment]
Thanks!
