### ISSUE TITLE
Cannot start any Scene because of CoreBrainInternal.cs

### ISSUE THREAD

**Issue by lagidigu** [Unity-Technologies/ml-agents#722]
Hi!

I have ENABLE_TENSORFLOW in Scripting Define Symbols, and installed all the dependencies. I am getting the following errors: 

> Assets/ML-Agents/Scripts/CoreBrainInternal.cs(12,7): error CS0246: The type or namespace name `TensorFlow' could not be found. Are you missing an assembly reference?

> Assets/ML-Agents/Scripts/CoreBrainInternal.cs(70,5): error CS0246: The type or namespace name `TFGraph' could not be found. Are you missing an assembly reference?

> Assets/ML-Agents/Scripts/CoreBrainInternal.cs(71,5): error CS0246: The type or namespace name `TFSession' could not be found. Are you missing an assembly reference?

Tensorflow is installed, so I am not sure what the problem is. I cannot run the scene to begin with...

**Comment by oddEventHorizon** [comment]
Why was this closed? Was it resolved somehow? I have exactly the same issue. 

The moment I remove ENABLE_TENSORFLOW from Scripting Define Symbols. Everything is fine. When I put it back again i get pretyy much the same errors are ladigu. I've been looking for potential solutions for a few days now without luck. I even reinstalled unity and started a new project but this didn't help.
