### ISSUE TITLE
More than one visual observation - ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by denisamselem** [Unity-Technologies/ml-agents#723]
Hello there,

Has anyone been able to use 2 Visual Observations successfully?
Training and generating the model appears to be working but there seems to be an issue while using the generated model in internal mode. At runtime the Unity console will spit out the following exceptions:

**First exception (only reported once)** 
```
NullReferenceException: Object reference not set to an instance of an object
CoreBrainInternal.DecideAction (System.Collections.Generic.Dictionary`2[TKey,TValue] agentInfo) (at Assets/ML-Agents/Scripts/CoreBrainInternal.cs:308)
Brain.DecideAction () (at Assets/ML-Agents/Scripts/Brain.cs:241)
Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:477)
Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:507)

```

**Second exception: reported every frame**
```
ArgumentException: An item with the same key has already been added.
System.ThrowHelper.ThrowArgumentException (System.ExceptionResource resource) (at /Users/builduser/buildslave/mono/build/mcs/class/referencesource/mscorlib/system/throwhelper.cs:72)
System.Collections.Generic.Dictionary`2[TKey,TValue].Insert (TKey key, TValue value, System.Boolean add) (at /Users/builduser/buildslave/mono/build/mcs/class/referencesource/mscorlib/system/collections/generic/dictionary.cs:336)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at /Users/builduser/buildslave/mono/build/mcs/class/referencesource/mscorlib/system/collections/generic/list.cs:424)
Brain.SendState (Agent agent, AgentInfo info) (at Assets/ML-Agents/Scripts/Brain.cs:234)
Agent.SendInfoToBrain () (at Assets/ML-Agents/Scripts/Agent.cs:566)
Agent.SendInfo () (at Assets/ML-Agents/Scripts/Agent.cs:829)
Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:475)
Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:507)


```
I have stepped through the code at runtime and was able to spot something odd in **CoreBraininternal.cs** when introspecting the 'graph' and 'VisualObservationPlaceholderName' variables:

While the 'VisualObservationPlaceholderName' array does seem to hold 2 valid entries :

```
VisualObservationPlaceholderName[0] : "visual_observation_0"
VisualObservationPlaceholderName[1] : "visual_observation_1"
```

The graph object appears confused :
```
graph[graphScope + VisualObservationPlaceholderName[0]] : null
graph[graphScope + VisualObservationPlaceholderName[1]] : {TensorFlow.TFOperation}
```
So, it sounds like somehow the first visual observation goes missing - hard to tell if it's missing from the model that's been generated in the first place or if something else if going on.

I've followed the pretty straightforward instructions on how to add a second visual observation but I could be missing something.
Searched through the closed and open issues but didn't find anything in there.
Any kind of input / suggestion will be appreciated,
Thanks all

**Comment by vincentpierre** [comment]
Hi, are you using 0.3.1? There was a but in 0.3.0 where the generated model would only contain the last visual observation. Can you try visualizing the graph the graph in Tensorboard and tell us if the "visual_observation_0" is used to generate the action ?

**Comment by denisamselem** [comment]
That was it! 
I was on 0.3.0b and moving to 0.3.1 solved the issue.
Thanks again @vincentpierre ,
You and the rest of the team keep up the good work.
