### ISSUE TITLE
Access Python Script from Unity Android App locally (without http request and response on server)

### ISSUE THREAD

**Issue by abhibagadi** [Unity-Technologies/ml-agents#73]
Hello Everyone,

I am a beginner in Unity environment, want to do:

1. Take images by accessing camera through unity
2. Access those images from python script for some image processing (**_not_** using **_http_** request). _I want to run python script locally in Unity app_
3. Access those processed images from python script to Unity
4. Use few more functionality of Unity such as animation and audio api for further processing

Can anybody please help me out??

**Comment by awjuliani** [comment]
Hi @abhibagadi,

We currently don't support accessing Python from Unity on Android. What is the specific case for this? If you'd like to use a Tensorflow model on the python side, you can use our TensorFlowSharp support to integrate the model directly into Unity: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-TensorFlow-Sharp-in-Unity-(Experimental).md
