### ISSUE TITLE
Unexpected behavior of EpisodeCount and AcademyReset (develop branch)

### ISSUE THREAD

**Issue by MarcoMeter** [Unity-Technologies/ml-agents#733]
On the Unity side I wrote some code to log some statistics to a csv file on each end of an episode.
For that reason I'm using the override of AcademyReset().

While working on that, I encountered some strange behavior. The summaries, the agents and the Academy have a maxStep of 1k. Running for 300k steps should result in 300 episodes, however the actual episode count after 300k steps was 600. So it seems to be that EnvironmentReset() is called twice before each episode.

**Comment by vincentpierre** [comment]
This looks like a bug to me, can you try with agent having max step to 0? Can you reproduce this on develop? I think it could be an error of implementation of the ForcedFullReset method.

**Comment by awjuliani** [comment]
Hi @vincentpierre were you able to address this bug?

**Comment by vincentpierre** [comment]
I was not able to reproduce this bug as of v0.4
@MarcoMeter Does the problem persist for you ?
