### ISSUE TITLE
SoccerTwos observation space

### ISSUE THREAD

**Issue by alexisbcook** [Unity-Technologies/ml-agents#734]
In the [docs](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Examples.md#soccer-twos), I read that the observation space has size 112. 
When I built the environment, the observation space for each agent was size 336.
Is this an error in my environment or a small typo in the docs?

**Comment by vincentpierre** [comment]
This is probably due to Staked Vectors being set to 3 in the brain inspector. See [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design-Brains.md#brain-properties) for details on the brain properties.

**Comment by alexisbcook** [comment]
makes sense. thanks!
