### ISSUE TITLE
.bytes files, and exporting them

### ISSUE THREAD

**Issue by theforgottenmachine** [Unity-Technologies/ml-agents#735]
Hi, 

Is there any information on how to export .bytes model files and use them elsewhere? Are these just standard tensorflow models or is there something special here?

Thanks!

**Comment by vincentpierre** [comment]
`.bytes` files are just `.pb` files renamed as .`bytes` files so Unity will be able to load them. If you rename them, they should still be usable. We use `freeze_graph` to generate the graph, it is a standard way to generate TensorFlow graphs.

**Comment by nadir500** [comment]
it's not working @vincentpierre  :/ 
gave me this error 
btw i am working with the speech commands example on tensorflow to generate a .pb model and then export it to unity 
unity 2018.1.0f2
``TFException: Shape must be rank 1 but is rank 0 for 'Mfcc' (op: 'Mfcc') with input shapes: [16000,0,257], [].
TensorFlow.TFStatus.CheckMaybeRaise (TensorFlow.TFStatus incomingStatus, System.Boolean last) (at <6ed6db22f8874deba74ffe3e566039be>:0)
TensorFlow.TFGraph.Import (TensorFlow.TFBuffer graphDef, TensorFlow.TFImportGraphDefOptions options, TensorFlow.TFStatus status) (at <6ed6db22f8874deba74ffe3e566039be>:0)
TensorFlow.TFGraph.Import (System.Byte[] buffer, ``

**Comment by xiaomaogy** [comment]
@nadir500 The .pb file needs to be in specific format for it to work. Please refer to our code on how we generated the .bytes file.

**Comment by mmattar** [comment]
Hi @nadir500 - are you still facing any issues?

**Comment by mmattar** [comment]
Closing this issue for now, but please re-open if you continue facing issues.

**Comment by bhamapillutla** [comment]
not able to convert .pb file to .bytes for SSD mobilenetv1 object detection custom data for unity 
please assist urgent requirement
