### ISSUE TITLE
Curriculum training by multiplebrains

### ISSUE THREAD

**Issue by YuMurata** [Unity-Technologies/ml-agents#736]
hi there

i have 2 agents and brains, avoider(brain 1) and shooter(brain 2).
i want to use different curriculum to train them 
and use "reward" for parameter of "measure"
can i use curriculum  for each brains ?

thanks!

**Comment by vincentpierre** [comment]
As of now, no. Curriculum will look at the sums of the rewards. An alternative would be to use the number of steps as threshold. Upgrading the curriculum to support these things is on our roadmap.

**Comment by YuMurata** [comment]
i got it
im looking forward to upgrade :)
thanks!
