### ISSUE TITLE
Can I implement curriculum training with ml-agents?

### ISSUE THREAD

**Issue by dora-gt** [Unity-Technologies/ml-agents#74]
I have a question. Can I implement curriculum training with ml-agents?
If I can, how should I implement it?

**Comment by awjuliani** [comment]
Hi @dora-gt,

Curriculum training is supported through the `reset parameters`. For an Academy you can set reset parameters, and then use them to adjust how the environment is initialized when it is reset. From python, you can set `config=` to a dictionary containing the reset parameters defined on the Unity side. Hopefully that helps. For an example, check out the `GridWorld` example, which uses grid size as a reset parameter.

**Comment by dora-gt** [comment]
Thank you so much @awjuliani ,

I look into `GridWorld` sample.

One more thing, is it normal to switch reward logic according to curriculum?
For example,

```
// CurriculumType is enum

if (CurriculumType.EasyOne)
{
    if (Hoge is true)
}
else if (CurriculumType.HardOne)
{
}
```

**Comment by awjuliani** [comment]
Hi @dora-gt,

It would be best to keep the reward function as similar as possible, but to change other things about the environment. If it is a first-person shooter game for example, killing an enemy might be +0.1 reward. It would be +0.1 under all circumstances, but the strength or speed of the opponent might change based on the curriculum.

**Comment by dora-gt** [comment]
Thank you so much. I'll try so.

**Comment by dora-gt** [comment]
Hi @awjuliani ,

Do you mean setting `config=` is customizing this line?
https://github.com/Unity-Technologies/ml-agents/blob/master/python/ppo.py#L103
