### ISSUE TITLE
Mean reward always remains negative.

### ISSUE THREAD

**Issue by Aarsh-Singh-Vishen** [Unity-Technologies/ml-agents#743]
`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;
public class Follow : Agent
{

    private BasicAcademy academy;
    public float timeBetweenDecisionsAtInference;
    private float timeSinceDecision;
    public int position;
    Vector3 pos;
    public Vector3 destination;
    Vector3 start_pos;
    NavMeshAgent nagent;
    [SerializeField] GameObject finish;
    void Start()
    {
        start_pos = this.gameObject.transform.position;
        pos = this.gameObject.transform.position;
        nagent = this.gameObject.GetComponent<NavMeshAgent>();
        destination = new Vector3(0, 0, 0);

    }
    public override void InitializeAgent()
    {

        academy = FindObjectOfType(typeof(BasicAcademy)) as BasicAcademy;
    }

    public override void CollectObservations()
    {

        AddVectorObs(pos);
      

    }

    public override void AgentAction(float[] vectorAction, string textAction)
    {

        float movement = vectorAction[0];
        destination = new Vector3(0, 0, 0);
        switch ((int)vectorAction[0])
        {
            case 0:
                pos = new Vector3(this.gameObject.transform.position.x, this.gameObject.transform.position.y, this.gameObject.transform.position.z + 2f);
                nagent.SetDestination(pos);
                AddReward(-0.01f);

                if (Vector3.Distance(this.gameObject.transform.position, destination) > 3)
                {
                    Debug.Log("away");
                    AddReward(-0.01f);

                }

                if (Vector3.Distance(this.gameObject.transform.position, destination) < 3)
                {
                    AddReward(1f);
                    Done();

                }

                break;
            case 1:
                pos = new Vector3(this.gameObject.transform.position.x, this.gameObject.transform.position.y, this.gameObject.transform.position.z - 2f);

                nagent.SetDestination(pos);
                AddReward(-0.01f);

                if (Vector3.Distance(this.gameObject.transform.position, destination) > 3)
                {
                    Debug.Log("awayfrom");
                    AddReward(-0.01f);

                }

                if (Vector3.Distance(this.gameObject.transform.position, destination) < 3)
                {
                    AddReward(1f);
                    Done();

                }

                break;
            case 2:
                pos = new Vector3(this.gameObject.transform.position.x + 2f, this.gameObject.transform.position.y, this.gameObject.transform.position.z);
                nagent.SetDestination(pos);
                AddReward(-0.01f);

                if (Vector3.Distance(this.gameObject.transform.position, destination) > 3)
                {
                    Debug.Log("away");
                    AddReward(-0.01f);

                }

                if (Vector3.Distance(this.gameObject.transform.position, destination) < 3)
                {
                    AddReward(1f);
                    Done();

                }

                break;
            case 3:
                pos = new Vector3(this.gameObject.transform.position.x - 2f, this.gameObject.transform.position.y, this.gameObject.transform.position.z);

                nagent.SetDestination(pos);
                AddReward(-0.01f);

                if (Vector3.Distance(this.gameObject.transform.position, destination) > 3)
                {
                    Debug.Log("away");
                    AddReward(-0.01f);

                }

                if (Vector3.Distance(this.gameObject.transform.position, destination) < 3)
                {
                    AddReward(1f);
                    Done();

                }

                break;
            case 4:
                pos = this.gameObject.transform.position;
                nagent.SetDestination(pos);
                AddReward(-0.01f);

                if (Vector3.Distance(this.gameObject.transform.position, destination) > 3)
                {
                    Debug.Log("away");
                    AddReward(-0.01f);

                }

                if (Vector3.Distance(this.gameObject.transform.position, destination) < 3)
                {
                    AddReward(1f);
                    Done();

                }

                break;
            default:

                return;
        }
     

    }

    public override void AgentReset()
    {
        Debug.Log("reset!");
        gameObject.transform.position = new Vector3(Random.Range(-15,15),0, Random.Range(-15, 15));

    }

    public override void AgentOnDone()
    {
        Debug.Log("done");
      
    }

    /* public void FixedUpdate()
     {
         WaitTimeInference();
     }
 */
    private void WaitTimeInference()
    {
        if (!academy.GetIsInference())
        {
            RequestDecision();
        }
        else
        {
            if (timeSinceDecision >= timeBetweenDecisionsAtInference)
            {
                timeSinceDecision = 0f;
                RequestDecision();
            }
            else
            {
                timeSinceDecision += Time.fixedDeltaTime;
            }
        }
    }

}`

My mean reward just does not become positive, in fact as of now it stays at -20. Any ideas why?

**Comment by vincentpierre** [comment]
* Have you made sure a player Brain or a heuristic brain can solve the problem ?
 * You should normalize your inputs, divide `pos` by 15 before calling AddVectorObs
 * Did you make sure that the action space size was set to 4 in the brain inspector?
 * You could try to increase the distance threshold for the agent to meet the goal to make sure it works.
 * You could penalize the agent by a number proportional to the distance to the goal to make sure it works.

I hope this helps

**Comment by Aarsh-Singh-Vishen** [comment]
Thanks, I'll check it out and get back to you!

**Comment by Aarsh-Singh-Vishen** [comment]
The problem was that I set the negative reward for taking a step as too high. 
Lowering it helped! Thanks :)
