### ISSUE TITLE
Vector Observation Size Mismatch Error

### ISSUE THREAD

**Issue by BenM77** [Unity-Technologies/ml-agents#748]
I am getting the following exception:
UnityAgentsException: Vector Observation size mismatch between continuous agent Enemy and brain Brain. Was Expecting 29 but received 33. 
Agent.SendInfoToBrain () (at Assets/ML-Agents/Scripts/Agent.cs:518)
Agent.SendInfo () (at Assets/ML-Agents/Scripts/Agent.cs:829)
Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:475)
Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:507)

In my script I use AddVectorObs() 29 times, but somehow it receives 33. If I tell it to expect 33, then it says it received 38. If it tell to expect 38, it receives 33 first. Somehow it is sending different amounts of observations?

![capture](https://user-images.githubusercontent.com/34111213/39965015-dd6bdf7e-5645-11e8-80aa-a63b278c3bbe.JPG)

public override void CollectObservations()
    {
        List<float> platformsX = new List<float>();
        List<float> platformsY = new List<float>();

        List<float> weaponsX = new List<float>();
        List<float> weaponsY = new List<float>();

        List<float> thrownWeaponsX = new List<float>();
        List<float> thrownWeaponsY = new List<float>();

        List<float> weaponsVelocityX = new List<float>();
        List<float> weaponsVelocityY = new List<float>();

        List<float> thrownWeaponsVelocityX = new List<float>();
        List<float> thrownWeaponsVelocityY = new List<float>();

        List<float> weaponTypes = new List<float>();
        List<float> thrownWeaponTypes = new List<float>();

        //relative values used to give normalized inputs from -1 to 1 to the neural network
        foreach (Transform platform in platforms)
        {
            platformsX.Add((transform.position.x - platform.transform.position.x) / halfWorldSpaceSize);//position relative to all platforms present
            platformsY.Add((transform.position.y - platform.transform.position.y) / halfWorldSpaceSizeVertical);
        }
        AddVectorObs(platformsX);
        AddVectorObs(platformsY);

        int weaponType;
        foreach (Transform weapon in weapons)
        {
            weaponsX.Add((transform.position.x - weapon.position.x) / halfWorldSpaceSize);//position relative to all spawned weapons
            weaponsY.Add((transform.position.y - weapon.position.y) / halfWorldSpaceSizeVertical);

            weaponsVelocityX.Add(weapon.GetComponent<Rigidbody2D>().velocity.x / halfWorldSpaceSize);
            weaponsVelocityY.Add(weapon.GetComponent<Rigidbody2D>().velocity.y / halfWorldSpaceSizeVertical);

            if (weapon.tag == "mace")
                weaponType = 0;
            else if (weapon.tag == "grenade")
                weaponType = 1;
            else if (weapon.tag == "boomerang")
                weaponType = 2;
            else if (weapon.tag == "bow")
                weaponType = 3;
            else if (weapon.tag == "spear")
                weaponType = 4;
            else//gun
                weaponType = 5;
            weaponTypes.Add(weaponType);
        }

        AddVectorObs(weaponsX);
        AddVectorObs(weaponsY);

        AddVectorObs((transform.position.x - player.transform.position.x) / halfWorldSpaceSize);//position relative to player
        AddVectorObs((transform.position.y - player.transform.position.y) / halfWorldSpaceSizeVertical);

        AddVectorObs((transform.position.x + halfWorldSpaceSize) / halfWorldSpaceSize);//position relative to walls
        AddVectorObs((transform.position.x - halfWorldSpaceSize) / halfWorldSpaceSize);
        AddVectorObs((transform.position.y + halfWorldSpaceSizeVertical) / halfWorldSpaceSizeVertical);
        AddVectorObs((transform.position.y - halfWorldSpaceSizeVertical) / halfWorldSpaceSizeVertical);

        AddVectorObs(enemyRGB2D.velocity.x / halfWorldSpaceSize);//relative velocity
        AddVectorObs(enemyRGB2D.velocity.y / halfWorldSpaceSizeVertical);
        AddVectorObs(player.gameObject.GetComponent<Rigidbody2D>().velocity.x / halfWorldSpaceSize);
        AddVectorObs(player.gameObject.GetComponent<Rigidbody2D>().velocity.y / halfWorldSpaceSizeVertical);

        AddVectorObs(activeWeapon);//current weapons
        AddVectorObs(player.activeWeapon);

        AddVectorObs(player.health);//health standings
        AddVectorObs(enemy.health);

        AddVectorObs(enemyWeaponPickup.activeSprite.uses);//ammo (-1 if N/A)
        AddVectorObs(playerWeaponPickup.activeSprite.uses);

        foreach(Transform thrownWeapon in thrownWeapons)//weapons to avoid
        {
            thrownWeaponsX.Add((transform.position.x - thrownWeapon.transform.position.x) / halfWorldSpaceSize);
            thrownWeaponsY.Add((transform.position.y - thrownWeapon.transform.position.y) / halfWorldSpaceSizeVertical);

            thrownWeaponsVelocityX.Add(thrownWeapon.GetComponent<Rigidbody2D>().velocity.x / halfWorldSpaceSize);
            thrownWeaponsVelocityY.Add(thrownWeapon.GetComponent<Rigidbody2D>().velocity.y / halfWorldSpaceSizeVertical);

            if (thrownWeapon.tag == "mace")
                weaponType = 0;
            else if (thrownWeapon.tag == "grenade")
                weaponType = 1;
            else if (thrownWeapon.tag == "boomerang")
                weaponType = 2;
            else if (thrownWeapon.tag == "bow")
                weaponType = 3;
            else if (thrownWeapon.tag == "spear")
                weaponType = 4;
            else//gun
                weaponType = 5;
            thrownWeaponTypes.Add(weaponType);
        }

        AddVectorObs(thrownWeaponsX);
        AddVectorObs(thrownWeaponsY);

        AddVectorObs(weaponsVelocityX);
        AddVectorObs(weaponsVelocityY);

        AddVectorObs(thrownWeaponsVelocityX);
        AddVectorObs(thrownWeaponsVelocityY);

        AddVectorObs(weaponTypes);
        AddVectorObs(thrownWeaponTypes);

        int jumps;
        if (enemy.grounded)
            jumps = 0;
        else if (!enemy.doubleJump)
            jumps = 1;
        else
            jumps = 2;

        AddVectorObs(jumps);
    }

**Comment by mbaske** [comment]
AddVectorObs(thrownWeaponTypes);
You're passing a list here whose size depends on thrownWeapons. Maybe the size of your thrownWeapons list varies?

**Comment by BenM77** [comment]
Does that matter? I'm still passing in the same amount of lists no matter what. Otherwise, how would you handle tracking a variable amount of objects present in the scene?

**Comment by mbaske** [comment]
Yes, passing a list to AddVectorObs increases the size of the agents vector observation by the size of that list.
If you know the max number of objects you want to track, then you could always pass a list of that size. And set a specific value for objects that aren't present at a given observation. Like a weaponType "none".
