### ISSUE TITLE
Training not executing

### ISSUE THREAD

**Issue by BenM77** [Unity-Technologies/ml-agents#749]
When i tell my anaconda prompt to train my agent, it doesn't actually do anything.
<img width="960" alt="2018-05-13" src="https://user-images.githubusercontent.com/34111213/39974148-95e92b3e-56db-11e8-8256-172697249dce.png">

**Comment by vincentpierre** [comment]
I think it might be because of the white spaces in the folders you have. Can you try wrap your paths into double quotes ? Or Put the project in a path that does not contain white space ?

**Comment by BenM77** [comment]
It was because I was using a .apk instead of a .exe. It worked after building to standalone PC/Mac/Linux instead of Android. It seems like it is intended to work with building to any platform, but if not it should be clarified that .exe must be used.
