### ISSUE TITLE
How to train multiple times

### ISSUE THREAD

**Issue by dora-gt** [Unity-Technologies/ml-agents#75]
How can I train multiple times?
For example...

1. Run `python3 ppo.py <env_name> --train`.
2. Python correctly quits.

If I want to train more, what should I do?
Run `python3 ppo.py <env_name> --train --load`?

**Comment by SPINACHCEO** [comment]
Hi, you should increase the max_steps in python. Or change the loop condition.

**Comment by dora-gt** [comment]
So you mean that training process should be done at a time?

**Comment by awjuliani** [comment]
Hi @dora-gt,

If the training process ends and you want to train longer, use `--train --load --max-steps=<your new value>`

**Comment by dora-gt** [comment]
thank you so much!
