### ISSUE TITLE
Using two adversial brains and I get this error while I run it with Internal brain.

### ISSUE THREAD

**Issue by Aarsh-Singh-Vishen** [Unity-Technologies/ml-agents#757]
> UnityAgentsException: The node action could not be found. Please make sure the graphScope  is correct
CoreBrainInternal.DecideAction (System.Collections.Generic.Dictionary`2[TKey,TValue] agentInfo) (at Assets/ML-Agents/Scripts/CoreBrainInternal.cs:251)
Brain.DecideAction () (at Assets/ML-Agents/Scripts/Brain.cs:241)
Academy.EnvironmentStep () (at Assets/ML-Agents/Scripts/Academy.cs:477)
Academy.FixedUpdate () (at Assets/ML-Agents/Scripts/Academy.cs:507)

Any ideas?

**Comment by vincentpierre** [comment]
Is the graphScope correct ?
When you finished training with `learn.py`, there should have been a message with the names of the exported nodes and the graphScopes present in the graph. You must use the appropriate graph scope in the Internal Brain. In theory, it should be the brain name with some escaping on it. You can look at `GoalieBrain` and `StrikerBrain` in the `SoccerTwos` example.
I hope this helps.

**Comment by Aarsh-Singh-Vishen** [comment]
Yup this works  Thanks! :)
