### ISSUE TITLE
Best practice for hierarchical RL?

### ISSUE THREAD

**Issue by mbaske** [Unity-Technologies/ml-agents#758]
Hi - I have a robot agent with two brains. The low level brain controls walking while the high level brain is concerned with navigation. They have different  observation and action spaces. I was able to train each of them individually and would now like to continue training them together. What is the recommended way to set this up? My guess is I'll need to keep two distinct agent classes, but I'm not sure how to deal with their different decision frequencies, episode lengths, rewards etc during training. Thanks.

**Comment by vincentpierre** [comment]
Hi, this is a super cool idea for a project. I think you need 2 agents classes yes. I would have the high level take decisions with On-demand-decision and the low level have a fixed decision frequency. The action of the high level should be included in the observations of the agent (we do not have a way to specify goals yet, so this is the closest thing I can think of). I think episode length should not be fixed (except maybe in the academy) but the two agents should reset at the same time (The done flag should be passed simultaneously. Rewards should remain the same as when you trained them separately I think. I hope this helps, let us know about your findings !

**Comment by mbaske** [comment]
@vincentpierre Thanks for your input on this! The project is finally up and running.
https://www.youtube.com/watch?v=iUOOoM0NLlo
https://github.com/mbaske/robot-ants

**Comment by lagidigu** [comment]
@mbaske sick!

**Comment by mmattar** [comment]
Demo video looks fantastic @mbaske! Closing out this issue as things to seem have worked out. Do continue to share with us any additional projects you create.
