### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'PngImageFile' and 'float'

### ISSUE THREAD

**Issue by SPINACHCEO** [Unity-Technologies/ml-agents#76]
Hi there.
When I train with a camera observation, 
TypeError: unsupported operand type(s) for /: 'PngImageFile' and 'float'
is raised in python during training.

Is this a bug or it could because my wrong configuration ?
I am sure there's not errors in my Unity3D environment.

**Comment by SPINACHCEO** [comment]
`python/unityagents/environment.py in _process_pixels(image_bytes, bw)
    140         s = bytearray(image_bytes)
    141         image = Image.open(io.BytesIO(s))
--> 142         s = np.array(image) / 255.0
    143         if bw:
    144             s = np.mean(s, axis=2)

TypeError: unsupported operand type(s) for /: 'PngImageFile' and 'float'`

for more information

**Comment by awjuliani** [comment]
Hi @SPINACHCEO,

I think this may be related to your version of Pillow. Can you let me know what version it is?

**Comment by SPINACHCEO** [comment]
Hi @awjuliani 
I think I am using the latest version.
I don't think this could be the problem with Pillow cause it only throw "sometimes".
Usually around 1000~2000 successful steps.
Could this because of some problem with socket ?

**Comment by SPINACHCEO** [comment]
Anyone help, please ?

**Comment by awjuliani** [comment]
@SPINACHCEO,

What is the size of the camera observation you are trying to send over? I believe there is an issue when sending cameras over which are larger than 100x100 or so.

**Comment by SPINACHCEO** [comment]
Hi, thanks. I was using 128 * 128. And that's the problem.
Please forgive me if there is any documentation that already mentioned this.
