### ISSUE TITLE
3DBall example, learns but doesnt play in Unity

### ISSUE THREAD

**Issue by aschmitz13** [Unity-Technologies/ml-agents#760]
I am currently setting up ML Agents and tried the tutorial here on the website. Everything works fine. When i use "python python/learn.py python/3dball.exe --train", I can see 3dball window and I see the agents improving. I can visualize with tensorboard as well. Once it is finished i got a .bytes file (this file is named slightly different than in the tutorial: 3DBall_ppo.bytes).

But when i load it in Unity (set Ball3dBrain to internal, put the new bytes file in) nothing happens. the ball just falls down. But when i load the 3DBall.bytes which is delivered within the package it works perfectly.

What do i do wrong?

Version Information:
Python 3.5.2
Tensorflow 1.8.0
Unity 2018.1.0f2

**Comment by aschmitz13** [comment]
Ok i found the solution for now. tensorflow 1.8.0 is not working with ml-agents. it has to be tensorflow 1.4.0

**Comment by icaro56** [comment]
@aschmitz13, close this topic.

I had this same problem a few months ago.
