### ISSUE TITLE
Best practice to define hidden-units?

### ISSUE THREAD

**Issue by dora-gt** [Unity-Technologies/ml-agents#78]
Hi.

I would like to know how to set `hidden-units`.

`--hidden-units=<n>         Number of units in hidden layer [default: 64].`

Does `hidden-units` mean the number of layers? or the number of neurons?
Can I modify it after trainings and train again? How should I define it?

For example, my network is like...

Input: 8
Output: 3
Environment: driving a car to go to given position

Could you tell me?

Maybe I should use tensorboard, but I am not used to it, don't know the vital point.

**Comment by awjuliani** [comment]
Hi @dora-gt,

Hidden units correspond to how many neurons in each of the hidden layers of the neural network. The default is 64, but for more complex problems this may be too few. Once the neural network is trained using a specific set of hidden units, the number cannot be adjusted without the need to retrain the model. Here is a discussion of neural networks and hidden units which may be helpful: https://stats.stackexchange.com/questions/63152/what-does-the-hidden-layer-in-a-neural-network-compute

**Comment by dora-gt** [comment]
Thank you @awjuliani , I'll check the document.
