### ISSUE TITLE
Curriculum Learning.

### ISSUE THREAD

**Issue by Aarsh-Singh-Vishen** [Unity-Technologies/ml-agents#783]
> Once these are in place, we simply launch ppo.py using the –curriculum-file flag to point to the JSON file, and PPO we will train using Curriculum Learning. 

So I came across this and I don't know how launch ppo using the curriculum-file thingy. 
Well I kinda don't know how to do most of that sentence. Help appreciated!

**Comment by Aarsh-Singh-Vishen** [comment]
Is there a more detailed how -to?

**Comment by xiaomaogy** [comment]
Yes I agree, we should come up with some doc with more detailed explanation and guidance. Will raise it within the team.

**Comment by dddanmar** [comment]
Blake has a good 2 part video on getting started with curriculum learning - https://www.youtube.com/watch?v=zieklxM9LZE&t=1s

**Comment by Aarsh-Singh-Vishen** [comment]
Thanks!

**Comment by awjuliani** [comment]
Hi all. We will be closing this issue for now due to inactivity. We are actively working on a revamp to the curriculum learning system which will include additional documentation on usage.
