### ISSUE TITLE
AddVectorObs() during runtime. 

### ISSUE THREAD

**Issue by Aarsh-Singh-Vishen** [Unity-Technologies/ml-agents#785]
Can i use AddVectorObs()  during runtime to monitor the position of an instantiated object (eg:bullets,spawned enemies,etc) in the AgentAction function?

**Comment by vincentpierre** [comment]
`AddVectorObs()` can only be called in `CollectObservations()`. 
If all you want to do is see some values, you could use the [Monitor](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Feature-Monitor.md) or you could store the values you are interested in in a temporary variable during `AgentAction` and then add them to the Observations in `CollectObservations`

**Comment by Aarsh-Singh-Vishen** [comment]
Thanks
:)
