### ISSUE TITLE
Do AddReward() called in another script works?

### ISSUE THREAD

**Issue by icaro56** [Unity-Technologies/ml-agents#794]
I am doing a Bomberman. When the agent put the bomb, this bomb has a timer of 3 seconds.

If this bomb destroy a block, in this CollisionEvent from Block script, I call the AddReward to agent.

Do AddReward called in another script works? My agent does not learn in any way that the bomb destroys blocks and with that receives a great positive reward. I even put the reward for destroying blocks more advantageous than worrying about the agent's life, but it did not work either.

```
public void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Explosion"))
        {
            if (!wasDestroy)
            {
                wasDestroy = true;
                Bomb bomb = other.gameObject.GetComponent<DestroySelf>().myBomb;
                if (bomb != null)
                {
                    bomb.bomberman.AddReward(0.5f);
                }
                gameObject.SetActive(false);
            }

        }
    }
```

**Comment by vincentpierre** [comment]
There is similar code in the Bouncer Environment in the `BouncerBanana.cs` script : 
```csharp
    private void OnTriggerEnter(Collider collision)
    {
        Agent agent = collision.gameObject.GetComponent<Agent>();
        if (agent != null)
        {
            agent.AddReward(1f);
            Respawn();
        }
    }
```

`AddReward` and `Done` can both be called from any script.

**Comment by icaro56** [comment]
Thanks. 

So, I don't understand why my agent does not learn put bomb to destroy blocks! :(

I discretized the movement to facilitate the learning. Nothing works. I will test with recurrent true.
