### ISSUE TITLE
tensorflow.python.framework.errors_impl.UnknownError: Failed to rename

### ISSUE THREAD

**Issue by DavidLining** [Unity-Technologies/ml-agents#799]
Error Log：
**tensorflow.python.framework.errors_impl.UnknownError: Failed to rename: ./models
/ppo\checkpoint.tmp2fd5af3d873541a1aff8a018d0fded87 to: ./models/ppo\checkpoint
: \udcbe\u073e\udcf8\udcb7\udcc3\udcce\u02a1\udca3
; Input/output error**
Did anyone encounter this issue? It seems a tensorflow error.

**Comment by DavidLining** [comment]
It's always happened after I increased the 'max_steps'. What's wrong with it???

**Comment by DavidLining** [comment]
@eshvk First I used v1.4.0, then I updated it to be v1.8.0, the problem is still existed.

**Comment by DavidLining** [comment]
It seems a problem of Tensorflow. [https://github.com/tensorflow/models/issues/4177](url)

**Comment by harperj** [comment]
Thanks for the report. Like you said this seems to be a TensorFlow issue (which is still open).  This issue has been inactive for a long time now so I'm going to close it for now.

**Comment by GoingMyWay** [comment]
Same error does anyone solved it？

**Comment by spagliarini** [comment]
Same error, any available solution?

**Comment by Ailing-Zou** [comment]
Same error, any available solution？
