### ISSUE TITLE
Missing documentation on how to run curriculum training in docker

### ISSUE THREAD

**Issue by me97esn** [Unity-Technologies/ml-agents#801]
How is this acheived? Would be great if the docs could be updated with an example.

**Comment by xiaomaogy** [comment]
@me97esn Just using the same command you would use for normal curriculum learning should work (By providing a --curriculum=<file> argument)

**Comment by awjuliani** [comment]
Hi All,

I am closing this thread due to inactivity, but feel free to re-open it if you desire.
