### ISSUE TITLE
Best way to represent a grid state.

### ISSUE THREAD

**Issue by icaro56** [Unity-Technologies/ml-agents#802]
I would like to know the best way to represent a grid cell in a game to facilitate the learning. 

If a cell, for example, can have the state: Empty, Agent, Block, Bomb. **Remember that a cell sometimes can have 1 or more states at same time**. In a grid 2 x 2 I can represent the state as:

## Integers
Empty=0, Agent=1, Block=2, Bomb=3
### Grid
|0|1|
|2|3|
### Agent Vector Observation
Increases the size of the agents vector observation by grid size
### Observation
We can not represent 2 or more states at the same time. Only if we create an integer for each possible combination of elements e.g. Bomb + Agent => BombAgent = 4.

## One-hot
Empty=[1, 0, 0, 0], Agent=[0, 1, 0, 0], Block=[0, 0, 1, 0], Bomb=[0, 0, 0, 1]
### Grid
| [1, 0, 0, 0] | [0, 1, 0, 0] |
| [0, 0, 1, 0] | [0, 0, 0, 1] |
### Agent Vector Observation
Increases the size of the agents vector observation by one-hot size x grid size
### Observation
We also can not represent 2 or more states at the same time. Only if we create an one-hot for each possible combination of elements e.g. Bomb + Agent => BombAgent = [0, 0, 0, 0, 1]. 

## Binary Flag
Empty=000, Agent=001, Block=010, Bomb=100
### Grid
| 000 | 001 |
| 010 | 100 |
### Agent Vector Observation
Increases the size of the agents vector observation by grid size
## Observation
We can 2 or more states at the same time. If in a cell is the Agent + Bomb, then we can combine the flags 001 | 100 =  101.

## Hybrid = Binary Flag + One-hot
Empty=[0, 0, 0], Agent=[1, 0, 0], Block=[0, 1, 0], Bomb=[0, 0, 1]
### Grid
| [0, 0, 0] | [1, 0, 0] |
| [0, 1, 0] | [0, 0, 1] |
### Agent Vector Observation
Increases the size of the agents vector observation by one-hot size x grid size. The Empty state is only the 0 array.
### Observation
We also can represent 2 or more states at the same time. If in a cell is the Agent + Bomb, then we can combine the Hybrids -> [0,0,1] | [1,0,0] =  [1,0,1].

**Comment by icaro56** [comment]
I compared the Binary Flag X Hybrid

With the Binary Flag representation, the cumulative reward is greater.

**Comment by icaro56** [comment]
Does anyone have any experience with the representation of a grid that can share with us?

**Comment by icaro56** [comment]
@mmattar ,

**can you further explain why a cell may have more than one state at the same time?**
I am developing a Bomberman clone. When the agent put a bomb, the actual position have a agent and a bomb. I think other games can have similar situations.

**Also, is it necessary to represent the full state by encoding the grid?**
So, I pass only the grid observation for my agent. Like a visual observation of the screen. I do not want to give the agent any insider information.

**An alternative is to define informative numeric observations for the agent.**
Can you explain this?

Thanks

**Comment by mmattar** [comment]
@icaro56 - apologies for the delay - what have you found to work well so far?

To further explain numeric observations:

Within ML-Agents you can define an agents observation as either the visual input from the camera and/or a numeric representation for the agent. For example, you may include the distance of the agent to a bomb, the number of cells that have an bomb, etc. In our sample environments, the [Balance Ball example](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Examples.md#3dball-3d-balance-ball) uses numeric observations, not visual ones.

**Comment by icaro56** [comment]
Ah yes. I use numeric observations.

Representing the state as Binary Flags has been better for me. But I will have to experiment more.

**Comment by mmattar** [comment]
Hey @icaro56 - closing out this issue for now, but please re-open as you have updates or run into any related issues.

**Comment by icaro56** [comment]
In recent tests, hybrid representations is the best.
