### ISSUE TITLE
Variable action space size or limited actions

### ISSUE THREAD

**Issue by vlatkozelka** [Unity-Technologies/ml-agents#807]
In many games, the agent isn't allowed to take any action available to it from the action space at every given time. For example in a card game you can't just choose any card anytime, or in an action game you can't shoot if you have no ammo, etc...

So I'd like to ask if this is possible in ml-agents, or if there is a work-around for it in some way. 
If not, is it a limitation from ml-agents only? Or a limitation of reinforcement learning in general?

Thanks

**Comment by mbaske** [comment]
You could consider an agent taking unavailable actions as breaking the rules of a game - and assign penalties for that. For instance, the amount of ammo would be part of the agent's observation space. If it attempts to fire without ammo, it would receive a penalty (negative reward) and eventually learn not to fire in that situation.

**Comment by msaroufim** [comment]
Why does this require a special workaround? It's similar to a player pushing wrong buttons in a video game.

**Comment by MarcoMeter** [comment]
It's not optimal to pick an action which is not available. Plus this might increase the credit assignment problem for crediting the right action.

**Comment by metamorphling** [comment]
`In many games, the agent isn't allowed to take any action available to it from the action space at every given time. For example in a card game you can't just choose any card anytime`
As far as I'm aware that's what "On Demand Decision" is here for.
When step is needed only at specific time you request it with RequestDecision() which leads to AgentAction, or use RequestAction() directly depending on your use case.

**Comment by awjuliani** [comment]
Hi all,

The ability to "mask" certain discrete actions will be available in v0.5, releasing next week. You can check it out early here: https://github.com/Unity-Technologies/ml-agents/tree/release-v0.5
