### ISSUE TITLE
Agent.RequestDecision() sometimes does more than one action

### ISSUE THREAD

**Issue by al291708** [Unity-Technologies/ml-agents#812]
Hi,

I am developing a Tower Defense video game and, every 3 seconds (managed with a coroutine) I want to insert a character on the board I call Agent.RequestDecision().

```
    private void playRequestingAgentDecisions()
    {
        StartCoroutine("requestAgentDecision");
    }

    IEnumerator requestAgentDecision()
    {
        while (gameIsOver == false)
        {
            GetComponent<Agent>().RequestDecision();
            yield return new WaitForSeconds(3);
        }
    }
```

My actions are discrete. Action 1 inserts a character in a place, action 2 inserts another character in another place, etc.. What I understand is that Agent.RequestDecision() "starts one iteration of the observation-decision-action-reward cycle". So, it should only do 1 action for each call I make.

It seems that, only sometimes, it has "enough time" to do more than one action. Does it do more than one environment step in this space of time? I know it doesn't use steps when OnDemandDecisions is used, but... I'm just trying to figure out what is wrong here...

 It does something like: 
_RequestDecision() -> action "1" (one action, OK) -> wait -> RequestDecision() -> action "4", action "2" (does more than one action, NOT OK) -> wait -> RequestDecision() -> action 3 (one action, OK)-> wait -> etc..._

Could you tell me if I am doing something wrong or if there is a way to force RequestDecision() to only do 1 action?

Thanks a lot.

**Comment by awjuliani** [comment]
Hi All,

I am closing this thread due to inactivity, but feel free to re-open it if you desire.
