### ISSUE TITLE
Require Video Tutorial

### ISSUE THREAD

**Issue by sinhadanish** [Unity-Technologies/ml-agents#813]
Can someone please  post links to video tutorial to correctly setup  and run 3D ball example for 0.3 version?

**Comment by sinhadanish** [comment]
Suggestion: Unity Official Video Tutorial for 0.3v on:
1. How to setup for Windows, Mac and Linux 
2. Walkthrough of all the different example scenes explaining important parts
3. Creating Custom Learning Environment

**Comment by roboserg** [comment]
1. Go to youtube and search for "unity ml agents" (suddenly, who knew?)
2. Watch [this ](https://www.youtube.com/playlist?list=PLX2vGYjWbI0R08eWQkO7nQkGiicHAX7IX)
3. And [this](https://www.youtube.com/playlist?list=PLB5_EOMkLx_Ub1A4iHoDUx7vg37sVoL-E)

**Comment by sinhadanish** [comment]
Already checked all the links.
The first one is more of the interesting stuff you can do with machine learning. 
I think  I will wait for a  stable 1.0  version and then request for tutorial etc. 

The second link  is for version 0.2 and it not compatible with 0.3.

**Comment by eshvk** [comment]
Hey @sinhadanish .Thank you for your comments.  We’ve documented your feedback and will prioritize when appropriate.
