### ISSUE TITLE
Training on AWS Compute Optimized (c5) Instances

### ISSUE THREAD

**Issue by EnigmaVariation** [Unity-Technologies/ml-agents#815]
Hello!

I'm using AWS compute optimized instances (c5) to train my agents.
My setup includes the Intel Python Distribution [1] and a Tensorflow wheel which supports AVX2 instructions on Linux. I'm generally happy with this setup (and I believe I'm getting more bang for my buck as compared to GPU instances). But I found that when I'm trying to scale up, larger instances don't use their full vCPU capacity (blue: 4 vCPU, orange: 16 vCPU):

![cpu](https://user-images.githubusercontent.com/9258649/40643188-91b2bc92-631f-11e8-8824-9ce715133d8b.JPG)

Do any of you have any experience with training on c5 instances? Any idea what might be the bottleneck or the error in the setup?

Edit: Added potentially relevant Links [2],[3]. So far I couldn't get it to scale up properly.

[1] -- https://software.intel.com/en-us/distribution-for-python
[2] -- https://stackoverflow.com/questions/49186487/unable-to-use-all-processors-in-net-on-aws-c5-18xlarge-72-vpu
[3] -- https://www.tensorflow.org/performance/performance_guide#optimizing_for_cpu

**Comment by xiaomaogy** [comment]
@EnigmaVariation What is the approach that you used to scale up during training? (Running multiple python process to train different environments? Or some custom setup to use multiple python process to train one environment?) Also what is the y-axis in your graph?

**Comment by EnigmaVariation** [comment]
The y-Axis is the vCPU usage (blue: 100% for the smaller instance, orange: ~40%-80% for the larger one); there is no particularly interesting setup involved, it's just a single environment.

**Comment by karta1297963** [comment]
@EnigmaVariation  What's your training speed respectively?

**Comment by EnigmaVariation** [comment]
The training speed aligns as expected (i.e. 16 vCPU at 50% are approximately as fast as 8 vCPU at 100%).

**Comment by karta1297963** [comment]
I have experienced similar performance issue, after using the profiler, here's some of mine conclusion.

CPU side, the main bottleneck is the following (in ml-agent v0.2):
![2018-07-25 5 00 03](https://user-images.githubusercontent.com/14128307/43190778-6719b636-902c-11e8-965d-19f6dc7ed643.jpg)
I think the issue is all that function are single threaded, so naturally not scale well in multicore environment.

GPU side, the bottleneck is some "mystery" function "RenderTexture.SetActive" ref: #346

**Comment by EnigmaVariation** [comment]
That sounds very reasonable! I got a lot of performance (better vCPU usage) by optimizing the code in the Agent step.

**Comment by karta1297963** [comment]
How did you optimize?

**Comment by EnigmaVariation** [comment]
Nothing fancy, just some optimizations that were not done correctly in the first draft. See for example [1].

[1] -- https://unity3d.com/de/learn/tutorials/topics/performance-optimization

**Comment by awjuliani** [comment]
Hi All,

I am closing this thread due to inactivity, but feel free to re-open it if you desire.
