### ISSUE TITLE
Tutorial's ball is shaking after training

### ISSUE THREAD

**Issue by Tlospock** [Unity-Technologies/ml-agents#817]
Hey,

So I've been trying to adapt the basic ML_Agents project with the ball with a discrete displacement (at each turn, the agent move from a fixed movement step in one of the eight direction), without using force*speed.
But I don't know why, after training, the agent is shaky and have spend some time getting some collectibles. I don't really know which parameters to fix.

The reward function and all parameters are the same as in the tutorial.
 
![balltraining](https://user-images.githubusercontent.com/16708864/40715217-cc78bc52-643f-11e8-86df-3067cc8dd44a.gif)

**Comment by xiaomaogy** [comment]
You can try to remove the reward of moving closer to the target, since this is encouraging the agent to slowly move closer to the target instead of reaching it.

**Comment by awjuliani** [comment]
Thanks for pointing this out. The tutorial instructions have been updated for the new v0.5 release to no longer cause the shaking.
