### ISSUE TITLE
Rich Observations (Map Reading) example 

### ISSUE THREAD

**Issue by fluffymudkip** [Unity-Technologies/ml-agents#827]
I was wondering if anyone knows where i can find the Rich Observations (Map Reading) example showed at PAPIs.io: https://youtu.be/rv224ozz7vo?t=16m15s 
I am trying to create something somewhat similar and would love to have a look at that example, or its hyperparameter settings. 
Thanks!

**Comment by eshvk** [comment]
Hey @billluky, I see we haven't had any responses in this thread for a while. Do you still need help with this issue?

**Comment by awjuliani** [comment]
Hi @fluffymudkip,

I was the one who originally created that environment. It was built using an older version of Unity and ML-Agents, but I intend to re-create it in a current version at some point in the future.
