### ISSUE TITLE
Best way to represent orientation ?

### ISSUE THREAD

**Issue by SPINACHCEO** [Unity-Technologies/ml-agents#83]
Hello there.
I am wondering what is the best way to represent agent's orientation as state.
I can't directly use euler Y axis because it is not a continues value.
My current approach is `transform.forward` but it doesn't seems to work.

Does anyone have a better solution?
Thanks you for your time :)

**Comment by liamFerris** [comment]
I may not fully understand your question, but for orientation I would use `transform.rotation.x`, transform.rotation.y` and, transform.rotation.z`.

I don't think `transform.forward` would work as it is a Vector3 object not a number. If you are trying to use the forward vector you can use `transform.forward.x` and so on...

**Comment by SPINACHCEO** [comment]
Thanks very much for your reply.
Yes by transform.forward I means to put x and z axis as two float into state.
But I am not sure if this is the best choice. 
For example, if my agent may only rotate along it's Y axis, should I use `transform.rotation.y` and `transform.rotation.z` ?
Or I may put all four value into state ?

Thank you

**Comment by SPINACHCEO** [comment]
Thanks very much for your reply.
Yes by transform.forward I means to put x and z axis as two float into state.
But I am not sure if this is the best choice. 
For example, if my agent may only rotate along it's Y axis, should I use `transform.rotation.y` and `transform.rotation.z` ?
Or I may put all four value into state ?

Thank you

**Comment by liamFerris** [comment]
I imagine that you needn't use both.

`transform.rotation` is an object's rotation relative to the world.
`transform.localRotation` is an object's rotation relative to its parent gameobject.
`transform.forward` is an arbitrary value meant to represent the front facing direction of an object, it is used in various Unity methods like `LookTowards` etc. You are also able to change an object's forward at any time. 

I would recommend `transform.rotation` like what is used in the 3D Ball example.

**Comment by SPINACHCEO** [comment]
Thanks for the reply :)
I know what these thing are but I am really confused when choose them as state.
Seems like all the example are using absolute values like world position and world rotation.
For me I would think relative value will some how much more make sense.
Such as if I want to train an agent to chase something. The agent should know the relative position(agent's position - target's position), and it's current forward direction(transform.forward). But the training never succeed in this way.
I don't know why it not work. 

Please check the last post in #70 I made. Which is a little soccer like game.
I successfully trained agent of this game by ignoring rotation- action and state, and use world position for agent it self and ball. And only a single agent.
But when I add rotation into it(with transform.forward as state), it doesn't seems to work.

**Comment by awjuliani** [comment]
Hi all,

I was just speaking with a Unity developer, and he mention that changing

`state.Add(transform.rotation.eulerAngles.y/180.0f-1.0f);` 

is the appropriate method for registering y angle.
