### ISSUE TITLE
When I try to load a previous model using Imitation Learning it does not work.

### ISSUE THREAD

**Issue by sam-ulrich1** [Unity-Technologies/ml-agents#834]
Every time I try to load a model using Imitation Learning the step count starts over at 0. However, if I am using reinforcement learning I can load a model with no issues. Am I missing something?

**Comment by sam-ulrich1** [comment]
Can someone just tell me if loading a model while using imitation learning is possible? As of now I don't know if I'm doing something wrong or just trying something that isn't possible.

**Comment by eshvk** [comment]
Hi @sam-ulrich1 , so loading a model using imitation learning is possible. It is just that the step was not being saved in the graph so the loaded model had no memory of the global step that was being used. We have changed this to fix this and it should be merged.

**Comment by sam-ulrich1** [comment]
@eshvk  Thanks man!

**Comment by sam-ulrich1** [comment]
@eshvk I just updated my ml-agents and when I ran the Imitation Learning I got the same result. Is there an extra step that I could be missing?

**Comment by sam-ulrich1** [comment]
@eshvk Never mind I just copied the corrections from your pull request and it work fine now. Thank you again!
