### ISSUE TITLE
Providing complete MDP

### ISSUE THREAD

**Issue by leonardoaraujosantos** [Unity-Technologies/ml-agents#84]
Hi guys,
It's possible to extend the interface to include the MDP? (Or point me out so I could extend and post as a Pull request)
* GetTransitionStatesAndProbabilities (given state and action)
* GetReward (given: state, action and next_state)

The idea is to allow teaching people RL from the basics doing Dynamic Programming (Police/Value iteration)

### References
* http://ai.berkeley.edu/reinforcement.html

`
import random
class MarkovDecisionProcess:

    def getStates(self):
        """
        Return a list of all states in the MDP.
        Not generally possible for large MDPs.
        """
        abstract

    def getStartState(self):
        """
        Return the start state of the MDP.
        """
        abstract

    def getPossibleActions(self, state):
        """
        Return list of possible actions from 'state'.
        """
        abstract

    def getTransitionStatesAndProbs(self, state, action):
        """
        Returns list of (nextState, prob) pairs
        representing the states reachable
        from 'state' by taking 'action' along
        with their transition probabilities.

        Note that in Q-Learning and reinforcment
        learning in general, we do not know these
        probabilities nor do we directly model them.
        """
        abstract

    def getReward(self, state, action, nextState):
        """
        Get the reward for the state, action, nextState transition.

        Not available in reinforcement learning.
        """
        abstract

    def isTerminal(self, state):
        """
        Returns true if the current state is a terminal state.  By convention,
        a terminal state has zero future rewards.  Sometimes the terminal state(s)
        may have no possible actions.  It is also common to think of the terminal
        state as having a self-loop action 'pass' with zero reward; the formulations
        are equivalent.
        """
        abstract
`

**Comment by awjuliani** [comment]
Hi @leonardoaraujosantos,

This is a cool idea! I would say that it isn't necessarily high on our list to implement, but if you wanted to add this feature, we'd definitely consider incorporating it. One issue I could see arising however is that the majority of environments are POMDPs rather than MDPs, and as such exact transition and reward probabilities can't easily be computed. Of course, the developer of an environment could work to describe them, depending on the complexity of that environment.

**Comment by EnthusedDragon** [comment]
I see this enhancement was closed.
Was this successfully implemented into ml-agents?
