### ISSUE TITLE
Support adding observations with Matrix in the future?

### ISSUE THREAD

**Issue by DavidLining** [Unity-Technologies/ml-agents#845]
I plan to use 3D convolution nerual network with PPO for my project recently, I don't know if it can works. haha~
However, it seems that ML-Agents only support adding one-dimensional array observation to the vector of observations of the agent.
Will the ML-Agents team support adding multi-dimensional array obvervation in the future?

Thanks.

**Comment by MarcoMeter** [comment]
As of now, ML-Agents supports camera image observations, which are fed to a convolutional layer.

**Comment by DavidLining** [comment]
@MarcoMeter  yes, but it's an 2D convolutional layer. It's better if ML-Agents can support 3D inputs in the future.

**Comment by awjuliani** [comment]
Hi All,

We plan to add more variable observation space types in the future, including matrices.

**Comment by mmattar** [comment]
Thank you for your comments.  We have this in our roadmap to complete in the future.  We will communicate when this is available in a later release.

**Comment by Amr311** [comment]
Hello everyone,

Is this available now? to pass a 2D array as an observation?
