### ISSUE TITLE
`System.Text.StringBuilder' does not contain a definition for `Clear'

### ISSUE THREAD

**Issue by DynamiteStick** [Unity-Technologies/ml-agents#852]
I just imported the latest version and I got this I have not done anything to the code at all. Help.

Assets/ml-agents-0.3.1b/unity-environment/Assets/ML-Agents/Scripts/ExternalCommunicator.cs(269,24): error CS1061: Type `System.Text.StringBuilder' does not contain a definition for `Clear' and no extension method `Clear' of type `System.Text.StringBuilder' could be found. Are you missing an assembly reference?

**Comment by Fellfalla** [comment]
In `ExternalCommunicator` I replaced 2 occurences of `rMessageString.Clear()` with `rMessageString.Remove(0, rMessageString.Length);`

**Comment by jo3w4rd** [comment]
This is a duplicate of #798 

In summary, change your Scripting Runtime Version to 4.6 in the Unity Player Settings.
