### ISSUE TITLE
Custom Training Stats

### ISSUE THREAD

**Issue by m-ronchi** [Unity-Technologies/ml-agents#858]
is it possible to send custom stats to tensorboard from the training environment?

for example, I want to count whenever an agent makes an invalid action, to check it is going towards zero as the training progresses.

**Comment by xiaomaogy** [comment]
This is something we are thinking about adding, but we don't have this right now.

**Comment by eshvk** [comment]
Thank you for this discussion, we are going to close this issue due to inactivity for now.
