### ISSUE TITLE
FrameToSkip clarification

### ISSUE THREAD

**Issue by mplantady** [Unity-Technologies/ml-agents#86]
Hi!

I find it a bit confusing that Agent's rewards are cumulated over all the skipped frames before being sent. That means that if you assign a value instead of incremented it, some data are lost.

Maybe it could be great to pass a parameter to the Step() function to know if we are currently in a frame skipped or not.
Or at least make it very clear in the documentation.

Thanks!

**Comment by dora-gt** [comment]
Hi.

Check out [this](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Making-a-new-Unity-Environment.md#defining-the-reward-function) section.

The problem you mentioned is written but I think writing it too [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Making-a-new-Unity-Environment.md#implementing-yournameacademy) or [here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Making-a-new-Unity-Environment.md#implementing-yournameagent), is better.

Why don't you issue pull-request.

**Comment by mplantady** [comment]
My bad, I missed this section of the reward documentation! It was just to make sure it was intentional.
