### ISSUE TITLE
Cannot install on windows

### ISSUE THREAD

**Issue by sonicviz** [Unity-Technologies/ml-agents#87]
Tried doing "Pip3 install ." with Python 3.6.2 and get "Could not find a version that satisfies the requirement tensorflow>=1.0 (from unityagents==0.1.1) (from versions: ) No matching distribution found for tensorflow>=1.0 (from unityagents==0.1.1)"

According to https://stackoverflow.com/questions/41046748/issue-with-pip-installing-tensorflow-in-windows-no-matching-distribution-found you "You need to use Python 3.5, 64-bit. No other version currently works -- even 3.6 64-bit."

That's just silly.

Any way around this?

**Comment by xujiezhige** [comment]
If you use Anaconda, creating a new environment with Python 3.5 is convenient.

**Comment by unity3dcollege** [comment]
If you're still having problems, I did a setup post a few days ago after struggling with it a bit.  It mostly came down to getting the right versions of everything, but it was a little difficult so seemed worth documenting.  Hope it's helpful: https://unity3d.college/2017/10/25/machine-learning-in-unity3d-setting-up-the-environment-tensorflow-for-agentml-on-windows-10/

**Comment by sonicviz** [comment]
Nice job, ty!

**Comment by awjuliani** [comment]
Very nice @unity3dcollege,

If you don't mind, I am going to add a link to your walkthrough in the installation page.

**Comment by unity3dcollege** [comment]
Sounds good to me.

BTW I did another one earlier today showing how to create a super simple agent here: https://unity3d.college/2017/11/01/unity3d-machine-learning-writing-a-custom-agent-create-your-own-ai-bot/

Was hoping someone could take a look and let me know if I messed up anything bad... Still trying to get a grip on ML, and while the end result 'worked', I wanna make sure there's no bad/wrong advice in there :)
