### ISSUE TITLE
Recording agent expierience

### ISSUE THREAD

**Issue by 5665tm** [Unity-Technologies/ml-agents#880]
> when using immitation learning there is a problem: I have to play several times if I just want to change settings or rewards. This is a big problem if the training lasts 20-40 minutes. Instead of writing code or drinking tea, I have to sit and play, play, play, play, play, play, play, play, play. it's terrible, and I do not really like to play.

I would like to implement a functional that allows you to record agent expierience (inputs + actions + rewards) once, and use them for training at all times

development sequence:
1) I will describe my decisions in this issue (1-2 days, I see several ways to solve this challenge)
2) discussion with contributors, choice of the best solution
3) implementing of feature

**Comment by 5665tm** [comment]
@awjuliani 

I tried different solutions, and unfortunately I could not find a solution that I liked.
The main problem - I want to be able to change the values of rewards after recording.
Unfortunately, this desire makes the code horrible, and I could not find a way to do nicely.
I will show you the solution that brings the least pain (but I still do not like it)

Scheme - http://joxi.ru/EA4bqKjCwpgnOm
Pseudocode - https://gist.github.com/5665tm/66e8f0fce26e799bc0f855d2ff3f9c36

if you say "this decision is terrible," I will not be offended
Because it really is so :)

**Comment by awjuliani** [comment]
Hi @5665tm,

As I see it, a simple first step would be to simple record <observation, action, reward, done> tuples for a set of trajectories, and save them as some sort of asset file which could be recovered from Unity, or provided to python during the behavioral cloning training session.

**Comment by 5665tm** [comment]
@awjuliani ok, i will try it

**Comment by 5665tm** [comment]
@awjuliani 
Unfortunately, it seems that I can not take this task.
At the moment I'm busy on my main job and preparing for the release of my indie project. I sensibly appreciated my free time and decided to abandon the task.
I think I can join your project again in the fall.
Let another person do this.
Excuse me.

**Comment by awjuliani** [comment]
@5665tm Please do not worry about it! This is a feature we will likely work to implement internally sometime soon ourselves. Best of luck on your indie project, and happy to see you around when you have the time.

**Comment by xiaomaogy** [comment]
In v0.6 we've added the demonstration recorder feature which is exactly what is being talked here. So I'm closing this issue.
