### ISSUE TITLE
TensorflowSharp .so filenames

### ISSUE THREAD

**Issue by DaWelter** [Unity-Technologies/ml-agents#891]
Hello!

To get started on Linux with your wonderful ml-agents, I downloaded
https://s3.amazonaws.com/unity-ml-agents/0.4/TFSharpPlugin.unitypackage,
installed everything, tried to run a pretrained model and got error messages like:
Plugins: Couldn't open Assets/ML-Agents/Plugins/Computer/liblibtensorflow.so, error: libtensorflow_framework.so: cannot open shared object file: No such file or directory

I noticed that some of the files have the lib prefix twice in their name. Like liblibtensorflow_framework.so. Odd. Also 
$ldd liblibtensorflow.so
        ....
	libtensorflow_framework.so => not found
        ...
So I removed the duplicate lib prefixes. -> Works!

Thought I should let you know. And thanks for your great work!

Best regards.

**Comment by xiaomaogy** [comment]
@DaWelter Thank you for your information! You are right, I will update the unitypackage with the correction.

**Comment by xiaomaogy** [comment]
Fixed.
