### ISSUE TITLE
Using Genetic algorithm with brain

### ISSUE THREAD

**Issue by jpax1996** [Unity-Technologies/ml-agents#893]
Hello,
I was wondering if it was possible to implement some kind of genetic algorithm to the training of our agents to make the learning possess more effective?
What i was thinking of doing would be to create a learning environment with several agents each one with their own brain. We would then run the environment and wait until all the agents had stopped or reset. For the next session, we will keep the top brains and link the rest of the agents to them and repeat until we had a really strong brain. 
Is this a good way of going about it or is there a better solution?

**Comment by awjuliani** [comment]
Hi @jpax1996,

This is an interesting approach. I think what you've described could definitely work with the current system. Given our current code-base, this will essentially allow you to converge to whichever network was initialized most promisingly from the beginning of training. There are of course a lot of more advanced approaches which are more like true genetic algorithms where variation is introduced into the weights of the children networks each generation. That would require a refactoring from our current training code-base but is definitely possible. It would also be possible to create purely evolution-based training algorithm if you were interested.

**Comment by jpax1996** [comment]
Thank you @awjuliani for the fast reply,
I'm wondering to replace the worst brains of the agents with the brain with highest reward, can i simply deleted the old brain, duplicate the best brain and connect the agent to this new brain?

**Comment by AMGValue** [comment]
@awjuliani have you thought about applying AutoML to ML-Agents?

Right now, AutoML is offered to vision, but maybe with a little fitting...

**Comment by awjuliani** [comment]
Hi @AMGValue,

There are a lot of possibilities for automating the meta-level optimization process. We are definitely exploring them.
