### ISSUE TITLE
Doubt about Agent stepCount

### ISSUE THREAD

**Issue by icaro56** [Unity-Technologies/ml-agents#894]
Why is Agent's stepCount incremented even when a request with RequestDecision is not requested?

I call RequestDecision On Demand every 0.5 milliseconds. More or less every 25 steps, the agent makes a decision.

Does this 25-step jump influence the agent's learning in the PPO or BC?

Would you be able to synchronize the step with Agent RequestDecision?

**Comment by icaro56** [comment]
Another doubt. I create a specialist brain/agent that is heuristic and stays repeting the move all the time.

Is better stop to record the movement when he finish the repertoire or not?

**Comment by xiaomaogy** [comment]
**Why is Agent's stepCount incremented even when a request with RequestDecision is not requested?**

stepCount is incremented as we step the agent, this doesn't require a decision to be made on that agent. 

**Does this 25-step jump influence the agent's learning in the PPO or BC?**

If you use on demand decision, the learning will be different from if you are not using it. 

**Would you be able to synchronize the step with Agent RequestDecision?**

What do you mean synchronize the step with requestDecision?

**Is better stop to record the movement when he finish the repertoire or not?**

If you don't stop recording, it will just keep recording your observation-action behavior, which in your case is "some observation --> not moving " pair.

**Comment by icaro56** [comment]
Thanks @xiaomaogy 

**What do you mean synchronize the step with requestDecision?**
It is because I observed the step count of a agent/brain is incremented even without calling the requestDecision function when the environment is On Demand Decision

Are there some way of to use fast simulation on imitation learning? As I am using heuristic brain to demonstrate the specialist's movement, then I do not need that enviroment to be executed in slow mode.

**Comment by xiaomaogy** [comment]
@icaro56 For new questions irrelevant to your title, it would be better if you can open a new issue to discuss it next time. 

Right now our setup of imitation learning doesn't allow you to do that. This is something we plan to improve in the future version. 

Just curious, why do you want to use imitation learning to transfer the logic from a heuristic brain to a neural network? What is the use case here?

**Comment by xiaomaogy** [comment]
But even if you've trained the learner brain and it behaves exactly as the Heuristic brain, how are you going to use it (what are the things you can use it for, in which the Heuristic brain cannot do)?

To answer your question: Yes, it will keep iterating. 
Here RequestDecision means: Give me a new way of acting. 
RequestAction (another function in Agent.cs) means: Do the iteration. 

Even if you are not calling RequestDecision, the RequestAction still gets called every step.

**Comment by icaro56** [comment]
`But even if you've trained the learner brain and it behaves exactly as the Heuristic brain, how are you going to use it (what are the things you can use it for, in which the Heuristic brain cannot do)?`

The heuristic brain follows a replay file with the movements of a player. I'm trying to make the apprentice brain to learn similar movements of a player. I am doing experiments to test if agent manages to generalize. Next, I will try to update the BC algorithm for the agent continue learning.

Thank you @xiaomaogy

**Comment by xiaomaogy** [comment]
@icaro56 

Regarding Edit 1: 
Sorry, you are right. I was confused about the RequestAction() function myself. 

What RequestAction() does is not do the iteration (which you can understand as calling FixedUpdate() and do the moving etc), but instead call the AgentAction() function. 

Note when you call the AgentAction() using RequestAction(), it will not use a new action based on your new observation. It will instead use an old action you had previously. You can see the example in WalkerAgent : 98 for example. 

Regarding Edit 2: 

Where did you put your counter? In the AgentStep()?

**Comment by icaro56** [comment]
Hi @xiaomaogy 

I increment my counter in AgentAction function.

I am investigating this, and I noted that the funcion env.step in Python sometimes can to get external brain without agents. In add_experiences function inside BC_trainer there are conditions in the for loops that treat this problem. Maybe, the request done by env.step via RPC are not return OK.

**Comment by awjuliani** [comment]
Hi @icaro56 , we've changed the logic for counting steps, and it should be accurate now in `develop`.
