### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by icaro56** [Unity-Technologies/ml-agents#897]
In https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation-Windows.md

You recommend Tensorflow version 1.4.0.
"_**Latest versions of Tensorflow won't work, so you will need to make sure that you install version 1.4.0**_"

And in the code tag is:
pip install tensorflow==1.7.1

**Comment by xiaomaogy** [comment]
@icaro56 Thanks for that note, we will fix that along with the hotfix merge.
