### ISSUE TITLE
Showing progress may help

### ISSUE THREAD

**Issue by dora-gt** [Unity-Technologies/ml-agents#90]
Hi,

With the current version, python process only outputs `Mean reward` and `Saved Model`.
It may help outputting `Progress --%` and `Estimated time remaining: -- [h]`.

Thank you.

**Comment by SPINACHCEO** [comment]
I think it is very hard to tell the progress and time remaining. If you want to see how many step has taken you can see them easily in tensorboard.
But most of time, you don't even know if the training will even be succeed.

But I do think a training control panel would be a good idea. Like you can pause and resume the training any time and view the current result.

**Comment by dora-gt** [comment]
Why do you think it is hard?

Max step is defined, step done is clear, how long did it cost is clear, so I think we can calculate it.
(Of course it is `prediction`)

**Comment by SPINACHCEO** [comment]
Yeah, because the max step doesn't mean the end of training at all.
Like I mentioned currently you can view the current step in tensorboard.
I just added some code to log time and percent:

add `timer = time.time()` before the main loop and 

```
 if steps % progress_freq == 0 and steps != 0 and train_model:
            m, s = divmod((time.time() - timer) / progress_freq * (max_steps - steps),60)
            h, m = divmod(m, 60)
            timer = time.time()
            print( f"Progress: {steps/max_steps * 100:.2f}%, time to max-steps {h}h:{m}m:{s:.2f}s")
```

inside the loop

`progress_freq` in a int indicating the frequency of logging progress.
And make sure  `import time` at the beginning.

**Comment by dora-gt** [comment]
Thank you so much @SPINACHCEO ,

I understand what you mean, the end of training differs from the end of the python process(max step).

Anyway, I'll add the code and try. Thank you again.

**Comment by SPINACHCEO** [comment]
#96

**Comment by awjuliani** [comment]
Hi all,

We use TensorBoard as the default method of monitoring progress during training. I would encourage users to use that.
