### ISSUE TITLE
Is the code right in the sequence_length in Behavioral Cloning?

### ISSUE THREAD

**Issue by icaro56** [Unity-Technologies/ml-agents#907]
bc/trainer.py
BehavioralCloningTrainer class

In the function take_action, the self.model.sequence_length is informed as 1, but if recurrent is set to True, this parameter mabe should b self.sequence_length.
```
def take_action(self, all_brain_info: AllBrainInfo):
        if len(all_brain_info[self.brain_name].agents) == 0:
            return [], [], [], None

        agent_brain = all_brain_info[self.brain_name]
        feed_dict = {self.model.dropout_rate: 1.0, self.model.sequence_length: 1}
...
```
Please check this part of the code.

**Comment by awjuliani** [comment]
Hi @icaro56,

During inference (action taking) the sequence will only ever be one, since the agent only needs to take one action at a time, using the current observation. During training is when longer sequences can be necessary. I hope that clarifies things for you.
