### ISSUE TITLE
if you get a python stack trace with the first error being a load dll error it might be your CPU doesnt support AVX

### ISSUE THREAD

**Issue by dizzy2003** [Unity-Technologies/ml-agents#910]
I was having the above issue, (old xeon processor)

This thread helped https://github.com/tensorflow/tensorflow/issues/17386

installing the below .whl fixed it for me, allthough this is a downgrade to tensorflow 1.6

https://github.com/fo40225/tensorflow-windows-wheel/tree/master/1.6.0/py36/CPU/sse2

pip install tensorflow-1.6.0-cp36-cp36m-win_amd64.whl

**Comment by xiaomaogy** [comment]
@dizzy2003 Are you seeking some help in this issue or you are just providing a solution to other people?

**Comment by dizzy2003** [comment]
notification of an issue and a solution :)

All though I get a crash when using the binary file with tensorflowsharp,
so not sure if I have caused an incompatibility by using TF1.6 built
without AVX with latest TFSharp..


On Tue, Jun 26, 2018 at 3:51 AM, Vincent(Yuan) Gao <notifications@github.com

**Comment by xiaomaogy** [comment]
I haven't tested TF 1.6 with the tensorflowsharp plugin, so I am not sure how it works. 

If I am understanding you correctly, you have an old xeon cpu, which only works with TF 1.6, and that's why you are stuck with TF 1.6? 

And you are asking if ML-Agents can work with your version of TF 1.6?

**Comment by dizzy2003** [comment]
Following the instructions provided, produced a python stack trace saying
dll load error. when python imports the tf lib.

After a bit of googling it seems that ml-agent has installed a version of
TF that requires some AVX support that my CPU doesnt have.

It looks like TF1.6 also requires AVX, but someone has compiled a version
of 1.6 that doesnt require AVX and thats the whl file I linked.


So I posted the issue both as a heads up about the compatibility issue and
help for others who might hit this issue.

Since then I have discovered my binary data causes unity to crash, I dont
know at this time if its due to me using TF 1.6. or some other issue.

A version of TF 1.7 that doesnt require AVX would be great if such a thing
exists though.





On Tue, Jun 26, 2018 at 9:50 AM, Vincent(Yuan) Gao <notifications@github.com

**Comment by xiaomaogy** [comment]
Yes I agree, that would be great. But right now we probably won't be working on supporting that. You are welcome to contribute on this if you are interested.

**Comment by dizzy2003** [comment]
Will report back if I find a solution to the binary data issue/ TF 1.7 with
non AVX supprt

**Comment by xiaomaogy** [comment]
@dizzy2003 Just to close the loop, if you want to use ML-Agents for training, you can build a version of TensorFlow without requiring AVX support by building from source. It could be that the TF version that is automatically installed by pip requires AVX support.
