### ISSUE TITLE
Experimental (.NET 4.6 Equivalent) ?

### ISSUE THREAD

**Issue by ivenzor** [Unity-Technologies/ml-agents#911]
According to the documentation (https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Basic-Guide.md) when editing Player Configuration settings you should have .NET **4.6** in both Scripting Runtime Version and Api Compatibility Level.

However in my installation I can only choose .Net 3.X Equivalent or .Net _4.X_ Equivalent.
Was my environment installed properly or something is missing regarding that specific  .NET 4.6 option I don't have?

I'm using Unity 2018.1.5f1 on Win10.

**Comment by xiaomaogy** [comment]
You should choose the .NET 4.X Equivalent. .NET 4.6 was from the Unity 2017.x version. I will update the documentation accordingly. Thanks for the notes.

**Comment by ivenzor** [comment]
Many thanks for your reply.
