### ISSUE TITLE
Saving fails every 15k steps

### ISSUE THREAD

**Issue by AndreiSalamon** [Unity-Technologies/ml-agents#912]
Having a weird issue during training. I set the max steps to 500k but at around 15k-20k steps (last status was 14k) the training just stops. No exception in either Unity OR the console. It just ends, and there is no bytes file saved.
This was after I continued the training for the third time. First time it reached 15k and stopped, second time almost 35k and stopped, and third time 50k and stopped.

I get the feeling that it may be failing during the status update. I've seen the Unity Editor freeze and become unresonsive when the console was supposed to write a status update and would only continue if I pressed Ctrl+C. Note that it would CONTINUE not end when I pressed Ctrl+C.

**Comment by AndreiSalamon** [comment]
I'm gonna go ahead and answer my own question again XD
Turns out the issue was the visual observations. I had one camera at a resolution of 300x300 for my visual observations and it was causing the RAM requirements to go higher and higher and eventually (at step 20k) python would throw an "invisible" out-of-memory error. Without the camera the ram usage is steady at around 4GB and it successfully passed the 20k mark in the training process.

Is there something I am missing about the visual observations? Is there a max recommended resolution that should be set? Or is there a minimum number of frames one should wait after each action to ensure the image processing passes successfully?

**Comment by awjuliani** [comment]
Hi @AndreiSalamon,

Thanks for pointing this out. There may be a memory leak that we will look into. As for frame size and frequency, people doing Reinforcement Learning typically use between 64x64 and 128x128. The PPO model we provide with `learn.py` is optimized for 84x84, actually. Depending on the task, it may not be necessary to use such a large image, since you only need to feed the neural network the smallest necessary image to discern the relevant details from the scene.

**Comment by AndreiSalamon** [comment]
@awjuliani I retested overnight with a lower resolution of 100x100 and it seems to do the trick. There were no more memory issues with the RAM usage being fairly constant at around 5GB. So yes, it is most likely a memory leak at higher resolutions.

**Comment by awjuliani** [comment]
Hi @AndreiSalamon,

Thank you for doing additional testing. We released v0.4.0a a couple weeks ago, which addresses a memory leak issue with using visual observations, and may address your problem as well. https://github.com/Unity-Technologies/ml-agents/releases/tag/0.4.0a
