### ISSUE TITLE
Storage of dataset passed to NN

### ISSUE THREAD

**Issue by juancarlosgdm** [Unity-Technologies/ml-agents#914]
The dataset generated by Unity and passed to the neural network is saved anywhere in the project? Or at least, is it possible to check it? If not, could you give me some clues for find the data and implement a way to get this information? Thanks!

**Comment by xiaomaogy** [comment]
The dataset is not saved anywhere in the project. You could add some custom code to save it yourself, like in the Batcher.cs's SendBatchedMessageHelper() function, log the information that gets send out to the python side.

**Comment by juancarlosgdm** [comment]
Perfect, your answer is more than enough. Thank you so much!
