### ISSUE TITLE
Camera as a state

### ISSUE THREAD

**Issue by darnox** [Unity-Technologies/ml-agents#92]
Can I use camera output to define an agent state based on it?

**Comment by awjuliani** [comment]
Hi @darnox,

You can definitely use cameras as observations for your agents.

Simply add an observation to the agent within the Editor Inspector: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Agents-Editor-Interface.md#agent 

And then set the Camera Resolution within that Agent's linked Brain: 
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Agents-Editor-Interface.md#brain

**Comment by darnox** [comment]
Hi @awjuliani,

Thanks for quick response. I've already set up my academy like you suggested and now I'm training my agents. Just wanted to know if this is simple enough or I have to add some more states to get my agent to learn from the camera. Do you think I should provide my agent with additional states that represent e.g. it position or velocity?

**Comment by awjuliani** [comment]
The PPO model should be able to learn directly from the camera if you followed those two steps. Adding additional state information, as long as it is relevant to the problem, will likely help speed up learning as well. What kind of task are you trying to teach your agent to complete?

**Comment by darnox** [comment]
I prepared a simple game in which a ball (agent) have to get to the opposite side of a map where is located trigger - an area that ends the game with a win. To make it more difficult there are placed some boxes sliding up from the ground over time, so they are blocking the ball against rolling straight. This game has no specific purpose, I created it only to learn how to use Unity ML before starting work on something more advanced.

**Comment by bitBrainResearch** [comment]
I'd like to see more information about setting up cameras.  I get an error with two cameras.  One works but I currently have the resolution set to 32 x 32.  I kept getting errors so I just followed the settings of one of the examples.  I'm not sure if it's made much difference or not.  I might have to try a camera only approach at some point just to see what happens!

**Comment by awjuliani** [comment]
Hi @bitBrainResearch,

There was an issue with sending states/observations that were too large in the initial release. We have fixed this in the `development` branch, and it will be fixed in the master branch, once it is merged in as well for the next release.
