### ISSUE TITLE
Brain automatically gets disconnected on Play

### ISSUE THREAD

**Issue by metamorphling** [Unity-Technologies/ml-agents#920]
There is a bug which disconnects graph model if brain is instantiated from prefab.

Story:
Trained brain in a separate scene, wanted to bring it back into my main project and noticed how on Play model switches to not set position and "Please provide a tensorflow graph as a bytes file" is shown.

Needed:
1) Prefab containing at least academy and brain.
2) Use any trained model at hand.
3) Unity 2018.1.0b11(not strictly I think)

Steps to reproduce(minimal example):
1) Create empty game object to hold academy derived script and a child game object to hold brain script.
2) Make parent game object into prefab
3) Delete them from scene
4) Instantiate prefab back into scene
5) Put trained model into a brain(brain parameters should match with that of a model)
6) Press Play

Resulting behaviour:
- No errors are thrown, brain graph model silently disappears from brain
- It is possible to stop, add model once again and press Play, model will disappear again

Expected behaviour:
- Model does not disappear without saying a thing(at least throw an error to understand what is wrong)

Found fix:
(1-4 as in reproduce guide)
4) Instantiate prefab back into scene
5) Switch Brain Type to External
6) Switch Brain Type back to Internal
5) Put trained model into a brain(brain parameters should match with that of a model)
6) Press Play

Resulting behaviour:
- Trained model stays in place

This is not a party crusher, but is just annoying to switch brain types back and forth just to make it work.

**Comment by xiaomaogy** [comment]
@metamorphling Why do you want to make the academy as a prefab?

**Comment by metamorphling** [comment]
I have my whole AI playground as a prefab, so that I can toss it around from project to project easily.
Structure looks like this:
>ParentGO(prefabed)
>>Academy
>>>Brain
>>Agent

Is it considered to be a bad practice or a plain misuse? From what I see it works, just a small nasty detail where I have to switch brain types Internal -> External -> Internal for graph model to be usable.

**Comment by xiaomaogy** [comment]
This is something valid but maybe currently not so urgent to be solved. We are actually working on changing the way brain gets stored, which is in this PR. https://github.com/Unity-Technologies/ml-agents/pull/903. Potentially this might solve this bug.

**Comment by jo3w4rd** [comment]
Does this work for you? https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design-Agents.md#instantiating-an-agent-at-runtime

**Comment by awjuliani** [comment]
Hi @metamorphling We will be changing the way Brains work in an upcoming release to resolve this issue. Thanks for bringing it to our attention.
