### ISSUE TITLE
Confused about continuous action vector

### ISSUE THREAD

**Issue by aurelien78** [Unity-Technologies/ml-agents#922]
Hi,

I'm using continuous action vector and when debuging received values I get those trace : 

DEBUG = 2,029609
DEBUG = -2,836936

I'm confused since I though coutinuous action values shall be in (-1;1)

Thanks

**Comment by icaro56** [comment]
You can clamp the value.

`Mathf.Clamp(vectorAction[0], -1f, 1f);`

See 3dBallExample: https://github.com/Unity-Technologies/ml-agents/blob/master/unity-environment/Assets/ML-Agents/Examples/3DBall/Scripts/Ball3DAgent.cs

**Comment by MarcoMeter** [comment]
On the python side, the outputs are clamped in the range -3 and 3. After that step, the value is divided by 3 to ultimately lie in the range -1 to 1.

Are you using ML-Agents v0.4?

**Comment by aurelien78** [comment]
Hi, thanks.

I'm using ML-Agents v0.3.0

I see some logs like DEBUG = -5,642792 or DEBUG = 4,168881 so not clamped in python.
It looks strange to me than network output is not "normalized" to [-1;1].

Anyway, I'll clamp it on C# side.

Thanks

**Comment by awjuliani** [comment]
Hi @aurelien78,

As of v0.4, the values should be clamped. Glad you were able to get them working on your end though.
