### ISSUE TITLE
Turn base game

### ISSUE THREAD

**Issue by GarySVR** [Unity-Technologies/ml-agents#938]
Currently looking into AI options for a turn base game, would it be possible to use Unity's ML for a turn base game like chess?

**Comment by GarySVR** [comment]
Hi @awjuliani ,
Thank you for your reply. 
I just looked through that documentation and just have a question about actions. As the game I'm working on is similar to chess, the amount of moves a piece can make can change as other pieces get in the way.
Are there any examples that allow a agent to make a action from a array that can change in size?

**Comment by scotthovestadt** [comment]
@GarySVR You'll have to always allow the agent to make the maximum number of actions and just ignore actions that touch pieces that cannot be moved. The observation space will work the same way: you'll still send observations every frame for pieces that are inactive, it'll just be a specific value that indicates the piece is inactive.

**Comment by GarySVR** [comment]
Hi @scotthovestadt,
Thanks for your reply, that makes sense :)
Do you know if there's any further documentation in regards to having the agents make a decision?

**Comment by awjuliani** [comment]
Hi @GarySVR,

As mentioned above, the current solution would be to provide all possible actions, and simply not count actions which are invalid. We are working on a method to explicitly provide a mask of invalid actions that the algorithm can ignore, but this likely won't come for another few weeks.

**Comment by awjuliani** [comment]
Hi All,

I am closing this thread due to inactivity, but feel free to re-open it if you desire.
