### ISSUE TITLE
Error training agents in V 0.3

### ISSUE THREAD

**Issue by nrawitscher954** [Unity-Technologies/ml-agents#941]
Hi,

I have successfully installed al ml-agents dependencies and I am using the latest Unity version. When I try to train the 3DBall example I get the following exception from the output log:

UnityAgentsException: The Communicator was unable to connect. Please make sure the External process is ready to accept communication with Unity.
  at MLAgents.Batcher.SendAcademyParameters (MLAgents.CommunicatorObjects.UnityRLInitializationOutput academyParameters) [0x00031] in C:\Users\nicol\ml-agents-master\unity-environment\Assets\ML-Agents\Scripts\Batcher.cs:83 
  at MLAgents.Academy.InitializeEnvironment () [0x001f2] in C:\Users\nicol\ml-agents-master\unity-environment\Assets\ML-Agents\Scripts\Academy.cs:319 
  at MLAgents.Academy.Awake () [0x00002] in C:\Users\nicol\ml-agents-master\unity-environment\Assets\ML-Agents\Scripts\Academy.cs:227 
 
(Filename: C:/Users/nicol/ml-agents-master/unity-environment/Assets/ML-Agents/Scripts/Batcher.cs Line: 83)

In addition I also get:

Fallback handler could not load library C:/Users/nicol/ml-agents-master/python/python_Data/Mono/libcoreclr.so
Fallback handler could not load library C:/Users/nicol/ml-agents-master/python/python_Data/Mono/libcoreclr.so.dll
Fallback handler could not load library C:/Users/nicol/ml-agents-master/python/python_Data/Mono/libcoreclr.so
Fallback handler could not load library C:/Users/nicol/ml-agents-master/python/python_Data/Mono/libdl.so
Fallback handler could not load library C:/Users/nicol/ml-agents-master/python/python_Data/Mono/libdl.so.dll
Fallback handler could not load library C:/Users/nicol/ml-agents-master/python/python_Data/Mono/libdl.so
Fallback handler could not load library C:/Users/nicol/ml-agents-master/python/python_Data/Mono/libSystem.dylib
Fallback handler could not load library C:/Users/nicol/ml-agents-master/python/python_Data/Mono/libSystem.dylib.dll
Fallback handler could not load library C:/Users/nicol/ml-agents-master/python/python_Data/Mono/libSystem.dylib
Fallback handler could not load library C:/Users/nicol/ml-agents-master/python/python_Data/Mono/libcoreclr.so
Fallback handler could not load library C:/Users/nicol/ml-agents-master/python/python_Data/Mono/libcoreclr.so.dll
Fallback handler could not load library C:/Users/nicol/ml-agents-master/python/python_Data/Mono/libcoreclr.so
Fallback handler could not load library C:/Users/nicol/ml-agents-master/python/python_Data/Mono/libdl.so
Fallback handler could not load library C:/Users/nicol/ml-agents-master/python/python_Data/Mono/libdl.so.dll
Fallback handler could not load library C:/Users/nicol/ml-agents-master/python/python_Data/Mono/libdl.so
Fallback handler could not load library C:/Users/nicol/ml-agents-master/python/python_Data/Mono/libSystem.dylib
Fallback handler could not load library C:/Users/nicol/ml-agents-master/python/python_Data/Mono/libSystem.dylib.dll
Fallback handler could not load library C:/Users/nicol/ml-agents-master/python/python_Data/Mono/libSystem.dylib

I also set the brain to external.

Any help will be great!

Thank you,

Nicolas

**Comment by awjuliani** [comment]
Hi @nrawitscher954,

Did you first launch the `learn.py` script from the command line before starting the Editor play session?

**Comment by nrawitscher954** [comment]
Hi @awjuliani 

thank you for your reply, I did fix the problem, I cloned the ml-agents repo again and everything worked fine!

**Comment by awjuliani** [comment]
Great to hear you were able to fix the issue.
