### ISSUE TITLE
2D platformer agents keep killing themselves

### ISSUE THREAD

**Issue by jpax1996** [Unity-Technologies/ml-agents#942]
Hello,
So i'm trying to train my AI to solve a 2d platforming level. For the AI to complete the level he will have to reach the flag on the right end side of the level. 
When i launch the training it takes my AI a few seconds to understand that they have to move right to get a higher reward, but when they learn that, they will complete the level almost instantly. But as the video shows only a few of them will actually finish the level while the others will fall to their deaths. And quickly they will forget how to solve the level and will keep dying in the same place. 
All the agents in the level share the same brain and are reset once they either die, reach the goal or the maximum steps is reached (400 steps). 
I've tried changing the amount of rewards i give to the agents but nothing completely fixes the issue.

Is there a way to somehow end the training once an agent has reached the goal and keep his brain?

Here's a video showing my training process:
https://drive.google.com/open?id=1PWHWxsTUAIJPdz2u4zpgCqozKDO-zsVi

**Comment by traveltrousers** [comment]
What are your rewards?

**Comment by jpax1996** [comment]
![reward](https://user-images.githubusercontent.com/26434446/42102862-259dbc6a-7bbf-11e8-9a0d-6340ad2d484a.png)
these reward calculations are in the AgentAction function. I also give a reward of 1 if he reaches the goal and -1 if he falls on the spike.

**Comment by jpax1996** [comment]
Thank you for the input @jo3w4rd  that's actually really helpful, i'll make those changes and see the differences.

**Comment by awjuliani** [comment]
Hi @jpax1996,

One additional possible recommendation is to increase the `beta` hyperparameter in the `trainer_config.yaml` file. It looks like all of your agents are quickly converging to a single behavior. Increasing this will encourage them to continue to act more randomly toward the beginning of training, making it more likely that they will not get stuck in a local optima.

**Comment by awjuliani** [comment]
Hi All,

I am closing this thread due to inactivity, but feel free to re-open it if you desire.
