### ISSUE TITLE
Curriculum feature request

### ISSUE THREAD

**Issue by traveltrousers** [Unity-Technologies/ml-agents#943]
Is it possible to reconfigure curriculum training to increase (or decrease) the parameters by a set amount each time the threshold is reached?  I have a agent that rapidly hits the highest reward but would like to make it much more robust by adding increasing noise to the inputs and linearly adjusting variables. 

If the walljump example was able to change it's height parameters by 0.1 each time it would presumably train much quicker, but to do that means writing : 

"big_wall_min_height" : [0.0, 0.1, 0.2, 0.3,  0.4, 0.5, 0.6.... etc all the way to,,,, 7.9, 8.0],

**Comment by awjuliani** [comment]
Hi @traveltrousers Thanks for making this issue. We are actually in the process of reworking the curriculum learning feature, and the ability to easily define changes like this is something we are very much considering.

@dericp (For your visibility)

**Comment by traveltrousers** [comment]
Thanks.....

Just as an aside, if anyone else wants to create a huge JSON file for training just make it as a spreadsheet and export a CSV which makes it easy to make and copy all the parameters you might need ...

although if I had realised that I might not have made the request :)
