### ISSUE TITLE
Backwards Compatibility Compiler Error with Unity 2017.1 (Which the documentation states is a supported version)

### ISSUE THREAD

**Issue by sterling000** [Unity-Technologies/ml-agents#948]
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md

The very 4th line of the installation documentation says Install Unity 2017.1 or later, but the current version contains references to ... https://docs.unity3d.com/2017.2/Documentation/ScriptReference/PlayModeStateChange.html released in 2017.2

Either the documentation needs to be updated that ml-agents 0.4 requires 2017.2 or later, or a backwards compatible version should be added.

**Comment by awjuliani** [comment]
Hi @sterling000,

Thanks for pointing this out, and for already making a PR: https://github.com/Unity-Technologies/ml-agents/pull/949.
