### ISSUE TITLE
Training Agent only based on Camera output?

### ISSUE THREAD

**Issue by liuyihunter** [Unity-Technologies/ml-agents#95]
The question is even i have referenced "Main camera" for observations in "Ball3DAgent.cs".  PPO seems still need "CollectState()" to make it works. My understanding is using Camera Output, which is an image, to replace the actual hard coding state which base on value(position,Rotation,etc). am i wrong? i'm quite confused about the purpose to setup Camera, is it only for accelerate the training process?

**Comment by SPINACHCEO** [comment]
Hi,
If you don't want to output any state, you can simply return an empty list in `CollectState()`.

**Comment by liuyihunter** [comment]
Hi  SPINACHCEO ,

Thank you for your answer. i will try it and see if it's works.

**Comment by awjuliani** [comment]
Hi @liuyihunter,

In most cases, if it is possible to describe the problem using states, this will be more informative to the neural network. In cases where the state is too complex, an image may be easier to convey the required information for the task. However, it takes more time for a network to learn to successfully extract the required information from an image, so the training process may take longer, or require more hyperparameter tuning.

**Comment by liuyihunter** [comment]
Hi @awjuliani ，

Your answer is helpful, cheers!!!
