### ISSUE TITLE
Training from simple to complex turn based game

### ISSUE THREAD

**Issue by phatal** [Unity-Technologies/ml-agents#950]
I wanna to make simple clone of soccer stars game with where team will be controled by ML agents (just for learning myself). For what would be easier to explain I will attach screenshot:

![image](https://user-images.githubusercontent.com/14150045/42123779-e4a36a02-7c81-11e8-993f-97746883d890.png)

1. 2 teams. 5 units (footballers) at each 1 ball 2 goals. units in team do not divide into a goalkeeper and usual player (all the same)

2. Turn based game. Players make moves one by one.

3. During turn player choose which unit will kick, and then drag him to set him power and direction in 2d space (dragging is just anim and not neccesary for ML agent players of course, therefore just set power and direction) and then the given force is applied to the unit.

4. Unit can collide with other units, ball, walls, goal.

5. Turn is considered complete when all moving units stop or when ball hits the goal. if at the end of the turn any unit is inside goal (except ball of course), then it will be moved to any free position at some distance from the goal. But space inside the goal can be used like usual walls when ball is kicking.

6. Then the turn goes to another player.

7. Win team which will score first 3 goals (for example 3. can the number be different).

Summarize this game such a mix of footbal and airhockey with turn based gameplay. 

When I was thinking how to solve this problem, I first of all thought that it would be logical to train agent from simple to complex and decide that first task will be to learn player score the goal by collecting dist from player to main parts of env like ball, walls, goal (top and bottom point to know size of goal) and appliyng power and direction to unit (changing ```localEulerAngles``` and,```addforce``` to ```RigidBody``` along red axis). I spent about 2-3 days triyng to realize that result wasn't satysfying. Then I decide to make a task more simple and train agent just to kick a ball. So...it was like that I coped with this task (default ppo), but then I become stuck with problem how to use my already trained model to solve next task about scoring the goal, and even more how to use later that model with task when at field will be all 10 players (5 each team). I see this so that the good trained agent will be analyze environiment state and decide which unit will be used to hit and which force and direction will be applied to them, and decision will be based on various factors, not only just positions of ball, enemies etc, but also on such as possibility to score a goal with one hit, kick the ball or just move unit to the goal to defence it (if it's not possible to score a goal cuz enemies unit standing  not allowing to do it right now) etc. And at that moment I realized that I need help. Of course I'm not asking you to explain me solution in every small details, but any info will be useful for me. 
Thank you in advance and I apologize for the level of my English and using googltranslate sometimes for translating text )))

**Comment by phatal** [comment]
Ok...if know that no one wanna read much text or does not know the exact answer I will ask simpler: how to organize from simple to comples training process (I mean type of training and combining their results) I need to train my agents to do the following things:
1) Kick the ball
2) Score the goal (including kick  with ricochet off the wall)
3) Decide which one (within one team) will kick depending  on the situation on the field.

**Comment by scotthovestadt** [comment]
@phatal Break it down into much smaller pieces. I would start with 1 agent on a small field trying to knock the ball into the goal and go from there.

**Comment by phatal** [comment]
@scotthovestadt  yep, I write about that already in the last lines in my message. But how I can use then this  trained model for further training. Even my players will know how to kick ball and even they will know  how to score the goal but next step will be to play 5 v 5 where player need choose one of 5 units to kick depending on it's own units position and enemy units position (and at some situation for example more usefull will be not kickin the ball but apply force to kick enemy unity  to clear space before kicking to the goal at the next turn). 

But ok I will try to move at that direction.
thx. for your answer.

**Comment by mmattar** [comment]
Thanks for the feedback @scotthovestadt. @phatal - I'd like to also point you to the [Open AI Scholars page](https://blog.openai.com/openai-scholars-class-2018/) as the first scholar also experimented with a soccer simulation.

**Comment by phatal** [comment]
@mmattar thanks!
