### ISSUE TITLE
Changing goal location with currivulum learning

### ISSUE THREAD

**Issue by jpax1996** [Unity-Technologies/ml-agents#951]
Hello,
I'm trying to change my goal location after the player reaches a certain reward but unfortunatly it is not working.
https://drive.google.com/file/d/1vFoRb9ppes1PXFN02l3FCgVdrOXqGlHp/view?usp=sharing

In my AcademyReset(), i change the goals location once the currCheckPointValue changes
![currlearning](https://user-images.githubusercontent.com/26434446/42163026-dcc22670-7df8-11e8-88b5-8c247686a04e.png)

I'm sure i'm doing something wrong, but since it's my first time using curriculum learning, i'm not sure what.
here's my json file:
![currlearning](https://user-images.githubusercontent.com/26434446/42163100-1eb0f728-7df9-11e8-8fad-f00f99b729a1.png)

**Comment by jpax1996** [comment]
So i managed to make the goal location change depending on how much reward the agents are receiving.
But i noticed that for some reason the AddReward() that the agent receives when he collides with the goal or with he spikes does not affect the mean reward.
If i let the training run with only rewards from colliding with either the goal or the spikes, the agents will learn to reach the goal and avoid the spikes (which means that the rewards are affecting the agents decisions), but it will not affect the mean rewards for some reason (the mean rewards will stay in 0 ).

here's a picture of the rewards when the agent collides with the goal or spikes
![rewards](https://user-images.githubusercontent.com/26434446/42213149-ed9363e4-7eaf-11e8-9c62-2f478d2acbad.png)

**Comment by jpax1996** [comment]
Ok i managed to solve also my last issue and the problem was that because i was adding a reward and setting the agent to done in the same step, the agent was not able to send it and affect the overall mean.

**Comment by mmattar** [comment]
Hi @jpax1996 - just to clarify, were you able to solve your issues? Or is there something that still is not working?

**Comment by mmattar** [comment]
Closing this issue for now, but please re-open if you continue facing issues.
