### ISSUE TITLE
MagicLeap Lumin OS Support

### ISSUE THREAD

**Issue by Ancient23** [Unity-Technologies/ml-agents#961]
Unity's Machine Learning internal tensorflow brains wont work on Magic Leap's platform until someone compiles the TensorflowSharp plugin for Lumin. 

To reproduce, download the Magic Leap SDK and Unity Technical preview (2018.1-0f2-MLTP6) and open the 3DBall sample. Load the TensorflowSharp.UnityPackage and switch platform to Lumin. 

Notice setting an internal brain type yields an error in the inspector that reads: "you need to install the tensorflowsharp plugin in order to us an internal brain"

**Comment by xiaomaogy** [comment]
Hi @Ancient23, right now we don't have any plans to support Magic Leap's platform. You are welcome to contribute to this if you are interested.

**Comment by eshvk** [comment]
We now use an internal inference engine which should support MagicLeap Lumin OS. Please check it out.
