### ISSUE TITLE
Citation of the project.

### ISSUE THREAD

**Issue by gaoyuankidult** [Unity-Technologies/ml-agents#962]
Hi,

I am using ML-agent for my research project.  Is there any paper I can cite to introduce ML-agent to others?

Best,

**Comment by ivenzor** [comment]
I would like to cite this project as well. Maybe an arxiv paper explaining ml-agents so others could cite you easily?

**Comment by harperj** [comment]
You can find a link to cite a preprint of our paper in the README now:
https://github.com/Unity-Technologies/ml-agents#citation
