### ISSUE TITLE
Nothing happens after docker run

### ISSUE THREAD

**Issue by Dubn** [Unity-Technologies/ml-agents#963]
Hi, can anyone explain why nothing happening?
` docker run --mount type=bind,source="$(pwd)"/unity-volume,target=/unity-volume ball.10:la
test --docker-target-name=unity-volume --train --run-id=2`
![image](https://user-images.githubusercontent.com/21372143/42510882-916d105a-8450-11e8-8e0d-7d9d10ba8aa3.png)
in the docker

**Comment by xiaozhuzhuzhu** [comment]
Me too.In addition, my 3Dball.exe is finished  to train when it only trained a ball.

**Comment by eshvk** [comment]
HI @Dubn, are you able to get docker setup and run _other_ docker containers on your windows machine without any problems?

**Comment by xiaozhuzhuzhu** [comment]
My two windows mashines can't  succeed if I use version v0.4，but version v0.3 both OK and MacOs in v0.4 is ok.

**Comment by eshvk** [comment]
@xiaozhuzhuzhu So in both scenarios, when you use v0.4 with Docker containers in windows, you are having problems, correct? Have you been able to run v0.4 without Docker on your windows machines?

**Comment by xiaozhuzhuzhu** [comment]
Hi
I have solved this problem. I updated tensorflow and then updated the docopt module in tensorflow. Then v0.4 can run normally.
Note: I am using win10 system, using anaconda+tensorflow and the version of unity is 2018
Hope can help you！

**Comment by eshvk** [comment]
Excellent, thank you for sending this! I will close this issue now.
