### ISSUE TITLE
Looking for an explanation on reward and python API

### ISSUE THREAD

**Issue by Guidosalimbeni** [Unity-Technologies/ml-agents#966]
Hello,
such a great ML tool in Unity!

I am experimenting with the ML-agents and I wonder if you can tell me if it is possible to access the reward 'architecture' through the Python API. Maybe the question it does not make any sense, and I apologise in this case. But I wonder if ML-agents is set in a way that only works when the reward assignment is built in UNITY. I do need to use an external python program to set the rewards to the agent since UNITY can't provide what I need. For a moment I thought that the Python API could be a possible solution but it seems that its purpose is to send actions to the agent via an external Python program. Am I right? Can you suggest what you would do if you had the same problem of mine?

that would be really appreciated.

Guido

**Comment by eshvk** [comment]
Hi @Guidosalimbeni, I am not too sure what `reward 'architecture' `  means. Can you please explain?

**Comment by eshvk** [comment]
Ah understood. Unfortunately, we haven't set it up for you to do that as of now.  This is partly because the intent is that reward is computed and tied to the environment (which happens to be Unity).

**Comment by Guidosalimbeni** [comment]
Dear Eshvk,
any updates on this ?
regards
Guido

**Comment by eshvk** [comment]
Hi @Guidosalimbeni, this hasn't been prioritized yet. I will let you know once we ship this.

**Comment by eshvk** [comment]
We are going to close this issue for now, if and when it gets prioritized, this feature will be noted in our release notes.
