### ISSUE TITLE
Collect Data in the saved_play folder

### ISSUE THREAD

**Issue by taka-acn** [Unity-Technologies/ml-agents#97]
According to the "Making a new Learning Environment" page, 
"If you want to collect data on you play, you can check the box **Collect Data**. This way, the states and actions passing through the brain will be saved in the folder **saved_plays**"

https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Making-a-new-Unity-Environment.md

But I don't see the checkbox named "Collect Data" in the inspector tab of my Brain Game Object. This might be my user error -- I might be overlooking this checkbox somewhere else. But I need to figure out how to save the game data in the saved_play folder.

**Comment by vincentpierre** [comment]
Thank you, for spotting this. It is a mistake and I removed it from the documentation. It was an implementation of a feature we are working on. Collecting data from Player gameplay will be made possible in a future version but not through a `Collect Data` checkbox. If you are interested, you can have a look at the branch `dev-broadcast` that sends gameplay data via socket to python.

**Comment by taka-acn** [comment]
Thanks a lot for the quick update. Closing this issue.
