### ISSUE TITLE
Using ml-agents in a Nintendo Switch game

### ISSUE THREAD

**Issue by Kaihnn** [Unity-Technologies/ml-agents#970]
Hi,

I was planning to use ml-agents imitation learning, to implements an AI in my game project. I'd like to know if a Switch build would still be possible after that. I understood that using imitation learning require the use of an internal brain, thus of TensorFlowSharp, but as I'm new in the world of ml-agents, I'm not really sure of that.

Thanks in advance for your answers !

**Comment by eshvk** [comment]
Hi @Kaihnn, as of now, we don't technically support ML-Agents on Switch. I am not sure if TensorFlowSharp can be built on a Switch platform. I think this is something you'd have to investigate. Please do let us know if you do find out.
