### ISSUE TITLE
Possible bug in RayPerception -- sends 1 extra float for each angle

### ISSUE THREAD

**Issue by scotthovestadt** [Unity-Technologies/ml-agents#971]
For each angle passed to RayPerception, the following floats are sent to the network:
```
0-1 (distance)
0 or 1 (for each tag)
1 (always sent)
```
So, for example, if you have 1 angle and 2 tags (A and B), and the ray hits tag A, you send:
```
.5 (distance)
0 (tag B boolean)
1 (tag A boolean)
1 (always sent)
```
As you can see, the 1 never changes. In this case, what's the point of sending it? Please explain if possible.

**Comment by hashbangCoder** [comment]
I had a similar question in #973, there are 7 angles and vector of size 10 is returned for each angle for 3 tags in `PushBlock` example

**Comment by eshvk** [comment]
Hey folks, I will mark this as a bug for now. We will take a look at it and get back. Thanks!

**Comment by awjuliani** [comment]
Hi All. There actually isn't a bug here. In the case of push block there are 14 rays sent, and 70 total observations. That means 5 observations-per-ray. Three of those correspond to the three objects to be detected. One corresponds to whether nothing was detected, and the final one corresponds to how far away the detected object is.
