### ISSUE TITLE
PushBlock documentation might be outdated 

### ISSUE THREAD

**Issue by hashbangCoder** [Unity-Technologies/ml-agents#973]
The `PushBlock` environment [doc](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Examples.md#push-block) says the `Observation` vector is of size 15 and contains position and velocities. 

But the  [code](https://github.com/Unity-Technologies/ml-agents/blob/master/unity-environment/Assets/ML-Agents/Examples/PushBlock/Scripts/PushAgentBasic.cs#L77)  appears to be adding vectors of ray perception at different angles and object detections 

```
AddVectorObs(rayPer.Perceive(rayDistance, rayAngles, detectableObjects, 0f, 0f));
AddVectorObs(rayPer.Perceive(rayDistance, rayAngles, detectableObjects, 1.5f, 0f));
```

From the comments in `RayPerception` class, it directs rays at specified angles and  records detected objects (goal, wall and block in this case) and the distance to object?

I'm getting a 70 size vector in the `env_info` object.  Since there are 7 angles specified in `CollectObservations`, I'm thinking 10 size sub-vector for each angle?

**Comment by awjuliani** [comment]
Hi @hashbangCoder,

Thanks for pointing this out! I've made a fix to the documentation in a hotfix branch, which will be merged into master soon: https://github.com/Unity-Technologies/ml-agents/tree/hotfix-0.4b .
