### ISSUE TITLE
Installation documentation wording

### ISSUE THREAD

**Issue by tpark1102** [Unity-Technologies/ml-agents#975]
Hello, I have a small suggestion to make. I think it would make sense to change the wording of the "Install Python" section of ml-agents/docs/Installation.md. When I was installing ml-agents, I skipped over the guide mentioned in 

> "If you are a Windows user who is new to Python and TensorFlow, follow this guide to set up your Python environment."

 because I thought it would just simply be instructions on how to install python and tensorflow. I think changing the wording to make it clear that the guide has important instructions relevant to installing ml-agents correctly would make things a lot easier so that other people won't have the same trouble I did. Thank you! :)

**Comment by eshvk** [comment]
Hey @tpark1102, skimmed through the page. I think the page is intended to be a Python installation using  ML-Agents as an example. We'd happily accept a PR or consider a sentence that would accurately describe it.
