### ISSUE TITLE
ImportError: No module named 'PIL'

### ISSUE THREAD

**Issue by MihaelFeldman** [Unity-Technologies/ml-agents#98]
Windows 10 setup with Conda environment. When trying to run the first block of Jupyter code there was issue importing "Image":

ImportError                               Traceback (most recent call last)
<ipython-input-1-766163402304> in <module>()
      4 
      5 from ppo.history import *
----> 6 from ppo.models import *
      7 from ppo.trainer import Trainer
      8 from unityagents import *

C:\ML Agents\python\ppo\models.py in <module>()
      3 import tensorflow.contrib.layers as c_layers
      4 from tensorflow.python.tools import freeze_graph
----> 5 from unityagents import UnityEnvironmentException
      6 
      7 

C:\ML Agents\python\unityagents\__init__.py in <module>()
----> 1 from .environment import *
      2 from .brain import *
      3 from .exception import *

C:\ML Agents\python\unityagents\environment.py in <module>()
     12 from .exception import UnityEnvironmentException, UnityActionException
     13 
---> 14 from PIL import Image
     15 from sys import platform
     16 

ImportError: No module named 'PIL'

**Comment by vincentpierre** [comment]
Hi, there is a list of dependencies in [requirements.txt](https://github.com/Unity-Technologies/ml-agents/blob/master/python/requirements.txt). This includes Pillow, I think you will have to install Pillow either with conda or pip. I hope this helps.

**Comment by AbdulkadirGul** [comment]
Same problem :(

 I have anaconda virtual environment and MLAgents-v0.4b. I installed everything with "setup.py" but when i'm trying to run second cell in "Basics" notebook i got ImportError: No module named 'PIL'. I checked from "pip freeze" i can see pillow as "Pillow==5.4.1". I tried removing with pip and install with conda nothing changed.

**Comment by sagivo** [comment]
same problem here. pillow is installed

**Comment by AbdulkadirGul** [comment]
@sagivo i found a solution as down here:

1. Uninstall anaconda, follow the instuctions in the link: https://stackoverflow.com/a/48238444/7583332
2. Delete anaconda folders in ..\AppData and your user folder.
3. And install everything, follow document steps: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation-Windows.md

Then works like a charm..

**Comment by sagivo** [comment]
Yeah reinstall everything solved it for me. On leave thing I didn't notice is that I run it from Jupyter notebook with different python version. Updating it was the answer.
