### ISSUE TITLE
Ctrl-C not saving/exporting at end of training

### ISSUE THREAD

**Issue by NightSp4rk** [Unity-Technologies/ml-agents#980]
As the title says.
After some digging, I saw that KeyboardInterrupt exception was not being called, instead giving the following error:

> forrtl: error (200): program aborting due to control-C event
> Image              PC                Routine            Line        Source

> libifcoremd.dll    00007FFB5F4194C4  Unknown               Unknown  Unknown
> KERNELBASE.dll     00007FFB982DEC3F  Unknown               Unknown  Unknown
> KERNEL32.DLL       00007FFB9AE113D2  Unknown               Unknown  Unknown
> ntdll.dll          00007FFB9B0C54E4  Unknown               Unknown  Unknown

I have altered the trainer_controller.py to save and export every few thousand steps, as a way to bypass this issue. But I'm wondering if it's just me, and why am I facing this issue.
Thanks

**Comment by NightSp4rk** [comment]
I am indeed using the latest from master. I think this may be a different issue as the error I got is different from the one at that link, and since I am getting this when it should already have been fixed.

**Comment by KReguieg** [comment]
**HINT IF AFRAID OF LOOSING MODEL AFTER OURS OF TRAINING BY PRESSING CTRL-C**

We had the same issue, and thought our model is lost, but refering to [@Hengoo answer](https://github.com/Unity-Technologies/ml-agents/issues/532) you can load the model and continue training at a given point in time, and then exit the training in Unity by pressing the Play-Button, so your model get's saved. ;)

**Comment by SetoKaiba** [comment]
Model can't be saved even exit by pressing the play button. Any idea?

**Comment by SetoKaiba** [comment]
Set the max_steps in config yaml will not terminate the training.

**Comment by SetoKaiba** [comment]
> (ml-agents) F:\ml-agents>mlagents-learn config/trainer_config.yaml --run-id=aaa --train
> 
> 
>                         ▄▄▄▓▓▓▓
>                    ╓▓▓▓▓▓▓█▓▓▓▓▓
>               ,▄▄▄m▀▀▀'  ,▓▓▓▀▓▓▄                           ▓▓▓  ▓▓▌
>             ▄▓▓▓▀'      ▄▓▓▀  ▓▓▓      ▄▄     ▄▄ ,▄▄ ▄▄▄▄   ,▄▄ ▄▓▓▌▄ ▄▄▄    ,▄▄
>           ▄▓▓▓▀        ▄▓▓▀   ▐▓▓▌     ▓▓▌   ▐▓▓ ▐▓▓▓▀▀▀▓▓▌ ▓▓▓ ▀▓▓▌▀ ^▓▓▌  ╒▓▓▌
>         ▄▓▓▓▓▓▄▄▄▄▄▄▄▄▓▓▓      ▓▀      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌   ▐▓▓▄ ▓▓▌
>         ▀▓▓▓▓▀▀▀▀▀▀▀▀▀▀▓▓▄     ▓▓      ▓▓▌   ▐▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▌    ▐▓▓▐▓▓
>           ^█▓▓▓        ▀▓▓▄   ▐▓▓▌     ▓▓▓▓▄▓▓▓▓ ▐▓▓    ▓▓▓ ▓▓▓  ▓▓▓▄    ▓▓▓▓`
>             '▀▓▓▓▄      ^▓▓▓  ▓▓▓       └▀▀▀▀ ▀▀ ^▀▀    `▀▀ `▀▀   '▀▀    ▐▓▓▌
>                ▀▀▀▀▓▄▄▄   ▓▓▓▓▓▓,                                      ▓▓▓▓▀
>                    `▀█▓▓▓▓▓▓▓▓▓▌
>                         ¬`▀▀▀█▓
> 
> 
> INFO:mlagents.trainers:{'--curriculum': 'None',
>  '--docker-target-name': 'None',
>  '--env': 'None',
>  '--help': False,
>  '--keep-checkpoints': '5',
>  '--lesson': '0',
>  '--load': False,
>  '--no-graphics': False,
>  '--num-runs': '1',
>  '--run-id': 'aaa',
>  '--save-freq': '50000',
>  '--seed': '-1',
>  '--slow': False,
>  '--train': True,
>  '--worker-id': '0',
>  '<trainer-config-path>': 'config/trainer_config.yaml'}
> INFO:mlagents.envs:Start training by pressing the Play button in the Unity Editor.
> INFO:mlagents.envs:
> 'Ball3DAcademy' started successfully!
> Unity Academy name: Ball3DAcademy
>         Number of Brains: 1
>         Number of Training Brains : 1
>         Reset Parameters :
> 
> Unity brain name: 3DBallLearning
>         Number of Visual Observations (per agent): 0
>         Vector Observation space size (per agent): 8
>         Number of stacked Vector Observation: 1
>         Vector Action space type: continuous
>         Vector Action space size (per agent): [2]
>         Vector Action descriptions: ,
> 2018-12-20 11:31:33.400430: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
> INFO:mlagents.envs:Hyperparameters for the PPO Trainer of brain 3DBallLearning:
>         batch_size:     64
>         beta:   0.001
>         buffer_size:    12000
>         epsilon:        0.2
>         gamma:  0.995
>         hidden_units:   128
>         lambd:  0.99
>         learning_rate:  0.0003
>         max_steps:      5.0e4
>         normalize:      True
>         num_epoch:      3
>         num_layers:     2
>         time_horizon:   1000
>         sequence_length:        64
>         summary_freq:   1000
>         use_recurrent:  False
>         summary_path:   ./summaries/aaa-0_3DBallLearning
>         memory_size:    256
>         use_curiosity:  True
>         curiosity_strength:     0.01
>         curiosity_enc_size:     128
>         model_path:     ./models/aaa-0/3DBallLearning
> Process Process-1:
> Traceback (most recent call last):
>   File "D:\Users\Seto\Anaconda3\envs\ml-agents\lib\multiprocessing\process.py", line 258, in _bootstrap
>     self.run()
>   File "D:\Users\Seto\Anaconda3\envs\ml-agents\lib\multiprocessing\process.py", line 93, in run
>     self._target(*self._args, **self._kwargs)
>   File "f:\ml-agents\ml-agents\mlagents\trainers\learn.py", line 52, in run_training
>     tc.start_learning()
>   File "f:\ml-agents\ml-agents\mlagents\trainers\trainer_controller.py", line 344, in start_learning
>     value=take_action_value)
>   File "f:\ml-agents\ml-agents\mlagents\envs\environment.py", line 405, in step
>     "The episode is completed. Reset the environment with 'reset()'")
> mlagents.envs.exception.UnityActionException: The episode is completed. Reset the environment with 'reset()'

Here's the output by setting Academy Max steps to terminate the training.

**Comment by SetoKaiba** [comment]
All 3 cases is running on Windows and not saving the model. I followed the instruction below.
https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation-Windows.md

**Comment by SetoKaiba** [comment]
Can anyone help?

**Comment by SetoKaiba** [comment]
After a deeper digging, I found it stuck with the lines below in the environment.py.
I found it never began the training. Any idea of it?

```
            outputs = self.communicator.exchange(
                self._generate_reset_input(train_mode, config)
            )
```

**Comment by xiaomaogy** [comment]
This bug has been fixed with https://github.com/Unity-Technologies/ml-agents/pull/1558. The error message 
```
forrtl: error (200): program aborting due to control-C event
Image PC Routine Line Source
libifcoremd.dll 00007FFDAFF994C4 Unknown Unknown Unknown
KERNELBASE.dll 00007FFDEF127EDD Unknown Unknown Unknown
KERNEL32.DLL 00007FFDF2131FE4 Unknown Unknown Unknown
ntdll.dll 00007FFDF226EFC1 Unknown Unknown Unknown
```

still exist, which is related to this stackoverflow https://stackoverflow.com/questions/42653389/ctrl-c-causes-forrtl-error-200-rather-than-python-keyboardinterrupt-exception. Our fix get around this error by adding another ctrl-c event handler which saves the model before this error.
