### ISSUE TITLE
Which Tensorflow version ML-agents is using ?

### ISSUE THREAD

**Issue by aliBUT** [Unity-Technologies/ml-agents#981]
I was planning to use pre-trained models and for some reason they were not working. I just wanted to make sure that ml-agents is using tensorflow 1.7 or some other version ?

thanks

**Comment by icaro56** [comment]
I guess is 1.7.1

**Comment by eshvk** [comment]
Hi @aliBUT, I hope this answers your question and wraps up the issue?

**Comment by aliBUT** [comment]
@eshvk  yes it does. Thanks
