### ISSUE TITLE
UnicodeEncodeError complaining about characters when running learn.py

### ISSUE THREAD

**Issue by jjjuande** [Unity-Technologies/ml-agents#982]
When I run learn.py (ML-Agents0.4.0a) in Windows 10 I get the following error:

> Traceback (most recent call last):
  File "python/learn.py", line 28, in <module>
    ''')
  File "C:\Users\Juande\Anaconda3\envs\ml-agents\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 28-34: character maps to undefined

I suppose it has to do with this:

![image](https://user-images.githubusercontent.com/168978/42769078-7baa91f4-8921-11e8-8034-e5b79ba141ab.png)

I haven't touched/edited the file. It's as is when uncompressed from the zip https://github.com/Unity-Technologies/ml-agents/archive/0.4.0a.zip

I'm getting this error when running using Anaconda Prompt. Everything worked fine with 0.3.1a. In case is useful, this is the list of packages installed on the activate environment I use from ML-Agents:

absl-py                   0.2.2                     <pip>
astor                     0.7.1                     <pip>
attrs                     17.4.0                    <pip>
backcall                  0.1.0                     <pip>
bleach                    1.5.0                     <pip>
certifi                   2018.1.18                py35_0
colorama                  0.3.9                     <pip>
cycler                    0.10.0                    <pip>
decorator                 4.3.0                     <pip>
docopt                    0.6.2                     <pip>
entrypoints               0.2.3                     <pip>
enum34                    1.1.6                     <pip>
gast                      0.2.0                     <pip>
grpcio                    1.11.0                    <pip>
html5lib                  0.9999999                 <pip>
ipykernel                 4.8.2                     <pip>
ipython                   6.3.1                     <pip>
ipython-genutils          0.2.0                     <pip>
ipywidgets                7.2.1                     <pip>
jedi                      0.12.0                    <pip>
Jinja2                    2.10                      <pip>
jsonschema                2.6.0                     <pip>
jupyter                   1.0.0                     <pip>
jupyter-client            5.2.3                     <pip>
jupyter-console           5.2.0                     <pip>
jupyter-core              4.4.0                     <pip>
kiwisolver                1.0.1                     <pip>
Markdown                  2.6.11                    <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.2.2                     <pip>
mistune                   0.8.3                     <pip>
more-itertools            4.1.0                     <pip>
nbconvert                 5.3.1                     <pip>
nbformat                  4.4.0                     <pip>
notebook                  5.4.1                     <pip>
numpy                     1.14.2                    <pip>
pandocfilters             1.4.2                     <pip>
parso                     0.2.0                     <pip>
pickleshare               0.7.4                     <pip>
Pillow                    5.1.0                     <pip>
pip                       9.0.3                    py35_0
pluggy                    0.6.0                     <pip>
prompt-toolkit            1.0.15                    <pip>
protobuf                  3.5.2                     <pip>
py                        1.5.3                     <pip>
Pygments                  2.2.0                     <pip>
pyparsing                 2.2.0                     <pip>
pytest                    3.5.0                     <pip>
python                    3.5.5                h0c2934d_2
python-dateutil           2.7.2                     <pip>
pytz                      2018.4                    <pip>
pywinpty                  0.5.1                     <pip>
PyYAML                    3.12                      <pip>
pyzmq                     17.0.0                    <pip>
qtconsole                 4.3.1                     <pip>
Send2Trash                1.5.0                     <pip>
setuptools                39.0.1                   py35_0
simplegeneric             0.8.1                     <pip>
six                       1.11.0                    <pip>
tensorboard               1.7.0                     <pip>
tensorflow                1.7.1                     <pip>
tensorflow-tensorboard    0.4.0                     <pip>
termcolor                 1.1.0                     <pip>
terminado                 0.8.1                     <pip>
testpath                  0.3.1                     <pip>
tornado                   5.0.2                     <pip>
traitlets                 4.3.2                     <pip>
unityagents               0.4.0                     <pip>
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
wcwidth                   0.1.7                     <pip>
Werkzeug                  0.14.1                    <pip>
wheel                     0.31.0                   py35_0
widgetsnbextension        3.2.1                     <pip>
win-unicode-console       0.5                       <pip>
wincertstore              0.2              py35hfebbdb8_0

I could remove the problematic lines and continue working, but I wanted to ask if I'm missing something. Thanks.

**Comment by eshvk** [comment]
Hi @jjjuande I am guessing you are running this via Python 3?

**Comment by jjjuande** [comment]
Yes. The package I have installed is anaconda prompt is:
python 3.5.5 h0c2934d_2

**Comment by jjjuande** [comment]
I'm going to update to python 3.6 since that's the recommended version in the install docs for this new version. (Previously I had the 0.3.1a version)
I'll share the results.

**Comment by jjjuande** [comment]
Creating a new Conda Environment and doing again the packages installation process fixed the issue.

conda create -n ml-agents python=3.6
activate ml-agents
pip install tensorflow==1.7.1
cd route-to-ml-agents/python
pip install .             

![image](https://user-images.githubusercontent.com/168978/42962782-ad06ff6c-8b92-11e8-9b2f-14b6d931d500.png)

I thought doing the "pip install ." on the "python" folder (ml-agents-0.4.0a/python) was enough to upgrade from 3.1a. But it seems that's not as straightforward as I believed.

So issue closed! Thanks.
