### ISSUE TITLE
Getting Training to Start

### ISSUE THREAD

**Issue by jek343** [Unity-Technologies/ml-agents#983]
Hello!

I'm just trying to get the provided 3DBall environment to train. I'm using a Mac, so I created a conda environment called ml-agents and activated it. Then I try to run:

'python3 learn.py .../Downloads/ml-agents-master/python/3DBallBuild.app --run-id=3db1 --train'
 
However, I keep getting errors that modules have not been imported. First docopt, then numpy, then google. I was able to get docopt and numpy installed by running 'pip install docopt' and 'pip install numpy' respectively. However, 'pip install google' is unsuccessful. After some searching on the web, I tried to run 'pip install .' so that all the necessary modules would be imported, but I get this error:

Processing .../Downloads/ml-agents-master/python
Collecting tensorflow==1.7.1 (from unityagents==0.4.0)
  Could not find a version that satisfies the requirement tensorflow==1.7.1 (from unityagents==0.4.0) (from versions: )
No matching distribution found for tensorflow==1.7.1 (from unityagents==0.4.0)

But I know for sure that I've used tensorflow before in jupyter notebook! Regardless, when I try to run 'pip install tensorflow' I get the following error:

Collecting tensorflow
  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow

I really don't know what else to try here. I have the brain set to external, I built the environment and put it in the python folder, and I'm inside the python folder. If someone could help me figure out how to train this, that would be amazing. Thanks in advance.

**Comment by eshvk** [comment]
Hi @jek343 
I suspect that this is more of a problem with your python installation than ML-Agents. 
Can you please go into your conda environment, which I assume is still called `ML-Agents` and type `conda list`, that will let us know what version of TensorFlow is installed.

**Comment by jek343** [comment]
Thank you @eshvk ! The problem was with my installation. There were a few versions that were off (I didn't realize some newer versions would not work) and I had skipped over the part to install cuda.
