### ISSUE TITLE
Why not use directly TensorFlowSharp in Unity for training ?

### ISSUE THREAD

**Issue by ThierryBachmann** [Unity-Technologies/ml-agents#986]
Hello
Sorry, for this question of beginner. It could be so more comfortable to get training in Unity !
Thank

**Comment by mmattar** [comment]
Hi @ThierryBachmann - interesting observation. There are a couple of reasons for this. 1. Machine learning libraries in Python are typically better supported and used by a wider range of researchers. So by enabling data extraction from Unity through the communicator we can leverage a wider range of tools and simply the process of adding new algorithms by the open source community. 2. De-coupling the Unity simulation from the training process enables us to scale up to distributed training algorithms more easily, which will be helpful for larger and more complex games. 

That said, it doesn't preclude us from potentially adding training algorithms in the future that live fully within C# and Unity. We do recognize that in the short-term this complicates the set-up process. We are actively working to streamline on boarding and happy to hear and incorporate any feedback you may have.

**Comment by ThierryBachmann** [comment]
Hi mmattar. Thank for your response, I well understand the reasons you exposed, obviously, you are right. Yes, the idea would be to propose a more easy package but also, why not, to imagine an IA that adapts over time with the player, but quite futuristic ! 
The set-up process is well explained, thank for that. I have got an issue on my corporate desktop because of the firewall  not configurable : issue to RPC communication between Unity and Python process. I have fix by running Unity in administrator mode (right to write exception in FW, I think). Could be useful for other. Now, I'm able to debug (with Visual Studio) Python code or Unity C#, usefull to understand ;-)

**Comment by mmattar** [comment]
Hi @ThierryBachmann - thanks for your note. We hope to enable some of these scenarios - particularly the player adaptation. I've made a note regarding the gRPC permissions issue, but glad to hear things are working. I'm closing out the issue for now, but please re-open if you have any follow-ups or submit a new issue if you run into any additional problems.
