### ISSUE TITLE
How do I support multi-key input in the Player Brain -> Discrete Player Actions?

### ISSUE THREAD

**Issue by Sohojoe** [Unity-Technologies/ml-agents#987]
Goal: I wish to implement a brain that supports the following discrete actions with key combinations when using Player Brain

Element 0. Key ’None’. Action = NoOp
Element 1. Key ’Right Arrow’. Action = Move Right
Element 2. Key ’Left Arrow’. Action = Move Left
Element 3. Key ’space’. Action = Jump
Element 4. Key ’space’ + ’Right Arrow’. Action = Jump Right
Element 5. Key ’space’ + ’Left Arrow’. Action = Jump Left

I do not see how to have multiple keys within one element

**Comment by mmattar** [comment]
Thanks @NightSp4rk. Let us know if this addresses your issue @Sohojoe.

**Comment by Sohojoe** [comment]
@mmattar / @NightSp4rk  - what i need is for Element 4 to be triggered when right arrow AND space are press and Element 5 to be triggered on left arrow AND space

<img width="487" alt="image" src="https://user-images.githubusercontent.com/4400544/43300863-678dcd92-9116-11e8-8e56-8a7e531ee9b5.png">

**Comment by Sohojoe** [comment]
@xiaomaogy  - I tested with 0.5 and it solves it - thanks!
