### ISSUE TITLE
Updating visual observations in Jupyter notebook

### ISSUE THREAD

**Issue by adididi** [Unity-Technologies/ml-agents#989]
Hello,
I'm kind of new in the field and I think that my question is quite trivial.
I have 2 cameras in Unity and I want to save every frame (up to a certain number), say from the Jupyter notebook as png pictures.
When I plot the visual observations coming from the cameras it seems that I plot several times the same visual observation (I have a moving ball on a plan). I suppose that I'm not synchronized with the unity frames. What am I doing wrong, are there some kind of flag to check to know if a new visual observation has arrived ?

for nb_frames in range (300):
    info = env.step()
    brainInfo = info[env.brain_names[0]]
    observations = brainInfo.visual_observations    
    for observation in observations:
        if observation.shape[3] == 3:
            plt.imshow(observation[0,:,:,:])
            plt.show()

**Comment by adididi** [comment]
Hi @mmattar, thank you I think that it solved my problem !

**Comment by mmattar** [comment]
Great to hear @adididi - closing the issue, but feel free to reopen if you have any additional follow-ups.
