### ISSUE TITLE
How do you implement a Tensorflow deep learning network on Unity ml-agents with the Python API 

### ISSUE THREAD

**Issue by ImranRolo** [Unity-Technologies/ml-agents#990]
I understand that Unity ML-agents runs on a python API and Tensorflow but where exactly (which python script file) can you configure a Tensorflow deep reinforcement learning algorithm to train the agents? For example if someone wanted to train the unity agents in a game with a specific deep learning algorithm - how would one do that in python?

On the Unity ML tutorial, the games are trained with `learn.py` - but I don't see anywhere in the code where the Tensorflow network is training the agents. I can only see the hyperparameters in the trainer_config.yaml file but no network architecture.

**Comment by mmattar** [comment]
Hi @ImranRolo - the primary algorithm we provide for deep RL is PPO. This is implemented in the [PPO Trainer](https://github.com/Unity-Technologies/ml-agents/blob/master/python/unitytrainers/ppo/trainer.py) class. Anyone can add their own algorithms by implementing their own Trainer class (inheriting from [Trainer](https://github.com/Unity-Technologies/ml-agents/blob/master/python/unitytrainers/trainer.py)).

**Comment by mmattar** [comment]
Closing this issue for now, but please re-open if you continue facing issues.
