### ISSUE TITLE
Question : What is the purpose of SetTextObs(string textObservation) in Unity ML-Agents package and what are the various use cases of this function ?

### ISSUE THREAD

**Issue by shrirammoni** [Unity-Technologies/ml-agents#993]
I am currently working on a machine learning project in unity. I am using **ML-Agents** package. There is a function named **SetTextObs(string textObservation)**, which sets the observation as text. What is the purpose of this function and what are the various use cases of this function ?

**Comment by mmattar** [comment]
Hi @shrirammoni - this was a feature we added initially to support our imitation learning scenario where we need to send messages from Unity Editor to the learner in Python whenever the developer pauses the recording of demonstrations. It could also be used for custom messages, but we plan to enable the ability for users to define their own messages within ProtoBuf in the future, so I wouldn't recommend planning on using text observations/actions for custom messages (for the long-term at least).

**Comment by shrirammoni** [comment]
Hey, @mmattar thanks for the help 👍

**Comment by mmattar** [comment]
Of course - closing the issue, but feel free to reopen if you have any follow-ups or submit another issue for any other questions.
