### ISSUE TITLE
Input.GetKeyDown possible as an action input?

### ISSUE THREAD

**Issue by Guidosalimbeni** [Unity-Technologies/ml-agents#994]
Hi,
just wondering if it possible to train an agent using actions that work with Input.GetKeyDown. 
It seems that I can only work with actions that imply movement like. Is it possible to set the action that performs a switch between elements in the scene? If press 'a' means select element 1 and move element 1, if I press 's' select element 2 and move element 2? Is this possible? I cannot figure out how to implement this using the current action functionality in ml-agents, I usually use Input.GetKeyDown and set a bool to true or false in Unity3D when I work without ML-agents. Any help would be really appreciated.
Best regards
Guido

**Comment by mmattar** [comment]
Hi @Guidosalimbeni - just to clarify, are you referring to setting up the Player Teacher Brain during imitation learning?

**Comment by Guidosalimbeni** [comment]
Yes I do. Thank you for taking this help request in consideration. Looking forward to hearing from you.

**Comment by harperj** [comment]
Since there hasn't been any activity on this issue in many months and we don't currently have it on our roadmap I'm going to close it.  Please feel free to reopen if you're working on this or have more to add.
