### ISSUE TITLE
The Brain is None in the Prefabs

### ISSUE THREAD

**Issue by lyp741** [Unity-Technologies/ml-agents#998]
I want to create a prefab for the agent, but the "Brain" is None in the prefab. And also None if instantiate. Is it a bug?

**Comment by jo3w4rd** [comment]
You have to "give" a brain to the agent at runtime if you use a prefab or instantiation: https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design-Agents.md#instantiating-an-agent-at-runtime

**Comment by mmattar** [comment]
Thanks @jo3w4rd. Let us know if this resolves your issue @lyp741.
