### ISSUE TITLE
reset all the agents to original position via academy

### ISSUE THREAD

**Issue by Guidosalimbeni** [Unity-Technologies/ml-agents#999]
I am trying to reset all the agents to their initial position when only one of them reaches a goal target. 
I have tried for half a day to understand how to do it via academy but obviously, I missing something.
I cannot find a specific explanation in the manual and I wonder if you could help with steps I need to code.
My scene is very simple. 3 agents 1 brain ,  actions for moving the object, one single goal area. as soon as one agent reaches the goal I would like to start from the beginning having all the agents at the original position. At moment I managed to set one single agent at its original position.
Any help would be really appreciated. And if possible with example.
Thank you
Guido

**Comment by pakaponk** [comment]
I think the information, you are looking for, resides on this document. [The simulation and training process](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Design.md#the-simulation-and-training-process).

As mentioned in the document, You could reset agents' position by either override `AcademyReset()` or `AgentReset` then implementing the resetting code there. However, These methods will run when either the `Academy` has reached its maximum number of steps or all agents in the scene are ***done***. So you have to ensure that when one of your agent reachs the goal, All of your agents call `Done()`.

Hope that this help solve your problem 😃

**Comment by mmattar** [comment]
Thanks @pakaponk. Let us know if you have any additional follow-ups @Guidosalimbeni.

**Comment by mmattar** [comment]
Closing this issue for now, but please re-open if you continue facing issues.
